website/content/docs/secrets/pki/considerations.mdx

Also adds auditing section about suggested un-HMAC'd request/response
parameters.
---
Let me know if I missed anything, but I don't think the other docs pages mention single issuer as a restriction (so there should be no need to update them).

Update considerations for multiple issuers

---

api/secret.go
builtin/logical/ssh/util.go
command/base_flags.go
command/server/config.go
go.mod
go.sum

This fixes a few integer overflow bugs, using the new Safe variants of ParseUtil. One additional fix was detected in `command/server/config.go` by the GH Security Alerts, so I've opted to fix that as well. 
---
I'm inclined to think these aren't worthy of a changelog entry? There should be no behavior change. 
VAULT-3892

Fix integer overflows with new parseutil

---

builtin/logical/transit/path_import.go
sdk/helper/keysutil/lock_manager.go

This fixes a couple issues:
- Defers a policy unlock in keysutil that could cause single policy deadlocks when an import fails.
- Updates Transit import endpoint to accept different capitalizations of key type for convenience.

Fix a keysutil policy lock

---

builtin/logical/pki/storage_migrations.go
builtin/logical/pki/storage_migrations_test.go

If necessary, this will let us correlate migrated values afterwards.
---
@sgmiller and @stevendpclark I think we talked about this but never got around to doing it. I think it was supposed to be done around the same time as adding the (present) issuer to the certificate storage entry, but because that didn't happen (wasn't a fat format), this didn't happen either.
I opted to add it to the log, even though there's no (present) way of returning the log info to the user, rather than to the issuers config. Thoughts?

Store migrated issuer, key ID in migration log

---

changelog/15055.txt
vault/identity_store_groups_test.go
vault/identity_store_util.go

Currently when adding policies to identity groups, the list is not deduplicated resulting in multiple copies of the same policy in an identity group.

Remove duplicate policies when creating/updating identity groups

---

website/content/docs/auth/jwt/oidc_providers.mdx

This PR documents that only the `sub` and `email` claims can be used as the `user_claim` value for roles configured to use the [Google Workspace](https://www.vaultproject.io/docs/auth/jwt/oidc_providers#optional-google-specific-configuration) groups and user info feature. 
See #15330 for more details on this constraint.

auth/oidc: documents user claim constraint for optional google workspace config

---

website/content/api-docs/auth/jwt.mdx
website/content/docs/auth/jwt/index.mdx

This PR adds documentation for using JSON pointer in the `user_claim` parameter for JWT/OIDC auth.
Related PR: https://github.com/hashicorp/vault-plugin-auth-jwt/pull/204

auth/oidc: adds documentation for JSON pointer user claim

---

audit/format.go
changelog/15457.txt
sdk/logical/auth.go
vault/acl.go
vault/acl_test.go
vault/policy.go
vault/request_handling.go

This PR adds a policy results block to the audit log output. This block contains a list of the policy or policies that actually granted the permissions needed for the request. 
Example Audit Logs:
```
"policy_results": {
"allowed": true,
"granting_policies": [
{
"name": "admin",
"namespace_id": "root",
"type": "acl"
},
{
"name": "always-pass1",
"namespace_id": "root",
"type": "rgp"
},
{
"name": "always-pass-ns1",
"namespace_id": "root",
"type": "egp"
}
]
},
```
The policy_results block is also a more explicit way to detect a request failed due to being unauthorized:
```
"policy_results": {
"allowed": false
},
```

Add list of granting policies audit logs

---

builtin/logical/pki/backend.go
builtin/logical/pki/storage_migrations.go

- No point in writing any logs if no previous bundle exists
- Only log output and schedule a CRL rebuild is we actually migrated something
- Do not log on PKI storage version set/checks.
Logs when needing to migration an existing bundle
```
2022-05-16T17:19:12.085-0400 [INFO]  secrets.pki.pki_e3586de1: performing PKI migration to new keys/issuers layout
2022-05-16T17:19:12.086-0400 [INFO]  secrets.pki.pki_e3586de1: Migration generated the following ids and set them as defaults: issuer id=691b8102-1e26-ddc3-a891-5ac8145ce081 key id=7396a3a8-f72a-4eaf-e6fc-547f295a45d9
2022-05-16T17:19:12.086-0400 [INFO]  secrets.pki.pki_e3586de1: Scheduling PKI CRL rebuild.
```
There are no logs printed out if there isn't an existing bundle.
We output the following on non-active nodes when a migration has …

Log less around the current status of the PKI migration

---

builtin/logical/pki/cert_util.go
builtin/logical/pki/crl_util.go
builtin/logical/pki/path_config_crl.go
builtin/logical/pki/path_config_urls.go
changelog/15470.txt

Vault currently returns a `nil` response when the default CRL and URL configuration is being used. This doesn't really make sense, especially in the CRL case, as this default CRL config actually has 72h expiration (and isn't disabled). 
Instead, always return config structs for both of these two configs. This matches the behavior introduced in the multi-issuer changes  where `config/issuers` and `config/keys` always returns structs (even if empty of values).

Always return PKI configs for CRLs, URLs

---

website/content/api-docs/secret/ad.mdx

Documentation clarifying related to https://github.com/hashicorp/vault-plugin-secrets-ad/issues/84, where `upndomain` can cause confusion while configuring the AD secret engine when used with `binddn`.

docs: add note about upndomain for AD secret engine

---

website/content/docs/secrets/pki/considerations.mdx
website/content/docs/secrets/pki/index.mdx
website/content/docs/secrets/pki/quick-start-intermediate-ca.mdx
website/content/docs/secrets/pki/quick-start-root-ca.mdx
website/content/docs/secrets/pki/rotation-primitives.mdx
website/content/docs/secrets/pki/setup.mdx
website/data/docs-nav-data.json

This imports the rotation primitives with few changes (previously we called them ratchets) from the RFC, including the diagrams and external links.
I also updated the titles to be consistent with the identity secrets engine (used `:` as a separator in the title between parent doc title and child-doc title).
If people have comments, happy to edit the docs but I've looked at it so many times I'm not sure what to change any more :/

Add documentation on rotation primitives

---

api/sys_plugins.go
api/sys_plugins_test.go
changelog/15434.txt

Currently, adding a new type to the top-level keys of response data will break client code if it's not a plugin type that the client already knows about. This PR makes it only iterate over known plugin types instead to make it more resilient to any future changes.

api: make ListPlugins parse only known plugin types

---

ui/app/adapters/mfa-login-enforcement.js
ui/app/components/mfa-login-enforcement-form.js
ui/app/controllers/vault/cluster/access/mfa/enforcements/enforcement/index.js
ui/app/controllers/vault/cluster/access/mfa/enforcements/index.js
ui/app/models/mfa-login-enforcement.js
ui/app/routes/vault/cluster/access/mfa/enforcements/enforcement.js
ui/app/styles/core/helpers.scss
ui/app/templates/components/mfa-login-enforcement-form.hbs
ui/app/templates/components/mfa-method-list-item.hbs
ui/app/templates/vault/cluster/access/mfa/enforcements/enforcement/index.hbs
ui/app/templates/vault/cluster/access/mfa/enforcements/index.hbs
ui/app/templates/vault/cluster/access/mfa/methods/index.hbs
ui/lib/core/addon/components/linked-block.hbs
ui/lib/core/addon/components/linked-block.js
ui/tests/integration/components/mfa-method-list-item-test.js

Adds read views for MFA login enforcements with tabs to display associated targets and methods.

MFA Login Enforcement Read Views

---

changelog/15428.txt
command/format.go
command/login.go

Two issues have been fixed:
- The success message being erroneously reported during a two-phase MFA flow
- The MFA information being missing during a two-phase MFA flow unless -format=json was provided
Two-step MFA will now look something like this:
```
violethynes@violethynes-C02CW1WWMD6R Repositories % vault login -method userpass username=alice password=kQ3BlE+5M1libWJc
A login request was issued that is subject to MFA validation. Please make sure
to validate the login by sending another request to sys/mfa/validate endpoint.
WARNING! The VAULT_TOKEN environment variable is set! The value of this
variable will take precedence; if this is unwanted please unset VAULT_TOKEN or
update its value accordingly.
WARNING! The following warnings were returned from Vault:
* A login request was …
```

VAULT-5885: Fix erroneous success message in case of two-phase MFA, and provide MFA information in table format

---

changelog/15452.txt
command/operator_diagnose_test.go
command/server/config.go
command/server_test.go
http/plugin_test.go
sdk/helper/consts/consts.go
vault/core.go
vault/logical_system_integ_test.go

https://hashicorp.atlassian.net/browse/VAULT-6037
Making this change opt-in, by renaming the environment variable VAULT_DISABLE_FILE_PERMISSIONS_CHECK to VAULT_ENABLE_FILE_PERMISSIONS_CHECK and adjusting the logic

Vault-6037 making filesystem permissions check opt-in

---

website/content/api-docs/secret/pki.mdx
website/content/api-docs/secret/ssh.mdx
website/content/api-docs/secret/transit.mdx
website/content/api-docs/system/tools.mdx
website/content/docs/enterprise/fips/fips1402.mdx
website/content/docs/enterprise/fips/index.mdx
website/content/docs/enterprise/fips/sealwrap.mdx
website/content/docs/enterprise/sealwrap.mdx
website/content/docs/secrets/transit.mdx
website/data/docs-nav-data.json

This restructures the FIPS documentation a little, turning it into a proper section, and adds the FIPS 140-2 inside documentation. 
We add notes to various other documentation sections, stating which algorithms cannot compliantly be used with the FIPS edition; these still will work, but aren't certified/certifiable.

Start documentation for FIPS variants of Vault Enterprise

---

changelog/15469.txt
vault/request_handling.go
vault/request_handling_util.go

This PR is the OSS part of this [one](https://github.com/hashicorp/vault-enterprise/pull/2749).
It removes the logic for forwarding all login requests from a perfStandby node to the active node. Instead, it enables forwarding cached MFA auth response to the leader so that MFA validation works.

possibly forward cached MFA auth response to leader

---

website/content/docs/platform/k8s/helm/configuration.mdx
website/content/docs/platform/k8s/helm/enterprise.mdx
website/content/docs/platform/k8s/helm/examples/development.mdx
website/content/docs/platform/k8s/helm/examples/enterprise-dr-with-raft.mdx
website/content/docs/platform/k8s/helm/examples/enterprise-perf-with-raft.mdx
website/content/docs/platform/k8s/helm/examples/enterprise-with-raft.mdx
website/content/docs/platform/k8s/helm/examples/external.mdx
website/content/docs/platform/k8s/helm/examples/ha-with-consul.mdx
website/content/docs/platform/k8s/helm/examples/ha-with-raft.mdx
website/content/docs/platform/k8s/helm/examples/index.mdx
website/content/docs/platform/k8s/helm/examples/injector-tls.mdx
website/content/docs/platform/k8s/helm/examples/kubernetes-auth.mdx
website/content/docs/platform/k8s/helm/examples/standalone-audit.mdx
website/content/docs/platform/k8s/helm/examples/standalone-load-balanced-ui.mdx
website/content/docs/platform/k8s/helm/examples/standalone-tls.mdx
website/content/docs/platform/k8s/helm/index.mdx
website/content/docs/platform/k8s/helm/openshift.mdx
website/content/docs/platform/k8s/helm/run.mdx

Adds a note about vault-helm requiring Helm 3.6+. Users may run into errors during installation if using older versions:
```
Error: parse error at (vault/templates/_helpers.tpl:38): unclosed action
```

docs: add note about requiring 3.6+ helm

---

changelog/15474.txt
ui/app/templates/components/transit-form-create.hbs
ui/app/templates/components/transit-form-edit.hbs
ui/lib/core/addon/components/ttl-picker2.js
ui/tests/acceptance/transit-test.js
ui/tests/integration/components/ttl-picker2-test.js

Update the default transit auto-rotation from `1h` to `30d`, to represent a more reasonable default value for keys.

UI: Better default transit auto-rotation

---

builtin/logical/pki/fields.go

- The field could be used to be applied to keys/issuers being generated or to update the name on existing values.

Fix a generic PKI description for key_name and issuer_name fields

---

changelog/15417.txt
command/base.go
command/commands.go
command/format.go
command/list.go
command/main.go
command/operator_unseal_test.go
command/version_history_test.go

This adds the ability (via switch `-detailed`) to show the additional metadata returned by endpoints which use the `ListResponseWithInfo` format helper. We add support for both table and JSON formatted response printing. 
See the individual commit messages for examples of each. 
---
An unofficial survey of endpoints returns:
- PKI: `/issuers` and `/keys`, which are new to 1.11
- SSH: `/roles`, which has been around for a while. It returns the `key_type` field.
A few other uses:
```
vault/identity_store_entities.go:666:			resp := logical.ListResponseWithInfo(keys, entityInfo)
vault/identity_store_entities.go:717:	return logical.ListResponseWithInfo(keys, entityInfo), nil
vault/identity_store_groups.go:533:	return logical.ListResponseWithInfo(keys, groupInfo), nil …
```

Vault CLI: show detailed information with ListResponseWithInfo

---

changelog/15464.txt
ui/app/adapters/pki-ca-certificate.js
ui/app/components/config-pki-ca.js
ui/app/components/config-pki.js
ui/app/models/pki-ca-certificate.js
ui/app/styles/components/popup-menu.scss
ui/app/templates/components/config-pki-ca.hbs
ui/tests/integration/components/config-pki-ca-test.js

- copy changes from "Replace CA" to "Add" 
- disabling delete (for 1.11 all delete capabilities will only be available via CLI and API) 
<hr>

UI/vault 6212/multiple issuer pki changes

---

changelog/15493.txt
go.mod
go.sum
physical/raft/raft_autopilot.go
vault/ha.go
vault/logical_system_raft.go

Make sure that autopilot is disabled when we step down from active node state.  Forward autopilot state requests to the active node.  Avoid self-dialing due to stale advertisement from when we used to be active node.

Forward autopilot state reqs, avoid self-dialing

---

builtin/logical/pki/path_fetch_issuers.go
builtin/logical/pki/path_roles.go
builtin/logical/pki/storage.go

This covers two things:
* @cipherboy 's comments that we should probably say something if the floating reference referred to by a role does not exist. 
* @ivana-mcconnell comments during review that it would be nice if we warned when we were deleting a floating reference to an issuer that was used by a role.

Vault 6122 pki role issuer name validation

---

builtin/logical/cassandra/test-fixtures/cassandra.yaml
website/content/api-docs/secret/databases/hanadb.mdx
website/content/api-docs/secret/databases/index.mdx
website/content/api-docs/secret/databases/mssql.mdx
website/content/api-docs/secret/databases/mysql-maria.mdx
website/content/api-docs/secret/databases/oracle.mdx
website/content/api-docs/secret/databases/postgresql.mdx
website/content/api-docs/secret/databases/redshift.mdx
website/content/api-docs/secret/databases/snowflake.mdx
website/content/docs/secrets/databases/index.mdx

Change terminology from "symbol characters" to "special characters" as they may not all be symbols. Also fix several instances of the typo "for for".

Fix minor typos and change terminology slightly in database secrets engines docs

---

website/content/docs/enterprise/fips/fips1402.mdx

This clarifies a limitation of the FIPS based container images,
to note that due to OpenShift requirements, we need to suggest
ways of disabling mlock or allowing Vault to set mlock.

Update FIPS documentation to clarify mlock

---

builtin/logical/pki/path_intermediate.go
builtin/logical/pki/path_root.go
changelog/15509.txt

---
```
$ vault write pki/root/generate/exported common_name="not-empty" issuer_name=unknown-2 
WARNING! The following warnings were returned from Vault:
* This mount hasn't configured any authority access information fields;
this may make it harder for systems to find missing certificates in the
chain or to validate revocation status of certificates. Consider updating
/config/urls with this information.
```

Add warning on missing AIA info fields

---

builtin/logical/consul/backend_test.go
builtin/logical/consul/path_roles.go
builtin/logical/consul/path_token.go
builtin/logical/consul/path_token_test.go
changelog/15400.txt

With the Consul secrets engine improvements, several new parameters were added. Roles for example, but since Vault uses the term roles already, the parameter was named `consul_roles`. Similarly, the parameter for Consul namespaces was named `consul_namespace`. For example:
`$ vault write consul/roles/my-role consul_roles="role1"`
and
`$ vault write -namespace="ns1" consul/roles/my-role consul_namespace="ns2"`
This has created an inconsistent naming convention for the parameters. A counterexample to the above is policies, as both Consul and Vault use them, yet the parameter is simply named `policies` without the "consul_" prefix:
`$ vault write consul/roles/my-role policies="global-management"`
We could consider renaming the parameters to be consistent, and if so decide which parameters …

Consistent consul secrets parameter names

---

changelog/15519.txt
vault/raft.go

This ensures servers started on an environment where $VAULT_NAMESPACE is set do not use such a variable when making this kind of call, causing an error.
Notably, this file seems to be the only place where stripping the namespace makes sense (other API clients come from a CLI/api client call, where the namespace makes sense), which is why I did not make it a configuration item for ApiClient or similar. If it becomes a more general need, it makes sense to make the configuration change then, but it didn't make sense to me to add a new configuration item or method for what appears to be a snowflake.

VAULT-4306 Ensure /raft/bootstrap/challenge call ignores erroneous namespaces set

---

command/main.go

This part of the code currently relies on a hard-coded check that certain flags were provided. However, many users are probably accustomed to the double-hyphen style of flag, so let's accept both.

Set OutputCurlString and OutputPolicy on client whether single or double hyphen in flag

---

website/content/docs/concepts/integrated-storage/autopilot.mdx
website/content/docs/concepts/password-policies.mdx
website/content/docs/concepts/policies.mdx
website/content/docs/concepts/resource-quotas.mdx
website/content/docs/concepts/username-templating.mdx
website/content/docs/configuration/seal/gcpckms.mdx
website/content/docs/configuration/storage/index.mdx
website/content/docs/configuration/storage/raft.mdx
website/content/docs/enterprise/lease-count-quotas.mdx
website/content/docs/enterprise/replication.mdx
website/content/docs/platform/aws/lambda-extension.mdx
website/content/docs/platform/k8s/injector/index.mdx
website/content/docs/secrets/consul.mdx
website/content/docs/secrets/databases/index.mdx
website/content/docs/secrets/databases/mongodb.mdx
website/content/docs/secrets/kmip.mdx
website/content/docs/secrets/nomad.mdx
website/content/docs/secrets/pki/index.mdx
website/content/docs/secrets/terraform.mdx
website/content/docs/secrets/transform/tokenization.mdx

Per [Asana](https://app.asana.com/0/inbox/1200328878163177/1202303978180687/1202307649954451), a number of files have been updated to replace references to **Learn** with **Tutorial**. 
These files were not listed the original query list, and therefore, were missed: https://docs.google.com/spreadsheets/d/1dDR-jsL9iqQcd8WAQWsuEGGs2bXyks5Cw5ku5TfC-HA/edit#gid=1279078251

Vault documentation: updated all references from Learn to Tutorial

---

builtin/logical/pki/backend_test.go
builtin/logical/pki/path_root.go
changelog/15524.txt

- When signing a CA certificate we should include it along with the issuers CA chain in the response.

Return the signed ca in the ca_chain response field within sign-intermediate api call.

---

website/content/api-docs/secret/pki.mdx

---
This resolves #[13364](https://github.com/hashicorp/vault/issues/13364) with a documentation update. In particular, modifying the behavior of `sign-verbatim` at this point in time is not possible, so we attempt to clarify the documentation.
Resolves: #13364

Clarify KU/EKU parameters on sign-verbatim

---

website/content/api-docs/secret/pki.mdx

Fix typo in allowed_uri_sans_template doctype

---

changelog/15513.txt
ui/app/serializers/license.js
ui/app/templates/components/license-info.hbs
ui/mirage/handlers/base.js
ui/tests/integration/components/license-info-test.js

- Stored license was deprecated in 1.8 and from 1.11 all licenses will be
auto loaded.

Remove reference to stored license

---

builtin/logical/pki/path_fetch_issuers.go
builtin/logical/pki/path_fetch_keys.go
builtin/logical/pki/path_manage_keys_test.go

- No longer error out when we fail to lookup the passed in issuer_ref or key_ref values on delete apis.
- Add more key related unit tests

PKI: Do not error out on unknown issuers/keys on delete api calls.

---

ui/app/models/mfa-method.js

- use passcode had a default value, as a result it was being sent
with all the mfa method types during save and edit flows..

Remove default values from mfa method model

---

ui/app/components/mfa-login-enforcement-form.js
ui/tests/integration/components/mfa-login-enforcement-form-test.js

When selecting an auth method type to add as a target an error was being returned for types that are not currently mounted. The list now represents only auth types that are mounted.

MFA Login Enforcements Auth Method Target Bug

---

ui/app/components/mount-accessor-select.js
ui/app/templates/components/mfa-login-enforcement-form.hbs
ui/app/templates/components/mount-accessor-select.hbs

According to the backend: >Vault login with a token doesn’t actually talk to vault, it’s just shorthand for “copy this token into my token helper, by default into ~/.vault-token”.  I would omit it (token) from the enforcement options, auth/token with mfa is more of a step-up mfa (ent mfa) thing.
This PR filters it out as an option in the template.

remove token type

---

builtin/logical/pki/path_fetch_issuers.go
builtin/logical/pki/path_roles_test.go
website/content/api-docs/secret/pki.mdx

This updates almost all fields individually in a role, with the exceptions of (key_type, key_bits, and signature_bits) due to inter-dependencies between them. 
Also, fixes a bug spotted by @stevendpclark during review of #15510, where both Update and Patch issuer didn't validate the new name.

Add role patching test case

---

changelog/15167.txt
ui/app/adapters/clients/activity.js

- Backend convert the timezone to UTC, to mitigate it's impact sending
start and end date other than 1. Chose 10 and 20 randomly.

Handle client count timezone

---

builtin/logical/consul/path_roles.go
changelog/15550.txt

Adding deprecated tags to the fields `token_type` and `policy` as they were long-ago deprecated in Consul and no longer supported in new versions. Documentation and explanation of this change will be added in the neat future separately.

Add deprecated tags to token_type and policy

---

builtin/credential/ldap/backend.go
builtin/credential/ldap/backend_test.go
builtin/credential/ldap/path_login.go
changelog/15525.txt
sdk/helper/ldaputil/client.go

There is a bug that was introduced in the LDAP authentication method by https://github.com/hashicorp/vault/pull/11000.
It was thought to be backward compatible but has broken a number of users. Later
a new parameter `username_as_alias` was introduced in https://github.com/hashicorp/vault/pull/14324
to make it possible for operators to restore the previous behavior.
The way it is currently working is not completely backward compatible thought
because when username_as_alias is set, a call to GetUserAliasAttributeValue() will
first be made, then this value is completely discarded in pathLogin() and replaced
by the username as expected.
This is an issue because it makes useless calls to the LDAP server and will break
backward compatibility if one of the constraints in …

Fix handling of username_as_alias during LDAP authentication

---

builtin/logical/ssh/path_roles.go
changelog/15559.txt

Found a bug in an improvement that was merged to main the other day (#15250).
The SSH Role field `not_before_duration` field is returned in nanoseconds instead of seconds (as expected).
The following requests fixes this issue by converting the value of the fields to seconds before returning it.
PS: The screenshots are a bit bigger than expected.
Not sure if it's worth creating an issue for this.
@cipherboy 
Sorry for pinging, just thought it would be faster since you have context of what was done.

Convert not_before_duration to seconds before returning it

---

website/content/docs/enterprise/license/faq.mdx

Support for stored licenses will be removed in Vault 1.11. This PR introduces the associated changes to the license [FAQ doc page](https://www.vaultproject.io/docs/enterprise/license/faq).

FAQ doc updates for removal of stored licenses in 1.11

---

CHANGELOG.md
changelog/14975.txt
changelog/15004.txt
changelog/15100.txt
changelog/15152.txt
changelog/15155.txt
changelog/15179.txt
changelog/15211.txt
changelog/15277.txt

Add various changelog entries to call out changes that occurred as part of the PKI rotation project to existing behaviors.

Add various missing PKI related changelog entries

---

website/content/docs/secrets/pki/considerations.mdx

1. Add note about cross-cluster CRL URIs
2. Add note that short TTLs are relative to quantity
3. Add note to make sure default is configured
4. Add note about automating certificate renewal
1, 2, and 4 were suggested by @gitrgoliveira, thank you!

Add more PKI usage best practices to documentation

---

builtin/logical/pki/backend.go
builtin/logical/pki/path_issue_sign.go
changelog/15543.txt

In #15277, we missed that the new `/issuer/issuer_ref/sign-verbatim` path lacked a role-allowed variant (like `/sign-verbatim/:role` does). Add the missing parameter.
Additionally, I noticed that `sign-verbatim` (since early versions), wouldn't warn or err on a missing role when one was requested. Since we don't currently err, we can't now err, so add a warning instead.

Allow issuer/:issuer_ref/sign-verbatim/:role, add error on missing role

---

website/content/docs/auth/okta.mdx
website/content/docs/auth/token.mdx

This PR adds documentation to recommended a minimally permissive role to use when generating the API token used by Vault's Okta auth method.

auth/okta: documents API token minimal permissions

---

website/content/docs/commands/operator/init.mdx
website/content/docs/concepts/seal.mdx
website/content/docs/enterprise/hsm/behavior.mdx

Per [Asana](https://app.asana.com/0/563192436488770/1202302893205879/f), the following actions were taken:
- The recovery key description was moved from the [HSM](https://www.vaultproject.io/docs/enterprise/hsm/behavior) doc to the [Auto-unseal](https://www.vaultproject.io/docs/concepts/seal#auto-unseal) doc.
- A cross-link to the [Auto-unseal](https://www.vaultproject.io/docs/concepts/seal#auto-unseal) doc was added from the [HSM](https://www.vaultproject.io/docs/enterprise/hsm/behavior)  and [operator init](https://www.vaultproject.io/docs/commands/operator/init) docs.
HSM :mag: [Deploy Preview](https://vault-git-docs-recovery-keys-update-hashicorp.vercel.app/docs/enterprise/hsm/behavior)
Auto-Unseal :mag: [Deploy Preview](https://vault-git-docs-recovery-keys-update-hashicorp.vercel.app/ …

Vault documentation: reorganized docs by moving recovery key description

---

api/sys_monitor.go
changelog/15536.txt
command/debug.go
command/monitor.go
helper/monitor/monitor_test.go
http/sys_monitor_test.go
vault/logical_system.go
vault/logical_system_paths.go
website/content/api-docs/system/monitor.mdx
website/content/docs/commands/debug.mdx
website/content/docs/commands/monitor.mdx

Adding log_format flag to monitor endpoint as well as debug command. This will allow the option for vault logs being emitted via monitor to come through as JSON format. The default behavior is to emit in the standard log format.
Usage:
`vault monitor -log-level=DEBUG -log-format=JSON`
`curl -H "X-Vault-Request: true" -H "X-Vault-Token: $(vault print token)" http://127.0.0.1:8200/v1/sys/monitor?log_format=json&log_level=trace`
`vault debug -target=log -log-format=json`

api/monitor: Adding log format to monitor command and debug

---

changelog/15573.txt
ui/app/models/database/role.js

Removed unsupported field of `revocation_statements` for DB roles for `elasticsearch` database

Remove unsupported fields for DB roles show page

---

physical/raft/raft.go
physical/raft/raft_test.go

I forgot to include this check in the original PR. I'm assigning the nochangelog label because this technically falls under the enterprise autopilot changelog.

autopilot_upgrade_version should be parseable

---

website/data/docs-nav-data.json

This PR updates external Learn links in the sidebar data to reference dev portal paths. @BRKalow let me know if this should be handled in dev portal instead of on this branch.

Chore (dev portal): update learn nav data links 

---

ui/app/services/permissions.js

I ran into this bug when using the following policy. (Policy is needed for mfa-end-user flow). It appears main app route was searching for `identity/mfa/method` but couldn't find it. In the MFA work, this API_PATH had been added to the permission.js file but not to the API_PATHS_TO_ROUTE_PARAMS, so it was returning null and causing an error. I can't say I understand this service entirely, but this does fix the issue.
```
path "identity/*" {
capabilities = ["create", "read", "update", "delete", "list"]
}
```

BUG: MFA permissions fix

---

changelog/15592.txt
go.mod
go.sum

This PR updates vault-plugin-auth-gcp to [v0.13.0](https://github.com/hashicorp/vault-plugin-auth-gcp/releases/tag/v0.13.0).
```
go get github.com/hashicorp/vault-plugin-auth-gcp@v0.13.0
go mod tidy
```

auth/gcp: updates plugin to v0.13.0

---

changelog/15584.txt
go.mod
go.sum

Also updates the cap library to `main`, since v0.13.0 of k8s auth relies on it.
```
go get github.com/hashicorp/cap@main
go get github.com/hashicorp/vault-plugin-auth-kubernetes@v0.13.0
go mod tidy
```

upgrade vault-plugin-auth-kubernetes to v0.13.0

---

changelog/15585.txt
go.mod
go.sum

Update the k8s auth plugin to v0.12.1
Steps:
```
go get github.com/hashicorp/vault-plugin-auth-kubernetes@v0.12.1
go mod tidy
```

update k8s auth version for 1.10.x

---

website/content/api-docs/secret/databases/elasticdb.mdx
website/content/docs/upgrading/upgrade-to-1.11.x.mdx
website/data/docs-nav-data.json

Update elasticsearch db secrets engine docs for the `use_old_xpack` option being introduced in https://github.com/hashicorp/vault-plugin-database-elasticsearch/pull/37. Also include an upgrade note.

docs/database/elasticsearch: use_old_xpack option

---

go.mod
go.sum

This PR vault-plugin-auth-alicloud to v0.12.0
```sh
$ go get github.com/hashicorp/vault-plugin-auth-alicloud@v0.12.0
$ go mod tidy
```

auth/alicloud: update plugin to v0.12.0

---

go.mod
go.sum

This PR updates vault-plugin-secrets-gcp to [v0.13.0](https://github.com/hashicorp/vault-plugin-secrets-gcp/releases/tag/v0.13.0).
```
go get github.com/hashicorp/vault-plugin-secrets-gcp@v0.13.0
go mod tidy
```

secrets/gcp: updates plugin to v0.13.0

---

.release/ci.hcl
sdk/version/version_base.go

- Increased SDK `Version` to `1.12.0`
- Removed 1.7.x branch and added 1.11.x branch in `.releases/ci.hcl`

Prep for 1.12

---

go.mod
go.sum

This PR updates vault-plugin-database-couchbase to [v0.7.0](https://github.com/hashicorp/vault-plugin-database-couchbase/releases/tag/v0.7.0)
Steps
```
go get github.com/hashicorp/vault-plugin-database-couchbase@v0.7.0
go mod tidy
```

fix: upgrade vault-plugin-database-couchbase to v0.7.0

---

changelog/15608.txt
go.mod
go.sum

This PR updates vault-plugin-database-snowflake to [v0.5.0](https://github.com/hashicorp/vault-plugin-database-snowflake/releases/tag/v0.5.0)
Steps
```
go get github.com/hashicorp/vault-plugin-database-snowflake@v0.5.0
go mod tidy
```

fix: upgrade vault-plugin-database-snowflake to v0.5.0

---

go.mod
go.sum

This PR updates vault-plugin-database-mongodbatlas to [v0.7.0](https://github.com/hashicorp/vault-plugin-database-mongodbatlas/releases/tag/v0.7.0)
Steps
```
go get github.com/hashicorp/vault-plugin-database-mongodbatlas@v0.7.0
go mod tidy
```

fix: upgrade vault-plugin-database-mongodbatlas to v0.7.0

---

website/content/api-docs/secret/mongodbatlas.mdx

This PR adds the missing [`organization_id`](https://github.com/hashicorp/vault-plugin-secrets-mongodbatlas/blob/main/path_roles.go#L30) parameter to the MongoDB Atlas secrets engine API docs.

secrets/mongodbatlas: adds missing organization_id to API docs

---

ui/app/models/mfa-login-enforcement.js
ui/app/serializers/mfa-login-enforcement.js
ui/app/templates/components/mfa/login-enforcement-list-item.hbs
ui/app/templates/components/mfa/method-list-item.hbs
ui/app/templates/components/mfa/nav.hbs
ui/app/templates/vault/cluster/access.hbs
ui/app/templates/vault/cluster/access/mfa/enforcements/enforcement/index.hbs
ui/app/templates/vault/cluster/access/mfa/enforcements/index.hbs
ui/mirage/factories/mfa-login-enforcement.js
ui/mirage/handlers/mfa-config.js
ui/tests/acceptance/mfa-login-enforcement-test.js

- adds acceptance tests for mfa config login enforcement workflows
- fixes bug setting icon for token mount when preparing login enforcement targets
- fixes bug with removing `auth_method_accessors` or `auth_method_types` not saving

MFA Login Enforcement Acceptance Tests

---

changelog/15583.txt
vault/logical_system.go

Wrapping and unwrapping works in namespaces, but a lookup operation always throws an error.
Example of proper functioning within root namespace:
```
❯ vault write -format=json sys/wrapping/wrap foo=bar | jq .wrap_info.token
"hvs.CAESIIKmFRNNJnGtpY204WMmkfoaLndJkBd0ZG4ZVtaan81lGh4KHGh2cy41cGxKYURDeGRwWlpaaTNYTWNSdmRuWFg"
❯ vault write sys/wrapping/lookup token=hvs.CAESIIKmFRNNJnGtpY204WMmkfoaLndJkBd0ZG4ZVtaan81lGh4KHGh2cy41cGxKYURDeGRwWlpaaTNYTWNSdmRuWFg
Key              Value
---              -----
creation_path    sys/wrapping/wrap
creation_time    2022-05-24T17:00:57.64062-04:00
creation_ttl     5m
❯ vault write -format=json sys/wrapping/unwrap token=hvs.CAESIIKmFRNNJnGtpY204WMmkfoaLndJkBd0ZG4ZVtaan81lGh4KHGh2cy41cGxKYURDeGRwWlpaaTNYTWNSdmRuWFg
{
"foo": "bar"
}
```
Example of error …

use provided namespace for wrapping lookup cubbyhole request

---

changelog/15655.txt
go.mod
go.sum

Updates vault-plugin-secrets-kubernetes to [v0.1.1](https://github.com/hashicorp/vault/pull/new/k8s-secrets-0.1.1)
```console
go get github.com/hashicorp/vault-plugin-secrets-kubernetes@v0.1.1
go mod tidy
```

secrets/kubernetes: update to v0.1.1

---

builtin/logical/transit/path_import.go
builtin/logical/transit/path_import_test.go

This updates the Transit BYOK import ciphertext to be standard base64 encoding as used in other input fields across Vault.

Updated base64 encoding of ciphertext for Transit BYOK import.

---

go.mod
go.sum

Updates OpenLDAP secrets engine to v0.8.0.
```
go get github.com/hashicorp/vault-plugin-secrets-openldap@v0.8.0
go mod tidy
```

Update openldap secrets to v0.8

---

website/content/api-docs/secret/pki.mdx
website/content/docs/secrets/pki/considerations.mdx

- Add a TOC to the PKI considerations page
- Merge in the existing certificate storage into a new Replicated DataSets section
- Move the existing Cluster Scalability section from the api-docs into the considerations page.

Add a little more information about PKI and replicated data sets to the PKI docs.

---

website/content/api-docs/auth/gcp.mdx
website/content/docs/auth/gcp.mdx

This PR adds documentation for the custom endpoint configuration added to the GCP auth method in https://github.com/hashicorp/vault-plugin-auth-gcp/pull/126.
Additionally, it consolidates documentation around service account permissions and GCP APIs that need to be enabled for specific configs.

auth/gcp: adds documentation for custom endpoint overrides

---

changelog/15482.txt
vault/external_tests/mfa/login_mfa_test.go
vault/identity_store.go
vault/login_mfa.go

Related to [VAULT-5993](https://hashicorp.atlassian.net/browse/VAULT-5993)
Prevent deleting a valid MFA method ID using the endpoint for a different MFA method type

prevent deleting MFA method through an invalid path

---

builtin/logical/pki/integation_test.go
builtin/logical/pki/path_root.go
website/content/api-docs/secret/pki.mdx

- Add tests for the two api endpoints
- Also return the issuer_name and key_name fields within the generate root api response
- Update api-docs for Generate Root to match what we return as api response and the params we accept.

Add integration tests for aliased PKI paths (root/rotate, root/replace)

---

website/content/docs/auth/jwt/oidc_providers.mdx
website/content/docs/auth/kubernetes.mdx

I learned about the `--raw` option recently, which helps avoid the complications of running the proxy in the background for sample commands that interact with the k8s API.

docs: Improve sample commands for querying k8s API

---

website/content/docs/platform/k8s/index.mdx

Per Jonathan's request, the link to **Vault Installation to Minikube via Helm** tutorial needed to be updated.
:mag: [Deploy Preview](https://vault-git-docs-update-learn-link-hashicorp.vercel.app/docs/platform/k8s#guides)

Vault documentation: updated learn link

---

.github/workflows/build.yml
.release/docker/ubi-docker-entrypoint.sh
Dockerfile

See also: #14369 + #15272 + #15439 + #15443 + #15438.
Note that #14369 wasn't cherry-picked but included in the first commit. This isn't relevant for FIPS but is good to have UBI process be the same across releases.

Backport CRT UBI onboarding to 1.9.x

---

.github/workflows/build.yml
.release/docker/ubi-docker-entrypoint.sh
Dockerfile

See also: #14369 + #15272 + #15439 + #15443 + #15438.
Note that #14369 wasn't cherry-picked but included in the first commit. This will be necessary for future FIPS 140-2 UBI releases on the 1.10.x series.

Backport CRT UBI onboarding to 1.10.x

---

go.mod
go.sum

Updates Terraform secrets engine to v0.5.0.
```
go get github.com/hashicorp/vault-plugin-secrets-terraform@v0.5.0
go mod tidy
```

Update terraform secrets to v0.5

---

vault/activity_log.go
vault/activity_log_test.go

This PR fixes an off-by-one error in the nil month padding code in the activity log, which I added in the following PR: https://github.com/hashicorp/vault/pull/15420/files

fix off by one error in activity log nil padding for month data

---

helper/random/random_api.go

- When an end-user specifies the all source type within
transit/random and sys/tools/random, only use the additional source
if we are actually configured with an external entropy source
Addresses: VAULT-6415

Only use additional entropy source when configured within transit and sys random calls

---

ui/app/models/mfa-method.js
ui/lib/core/addon/components/form-field.hbs
ui/lib/core/addon/components/ttl-picker2.js
ui/tests/integration/components/form-field-test.js
ui/tests/pages/components/form-field.js

- For possible values, now we can render either dropdown or radio buttons
- Drop down will be used for larger data set, whereas radio buttons should
be used when we have only couple of options (example totp mfa)
- Added test for radio button functionality
- Added missing test for ttl without toggle

Option to show radio button in form field

---

website/content/api-docs/secret/pki.mdx
website/content/docs/secrets/pki/considerations.mdx

- Missing `key_ref` param on generate root
- Missing section on key generation
- Document permissions for manged key access.

More PKI docs updates

---

builtin/logical/pki/integation_test.go
builtin/logical/pki/path_manage_issuers.go
builtin/logical/pki/storage.go

- Do not set the first issuer we attempt to import as the default issuer unless
it has a corresponding key.
- Add the ability to set a default issuer if none exist and we import it's corresponding key after the fact.
- Add a warning to an end-user if we imported multiple issuers with keys and we
choose one of them as the default value.

PKI: Only set issuers with an associated key as default on import

---

website/content/docs/audit/index.mdx

Per [Asana](https://app.asana.com/0/563192436488770/1202383293623144), a link to the relevant block audit device tutorial was added to the audit device page.
:mag: [Deploy Preview](https://vault-git-docs-add-tutorial-link-hashicorp.vercel.app/docs/audit#tutorial)

Vault documentation: added relevant link to tutorial from audit device page

---

website/content/api-docs/secret/pki.mdx

As caught by Ivana, thank you!

Fix copy/paste typo in PKI key generation docs

---

changelog/15769.txt
ui/app/lib/local-storage.js
ui/app/lib/token-storage.js
ui/tests/acceptance/enterprise-control-groups-test.js
ui/tests/acceptance/redirect-to-test.js

In #14054 we moved from localStorage to using sessionStorage in an effort to make the Vault UI auth sessions tab-specific rather than browser-wide. However, after hearing from the community we are going to revisit our approach to browser security and revert this change for now.

Revert UI: replace localStorage with sessionStorage

---

website/content/api-docs/auth/jwt.mdx
website/content/api-docs/index.mdx
website/content/api-docs/secret/cassandra.mdx
website/content/api-docs/secret/identity/mfa/duo.mdx
website/content/api-docs/secret/identity/mfa/index.mdx
website/content/api-docs/secret/identity/mfa/okta.mdx
website/content/api-docs/secret/identity/mfa/pingid.mdx
website/content/api-docs/secret/identity/mfa/totp.mdx
website/content/api-docs/secret/kv/index.mdx
website/content/api-docs/system/mfa/index.mdx
website/content/api-docs/system/mounts.mdx
website/content/docs/auth/jwt/index.mdx
website/content/docs/commands/operator/generate-root.mdx
website/content/docs/commands/operator/rekey.mdx
website/content/docs/concepts/dev-server.mdx
website/content/docs/concepts/policies.mdx
website/content/docs/concepts/tokens.mdx
website/content/docs/index.mdx
website/content/docs/internals/telemetry.mdx
website/content/docs/partnerships.mdx
website/content/docs/secrets/databases/elasticdb.mdx
website/content/docs/secrets/databases/mysql-maria.mdx
website/content/docs/use-cases.mdx

Fix links which point at redirects defined in `website/redirects.js`
The formatting changes are a result of us running the content through a parser and re-stringifying it from an AST. Functionally nothing should change.

website: fix internal redirect links

---

builtin/audit/file/backend.go
builtin/audit/file/backend_test.go
changelog/15759.txt

https://github.com/hashicorp/vault/issues/14182

File Audit Mode 0000 bug 

---

builtin/logical/pki/path_roles.go
builtin/logical/pki/path_roles_test.go
changelog/15751.txt
sdk/helper/certutil/helpers.go
sdk/helper/certutil/types.go

Allows a new method of adding Policy Information that enables the use of CPS URLs and (explicit text) user notices.  This is done in one field (in the same field as previously).
Eg: 
```
vault write pki/roles/puppy policy_identifiers='[{"oid":"1.3.6.1.4.1.7.8","notice":"I am a user Notice"}, {"oid":"1.3.6.1.4.1.44947.1.2.4","cps":"https://example.com"}]'
Success! Data written to: pki/roles/puppy
```
On the backend each policy_identifier is stored separately - those might be an oid or string_json form of policy identifier with qualifiers.

Support for CPS URLs in Custom Policy Identifiers.

---

website/content/docs/concepts/policies.mdx

The [policies docs](https://www.vaultproject.io/docs/concepts/policies#capabilities) do not currently account for the `patch`  capability. This PR adds it and provides some useful examples.

add missing patch capability to policy docs

---

changelog/15735.txt
vault/request_handling.go

The crux of the issue here was that lease quota checks get routed differently to rate limit checks. In the case of lease quota checks, the MountPoint was not always present on the logical.Request. In essence, when searching for an applicable quota to apply to the request, it would not correctly find the applicable quota as it uses the MountPoint as part of searching for applicable quotas. It seems to apply only to endpoints that generate a lease on Read.
Lease quotas now apply properly on quotas based on mounts that when generating a lease on a Read:
```
violethynes@violethynes-C02CW1WWMD6R vault-enterprise % vault read mysql-database/creds/my-role
Error reading mysql-database/creds/my-role: Error making API request.
URL: GET http://127.0.0.1:8200/v1/mysql-database/creds/my-role
Code: …
```

VAULT-6371 Fix issue with lease quotas on read requests that generate leases

---

changelog/15792.txt
go.mod
go.sum

Upgrading `vault-plugin-secrets-kv` to `v0.12.1` includes the bug fix described in https://github.com/hashicorp/vault-plugin-secrets-kv/pull/62.

bump vault-plugin-secrets-kv to v0.12.1

---

changelog/15789.txt
ui/app/components/calendar-widget.js
ui/app/styles/components/calendar-widget.scss
ui/app/templates/components/calendar-widget.hbs
ui/tests/integration/components/calendar-widget-test.js

Fixes calendar widget allowing user to select an end month prior to the start month (ex. `May 2022 - January 2021`)

UI: calendar widget fix

---

sdk/database/dbplugin/v5/database.go
sdk/database/dbplugin/v5/grpc_client.go

This PR fixes an issue that occurs in the `map[string]interface{}` to [`structpb.Struct`](https://pkg.go.dev/google.golang.org/protobuf/types/known/structpb#Struct) conversion at [dbplugin/v5/marshalling.go#L24](https://github.com/hashicorp/vault/blob/main/sdk/database/dbplugin/v5/marshalling.go#L24). The issue is that [`NewStruct`](https://pkg.go.dev/google.golang.org/protobuf/types/known/structpb#NewStruct) can only convert `[]interface{}` for list types. We were using `[]string` to allow plugins to communicate supported credential types in the initialization response which resulted in the following error:
```
* error creating database object: unable to initialize: rpc error: code = Internal desc = failed to marshal new config to JSON: proto: invalid type: []string
```
This only occurs …

secrets/db: fix structpb conversion for external plugins using alternative cred types

---

ui/app/components/database-role-setting-form.js
ui/app/components/generated-item-list.js
ui/app/components/home-link.js
ui/app/components/hover-copy-button.js
ui/app/templates/components/generated-item-list.hbs
ui/app/templates/components/home-link.hbs
ui/app/templates/components/hover-copy-button.hbs
ui/app/templates/vault/cluster/access/method/item/list.hbs
ui/tests/integration/components/hover-copy-button-test.js

This PR glimmerizes the following components:
1. generated-item-list
2. hover-copy-button
3. home-link
Small components. It makes it easier to have small contained components glimmerized before hitting the more nuanced components, at least that's what I'm telling myself.

Glimmer continued

---

.github/workflows/build.yml

Similar to https://github.com/hashicorp/vault/blob/main/.circleci/config/commands/exit-if-ui-or-docs-branch.yml, ignore CRT builds if it's just a docs change.
I also pushed these changes to a docs/ branch to test: https://github.com/hashicorp/vault/compare/docs/ignore-crt-builds-on-docs-branches?expand=1

Ignore crt builds on docs branches

---

go.mod
go.sum

This PR updates vault-plugin-database-snowflake to [v0.5.1](https://github.com/hashicorp/vault-plugin-database-snowflake/releases/tag/v0.5.1) to bring in a bug fix from:
- https://github.com/hashicorp/vault/pull/15801
- https://github.com/hashicorp/vault-plugin-database-snowflake/pull/16
Steps:
```
go get github.com/hashicorp/vault-plugin-database-snowflake@v0.5.1
go mod tidy
```

db/snowflake: updates plugin to v0.5.1

---

vault/logical_system.go
website/content/api-docs/system/auth.mdx

- Fixes the documentation on `/sys/auth` to match `/sys/mounts`,
- Fix the path-help value as well, though I don't know where this particular one shows up.
See also: #15209.

Fix listing_visibility value documentation

---

builtin/logical/transit/path_import_test.go
changelog/15742.txt
sdk/helper/keysutil/policy.go
sdk/helper/keysutil/util.go

NSS wraps Ed25519 using the PKCS#8 standard structure. The Go standard
library as of Go 1.18.x doesn't support parsing this key type with the
OID used by NSS; it requires the 1.3.101.112/RFC 8410 format, rather
than the RFC 5915-esque structure supported here.
```
Co-authored-by: Rachel Culpepper <84159930+rculpepper@users.noreply.github.com>
```

Add parsing for NSS-wrapped Ed25519 keys

---

website/content/docs/platform/k8s/csi/configurations.mdx
website/content/docs/platform/k8s/helm/configuration.mdx

Updates the website with the latest flags, and also make some other small improvements to help users link things together.

docs: Update CSI Provider command line arguments

---

website/content/docs/configuration/entropy-augmentation.mdx
website/content/docs/enterprise/entropy-augmentation.mdx
website/content/docs/enterprise/fips/fips1402.mdx

This adds a known-panic w.r.t. Entropy Augmentation due to restrictions
in how BoringCrypto's RNG works. Additionally adds the RH Access
container repository and adds a note about restricted support scenarios.

Add support notes, Entropy Augmentation notes, RH repo

---

changelog/15824.txt
ui/app/components/secret-edit.js
ui/tests/acceptance/secrets/backend/kv/secret-test.js

This PR fixes the path what capabilities are checked against when evaluating whether to show the metadata tab on KV v2 secrets engine. Since metadata is only ever connected to a secret with an ID, we need to provide the ID on that capability path so that it is checked for each specific secret view. 
Repro steps for the bug are excellently outlined in issue #15347

UI: Fix metadata tab not showing given policy

---

website/content/docs/agent/template.mdx

PR to add an example for `pkiCert` in our docs which got introduced in consul-template v0.29.0 and slated for release in Vault 1.11.
Related to https://github.com/hashicorp/vault/pull/15293

docs: add pkiCert example on agent template docs

---

website/content/docs/auth/gcp.mdx

Adds to and updates gcp auth docs for feature added in 1.11 to allow easier login when running Vault on a GCE/GKE instance.

Update GCP auth docs for GCE identity token login

---

changelog/15858.txt
command/server.go

---
[Per docs](https://www.vaultproject.io/docs/configuration/entropy-augmentation#requirements) entropy augmentation does not work with FIPS 140-2. Add a warning to server startup and disable the config.

Add warning about EA in FIPS mode

---

website/content/api-docs/secret/pki.mdx
website/content/docs/secrets/pki/considerations.mdx

This adds a note that manual_chain is required for cross-signed
intermediates, as Vault will not automatically associate the
cross-signed pair during chain construction. During issuance, the chain
is used verbatim from the issuer, so no chain detection will be used
then.

Use manual_chain for cross-signed intermediates

---

api/kv.go
api/kv_v1.go
api/kv_v2.go

The new KV helper methods (Get, PutMetadata, etc.) are not that useful if users cannot find them, and various usability studies we've done have shown that many users rely on the [godoc](https://pkg.go.dev/github.com/hashicorp/vault/api) page for discovery of the api package's functionality.
Since the kvv1 and kvv2 structs are private, their methods do not show in the godoc.
By changing them to public but keeping their fields private, we still force users to go through our constructor method (`client.KVv1(mountPath)` and `client.KVv2(mountPath)`) to initiate the structs, but their methods will now be displayed in the godoc.
This also matches how the similarly-designed `Logical` and `Auth` struct work today.

Make KV structs public so the KV helper methods show in godoc

---

builtin/logical/pki/storage_migrations.go
builtin/logical/pki/storage_migrations_test.go

- Selecting a constant default value exposed a possible edge case
that the migration would fail if a previous migration contained the
same issuer or key name.

pki: Do not use a static issuer/key name within the migration

---

command/server.go

This was causing failures when running `vault server -dev`:
> ```
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x105c41c1c]
>
> goroutine 1 [running]:
> github.com/hashicorp/vault/command.(*ServerCommand).parseConfig(0x140005a2180)
> 	.../vault/command/server.go:429 +0x5c
> ```
Interestingly, we do not have a test case for running the dev
sever.
---
This was broken in: https://github.com/hashicorp/vault/pull/15858

Add missing nil check to FIPS EA verification

---

ui/ember-cli-build.js

By default, ember build fingerprint all the static assets such as
'js', 'css', 'png', 'jpg', 'gif', 'map' during compilation. As a result the image
referenced in mfa landing page was not loading in binary. For now, exclude fingerprinting
for all the files which exists under images directory.

Remove fingerprinting for images

---

command/server.go
command/server_util.go

Vault Enterprise will need to ensure that a supported storage backend is configured upon startup. This PR includes the OSS pieces to support that check within the `vault server` command.

add OSS noop check for valid ent storage

---

changelog/15866.txt
physical/postgresql/postgresql.go

I have observed postgres backend query times far exceed request time in cases where the client cancels the request (usually because postgres is not responding fast enough). This solves the issue by allowing the postgres query to be canceled when the associated request is cancelled.

pass context to postgres queries

---

website/content/docs/auth/approle.mdx
website/content/docs/auth/aws.mdx
website/content/docs/auth/azure.mdx
website/content/docs/auth/gcp.mdx
website/content/docs/auth/kubernetes.mdx
website/content/docs/get-started/developer-qs.mdx

This PR updates the example snippets in the docs and dev quickstart guide to use the new KV helper methods (matching what we'll have in the hashicorp/vault-examples repo).

Use KV helpers in docs and dev quickstart guide

---

ui/app/components/clients/vertical-bar-chart.js
ui/app/templates/components/clients/vertical-bar-chart.hbs

Previously the tooltip displayed in the middle of the bar, moved it to the top of each bar.

UI: Fix tooltip hover for vertical bar chart

---

sdk/go.mod

The sdk package is now relying on `//go:build` directives, so the minimum required Go version needs to be `go 1.17`.

Update minimum required go version for sdk

---

api/go.mod
api/go.sum
go.mod

Now that `sdk` requires a minimum version of go 1.17 to work, api should reflect the same since sdk is a dependency.

Update minimum required go version for api

---

go.mod

This PR bumps the version of the `api` version used by the Vault binary to the latest version `api/v1.7.2`.

Use latest api version

---

website/content/docs/configuration/storage/cockroachdb.mdx
website/content/docs/configuration/storage/postgresql.mdx
website/content/docs/secrets/databases/postgresql.mdx

This PR updates documentation that was referencing the [lib/pq](https://github.com/lib/pq) package which is being replaced by [jackc/pgx](https://github.com/jackc/pgx).
Related PR: https://github.com/hashicorp/vault/pull/15343

docs/postgres: replaces lib/pq with pgx

---

changelog/15900.txt
command/server/config.go
command/server/config_test.go
command/server/config_test_helpers.go

https://github.com/hashicorp/vault/issues/14043
The gh issue is specific to zookeeper but this is applicable for all ha_storage backends 
When providing boolean options to an ha_storage backend (ex. tls_enabled, tls_skip_verify) vault cannot parse them. It only accepts string values for boolean fields i.e; "true" and "false"
The parsing works well for storage backends. Therefore, changed the parsing similar to parsing values for storage backend

Parse ha_storage in config 

---

website/content/api-docs/secret/databases/index.mdx
website/content/api-docs/secret/databases/snowflake.mdx
website/content/docs/secrets/databases/index.mdx
website/content/docs/secrets/databases/snowflake.mdx
website/content/partials/db-secrets-credential-types.mdx

This PR adds documentation for the following:
- Credential types and configuration for the database secrets engine
- Usage of the `rsa_private_key` credential type in the Snowflake database plugin

secrets/db: documents credential types and snowflake key pair auth

---

changelog/14399.txt
command/debug.go

This PR resolves a panic on Windows that occurs when capturing a vault debug bundle.
Fixes #14394

Fix debug bundle panic on Windows

---

ui/app/components/mount-backend-form.js
ui/app/templates/components/mount-backend-form.hbs

This PR glimmerizes the mount-backend-form component. I went ahead and tackled this one because we will be working in this component for the upcoming PKI work. It will make it a little easier for the future work having this component updated. Specifically, having tracked properties instead of computed.

Glimmerize mount-backend-form

---

ui/app/routes/vault/cluster/secrets/backend/overview.js

The Overview page, unlike the Roles, or the Configuration page on secret engines doest not use the secret-engine model. It makes its own and this model is missing the icon param. Thus, the icon was not showing on the overview page even if it was showing on all the other tabs. I added it in.
I ran into this during the PKI R&D work.
The hardcoded value works here because the Overview page is only used for the database secret-engine. This will be changed in the PKI work which will also use the overview page. However, because each overview will be very different (make different request, need a different model), I am going to distinguish theses by renaming them overview-database and overview-pki. There is also a hard coded value already in this route for engineType on row 52.
**Before:** …

Quick Bug Fix: missing database icon on overview page

---

builtin/logical/nomad/backend_test.go
builtin/logical/nomad/path_config_access.go
changelog/15809.txt

In the Nomad secret engine, writing to `/nomad/config/access` allows users
to specify a CA certificate and client credential pair. However, these
values are not in the read of the endpoint, making it hard for operators
to see if these values were specified and if they need to be rotated.
Add `ca_cert` and `client_cert` parameters to the response, eliding the
`client_key` parameter as it is more sensitive (and should most likely
be replaced at the same time as `client_cert`).
---
Resolves: #10628

Allow reading Nomad CA/Client cert configuration

---

website/content/api-docs/secret/ssh.mdx

Fix location of not_before_duration on ssh docs

---

changelog/15912.txt
vault/identity_store_groups.go
vault/identity_store_groups_test.go
vault/identity_store_util.go

Providing `member_group_ids` that contains a cycle for an identity group to `identity/group/name/<name>` will currently result in a 500 response. This should instead be a 400 response stating that a cycle was detected.
**Reproduction steps:**
Create groups:
```
ID_Group_0=`vault write -format=json identity/group/name/Group_0 | jq -r ".data.id"
ID_Group_1=`vault write -format=json identity/group/name/Group_1 | jq -r ".data.id"
ID_Group_2=`vault write -format=json identity/group/name/Group_2  | jq -r ".data.id"
```
Specify group IDs for `Group_0` and `Group_1`:
```
vault write identity/group/name/Group_0 member_group_ids= 
vault write identity/group/name/Group_1 member_group_ids=$ID_Group_2 
```
Specify group IDs for `Group_2` will fail due to cycle:
```
vault write …
```

return bad request instead of server error for identity group cycle detection

---

website/data/api-docs-nav-data.json
website/data/docs-nav-data.json

Replaces the `<sup>` tags in nav data JSON files with a `badge` property. This is a new feature in DevDot, introduced in https://github.com/hashicorp/dev-portal/pull/562. Each badge has `type="outlined"` and `color="neutral"`.
Asana task: https://app.asana.com/0/1202114367927919/1202405210286703/f

Use `badge` for `<sup>` tags in nav data JSON files

---

builtin/logical/ssh/path_issue.go
builtin/logical/ssh/path_sign.go

Do not wrap all errors into logical.ErrorResponse as I believe that switches the return code from a 5XX to a 4XX. Also if the `pathSignIssueCertificateHelper` returns an error response value, do not add data to it.

ssh: Do not convert errors into logical.ErrorResponse in issue path

---

website/content/api-docs/system/lease-count-quotas.mdx
website/content/api-docs/system/rate-limit-quotas.mdx
website/content/docs/enterprise/lease-count-quotas.mdx

We made a decision on Slack: https://hashicorp.slack.com/archives/CMRSLF924/p1654718659650829
To update the docs instead of fix this issue as it's ultimately a breaking change if we were to enable this behaviour now.
I wasn't sure about the additions in the API docs but it felt like the best place to put the information and I felt it was important that this was documented as it could seem unintuitive (as root namespace quotas do get inherited)

VAULT-5095 Update docs to reflect that child namespaces do not inherit parent quotas

---

builtin/logical/database/backend.go

To signal to any credentials rotating goroutines that they should cancel
pending operations, which reduces lock contention.

database plugin: Invalidate queue should cancel context first

---

website/content/docs/auth/jwt/oidc_providers.mdx

This PR adds missing steps to the documentation for configuring OIDC auth with the Google workspace integration. I ran into these issues when setting up the configuration in a new GCP project.

docs/oidc: adds missing steps for Google Workspace configuration

---

changelog/15685.txt
ui/app/models/aws-credential.js

Hello maintainers! 👋🏼 
While working on some demos with the AWS backend, I noticed that in the _Generate AWS Credentials_ screen, when clicking on the blue _Copy credentials_ button, the following payload is copied:
```json
{
"accessKey": "AKIAIOSFODNN7EXAMPLE",
"secretKey": "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
"leasId": "aws/creds/consumer/L0mkTBzIsjki3jojjgrcICVo.at2AD"
}
```
I believe that `leasId` ought to be `leaseId`, in line with `this.leaseId`.

updates `leasId` to `leaseId`

---

go.mod

We cut a new SDK `v0.5.2` from `HEAD` of `release/1.11.x`. This PR bumps to that version:
```
❯ go get github.com/hashicorp/vault/sdk@sdk/v0.5.2
go: upgraded github.com/hashicorp/vault/sdk v0.5.1 => v0.5.2
```

go get sdk v0.5.2

---

api/renewer_test.go

- If the timing is correct, a delay in the test's select might see the
doneCh signal before the renew channels signal. If that happens, the
test fails as it assumes we will receive signals across different
channels in order.
- Rework the test to make sure that we read from the renew channel if expected
and the done channel so that any errors might not be escaping from detection
on a renew.

TestLifetimeWatcher: Address bad assumption in test assertions

---

ui/app/components/keymgmt/distribute.js
ui/app/models/keymgmt/provider.js
ui/app/templates/components/keymgmt/distribute.hbs
ui/app/templates/components/keymgmt/provider-edit.hbs
ui/tests/acceptance/enterprise-kmse-test.js
ui/tests/integration/components/keymgmt/provider-edit-test.js

When distributing a key to a provider via the _Distribute key_ action in the provider toolbar the key was not appearing in the _Keys_ tab of the provider view until after a refresh. This fixes that and adds a test for the workflow.

KMSE distribute key bug

---

website/content/docs/platform/k8s/injector/annotations.mdx

The injector's `service` annotation is really the vault address to
use, and not just the name of the service.
Also change a couple mentions of "controller" to "injector".
Related to https://github.com/hashicorp/vault-k8s/issues/299

docs/vault-k8s: update the service annotation

---

ui/app/adapters/keymgmt/provider.js
ui/app/serializers/keymgmt/provider.js
ui/app/templates/components/secret-list/item.hbs

- Backend value had to be mapped to the payload so capabilities call
can be triggered. Based on the response from capabilities, options are
rendered in the more menu dropdown.

KMSE provider list menu fix

---

builtin/credential/aws/path_config_rotate_root_test.go
command/operator_diagnose.go
helper/identity/sentinel.go
plugins/database/mssql/mssql.go
sdk/version/version_base.go
vault/cluster.go
vault/ha.go

This brings OSS files in this repo in line with changes that have been made to these files in the ENT repo, but were never backported here.

Correct drift between ENT and OSS

---

website/content/docs/agent/autoauth/methods/gcp.mdx
website/content/docs/auth/gcp.mdx

This PR adds a callout to the configuration section of the GCP auth method docs for [`custom_endpoints`](https://vault-git-main-hashicorp.vercel.app/api-docs/auth/gcp#custom_endpoint).
It also removes a note on parameter removal that was from a few releases ago.

auth/gcp: adds note on custom endpoints to configuration section

---

website/content/docs/commands/index.mdx
website/content/docs/commands/kv/delete.mdx
website/content/docs/commands/kv/destroy.mdx
website/content/docs/commands/kv/get.mdx
website/content/docs/commands/kv/index.mdx
website/content/docs/commands/kv/metadata.mdx
website/content/docs/commands/kv/patch.mdx
website/content/docs/commands/kv/put.mdx
website/content/docs/commands/kv/rollback.mdx
website/content/docs/commands/kv/undelete.mdx
website/content/docs/commands/read.mdx

I have updated all docs pages dealing with the KV CLI to use the new `-mount` flag syntax, which was created to mitigate confusion caused by the previous syntax for interacting with KV secrets in the CLI.
These docs pages will now match the text produced by calling a vault kv subcommand with the `-help` flag.
This syntax is optional, allowing users to do `vault kv get -mount=secret foo` instead of the old `vault kv get secret/foo`. While the old way may look prettier, it turned out this syntax caused a lot of confusion for new users, who quickly run into issues caused by the fact that `secret/foo` looks like a path but is not actually the real path to the secret for KV v2 (`secret/data/foo`). The real path is used by policies and the API, so users fresh off the Getting Started guide often …

Use new -mount syntax for all KV subcommands in 1.11 docs

---

website/content/docs/commands/index.mdx
website/content/docs/commands/kv/delete.mdx
website/content/docs/commands/kv/destroy.mdx
website/content/docs/commands/kv/get.mdx
website/content/docs/commands/kv/index.mdx
website/content/docs/commands/kv/metadata.mdx
website/content/docs/commands/kv/patch.mdx
website/content/docs/commands/kv/put.mdx
website/content/docs/commands/kv/rollback.mdx
website/content/docs/commands/kv/undelete.mdx
website/content/docs/commands/read.mdx

* Use new -mount syntax for all KV subcommands in 1.11 docs
* Use more appropriate heading size for mount flag syntax
* Add the explanatory syntax blurb from the -help text
* Adjust some wording

manual backport: Use new -mount syntax for all KV subcommands in 1.11 docs

---

website/content/docs/release-notes/1.11.0.mdx
website/data/docs-nav-data.json

Created new release notes for Vault 1.11.0
:mag: [Deploy Preview](https://vault-git-docs-release-notes-hashicorp.vercel.app/docs/release-notes/1.11.0)

Vault documentation: release notes for 1.11.0

---

builtin/logical/pki/backend_test.go
builtin/logical/pki/chain_test.go
builtin/logical/pki/crl_test.go
builtin/logical/pki/test_helpers.go

I've personally introduced a number of slow tests to the PKI backend. :-) Here's an attempt at trying to fix that a bit.
See individual commits for individual test speed up counts on my machine. There's definitely more to do but this is a start. :-)
Before: github.com/hashicorp/vault/builtin/logical/pki	355.430s
After: github.com/hashicorp/vault/builtin/logical/pki	151.182s
Edit: add some more refactors. This gets us down by over half!

Refactor PKI tests for speed

---

builtin/logical/pki/backend_test.go

--
What I get for using auto-merge after resolving conflicts :-D

Fix format errors in PKI tests

---

website/content/docs/enterprise/entropy-augmentation.mdx

I noticed the docs page already had some Entropy Augmentation uses, so this adds some missing ones to it.

Document additional entropy augmentation usage locations

---

vault/logical_system_quotas.go
vault/mount.go

Will be used in the PR for path suffix bassed lease-count quotas also. All Ent tests pass.
This seemed to be the nicest refactor to this section possible (the rest is very small, and error handling is done for the MountEntry), and also seems to be much more in line with the normal way to get API paths.

Small refactor of mount entry manipulation

---

vault/external_tests/api/api_integration_test.go

These tests only ever talk to a single node anyway, they run with lots of parallelism, and we'll get better performance and predictability this way.

Use single-core clusters for api integration tests

---

builtin/logical/database/backend.go
builtin/logical/database/path_config_connection.go
builtin/logical/database/path_rotate_credentials.go
builtin/logical/database/rotation.go

Following up from discussions in #15923 and #15933, I wanted to split
out a separate PR that drastically reduced the complexity of the use of
the databaseBackend lock. We no longer need it at all for the
`credRotationQueue`, and we can move it to be solely used in a few,
small connections map management functions.

Cleanup and simplify lock usage in database plugin

---

ui/app/helpers/-date-base.js

While testing, I don't believe the setTimeout written into the date-base helper is working as intended for testing. So higher up I check for testing and return, essentially ignoring the interval.

Fix flaky test

---

builtin/logical/pki/backend_test.go
builtin/logical/pki/chain_test.go
builtin/logical/pki/crl_test.go
builtin/logical/pki/crl_util.go
builtin/logical/pki/test_helpers.go

Backport of #16052. However, the test infra in #15999 was also pulled in. Either we had to rewrite the backported test, or pull in most of the updated testing infra. Importing it verbatim as a backport seemed cleaner than a piece-meal backport.

Backport PKI Intermediate Revocation bug fix and test improvements

---

website/content/docs/concepts/oidc-provider.mdx

Fix default config listed [here](https://www.vaultproject.io/docs/concepts/oidc-provider#keys). The first attr says `rotation_period` but this should read: `algorithm` ([key docs](https://www.vaultproject.io/api-docs/secret/identity/tokens#algorithm))

change rotation_period to algorithm

---

website/content/api-docs/secret/pki.mdx

The returned chain on the issuer is presented both for signing request
responses and (if the default issuer) on the `/ca_chain` path. Overriding
the issuers' automatically constructed chain with a `manual_chain` allows
removal of the root CA if desired.

Clarify that the returned chain is used everywhere

---

website/content/docs/agent/index.mdx

just a little typo fix - we say couple but there are three items

fix docs typo - couple to few

---

builtin/credential/approle/path_login.go
builtin/credential/approle/path_login_test.go
sdk/logical/request.go
sdk/logical/response.go
vault/logical_system_quotas.go

This PR is meant as a start to the role resolution logic for role based quotas. This PR doesn't add any new functionality (hence no changelog), but acts as a basis for the role resolution required for role based quotas.
At this point, I'm hoping most for feedback relating to approach (and sanity checks) before I continue with the implementation for the other auth methods in implementing their Operation to get the role information. The new logic for rate limit quotas can be considered an example of how it might work in the creation of both types of quota.
Left to do:
- Adding the `ResolveRoleOperation` to all auth methods that support roles
- Adding the `role` field to the Quota structs, and using it as part of retrieving/creating quotas
- Performing the `ResolveRoleOperation` when …

Start of implementation of the plumbing for role resolution logic on auth mounts

---

website/content/docs/secrets/transit.mdx

This fixes incorrect HSM mechanisms in the documentation for importing transit keys (from #15817 ).

Fix incorrect HSM mechanisms in transit BYOK docs

---

api/client.go
api/client_test.go
changelog/11904.txt

This PR started out as a fix for issue #11865.  After realizing that not much can be done to address the issue, it shifted into an attempt to provide a workaround.  That lead to extracting the Unix domain socket handling found in the **NewClient(\*Config)** function into its own function, **ParseAddress(string, \*Config)**.  In doing so, it became apparent that if a **Client** is originally created using a TCP based address but then the SetAddress is used to change to a Unix domain socket, the DialContext function in the **HttpClient.Transport** won't be updated as it is in the **NewClient(\*Config)** function.
The current state of this PR has the **SetAddress(string)** function also using this function, however, in order to support changing from a Unix domain socket back to a TCP based …

Improving Handling of Unix Domain Socket Addresses

---

website/content/api-docs/secret/kmip.mdx

The KMIP backend has four new parameters for the API call to create or update a
role:
- operation_decrypt
- operation_encrypt
- operation_import
- operation_query

Add new KMIP backend operation parameters to API documentation.

---

changelog/16094.txt
vault/plugin_catalog.go

* multiplexing: guard against connection panic
* changelog
* Update vault/plugin_catalog.go
Co-authored-by: Calvin Leung Huang <1883212+calvn@users.noreply.github.com>
Co-authored-by: Calvin Leung Huang <1883212+calvn@users.noreply.github.com>

Backport: fix bug where id not existing in multiplexing map causes panic (#16094)

---

ui/app/adapters/named-path.js
ui/app/adapters/oidc/assignment.js
ui/app/adapters/oidc/client.js
ui/app/adapters/oidc/key.js
ui/app/adapters/oidc/provider.js
ui/app/adapters/oidc/scope.js
ui/app/models/oidc/provider.js
ui/app/serializers/oidc/assignment.js
ui/app/serializers/oidc/client.js
ui/app/serializers/oidc/key.js
ui/app/serializers/oidc/provider.js
ui/app/serializers/oidc/scope.js
ui/tests/unit/adapters/oidc/assignment-test.js
ui/tests/unit/adapters/oidc/client-test.js
ui/tests/unit/adapters/oidc/key-test.js
ui/tests/unit/adapters/oidc/provider-test.js
ui/tests/unit/adapters/oidc/scope-test.js
ui/tests/unit/adapters/oidc/test-helper.js

- adds named-path adapter for resources that follow that pattern
- adds adapters for oidc resources with tests
- adds serializers for oidc resources
- fixes issue with supported_scopes relationship on oidc/provider model (stumbled upon this while running tests)
I added minimal serializers for now since it's tough to determine what else is needed until the forms and views are wired up. I wouldn't necessarily add tests for adapters unless there was some unique logic to them but since I added the `named-path` adapter I wanted to be sure that the requests were hitting the correct endpoints based on the docs.

OIDC Adapters and Serializers

---

builtin/logical/pki/backend_test.go
builtin/logical/pki/path_issue_sign.go
builtin/logical/pki/path_root.go
builtin/logical/pki/path_sign_issuers.go
changelog/16124.txt
website/content/api-docs/secret/pki.mdx

Both of these two signing requests lacked the `signature_bits` parameter, prohibiting callers from modifying the signature size on RSA key sizes. 
Notably, this parameter is present on root generation and role based signing. Since this parameter might change from request to request, I opted not to pull it out of the role and instead use the API-provided value.

Add signature_bits to sign-intermediate, sign-verbatim

---

changelog/16112.txt
vault/request_handling.go

Closes https://github.com/hashicorp/vault/issues/16102

Return a 403 for a bad SSCT instead of 500

---

website/content/api-docs/secret/kubernetes.mdx

This PR fixes a sample JSON payload for `generated_role_rules` in the k8s secrets API docs.

secrets/k8s: fix api docs for generated_role_rules json

---

changelog/16115.txt
http/util.go
vault/core.go
vault/logical_system_quotas.go
vault/quotas/quotas.go
vault/quotas/quotas_rate_limit.go
vault/quotas/quotas_rate_limit_test.go
vault/quotas/quotas_test.go

The subset of OSS changes required for role support for rate limit quotas.
PR best reviewed by the ent counterpart here: https://github.com/hashicorp/vault-enterprise/pull/2996

VAULT-6613 Add role support for rate limit quotas (OSS Changes)

---

changelog/16115.txt
http/util.go
vault/core.go
vault/external_tests/quotas/quotas_test.go
vault/logical_system_quotas.go
vault/quotas/quotas.go
vault/quotas/quotas_rate_limit.go
vault/quotas/quotas_rate_limit_test.go
vault/quotas/quotas_test.go

This should allow https://github.com/hashicorp/vault-enterprise/pull/2996 to meet the drift check.
THis function was a little confusing as it's only used in ent. I might move it to the ent files in a later PR.

VAULT-6613 Missed a part of OSS for rate limit role quotas

---

website/content/api-docs/secret/transit.mdx
website/content/docs/secrets/transit.mdx

The docs currently describe using an AES key for wrapping, but don't specify the key size

Specify the size of the ephemeral key for transit imports

---

builtin/logical/pki/path_manage_issuers.go
builtin/logical/pki/path_manage_keys.go

When users pass the path of the bundle to the API, rather than the
contents of the bundle (say, by omitting the `@` symbol on a Vault CLI
request), give a better error message indicating to the user what the
potential problem might be. While a larger bound for certificates was
given (75 bytes, likely 100 would be fine as well), a smaller bound had
to be chosen for keys as there's less standard DER encoding data around
them.

Return errors on short PEM bundles (keys, issuers)

---

ui/app/adapters/named-path.js

In order to prevent Ember Data from throwing an error if the backend does no return the name property in the response data, a findRecord override was added in the `NamedPathAdapter` to set the property with the id (name) supplied to the findRecord store method.

Named path adapter findRecord override

---

website/content/api-docs/secret/pki.mdx

---
This behavior isn't new and has existed for a while (even before the rotation changes). Since the dos were heavily restructured in 1.11, I'm going to avoid backporting this to 1.10 though.

Clarify LIST /certs doesn't include imports

---

builtin/logical/database/backend.go
builtin/logical/database/backend_test.go
builtin/logical/database/rotation_test.go
helper/metricsutil/gauge_process.go
helper/metricsutil/gauge_process_test.go
helper/metricsutil/wrapped_metrics.go

This is a replacement for #15923 that takes into account recent lock
cleanup.
I went ahead and added back in the hanging plugin test, which I meant to
add in #15944 but forgot.
I tested this by spinning up a statsd sink in the tests and verifying I
got a stream of metrics:
```
$ nc -u -l 8125 | grep backend
test.swenson-Q9Q0L72D39.secrets.database.backend.connections.count.pgx.5.:1.000000|g
test.swenson-Q9Q0L72D39.secrets.database.backend.connections.count.pgx.5.:0.000000|g
test.swenson-Q9Q0L72D39.secrets.database.backend.connections.count.pgx.5.:1.000000|g
test.swenson-Q9Q0L72D39.secrets.database.backend.connections.count.pgx.5.:0.000000|g
```

Add database plugin metrics around connections

---

changelog/16146.txt
go.mod
go.sum
vault/activity_log.go
vault/activity_log_test.go

JIRA: https://hashicorp.atlassian.net/browse/VAULT-6629
Related RFC: https://docs.google.com/document/d/1V4zNjTMGOcDtcI9P92BV-rJDzU09D_koXWBZZUFNW-k/edit
Approved ent PR: https://github.com/hashicorp/vault-enterprise/pull/2995
Create hyperloglog consisting of clientIDs for each month during precomputationQueryWorker

ActivityLog Implement HyperLogLog Store Functionality During Precomputation

---

builtin/logical/database/backend.go
builtin/logical/database/backend_test.go

And only call it once.
This fixes a panic that can happen when the plugin `Cleanup` is called
twice.

Synchronize access to database plugin gauge process close

---

builtin/logical/pki/path_tidy.go

When tidy is called without arguments, we kick off a tidy operation with
no targets. This results in nothing being done, though the user might
reasonably expect some results.
Throw a warning in this case, so the user knows not to expect anything.

Add warning on missing tidy targets

---

changelog/16170.txt
ui/app/services/auth.js
ui/tests/acceptance/oidc-auth-method-test.js
ui/tests/pages/auth.js

This PR removes remaining references to sessionStorage. Here's what happened:
1. We swapped localStorage in favor of sessionStorage in #14054 
2. OIDC bugfix in #14545 used sessionStorage because that's what was standard at the time
3. Team realized the move to sessionStorage was a mistake, and reverted 14054 in #15769 
4. Changes from 14545 are still present in 1.11 onward, and this PR is to fix that.

UI Remove recent instances of sessionStorage

---

changelog/16088.txt
vault/external_tests/identity/identity_test.go
vault/identity_store_util.go

Addresses https://hashicorp.atlassian.net/browse/VAULT-2282
Example of reading an identity/group from a standby node:
`{
"request_id": "4015c4c6-ee28-eec9-a42d-a0be91970dbc",
"lease_id": "",
"lease_duration": 0,
"renewable": false,
"data": {
"alias": {},
"creation_time": "2022-06-21T05:56:12.378602Z",
"id": "6a769520-f4b5-59a1-d7d7-21a650c91343",
"last_update_time": "2022-06-21T05:56:12.378602Z",
"member_entity_ids": null,
"member_group_ids": [
"66bcfa57-8aab-04c8-d9ed-263bb5d2e6b0",
"b7919faf-0a16-6acd-9e4d-82ac6db946bc"
],
"metadata": null,
"modify_index": 1,
"name": "testgroup3",
"namespace_id": "root",
"parent_group_ids": null,
"policies": [
"default"
],
"type": "internal"
},
"warnings": [
"Endpoint ignored these unrecognized parameters: [-format]"
]
}`
A group is marshalled and …

Replicate member_entity_ids and policies in identity/group across nodes identically

---

builtin/logical/pki/backend_test.go
builtin/logical/pki/ca_util.go
builtin/logical/pki/cert_util.go
builtin/logical/pki/chain_test.go
builtin/logical/pki/chain_util.go
builtin/logical/pki/config_util.go
builtin/logical/pki/crl_test.go
builtin/logical/pki/crl_util.go
builtin/logical/pki/key_util.go
builtin/logical/pki/path_config_ca.go
builtin/logical/pki/path_config_urls.go
builtin/logical/pki/path_fetch.go
builtin/logical/pki/path_fetch_issuers.go
builtin/logical/pki/path_fetch_keys.go
builtin/logical/pki/path_intermediate.go
builtin/logical/pki/path_issue_sign.go
builtin/logical/pki/path_manage_issuers.go
builtin/logical/pki/path_manage_keys.go
builtin/logical/pki/path_manage_keys_test.go
builtin/logical/pki/path_roles.go
builtin/logical/pki/path_root.go
builtin/logical/pki/storage.go
builtin/logical/pki/storage_migrations.go
builtin/logical/pki/storage_migrations_test.go
builtin/logical/pki/storage_test.go
builtin/logical/pki/util.go

This will allow us to refactor the storage functions to take additional
parameters (or backend-inferred values) in the future. In particular, as
we look towards adding a storage cache layer, we'll need to add this to
the backend, which is now accessible from all storage functions.
---
There has admittedly been a little bit of scope creep in order to make things consistent. But I believe at the top-level handler, we'll now fetch the new storage context struct once and pass that down the chain for use.

Refactor PKI storage calls to take a shared struct

---

changelog/16184.txt
vault/activity_log.go
vault/activity_log_test.go
vault/activity_log_util_common.go
vault/activity_log_util_common_test.go

Approved Ent PR: https://github.com/hashicorp/vault-enterprise/pull/2997/files#diff-1f4207e699cd95fe7169925fd5b032560c07a1e73005a085e661dac1064dbacf

Port: Use Stored Hll to Compute New Clients For Current Month

---

builtin/logical/pki/path_config_crl.go
builtin/logical/pki/path_config_urls.go
builtin/logical/pki/path_roles.go
builtin/logical/pki/path_roles_test.go
builtin/logical/pki/storage.go
builtin/logical/pki/storage_migrations.go

`structs` and `mapstructure` aren't really used within Vault much any more,
so we should start removing them. Luckily there was only one externally
accessible place where structs was used (AIA URLs config) so that was
easy to remove. The rest is mostly structure tag changes.
`path_roles_tests.go` relied on `mapstructure` in some places that broke,
but otherwise `backend_test.go` hasn't yet been modified to remove the
dependency on `mapstructure`. These didn't break as the underlying
CertBundle didn't get `mapstructure` support removed (as its in the SDK).

Remove structs, mapstructure from PKI storage

---

changelog/15835.txt
sdk/framework/backend.go
sdk/framework/openapi.go
sdk/framework/openapi_test.go
sdk/framework/path.go
vault/logical_system.go
vault/logical_system_paths.go
vault/logical_system_test.go
website/content/api-docs/system/internal-specs-openapi.mdx

This query parameter will be primarily for DevEx and code generation usage. The idea is to replace hard coded mount paths in the OpenApi spec with a dynamic parameter i.e. `{mountPath}`.
When the new call is made to `/sys/internal/specs/openapi?generic_paths=true` the resulting OpenApi spec will have 
`"paths": {
"/auth/{mountPath}/login/": {
"description": "",
"parameters": [
{
"name": "mountPath",
"description": "Path that the backend was mounted at",
"in": "path",
"schema": {
"type": "string"
},
"required": true
}
],`
The resulting generated code will allow users of the client library to pass through a mount path that would've otherwise been hardcoded as e.g. `approle`

Dynamic parameter for mountpaths

---

api/README.md
website/content/api-docs/libraries.mdx
website/content/docs/get-started/developer-qs.mdx

- Make the dev quick start link readily available on the client library documentation page
- Move the full code samples to the top of the dev quickstart page so that they're easily accessible.
- Update the api/readme to have a link to the dev quickstart

Developer Quickstart docs improvements

---

website/content/api-docs/secret/pki.mdx

See also: https://discuss.hashicorp.com/t/missing-pki-secret-engine-api-documentation-for-root-rotate-and-root-replace-endpoints/41215

Document PKI root rotation, replacement paths

---

website/content/docs/enterprise/fips/fips1402.mdx

This documents some additional restrictions around TLS cipher suites from Go's restriction sets (plus our more permissive P521/RSA support).

Document additional FIPS restrictions

---

website/content/docs/plugins/plugin-portal.mdx

repository: https://github.com/PaddyPowerBetfair/vault-plugin-hydrant-pki
raised issue: #16011
also updated docs (link to page for PR)

Adding Vault HydrantID Pki Plugin

---

website/content/docs/concepts/seal.mdx

This small chore/docs PR includes the following:
* Replaces a remaining "master key" occurrence
* Replaces a few occurrences of "AutoUnseal" with "Auto Unseal" to be more consistent
* Fixes a few minor typos
* Breaks down a few long lines to improve Markdown readability

Seal/Unseal docs: Improve readability, fix master key occurrence and typos

---

website/content/docs/platform/k8s/helm/configuration.mdx
website/content/docs/platform/k8s/helm/examples/ha-with-consul.mdx
website/content/docs/platform/k8s/helm/examples/standalone-tls.mdx
website/content/docs/platform/k8s/helm/run.mdx

Per [Asana](https://app.asana.com/0/563192436488770/1202424480411259/f) task, the following documentation have been amended to remove `extraVolumes` from the configuration examples since it's been deprecated and replaced with `Volumes`.
- Configuration: :mag: [Deploy Preview](https://vault-git-docs-update-k8s-examples-hashicorp.vercel.app/docs/platform/k8s/helm/configuration)
- HA Vault Cluster with Consul: :mag: [Deploy Preview](https://vault-git-docs-update-k8s-examples-hashicorp.vercel.app/docs/platform/k8s/helm/examples/ha-with-consul)
- Standalone Server with TLS: :mag: [Deploy Preview](https://vault-git-docs-update-k8s-examples-hashicorp.vercel.app/docs/platform/k8s/helm/examples/standalone-tls)
- Run Vault on Kubernetes: :mag: [Deploy …

vault documentation: updated examples to use volumes

---

website/content/docs/secrets/kmip.mdx

Per [Asana](https://app.asana.com/0/563192436488770/1202431086811911/f), a concepts paragraph was added to provide network guidance for KMIP.
:mag: [Deploy Preview](https://vault-git-docs-kmip-doc-update-hashicorp.vercel.app/docs/secrets/kmip)

Vault documentation: added content for network guidance for KMIP

---

website/content/docs/commands/index.mdx
website/content/docs/concepts/policies.mdx

Per [Asana](https://app.asana.com/0/563192436488770/1202488666098337/f), the following documents were updated to reference the new `-output-policy` flag. While I was in the files, I cleaned things up a bit.
- Policies :mag: [Deploy Preview](https://vault-git-docs-add-output-policy-flag-hashicorp.vercel.app/docs/concepts/policies#capabilities)
- Command (CLI) :mag: [Deploy Preview](https://vault-git-docs-add-output-policy-flag-hashicorp.vercel.app/docs/commands#print-policy-requirements)

Vault documentation: added info about new policy flag

---

builtin/logical/pki/backend_test.go
builtin/logical/pki/cert_util.go
builtin/logical/pki/path_roles.go
changelog/16246.txt
website/content/api-docs/secret/pki.mdx

This addresses issue #16237. 
When signing a CSR using /sign/<:role name> api method we validate that the CSR matches up with the role's `key_type` and `key_bits` values. If the `key_type` is set to `any`, these checks don't really make sense, and these checks were effectively bypassed when the `key_bits` value was set to current default value of 0.
The issue that was missed was the default value for created role's `key_bits` parameter was changed in 1.10 from 2048 to 0. So effectively the fix we previously made within [PR#14875](https://github.com/hashicorp/vault/pull/14875) addressed the issue, but only when the role was created in Vault 1.10 and higher. 
Now we bypass the validation for the role's `key_bits` value when signing CSRs if the `key_type` is set to `any`. We still validate …

pki: When a role sets key_type to any ignore key_bits value when signing a csr

---

website/content/api-docs/secret/kubernetes.mdx

This PR updates the API docs for the `kubernetes_host` field to reference the env var that's used in the code at [path_config.go#L18](https://github.com/hashicorp/vault-plugin-secrets-kubernetes/blob/main/path_config.go#L18).

secrets/k8s: updates API docs for kubernetes_host env var

---

vault/logical_system_test.go

Use `Core.logLevel` instead of the `LogLevel` from `GetCoreConfigInternal` in logger API tests as it is what is actually configured for the core.

remove GetCoreConfigInternal from logger API tests

---

builtin/logical/pki/backend_test.go
builtin/logical/pki/path_roles_test.go
builtin/logical/pki/test_helpers.go

- A lot of helper methods to write tests for PKI were created in the 1.11
branch timeframe, which we should backport to help reduce the friction
of new tests on main being backported to this branch.
- This only affects test code, and the existing test files that were touched
simply had their functions moved into test_helper.go

Backport pki test_helpers to reduce backport friction to 1.10

---

vault/request_handling.go

Regarding the changes here https://github.com/hashicorp/vault/pull/16112/files, I think we should throw the `RequestForwarding` error as well as the `MissingRequiredState` error, as in these cases we want the server to forward the request and throw a 412 respectively.

Throw SSCT Error In Some Cases

---

website/content/docs/configuration/storage/cockroachdb.mdx

HA support for CockroachDB was added in #12965. This commit updates the docs
to reflect that support.

docs/configuration: document CockroachDB HA mode

---

changelog/16274.txt
website/content/api-docs/auth/jwt.mdx
website/content/docs/auth/jwt/oidc-providers/index.mdx
website/content/docs/auth/jwt/oidc-providers/secureauth.mdx
website/data/docs-nav-data.json

This PR documents the SecureAuth OIDC provider configuration following the recent addition from hashicorp/vault-plugin-auth-jwt#196.

auth/oidc: Adds documentation for SecureAuth IdP

---

changelog/16218.txt
website/content/docs/enterprise/replication.mdx

The docs were unclear on this point, so @russparsloe and I looked into it.
Local mounts are indeed replicated to DR secondaries.
This is the opposite of what it says on https://developer.hashicorp.com/vault/tutorials/enterprise/performance-replication#disaster-recovery 
> Local backend mounts are not replicated and their use will require existing DR mechanisms if DR is necessary in your implementation.
So that page will also need updating
The following were all configured on a DR primary, then replicated over to a DR secondary. That DR secondary was then promoted to a primary.
```
$ vault audit list -detailed
Path     Type    Description    Replication    Options
----     ----    -----------    -----------    -------
file/    file    n/a            local          file_path=stdout
$ vault …
```

Clarification for local mounts in the context of DR

---

CHANGELOG.md

Updates the changelog to include the following entries:
* CVE-2022-30689 / [HSEC-2022-09](https://discuss.hashicorp.com/t/hcsec-2022-09-vault-pki-secrets-engine-policy-results-in-incorrect-wildcard-certificate-issuance/36600)
* CVE-2022-25244 / [HSEC-2022-08](https://discuss.hashicorp.com/t/hcsec-2022-08-vault-enterprise-s-tokenization-transform-configuration-endpoint-may-expose-transform-key/36599)

update changelog with recent advisories

---

website/content/api-docs/system/mfa/index.mdx

Per [Asana](https://app.asana.com/0/563192436488770/1202600007772275/f), the sys-mfa API doc now includes a new section called **Step-up Enterprise MFA** and attempts to distinguish the different API endpoints, as well as points out an endpoint that is only supported for Vault Enterprise.
:mag: [Deploy Preview](https://vault-git-docs-update-sys-mfa-hashicorp.vercel.app/api-docs/system/mfa)

Vault documentation: updated sys-mfa api doc

---

website/content/docs/concepts/policies.mdx

🎟️ [Asana](https://app.asana.com/0/563192436488770/1202315039171923/f)
🔍 [Deploy Preview](https://vault-git-docs-update-policy-example-hashicorp.vercel.app/docs/concepts/policies#fine-grained-control)
This PR was created based on the [Github issue](https://github.com/hashicorp/vault/issues/15508). Current policy example for `required_parameters`, `allowed_parameters`, and `denied_parameters` are for KV v1 and too vague. 
I updated the policy examples to be little more realistic.

Update the policy examples

---

website/content/api-docs/secret/consul.mdx

Accidentally put `consul_namespace` support in the Consul secrets engine under the Consul 1.8 area instead of Consul 1.7 to accurately reflect when it was added.

Fix docs consul feature version

---

changelog/16324.txt
helper/testhelpers/teststorage/teststorage.go
helper/testhelpers/teststorage/teststorage_reusable.go
vault/raft.go

raft: Ensure init before setting suffrage

Vault 6773/raft rejoin nonvoter

---

api/plugin_helpers.go
builtin/plugin/backend.go
builtin/plugin/backend_lazyLoad_test.go
changelog/15671.txt
sdk/helper/pluginutil/env.go
sdk/helper/pluginutil/multiplexing.go
sdk/helper/pluginutil/run_config.go
sdk/helper/pluginutil/run_config_test.go
sdk/helper/pluginutil/runner.go
sdk/helper/pluginutil/tls.go
sdk/plugin/backend.go
sdk/plugin/plugin.go
sdk/plugin/serve.go
vault/logical_system_integ_test.go
vault/plugin_catalog.go

Use go-plugin's AutoMTLS feature for secrets/auth plugins. This will require a version bump (v5) for the PluginSet that go-plugin can dispense.
This change is transparent to vault plugin developers. To take advantage of AutoMTLS, a vault operator must recompile their plugin.
Note that MetadataMode is _not_ used for plugin registration for plugins compiled with these changes.

AutoMTLS for secrets/auth plugins

---

api/plugin_helpers.go
builtin/plugin/backend.go
builtin/plugin/backend_lazyLoad_test.go
changelog/15671.txt
sdk/helper/pluginutil/env.go
sdk/helper/pluginutil/multiplexing.go
sdk/helper/pluginutil/run_config.go
sdk/helper/pluginutil/run_config_test.go
sdk/helper/pluginutil/runner.go
sdk/plugin/backend.go
sdk/plugin/plugin.go
sdk/plugin/serve.go
vault/logical_system_integ_test.go
vault/plugin_catalog.go

Manual backport of https://github.com/hashicorp/vault/pull/15671 into 1.11.x

Backport of AutoMTLS for secrets/auth plugins into release/1.11.x

---

website/content/docs/what-is-vault.mdx

The link for **contributing guide** should be pointing to the vault repo. 
🔍 [Deploy preview](https://vault-git-docs-update-community-links-hashicorp.vercel.app/docs/what-is-vault#community)

Fix the contribution guide link

---

website/content/docs/plugins/plugin-portal.mdx

This PR adds a few HashiCorp supported plugins to the plugin portal documentation.

docs/plugin-portal: adds missing HashiCorp supported plugins

---

website/content/api-docs/relatedtools.mdx

This PR adds [HashiBox](https://github.com/nunchistudio/hashibox) to the community tools.
HashiBox is a local environment to simulate a highly-available cloud with [Consul](https://www.consul.io/), [Nomad](https://www.nomadproject.io/), and [Vault](https://www.vaultproject.io/). OSS and Enterprise versions of each product are supported.

Add HashiBox to community tools

---

api/plugin_helpers.go
builtin/plugin/backend.go
builtin/plugin/backend_lazyLoad_test.go
changelog/15671.txt
sdk/helper/pluginutil/env.go
sdk/helper/pluginutil/multiplexing.go
sdk/helper/pluginutil/run_config.go
sdk/helper/pluginutil/run_config_test.go
sdk/helper/pluginutil/runner.go
sdk/plugin/backend.go
sdk/plugin/plugin.go
sdk/plugin/serve.go
vault/logical_system_integ_test.go
vault/plugin_catalog.go

This reverts commit b443be6491ba40bb45c9e08d5b52dd8ead3e1e73.
The original commit caused the PKI plugin to fail:
```
$ vault secrets enable pki
$ vault write -format=json pki/root/generate/internal \
common_name=example.com \
ttl=8760h
...
* Can not create root CA until migration has completed
```

Revert "Backport of AutoMTLS for secrets/auth plugins into release/1.11.x (#16343)"

---

builtin/credential/approle/path_login.go
builtin/credential/approle/path_login_test.go
builtin/credential/cert/path_login.go
builtin/credential/cert/path_login_test.go

This PR does the following:
- Adds additional check to approle resolution to be consistent with other auth plugin behaviour
- Correct cert role resolution to be accurate to what the actual role is
- Add additional tests to cert and approle resolution
Note that no changelog is really added here as it's not a feature unto itself. There are already changelogs for the role resolution feature.

VAULT-6727 Adjust cert and approle role resolution, add more tests

---

Makefile
changelog/16353.txt
go.mod
go.sum
make.bat
scripts/build.sh
scripts/cross/Dockerfile
scripts/docker/Dockerfile
scripts/docker/Dockerfile.ui
scripts/windows/build.bat
tools/tools.go

`gox` hasn't had a release to update it in many years, so is missing
support for many modern systems, like `darwin/arm64`.
In any case, we only use it for dev builds, where we don't even use
the ability of it to build for multiple platforms. Release builds use
`go build` now.
So, this switches to `go build` everywhere.
I pulled this down and tested it in Windows as well. (Side note: I
couldn't get `gox` to work in Windows, so couldn't build before this
change.)

Remove gox in favor of go build.

---

ui/tests/acceptance/enterprise-replication-test.js

Small failure that was caused by a dynamic selector change on a glimmerization of a component. See PR [here](https://github.com/hashicorp/vault/pull/16032).
Good reminder that it's best to run enterprise test locally on PRs that might in any way touch an enterprise area of the application. I'll try to do a better job as PR reviewer to ask this of folks.
Note: yep, I ran the enterprise test locally and they all passed with this change.

Fix replication test failure

---

changelog/16327.txt
vault/cluster/cluster.go

By default `http2.Server` allows for 250 concurrent streams per host. This limit can cause bottlenecks on clusters with many forwarded requests/rpcs. This changes the default to match what the gRPC library uses: `MaxUint32`.

Increase the allowed concurrent gRPC streams

---

website/content/docs/platform/k8s/helm/configuration.mdx

It's very confusing, `Volumes` are very similar to `volumes` and can cause confusion 😄

Fix typo in the docs

---

builtin/logical/pki/path_manage_issuers.go
builtin/logical/pki/path_root.go

This tells the user that the next step should be to configure AIA URLs
on this newly imported issuer/mount point. Ideally this should occur
before any leaves are issued such that they have the correct
information.

Add next-step warning on import without AIA URLs

---

changelog/16274.txt

This PR fixes a changelog entry for SecureAuth groups parsing. It's not really a feature and wasn't in the specific feature format.
Prompted by https://github.com/hashicorp/vault/pull/16274#discussion_r926028248.

auth/oidc: fix changelog entry for SecureAuth groups parsing

---

website/content/api-docs/system/remount.mdx

Fix typo in remount (#16100)

---

website/content/api-docs/auth/jwt.mdx

This PR documents the optional `client_nonce` parameter in the OIDC auth method [`auth_url`](https://www.vaultproject.io/api-docs/auth/jwt#oidc-authorization-url-request) and [`callback`](https://www.vaultproject.io/api-docs/auth/jwt#oidc-callback) APIs.
Resolves: https://github.com/hashicorp/vault/issues/14188

auth/oidc: documents the client_nonce parameter

---

vault/identity_store.go
vault/request_handling.go
vault/request_handling_util.go

OSS changes from https://github.com/hashicorp/vault-enterprise/pull/2954
Added a no-op version of updateLocalAlias to request_handling_util.go

[VAULT-6622] oss changes 

---

changelog/16386.txt
vault/quotas/quotas.go
vault/quotas/quotas_test.go

This is the set of OSS changes. To see the full range of tests added, see the Ent PR here: https://github.com/hashicorp/vault-enterprise/pull/3066

VAULT-7046 Allow trailing globbing at the end of a path suffix quota

---

website/content/docs/platform/k8s/helm/examples/standalone-tls.mdx

I've gotten a few tickets regarding the Standalone TLS Helm Chart example not working for customers running EKS.  This is because in version `1.22` and higher you need to use the `signerName: beta.eks.amazonaws.com/app-serving`.  I put an "Important Note" on this tutorial highlighting this to hopefully help prevent customers getting this issue.
Below is how the note renders on the site.
---

Add an "Important Note" regarding EKS CSR approval.

---

changelog/16409.txt
command/audit_enable.go
command/audit_enable_test.go

Just a small improvement to the returned error message if you don't include the audit device type:
```bash
[~] vault audit enable
Missing TYPE!
```
The new error message looks like this:
```
[~] vault audit enable
Error enabling audit device: audit type missing. Valid types include 'file', 'socket' and 'syslog'.
```

command/audit: improve audit enable type missing error message

---

.circleci/config.yml
.circleci/config/commands/setup-semgrep.yml

Update to the latest version of [semgrep](https://semgrep.dev/) 0.106.0. 
New dependencies (ujson) are being pulled that now require the environment to have gcc/g++ and python3-dev. Part of me wonders if we should instead switch this to using the upstream docker image: https://hub.docker.com/r/returntocorp/semgrep

update semgrep to 0.106.0

---

changelog/16421.txt
command/server.go
command/server/config.go
command/server/tls_util.go
website/content/docs/commands/server.mdx

This adds new server subcommands, `-dev-tls` and `-dev-tls-cert-dir`, which will generate self-signed CA, server certificate, private key and will configure Vault to use them for TLS. This is helpful if you want to do dev work against a TLS enabled server. The generated certs are valid for 1 year.
During startup, the server will output the location of the CA so you can easily set the `VAULT_CACERT` environment variable:
```bash
[~/vault] vault server -dev-tls
==> Vault server configuration:
...
WARNING! dev mode is enabled! In this mode, Vault runs entirely in-memory
and starts unsealed with a single unseal key. The root token is already
authenticated to the CLI, so you can immediately begin using Vault.
You may need to set the following environment variable:
$ export …
```

command/server: add dev-tls flag

---

vault/acl.go
vault/acl_test.go
vault/policy.go

Fixing a few small issues I noticed while looking into policy parameter constraints:
- `nil` was passed to context in tests; replaced it with `context.Background()`
- `t.Fatal` was being used inside of internal go-routines, which would not fail the test; changed the test to push errors into a channel and check them at the end
- use `copy` and `append` instead of loops to copy/append slices

Fix linter issues in policy.go & acl.go

---

changelog/16435.txt
go.mod
go.sum

Manual test steps documented below for the new feature. A GCE instance group was created in the us-east1 region with 1 running instance for the test. Then the same steps were performed on a us-central1 instance to demonstrate failure.
Setup steps:
```
vault policy write gce-reader gce-reader.hcl
vault kv put secret/gcp-info/key name="secret" value="abc"
vault auth enable gcp
vault write auth/gcp/config \
credentials=@credentials.json
vault write auth/gcp/role/reader \
type="gce" \
policies="gce-reader" \
bound_regions="us-east1" \
bound_instance_groups="my-region-group" \
```
New session steps:
```
vault login \
-method=gcp \
role=reader
vault kv get secret/gcp-info/key
```
Success output:
```
robmonte@my-region-group-pdfb:~$ vault login -method=gcp role=reader
Success! You are now …
```

Update GCP auth to add support for regional instance groups

---

changelog/16379.txt
command/operator_init.go
command/operator_init_test.go
http/sys_init.go
http/sys_init_test.go

https://hashicorp.atlassian.net/browse/VAULT-951
The "vault operator" command should not operate if there are unused command-line flags, for example:
vault operator init --recovery-threshold=1 --recovery-shares=1
should return an error because auto unseal is not being used (the correct flags are -key-shares and -key threshold.)

Validate parameters for vault operator init  

---

website/content/docs/platform/k8s/injector/index.mdx

I expect we can add more rows to the table as we release more versions in future. Maybe limit it to a maximum of 3 or 5 vault-k8s versions or something?
Pairs with https://github.com/hashicorp/vault-k8s/pull/372.

Docs: Add table documenting compatible k8s versions for agent injector

---

ui/app/routes/vault/cluster/access/oidc/keys/index.js
ui/app/templates/vault/cluster/access/oidc/keys/index.hbs

Added list view for keys. There is always a default key which cannot be deleted but can be edited so there is no empty state for the list view. Since this default key cannot be deleted but only edited, the deleted button will be greyed out in the details view with a tooltip note instead.

Added list view for keys

---

ui/app/routes/vault/cluster/access/oidc/clients/index.js
ui/app/templates/vault/cluster/access/oidc/clients/index.hbs

There is always an item on the application list view since an application always has to be created first. Note that the client ID still needs to be added below the names (to be done when LIST API is included to contain that info).

Added list view for application

---

changelog/16140.txt

This PR adds a changelog entry for the fix that's addressed by the plugin version bump in #16140.

changelog: Add entry for AD secrets engine bug fix

---

ui/app/routes/vault/cluster/access/oidc/assignments/index.js
ui/app/styles/components/list-item-row.scss
ui/app/templates/vault/cluster/access/oidc/assignments/index.hbs

There is always a returned item on the assignment list view. It always returns allow_all. This is how that is handled as you cannot modify this assignment.
Here's what it looks like with other assignments.
Because this is a route, the testing will be added to an acceptance test. Waiting for Claire to return to discuss how she'd like to approach route testing. So far, we've only established component testing.

Assignment list view

---

sdk/helper/custommetadata/custom_metadata.go
sdk/helper/custommetadata/custom_metadata_test.go
vault/identity_store_aliases.go

Custom metadata is a concept that has been included in multiple features including KVv2 metadata and identity aliases. Issue #16217 outlines an enhancement request to include it for namespace entries. Including it within storage entries is generally straightforward and it likely makes sense to impose the same limits across all of Vault to ensure a consistent UX. This PR moves the constants and validation logic from the identity alias logic (which was initially lifted from KVv2 metadata) into its own package so that it can be used in a consistent way across Vault.

move custom metadata validation logic to its own package

---

changelog/16181.txt
http/logical.go
vault/identity_store_oidc_provider.go
vault/identity_store_oidc_provider_test.go
website/content/api-docs/secret/identity/oidc-provider.mdx

This PR allows filtering the [list providers](https://www.vaultproject.io/api-docs/secret/identity/oidc-provider#list-providers) response by an `allowed_client_id` value. The list of providers returned will be those that allow the given client ID in their [`allowed_client_ids`](https://www.vaultproject.io/api-docs/secret/identity/oidc-provider#allowed_client_ids) field. This is useful for a UI workflow where suggesting an issuer to use along with client application creation.
Example:
```sh
$ curl -H "X-Vault-Token: ..." -X LIST http://127.0.0.1:8200/v1/identity/oidc/provider?allowed_client_id="<client_id>"
```
I've added tests to this PR which exercise the list filtering capability.

identity/oidc: allow filtering the list providers response by an allowed_client_id

---

changelog/16443.txt
command/kv_get.go
command/kv_test.go

Handling of leading slashes was not consistent in the `vault kv get` command. This can be fixed by simply ignoring the leading slash of the requested path. The following will all successfully fetch a secret at path `secret/foo`:
```
vault kv get /secret/foo
vault kv get secret/foo
vault kv get -mount=secret /foo
vault kv get -mount=secret foo
```
Fixes https://github.com/hashicorp/vault/issues/16238

ignore leading slash in kv get command

---

changelog/16489.txt
ui/app/templates/components/tool-lookup.hbs
ui/app/templates/components/tool-rewrap.hbs
ui/app/templates/components/tool-unwrap.hbs
ui/app/templates/components/tool-wrap.hbs
ui/app/templates/components/wizard/tools-unwrapped.hbs

Renamed label of `wrapping token` to `wrapped token` under Tools for Lookup, Unwrap and Rewrap. Added descriptions for them as well. Changed label under Wrap as well. Note that if an error is thrown, it still says `wrapping token` since that error message comes from the backend

Lookup, wrap, rewrap and unwrap token rename with description

---

api/client.go
changelog/16479.txt
command/agent.go
command/agent/config/config.go
command/agent/config/config_test.go
command/agent/config/test-fixtures/bad-config-disable-keep-alives.hcl
command/agent/config/test-fixtures/config-disable-keep-alives-all.hcl
command/agent/config/test-fixtures/config-disable-keep-alives-auto-auth.hcl
command/agent/config/test-fixtures/config-disable-keep-alives-caching.hcl
command/agent/config/test-fixtures/config-disable-keep-alives-empty.hcl
command/agent/config/test-fixtures/config-disable-keep-alives-templating.hcl
command/agent/template/template.go
website/content/docs/agent/index.mdx

Follow up for https://github.com/hashicorp/vault/pull/15986.
This PR adds a new configurable, `disable_keep_alives`, which takes a string list to disable keep alives for various features in Vault Agent (`auto-auth`, `caching` and `templating`).
A small example can be found here:
```hcl
"auto_auth" = {
"method" = {
"config" = {
"role" = "app"
}
"type" = "kubernetes"
}
"sink" = {
"config" = {
"path" = "/home/vault/.token"
}
"type" = "file"
}
}
"disable_idle_connections" = ["auto-auth", "caching", "templating"]
"disable_keep_alives" = ["auto-auth", "caching", "templating"]
"exit_after_auth" = false
"pid_file" = "/home/vault/.pid"
"template" = {
"contents" = "{{ with secret \"secret/hashiconf\" }}{{ .Data | toJSONPretty }}{{ end }}"
"destination" = "/vault/secrets/kv-secret" …
```

agent: add disable_keep_alives configurable

---

builtin/logical/ssh/backend_test.go
builtin/logical/ssh/path_issue_sign.go
builtin/logical/ssh/path_roles.go
changelog/16351.txt
website/content/api-docs/secret/ssh.mdx

Fixes #16350 by enabling Identity attribute templating support for the `default_user` field on the SSH backend roles

Allow identity templates in ssh backend `default_user` field

---

helper/namespace/namespace.go
sdk/helper/custommetadata/custom_metadata.go
sdk/helper/custommetadata/custom_metadata_test.go

A [prior PR](https://github.com/hashicorp/vault/pull/16464) abstracted the concept of custom metadata into its own helper package. That initial abstraction included a type which ultimately does not play nicely with the `framework.FieldData` logic. We could use a type alias instead of a strict type but that seems to just add cognitive overhead with not much gain. With that said, this PR removes the `CustomMetadata` type in favor of using `map[string]string` which the `Validate` function uses. The type also did not provide much gain in terms of consistency because API paths would need to be defined to use `framework.TypeKVPairs` which maps to a `map[string]string`.
Along with that, this PR prepares for the addition of custom metadata to namespaces by adding the associated field to the …

VAULT-7256 - Add CustomMetadata to Namespace type

---

builtin/logical/ssh/path_issue_sign.go

A small tweak to restore the returned errors as we previously did from a refactor that occurred in #16351.

secret/ssh: Return errors for bad templates in roles as we did previously

---

vault/identity_store_oidc_provider_test.go

so that the default provider will show up in the test storage response

oidc provider: use identity store's storage view in test

---

changelog/16524.txt
go.mod
go.sum

This PR updates vault-plugin-auth-gcp to [v0.12.2](https://github.com/hashicorp/vault-plugin-auth-gcp/releases/tag/v0.12.2) to bring in a bug fix from https://github.com/hashicorp/vault-plugin-auth-gcp/pull/132.
Steps:
```
go get -d github.com/hashicorp/vault-plugin-auth-gcp@v0.12.2
go mod tidy
```

auth/gcp: updates plugin to v0.12.2

---

changelog/16525.txt
go.mod
go.sum

This PR updates the vault-plugin-auth-jwt dependency to the latest pseudo-version from its main branch. 
Changelog entries are added for the following 1.12 improvements to the plugin:
- https://github.com/hashicorp/vault-plugin-auth-jwt/pull/211
- https://github.com/hashicorp/vault-plugin-auth-jwt/pull/209

auth/jwt: updates dependency and adds changelogs

---

changelog/16523.txt
go.mod
go.sum

This PR updates vault-plugin-auth-gcp to [v0.13.2](https://github.com/hashicorp/vault-plugin-auth-gcp/releases/tag/v0.13.2) to bring in a bug fix from https://github.com/hashicorp/vault-plugin-auth-gcp/pull/132.
Note that [v0.13.1](https://github.com/hashicorp/vault-plugin-auth-gcp/releases/tag/v0.13.1) is skipped because it was improperly released outside of our team.
Steps:
```
go get -d github.com/hashicorp/vault-plugin-auth-gcp@v0.13.2
go mod tidy
```

auth/gcp: updates plugin to v0.13.2

---

builtin/logical/pki/backend_test.go
builtin/logical/pki/ca_test.go
builtin/logical/pki/cert_util_test.go
builtin/logical/pki/chain_test.go
builtin/logical/pki/integation_test.go
builtin/logical/pki/path_manage_keys_test.go
builtin/logical/pki/path_roles_test.go
builtin/logical/pki/storage_migrations_test.go
builtin/logical/pki/storage_test.go

This decreases the total time to run the test suite significantly. From
[the last PR](#15999), we were at 151s:
> [cipherboy@xps15 pki]$ go test -count=1 github.com/hashicorp/vault/builtin/logical/pki
> ok    github.com/hashicorp/vault/builtin/logical/pki  151.182s
Now we're around 60s:
> [cipherboy@xps15 pki]$ go test -count=1 github.com/hashicorp/vault/builtin/logical/pki
> ok    github.com/hashicorp/vault/builtin/logical/pki  61.838s
Notably, Go will [correctly handle parallelizing tests](https://engineering.mercari.com/en/blog/entry/20220408-how_to_use_t_parallel/) across both
packages and within a package, so this shouldn't really impact test
runners (if they're already saturated).
The [only gotcha in this approach](https://gist.github.com/posener/92a55c4cd441fc5e5e85f27bca008721) is …

Make PKI tests run in parallel

---

changelog/16526.txt
go.mod
go.sum

This PR updates vault-plugin-database-elasticsearch to [v0.11.1](https://github.com/hashicorp/vault-plugin-database-elasticsearch/releases/tag/v0.11.1) to bring in a bug fix from https://github.com/hashicorp/vault-plugin-database-elasticsearch/pull/38
Steps:
```
go get -d github.com/hashicorp/vault-plugin-database-elasticsearch@v0.11.1
go mod tidy
```

db/elasticsearch: update plugin to v0.11.1

---

.github/workflows/changelog-checker.yml

- Bringing back @mladlow's work that was done in ENT to OSS updating our filename checks for Go version bumps in the changelog checker

Update Go version changelog checker to indicate underscore is required

---

go.mod
go.sum

This PR updates vault-plugin-secrets-gcp to [v0.12.1](https://github.com/hashicorp/vault-plugin-secrets-gcp/releases/tag/v0.12.1) to bring in a bug fix from https://github.com/hashicorp/vault-plugin-secrets-gcp/pull/144.
Steps:
```
go get -d github.com/hashicorp/vault-plugin-secrets-gcp@v0.12.1
go mod tidy
```

secrets/gcp: updates plugin to v0.12.1

---

go.mod
go.sum

This PR updates vault-plugin-secrets-gcp to [v0.13.1](https://github.com/hashicorp/vault-plugin-secrets-gcp/releases/tag/v0.13.1) to bring in a bug fix from https://github.com/hashicorp/vault-plugin-secrets-gcp/pull/144.
Steps:
```
go get -d github.com/hashicorp/vault-plugin-secrets-gcp@v0.13.1
go mod tidy
```

secrets/gcp: updates plugin to v0.13.1

---

changelog/16534.txt

This PR adds a changelog entry for the GCP secrets bug fixes in:
- https://github.com/hashicorp/vault/pull/16532
- https://github.com/hashicorp/vault/pull/16533

secrets/gcp: adds changelog entry for bug fixes in release branches

---

website/content/docs/upgrading/index.mdx
website/content/docs/upgrading/upgrade-to-1.11.x.mdx

Move the note about Integrated Storage automated upgrade note from the [Vault 1.11 Upgrade guide](https://www.vaultproject.io/docs/upgrading/upgrade-to-1.11.x) to the [top-level](https://www.vaultproject.io/docs/upgrading) (requested by Aarti Iyengar). 
🔍 [Deploy Preview](https://vault-git-docs-edit-upgrade-guide-hashicorp.vercel.app/docs/upgrading)

Move the IS Autopilot note from 1.11 upgrade guide

---

builtin/logical/pki/backend_test.go
builtin/logical/pki/cert_util.go
builtin/logical/pki/chain_test.go
builtin/logical/pki/path_sign_issuers.go
changelog/16494.txt
sdk/helper/certutil/helpers.go
sdk/helper/certutil/types.go
website/content/api-docs/secret/pki.mdx

In Vault 1.11, we introduced cross-signing support, but the earlier SKID
field change in Vault 1.10 causes problems: notably, certs created on
older versions of Vault (<=1.9) or outside of Vault (with a different
SKID method) cannot be cross-signed and validated in OpenSSL.
In particular, OpenSSL appears to be unique in requiring a SKID/AKID
match for chain building. If AKID and SKID are present on an otherwise
valid client/parent cert pair and the values are different, OpenSSL will
not build a valid path over those two, whereas most other chain
validation implementations will.
Regardless, to have proper cross-signing support, we really aught to
support copying an SKID. This adds such support to the sign-intermediate
endpoint. Support for the /issue endpoint is not added, as cross-signing …

Allow old certs to be cross-signed

---

website/content/docs/concepts/client-count/faq.mdx

(Reported by @buenospot)
This fixes two typos on https://www.vaultproject.io/docs/concepts/client-count/faq#q-what-does-the-usage-metrics-look-like-for-vault-1-10
```diff
- Vault 1.19
+ Vault 1.9
- montly
+ monthly
```

fix(docs): typos

---

builtin/logical/pki/backend_test.go
builtin/logical/pki/ca_util.go
builtin/logical/pki/cert_util.go
builtin/logical/pki/crl_test.go
builtin/logical/pki/crl_util.go
builtin/logical/pki/fields.go
builtin/logical/pki/path_fetch_issuers.go
builtin/logical/pki/path_intermediate.go
builtin/logical/pki/path_issue_sign.go
builtin/logical/pki/path_manage_issuers.go
builtin/logical/pki/path_roles.go
builtin/logical/pki/path_root.go
builtin/logical/pki/path_sign_issuers.go
builtin/logical/pki/storage.go
builtin/logical/pki/test_helpers.go
changelog/16519.txt
sdk/helper/certutil/helpers.go
sdk/helper/certutil/types.go
website/content/api-docs/secret/pki.mdx

Noting that NIST is deprecating PKCS#1v1.5 signatures here at the end of December 2023, we've gone ahead and added PSS support for RSA-typed issuers in the PKI Secrets Mount. 
This introduces two changes:
- `use_pss` on roles and signing endpoints (such as `/sign-verbatim` &c) -- this allows us to create self-signed roots & intermediates using the PSS algorithm.
- Setting a `revocation_signature_algorithm` on the Issuer, allowing us to choose override the default signature on CRLs &c.
This should let us work with PSS-only keys in the future (from say, a HSM) in Vault Enterprise within the PKI mount.

Add PSS support to PKI Secrets Engine

---

builtin/logical/consul/backend_test.go
helper/testhelpers/consul/consulhelper.go

Currently the token was always being added, when the ACL bootstrap test should not add it.

Update Consul bootstrap test case to conditionally add token to config

---

changelog/16565.txt
vault/core.go
vault/raft.go

This fixes some racy behavior discovered in parallel testing. Change the
core struct member to an atomic and update references throughout.

storage/raft: Make raftInfo atomic

---

changelog/16550.txt
helper/testhelpers/testhelpers.go
vault/external_tests/raft/raft_test.go
vault/external_tests/raftha/raft_ha_test.go
vault/raft.go

This PR addresses a bug found in https://github.com/hashicorp/vault/issues/16486
The `retry_join` loop in `JoinRaftCluster` continues to execute if a call to `join()` returns with an error.
Commit introduced a change which removes an erroneous error wrapper, but did not
handle the case where a join was in progress and err == nil. This ends the
`retry_join` loop and prevents a node from waiting to join.
Fix this by handling the `nil` channel response and returning an
error, allowing the `retry_join` to continue.

Vault 7338/fix retry join

---

ui/app/components/auth-form.js
ui/app/services/auth.js
ui/app/templates/vault/cluster/auth.hbs

Fixed 403 error on Vault Enterprise, fixed issue where namespace is undefined and bug where when Okta selected in 'Other' tab, it doesn't work. 
Changed the `auth.hbs` to not check if the `authMethod` is Okta because I noticed that if the user logs out from originally signing in with a token and we switch to the okta tab, the authMethod value isn't `okta/`

UI/vault 7312/fix vault enterprise error for okta number challenge

---

changelog/16567.txt
vault/identity_store_oidc_provider.go
vault/identity_store_oidc_provider_test.go
website/content/api-docs/secret/identity/oidc-provider.mdx

This PR adds detailed listing capability for OIDC clients and providers by introducing the `detailed` query parameter. The motivation for this is to improve the user experience in the Vault UI.
Example of detailed client list:
```sh
$ vault list -detailed identity/oidc/client
Keys      access_token_ttl    assignments    client_id                           client_type     id_token_ttl    key        redirect_uris
----      ----------------    -----------    ---------                           -----------     ------------    ---        -------------
my-app    24h                 [allow_all]    wGr981oYLJbcr4zrUriYxjxSc80JL7HW    confidential    24h             default    [http://localhost:5555/callback]
```
Example of detailed provider list:
```sh
$ vault list -detailed …
```

identity/oidc: adds detailed listing capability for clients and providers

---

website/content/docs/auth/jwt/oidc-providers/index.mdx

Okta was pointing at /docs/auth/jwt/oidc-providers/kubernetes.  Updated to point at /docs/auth/jwt/oidc-providers/okta

Fix Link: OIDC Provider Config - Okta

---

changelog/16609.txt
go.mod
go.sum

1.3.10 Release: https://github.com/hashicorp/raft/releases
Draft PR to run ent tests: https://github.com/hashicorp/vault-enterprise/pull/3105

upgrade raft to 1.3.10

---

changelog/16599.txt
vault/identity_store_oidc_provider.go
vault/identity_store_oidc_provider_test.go
website/content/api-docs/secret/identity/oidc-provider.mdx
website/content/docs/concepts/oidc-provider.mdx

This PR makes the `state` parameter optional per [3.1.2.1. Authentication Request](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest).
Fixes: https://github.com/hashicorp/vault/issues/14194

identity/oidc: change the state parameter to optional

---

changelog/16600.txt
ui/app/controllers/vault/cluster/oidc-provider.js
vault/identity_store_oidc_provider.go
vault/identity_store_oidc_provider_test.go
website/content/api-docs/secret/identity/oidc-provider.mdx
website/content/docs/secrets/identity/oidc-provider.mdx

This PR fixes required validation already present in [identity_store_oidc_provider.go#L1684-L1693](https://github.com/hashicorp/vault/blob/main/vault/identity_store_oidc_provider.go#L1684-L1693) which wasn't being passed to the server by UI code. It also adds the `request_parameter_supported` field to the OIDC discovery document per [6.1. Passing a Request Object by Value](https://openid.net/specs/openid-connect-core-1_0.html#RequestObject).

identity/oidc: fixes validation of the request and request_uri parameters

---

changelog/16598.txt
vault/identity_store_oidc_provider.go
vault/identity_store_oidc_provider_test.go
website/content/api-docs/secret/identity/oidc-provider.mdx
website/content/docs/concepts/oidc-provider.mdx
website/content/docs/secrets/identity/oidc-provider.mdx

This PR adds the `client_secret_post` token authentication method per [9. Client Authentication
](https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication)

identity/oidc: adds client_secret_post token endpoint authentication method

---

.release/ci.hcl

This PR introduces a new CRT workflow event in the ci.hcl file, `post-publish-website` and this event handles the dispatching of an API call (HTTP POST) to the mktg-dev endpoint. This is responsible for automating the triggering of marketing-dev's versioned docs pipeline to release versioned docs for product repos. 
This only gets triggered as a post-publish event after you release your artifacts to production. The workflow should wait for the docs to be published and report passed/failed status.
This should not be merged into ENT repos as the versioned docs only live in OSS repos. (if you have an automated OSS-->ENT merge set up, please let me know to follow up with a PR to remove this event out of the ENT repo)  
I will merge this PR in next Monday (07/25) (this is after your Wednesday …

introduces the post publish website event

---

changelog/16601.txt
vault/identity_store_oidc_provider.go

This PR reorders validation in the Authorization Endpoint in order to detect invalid `redirect_uri` values sooner. This is important because an invalid `redirect_uri` must not result in the user agent redirecting to the relying party per [3.1.2.6. Authentication Error Response](https://openid.net/specs/openid-connect-core-1_0.html#AuthError).

identity/oidc: reorder authorization endpoint validation for invalid redirect uris

---

builtin/logical/pki/path_roles.go

This option is known to cause problems with large numbers of issued
certificates. Ensure admins are warned about the impact of this field
and encourage them to disable it.

Add warning when generate_lease=true on PKI roles

---

changelog/16631.txt
plugins/database/hana/hana.go
plugins/database/hana/hana_test.go
website/content/api-docs/secret/databases/hanadb.mdx
website/content/docs/secrets/databases/index.mdx

Adds the ability to customize username generation for dynamic users in HanaDB.
Uses the new field username_template with the [go template language](https://golang.org/pkg/text/template/).

Hana - Add username customization 

---

website/content/api-docs/secret/identity/oidc-provider.mdx

This PR makes minor fixes the OIDC provider API documentation including:
- Stating that the `client_type` cannot be modified after creation
- Using UUIDs in the examples for creating and reading an assignment

identity/oidc: minor fixes to the API documentation

---

command/commands.go
command/namespace.go
command/namespace_create.go
command/namespace_patch.go
helper/namespace/namespace.go
sdk/helper/custommetadata/custom_metadata.go

Issue https://github.com/hashicorp/vault/issues/16217 describes the request to enhance namespaces with the addition of `custom_metadata`. This PR introduces the necessary changes to both the API and CLI to allow for both writing and reading custom metadata.
This PR includes the following changes:
- Add `mapstructure` tags to `Namespace` for struct->map decoding
- Add a `Parse` function to custom metadata helper which is largely taken from [parseCustomMetadata](https://github.com/hashicorp/vault-plugin-secrets-kv/blob/main/path_metadata.go#L227) in KVv2.
- Add `-custom-metadata` flag to the `vault namespace create` command
- Add a `vault namespace patch command` which allows users to patch an existing namespace's custom metadata
The changelog entry has been provided in a separate ENT PR. …

VAULT-7256: Add custom_metadata to namespaces

---

website/content/docs/enterprise/license/faq.mdx

Update the license FAQ docs page to account for license expiration/termination changes that will be included in Vault 1.12.

update license FAQ docs with termination changes

---

website/content/docs/upgrading/index.mdx

I added a new "important" section below "HA Installations" and re-worded the first paragraph a little bit. The result looks like this:

Clarify upgrades post 1.11

---

website/content/docs/internals/architecture.mdx

Changed the reference 'unauthorized attacker' to say 'malicious attacker' instead; unauthorized attacker is an oxymoron.
:mag: [Deploy Preview](https://vault-git-docs-update-architecture-page-hashicorp.vercel.app/docs/internals/architecture)

Vault documentation: updated architecture page 

---

website/content/docs/internals/architecture.mdx

Manually cherry-picking since the backport [PR](https://github.com/hashicorp/vault/pull/16657) failed.

Backports 16655 into release/1.11.x

---

website/content/api-docs/secret/identity/entity.mdx

Sister PR to https://github.com/hashicorp/vault/pull/16539 - context about this particular change can be found there.
In short, just documentation about the new behaviour for entity merging in the case of alias clash.

VAULT-6818 Docs for entity merge functionality

---

.github/workflows/oss.yml

If we don't guard against pull_request being null, we do a lot of extra
checkout and path filtering, and it ends up putting everything in the UI
board.
I tested this in another repo, and it seems to behave correctly.

Update OSS workflow so not all issues get put in the UI board

---

website/content/docs/platform/k8s/csi/configurations.mdx

Closes https://github.com/hashicorp/vault-csi-provider/issues/167
These config options were added in [1.1.0](https://github.com/hashicorp/vault-csi-provider/blob/main/CHANGELOG.md#110-april-26th-2022) but never added to the docs site.

Docs: Update Vault CSI Provider SecretProviderClass config options

---

ui/app/components/oidc/provider-form.js
ui/app/components/regex-validator.hbs
ui/app/controllers/vault/cluster/access/oidc/providers/provider.js
ui/app/models/database/connection.js
ui/app/models/oidc/provider.js
ui/app/routes/vault/cluster/access/oidc/providers/create.js
ui/app/routes/vault/cluster/access/oidc/providers/provider.js
ui/app/templates/components/clients/config.hbs
ui/app/templates/components/oidc/provider-form.hbs
ui/app/templates/vault/cluster/access/oidc/providers/create.hbs
ui/app/templates/vault/cluster/access/oidc/providers/provider.hbs
ui/app/templates/vault/cluster/access/oidc/providers/provider/edit.hbs
ui/lib/core/addon/components/form-field-label.hbs
ui/lib/core/addon/components/form-field.hbs
ui/mirage/handlers/oidc-config.js
ui/tests/integration/components/form-field-label-test.js
ui/tests/integration/components/oidc/provider-form-test.js

Updated PR to reflect latest designs. Notice that the `Issuer` has a placeholder on create, and then on edit the URL path is trimmed to just the `scheme://host:port` portion. The issuer param's _output_ is different than the _input_. The full URL is the output of a provider's attribute, but only the origin piece is valid input. [See docs](https://www.vaultproject.io/api-docs/secret/identity/oidc-provider#parameters)
<hr>
_**create**_
_**edit**_

UI/OIDC providers create/edit route

---

vault/testing.go

We don't actually need to pull in this dependency in our tests. So we mock it instead.

unit test: remove postgres dependecy from testing.go

---

website/content/docs/agent/template.mdx

Docs PR to clarify and distinguish behavior between the usage of `secret` and `pkiCert` template functions for rendering certificates with Agent.
Related to:
- https://github.com/hashicorp/vault/pull/15293
- https://github.com/hashicorp/vault/pull/16087

docs: update agent template certificate section

---

website/content/docs/secrets/databases/index.mdx

This PR removes a statement that's no longer true from the password policy section of the database secrets engine documentation. Password policies can be set at the [role level](https://www.vaultproject.io/api-docs/secret/databases#password_policy-1) since Vault 1.11.

secrets/db: update documentation on password policies

---

changelog/16673.txt
vault/auth.go
vault/auth_test.go
vault/mount.go
vault/mount_test.go
vault/testing.go

Ensure we use the alias mappings for secrets engines and auth methods if they exist. This will prevent vault from reporting the plugin does not exist in the catalog.
These alias mappings are evaluated JIT before instantiating the backend as a less invasive solution to support legacy backend types.

secrets/auth: fix bug with aliased backends

---

.release/ci.hcl

Adding a note in `ci.hcl` file to emphasize that the `post-publish-website` event is for OSS use only. It should not be merged into Enterprise repos.

add a note clarifying to leave website event in oss only

---

builtin/logical/database/rotation.go
changelog/16686.txt

This fixes a small bug in the `initQueue` function where a WAL write test is performed prior to starting the database secret engine caused a lot of delete wal calls to be queued. 
When Vault is starting up, it's storage is in read only, so writes will produce an error. The current code checks if a WAL ID is returned after calling `PutWal`, but this function always returns a WAL ID so it defers a delete call. Since an error is also returned, it then loops and tries again. If start up is taking an excessive amount of time, this bug will queue up a delete wal every 10ms until Vault's storage accepts writes. This is amplified if you have many database secret engines.

secret/database: fix bug where too many wal deletes are deferred

---

ui/tests/acceptance/enterprise-control-groups-test.js
ui/tests/acceptance/enterprise-kmip-test.js

Instead of backporting because some of the fixes already exist already on main, I'm targeting the individual release branches, and making fixes here. There will be two other PRs: one for 1.10 and one for 1.11.
This PR address these failures.

Fix UI Enterprise test failures on 1.9 specifically

---

ui/tests/acceptance/enterprise-kmip-test.js

Building off of [1.10 PR](https://github.com/hashicorp/vault/pull/16698) fix, but this release branch already had the control group fixes.

Fix enterprise test failures for 1.11

---

sdk/helper/keysutil/policy.go
sdk/helper/keysutil/policy_test.go

Found by @trishankatdatadog in [PR#16549](https://github.com/hashicorp/vault/pull/16549#discussion_r943618434). We are masking errors coming out of the RSA verification call, as verification errors instead of returning them as usage errors.

Do not mask RSA verification misuse errors as verification failures

---

api/kv.go
api/kv_v1.go
api/kv_v2.go
changelog/16699.txt
vault/external_tests/api/kv_helpers_test.go

Adding a sentinel error value `ErrSecretNotFound`. With this change, callers can check specifically for non-existing secrets:
```go
secret, err := client.KvV2("secret").Get("foo")
if errors.Is(err, vault.ErrSecretNotFound) {
// handle missing secret
}
if err != nil {
// handle other errors
}
```
An example where this would be useful is when implementing an "upsert" behavior, as suggested in #16483. The caller can check the error returned from `KVv2.Patch` for `errors.Is(err, vault.ErrSecretNotFound)` and call `KvV2.Put` accordingly.

Add a sentinel error for missing KV secrets

---

builtin/logical/pki/backend_test.go
builtin/logical/pki/crl_test.go
builtin/logical/pki/crl_util.go
builtin/logical/pki/path_revoke.go
builtin/logical/pki/storage.go
builtin/logical/pki/util.go
changelog/16564.txt
website/content/api-docs/secret/pki.mdx

This PR adds support for post-hoc revocation of certificates either signed externally (prior to Vault owning the CA) or of certificates issued from a `no_store=true` role. This allows all certificates to be revoked, regardless of origin. 
This is done by specifying the `certificate` parameter (taking a PEM-encoded certificate) on the `/revoke` API endpoint, instead of the `serial_number` argument. Vault verifies this against the mount's issuers and adds it to the local storage before also revoking it.
Currently there is no way to import active certificates for storage without revoking them as well.
---

Add BYOC-based revocation to PKI secrets engine

---

builtin/logical/pki/backend_test.go
builtin/logical/pki/path_manage_issuers.go
changelog/16721.txt

While older versions of Vault supported sending this, we broke such
support in 1.11. Ignore them from the manage issuers endpoint (which is
aliased to the old `/config/ca` path) -- but keep erring in the import
keys paths. The latter is a new endpoint not aliased to anything and
only expects a single PEM block.
---
Resolves: #16667

Ignore EC PARAMETER blocks during issuer import

---

changelog/16714.txt
command/debug.go
website/content/api-docs/system/monitor.mdx

https://github.com/hashicorp/vault/issues/16228
When running vault debug command, then either observe the vault.log while the command is running or examine the vault.log in the archive, there are several empty lines added.

Remove extra empty lines from vault.log - Debug command 

---

website/content/docs/auth/cert.mdx

[Old PR](https://github.com/hashicorp/vault/pull/10389) created in 2020 fixes this typo in a different directory structure. 
The typo still exists, so this PR fixes that. 
🔍 [Deploy Preview](https://vault-git-docs-fix-auth-cert-typo-hashicorp.vercel.app/docs/auth/cert#revocation-checking)

Fix a typo -> 'authorised' should be 'authorized'

---

builtin/logical/pki/backend.go
builtin/logical/pki/crl_test.go
builtin/logical/pki/path_revoke.go
changelog/16566.txt
sdk/helper/certutil/helpers.go
website/content/api-docs/secret/pki.mdx
website/content/docs/secrets/pki/considerations.mdx

This PR adds support to the PKI secrets engine for revocation of certs without requiring privileged access to the `/revoke` endpoint. In particular, we use the private key as evidence of permission to revoke the certificate: either the private key was leaked, therefore suggesting the certificate should be revoked anyways, or someone with access to the private key material (and thus, likely the original issuer) suggests the certificate should be revoked and could publish the private key publicly (therefore, triggering case one).
This is done by hitting a new `/revoke-with-key` endpoint with the `private_key` field (taking a PEM-encoded private key). This endpoint otherwise has semantics similar to `/revoke` (allowing it to either revoke by BYOC or stored cert serial number), but is less …

Add proof possession revocation for PKI secrets engine

---

changelog/16739.txt
ui/app/models/pki-ca-certificate-sign.js
ui/app/models/pki-ca-certificate.js

PKI has consistently used `permitted_dns_domains` since it was originally
[introduced as a parameter](https://github.com/hashicorp/vault/commit/e6b43f7278d2c7e710b727b2e903c2fef1458d46). However, it appears the Web UI was updated to
[add this field (n.b.: prior to the move to OSS)](https://github.com/hashicorp/vault/blob/2c2f0d853f0342509037b4573c28d9be409db2fb//ui/app/models/pki-ca-certificate.js#L58), but used an incorrect internal identifier
(`permittedDnsNames` rather than `permittedDnsDomains`).
This triggers a warning from the backend about an unknown parameter, and
the domain restriction isn't added:
> ```
> Endpoint ignored these unrecognized parameters: [permitted_dns_names]
> ```
---
I think with the changes to the UI …

Fix naming of permitted_dns_domains in webui

---

builtin/logical/ssh/backend_test.go
builtin/logical/ssh/path_issue_sign.go
builtin/logical/ssh/path_roles.go
changelog/16056.txt
website/content/api-docs/secret/ssh.mdx

This implements the `allowed_domains_template` field when configuring SSH roles on the SSH secret engine (as explained in issue #10943). It also fixes an issue that `allowed_users_template` actually affected the domain templating. I also directly added the documentation for it.

fix bug with allowed_users_template and add allowed_domains_template for SSH role

---

website/content/docs/agent/index.mdx

This PR fixes what [PR 9766](https://github.com/hashicorp/vault/pull/9766) intend to fix.
[PR 9766](https://github.com/hashicorp/vault/pull/9766) was opened in 2020. Since then, the folder structure has changed. 
🔍 [Deploy Preview](https://vault-git-docs-vault-agent-doc-fix-hashicorp.vercel.app/docs/agent#address)

Update the Vault Agent config example

---

changelog/16447.txt
vault/activity_log.go

Deleted changelog for https://github.com/hashicorp/vault/pull/16447/files as it's a bug fix before feature release. 
Tests for HandleQuery must be in Ent: https://github.com/hashicorp/vault-enterprise/pull/3081/files

re-add namespace attribution to current month

---

vault/activity_log.go
vault/activity_log_test.go
vault/activity_log_util_common.go

Approved Ent PR: https://github.com/hashicorp/vault-enterprise/pull/3084/files

Allow Partial Month Counts To Be Returned Without Precomputation [OSS]

---

website/content/docs/platform/k8s/index.mdx

🧵 [Slack chat](https://hashicorp.slack.com/archives/CQS78SFQD/p1660642943470079)
🔍 [Deploy Preview](https://vault-git-docs-fix-k8s-raft-hashicorp.vercel.app/docs/platform/k8s#guides)
It was reported that the doc points to the wrong tutorial. 
This PR:
- Points to the correct tutorial link 
- Removed the collection path in the tutorial URL (`?in=vault/kubernetes`) to avoid potential complication post migrating to DevDot

Fix the referenced learn link

---

website/content/docs/commands/secrets/enable.mdx
website/content/docs/secrets/index.mdx

🔍 [Deploy Preview - Secrets Engine](https://vault-git-docs-secrets-mount-paths-hashicorp.vercel.app/docs/secrets)
🔍 [Deploy Preview - secrets enable command](https://vault-git-docs-secrets-mount-paths-hashicorp.vercel.app/docs/commands/secrets/enable#path)
This PR fixes what [PR 9199](https://github.com/hashicorp/vault/pull/9199) intended to fix. 
- Adds a callout note to say that mount path is case-sensitive
- Add hyperlinks to respective command docs

Mount paths case-sensitivity

---

changelog/16683.txt
command/base.go
command/base_helpers.go
command/base_helpers_test.go
command/main.go

+ added filtering for env flags when generating command parsing warnings
- removed some duplication and created constants so new flags are properly handled automatically if added to the defined collection
Env flags passed at the end of a command generates undesired warnings, e.g.:
```
vault read sys/auth/approle/tune -format=json
Flags must be provided before positional arguments. The following arguments will not be parsed as flags: [-format=json]
(...)
```
Some flags are not tied to a command but to the general execution environment and are valid when passed at the very end. For example: `format=json`. Warnings introduced during [this pull request](https://github.com/hashicorp/vault/pull/16441) could create false positives when environment flags are used appropriately as it treated any …

Env Flag Filtering

---

go.mod
go.sum

to bring in changes from https://github.com/hashicorp/go-plugin/pull/207. This adds a log warning when the SecureConfig is not set.
Steps:
```
go get github.com/hashicorp/go-plugin@v1.4.5
go mod tidy
```

update go-plugin to v1.4.5

---

ui/lib/core/addon/components/confirm-action.hbs
ui/lib/core/addon/components/confirm-action.js
ui/tests/integration/components/confirm-action-test.js

It turns out the confirm-action component was never closing the content modal after deleting whatever it was deleting. This becomes an issue in future oidc provider work. I added test coverage so I could actually test that this was happening and then fix it. 
Thank you Claire for pointing this out!

Confirm-action fixes

---

website/content/api-docs/secret/databases/postgresql.mdx
website/content/docs/secrets/databases/postgresql.mdx

With the switch to `pgx` for the database driver, multi-host connection strings are now supported by the postgresql database plugin. This adds a small bit of documentation outlining how you might use it and refers to the official Postgres docs for more info on string formatting.
Also added examples for the keyword/value style connection.
e.g.
`"postgresql://{{username}}:{{password}}@host1:5432,host2:5432/database"`
`"host=host1,host2 port=5432 user={{username}} password={{password}} dbname=database"`

Add Multi-Host Connection String info to Postgres secrets API docs

---

builtin/credential/github/backend.go

Security recommendation; disabling the upload url which is currently unused and unconfigurable will not impair the functionality of the plugin but limit the odds of introducing a potential vulnerability if a code path ever uses the default url (uploadBaseURL  = "https://uploads.github.com/") by mistake
A helper method github.NewEnterpriseClient() was introduced to let urls be configured during the client's instantiation but using it would be breaking. Vault fallbacks on the default base URL (defaultBaseURL = "https://api.github.com/") if the base_url argument is not provided when configuring the github plugin.

Setting upload url explicitly empty

---

ui/tests/acceptance/oidc-auth-method-test.js

It appears to be an issue with having the login async function outside of the tests. I tried adding the `waitUntil` inside the login function, but that wasn't enough. I had to remove the function entirely and add the chunks to the individual tests and add the waitUntils.
To reproduce the earlier failure, just run this test suite more than once. I have tested with this fix and it longer fails after running several times in a row 🎉.

Fixing flaky "oidc auth method" tests

---

website/content/docs/use-cases.mdx

Modified the use case doc based on PM's input/feedback.
:mag:[Deploy Preview](https://vault-git-docs-update-use-cases-hashicorp.vercel.app/docs/use-cases)

vault documentation: updated use cases doc

---

builtin/logical/pki/backend.go
builtin/logical/pki/crl_test.go
builtin/logical/pki/crl_util.go
builtin/logical/pki/path_fetch_issuers.go
builtin/logical/pki/path_manage_issuers.go
builtin/logical/pki/storage.go
changelog/16621.txt
website/content/api-docs/secret/pki.mdx
website/content/docs/secrets/pki/considerations.mdx

This allows PKI's issuers to be considered revoked and appear on each
others' CRLs. We disable issuance (via removing the usage) and prohibit
modifying the usage via the regular issuer management interface.
A separate endpoint is necessary because issuers (especially if signed
by a third-party CA using incremental serial numbers) might share a
serial number (e.g., an intermediate under cross-signing might share the
same number as an external root or an unrelated intermediate).
When the next CRL rebuild happens, this issuer will then appear on
others issuers CRLs, if they validate this issuer's certificate.
---

Allow marking issuers as revoked

---

builtin/logical/pki/backend_test.go
builtin/logical/pki/cert_util.go
builtin/logical/pki/path_config_urls.go
builtin/logical/pki/path_fetch_issuers.go
builtin/logical/pki/path_intermediate.go
builtin/logical/pki/path_manage_issuers.go
builtin/logical/pki/path_root.go
builtin/logical/pki/storage.go
builtin/logical/pki/util.go
changelog/16563.txt
website/content/api-docs/secret/pki.mdx
website/content/docs/secrets/pki/considerations.mdx

Per discussion on GitHub with @maxb, this allows issuers to have their
own copy of AIA URIs. Because each issuer has its own URLs (for CA and
CRL access), its necessary to mint their issued certs pointing to the
correct issuer and not to the global default issuer. For anyone using
multiple issuers within a mount, this change allows the issuer to point
back to itself via leaf's AIA info.
---

Add per-issuer AIA URI information to PKI secrets engine

---

go.mod
go.sum

Updates `consul-template` to `v0.27.3`

Backport consul-template update

---

website/content/docs/auth/gcp.mdx

This replicates [PR 11513](https://github.com/hashicorp/vault/pull/11513) which was opened in May, 2021.  Since the originator hasn't signed the CLA, we cannot merge the PR. 
This PR attempts to implement the suggested updates. 
🔍 [Deploy Preview](https://vault-git-docs-gcp-auth-jwt-hashicorp.vercel.app/docs/auth/gcp#service-account-credentials-api)

Include jwt_claim expiration error message

---

website/content/docs/auth/kerberos.mdx

For some reason, the original [PR 12880](https://github.com/hashicorp/vault/pull/12880) seems to hang. 
This PR attempts to try making the same edit. 
🔍 [Deploy preview](https://vault-git-docs-clarify-keytab-hashicorp.vercel.app/docs/auth/kerberos)

Clarify keytab gen process

---

sdk/helper/keysutil/policy.go
sdk/helper/keysutil/policy_test.go

Reverting fix done within [PR#16695](https://github.com/hashicorp/vault/pull/16695) as its causing some issues within the Boringcrypto version of Go we use around the tests that were written for the verification. This also questions the value of the fix as end-users still should be failing validation in both circumstances.
This reverts commit 34225943c5a3ff60c9be14dc8522862023af5d9b.

Revert "Do not mask RSA verification misuse errors as verification failures (#16695)"

---

website/content/docs/auth/kubernetes.mdx

Update the `apiVersion` of the `ClusterRoleBinding` example in the [Configuring Kubernetes](https://www.vaultproject.io/docs/auth/kubernetes#configuring-kubernetes) section of the Kubernetes Auth method documentation.  This is necessary as the `v1beta1` version has been deprecated and removed.
> [Warning: rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+](https://stackoverflow.com/q/65068168/6466149)
Without this, we get the following error:
```sh
$ k apply --filename cluster-role-binding.yaml
error: unable to recognize "cluster-role-binding.yaml": no matches for kind "ClusterRoleBinding" in version "rbac.authorization.k8s.io/v1beta1"
```
Before and after shots attached.
---

Update apiVersion of the ClusterRoleBinding example

---

go.mod
go.sum

The current version of crypto contains the GO-2021-0356 vulnerability.
The version consumed in this PR has been patched.
https://deps.dev/advisory/osv/GO-2021-0356

Update crypto package to fix GO-2021-0356

---

builtin/logical/pki/storage.go
builtin/logical/pki/storage_migrations_test.go
changelog/16813.txt

- We missed testing a use-case of the migration that someone has a PKI
mount point that generated a CSR but never called set-signed back on
that mount point so it only contains a key.
Fixes reported issue #16810

Migrate existing PKI mounts that only contains a key

---

website/content/api-docs/auth/userpass.mdx

While using the Userpass docs recently, I noticed that there were inconsistencies in the names of parameters.  Upon further research, I found that the docs were using a mixture of up-to-date and deprecated parameter names which I found confusing.
I went through and updated the Userpass API docs to no longer use deprecated parameter names.  Additionally, I updated the output examples to be accurate for latest version of Vault.  This generally made the docs more cohesive and less contradictory in my opinion.
Note that you can see which parameters are deprecated with the help of the `path-help` command.  I'll include an example below:
```
$ vault path-help auth/userpass/users/mitchellh
Request:        users/mitchellh
Matching Route: ^users/(?P<username>\w(([\w-.]+)?\w)?)$
Manage users …
```

Update Userpass API Docs 

---

website/content/docs/platform/servicenow/installation.mdx

Use `hcl` so the code snippet is more readable and is highlighted correctly.

Use HCL syntax for code snippet

---

changelog/16794.txt
http/sys_wrapping_test.go
sdk/framework/backend.go
sdk/framework/path.go
vault/logical_system_paths.go

The changes made to `TestHTTP_Wrapping` made the test fail before my fix, and this fixes the issue.
The output of an unwrap no longer contains a warning:
```
vault write -force sys/wrapping/unwrap
Key    Value
---    -----
foo    bar
```
I could not find any other endpoint that would be appropriate to add `TakesArbitraryInput: true` to, but it made sense to me to add the new option to the framework instead of simply making an exception for this particular endpoint, which felt messy. It seems likely we'll have need for this boolean in the future.

VAULT-7698 Fix ignored parameter warnings for endpoint arbitrary data options

---

builtin/logical/pki/backend.go
changelog/16830.txt

LIST operation backport fixes failure to cherrypick.

Fix cherrypick on backport to 1.11.x

---

changelog/16821.txt
ui/app/lib/route-paths.js
ui/app/mixins/cluster-route.js
ui/app/router.js
ui/app/routes/vault/cluster/redirect.js
ui/app/templates/vault/cluster/redirect.hbs
ui/tests/unit/mixins/cluster-route-test.js
ui/tests/unit/routes/vault/cluster/redirect-test.js

This adds behavior to the auth route where, if the user is already logged in and they attempt to go to the auth url with the `redirect_to` param present, they will get redirected to the `redirect_to` route:
Previously, attempting to go to the auth route when already logged in will always route you to the main secrets list:

UI: Forward to `redirect_to` param to when auth'd

---

builtin/logical/pki/backend.go
builtin/logical/pki/crl_test.go
builtin/logical/pki/storage.go

Previously we used the global backend-set `crlLifetime` as a default
value. However, this was refactored into a new `defaultCrlConfig` instead,
which we should reply with when the CRL configuration has not been set
yet. In particular, the 72h default expiry (and new 12h auto-rebuild
grace period) was added and made explicit.
[This fixes the broken UI test](https://app.circleci.com/pipelines/github/hashicorp/vault/40020/workflows/bc2c9cf8-2353-4acb-a4fd-92c4967b6049/jobs/499177).

Finish refactor to remove global crlLifetime

---

vault/identity_store.go
vault/identity_store_test.go

This fixes a bug in the Identity store where metadata can be leaked between aliases using the same name but have different mount accessors. This also can have adverse effects on Vault performance because it's causing unnecessary entity updates.

identity/entity-alias: fix bug where wrong metadata was updated

---

changelog/16834.txt
command/debug.go

This PR fixes a bug in the log target for vault debug. When defining a debug duration length longer than two minutes, the vault.log file in the debug package would only have the first two minutes of logs emitted during the window, and then have newlines for the remainder of the time frame.

command/debug: fix bug where monitor was not honoring configured duration

---

website/content/docs/auth/cf.mdx

🔍 [Deploy preview](https://vault-git-docs-enable-mtls-cf-hashicorp.vercel.app/docs/auth/cf#enabling-mutual-tls-with-the-cf-api)
This PR duplicates what [PR 10356](https://github.com/hashicorp/vault/pull/10356) intended to do. 
The original PR was created in 2020.  Since then, the file structure has changed and causing merge conflict.

Add documentation for enabling mutual TLS with the CloudFoundry API

---

website/content/api-docs/secret/nomad.mdx
website/content/docs/secrets/nomad.mdx

This PR accomplishes what [PR 8983](https://github.com/hashicorp/vault/pull/8938) meant to do. 
Since PR 8983 was opened back in 2020, it's troublesome to merge the PR.  We'll fix the terminology with this PR and close PR 8983.

Updated Nomad Secret Engine docs with proper terminology

---

changelog/16826.txt
website/content/docs/secrets/ssh/signed-ssh-certificates.mdx

Relates to website section: [vaultproject.io/docs/secrets/ssh/signed-ssh-certificates](https://www.vaultproject.io/docs/secrets/ssh/signed-ssh-certificates) & Issue request #7529 - which still seems relevant and the clarity note would still be welcome.
Original request was asking for API addition - however given the nature of the request and explanations required it's been detailed instead in the bottom of the page near the Troubleshoot and Known issues area.

Docs: SSH CA Config & Comments. Resolves: #7529

---

builtin/logical/pki/ocsp.go
builtin/logical/pki/ocsp_test.go

Select the first issuer that matches our request hashes and has the OCSP signing usage enabled. This might not match the exact issuer id that issued the certificate but the signatures will be okay.
This should resolve the comment brought up by @kitography in [PR#16723](https://github.com/hashicorp/vault/pull/16723#discussion_r951592384). Thanks again for identifying this issue in the review!

Handle multiple matching issuers in OCSP requests

---

website/content/docs/concepts/seal.mdx

The following sentence does not read easily:
"Take down the old active node, update its configuration of the old active node to use the new seal blocks (completely unaware of the old seal type) and bring it back up."
I have changed this to the sentence below, which I believe reads better.
"Take down the old active node, update its configuration to use the new seal blocks (completely unaware of the old seal type) and bring it back up."

Documentation grammar update for https://www.vaultproject.io/docs/concepts/seal#migration-post-vault-1-5-1

---

builtin/logical/pki/crl_test.go
builtin/logical/pki/crl_util.go

When we attempt to revoke a leaf certificate, we already parse all of
the issuers within the mount (to x509.Certificate) to ensure we don't
accidentally revoke an issuer via the leaf revocation endpoint. We can
reuse this information to associate the issuer (via issuer/subject
comparison and signature checking) to the revoked cert in its revocation
info. This will help OCSP, avoiding the case where the OCSP handler
needs to associate a certificate to its issuer.
---

Identify issuer on revocation

---

website/content/docs/concepts/client-count/index.mdx

Docs: Client Count Concept clarity.

---

website/content/api-docs/secret/ssh.mdx

This PR attempts to accomplish what [PR 10012](https://github.com/hashicorp/vault/pull/10012) intended.
In addition, I rephrased the sentence to read better. 
🔍 [Deploy preview](https://vault-git-docs-update-ssh-secrets-hashicorp.vercel.app/api-docs/secret/ssh#allowed_users)

Mention allowed_users and allowed_domains are comma separated lists

---

builtin/logical/database/rotation_test.go
builtin/logical/mongodb/backend_test.go
plugins/database/mongodb/mongodb_test.go

v6 was released in the last 24h, and our tests fail to connect to the db when v6 is used.
Using v6 needs investigating, but for now I'm pinning to the last known good version.
Failure messages look like:
```
Failed
=== RUN   TestBackend_basic
mongodbhelper.go:68: could not start docker mongo: no reachable servers
--- FAIL: TestBackend_basic (323.90s)
```
See [here](https://app.circleci.com/pipelines/github/hashicorp/vault/40223/workflows/53234c55-8579-4725-a7ee-f120b47916b1/jobs/500984) for an example failing job.

Pin MongoDB test container images pre-v6

---

builtin/logical/pki/chain_test.go
builtin/logical/pki/crl_test.go
builtin/logical/pki/crl_util.go
changelog/16874.txt

This makes four incremental improvements to revocation (around issuers and otherwise):
1. Fixes the nits from the earlier auto-merged PR (sorry @kitography!) and updates the tests according to @stevendpclark's internal suggestions.
2. Now that #16762 is merged and #16871 is opened, makes CRL building skip the step of doing cert association. This means we can exit fast if CRL building is disabled altogether.
3. Fix a bug identified during an internal demo call, wherein a root appeared on its own CRL, and intermediates appearing multiple times (oops). This is because of @kitography's last-minute-but-good suggestion of writing out a fat revInfo entry for serials we see in storage, and my forgetting to filter them out when building the CRL. D'oh.
4. The **most complex** change: actually …

Cleanup changes around issuer revocation

---

builtin/logical/pki/ocsp.go

Limit the maximum number of bytes we will consume from the post body, the get request I believe is already a bit too late, but checks added to be consistent. 
Not really sure if this is deserving of a test beyond what we already have.

Add maximums on how much data we will read for OCSP requests

---

changelog/16846.txt

The previous changelog specified a type of `enhancement`, which is
invalid. It should be `improvement`.

Fix changelog type for registry deprecation status

---

builtin/logical/pki/crl_test.go
builtin/logical/pki/ocsp.go
builtin/logical/pki/ocsp_test.go
builtin/logical/pki/path_config_crl.go
builtin/logical/pki/storage.go
website/content/api-docs/secret/pki.mdx

- Add a new configurable duration field to the crl configuration to allow operator control of how long an OCSP response can be cached for. A value of 0 means no one should cache the response.
- This is useful for how long a server like NGINX/Apache is allowed to cache the response for OCSP stapling.
- Address an issue discovered that we did not upgrade existing crl configurations properly

Add ocsp_expiry configuration field to PKI crl config

---

changelog/16890.txt
go.mod
go.sum
website/content/api-docs/auth/kerberos.mdx

Updates Vault to include new kerberos auth config `add_group_aliases`, which includes LDAP groups in the group aliases for the login: https://github.com/hashicorp/vault-plugin-auth-kerberos/pull/73.

auth/kerberos: add config to include ldap groups in group alias

---

changelog/14455.txt
website/content/docs/configuration/storage/google-cloud-storage.mdx

Add mentions the environment variables that can be used to configure the backend instead of using the stanza parameters

Update google-cloud-storage backend documentation

---

website/content/docs/enterprise/license/autoloading.mdx

The "DELETE API" links to a nonexistent subsection of the /sys/license/status page from 1.11.x onwards. Not sure if the suggestion to restart the service should remain in this edit - I found a restart of all Vault servers cleared this message where other attempts failed - happy to remove it if preferred, though.

Description

---

builtin/logical/transit/path_decrypt.go
builtin/logical/transit/path_encrypt.go

Update descriptions to match field content (the field is actually key name, not policy name).
As shown in the attached screen shot of API Explorer for Transit, the encrypt endpoint takes a key name, and the UI text appears to be pulling the **Description** field as  "Name of the policy" from the secrets engine instead of "Name of the key", which is what really goes in the field (i.e. "my-key").

Transit: update documentation strings

---

helper/testhelpers/testhelpers.go
helper/testhelpers/testhelpers_oss.go
vault/cluster_test.go

This works because activeNodeReplicationState is initialized to zero, updated as a result of echo requests, and reset back to zero when heartbeating is shut down (as when transitioning to/from active state, or when the leader changes.)
Example failure: https://app.circleci.com/pipelines/github/hashicorp/vault/4864/workflows/ed93e741-eb56-4c67-aad8-842420260319/jobs/501541

Wait for standby to have a working grpc connection before we try to use it

---

builtin/logical/pki/chain_util.go

Fixes https://github.com/hashicorp/vault/security/code-scanning/139
+ https://github.com/hashicorp/vault/security/code-scanning/138

Fix CodeQL Errors - check allocation is smaller than 2^30

---

changelog/16911.txt
vault/external_tests/mfa/login_mfa_test.go
vault/login_mfa.go

namespace_path is now returned:
```
violet@violet-TX54KFJWXM vault % curl \
--header "X-Vault-Token: hvs.INkinqiHlLMccLwuOsTB9WTI" \
--header "X-Vault-Namespace: abc" \
--request GET \
'http://127.0.0.1:8200/v1/identity/mfa/method?list=true'
{"request_id":"dac656b6-b86b-9e51-bf47-c78d07acc370","lease_id":"","renewable":false,"lease_duration":0,"data":{"key_info":{"25241e4f-6146-c1fb-9cdd-761e56599e73":{"base_url":"okta.com","id":"25241e4f-6146-c1fb-9cdd-761e56599e73","mount_accessor":"","name":"","namespace_id":"cBQTS","namespace_path":"abc/","org_name":"dev-08217481","type":"okta","username_format":"{{identity.entity.aliases.auth_userpass_3aae7eb0.name}}.hynes+second@hashicorp.com"}},"keys":["25241e4f-6146-c1fb-9cdd-761e56599e73"]},"wrap_info":null,"warnings":null,"auth":null} …
```

VAULT-6433: Add namespace path to MFA read/list endpoints

---

builtin/logical/pki/backend.go
builtin/logical/pki/cert_util.go
builtin/logical/pki/crl_test.go
builtin/logical/pki/crl_util.go
builtin/logical/pki/path_config_crl.go
builtin/logical/pki/path_fetch.go
builtin/logical/pki/path_fetch_issuers.go
builtin/logical/pki/storage.go
changelog/16773.txt
sdk/helper/certutil/helpers.go
website/content/api-docs/secret/pki.mdx

While switching to periodic rebuilds of CRLs alleviates the constant
rebuild pressure on Vault during times of high revocation, the CRL
proper becomes stale. One response to this is to switch to OCSP, but not
every system has support for this. Additionally, OCSP usually requires
connectivity and isn't used to augment a pre-distributed CRL (and is
instead used independently).
By generating delta CRLs containing only new revocations, an existing
CRL can be supplemented with newer revocations without requiring Vault
to rebuild all complete CRLs. Admins can periodically fetch the delta
CRL and add it to the existing CRL and applications should be able to
support using serials from both.
Because delta CRLs are emptied when the next complete CRL is rebuilt, it
is important that applications …

Support for generating Delta CRLs

---

ui/app/adapters/named-path.js
ui/app/components/oidc/assignment-form.js
ui/app/components/oidc/client-form.js
ui/app/components/oidc/key-form.js
ui/app/components/oidc/provider-form.js
ui/app/components/oidc/scope-form.js
ui/app/models/oidc/client.js
ui/app/styles/core/forms.scss
ui/app/templates/components/oidc/assignment-form.hbs
ui/app/templates/components/oidc/client-form.hbs
ui/app/templates/components/oidc/key-form.hbs
ui/app/templates/components/oidc/provider-form.hbs
ui/app/templates/components/oidc/scope-form.hbs
ui/lib/core/addon/components/alert-inline.hbs
ui/lib/core/addon/components/alert-inline.js
ui/lib/core/addon/components/form-field.hbs
ui/tests/acceptance/oidc-config/clients-test.js
ui/tests/helpers/oidc-config.js
ui/tests/integration/components/oidc/client-form-test.js
ui/tests/integration/components/oidc/key-form-test.js
ui/tests/integration/components/oidc/provider-form-test.js
ui/tests/integration/components/oidc/scope-form-test.js
ui/tests/unit/adapters/oidc/test-helper.js

UI: Checks if records exists before creating record when URL contains :name

---

ui/app/components/oidc/client-form.js
ui/app/components/oidc/key-form.js
ui/app/templates/components/oidc/key-form.hbs
ui/app/templates/components/radio-card.hbs
ui/lib/core/addon/components/search-select.js
ui/lib/core/addon/components/tool-tip.js
ui/tests/helpers/oidc-config.js
ui/tests/integration/components/mfa-login-enforcement-header-test.js
ui/tests/integration/components/oidc/key-form-test.js

This PR disables limiting applications when initially creating a key to prevent a user from limiting access to an application that references a different key. An application's key **cannot be edited** so the key must first exist and assigned to an application before a key's access can be limited. 
> _Application form dropdown for selecting a `key`_
Once the key is referenced by an application, then we can go back and **edit** the key and limit access so only selected applications can use it for authentication requests. The search select dropdown only shows applications that reference the current key. Notice that `test-key` only has `app-1` and `app-2` in the dropdown because they are the only two apps that use it. 
<hr>

UI: Disable limiting clients when creating key, filter clients when editing

---

builtin/logical/pki/backend.go
builtin/logical/pki/backend_test.go
builtin/logical/pki/config_util.go
builtin/logical/pki/crl_util.go
builtin/logical/pki/path_fetch.go
builtin/logical/pki/path_fetch_issuers.go
builtin/logical/pki/storage.go
builtin/logical/pki/util.go

This adds two behavior fixes to the If-Modified-Since header:
1. Ensure that issuer renames correctly invalidate the config. A three-way swap of issuer names is equivalent to the default changing.
2. Add correct handling behavior for the delta CRL.
2 needs some follow-up testing in a second PR; we want to introduce a `crl/rotate-delta` URL that rotates _just_ the delta CRL, which we can use for further testing of the Delta CRL IMS behavior. Right now we just test to ensure it has semantics equivalent to the main CRL...
No new changelog or docs entries are necessary since this isn't yet shipped in a release. 
---
cc @Gabrielopesantos -- in case you're interested in what the follow-up looks like :-)

Clean up behavior of If-Modified-Since header

---

vault/login_mfa.go

Small bug that was breaking `TestIdentityMFA_TypeImmutability` in ent. I did run the tests in ent that I found before merging, but missed this one as it was in the `vault` package.

VAULT-6433 do not return nil resp if ns is nil

---

builtin/logical/pki/backend.go
builtin/logical/pki/crl_test.go
builtin/logical/pki/fields.go
builtin/logical/pki/path_tidy.go
builtin/logical/pki/path_tidy_test.go
builtin/logical/pki/storage.go
changelog/16900.txt
vault/rollback.go
vault/testing.go
website/content/api-docs/secret/pki.mdx

This enables the PKI secrets engine to allow tidy to be started
periodically by the engine itself, avoiding the need for interaction.
This operation is disabled by default (to avoid load on clusters which
don't need tidy to be run) but can be enabled.
In particular, a default tidy configuration is written (via
`/config/auto-tidy`) which mirrors the options passed to `/tidy`. Two
additional parameters, enabled and interval, are accepted, allowing
auto-tidy to be enabled or disabled and controlling the interval
(between successful tidy runs) to attempt auto-tidy.
Notably, a manual execution of tidy will delay additional auto-tidy
operations. Status is reported via the existing `/tidy-status` endpoint.
---

Add ability to perform automatic tidy operations

---

builtin/logical/pki/fields.go
builtin/logical/pki/path_tidy.go

We switch these fields to use the explicit default value (computing the
time in seconds appropriately).
As reported by @beornf, thanks!

Fix comment of default value of tidy interval

---

builtin/logical/pki/backend_test.go
builtin/logical/pki/fields.go
builtin/logical/pki/path_issue_sign.go
changelog/16935.txt
website/content/api-docs/secret/pki.mdx

This adds a new flag to allow end-users to control if we return the self-signed/root CA certificates within the ca_chain field on issue and sign api calls. This was done to resolve concerns brought up by @maxb within issue #16057. The default behavior for the flag does preserve the behavior returning the root CA within the ca_chain field. The new flag is available on the following apis.
- `issue/<role>`
- `issuer/<issuer ref>/issue/<role>`
- `sign/<role>`
- `issuer/<issuer_ref>/sign/<role>`
- `sign-verbatim`
Note that the change mentioned within #16057 only affected mounts that had been initialized with the `root/generate/internal` api. Had an intermediary mount had an `intermediate/set-signed` call with the root CA within the PEM bundle, it would have contained the root CA certificate …

Add remove_roots_from_chain to sign and issue pki apis

---

changelog/16950.txt
website/content/api-docs/system/lease-count-quotas.mdx

Came via customer case. Really, the only approach that makes sense here is documentation around the fact that this can be expensive if you do a lot of it.

VAULT-7707 Add docs around making mass amounts of lease count quotas via automation

---

builtin/logical/transit/path_sign_verify.go
builtin/logical/transit/path_sign_verify_test.go
changelog/16549.txt
sdk/helper/keysutil/consts.go
sdk/helper/keysutil/policy.go
sdk/helper/keysutil/policy_test.go
website/content/api-docs/secret/transit.mdx

The Golang `crypto/rsa` package [allows](https://pkg.go.dev/crypto/rsa#pkg-constants) for using at least two possible [salt lengths](https://crypto.stackexchange.com/questions/1217/rsa-pss-salt-size) (`auto` and `hash` for want better terminology) when creating/verifying RSA PSS signatures. However, these options are currently not exposed via the Vault Transit Secrets Engine. These options would allow for cross-platform signature verification without modifying downstream clients (e.g., the [securesystemslib](https://github.com/secure-systems-lab/securesystemslib/pull/262) package, used by the [python-tuf](https://github.com/theupdateframework/python-tuf) and [python-in-toto](https://github.com/in-toto/in-toto) supply chain security frameworks, which currently assumes a different salt …

Allow configuring the possible salt lengths for RSA PSS signatures

---

website/content/docs/configuration/seal/awskms.mdx

adds note specifying optional use and formatting of aws kms_key_id alias

adds note about aws kms_key_id alias

---

changelog/16956.txt
vault/token_store_util_common.go

This PR is a port of https://github.com/hashicorp/vault-enterprise/pull/3170/files.
Description (from ent PR): 
This PR fixes the regression with SSCT. 
The issue is that the SSCT Generation counter was not being loaded from storage, so when it was written to storage during DR promotion it would always be 1. The fix is to load the value from storage during DR promotion. DRs never use the generation counter, but on DR clusters the value in memory will always be 1 less than the value in storage. However, the moment the DR gets updated to a primary, the value from storage will be incremented and written back.
Will open the OSS port after this PR is approved, with a changelog in OSS.
The PR will need to be backported to 1.10.

Load SSCT Generation Counter Upon DR Promotion [OSS]

---

builtin/logical/pki/backend.go
builtin/logical/pki/backend_test.go
builtin/logical/pki/fields.go
builtin/logical/pki/path_tidy.go
builtin/logical/pki/path_tidy_test.go
changelog/16958.txt
website/content/api-docs/secret/pki.mdx

This adds two features to the PKI tidy operation that become useful with auto-tidy:
1. The ability to cancel running tidy operations, freeing up resources on the cluster.
2. The ability to pause between processing individual certificates. When handling the revoked certificates, this allows the operation to release the revoked-store lock, allowing new revocations to continue. This can reduce the resource utilization on a cluster during a tidy operation, but needs to be tuned carefully so not to have too much lock contention but also not cause the tidy to take too long.

Add ability to cancel PKI tidy operations, pause between tidying certs

---

builtin/logical/pki/backend.go
builtin/logical/pki/backend_test.go
builtin/logical/pki/crl_util.go
builtin/logical/pki/path_revoke.go
website/content/api-docs/secret/pki.mdx

Since Delta CRL functionality has its own changelog entry, I'm inclined not to bother with a changelog for this.
---
We add a new read endpoint, `crl/rotate-delta` to force a manual rebuild of the Delta CRLs on this local cluster. This mirrors the behavior of the existing `crl/rotate` endpoint, just for delta CRLs instead of full CRLs. We add a warning that this is a no-op when delta CRLs are not enabled.
This also adds a missing doc (as pointed out by @Gabrielopesantos in a ticket) about the response header. As far as I can tell, there's no real way to validate this header with `client.Logical()`; we'd probably have to resort to `client.RawRequest(...)` to validate it if we wanted to.

Add ability to request manual rebuild of Delta CRLs

---

api/sys_mounts.go
changelog/16849.txt
command/auth_list.go
command/secrets_list.go
command/secrets_list_test.go
http/sys_auth_test.go
vault/logical_system.go
vault/mount.go
vault/testing.go
website/content/docs/commands/auth/list.mdx
website/content/docs/commands/secrets/list.mdx

This PR adds the ability to query builtin deprecation status by adding a new column to the auth, secrets, and plugins lists. This will be further augmented in a follow-up PR which will add the status information to API endpoints as well.

Add deprecation status to list commands

---

builtin/logical/pki/backend_test.go
builtin/logical/pki/cert_util.go
builtin/logical/pki/chain_util.go
builtin/logical/pki/crl_test.go
builtin/logical/pki/crl_util.go
builtin/logical/pki/ocsp.go
builtin/logical/pki/ocsp_test.go
builtin/logical/pki/path_config_crl.go
builtin/logical/pki/path_fetch_issuers.go
builtin/logical/pki/path_issue_sign.go
builtin/logical/pki/path_revoke.go
builtin/logical/pki/path_roles.go
builtin/logical/pki/path_tidy.go
builtin/logical/pki/path_tidy_test.go
builtin/logical/pki/storage.go
builtin/logical/pki/test_helpers.go
builtin/logical/pki/util.go

Got curious and ran staticcheck on the PKI plugin. Nothing too bad and I've fixed the trivial issues reported in two separate commits, one for production files and the other for tests. No behavior change is expected from these changes.

Fix various trivial warnings from staticcheck in the PKI plugin 

---

changelog/16723.txt

Update the OCSP feature changelog entry to use the proper formatting as pointed out by @mladlow in https://github.com/hashicorp/vault/pull/16723#discussion_r959973127
One question is do I need to update the changelog.md file as part of this or will the existing reference be updated when this gets merged?

Update changelog for OCSP feature

---

changelog/16938.txt
vault/token_store.go

This PR fixes a bug where a user would receive a warning that the endpoint ignored unrecognized parameters, when those parameters are in fact recognized and expected when calling `vault token create` in the CLI or the equivalent API call:
```
❯ ./vault token create -explicit-max-ttl="10m" -policy="default"
WARNING! The following warnings were returned from Vault:
* TTL of "768h" exceeded the effective max_ttl of "10m"; TTL value is capped
accordingly
* Endpoint ignored these unrecognized parameters: [display_name entity_alias
explicit_max_ttl num_uses period policies renewable ttl type]
```

auth/token: Fix ignored parameter warnings for valid parameters on token create

---

CODEOWNERS

Hi gang. With Core taking over Agent, it makes sense to me to remove ecosystem as the owner of Agent, so we don't spam you with pull requests :)

Remove Ecosystem as a code owner of Vault Agent

---

.github/workflows/enos-run.yml

Disable the fail-fast feature for the matrix strategy. This prevents a
single failure to cascade to all jobs in the matrix. This prevents cases
where other jobs fail before they're able to clean up resources.

enos: don't fail fast in enos integration matrix

---

website/content/docs/auth/jwt/oidc-providers/azuread.mdx

Just adding a little context about Azure's 200 groups edge case so users know how to configure OIDC azure auth accordingly.

auth/oidc: add extra context about claim names in doc

---

website/content/docs/platform/aws/lambda-extension.mdx

Adds missing `VAULT_LOG_LEVEL` as a configuration option to the docs for Vault Lambda Extension.

Docs: Add log level environment variable for Vault Lambda Extension

---

http/logical.go
http/logical_test.go

This PR allows query parameters to be parsed and provided to backends for GET requests that are turned into `logical.ListOperation`. We started doing this for LIST requests as of https://github.com/hashicorp/vault/pull/16181. This makes the behavior consistent for Vault API requests that end up becoming a `logical.ListOperation`.
Example requests that result in a `logical.ListOperation`:
```sh
$ curl -X GET http://127.0.0.1:8200/v1/identity/oidc/provider?list=true&allowed_client_id=abc123
$ curl -X LIST http://127.0.0.1:8200/v1/identity/oidc/provider?allowed_client_id=abc123
```

Parse query parameters for GET request turned in logical.ListOperation

---

website/content/docs/secrets/databases/postgresql.mdx

Relates to #12458 and website section: [vaultproject.io/docs/secrets/databases/postgresql](https://www.vaultproject.io/docs/secrets/databases/postgresql#setup)

Docs: PostgreSQL Docs added DB name note for connection_url. 

---

website/content/docs/auth/gcp.mdx

Missed merger (from: #12231) with good clarity notes that still relevant to: [vaultproject.io/docs/auth/gcp](https://www.vaultproject.io/docs/auth/gcp#permissions-for-authenticating-against-vault) - please merge.

Docs: GCP SA clarity. Resolved merge conflict. Closes: #12231.

---

changelog/16970.txt
command/agent/cache/api_proxy.go
command/agent/cache/handler.go
command/agent/cache/lease_cache.go
command/agent/template/template.go

It seems like ignoring retry config with caching set was originally intentional behaviour, but it definitely doesn't seem right to me nor I guess the many, many customers that have reported it as a bug.
With this change, Agent will respect the retry settings, regardless of whether caching is enabled (in other words, enabling caching will have the same retry behaviour as not doing). Note that it will still continue to check the cache and the layering still works fine.
For those interested (as we're new to Agent on Core), I used the following config HCL for this change (I modified bits to reproduce different cases, of course):
```
violet@violet-TX54KFJWXM vault % cat ../vault_agent.hcl
pid_file = "/tmp/pidfile"
vault {
address = "http://127.0.0.1:8200"
tls_skip_verify = true
retry { …
```

VAULT-6575 Vault agent respects retry config even with caching set

---

website/content/docs/secrets/transit/key-wrapping-guide.mdx

This adds the `noheader` flag to the `wrapKey` command. This flag is required for the output to be decrypted successfully by Vault

Add missing flag to wrapKey command in key wrapping guide

---

vault/plugin_catalog.go

to only print errors once we have failed the last attempt to dispense a plugin. The debug logs were a bit too noisy otherwise.

plugin: update debug logging

---

builtin/logical/transit/path_import.go

Part of the Transit BYOK process could error silently. This addresses that.
Addresses VAULT-7974

Account for a possible error in Transit BYOK.

---

changelog/17019.txt
vault/cluster/inmem_layer.go
vault/external_tests/raft/raft_autopilot_test.go
vault/raft.go

Failing to provide a version/upgrade_version will result in Autopilot (on ent) demoting those unversioned nodes to non-voters until we receive a heartbeat from them.  So to prevent that, fake it by using the active node's version for such nodes.

autopilot: assume nodes we haven't received heartbeats from are running the same version as we are

---

website/content/docs/commands/auth/enable.mdx
website/content/docs/commands/auth/tune.mdx

Token type is a valid option for the `auth enable` command.  This adds that to the documentation.

docs: update token type for auth enable CLI command

---

changelog/17028.txt
vault/activity_log.go
vault/activity_log_test.go
vault/testing.go

OSS parts of ent #3157.  Some activity log tests were flaky because background workers could race with them; now we overload DisableTimers to stop some of them from running, and add some channels we can use to wait for others to complete before we start testing.

Make some activity log tests less flaky

---

.circleci/config.yml
.circleci/config/commands/go_test.yml

`test-go-remote-docker` and `test-go-race-remote-docker` seem to have been a little flaky lately, with [errors](https://app.circleci.com/pipelines/github/hashicorp/vault/40740/workflows/6b6a714b-9da3-4edf-9f5c-db9101e27037/jobs/505610) [like so](https://app.circleci.com/pipelines/github/hashicorp/vault/40762/workflows/95737136-c6b7-422f-b40e-955964a77e7d/jobs/505821):
```
Failed
=== RUN   TestBackend_basic
mongodbhelper.go:68: could not start docker mongo: container start failed: Error response from daemon: network 953d93bc05fe is ambiguous (4 matches found on name)
--- FAIL: TestBackend_basic (1.05s)
```
_EDIT: Also some new follow-up errors in the comment down below._
It seems that multiple concurrent calls to `docker network create vaulttest` can all succeed. On using the network, the …

CI: Delete duplicate vaulttest docker networks to improve reliability

---

changelog/17038.txt
command/secrets_enable_test.go
helper/builtinplugins/registry.go
helper/builtinplugins/registry_test.go

This PR marks the database-specific secrets engines (standalone DB) as `Pending Removal` and updates associated tests so they pass. These database engines will now be subject to the deprecation handling introduced in https://github.com/hashicorp/vault/pull/17005

Mark database-specific secrets engines Pending Removal

---

ui/app/templates/components/keymgmt/key-edit.hbs

[The following test](https://app.circleci.com/pipelines/github/hashicorp/vault-enterprise/16638/workflows/56da18b4-1798-4945-9738-b3b9a837ad7f/jobs/406447) was failing on enterprise because the unless was passing an empty object to the `LinkTo @query` param. 
Acceptance | Enterprise | keymgmt: it should add new key and distribute to provider.
I did a search for similar situations on query but we have a LOT of LinkTos, so it was tough to look through them all. If anyone has any thoughts of why suddenly this would fail, I'm all ears. I've been running enterprise locally for PKI work and haven't seen the failure, but I'm seeing it now on main. There doesn't appear to be any PRs that touched this code recently either.
Notes: I ran test locally, they failed on this test before the fix and …

Fix LinkTo @query param on KMSE

---

changelog/16959.txt
ui/app/components/link-status.js
ui/app/components/nav-header.js
ui/app/models/cluster.js
ui/app/models/node.js
ui/app/styles/core/navbar.scss
ui/app/templates/components/link-status.hbs
ui/app/templates/components/nav-header.hbs
ui/mirage/handlers/hcp-link.js
ui/mirage/handlers/index.js
ui/tests/integration/components/link-status-test.js

This PR adds a new component to the nav bar to display the HCP link status. At this time, given the data returned from the API, only the connected state will trigger the banner to display (enterprise only). The warning states have been roughed in and a subsequent PR will be opened once the API is updated.

HCP Link Status

---

ui/app/templates/components/alphabet-edit.hbs
ui/app/templates/components/transform-role-edit.hbs
ui/app/templates/components/transform-show-transformation.hbs
ui/app/templates/vault/cluster/access/oidc/assignments/assignment/details.hbs
ui/app/templates/vault/cluster/access/oidc/providers/provider/details.hbs
ui/lib/core/addon/components/info-table-item-array.hbs
ui/lib/core/addon/components/info-table-item-array.js
ui/lib/core/addon/components/info-table-row.hbs
ui/tests/integration/components/info-table-item-array-test.js

In addition to cleaning up the provider details, this includes some small cleanup for the `InfoTableArray` component
one scope:
multiple:

UI: Remove trailing comma from scopes, provider details page

---

website/content/api-docs/secret/pki.mdx

- Update the documentation in regards to the private_key_format argument only controls the behavior of the private_key response field and does not modify the encoding of the private key within the pem_bundle.

Update PKI documentation to clear up PKCS8 marshalling behavior

---

changelog/17079.txt
vault/raft.go

We've seen cases like https://github.com/hashicorp/vault/issues/16010 where followers fail to start with an error:
```
core: error writing raft TLS keyring: error="node is not the leader"
```
This comes from startRaftBackend, which, when it doesn't find a raft TLS keyring in storage, decides that this must be the first node of a new raft cluster, and so attempts to create its own keyring.  However, it is incorrect, and when it tries to write the keyring it fails because we are a node of an existing raft cluster, and we just haven't yet received the log/snapshot containing the raft TLS keyring.  Indeed, we see prior to the "node is not the leader" error, the log message
```
storage.raft: raft already started, not setting up cluster
```
When that log is written, RaftBackend.SetupCluster is …

Do not attempt to write a new TLS keyring at startup if raft is already setup

---

builtin/logical/pki/path_fetch_issuers.go

This option was elided from the default value for the usage field. This results in issuers "losing" `ocsp-signing` when they're `POST` updated. Most issuers will want OCSP signing by default, so it makes sense to add this as the default.

Update issuer usage with ocsp-signing by default

---

.circleci/config.yml
.circleci/config/commands/go_test.yml

Previously, we were running into a scenario where `docker network create` would result in the following CircleCI failure:
```
++ docker network create <network-id>
Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
```
In an effort to get rid of potentially superfluous networks, simply prune unused networks before attempting to create a new one.

CI: prune docker networks before creation

---

builtin/logical/pki/backend_test.go
builtin/logical/pki/storage.go

Attempt to prevent a future bug as I had introduced with the new OCSP signing usage, by having the field defaults out of sync across the creation and update APIs for issuers. Also always return a sorted output of usages for an issuer so things that compare outputs such as terraform state files don't think the value is changing

A PKI test to verify our defaults are the same for creates and update apis

---

ui/app/models/oidc/assignment.js
ui/app/models/oidc/client.js
ui/app/models/oidc/key.js
ui/app/models/oidc/provider.js
ui/app/models/oidc/scope.js
ui/app/templates/components/oidc/provider-list.hbs
ui/app/templates/vault/cluster/access/oidc/assignments/assignment/details.hbs
ui/lib/core/addon/components/info-table-item-array.hbs
ui/lib/core/addon/components/info-table-item-array.js
ui/lib/core/addon/components/info-table-row.hbs
ui/lib/core/addon/components/search-select.js
ui/lib/core/addon/templates/components/search-select.hbs
ui/tests/acceptance/oidc-config/clients-assignments-test.js
ui/tests/integration/components/info-table-item-array-test.js
ui/tests/integration/components/search-select-test.js

Renders names instead of ids for entities and groups along with cleaning up unused capabilities checks

UI: OIDC config cleanup

---

builtin/logical/transit/path_decrypt.go
builtin/logical/transit/path_decrypt_test.go
builtin/logical/transit/path_encrypt.go
changelog/17118.txt
website/content/api-docs/secret/transit.mdx

Lets users specify an arbitrary response code iif there were user failures in a batch but also successes.

Implement partial_failure_response_code_override for batch requests

---

changelog/17124.txt
ui/app/components/secret-delete-menu.js
ui/app/templates/components/secret-delete-menu.hbs
ui/app/templates/components/secret-version-menu.hbs
ui/tests/acceptance/secrets/backend/kv/secret-test.js

The following policy grants `delete` capabilities to `some-secret` and allows [deletion of the latest version ](https://www.vaultproject.io/api-docs/secret/kv/kv-v2#delete-latest-version-of-secret) of a secret, but **does not allow** deleting a specific the version of the secret.
```
path "kv-engine-path/data/some-secret" { capabilities = ["create","read","update","delete","list"] }
path "kv-engine-path/metadata/*" { capabilities = ["create","update","delete","list","read"] }
path "kv-engine-path/undelete/*" { capabilities = ["update"] }
```
This was unclear in the UI because the delete modal appeared to offer "Delete this version" as an option. When a user selected that option, they would find that the latest version had been deleted, not an older version as expected (Version 1 in this …

UI: Fix KV engine deleting latest version instead of specified version depending on policy

---

changelog/17045.txt
website/content/api-docs/secret/azure.mdx
website/content/docs/secrets/azure.mdx

Corresponds to https://github.com/hashicorp/vault-plugin-secrets-azure/pull/104
That PR allows for permanent deletion of AzureAD apps and service principals that are created by the secrets engine. Traditionally, the Vault secrets engine does not permanently delete the service principals/apps from AzureAD when leases expire. Instead, the objects are placed in a "recycle bin," and they count toward the [limit of AzureAD objects in a tenant](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/azure-subscription-service-limits#active-directory-limits) (that limit ranges from 50k to 500k objects). So after 50k-500k leases, Vault hits the limit of objects in an Azure AD and causes all create operations on the tenant to fail.

Update Vault Azure Secrets docs for permanent deletion feature

---

enos/modules/build_local/main.tf

- When running enos scenario validate <test> the following error comes up.
```
❯ enos scenario validate managed_keys
Scenario: managed_keys [arch:arm64 backend:raft builder:local distro:ubuntu edition:ent seal:awskms]
Generate: ✅
Init: ❌
Error: Invalid provider registry host
The host "hashicorp.com" given in in provider source address "hashicorp.com/qti/enos" does not offer a Terraform provider registry.
```

Update the enos provider source in build_local

---

changelog/17124.txt
ui/app/templates/components/secret-delete-menu.hbs

Backport of UI: Fix KV engine deleting latest version instead of specified version depending on policy into release/1.10.x

---

ui/app/adapters/pki/pki-role-engine.js
ui/app/models/pki/pki-role-engine.js
ui/app/serializers/pki/pki-role-engine.js
ui/lib/core/addon/components/linked-block.js
ui/lib/pki/addon/controllers/roles/index.js
ui/lib/pki/addon/routes.js
ui/lib/pki/addon/routes/roles/index.js
ui/lib/pki/addon/routes/roles/role/details.js
ui/lib/pki/addon/routes/roles/role/edit.js
ui/lib/pki/addon/templates/roles.hbs
ui/lib/pki/addon/templates/roles/index.hbs
ui/lib/pki/addon/templates/roles/role/details.hbs
ui/lib/pki/addon/templates/roles/role/edit.hbs

This PR starts the setup for the PKI roles model and gets the Roles List View setup.
The Roles model will undergo some tweaks, but the connection and openAPI are setup here.  I can't finalize the model until I work through some questions with the backend and design. The model will be finalized when I work on the Roles Create view.
Below is a video of the changes. I start by showing the empty state, routing, and then the model with all of the OpenAPI params at the end. (The video makes it look like I'm missing some border styling, it's just the video quality).
https://user-images.githubusercontent.com/6618863/190208559-9a1a5ff9-c8ce-4377-9038-b9f239ede67f.mov

PKI Role's model and List view

---

builtin/credential/cert/backend.go
builtin/credential/cert/path_login.go
changelog/17138.txt

Currently Vault doesn't do this, so CRLs aren't in force until the CRL read or write endpoint is hit.

Load existing CRLs on startup and after invalidate

---

tools/semgrep/ci/loopclosure.yml

`go tool vet -loopclosure` does not find all instances of loop closure captures. Add a check to catch loop vars in goroutines. This is taken from the Nomad project's semgrep rules: https://github.com/hashicorp/nomad/blob/d83ae577f3073e226e9740019eefc3c08ece161f/.semgrep/loopclosure.yml

semgrep: Enforce no loop vars in goroutines

---

changelog/17091.txt
command/agent.go
command/agent/auth/auth.go
command/agent/auth/auth_test.go
command/agent/config/config.go
command/agent/config/config_test.go
command/agent/config/test-fixtures/config-method-exit-on-err.hcl
website/content/docs/agent/autoauth/index.mdx

When Agent's auto-auth encounters a problem it will retry indefinitely, regardless of the error. This configurable allows users to specify if Vault should exit on auto-auth error, similar to `exit_on_err` in the caching engine: https://www.vaultproject.io/docs/agent/caching#exit_on_err.
At the moment this will exit on any error, but I'm open to only exiting on some errors (such as 400 errors).

agent/auto-auth: add exit_on_err configurable

---

changelog/17139.txt
ui/app/routes/vault/cluster.js
website/content/api-docs/system/internal-ui-resultant-acl.mdx

In PR #12713 the `/sys/internal/ui/resultant-acl` endpoint was made to be authenticated. As mentioned in issue #14097 the UI was continuing to make requests to this endpoint when unauthenticated so that has been updated as well as an update to the api doc.

Prevent Requests to resultant-acl Endpoint When Unauthenticated

---

builtin/logical/pki/cert_util.go
builtin/logical/pki/cert_util_test.go
builtin/logical/pki/path_intermediate.go
builtin/logical/pki/path_issue_sign.go
builtin/logical/pki/path_root.go
builtin/logical/pki/storage_test.go
builtin/logical/pki/util.go
changelog/17073.txt

This adds a warning when TTL is over-written, resolving https://github.com/hashicorp/vault/issues/10740 ;
In order to do that, we need to be able to pass warnings through several functions.

Add "plumbing" for surfacing warnings, and warning overwriting ttl

---

go.mod
go.sum

This PR updates vault-plugin-auth-jwt to [v0.14.0](https://github.com/hashicorp/vault-plugin-auth-jwt/releases/tag/v0.14.0).
Steps:
```
go get github.com/hashicorp/vault-plugin-auth-jwt@v0.14.0
go mod tidy
```

auth/jwt: updates plugin to v0.14.0

---

changelog/17152.txt
command/secrets_enable_test.go
go.mod
go.sum
helper/builtinplugins/registry.go
helper/builtinplugins/registry_test.go

This PR updates vault-plugin-secrets-openldap to [v0.9.0](https://github.com/hashicorp/vault-plugin-secrets-openldap/releases/tag/v0.9.0).
Additionally, this adds the "ldap" secrets engine to the plugin registry. Eventually, the ability to enable/disable the "ad" and "openldap" secrets engines will be deprecated in favor of the unified "ldap" secrets engine.
Steps:
```
go get github.com/hashicorp/vault-plugin-secrets-openldap@v0.9.0
go mod tidy
```

Adds ldap secrets to plugin registry and updates to v0.9.0

---

changelog/16240.txt
changelog/17164.txt
go.mod
go.sum

https://github.com/hashicorp/vault-plugin-secrets-kubernetes/releases/tag/v0.2.0
Also moved the changelog entry from #16240 to this PR, since #16240 was the associated docs update.

secrets/kubernetes: upgrade to v0.2.0

---

changelog/17162.txt
go.mod
go.sum

https://github.com/hashicorp/vault-plugin-auth-kubernetes/releases/tag/v0.13.2

auth/kubernetes: upgrade to v0.13.2 in release/1.11.x

---

go.mod
go.sum

Bump to first released version of the [redis elasticache plugin](https://github.com/hashicorp/vault-plugin-database-redis-elasticache).
```
go get github.com/hashicorp/vault-plugin-database-redis-elasticache@v0.1.0
go mod tidy
```

+ upgrade redis-elasticache plugin to v0.1.0

---

changelog/17160.txt
go.mod
go.sum

Updates `vault-plugin-auth-gcp` to [v0.14.0](https://github.com/hashicorp/vault-plugin-auth-gcp/releases/tag/v0.14.0)
Steps:
```
go get github.com/hashicorp/vault-plugin-auth-gcp@v0.14.0
go mod tidy
```

update auth/gcp to v0.14.0

---

changelog/17174.txt
go.mod
go.sum

This PR updates vault-plugin-secrets-gcp to [v0.14.0](https://github.com/hashicorp/vault-plugin-secrets-gcp/releases/tag/v0.14.0).
Steps:
```
go get github.com/hashicorp/vault-plugin-secrets-gcp@v0.14.0
go mod tidy
```

secrets/gcp: updates plugin to v0.14.0

---

website/content/docs/configuration/service-registration/index.mdx

Adds links to service registration providers to the overview page for service registration: https://developer.hashicorp.com/vault/docs/configuration/service-registration .
https://hashicorp.atlassian.net/browse/VAULT-8455

Add links for service registration provides

---

changelog/17172.txt
go.mod
go.sum

Update terraform secrets plugin to v0.6.0.
```
go get github.com/hashicorp/vault-plugin-secrets-terraform/@v0.6.0
go mod tidy
```

Update terraform secrets version to v.0.6.0

---

builtin/credential/cert/backend.go
builtin/credential/cert/path_crls.go
builtin/credential/cert/path_crls_test.go
builtin/credential/cert/path_login.go
changelog/17136.txt
website/content/docs/auth/cert.mdx
website/content/docs/auth/jwt/oidc-providers/google.mdx

Extends path_crl to accept either a CRL in PEM or DER format _or_ a URL for the CRL Distribution Point.  In the latter case, we periodically fetch that CRL according to it's validity dates.

Fetch CRLs from a user defined URL

---

builtin/credential/cert/path_crls_test.go

This race was added in #17136 but doesn't affect the shipped binary as it exists solely in the tests. The test would race against the periodic func for access to these variables.

Fix race in cert auth tests

---

builtin/logical/pki/backend.go
builtin/logical/pki/crl_test.go
builtin/logical/pki/crl_util.go

Core has recently seen some data races during `SystemView`/replication updates between them and the PKI subsystem. This is because this `SystemView` access occurs outside of a request (during invalidation handling) and thus the proper lock isn't held.
Because replication status cannot change within the lifetime of a plugin (and instead, if a node switches replication status, the entire plugin instance will be torn down and recreated), it is safe to cache this once, at plugin startup, and use it throughout its lifetime.
Thus, we replace this `SystemView` access with a stored boolean variable computed ahead of time.

Don't race for CRL rebuilding capability check

---

website/content/api-docs/system/managed-keys.mdx

Missing documentation update that occurred only in ENT from a PR #2835

Bring back managed key documentation update from ENT to OSS

---

website/content/docs/secrets/transit/index.mdx

🧵 [Slack](https://hashicorp.slack.com/archives/C012RTGJR1V/p1663398926721949)
It was reported that the links to Transit secrets engine API doc is broken.  This PR is to fix the URL:  `/secrets/` --> `/secret/`

Fix a broken URL in Transit API doc

---

changelog/17199.txt
go.mod
go.sum

vault-plugin-secrets-gcpkms-v0.13.0 does not bring in any new changes. This PR only provides the necessary branching/tagging for potential vault-1.12.x specific updates.

fix: upgrade vault-plugin-secrets-gcpkms to v0.13.0

---

changelog/17180.txt
go.mod
go.sum

Steps:
```
go get github.com/hashicorp/vault-plugin-secrets-azure@v0.14.0
go mod tidy
```

bump secrets/azure to v0.14.0

---

go.mod
go.sum

vault-plugin-secrets-alicloud-v0.13.0 does not bring in any new changes. This PR only provides the necessary branching/tagging for potential vault-1.12.x specific updates.

fix: upgrade vault-plugin-secrets-alicloud to v0.13.0

---

go.mod
go.sum

This PR updates vault-plugin-secrets-mongodbatlas to [v0.8.0](https://github.com/hashicorp/vault-plugin-secrets-mongodbatlas/releases/tag/v0.8.0).
Steps:
```
go get github.com/hashicorp/vault-plugin-secrets-mongodbatlas@v0.8.0
go mod tidy
```

secrets/mongodbatlas: upgrade plugin to v0.8.0

---

changelog/17153.txt
ui/app/components/pki/config-pki.js
ui/app/models/pki/pki-config.js
ui/app/templates/components/pki/config-pki.hbs
ui/lib/core/addon/components/form-field.js
ui/tests/integration/components/pki/config-pki-test.js

Adds the `disable` param to CRL config while saving whatever the last `expiry` value was, so when re-enabling the last set TTL duration is there.

UI: Add 'disable' to CRL config

---

changelog/17204.txt
vault/auth.go

Example panic this should avert: https://app.circleci.com/pipelines/github/hashicorp/vault-enterprise/16970/workflows/b790bc33-bd1f-485b-9025-e4e4b5dd023b/jobs/409253

Handle when pluginCatalog.Get returns (nil,nil) during cred backend creation

---

api/auth/approle/go.mod
api/auth/approle/go.sum
api/auth/aws/go.mod
api/auth/aws/go.sum
api/auth/azure/go.mod
api/auth/azure/go.sum
api/auth/gcp/go.mod
api/auth/gcp/go.sum
api/auth/kubernetes/go.mod
api/auth/kubernetes/go.sum
api/auth/ldap/go.mod
api/auth/ldap/go.sum
api/auth/userpass/go.mod
api/auth/userpass/go.sum

Update all Vault auth submodules to the latest release of api/v1.8.0

update vault auth submodules to api/v1.8.0

---

changelog/17187.txt
vault/core_metrics.go
vault/ha.go
vault/logical_system_raft.go
vault/raft.go
vault/rollback.go

Without this change, the "grab" locking goroutine looks the same regardless of who was calling grabLockOrStop, so there's no way to identify one of the deadlock parties.
Example of the confusion we're trying to eliminate:
```
=== CONT  TestSecret_TokenAccessor/auth
POTENTIAL DEADLOCK:
Previous place where the lock was grabbed
goroutine 8799 lock 0xc000ccd298
../../init.go:230 vault.(*Core).Initialize { c.stateLock.Lock() } <<<<<
../../testing.go:341 vault.TestCoreInitClusterWrapperSetup { result, err := core.Initialize(context.Background(), initParams) }
../../testing.go:2037 vault.(*TestCluster).initCores { bKeys, rKeys, root := TestCoreInitClusterWrapperSetup(t, leader.Core, leader.Handler) }
../../testing.go:1759 vault.NewTestCluster { testCluster.initCores(t, opts, addAuditBackend) } …
```

Break grabLockOrStop into two pieces to facilitate investigating deadlocks

---

ui/app/adapters/pki/pki-issuer-engine.js
ui/app/models/pki/pki-issuer-engine.js
ui/app/models/pki/pki-role-engine.js
ui/app/serializers/pki/pki-issuer-engine.js
ui/lib/pki/addon/controllers/issuers/index.js
ui/lib/pki/addon/controllers/roles/index.js
ui/lib/pki/addon/routes.js
ui/lib/pki/addon/routes/configuration/create/generate-csr.js
ui/lib/pki/addon/routes/configuration/create/generate-root.js
ui/lib/pki/addon/routes/configuration/create/import-ca.js
ui/lib/pki/addon/routes/issuers/index.js
ui/lib/pki/addon/templates/configuration/create/generate-csr.hbs
ui/lib/pki/addon/templates/configuration/create/generate-root.hbs
ui/lib/pki/addon/templates/configuration/create/import-ca.hbs
ui/lib/pki/addon/templates/issuers.hbs
ui/lib/pki/addon/templates/issuers/index.hbs
ui/lib/pki/addon/templates/roles/index.hbs

This PR adds the list view for the default issuer. Confirmed with Backend and Design that at this point we cannot get all the information Design originally wanted on this list view without iterating over each issuer and making additional network request. We put this as a nice-to-have ticket in the future as it's outside the scope of this ticket (design originally thought this data was available on the LIST endpoint).
**Here are the designs:**
**Here is the outcome:** 
* Not every issuer will have a issuer_name so in those cases we use the id.
* Flight icons won't let us go smaller than what we are currently using and thus they don't fit the designs. Design gave okay to not use the info icons as they did not look great with the current sizing available to us.
* We can't know if it's an …

PKI Issuer List view

---

ui/app/components/link-status.js
ui/app/templates/components/link-status.hbs
ui/tests/integration/components/link-status-test.js

During manual testing with the backend it was discovered that `connecting` was being returned without a timestamp or error message for `hcp_link_status`. While this will be fixed on the backend to always return in the expected format, the frontend checks were too loose and allowed for possible uncaught errors when parsing the `hcp_link_status` string. Additional logic was added to check for timestamp and error existence. _Hashicorp Cloud Platform_ has also been abbreviated to _HCP_ in the messaging for brevity.

HCP Link Status Checks

---

go.mod

Last bit of work on OSS to update Vault on main to start using the SDK that says we are now building version 1.13.0-dev1

Update Vault on main to pull in SDK 1.13 version bump

---

ui/app/adapters/pki/pki-certificate-engine.js
ui/app/models/pki/pki-certificate-engine.js
ui/app/serializers/pki/pki-certificate-engine.js
ui/lib/pki/addon/controllers/certificates/index.js
ui/lib/pki/addon/routes.js
ui/lib/pki/addon/routes/certificates/index.js
ui/lib/pki/addon/routes/roles/index.js
ui/lib/pki/addon/templates/certificates.hbs
ui/lib/pki/addon/templates/certificates/index.hbs
ui/lib/pki/addon/templates/issuers/index.hbs
ui/lib/pki/addon/templates/roles/index.hbs

Similar to the Issuer list view there are some components to the design that are not on the List endpoint. I moved these to a nice-to-have ticket and we'll need to do a bit of research re: how many certificates a user can expect and if there are performance concerns for iterating over each to make the network request required to retrieve the information.
**Designs:**
What we have:
**Notes**:
* No milestone because one is not created for 1.13 and there is already a 1.12 branch cut. I do not need to backport this PR so holding off on a milestone until it's made.
* I'm waiting on some feedback from design, but it's not critical I wait for them to move forward. I have made notes in the code where I am waiting for design feedback (specifically the EmptyState text and the dropdown list menu …

PKI Certificates List View

---

command/agent/config/config_test.go

A test was missing its file suffix and only passing because of the error-checking logic.

agent: Fix missing file suffix in config test

---

sdk/plugin/grpc_backend_server.go

This PR fixes a concurrent map write panic seen in testing multiplexed secrets/auth external plugins. See error below for top of goroutine stack where this occurred.
```
2022-09-20T22:00:19.435-0700 [DEBUG] auth.vault-plugin-auth-userpass-mux-ext.auth_vault-plugin-auth-userpass-mux-ext_a4786ce6.vault-plugin-auth-userpass-mux-ext.vault-plugin-auth-userpass-mux-ext: fatal error: concurrent map writes
2022-09-20T22:00:19.443-0700 [DEBUG] auth.vault-plugin-auth-userpass-mux-ext.auth_vault-plugin-auth-userpass-mux-ext_a4786ce6.vault-plugin-auth-userpass-mux-ext.vault-plugin-auth-userpass-mux-ext
2022-09-20T22:00:19.443-0700 [DEBUG] auth.vault-plugin-auth-userpass-mux-ext.auth_vault-plugin-auth-userpass-mux-ext_a4786ce6.vault-plugin-auth-userpass-mux-ext.vault-plugin-auth-userpass-mux-ext: …
```

Fixes concurrent map writes in GRPC plugin server setup

---

website/content/docs/agent/autoauth/index.mdx

This PR aims to clarify some confusion around the differing `sinks` specifications in the auto-auth config. Relevant discussion in #7380.

docs: Update agent autoauth sinks examples

---

builtin/credential/approle/backend.go
builtin/logical/consul/backend.go
plugins/database/postgresql/postgresql.go
sdk/database/dbplugin/v5/grpc_server.go
sdk/database/dbplugin/v5/middleware.go
sdk/helper/consts/consts.go
sdk/helper/pluginutil/multiplexing.go
vault/auth.go
vault/external_plugin_test.go
vault/identity_store_entities_test.go
vault/logical_system.go
vault/mount.go
vault/plugin_catalog.go
vault/plugin_reload.go

When registering a plugin, we check if the request version matches the self-reported version from the plugin. If these do not match, we log a warning.
This uncovered a few missing pieces for getting the database version code fully working.
We added an environment variable that helps us unit test the running version behavior as well, but only for approle, postgresql, and consul plugins.

Check if plugin version matches running version

---

command/base_helpers.go
command/base_helpers_test.go

Previously we got an error when using stdin as the path argument in a command:
```shell-session
$ vault policy write myapp-kv-ro - <<EOF
path "secret/data/myapp/*" {
capabilities = ["read", "list"]
}
EOF
Command flags must be provided before positional arguments. The following arguments will not be parsed as flags: [-]
Success! Uploaded policy: myapp-kv-ro
```
Now:
```shell-session
$ vault policy write myapp-kv-ro - <<EOF
path "secret/data/myapp/*" {
capabilities = ["read", "list"]
}
EOF
Success! Uploaded policy: myapp-kv-ro
```
I've skipped adding a changelog because I don't believe the original code has been released yet.

CLI: Fix erroneous warning when reading from stdin

---

changelog/17251.txt
go.mod
go.sum

Steps:
```bash
go get github.com/hashicorp/vault-plugin-auth-alicloud@v0.13.0
go mod tidy
```

Upgrade vault-plugin-auth-alicloud to v0.13.0

---

builtin/plugin/backend.go
vault/plugin_reload.go

This PR fixes an issue where multiplexed v5 plugin backends aren't initialized after a manual [plugin reload](https://www.vaultproject.io/docs/commands/plugin/reload). This call to `Initialize()` is a no-op for backends < v5 which rely on lazy loading for initialization (see [backend.go#L265-L269](https://github.com/hashicorp/vault/blob/main/builtin/plugin/backend.go#L265-L269)). v5 backends do not rely on lazy loading for initialization (unless the plugin process is killed, which was recently fixed in https://github.com/hashicorp/vault/pull/17140). Reload of a v5 backend results in a new plugin process, so we must initialize the backend at this location. Otherwise, the plugin will not be initialized via [request handling logic](https://github.com/hashicorp/vault/blob/main/builtin/plugin/v …

Fixes multiplexed plugin initialization after manual plugin reload

---

api/sys_mounts.go
command/auth_enable.go
command/auth_tune.go
command/auth_tune_test.go
command/commands.go
command/plugin_register_test.go
command/secrets_enable.go
command/secrets_tune.go
command/secrets_tune_test.go
vault/external_plugin_test.go
vault/logical_system.go
vault/mount.go
vault/plugin_catalog.go

* Adds `-plugin-version` flag to `vault secrets tune` and `vault auth tune` commands
* Also adds `-plugin-version` flag to `vault secrets enable` which slipped unnoticed previously
* The `plugin_register_test.go` tests uncovered a bug in listing plugins. If you register both an auth and secrets "my-plugin"@v1.0.0, listing plugins would previously report two v1.0.0 plugins called "my-plugin" for both auth and secret types, giving 4 plugins instead of the correct 2.
I had to move the `PluginVersion` field from `MountInput` to the embedded `MountInputConfig` in order to support the way the `tune` commands gather their inputs. Normally, those two structs' fields would correspond to fields in `MountEntry` and its embedded `MountConfig` respectively, but I have currently left the `Version` …

CLI: Tune plugin version for auth/secret mounts

---

changelog/17281.txt
vault/quotas/quotas.go

We current have a goroutine leak since as part of creating RLQs, we create a goroutine as part of `memorystore.New` - however, as part of `Reset`, we don’t actually call `Close` on it. As a result, upon seal/unseal, a lot of these goroutines get stranded.
This could cause an issue with a combination of high leadership changes and high quotas.
I tested this manually and this definitely fixes things. Adding a non-manual test doesn't seem particularly easy/possible due to our existing leaks.

VAULT-8630 Fix goroutine leak from RLQ initialize

---

ui/app/templates/components/oidc/provider-form.hbs
ui/lib/core/addon/components/search-select.js
ui/lib/core/addon/templates/components/search-select.hbs
ui/tests/integration/components/search-select-test.js

This functionality was originally added so that a user would be able to clean up an OIDC provider, and remove any allowed app's that may have been deleted. As you can see from the screenshot, only the `client_id` renders, and not the rest of the model information when a client has been deleted.
Search select is used widely so decided to add a param so that the tooltip _only_  renders if we expect it to (as we do in the `provider-form`). This component will be fully refactored in 1.13, so the intent here is a quick fix to avoid wide-reaching consequences where we may not anticipate them.

UI: Pass param so infotooltip conditionally renders

---

vault/auth_test.go
vault/logical_system.go
vault/logical_system_test.go
vault/plugin_catalog.go
vault/plugin_catalog_test.go

For example, if you have registered a versioned kubernetes auth plugin, omitting the version when mounting kubernetes auth will always select the versioned plugin, but you can specify the builtin version instead like so:
```bash
vault auth enable -plugin-version="v0.14.0+builtin" kubernetes
```
Also disallows registering any plugins with a `builtin` identifier in the metadata. I referenced [here](https://semver.org/#spec-item-10) for the format and terminology of the tag metadata.

Plugins: Allow explicitly specifying the builtin version of a plugin

---

builtin/plugin/backend_test.go
http/sys_auth_test.go
sdk/plugin/grpc_backend_test.go
sdk/plugin/mock/backend.go
vault/auth.go
vault/external_plugin_test.go
vault/logical_system_test.go
vault/mount.go
vault/plugin_catalog.go
vault/plugin_reload.go

There were a few cases where `running_plugin_version` wasn't getting populated, but it should always be up to date and in sync with the `running_sha256` field now.
I also added a small tweak to plugin catalog registration to ensure we always capture output of the `Versioner` interface on registration, so we should be able to just use the mount entry's configured version immediately after starting a new backend, as that will be the version it used to query the catalog. ~I'll try to write an additional test for that, but wanted to get some feedback while that's in progress.~ Turns out the existing tests exercise that functionality quite nicely.

Plugins: Update running version everywhere running sha256 is set

---

website/content/api-docs/secret/pki.mdx
website/content/docs/secrets/pki/considerations.mdx

---
Seeing as https://github.com/golang/go/issues/53754 has not received any attention upstream, it is best we add this shortcoming of Go's CRL generation to the documentation.

Add note about issuer naming and CRLs

---

command/namespace_patch.go

Namespace not found for `namespace patch` command is now based on 404 response. Fix not found error from `No namespace found: %!s(<nil>)` (erroneously included err var before 404 logic was introduced) to `Namespace not found`

fix namespace patch not found error message

---

enos/enos-scenario-autopilot.hcl

This scenario was getting occasional errors from AWS complaining that `t3a.small` instances weren't available in all AZs within the region. The `az_finder` module limits the VPC to only the AZs that have the requested instance type. Also, forgot some tags!

Enos: Add missing tags and use az_finder for AZs to Autopilot scenario

---

changelog/17308.txt
command/main.go

Per the consensus of most programs, and mirroring the GNU Coding Standards for CLI design, when users request `-help` explicitly via the CLI, this should be written to `stdout` to allow paging of output. `stderr` is (implicitly) fine when an invalid usage triggers the help text however.
In our case, `mitchellh/cli` helpfully adds a `HelpWriter` that we previously set to `stderr` explicitly. This writer is only called to print user-requested help text; it is not called on error cases (e.g., bad usage triggering additional help text to the user).
Thus it should safely be settable to `stdout`, enabling pagers without additional redirects and without affecting any user scripts relying on stdout not containing help text when bad usage occurs (or similarly, that stderr contains help when bad …

Write explicit -help output to stdout

---

website/content/docs/agent/template.mdx

Our docs could be better here. In particular, we should recommend the array approach, for more safety and ease. It's generally considered best practice to use an array for commands like this, as far as I'm aware.

VAULT-8144 Improve docs around exec

---

changelog/16688.txt
changelog/16982.txt
changelog/17167.txt
changelog/17289.txt
changelog/plugin-versioning.txt

Changelogs for plugin versioning PRs: #16688, #16982, #17015, #17088, #17167, #17171, #17182, #17217, #17266, #17277, #17289, #17292, #17293, #17301, #17304

Plugin versioning changelog entries

---

website/content/api-docs/system/managed-keys.mdx

- The existing test/sign managed key api now has two new api params allowing an operator to specify to use RSA PSS signatures (use_pss) and to specify the hashing algorithm to use (hash_algorithm)
This brings back the documentation update within the corresponding enterprise PR.

Update docs for new test/sign params for managed key api and GCP parameters

---

builtin/credential/cert/path_crls_test.go

The periodic function only runs every 50ms, so waiting 60ms means we might not be done fetching the CRL on slower CI systems or with high test parallelism.
Tested with:
> untilfail -parallel=-9 ../../../cert.test -test.run=TestCRLFetch -test.count=1 -test.v
And shown to reliably fail before, fixed after.
---
```
[cipherboy@xps15 cert]$ untilfail -parallel=-3 ../../../cert.test -test.run=TestCRLFetch -test.count=1 -test.v
32
got failure after 33 runs, err: "exit status 1", output on stdout
=== RUN   TestCRLFetch
path_crls_test.go:191: wrong number of certs in CRL
--- FAIL: TestCRLFetch (0.08s)
FAIL
```
Test failure only; doesn't impact shipped code.

Increase sleep to fix CI cert auth test failure

---

builtin/logical/pki/crl_test.go
builtin/logical/pki/crl_util.go

When adding delta CRL support, we unconditionally added the delta indicator extension to the main CRL. We shouldn't have done this, and instead only added it conditionally when we were building delta CRLs.

Remove delta indicator on main CRL

---

builtin/credential/approle/backend_test.go
builtin/credential/approle/path_login.go
builtin/credential/approle/path_role_test.go
builtin/credential/ldap/backend.go
builtin/credential/userpass/path_login.go
builtin/logical/aws/iam_policies_test.go
changelog/17104.txt
sdk/logical/error.go
sdk/logical/response_util.go
sdk/logical/response_util_test.go

https://hashicorp.atlassian.net/browse/VAULT-8304
The auth methods returns a specific error code “ErrInvalidCredentials” in cases where it fails due to invalid credentials for existent users.
This helps to differentiate between existent and not existent users when lockout feature is implemented to prevent brute forcing
This is only used for handling lockouts and will be removed before return. This will not be returned or seen externally. 
These changes are for approle, ldap and userpass auth methods 
Added changes to RespondErrorCommon and also added a test to confirm that ErrInvalidCredentials is not seen externally.

Return errInvalidCredentials when wrong credentials is provided for existent users 

---

changelog/17328.txt
sdk/helper/certutil/helpers.go
sdk/helper/certutil/types.go

- When calling sign-intermediate and other apis with signature_bits value overridden with a backing managed key we did not use that value as tests for the private key type were not working.
- This was exposed with GCP managed key testing as we started failing with a backing PSS SHA512 RSA key
```
vault write  -format=json pki/root/sign-intermediate signature_bits=512 csr=@pki_intermediate.csr use_pss=true \
format=pem_bundle ttl="43800h" \
| jq -r '.data.certificate' > intermediate.cert.pem
Error writing data to pki/root/sign-intermediate: Error making API request.
URL: PUT http://127.0.0.1:8200/v1/pki/root/sign-intermediate
Code: 500. Errors:
* 1 error occurred:
* error signing cert: unable to create certificate: rpc error: code = InvalidArgument desc = The digest SHA256 is not valid for …
```

PKI: Fix managed key signatures when using specified signature_bits

---

ui/app/templates/components/link-status.hbs

This PR resolves a merge conflict from #17302 where the wrong commit was selected reverting the template copy change from HCP to Hashicorp Cloud Platform.

HCP Link Copy Fix

---

ui/lib/core/addon/components/modal.hbs
ui/tests/acceptance/enterprise-replication-test.js

After adding a modal to the `LinkStatus` component it's possible that tests previously expecting only 1 modal to be rendered would be selecting the incorrect modal. This was the case with an enterprise replication test. I added `@title` as the value for the `data-test-modal-background` attribute so that it can be individually targeted.

Replication Test Fix

---

api/sys_plugins.go
api/sys_plugins_test.go
changelog/17347.txt
command/plugin_list.go
command/plugin_list_test.go
vault/logical_system.go
vault/logical_system_test.go
website/content/docs/commands/plugin/list.mdx

I found an issue where `vault plugin list -detailed auth` returned an empty response. There was also a small bug in the `api` package's JSON tags that stopped `type` getting populated in details.
```shell-session
$ vault plugin list -detailed auth
Name    Type    Version    Deprecation Status
----    ----    -------    ------------------
```
api: Updated the typed call to always use the untyped API so that it can always include the extra details like version etc.
cli: Added `detailed` key to JSON output, and type/version to non-detailed output because a plugin name on its own is not enough to specify a plugin, so it's not very informative to just list the names.
New output:
```shell-session
$ vault plugin list secret
Name             Version
----             -------
kv …
```

cli/api: Update plugin listing to always include version info in the response

---

command/server.go
vault/mount.go
website/content/docs/commands/server.mdx

Previously the environment variable used to allow deprecated ("Pending Removal") builtins to be mounted was processed using string validation (set v. unset). It was confusing for users who might set `VAULT_ALLOW_PENDING_REMOVAL_MOUNTS=false`, which would behave exactly like `VAULT_ALLOW_PENDING_REMOVAL_MOUNTS=true`. Change this logic to instead be processed as a boolean in accordance with the principle of least surprise.

core: Parse VAULT_ALLOW_PENDING_REMOVAL_MOUNTS as bool

---

.github/workflows/build.yml
.github/workflows/enos-run.yml

As of 1.11.x, Vault uses the Build Date for licensing. 78e0656b5544359e7018aa8a39069d90c68bc0c3 updated the build logic to use a new `product-metadata` job, and missed one older usage. As such, `VAULT_BUILD_DATE` was left unset and the Build Date was left empty.
This was properly caught in smoke testing. A further update should use the smoke tests to identify regressions before they're merged. For now, let's just make the change to get the tests passing.

build: Update VAULT_BUILD_DATE to use product-metadata job output

---

changelog/17340.txt
vault/external_plugin_test.go
vault/plugin_catalog.go

Previously, there was a bug where the wrong path would be checked during the mount operation because we just pulled the plugin name from the config (but not during registration, because it correctly used the `command` input at that point). The plugin name often matches the binary name, but not necessarily, and it will match the name less often once people start using versioned plugins if they want two versions of the same plugin to co-exist in the plugin directory.
I've committed the test first, so hopefully that should show an error which gets fixed by the second commit once the CI finishes.

Plugins: Fix file permissions check to always use the correct path

---

changelog/16959.txt

A changelog entry for the HCP link UI banner was added by mistake and this PR is to remove it.

Remove HCP Link UI Changelog Entry

---

builtin/logical/pki/crl_util.go
changelog/17384.txt

- Restore the prior behavior of not reading in all revoked certificates if the CRL has been disabled.
- This has already been addressed on 1.12 and main in a slightly different manner

PKI: Do not read revoked certificates if CRL is disabled

---

builtin/logical/pki/crl_util.go
changelog/17385.txt

- Restore the prior behavior of not reading in all revoked certificates if the CRL has been disabled as there might be performance issues if a customer had or is still revoking a lot of certificates.
This is pulling up the missing piece from https://github.com/hashicorp/vault/pull/17384 for main and 1.12.

PKI: Do not load revoked certificates if CRL has been disabled

---

website/content/docs/release-notes/1.12.0.mdx
website/data/docs-nav-data.json

Release notes for Vault 1.12 release based on the [google doc](https://docs.google.com/document/d/15RyS_UzERLuj1_71_kgb5k5cUMtrzOtD62TqCD4TNVU/edit#heading=h.n7xfh4gvdmb)
**Outstanding items that still need to be addressed include the following:**
- PKI Telemetry Improvements section still needs two documentation links
- Redis Secrets engine section calls out an individual by name. The decision to include the person's name in the release notes has not been finalized it.
:mag: [Deploy Preview](https://vault-git-docs-release-notes-1-12-hashicorp.vercel.app/docs/release-notes/1.12.0)

Vault documentation: release notes for 1.12

---

website/content/docs/auth/jwt/oidc-providers/google.mdx

This PR fixes broken links to documentation for setting up domain-wide delegation of authority for the Google Workspace OIDC auth integration.

auth/oidc: fix documentation link anchors for Google Workspace integration

---

builtin/logical/pki/backend_test.go
builtin/logical/pki/integation_test.go
builtin/logical/pki/path_intermediate.go
builtin/logical/pki/path_manage_issuers.go
builtin/logical/pki/test_helpers.go
changelog/17388.txt
sdk/helper/certutil/helpers.go
website/content/api-docs/secret/pki.mdx
website/content/docs/secrets/pki/considerations.mdx

- Mainly to work properly with GCP backed managed keys, we need to issue signatures that would match the GCP key algorithm.
- At this time due to https://github.com/golang/go/issues/45990 we can't issue PSS signed CSRs, as the libraries in Go always request a PKCS1v15.
- Add an extra check in intermediate/generate that validates the CSR's signature before providing it back to the client in case we generated a bad signature such as if an end-user used a GCP backed managed key with a RSA PSS algorithm.
- GCP ignores the requested signature type and always signs with the key's algorithm which can lead to a CSR that says it is signed with a PKCS1v15 algorithm but is actually a RSA PSS signature

PKI: Add support for signature_bits param to the intermediate/generate api

---

website/content/docs/enterprise/pkcs11-provider/index.mdx
website/content/docs/enterprise/pkcs11-provider/oracle-tde.mdx
website/data/docs-nav-data.json

The PKCS#11 provider is being released shortly.
This moves over the preliminary docs and cleans them up.
I added them as a new section under "Vault Enterprise" -> "PKCS#11 Provider", but I am open to suggestion on if there is a better place for them, e.g., "Platforms", or somehow merging with "Vault Enterprise" -> "HSM"?
**Do not merge until the PKCS#11 provider has been released.**

docs: Add docs for PKCS#11 provider

---

changelog/16872.txt
command/agent/approle_end_to_end_test.go
command/kv_test.go
command/operator_diagnose.go
command/server.go

This fixes a couple of references to loop variables in parallel tests
and deferred functions. When running a parallel test (calling
`t.Parallel()`) combined with the table-driven pattern, it's necessary
to copy the test case loop variable, otherwise only the last test case
is exercised. This is documented in the `testing` package:
https://pkg.go.dev/testing#hdr-Subtests_and_Sub_benchmarks
`defer` statements that invoke a closure should also not reference a
loop variable directly as the referenced value will change in each
iteration of the loop.
Issues were automatically found with the `loopvarcapture` linter.

fix incorrect use of loop variable

---

ui/app/templates/components/database-connection.hbs
ui/app/templates/components/database-role-edit.hbs
ui/app/templates/components/keymgmt/key-edit.hbs
ui/app/templates/components/keymgmt/provider-edit.hbs
ui/app/templates/components/pki/role-pki-edit.hbs
ui/app/templates/components/secret-create-or-update.hbs
ui/app/templates/components/secret-edit-toolbar.hbs
ui/app/templates/components/secret-list/transform-list-item.hbs
ui/app/templates/components/secret-list/transform-transformation-item.hbs
ui/app/templates/components/transit-form-show.hbs
ui/app/templates/vault/cluster/secrets/backend/list.hbs
ui/app/templates/vault/cluster/secrets/backend/overview.hbs
ui/app/templates/vault/cluster/secrets/backend/transit-actions-layout.hbs
ui/app/templates/vault/cluster/secrets/backend/versions.hbs

As of Ember version 4.0 [the query-params helper was removed](https://deprecations.emberjs.com/v3.x#toc_ember-glimmer-link-to-positional-arguments) and the `query` arg on `LinkTo` can be passed a simple object. This PR replaces the `query-params` helper with `hash`.

Replace query-params helper with hash

---

changelog/17407.txt
ui/app/models/keymgmt/key.js
ui/tests/integration/components/keymgmt/key-edit-test.js

Fixes a bug where the first possibleValue was being populated in the dropdown Key Type but because no change event was triggered on init the `defaultValue` of `rsa-2048` was being sent, not the value shown. Setting the `defaultValue` to match the [API](https://www.vaultproject.io/api-docs/secret/key-management#create-key) fixes this. 
_Note: `defaultValue` is a attr on the ember data model. So though our form-field.hbs component does not set the defaultValue if one is specified, the model automatically adds it because it's an ember attribute._
Ran enterprise test locally and all are passing.

Bug Fix for Kymgmt keyType on default

---

changelog/17186.txt
vault/dynamic_system_view.go
vault/mount_util.go
vault/policy_store.go
vault/testing.go

Ensure that we don't try to access Core.perfStandby or Core.PerfStandby() from dynamicSystemView, which might be accessed with or without stateLock held.

Fix unsafe access to perf standby status from systemview

---

ui/.template-lintrc.js
ui/app/components/diff-version-selector.js
ui/app/templates/components/clients/history.hbs
ui/app/templates/components/configure-aws-secret.hbs
ui/app/templates/components/database-connection.hbs
ui/app/templates/components/database-role-setting-form.hbs
ui/app/templates/components/date-dropdown.hbs
ui/app/templates/components/diff-version-selector.hbs
ui/app/templates/components/file-to-array-buffer.hbs
ui/app/templates/components/generate-credentials-database.hbs
ui/app/templates/components/namespace-link.hbs
ui/app/templates/components/pgp-file.hbs
ui/app/templates/components/pki/config-pki-ca.hbs
ui/app/templates/components/raft-storage-overview.hbs
ui/app/templates/components/secret-create-or-update.hbs
ui/app/templates/components/text-file.hbs
ui/app/templates/components/transit-form-show.hbs
ui/app/templates/vault/cluster/access/identity/aliases/show.hbs
ui/app/templates/vault/cluster/access/identity/show.hbs
ui/app/templates/vault/cluster/access/leases/list.hbs
ui/app/templates/vault/cluster/access/mfa/methods/method/index.hbs
ui/app/templates/vault/cluster/secrets/backends.hbs
ui/lib/core/addon/templates/components/masked-input.hbs
ui/lib/core/addon/templates/components/navigate-input.hbs
ui/lib/core/addon/templates/components/shamir-flow.hbs
ui/lib/core/addon/templates/components/shamir-modal-flow.hbs
ui/lib/replication/addon/templates/components/replication-summary.hbs
ui/lib/replication/addon/templates/mode.hbs

There were no new template lint errors after the Ember 4.4 upgrade but warnings left over from the previous upgrade were cleaned up.

Template lint warning clean up

---

api/kv_test.go
api/kv_v2.go
changelog/17395.txt

This handles the case in which users are using the new `KV_V2` client library with an older version of Vault (~1.8) that doesn't have an implementation for `custom_metadata`. Currently this use case is failing when attempting to read. 
#16870

Fix for KV_V2 Custom Metadata Bug

---

builtin/logical/pki/ocsp.go
builtin/logical/pki/path_fetch_issuers.go
website/content/api-docs/secret/pki.mdx
website/content/docs/secrets/pki/considerations.mdx

This fixes OCSP's handling of the issuer's RevocationSigAlgo choice. With the exception of PSS (which `x/crypto/ocsp` apparently doesn't support...), this now respects that value.
Due to the shortcomings in the library, a note has been added to the issuer (when PSS is used here) and to the documentation.

Fix RevocationSigAlgo support in OCSP

---

vault/external_plugin_test.go

We are specifically checking that the writes are now allowed for group and other.
I don't know how this test was passing on non-arm64 platforms, but hopefully this should fix it.

Don't allow write perms to plugins in test

---

website/content/api-docs/secret/pki.mdx

Addresses two feedback items on API docs: 
- `signature_bits` applies relative to the _issuer's_ key type.
- `key_type=any` doesn't allow generation of keys/certs, only allows signing arbitrary CSRs.

Better docs on PKI key stuff

---

builtin/logical/pki/backend_test.go
builtin/logical/pki/crl_test.go
builtin/logical/pki/path_fetch_issuers.go
builtin/logical/pki/path_manage_issuers.go
builtin/logical/pki/path_root.go
sdk/helper/certutil/certutil_test.go
sdk/helper/certutil/helpers.go

GCP restricts keys to a certain type of signature, including hash algorithm, so we must provision our RevocationSigAlg from the root itself unconditionally in order for GCP to work.
This does change the default, but only for newly created certificates.
Additionally, we clarify that CRL building is not fatal to the import process.
---
Also fixes round-tripping of rev-sig-algo and adds a test for it.

Fix RevocationSigAlg provisioning in GCP

---

website/content/docs/commands/operator/raft.mdx

Clarify in `docs` that if a server surpasses the `dead-server-last-contact-threshold` then it cannot rejoin the cluster without being reinitialized.

Add 'note' for surpassing dead server threshold time

---

website/content/api-docs/secret/ldap.mdx

This PR updates the API documentation for the LDAP secrets engine. 
Notable changes include:
- Making the sequencing of headings, parameters, and sample requests/responses more consistent
- Adding documentation for service account check-out feature that came from the [AD secrets engine](https://www.vaultproject.io/api-docs/secret/ad#library-management) (slight modifications to the docs)
- Adding the new `last_password` field in the static-creds response
- Adding new configuration parameters

secrets/ldap: updates API documentation

---

api/sys_plugins.go
api/sys_plugins_test.go
command/plugin_deregister_test.go
command/plugin_info.go
command/plugin_info_test.go
command/plugin_reload_test.go
command/plugin_test.go
vault/logical_system.go

Adds `-version` flag for querying, and reported version to output:
Versioned plugin:
```shell-session
$ vault plugin info -version=1.0.0 secret consul
Key                   Value
---                   -----
args                  []
builtin               false
command               vault-plugin-secrets-consul-1
deprecation_status    n/a
name                  consul
sha256                1684ab47eae06ec5dc6e17089f2ce669b6bbd30e6b9c9670692a5bb2e37eb4db
version               v1.0.0
```
Builtin plugin:
```shell-session
$ vault plugin info secret azure
Key                   Value
---                   -----
args                  []
builtin               true
command               n/a
deprecation_status    supported
name                  azure
sha256                n/a
version …
```

Plugins: Add -version flag to 'vault plugin info'

---

builtin/logical/pki/backend_test.go
changelog/16700.txt
sdk/helper/certutil/helpers.go

When UseCSRValues is true (as is the case on the sign-verbatim endpoint), all extensions including Subject Alternative Names are copied from the CSR to the final certificate.
If the Subject Alternative Name in question contains any othernames (such as a Microsoft UPN) the SAN extension is added again a few lines later as a workaround for an encoding issue (by function HandleOtherSANs).
This way you end up with two copies of the SAN extension in the final certificate.
Having duplicate x509v3 extensions is invalid and is rejected by openssl on Ubuntu 20.04 (but not on Ubuntu 18.04), and is also rejected by Go in x509.ParseCertificate since https://github.com/golang/go/issues/50988 (part of Go 1.19).
In this fix I do not copy the extension from the CSR if it will already be added by …

Fix for duplicate SANs in signed certificates

---

builtin/logical/pki/crl_test.go
builtin/logical/pki/crl_util.go

When revoking an issuer, we immediately force a full rebuild of all CRLs (complete and delta). However, we had forgotten to guard the delta CRL's inclusion of augmented issuers, resulting in double-listing the issuer's serial number on both the complete and the delta CRL. This isn't necessary as the delta's referenced complete CRL number has incremented to the point where the issuer itself was included on the complete CRL.
Avoid this double reference and don't include issuers on delta CRLs; they should always appear only on the complete CRL.

Don't include issuers on delta CRLs

---

vault/activity_log_util_common.go
vault/activity_log_util_common_test.go

Vault will panic when requesting the current month's client counts if no records exist.
To reproduce, make a request to `/sys/internal/counters/activity` with `start_time` and `end_time` values that fall within the current month. Example:
```
curl -H "X-Vault-Token: $VAULT_TOKEN" "$VAULT_ADDR/v1/sys/internal/counters/activity?end_time=2022-10-06T00:00:00Z&start_time=2022-10-01T00:00:00Z"
```
This will produce the following panic:
```
2022-10-07T10:11:59.672-0400 [INFO]  http: panic serving 127.0.0.1:51376: runtime error: index out of range [0] with length 0
goroutine 799 [running]:
net/http.(*conn).serve.func1()
/usr/local/go/src/net/http/server.go:1850 +0xbf
panic({0x6018460, 0xc001392f18})
/usr/local/go/src/runtime/panic.go:890 +0x262 …
```

Fix off by one err in current month client count computation

---

changelog/17340.txt
vault/external_plugin_test.go
vault/plugin_catalog.go

Plugins: Fix file permissions check to always use the correct path
* Add failing test for when command != plugin name
* wrapFactoryCheckPerms uses pluginCatalog.Get to fetch the correct command
* Use filepath.Rel for consistency with plugin read API handler

backport/1.12.x: #17340

---

ui/tests/acceptance/enterprise-transform-test.js

Good old settled. Inconsistent flakyness but it does fail locally sometimes if I run just Enterprise test or I run the whole suite (not if I just run -f=transform).

Fix transform secrets flaky test

---

website/content/docs/secrets/ldap.mdx

This PR updates the LDAP secrets documentation. 
Notable changes include:
- Relocation of schema section that applies more broadly after the AD feature unification
- Adding documentation for service account check-out feature that came from the [AD secrets engine](https://www.vaultproject.io/docs/secrets/ad#service-account-check-out) (slight modifications to the docs)

secrets/ldap: updates documentation

---

website/content/api-docs/libraries.mdx

The repository for AsyncHVAC (https://github.com/Aloomaio/async-hvac) no longer exists, so removing a reference to it.

Remove Async-HVAC from recommended libraries list

---

website/content/partials/raft-retry-join-failure.mdx

Update the doc to show affected versions 1.11.2 and 1.10.6.

docs: Update retry_join Known Issue versions

---

website/content/docs/enterprise/namespaces.mdx

You cannot interact with this API from a non-root namespace, and it was missing from this list as a result.

VAULT-1603 add sys/quotas to root-only api path docs

---

website/content/api-docs/secret/databases/index.mdx
website/content/api-docs/system/auth.mdx
website/content/api-docs/system/mounts.mdx
website/content/api-docs/system/plugins-catalog.mdx
website/content/docs/commands/auth/enable.mdx
website/content/docs/commands/auth/list.mdx
website/content/docs/commands/auth/tune.mdx
website/content/docs/commands/plugin/index.mdx
website/content/docs/commands/plugin/info.mdx
website/content/docs/commands/plugin/register.mdx
website/content/docs/commands/secrets/enable.mdx
website/content/docs/commands/secrets/list.mdx
website/content/docs/commands/secrets/tune.mdx
website/content/docs/plugins/index.mdx
website/content/docs/upgrading/plugins.mdx

This updates most of the docs and API docs for plugin versioning updates. The updates to upgrading plugins is the most drastically different, most of the rest is fairly additive.
The only thing I've intentionally left out for now is the plugin version interface, as this PR was already getting pretty big. I'll follow up with another PR for that.

Docs: Plugin versioning documentation

---

builtin/logical/pki/path_tidy.go
changelog/17497.txt

PKI's tidy-status included a bug that prevented PR secondary nodes from responding with the status of the running tidy operation: while the operation constructor correctly forwarded the node on PR standby instances, the handler itself forwarded also on PR secondary nodes.
This is incorrect as the PR secondary nodes are the active node in the local PR cluster, and run tidy operations otherwise.
This meant that while auto-tidy and tidy operations would run, there was no insight into the process.
When implementing tidy-cancel, tidy-status's handler logic was reused, duplicating the bug there as well.

Fix tidy-status, tidy-cancel on PR Secondaries

---

builtin/logical/database/rotation_test.go

Part of a test fixing exercise, this test has been disabled for a long time. Enabling it and running tests locally multiple times yielded no failures, so let's reinstate it until it becomes a problem again - then figure out what's wrong.

The 2 year temporary disabling of this test has come to an end

---

builtin/logical/pki/zlint_test.go
helper/testhelpers/docker/testhelpers.go

Depends on #17231 
---
In particular, we build a container [with `zmap/zlint`](https://github.com/zmap/zlint) and use it to validate that relatively stock root certificates behave correctly. 
This test adds about 30s, but I'd be curious to see how it can be parallelized. I think we'd have to either provision all the certs at once for zlint (saving ~4s of setup per cert checked), or we could perhaps do a single fetch of zlint into a layer and then parallelize the tests (only having to provision the cert itself).

Add pki zlint tests

---

website/content/api-docs/secret/transit.mdx

Also synchronize the doc between two import api:
- `/transit/keys/:name/import`
- `/transit/keys/:name/import_version`

doc: fix broken link in transit api

---

.github/workflows/backport.yml

I followed the documentation here: https://github.com/hashicorp/backport-assistant/pull/45 and also looked at how similar options are used in other products, e.g. nomad: https://github.com/hashicorp/nomad/blob/main/.github/workflows/backport.yml
I'm admittedly not sure how to test this locally before merging (open to suggestions, if people feel it's important), but the risk does not seem very high.

VAULT-8242 Add automerge functionality to backport

---

CODEOWNERS

Loann Le (@taoism4504) has left HashiCorp.  We're currently recruiting a new Tech Writer to fill her place. 
Meanwhile, I'm removing her username from the CODEOWNER file.

CODEOWNER - Remove Loann

---

website/content/docs/secrets/transit/index.mdx

---
Symmetric keys are in raw format, but asymmetric keys needs to be in PKCS8 format (and not PKCS1).

Add note about transit BYOK key formats

---

builtin/logical/ssh/backend_test.go
builtin/logical/ssh/path_issue_sign.go
changelog/16622.txt

The SSH secrets engine previously split the `validPrincipals` field
on comma, then if user templating is enabled, evaluated the
templates on each substring. This meant the identity template was only
ever allowed to return a single principal. There are use cases
where it would be helpful for identity metadata to contain a list
of valid principals and for the identity template to be able to inject
all of those as valid principals.
This change inverts the order of processing. First the template
is evaluated, and then the resulting string is split on commas.
This allows the identity template to return a single comma-separated
string with multiple permitted principals.
There is a potential security implication here, that if a user is
allowed to update their own identity metadata, they may be …

Evaluate ssh validprincipals user template before splitting

---

vault/core.go
vault/core_util.go

This places the rollback period initialization in a path that is used by enterprise and OSS. The functionality should be consistent between both editions.

core: move rollback period init to NewCore

---

website/content/docs/concepts/storage.mdx
website/content/docs/upgrading/upgrade-to-1.12.x.mdx
website/content/partials/ent-supported-storage.mdx
website/data/docs-nav-data.json

Vault will now perform a supported storage check during startup. There is no impact on Vault OSS but Vault Enterprise will no longer startup if configured to use a storage backend other than `consul` or `raft`. This PR includes the documentation and upgrade notes for 1.12 outlining this change.

Add storage check upgrade notes

---

changelog/17532.txt
vault/acl.go
vault/policy.go

The problem might actually be that the Policy object is cached in the policy store's LRU. Then, we are assigning existingPerms.ControlGroup = pc.Permissions.ControlGroup. This is a pointer to the policy's control group. Then on next iteration we are appending another policy's control group factors to this one, making the actual policy object in the LRU cache larger. This causes the policy in the cache to no longer match the policy on disk.
Instead of using a map and de-duplicating factors i think we want to clone the original Policy's control group so we aren't reusing the pointer and mutating cache objects. If we clone the control group then any factors that we append to it will only live for the lifetime of the request and be garbage collected afterwards. This behaves similarly to the …

prevent memory leak when using control group factors in a policy

---

changelog/17459.txt
http/handler.go
sdk/logical/response.go
sdk/logical/response_util.go
vault/external_tests/identity/aliases_test.go
vault/identity_lookup_test.go
vault/identity_store_entities.go
vault/identity_store_util.go

Note that I did need to do a little black magic here. The response as read by the logical framework is the same (nil response, non-nil error), but raw API requests give the full data array. This seems like a pretty good solution to me, as it doesn't return both a resp and an error to the logical framework, but I'm open to other thoughts and opinions and as to whether or not this is the right kind of black magic. 
The approach is broadly extensible, in the sense that we can follow the same method again in the future, too.
The body of a response after this change will look a little like this (in the case of a double clash):
```
{
"errors":[
"3 errors occurred:\n\t* toEntity and at least one fromEntity have aliases with the same mount accessor, repeat the merge request specifying exactly one …
```

VAULT-8719 Support data array for alias clash error response so UI/machines can understand error

---

changelog/17577.txt
command/secrets_list.go

Fixes empty column in `vault secrets list -detailed` output introduced with #17293.

CLI: Fix secrets list -detailed headings

---

website/content/docs/secrets/transform/index.mdx

Fixes incorrect url to key wrapping for transit import page. This was reported by a user to HashiCorp HelpDesk, who sent it on to me.

docs: fix broken link to transit key wrap

---

website/content/docs/plugins/plugin-portal.mdx

Please see issue https://github.com/hashicorp/vault/issues/17560.

Rename "Google Apigee" to "Apigee"

---

helper/testhelpers/docker/testhelpers.go

Spotted this as part of hack week, was an easy enough fix so thought I'd just make the PR.

Fix format strings missing an argument

---

changelog/17594.txt
go.mod
go.sum

```
go get github.com/hashicorp/vault-plugin-database-snowflake@v0.5.2
go mod tidy
```
Note: This is a direct PR against the release branch due to N-1 backport

database/snowflake: update plugin to v0.5.2

---

changelog/17612.txt
internalshared/configutil/kms.go

Wrapper v2 has a dedicated option for KeyID.  But we handle seal config
generically.  We need to catch this in the config map and convert it to the
new option.

Intercept key_id from generic configmap and turn it into a wrapperv2 option

---

ui/app/models/pki/pki-role-engine.js
ui/lib/pki/addon/components/pki-key-parameters.hbs
ui/lib/pki/addon/components/pki-key-parameters.js
ui/lib/pki/addon/components/pki-role-form.hbs
ui/lib/pki/addon/templates/configuration/index.hbs
ui/lib/pki/addon/templates/issuers/index.hbs
ui/lib/pki/addon/templates/keys/index.hbs
ui/lib/pki/addon/templates/overview.hbs
ui/lib/pki/addon/templates/roles/index.hbs

There was an issue where the `keyBit` value was not being set on init nor was it being set when `keyType` changed, even though the dropdown options were changing.
I pulled all the conditional options work out of the model, and moved it all into a component. This should help clarify what's going on, and move semi-complication logic work out of the model. Also, it will help organize testing.
https://user-images.githubusercontent.com/6618863/196794124-31ccdac2-4f38-4b59-95f6-71a936262453.mov
In the API you can see the default key_bits set for each key_type.
And the default key_type is `rsa`. You can test this in the current PKI. Even though we don't send this default value in the old PKI, the read view shows rsa and 2048.

PKI role create: fix issue with setting default key_bits on init and when key_type changes

---

CHANGELOG.md

This has the contents of https://github.com/hashicorp/vault/blob/826b20c1da99fc57ae99cc399ef28c3fbacad0b1/changelog/plugin-versioning.txt. I'm not clear what went wrong, but now that the release is done, we'll need to add it directly instead of relying on the changelog tooling.

Add plugin versioning to 1.12.0 release notes

---

changelog/17540.txt
website/content/docs/auth/azure.mdx

This PR adds documentation for using the Azure auth method with managed service identity from Virtual Machine Scale Sets in [Flexible orchestration](https://learn.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-orchestration-modes#scale-sets-with-flexible-orchestration) mode. Support for this was recently added to the Azure auth method in https://github.com/hashicorp/vault-plugin-auth-azure/pull/63.
The key difference between uniform and flexible orchestration mode from the perspective of a Vault admin configuring Azure auth is that there is an additional API permission required for flexible orchestration (`Microsoft.ManagedIdentity/userAssignedIdentities/*/read`).

auth/azure: documents auth support for VMSS flexible orchestration

---

.github/workflows/enos-run-k8s.yml

The `enos-run-k8s.yml` workflow had a bug that assumed the docker image repo was always `hashicorp/vault` when it should be `hashicorp/vault-enterprise` when the workflow runs in the `vault-enterprise` project.

[QT-182] Fix broken k8s workflow for vault-enterprise

---

website/content/api-docs/system/loggers.mdx

New functionality was added to Vault to enable changing the log level via an API endpoint, this PR adds a note to advise users that changes made via the endpoint are not persisted as it was unclear before.

added note regarding persistence for log level changes

---

website/content/api-docs/system/loggers.mdx

The `backport/1.12.x` label failed to perform automatic backport of [PR 17596](https://github.com/hashicorp/vault/pull/17596). So, this PR is to manually cherry-pick the commit into `release/1.12.x` branch.

[Backport] added note regarding persistence for log level changes (#17596)

---

vault/identity_store_entities.go
vault/identity_store_util.go

I ran `TestReplicationApi_ApproleLocal_MultiNodeMultiLogin` a bunch of times (which showed this race) and can't seem to reproduce this race any more (and can't see how it would occur any more).
Do let me know if there's any other test i should be running.
This also changes so that `ValidateMountByAccessor` is only called when required, which should be better anyway.

VAULT-9451 Fix data race in entity merge

---

builtin/logical/transit/backend_test.go
builtin/logical/transit/path_decrypt.go
builtin/logical/transit/path_encrypt.go
changelog/17638.txt
sdk/helper/keysutil/policy.go
website/content/api-docs/secret/transit.mdx

Project I started during hack week, but didn't quite finish... (something something, tests) :-) 
This adds a new parameter, `associated_data` to be passed when using an AEAD cipher (AES+GCM, ChaCha20+Poly1305). This is authenticated, but need not be transited in ciphertext.

Add AD mode to Transit's AEAD ciphers

---

website/content/docs/concepts/tokens.mdx

🎟️ [Asana](https://app.asana.com/0/563192436488770/1203231828714799/f)
🔍 [Deploy Preview](https://vault-git-docs-update-token-table-hashicorp.vercel.app/vault/docs/concepts/tokens#token-type-comparison)
It was reported that **Manually Revocable** is not mentioned in the service vs. batch token comparison table. This PR adds a row to mention that.

[docs] Added 'Manually Revocable' to the table

---

website/content/docs/platform/k8s/helm/examples/injector-tls-cert-manager.mdx

Use `injector.webhook.annotations` instead of the deprecated `injector.webhookAnnotations`

docs/vault-helm: update cert-manager example

---

.circleci/config.yml
.circleci/config/commands/go_test.yml

Use more permissions for mkdir

---

website/content/docs/configuration/listener/tcp.mdx

The double quote used broke syntax highlighting. Replace with a proper double quote.
[Before](https://developer.hashicorp.com/vault/docs/configuration/listener/tcp#configuring-custom-http-response-headers):

Fix rendering of custom response headers

---

changelog/17650.txt
command/commands.go
command/patch.go
command/patch_test.go
command/write.go
website/content/docs/commands/patch.mdx

This adds `patch` as a top-level command in the `vault` CLI, allowing access to these endpoints from our default CLI. Under the covers, we simply delegate info to a `client.Logical().JSONMergePatch(...)` call instead of `Write(...)`, making this fairly simple to implement. Unlike `vault kv patch` though, we don't dump all of the data in an inner `data: ...` struct however, as non-KVv2 PATCH APIs don't require that structure.

Add PATCH support to Vault CLI

---

.circleci/config.yml
.circleci/config/commands/go_test.yml
changelog/17640.txt
sdk/helper/ldaputil/client.go
sdk/helper/ldaputil/connection.go

Vault was returning the following error when trying to filter on a large number of groups
```
* LDAP search failed: LDAP Result Code 4 "Size Limit Exceeded": 
```
This change makes use of paginated ldap searching, through a new connection interface as to maintain backwards compatibility for the SDK.
Fixes #7702

Add Paging Interface for LDAP Connection

---

command/server/tls_util.go

Vault's new TLS `devvault` mode has two nits with certificate construction that I missed on the initial review:
1. The CA doesn't need to include any SANs, as these aren't checked. Technically this means the CA could be reused as a leaf certificate for the one specified IP SAN, which is less desirable.
2. Add hostname to SANs in addition to CNs. This is a best practice, as (when the CN is a hostname), it is preferable to have everything in SANs as well.
Neither of these are major changes.

Clean up dev cert construction

---

changelog/17040.txt
command/base.go
command/login.go
command/login_test.go
command/write.go
helper/testhelpers/testhelpers.go
vault/external_tests/identity/aliases_test.go
vault/external_tests/identity/login_mfa_totp_test.go

This PR updates the `login` path to store a token when using single-phase MFA validation. Still need to do some testing to see if this breaks any of the pre-existing functionality (particularly two-phase MFA).
Fixes: #16928

Store login MFA secret with tokenhelper

---

builtin/logical/transit/backend_test.go
builtin/logical/transit/path_sign_verify.go
builtin/logical/transit/path_sign_verify_test.go
changelog/17636.txt
sdk/helper/keysutil/consts.go
sdk/helper/keysutil/policy_test.go
website/content/api-docs/secret/transit.mdx

This assumes a pre-hashed input has been provided to Vault, but we do not write the hash's OID into the signature stream. This allows us to generate the alternative PKCSv1_5_NoOID signature type rather than the existing PKCSv1_5_DERnull signature type we presently use.
These are specified in RFC 3447 Section 9.2.
---
I've not figured out how to test this independently with PyCryptography or OpenSSL... I'm not sure its really supported in their PKCS#1v1.5 APIs.
This fails on my system, since OpenSSL can't map `none` to a valid `EVP_md` algorithm:
```python
#!/usr/bin/python3
import base64
import cryptography
import cryptography.hazmat
import cryptography.hazmat.primitives
import cryptography.hazmat.primitives.asymmetric
import …
```

Add support for PKCSv1_5_NoOID signatures

---

builtin/logical/pki/storage.go

Ref: https://github.com/hashicorp/vault/issues/17642

Default crl expiry

---

website/content/api-docs/secret/ssh.mdx

The initial documentation for the new API endpoint `POST /ssh/issue/:name` in #15561 was a bit short.
Extend it to make the new API call more clear.

Update POST /ssh/issue/:name in website/content/api-docs/secret/ssh.mdx

---

builtin/logical/pki/backend_test.go
builtin/logical/pki/storage.go
changelog/17693.txt

Also fixes missing `delta_rebuild_interval` parameter.
--
cc @JNProtzman -- I missed a field in the review, that's what the test was for. :-D

Add empty expiry crlConfig upgrade test

---

helper/testhelpers/mongodb/mongodbhelper.go
plugins/database/mongodb/connection_producer_test.go
plugins/database/mongodb/mongodb_test.go

Related PR: https://github.com/hashicorp/vault/pull/16880 
MongoDB tests started failing when Mongo released v6 docker version. I updated MongoDB driver from [mgo](https://github.com/go-mgo/mgo) unmaintained driver to the official [MongoDB driver](https://github.com/mongodb/mongo-go-driver).
Updating the driver and deleting the standalone secrets engine fixed the problem. Results from running tests with the "_latest_" tag:

Fix tests - Update MongoDB driver

---

website/content/api-docs/secret/ssh.mdx

Added clarity notes on required permissions (`update` & `create`) that's otherwise not obvious without experience of other mounts that have requirements for similar ACL to manage. Resolves #9888.

Docs: API secret/ssh clarity on Create & Update

---

website/data/docs-nav-data.json

#17650 introduced some vercel build failures on main, e.g. https://vercel.com/hashicorp/vault/ETjK3dsbZq86oQtLumQRsTyGUZuP
> Error: Unlinked pages found in the ../content/docs directory.
#17676 fixed it, but then also backported it to the release branches which don't have the new file, causing errors like https://vercel.com/hashicorp/vault/2jp5Sh6phpDmdpgaAQ2iZLgJX5g6
> Error: Could not find file to match path "commands/patch". Neither "commands/patch.mdx" or "commands/patch/index.mdx" could be found.
I'm surprised, but it seems like despite that vercel error, `patch` is still showing up on the 1.12.x, 1.11.x and 1.10.x versions of the docs atm, but with an error:
* https://developer.hashicorp.com/vault/docs/commands
* https://developer.hashicorp.com/vault/docs/commands/patch
* …

Docs: Patch command ordering

---

api/logical.go
changelog/14945.txt
command/format.go
command/read.go

Not really sure who should own this work :-) I realize the approach hasn't been popular in the past...
...but I figured I'd re-open a branch I had with this change to see where it'll go this time.
We expose a `ReadRaw...` operations, which returns a raw `Response` rather than a parsed `Secret`. This allows us to hit endpoints (such as the various PKI endpoints -- which are ever-expanding) which return non-JSON formatted responses from both the Client and the API. These responses include DER and PEM-formatted bundles.
From a CLI perspective, this lets the following succeed, which IMO, is a big improvement over the existing behavior:
```
$ vault read -format=raw pki/ca/pem
-----BEGIN CERTIFICATE-----
MIIDNTCCAh2gAwIBAgIUNTLfhEuAQITKoNnJWDrnJXrLDHwwDQYJKoZIhvcNAQEL …
```

Vault Raw Read Support (CLI & Client) 

---

command/base.go
command/base_helpers.go
command/format.go
command/read.go
command/util.go
website/content/docs/commands/read.mdx

Figured out how that error message gets triggered!
```
[cipherboy@xps15 vault]$ vault write -format=raw pki/root/generate/internal use_pss=true common_name="hack week demo root"
Could not parse output: unable to type assert to []byte: *api.Secret; please share the command run
```
This also lends itself to a much nicer error message instead:
```
[cipherboy@xps15 vault]$ vault write -format=raw pki/root/generate/internal use_pss=true common_name="hack week demo root"
Could not parse output: This command does not support the -format=raw option; only `vault read` does.
```
Also add the format mode to the website docs page.
---
To support `-format=raw` on other display engines, they'd have to have raw `*Response` variants of all calls (Write/Patch/...), which is less than ideal, IMO. Only …

Fix raw format for other commands, add to docs!

---

.circleci/config.yml
.circleci/config/commands/go_test.yml

When copying data into the container, due to the id changes pointed out in the previous attempt, the container couldn't read this data.
By creating a new group inside the container, with the host's GID (if it doesn't already exist) and modifying the container user to also have this group, it should be able to access these files without requiring a chmod.
See also: https://github.com/hashicorp/vault/pull/17658

Add container's executor to host's group for copy

---

builtin/logical/aws/backend_test.go
builtin/logical/aws/stepwise_test.go

AWS STS secrets were changed to no longer create a lease. This updates a test case relying on checking for a secret in the response. Also fixes a sync.Once object being used in two locations.

Update AWS secrets tests

---

changelog/17747.txt
go.mod
go.sum

The following list is all of the modules for the AWS secret engine:
```
github.com/aws/aws-sdk-go 
github.com/hashicorp/errwrap 
github.com/hashicorp/go-cleanhttp 
github.com/hashicorp/go-hclog 
github.com/hashicorp/go-multierror
github.com/hashicorp/go-secure-stdlib/awsutil
github.com/hashicorp/go-secure-stdlib/strutil
github.com/hashicorp/vault
github.com/hashicorp/vault-testing-stepwise
github.com/mitchellh/mapstructure
github.com/stretchr/testify
```
Ran `go get ...` for each of these in the list.
Ran `make testacc TEST=./builtin/logical/aws TESTARGS='-count=1'` before and after to ensure all tests remain passing.

Update AWS secret engine deps

---

builtin/credential/approle/path_role.go
builtin/credential/approle/validation.go
changelog/17768.txt
command/agent/approle_end_to_end_test.go
website/content/api-docs/auth/approle.mdx

As part of https://github.com/hashicorp/vault/pull/14746, we restricted the length of approle's HMAC to 1024. This had the unfortunate effect of making it so that operations on an approle with such a name would fail.
As part of this change, I've increased the limit slightly, so that it's more permissive to names, but also made approle creation fail if the name passes this limit, so that we cannot get into this state to begin with.

VAULT-8518 Increase HMAC limit to 4096, and limit approle names to the same limit

---

builtin/logical/pki/path_fetch.go
builtin/logical/pki/path_tidy_test.go
changelog/17774.txt
website/content/api-docs/secret/pki.mdx

The existing `/cert/<serial>` endpoint already returned both the `certificate` and a `revocation_time` fields populated prior to this change.
Update the api to return `revocation_time_rfc3339` as we do elsewhere and also `issuer_id` if it was revoked and populated. 
This will allow callers to associate a revoked cert with an issuer if trying to build up an external CRL or any other use case.

Return revocation info within existing certs/<serial> api

---

builtin/credential/radius/backend_test.go
builtin/logical/pki/zlint_test.go
builtin/logical/rabbitmq/backend_test.go
builtin/logical/ssh/backend_test.go
command/server/server_seal_transit_acc_test.go
helper/testhelpers/cassandra/cassandrahelper.go
helper/testhelpers/consul/consulhelper.go
helper/testhelpers/fakegcsserver/fake-gcs-server.go
helper/testhelpers/ldap/ldaphelper.go
helper/testhelpers/minio/miniohelper.go
helper/testhelpers/mongodb/mongodbhelper.go
helper/testhelpers/mysql/mysqlhelper.go
helper/testhelpers/postgresql/postgresqlhelper.go
physical/aerospike/aerospike_test.go
physical/cockroachdb/cockroachdb_test.go
physical/couchdb/couchdb_test.go
physical/dynamodb/dynamodb_test.go

When running the test suite in CI (where requests are centralized from relatively few IPs), we'd occasionally hit Dockerhub's rate limits. Luckily Hashicorp runs a (limited) public mirror of the containers we need, so we can switch to them here in the tests.
For consistency between developer and CI, we've opted to have the tests always pull from the Hashicorp mirror, rather than updating the CI runner to prefer the mirror.
---
I'm inclined to give this a little testing first and then backport it later if it works on `main` consistently well.

Use hashicorp mirror for container pulls

---

Makefile
changelog/17678.txt

By adding the link flags `-s -w` we can reduce the Vault binary size from 204 MB to 167 MB (about 18% reduction in size).
This removes the DWARF section of the binary.
i.e., before:
```
$ objdump --section-headers vault-debug
vault-debug:	file format mach-o arm64
Sections:
Idx Name             Size     VMA              Type
0 __text           03a00340 0000000100001000 TEXT
1 __symbol_stub1   00000618 0000000103a01340 TEXT
2 __rodata         00c18088 0000000103a01960 DATA
3 __rodata         015aee18 000000010461c000 DATA
4 __typelink       0004616c 0000000105bcae20 DATA
5 __itablink       0000eb68 0000000105c10fa0 DATA
6 __gosymtab       00000000 0000000105c1fb08 DATA
7 __gopclntab      02a5b8e0 0000000105c1fb20 DATA
8 __go_buildinfo   00008c10 000000010867c000 DATA
9 __nl_symbol_ptr …
```

Proposal: Remove debug symbols from build

---

changelog/17769.txt
ui/app/components/raft-storage-overview.js
ui/lib/service-worker-authenticated-download/service-worker-registration/index.js
ui/tests/integration/components/raft-storage-overview-test.js

An uncaught error was causing the service worker to hang when attempting to download a raft snapshot which would eventually result in a permission denied response since the token was not provided to the fetch request.
In the `service-worker-authenticated-download` in-repo addon the `service-worker-registration` is attempting to import from `@ember/application/namespace`. In the generated `sw-registration.js` script this results in that module being accessed from the `Ember` global which has been removed and is undefined.
[Screencast from 2022-11-01 03:27:11 PM.webm](https://user-images.githubusercontent.com/24611656/199345314-0197fbc5-963b-4c69-8ff1-5216ecc92904.webm)
This seems to be an issue with `ember-auto-import` (or babel or webpack by extension) but I just couldn't figure out how …

Raft Snapshot Download Bug

---

website/content/docs/concepts/seal.mdx

This "Seal/Unseal" article seems to use the terms "shares" and "shards" interchangeably to describe the parts in which the secret is split under SSS. While both seem to be correct, sticking to one term would save a newbie reader (like myself) the confusion.  
Since the Wikipedia article that's linked in this article only mentions "shares" and the CLI flags (for recovery keys) also use `-shares`, I opted for that.
I did not create an separate issue for that, because the change seemed trivial, I hope that's not a problem.
Should I add a `changelog/#.txt` though?

Update seal.mdx, use consistent terminology

---

website/content/docs/upgrading/upgrade-to-1.12.x.mdx

As explained in the docs, there is an issue in some cases when an explicit builtin version has been specified. We're currently working on a fix to go into 1.12.2.
When the issue occurs, users will see log lines something like:
```
[ERROR] core: failed to create credential entry: path=approle/ error="plugin not found in the catalog: approle, version=v1.13.0+builtin.vault"
```

Docs: Add known issue for 1.12.1 builtin plugin version upgrades

---

website/content/api-docs/secret/transit.mdx

Added note about output order to each `batch_input` reference.  I'm not sure I formatted the changes correctly 😬

docs: in transit secret engine docs, specify order with batch_input param

---

Makefile

Typo, I couldn't find any other mentions of `.go_version`

Fix .go-version path in Makefile

---

builtin/logical/pki/chain_util.go
builtin/logical/pki/storage_migrations.go
builtin/logical/pki/storage_migrations_test.go
builtin/logical/pki/storage_test.go
changelog/17772.txt
website/content/docs/secrets/pki/considerations.mdx

Probably best to defer to the commit messages here:
```
commit 8010a8755755afd19d5a62fd5073acb2fea1e1ba
Author: Alexander Scheel <alex.scheel@hashicorp.com>
Date:   Wed Nov 2 08:59:44 2022 -0400
Remigrate ca_chains to fix any missing issuers
In the previous commit, we identified an issue that would occur on
legacy issuer migration to the new storage format. This is easy enough
to detect for any given mount (by an operator), but automating scanning
and remediating all PKI mounts in large deployments might be difficult.
Write a new storage migration version to regenerate all chains on
upgrade, once.
commit 8a786b0c57c27a6e3dc1d06edacd03672d8f8bc9
Author: Alexander Scheel <alex.scheel@hashicorp.com>
Date:   Wed Nov 2 08:12:34 2022 …
```

PKI - Fix order of chain building writes

---

helper/testhelpers/testhelpers.go

Give the default `SetupLoginMFATOTP` helper a more reasonable period/skew. 403 failures on test-go-race are likely due to TOTP code timeouts being too aggressive.

Bump up loginMFA testhelper period and skew

---

changelog/17801.txt
vault/policy_store.go

This fixes a start up race condition where recently assigned performance standbys might not yet have received logs from the active node containing policies. This can sometimes result in a mount loop on the performance standbys and would only be fixed by restarting the performance standbys. The fix simply skips performance standbys all together.

core: fix start up policy loading race condition on perf standbys

---

builtin/logical/pki/backend.go
builtin/logical/pki/backend_test.go
builtin/logical/pki/path_revoke.go
builtin/logical/pki/storage.go
changelog/17779.txt
website/content/api-docs/secret/pki.mdx

A new API that will return the list of serial numbers of revoked certificates on the local cluster.
```
❯ curl \
--header "X-Vault-Token: $VAULT_TOKEN" \
--request LIST \
http://127.0.0.1:8200/v1/pki_int/certs/revoked | jq
{
"request_id": "e221b49c-6c28-0b08-30dc-e2dd2f37d077",
"lease_id": "",
"renewable": false,
"lease_duration": 0,
"data": {
"keys": [
"3d:80:91:c3:c2:34:3b:81:69:3d:92:a3:80:69:db:53:04:26:ab:b4"
]
},
"wrap_info": null,
"warnings": null,
"auth": null
}
```

Add new API to PKI to list revoked certificates

---

helper/testhelpers/testhelpers.go

Backup assistant failed to kick off the backport PRs, so I had to cherry-pick the commit onto all of the relevant release branches.
Give the default SetupLoginMFATOTP helper a more robust period/skew. 403 failures on test-go-race are likely due to TOTP code timeouts being too aggressive.

Backport of Bump up period and skew to prevent timeouts into release/1.11.x

---

helper/testhelpers/testhelpers.go

Backup assistant failed to kick off the backport PRs, so I had to cherry-pick the commit onto all of the relevant release branches.
Give the default SetupLoginMFATOTP helper a more robust period/skew. 403 failures on test-go-race are likely due to TOTP code timeouts being too aggressive.

Backport of Bump up period and skew to prevent timeouts int release/1.12.x

---

api/plugin_helpers.go
changelog/17789.txt
vault/inspectable.go
vault/inspectable_test.go
vault/logical_system.go
vault/logical_system_paths.go
vault/logical_system_test.go
vault/mount.go
vault/router.go

Link to ENT PR: https://github.com/hashicorp/vault-enterprise/pull/3267
Link to Documentation PR: https://github.com/hashicorp/vault/pull/17753

Introspection API Implementation for Router Struct

---

website/content/docs/platform/k8s/injector/examples.mdx

Specifying only `args` will just append them to the container image's entrypoint instead of replacing it: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#container-v1-core. So this example wasn't actually setting the env variable in the app's env.
Setting `command` overrides the entrypoint, and `args` is then appended to the command.
Related to https://github.com/hashicorp/vault-k8s/issues/45

docs/vault-k8s: update env example

---

CHANGELOG.md

Preview content for 1.13
Tagging EMs as reviewers but going to merge without approval. It would be great if you all could give this a once-over and confirm that all of these updates correspond to 1.13 content and not content from earlier releases.

1.13 preview

---

.release/ci.hcl

Iron Bank won't be offering this version of Vault anymore, so this workflow is not necessary.

Delete iron bank update event for Vault 1.9.x

---

changelog/17848.txt
go.mod
go.sum

Updated `raft-autopilot` to respect minimum quorum for potential voters when handling server removal from the raft configuration. This PR updates the `raft-autopilot` that Vault consumes to use the updated version (`v0.2.0`).
Related PR: https://github.com/hashicorp/raft-autopilot/pull/23 (see PR for related issues).

updated raft-autopilot to v0.2.0

---

ui/package.json
ui/yarn.lock

Bumps ember-source version to 4.4.4 which [patches a security vulnerability](https://blog.emberjs.com/ember-4-8-1-released/).

Ember Security Vulnerability Patch

---

ui/package.json
ui/yarn.lock

Manual backport of #17842 since `ember-source` version differs across vault versions.

Backport of Ember Security Vulnerability Patch into release/1.12.x

---

ui/package.json
ui/yarn.lock

Manual backport of #17842 since `ember-source` version differs across vault versions.

Backport of Ember Security Vulnerability Patch into release/1.10.x

---

builtin/logical/pki/config_util.go
builtin/logical/pki/integation_test.go
builtin/logical/pki/path_config_ca.go
builtin/logical/pki/path_manage_issuers.go
builtin/logical/pki/path_root.go
builtin/logical/pki/storage.go
builtin/logical/pki/storage_migrations_test.go
builtin/logical/pki/storage_test.go
changelog/17824.txt
website/content/api-docs/secret/pki.mdx

When attempting compatibility against multiple versions of Vault, one major breaking change in Vault 1.11 was the multiple issuer's functionality and behavior changes around importing issuers (wherein `/config/ca` required a deletion first) and generation of new issuers (where both root/intermediate generation silently removed old keys!).
While we don't wish to remove key material any more, thus becoming more safe, the net was a breaking change _across APIs_: because the default issuer was not updated on these operations, the issuer would appear "lost" to any callers. Only when an operator updated the default issuer would non-multi-issuer aware applications see this new CA.
However, not everyone will want to automatically change the default issuer: for applications and operators aware of …

Optional automatic default issuer selection

---

api/sys_seal.go
changelog/17855.txt
command/format.go
command/format_test.go
http/sys_seal_test.go
vault/logical_system.go

If this environment variable is set, you will now get the following output:
```
violet@violet-TX54KFJWXM vault % vault status
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    1
Threshold       1
Version         1.13.0-dev1
Build Date      2022-10-31T11:14:49Z
Storage Type    inmem
Cluster Name    vault-cluster-30c0be85
Cluster ID      64a060de-020b-91a7-ec26-0a6686c3beea
HA Enabled      false
Warnings        [Server Side Consistent Tokens are disabled, due to the VAULT_DISABLE_SERVER_SIDE_CONSISTENT_TOKENS environment variable being set. It is not recommended to run Vault for an extended period of time with this configuration.]
```
"Warnings" will not be present if this option is not given.
Also, json output:
``` …
```

VAULT-8703 Add warning for dangerous undocumented overrides, if used, in status response

---

website/content/docs/concepts/policies.mdx

https://github.com/hashicorp/vault/issues/17733 notes that the examples in the policy concepts docs are a bit misleading. There are policy examples meant for KVv1 but they are not denoted as such. This PR add a callout and links to the KVv1 API docs for further context.

clarify that certain policy examples are for KVv1

---

website/content/docs/commands/kv/metadata.mdx

There is a missing dash before 'custom-metadata':
$ vault kv metadata put custom-metadata="foo=bar" secret/hub/config-demo
Too many arguments (expected 1, got 2)
$ vault kv metadata put -custom-metadata="foo=bar" secret/hub/config-demo
Success! Data written to: secret/metadata/hub/config-demo
Signed-off-by: Michele Baldessari <michele@acksyn.org>

Fix a typo around custom-metadata in kv put docs

---

builtin/logical/pki/backend.go
builtin/logical/pki/backend_test.go
builtin/logical/pki/fields.go
builtin/logical/pki/path_tidy.go
builtin/logical/pki/path_tidy_test.go
builtin/logical/pki/storage.go
changelog/17823.txt
website/content/api-docs/secret/pki.mdx

To aid PKI users like Consul, which periodically rotate intermediates, and provided a little more consistency with older versions of Vault which would silently (and dangerously!) replace the configured CA on root/intermediate generation, we introduce an automatic tidy of expired issuers.
This includes a longer safety buffer (1 year) and logging of the relevant issuer information prior to deletion (certificate contents, key ID, and issuer ID/name) to allow admins to recover this value if desired, or perform further cleanup of keys.
From my PoV, removal of the issuer is thus a relatively safe operation compared to keys (which I do not feel comfortable removing) as they can always be re-imported if desired. Additionally, this is an opt-in tidy operation, not enabled by default. Lastly, most …

Add automatic tidy of expired issuers

---

changelog/17856.txt
vault/activity_log.go

From what I can tell, I think the activity log endpoint is returning the correct data, but it's not adjusting the `end_time` that's returned when we calculate partial month counts. Instead, it was always using the end time for the pre-computed query. This meant that the end_time returned didn't accurately reflect the actual data. Now it should.
For more detail see https://hashicorp.atlassian.net/browse/VAULT-9257

Fix activity log end time

---

website/content/api-docs/system/init.mdx
website/content/docs/commands/operator/init.mdx

https://github.com/hashicorp/vault/issues/17764 noted that the recent validation changes to the `sys/init` endpoint around the recovery options were not clearly documented. This PR clarifies that the recovery options are only available if auto unseal is in use.

clarify that init recovery options are only available for auto unseal

---

api/plugin_helpers.go
changelog/17839.txt
scripts/gen_openapi.sh
sdk/framework/backend.go
sdk/framework/openapi.go
sdk/framework/openapi_test.go
sdk/framework/path.go
sdk/framework/testdata/legacy.json
sdk/framework/testdata/operations.json
sdk/framework/testdata/operations_list.json
sdk/framework/testdata/responses.json
vault/logical_system.go
vault/logical_system_test.go
website/content/api-docs/system/internal-specs-openapi.mdx

The current behaviour is to only add mount paths into the generated `opeanpi.json` spec if a `generic_mount_paths` flag is added to the request. This means that we would have to maintain two different `openapi.json` files, which is not ideal. The new solution in this PR is to add `{mount_path}` into every path with a default value specified:
```diff
--    "/auth/token/accessors/": {
++    "/auth/{mount_path}/accessors/": {
"parameters": [
{
"name": "mount_path",
"description": "....",
"in": "path",
"schema": {
"type": "string",
++          "default": "token"
}
}
],
```
Additionally, fixed the logic to generate the `operationId` (used to generate method names in the code generated from OpenAPI spec). It had a bug where the ID had `mountPath` in it. The new ID will look like this:
```diff …
```

Add mount path into the default generated openapi.json spec

---

command/server.go
command/server_util.go

A change was added to the `vault server` command in 1.12 that would prevent startup (when not in dev mode) if configured to use an unsupported storage backend. HashiCorp currently supports Consul (consul) and Integrated Storage (raft). We are modifying this change so that it will instead log a warning. This PR includes the changes to the `vault server` command and an associated NOOP check as there is no support restriction on storage backend in OSS.
The check could be disabled using an environment variable, `VAULT_DISABLE_SUPPORTED_STORAGE_CHECK`.  This environment variable has been removed as there is no longer any need to disable the check as its only effect is that a warning will be logged.
Docs PR: https://github.com/hashicorp/vault/pull/17885

add noop ent supported storage check

---

builtin/logical/ssh/path_roles.go
changelog/10299.txt
ui/app/models/role-ssh.js

Implements: #10114 
* Adds allowed values for algorithm_signer to ssh plugin API
* Adds algorithm_signer as field in UI

Expose ssh algorithm_signer in web interface (#10114)

---

website/content/api-docs/system/managed-keys.mdx

Updated the description for the Azure 'key_type' parameter to read 'RSA-HSM' as the only supported value. The existing value in the description reads 'RSA' which returns the following 'Unsupported managed key type' error:
https://github.com/hashicorp/vault-enterprise/blob/5b5f8c0b3d2bc707d9fda9016c8b4c97d558322e/vault/managed_key/azurekeyvault_ent.go#L142

Update Azure 'key_type' description

---

changelog/17866.txt
ui/app/templates/components/database-connection.hbs
ui/app/templates/components/license-banners.hbs
ui/app/templates/components/link-status.hbs
ui/app/templates/components/namespace-link.hbs
ui/app/templates/components/pki/config-pki-ca.hbs
ui/app/templates/components/raft-storage-overview.hbs
ui/app/templates/components/transform-advanced-templating.hbs
ui/app/templates/vault.hbs
ui/app/templates/vault/cluster/unseal.hbs
ui/lib/core/addon/components/doc-link.js
ui/lib/core/addon/components/external-link.hbs
ui/lib/core/addon/components/external-link.js
ui/lib/core/addon/components/learn-link.js
ui/lib/core/addon/templates/components/replication-mode-summary.hbs
ui/lib/core/addon/templates/components/replication-secondary-card.hbs
ui/lib/core/addon/templates/components/upgrade-page.hbs
ui/lib/core/app/components/external-link.js

`<a>` tags have different behavior than `<LinkTo>` within our app with regards to keeping root users logged in on page load. This change is to make sure we're using `<a>` tags as minimally as possible. All the current implementations of these tags are legitimate (they correctly reload the page or link to an external site) but to consolidate their usage I created a new `ExternalLink` component, and glimmerized `DocLink` and `LearnLink` so they can extend this new component. 
Something I considered that is out of scope of this ticket, is using the [HDS Links](https://design-system-components-hashicorp.vercel.app/components/link/inline) instead, but I think that should be follow-on work

UI: Update <a> tags to LinkTo's

---

builtin/credential/cert/path_login.go
changelog/17904.txt

Link to ENT PR: https://github.com/hashicorp/vault-enterprise/pull/3365

Added error message

---

changelog/17816.txt
vault/external_plugin_test.go
vault/logical_system.go
vault/mount.go

Only update the status on mount and secrets/auth enable. This should resolve VAULT-9019.

plugins: Filter builtins by RunningVersion

---

changelog/17909.txt
sdk/framework/openapi.go
sdk/framework/testdata/legacy.json
sdk/framework/testdata/operations.json

Making request objects required. This cleans up the C# generated code by not allowing defaults

Make request objects required

---

website/content/api-docs/secret/pki.mdx

Update a note within the PKI API documentation which incorrectly mentioned that the automatic tidying of issuers would remove a `default` issuer. That doesn't happen according to the code, we will simply log the fact that the default issuer is expired but no removal occurs.

Update api-doc about PKI automatic tidying of issuers and the default issuer

---

builtin/logical/pki/backend_test.go
builtin/logical/pki/cert_util_test.go
builtin/logical/pki/chain_test.go
builtin/logical/pki/crl_test.go
builtin/logical/pki/integation_test.go
builtin/logical/pki/ocsp_test.go
builtin/logical/pki/path_manage_keys_test.go
builtin/logical/pki/path_roles_test.go
builtin/logical/pki/path_tidy_test.go
builtin/logical/pki/storage_migrations_test.go
builtin/logical/pki/storage_test.go
builtin/logical/pki/test_helpers.go
builtin/logical/pkiext/README.md
builtin/logical/pkiext/zlint_test.go
command/secrets_enable_test.go

As discussed on the test fixing call, we should move the PKI Docker tests to a new package so they get executed on a different runner than the main (non-Docker) PKI tests.

Move pki docker tests to pkiext

---

website/content/docs/secrets/pki/considerations.mdx

Clarify revoke doesn't need a root/sudo token, and why we use separate root/intermediate mounts.

Docs clarifications around PKI considerations

---

enos/enos-scenario-agent.hcl
enos/enos-scenario-smoke.hcl
enos/enos-scenario-upgrade.hcl

Previously we'd pass the matrix variant to the backend cluster module which is currently unsupported by the consul module. Instead we'll always pass the ubuntu/amd64 AMI ID to the consul backend module.
This should resolve the enos-verify-stable matrix failures here https://github.com/hashicorp/vault/actions/runs/3448137968/jobs/5754873688#step:11:191

enos: use amd64 for consul backend

---

changelog/17935.txt
vault/activity_log.go

Previously, if a Vault instance only had client count data for the current month, and you queried the activity log endpoint using dates that spanned historical data, you'd just get a 204 empty response. Now, instead, you get back the client counts for the current month. A concrete example might make things clearer:
Today is November 14. My Vault server came online for the first time on November 2. I've been using it ever since. If I query the activity log endpoint for 11/1/22 - 11/14/22, all is well. I get back partial results for this month. But, if I query for 10/1/22 - 11/14/22, previously I would get a 204 empty response. That's not correct though. I do have client count information for the time range requested, it's just all in November. With this patch, if I query for 10/1/22 - …

Don't return a 204 if there's no historical data

---

website/content/docs/secrets/pki/considerations.mdx

Thanks to Khai Tran for identifying that syslogging has a lower limit on message size and sometimes large CRLs can hit that limit.

Clarify more documentation on audit logging.

---

api/logical.go
changelog/17750.txt
command/commands.go
command/healthcheck/common.go
command/healthcheck/pki.go
command/healthcheck/pki_ca_validity_period.go
command/healthcheck/pki_crl_validity_period.go
command/healthcheck/util.go
command/pki_health_check.go
command/pki_health_check_test.go

This pull requests adds initial support for the `vault pki health-check` command, with two health checks. More will be added in future PRs, but I wanted to get this opened for review before we get too far and add too many tests.
---
TODO:

PKI Health Check Command

---

website/content/api-docs/secret/pki.mdx

When renaming the header to Set Revocation Configuration, we broke bookmarks. Add in the named anchor so the old bookmarks and links still work.

Add missing anchor for set-crl-configuration

---

.github/workflows/build.yml

Per discussion in https://github.com/hashicorp/vault-enterprise/pull/3376
Removing an unnecessary substep in build.yml

removing setup-go in build.yml as it is unnecessary

---

command/healthcheck/pki.go
command/healthcheck/pki_hardware_backed_root.go
command/healthcheck/pki_root_issued_leaves.go
command/pki_health_check.go

~This is based on top of #17750; will be rebased once that merges.~
We add two new health checks in this one:
- `hardware_backed_root`, defaulting to disabled, which checks whether Root CAs are backed by the Managed Key subsystem.
- `root_issued_leaves`, which checks whether the root has directly issued leaf certificates.
We also update the list to also show the configuration for that health check, and fix table listing to be in a static order.

Add hardware_backed_root, root_issued_leaves health checks

---

changelog/17950.txt
ui/app/templates/components/identity/item-policies.hbs
ui/app/templates/vault/cluster/policy/show.hbs

this PR previously addressed a capabilities issue in the show template, but we decided to approach the solution another day and get to the root of the problem (rather than supply a bandaid fix)

UI: fixes link from to show page from entity policies list

---

changelog/17914.txt
vault/request_handling.go

This PR solves an issue where a token can have duplicate policies as part of its policy set when using external groups. This scenario is encountered when an external group policy mapping is created in Vault containing duplicate policies to those defined by the authentication method.

Deduplicate policies prior to generating ACL on request

---

website/content/api-docs/secret/pki.mdx

- Within the table specifying the various paths to generate a CSR in the PKI api-docs, the new issuers based API has a typo in it missing the issuers/ prefix.
- Brought to our attention by Chelsea and Claire, thanks!

Fix path typo in Generate Intermediate CSR PKI docs

---

ui/app/adapters/kubernetes/config.js
ui/app/adapters/kubernetes/role.js
ui/app/decorators/model-form-fields.js
ui/app/models/kubernetes/config.js
ui/app/models/kubernetes/role.js
ui/app/serializers/kubernetes/config.js
ui/app/serializers/kubernetes/role.js
ui/tests/unit/adapters/kubernetes/config-test.js
ui/tests/unit/adapters/kubernetes/role-test.js
ui/tests/unit/decorators/model-form-fields-test.js

Adds models, adapters and serializers for Kubernetes secrets engine. In addition, I took a stab at creating a decorator for setting up `formFields` and `formFieldGroups` properties on a Model class which leverages the existing `expandAttributeMeta` and `fieldToAttrs` utilities.

Kubernetes Models, Adapters and Serializers

---

ui/mirage/factories/kubernetes-config.js
ui/mirage/factories/kubernetes-role.js
ui/mirage/handlers/index.js
ui/mirage/handlers/kubernetes.js

Adds mirage factories and handlers for use during development and testing.

Kubernetes Mirage Setup

---

api/logical.go
api/secret.go
changelog/17913.txt
command/read_test.go

https://hashicorp.atlassian.net/browse/VAULT-9800
The response bodies for the sys/health and sys/leader endpoints do not include a top-level data object. The vault read command expects this top-level field unless -format=raw (a recent addition) is used. It is entirely possible that issue exists for other endpoints and solving for these two likely solves for all.
**Issue:** 
vault read sys/health -format=json
{
"request_id": "",
"lease_id": "",
"lease_duration": 0,
"renewable": false,
"data": null,
"warnings": null
}
vault read sys/health
(No response)
**Sample response:**
vault read sys/health
Key                             Value
---                             -----
cluster_id                      9501c424-662b-01ef-c5f0-0f7a2e48575d
cluster_name …

Vault 9800 Fix vault read handling for endpoints with no top-level data object 

---

builtin/credential/okta/backend_test.go
command/agent/alicloud_end_to_end_test.go
command/agent/aws_end_to_end_test.go
helper/testhelpers/testhelpers.go
plugins/database/redshift/redshift_test.go

This PR represents the first body of work in the process of ensuring that credentials are set in order for certain acceptance tests to be run. There are some subtle distinctions between environment variables being set and the credentials being valid. This work only adds the former.
You will find a test helper that has been added in order to DRY up this process. The test helper is then used in acceptance tests that need cloud credentials set in their environment.
Some tests that need credentials are either not available in the Vault OSS repository or require extended logic to fully check that their credentials are not available. Those are not included in this PR though they are a part of the larger QT-309 task. I have provided a simple table that indicates what should be in this PR and …

[QT-309] Ensure environment variables are populated before proceeding

---

builtin/logical/aws/backend_test.go
go.mod

There is a related PR; see #17915.
When testing against AWS, we need to resolve an AWS config, attempt to use the credentials, and then proceed with performing the actual test.
The first step, resolving the AWS config, is not currently present in many cases. This change aims to generalize that process where appropriate using the tools provided by AWS themselves so as to obtain a free lunch with regard to possible future ways of resolving an AWS config.
The change is rather minimal due to the existing generalization of the code. In a related block that pre-checks for environment variables or skips, this change will also attempt to resolve an AWS config or skip.

[QT-309] Resolve AWS config before testing ACC

---

sdk/helper/certutil/certutil_test.go
sdk/helper/certutil/helpers.go

Switch to using `ParseUint` of 8 bits to parse the hex values properly as `ParseInt` limited to 8 bits will only handle values up to 127 decimal or 7F. Add a test that validates the function can parse properly.
I only see a [single user of this function](https://github.com/hashicorp/vault/blob/f5cc167bff4b489f949fe62076c2a7a81eddc490/builtin/credential/cert/path_crls.go#L114-L113) but that function doesn't seem to be used so will not backport this fix for now.

certutil.ParseHexFormatted fails parsing 80 hex and above

---

command/healthcheck/pki.go
command/healthcheck/pki_role_allows_glob_wildcards.go
command/healthcheck/pki_role_allows_localhost.go
command/healthcheck/pki_role_no_store_false.go
command/pki_health_check.go
command/pki_health_check_test.go

~Based on #17750 and #17865; will be rebased once they merge.~
This adds the three role-based health checks: 
- `role_allows_localhost`, for whether or not a role has both a non-empty `allowed_domains` list and `allow_localhost=true`.
- `role_allows_glob_wildcards`, for whether or not a role allows both glob domains and wildcard certs, which is potentially unsafe.
- `role_no_store_false`, for whether or not a role has roles with `no_store=false` and no auto-rebuild of CRLs, as this can cause performance issues.

Add role-based health checks to PKI Health Check

---

changelog/18021.txt
go.mod
go.sum

This PR upgrades the [vault-plugin-auth-alicloud](https://github.com/hashicorp/vault-plugin-auth-alicloud) dependency to the latest pseudo-version from its main branch. The plugin recently had some of its dependencies upgraded in https://github.com/hashicorp/vault-plugin-auth-alicloud/pull/43, which is why additional `go.mod` changes are present in this PR.
Steps:
```sh
go get github.com/hashicorp/vault-plugin-auth-alicloud@main
go mod tidy
```

auth/alicloud: update dependencies

---

builtin/logical/pki/backend.go
builtin/logical/pki/cert_util.go
builtin/logical/pki/path_resign_crls.go
builtin/logical/pki/path_resign_crls_test.go
builtin/logical/pki/test_helpers.go
website/content/api-docs/secret/pki.mdx

- Add a new PKI api `/issuer/<issuer ref>/resign-crls` that will allow combining and signing different CRLs that were signed by the same issuer.
- This allows external actors to combine CRLs into a single CRL across different Vault clusters that share the CA certificate and key material such as performance replica clusters and the primary cluster

Add new PKI api to combine and sign different CRLs from the same issuer

---

website/content/docs/upgrading/upgrade-to-1.13.x.mdx
website/data/docs-nav-data.json

Since we've already identified something for the 1.13 upgrade guide, we'll create the guide now but:
- leave it out of the sidebar
- add a disclaimer to the top

add draft 1.13.x upgrade guide

---

builtin/credential/cert/backend_test.go
builtin/credential/cert/path_login.go
builtin/credential/okta/path_login.go
changelog/18011.txt

Addresses https://github.com/hashicorp/vault/issues/17013
When `handleAuthRenew` is invoked, `b.AuthRenew` is called with nil `framework.FieldData` [here](https://github.com/hashicorp/vault/blob/322ebe5ae1d700bb13f59994bb0455d9db8e7541/sdk/framework/backend.go#LL615-L620C2). This request goes to `pathLoginRenew` and this causes a panic for the case of [Okta](https://github.com/hashicorp/vault/blob/8d14e54b8cf6d9c93a11d2d927726a9bbcb9e0c5/builtin/credential/okta/path_login.go#L146) engine which expects to get a nonce from the field data.
The proposed fix assumes that there could be other code paths that call `pathLoginRenew`. 
```
2022-11-17T09:30:58.576-0800 [INFO]  http: panic serving 127.0.0.1:61385: runtime error: invalid memory address or nil pointer dereference
goroutine 830 …
```

fix auth renew panic

---

command/healthcheck/pki.go
command/healthcheck/pki_enable_auto_tidy.go
command/healthcheck/pki_tidy_last_run.go
command/healthcheck/pki_too_many_certs.go
command/pki_health_check.go

~This is based on top of the earlier PRs and will be rebased when #17877 &co merge.~
This includes three new health checks:
- `enable_auto_tidy`, for encouraging that auto-tidy gets enabled,
- `tidy_last_run` for verifying that tidy gets run on a relevant schedule (separately from the above),
- `too_many_certs`, for verifying that there aren't too many certificates within the mount.

Add auto-tidy, last-tidy, and leaf cert health checks

---

builtin/credential/cert/backend.go
builtin/credential/cert/backend_test.go
builtin/credential/cert/path_crls.go
changelog/18043.txt
website/content/api-docs/auth/cert.mdx

Cert auth method lacked support for listing CRLs. This can cause users to forget which CRLs they've already had provisioned and duplicate them across different names.
Add the LIST capability to allow users to discover which CRLs they've imported already.

Add list to cert auth's CRLs

---

changelog/18030.txt
physical/raft/raft.go
physical/raft/raft_test.go
vault/raft.go
website/content/docs/commands/operator/raft.mdx
website/content/docs/configuration/storage/raft.mdx

Adds `retry_join_as_non_voter` config option for raft storage, including an environment variable override `VAULT_RAFT_RETRY_JOIN_AS_NON_VOTER`. Has the same effect as `vault operator raft join -non-voter`, but only applies to joins performed due to `retry_join` config.

storage/raft: Add retry_join_as_non_voter config option

---

command/healthcheck/pki.go
command/healthcheck/pki_ca_validity_period.go
command/healthcheck/pki_crl_validity_period.go
command/healthcheck/pki_hardware_backed_root.go
command/healthcheck/pki_role_allows_glob_wildcards.go
command/healthcheck/pki_role_allows_localhost.go
command/healthcheck/pki_role_no_store_false.go
command/healthcheck/pki_root_issued_leaves.go
command/healthcheck/pki_too_many_certs.go

Based on top of #17902, will be rebased when that merges.
Renames all plural fetch helpers to using the `List` suffix, and softens langauge in the root check one.

Rename PKI health check helpers 

---

ui/lib/keep-gitkeep/index.js
ui/lib/keep-gitkeep/package.json
ui/package.json

A .gitkeep file was added to `http/web_ui` in order to make the folder compliant with Go's native embedding ([#14246](https://github.com/hashicorp/vault/pull/14246)). However, ever since then while developing on the UI the file would get deleted locally, which caused frustration and overhead for developers to remember not to commit those changes. 
The root cause is that the contents of that folder are generated on hot reload whenever we run the ember server, and the folder contents get overwritten. This PR adds and in-repo addon which writes the .gitkeep file after build for all build types (development, production).

UI: Create .gitignore file on postBuild

---

.github/enos-run-matrices/artifactory-ent.json
.github/enos-run-matrices/crt-ent.json

- Replicate the change (ENT commit: [db10d462f979ef2b35f53366c15c1e0e2bb80ee9](https://github.com/hashicorp/vault-enterprise/commit/db10d462f979ef2b35f53366c15c1e0e2bb80ee9)) that was performed in ENT but not in OSS. Due to that a recent OSS->ENT merge brought back the broken test within ENT.
- Update these files in 1.10.x only in OSS so we don't bring back these tests in ENT in the future

Remove ENOS autopilot tests from 1.10.x branch

---

changelog/18067.txt
command/kv_metadata_patch.go
command/kv_metadata_patch_test.go
command/kv_patch.go
vault/external_tests/kv/kv_patch_test.go

Addresses https://github.com/hashicorp/vault/issues/18034

improve kv CLI to remove data or custom metadata using kv patch

---

ui/app/models/pki/role.js
ui/lib/pki/addon/components/pki-key-parameters.hbs
ui/lib/pki/addon/components/pki-key-parameters.js
ui/lib/pki/addon/components/pki-key-usage.hbs
ui/lib/pki/addon/components/pki-role-form.hbs
ui/tests/integration/components/pki/pki-key-parameters-test.js
ui/tests/integration/components/pki/pki-key-usage-test.js
ui/tests/integration/components/pki/pki-role-form-test.js

This PR removes any `<ToggleGroup>`-ing from the new pki form components to the parent so they can be reused elsewhere

UI: refactor pki role form to reuse PkiKeyParameters component

---

website/package.json

Restrict the node engines declaration for the website so it only uses up to 16.x.

website: restrict node engines to <= 16.x

---

command/healthcheck/pki_allow_if_modified_since.go
command/healthcheck/pki_audit_visibility.go
command/healthcheck/shared.go
command/pki_health_check.go

Based on top of #17901 -- will be rebased once that one merges.
This adds two new health checks: 
- `audit_visibility`, which ensures that relevant parameters are either not HMAC'd or are HMAC'd, depending on [sensitivity](https://developer.hashicorp.com/vault/docs/secrets/pki/considerations#auditing).
- `allow_if_modified_since`, which ensures the If-Modified-Since request parameter and Last-Modified response parameters are passed-through to/from the plugin.

Add mount tuning health checks
