hashicorp/vault

command/healthcheck/pki_ca_validity_period.go, command/healthcheck/pki_crl_validity_period.go, command/healthcheck/pki_hardware_backed_root.go, command/healthcheck/pki_root_issued_leaves.go
=> Fix semgrep false-positive due to co-dependent returns

website/content/docs/enterprise/mfa/index.mdx, website/content/docs/enterprise/mfa/mfa-totp.mdx
- Add note to TOTP about authenticator supported alogrithms
- Fix typos
=> Docs: Enterprise TOTP updates

website/content/docs/platform/k8s/injector/annotations.mdx
From https://github.com/hashicorp/vault-k8s/pull/399
(We should wait to merge this until we are ready to release `vault-k8s`.)
=> Add docs for vault-k8s JSON patch

vault/quotas/quotas.go
See enterprise PR for full set of changes.
=> VAULT-7707 OSS portion of changes

website/content/docs/platform/k8s/injector/annotations.mdx, website/content/docs/platform/k8s/injector/index.mdx
https://github.com/hashicorp/vault-k8s/blob/main/CHANGELOG.md#110-november-17-2022
#17712 covers the json-patch annotations
=> docs/vault-k8s: updates for v1.1.0

website/content/docs/upgrading/upgrade-to-1.12.x.mdx
=> Docs: Clarify plugin versioning known issue

vault/quotas/quotas.go
Backport of https://github.com/hashicorp/vault/pull/18019.
=> Backport 1.10: VAULT-7707 OSS portion of changes (#18019)

vault/quotas/quotas.go
Backport of https://github.com/hashicorp/vault/pull/18019.
=> Backport 1.11: VAULT-7707 OSS portion of changes (#18019)

.github/workflows/security-scan.yml
Pin to commit d679c9eff50e08616bf094d60846bab347ff94a3
=> pin security-scanner workflow

website/content/docs/auth/login-mfa/index.mdx
Some updates from our MFA discussion
Vercel's not working but I have a local preview:
=> Update MFA docs

.github/workflows/security-scan.yml, scan.hcl
update security-scanner and add `generic.html-templates.security.unquoted-attribute-var.unquoted-attribute-var` to exclude-rule
=> update semgrep excludes in security scan

ui/app/styles/components/radio-card.scss, ui/app/templates/components/oidc/client-form.hbs, ui/app/templates/components/oidc/key-form.hbs, ui/app/templates/components/oidc/provider-form.hbs, ui/lib/core/addon/components/radio-card.hbs, ui/lib/core/app/components/radio-card.js, ui/tests/acceptance/oidc-config/clients-assignments-test.js, ui/tests/acceptance/oidc-config/clients-keys-test.js, ui/tests/acceptance/oidc-config/providers-scopes-test.js, ui/tests/integration/components/oidc/client-form-test.js, ui/tests/integration/components/oidc/key-form-test.js, ui/tests/integration/components/oidc/provider-form-test.js
Porting changes to `RadioCard` component from ui/kubernetes-secrets-engine side branch originally done in #18108
Second attempt since #18108 reverted some changes on main
=> Sideport RadioCard v2

website/content/api-docs/system/replication/replication-performance.mdx
Per conversation on Slack with Nick.
Co-authored-by: Nick Cabatoff <ncabatoff@hashicorp.com>
=> Clarify that cluster_id differs between PR Primary/Secondary clusters

website/content/docs/platform/k8s/helm/configuration.mdx, website/content/docs/platform/k8s/helm/enterprise.mdx, website/content/docs/platform/k8s/helm/examples/enterprise-dr-with-raft.mdx, website/content/docs/platform/k8s/helm/examples/enterprise-perf-with-raft.mdx, website/content/docs/platform/k8s/helm/examples/enterprise-with-raft.mdx, website/content/docs/platform/k8s/helm/run.mdx, website/content/partials/helm/install.mdx, website/content/partials/helm/repo.mdx
Updates website documentation for v0.23.0 release.
See https://github.com/hashicorp/vault-helm/releases/tag/v0.23.0 for changelog.
=> Docs: vault-helm 0.23.0 updates

vault/expiration.go
OSS side of changes for potential deadlock issue.
=> VAULT-11786 OSS changes for potential deadlock issue

builtin/logical/pkiext/nginx_test.go
=> Disable nginx integration test in pki test suites

sdk/version/version_base.go
Update version to prep up next minor release of Vault 1.10
=> Update SDK to 1.10.10

changelog/17841.txt, changelog/18031.txt
Related to https://github.com/hashicorp/vault/pull/18144. Updated changelog entries for log-file and log rotation.
=> Updated changelogs from 'feature' to 'improvement'

sdk/version/version_base.go
Update SDK version to next 1.12. Vault version being 1.12.3
=> Update SDK to 1.12.3

website/content/docs/upgrading/upgrade-to-1.12.x.mdx
=> docs: Add 1.12 upgrade note for pending removal builtins

changelog/17749.txt
re: **https://github.com/hashicorp/vault/pull/18144#pullrequestreview-1199406602**
=> Change release note from 'feature' to 'improvement' 

.github/workflows/enos-ci-bootstrap.yml, enos/README.md, enos/ci/bootstrap/main.tf, enos/ci/bootstrap/variables.tf
Update the enos CI bootstrap workflow to:
- add a workflow dispatch trigger
- add repo name to the ssh key name
=> [QT-318] Add workflow dispatch trigger for bootstrap workflow, update ssh key name

website/content/docs/secrets/databases/mssql.mdx
[Removed semi colon from Amazon RDS in MSSQL Database Secrets Engine.](https://app.asana.com/0/563192436488770/1203413797765360/f)
=> Remove semi colon from mysql

website/content/api-docs/auth/jwt.mdx
closes #18264
please let me know if there's anything else that should be changed.
=> Docs: improve bound_audiences documentation for jwt role

changelog/18263.txt, vault/external_tests/raft/raft_autopilot_test.go, vault/external_tests/raft/raft_test.go, vault/logical_system_raft.go
OSS part of https://github.com/hashicorp/vault-enterprise/pull/3395
=> Prevent autopilot from demoting voters when they join a 2nd time

.github/workflows/build-vault-oss.yml, .github/workflows/enos-release-testing-oss.yml
=> test: use the correct actions runner

.github/workflows/build-vault-oss.yml, .github/workflows/enos-release-testing-oss.yml
* Use the correct runner
* Fix indentation
=> test: fix release testing workflows (#18322)

.github/workflows/enos-release-testing-oss.yml
=> test: add build artifacts to release testing workflow

changelog/18342.txt, ui/app/adapters/cluster.js, ui/mirage/handlers/mfa.js, ui/tests/integration/components/mfa-form-test.js
Backports #18342 to release/1.10.x
=> Backport of Duo Passcode Prepend into release/1.10.x

website/content/docs/platform/k8s/helm/configuration.mdx
Fixes [#820](https://github.com/hashicorp/vault-helm/issues/820) and some other minor inconsistencies to do with defaults and data types.
=> [Doc] Fix minor inconsistencies with vault Helm chart

.github/workflows/enos-release-testing-oss.yml
=> test: pass build artifact name to release testing workflow

.github/workflows/enos-release-testing-oss.yml
=> test: normalize job and steps between build and release test workflows

enos/enos-scenario-autopilot.hcl, enos/modules/vault_verify_autopilot/main.tf
Verify upgraded nodes are unsealed before autopilot verification tests
=> Fix autopilot scenario race condition

enos/modules/vault_artifactory_artifact/locals.tf, enos/modules/vault_artifactory_artifact/main.tf
=> Fix Artifactory search for fips and hsm editions

command/commands.go, command/pki.go
=> Add PKI base command

ui/lib/kubernetes/addon/components/page/configure.js, ui/lib/kubernetes/addon/components/page/credentials.js, ui/lib/kubernetes/addon/components/page/overview.js, ui/lib/kubernetes/addon/components/page/role/create-and-edit.js, ui/lib/kubernetes/addon/components/page/role/details.js, ui/lib/kubernetes/addon/components/page/roles.js
Add jsdoc to kubernetes secret engine page component!
=> VAULT-12166 Add jsdoc to kubernetes secret engine pages

.github/workflows/enos-release-testing-oss.yml
=> Save release testing metadata only when tests are run

ui/tests/acceptance/client-history-test.js, ui/tests/integration/components/date-dropdown-test.js
Fixes test failures due to incorrect date conditionals in some ui tests. Opted to skip some tests in favor of the refactor in #17575
=> UI: fix ui date-related tests

website/content/api-docs/secret/gcp.mdx
Correct sample payload of Generate Service Account Key secrets section
=> Correct sample payload at Generate Secret

vault/core.go, vault/logical_system.go, vault/request_handling.go
=> VAULT-12489 OSS Changes

changelog/18568.txt, vault/acl.go
=> Fix HelpOperation on sudo-protected paths

command/format.go, command/login_test.go, vault/login_mfa.go
Addresses https://hashicorp.atlassian.net/browse/VAULT-12490
=> consistent use of passcode for all MFA methods

changelog/18651.txt, ui/app/components/mount-backend-form.js
=> ui: unload auth method when navigating away from form

changelog/18673.txt, vault/core.go, vault/core_test.go
Approved ent branch : https://github.com/hashicorp/vault-enterprise/pull/3415
=> Vault 8308 Background thread to update locked user entries

changelog/18651.txt, ui/app/components/mount-backend-form.js
=> Backport: ui: unload auth method when navigating away from form #18651

website/content/docs/auth/jwt/index.mdx
Based on https://github.com/hashicorp/vault-plugin-auth-jwt/issues/200
[Ticket](https://app.asana.com/0/563192436488770/1203698547045162/f)
=> Added JWT Token Validation

website/README.md, website/package-lock.json, website/package.json
This updates the generated docs for the new [mdx inline alert component](https://github.com/hashicorp/dev-portal/pull/1517). See [docs on dev portal here.](https://developer.hashicorp.com/swingset/components/mdxinlinealert)
=> docs: updates inline alert authoring info

ui/lib/pki/addon/routes/certificates/index.js, ui/lib/pki/addon/routes/roles/index.js, ui/lib/pki/addon/templates/certificates/index.hbs, ui/lib/pki/addon/templates/roles/index.hbs, ui/tests/acceptance/pki/pki-engine-workflow-test.js, ui/tests/helpers/pki/workflow.js
- Add empty states for roles and certificates
- Add test for empty states
**Roles**
**Certificates**
=> ui: VAULT-8673 Add empty states to certificates and roles

enos/enos-scenario-replication.hcl
=> Fix arch for backend storage in Enos replication scenario

changelog/18743.txt, ui/lib/open-api-explorer/addon/components/swagger-ui.js
=> Backport of API Explorer Query Params into release/1.11.x

changelog/18743.txt, ui/lib/open-api-explorer/addon/components/swagger-ui.js
=> Backport of API Explorer Query Params into release/1.10.x

enos/ci/aws-nuke.yml
One last step before we cut the accounts over
=> Add enterprise resources to CI cleanup

enos/enos-modules.hcl, enos/enos-scenario-autopilot.hcl, enos/enos-variables.hcl, enos/modules/shutdown_multiple_nodes/main.tf, enos/modules/vault_raft_remove_peer/main.tf, enos/modules/vault_raft_remove_peer/templates/raft-remove-peer.sh, enos/modules/vault_verify_undo_logs/main.tf, enos/modules/vault_verify_undo_logs/scripts/smoke-verify-undo-logs.sh
Addresses: https://hashicorp.atlassian.net/browse/VAULT-9199
ENT side is [here](https://github.com/hashicorp/vault-enterprise/pull/3560)
=> enos: default undo-logs to cluster behavior

builtin/logical/pki/ca_util.go
=> Add missing space in PKI error

builtin/logical/pki/backend.go, builtin/logical/pki/crl_util.go, builtin/logical/pki/fields.go, builtin/logical/pki/path_config_crl.go, builtin/logical/pki/path_revoke.go, builtin/logical/pki/path_tidy.go, builtin/logical/pki/path_tidy_test.go, builtin/logical/pki/storage.go, builtin/logical/pki/util.go, vault/testing.go
OSS portion of Enterprise PR: https://github.com/hashicorp/vault-enterprise/pull/3439; see that one for more details.
Helps if I base it on a version of `main` with #18735 :-)
=> Add cross-cluster revocation queues for PKI

builtin/logical/pki/backend.go, builtin/logical/pki/cert_util.go, builtin/logical/pki/crl_util.go, builtin/logical/pki/path_config_crl.go, builtin/logical/pki/path_fetch.go, builtin/logical/pki/path_fetch_issuers.go, builtin/logical/pki/storage.go, builtin/logical/pki/util.go
OSS Port of https://github.com/hashicorp/vault-enterprise/pull/3582 ; see that PR for details.
=> Add unified crl building

changelog/18787.txt, ui/app/components/auth-jwt.js
Clarify warning and message as per community suggestion (#10753) to be more explicit about blocked pop-ups.
=> UI: JWT Auth Browser Popup warning. Resolves: #10753.

builtin/logical/pki/path_config_crl.go
=> Ensure unified_crl requires auto_rebuild

ui/lib/pki/addon/templates/configuration/index.hbs
- Temporarily removes configuration toolbar
=> UI: VAULT-12892 temporarily remove configuration toolbar

vault/external_tests/sealmigration/seal_migration_oss_test.go, vault/external_tests/sealmigration/seal_migration_test.go
... and in a moment, an ENT pr that will gate unseal recovery.
=> Don't execute the seal recovery tests on ENT.

website/content/docs/enterprise/fips/fips1402.mdx
=> Add note about mixed FIPS cluster deployments

builtin/logical/pki/path_revoke.go, builtin/logical/pki/storage_unified.go
- Return a detailed response within the LIST API that an end-user can use to determine what clusters revoked the certificate on from the `pki/certs/unified-revoked` LIST API.
- Return colon delimited serial numbers from the certs/revocation-queue LIST API
- Fix a bug in the `unified_storage::lookupUnifiedClusterPaths` that returned cluster ids with a trailing '/' as the key
=> Return a detailed list response for unified-revoked API endpoint

ui/lib/core/addon/components/secret-list-header.hbs
- Update second bullet point copy to be `Cross-signing: cross-sign multiple intermediates in a single step`
=> UI: VAULT-12985 Update pki modal copy

ui/lib/pki/addon/templates/certificates/index.hbs
adds empty state when the pki engine is configured but no certificates have been generated yet
=> ui: add empty state for certificate index view

website/content/api-docs/secret/azure.mdx
Updates the docs for a new field added in https://github.com/hashicorp/vault-plugin-secrets-azure/pull/98
=> Update docs for Azure Secrets Engine new feature

ui/tests/integration/components/date-dropdown-test.js
The tests were written in such a way that they break every January. This is not exactly the code from #18586 but solves the same problem.
=> UI: Fix date-dropdown test

.github/workflows/build.yml
=> [QT-470] Normalize and simplify container build workflows

enos/modules/vault_verify_performance_replication/main.tf, enos/modules/vault_verify_performance_replication/scripts/verify-performance-replication.sh
=> Update replication verification to check connection status

go.mod, go.sum, vault/hcp_link/capabilities/meta/meta.go, vault/hcp_link/internal/wrapped_hcpLink.go
Add `ClusterName` to the `GetClusterStatus` response based on the output of `Core.Cluster()`
=> Add ClusteName to GetClusterStatus response

ui/lib/core/addon/components/secret-list-header.js
- Fix beta modal transitionTo bug. 
- https://hashicorp.atlassian.net/browse/VAULT-13168
=> VAULT-7254 beta pki modal bugfix

website/content/docs/configuration/storage/mysql.mdx
see: https://github.com/hashicorp/vault/blob/main/physical/mysql/mysql.go#L132
=> docs: Change default value for ha_enabled to false

website/content/api-docs/secret/pki.mdx
Adds new API docs on more cross-cluster functionality.
=> Add docs on cross cluster tidy operations

website/content/api-docs/secret/pki.mdx
=> Add docs on cross-cluster listing endpoints

website/content/api-docs/secret/pki.mdx
This adds API docs for the above feature. More PRs to follow with other sections of the doc. :-)
=> Document Cross-Cluster CRLs/OCSP for Vault Enterprise

website/content/api-docs/secret/transit.mdx, website/content/api-docs/system/managed-keys.mdx, website/content/docs/secrets/transit/index.mdx
Documents managed key support in Transit and new parameters in the system backend's managed keys endpoints.
=> Transit Managed Keys Documentation

website/content/docs/secrets/pki/rotation-primitives.mdx
=> Add suggested root rotation procedure

ui/lib/core/addon/components/object-list-input.hbs, ui/lib/core/addon/components/object-list-input.js, ui/lib/pki/addon/components/pki-issuer-cross-sign.hbs, ui/lib/pki/addon/components/pki-issuer-cross-sign.js
=> UI: add error-handling and validation to pki cross-signing

changelog/17893.txt
Updates formatting of changelog entry for Kubernetes secrets engine
=> Changelog entry fix

go.mod, go.sum
No functional changes to the plugin, so no changelog file added.
=> Update terraform secrets plugin version

ui/app/models/pki/certificate/generate.js, ui/lib/pki/addon/components/pki-role-generate.hbs, ui/lib/pki/addon/components/pki-role-generate.ts, ui/tests/helpers/pki/pki-role-generate.js, ui/tests/integration/components/pki-role-generate-test.js, ui/types/vault/models/pki/certificate/generate.d.ts
Add inline errors to generate cert form
=> UI: VAULT-13128 Add inline error to generate cert form

enos/enos-scenario-agent.hcl, enos/enos-scenario-autopilot.hcl, enos/enos-scenario-replication.hcl, enos/enos-scenario-smoke.hcl, enos/enos-scenario-ui.hcl, enos/enos-scenario-upgrade.hcl, enos/enos-variables.hcl, enos/k8s/enos-scenario-k8s.hcl, enos/k8s/enos-variables-k8s.hcl, enos/modules/k8s_deploy_vault/main.tf, enos/modules/k8s_deploy_vault/variables.tf
=> Add Vault log level support

changelog/19145.txt, go.mod, go.sum
Bumps kv secrets engine to include latest events updates.
=> Bump kv plugin v0.14.0->v0.14.2

changelog/19135.txt, ui/app/templates/components/transform-role-edit.hbs
=> Backport of UI: Fix cancel button on role transform form into release/1.10.x

changelog/19194.txt
Feature changelog for event system.
=> Add changelog entry for alpha event system feature

ui/tests/integration/components/database-role-edit-test.js
See PR [here](https://github.com/hashicorp/vault/pull/19190) and the reason I didn't add test coverage in that PR. 
Note: The test was originally included in the PR and so it's been reviewed/approved.
=> Adds test coverage for PR 19190

website/content/docs/upgrading/upgrade-to-1.12.x.mdx
The mentioned changes to plugin loading were added in:
- https://github.com/hashicorp/vault/pull/14946
=> docs/upgrade guide: add changes to plugin loading

vault/external_tests/plugin/external_plugin_test.go
This PR adds more test scenarios for external plugins. In particular we parallelize some of the tests to simulate more realistic workflows.
This is a followup to:
- https://github.com/hashicorp/vault/pull/18952
- https://github.com/hashicorp/vault/pull/19090
- https://github.com/hashicorp/vault/pull/19191
=> test/plugin: add more test scenarios for external plugins

http/events_test.go
I messed up merging in main from #19246, so this re-adds the test coverage I had meant to include on event formatting, plus extends it a little bit now that it's asserting about cloud events formatted events rather than just the payload.
=> Test coverage for event format

changelog/17848.txt, go.mod, go.sum
This reverts commit 21cab77be8df948af147c11758f7fa0620ae8be6.
=> Revert "updated raft-autopilot to v0.2.0 (#17848)"

CHANGELOG.md
Updated with missing OpenAPI-based Go & .NET Client Libraries (Beta) context
=> Add OpenAPI-based (Beta)

.github/scripts/generate-test-package-lists.sh, .github/scripts/test-generate-test-package-lists.sh, .github/workflows/ci.yml, .github/workflows/setup-go-cache.yml, .github/workflows/test-go.yml, command/debug_test.go, command/server/hcp_link_config_test.go, go.mod, go.sum, serviceregistration/kubernetes/testing/testserver.go, tools/tools.go
This PR introduces a GitHub Actions Workflow to eventually replace the **ci** workflow contained in the CircleCI configuration.
=> Introduce GitHub Actions CI Workflow

website/content/docs/upgrading/upgrade-to-1.13.x.mdx
This PR adds an upgrade note to the docs for 1.13.
=> Add upgrade docs for Removed builtins in 1.13

website/content/docs/concepts/policies.mdx
Update documentation to clarify how policies work with default parameters.
=> VAULT-14204 Update parameter policy documentation

vault/request_handling.go, vault/token_store.go
=> VAULT-8337 OSS changes

changelog/19625.txt, vault/activity_log.go, vault/activity_log_util.go, vault/census.go, vault/core.go, vault/testing.go
This PR introduces some OSS plumbing for the Census Agent.
Addresses: VAULT-13194
=> Add no-op CensusAgent

website/content/docs/commands/plugin/deregister.mdx
This PR replaces the automatic [backport PR](https://github.com/hashicorp/vault/pull/19644) which failed due to merge conflict.
=> Manually cherry-pick docs PR 19573

website/content/docs/release-notes/1.13.0.mdx
add a note to known issues section of the Vault 1.13.0 release notes page (https://developer.hashicorp.com/vault/docs/release-notes/1.13.0#known-issues)
preview: https://vault-jmfxzx6en-hashicorp.vercel.app/vault/docs/release-notes/1.13.0#known-issues
=> docs / Update 1.13.0 Known Issues

changelog/19460.txt, ui/app/routes/vault/cluster/oidc-callback.js, ui/tests/unit/routes/vault/cluster/oidc-callback-test.js
=> Backport 1.13.x: AD FS namespace OIDC bug fix #19460 

.github/workflows/ci.yml, .hooks/pre-commit
This PR adds the **test-ui** job as a dependency of the **tests-completed** job, which is currently configured as a required status check on Pull Requests for this repository. This will ensure that if the conditions needed to run the **test-ui** job are met, that it must succeed in order to allow this PR to be merged.
This PR also removes the CircleCI references from the pre-commit git hook in preparation for the removal of the CircleCI configuration.
=> Marcboudreau/vault 13760/add test UI to completed

website/content/partials/tokenstorefields.mdx
- Clarify `token_period` value per feedback
=> Docs: API: Update token_period description

website/content/docs/platform/k8s/vso/installation.mdx
Update the helm commands to work with the beta release.
=> docs/vault-secrets-operator: update for beta install

CHANGELOG.md
Update changelog for 1.13.1, 1.12.5, 1.11.9 relesases
=> changelog: updates for 1.13.1, 1.12.5, 1.11.9

.github/scripts/generate-test-package-lists.sh
Of course, forgetting to add it, I forgot to remove it...
=> Remove acme from CI test_packages

go.mod
Import new SDK version bump to 1.12.6 from #19844
=> Bump vault version to 1.12.6

go.mod
Import new SDK version bump to 1.11.10 from #19845
=> Bump Vault version to 1.11.10

.github/workflows/ci.yml
⚠️ This will need to be rebased on main once PR #19807 is merged in.
=> Update the if conditions for test-go jobs in CI

changelog/19954.txt, go.mod, go.sum, plugins/database/mongodb/mongodb_test.go
Attempt to see if this will fix the 32-bit system failures in TestBackend_StaticRole_Rotations_MongoDB and TestMongoDB_Initialize
=> upgrade mongo driver to 1.11

sdk/framework/testdata/legacy.json, sdk/framework/testdata/operations.json, sdk/framework/testdata/responses.json
A test failure in https://github.com/hashicorp/vault/pull/19319 somehow slipped past the CI. Fixing it in this PR.
=> Fix OpenAPI-related tests

.github/workflows/ci.yml
This PR adds the **workflow_dispatch** trigger to the _ci.yml_ workflow.
=> Add workflow_dispatch Trigger to ci.yml Workflow

vault/token_store_util_common.go
Additional ssct gen counter logs for future debugging.
=> Add extra ssct gen counter debug logs

.github/workflows/ci.yml
This PR is manually generated from #19979 to be assessed for backporting.
---
This PR adds the workflow_dispatch trigger to the ci.yml workflow.
---
<details>
<summary>Overview of commits</summary>
- 7d8d4377897e60080eb4ff1af79b85b5867eea66
</details>
=> Backport Add workflow_dispatch Trigger to ci.yml Workflow into release/1.11.x

.github/workflows/ci.yml
This PR is manually generated from #19979 to be assessed for backporting.
---
This PR adds the workflow_dispatch trigger to the ci.yml workflow.
---
<details>
<summary>Overview of commits</summary>
- 7d8d4377897e60080eb4ff1af79b85b5867eea66
</details>
=> Backport Add workflow_dispatch Trigger to ci.yml Workflow into release/1.13.x

.github/workflows/ci.yml
This PR is manually generated from #19979 to be assessed for backporting.
---
This PR adds the workflow_dispatch trigger to the ci.yml workflow.
---
<details>
<summary>Overview of commits</summary>
- 7d8d4377897e60080eb4ff1af79b85b5867eea66
</details>
=> Backport Add workflow_dispatch Trigger to ci.yml Workflow into release/1.12.x

changelog/19799.txt, ui/app/adapters/namespace.js, ui/app/components/namespace-link.js, ui/app/models/namespace.js, ui/app/serializers/namespace.js, ui/app/templates/vault/cluster/access/namespaces/index.hbs
=> UI: Namespace area fixes (#19799)

website/content/docs/platform/k8s/vso/index.mdx
update index.mdx with installation doc ref to point to the right installation.mdx path
=> update index.mdx with correct installation doc ref

changelog/20070.txt, ui/app/templates/components/keymgmt/distribute.hbs, ui/app/templates/components/mfa/mfa-login-enforcement-header.hbs, ui/app/templates/components/oidc/scope-form.hbs, ui/app/templates/components/pki/config-pki-ca.hbs, ui/app/templates/components/secret-form-show.hbs, ui/app/templates/vault.hbs, ui/app/templates/vault/cluster/access/method/section.hbs, ui/app/templates/vault/cluster/access/mfa/methods/create.hbs, ui/app/templates/vault/cluster/access/oidc/assignments/index.hbs, ui/app/templates/vault/cluster/access/oidc/scopes/index.hbs, ui/app/templates/vault/cluster/secrets/backend/edit-metadata.hbs, ui/lib/core/addon/components/doc-link.js, ui/lib/open-api-explorer/addon/templates/components/swagger-ui.hbs, ui/lib/replication/addon/templates/mode/secondaries/index.hbs
I really thought we had updated all of these, but I came across some that were missed!
=> UI: Fix remaining DocLink paths

vault/testing.go, vault/testing_util.go
=> Revert "Remove dead licensing code and extra core setup"

website/content/docs/auth/jwt/oidc-providers/azuread.mdx
The backport PR (https://github.com/hashicorp/vault/pull/20104) failed due to merge conflict. 
This PR manually resolves the merge conflict and cherry-pick the commit into the `release/1.11.x` branch.
=> [Backport] Fix list formatting (#20076)

ui/app/components/modal-form/policy-template.hbs, ui/app/styles/components/icon.scss, ui/app/styles/components/modal.scss, ui/app/styles/components/popup-menu.scss, ui/app/styles/components/tabs.scss, ui/app/styles/core/breadcrumb.scss, ui/app/styles/core/buttons.scss, ui/app/styles/core/checkbox-and-radio.scss, ui/app/styles/core/file.scss, ui/app/styles/core/inputs.scss, ui/app/styles/core/message.scss, ui/app/styles/core/navbar.scss, ui/app/styles/core/switch.scss, ui/app/styles/helper-classes/spacing.scss, ui/app/styles/helper-classes/typography.scss, ui/app/templates/components/file-to-array-buffer.hbs, ui/lib/core/addon/components/modal.hbs, ui/lib/core/addon/components/text-file.hbs
**The first of many QA and small fixes prs**. I had tickets associated with some of these and others I ran across while QA'ing. (Gosh the app is looking so close to what we have 🤗).
* Spot checked the `core/file.scss` styling. I suspected there were some missing details from the bulma merge so I made a ticket to revisit this file. I found a few missing styles and alphabetized the file for easier navigation.
* Fixed missing `.message-body` coloring for `core/message.scss`. For this, I did actually change some of the colors from what's on main. You probably would not notice the color change with the naked eye. I did this so we could avoid using hard-coded bulma colors and instead use our own color vars. I double checked the look of each of these and I promise you won't notice it unless you …
=> Bulma removal: starting the clean up process

changelog/20064.txt, ui/.template-lintrc.js, ui/app/templates/components/console/log-command.hbs, ui/app/templates/components/console/log-help.hbs, ui/app/templates/components/console/log-list.hbs, ui/tests/integration/components/console/log-command-test.js
backport for https://github.com/hashicorp/vault/pull/20064 + https://github.com/hashicorp/vault/pull/20094
=> Backport 1.12.x: UI/fix browser console formatting

changelog/20064.txt, ui/.template-lintrc.js, ui/app/templates/components/console/log-command.hbs, ui/app/templates/components/console/log-help.hbs, ui/app/templates/components/console/log-list.hbs, ui/tests/integration/components/console/log-command-test.js
=> Backport 1.11.x: UI/fix browser console formatting

changelog/20114.txt, website/content/docs/enterprise/namespaces.mdx
The current link redirects to a personal beauty sales site.
=> Potentially Malicious Link

changelog/20114.txt
CLs removed from backports before realizing I could've removed it from the main PR originally... :-)
=> Delete unnecessary changelog from #20114

changelog/19891.txt, command/server/config_test_helpers.go, command/server/config_test_helpers_util.go, vault/activity_log.go, vault/core.go, vault/logical_system_activity.go, vault/testing.go
=> Revert "Backport of VAULT-13191: OSS changes into release/1.13.x"

vault/activity_log.go, vault/activity_log_util.go, vault/census.go, vault/core.go, vault/testing.go
=> Revert "Backport of Add no-op CensusAgent into release/1.13.x"

builtin/logical/pki/acme_authorizations.go, builtin/logical/pki/acme_wrappers.go, builtin/logical/pki/path_acme_authorizations.go, builtin/logical/pki/path_acme_challenges.go, builtin/logical/pki/path_acme_order.go, builtin/logical/pki/path_acme_test.go
- Add tests to validate that we can load authorizations and challenges from the server and some required fixes to get those working properly.
=> Add tests for fetching ACME authorizations and challenges

changelog/19495.txt
=> Add changelog for constant-time shamir change

changelog/20263.txt, ui/app/models/role-jwt.js, ui/tests/unit/models/role-jwt-test.js
=> Backport UI: OIDC provider logo fix (#20263)

ui/app/components/sidebar/frame.hbs, ui/app/components/sidebar/frame.js, ui/app/components/sidebar/nav/access.hbs, ui/app/components/sidebar/nav/cluster.hbs, ui/app/components/sidebar/nav/policies.hbs, ui/app/components/sidebar/nav/tools.hbs, ui/app/components/sidebar/user-menu.hbs, ui/app/styles/components/console-ui-panel.scss, ui/app/templates/components/console/command-input.hbs, ui/app/templates/components/namespace-picker.hbs, ui/app/templates/vault/error.hbs, ui/mirage/handlers/hcp-link.js, ui/mirage/helpers/modify-passthrough-response.js, ui/tests/acceptance/enterprise-namespaces-test.js, ui/tests/acceptance/enterprise-sidebar-nav-test.js, ui/tests/acceptance/not-found-test.js, ui/tests/acceptance/sidebar-nav-test.js, ui/tests/integration/components/calendar-widget-test.js, ui/tests/integration/components/console/log-command-test.js, ui/tests/pages/components/calendar-widget.js
Adds acceptance tests to validate route changes from the sidebar navigation panels and fixes other test failures from the project. Some additional feedback from #20197 was addressed as well.
=> Sidebar navigation acceptance tests

builtin/logical/pki/acme_challenge_engine.go, builtin/logical/pki/acme_challenges.go
This adds a DNS challenge validator to the PKI ACME server and fixes the retry issues with the challenge engine.
=> Add ACME DNS validator

website/content/api-docs/system/replication/replication-dr.mdx, website/content/api-docs/system/replication/replication-performance.mdx
https://github.com/hashicorp/vault-enterprise/pull/3826 included some updates to the web site that I forgot to put in my OSS PR. This PR has those updates.
=> update website docs for new update-primary mode

website/content/api-docs/libraries.mdx
=> VAULT-15791: Update docs to use vault-java-driver fork

CHANGELOG.md
Update changelog for 1.13.2, 1.12.6, 1.11.10 releases
=> changelog: updates for 1.13.2, 1.12.6, 1.11.10

website/content/api-docs/system/replication/replication-dr.mdx
- Add clarification for secondary_public_key parameter
- Update section header
=> Docs: DR replication API updates

builtin/logical/pki/acme_wrappers.go, builtin/logical/pki/acme_wrappers_test.go, builtin/logical/pki/path_acme_test.go, builtin/logical/pki/path_config_acme.go, builtin/logical/pkiext/pkiext_binary/acme_test.go
Also enforce role and issuer restrictions. :-)
=> Integrate acme config enable/disable into tests

builtin/logical/aws/path_static_creds_test.go, builtin/logical/aws/path_static_roles.go, builtin/logical/aws/path_static_roles_test.go, go.mod, go.sum
This adds the validator code for the static-roles branch, plus related tests
=> validate static role values, add a test, some placeholder descriptions

website/content/docs/secrets/databases/oracle.mdx
This PR manually cherry-pick https://github.com/hashicorp/vault/pull/20361.
* Add HCP tabs, apply Vale suggestions, fix heading case
* Apply feedback
* Apply PM feedback
* Update website/content/docs/secrets/databases/oracle.mdx
* Update website/content/docs/secrets/databases/oracle.mdx
* Update website/content/docs/secrets/databases/oracle.mdx
---------
=> [Backport] Add HCP tabs, apply Vale suggestions, fix heading case (#20361)

ui/tests/acceptance/access/identity/entities/aliases/create-test.js, ui/tests/acceptance/access/identity/groups/aliases/create-test.js, ui/tests/acceptance/secrets/backend/kv/secret-test.js
=> Backport 1.12.7 - UI: Stabilize KV secret tests (#20491)

ui/tests/acceptance/access/identity/entities/aliases/create-test.js, ui/tests/acceptance/access/identity/groups/aliases/create-test.js, ui/tests/acceptance/secrets/backend/kv/secret-test.js
=> Backport 1.11.11 - UI: Stabilize KV secret tests (#20491)

ui/tests/acceptance/access/identity/entities/aliases/create-test.js, ui/tests/acceptance/access/identity/groups/aliases/create-test.js, ui/tests/acceptance/secrets/backend/kv/secret-test.js, ui/tests/integration/helpers/date-format-test.js
=> Backport 1.13.3 - UI: Stabilize KV secret tests (#20491)

audit/format.go, sdk/logical/auth.go, vault/acl.go, vault/acl_test.go, vault/policy.go
OSS version of https://github.com/hashicorp/vault-enterprise/pull/4027
=> [VAULT-14649] Add ns path to granting_policies

.github/workflows/test-go.yml, builtin/logical/nomad/backend_test.go, plugins/database/influxdb/influxdb_test.go
I'm not sure if I'm doing this right 😆
=> use internal docker mirror for CI

builtin/logical/aws/path_static_creds_test.go, builtin/logical/aws/path_static_roles_test.go, builtin/logical/aws/rotation_test.go
This PR adds a number of tests related to the new static-roles code for the aws secrets plugin.
=> Test coverage for static roles

website/content/docs/secrets/kv/kv-v1.mdx, website/content/docs/secrets/kv/kv-v2.mdx
🎟️ [Jira ticket](https://hashicorp.atlassian.net/browse/SPE-111?atlOrigin=eyJpIjoiYWY4NjI3YzdiYTRjNDRjOTg3ZjQ3MjY5ZWU0YmQ4MDAiLCJwIjoiaiJ9)
:mag: [Deploy preview kv-v1](https://vault-800o3nvpo-hashicorp.vercel.app/vault/docs/secrets/kv/kv-v1)
:mag: [Deploy preview kv-v2](https://vault-800o3nvpo-hashicorp.vercel.app/vault/docs/secrets/kv/kv-v2)
- Add request to show KV in conjunction with password policy/generated password.
=> Add requested generated secret example

enos/modules/target_ec2_spot_fleet/main.tf
Determine the allocation pool size for the spot fleet by the allocation strategy. This allows us to ensure a consistent attribute plan during re-runs which avoid rebuilding the target fleets.
=> test: use correct pool allocation for spot strategy

ui/app/components/sidebar/nav/access.hbs, ui/tests/acceptance/sidebar-nav-test.js, ui/tests/integration/components/sidebar/nav/access-test.js
Update OIDC navbar name to OIDC provider
=> UI: VAULT-16309 Update OIDC navbar name to OIDC provider

website/content/docs/concepts/policies.mdx
🎟️ [Jira ticket](https://hashicorp.atlassian.net/browse/SPE-178?atlOrigin=eyJpIjoiZGViMGQzYThhMzJjNDQxMDgyOWJjZTMwZjc4MjQwOTEiLCJwIjoiaiJ9)
🔍 [Deploy preview](https://vault-g4twv2eag-hashicorp.vercel.app/vault/docs/concepts/policies)
- Add root protected endpoint table from Vault policies tutorial
=> Add root protected endpoint table

ui/app/adapters/pki/tidy.js, ui/lib/pki/addon/components/page/pki-tidy-status.hbs, ui/lib/pki/addon/components/page/pki-tidy-status.ts, ui/tests/helpers/pki/page/pki-tidy-status.js, ui/tests/integration/components/pki/page/pki-tidy-status-test.js, ui/types/ember-data/types/registries/adapter.d.ts, ui/types/vault/adapters/pki/tidy.d.ts
- Add custom adapter method for pki tidy
- When user clicks on cancel tidy, confirm cancel pops up
=> UI: VAULT-16368 pki tidy custom method

.github/workflows/actionlint.yml, .github/workflows/build-vault-oss.yml, .github/workflows/build.yml, .github/workflows/changelog-checker.yml, .github/workflows/ci.yml, .github/workflows/drepecated-functions-checker.yml, .github/workflows/enos-fmt.yml, .github/workflows/enos-release-testing-oss.yml, .github/workflows/enos-run-k8s.yml, .github/workflows/godoc-test-checker.yml, .github/workflows/milestone-checker.yml, .github/workflows/oss.yml, .github/workflows/remove-labels.yml, .github/workflows/security-scan.yml, .github/workflows/setup-go-cache.yml, .github/workflows/stable-website.yaml, .github/workflows/test-ci-bootstrap.yml, .github/workflows/test-ci-cleanup.yml, .github/workflows/test-enos-scenario-ui.yml, .github/workflows/test-go.yml, .github/workflows/test-run-acc-tests-for-path.yml, .github/workflows/test-run-enos-scenario-matrix.yml, enos/ci/service-user-iam/service-quotas.tf
* Fix regions on two service quotas
* Request an increase in VPCs per region
* Pin enos workflows
=> ci: request vpc quota increase

audit/format.go, sdk/logical/request.go
=> Revert "VAULT-11595: Augment forwarded requests with host:port info (from/to nodes) (Enterprise)"

changelog/20766.txt, vault/core.go, vault/core_test.go, vault/external_tests/identity/userlockouts_test.go, vault/logical_system_user_lockout.go, vault/request_handling.go, vault/request_handling_util.go
=> Revert "User Lockout Perf Standby Error oss "

ui/app/app.js, ui/app/router.js, ui/lib/ldap/addon/engine.js, ui/lib/ldap/addon/routes.js, ui/lib/ldap/config/environment.js, ui/lib/ldap/index.js, ui/lib/ldap/package.json, ui/package.json
This PR adds an Ember Engine to be used for the LDAP secrets engine.
=> Adds Ember Engine for LDAP Secrets Engine

website/content/docs/platform/k8s/vso/helm.mdx
Updates the helm documentation for the VSO project for beta1.
=> [docs] update helm docs for vso beta1 release

changelog/20548.txt
See: https://hashicorp.atlassian.net/wiki/spaces/VAULT/pages/1311244491/Changelog+Process#New-and-Major-Features
=> Update Vault Proxy changelog to use the new feature format

version/version_base.go
=> Update to rc1

version/version_base.go
This should be updated now that the release branch for 1.14 has been created.
=> Update development version to 1.15

sdk/helper/testcluster/docker/replication.go, vault/request_handling.go
OSS portion of https://github.com/hashicorp/vault-enterprise/pull/3997
=> OSS portion of additional DR failover tests

vault/external_tests/raft/raft_autopilot_test.go
Allowing upgrade migration can make the test flake, e.g. in https://github.com/hashicorp/vault-enterprise/actions/runs/5114335413/jobs/9194515037 we see
```
2023-05-29T18:27:55.237Z [TRACE] core0.raft: adding server to raft via autopilot: id=core-3
2023-05-29T18:27:55.237Z [INFO]  core0.raft: updating configuration: command=AddNonvoter server-id=core-3 server-addr=682a69f1-2120-f406-09e4-aadbbede14d7 servers="[{Suffrage:Voter ID:core-0 Address:127.0.0.1:0} {Suffrage:Voter ID:core-1 Address:e299e63d-66f0-9eb0-2c20-74bdd2b79a04} {Suffrage:Voter ID:core-2 Address:95182566-54e3-b173-d963-b5194814bb9c} {Suffrage:Nonvoter ID:core-3 Address:682a69f1-2120-f406-09e4-aadbbede14d7}]"
2023-05-29T18:27:55.239Z [INFO]  core0.raft: added peer, starting replication: peer=core-3
2023-05-29T18:27:55.240Z …
```
=> TestRaft_Autopilot_DeadServerCleanup: disable upgrade migration on ent

website/content/api-docs/secret/databases/postgresql.mdx
=> website: fix typo in postgresql.mdx

builtin/logical/ssh/backend_test.go
Adds another set of test steps to test the issue path while we're here.
=> Add tests issuing certificate and using against docker

changelog/20897.txt, ui/app/controllers/vault/cluster/init.js, ui/tests/acceptance/init-test.js
=> Backport of UI cluster unseal bug into release/1.12.x

ui/app/adapters/kubernetes/config.js, ui/app/adapters/ldap/config.js, ui/app/adapters/secrets-engine-path.js, ui/app/models/ldap/config.js, ui/app/serializers/ldap/config.js, ui/tests/unit/adapters/kubernetes/config-test.js, ui/tests/unit/adapters/ldap/config-test.js
Initial setup of model, adapter and serializer for LDAP config. Since the adapter setup appeared to be identical from Kubernetes config I elected to extract the methods into a general use adapter.
=> LDAP Config Ember Data Setup

ui/app/adapters/pki/config/acme.js, ui/app/models/pki/config/acme.js, ui/app/models/pki/config/cluster.js, ui/app/models/pki/config/urls.js, ui/lib/pki/addon/components/page/pki-configuration-details.hbs, ui/lib/pki/addon/components/page/pki-configuration-edit.hbs, ui/lib/pki/addon/components/page/pki-configuration-edit.ts, ui/lib/pki/addon/routes/application.js, ui/lib/pki/addon/routes/configuration.js, ui/lib/pki/addon/routes/configuration/edit.js, ui/lib/pki/addon/routes/configuration/index.js, ui/lib/pki/addon/templates/configuration/edit.hbs, ui/lib/pki/addon/templates/configuration/index.hbs, ui/tests/acceptance/pki/pki-engine-workflow-test.js, ui/tests/helpers/pki/page/pki-configuration-edit.js, ui/tests/helpers/pki/workflow.js, ui/tests/integration/components/pki/page/pki-configuration-edit-test.js, website/content/api-docs/secret/pki.mdx
Follow on improvement: 
- Make allowed roles and issuer search selects 
- make roles and issuers linkable in details view
<hr>
=> UI: add pki/config/acme, fix pki/configcluster save bug

command/test-backend/main.go, enos/enos-scenario-agent.hcl, enos/enos-scenario-autopilot.hcl, enos/enos-scenario-replication.hcl, enos/enos-scenario-smoke.hcl, enos/enos-scenario-ui.hcl, enos/enos-scenario-upgrade.hcl, enos/enos-variables.hcl, enos/modules/build_local/main.tf, enos/modules/get_local_metadata/main.tf, enos/modules/vault_cluster/main.tf, enos/modules/vault_cluster/outputs.tf, enos/modules/vault_cluster/scripts/create_audit_log_dir.sh, enos/modules/vault_cluster/scripts/enable_audit_logging.sh, enos/modules/vault_cluster/variables.tf, enos/modules/vault_get_cluster_ips/main.tf, enos/modules/vault_setup_perf_primary/main.tf, enos/modules/vault_unseal_nodes/main.tf, enos/modules/vault_verify_performance_replication/main.tf, enos/modules/vault_verify_read_data/main.tf, enos/modules/vault_verify_write_data/main.tf
Manually backporting the changes for the audit file feature to the `release/1.14.x` release branch.
=> Backport of audit file changes to release/1.14.x

builtin/logical/pki/path_acme_test.go, builtin/logical/pki/test_helpers.go
This adds a few more test scenarios from the automation spreadsheet that we wanted to see :-)
=> Add more tests around issuers, roles, and directories

api/replication_status.go, changelog/20995.txt, sdk/helper/testcluster/replication.go
OSS part of ENT [PR](https://github.com/hashicorp/vault-enterprise/pull/4034)
=> OSS part of replication sys method

builtin/logical/pkiext/pkiext_binary/acme_test.go
This adds tests for certbot renewal both with and without EAB.
=> Add certbot renewal tests to ACME test suite.

enos/enos-scenario-autopilot.hcl
Fix the sneaked in typo from latest autopilot scenario fixes
=> Fix autopilot scenario validation error

builtin/logical/pki/dnstest/server.go
When writing DNS configs, make sure to push the zone file prior to writing the reference to the zone in the named.conf.options file. Otherwise, when adding the initial domain (or any subsequent domains, which isn't really used by these tests), a race occurs between Docker, writing the updated config files, and the bind daemon, detecting that mtime has changed on the named.conf.options file and reloading it and any referenced zone files.
This should fix the error seen in some tests:
> ```
> /etc/bind/named.conf:9: parsing failed: file not found
> ```
=> Fix race in DNS test server configs

ui/lib/kv/addon/routes.js, ui/lib/kv/addon/routes/configuration.js, ui/lib/kv/addon/routes/secrets/create.js, ui/lib/kv/addon/routes/secrets/index.js, ui/lib/kv/addon/routes/secrets/secret/details.js, ui/lib/kv/addon/routes/secrets/secret/diff.js, ui/lib/kv/addon/routes/secrets/secret/edit.js, ui/lib/kv/addon/routes/secrets/secret/metadata/details.js, ui/lib/kv/addon/routes/secrets/secret/metadata/edit.js, ui/lib/kv/addon/routes/secrets/secret/versions.js, ui/lib/kv/addon/templates/configuration.hbs, ui/lib/kv/addon/templates/secrets/create.hbs, ui/lib/kv/addon/templates/secrets/index.hbs, ui/lib/kv/addon/templates/secrets/secret/details.hbs, ui/lib/kv/addon/templates/secrets/secret/diff.hbs, ui/lib/kv/addon/templates/secrets/secret/edit.hbs, ui/lib/kv/addon/templates/secrets/secret/metadata/details.hbs, ui/lib/kv/addon/templates/secrets/secret/metadata/edit.hbs, ui/lib/kv/addon/templates/secrets/secret/versions.hbs
Following the route.js file I added each of the corresponding route template and js files. In the template file I typed out the route path to help while navigating through the engine. I did this when first setting up PKI and found it helpful.
Example of the secrets/index route
=> Add route template and js files

vault/seal.go, vault/seal_autoseal.go, vault/seal_util.go, vault/sealunwrapper.go
Add new file seal_util.go to hold functions that perform seal wrapping and unwrapping.
=> Refactor encryption funcs for the StoredBarrierKeysPath (root key) OSS

website/content/docs/platform/k8s/vso/api-reference.mdx, website/content/docs/platform/k8s/vso/helm.mdx, website/content/docs/platform/k8s/vso/index.mdx, website/content/docs/platform/k8s/vso/installation.mdx
Update api-ref, helm docs, and VSO version for VSO v0.1.0-rc.1 release
=> [Docs] Update api-ref, helm docs, and vso version for v0.1.0-rc.1 

website/content/docs/platform/k8s/vso/api-reference.mdx, website/content/docs/platform/k8s/vso/index.mdx, website/content/docs/platform/k8s/vso/installation.mdx
* Merged main in + fixed merge conflicts
* Fix a typo in api-docs
* Add supported cloud providers + Vault versions to Overview page
* Bulletize a few things
=> [docs] Additional docs updates for VSO GA

changelog/20530.txt
Fixing this feature release note for 1.14 release.
=> Fix release note for Secrets as Environment Variables

website/content/docs/upgrading/upgrade-to-1.12.x.mdx, website/content/docs/upgrading/upgrade-to-1.13.x.mdx
Bad link in the known issue for PKI slow startup.
=> Fix link in known issue

helper/testhelpers/teststorage/teststorage.go, sdk/physical/latency.go, vault/testing.go, website/content/api-docs/system/replication/replication-dr.mdx
ENT PR https://github.com/hashicorp/vault-enterprise/pull/4063
I'll put the changelog in the ENT PR
=> OSS changes for fixing bug in update-primary

helper/testhelpers/teststorage/teststorage.go, sdk/physical/latency.go, vault/testing.go, website/content/api-docs/system/replication/replication-dr.mdx
ENT PR https://github.com/hashicorp/vault-enterprise/pull/4063
=> OSS changes for fixing bug in update-primary (#21119)

website/content/docs/platform/k8s/vso/telemetry.mdx
Adds some initial documentation for telemetry for VSO
=> [docs] add telemetry docs for VSO

website/content/docs/platform/k8s/vso/api-reference.mdx, website/content/docs/platform/k8s/vso/helm.mdx
* Ignore the helm chart changes :)
=> [docs] update api reference for VSO

website/content/docs/enterprise/license/utilization-reporting.mdx
Add the list of parameters included in the payload. 
🔍 [Deploy preview](https://vault-git-docs-update-auto-reporting-hashicorp.vercel.app/vault/docs/enterprise/license/utilization-reporting#example-payloads)
=> Add the payload parameter description

website/content/docs/agent-and-proxy/agent/process-supervisor.mdx
omitted agent injector by mistake, adding here
see https://github.com/hashicorp/vault/pull/21056#discussion_r1227144762
=> [docs] Add note about agent sidecar injector

changelog/20125.txt, ui/app/components/clients/config.js, ui/app/decorators/model-validations.js, ui/app/models/clients/config.js, ui/app/templates/components/clients/config.hbs, ui/app/templates/components/clients/dashboard.hbs, ui/app/templates/vault/cluster/clients.hbs, ui/app/templates/vault/cluster/clients/config.hbs, ui/tests/integration/components/clients/config-test.js
=> Backport of Clients config updates for census reporting into release/1.13.x

website/content/docs/platform/k8s/vso/api-reference.mdx
From hashicorp/vault-secrets-operator@[90ae1b3095c65c1e3eeec157971bd6a3e2c3f5e1](https://github.com/hashicorp/vault-secrets-operator/commit/90ae1b3095c65c1e3eeec157971bd6a3e2c3f5e1)
=> docs/vso: updating pki secret destination doc string

changelog/20125.txt, ui/app/components/clients/config.js, ui/app/decorators/model-validations.js, ui/app/models/clients/config.js, ui/app/templates/components/clients/config.hbs, ui/app/templates/components/clients/current.hbs, ui/app/templates/components/clients/history.hbs, ui/app/templates/vault/cluster/clients.hbs, ui/app/templates/vault/cluster/clients/config.hbs, ui/tests/integration/components/clients/config-test.js
=> Backport of Clients config updates for census reporting into release/1.11.x

changelog/20125.txt, ui/app/components/clients/config.js, ui/app/decorators/model-validations.js, ui/app/models/clients/config.js, ui/app/templates/components/clients/config.hbs, ui/app/templates/components/clients/current.hbs, ui/app/templates/components/clients/history.hbs, ui/app/templates/vault/cluster/clients.hbs, ui/app/templates/vault/cluster/clients/config.hbs, ui/tests/integration/components/clients/config-test.js
=> Backport of Clients config updates for census reporting into release/1.12.x

enos/enos-modules.hcl, enos/enos-variables.hcl
Set the vault and consul default log_level to trace.
=> test: run enos scenarios with trace log level

vault/mount.go, vault/mount_util.go
This is for use in merkle tree management
=> Allow mounted paths to be tracked via path hook 

website/content/docs/secrets/pki/considerations.mdx
This adds a few notes to the considerations guide around ACME support:
- No client is shipped,
- Notes on running ACME on publicly-facing Vault servers
- Tidy/scalability importance
- Error logs location
- How to restrict access to particular roles/issuers
- Other general security considerations
This also includes an expanded key types discussion with benchmark-vault.
=> ACME Considerations Guide

builtin/logical/pki/path_acme_test.go, builtin/logical/pki/path_ocsp_test.go, builtin/logical/pki/test_helpers.go
- Some changes within the OSS test helpers to help in the ACME Enterprise test cases.
=> Supporting PR for Enterprise ACME PR cluster tests

website/content/api-docs/relatedtools.mdx
=> [docs] Add Agent & Proxy to related tools

ui/app/components/dashboard/secrets-engines-card.js, ui/app/components/sidebar/frame.hbs, ui/app/components/sidebar/nav/cluster.hbs, ui/app/routes/vault/cluster/dashboard.js, ui/app/routes/vault/cluster/secrets/backends.js, ui/app/styles/helper-classes/flexbox-and-grid.scss, ui/app/styles/helper-classes/general.scss, ui/app/styles/helper-classes/spacing.scss, ui/app/templates/components/dashboard/secrets-engines-card.hbs, ui/app/templates/vault/cluster/dashboard.hbs, ui/tests/acceptance/dashboard-test.js, ui/tests/helpers/components/dashboard/secrets-engines-card.js, ui/tests/integration/components/dashboard/secrets-engines-card-test.js, ui/tests/integration/components/sidebar/nav/cluster-test.js
- Query data for the secrets engines card
- Create component for secrets engines card
- Create secrets engines card test
- TODO: Fix the table to have rounded borders (VAULT-17365)
- TODO for design
- ask yongqi about the Secrets Engines Title so that it's more specific to users about how many are being shown
- ask about namespaces and whether we should move them up or include them in dashboard header
- ask about how unsupported backends look in the card
- confirm how long descriptions will look
=> UI: VAULT-17008 Dashboard Secrets Engines Card

website/content/docs/enterprise/license/faq.mdx
Remove dead link in Enterprise license FAQ page.
=> Update license faq.mdx to remove a dead link

website/content/docs/configuration/log-requests-level.mdx
I made some small updates to these docs based on my experience with playing around with this feature. I fixed a couple of typos, added some additional information, and added a new example that should hopefully help.
=> Update logging completed requests docs

CHANGELOG.md
Update CHANGELOG.md for 1.14.0, 1.13.4, 1.12.8 and 1.11.12
=> Update CHANGELOG.md for 1.14.0, 1.13.4, 1.12.8 and 1.11.12

command/server/config.go, command/server/config_test_helpers.go, command/server/config_util.go, internalshared/configutil/config.go, internalshared/configutil/env_var_util.go, internalshared/configutil/kms.go, internalshared/configutil/kms_test.go
This is the OSS side of the changes for seal config checks and using env vars for seals
=> Vault-11623: OSS changes for seal config and env vars

changelog/21375.txt
changelog for https://github.com/hashicorp/vault/pull/21375
=> changelog for replacing AlertBanner with <Hds::Alert>

website/content/docs/auth/index.mdx
This is my recommended revision to the documentation based on what I believe the author was originally trying to communicate.  Please review any discussion in #21300 prior to merging.
resolves #21300
=> docs: clarify external auth method considerations

ui/app/models/ldap/config.js, ui/lib/core/addon/components/secrets-engine-mount-config.hbs, ui/lib/core/addon/components/secrets-engine-mount-config.ts, ui/lib/core/app/components/secrets-engine-mount-config.js, ui/lib/ldap/addon/components/config-cta.hbs, ui/lib/ldap/addon/components/page/configuration.hbs, ui/lib/ldap/addon/components/page/configuration.ts, ui/lib/ldap/addon/routes/configuration.ts, ui/lib/ldap/addon/templates/configuration.hbs, ui/mirage/factories/ldap-config.js, ui/tests/integration/components/ldap/config-cta-test.js, ui/tests/integration/components/ldap/page/configuration-test.js, ui/tests/integration/components/secrets-engine-mount-config-test.js, ui/types/vault/app-types.ts, ui/types/vault/models/ldap/config.d.ts, ui/types/vault/models/mount-config.d.ts, ui/types/vault/models/secret-engine.d.ts
This PR adds components for the LDAP configuration view.
=> LDAP Configuration

website/content/docs/upgrading/upgrade-to-1.13.x.mdx, website/content/docs/upgrading/upgrade-to-1.14.x.mdx, website/content/partials/known-issues/update-primary-addrs-panic.mdx, website/content/partials/update-primary-addrs-panic.mdx
A fix for this will be available in the next minor release of Vault.
=> Add known issue about update_primary_addrs panic

changelog/README.md
Related: #20903
See also: #20864
=> Document multiple changelog entries in one file

internalshared/configutil/env_var_util.go
This uses wrapper constants for env var names
=> Update env vars to use wrapper constants

helper/syncmap/syncmap_test.go
=> Use the sorted values so that the test is not flaky

.github/scripts/plugin-helper-gh-pr-create.sh, .github/workflows/plugin-update-check.yml
Make the plugin update check workflow comment on the plugin repo's PR with a link to itself.
=> updates to plugin update check

.github/scripts/plugin-helper-gh-pr-create.sh
=> Add some debugging to figure out what is happening

.github/scripts/plugin-helper-gh-pr-create.sh
Some more fixes to how the workflow creates the vault dependency test pr
(this is a hackweek pr)
=> more plugin workflow changes

.github/scripts/plugin-helper-gh-pr-create.sh
another hackweek fix, this is cuts something we would like to do, but the token permissions aren't quite there
=> comment out pr editing due to permissions issues

changelog/21531.txt, ui/app/templates/components/configure-ssh-secret.hbs
Description:
- removes extra class
Before bugfix:
After:
=> UI: VAULT-17699 Fix masked input bug

.github/scripts/plugin-helper-gh-pr-create.sh, .github/workflows/plugin-update-check.yml
This is a companion PR to https://github.com/hashicorp/vault-workflows-common/pull/34, preparing the workflow for potential prod use.
=> Plugin workflow updates

website/content/docs/commands/pki/health-check.mdx
Add steps and guidance for operators on how to address some of the feedback from the pki health-check output.
=> Add remediation steps to the PKI health-check docs

.github/workflows/add-hashicorp-contributed-label.yml
We don't expect any community contributions on anything but our OSS repo :)
=> Run add-hashicorp-contributed-label only on OSS

ui/app/adapters/ldap/role.js, ui/app/models/ldap/role.js, ui/app/serializers/kubernetes/role.js, ui/app/serializers/ldap/role.js, ui/tests/unit/adapters/ldap/role-test.js, ui/tests/unit/serializers/ldap/role-test.js
This PR adds a model, adapter and serializer for LDAP roles.
=> LDAP Role Model, Adapter and Serializer

ui/app/adapters/ldap/library.js, ui/app/models/ldap/library.js, ui/app/models/ldap/role.js, ui/app/serializers/ldap/library.js, ui/app/serializers/ldap/role.js, ui/tests/unit/adapters/ldap/library-test.js, ui/tests/unit/serializers/ldap/library-test.js
This PR adds a model, adapter and serializer for LDAP libraries.
=> LDAP Library Model, Adapter and Serializer

.github/configs/milestone-check.json, .github/workflows/ci.yml, .github/workflows/milestone-checker.yml, .github/workflows/oss.yml
Also simplify the milestone check to just check if the milestone exists for the pull request
=> VAULT-14696: Pin 3rd party actions

.github/workflows/ci.yml, .github/workflows/test-go.yml, .github/workflows/verify_changes.yml
Now each failure in the row will have a link to relevant logs.
=> VAULT-12958 Go test failure summary improvements

helper/experiments/experiments.go, http/events_test.go, vault/events_test.go, vault/testing.go
- allow to configure experiments in test cores
- add experiment for secrets sync
=> Allow to configure experiments in test cores

website/content/docs/use-cases.mdx
=> grammar fix

ui/lib/core/addon/components/navigate-input.js
Noticed this console error happening on kubernetes/role Navigate Input after this [PR update](https://github.com/hashicorp/vault/pull/21767). Fixed with a small check.
=> Navigate Input fix

.github/workflows/ci.yml, .github/workflows/oss.yml
This is in order to complete SEC-90 for Vault, updates the comments and pin a version used elsewhere.
=> Update action pinning

vault/mount.go
ENT side:https://github.com/hashicorp/vault-enterprise/pull/4271
=> OSS part of taint-namespace-sys-test

.github/workflows/enos-lint.yml, .github/workflows/test-run-enos-scenario-matrix.yml, enos/Makefile, enos/enos-modules.hcl, enos/enos-scenario-autopilot.hcl, enos/enos-scenario-proxy.hcl, enos/enos-scenario-replication.hcl, enos/enos-scenario-smoke.hcl, enos/enos-scenario-ui.hcl, enos/enos-scenario-upgrade.hcl, enos/enos-variables.hcl, enos/enos.vars.hcl, enos/modules/target_ec2_fleet/main.tf, enos/modules/target_ec2_instances/main.tf, enos/modules/target_ec2_spot_fleet/main.tf, enos/modules/vault_proxy/main.tf, enos/modules/vault_proxy/templates/set-up-approle-and-proxy.sh, enos/modules/vault_proxy/templates/use-proxy.sh
Fix sync issues between oss and enterprise and add a lint check to ensure invalid scenarios aren't accidentally merged.
=> test: fix drift between enos directories

website/content/docs/secrets/databases/oracle.mdx
I am not an Oracle expert but working through example workflows these are the privileges I needed.
=> docs/oracle: add admin privileges needed

ui/app/models/ldap/role.js, ui/lib/ldap/addon/components/page/configure.ts, ui/lib/ldap/addon/components/page/role/create-and-edit.ts, ui/lib/ldap/addon/components/page/role/details.hbs, ui/lib/ldap/addon/components/page/role/details.ts, ui/lib/ldap/addon/routes/roles/role.ts, ui/lib/ldap/addon/routes/roles/role/details.ts, ui/lib/ldap/addon/routes/roles/role/edit.ts, ui/lib/ldap/addon/routes/roles/role/index.ts, ui/lib/ldap/addon/templates/roles/role/details.hbs, ui/tests/integration/components/ldap/page/role/details-test.js
This PR adds a route and page component for ldap role details.
=> LDAP Role Details

CHANGELOG.md
Updating CHANGLOG.md for 1.14.1, 1.13.5, and 1.12.9
=> Changelog update for 1.14.1, 1.13.5, and 1.12.9

changelog/21583.txt
Fixed changelog's release note for PR #21583, which is titled "UI: Add example modal to policy form"
=> UI: Fix changelog for PR #21583

.github/workflows/plugin-update-check.yml
Add `run-name` for better discoverability, fix bug with fetching Vault PR url, and don't fail if we can't add labels to the Vault PR.
=> gh action: update plugin update check

.github/workflows/plugin-update.yml
This will allow manual dispatch of a GH workflow to update a plugin by tag.
=> gh action: add plugin update job

website/content/docs/secrets/databases/mssql.mdx
These were the permissions I needed to generate dynamic secrets, revoke leases and rotate the root credential.  Let me know if anything is overly permissive!
=> docs/mssql: add admin privileges needed

website/content/api-docs/index.mdx
https://github.com/hashicorp/vault/blob/3acfa450c2605226418c7dad00b39cbfb857f7b4/website/content/api-docs/system/health.mdx#L26
=> add 472 return code

website/content/api-docs/index.mdx
Manual cherry-pick of [PR 22105](https://github.com/hashicorp/vault/pull/22105)
* add 472 return code
* Updated the wording for consistency
---------
=> Add 472 return code (#22105)

buf.yaml
Update the `buf lint` config file with the exceptions needed by vault-enterprise.
=> Add protobuf linter config necessary for vault-enterprise.

ui/app/models/ldap/library.js, ui/app/styles/helper-classes/colors.scss, ui/app/styles/helper-classes/spacing.scss, ui/lib/core/addon/components/form-field.hbs, ui/lib/ldap/addon/components/page/library/create-and-edit.hbs, ui/lib/ldap/addon/components/page/library/create-and-edit.ts, ui/lib/ldap/addon/routes/libraries/create.ts, ui/lib/ldap/addon/routes/libraries/library.ts, ui/lib/ldap/addon/routes/libraries/library/edit.ts, ui/lib/ldap/addon/routes/libraries/library/index.ts, ui/lib/ldap/addon/templates/libraries/create.hbs, ui/lib/ldap/addon/templates/libraries/library/edit.hbs, ui/mirage/factories/ldap-library.js, ui/mirage/handlers/ldap.js, ui/tests/integration/components/ldap/page/library/create-and-edit-test.js, ui/tests/integration/components/ldap/page/role/create-and-edit-test.js, ui/types/vault/models/ldap/library.d.ts
This PR adds routes and a page component for ldap library create and edit workflows.
=> LDAP Library Create and Edit

ui/app/adapters/ldap/library.js, ui/app/models/ldap/library.js, ui/lib/ldap/addon/components/page/libraries.hbs, ui/lib/ldap/addon/components/page/libraries.ts, ui/lib/ldap/addon/routes/libraries/index.ts, ui/lib/ldap/addon/routes/roles/index.ts, ui/lib/ldap/addon/templates/libraries/index.hbs, ui/lib/ldap/index.js, ui/mirage/handlers/ldap.js, ui/tests/integration/components/ldap/page/libraries-test.js
This PR adds a route and page component for the ldap libraries list view
=> LDAP Libraries

ui/lib/kv/addon/components/page/secret/metadata/version-history.hbs
=> UI: disable create popup menu link from deleted version

ui/app/adapters/ldap/library.js, ui/app/app.js, ui/app/models/ldap/library.js, ui/app/styles/helper-classes/colors.scss, ui/app/styles/helper-classes/general.scss, ui/app/styles/helper-classes/spacing.scss, ui/lib/ldap/addon/components/accounts-checked-out.hbs, ui/lib/ldap/addon/components/accounts-checked-out.ts, ui/lib/ldap/addon/components/page/library/details/accounts.hbs, ui/lib/ldap/addon/components/page/library/details/accounts.ts, ui/lib/ldap/addon/engine.js, ui/lib/ldap/addon/routes/libraries/library/details/accounts.ts, ui/lib/ldap/addon/templates/libraries/library/details/accounts.hbs, ui/tests/integration/components/ldap/accounts-checked-out-test.js, ui/tests/integration/components/ldap/page/library/details/accounts-test.js, ui/tests/unit/adapters/ldap/library-test.js, ui/types/ember-data/types/registries/adapter.d.ts, ui/types/vault/adapters/ldap/library.d.ts, ui/types/vault/models/ldap/library.d.ts, ui/types/vault/services/auth.d.ts
This PR adds a route and components for the ldap library details accounts tab.
=> LDAP Library Account Details

audit/entry_formatter.go, audit/nodes.go, audit/nodes_test.go, audit/types.go
Great catch Marc! I'm wondering if we can just check the node type and save having to mess with things at particular indexes?
=> suggestion for log test message fix

ui/lib/kv/addon/components/kv-version-dropdown.hbs, ui/lib/kv/addon/components/page/secret/details.hbs, ui/lib/kv/addon/components/page/secret/metadata/details.hbs, ui/lib/kv/addon/components/page/secret/metadata/version-diff.hbs, ui/lib/kv/addon/components/page/secret/metadata/version-history.hbs, ui/tests/acceptance/secrets/backend/kv/kv-engine-permissions-test.js, ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-navigation-test.js
=> Move version diff to dropdown and remove from tab

ui/app/adapters/kv/data.js, ui/app/components/secret-edit-toolbar.js, ui/app/templates/components/secret-edit-toolbar.hbs, ui/lib/core/addon/components/copy-secret-dropdown.hbs, ui/lib/core/app/components/copy-secret-dropdown.js, ui/lib/kv/addon/components/page/secret/details.hbs, ui/lib/kv/addon/components/page/secret/details.js, ui/tests/acceptance/secrets/backend/cubbyhole/secret-test.js, ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-navigation-test.js, ui/tests/acceptance/secrets/backend/kv/secret-test.js, ui/tests/helpers/secret-edit-toolbar.js, ui/tests/integration/components/copy-secret-dropdown-test.js
- Moves copy dropdown into separate component
- Adds copy and wrap secret functionality to secret details page
=> UI: Copy/wrap kv secret

ui/lib/core/addon/components/page/breadcrumbs.hbs, ui/lib/ldap/addon/components/page/overview.hbs, ui/lib/ldap/addon/routes/roles/role/details.ts, ui/mirage/factories/ldap-role.js, ui/mirage/handlers/ldap.js, ui/mirage/scenarios/default.js, ui/mirage/scenarios/index.js, ui/mirage/scenarios/ldap.js, ui/tests/acceptance/secrets/backend/ldap/libraries-test.js, ui/tests/acceptance/secrets/backend/ldap/overview-test.js, ui/tests/acceptance/secrets/backend/ldap/roles-test.js, ui/tests/helpers/ldap.js, ui/tests/integration/components/ldap/page/overview-test.js
This PR adds acceptance tests for the ldap secrets engine workflows and actions not covered page integration tests.
=> LDAP Acceptance Tests

website/content/docs/platform/k8s/vso/api-reference.mdx, website/content/docs/platform/k8s/vso/helm.mdx, website/content/partials/kubernetes-supported-versions.mdx
https://github.com/hashicorp/vault-secrets-operator/releases/tag/v0.2.0
=> docs/vault-secrets-operator: 0.2.0 release updates

ui/docs/fetch-secrets-engine-config.md, ui/lib/ldap/addon/routes/configuration.ts, ui/lib/ldap/addon/routes/configure.ts, ui/lib/ldap/addon/routes/libraries/index.ts, ui/lib/ldap/addon/routes/overview.ts, ui/lib/ldap/addon/routes/roles/index.ts
This PR adds documentation for the `fetch-secrets-engine-config` decorator with example usage.
=> Fetch Secrets Engine Config Decorator Docs

enos/enos-scenario-replication.hcl, enos/enos-scenario-smoke.hcl, enos/enos-scenario-ui.hcl, enos/enos-scenario-upgrade.hcl, enos/enos-variables.hcl
I accidentally removed this step on an earlier PR. Adding back in.
=> Add `get_local_metadata` step back into `upgrade` scenario

changelog/22452.txt, vault/logical_system_quotas.go, vault/quotas/quotas.go, vault/quotas/quotas_rate_limit.go, vault/quotas/quotas_rate_limit_test.go, vault/quotas/quotas_test.go, vault/quotas/quotas_util.go
ENT PR: https://github.com/hashicorp/vault-enterprise/pull/4552
=> Quota Inheritance for Rate Limit (OSS)

sdk/helper/consts/consts.go, vault/testing.go, website/content/api-docs/system/replication/replication-dr.mdx
=> OSS changes for https://github.com/hashicorp/vault-enterprise/pull/4254

ui/lib/core/addon/components/page/error.hbs, ui/lib/kv/addon/routes/error.js, ui/lib/kv/addon/templates/error.hbs, ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-edge-cases-test.js, ui/tests/helpers/kv/kv-selectors.js
Adds error substate to kv engine
=> ui: KV add error template substate

website/content/docs/auth/jwt/oidc-providers/azuread.mdx
Update broken link to Azure docs for using claims to reliably identify a user.
=> Update azuread.mdx link to "Use claims to reliably identify a user"

website/content/docs/platform/k8s/vso/openshift.mdx, website/data/docs-nav-data.json
Adds info about installing the operator on openshift.
=> docs/vault-secrets-operator: add openshift page

ui/app/styles/components/code-snippet.scss, ui/app/styles/core.scss, ui/lib/core/addon/components/code-snippet.hbs, ui/lib/core/app/components/code-snippet.js
Code snippet display only component for consistent styling
=> UI: code snippet component

changelog/22502.txt, ui/.gitignore, ui/app/components/get-credentials-card.js, ui/app/templates/components/get-credentials-card.hbs, ui/app/templates/vault/cluster/secrets/backend/list.hbs, ui/lib/core/addon/components/input-search.js, ui/tests/integration/components/get-credentials-card-test.js
=> Backport UI: Allow navigate to list from View Secret card (#22502)

.github/workflows/ci.yml, .github/workflows/security-scan.yml
This has already been removed from the ent side (moved into its own file), removing it here to reduce differences between ci.yml in the two repos.
=> Fix some ci inconsistencies, and logic for security scan and go test comment

ui/app/models/kmip/scope.js, ui/app/models/transform.js
Follow-on to this PR https://github.com/hashicorp/vault/pull/22483
=> ui: fix missing KMIP and Transform apiPath param

website/content/docs/enterprise/pkcs11-provider/oracle-tde.mdx
Remove Note block which was causing a formatting issue with the sql code under Enable TDE
=> Update oracle-tde.mdx Formatting issues

http/events_test.go
CI is sometimes slow, so 100ms was not enough time for all events to be sent and processed in `http/events_test.go`.
We bumped that timeout to a full 1 second, but also added a trick at the end to shorten the timeout once the expected number of events have been receieved. This way, once the test has passed, we only wait 100ms for any "extra" events to make the test fail, instead of waiting for the full 1 second before we let the test pass. This should keep the test relatively fast, while still allowing for it to be slow sometimes.
=> Allow more time for CI events test

command/server.go, vault/core.go, vault/seal/seal.go
This is the Vault community counterpart for the vault-enterprise PR #4611.
=> Fix JSON serialization of SealGenerationInfo.

vault/request_handling.go, vault/wrapping.go
This PR removes some role-tracking in non-login paths.
=> Only track role in login path

.github/workflows/actionlint.yml, .github/workflows/enos-release-testing-oss.yml, .github/workflows/security-scan.yml, .github/workflows/stable-website.yaml, .github/workflows/test-acc-dockeronly-nightly.yml, .github/workflows/test-ci-bootstrap.yml, .github/workflows/test-enos-scenario-ui.yml
This PR adds concurrency controls to minimize redundant workflow runs.
=> RELENG-773: Add GitHub workflow concurrency controls

command/operator_diagnose.go, command/server.go, helper/testhelpers/seal/sealhelper.go, vault/core.go, vault/logical_system.go, vault/rekey.go, vault/seal/seal.go, vault/seal/seal_testing.go, vault/seal_autoseal.go, vault/seal_testing_util.go
This is a simple refactoring of names, there are no behaviour changes.
=> Rename SealInfo to SealWrapper.

ui/app/components/dashboard/quick-actions-card.js, ui/app/components/dashboard/secrets-engines-card.js, ui/app/templates/components/dashboard/quick-actions-card.hbs, ui/app/templates/components/dashboard/secrets-engines-card.hbs, ui/tests/helpers/components/dashboard/dashboard-selectors.js, ui/tests/integration/components/dashboard/overview-test.js
Description
- add empty states when no secrets engines returned
=> UI: [VAULT-19560] Add empty states and tests

command/operator_diagnose.go, command/server.go, command/server_sealgenerationinfo_test.go, vault/seal/seal.go, vault/seal_stubs_oss.go
This PR add changes to reject seal config changes if current seal generation is in middle of rewrapping.
=> Add checks to see if current seal generation is in middle of rewrapping

builtin/logical/database/path_roles.go, builtin/logical/database/rotation.go
Fix a bug where rotations would occur outside a rotation window after rotation errors.
Working on tests and will add them in a separate PR.
=> fix rotation_window bug in error path

vault/seal/seal_wrapper.go
Aligns formatting using `make fmt`.
=> seal_wrapper: make fmt fix

vault/plugin_runtime_catalog.go
add missing copyright header in https://github.com/hashicorp/vault/pull/22469
=> add copyright header

command/transit_import_key.go
- Doubtful this will ever happen in real life
- We would nil panic if the public_key field was not present in the wrapping key response
- Also trap a casting error if the public key was not an RSA public key
Discovered when doing a little audit based on https://github.com/hashicorp/vault/pull/22753
=> Improve transit import command error handling

changelog/22797.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/6099408033
=> Update hashicorp/vault-plugin-auth-kerberos to v0.10.1

changelog/22799.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/6099580101
=> Update hashicorp/vault-plugin-secrets-azure to v0.16.2

changelog/22823.txt, go.mod, go.sum, vault/seal/seal.go, website/content/partials/db-secrets-credential-types.mdx
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/6101690775
=> Update hashicorp/vault-plugin-secrets-kubernetes to v0.6.0

vault/seal/seal.go
=> fmt: fix formatting

vault/activity_log.go, vault/logical_system_activity_write_testonly.go, vault/logical_system_activity_write_testonly_test.go
=> [VAULT-15398] Activity log data generation fixes

api/sys_plugins.go, command/plugin_list.go, sdk/helper/pluginutil/runner.go, vault/logical_system.go, vault/plugin_catalog.go
add oci_image and runtime to VersionedPlugin
=> add oci_image and runtime to VersionedPlugin

website/content/api-docs/secret/databases/index.mdx, website/content/docs/secrets/databases/index.mdx
Add docs for the upcoming 1.15 feature
- https://github.com/hashicorp/vault/pull/22484
=> docs: db schedule-based static role rotations

changelog/22871.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/6114312083
=> Update hashicorp/vault-plugin-database-couchbase to v0.9.4

builtin/logical/transit/backend_test.go, builtin/logical/transit/path_datakey.go, builtin/logical/transit/path_encrypt.go, builtin/logical/transit/path_encrypt_test.go, builtin/logical/transit/path_rewrap.go, changelog/22852.txt, sdk/helper/keysutil/policy.go
=> Reject supplied nonces for non-convergent encryption operations (#22852)

enos/modules/vault_artifactory_artifact/variables.tf
Fix release testing workflow: https://github.com/hashicorp/vault/actions/runs/6125770695/job/16628447630#step:10:51
Verified the fix locally with the same artifact and scenario.
=> test: fix release testing from artifactory

internalshared/configutil/kms.go
* Initialize seal config map if nil
* Move the function outside if
=> Backport 1.15.x - Initialize seal config map if nil (#22912)

website/content/docs/enterprise/hsm/behavior.mdx, website/content/docs/enterprise/hsm/index.mdx, website/content/docs/enterprise/hsm/security.mdx
HSM support is not available for HCP Vault at this time.
=> removed HCP Plus cluster

ui/app/models/namespace.js, ui/lib/core/addon/components/edit-form.js, ui/lib/core/addon/components/form-field.hbs, ui/lib/core/addon/components/form-save-buttons.hbs, ui/lib/core/addon/components/form-save-buttons.js, ui/lib/core/addon/templates/components/edit-form.hbs
=> Backport UI: Namespace validation update (#22820)

website/content/api-docs/secret/transit.mdx
Adds API docs on the new Transit X.509 certificate features!
=> Add API docs on Transit X.509 certificates

ui/app/adapters/ldap/role.js, ui/app/services/store.js, ui/lib/core/addon/components/filter-input.hbs, ui/lib/core/addon/components/filter-input.ts, ui/lib/ldap/addon/components/page/role/create-and-edit.ts, ui/lib/ldap/addon/components/page/role/details.ts, ui/lib/ldap/addon/components/page/roles.hbs, ui/lib/ldap/addon/components/page/roles.ts, ui/lib/ldap/addon/controllers/roles/index.ts, ui/lib/ldap/addon/routes/roles/index.ts, ui/lib/ldap/addon/templates/roles/index.hbs, ui/tests/acceptance/secrets/backend/ldap/roles-test.js, ui/tests/integration/components/filter-input-test.js, ui/tests/integration/components/ldap/page/roles-test.js, ui/types/vault/services/store.d.ts
This PR adds pagination for LDAP roles.
https://github.com/hashicorp/vault/assets/24611656/0014b974-3972-4d35-bb48-a410db608f8b
=> LDAP Roles Pagination

website/content/docs/platform/mssql/installation.mdx
Add MSSQL version to EKM installation doc as requested.
=> Add MSSQL version to EKM install doc

changelog/23059.txt, website/content/api-docs/auth/azure.mdx
Changelog and doc for https://github.com/hashicorp/vault-plugin-auth-azure/pull/133
=> Update changelog for auth/azure v0.16.2

changelog/23060.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/6177857384
=> Update hashicorp/vault-plugin-auth-azure to v0.16.2

website/content/docs/auth/approle.mdx, website/content/docs/auth/ldap.mdx, website/content/docs/auth/userpass.mdx, website/content/partials/user-lockout.mdx
Adds section about user lockout to userpass, approle, and ldap docs.
=> Add section about user lockout

ui/app/components/file-to-array-buffer.js, ui/app/templates/components/file-to-array-buffer.hbs
This PR addresses an issue in the `file-to-array-buffer` component that was causing flakiness in test runs as well as updates the component to glimmer ✨ ✨ .
=> Raft Storage Flaky Test

website/content/api-docs/secret/identity/entity-alias.mdx
I updated the LIST identity/entity-alias/id endpoint docs to include details on new data that the endpoint returns.
=> updated the LIST identity/entity-alias/id endpoint docs 

builtin/logical/database/path_roles.go, builtin/logical/database/path_roles_test.go
Addressing some feedback from
- https://github.com/hashicorp/vault/pull/22484
=> secrets/db: add tests for static role config updates

changelog/23066.txt, ui/app/styles/components/confirm.scss, ui/lib/core/addon/components/confirm.js, ui/lib/core/addon/templates/components/confirm.hbs
backport of https://github.com/hashicorp/vault/pull/23066
=> Backport 1.14.3: confirm delete modal for namespaces

command/server.go, go.mod, go.sum, internalshared/configutil/kms.go, vault/logical_system.go, vault/logical_system_test.go, vault/rekey.go, vault/seal/seal.go, vault/seal/seal_testing.go, vault/seal/seal_wrapper.go, vault/seal_autoseal.go, vault/seal_testing_util.go
Tracks seals which are configured but not available at startup time.
=> Unseal HA changes, CE side

command/server.go, go.mod, go.sum, internalshared/configutil/kms.go, vault/logical_system.go, vault/logical_system_test.go, vault/rekey.go, vault/seal/seal.go, vault/seal/seal_testing.go, vault/seal/seal_wrapper.go, vault/seal_autoseal.go, vault/seal_testing_util.go
* Unseal HA changes, CE side
* Transit wrapper update
=> Backport Unseal HA changes, CE side (#23192) to 1.15.x

website/content/api-docs/system/lease-count-quotas.mdx, website/content/api-docs/system/rate-limit-quotas.mdx
Approved Ent PR: https://github.com/hashicorp/vault-enterprise/pull/4764
=> Docs Update

ui/lib/replication/addon/templates/index.hbs, ui/tests/acceptance/enterprise-replication-unsupported-test.js
=> UI: Show unsupported screen if replication unsupported (#23178)

.github/.secret_scanning.yml
Allowlist for website markdown contents.
=> add secret scanning exemptions

command/server.go, website/content/api-docs/system/seal-backend-status.mdx, website/content/docs/concepts/seal.mdx, website/content/docs/configuration/entropy-augmentation.mdx, website/content/docs/configuration/seal/index.mdx, website/content/docs/configuration/seal/seal-ha.mdx, website/content/docs/configuration/seal/transit.mdx, website/data/api-docs-nav-data.json, website/data/docs-nav-data.json
=> First draft of Seal HA documentation

changelog/23260.txt, ui/lib/core/addon/components/download-button.js, ui/lib/core/addon/components/masked-input.hbs, ui/lib/core/addon/components/masked-input.js, ui/tests/index.html, ui/tests/integration/components/masked-input-test.js, ui/tests/pages/components/masked-input.js
Backport for https://github.com/hashicorp/vault/pull/23260
=> Backport 1.14.x: UI: add warning before downloading secret data

website/content/docs/sync/awssm.mdx, website/content/docs/sync/azurekv.mdx, website/content/docs/sync/github.mdx, website/content/docs/sync/vercelproject.mdx
This is for https://github.com/hashicorp/vault/pull/23189
Very minor fixes.  Things that I missed the first time I reviewed.
=> [Secret Sync docs] Minor fixes

CHANGELOG.md
Also includes updates for 1.14.4 and 1.13.8
=> Updating the changelog for 1.15.0

website/content/api-docs/system/internal-counters.mdx, website/content/partials/api/restricted-endpoints.mdx
* Update restricted API list and alert tags
* add cli commands w/o public endpoints
=> [DOCS] Manual backport of 'Fix restricted endpoint info (#23333)' to 1.15

website/content/api-docs/system/internal-counters.mdx, website/content/partials/api/restricted-endpoints.mdx
* Update restricted API list and alert tags
* add cli commands w/o public endpoints
=> [DOCS] Fix restricted endpoint info (#23333)

enos/enos-scenario-replication.hcl, enos/modules/vault_get_cluster_ips/scripts/get-follower-private-ips.sh
Increase default retries for modules used in replication.
=> test: increase wait timers in new modules

ui/app/templates/vault/cluster/access/leases/list.hbs, ui/app/templates/vault/cluster/policies/index.hbs
Fixes regression introduced by https://github.com/hashicorp/vault/pull/23308
=> UI: Move pagination outside of {{each}} conditional

website/content/api-docs/system/replication/index.mdx, website/content/api-docs/system/replication/replication-dr.mdx, website/content/api-docs/system/replication/replication-performance.mdx
Addresses https://hashicorp.atlassian.net/browse/VAULT-17665
=> merkle corruption checker docs

website/content/docs/concepts/events.mdx, website/content/docs/configuration/seal/seal-ha.mdx, website/content/docs/plugins/containerized-plugins.mdx, website/content/docs/release-notes/1.15.0.mdx, website/content/docs/sync/index.mdx, website/content/partials/alerts/beta.mdx, website/data/docs-nav-data.json
Clarify beta features in nav and at the top of key landing page
Update seal ha target doc
=> [DOCS] Release notes updates

website/content/docs/release-notes/1.15.0.mdx
This PR fixes a minor typo in the Vault 1.15 Release Notes.
=> [Docs] Fix a typo

ui/app/templates/components/dashboard/overview.hbs, ui/tests/acceptance/dashboard-test.js
Hides replication card if the user doesn't have permissions to view the card.
=> UI: [VAULT-20626] Hide replication if user doesnt have permissions

website/content/docs/platform/k8s/vso/installation.mdx
Provide detailed steps for upgrading a Helm installed/managed vault-secrets-operator.
=> Document how to upgrade a Helm managed VSO

website/content/partials/api/restricted-endpoints.mdx
Final correction ( 🤞🏽 ) for restricted endpoint alerts
=> [DOCS] Manual fix of restricted endpoint alerts (1.14.x)

website/content/partials/api/restricted-endpoints.mdx
Final correction ( 🤞🏽 ) for restricted endpoint alerts
=> [DOCS] Manual fix of restricted endpoint alerts (main)

website/content/docs/release-notes/1.15.0.mdx, website/content/docs/upgrading/upgrade-to-1.15.x.mdx, website/content/partials/known-issues/aws-auth-panics.mdx
Readding the docs from #23366 until the bugfix is ready to remerge
=> Add known issue notice for AWS auth panic

website/content/docs/release-notes/1.15.0.mdx, website/content/docs/upgrading/upgrade-to-1.15.x.mdx, website/content/partials/known-issues/aws-auth-panics.mdx
=> Backport of commit 'baa4dbe8e285e1e3244ae5ce2be89d67c1b5cea9'

.github/workflows/ci.yml, .github/workflows/test-go.yml
Original PR : https://github.com/hashicorp/vault/pull/22439
=> adding testonly CI test job (#22439)

vault/core_util.go, vault/raft.go
ENT PR https://github.com/hashicorp/vault-enterprise/pull/4780
=> CE changes for https://github.com/hashicorp/vault-enterprise/pull/4780

http/util_stubs_oss.go, tools/stubmaker/main.go, vault/core.go, vault/core_stubs_oss.go
Also fix some stubs defined in #23557 which either had the wrong signature or needed to be public.
=> Teach stubmaker how to work with methods, not just funcs.  

command/command_stubs_oss.go, command/server.go
=> remove unused param from entEnableFourClusterDev

builtin/logical/transit/path_sign_verify.go, sdk/helper/keysutil/policy.go
- This is the OSS parts of the greater enterprise PR to address some issues with signing and encryption within Transit using managed keys.
=> Transit managed key fixes - OSS

ui/mirage/factories/sync-association.js, ui/mirage/factories/sync-destination.js, ui/mirage/handlers/index.js, ui/mirage/handlers/sync.js, ui/mirage/scenarios/index.js, ui/mirage/scenarios/sync.js
This PR handles the initial mirage setup for sync endpoints based on the API documentation.
=> Sync Mirage Setup

changelog/23695.txt
Adding a changelog in a separate PR since it was missed in the original PR: https://github.com/hashicorp/vault/pull/23695
=> UI: Add changelog for decoding connection url

ui/app/styles/components/ui-wizard.scss, ui/app/styles/core/buttons.scss, ui/app/templates/components/wizard/auth-details.hbs, ui/app/templates/components/wizard/features-selection.hbs, ui/app/templates/components/wizard/policies-others.hbs, ui/app/templates/components/wizard/secrets-display.hbs, ui/app/templates/components/wizard/tools-unwrapped.hbs, ui/app/templates/components/wizard/tutorial-complete.hbs, ui/app/templates/components/wizard/tutorial-error.hbs, ui/app/templates/components/wizard/tutorial-idle.hbs, ui/app/templates/components/wizard/tutorial-paused.hbs
Replace buttons in unused wizard templates
=> UI: replace wizard buttons

changelog/23573.txt
Fix formatting of the Seal HA bug changelog removing the * before the component name.
=> Fix changelog entry formatting

changelog/23747.txt, ui/lib/core/addon/components/masked-input.hbs, ui/lib/core/addon/components/masked-input.js, ui/tests/integration/components/masked-input-test.js
=> Backport KV Download Value Stringify Toggle (#23747) to 1.15

website/content/docs/platform/k8s/vso/api-reference.mdx, website/content/docs/platform/k8s/vso/helm.mdx, website/content/docs/platform/k8s/vso/installation.mdx, website/content/docs/platform/k8s/vso/openshift.mdx
https://github.com/hashicorp/vault-secrets-operator/releases/tag/v0.3.4
=> docs/vault-secrets-operator v0.3.4 release update

ui/mirage/handlers/index.js, ui/mirage/handlers/reduced-disclosure.js
Add mirage handler for reduced disclosure endpoints
=> UI: mirage endpoints for reduced disclosure

LICENSE
=> Update LICENSE to 1.15.1

ui/app/components/page/userpass-reset-password.hbs, ui/app/components/page/userpass-reset-password.js, ui/app/routes/vault/cluster/access/reset-password.js, ui/app/templates/vault/cluster/access/reset-password-error.hbs, ui/app/templates/vault/cluster/access/reset-password.hbs, ui/tests/acceptance/reset-password-test.js, ui/tests/integration/components/page/userpass-reset-password-test.js
Whoops -- forgot to add these headers for #23797
=> Add copyright headers to reset-password code

CHANGELOG.md
Update CHANGELOG.md for 1.15.1, 1.14.5, 1.13.9
=> Update CHANGELOG.md for 1.15.1, 1.14.5, 1.13.9

website/content/docs/enterprise/hsm/behavior.mdx, website/content/docs/enterprise/hsm/index.mdx, website/content/docs/enterprise/hsm/security.mdx
Corrects references to a defunct partial that no longer exists
=> [DOCS] Fix partial reference error

website/content/docs/configuration/service-registration/kubernetes.mdx, website/content/docs/platform/k8s/helm/configuration.mdx, website/content/docs/platform/k8s/helm/enterprise.mdx, website/content/docs/platform/k8s/helm/examples/enterprise-dr-with-raft.mdx, website/content/docs/platform/k8s/helm/examples/enterprise-perf-with-raft.mdx, website/content/docs/platform/k8s/helm/examples/enterprise-with-raft.mdx, website/content/docs/platform/k8s/helm/run.mdx, website/content/partials/helm/install.mdx, website/content/partials/helm/repo.mdx
https://github.com/hashicorp/vault-helm/releases/tag/v0.25.0
Just getting the docs up to date to make the upcoming release easier.
=> docs/vault-helm: updates for the last release (v0.25.0)

website/content/docs/configuration/service-registration/kubernetes.mdx, website/content/docs/platform/k8s/helm/configuration.mdx, website/content/docs/platform/k8s/helm/enterprise.mdx, website/content/docs/platform/k8s/helm/examples/enterprise-dr-with-raft.mdx, website/content/docs/platform/k8s/helm/examples/enterprise-perf-with-raft.mdx, website/content/docs/platform/k8s/helm/examples/enterprise-with-raft.mdx, website/content/docs/platform/k8s/helm/run.mdx, website/content/partials/helm/install.mdx, website/content/partials/helm/repo.mdx
docs/vault-helm: updates for the last release (v0.25.0) (#23844)
Manual backport superseding #23858
=> backport of commit 41cc3b31bf374c43dec139944a541a297bc7faa9

command/kv_test.go, website/content/docs/configuration/service-registration/kubernetes.mdx, website/content/docs/platform/k8s/helm/configuration.mdx, website/content/docs/platform/k8s/helm/enterprise.mdx, website/content/docs/platform/k8s/helm/examples/enterprise-dr-with-raft.mdx, website/content/docs/platform/k8s/helm/examples/enterprise-perf-with-raft.mdx, website/content/docs/platform/k8s/helm/examples/enterprise-with-raft.mdx, website/content/docs/platform/k8s/helm/run.mdx, website/content/partials/helm/install.mdx, website/content/partials/helm/repo.mdx
Updates the vault-helm docs for the `0.26.0` release.
=> [docs] update docs for latest 0.26.1 release

ui/app/components/sidebar/nav/cluster.hbs, ui/app/services/permissions.js, ui/tests/integration/components/sidebar/nav/cluster-test.js
- Add Settings section and Custom Messages to sidebar
=> UI: [VAULT-21588] Add Custom Messages to the sidebar

changelog/23942.txt, ui/app/adapters/cluster.js, ui/app/models/cluster.js, ui/app/models/node.js, ui/app/routes/vault/cluster/dashboard.js, ui/app/services/version.js, ui/app/templates/error.hbs, ui/app/templates/vault/cluster/dashboard.hbs, ui/mirage/handlers/chroot-namespace.js, ui/mirage/handlers/index.js, ui/package.json, ui/tests/acceptance/chroot-namespace-test.js, ui/tests/acceptance/dashboard-test.js
=> Backport UI: chroot namespace listener (#23942)

changelog/22038.txt, command/server.go, helper/logging/logger.go, helper/testhelpers/corehelpers/corehelpers.go, vault/activity_log.go, vault/audit.go, vault/auth.go, vault/cluster.go, vault/core.go, vault/core_util.go, vault/expiration.go, vault/identity_store.go, vault/logical_system_test.go, vault/mount.go, vault/policy_store.go, vault/raft.go, vault/rollback.go, vault/seal_autoseal.go, vault/testing.go
This reverts commit 4c8cc87794ed2d989f515cd30c1c1b953d092ef3.
=> Revert "Automatically track subloggers in allLoggers (#22038)"

website/content/docs/platform/github-actions.mdx
Manual cherry-pick of https://github.com/hashicorp/vault/pull/23290 and https://github.com/hashicorp/vault/pull/23993
=> [DOCS] Update the Vault Github action URL

vault/core.go
This bit was missing from https://github.com/hashicorp/vault/pull/23986
=> use new logger variables in init funcs

website/content/docs/release-notes/1.13.0.mdx, website/content/docs/release-notes/1.14.0.mdx, website/content/docs/release-notes/1.15.0.mdx, website/content/docs/upgrading/upgrade-to-1.13.x.mdx, website/content/docs/upgrading/upgrade-to-1.14.x.mdx, website/content/docs/upgrading/upgrade-to-1.15.x.mdx, website/content/partials/known-issues/ephemeral-loggers-memory-leak.mdx
Add known issue around VAULT-21649
=> Add known issue for sublogger memory leak

website/content/docs/release-notes/1.14.0.mdx, website/content/docs/release-notes/1.15.0.mdx
This PR updates the known issues table with logger leak reference
=> Docs: Update known issues table logger leak

website/content/partials/known-issues/ephemeral-loggers-memory-leak.mdx, website/content/partials/known-issues/expiration-metrics-fatal-error.mdx, website/content/partials/known-issues/internal-error-namespace-missing-policy.mdx
Updating known issues to reflect the versions where fixes have been issued.
=> Update latest known issues to reflect fixes arriving in latest release

LICENSE
Update LICENSE file to include new Additional Use Grants per https://www.hashicorp.com/bsl. Please contact team-rel-eng for questions.
=> REPLAT-962 Update LICENSE

website/content/api-docs/system/secrets-sync.mdx
Documentation for modifications from these 2 PRs:
* [Destination list endpoint](https://github.com/hashicorp/vault-enterprise/pull/4921)
* [Association list endpoint](https://github.com/hashicorp/vault-enterprise/pull/4925)
=> Document secrets sync LIST request modifications

LICENSE
On the 1.15 release branch for 1.15.2
=> Updating license file

ui/app/adapters/sync/association.js, ui/app/models/sync/association.js, ui/app/serializers/sync/association.js, ui/mirage/factories/sync-association.js, ui/mirage/handlers/sync.js, ui/tests/unit/adapters/sync/associations-test.js, ui/tests/unit/serializers/sync/associations-test.js, ui/types/vault/models/sync/association.d.ts
Adds model, adapter and serializer for sync associations along with tests.
=> Sync Associations Ember Data Setup

website/content/docs/platform/k8s/vso/api-reference.mdx, website/content/docs/platform/k8s/vso/helm.mdx, website/content/docs/platform/k8s/vso/installation.mdx, website/content/docs/platform/k8s/vso/openshift.mdx
Update the docs for the VSO 0.4.0 release: https://github.com/hashicorp/vault-secrets-operator/milestone/15
=> Update VSO docs for v0.4.0

ui/app/styles/helper-classes/layout.scss, ui/lib/pki/addon/components/page/pki-certificate-details.hbs, ui/lib/pki/addon/components/page/pki-configuration-details.hbs, ui/lib/pki/addon/components/page/pki-configuration-edit.hbs, ui/lib/pki/addon/components/page/pki-configure-create.hbs, ui/lib/pki/addon/components/page/pki-issuer-details.hbs, ui/lib/pki/addon/components/page/pki-issuer-edit.hbs, ui/lib/pki/addon/components/page/pki-issuer-rotate-root.hbs, ui/lib/pki/addon/components/page/pki-overview.hbs, ui/lib/pki/addon/components/pki-generate-csr.hbs, ui/lib/pki/addon/components/pki-generate-root.hbs, ui/lib/pki/addon/components/pki-import-pem-bundle.hbs, ui/lib/pki/addon/components/pki-issuer-cross-sign.hbs, ui/lib/pki/addon/components/pki-key-form.hbs, ui/lib/pki/addon/components/pki-key-import.hbs, ui/lib/pki/addon/components/pki-role-form.hbs, ui/lib/pki/addon/components/pki-role-generate.hbs, ui/lib/pki/addon/components/pki-sign-intermediate-form.hbs, ui/lib/pki/addon/components/pki-tidy-form.hbs
Replaces all buttons in the lib/pki directory.
=> UI: HDS adoption replace <Button> in lib/pki

ui/lib/sync/addon/components/secrets/page/destinations.hbs, ui/lib/sync/addon/components/secrets/page/destinations/destination/secrets.hbs
=> UI: Secrets sync: Use updated <ConfirmAction> component in popup menus

ui/tests/acceptance/auth-list-test.js
Fixes test that failed from bad backport of #24147
=> UI Backport 1.13.x: fix auth list test

ui/tests/acceptance/auth-list-test.js
Fixes test that failed from bad backport of #24147
=> UI Backport 1.14.x: fix auth list test

changelog/24168.txt, ui/app/adapters/capabilities.js, ui/app/services/namespace.js, ui/lib/core/addon/utils/sanitize-path.js, ui/lib/core/app/utils/sanitize-path.js, ui/tests/unit/adapters/capabilities-test.js, ui/tests/unit/utils/sanitize-path-test.js
=> Backport UI: always send capabilities-self request in user's root namespace

changelog/24224.txt, ui/lib/kv/addon/components/kv-data-fields.hbs, ui/lib/kv/addon/components/kv-data-fields.js, ui/lib/kv/addon/components/page/secret/edit.hbs, ui/lib/kv/addon/components/page/secret/edit.js, ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-edge-cases-test.js, ui/tests/integration/components/kv/kv-data-fields-test.js
=> Backport UI: Fix KV v2 json editor (#24224)

vault/audit_broker.go
Doing the right thing for @raskchanky
=> fix import formatting on audit broker

vault/seal/seal_test.go, vault/seal/seal_testing.go
Fixes the bad formatting introduced by https://github.com/hashicorp/vault/pull/24266.
=> Run make fmt.

ui/app/styles/components/selectable-card-container.scss, ui/lib/kv/addon/components/page/list.hbs
=> Fix KV "View secret" or "View list" HDS button styling

ui/tests/acceptance/enterprise-reduced-disclosure-test.js
Whoops -- adds missing dependencies for new enterprise test
=> UI: fix ent tests

http/handler.go, http/logical.go, http/logical_test.go, http/sys_seal.go, sdk/logical/request.go, vault/logical_system.go, vault/logical_system_integ_test.go, vault/logical_system_paths.go
Backport of https://github.com/hashicorp/vault/pull/24355
=> Add_Chroot_Namespace_In_Response

vault/seal/seal.go
=> Fix typo in seal.go

website/content/docs/install.mdx, website/content/docs/upgrading/index.mdx, website/content/partials/versions.mdx
Context: this was suggested as potentially helpful in a slack thread. I drew up the edits accordingly, and they've been approved at a high level. I'm happy to take further editorial comments from other reviewers.
Preview:
=> Clarify Vault versions, some upgrade guidance

ui/tests/acceptance/enterprise-replication-test.js, ui/tests/acceptance/enterprise-transform-test.js
Forgot to update enterprise tests for breadcrumb PR https://github.com/hashicorp/vault/pull/24387! 🙈
=> UI: Update breadcrumb selectors for enterprise tests

vault/seal/seal.go
To minimize the race chances between result send and close.
=> Make sure stopCh is closed first

website/content/docs/configuration/telemetry.mdx, website/content/docs/enterprise/performance-standby.mdx
=> Docs updates about redirection and metrics

command/agentproxyshared/cache/lease_cache_test.go
Problem: sometimes, in CI, this test gets 'too much' time and the renewals for the expired secrets evict them, whereas the test does not expect to be evicted.
I'm not _entirely_ satisfied with this fix. I think, ideally, we'd build a way to make a lease cache without renewal logic for tests or similar so that we could test the expected number exactly. However, I think that'd take a lot more time than it would be worth, and we have other tests in this area too. I don't believe we're losing coverage here.
=> Fix flaky restore test (TestLeaseCacheRestore_expired)

website/content/docs/concepts/client-count/index.mdx
- Attempt to make the various examples for how we generate entity tokens when leveraging ACME clearer.
=> Update ACME entity assignment examples

ui/app/styles/components/calendar-widget.scss, ui/app/templates/components/configure-aws-secret.hbs, ui/app/templates/components/dashboard/client-count-card.hbs, ui/app/templates/components/dashboard/replication-card.hbs, ui/app/templates/components/dashboard/secrets-engines-card.hbs, ui/app/templates/components/identity/entity-nav.hbs, ui/app/templates/vault/cluster/access/identity/index.hbs, ui/app/templates/vault/cluster/access/methods.hbs, ui/app/templates/vault/cluster/access/mfa/index.hbs, ui/app/templates/vault/cluster/secrets/backends.hbs, ui/app/templates/vault/error.hbs, ui/lib/core/addon/components/enable-input.hbs, ui/lib/core/addon/components/enable-input.ts, ui/lib/core/addon/components/form-field.hbs, ui/lib/ldap/addon/components/page/libraries.hbs, ui/lib/ldap/addon/components/page/roles.hbs, ui/lib/sync/addon/components/secrets/destination-header.hbs, ui/lib/sync/addon/components/secrets/page/destinations.hbs, ui/testem.js, ui/tests/integration/components/clients/horizontal-bar-chart-test.js, ui/tests/integration/components/clients/line-chart-test.js, ui/tests/integration/components/clients/vertical-bar-chart-test.js, ui/tests/integration/components/database-role-setting-form-test.js, ui/tests/integration/components/enable-input-test.js, ui/tests/integration/components/filter-input-test.js, ui/tests/integration/components/pgp-file-test.js, ui/tests/integration/components/text-file-test.js, ui/tests/integration/components/tool-tip-test.js
Some updates from upstream-merged sync work, and other cleanup items
=> UI: a11y sidebranch - sync cleanup

vault/audit_broker.go
Some refactoring of AuditBroker extracting methods and general clean-up.
=> Refactor `AuditBroker`

builtin/credential/ldap/backend.go, builtin/credential/ldap/backend_test.go, builtin/credential/ldap/path_config.go, builtin/logical/aws/path_config_root.go, vault/rotation.go
=> add pool and ldap integration to rotation poc

website/content/docs/plugins/containerized-plugins/add-a-containerized-plugin.mdx
🔍 [Deploy preview](https://vault-76yzt4835-hashicorp.vercel.app/vault/docs/plugins/containerized-plugins/add-a-containerized-plugin)
This PR suggests format fixes for https://github.com/hashicorp/vault/pull/24537. 
Some of the suggestions were made to make sure the copy-to-clipboard button copies the correct lines.
=> Minor format fixes for PR 24537

website/content/api-docs/system/secrets-sync.mdx
Small mistake, the param is an array of strings not a string.
=> Fix small doc error

ui/app/serializers/config-ui/message.js, ui/lib/config-ui/addon/components/messages/page/details.hbs, ui/lib/config-ui/addon/components/messages/page/details.js, ui/lib/config-ui/addon/components/messages/page/list.hbs, ui/lib/config-ui/addon/routes/messages/message/details.js, ui/lib/config-ui/addon/templates/messages/message/details.hbs, ui/tests/integration/components/config-ui/messages/page/details-test.js, ui/tests/integration/components/config-ui/messages/page/list-test.js
- fixes create and edit date bug
- adds details view
=> UI: [VAULT-21435] Message details

ui/app/templates/components/backend-configure.hbs
=> UI: Delete empty file thats causing ui linting errors

ui/app/templates/components/backend-configure.hbs
=> UI: Delete empty file thats causing ui linter errors

website/content/api-docs/auth/kubernetes.mdx
add token_reviewer_jwt_set to resp data on config read api doc example
=> add token_reviewer_jwt_set to resp data on config read api doc example 

ui/lib/kv/addon/components/page/secret/details.hbs, ui/lib/kv/package.json, ui/lib/sync/addon/components/secrets/page/destinations/destination/sync.hbs, ui/lib/sync/addon/components/secrets/page/overview.hbs, ui/tests/integration/components/kv/page/kv-page-secret-details-test.js, ui/tests/integration/components/sync/secrets/page/overview-test.js
Small UX changes to clarify copy
=> Secrets Sync UI: Small UX copy improvements

changelog/24686.txt, ui/app/models/pki/issuer.js, ui/tests/acceptance/pki/pki-overview-test.js, ui/tests/helpers/pki/pki-run-commands.js
=> Backport UI: fix PKI issuer capabilities (#24686)

ui/app/lib/attach-capabilities.js, ui/app/models/pki/certificate/base.js, ui/app/routes/vault.js, ui/app/serializers/database/connection.js, ui/lib/pki/addon/decorators/check-issuers.js, ui/lib/pki/addon/routes/certificates/index.js, ui/lib/pki/addon/routes/configuration/index.js, ui/lib/pki/addon/routes/keys/index.js, ui/lib/pki/addon/routes/overview.js, ui/lib/pki/addon/routes/roles/index.js, ui/lib/pki/addon/routes/tidy.js, ui/package.json, ui/tests/acceptance/oidc-provider-test.js, ui/yarn.lock
Rounding up the last couple of changes that can be merged into main preparing for the Ember data upgrade.
=> Prep for ember data: misc

.github/workflows/test-go.yml
Manual backport of https://github.com/hashicorp/vault/pull/24711
=> Manual backport for deleting only files

builtin/credential/ldap/backend.go, builtin/logical/aws/backend.go, builtin/logical/aws/path_config_rotate_root.go
Add aws support to the rotation poc
=> Vault 22857/add rotate aws poc

api/logical.go, builtin/logical/pki/test_helpers.go
- This is to support the EST test cases within Vault Enterprise
=> Add WriteRaw to client api and new PKI test helper

ui/tests/acceptance/reset-password-test.js
Attempt 2 to resolve flakiness on this test
=> UI: make user reset password test less flakey

website/content/docs/secrets/identity/oidc-provider.mdx
Fixes https://github.com/hashicorp/vault/issues/24876
=> Fix docs link typos

helper/testhelpers/teststorage/teststorage.go, vault/testing.go
#24560 changed how we handle addresses in raft when using ephemeral ports, and I overlooked nightly test breakage. The issue is that when ClusterSetup is used, the resulting conf and opts are shared between multiple clusters in some tests, and we were populating per-cluster config (ClusterAddrBridge) into that shared conf.  Now instead that per-cluster config is only used for the specific cluster it's intended for.
=> Fix multi-cluster raft tests that use TCP networking

ui/app/components/clients/attribution.js, ui/app/components/clients/horizontal-bar-chart.js, ui/app/components/clients/line-chart.js, ui/app/components/clients/monthly-usage.js, ui/app/components/clients/page/token.hbs, ui/app/components/clients/running-total.js, ui/app/components/clients/vertical-bar-chart.js, ui/app/styles/core/charts.scss, ui/app/templates/components/clients/attribution.hbs, ui/app/templates/components/clients/horizontal-bar-chart.hbs, ui/app/templates/components/clients/line-chart.hbs, ui/app/templates/components/clients/monthly-usage.hbs, ui/app/templates/components/clients/running-total.hbs, ui/app/templates/components/clients/vertical-bar-chart.hbs, ui/app/utils/chart-helpers.js, ui/lib/core/addon/utils/client-count-utils.js, ui/mirage/handlers/clients.js, ui/tests/integration/components/clients/attribution-test.js, ui/tests/integration/components/clients/monthly-usage-test.js, ui/tests/integration/components/clients/running-total-test.js, ui/tests/unit/utils/chart-helpers-test.js
=> UI: Set up client charts for incoming sync data

website/Dockerfile, website/package-lock.json, website/package.json
Dev Portal was recently updated to use Next V14. The package.json and Dockerfile in the Vault website repo have been updated accordingly.
=> [website] Update node, npm and next versions in website directory

audit/event.go, audit/event_test.go, builtin/audit/file/backend.go, builtin/audit/socket/backend.go, builtin/audit/socket/backend_test.go, internal/observability/event/options.go, internal/observability/event/options_test.go, internal/observability/event/sink_socket_test.go
Tidy up for some unused fields, error message improvement.
=> updates to tidy up audit code

website/content/api-docs/secret/databases/oracle.mdx
Adding missing feature flags to API doc. 
split_statements and disconnect_sessions.
Related PR
https://github.com/hashicorp/vault-plugin-database-oracle/pull/62
=> Update oracle.mdx missing feature flags

ui/app/serializers/config-ui/message.js, ui/app/transforms/object.js, ui/lib/config-ui/addon/components/messages/page/list.hbs, ui/lib/config-ui/addon/components/messages/page/list.js, ui/tests/helpers/config-ui/message-selectors.js, ui/tests/integration/components/config-ui/messages/page/details-test.js, ui/tests/integration/components/config-ui/messages/page/list-test.js
=> UI: fix link bug and add colors

api/go.mod, api/go.sum, api/sys_ui_custom_message.go, api/sys_ui_custom_message_test.go
This PR adds methods to the Sys struct in the api package that facilitate manipulating UI Custom Messages.
=> VAULT-22504: Support Custom Messages in api Package

sdk/logical/system_view.go
A small set of changes from a larger ENT PR to properly support registration of well-known EST labels on PR clusters.
=> CE changes to support ENT EST cross cluster well-known registrations

website/content/partials/storage-entry-size.mdx
=> Fix typo in Consul ref

changelog/25040.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/7645281353
=> Update vault-plugin-secrets-openldap to v0.11.3

changelog/25058.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/7647363221
=> Update vault-plugin-secrets-ad to v0.16.2

helper/timeutil/timeutil.go, helper/timeutil/timeutil_test.go, vault/census.go, vault/core.go
JIRA: https://hashicorp.atlassian.net/browse/VAULT-22881
Approved ent PR: https://github.com/hashicorp/vault-enterprise/pull/5205
=> Manual census snapshot cleanup changes CE

ui/app/components/clients/attribution.js, ui/app/components/clients/horizontal-bar-chart.js, ui/app/templates/components/clients/attribution.hbs, ui/app/templates/components/clients/horizontal-bar-chart.hbs, ui/mirage/handlers/clients.js
=> Secrets Sync UI: Add secrets syncs to csv export

helper/timeutil/timeutil.go, helper/timeutil/timeutil_test.go, vault/activity_log.go, vault/activity_log_test.go, vault/census.go, vault/core.go, vault/logical_system_activity.go, vault/testing.go
Reverting changes in 
https://github.com/hashicorp/vault/pull/25064
https://github.com/hashicorp/vault/pull/25050
https://github.com/hashicorp/vault/pull/24850
=> Revert manual license reporting changes from  1.14.x

.github/workflows/code-checker.yml, vault/core.go
Also introduce an exclusion for an existing false positive.
=> Use a newer version of semgrep that supports exclusions 

vault/logical_system.go
ENT side: https://github.com/hashicorp/vault-enterprise/pull/5229
=> census manual reporting API sys help

builtin/logical/pkiext/pkiext_binary/acme_test.go
Outcome of the collaborative test fixing session on 26 Jan.
The idea was mainly to remove the calls to `t.Log` and `t.Logf`, so that the tests don't print the name of the file, unless it's a test failure. Our CI logs get noisy and searching for `.go` is often the best way to find failure messages in them.
=> Swap calls to t.Log to a corehelpers test logger in ACME tests

command/commands.go, command/operator_utilization.go
Approved ent: https://github.com/hashicorp/vault-enterprise/pull/5239
Changelog in ent PR
=> Census manual reporting: CLI 

changelog/25059.txt
changelog for https://github.com/hashicorp/vault/pull/25059
=> backport 1.13: add changelog for update plugin snowflake to v0.7.4

changelog/25057.txt
changelog for https://github.com/hashicorp/vault/pull/25057
=> backport 1.14: add changelog for update plugin snowflake to 0.9.2

website/content/docs/platform/k8s/vso/api-reference.mdx
syncs the api-docs for VSO with the VSO repository.
=> [docs] update docs from vso repository

sdk/physical/inmem/inmem.go
This PR was [approved in Ent](https://github.com/hashicorp/vault-enterprise/pull/5277) and adds a mechanism to test with artificial latency when writing to `InmemBackend`.
It's not used anywhere in this PR as the test that requires it is current Enterprise only.
=> Add configurable latency when performing Inmem writes.

ui/tests/acceptance/dashboard-test.js, ui/tests/helpers/commands.js
- Update dashboard test to use runCmd and also add assert
=> UI: Clean up dashboard test

changelog/25143.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/7729129022
=> Update vault-plugin-database-snowflake to v0.10.0

.github/workflows/ci.yml, .github/workflows/test-go.yml
Link to ENT PR:
https://github.com/hashicorp/vault-enterprise/pull/5291
=> Notify For Data Race Failures

website/content/partials/telemetry-metrics/vault/identity/entity/alias/count.mdx
Fix small typo in the documentation.
=> Fix typo in count.mdx

changelog/25152.txt, ui/lib/kv/addon/components/kv-data-fields.hbs, ui/lib/kv/addon/components/kv-data-fields.js, ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-edge-cases-test.js
=> Backport 1.15.6: Manual of update KV data on version dropdown change for nested secrets

changelog/25196.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/7759140651
=> Update vault-plugin-auth-cf to v0.16.0

changelog/25207.txt, go.mod, go.sum
Steps:
```
go get github.com/hashicorp/vault-plugin-auth-kubernetes@v0.18.0
go mod tidy
```
=> Update vault-plugin-auth-kubernetes to v0.18.0

ui/lib/sync/addon/components/secrets/page/destinations/select-type.hbs, ui/tests/acceptance/sync/secrets/destination-test.js, ui/tests/acceptance/sync/secrets/destinations-test.js, ui/tests/acceptance/sync/secrets/overview-test.js, ui/tests/helpers/general-selectors.js, ui/tests/helpers/sync/sync-selectors.js
This PR adds more acceptance tests to cover sync workflows, primarily navigational aspects since the majority of the functionality is covered in component tests.
=> Sync Acceptance Tests

vault/seal/seal.go
We improved the seal HA wrapper search by always searching for wrappers by
priority vs blobInfo keyIds.  However, this was an iteration over a map,
which isn't deterministic.  Something like 1 in 10 times it would choose a
wrapper that unit tests didn't expect.  Instead, iterate through wrappers by
priority and do a simple loop to find matching blobInfos, which is always
consistent.
=> Avoid map iteration induced flakiness in seal wrapper key searching

ui/app/adapters/ldap/role.js, ui/tests/acceptance/oidc-provider-test.js, ui/tests/integration/components/page/userpass-reset-password-test.js
Wrapping up the last test stability PR. Changes here come from the Ember data upgrade, but are not dependent on the upgrade and provide more stability to the current tests.
=> Test stability cont.

ui/lib/core/addon/utils/advanced-secret.js, ui/tests/unit/utils/advanced-secret-test.js
Small updates to make the `advanced-secret` util more robust
=> UI: Update advanced-secret tests and logic

website/content/docs/concepts/namespace-api-lock.mdx
Fix typo in API unlock section.
=> Fix typo in namespace API unlock

changelog/25277.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/7821579490
=> Update vault-plugin-secrets-kv to v0.17.0

ui/tests/acceptance/sync/secrets/destination-test.js
Updates enterprise test after this PR was merged https://github.com/hashicorp/vault/pull/25273 
failure: https://github.com/hashicorp/vault-enterprise/actions/runs/7823964491/job/21345762535
=> UI: Updates sync delete test

changelog/25335.txt, ui/app/components/token-expire-warning.js, ui/app/templates/components/token-expire-warning.hbs
Backport of #25335 
* Redirect after logging in from token expiry. Fixes #10963
* Add changelog
=> Backport UI: Redirect after logging in from token expiry (#25335)

.github/scripts/report-ci-status.sh, .github/workflows/build.yml, .github/workflows/ci.yml
* Fix the build notification. It appears that during a rebase the JSON
payload was slightly corrupted.
* Don't create a successful CI step summary if the CI workflow is
cancelled.
* Don't create a successful CI comment if the workflow is cancelled.
=> ci: fix notification, step summary, and comment

changelog/25364.txt, ui/app/routes/vault/cluster/access/method.js
=> Backport UI: Skip OpenAPI call for unmanaged auth methods (#25364)

ui/app/adapters/capabilities.js, ui/app/adapters/control-group.js
Same change as https://github.com/hashicorp/vault/pull/25447 but this will be backported to 1.16.x and 1.15.x
=> UI: Control group flaky enterprise test fix attempt 

website/content/docs/platform/k8s/vso/api-reference.mdx, website/content/docs/platform/k8s/vso/helm.mdx, website/content/docs/platform/k8s/vso/index.mdx, website/content/docs/platform/k8s/vso/installation.mdx, website/content/docs/platform/k8s/vso/openshift.mdx, website/content/docs/platform/k8s/vso/secret-transformation.mdx, website/data/docs-nav-data.json
Doc updates for VSO v0.5.0
- Document the new secret transformation feature
- Update API and Helm reference docs
=> Update docs for VSO v0.5.0

go.mod
See the corresponding enterprise PR for more details, but we need this for enterprise.
=> VAULT-23589 add replace directive to CE

ui/app/services/namespace.js, ui/tests/acceptance/enterprise-namespaces-test.js
an attempt -- I'm unable to reproduce failures locally so this is somewhat a shot in the dark
=> UI: stabilize flaky ns test

ui/app/services/namespace.js, ui/tests/acceptance/enterprise-namespaces-test.js
=> Backport UI: stabilize flaky ns test (#25488)

helper/testhelpers/corehelpers/corehelpers.go
Add an event listener to NoopAudit in order to facilitate making assertions on audited requests.
This is used by a unit test in the Vault Enterprise EST backend.
=> Add event listerner to NoopAudit for audited request assertions.

website/content/docs/enterprise/lease-count-quotas.mdx
Update documentation to correctly indicate the default LCQ value of 300k.
=> Update old Default LCQ value

builtin/credential/cert/backend.go, builtin/credential/cert/path_certs.go, builtin/credential/cert/path_config.go, builtin/credential/cert/path_crls.go, builtin/credential/cert/path_login.go, builtin/credential/cert/path_login_test.go, changelog/25421.txt, go.mod, go.sum, website/content/api-docs/auth/cert.mdx
=> Cache trusted cert values, invalidating when anything changes (#25421)

website/content/docs/enterprise/entropy-augmentation.mdx
They don't.  c.f. https://github.com/hashicorp/vault/blob/af27ab3524da78ba6b21b06b2efd15ab928312f0/vault/dynamic_system_view.go#L449
=> Correct documentation that password generation uses entropy augmentation

website/content/docs/platform/k8s/vso/helm.mdx, website/content/docs/platform/k8s/vso/installation.mdx, website/content/docs/platform/k8s/vso/openshift.mdx
Update docs for the VSO 0.5.1 release.
=> Update docs for VSO v0.5.1

ui/tests/acceptance/enterprise-kmip-test.js
=> UI: Change path and ids from date now to uuid

website/content/docs/agent-and-proxy/autoauth/methods/cert.mdx, website/content/docs/agent-and-proxy/proxy/apiproxy.mdx
Spotted this when looking through the docs. It was a quick fix so I decided to get it while I was there :)
=> Fix a broken link

command/agentproxyshared/cache/static_secret_cache_updater.go, command/agentproxyshared/cache/static_secret_cache_updater_test.go
This is an improvement to the erroring for Static Secret Caching to make it clear that it's enterprise only in the logs. It will error like this for a CE Vault:
```
2024-02-27T10:07:29.587-0500 [INFO]  proxy.sink.file: token written: path=/Users/violet/vault/token
2024-02-27T10:07:29.690-0500 [ERROR] proxy.cache.staticsecretcacheupdater: error occurred during streaming static secret cache update events: err="received 404 when opening web socket to ws://127.0.0.1:8200/v1/sys/events/subscribe/kv%2A?json=true, ensure Vault is Enterprise version 1.16 or above"
2024-02-27T10:07:39.699-0500 [ERROR] proxy.cache.staticsecretcacheupdater: error occurred during streaming static secret cache update events: err="received 404 when opening web socket to …
```
=> VAULT-24386 better erroring for Proxy static secret caching for CE

website/content/docs/ui/custom-messages.mdx
There were some grammar and spelling issues found https://github.com/hashicorp/vault/pull/25638.
🔍 [deploy preview](https://vault-4phwsgdzz-hashicorp.vercel.app/vault/docs/ui/custom-messages)
=> UI: Fix grammar and spelling issues in Custom Messages Docs

builtin/logical/aws/path_config_root.go, builtin/logical/aws/path_config_root_test.go, changelog/25219.txt, sdk/helper/pluginidentityutil/errors.go, vault/identity_store_oidc.go, vault/identity_store_oidc_stubs_oss.go, vault/identity_store_oidc_test.go
This PR adds enterprise stubs for plugin WIF.
=> Add stubs for plugin WIF

website/content/docs/ui/custom-messages.mdx
Addresses feedback from backport https://github.com/hashicorp/vault/pull/25672
=> UI: Addresses custom messages doc feedback from backport

vault/activity_log.go, vault/core.go, vault/logical_system_helpers.go
=> Revert "Backport of VAULT-23468: Bill on number of secrets currently being synced into release/1.15.x"

http/sys_health.go, http/sys_leader.go, http/sys_seal.go, http/sys_seal_test.go, sdk/helper/testcluster/docker/environment.go, sdk/helper/testcluster/types.go, vault/core.go, vault/logical_system.go
Link to ENT PR: https://github.com/hashicorp/vault-enterprise/pull/5515
=> Redact Sensitive Info Only When Token Is Not Present

http/sys_health.go, http/sys_leader.go, http/sys_seal.go, http/sys_seal_test.go, sdk/helper/testcluster/docker/environment.go, sdk/helper/testcluster/types.go, vault/core.go, vault/logical_system.go
Link to original PR. https://github.com/hashicorp/vault/pull/25735
closes https://github.com/hashicorp/vault/pull/25753
=> Manual Backport Redact with Valid token

vault/eventbus/filter.go
Although we used a single goroutine for sending to the watcher's channel, since we sent in a separate goroutine, there is a race condition where the channel could be closed before the send is attempted.
To fix these, we coordinate with another goroutine through another channel.
The first goroutine sits on the condition variable and holds the lock continuously to ensure that it does not miss any updates.
The second goroutine calculates the changes from the first goroutine and sends them to the watcher's channel, and is responsible for closing the watcher's channel.
Although a little more complex, this simplifies the sending path and use of locks, and should ensure that there are no race condition in this piece of code.
=> events: Race condition in filter

website/content/api-docs/secret/pki.mdx, website/content/docs/secrets/pki/est.mdx, website/content/docs/secrets/pki/index.mdx, website/content/partials/pki-est-default-policy.mdx, website/data/docs-nav-data.json
Initial draft of the PKI EST setup and API docs for feedback
=> PKI EST docs

vault/activity_log.go, vault/activity_log_test.go, vault/core_stubs_oss.go
OSS components for the ent PR.
=> VAULT-23705: Enable secret sync billing

website/content/docs/faq/ssct.mdx
Some strange caps issues hopefully now fixed.
=> SSCT: updated docs

ui/lib/core/addon/templates/components/message-error.hbs, ui/lib/sync/addon/components/secrets/page/overview.hbs, ui/lib/sync/addon/components/secrets/page/overview.ts, ui/lib/sync/addon/routes/secrets.ts, ui/lib/sync/addon/routes/secrets/overview.ts, ui/lib/sync/addon/templates/secrets/overview.hbs, ui/tests/acceptance/sync/secrets/destinations-test.js, ui/tests/acceptance/sync/secrets/overview-test.js, ui/tests/helpers/sync/sync-selectors.js, ui/tests/integration/components/sync/secrets/page/overview-test.js
=> Backport 1.16.x: fix opt-in disable button and test coverage

website/content/api-docs/index.mdx
Fixes https://github.com/hashicorp/vault/issues/25969
=> document that LISTs with no results return 404

.github/workflows/build.yml, .github/workflows/ci.yml, .github/workflows/oss.yml, .github/workflows/security-scan.yml, .github/workflows/test-ci-bootstrap.yml, .github/workflows/test-ci-cleanup.yml, .github/workflows/test-enos-scenario-ui.yml, .github/workflows/test-go.yml, .github/workflows/test-run-acc-tests-for-path.yml, .github/workflows/test-run-enos-scenario-matrix.yml
This should resolve various Node JS 16 deprecation warnings.
=> [QT-688] Pin to latest tsccr actions

changelog/25999.txt, ui/app/helpers/mountable-auth-methods.js, ui/app/helpers/supported-auth-backends.js, ui/app/helpers/supported-managed-auth-backends.js, ui/tests/acceptance/auth-list-test.js
Backport of #25999 
Ent tests passed locally
=> Backport UI: Fix kubernetes auth method role management to 1.15.x (#25999)

changelog/25999.txt, ui/app/helpers/mountable-auth-methods.js, ui/app/helpers/supported-auth-backends.js, ui/app/helpers/supported-managed-auth-backends.js
=> Backport UI: Fix kubernetes auth method role management 1.14.x (#25999)

website/content/docs/concepts/seal.mdx, website/content/docs/configuration/seal/seal-ha.mdx
... in that they aren't compatible
=> Be explicit about Shamir seals in Seal HA

website/content/docs/sync/index.mdx, website/data/docs-nav-data.json
=> Removed beta badges

website/content/docs/ui/index.mdx, website/content/partials/ui/policy-requirements.mdx
Add policy notes for UI configuration
=> [DOCS] Add UI policy notes partial and include in overview

vault/identity_store.go
This PR extracts the remaining switch cases from the `(*IdentityStore).Invalidate` function into their own functions to improve readability.
Later on, substantive changes will be made to these new functions to improve the overall performance of the Invalidate operation of the IdentityStore backend.
=> VAULT-25207: Extract remaining switch cases from Invalidate function into separate functions

website/content/docs/upgrading/upgrade-to-1.16.x.mdx, website/content/partials/known-issues/1_16-ldap_auth_login_anonymous_group_search.mdx, website/content/partials/known-issues/1_16-ldap_auth_login_missing_entity_alias.mdx
Add known issue doc for https://github.com/hashicorp/vault/issues/26171
=> docs: add ldap auth login known issue

internalshared/configutil/kms.go
=> Use local wrapping option for withDisallowEnvVars for AWS & Azure

website/content/docs/concepts/seal.mdx
Adding a sentence to improve clarity around DR perf standby seal behavior after auto-unseal.
=> Clarify DR perf-standby seal behavior

website/content/docs/upgrading/upgrade-to-1.16.x.mdx, website/content/partials/known-issues/1_16-jwt_auth_config.mdx
Known issue entry for https://github.com/hashicorp/vault-plugin-auth-jwt/pull/290
=> docs: add known issue for jwt auth config

website/content/partials/known-issues/1_16-ldap_auth_login_anonymous_group_search.mdx, website/content/partials/known-issues/1_16-ldap_auth_login_missing_entity_alias.mdx
Updates known issues to include resolved versions for
- https://github.com/hashicorp/vault/issues/26183
- https://github.com/hashicorp/vault/issues/26171
=> docs: add known issue resolved version

ui/lib/core/addon/components/replication-page.js, ui/tests/acceptance/replication-nav-test.js
This is a backport of 1.16-specific changes in #26350, plus some test changes specific to 1.15. (related to #26325)
=> UI: fix replication nav 1.15.x

website/content/docs/internals/integrated-storage.mdx
Approximately half a dozen fixes to spelling and grammar.
=> Editorial changes to integrated-storage.mdx

website/content/api-docs/system/config-group-policy-application.mdx, website/content/partials/api/restricted-endpoints.mdx
Add sys/config/group-policy-application to admin namespace endpoints.
=> Add to admin namespace

changelog/26396.txt, ui/app/services/auth.js
=> UI: show banner when batch token expired (#26396)

api/sys_raft.go, physical/raft/raft.go, physical/raft/raft_autopilot.go, vault/ha.go, vault/raft.go, vault/request_forwarding_rpc.go
Approved ENT PR is here https://github.com/hashicorp/vault-enterprise/pull/5695
Note that I didn't include the changes to `go.mod` here because it conflicted. I'm assuming that will sort itself out once this merges and I merge CE main into ENT main.
=> CE changes for https://github.com/hashicorp/vault-enterprise/pull/5695

vault/census_stubs_oss.go, vault/logical_system_activity.go
ENT changes: https://github.com/hashicorp/vault-enterprise/pull/5721
=> Census agent not getting reloaded retention window gets updated CE changes

physical/raft/testing.go
https://github.com/hashicorp/vault-enterprise/pull/5726 requires the test function refactoring below in order to work
=> Backport 1.15: raft test function refactor

physical/raft/testing.go
https://github.com/hashicorp/vault-enterprise/pull/5725 requires this test refactoring to work.
=> Backport 1.16: raft test function refactor

physical/raft/testing.go
https://github.com/hashicorp/vault-enterprise/pull/5727 requires these test change refactors in order to run the tests
=> Backport 1.14: raft test function refactor

website/content/docs/internals/telemetry/key-metrics.mdx, website/data/docs-nav-data.json
- Add key metrics document to telemetry internals documentation
=> Docs: migrate key metrics from WAF to telemetry

.github/workflows/ci.yml
Fixes regression introduced by https://github.com/hashicorp/vault/pull/25705
=> Install tools when doing test-ui builds

audit/sink_metric_labeler.go, audit/sink_metric_labeler_test.go
Ent PR: https://github.com/hashicorp/vault-enterprise/pull/5746
=> Audit: Update metric labeler for CE/Ent

builtin/logical/transit/backend.go, builtin/logical/transit/backend_ce.go, builtin/logical/transit/key_utils.go, builtin/logical/transit/path_cmac_ce.go, builtin/logical/transit/path_sign_verify.go, sdk/helper/keysutil/policy.go
Add stubs within CE to support the Transit CMAC enterprise functionality.
=> Add Transit CMAC stubs in CE

helper/testhelpers/testhelpers.go, vault/external_tests/seal_binary/seal_docker_util.go
The new function is used by a test in vault-enterprise.
=> Add new func RetryUntilAtCadenceWithHandler to testhelpers.go.

vault/request_handling.go
=> VAULT-23964 Fix 403 When Forwarding Invalid Token to Active

command/agent/agent_auto_auth_self_heal_test.go
In short, I replaced the wait for file modification time with waiting for file content. I think this will remove the flakiness and hopefully read cleaner. There are a lot of moving parts to the components in these tests, and a lot of things that can trigger updates, so this reduces the chance timing issues affect anything, and it keeps the fidelity of the tests, too.
=> VAULT-25987 Fully deflake self-healing tests

changelog/26519.txt, vault/activity_log.go, vault/activity_log_test.go
https://hashicorp.atlassian.net/browse/VAULT-24579
=> Add metrics for ACME clients in precomputed queries

changelog/22460.txt
The #22460 PR didn't include a changelog because I wanted to get the PR in without needing another collaboration loop with the submitter, so this is the attached changelog.
=> Add changelog for PR #22460

vault/logical_system_activity_write_testonly.go, vault/logical_system_activity_write_testonly_test.go
=> Revert "Client count generation simplification"

website/content/api-docs/auth/cert.mdx
Changed sample request for Configure TLS certificate method from auth/cert/certs/cert1 to auth/cert/config
=> [DOCS]docs/Update cert.mdx

website/content/docs/sync/azurekv.mdx
Replaced stores with destinations in azure secrets sync configuration path
=> [DOCS] update azure secret path

vault/logical_system_activity_write_testonly.go, vault/logical_system_activity_write_testonly_test.go
This time correct!
Tests on enterprise pass this time: https://github.com/hashicorp/vault-enterprise/pull/5798
=> Client count generation simplification, take 2

command/agentproxyshared/cache/static_secret_cache_updater.go, command/agentproxyshared/cache/static_secret_capability_manager.go, command/agentproxyshared/cache/static_secret_capability_manager_test.go, command/proxy.go, command/proxy/config/config.go, website/content/docs/agent-and-proxy/proxy/caching/static-secret-caching.mdx
CE side of changes for this work.
=> VAULT-24736 CE changes for static secret capability behaviour toggle

ui/mirage/handlers/clients.js, ui/tests/acceptance/clients/counts/sync-test.js
=> Backport UI: Fix sync test (#26820)

ui/app/components/clients/attribution.js, ui/app/components/clients/page/counts.ts, ui/lib/core/addon/utils/client-count-utils.ts, ui/mirage/handlers/clients.js, ui/tests/integration/components/clients/page/counts-test.js
=> UI: Add 1.17 changes to upgrade alert

ui/lib/core/package.json
=> Backport 1.14.x - ui deps: specify ember scope explicitly

changelog/26877.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/9003487880
=> Update vault-plugin-secrets-kv to v0.18.0

ui/app/components/clients/attribution.js, ui/tests/integration/components/clients/attribution-test.js
=> UI: Fix CSV header descriptions

ui/lib/kv/addon/components/page/list.hbs
=> UI: remove slash

changelog/26890.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/9009980689
=> Update vault-plugin-auth-jwt to v0.20.3

website/content/docs/browser-support.mdx, website/content/docs/configuration/listener/tcp.mdx
=> Added some notes about TLS and browser Secure Contexts

.github/actions/changed-files/action.yml, .github/actions/checkout/action.yml, .github/workflows/actionlint.yml, .github/workflows/build-artifacts-ce.yml, .github/workflows/build.yml, .github/workflows/ci.yml, .github/workflows/code-checker.yml, .github/workflows/copywrite.yml, .github/workflows/enos-lint.yml, .github/workflows/enos-release-testing-oss.yml, .github/workflows/enos-run-k8s.yml, .github/workflows/oss.yml, .github/workflows/security-scan.yml, .github/workflows/stable-website.yaml, .github/workflows/test-ci-bootstrap.yml, .github/workflows/test-ci-cleanup.yml, .github/workflows/test-enos-scenario-ui.yml, .github/workflows/test-go.yml, .github/workflows/test-run-acc-tests-for-path.yml, .github/workflows/test-run-enos-scenario-matrix.yml
Manual backport of https://github.com/hashicorp/vault/pull/26920 for 1.14
=> Update actions/checkout to 4.1.5 for 1.14

.github/actions/changed-files/action.yml, .github/actions/checkout/action.yml, .github/workflows/actionlint.yml, .github/workflows/build-artifacts-ce.yml, .github/workflows/build.yml, .github/workflows/changelog-checker.yml, .github/workflows/ci.yml, .github/workflows/code-checker.yml, .github/workflows/copywrite.yml, .github/workflows/enos-lint.yml, .github/workflows/enos-release-testing-oss.yml, .github/workflows/enos-run-k8s.yml, .github/workflows/oss.yml, .github/workflows/plugin-update-check.yml, .github/workflows/plugin-update.yml, .github/workflows/security-scan.yml, .github/workflows/stable-website.yaml, .github/workflows/test-ci-bootstrap.yml, .github/workflows/test-ci-cleanup.yml, .github/workflows/test-enos-scenario-ui.yml, .github/workflows/test-go.yml, .github/workflows/test-run-acc-tests-for-path.yml, .github/workflows/test-run-enos-scenario-matrix.yml
Manual backport of https://github.com/hashicorp/vault/pull/26920
=> Update actions/checkout to 4.1.5 for 1.15

website/content/docs/enterprise/cluster-design.mdx, website/data/docs-nav-data.json
Preview link: https://vault-9mygetkrz-hashicorp.vercel.app/vault/docs/enterprise/cluster-design
=> Add reading guide for designing Vault clusters

website/content/docs/configuration/programmatic-best-practices.mdx, website/content/docs/enterprise/cluster-design.mdx, website/data/docs-nav-data.json
This PR manually cherry-pick https://github.com/hashicorp/vault/pull/26515 to v1.15 doc
🔍 [Deploy preview - Best practices for programmatic Vault management](https://vault-dqjwo4mhj-hashicorp.vercel.app/vault/docs/configuration/programmatic-best-practices)
🔍 [Deploy preview - Design your Vault Enterprise cluster](https://vault-dqjwo4mhj-hashicorp.vercel.app/vault/docs/enterprise/cluster-design)
=> [Backport 1.14] Docs/backport pr26515 v1.14

website/content/docs/configuration/programmatic-best-practices.mdx, website/content/docs/enterprise/cluster-design.mdx, website/data/docs-nav-data.json
This PR manually cherry-pick https://github.com/hashicorp/vault/pull/26515 to v1.15 doc
🔍 [Deploy preview - Best practices for programmatic Vault management](https://vault-fsoc1pt6d-hashicorp.vercel.app/vault/docs/configuration/programmatic-best-practices)
🔍 [Deploy preview - Design your Vault Enterprise cluster](https://vault-fsoc1pt6d-hashicorp.vercel.app/vault/docs/enterprise/cluster-design)
=> [Backport 1.15] Docs/waf vault tf (#26515)

website/content/docs/enterprise/cluster-design.mdx, website/content/partials/ui/policy-requirements.mdx, website/data/docs-nav-data.json
Covers the following updates
Original PR | Failed backport | Commit hash | PR title
----------- | --------------- | ----------- | -----------
#26830 | #26958 | 0a54c628ad | fix lack of space character
#26947 | #26964 | b38fdef012 | reading guide for designing Vault clusters
#26975 | #26982 | 01c95e04ec | Fix Vault anti-patterns url
=> [BACKPORT] Manual cherry-pick of failed release/1.15.x backport PRs

website/content/partials/ui/policy-requirements.mdx
Covers the following updates
Original PR | Failed backport | Commit hash | PR title
----------- | --------------- | ----------- | -----------
#26830 | #26956 | 0a54c628ad | fix lack of space character
=> [BACKPORT] Manual cherry-pick of failed release/1.13.x backport PRs

changelog/27019.txt, ui/app/models/secret-engine.js, ui/app/routes/vault/cluster/secrets/backend/list.js, ui/tests/acceptance/secrets/backend/generic/secret-test.js
=> Backport UI: Fix generic v2 secret engine links (#27019)

audit/broker_test.go
See: https://github.com/hashicorp/vault-enterprise/pull/5854
=> increase the time on a context check for audit related tests

enos/README.md, enos/enos-dev-scenario-pr-replication.hcl, enos/enos-dev-scenario-single-cluster.hcl, enos/enos-dev-variables.hcl, enos/enos-globals.hcl, enos/enos-modules.hcl, enos/enos-terraform.hcl, enos/enos-variables.hcl, enos/enos.vars.hcl, enos/k8s/enos-terraform-k8s.hcl, enos/k8s/enos-variables-k8s.hcl, enos/modules/build_artifactory_package/main.tf, enos/modules/build_crt/main.tf, enos/modules/build_local/main.tf, enos/modules/vault_cluster/main.tf, enos/modules/vault_cluster/scripts/set-up-login-shell-profile.sh
Manual backport of https://github.com/hashicorp/vault/pull/27028 and https://github.com/hashicorp/vault/pull/27055
=> Backport VAULT-26888 to 1.16.x

enos/README.md, enos/enos-dev-scenario-pr-replication.hcl, enos/enos-dev-scenario-single-cluster.hcl, enos/enos-dev-variables.hcl, enos/enos-globals.hcl, enos/enos-modules.hcl, enos/enos-terraform.hcl, enos/enos-variables.hcl, enos/enos.vars.hcl, enos/k8s/enos-terraform-k8s.hcl, enos/k8s/enos-variables-k8s.hcl, enos/modules/build_artifactory_package/main.tf, enos/modules/build_crt/main.tf, enos/modules/build_local/main.tf, enos/modules/vault_cluster/main.tf, enos/modules/vault_cluster/scripts/set-up-login-shell-profile.sh
Manual backport of https://github.com/hashicorp/vault/pull/27028 and https://github.com/hashicorp/vault/pull/27055
=> Backport VAULT-26888 to 1.15.x

enos/README.md, enos/enos-dev-scenario-pr-replication.hcl, enos/enos-dev-scenario-single-cluster.hcl, enos/enos-dev-variables.hcl, enos/enos-globals.hcl, enos/enos-modules.hcl, enos/enos-terraform.hcl, enos/enos-variables.hcl, enos/enos.vars.hcl, enos/k8s/enos-terraform-k8s.hcl, enos/k8s/enos-variables-k8s.hcl, enos/modules/build_artifactory_package/main.tf, enos/modules/build_crt/main.tf, enos/modules/build_local/main.tf, enos/modules/vault_cluster/main.tf, enos/modules/vault_cluster/scripts/set-up-login-shell-profile.sh
Manual backport of https://github.com/hashicorp/vault/pull/27028 and https://github.com/hashicorp/vault/pull/27055
=> Backport VAULT-26888 to 1.14.x

website/content/partials/known-issues/perf-standbys-revert-to-standby.mdx
Bad link to /sys/health endpoint.
=> Fix bad link to /sys/health API docs

ui/package.json, ui/yarn.lock
Bumps [ember-plugin-compat](https://www.npmjs.com/package/eslint-plugin-compat)
=> UI: bump ember-plugin-compat to 4.2.0

ui/package.json, ui/yarn.lock
=> Backport UI: bump ember-plugin-compat

.github/actions/changed-files/action.yml, .github/actions/checkout/action.yml, .github/workflows/actionlint.yml, .github/workflows/build-artifacts-ce.yml, .github/workflows/build.yml, .github/workflows/ci.yml, .github/workflows/code-checker.yml, .github/workflows/copywrite.yml, .github/workflows/enos-lint.yml, .github/workflows/enos-release-testing-oss.yml, .github/workflows/enos-run-k8s.yml, .github/workflows/oss.yml, .github/workflows/security-scan.yml, .github/workflows/stable-website.yaml, .github/workflows/test-ci-bootstrap.yml, .github/workflows/test-ci-cleanup.yml, .github/workflows/test-enos-scenario-ui.yml, .github/workflows/test-go.yml, .github/workflows/test-run-acc-tests-for-path.yml, .github/workflows/test-run-enos-scenario-matrix.yml
Manual backport of https://github.com/hashicorp/vault/pull/27104
=> Update actions/checkout for 1.14

ui/tests/acceptance/enterprise-kmip-test.js
=> Backport UI: Fix flaky KMIP test

.github/actions/changed-files/action.yml, .github/actions/checkout/action.yml, .github/workflows/actionlint.yml, .github/workflows/build-artifacts-ce.yml, .github/workflows/build.yml, .github/workflows/changelog-checker.yml, .github/workflows/ci.yml, .github/workflows/code-checker.yml, .github/workflows/copywrite.yml, .github/workflows/enos-lint.yml, .github/workflows/enos-release-testing-oss.yml, .github/workflows/enos-run-k8s.yml, .github/workflows/oss.yml, .github/workflows/plugin-update-check.yml, .github/workflows/plugin-update.yml, .github/workflows/security-scan.yml, .github/workflows/stable-website.yaml, .github/workflows/test-ci-bootstrap.yml, .github/workflows/test-ci-cleanup.yml, .github/workflows/test-enos-scenario-ui.yml, .github/workflows/test-go.yml, .github/workflows/test-run-acc-tests-for-path.yml, .github/workflows/test-run-enos-scenario-matrix.yml
Manual backport of https://github.com/hashicorp/vault/pull/27104
=> Update actions/checkout for 1.15

changelog/27117.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/9132354296
=> Update vault-plugin-database-redis to v0.3.0

changelog/27133.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/9162648357
=> Update vault-plugin-auth-alicloud to v0.18.0

changelog/27132.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/9162632047
=> Update vault-plugin-database-snowflake to v0.11.0

changelog/27137.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/9163215024
=> Update vault-plugin-secrets-openldap to v0.13.0

changelog/27146.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/9165120281
=> Update vault-plugin-auth-azure to v0.18.0

changelog/27147.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/9165308213
=> Update vault-plugin-secrets-terraform to v0.8.0

changelog/27159.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/9177826035
=> Update vault-plugin-secrets-kv to v0.19.0

changelog/27161.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/9179509727
=> Update vault-plugin-auth-cf to v0.17.0

vault/activity_log.go, vault/logical_system_activity.go
Approved ENT PR: https://github.com/hashicorp/vault-enterprise/pull/5869/files
=> Fix read only error to storage error while updating retention months for upgrades CE changes

changelog/27186.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/9198975462
=> Update vault-plugin-auth-kubernetes to v0.19.0

ui/app/models/auth-config/kubernetes.js, ui/tests/helpers/openapi/expected-auth-attrs.js
=> UI backport 1.17.x PR 27196 failing test

http/handler.go
As per request, adding additional trace logging so that operators can identify more easily when raw forwarding isn't working
=> Add additional trace logging in raw forwarding

website/content/docs/sync/index.mdx
Add HVS callout per [Slack request](https://hashicorp.slack.com/archives/C8DK5PR0B/p1717084527629439)
=> Add note about HVS secret sync

Dockerfile
Use a supported version of the image
=> docker: update ubi-minimal image to 8.10

changelog/27178.txt, ui/lib/core/addon/components/filter-input-explicit.hbs, ui/lib/core/app/components/filter-input-explicit.js, ui/lib/kubernetes/addon/components/page/roles.hbs, ui/lib/kubernetes/addon/components/page/roles.js, ui/lib/kubernetes/addon/components/tab-page-header.hbs, ui/tests/acceptance/secrets/backend/kubernetes/roles-test.js, ui/tests/helpers/general-selectors.js, ui/tests/integration/components/filter-input-explicit-test.js, ui/tests/integration/components/kubernetes/page/roles-test.js, ui/tests/integration/components/kubernetes/tab-page-header-test.js
=> Backport 1.16.x: UI fix k8 role filter

ui/tests/acceptance/open-api-path-help-test.js, ui/tests/helpers/openapi/expected-secret-attrs.js
Fixes OpenAPI check tests, and improves the output of the test results so they are easier to parse
=> UI: PKI OpenAPI attributes update

.github/docs/pull_request_template.md, .github/pull_request_template.md
This is my first try at making a PR template. Please make suggestions if you feel anything else should be added.
=> add PR template

website/content/docs/release-notes/1.17.0.mdx, website/content/docs/upgrading/upgrade-to-1.17.x.mdx, website/content/partials/known-issues/ocsp-redirect.mdx, website/data/docs-nav-data.json
Release notes for Vault 1.17 plus explicit anchors for easier linking
=> [DOCS] Vault 1.17 release notes

builtin/logical/pki/issuing/issuers.go
Add GetFullCaChain method to PKI issuer which is leveraged from a function in vault-enterprise.
applied. Brand new features have a differently
formatted changelog than other changelogs, so pay attention to that. If this
PR is the CE portion of an ENT PR, put the changelog here, _not_ in your ENT
PR. Feel free to refer to the [instructions](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md#changelog-entries) on changelog formatting if necessary. …
=> Add GetFullCaChain method to PKI issuer

website/content/docs/concepts/seal.mdx, website/content/docs/configuration/seal/seal-ha.mdx
=> Remove the Beta flag from Seal HA (#27437)

ui/app/controllers/application.js, ui/app/controllers/application.ts, ui/app/routes/application.js, ui/tests/acceptance/enterprise-replication-test.js
Glimmerizes application route and controller. As a bonus, it also converts the controller to typescript!
=> UI: Glimmerize application route

ui/app/routes/application.js, ui/ember-cli-build.js, ui/package.json, ui/yarn.lock
This PR installs and instantiates ember-simple-auth, without yet using it.
=> [LOGIN SIDEBRANCH] Install & setup ember-simple-auth

website/content/docs/commands/transform/import.mdx, website/content/docs/commands/transform/index.mdx, website/content/docs/commands/transit/index.mdx, website/data/docs-nav-data.json
This was missing for Transform but present for Transit
=> Update documentation to add the Transform import CLI command

website/data/docs-nav-data.json
Remove the 'BETA' flag from the nav title
🔍 [Deploy preview](https://vault-4v3sv6w29-hashicorp.vercel.app/vault/docs/configuration/seal/seal-ha)
files.
=> Remove 'BETA' on Seal HA

changelog/27498.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/9506267411
=> Update vault-plugin-auth-jwt to v0.21.0

command/server.go
Lowercase first letter or error message to match standard.
=> lowercase first letter of error message

ui/lib/replication/addon/components/page/mode-index.hbs, ui/lib/replication/addon/components/replication-summary.js, ui/lib/replication/addon/templates/mode/index.hbs, ui/tests/acceptance/enterprise-replication-modes-test.js, ui/tests/integration/components/page/mode-index-test.js
This PR refactors the mode/index template into a template-only component for simpler testing. I ran the replication tests locally multiple times and this seems to stabilize the flakiness 🎉
=> UI: Refactor replication tests

website/content/docs/release-notes/1.15.0.mdx, website/content/docs/release-notes/1.16.1.mdx, website/content/docs/release-notes/1.17.0.mdx, website/content/docs/upgrading/upgrade-to-1.15.x.mdx, website/content/partials/known-issues/1_15-auto-upgrade.mdx
Manual backport of changes in #27454 to the 1.17.x release branch
=> [BACKPORT] Manual cherry-pick of failed release/1.17.x backport (DOCS: SPE-827)

website/content/docs/interoperability-matrix.mdx
Manual backport of changes in #27195 to the 1.17.x release branch
=> [BACKPORT] Manual cherry-pick of #27195 to 1.17.x

website/content/docs/release-notes/1.16.1.mdx, website/content/docs/upgrading/upgrade-to-1.16.x.mdx, website/content/partials/known-issues/1_16_secrets-sync-chroot-activation.mdx
Backport of https://github.com/hashicorp/vault/pull/27558 for 1.16.x
=> Add chroot known-issue and sync activation-flag release note (#27558)

website/content/docs/concepts/tokens.mdx
Fixes an incorrect style issue from https://github.com/hashicorp/vault/pull/27562
=> Add product name to relative link in token docs

CHANGELOG.md
Updated changelog for 1.17.1, 1.16.5, and 1.15.11 releases
=> Updated changelog for 1.17.1, 1.16.5, and 1.15.11 releases

website/content/docs/enterprise/index.mdx
Found inconsistent capitalization of Vault Enterprise, this is my suggested edit.
files.
=> Update index.mdx with proper capitalization

plugins/database/mssql/mssql.go, plugins/database/mssql/mssql_test.go
Attempting to fix flaky tests.
=> db/mssql: increase context timeout in test

website/content/docs/enterprise/replication/index.mdx
Updates links to performance replication tutorial (path filter merged with general perf rep tutorial)
files.
=> Update link to perf rep tutorial

website/content/docs/release-notes/1.16.1.mdx
=> Fix space in release notes

website/content/docs/internals/telemetry/key-metrics.mdx
=> Remove link

ui/tests/acceptance/auth-test.js
This PR adds additional coverage for the auth form, checking that the payload and URL are as expected when all the inputs are filled in.
=> UI: Add more auth test coverage

CHANGELOG.md
=> Update CHANGELOG.md for 1.17.2 1.16.6 and 1.15.12

changelog/27569.txt, ui/lib/core/addon/modifiers/code-mirror.js, ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-edge-cases-test.js, ui/tests/helpers/general-selectors.ts, ui/tests/integration/components/json-editor-test.js
Manual Backport for #27569
Closes VAULT-28328
=> Backport of UI: fix KVv2 cursor jumps on enter into release/1.17.x

ui/mirage/handlers/clients.js
This PR updates the Mirage handler for client count activity so that it reuses previously-generated data if it exists for a start/end time.
=> UI: Reuse CC Mirage data if dates are same

builtin/logical/database/backend_test.go, builtin/logical/database/path_roles_test.go, builtin/logical/database/rollback_test.go, builtin/logical/database/rotation_test.go, helper/testhelpers/postgresql/postgresqlhelper.go, physical/postgresql/postgresql_test.go, plugins/database/postgresql/postgresql_test.go, vault/external_tests/plugin/external_plugin_test.go
preparing for some upcoming tests...
=> db: refactor postgres test helpers

audit/hashstructure_test.go, http/logical_test.go, vault/external_tests/kv/kv_patch_test.go, vault/external_tests/plugin/external_plugin_test.go
This PR fixes minor issues in some tests that mean certain things were not being tested, it also make some slight changes to style.
files.
=> Audit: Test fixes and improvements

builtin/logical/pki/issuing/keys.go
This is a new supporting method to get a crypto.Signer object from a PKI keyEntry. This is only used on the enterprise side at this time.
files.
=> Add new GetSignerFromKeyEntry method for ent usage

website/content/docs/upgrading/upgrade-to-1.16.x.mdx
=> docs: fix upgrade 1.16.x

enos/enos-scenario-replication.hcl
Sometimes the replication scenario will race with other steps and attempt to check the `v1/sys/version-history` API before the cluster is ready. Eventually when it gets retried some of the original nodes are down so it will fail. This makes the verification happen later, only after we've ensured the cluster is unsealed and have gotten leader and cluster IP addresses. We also make dependent steps require the version verification so that if it does fail for some reason it will retry before doing the rest of the scenario.
applying …
=> VAULT-29739: Wait for cluster unseal before checking version history

website/content/docs/enterprise/replication/index.mdx
🎟️ [Jira ticket](https://hashicorp.atlassian.net/browse/VAULT-10218)
files.
=> [Docs] Minor edits - paths filter

vault/activity_log_util_common.go
=> Fix linting issue

ui/app/components/secret-engine/configure-aws.hbs, ui/tests/acceptance/secrets/backend/aws/aws-configuration-test.js, ui/tests/acceptance/secrets/backend/aws/aws-test.js, ui/tests/helpers/secret-engine/secret-engine-helpers.js, ui/tests/helpers/secret-engine/secret-engine-selectors.ts, ui/tests/integration/components/secret-engine/configure-aws-test.js
This pr adds and cleans up test coverage for the AWS secret engine configuration flow. This work will clarify what is going to change in the AWS WIF work, while also trying to prevent unknown regressions.
No user facing changes.
=> AWS test prep for WIF work

website/content/docs/configuration/index.mdx
🎫 [Slack request](https://hashicorp.slack.com/archives/C012RTGJR1V/p1723833645046859)
- Add requested valid, routable IP callout.
- Fix old note styles
files.
=> Add valid IP callout

ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-navigation-test.js
test cleanup to make incoming changes easier to update
=> UI: kv v2 test updates

ui/tests/acceptance/clients/counts/overview-test.js
This PR fortifies the overview acceptance test against Mirage data which is generated.
=> UI: update cc overview test

ui/tests/acceptance/enterprise-replication-test.js
Removes an assertion that isn't really even checking anything, which is causing lots of strife due to flakiness in the enterprise repo
=> UI: remove incredibly flaky title assertion

vault/activity_log.go, vault/external_tests/activity_testonly/activity_testonly_test.go
This PR fixes an issue where non-entity clients had empty mount_type and mount_path values. In fixing it, I also made a small change to provide empty map and array values instead of nulls for the policies, entity_metadata, entity_alias_metadata, entity_alias_custom_metadata, and entity_group_ids.
RFC: [VLT-324: Enhance Activity Export API with Identity Metadata](https://docs.google.com/document/d/1L42mm7rSwJSwMN4h7TnJCwt2GJ_DjKnlJIW8LxJzRgU/edit)
ENT PR: https://github.com/hashicorp/vault-enterprise/pull/6543
applying the patch …
=> handle mount fields for non-entity clients; prevent null values

changelog/28204.txt, ui/app/components/auth-jwt.js, ui/app/services/auth.js, ui/tests/acceptance/auth-test.js
=> Backport UI: remove renew self call after login

CHANGELOG.md
=> Update CHANGELOG.md for 1.17.4 1.16.8 and 1.15.14

ui/lib/kv/addon/components/page/secret/metadata/details.js, ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-delete-test.js, ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-navigation-test.js
=> fix test failures

builtin/logical/pki/revocation/revoke.go, plugins/database/postgresql/postgresql_test.go
Adds Ent check on OSS tests so that they are skipped against Enterprise versions.
=> Add Enterprise check on new Postgres tests

ui/app/services/capabilities.ts, ui/lib/kv/addon/components/page/secret/details.hbs, ui/lib/kv/addon/components/page/secret/details.js, ui/lib/kv/addon/routes/secret.js, ui/lib/kv/addon/utils/kv-breadcrumbs.js, ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-create-test.js, ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-delete-test.js, ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-edge-cases-test.js, ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-navigation-test.js, ui/tests/helpers/kv/kv-selectors.js, ui/tests/unit/services/capabilities-test.js, ui/tests/unit/utils/kv-breadcrumbs-test.js
=> small cleanup items!

website/content/api-docs/system/internal-counters.mdx, website/content/partials/api/restricted-endpoints.mdx
Add documentation updates for the activity export API.
RFC: [VLT-324: Enhance Activity Export API with Identity Metadata](https://docs.google.com/document/d/1L42mm7rSwJSwMN4h7TnJCwt2GJ_DjKnlJIW8LxJzRgU/edit)
Jira: [VAULT-28038](https://hashicorp.atlassian.net/browse/VAULT-28038)
files.
description. Also, make sure the changelog is …
=> Activity Export API doc updates

website/content/docs/upgrading/upgrade-to-1.16.x.mdx, website/content/docs/upgrading/upgrade-to-1.17.x.mdx, website/content/partials/known-issues/1_17_audit-log-hmac.mdx
=> Adding known issue writeup for audit log bug

changelog/28264.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/10704215351
=> Update vault-plugin-auth-kerberos to v0.13.0

changelog/28266.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/10705348804
=> Update vault-plugin-auth-cf to v0.19.0

changelog/28271.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/10706638298
=> Update vault-plugin-secrets-alicloud to v0.18.0

changelog/28294.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/10723974335
=> Update vault-plugin-auth-azure to v0.19.0

go.mod, go.sum
Expect a correpsonding ENT PR later.
=> Update dependencies used by the crypto team

website/content/docs/enterprise/lts.mdx
=> Fix repeating word in docs

website/content/api-docs/secret/databases/postgresql.mdx, website/content/docs/secrets/databases/postgresql.mdx
Document the fields added in https://github.com/hashicorp/vault/pull/28024
Closes https://github.com/hashicorp/vault/issues/13934
=> docs: add postgres TLS docs

changelog/28324.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/10778143396
=> Update vault-plugin-secrets-gcp to v0.20.0

changelog/28334.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/10796412320
=> Update vault-plugin-secrets-kv to v0.20.0

changelog/28348.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/10804667684
=> Update vault-plugin-secrets-mongodbatlas to v0.13.0

enos/enos-scenario-dr-replication.hcl
Ensure that both clusters have completed their seal rewrap before enabling DR on the secondary. We don't want the secondary to come back up in an in-between state.
files.
=> VAULT-30819: DR replication: wait for seal rewrap before enabling DR

website/content/docs/install/index.mdx
=> Fix markdown typo on install page

changelog/28478.txt, go.mod, go.sum
=> Update vault-plugin-secrets-openldap to v0.13.1

changelog/28479.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/11001776700
=> Update vault-plugin-secrets-openldap to v0.14.1

vault/identity_store_entities.go
=> Clone entity memdb

website/content/docs/release-notes/1.18.0.mdx, website/data/docs-nav-data.json
Preview: https://vault-git-docs-118-release-notes-hashicorp.vercel.app/vault/docs/release-notes/1.18.0
=> Add release notes for 1.18

CHANGELOG.md
Fixing an entry in the changelog
=> Fixing entry in the changelog

CHANGELOG.md
=> Update changelog with recent advisories

ui/README.md
Updating Mirage readme to clarify a few points of confusion.
=> Update mirage readme instructions

.release/versions.hcl
Updating the active version to 1.18.x
=> Updating the active version to 1.18.x

changelog/28699.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/11331233299
=> Update vault-plugin-secrets-azure to v0.20.1

website/content/docs/secrets/mongodbatlas.mdx
Backporting to 1.18.x so that the changes go live
=> docs: fix links and format for mongodbatlas secrets

changelog/28712.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/11349954315
=> Update vault-plugin-auth-azure to v0.19.1

website/content/api-docs/secret/pki/index.mdx
Add some sublinks to the PKI docs page so enrollment protocols can be found easier.
=> Add enrollment protocol sublinks.

changelog/28780.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/11524305695
=> Update vault-plugin-secrets-openldap to v0.14.3

website/content/docs/release-notes/1.18.0.mdx
Add missing entry to release notes
=> Add note about new KV functionality in GUI

changelog/28848.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/11711101104
=> Update vault-plugin-auth-azure to v0.19.2

website/content/docs/platform/aws/index.mdx
This PR fixes a reported issue --> 🎫 [SPE-1068](https://hashicorp.atlassian.net/browse/SPE-1068)
🔍 [Deploy preview](https://vault-git-docs-fix-aws-marketplace-link-hashicorp.vercel.app/vault/docs/platform/aws)
AWS Marketplace link is broken.
files. …
=> [Docs] Update the AWS Marketplace link

website/content/docs/concepts/username-templating.mdx, website/content/docs/secrets/databases/mongodb.mdx
Remove deprecated tutorial links
files.
=> Remove deprecated tutorial links

website/content/partials/kubernetes-supported-versions.mdx
update supported k8s version for VSO
=> update supported k8s versions for VSO

website/content/docs/concepts/events.mdx
Update eventing docs to include notes about different issues its currently facing as described in this [ticket](https://hashicorp.atlassian.net/browse/VAULT-32448).
=> update docs for eventing

website/content/docs/platform/k8s/vso/helm.mdx, website/content/docs/platform/k8s/vso/installation.mdx, website/content/docs/platform/k8s/vso/openshift.mdx
=> Update VSO docs for v0.9.1

changelog/28121.txt
Update the changelog for #28121 with a little more information
=> update changelog for okta dependency update

changelog/28989.txt, changelog/29131.txt
Updates changelogs to be more descriptive and to highlight relevant customer impact.
=> update changelogs for static role role rotation updates

vault/activity_log.go, vault/activity_log_util_common.go
=> Revert "Run Migrations If Migration Worker has not been run #7162"

vault/logical_system_activity.go
=> Revert "Disallow querying of activity APIs during upgrade"

vault/activity_log.go, vault/activity_log_test.go, vault/activity_log_testing_util.go, vault/activity_log_util.go, vault/activity_log_util_common.go, vault/activity_log_util_common_test.go
=> Revert "Send Global Data From Secondary to Primary During Upgrade"

builtin/logical/pki/acme_billing_test.go, command/command_testonly/operator_usage_testonly_test.go, sdk/helper/clientcountutil/clientcountutil.go, sdk/helper/clientcountutil/clientcountutil_test.go, vault/activity_log.go, vault/activity_log_test.go, vault/activity_log_testing_util.go, vault/activity_log_util_common.go, vault/activity_log_util_common_test.go, vault/external_tests/activity_testonly/acme_regeneration_test.go, vault/external_tests/activity_testonly/activity_testonly_oss_test.go, vault/external_tests/activity_testonly/activity_testonly_test.go, vault/logical_system_activity_write_testonly.go, vault/logical_system_activity_write_testonly_test.go
=> Revert "Remove all references to current fragments, standbyfragments and partialMonthTracker"

command/command_testonly/operator_usage_testonly_test.go, sdk/helper/clientcountutil/clientcountutil.go, sdk/helper/clientcountutil/clientcountutil_test.go, vault/activity_log.go, vault/activity_log_test.go, vault/activity_log_testing_util.go, vault/activity_log_util_common.go, vault/activity_log_util_common_test.go, vault/external_tests/activity_testonly/acme_regeneration_test.go, vault/external_tests/activity_testonly/activity_testonly_oss_test.go, vault/external_tests/activity_testonly/activity_testonly_test.go, vault/logical_system_activity_write_testonly.go
=> Revert "Storing local clients to local storage paths ce changes"

command/command_testonly/operator_usage_testonly_test.go, sdk/helper/clientcountutil/clientcountutil.go, sdk/helper/clientcountutil/clientcountutil_test.go, vault/activity_log.go, vault/activity_log_test.go, vault/activity_log_testing_util.go, vault/activity_log_util_common.go, vault/activity_log_util_common_test.go, vault/external_tests/activity_testonly/acme_regeneration_test.go, vault/external_tests/activity_testonly/activity_testonly_oss_test.go, vault/external_tests/activity_testonly/activity_testonly_test.go, vault/logical_system_activity_write_testonly.go, vault/logical_system_activity_write_testonly_test.go
=> Revert "Store global clients at separate storage paths"

vault/activity_log.go, vault/activity_log_test.go, vault/activity_log_testing_util.go
=> Revert "adding local clients to local fragments  ce changes"

vault/activity_log.go, vault/activity_log_test.go, vault/activity_log_testing_util.go
=> Revert "Send global client data from secondaries to primary to keep in memory."

website/content/api-docs/secret/transit.mdx, website/content/docs/secrets/transit/index.mdx
=> Add docs for ML-DSA and hybrid keys

website/content/docs/platform/k8s/vso/api-reference.mdx, website/content/docs/platform/k8s/vso/helm.mdx, website/content/docs/platform/k8s/vso/installation.mdx, website/content/docs/platform/k8s/vso/openshift.mdx, website/content/docs/platform/k8s/vso/secret-transformation.mdx, website/content/docs/platform/k8s/vso/sources/hvs.mdx, website/content/docs/platform/k8s/vso/sources/vault/auth/index.mdx, website/content/docs/platform/k8s/vso/sources/vault/index.mdx, website/content/docs/platform/k8s/vso/sources/vault/instant-updates.mdx, website/content/partials/vso/common-links.mdx, website/data/docs-nav-data.json
=> docs/vso: instant updates (#27668)

website/content/docs/concepts/events.mdx
manually backport docs for eventing to 1.16.x
=> update docs for eventing (#28950)

changelog/29430.txt, ui/app/components/dashboard/secrets-engines-card.hbs, ui/app/styles/components/linked-block.scss, ui/app/styles/components/search-select.scss, ui/app/styles/helper-classes/flexbox-and-grid.scss, ui/app/templates/vault/cluster/access/methods.hbs, ui/app/templates/vault/cluster/secrets/backends.hbs, ui/lib/core/addon/components/search-select.hbs, ui/tests/acceptance/access/methods-test.js, ui/tests/acceptance/secrets/backend/engines-test.js, ui/tests/integration/components/dashboard/secrets-engines-card-test.js, ui/tests/integration/components/search-select-test.js
=> Backport 1.18.x - UI: Fix text overflow for long Secret and Auth names (#29430)

changelog/29528.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/13205667197
=> Update vault-plugin-auth-cf to v0.20.0

changelog/29584.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/13293486128
=> Update vault-plugin-database-mongodbatlas to v0.14.0

builtin/credential/aws/path_config_client.go, builtin/logical/aws/path_config_root.go, builtin/logical/database/backend.go, builtin/logical/database/backend_test.go, builtin/logical/database/path_config_connection.go, builtin/logical/database/path_rotate_credentials.go, changelog/29497.txt, changelog/29557.txt, sdk/helper/automatedrotationutil/fields.go, sdk/helper/automatedrotationutil/fields_test.go, sdk/rotation/rotation_job.go
backports commit 9e38a88883597dd69c5d31f50b0fc3d9237200f9 from PR #29557 into the release branch
=> Backport Automated Root Rotation support for DB secrets to 1.19.x

changelog/29614.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/13314466954
=> Update vault-plugin-secrets-kv to v0.21.0

changelog/29619.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/13315513179
=> Update vault-plugin-auth-kubernetes to v0.21.0

changelog/29612.txt, changelog/29614.txt, go.mod, go.sum
manual backport for vault-plugin-secrets-gcpkms and vault-plugin-secrets-kv secrets enginers
=> backport secrets engine plugin updates for gcpkms and vault-plugin-secrets-kv 

changelog/29648.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/13337015252
=> Update vault-plugin-secrets-ad to v0.20.1

CHANGELOG.md
=> changelog update for 1.19.0-rc1

changelog/29728.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/13554569390
=> Update vault-plugin-auth-azure to v0.20.1

changelog/29729.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/13554596945
=> Update vault-plugin-secrets-azure to v0.21.1

website/content/api-docs/auth/aws.mdx, website/content/api-docs/secret/aws.mdx, website/content/api-docs/secret/databases/index.mdx, website/content/docs/auth/aws.mdx, website/content/docs/secrets/aws.mdx, website/content/docs/secrets/databases/index.mdx, website/content/partials/rotationfields.mdx
adds documentation for new feature. based on #29608
=> Add docs for scheduled root rotation feature for the AWS and DB engines

ui/app/components/alphabet-edit.hbs, ui/app/components/alphabet-edit.js, ui/app/components/transform-template-edit.hbs, ui/app/components/transform-template-edit.js, ui/app/models/transform/alphabet.js, ui/app/models/transform/template.js
Manual backport for PR https://github.com/hashicorp/vault/pull/29803
=> Backport 1.19.x 🥐Transform-edit-base: remove use in transform-template-edit and alphabet-edit (#29803)

website/content/docs/release-notes/1.19.0.mdx, website/content/docs/upgrading/upgrade-to-1.19.x.mdx, website/content/partials/known-issues/duplicate-hsm-key.mdx, website/data/docs-nav-data.json
Release notes for 1.19 release
=> 1.19 Release notes

CHANGELOG.md
=> Add missing CL for GH-29792

website/content/docs/release-notes/1.19.0.mdx
=> [DOCS] Add missing links

website/content/api-docs/system/mounts.mdx, website/content/docs/commands/secrets/enable.mdx, website/content/docs/concepts/seal.mdx
=> Fix reported typos

ui/app/components/sidebar/nav/cluster.hbs, ui/app/components/sidebar/nav/cluster.js, ui/app/router.js, ui/app/templates/vault/cluster/vault-usage.hbs
=> WIP: Route for vault usage dashboard

ui/app/components/tools/rewrap.ts
This PR converts the `tools/rewrap` component to `ts` and updates the `rewrap` request to use the api service.
files.
=> [UI] Ember Data Migration - Tools Rewrap Component

changelog/30037.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/14090208081
=> Update vault-plugin-secrets-azure to v0.21.2

changelog/30071.txt, vault/activity/query.go, vault/activity_log.go, vault/activity_log_util_common.go
=> Revert "Backport of Add mount_type to sys/counters/activity response into release/1.19.x"

website/content/docs/secrets/kv/index.mdx, website/content/partials/tips/try-hvs.mdx
🔍 [Deploy preview](https://vault-git-docs-add-hvs-reference-hashicorp.vercel.app/vault/docs/secrets/kv)
Adding a callout to promote HCP Vault Secrets as an alternative solution for managing static secrets.
files.
=> [Docs] Promote HVS as an alternative solution

website/data/docs-nav-data.json
=> [DOCS] Manual backport:  Fix true setting in nav into release/1.19.x

builtin/logical/ssh/backend.go, builtin/logical/ssh/managed_key/common.go, builtin/logical/ssh/managed_key/managed_key_util_ce.go, builtin/logical/ssh/path_config_ca.go
=> Add ce changes for ssh managed keys

website/content/docs/release-notes/1.16.1.mdx, website/content/docs/release-notes/1.17.0.mdx, website/content/docs/release-notes/1.18.0.mdx, website/content/docs/release-notes/1.19.0.mdx, website/content/docs/upgrading/upgrade-to-1.16.x.mdx, website/content/docs/upgrading/upgrade-to-1.17.x.mdx, website/content/docs/upgrading/upgrade-to-1.18.x.mdx, website/content/docs/upgrading/upgrade-to-1.19.x.mdx, website/content/partials/known-issues/log_file_flush_issue.mdx
=> add known issue for log file  missing logs #35101

website/content/docs/release-notes/1.16.1.mdx, website/content/docs/release-notes/1.17.0.mdx, website/content/docs/release-notes/1.18.0.mdx, website/content/docs/upgrading/upgrade-to-1.16.x.mdx, website/content/docs/upgrading/upgrade-to-1.17.x.mdx, website/content/docs/upgrading/upgrade-to-1.18.x.mdx, website/content/partials/known-issues/log_file_flush_issue.mdx
=> [backport 1.18] add known issue for log file missing logs (#30166)

website/content/docs/release-notes/1.16.1.mdx, website/content/docs/release-notes/1.17.0.mdx, website/content/docs/upgrading/upgrade-to-1.16.x.mdx, website/content/docs/upgrading/upgrade-to-1.17.x.mdx, website/content/partials/known-issues/log_file_flush_issue.mdx
=> [backport 1.17] add known issue for log file (#30166)

website/content/docs/release-notes/1.16.1.mdx, website/content/docs/upgrading/upgrade-to-1.16.x.mdx, website/content/partials/known-issues/log_file_flush_issue.mdx
=> 1.16/docs/known issue log file

CHANGELOG.md
Removes some duplicate CL entries.
=> Fixing some changelog duplicates

website/content/partials/known-issues/azure-unseal-regression.mdx, website/content/partials/known-issues/database-skip-static-role-rotation.mdx, website/content/partials/known-issues/duplicate-hsm-key.mdx
Add missing partials to fix build errors under the 1.17.x docset
=> [DOCS] Add missing include files

website/content/partials/known-issues/azure-unseal-regression.mdx, website/content/partials/known-issues/config_listener_proxy_protocol_behavior_issue.mdx, website/content/partials/known-issues/dangling-entity-aliases-in-memory.mdx, website/content/partials/known-issues/database-skip-static-role-rotation.mdx, website/content/partials/known-issues/duplicate-hsm-key.mdx, website/content/partials/known-issues/duplicate-identity-groups.mdx, website/content/partials/known-issues/manual-entity-merge-does-not-persist.mdx
=> [DOCS] Add missing partials to fix build errors

ui/app/components/usage/page/index.hbs, ui/app/components/usage/page/index.ts, ui/ember-cli-build.js
[UI] [HVT-6840] Add isVaultDedicated argument + Move CSS
Adds a new argument so we can correctly display information based on conditional logic when we render the dashboard.
Also moves css so the correct styling rules take precedence.
[HVT-6840]: https://hashicorp.atlassian.net/browse/HVT-6840?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [UI] HVT-6840: Add isVaultDedicated argument + Move CSS

website/content/docs/upgrading/upgrade-to-1.16.x.mdx, website/content/docs/upgrading/upgrade-to-1.17.x.mdx, website/content/docs/upgrading/upgrade-to-1.18.x.mdx, website/content/docs/upgrading/upgrade-to-1.19.x.mdx
=> Docs: include missing known issue partial

website/content/docs/upgrading/upgrade-to-1.16.x.mdx, website/content/docs/upgrading/upgrade-to-1.17.x.mdx, website/content/docs/upgrading/upgrade-to-1.18.x.mdx
* need to include partial in upgrade file
* add the other partials
files.
=> Docs: include missing known issue partial 

website/content/partials/known-issues/1_19-failures-after-external-group-changes-standby.mdx
Update known issue documentation with symptoms
files.
=> Update known issue documentation with symptoms

website/content/api-docs/secret/pki/index.mdx
Adds documentation for the recently-merged Delta-CRL-Distribution-Points feature.
- Docs only; main feature was here: https://github.com/hashicorp/vault/pull/30319
- JIRA is in branch name
- Internal mini-RFC is here:  https://docs.google.com/document/d/1QmijPA6uD4YdLHMKm1kJsyFKvllXJuAm4t5Z9h3NY2Y/edit?tab=t.0
=> API-Docs for new Delta_CRL_Distribution_Points field

website/content/docs/release-notes/1.19.0.mdx, website/content/docs/upgrading/upgrade-to-1.19.x.mdx, website/content/partials/known-issues/automated-rotation-stops-after-unseal.mdx
Add a known issue for the post-unseal rotation bug.
The named issue in the branch is for filing the known issue - the actual bug is described in VAULT-35505
=> known issue for post-unseal rotation

website/redirects.js
Adds redirect for the old licensing FAQ doc
=> [DOCS] Add missing redirect

ui/app/components/auth/form-template.ts, ui/app/components/auth/form/base.ts, ui/app/components/auth/form/oidc-jwt.ts, ui/app/components/auth/form/okta.ts, ui/app/components/auth/form/saml.ts, ui/app/components/auth/login-form.js, ui/app/components/auth/page.js, ui/app/services/auth.js, ui/tests/acceptance/wrapped-token-test.js, ui/tests/integration/components/auth/form/saml-test.js, ui/tests/integration/components/auth/login-form-test.js, ui/types/vault/adapters/auth-method.d.ts, ui/types/vault/api.d.ts, ui/types/vault/auth/methods.d.ts, ui/types/vault/auth/mfa.d.ts, ui/types/vault/services/auth.d.ts
Adds MFA support for SSO methods
files.
=> UI: Add MFA support for SSO methods

command/server.go, command/server/config.go, command/server/config_test_helpers.go, http/sys_config_state_test.go, vault/core.go, vault/expiration.go, vault/observations/observations_ce.go, vault/observations/observations_consts.go, vault/testing.go
=> VAULT-35396 CE changes

CHANGELOG.md
Backports #30497 to release/1.16.x
=> Backport 30497 to 1.16.x

CHANGELOG.md
Backports #30497 to release/1.18.x
=> backport 30497 to 1.18.x

ui/app/components/sidebar/nav/access.hbs, ui/app/controllers/vault/cluster/secrets/backends.js, ui/app/templates/vault/cluster/secrets/backends.hbs, ui/tests/acceptance/auth/mfa-test.js, ui/tests/acceptance/oidc-auth-method-test.js, ui/tests/acceptance/secrets/backend/engines-test.js, ui/tests/helpers/general-selectors.ts, ui/tests/helpers/secret-engine/secret-engine-selectors.ts, ui/tests/integration/components/json-editor-test.js
=> Backport 1.19.x: Fix headless tests

vault/core_metrics.go
Adds UI, Storage, and Replicated Mount Metrics:
UI Enabled
Number of Authenticated Custom Banners
Number of Unauthenticated Custom Banners
Max Entry Size
Max Namespace/Mount Entry Size
Number of replicated secret mounts
Number of local secret mounts
Number of replicated auth mounts
Number of local auth mounts
Associated ENT PR: https://github.com/hashicorp/vault-enterprise/pull/8028
files.
=> UI, Storage, and Replicated Mount Metrics

changelog/30583.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/14981976097
=> Update vault-plugin-auth-cf to v0.20.1

ui/app/components/sidebar/user-menu.hbs, ui/tests/acceptance/auth/auth-test.js, ui/tests/acceptance/cluster-test.js, ui/tests/acceptance/mfa-setup-test.js, ui/tests/acceptance/reset-password-test.js, ui/tests/acceptance/saml-auth-method-test.js, ui/tests/helpers/general-selectors.ts, ui/tests/integration/components/sidebar/user-menu-test.js
Attempt to address SAML flaky test. Add a custom wait in the form and add timeouts on the flaky tests.
Also, playing boyscout and cleaning up some test selectors.
=> Address SAML flaky test

CHANGELOG.md
=> Update CHANGELOG.md for 1.19.4

website/content/api-docs/secret/identity/group.mdx
Correct the `## Parameters` heading to be h3 instead.
=> Fix heading level (h2 --> h3)

api/sys_raft.go
What it says on the tin.
ENT PR: https://github.com/hashicorp/vault-enterprise/pull/8111
files.
=> [VAULT-35076] Add methods for loading and unloading snapshots to the sys/raft API client

website/content/docs/partners/hsm.mdx
Adding IBM Z & IBMs LinuxONE integration for HSM Dev Docs.
=> IBM Integrations with HSM

enos/modules/verify_secrets_engines/modules/create/auth.tf
Fix a potential race where we might attempt to update the auth before we've initially configured it. Also, rather than update it on all nodes we now choose a node in the cluster at random.
files.
=> enos(auth/ldap): update ldap auth config on random node in cluster

changelog/30832.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/15428067801
=> Update vault-plugin-secrets-azure to v0.22.0

changelog/30868.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/15476078500
=> Update vault-plugin-database-snowflake to v0.14.1

changelog/30872.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/15477697329
=> Update vault-plugin-auth-azure to v0.21.0

website/content/docs/upgrading/upgrade-to-1.16.x.mdx, website/content/docs/upgrading/upgrade-to-1.17.x.mdx, website/content/docs/upgrading/upgrade-to-1.18.x.mdx, website/content/partials/known-issues/duplicate-hsm-key.mdx, website/content/partials/known-issues/enterprise-plugins.mdx
Add missing entries and partials for 1.18 - 1.16 under the v1.18 docs
=> [DOCS] Add missing update info to v1.18 of docs

changelog/30876.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/15479712711
=> Update vault-plugin-auth-jwt to v0.24.1

website/content/docs/updates/change-tracker.mdx, website/content/docs/updates/important-changes.mdx, website/content/partials/release-notes/change-summary/1_16.mdx, website/content/partials/release-notes/change-summary/1_17.mdx, website/content/partials/release-notes/change-summary/1_18.mdx, website/content/partials/release-notes/change-summary/1_19.mdx, website/redirects.js
Layout change for change tracker summary tables and heading updates for Important changes
=> [DOCS] Update change tracker and important changes page

changelog/30910.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/15501999739
=> Update vault-plugin-auth-kubernetes to v0.22.1

website/content/docs/secrets/kv/kv-v2/index.mdx
=> Fix broken kv docs link

website/content/api-docs/secret/databases/snowflake.mdx
=> [DOCS] Fix build error associated with Snowflake warning (v 1.20)

website/content/api-docs/secret/databases/snowflake.mdx
=> [DOCS] Fix build error associated with Snowflake warning (v 1.17)

website/content/api-docs/secret/databases/snowflake.mdx
=> [DOCS] Fix build error associated with Snowflake warning (v 1.18)

website/content/api-docs/secret/databases/snowflake.mdx
=> [DOCS] Fix build error associated with Snowflake warning (v 1.16) 

ui/tests/acceptance/secret-engine-list-view-test.js
Fixes failing test from main pipeline - https://github.com/hashicorp/vault-enterprise/actions/runs/15765600848 
files.
=> UI: fix tooltip test

website/content/docs/updates/important-changes.mdx
=> [DOCS] Fix heading

go.mod, go.sum
Upgrade Kubernetes Authentication Plugin to 0.22.2
=> Upgrade Kubernetes Authentication Plugin to 0.22.2

vault/seal_autoseal.go
Perform an immediate check when starting the seal health check.
This is part of https://github.com/hashicorp/vault-enterprise/pull/8289
files.
=> Perform an immediate check when starting the seal health check

website/content/partials/tips/manage-snapshots.mdx
Fixes the manage snapshots link in the tip partial
=> [DOCS] Fix tip link

website/content/docs/updates/release-notes.mdx
Remove code formatting for metric doc links
=> [DOCS] Remove code formatting

CHANGELOG.md
=> Updates for minor versions in changelog.md

website/redirects.js
Corrects version slug formatting to add missing "v"
=> [DOCS] Correct version slug formatting

ui/tests/acceptance/pki/pki-action-forms-test.js, ui/tests/acceptance/pki/pki-cross-sign-test.js, ui/tests/acceptance/pki/pki-engine-workflow-test.js, ui/tests/helpers/sync/sync-selectors.js, ui/tests/integration/components/choose-pgp-key-form-test.js, ui/tests/integration/components/form-field-test.js, ui/tests/integration/components/pgp-file-test.js, ui/tests/integration/components/pki/page/pki-issuer-import-test.js, ui/tests/integration/components/pki/pki-import-pem-bundle-test.js, ui/tests/integration/components/shamir/dr-token-flow-test.js, ui/tests/integration/components/text-file-test.js
Replace `data-test-text-toggle` with general selector `textToggle`
=> [VAULT-37110] UI: Replace data-test-text-toggle with general selector textToggle

website/content/docs/license/product-usage-reporting.mdx
This PR adds the new MFA config count metrics as metrics entries to the product usage table.
Associated PR: https://github.com/hashicorp/vault-enterprise/pull/8368
files.
=> Docs: Add the new MFA metrics to the census table

website/content/docs/sysadmin/snapshots/restore.mdx
Cherry pick recent PR to 1.20.0 release branch
files.
=> Resolve stray spaces in codeblock example (#31235)

ui/tests/acceptance/enterprise-namespaces-test.js
Fixes failing test due to non-updated test selectors, switched to using a different selector
files.
=> UI: Fix failing test for namespace picker in 1.20.x

website/content/docs/about-vault/what-is-vault.mdx
Fixes a minor typo in the "What is Vault" concept. 
a variety options > a variety of options
files.
=> Docs: Fix minor typo

website/content/api-docs/secret/ssh.mdx, website/content/docs/enterprise/managed-keys.mdx, website/content/docs/secrets/ssh/signed-ssh-certificates.mdx
=> Add ssh managed key documentation

ui/app/styles/helper-classes/general.scss, ui/lib/replication/addon/templates/components/known-secondaries-table.hbs, ui/lib/replication/addon/templates/mode/secondaries/index.hbs, ui/tests/acceptance/enterprise-replication-test.js, ui/tests/integration/components/known-secondaries-table-test.js
Fixes overflow bugs seen with secondaries in DR
Before:
After:
files.
=> UI: Replication - fixing overflow issue on secondaries list / table

ui/app/app.js, ui/app/routes/vault/cluster/auth.js, ui/app/routes/vault/cluster/dashboard.js, ui/app/routes/vault/cluster/secrets/backends.ts, ui/lib/config-ui/addon/engine.js, ui/lib/config-ui/addon/routes/login-settings/index.js, ui/lib/sync/addon/components/secrets/page/destinations/destination/sync.ts
Prior to the casing updates to the API client, #31094 and #31150 reverted some usages of the api service. This PR adds them back in.
files.
=> [UI] Ember Data Migration - Reversions

CHANGELOG.md
Changelog updates for the 1.20.2, 1.19.8, 1.18.13, 1.16.24 release
- [x ] I have documented a clear reason for, and description of, the change I am making.
=> Changelog for 1.20.2, 1.19.8, 1.18.13, 1.16.24

go.mod, go.sum
Adds a list of versions to KV observations that perform a write.
files.
=> VAULT-38794 Update KV plugin to add additional version metadata for observations

.github/actionlint.yml, .github/actions/metadata/action.yml, .github/workflows/actionlint.yml, .github/workflows/benchmark-prevent-performance-degradations.yml, .github/workflows/build-artifacts-ce.yml, .github/workflows/build-artifacts-ent.yml, .github/workflows/build.yml, .github/workflows/changelog-checker.yml, .github/workflows/ci.yml, .github/workflows/copywrite.yml, .github/workflows/do-not-merge-checker.yml, .github/workflows/enos-lint.yml, .github/workflows/milestone-checker.yml, .github/workflows/plugin-update.yml, .github/workflows/test-enos-scenario-ui.yml, .github/workflows/test-go.yml, .github/workflows/test-run-enos-scenario-containers.yml, .github/workflows/test-run-enos-scenario-matrix.yml
The CE counterpart to https://github.com/hashicorp/vault-enterprise/pull/8562
This updates shared workflows between CE/Ent to support execution of CE branches within the enterprise repository context. 
files.
=> [VAULT-34830] actions: update CE workflows for unified enterprise repository

ui/tests/acceptance/dashboard-test.js
I think this was failing because 1) the stat wasn't rendered before the test was looking for it and then when that was resolved, `response` was empty because `peekRecord` would not consistently return data. Moved the request to the beforeEach hook and updated to use `findRecord` so it'd make a new request.
Ran this test in a `for...` loop and it consistently passed with these changes - it would fail pretty regularly before.
```  Acceptance | landing page dashboard > client counts card enterprise: shows the client count card for enterprise: Chrome 128.0
Element [data-test-stat-text="Total"] .stat-label should exist
Source:
at DOMAssertions.findTargetElement (http://localhost:7357/ui/assets/chunk.vendors-node_modules_glimmer_env_dist_modules_es2017_index_js-node_modules_axe-core_axe_js-no-b2 …
```
=> UI: Fix flaky dashboard client count test

.github/workflows/build.yml
Make sure that we always build and test the application if the go toolchain changes.
files.
=> [VAULT-38882] actions(build): build and test on changes to gotoolchain
