builtin/logical/pki/backend.go
builtin/logical/pki/path_resign_crls.go
builtin/logical/pki/path_resign_crls_test.go
changelog/18040.txt
website/content/api-docs/secret/pki.mdx

- Add a new PKI API that allows an end-user to feed in all the information required to generate and sign a CRL by a given issuer.
- This is pretty powerful API allowing an escape hatch for 3rd parties to craft customized CRLs with extensions based on their individual needs

New PKI API to generate and sign a CRL based on input data

---

changelog/18086.txt
go.mod
go.sum

Backporting https://github.com/hashicorp/vault-plugin-secrets-azure/pull/110 bug fix to 1.12.x.

Backport 1.12: secrets/azure: add wal to cleanup role assignments

---

changelog/18084.txt
go.mod
go.sum

Backporting https://github.com/hashicorp/vault-plugin-secrets-azure/pull/110 bug fix to 1.10.x.

Backport 1.10: secrets/azure: add wal to cleanup role assignments

---

builtin/logical/transit/backend_test.go

Execute with:
```
$ go test -v -run=TestTransitPKICSR github.com/hashicorp/vault/builtin/logical/transit ...
backend_test.go:1843: csr: -----BEGIN CERTIFICATE REQUEST-----
MIICXjCCAUYCAQAwGTEXMBUGA1UEAxMOZGFkZ2FyY29ycC5jb20wggEiMA0GCSqG
SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDD8GUy2Rut9ILPXH/Ef7lEaYijuBB9wogd
hKD3uJyfK5PqBqM8166UsrP7Y+bWkwDrMke3aDxXRNybys33kIc8KfGwS3omNYd3
17KN1D4ZgQ+oW6xISa3ISOl4D7XeFtHeTP0U1plVXBd9kqTlo4YPlUF/kTfqmxDu
2a41BIS5HlORdLLG+jQ3shRgwHANONBhlaUnIqEeykdW8/iEBlqoYlMzty9W724R
2mKk0FzrVAZ/X5ZO992dAMrQDvc3Nofl+ddzbElBJLumrcDSwALFVge+ag1N48kE
CCfxjizEykGdCrR+VELb8b33IgFf6EOVRnS5Qy8whmw943v5Oru5AgMBAAGgADAN
BgkqhkiG9w0BAQsFAAOCAQEAdg9SwbrWszMmz60JWQPPfwW+XhzR0MdY82adK8P6
9xpWyJU+U649tAFQb+PCT1OcU7ETd59QcEV38VLndBPWhotTXl5oB5XAqg2bkKHV …
```

Create CSR in Transit, sign with PKI

---

builtin/logical/database/backend_test.go
builtin/logical/database/path_config_connection.go
builtin/logical/database/path_config_connection_test.go
builtin/logical/database/path_rotate_credentials.go
builtin/logical/database/version_wrapper.go
changelog/18051.txt
helper/versions/version.go
helper/versions/version_test.go
vault/auth.go
vault/logical_system.go
vault/logical_system_test.go
vault/mount.go
vault/mount_test.go
vault/plugin_catalog.go
vault/plugin_catalog_test.go
vault/testing.go

Addresses bug described in the 1.12 upgrade guide: https://developer.hashicorp.com/vault/docs/upgrading/upgrade-to-1.12.x#pinning-to-builtin-plugin-versions-may-cause-failure-on-upgrade.
In a nutshell, when we try to start a plugin after upgrading, if it has a builtin version stored in the mount table and that version subsequently disappeared from catalog due to the upgrade, we won't be able to mount it. To fix this, the main idea is to stop storing version information for builtin plugins, and rely on the pre-existing behaviour that not specifying a version selects the builtin (unless it's been shadowed by an unversioned external plugin).
2 main changes, that need to be done for each of the 3 plugin types:
- Stop storing the builtin version for newly mounted plugins
- Clean up storage in …

Remove pinned builtin plugin versions from storage

---

ui/app/adapters/pki/key.js
ui/app/models/pki/key.js
ui/app/serializers/pki/key.js
ui/lib/pki/addon/components/pki-key-details.hbs
ui/lib/pki/addon/components/pki-key-details.ts
ui/lib/pki/addon/controllers/issuers/index.js
ui/lib/pki/addon/controllers/keys/index.js
ui/lib/pki/addon/routes.js
ui/lib/pki/addon/routes/keys/key.js
ui/lib/pki/addon/templates/keys/index.hbs
ui/lib/pki/addon/templates/keys/key/details.hbs

UI: Pki key read view

---

changelog/18109.txt
go.mod
go.sum

This PR backports https://github.com/hashicorp/vault-plugin-secrets-gcp/pull/153 by upgrading the plugin to [v0.12.2](https://github.com/hashicorp/vault-plugin-secrets-gcp/releases/tag/v0.12.2).

Backport 1.10.x: secrets/gcp - Fixes duplicate service account key for rotate root on standby or secondary

---

changelog/18110.txt
go.mod
go.sum

This PR backports https://github.com/hashicorp/vault-plugin-secrets-gcp/pull/153 by upgrading the plugin to [v0.13.2](https://github.com/hashicorp/vault-plugin-secrets-gcp/releases/tag/v0.13.2).

Backport 1.11.x: secrets/gcp - Fixes duplicate service account key for rotate root on standby or secondary

---

changelog/18111.txt
go.mod
go.sum

This PR backports https://github.com/hashicorp/vault-plugin-secrets-gcp/pull/153 by upgrading the plugin to [v0.14.1](https://github.com/hashicorp/vault-plugin-secrets-gcp/releases/tag/v0.14.1).

Backport 1.12.x: secrets/gcp - Fixes duplicate service account key for rotate root on standby or secondary

---

ui/app/utils/error-message.js

Porting `error-message` util from the ui/kubernetes-secrets-engine branch originally created in #18093

Sideport Error Message Util

---

ui/app/decorators/model-form-fields.js
ui/tests/unit/decorators/model-form-fields-test.js

Porting the `model-form-fields` decorator from the ui/kubernetes-secrets-engine feature branch originally created in #18010

Sideport Model Form Fields Decorator

---

changelog/18101.txt
command/agent.go
command/agent/config/config_test.go
command/agent/config/test-fixtures/config-cache-embedded-type.hcl
command/agent/config/test-fixtures/config-cache.hcl
internalshared/configutil/config.go
internalshared/configutil/listener.go
sdk/helper/consts/agent.go
website/content/docs/agent/caching/index.mdx

This introduces a new option for the Agent HCL config, `metrics_only_listener`. It defaults to false. If set to true, it will make the defined listener only serve metrics. It can be put alongside other listener blocks, too, like so:
```
cache {
enforce_consistency = "always"
use_auto_auth_token = true
}
listener "tcp" {
address = "127.0.0.1:8100"
tls_disable = true
}
listener "tcp" {
address = "127.0.0.1:3000"
tls_disable = true
telemetry {
metrics_only_listener = true
}
}
```
Using the above, you can e.g. cURL the metrics (but nothing else). This shows an example with an auth failure:
```
curl http://127.0.0.1:3000/agent/v1/metrics
{"Timestamp":"2022-11-23 17:41:50 +0000 UTC","Gauges":[{"Name":"vault.runtime.alloc_bytes","Value":10344560,"Labels":{}},{"Name":"vault.runtime.free_count","Va …
```

VAULT-6368 Metrics-only listener for Agent

---

builtin/logical/pkiext/nginx_test.go
builtin/logical/pkiext/test_helpers.go

~Blocked on #17320 -- will be rebased once that merges.~
---
This adds tests for CRL status in the integration tests. It appears that `wget2` might have support for Delta CRLs enabled already, so we might try that.

Add crl integraiton to tests

---

changelog/17979.txt
helper/logging/logger.go
vault/core.go
vault/logical_system.go
vault/logical_system_paths.go
vault/logical_system_test.go
website/content/api-docs/system/loggers.mdx

PR https://github.com/hashicorp/vault/pull/16111 added support to modify server logging verbosity both globally and for individual loggers. It did not, however, add the ability to read the current state of the logger verbosity levels. This PR introduces read handlers for the `sys/loggers` and `sys/loggers/:name` endpoints.
Additional more low-level changes:
- Modified `Core.SetLogLevelByName` to account for the potential of `Core.allLoggers` including loggers that share the same name
- Modified existing `sys/loggers` handlers to use `ParseLogLevel` from the logging helper package to remove redundant code
- Added checks to ensure `sys/loggers` endpoints do not handle base logger (name == `""`)
- Added a `TranslateLoggerLevel` func to the logging helper package to determine the logging …

VAULT-9427: Add read support to `sys/loggers` endpoints

---

changelog/17836.txt
http/sys_seal_test.go
vault/core.go
vault/seal.go

The error message inspection is the same as used elsewhere in the code (vault/barrier_aes_gcm.go).
ErrInvalidKey is already handled as a http 400 response in http/sys_seal.go, so we can simply use it in vault/seal.go to get http 400.
Regarding the error message, omitting the "message authentication failed" part, as it is printed to the end user.
Fixes #17792

Make the error and http code clearer when supplying wrong unseal key

---

ui/.eslintrc.js
ui/package.json
ui/yarn.lock

More Typescript updates, to use the linter. This came up because when trying to use `unknown` as a type, eslint complained that it was not a defined variable.

UI: Use typescript linter and parser

---

changelog/17835.txt
ui/mirage/handlers/mfa-login.js

Use `crypto.randomUUID()` to generate `mfa_request_id` instead of magic with `Math.random()`.
Fixes: 712cc9ee, ca14c191
Signed-off-by: Konstantin Demin <rockdrilla@gmail.com>

ui: mfa: use proper request id generation

---

command/agent_test.go
command/server.go
helper/locking/deadlock.go
helper/locking/lock.go
http/forwarded_for_test.go
http/handler.go
http/testing.go
vault/core.go
vault/expiration.go
vault/external_tests/quotas/quotas_test.go
vault/quotas/quotas.go
vault/testing.go

Also switch some key locks to use DeadlockMutex to make it easier to discover deadlocks in testing.
There's some interesting stuff in testing.go to address the problem of: how do we skip setting up quotas when someone is using a nonstandard handler that might not even implement the quotas endpoint? The challenge is that because we're taking a func pointer to generate the real handler func, we don't have any way to compare that func pointer to the standard handler (github.com/hashicorp/http.Handler) without creating a circular dependency between packages vault and http. The solution is to pass a method instead of an anonymous func pointer so that we can do reflection on it.  I'm not very happy with some of the names that resulted though ("HandlerHandler"? really?), hopefully we can improve …

Create global quotas of each type in every NewTestCluster.  

---

changelog/18121.txt
vault/audit_broker.go
vault/request_forwarding_rpc.go

Adds a stack trace to the logs when we recover from a panic, otherwise we only get the panic error string, and no code location for where it came from.
The only other bit of production code we add a `recover` to is: https://github.com/hashicorp/vault/blob/c73a6a4a9e5d5b4e27a51102c8243351d40f1386/builtin/logical/ssh/path_issue_sign.go#L477
It wasn't clear to me that we would want a stack trace in that instance, so I've left it alone.

Add stack trace to audit logging panic recovery

---

.circleci/config.yml
.circleci/config/commands/go_test.yml

Backport of  #17729 for 1.11.x, I accidentally closed the original backport PR.
When copying data into the container, due to the id changes pointed out in the previous attempt, the container couldn't read this data.
By creating a new user in the container, matching the host's UID/GID, we can successfully copy data in/out of the container without worrying about differing UID/GIDs.
See also: https://github.com/hashicorp/vault/pull/17658

Backport 1.11.x: Use host's uid in container's executor (#17729)

---

go.mod

Update go.mod to latest 1.11.7 SDK version update, along with a no-op `go mod tidy`

Update go.mod to use latest 1.11.7 SDK release

---

website/content/docs/enterprise/pkcs11-provider/aws-xks.mdx
website/content/docs/enterprise/pkcs11-provider/index.mdx
website/content/docs/enterprise/pkcs11-provider/oracle-tde.mdx
website/data/docs-nav-data.json

AWS announced [KMS External Key Store](https://aws.amazon.com/blogs/aws/announcing-aws-kms-external-key-store-xks/), which we support using their reference [`xks-proxy`](https://github.com/aws-samples/aws-kms-xks-proxy) software.
This adds a documentation page showing how to configure KMIP and the PKCS#11 provider to to work with KMS and `xks-proxy`.

Add doc for AWS XKS Proxy with PKCS#11 Provider

---

ui/app/app.js
ui/app/styles/core/helpers.scss
ui/lib/kubernetes/addon/components/config-cta.hbs
ui/lib/kubernetes/addon/components/page/configuration.hbs
ui/lib/kubernetes/addon/components/tab-page-header.hbs
ui/lib/kubernetes/addon/engine.js
ui/lib/kubernetes/addon/routes.js
ui/lib/kubernetes/addon/routes/configuration.js
ui/lib/kubernetes/addon/routes/configuration/edit.js
ui/lib/kubernetes/addon/routes/configuration/index.js
ui/lib/kubernetes/addon/templates/configuration.hbs
ui/lib/kubernetes/addon/templates/configuration/edit.hbs
ui/lib/kubernetes/addon/templates/configuration/index.hbs
ui/mirage/factories/kubernetes-config.js
ui/mirage/factories/kubernetes-role.js
ui/mirage/scenarios/default.js
ui/tests/integration/components/kubernetes/config-cta-test.js
ui/tests/integration/components/kubernetes/page/configuration-test.js
ui/tests/integration/components/kubernetes/page/configure-test.js
ui/tests/integration/components/kubernetes/tab-page-header-test.js

Configuration view for Kubernetes secrets engine:
- adds `TabPageHeader` component for use in tab (overview, roles, configuration) routes
- adds `ConfigCta` empty state wrapper component for use across tab routes
- adds page component for configuration view
- removes unneeded configuration edit and index routes 
- adds block for kubernetes in mirage default scenario for seeding db

Kubernetes Configuration View

---

CHANGELOG.md

This PR adds changelog entries for the Vault 1.10.9, 1.11.6, and 1.12.2 releases.
TODO:

changelog: add entries for 1.10.9, 1.11.6, 1.12.2

---

go.mod

Bump Vault to use SDK version 1.12.3 that was updated in https://github.com/hashicorp/vault/pull/18177
`go mod tidy` was a no-op

Update go.mod to Vault SDK version 1.12.3

---

changelog/18173.txt
vault/external_plugin_test.go
vault/logical_system.go
vault/logical_system_test.go
vault/testing.go

Fixes #17722
From 1.12.0 onwards, when the [`GET /v1/sys/plugins/catalog`](https://developer.hashicorp.com/vault/api-docs/system/plugins-catalog#list-plugins) endpoint is hit and audit logging is enabled, Vault panics while HMACing the response in order to audit log it. @jmthvt correctly diagnosed this was due to the SemanticVersion field in the struct included in the response.
The handler now takes a similar approach to [`mountInfo()`](https://github.com/hashicorp/vault/blob/1d7c5db671e6700933663269c476ed98e70b22e3/vault/logical_system.go#L898) and rebuilds the structs as maps composed of primitive values.
<details>
<summary>Logging with panic stack trace added</summary>
```text
2022-11-30T18:06:02.279Z [ERROR] vault.audit: panic during logging: request_path=sys/plugins/catalog …
```

Fix plugin list API when audit logging enabled

---

builtin/logical/pki/ocsp.go
changelog/18184.txt

Identified by @cipherboy thanks!
- Seems when no body is sent with a POST request Vault will not populate the HTTPRequest member variable which causes a nil panic, it can be reproduced with `vault write -force pki/ocsp`
- Add a check for it and the Body member variable to be nil before use.

Address a nil panic when writing an empty POST request to the ocsp handler

---

builtin/logical/pki/ocsp.go

This nil issue can't actually happen at the moment, until we added possibly say a delete handler to the router for OCSP or something else. Since we know this is a possible issue, fix it up. Thanks to @cipherboy for pointing this out as well.

Do not use possibly nil HttpRequest object in default OCSP error handler

---

changelog/18163.txt
command/kv_patch.go
command/kv_put.go

Vault is currently panicking when trying to `patch` with the `-field` parameter set.  This occurs because we are expecting there to be metadata around the secret, but none is getting returned due to the flag being set.  A check has been added to ensure that the `secret` is populated before trying to access the Data from underneath it.
Previous Error:
```console
$ vault kv patch -field=version  -method=rw -mount=kv /secrets test=- <<< "new"
4
= Secret Path =
kv/data/secrets
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x30 pc=0x103aeab1c]
goroutine 1 [running]:
github.com/hashicorp/vault/command.(*KVPatchCommand).Run(0x14000aca440, {0x140001a0030, 0x5, 0x5}) …
```

Skip Formatting For NIL Secret

---

changelog/18143.txt
command/namespace_patch.go

Correct the help text for Vault CLI namespace patch examples.

Fix vault cli namespace patch examples

---

changelog/18210.txt
sdk/plugin/grpc_storage.go
sdk/plugin/grpc_system.go
sdk/plugin/grpc_system_test.go
sdk/plugin/storage_test.go

And return an error instead of panicking.
This situation can occur if a plugin attempts to access the system view during setup when Vault is checking the plugin metadata.
Fixes #17878.

Check if sys view is missing in GRPC sys view

---

changelog/18189.txt
vault/auth.go
vault/core.go
vault/external_plugin_test.go
vault/mount.go

This PR fixes an inconsistency and logic issue in the previous unseal logic. We now consistently check the plugincatalog for secrets engines and auth methods and appropriately skip the backend startup for deregistered plugins.
This probably needs an unseal test to prevent regression.
This PR should resolve VAULT-11858

plugins: Mount missing plugin entries and skip loading

---

builtin/logical/pki/backend_test.go
builtin/logical/pki/crl_test.go
builtin/logical/pki/integration_test.go
builtin/logical/pki/ocsp_test.go
builtin/logical/pki/path_config_crl.go
builtin/logical/pki/path_resign_crls_test.go
builtin/logical/pki/path_roles.go
builtin/logical/pki/path_tidy.go
builtin/logical/pki/storage_migrations_test.go
changelog/18222.txt
command/patch_test.go

---
As identified in #18199, several `/config` endpoints behave differently than their non-config endpoints. This can be confusing as they won't clear their data; you must manually submit defaults if that's preferable.
Respond to all writes with the written data, rather than with nil responses. This lets operators see if their intended changes align with what actually occurred, without having to issue a new read.

Respond with data to all writes in PKI engine

---

changelog/18192.txt
sdk/framework/openapi.go
sdk/framework/openapi_test.go
sdk/framework/path.go
sdk/framework/testdata/responses.json
sdk/go.mod

This PR adds logic to generate `openapi.json` response structures. It's been split out from #18055 for easier review process.
For `GET "/auth/approle/role/{role_name}/bind-secret-id"` path, it will update the response as follows:
```diff
"responses": {
"200": {
"description": "OK",
++            "content": {
++              "application/json": {
++                "schema": {
++                  "$ref": "#/components/schemas/ApproleRoleBindSecretIdResponse"
++                }
++             }
}
}
}
```
And will add the actual response structure:
```diff
++      "ApproleRoleBindSecretIdResponse": {
++        "type": "object",
++        "properties": {
++          "bind_secret_id": {
++            "type": "boolean",
++            "description": "Impose secret_id to be presented when logging …
```

Add logic to generate openapi response structures

---

website/content/docs/commands/operator/raft.mdx
website/content/docs/configuration/storage/raft.mdx

Docs portion of #18030, now that 1.12.2 is released. Picked via:
```shell-session
git checkout main -- website/content/docs/configuration/storage/raft.mdx
```

Backport docs for retry_join_as_non_voter config option

---

sdk/logical/managed_key.go

This adds a managed MAC key interface in preparation for future HMAC managed keys support.
Ref: VAULT-11711

Add ManagedMACKey interface to SDK.

---

ui/app/styles/core/helpers.scss
ui/lib/kubernetes/addon/components/page/overview.hbs
ui/lib/kubernetes/addon/components/page/overview.js
ui/lib/kubernetes/addon/routes/overview.js
ui/lib/kubernetes/addon/templates/overview.hbs
ui/tests/integration/components/kubernetes/page/overview-test.js

Adds overview page for Kubernetes secrets engine
[Overview Figma Design here](https://www.figma.com/file/rB5gYCA95F9aKMc7I2Qx0d/Kubernetes-Secret-Engine-Handoff?node-id=1%3A719&t=LEZsdtAweDMP5xoW-0)
**Overview when Kubernetes is not configured:**
**Overview when Kubernetes has no roles:**
**Overview when there are roles**
https://user-images.githubusercontent.com/30884335/205747932-015021b7-3891-4ff5-a9ff-e8257bc09205.mov

VAULT-9863 Kubernetes Overview Page

---

ui/app/adapters/pki/role.js
ui/app/models/pki/role.js
ui/app/templates/components/pki/role-pki-edit.hbs
ui/lib/core/addon/components/secret-list-header-tab.hbs
ui/lib/pki/addon/components/page/pki-role-details.hbs
ui/lib/pki/addon/components/page/pki-role-details.ts
ui/lib/pki/addon/components/pki-role-form.hbs
ui/lib/pki/addon/routes/certificates/index.js
ui/lib/pki/addon/routes/issuers/index.js
ui/lib/pki/addon/routes/keys/index.js
ui/lib/pki/addon/routes/roles/create.js
ui/lib/pki/addon/routes/roles/index.js
ui/lib/pki/addon/routes/roles/role/details.js
ui/lib/pki/addon/routes/roles/role/edit.js
ui/lib/pki/addon/templates/roles/create.hbs
ui/lib/pki/addon/templates/roles/index.hbs
ui/lib/pki/addon/templates/roles/role/details.hbs
ui/lib/pki/addon/templates/roles/role/edit.hbs
ui/tests/acceptance/pki/pki-engine-workflow-test.js
ui/tests/helpers/pki/roles/page-details.js
ui/tests/helpers/pki/workflow.js
ui/tests/integration/components/pki/keys/page-details-test.js
ui/tests/integration/components/pki/pki-key-parameters-test.js
ui/tests/integration/components/pki/roles/page-pki-role-details-test.js

This PR adds capability checks on the role toolbar links, adds the ability to delete the role, and cleans up some breadcrumb and route logic (mostly prompted by test coverage)
**Role toolbar links go to the right place (not all pages built out yet)**
**Role view when you only have read/list access**
**Role view when you have all engine permissions**

UI: PKI Role toolbar

---

helper/logging/logger.go
helper/logging/logger_test.go

This was missed as part of the log rotation work (log file/log rotation)

Ensure base logging uses IndependentLevels

---

helper/logging/logfile.go

Log file rotation tests surfaced a potential bug whereby extra log files could be created depending on the execution time it takes to get through the `Write`. 
This fix attempts to ensure that we only look at possible rotation of log files, if the log files are already in existence.

Only attempt rotation if files already exist when a Write is requested.

---

builtin/logical/pki/backend_test.go

- @ncabatoff brought this to our attention, one of the PKI test suites is overwriting the production code's value leading to a data race issue.
- Remove the setting of the variable with the same value from the test suite.
```
Read at 0x000007d41580 by goroutine 2887:
github.com/hashicorp/vault/builtin/logical/pki.getOtherSANsFromX509Extensions()
/home/circleci/go/src/github.com/hashicorp/vault/builtin/logical/pki/cert_util.go:983 +0x13e
github.com/hashicorp/vault/builtin/logical/pki.generateCreationBundle()
/home/circleci/go/src/github.com/hashicorp/vault/builtin/logical/pki/cert_util.go:1182 +0xead
github.com/hashicorp/vault/builtin/logical/pki.signCert()
/home/circleci/go/src/github.com/hashicorp/vault/builtin/logical/pki/cert_util.go:923 +0x151e …
```

Address race in PKI test case

---

builtin/logical/pki/backend.go
builtin/logical/pki/cert_util.go
builtin/logical/pki/cert_util_test.go
builtin/logical/pki/crl_test.go
builtin/logical/pki/crl_util.go
builtin/logical/pki/ocsp.go
builtin/logical/pki/path_config_crl.go
builtin/logical/pki/path_fetch.go
builtin/logical/pki/path_fetch_issuers.go
builtin/logical/pki/path_manage_issuers.go
builtin/logical/pki/path_revoke.go
builtin/logical/pki/path_root.go
builtin/logical/pki/path_tidy.go
builtin/logical/pki/secret_certs.go

A lot of places took a `(context, backend, request)` tuple, ignoring the request proper and only using it for its storage. This (modified) tuple is exactly the set of elements in the shared storage context, so we should be using that instead of manually passing all three elements around.
This simplifies a few places where we'd generate a storage context at the request level and then split it apart only to recreate it again later (e.g., CRL building).
---
This also fixes the `path_revoke` to correctly use `certs/` as the prefix to fetchCertBySerial rather than `req.Path` :o

Refactor PKI to use shared storage context

---

sdk/logical/managed_key.go

This adds a managed key random source interface in preparation for future RNG managed keys support.
Ref: VAULT-11712

Add ManagedKeyRandomSource interface to SDK.

---

changelog/18273.txt
vault/external_tests/quotas/quotas_test.go
vault/quotas/quotas.go
website/content/docs/concepts/resource-quotas.mdx

It seems like this never really worked, unfortunately. We check the request path against the default exempt list to see if the request path is a prefix of any, but since the request path was `sys/health`, it wasn't a prefix of `/v1/sys/health`. After this change, everything seems to work as expected (as `sys/health` is indeed a prefix of `sys/health`).
The test I added will fail if this is broken again in the future, and all tests pass after this change (both OSS and Ent).
I updated the docs to make it clearer for users wanting to customize their set of defaults.

VAULT-8336 Fix default rate limit paths

---

website/content/docs/enterprise/license/faq.mdx

The free Vault Enterprise trial license form is no longer in use. This removes mention of it and the link to it.

Remove mention of public Vault trial license form

---

Makefile

`make proto` is currently broken and will return the following error:
```
Could not make proto path relative: vault/hcp_link/capabilities/meta/*.proto: No such file or directory
make: *** [proto] Error 1
```
The `meta` and `link_control` proto paths have been removed from the `proto` make target to resolve this issue.

remove deleted link proto paths

---

changelog/18227.txt
command/server/listener.go
command/server/listener_test.go
command/server/listener_unix.go
command/server/listener_unix_test.go
website/content/docs/configuration/listener/index.mdx
website/content/docs/configuration/listener/unix.mdx
website/data/docs-nav-data.json

Fix #5491  
hcl config
```text
listener "unix" {}
listener "tcp" {
address       = "127.0.0.1:8300"
tls_cert_file = ""
tls_key_file  = ""
tls_disable   = 1
}
api_addr     = "http://127.0.0.1:8300"
cluster_addr = "http://127.0.0.1:8300"
storage "file" {
path           = "/tmp/vault/storage"
connection_url = ""
ha_enabled     = false
}
```
Vault server logs: 
```sh
==> Vault server configuration:
Api Address: http://127.0.0.1:8300
Cgo: disabled
Cluster Address: https://127.0.0.1:8301
Environment Variables: DBUS_SESSION_BUS_ADDRESS, HOME, LANG, LC_CTYPE, LOGNAME, MOTD_SHOWN, OLDPWD, PATH, PWD, SHELL, SHLVL, SSH_CLIENT, SSH_CONNECTION, SSH_TTY, TERM, USER, XDG_DATA_DIRS, XDG_RUNTIME_DIR, XDG_SESSION_CLASS, XDG_SESSION_ID, XDG_SESSION_TYPE, _
Go Version: go1.19.3
Listener 1: unix …
```

Server: add and support unix listener (UDS)

---

ui/lib/kubernetes/addon/routes/overview.js

When visiting the overview route when no roles have been created, the promise rejection from the roles query was not being handled which resulted in the promise returned by `hash` also being rejected. This resulted in the 404 page being shown. I added a catch to the query and return an empty array if no roles are found.

Kubernetes Secrets Engine Overview Bug

---

builtin/credential/cert/path_certs.go
website/content/api-docs/auth/cert.mdx

Add missing documentation within the cert auth API docs about adding and/or augmenting an entity alias with extensions from the cert used to authorize the vault client. Feature was added in #13348 and #14751
Missing docs was pointed out by @tmanninger in this [issue thread](https://github.com/hashicorp/vault/issues/18212#issuecomment-1346096583)

Document adding metadata to entity alias within cert auth

---

changelog/18315.txt
command/server.go
command/server_test.go

The properly formatted `resource_id` found in the `cloud` config stanza will include the organization, project, and user-provided ID of the resource in HCP. This PR modifies the `vault server` command to include this information in the startup logs if a valid `cloud` stanza has been provided.
```
❯ vault server -dev -config=hcp.hcl
==> Vault server configuration:
HCP Organization: aa048f12-d735-4fe9-9443-40df11799938
HCP Project: 03d4f563-c136-49cd-9c57-3923a1ef28e9
HCP Resource ID: test-linked-cluster
Api Address: http://127.0.0.1:8200
Cgo: disabled
Cluster Address: https://127.0.0.1:8201
Environment Variables: <....>
Go Version: go1.19.3
Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "127.0.0.1:8201", max_request_duration: "1m30s", max_request_size: "33554432", tls: …
```

Add HCP connectivity info to `vault server` startup logs

---

ui/app/routes/vault/cluster/secrets/backend/list.js

Adds in check for `engineRoute` in `secrets.backend.list` route when linking to secrets engine inside an Ember Engine.

Secrets List Engine Link

---

builtin/logical/transit/path_encrypt.go
changelog/18310.txt
website/content/api-docs/secret/transit.mdx

Including InternalErrors such as decryption failures.

Return the partial success code override for all batch error types

---

.github/workflows/enos-ci-bootstrap.yml

The role name for the enterprise CI bootstrap workflow should have been: `aws_role=arn:aws:iam::505811019928:role/github_actions-vault_enterprise_ci`. This PR corrects this error.

Fix role name in CI bootstrap workflow

---

ui/lib/kubernetes/addon/components/config-cta.hbs
ui/lib/kubernetes/addon/components/page/configuration.hbs
ui/lib/kubernetes/addon/components/page/overview.hbs
ui/lib/kubernetes/addon/components/page/overview.js
ui/lib/kubernetes/addon/components/page/role/create-and-edit.hbs
ui/lib/kubernetes/addon/components/page/role/create-and-edit.js
ui/lib/kubernetes/addon/components/page/roles.hbs
ui/lib/kubernetes/addon/components/page/roles.js
ui/lib/kubernetes/addon/routes/index.js
ui/lib/kubernetes/addon/routes/roles/index.js
ui/lib/kubernetes/addon/templates/configuration.hbs
ui/lib/kubernetes/addon/templates/overview.hbs
ui/lib/kubernetes/addon/templates/roles/index.hbs
ui/mirage/factories/kubernetes-role.js
ui/tests/integration/components/kubernetes/page/configuration-test.js
ui/tests/integration/components/kubernetes/page/overview-test.js
ui/tests/integration/components/kubernetes/page/role/create-and-edit-test.js
ui/tests/integration/components/kubernetes/page/role/details-test.js
ui/tests/integration/components/kubernetes/page/roles-test.js

During manual testing some bugs were revealed and general improvements were made:
- link in `ConfigCta` component was pointed to incorrect route
- added catch to return empty array in roles model hook
- delete action in roles list menu was not working
- in role create/edit view the generated role rules were not saving
- updated overview, configuration and roles page components to accept args for individual model properties
- fixes page::role::details test broken in previous PR
- adds more test coverage for generated role rules
- adds top level index route that redirects to overview

Manual Testing: Bug Fixes and Improvements

---

website/content/docs/platform/aws/lambda-extension.mdx

[AWS SnapStart](https://docs.aws.amazon.com/lambda/latest/dg/snapstart.html) does not support the Lambda Extensions API. This makes the Vault Lambda Extension incompatible with AWS SnapStart. We will update our docs to note this limitation.
Backporting this to 1.12.x so that it makes it to the currently published docs.

docs: add note on aws snapstart incompatibility

---

command/audit.go
website/content/docs/audit/index.mdx

This PR adds some documentation to the `audit enable` command and docs in an effort to clearly communicate the recommendation to use multiple audit devices. Backporting to 1.12.x so the update makes it into the current website.
This PR was inspired by #3725.

command/audit: Recommend multiple audit devices

---

vault/core.go

When issuing a core.Shutdown(), it is common to background the shutdown request. This allows Vault to continue cleaning up, mainly to release the stateLock. This allows the shutdown to complete, but is inherently racy, so the core.shutdownDoneCh needs to be made atomic.

core: Make shutdownDoneCh atomic

---

ui/app/routes/vault/cluster/secrets/backend/list.js
ui/lib/kubernetes/addon/components/page/credentials.hbs
ui/lib/kubernetes/addon/components/page/roles.hbs
ui/mirage/handlers/kubernetes.js
ui/mirage/scenarios/default.js
ui/mirage/scenarios/kubernetes.js
ui/tests/acceptance/secrets/backend/kubernetes/roles-test.js

- adds acceptance tests for roles
- fixes previous test failures
- updates `TtlPicker2` instance to `TtlPicker`
- fixes issue with mirage delete route handler removing all roles
- adds kubernetes mirage scenario for use in dev and tests

Kubernetes Roles Acceptance Tests

---

website/content/docs/concepts/policies.mdx

Removing a reference to blacklist in the policy documentation.

docs/policies: update denied_parameters description

---

changelog/18350.txt
ui/app/models/database/role.js

Manual backport of #18350 due to merge conflicts in generated backport PRs.
---
Changes the language on database role from `Database` to `Connection name` 
**AFTER**
**BEFORE**
---
<details>
<summary> Overview of commits </summary>
- 58e9f4fcb699102efff3119fb4c8c6613f63784c 
</details>

UI: Update database to connection name on role (#18350)

---

command/commands.go
internal/go118_sha1_patch.go
main.go

**tl;dr** I'm sorry
This will allow us to upgrade to Go 1.19+ in Vault 1.10 and 1.11, which helps keeps security tools quiet about using older versions with CVE.
[Go 1.18+ has removed support (by default) for certificates containing signatures with SHA-1.](https://go.dev/doc/go1.18#sha1)
For Vault 1.12+, we've [officially deprecated](https://developer.hashicorp.com/vault/docs/deprecation/faq#q-what-is-the-impact-of-removing-support-for-x-509-certificates-with-signatures-that-use-sha-1) these kinds of signatures and have a runtime workaround using an environment variable that users can set. This is the only official workaround.
This PR patches an internal Go variable (that is also patched by the environment variable mentioned above), but does so permanently and only in code, so that users …

Add a workaround to allow SHA-1 signatures in certs to work for Vault <= 1.11

---

builtin/logical/pki/path_tidy.go
builtin/logical/pki/path_tidy_test.go
website/content/api-docs/secret/pki.mdx

---
Thanks @jkirschner-hashicorp for pointing out that the auto-tidy docs section was missing from main.

Correctly handle issuer tidying in auto-tidy config

---

.circleci/Makefile

The removal of the phony $(OUT) target was preventing `make ci-config` from recognizing changes to .go-version. Reintroduce this change to fix go version bumps.

Fix ci-config for go-version bumps

---

physical/raft/fsm.go
physical/raft/raft.go

We need a read lock when reading any of the FSM fields. Expose a new fsm.Stats to handle the read lock wrapping and make sure we use it. Also use the FSM's Rlock wrapper for `db` operations consistently.
Co-authored by: Josh Black <raskchanky@users.noreply.github.com>

Fix race in fsm.db

---

builtin/credential/aws/pkcs7/sign.go
internal/go118_sha1_patch.go

Bad news: the hot patch we were using breaks in Go 1.19.4: https://github.com/golang/go/commit/6109c07ec4cf2b26eba9441ad5148f8dcb8c6497
Good news: we can now patch with an environment variable at runtime.

Fix SHA1 patch for Go 1.19.4; patch test

---

changelog/18401.txt
vault/core.go
vault/expiration.go
vault/logical_passthrough.go
vault/logical_passthrough_test.go
vault/testing.go

The test in question lives in the ent repo, since it depends on perf standbys.

Prevent panics in expiration invalidation, and make some changes for testing

---

builtin/credential/approle/path_role_test.go
builtin/credential/approle/validation.go
changelog/18145.txt

This PR fixes an issue when attempting to use /32 CIDR blocks for Token Bound CIDR restrictions and Secret ID CIDR restrictions. When setting `token_bound_cidrs` on a role definition containing a CIDR block with the /32 mask, the block gets stored as a single IP address string. When setting `token_bound_cidrs` when generating a new Secret ID, Vault validates that the blocks defined in the Secret ID configuration are a subset of the CIDR blocks defined on the role. In the case of a /32 mask, since we store it as a single IP without the mask, this validation fails. This change checks for any blocks that may exist in the `token_bound_cidrs` configuration on the role definition that do not have a mask, and append a `/32` to the block to allow for proper validation.

Approle: Fix CIDR validation for /32 masks on Token Bound CIDRs

---

ui/lib/kubernetes/addon/components/page/credentials.hbs
ui/lib/kubernetes/addon/components/page/overview.hbs
ui/mirage/scenarios/kubernetes.js
ui/tests/acceptance/secrets/backend/kubernetes/configuration-test.js
ui/tests/acceptance/secrets/backend/kubernetes/credentials-test.js
ui/tests/acceptance/secrets/backend/kubernetes/overview-test.js

Acceptance tests for Kubernetes secrets engine workflows. The acceptance tests mainly tests for links and buttons that transition to different pages.
VAULT-12185 Acceptance test for overview
VAULT-12186 Acceptance test for configuration
VAULT-12298 Acceptance test for credentials

VAULT-11862 Kubernetes acceptance tests

---

website/content/docs/release-notes/1.11.0.mdx
website/content/docs/secrets/pki/index.mdx

🧵 [Slack thread](https://hashicorp.slack.com/archives/C04B4TAEQ6L/p1671143425042579)
Now that Consul patch is available, this PR updates:
- Release notes for Vault 1.11.0 (🔍 [Deploy Preview](https://vault-git-docs-update-release-notes-111-hashicorp.vercel.app/vault/docs/release-notes/1.11.0#known-issues))
- Notes on the PKI Secrets Engine (🔍 [Deploy Preview](https://vault-git-docs-update-release-notes-111-hashicorp.vercel.app/vault/docs/secrets/pki))

Update the notes about Consul Connect CA issue

---

.github/workflows/enos-run.yml

- enos-run workflow will checkout the `main` branch by default, which would pass incorrect metadata to the workflow so we use the `revision` passed by the calling workflow to checkout the sha and get the relavant metadata`

Fix the checkout sha for enos-run workflow

---

ui/tests/integration/components/mount-backend/type-form-test.js

One of the mount-backend/type-form tests were failing but only runs on enterprise

UI: Fix mount backend type-form enterprise test

---

changelog/18452.txt
vault/activity_log.go
vault/logical_system_activity.go

https://hashicorp.atlassian.net/browse/VAULT-12031

De-duplicate namespaces when historical and current month data are mixed

---

website/content/api-docs/secret/kv/kv-v1.mdx
website/content/api-docs/secret/kv/kv-v2.mdx

For kv secrets enving version 1 and 2 docs, highlight the fact that the secrets engine is enabled at `/secret` path. 
https://github.com/hashicorp/vault/issues/17425

docs: highlight paragraph about default path in kv secrets engines docs.

---

builtin/logical/pki/ca_test.go
builtin/logical/pki/path_fetch_issuers.go
changelog/18482.txt

This endpoint is unauthenticated and shouldn't contain sensitive information. However, listing the issuers (`LIST /issuers`) already returns both the issuer ID and the issuer name (if any) so this information is safe to return here.
When fetching `/pki/issuer/default/json`, it would be nice to know exactly which issuer ID and name it corresponds to, without having to fetch the authenticated endpoint as well.

Add issuer reference info on JSON endpoint

---

ui/lib/kubernetes/addon/components/page/configuration.hbs
ui/lib/kubernetes/addon/components/page/credentials.hbs
ui/lib/kubernetes/addon/components/page/overview.hbs
ui/lib/kubernetes/addon/components/page/role/details.hbs
ui/lib/kubernetes/addon/components/page/roles.hbs
ui/lib/kubernetes/addon/components/tab-page-header.hbs
ui/lib/kubernetes/addon/routes/configuration.js
ui/lib/kubernetes/addon/routes/overview.js
ui/lib/kubernetes/addon/routes/roles/index.js
ui/lib/kubernetes/addon/routes/roles/role/credentials.js
ui/lib/kubernetes/addon/routes/roles/role/details.js
ui/lib/kubernetes/addon/templates/configuration.hbs
ui/lib/kubernetes/addon/templates/overview.hbs
ui/lib/kubernetes/addon/templates/roles/index.hbs
ui/lib/kubernetes/addon/templates/roles/role/credentials.hbs
ui/lib/kubernetes/addon/templates/roles/role/details.hbs
ui/tests/acceptance/secrets/backend/kubernetes/credentials-test.js
ui/tests/acceptance/secrets/backend/kubernetes/roles-test.js
ui/tests/integration/components/kubernetes/page/configuration-test.js
ui/tests/integration/components/kubernetes/page/credentials-test.js
ui/tests/integration/components/kubernetes/page/overview-test.js
ui/tests/integration/components/kubernetes/page/role/details-test.js
ui/tests/integration/components/kubernetes/page/roles-test.js
ui/tests/integration/components/kubernetes/tab-page-header-test.js

Use `Page::Breadcrumb` component for all the pages in Kubernetes Secrets Engine instead of manually creating breadcrumbs!

VAULT-12127 Refactor breadcrumbs to use breadcrumb component

---

ui/app/adapters/pki/key.js
ui/lib/core/addon/templates/components/readonly-form-field.hbs
ui/lib/pki/addon/components/pki-key-form.hbs
ui/lib/pki/addon/components/pki-key-form.js
ui/lib/pki/addon/templates/keys/key/edit.hbs

ui: add ability to edit pki key

---

enos/enos-scenario-autopilot.hcl

This turns off undo_logs for the enos autopilot scenario pre-v1.13.
**Background**
When we perform an auto-upgrade, autopilot does the following:
1. Spins up N new nodes (where N is the size of the old cluster)
2. Demotes each old follower node 1 by 1, preventing quorum from being broken. These nodes are kept unsealed and marked as non-voters.
3. Once all of the followers have been demoted, one of the new nodes is promoted to leader.  The old leader is then demoted to follower/non-voter, at which point the auto-upgrade is complete.
**Issue**
Once raft has transferred to the new nodes on 1.12.x, the WAL will contain entries with the new raft operation, which is not supported on older versions of Vault. Since we cannot anticipate every vault version in production, this means that any old …

Turn off undo logs for enos auto-upgrade scenario pre-v1.13

---

.copywrite.hcl
.gitignore
builtin/credential/aws/pkcs7/LICENSE

This was not copied over when the this code was
copied in https://github.com/hashicorp/vault/pull/12340.
Also adds a stub for the `.copywrite.hcl` file (for when Vault is onboarded to Copywrite) and adds the `pkcs7` and `ui/node_modules` to the ignore pattern.

Add LICENSE back to pkcs7

---

changelog/17732.txt
physical/raft/fsm.go

* Don't panic on unknown raft ops
* avoid excessive logging
* track at the struct level, not the function level
* add changelog

Backport: 1.11.x: Don't panic on unknown raft ops (#17732)

---

website/content/docs/enterprise/pkcs11-provider/aws-xks.mdx

And add note about requiring the zero IV until `vault-pkcs11-provider` is released.

Update XKS docs to use AWS CLI

---

website/content/docs/auth/jwt/oidc-providers/azuread.mdx

This PR fixes the documented permission needed for the Azure 200+ group workflow in OIDC auth. I tested that the application doesn't need the `Directory.Read.All` API permission and can use the less permissive `User.Read` permission instead. Needing the `Directory.Read.All` permission was a user concern that prevented some from using this feature.

auth/oidc: fix permissions for Azure 200+ group workflow

---

changelog/18546.txt
plugins/database/mongodb/mongodb.go

When Vault deletes a user on a MongoDB replica, it always uses `WriteConcern = 'majority'` despite the setting in the connection configuration.
Results from the log without the fix using `write_concern="{\"W\": 1}"`:
```
{"t":{"$date":"2022-12-21T23:58:20.295+00:00"},"s":"I",  "c":"COMMAND",  "id":51803,   "ctx":"conn52","msg":"Slow query","attr":{"type":"command","ns":"admin.$cmd","appName":"mongosh 1.6.1","command":{"dropUser":"v-token-XXXXX-XXXXXXXXXXX-XXXXXX","writeConcern":{"w":"majority"},"lsid":{"id":{"$uuid":"503728f4-f4a7-45bc-bee5-cd9f36bf831b"}},"$clusterTime":{"clusterTime":{"$timestamp":{"t":1671667098,"i":1}},"signature":{"hash":{"$binary":{"base64":"AAAAAAAAAAAAAAAAAAAAAAAAAAA=","subType":"0"}},"keyId":0}},"$db":"admin","$readPreference":{"mode":"primaryPreferred"}},"numYiel …
```

MongoDB - Fix write_concern param

---

website/content/api-docs/secret/gcp.mdx
website/content/docs/secrets/gcp.mdx

Adds docs and api-docs coverage for GCP secrets engine service account impersonation.

secrets/gcp: add documentation for impersonated accounts feature

---

vault/policy_store.go
vault/request_handling.go

I happened to spot that the `TemplateError` type is never instantiated.
Therefore delete it, and code referencing it.

Remove unreachable code

---

ui/app/adapters/kubernetes/config.js
ui/mirage/handlers/kubernetes.js
ui/tests/integration/components/kubernetes/page/configure-test.js

Updates kubernetes/config adapter to use newly created endpoint for checking environment variables.

Kubernetes Environment Check

---

vault/logical_system_paths.go

PR #17926 already deleted the implementation of the
`generic_mount_paths` field so it needs to be removed from the declared
fields of the path too, so help and OpenAPI isn't misleading.

Remove `generic_mount_paths` field

---

changelog/18585.txt
vault/hcp_link/link.go

Vault nodes use SCADA session metadata to denote whether they are `ACTIVE`, `STANDBY`, or `PERF-STANDBY`. Providing this metadata is done by calling `UpdateMeta` on the SCADA provider. This is currently done every 5 seconds. A Vault node should only update its SCADA metadata if its status changes (i.e. leadership in the cluster has shifted).

only update SCADA metadata if status changes

---

ui/app/adapters/pki/config/import.js
ui/app/models/pki/config/import.js
ui/lib/pki/addon/components/page/pki-issuer-details.hbs
ui/lib/pki/addon/components/pki-config/import.hbs
ui/lib/pki/addon/components/pki-config/import.ts
ui/lib/pki/addon/components/pki-configure-form.hbs
ui/lib/pki/addon/components/pki-role-generate.ts
ui/lib/pki/addon/routes/overview.js
ui/tests/integration/components/pki-config/import-test.js
ui/tests/unit/adapters/pki/config/import-test.js
ui/types/ember-data/types/registries/model.d.ts
ui/types/vault/app-types.ts
ui/types/vault/models/pki/certificate/generate.d.ts
ui/types/vault/models/pki/config/import.d.ts

Allows user to configure the pki engine via the [/pki/issuers/import/bundle](https://github.com/hashicorp/vault/blob/main/website/content/api-docs/secret/pki.mdx#import-ca-certificates-and-keys) endpoint, with `pem_bundle` on the payload. 
(Issuer details view is on a different PR which is not merged at the time of the screenshot)

UI: PKI config via import

---

ui/lib/core/addon/components/form-field.hbs

While smoke testing the pki key workflow, I noticed the model name wasn't updating as the text changed in the input field.

ui: add input as event for text form field

---

vault/mount.go

Fix typo in mount.go

---

vault/logical_system_paths.go

This was accidentally duplicated in #5687.
Remove the second definition, which was shadowed by the first, and move the documentation that was part of the second to the surviving version.

Fix duplicate definition of path `sys/internal/specs/openapi`

---

website/content/docs/secrets/databases/index.mdx

This should allow users to more easily discover information on leases and how they relate to db roles/secrets.
Backporting to 1.12.x so that it is available on the website immediately.

docs: db plugin add link to lease docs

---

changelog/18598.txt
vault/activity_log.go

In https://github.com/hashicorp/vault/pull/18452 I failed to account for mount counts, which meant that when you did a CSV export in the UI, while the total was correct, if you added up all the totals for all the mounts, it fell short of the total by the exact amount from the current month data. This corrects that oversight. It would be super awesome to get some tests around all this stuff at some point but the current unit tests for this section of the code are a bit rough. I'm not sure if we want to hold up this PR for adding them, or add them at a later date.

Account for mount counts when de-duplicating current and historical month data

---

ui/app/routes/vault/cluster.js
ui/lib/kubernetes/addon/components/page/role/create-and-edit.hbs

It was observed within the kubernetes engine that the loading screen was not being shown consistently for routes that returned a promise in the model hook. The transition object `queryParamsOnly` property doesn't seem to be reliable in describing a transition where only the query params change so it was decided to check if the `from` and `to` route names are the same instead.

Loading Substate Handling Issue

---

website/content/docs/enterprise/pkcs11-provider/aws-xks.mdx
website/content/docs/enterprise/pkcs11-provider/index.mdx

Better IV random generation is supported with XKS in the latest version of the provider (0.1.3).

docs: Update PKCS#11 provider docs for XKS and RNG

---

CHANGELOG.md
changelog/changelog.tmpl

Too many newlines are stripped, which is responsible for the `FEATURES:`
heading in the current in-progress 1.13.0 changelog entry being
erroneously appended to the end of the last bullet point of the previous
`CHANGES:` section.

Fix error in changelog template

---

changelog/18351.txt
go.mod
go.sum
vault/cluster.go
vault/core.go
vault/external_tests/hcp_link/test_helpers.go
vault/hcp_link/capabilities/meta/meta.go
vault/hcp_link/internal/wrapped_hcpLink.go
vault/request_handling.go

The associated PR https://github.com/hashicorp/vault/pull/18316 expands the `meta` proto by introducing the `GetClusterStatus` RPC. This PR implements it.
The `GetClusterStatusResponse` includes the following fields:
- `ClusterID`
- `HAStatus`
- `RaftStatus`
- `StorageType`
A few new `Core` methods have been added for the purpose of de-coupling via `WrappedCoreMeta` (previously called `WrappedCoreListNamespacesMounts`):
- `ClusterID` loads and returns the atomic `Core.clusterID` value
- `HAEnabled` specifies whether high-availability mode is enabled
- `GetRaftConfiguration` exposes the Raft configuration, similar to what is provided via [/sys/storage/raft/configuration](https://developer.hashicorp.com/vault/api-docs/system/storage/raft#read-raft-configuration)
- `GetRaftAutopilotState` …

VAULT-11829: Add cluster status handler

---

website/content/api-docs/system/config-group-policy-application.mdx
website/content/docs/enterprise/namespaces.mdx
website/data/api-docs-nav-data.json

The documentation for the group policy configuration API and feature.
I'm pretty sure I covered the salient areas. There didn't seem to be any other references to policy sharing across namespaces I could find.
Feel free to let me know there actually are some other references to sharing that I missed.
The vercel currently has an older version deployed, and I'm not sure how to kick it to deploy again, but the two typos I spotted were corrected.

VAULT-12491 Add docs for group policy config

---

changelog/18629.txt
vault/activity_log.go

When viewing the `monthly` breakdown in the output, if you looked under `new_clients`:
* if you were viewing the current month only, you would see a namespace breakdown
* if you were viewing historical data only, you would see a namespace breakdown
* if you were viewing a date range that spanned both historical data as well as the current month, you'd see nothing
This PR rectifies this by showing the namespace breakdown for new clients in all 3 date range permutations, instead of only the first 2.

Add new clients into the monthly breakdown

---

website/content/docs/commands/pki/index.mdx
website/data/docs-nav-data.json

---
This starts a new section of the docs for the `vault pki` top-level command. Health check docs will come in a separate PR, this is just to get started so Kit and I don't conflict too much while writing docs.

Add vault pki command website documentation

---

builtin/logical/pki/backend_test.go
builtin/logical/pki/path_fetch_issuers.go
builtin/logical/pki/util.go
changelog/18466.txt

When using `client.Logical().JSONMergePatch(...)` with an empty issuer name, patch incorrectly reports:
> issuer name contained invalid characters
In this case, both the error in getIssuerName(...) is incorrect and patch should allow setting an empty issuer name explicitly.
---
Notably, while this also affects `vault write`, the new error message should be clearer and users can simply elide the `issuer_name` parameter (with empty value) and the the same behavior (clearing the name). However, for `vault patch` there is no equivalent and thus they have to have this bug fix.

Correctly distinguish empty issuer names in PKI

---

api/plugin_helpers.go
sdk/framework/backend.go
sdk/framework/openapi.go
sdk/framework/openapi_test.go
sdk/framework/path.go
sdk/framework/testdata/legacy.json
sdk/framework/testdata/operations.json
sdk/framework/testdata/operations_list.json
sdk/framework/testdata/responses.json
ui/app/services/path-help.js
vault/logical_system.go
vault/logical_system_paths.go
vault/logical_system_test.go

This reverts the following two commits:
- db8efac708e5385ec871be9558507eeaf54ac972 (#17926)
- 79c8f626c59ca11bb8e7f460d40b09f5e0cec76d (#18558)
____
We are reverting the default `{thing_mount_path}` in the OpenAPI paths logic due to a number of side effects introduced by this change. The detailed description of the side effects and the reasons for reverting can be found in #18560.
A few follow up PR's will address some of the other problems mentioned in #18560 and will switch the [`gen_openapi.sh`](https://github.com/hashicorp/vault/blob/334a4fb401a5a15f718418c5d3e84e5855beeb7d/scripts/gen_openapi.sh) script to use `generic_mount_paths` flag.

Revert "Add mount path into the default generated openapi.json spec (#17926)"

---

changelog/18632.txt
plugins/database/postgresql/postgresql.go
plugins/database/postgresql/postgresql_test.go

Use the existing helper function to enable parsing multiline strings in revocation statements like we do for creation statements.
fixes: https://github.com/hashicorp/vault/issues/15678

db plugin: support multiline revoke stmt in postgres

---

website/content/docs/commands/index.mdx

Vault environment variables can be set many ways. In 1.13 we can verify what environment variables have been set. 
`> vault server -dev`

docs: note that env vars must be set on the vault process and can be checked in 1.13

---

builtin/logical/pki/backend.go
builtin/logical/pki/backend_test.go
builtin/logical/pki/fields.go
builtin/logical/pki/path_root.go
builtin/logical/pki/path_tidy.go
builtin/logical/pki/storage.go
builtin/logical/pki/storage_migrations_test.go
changelog/18645.txt
website/content/api-docs/secret/pki.mdx

With the new `tidy_move_legacy_ca_bundle` option, we'll use tidy to move the legacy CA bundle from `/config/ca_bundle` to `/config/ca_bundle.bak`. This does two things:
1. Removes `ca_bundle` from the hot-path of initialization after initial migration has completed. Because this entry is seal wrapped, this may result in performance improvements.
2. Allows recovery of this value in the event of some other failure with migration.
Notably, this cannot occur during migration in the unlikely (and largely unsupported) case that the operator immediately downgrades to Vault <1.11.x. Thus, we reuse `issuer_safety_buffer`; while potentially long, tidy can always be run manually with a shorter buffer (and only this flag) to manually move the bundle if necessary.
In the event of needing to recover or …

Allow tidy to backup legacy CA bundles

---

builtin/credential/approle/path_role.go

Adding required fields where necessary and fixing a few schema types for AppRole path_role.go response schemas.
This PR is part of the ongoing work to add OpenAPI structured response support (VLT-234).

Fix AppRole / path_role response schema

---

website/content/docs/upgrading/plugins.mdx

This PR adds a note on lease and token handling during plugin upgrades and reloads.

docs/plugin: adds note on leases and tokens during upgrades

---

command/agent.go
command/agent_test.go
command/base_flags.go
command/log_flags.go
command/log_flags_test.go
command/server.go
helper/logging/logger.go
internalshared/configutil/config.go
internalshared/configutil/merge.go

Two of the configuration values related to log rotation are currently set up to expect `string`, however they should be handled as `int` (`log_rotate_bytes` and `log_rotate_max_files`). 
This PR should address this so we expect integers (or in the case of environment variables, strings which can satisfactorily be parsed to integers). 
* Adjusted `log_flags` to expect `int` for max files and max bytes
* Updated `server` and `agent`
*  Renamed updateConfig (and updateLogConfig)

VAULT-12264: Fix log rotation params which require an integer

---

website/content/docs/auth/jwt/oidc-providers/google.mdx

This PR changes the [user type](https://support.google.com/cloud/answer/10311615#user-type) recommendation in the setup documentation for the OIDC and Google workspace integration. This is in response to the discuss post at https://discuss.hashicorp.com/t/potential-security-risk-when-providing-external-access-to-oauth-app-needed-for-oidc-gsuite-backend/48466.
I've tested that using the internal user type works as expected before making this recommendation.

docs/oidc: change user type recommendation for Google workspace integration

---

go.mod
go.sum
vault/hcp_link/link.go

Our race tests caught a data race in `hcp-scada-provider` which has been fixed as part of https://github.com/hashicorp/hcp-scada-provider/pull/40. This PR pulls in these associated changes as part of `v0.2.1`. We caught a data race of our own between `HCPLinkVault.reportStatus` and `HCPLinkVault.Shutdown` with `HCPLinkVault.stopCh` once tests were no longer failing due to the `hcp-scada-provider` race. This PR also introduces a fix to account for that by creating a local copy of the stop channel while holding a read lock in `HCPLinkVault.reportStatus`.
TODO (keeping as a draft until the following is complete):

VAULT-12548: Fix data races in Link status reporting

---

ui/app/adapters/pki/issuer.js
ui/app/models/pki/issuer.js
ui/app/serializers/pki/issuer.js
ui/lib/pki/addon/components/page/pki-issuer-edit.hbs
ui/lib/pki/addon/components/page/pki-issuer-edit.ts
ui/lib/pki/addon/routes/index.js
ui/lib/pki/addon/routes/issuers/issuer/edit.js
ui/lib/pki/addon/templates/issuers/issuer/edit.hbs
ui/package.json
ui/tests/acceptance/pki/pki-engine-workflow-test.js
ui/tests/integration/components/pki/page/pki-issuer-edit-test.js
ui/types/vault/app-types.ts
ui/types/vault/models/pki/issuer.d.ts

PKI Issuer Edit

---

changelog/18684.txt
command/agent.go

Appears like this:
```
violet@violet-TX54KFJWXM vault % vault agent -config=../vault_agent.hcl
==> Note: Vault Agent is not running with the same version as Vault itself, we recommend you upgrade! Vault Agent version: 1.13.0-dev1, Vault version: 1.12.0-rc1
==> Vault Agent started! Log data will stream in below:
```

VAULT-12542 Add info encouraging users to upgrade if agent version is different to server

---

builtin/logical/pki/crl_util.go
builtin/logical/pki/path_revoke.go
builtin/logical/pki/secret_certs.go

For reviewers: step through this PR commit by commit as trying to decipher/validate this is doing the same thing will be difficult taking in all the changes in one go 
The point of this refactoring is to better isolate the code that does the final storage related to the revocation of a certificate. Many things had been mixed into a single function making it harder to implement the unified storage case than it should have been.
Items done within this refactoring:
- Move out lease specific revocation back into secret_certs.go 
- Load the certificate related to the revocation only once during the revocation process (BYOC we had at least 2 loads from storage and parsing of the certificate)
Code change/fix:
- The last commit fixes a "bug" in which for BYOC we wrote out the certificate if it …

Refactor the PKI revocation handler to prep for unified revocation

---

website/content/docs/commands/index.mdx

🧵 [Slack thread](https://hashicorp.slack.com/archives/C8DK5PR0B/p1673505578697569)
🔍 [Deploy preview](https://vault-git-docs-add-missing-env-hashicorp.vercel.app/vault/docs/commands#vault_log_level)
It was reported that the `VAULT_LOG_LEVEL` env var is missing from [the docs](https://developer.hashicorp.com/vault/docs/commands#environment-variables).  This PR adds the missing env var definition.

[Docs] Add VAULT_LOG_LEVEL to the environment var list

---

changelog/18716.txt
go.mod
go.sum

Update to the latest k8s-auth release [v0.14.1](https://github.com/hashicorp/vault-plugin-auth-kubernetes/releases/tag/v0.14.1)

auth/kubernetes: upgrade to v0.14.1

---

changelog/18629.txt
vault/activity_log.go

Reverts hashicorp/vault#18629. 
This is due to failing tests in the enterprise repository.

Revert "Add new clients into the monthly breakdown"

---

changelog/18704.txt
physical/raft/raft_autopilot.go

Panic we're trying to fix is here: https://app.circleci.com/pipelines/github/hashicorp/vault/4864/workflows/2ca6331a-2f99-4a50-92eb-2fa7575f8695/jobs/569495/parallel-runs/7
We think we ruled out all other explanations for that panic, landing on the theory that the ticker was still firing one last shot after a teardown, e.g. when we sealed.  I don't think any of the relevant code has changed in a long time, and I haven't seen this failure before, so it's presumably a very narrow race.

Speculative fix for a panic that might arise during raft teardown

---

ui/app/models/pki/issuer.js
ui/lib/pki/addon/components/page/pki-issuer-details.hbs

Adds default text and fixes link to key details page

ui: small pki issuer details cleanup

---

sdk/framework/path.go

Vault has gradually had the ability to pass query-string parameters added to GET, then DELETE, and now recently LIST requests. Update a comment which seems to date back to when no query-string parameters were used at all.

Fix a very old comment to include query-string parameters

---

physical/oci/oci_ha_test.go
physical/oci/oci_test.go
physical/s3/s3_test.go

* Ensure OCI creds are set for acc test
* Ensure AWS creds are resolvable before testing
After fixing the drift script for ENT->OSS, this appeared to only have been applied to the ENT tree. Cherry-pick it to OSS to fix the drift.

[QT-309] Ensure creds are available for OCI and S3

---

api/client.go
api/logical.go
changelog/18708.txt
command/healthcheck/healthcheck.go
command/read.go

Removing the timeout logic from raw-response functions and adding documentation comments. The following functions are affected:
- `ReadRaw`
- `ReadRawWithContext` (newly added)
- `ReadRawWithData`
- `ReadRawWithDataWithContext`
The previous logic of using `ctx, _ = c.c.withConfiguredTimeout(ctx)` could cause a potential [context leak](https://pkg.go.dev/context):
> Failing to call the CancelFunc leaks the child and its children until the parent is canceled or the timer fires. The go vet tool checks that CancelFuncs are used on all control-flow paths.
Cancelling the context would have caused more issues since the context would be cancelled before the request body is closed.
Resolves: #18658

Remove timeout logic from ReadRaw functions and add ReadRawWithContext

---

website/content/docs/agent/caching/index.mdx

- Wraps an example value for a link with backticks so it is not parsed as a Markdown link

[docs] Fixing invalid link

---

changelog/18743.txt
ui/lib/open-api-explorer/addon/components/swagger-ui.js

As mentioned in #18614, query parameters were not being passed in API explorer test requests due to a custom `requestInterceptor` which was not rebuilding the url with the query parameters.
Before
After

API Explorer Query Params

---

changelog/18663.txt
sdk/framework/backend.go
sdk/framework/openapi.go
sdk/framework/openapi_test.go
sdk/framework/path.go
vault/logical_system.go
vault/logical_system_test.go

An incremental improvement within larger context discussed in #18560.
* Following the revert in #18617, re-introduce the change from `{mountPath}` to `{<path-of-mount>_mount_path}`; this is needed, as otherwise paths from multiple plugins would clash - e.g. almost every auth method would provide a conflicting definition for `auth/{mountPath}/login`, and the last one written into the map would win.
* Move the half of the functionality that was in `sdk/framework/` to `vault/logical_system.go` with the rest; this is needed, as `sdk/framework/` gets compiled in to externally built plugins, and therefore there may be version skew between it and the Vault main code. Implementing the `generic_mount_paths` feature entirely on one side of this boundary frees us from problems caused by this.
* …

OpenAPI `generic_mount_paths` follow-up

---

changelog/18743.txt
ui/lib/open-api-explorer/addon/components/swagger-ui.js

Backport of API Explorer Query Params into release/1.12.x

---

ui/lib/pki/addon/components/page/pki-key-list.hbs
ui/tests/helpers/pki/page/pki-keys.js
ui/tests/integration/components/pki/page/pki-key-list-test.js

Updated the labels for list items to be consistent in ui.
**Before:**
**After:**

ui: VAULT-12670 Update pki list view labels for list items

---

builtin/logical/pki/backend.go
builtin/logical/pki/config_util.go
builtin/logical/pki/crl_test.go
builtin/logical/pki/crl_util.go
builtin/logical/pki/storage.go

This introduces a nasty refactor for `buildAnyCRLs` that splits it into a couple of functions that we can call for each global/local CRL variant, with different parameters and internally handling listing of the correct certificates to revoke.
Not saying this is perfect, but at least the structure is there and should be worthwhile anyways. :-) 
Also renames `localCRLConfigEntry`->`internalCRLConfigEntry` so we can reuse it entirely for unified CRLs.

Refactor CRL Building for unified CRLs

---

changelog/18752.txt
website/content/api-docs/secret/databases/rediselasticache.mdx
website/content/docs/secrets/databases/rediselasticache.mdx

* Changed username & password to access_key_id & secret_access_key since the parameter naming caused confusion. This has been reported by customers who had trouble setting up the plugin.
* Username & password are still supported for backward compatibility.
* Provided a IAM policy sample that the Vault role requires to manage users, this has also caused friction to some users.
* Various minor spelling corrections
**Question**: Should I only add the changelog when the plugin gets updated for Vault 1.13 release?
Docs
Api-Docs

* added the new redis parameter documentation

---

ui/app/styles/core/tags.scss
ui/lib/core/addon/components/secret-list-header.hbs

- Add underline to beta badge link!
- Fix colors + add bold to text to match designs
**Before:**
**After:**
_to compare here are the designs:_

UI: VAULT-12820 Fix styling for pki beta badge

---

vault/core.go
vault/hcp_link/capabilities/link_control/link_control.go
vault/hcp_link/capabilities/meta/meta.go
vault/hcp_link/capabilities/node_status/node_status.go
vault/hcp_link/link.go

The meta calls for `ListAuths` and `ListMounts` will panic when Vault is sealed. This PR introduces a change to the underlying methods for these endpoints so that an error is returned when Vault is sealed. A couple minor logging changes are also included.
Edit: It occurred to me that we should add panic recovery to all the capability endpoints to ensure that any HCP functionality does not unexpectedly cause a server to die.

Fix link meta panics

---

builtin/logical/pki/backend.go
builtin/logical/pki/crl_util.go
builtin/logical/pki/path_config_crl.go
builtin/logical/pki/path_revoke.go
builtin/logical/pki/secret_certs.go
builtin/logical/pki/storage_unified.go

OSS portion of enterprise PR:[3468](https://github.com/hashicorp/vault-enterprise/pull/3468)
Initial work to get revocations sent across multiple clusters working with the revoke by serial API to update the unified CRL.
Add a new LIST /certs/unified-revoked API returns the entry across both PR clusters, and that the second PR cluster does not return any values for the existing LIST /cert/revoked both before and after we "revoked" the certificate on the second PR cluster.

Add support for revoke by serial number to update the unified CRL

---

builtin/logical/pki/backend.go
builtin/logical/pki/ocsp.go
builtin/logical/pki/path_config_crl.go
builtin/logical/pki/storage.go
builtin/logical/pki/util.go

OSS portion of ENT PRs:[3542](https://github.com/hashicorp/vault-enterprise/pull/3542) and [3575](https://github.com/hashicorp/vault-enterprise/pull/3575)
Update the OCSP handler with new URLs for unified storage, add the ability to return responses from the local and/or the unified storage if either configuration is enabled or someone hit the /unified-ocsp/ path.
The unified-ocsp path will always prefer local storage entries if they exist.
Also add checks that none of the cross-cluster revocation features can be enabled on non-enterprise Vault versions.

Add unified storage support to OCSP handler

---

builtin/logical/pki/backend.go
builtin/logical/pki/backend_test.go
builtin/logical/pki/crl_util.go
builtin/logical/pki/path_tidy.go

This:
- Cleans up logging so its not quite as verbose,
- Adds missing count to tidy,
- Switches to `time.Since` for tidy,
- Allows tidy to remove confirmations as well (in case this wasn't done at plugin startup),
- Skips revocation requests from our current cluster, and
- Various commentary about why things were done.

More cross cluster queue tweaks

---

builtin/logical/pki/backend.go
builtin/logical/pki/backend_test.go
builtin/logical/pki/crl_util.go
builtin/logical/pki/path_config_crl.go

When we'd ordinarily write delta WALs for local CRLs, we also need to populate the cross-cluster delta WAL. This could cause revocation to appear to fail if the two clusters are disconnected, but notably regular cross-cluster revocation would also fail.
Notably, this commit also changes us to not write Delta WALs when Delta CRLs is disabled (versus previously doing it when auto rebuild is enabled in case Delta CRLs were later asked for), and instead, triggering rebuilding a complete CRL so we don't need up-to-date Delta WAL info.
---
OSS version of Enterprise https://github.com/hashicorp/vault-enterprise/pull/3577. Relies on an un-ported PR from @stevendpclark adding support for unified CRL, so will be rebased once that merges …

Write delta WAL entries for unified CRLs

---

CODEOWNERS

Replacing the CODEOWNER for docs contents.
Docs related PR review should be assigned to me until I find a new tech writer.

Replace the docs codeowner

---

changelog/18682.txt
helper/experiments/experiments.go
vault/core.go
vault/logical_system_test.go
website/content/api-docs/system/experiments.mdx

Start with alpha instead to give more time and scope for feedback.

Event system alpha experiment

---

changelog/18799.txt
plugins/database/mysql/connection_producer.go
website/content/api-docs/secret/databases/mysql-maria.mdx

The MySQL implementation supports TLS verification and auth, however, when testing against Cloud SQL it was very painful to verify the CA. This is because Cloud SQL does not add IP SANs to the certificate. The SANs available reference internal VM names which aren't easily obtainable as a user. I've added these parameters to make the engine more flexible. Although the connection url does support these, the MySQL driver stores a tls.Config and references it by name in the connection URL, so it makes sense to add these there.

secrets/mysql: Add `tls_server_name` and `tls_skip_verify` parameters

---

website/content/docs/index.mdx

🧵 [Slack thread](https://hashicorp.slack.com/archives/CQS78SFQD/p1672863055847219)
This PR adds the missing `description` front matter to the `website/content/docs/index.mdx` file.

Add the description front matter

---

builtin/logical/pki/path_config_crl.go

- It does not make sense to allow operators to enable the cross-cluster revocation features on local mounts as they will never have a corresponding mount on the other cluster, duplicating everything locally for no reason.

Deny setting cross-cluster revocation features on local mounts

---

ui/app/templates/components/pki/role-pki-edit.hbs

This PR fixes a bug [introduced](https://github.com/hashicorp/vault/pull/18229/files#diff-3596b087468b53afc2f7d781a5c3d0c1ba240fc3a3d39f74c4e3ca9da7508bac) during development for the new PKI engine. 
After: renders all field groups on role > details correctly
Before: no fields are rendered for role details

UI: Fix details view on role (old PKI)

---

website/content/api-docs/secret/kv/kv-v2.mdx

The automatic backport to 1.10.x failed. Here is a second manual attempt.

backport: fix indentation of cas field in KV API docs

---

changelog/18811.txt
vault/login_mfa.go

Addresses https://hashicorp.atlassian.net/browse/VAULT-12661
This PR is to provide the IP address of the request coming from Vault to a Duo challenge after successful authentication. This is to implement IP address restrictions for an instance of Vault. 
Currently, when a Duo challenge request is made, there is no IP address (IPv4 or v6) passed with that request, i.e., 0.0.0.0 is sent)

Provide IP Address in Duo Request

---

website/content/docs/agent/autoauth/methods/approle.mdx
website/content/docs/agent/autoauth/methods/token_file.mdx
website/data/docs-nav-data.json

To accompany https://github.com/hashicorp/vault/pull/18740
The salient page can be found here: https://vault-13p4v6q6e-hashicorp.vercel.app/vault/docs/agent/autoauth/methods/token_file

VAULT-12564 Docs for token file auth method

---

website/content/docs/secrets/pki/rotation-primitives.mdx

---
In discussion with UI team's cross-signing works, we realized we didn't have a good place to link to about finishing cross-signing of intermediates.

Document setting manual_chain after cross-signing

---

ui/lib/core/addon/components/overview-card.hbs
ui/lib/kubernetes/addon/components/page/overview.hbs
ui/lib/kubernetes/addon/components/page/overview.js
ui/lib/pki/addon/components/page/pki-overview.hbs
ui/lib/pki/addon/components/page/pki-overview.ts
ui/tests/acceptance/secrets/backend/kubernetes/overview-test.js
ui/tests/helpers/kubernetes/overview.js
ui/tests/integration/components/kubernetes/page/overview-test.js

- Update Kubernetes overview to use `OverviewCard` component. [Here are Kubernetes Overview Designs](https://www.figma.com/file/rB5gYCA95F9aKMc7I2Qx0d/Kubernetes-Secret-Engine-Handoff?node-id=1%3A719&t=gIRN29BBk24Bdjtw-0)
- Removed form element in the pki card forms and also added margin
**With Roles:**
- shows **number of roles** and **View roles** link
**Without Roles:**
- show **None** and has **Create role** link

UI: VAULT-12949 use overview card component for kubernetes overview

---

builtin/logical/pki/crl_util.go
builtin/logical/pki/storage.go

- I missed this in the original review, that we were storing the unified CRL in a cluster-local storage area (/crls/) so none of the other hosts would receive it.
- Discovered while writing unit tests, the main cluster had the unified CRL but the other clusters would return an empty response

Store the unified crl in a path that is not cluster local

---

builtin/logical/ssh/path_config_ca.go
website/content/api-docs/secret/ssh.mdx

This does two things:
- Makes the error on SSH CA generation more obvious that the key bits was unknown, versus the algorithm being unknown ("ec").
- Removes ECDSA P224 as a supported curve in the documentation. 
Resolves: #18843

Clarify key bits for ssh

---

command/format_test.go
command/login_test.go

output is defined in format_test.go as a global variable, which the login_test.go tests were unknowingly using. Since these tests execute in parallel, under the correct circumstances, they'd race to write/read from the same variable in separate tests.
Shadow to avoid the race.
---
Seen in: https://app.circleci.com/pipelines/github/hashicorp/vault/48890/workflows/b39e0bc2-8099-473e-b4fa-4a2964ebdf30/jobs/579807/steps

Shadow globally defined var to avoid race

---

builtin/logical/pki/backend_test.go
builtin/logical/pki/fields.go
builtin/logical/pki/path_tidy.go

This adds the ability to tidy cross-cluster revoked storage, removing any expired, revoked certs present.
We also fix a few bugs with missing output from tidy status here and there.

Add tidy of cross-cluster revoked storage

---

ui/lib/kubernetes/addon/components/page/configure.hbs
ui/lib/kubernetes/addon/components/page/role/create-and-edit.hbs
ui/lib/kubernetes/addon/routes/configure.js
ui/lib/kubernetes/addon/routes/roles/create.js
ui/lib/kubernetes/addon/routes/roles/role/edit.js
ui/lib/kubernetes/addon/templates/configure.hbs
ui/lib/kubernetes/addon/templates/roles/create.hbs
ui/lib/kubernetes/addon/templates/roles/role/edit.hbs
ui/tests/integration/components/kubernetes/page/configure-test.js
ui/tests/integration/components/kubernetes/page/role/create-and-edit-test.js

- Add breadcrumbs to Create + Edit Role, and Configure
- Add breadcrumbs to the respective tests

UI: VAULT-12950 Add breadcrumbs to create + edit roles and configure for Kubernetes

---

builtin/logical/pki/backend.go
builtin/logical/pki/crl_util.go
builtin/logical/pki/path_config_crl.go
builtin/logical/pki/periodic.go
builtin/logical/pki/storage.go
builtin/logical/pki/util.go

Add a periodic function that will list the local revocations and if any are missing from the unified revocation area will force a write to the unified revocation folder/remote instance.

Unified revocation migration code

---

builtin/logical/pki/backend.go
builtin/logical/pki/crl_util.go

If a BYOC revocation occurred on cluster A, while the cert was initially issued and stored on cluster B, we need to use the invalidation on the unified entry to detect this: the revocation queues only work for non-PoP, non-BYOC serial only revocations and thus this BYOC would be immediately accepted on cluster A. By checking all other incoming revocations for duplicates on a given cluster, we can ensure that unified revocation is consistent across clusters.

Allow unification of revocations on other clusters

---

command/commands.go
command/healthcheck/pki_crl_validity_period.go
command/pki_list_children_command.go
command/pki_list_intermediate_command.go
command/pki_list_intermediate_test.go
command/pki_verify_sign_command.go

Various minor nits around the new PKI commands I wanted to address. Mostly it was just formatting and consistency with the rest of the commands. :-) Plus a rename of ListChildren to ListIntermediates for consistency with the command name.

Small cleanup on pki commands for consistency

---

vault/cluster/inmem_layer.go

This adds the ability to simulate i/o timeouts on specific host names for testing purposes.

Add timeout functionality to inmem

---

builtin/logical/pki/backend_test.go
builtin/logical/pki/chain_test.go
builtin/logical/pki/ocsp_test.go
builtin/logical/pki/path_resign_crls_test.go
builtin/logical/pki/storage_migrations_test.go
builtin/logical/pki/test_helpers.go

This has been done to help diagnose PKI test failures in the future so that we get the callers in the trace's
when we fail and not just the helper's trace output. Many of our tests will repeat calls at different stages 
of the test itself so a better calling trace will be helpful.

Add t.Helper() to various PKI test helper methods

---

builtin/credential/cert/backend.go
builtin/credential/cert/backend_test.go
changelog/18885.txt

In further review with new understanding after #18244, loading configuration and CRLs within the backend's initialize function is the ideal approach: Factory construction is strictly serial, resulting in backend initialization blocking until config and CRLs are loaded. By using an InitializeFunc(...), we delay loading until after all backends are constructed (either right on startup in 1.12+, else during the initial PeriodicFunc(...) invocation on 1.11 and earlier).
We also invoke initialize automatically on test Factory construction.
Resolves: #17847
Co-authored-by: @valli0x 
---
@sgmiller I'm inclined not to backport this?

Move cert auth backend setup into initialize

---

ui/app/router.js

Before we decided to release a beta pki, this route was hidden from production environments.

ui: mount pki engine in router 

---

vault/cluster/inmem_layer.go

`make fmt` is failing on the release branches due to my recent change.

core: make fmt on inmem_layer

---

changelog/18892.txt
command/command_test.go
command/operator_rekey.go
command/operator_rekey_test.go

All the prompts for the rekey command currently assume that the `-target` flag is set to its default value of `barrier`. If the `-target=recovery` option is set, then the prompts should instead describe recovery keys. I updated the language and added some tests around recovery keys.

VAULT-12833 Update prompts for the rekey command

---

website/content/docs/partnerships.mdx
website/content/docs/plugins/index.mdx
website/content/docs/plugins/plugin-architecture.mdx
website/content/docs/plugins/plugin-development.mdx

🎟️ [Asana](https://app.asana.com/0/563192436488770/1203703363879992/f)
This PR replaces the Plugin Portal link to point the new Vault Integrations page.

Replace the Plugin Portal link to point Vault Integrations

---

changelog/18887.txt
command/commands.go
command/transit_import_key.go
command/transit_import_key_version.go
vault/cluster/inmem_layer.go

Adds transit import/import-key to bring keys into transit and transform via
the key wrapping protocol.

Transit Import Key CLI functionality

---

builtin/credential/userpass/path_login.go
changelog/18890.txt
vault/external_tests/identity/userlockouts_test.go

While testing brute forcing using enos, I noticed that unlocking "testUser" did not work as expected. 
On further investigation, I realized this was creating an entry in "core/login/lockedUsers/root/auth_userpass_2e744f4b/testuser" when it should have been "core/login/lockedUsers/root/auth_userpass_2e744f4b/testUser". The unlock user api endpoint was trying to delete the "core/login/lockedUsers/root/auth_userpass_2e744f4b/testUser" entry.
This was because of using strings.Lower in pathLoginAliasLookahead function. We call this function from request_handling.go to get the alias name from request. I tried creating multiple users with different cases like "testuser", testUser", "Testuser" and it works. Therefore, I removed this from aliasLookahead operation for userpass. 
The aliasname in …

Brute forcing unlock user bug

---

builtin/logical/pki/crl_test.go
builtin/logical/pki/test_helpers.go
sdk/helper/certutil/helpers.go

Attempt to address failures as of late within the PKI TestAutoRebuild test. This fix has run through around 4K runs of untilfail while prior to the fix, it would trigger on my laptop after a few hundred runs.
The fix is to wait for a CRL change before progressing to the next step after we change configuration. Prior to this we would be racing against the CRL reloading from the configuration change.

Address pki::TestAutoRebuild flakiness

---

command/commands.go
command/main.go
command/pki_health_check_test.go

When running `initCommands(...)` from multiple tests, they can
race, causing a panic. Test callers needing to set formatting
information must use `RunCustom(...)` instead of directly invoking the
test backend directly. When using `t.Parallel(...)` in these top-level
tests, we thus could race.
This removes the `Commands` global variable, making it a local variable
instead as nothing else appears to use it. We'll update Enterprise to
add in the Enterprise-specific commands to the existing list.
---
Also reverts #18751 to get back some parallelism.
n.b.: because the commands contain embedded copies of `UI`, it isn't possible to put these in a [sync group](https://github.com/hashicorp/vault/pull/18751#issuecomment-1387184409) as each CLI invocation will have different references to the UI. …

Fix command.RunCustom(...) correctly

---

builtin/credential/cert/backend_test.go
helper/testhelpers/testhelpers.go
http/forwarding_bench_test.go
http/forwarding_test.go
vault/external_tests/api/feature_flag_ext_test.go
vault/external_tests/pprof/pprof_test.go
vault/external_tests/raft/raft_autopilot_test.go
vault/external_tests/raft/raft_test.go
vault/external_tests/sealmigration/testshared.go
vault/testing.go

This rather trivial PR was factored out from a larger one to make that one less noisy.  It's not changing much, other than making the TLSConfig for a test cluster node be cloned in some cases where it wasn't before.

TestClusterCore's TLSConfig becomes a method and does a Clone

---

changelog/18859.txt
http/sys_wrapping_test.go
vault/request_handling.go

Requests to wrapping APIs will respond with a 500 status code if a token is not provided. This PR ensures that Vault properly responds with a 403.
Fixes https://github.com/hashicorp/vault/issues/18852

return 403 for wrapping requests when no token provided

---

changelog/18923.txt
vault/login_mfa.go

Addresses: https://github.com/hashicorp/vault/issues/18849

prevent panic on mfa enforcement delete after a namespace is deleted

---

changelog/18934.txt
scripts/gen_openapi.sh

`gen_openapi.sh` is a script used to generate `OpenAPI` schema for all built-in plugins. The resultant `openapi.json` schema is then used for client library generation.
This pull request fixes a couple issues:
- The script will now ignore plugins marked as "Removed" (these were causing script failures)
- The will now generate schema with `generic_mount_paths` set to true, inserting `/{thing_mount_path}/` elements into the paths for certain plugins. This was the default behavior before https://github.com/hashicorp/vault/pull/18617. We are now re-enabling the behavior but specifically for the schemas generated using this script.

Change gen_openapi.sh to generate schema with generic mount paths

---

changelog/18935.txt
sdk/framework/openapi.go
vault/logical_system.go

For `generic_mount_path=true` passed to the openapi endpoint, the following changes will be applied in the `openapi.json` for each _mount_path parameter. These changes are needed for proper library code generation.
```diff
{
"name": "alicloud_mount_path",
"description": "Path that the backend was mounted at",
"in": "path",
"schema": {
"type": "string",
++          "default": "alicloud"
},
--        "required": true
}
"post": {
++        "operationId": "postAuthAlicloudLogin",
--        "operationId": "postAuthAlicloud_mount_pathLogin",
```

openapi: Add default values to the thing_mount_path parameters

---

builtin/logical/ssh/backend_test.go
command/auth_tune_test.go
command/plugin_deregister_test.go
command/plugin_info_test.go
command/plugin_register_test.go
command/plugin_reload_test.go
command/secrets_tune_test.go
helper/testhelpers/corehelpers/corehelpers.go
helper/testhelpers/logical/testing.go
http/logical_test.go
http/sys_auth_test.go
http/sys_generate_root_test.go
http/sys_metrics_test.go
http/sys_mount_test.go
vault/audit_test.go
vault/auth_test.go
vault/cluster_test.go
vault/core_test.go
vault/external_plugin_test.go
vault/external_tests/identity/login_mfa_totp_test.go
vault/external_tests/metrics/core_metrics_int_test.go
vault/external_tests/raft/raft_test.go
vault/logical_system_integ_test.go
vault/logical_system_test.go
vault/mount_test.go
vault/testing.go

Move some test helper stuff from the vault package to a new helper/testhelpers/corehelpers package.  Consolidate on a single "noop audit" implementation.

Vault test cluster helper refactorings, mostly audit related

---

builtin/logical/pki/crl_test.go
builtin/logical/pki/test_helpers.go

We had two separate helpers that were very close, one in ENT, so unify them here in OSS using the same backing implementation

Refactor an ENT test helper back to OSS to wait for updated CRLs within PKI tests

---

builtin/logical/ssh/backend.go
builtin/logical/ssh/backend_test.go
builtin/logical/ssh/path_cleanup_dynamic_host_keys.go
changelog/18939.txt
website/content/api-docs/secret/ssh.mdx

This adds a new endpoint, `tidy/dynamic-keys` that removes any stale host keys still present on the mount. This does not clean up any pending dynamic key leases and will not remove these keys from systems with authorized hosts entries created by Vault.
---
Follow up to #18874.

Allow cleanup ssh dynamic keys host keys

---

website/content/api-docs/secret/azure.mdx
website/content/docs/secrets/azure.mdx

This PR updates the Azure secrets engine docs to recommend permissions that are minimally permissive. The current list provides API permissions that aren't needed. I've tested that these permissions work using the Azure secrets engine (see related PR at https://github.com/hashicorp/vault-plugin-secrets-azure/pull/125).
Additionally, this removes documentation for the `use_microsoft_graph_api` parameter. We removed the parameter and fully switch over to MS graph in Vault 1.12. With versioned docs in place, I think it's safe to remove this now.

secrets/azure: changes permission recommendation to be minimally permissive

---

builtin/credential/cert/backend.go
builtin/credential/cert/path_crls.go
builtin/credential/cert/path_crls_test.go
builtin/credential/cert/path_login.go
changelog/18945.txt

- Discovered by CircleCI the pathLogin, pathLoginRenew paths access and reload the b.crls member variable without a lock.
- Also discovered that pathLoginResolveRole never populated an empty b.crls before usage within b.verifyCredentials
```
=== RUN   TestCRLFetch
==================
Write at 0x00c0031af8c0 by goroutine 12215:
github.com/hashicorp/vault/builtin/credential/cert.(*backend).populateCRLs()
/home/circleci/go/src/github.com/hashicorp/vault/builtin/credential/cert/path_crls.go:85 +0xa5
github.com/hashicorp/vault/builtin/credential/cert.(*backend).pathLogin()
/home/circleci/go/src/github.com/hashicorp/vault/builtin/credential/cert/path_login.go:95 +0x145
github.com/hashicorp/vault/builtin/credential/cert.TestCRLFetch() …
```

Fix race accessing b.crls within cert auth

---

ui/app/models/pki-ca-certificate-sign.js
ui/app/models/pki/action.js
ui/app/models/pki/issuer.js
ui/app/models/pki/role.js
ui/app/models/pki/urls.js
ui/tests/integration/components/pki/page/pki-issuer-edit-test.js

- update the subText for OU across all areas
- update crlDistributionPoints, ocspServers, and ou to stringArray based on what was filed in the bug bash
stringArray Attribute:
[crlDistributionPoints](https://developer.hashicorp.com/vault/api-docs/secret/pki#crl_distribution_points)
[ocspServers](https://developer.hashicorp.com/vault/api-docs/secret/pki#ocsp_servers-1)
[ou, organization, country, city, state, street, postal code](https://developer.hashicorp.com/vault/api-docs/secret/pki#ou)
Fields Updated in **Create Role**:
Fields Updated in **Update Issuer**
Fields Update in "Generate Root"

UI: VAULT-13044 pki cleanup attributes

---

vault/logical_system.go

The path parameters must be `"required": true` per [OpenAPI specification](https://swagger.io/docs/specification/describing-parameters/#path-parameters).

openapi: Ensure mount_path parameters are marked as required

---

ui/app/models/database/connection.js
ui/app/models/oidc/provider.js
ui/app/models/pki/role.js

Some additional docLinks that needed to be fix alongside [this PR](https://github.com/hashicorp/vault/pull/18641/files).
The below video shows the before and after. I searched all the models for `docLinks` and `learnLinks` (just in case). Fixed and confirmed in the UI the ones I found missing `/vault` at the beginning of the url.
https://user-images.githubusercontent.com/6618863/216445943-b20e4e07-bbd6-44f8-93a0-6450be14aaad.mov

Fix docLinks in models

---

.github/workflows/enos-test-ui.yml
.github/workflows/test-enos-scenario-ui.yml
enos/README.md
enos/enos-modules.hcl
enos/enos-scenario-autopilot.hcl
enos/enos-scenario-ui.hcl
enos/enos-variables.hcl
enos/modules/vault_test_ui/main.tf
enos/modules/vault_test_ui/outputs.tf
enos/modules/vault_test_ui/scripts/test_ui.sh
enos/modules/vault_test_ui/variables.tf
ui/scripts/enos-test-ember.js

Added a new enos scenario that can run the UI tests. The scenario supports two variants: edition (oss or ent) and backend (raft or consul). Tests can be run in a completely automated manner or semi-automated when trouble shooting or adding new UI tests. The details of how to run the scenario and all the supported options is documented in the enos README at: ./enos/README.md.

[QT-304] Add enos ui scenario

---

ui/lib/core/addon/components/form-field.hbs

The additional `has-margin-bottom-m` was added in an attempt to fix an issue with multiple text files ([see PR and row here](https://github.com/hashicorp/vault/pull/18458/files#diff-d10b01999845cdbb2bb7704e40fc343061f6d2a35d0269fc97fa684d0a2de66aR307)). While I couldn't find the original issue (confirmed with Claire), it is causing all regular text inputs to have a margin medium which added too much spacing between form fields. 
If the original area/issue that is found, we can add a margin for that specific use case. In the meantime, I'm playing it safe and reverting so it doesn't impact the other fields used throughout the application.
**Before:**
**After fix:**

Revert has-bottom-margin-m on form-field

---

builtin/logical/pki/cert_util.go
changelog/18984.txt

When generating a leaf which exceeds the CA's validity period, Vault's error message was confusing as the leaf would use the server's time zone, but the CA's notAfter date would use UTC. This could cause user confusion as the leaf's expiry might look before the latter, due to using different time zones. E.g.:
> cannot satisfy request, as TTL would result in notAfter
> 2023-03-06T16:41:09.757694-08:00 that is beyond the expiration of
> the CA certificate at 2023-03-07T00:29:52Z
Consistently use UTC for this instead.
----
Reported by @hellobontempo, thanks! :-)

Use UTC for leaf exceeding CA's notAfter

---

ui/lib/pki/addon/routes/application.js
ui/lib/pki/addon/routes/overview.js
ui/lib/pki/addon/routes/roles/create.js
ui/lib/pki/addon/routes/roles/index.js
ui/lib/pki/addon/routes/roles/role/details.js
ui/lib/pki/addon/routes/roles/role/edit.js

OpenAPI attributes were not consistently being populated on the pki/role model. Specifically, if you were to refresh on the overview page, navigate to roles and then create a role you would notice missing check boxes in the _Domain handling_ section.
I'm not sure why exactly, but since the overview route was doing a query for roles and the call to `getNewModel` was happening in the roles routes, for whatever reason Ember was not using the newly registered model with the OpenAPI attributes. Since the `getNewModel` method from the `pathHelp` service only needs to be called once in order to re-register the new model with the properties from OpenAPI, I moved it to the application route of the engine to ensure it gets called before any calls to the store for the `pki/role` model happen. After …

OpenAPI attributes not populating on pki/role model

---

website/content/docs/faq/ssct.mdx

the example syntax used for `allow_forwarding_via_token` marks the option as an array when it does not need to be, this updates the format on the page to be a code block and removes the square braces
https://vault-kjcs96scp-hashicorp.vercel.app/vault/docs/faq/ssct#q-is-there-anything-else-i-need-to-consider-to-achieve-consistency-besides-upgrading-to-vault-1-10
https://vault-kjcs96scp-hashicorp.vercel.app/vault/docs/faq/ssct#q-is-there-a-new-configuration-that-this-feature-introduces

docs allow_forwarding_via_token syntax update

---

ui/lib/core/addon/components/text-file.hbs

- Update the `text-file` component to use ember's built in `Textarea` form field to avoid weird bugs. See ember doc [here](https://guides.emberjs.com/release/components/built-in-components/)
Before: 
After:

UI: VAULT-13136 Update textfile to use native ember Textarea

---

builtin/logical/pki/crl_util.go
builtin/logical/pki/path_fetch.go
builtin/logical/pki/path_ocsp.go
builtin/logical/pki/test_helpers.go

- If the crl configuration option unified_crl_on_existing_paths is set to true along with the unified_crl feature, provide the unified crl on the existing CRL paths.
- Added some test helpers to help debugging, they are being used by the ENT test that validates this feature.

Use the unified CRL on local CRL paths if UnifiedCRLOnExistingPaths is set

---

website/content/api-docs/secret/pki.mdx
website/content/docs/secrets/pki/considerations.mdx

This adds notes about how features behave on clusters of various sizes.  Also reorganizes the doc sections to order more naturally and fix the note about CRL naming.

Add notes on cross cluster CRLs

---

ui/app/adapters/pki/action.js
ui/app/models/pki/issuer.js
ui/lib/pki/addon/components/pki-issuer-cross-sign.hbs
ui/lib/pki/addon/components/pki-issuer-cross-sign.js
ui/lib/pki/addon/templates/issuers/index.hbs
ui/lib/pki/addon/templates/issuers/issuer/cross-sign.hbs
ui/tests/unit/serializers/pki/action-test.js
ui/types/vault/models/pki/issuer.d.ts

If an issuer is nameless we want to fallback and reference the `issuerId` - this PR adds a getter to fallback on the id consistently throughout the PKI engine. This fixes a bug where cross-signing fails if attempted from a nameless parent issuer.

UI: add issuerRef getter in case issuer is nameless

---

website/content/docs/enterprise/pkcs11-provider/aws-xks.mdx

The TLS settings should not need to be modified as xks-proxy should generate the certificate and key itself for listening.

docs: Remove XKS proxy TLS setup note

---

helper/testhelpers/pluginhelpers/pluginhelpers.go
vault/external_plugin_test.go
vault/testing.go

- move compilePlugin to helper package
- make NewTestCluster use compilePlugin
We are making these changes so that we can write tests that exercise regular plugin workflows (logins, renewals, revocations).

test/plugin: refactor compilePlugin for reuse

---

ui/lib/pki/addon/components/page/pki-role-details.ts
ui/lib/pki/addon/components/pki-role-form.js
ui/lib/pki/addon/routes/certificates/certificate/details.js
ui/lib/pki/addon/routes/configuration/create.js
ui/lib/pki/addon/routes/error.js
ui/lib/pki/addon/routes/issuers/generate-root.js
ui/lib/pki/addon/routes/issuers/index.js
ui/lib/pki/addon/routes/issuers/issuer/index.js
ui/lib/pki/addon/routes/issuers/issuer/sign.js
ui/lib/pki/addon/routes/keys/index.js
ui/lib/pki/addon/routes/roles/create.js
ui/lib/pki/addon/routes/roles/role/details.js
ui/lib/pki/addon/routes/roles/role/edit.js
ui/lib/pki/addon/routes/roles/role/generate.js
ui/lib/pki/addon/routes/roles/role/sign.js

While debugging the issue in #18993 we were discussing that in order to get to the pki engine route the `secret-engine` model must be loaded so we will always have the mount path value which is necessary to really do anything within the pki secret engine. This PR cleans up any remaining instances of a hardcoded mount path value.

PKI cleanup hardcoded mount path value 

---

changelog/18916.txt
vault/activity_log.go
vault/activity_log_test.go
vault/activity_log_util_common.go

There are two problems this PR fixes:
1. `processClientRecord` creates maps that key by mount accessor, but we later assume that the key is a mount path in `transformActivityLogMounts` 
2. Sometimes a deleted/empty mount record is thrown out (`precomputedQueryWorker`), while other times we keep it (`transformMonthBreakdowns `). This change means that we will always keep the mount record.
Closes #18814, #18812

VAULT-13061: Fix mount path discrepancy in activity log

---

api/lifetime_watcher.go
builtin/credential/okta/backend.go
builtin/credential/okta/cli.go
command/agent/sink/sink.go
command/server.go
physical/zookeeper/zookeeper.go
tools/semgrep/ci/loop-time-after.yml
vault/ha.go
vault/login_mfa.go
vault/raft.go

This PR removes instances where <-time.After is used in select statements within for loops, as this is a potential resource leak. However, the impact of the resource leak is minimal in our case because the loop is exited in the other condition of the select statement, so there won't be a buildup of un-fired timers. 
I also added a semgrep rule to catch these cases in the future.

VAULT-8436 remove <-time.After statements in for loops

---

ui/lib/pki/addon/components/pki-generate-root.hbs

- Remove form validation onChange
- The form will still validate `onSubmit` since this already implemented in the `pki-generate-root` component file

VAULT-13192 only validate form on submit instead of onChange

---

.github/workflows/test-enos-scenario-ui.yml
enos/enos-scenario-ui.hcl

After testing triggering the UI Tests GitHub Action manually, I noticed two problems:
* Chrome was being installed when the action was run in the `vault` repo, with the custom runner, which was not necessary
* The `ui_test_filter` was not properly set to `!enterprise` in the case when no filter was provided to the workflow.
This PR fixes these two issues, by:
* Changing the criteria for installing Chrome to rather check what repository the workflow is running in. Chrome should only be installed in the `vault-enterprise` repository.
* Updating the local used to set the ui test filter in the scenario to check if the filter is an empty string and if so adding the `!enterprise` filter.

[QT-304] Ensure Chrome is only installed for vault-enterprise UI Test workflows

---

changelog/19005.txt
go.mod
go.sum

This PR updates vault-plugin-auth-alicloud to [v0.14.0](https://github.com/hashicorp/vault-plugin-auth-alicloud/releases/tag/v0.14.0)
Steps:
```
go get github.com/hashicorp/vault-plugin-auth-alicloud@v0.14.0
go mod tidy
```

fix: upgrade vault-plugin-auth-alicloud to v0.14.0

---

website/content/docs/platform/k8s/injector/annotations.mdx
website/content/docs/platform/k8s/injector/index.mdx

Docs updates to go along with the [v1.2.0 release](https://github.com/hashicorp/vault-k8s/releases/tag/v1.2.0) (along with https://github.com/hashicorp/vault/pull/18681).

docs/vault-k8s: 1.2.0 release updates

---

go.mod
go.sum

This PR updates vault-plugin-secrets-mongodbatlas to [v0.9.0](https://github.com/hashicorp/vault-plugin-secrets-mongodbatlas/releases/tag/v0.9.0)
Steps:
```
go get github.com/hashicorp/vault-plugin-secrets-mongodbatlas@v0.9.0
go mod tidy
```

fix: upgrade vault-plugin-secrets-mongodbatlas to v0.9.0

---

.github/workflows/godoc-test-checker.yml
.gitignore
Makefile
go.mod
go.sum
tools/godoctests/main.go
tools/godoctests/pkg/analyzer/analyzer.go
tools/godoctests/pkg/analyzer/analyzer_test.go
tools/godoctests/pkg/analyzer/testdata/funcs.go
tools/tools.go
vault/activity_log_util_common_test.go

This is an example of how to do checking for godocs for tests. Unfortunately, I couldn't find a pre-built linter that would check for test functions having comments (they would only check exported functions, and test functions aren't exported).
Example usage when run locally:
```sh
$ make vet-godoctests
vault/activity_log_util_common_test.go:13:1: Test TestSomething is missing go-doc
make: *** [vet-godoctests] Error 1
``` 
There will also be a CI check that will fail if a new test doesn't have a go doc. This is only run for PRs into main.

VAULT-13169 Require go docs for all new test functions

---

go.mod
go.sum

This PR updates vault-plugin-database-snowflake to [v0.7.0](https://github.com/hashicorp/vault-plugin-database-snowflake/releases/tag/v0.7.0)
Steps:
```
go get github.com/hashicorp/vault-plugin-database-snowflake@v0.7.0
go mod tidy
```

fix: upgrade vault-plugin-database-snowflake to v0.7.0

---

ui/app/adapters/pki/role.js
ui/tests/integration/components/pki/pki-role-form-test.js
ui/tests/unit/adapters/pki/role-test.js

Solves problem where the backend was hardcoded when you edited a pki role. 
**Update**: 
- added test coverage to confirm the model is being unloaded or updated correctly. 
- added test coverage to check that the correct endpoint is being hit on updateRecord when the backend is something other than "pki". 
- In future PR will add test coverage for the other custom adapter methods used in pki-role adapter.

Add updateRecord to role adapter

---

website/content/api-docs/secret/pki.mdx
website/content/docs/secrets/pki/considerations.mdx

Talks more about what cross-cluster revocation is, and docs a missing tidy parameter.

Document pki cross cluster behavior

---

ui/app/adapters/pki/role.js
ui/types/vault/adapters/pki/role.d.ts

Went to write tests for the custom adapter methods in the pki/role adpater to find that they were not being used anywhere. Did a search for the methods and because they're custom they would have to specifically be called. Didn't find their use anywhere. It appears that these were written two months ago and then—my guess—[written elsewhere in the following adapters](https://github.com/hashicorp/vault/tree/main/ui/app/models/pki/certificate):
-pki/certificate/sign
-pki/certificate/generate
-pki/certificate/base

Remove duplicate adapter methods

---

website/content/docs/secrets/pki/considerations.mdx

Luckily this is only on the 1.13 version of the docs and isn't yet out.

Fix documentation on CRL fixed version

---

go.mod
go.sum

This PR updates vault-plugin-auth-gcp to [v0.15.0](https://github.com/hashicorp/vault-plugin-auth-gcp/releases/tag/v0.15.0)
Steps:
```
go get github.com/hashicorp/vault-plugin-auth-gcp@v0.15.0
go mod tidy
```
No changelog since from what I can see the only changes are dependency upgrades and no improvements or new features.

upgrade vault-plugin-auth-gcp to v0.15.0

---

changelog/19036.txt
ui/app/mixins/cluster-route.js
ui/tests/acceptance/wrapped-token-test.js

As reported in #17355, visiting the logout endpoint with a `wrapped_token` was not automatically logging in if the user was already logged out. The transition to the logout route was not being caught by the `EXCLUDED_REDIRECT_URLS` whitelist because of the query parameter. After the token was unwrapped and auth was successful, the user would be redirected back to logout and then the auth route where the token would again be unwrapped which would fail the second time.
I also discovered while testing this that the wrapped token can be passed to the auth route and it will automatically log in as well.

Wrapped token login bug

---

go.mod
go.sum

This PR updates vault-plugin-database-redis-elasticache to [v0.13.0](https://github.com/hashicorp/vault-plugin-database-elasticsearch/releases/tag/v0.13.0)
Steps:
```
go get github.com/hashicorp/vault-plugin-database-elasticsearch@v0.13.0
go mod tidy
```
No changelog since only changes are dependency updates, test fixes & compliance headers

upgrade vault-plugin-database-elasticsearch to v0.13.0

---

go.mod
go.sum

This PR updates vault-plugin-auth-kerberos to [v0.9.0](https://github.com/hashicorp/vault-plugin-auth-kerberos/releases/tag/v0.9.0)
Steps:
```
go get github.com/hashicorp/vault-plugin-auth-kerberos@v0.9.0
go mod tidy
```

fix: upgrade vault-plugin-auth-kerberos to v0.9.0

---

changelog/19063.txt
go.mod
go.sum

For the latest release of vault-plugin-secrets-gcpkms: https://github.com/hashicorp/vault-plugin-secrets-gcpkms/blob/main/CHANGELOG.md#v0140

secrets/gcpkms: upgrade to v0.14.0

---

changelog/19056.txt
go.mod
go.sum

This PR updates vault-plugin-secrets-kv to [v0.14.0](https://github.com/hashicorp/vault-plugin-secrets-kv/releases/tag/v0.14.0)
Steps:
```
go get github.com/hashicorp/vault-plugin-secrets-kv@v0.14.0
go mod tidy
```

update vault-plugin-secrets-kv to v0.14.0

---

website/content/docs/upgrading/upgrade-to-1.12.x.mdx

Add to the known issues for the 1.12.x upgrading guide about the discovered regression within the PKI OCSP GET handler in 1.12.3.

Document OCSP GET known issue

---

builtin/logical/pki/path_ocsp.go
builtin/logical/pki/path_ocsp_test.go

- The fix within #18938 was incorrect and has caused a regression in OCSP GET request handling, as now the tests and program are double URL encoding the base64 `+` character when using Vault are becoming space characters within the handler and failing base64 decoding.

Revert URL encoding OCSP GET fix #18938

---

ui/app/models/pki/issuer.js
ui/lib/pki/addon/components/page/pki-issuer-details.hbs
ui/tests/acceptance/pki/pki-engine-workflow-test.js

- Add issuer id as a field and copyable

UI: VAULT-13135 Add copyable issuer id row to issuer details

---

ui/app/components/mount-backend-form.js
ui/tests/integration/components/mount-backend-form-test.js

When the `mount-backend-form` component was glimmerized there was a reference to `this.mountType` that was not updated to `this.args.mountType` which caused the success message for mounting a secrets engine to display as _auth method_.
Now the correct type is referenced

Backend mount success message copy fix

---

changelog/19071.txt
ui/app/components/auth-jwt.js
ui/tests/unit/components/auth-jwt-test.js

Resolves Issue #17584 
In a browser fullscreen mode, there was a race condition where the new tab triggered close before the OIDC flow was finished. 
**Behavior before**
Locally we increased the timeout, which is a bad experience but shows that the core issue was the close being triggered too soon:
With the fix, we manually call close window after the OIDC succeeds, or when canceling login:

UI: Fix OIDC login in fullscreen

---

ui/lib/pki/addon/routes/overview.js
ui/lib/pki/addon/templates/configuration/index.hbs

Small change to clarify UI discrepancy between beta and regular PKI 
<hr>

UI: clarify beta configuration info banner

---

changelog/19096.txt
go.mod
go.sum

This PR updates vault-plugin-secrets-azure to [v0.15.0](https://github.com/hashicorp/vault-plugin-secrets-azure/releases/tag/v0.15.0).
Steps:
```
go get github.com/hashicorp/vault-plugin-secrets-azure@v0.15.0
go mod tidy
```

upgrade vault-plugin-secrets-azure to v0.15.0

---

.github/workflows/test-acc-dockeronly-nightly.yml
.github/workflows/test-run-acc-tests-for-path.yml

Previously, we had made the choice to move the VAULT_ACC env var declaration to the caller workflow as it didn't make sense to have the variable set for the more generically go-test workflow.
Upon reading some documentation today for an unrelated issue, I found [the following information](https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations):
> Any environment variables set in an env context defined at the workflow level in the caller workflow are not propagated to the called workflow.
This change also renames the called workflow file so as to indicate that it is to be used for acceptance tests exclusively.

[QT-481] Move env var declaration to called workflow

---

ui/app/models/kubernetes/config.js
ui/lib/kubernetes/addon/components/page/configure.hbs
ui/lib/kubernetes/addon/components/page/configure.js
ui/tests/integration/components/kubernetes/page/configure-test.js

It was discovered that when selecting _Manual configuration_ and submitting an empty form, if the necessary environment variables were previously set it would use those for an inferred configuration. Since we have an option for that in the UI we want to be explicit in how the configuration is created and have a clear separation between the two. For those reasons, validation was added to the form to required the `kubernetes_host` field.

Kubernetes config form validation 

---

command/pki_health_check.go
command/pki_issue_intermediate.go
command/pki_list_intermediate_command.go
command/pki_verify_sign_command.go

- Match the existing vault kv capitalization scheme for synopsis help of each sub-command.
- A few small tweaks to the messages text in a few cases
```
Subcommands:
health-check          Check a PKI Secrets Engine mount's health and operational status
issue                 Given a parent certificate, and a list of generation parameters, creates an issuer on a specified mount
list-intermediates    Determine which of a list of certificates, were issued by a given parent certificate
verify-sign           Check whether one certificate validates another specified certificate
```

Stop using title capitalization for vault pki synoposis

---

changelog/19098.txt
go.mod
go.sum

This PR updates vault-plugin-auth-cf to [v0.14.0](https://github.com/hashicorp/vault-plugin-auth-cf/releases/tag/v0.14.0).
Steps:
go get github.com/hashicorp/vault-plugin-auth-cf@v0.14.0
go mod tidy

auth/cf: update plugin to v0.14.0

---

command/operator_diagnose.go

docker dependency should no longer be included in the binary

update diagnose command to no longer require docker dependency

---

ui/lib/kubernetes/addon/components/page/role/create-and-edit.hbs
ui/lib/kubernetes/addon/components/page/role/create-and-edit.js
ui/tests/integration/components/kubernetes/page/role/create-and-edit-test.js

- Add inline form error and `MessageError` block for create/edit role form
Example 1:
Example 2:

UI: VAULT-13419 Remove flash message for form errors and use MessageError instead

---

changelog/19100.txt
go.mod
go.sum

[v1.4.8](https://github.com/hashicorp/go-plugin/releases/tag/v1.4.8)
BUG FIXES:
Fix windows build: [https://github.com/hashicorp/go-plugin/pull/227]
[v1.4.7](https://github.com/hashicorp/go-plugin/releases/tag/v1.4.7)
ENHANCEMENTS:
More detailed error message on plugin start failure: [https://github.com/hashicorp/go-plugin/pull/223]
[v1.4.6](https://github.com/hashicorp/go-plugin/releases/tag/v1.4.6)
BUG FIXES:
server: Prevent gRPC broker goroutine leak when using GRPCServer type GracefulStop() or Stop() methods [https://github.com/hashicorp/go-plugin/pull/220]

Bump go-plugin version 1.4.5->1.4.8

---

builtin/logical/ssh/path_roles.go
changelog/17894.txt
ui/app/models/role-ssh.js

* Adds `default` to allowed values for algorithm_signer to ssh plugin API introduced in #10299

Add default to allowed values for algorithm_signer

---

go.mod
go.sum

This PR updates vault-plugin-secrets-openldap to [v0.10.0](https://github.com/hashicorp/vault-plugin-secrets-openldap/releases/tag/v0.10.0). I didn't add a changelog because there aren't notable changes to call out here.
Steps:
```
go get github.com/hashicorp/vault-plugin-secrets-openldap@v0.10.0
go mod tidy
```

upgrade vault-plugin-secrets-openldap to v0.10.0

---

vault/logical_system.go
vault/policy_store.go
vault/policy_store_test.go

After some discussion internally, we'd prefer not to add new unauthenticated endpoints, especially as this one potentially leaks information about the API surface of Vault.
EDIT: See comment below

Make experiments API authenticated

---

changelog/19111.txt
go.mod
go.sum

This PR updates vault-plugin-secrets-mongodbatlas to [v0.9.1](https://github.com/hashicorp/vault-plugin-secrets-mongodbatlas/releases/tag/v0.9.1)
Steps:
```
go get github.com/hashicorp/vault-plugin-secrets-mongodbatlas@v0.9.1
go mod tidy
```

fix: upgrade vault-plugin-secrets-mongodbatlas to v0.9.1

---

go.mod
go.sum

This PR updates vault-plugin-database-redis to [v0.2.0](https://github.com/hashicorp/vault-plugin-database-redis/releases/tag/v0.2.0).
Steps:
```
go get github.com/hashicorp/vault-plugin-database-redis@v0.2.0
go mod tidy
```

upgrade vault-plugin-database-redis to v0.2.0

---

ui/app/models/kubernetes/config.js

In #19097 we added form validation to require `kubernetes_host` in the manual configuration workflow. The description for the field is now misleading since it can't default to the environment variables if the field is required to submit the form. That part of the copy has been removed.

Kubernetes host form field description change

---

changelog/19084.txt
go.mod
go.sum

This PR updates vault-plugin-secrets-kubernetes to [v0.3.0](https://github.com/hashicorp/vault-plugin-secrets-kubernetes/releases/tag/v0.3.0).
Steps:
```
go get github.com/hashicorp/vault-plugin-secrets-kubernetes@v0.3.0
go mod tidy
```

fix: upgrade vault-plugin-secrets-kubernetes to v0.3.0

---

go.mod
go.sum

This PR upgrades vault-plugin-secrets-alicloud to [v0.14.0](https://github.com/hashicorp/vault-plugin-secrets-alicloud/releases/tag/v0.14.0).
Steps:
```
go get github.com/hashicorp/vault-plugin-secrets-alicloud@v0.14.0
go mod tidy
```

upgrade vault-plugin-secrets-alicloud to v0.14.0

---

go.mod
go.sum

This PR upgrades vault-plugin-secrets-alicloud to [v0.14.1](https://github.com/hashicorp/vault-plugin-secrets-alicloud/releases/tag/v0.14.1).
Steps:
```
go get github.com/hashicorp/vault-plugin-secrets-alicloud@v0.14.1
go mod tidy
```

upgrade vault-plugin-secrets-alicloud to v0.14.1

---

ui/app/models/kubernetes/config.js
ui/tests/integration/components/kubernetes/page/configure-test.js

When validation was added to the manual config form to require `kubernetes_host`, this impacted the inferred config workflow and prevented it from saving. The validator was updated to only require `kubernetes_host` if `disable_local_ca_jwt` is `true`.

Kubernetes config validation update

---

http/events.go
http/handler.go
http/logical.go

Moves handling logic a bit further down the stack to allow us to dynamically hijack requests based on the context's namespace. Should be pretty close to a noop unless the experiment is enabled.

events: Allow subscribing to events in namespaces

---

changelog/19135.txt
ui/app/templates/components/transform-role-edit.hbs

Before this change, clicking "Cancel" from the create transform role page would result in this error: 
After the change, clicking Cancel from both the edit and create screens properly redirects to the show or list pages, respectively.

UI: Fix cancel button on role transform form

---

http/events.go
http/events_test.go
http/logical.go
vault/request_handling.go

This checks the request against the `read` permission for `sys/events/subscribe/{eventType}` on the initial subscribe.
Future work includes moving this to its own verb (`subscribe`) and periodically rechecking the request.
Tested locally by minting a token with the wrong permissions and verifying that they are rejected as expected, and that they work if the policy is adjusted to `sys/event/subscribe/*` (or the specific topic name) with `read` permissions.
I had to change the `core.checkToken()` to be publicly accessible, as it seems like the easiest way to check the token on the `logical.Request` against all relevant policies, but without going into all of the complex logic further in `handleLogical()`.

events: Check token and ACLs on request

---

website/content/api-docs/secret/pki.mdx

PKI Secret Engine documentation for auto-tidy(https://developer.hashicorp.com/vault/api-docs/secret/pki#configure-automatic-tidy) has a parameter interval_duration(https://developer.hashicorp.com/vault/api-docs/secret/pki#interval_duration). This needs to explicitly call out the default value to be 12 hours.

Update PKI Secret Engine doc for auto-tidy

---

changelog/19139.txt
ui/app/models/kmip/role.js
ui/lib/kmip/addon/components/edit-form-kmip-role.js
ui/tests/integration/components/edit-form-kmip-role-test.js

This PR fixes a kmip role still allowing all operations even if all of the checkboxes are deselected. This is because `operation_none` was only being set/unset when the blue toggle was clicked (see in gif only after it is toggled, then the operations are removed). But if a user unchecks `Allow this role to perform all operations` the change does not persist and all operations are still allowed. 
This also fixes a typo that made the server operation: `Discover versions` input render without a checkbox

UI: sets operationNone for a kmip role if no checkboxes are selected

---

go.mod
go.sum

This PR upgrades vault-plugin-database-mongodbatlas to [v0.9.0](https://github.com/hashicorp/vault-plugin-database-mongodbatlas/releases/tag/v0.9.0).
Steps:
```
go get github.com/hashicorp/vault-plugin-database-mongodbatlas@v0.9.0
go mod tidy
```

upgrade vault-plugin-database-mongodbatlas to v0.9.0

---

go.mod
go.sum

updates containerd/containerd and docker/distribution to reduce scanner noise. These are test dependencies that are not used by the Vault binary.

Update test dependencies

---

version/version_base.go

Missed this when cutting the release branch. Updating the version now to keep it matching ENT.

Update version to 1.14.0 and version prerelease to beta1

---

version/version_base.go

I've mistakenly left the `VersionPrerelease` as `dev1` on this release branch. Now we have improved versioning documentation, so I am fixing it.

Update version prerelease to rc1

---

helper/namespace/namespace.go

It looks like namespace context caching was removed in https://github.com/hashicorp/vault/pull/5200
but this comment was left referencing it, which I found confusing at first glance.

Update namespace.FromContext comment

---

website/content/docs/platform/k8s/helm/examples/enterprise-dr-with-raft.mdx
website/content/docs/platform/k8s/helm/examples/enterprise-perf-with-raft.mdx
website/content/docs/platform/k8s/helm/examples/enterprise-with-raft.mdx
website/content/docs/platform/k8s/helm/examples/ha-with-raft.mdx

Add a `$` before the command in shell blocks that include command output, so that the "Copy" button on the website only copies the command and not the output.
Example of current behavior: https://developer.hashicorp.com/vault/docs/platform/k8s/helm/examples/ha-with-raft
Example from this PR: https://vault-5f7042vor-hashicorp.vercel.app/vault/docs/platform/k8s/helm/examples/ha-with-raft

docs/vault-helm: fix multi-line block copy

---

changelog/19170.txt
website/content/api-docs/secret/databases/index.mdx

Fix database sample payload doc. Copy-pasting the provided sample now works with a properly configured MySQL plugin which will help user self-serve and learn how static users can be used.

Fix database sample payload doc

---

builtin/logical/pki/path_tidy_test.go

CI is encountering failures running the various PKI unit tests, looks like we are hitting OOM errors based on CircleCI resource usage.
- Do not retain a huge amount of intervals within the metrics sink to save on memory usage within CI. Otherwise, with a faster periodic timer as we have, without cleaning up, the memory consumption grows very quickly.  
- This shows the memory consumption with this fix in place.

Reduce memory usage within PKI testing in CI

---

changelog/19116.txt
ui/app/components/license-banners.js
ui/app/lib/local-storage.js
ui/app/templates/components/license-banners.hbs
ui/tests/integration/components/license-banners-test.js
ui/tests/unit/lib/local-storage-test.js

This PR allows the `licenseBanners` to be dismissed and records those preferences in localStorage.  Once a banner is dismissed, it will not show again unless a user clears their localStorage, or the vault version changes.
https://user-images.githubusercontent.com/6618863/218537469-adb243a6-cff0-45a2-a498-3ae29ea7dda1.mov

Disabling License Banners 

---

enos/modules/vault_verify_performance_replication/main.tf
enos/modules/vault_verify_performance_replication/scripts/get-replication-status.sh

Adding the replication status output to the verification script caused json decode error, so fetch the status in its own resource

Fetch replication status in its own resource

---

website/content/docs/upgrading/plugins.mdx

- add link to plugin versioning
- fix shell syntax
Backport to 1.12 because that is when plugin versioning was introduced.

docs/plugins: update upgrading plugins

---

ui/app/adapters/kubernetes/role.js
ui/app/serializers/kubernetes/config.js
ui/tests/integration/components/kubernetes/page/configure-test.js

After entering in values in the manual configuration form for a Kuberenetes secrets engine and either changing to the local cluster option or saving and then editing and changing to local cluster, the previously entered values would be sent to the server and saved. This was causing issues so the solution was to unset them in the serializer.

Kubernetes config payload fix

---

changelog/19196.txt

Add missing feature changelog entry for the Enterprise only PKI cross cluster revocation feature.

Add PKI unified-revocation feture changelog

---

builtin/credential/approle/path_login_test.go
builtin/credential/approle/path_role_test.go
builtin/credential/approle/path_tidy_user_id_test.go

This PR removes direct calls to `schema.ValidateResponse` in favor of `b.requestNoErr` helper introduced by @ncabatoff in #18865.

Refactor approle response validation tests

---

changelog/19018.txt

This PR changes the changelog format for an upcoming 1.13 feature in the GCP secrets engine.

secrets/gcp: use feature format for changelog entry of impersonated accounts

---

command/pki_health_check.go

This allows the bare:
$ vault pki health-check -list
without a corresponding mount path to complete. Otherwise, users would be greeted with a prompt for the mount, which is less than ideal.

Allow listing health checks without mount path

---

vault/eventbus/bus.go
vault/eventbus/bus_test.go

When subscriptions are too slow to accept messages on their channels, then we should remove them from the fanout so that we don't have dead subscriptions using up resources.
In addition, when a subscription is explicitly canceled, we should also clean up after it remove the corresponding pipeline.
We also add a new metrics, `events.subscriptions`, to keep track of the number of active subscriptions. This also helps us test.

events: Remove subscriptions on timeout and cancel

---

builtin/credential/aws/backend_test.go

Pulls the `client_user_id` from `resp.Auth.InternalData` instead of `resp.Auth.Metadata`.
Local Test run:
```
➜  vault git:(main) ✗ make testacc TEST=./builtin/credential/aws TESTARGS="-run=TestBackendAcc -count 1"
==> Checking that build is using go version >= 1.20...
==> Using go version 1.20...
go: downloading github.com/hashicorp/go-kms-wrapping/v2 v2.0.7
...
VAULT_ACC=1 go test -tags='' ./builtin/credential/aws -v -run=TestBackendAcc -count 1 -timeout=60m
=== RUN   TestBackendAcc_LoginWithInstanceIdentityDocAndAccessListIdentity
backend_test.go:1063: env var TEST_AWS_EC2_RSA2048 not set, skipping test
--- SKIP: TestBackendAcc_LoginWithInstanceIdentityDocAndAccessListIdentity (0.00s)
=== RUN   TestBackendAcc_LoginWithCallerIdentity
2023-02-15T11:01:24.993-0800 [DEBUG] no stsRole found …
```

fix TestBackendAcc_LoginWithCallerIdentity

---

helper/testhelpers/pluginhelpers/pluginhelpers.go
helper/testhelpers/postgresql/postgresqlhelper.go
vault/external_tests/plugin/external_plugin_test.go

This PR tests workflows for external plugins, namely the database secrets engine using Postgres. 
This is a followup to:
- https://github.com/hashicorp/vault/pull/18952
- https://github.com/hashicorp/vault/pull/19090

test/plugin: test external database plugin workflows

---

builtin/credential/approle/cmd/approle/main.go
builtin/credential/aws/cmd/aws/main.go
builtin/credential/cert/cmd/cert/main.go
builtin/credential/github/cmd/github/main.go
builtin/credential/ldap/cmd/ldap/main.go
builtin/credential/okta/cmd/okta/main.go
builtin/credential/radius/cmd/radius/main.go
builtin/credential/userpass/cmd/userpass/main.go
builtin/logical/aws/cmd/aws/main.go
builtin/logical/consul/cmd/consul/main.go
builtin/logical/nomad/cmd/nomad/main.go
builtin/logical/pki/cmd/pki/main.go
builtin/logical/rabbitmq/cmd/rabbitmq/main.go
builtin/logical/ssh/cmd/ssh/main.go
builtin/logical/totp/cmd/totp/main.go
builtin/logical/transit/cmd/transit/main.go
changelog/19215.txt

- the plugin will be multiplexed when run as an external plugin by vault versions that support secrets/auth plugin multiplexing (> 1.12)
- we continue to set the TLSProviderFunc to maintain backwards compatibility with vault versions that don't support AutoMTLS for secrets/auth plugins (< 1.12)

plugin/secrets/auth: enable multiplexing

---

changelog/19252.txt
scripts/gen_openapi.sh

This PR ensures that the `vault server -dev` process started by `gen_opeanpi.sh` is always stopped whether the script exists successfully or with an error.

Stop vault on exit in gen_openapi.sh

---

website/content/api-docs/secret/transform.mdx

Somehow this slipped through the cracks.

Document the 'convergent' tokenization transform option

---

website/content/docs/commands/print.mdx
website/data/docs-nav-data.json

Documentation Request - description
The Commands (CLI) section of the Vault Documentation does not contain an entry describing the vault print token command.
Reference - links
[Link to docs](https://developer.hashicorp.com/vault/docs/commands).
[Link to directory in Vault repo](https://github.com/hashicorp/vault/tree/main/website/content/docs/commands).
[zendesk#99855](https://hashicorp.zendesk.com/agent/tickets/99885)
Additional context
n/a

Add vault print token to commands in Vault docs

---

website/content/docs/platform/k8s/helm/examples/kubernetes-auth.mdx

Helm docs still have example for Kubernetes Auth Method that store the SA token in configuration https://www.vaultproject.io/docs/platform/k8s/helm/examples/kubernetes-auth. Update the example to allow rotated tokens to be reloaded automatically.
xref #15390
Signed-off-by: Tero Saarni <tero.saarni@est.tech>

docs/k8s: updated helm doc for short-lived SA tokens

---

changelog/19265.txt
command/pki_health_check.go

While testing the vault pki health-check feature, providing it a configuration file with integer value of say 100 for  `root_issued_leaves.root_issued_leaves` led to the following error. 
```
Failed to build health check configuration: error saving merged config for root_issued_leaves: error parsing root_issued_leaves.certs_to_fetch: could not parse value from input
```
- Go's default behavior when decoding numbers to an interface{} is to use a float64 type which `parseutil.SafeParseIntRange` does not handle. Switch to having the JSON decoder use `json.Number` which `parseutil` methods properly handle.
- Tested configuration values as strings, integers work
- Also tested we get proper error messages for out of bounds integers and float values

pki health-check fails to read in int config values

---

changelog/19269.txt
command/pki_health_check.go

- Change the output of the default configuration as JSON so it's usable as an input to the health-check command
- Prior to this change only each checker's configuration was output in JSON leading to an end-user needing to manually craft the JSON configuration

Output default config output from pki health-check --list as json

---

changelog/19274.txt
command/healthcheck/pki_role_allows_glob_wildcards.go
command/healthcheck/pki_role_allows_localhost.go
command/healthcheck/pki_role_no_store_false.go

- The various warning messages point to `{{mount}}/role/<rolename>` which is not a valid PKI path, it should be `{{mount}}/roles/<rolename>`

Fix role endpoint in pki health-check warnings

---

builtin/credential/github/path_config.go
builtin/credential/github/path_config_test.go
changelog/19244.txt
website/content/api-docs/auth/github.mdx

When running our acceptance tests in other repos, we often hit the rate limit for GitHub's API. See https://github.com/hashicorp/terraform-provider-vault/actions/runs/3767881277/jobs/6405863202#step:5:349 as an example. This change takes in the Github token (if present) when creating the GH client so that we can make authenticated requests, which bumps the rate limit to 5k requests per hour, instead of the 60/hour that we're currently exceeding.

use github token if present when fetching org id

---

changelog/19276.txt
command/healthcheck/pki_allow_if_modified_since.go
command/healthcheck/pki_audit_visibility.go
command/healthcheck/pki_tidy_last_run.go
command/healthcheck/shared.go

- Prior to this fix, if the end-user's Vault token did not have permission to the mount's tune api, we would return as if the tunable params had not been set.
- Now check to see if we encountered a permission issue and report that back to the end-user like the other checks do.

Handle permission issue on pki health-check tune checkers

---

vault/hcp_link/capabilities/node_status/node_status.go

Panic handling in Link uses `vault.ErrInternalError` in most cases except `GetNodeStatus`. This PR fixes that by using the appropriate error in `GetNodeStatus`.

add error consistency in link node status resp

---

ui/app/styles/app.scss
ui/app/styles/reset.scss
ui/ember-cli-build.js
ui/package.json
ui/yarn.lock

This PR brings in the Helios design system components in preparation for consuming the `hc-nav` addon as well as wider design system adoption.

Add Helios Design System Components

---

website/content/api-docs/auth/jwt.mdx

This PR makes it more clear that the contents of the CA certificate are expected instead of a file path. This is in response to feedback at https://github.com/hashicorp/vault/issues/6442#issuecomment-1440582029.

docs/oidc: make it clear that contents of CA certificate are expected

---

website/content/docs/secrets/consul.mdx

Consul 1.14.0 comes with a new model for deploying Consul without agents on K8s. Removing this warning since this is not relevant to Consul Secrets agent as the warning is only needed for the instance where Consul is used as backend storage to Vault.

docs: remove Consul data plane warning from Consul Secrets Engine page

---

command/agent.go
command/server.go

When we added additional logging features to `server` and `agent` in https://github.com/hashicorp/vault/pull/18031, we introduced an unintended change to the base logger names in both commands (setting them to `vault` and `vault-agent` respectively).
This PR restores the original names (in the case of `server` has no name) so that any log ingestion/parsing by downstream systems would not be impacted. Furthermore it also means that endpoints such as `sys/loggers` function as expected and don't require a `vault.` prefix for `server` loggers.

Restore 'server' and 'agent' base loggers to use their original names

---

builtin/credential/ldap/cli.go
changelog/18225.txt

This implements the requested enhancement from #13926 .

feat(auth/ldap): allow passing the LDAP password via an env var

---

ui/lib/pki/addon/decorators/check-config.js
ui/lib/pki/addon/routes/certificates/index.js
ui/lib/pki/addon/routes/issuers/index.js
ui/lib/pki/addon/routes/keys/index.js
ui/lib/pki/addon/routes/overview.js
ui/lib/pki/addon/routes/roles/index.js

- Use decorator instead of extending the overview route to check for config. Props to Jordan for setting up this pattern in k8s 🎉

VAULT-13220 use decorator instead of extending overview route

---

vault/external_tests/plugin/plugin_test.go
vault/testing.go

This PR fixes a bug in TestAddTestPlugin that appears to only manifest on Linux systems. This bug resulted in the test failing on Mac systems but passing on Linux systems because we failed to properly get the plugin version.
Additionally, we update the test to use the plugin version when performing the Read on the plugin catalog since this should now be properly set.
We write the plugin binary file in TestAddTestPlugin and then call file.Close() in a defer statement. However, we need to read the file's SHA256 sum immediately after writing the file so we call file.Sync(). On Linux this was not working as expected because we seem to be reading the sha sum and running the plugin too fast. This caused the call to get the plugin version to fail and to be incorrectly written to storage as …

test: Fix bug in TestAddTestPlugin test helper

---

website/content/docs/secrets/consul.mdx

Consul 1.14.0 comes with a new model for deploying Consul without agents on K8s. Removing this warning since this is not relevant to Consul Secrets agent as the warning is only needed for the instance where Consul is used as backend storage to Vault.

remove dataplane compat from consul secrets docs

---

vault/cluster/inmem_layer.go

@ncabatoff found a bug where when using forced timeouts in inmem a lock wasn't being released. This was causing instability in tests.

Fix test inmem layer unlock bug

---

vault/testing.go

For plugin tests, we copy the test binary. On macOS, if the destination binary already exists, then copying over it will result in an invalid signature.
The easiest workaround is to delete the file before copying.

When copying test binary, delete first

---

changelog/19334.txt
helper/builtinplugins/registry.go

This PR changes the deprecation status to deprecated for the AD secrets engine. This causes Vault to log that it's mounting a deprecated builtin similar to below:
```
2023-02-23T15:30:29.031-0800 [WARN]  core: mounting deprecated builtin: name=ad type=secret path=ad/
```

secrets/ad: change deprecation status to deprecated

---

vault/activity_log_test.go
vault/activity_log_util_common.go

Mount paths "auth/foo/" and "auth/foo" should both be represented as "auth/foo/" by the activity log responses, with the clients in those paths getting correctly deduplicated.
I didn't create a changelog entry since there's already one for the original change: https://github.com/hashicorp/vault/pull/18916

VAULT-13763 normalize activity log mount paths 

---

command/healthcheck/healthcheck.go
command/healthcheck/pki_hardware_backed_root.go
command/healthcheck/pki_role_allows_glob_wildcards.go
command/healthcheck/pki_role_allows_localhost.go
command/healthcheck/pki_role_no_store_false.go
command/healthcheck/pki_root_issued_leaves.go
command/healthcheck/pki_too_many_certs.go
command/pki_health_check.go
command/pki_health_check_test.go

- Notify user yaml output mode is not support with --list argument
- Output pure JSON in json output mode with --list argument
- If a checker returns a nil response, convert to an empty slice
- Add handler for permission errors to too many certs checker

Address some small issues within pki health-check

---

builtin/credential/approle/path_role.go
builtin/credential/approle/path_role_test.go
changelog/19186.txt

This PR adds a nil check for the secret ID entry when deleting via secret id accessor. This fixes a scenario where a secret_id can be deleted by providing a valid accessor to the destroy endpoint on any role in the same mount.

add nil check for secret id entry on delete via accessor

---

sdk/helper/ocsp/client.go

Mirror NSS's GET-vs-POST selection criteria, wherein GET is preferred over POST (as the former might be a response from a cached CDN entry, whereas the latter might hit a live responder). However, only accept it if it definitively says "Good" or "Revoked" -- trigger a POST request when an unknown or failure status is seen.
---
Because existing Vault PKI engines respond with a parse error, and not Method Not Allowed, this would probably be useful to backport to 1.13, which is the first release with OCSP support.

Refactor OCSP client to support better retries

---

builtin/credential/ldap/backend_test.go
changelog/18230.txt
sdk/helper/ldaputil/client.go
sdk/helper/ldaputil/config.go
sdk/helper/ldaputil/config_test.go
website/content/api-docs/auth/ldap.mdx
website/content/docs/auth/ldap.mdx

Implements the requested improvement from #6128

Allow alias dereferencing in LDAP searches

---

website/content/docs/release-notes/1.13.0.mdx
website/data/docs-nav-data.json

This PR adds the Release Notes for Vault 1.13.0. This was based on the [1.13.0, 1.12.4, 1.11.8, 1.10.11 announcement email draft](https://docs.google.com/document/d/1zUQLo9q55yhiOnJIYtXqWC3Qq6ig0rh3hIORkN_eMxg/edit?usp=sharing).
🔍 [Deploy Preview](https://vault-git-docs-v113-release-notes-hashicorp.vercel.app/vault/docs/release-notes/1.13.0)

Vault 1.13.0 Release Notes

---

website/content/api-docs/auth/approle.mdx

This backports the changes made by [PR19369](https://github.com/hashicorp/vault/pull/19369).
The [automatic backport PR](https://github.com/hashicorp/vault/pull/19380) failed due to merge conflict.

[Backport] approle naming syntax documentation (#19369)

---

command/commands.go
command/pki.go
command/transit.go
command/transit_import_key.go
command/transit_import_key_version.go

As reported by @miagilepner, thank you!
---
This fixes the typo in the PKI synopsis, incorrectly reporting it as a K/V helper. We introduce a matching one for Transit and clarify a few help texts.
```
[cipherboy@xps15 vault]$ vault -help
Usage: vault <command> [args]
Common commands:
read        Read data and retrieves secrets
write       Write data, configuration, and secrets
delete      Delete secrets and configuration
list        List data or secrets
login       Authenticate locally
agent       Start a Vault agent
server      Start a Vault server
status      Print seal and HA status
unwrap      Unwrap a wrapped secret
Other commands:
audit                Interact with audit devices
auth                 Interact with auth methods
debug                Runs the debug command
events …
```

Fix PKI Synopsis, add Transit help text and casing fixes

---

helper/builtinplugins/registry_test.go
scripts/gen_openapi.sh

`openldap` (https://github.com/hashicorp/vault-plugin-secrets-openldap) is an alias for `ldap` secrets engine. It was double-included and generated spurious endpoints.

Remove 'openldap' from gen_openapi.sh

---

ui/app/components/auth-form.js
ui/app/utils/identity-manager.js
ui/package.json
ui/tests/integration/components/auth-form-test.js
ui/tests/unit/serializers/cluster-test.js
ui/yarn.lock

This PR removes `crypto` and adds the [uuid](https://github.com/uuidjs/uuid) package since crypto is only available in secure contexts.
`crytpo.randomUUID()` was used to set an id for `dr` and `performance` replication attribute records returned on the cluster since there is no unique key for Ember Data to store the record. It was also used for the `nonce` value when logging in with the okta auth method when a number challenge is required.

Identity manager secure context fallback

---

changelog/19410.txt
ui/app/components/auth-form.js
ui/package.json
ui/tests/integration/components/auth-form-test.js
ui/yarn.lock

Similar to the changes made in #19403
This PR removes using the crypto interface which requires secure context [MDN docs here](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID) and adds the [uuid](https://github.com/uuidjs/uuid) package since crypto is only available in secure contexts.

UI: Use uuid dependency instead of crypto.randomUUID()

---

website/content/docs/commands/status.mdx

Related GH issue: https://github.com/hashicorp/vault/issues/9185
The issue is about getting different output values for “vault status” command depending on the format selected. 
Though the output looks inconsistent, It looks like we only want to display the relevant fields for "table" format. I posted this on vault-team-sustaining to see what others think about this https://hashicorp.slack.com/archives/C0287E435NE/p1677105285284409.
Mehdi gave some input from support perspective and suggested that we document this and also have an additional flag such as:  vault status -fields=all/* -format=table  - ie some additional parameter that over-rides the current user based adaptive outputs in favor of consistent output to always show all related fields.
For now, I am more inclined towards …

Vault Status Command Differs Depending on Format 

---

ui/tests/unit/adapters/clients-activity-test.js

Clients activity test was failing due to subtracting months twice. Instead of subtracting the month by `-2` and also subtracting using `subMonths(..,..)` we should only subtract dates using `subMonths`.

UI: Use specific date in clients activity test

---

CHANGELOG.md

Point releases: 1.10.11, 1.11.8, 1.12.4
I added the changelog line (a copy from the changelog in 1.12.4): `* ui: fixes reliance on secure context (https) by removing methods using the Crypto interface [[GH-19410](https://github.com/hashicorp/vault/pull/19410)]` 
to 1.13.0.

Updated Changelog for 1.13 and point releases

---

website/content/api-docs/secret/identity/entity-alias.mdx

The `name`, `canonical_id`, and `mount_accessor` parameters are not required parameters for updating a entity-alias.
Example:
```
~ vault status -format=json | jq -r '.version'
1.12.2+ent
~ vault read -field=mount_accessor identity/entity-alias/id/$AID 
auth_userpass_29867988
~ vault write identity/entity-alias/id/$AID mount_accessor=$MA2
Key             Value
---             -----
canonical_id    fd098313-4019-c7f1-de82-7fce975bf096
id              b19fe0ef-2aa6-6a44-c103-0d5c92a234cc
~ vault read -field=mount_accessor identity/entity-alias/id/$AID 
auth_userpass_be3e3761
```

update entity-alias doc fix

---

website/content/docs/secrets/ldap.mdx

Updated https://developer.hashicorp.com/vault/docs/secrets/ldap#active-directory-ad-1 to clarify customers configure username properly using username_template when sAMAccountName is involved.
Preview of changes: https://vault-bmlno4dzn-hashicorp.vercel.app/vault/docs/secrets/ldap#active-directory-ad-1

Docs - update ldap page to add clarity around sAMAccountName

---

website/content/docs/release-notes/index.mdx

🧵 [Slack thread](https://hashicorp.slack.com/archives/C012RTGJR1V/p1677809199484109)
🎫 [Zendesk ticket](https://hashicorp.slack.com/archives/C012RTGJR1V/p1677809199484109)
🔍 [Deploy preview](https://vault-git-docs-update-rn-landing-page-hashicorp.vercel.app/vault/docs/release-notes)
A customer feedback says the [Release Notes landing page](https://developer.hashicorp.com/vault/docs/release-notes) is empty (one sentence, so it feels empty?). So, I'm adding little more text.

Add more context on the Release Notes landing page

---

website/content/docs/secrets/identity/oidc-provider.mdx

Adds a link to the Nomad tutorial for Vault as OIDC Provider from https://developer.hashicorp.com/vault/docs/secrets/identity/oidc-provider
(Note: when running this locally, it didn't look like it was pulling the latest Nomad docs references. But the tutorial is up @ https://developer.hashicorp.com/nomad/tutorials/single-sign-on/sso-oidc-vault

[docs] Link to the Nomad tutorial for Vault as OIDC provider

---

changelog/19416.txt
vault/token_store.go
vault/token_store_test.go

Legacy service tokens generated in Vault 1.10+ with env var `VAULT_DISABLE_SERVER_SIDE_CONSISTENT_TOKENS=true` are not assigned a cubbyhole ID. The implication is that `cubbyhole/` cannot be used, nor can the tokens be revoked.
This commit assigns a cubbyhole ID to these tokens and adds a new test case to see that cubbyhole and revocation works correctly.
Fixes #18304

Fix cubbyhole and token revocation for legacy service tokens

---

sdk/helper/ldaputil/client.go

This PR adds a comment above execution of [text/template](https://pkg.go.dev/text/template) values used in the LDAP auth method for:
- https://developer.hashicorp.com/vault/api-docs/auth/ldap#userfilter
- https://developer.hashicorp.com/vault/api-docs/auth/ldap#groupfilter
The purpose of this is to make it clear that arbitrary functions cannot be invoked via templates. The only functions available within templates are noted within the comment.

ldaputil: adds comment on available text/template functions

---

changelog/19448.txt
ui/app/components/configure-ssh-secret.js
ui/app/controllers/vault/cluster/settings/configure-secret-backend.js
ui/app/templates/components/configure-ssh-secret.hbs
ui/app/templates/vault/cluster/settings/configure-secret-backend.hbs
ui/tests/acceptance/settings/configure-secret-backends/configure-ssh-secret-test.js

Fixes form submission issue preventing updates to an ssh config
<hr>
**After fix:**

UI: fix delete for SSH engine config

---

changelog/18729.txt
sdk/framework/backend.go

added TypeInt64 in Zero() method

bug: correct handling of the zero int64 value

---

.github/workflows/ci.yml
Makefile
command/server/hcp_link_config_test.go
vault/external_tests/hcp_link/hcp_link_test.go

This PR introduces a few minor corrections to avoid race conditions with the tests. It also corrects a syntax issue that led to most jobs from the CI GitHub Actions Workflow to be skipped.
In the end, the actual cause of the failing TestHCPLinkConnected test was that the HCP Link resource ended up in the _unlinking_ state, so a new resource needed to be created and the associated secrets were updated.

Fix failing TestHCPLinkConnected Test

---

website/content/docs/secrets/gcp.mdx

Adds an explanation to the GCP secret engine docs to mention that service account keys are returned as base64-encoded strings in the response.

Add note to gcp secrets docs to explan service account key encoding

---

sdk/framework/backend.go
sdk/framework/backend_test.go
sdk/framework/field_type.go

Follow up to #18729 to fix the fmt job (trailing whitespace) and help prevent regressions in the future.

sdk: Fix fmt + add FieldType test

---

builtin/logical/transit/path_import_test.go
changelog/19519.txt
sdk/helper/keysutil/policy.go
sdk/helper/keysutil/util.go

RSA-PSS keys would fail with the error:
```
$ vault transit import transit/keys/OS_key_test2 @newkey-pss.der.b64 type=rsa-2048
Retrieving transit wrapping key.
Wrapping source key with ephemeral key.
Encrypting ephemeral key with transit wrapping key.
Submitting wrapped key to Vault transit.
failed to call import:Error making API request.
URL: PUT http://localhost:8200/v1/transit/keys/OS_key_test2/import
Code: 500. Errors:
* 1 error occurred:
* error importing key: error parsing asymmetric key: x509: PKCS#8 wrapping contained private key with unknown algorithm: 1.2.840.113549.1.1.10
```
This adds custom PKCS8 parsing along the lines of our existing Ed25519 key parsing, though much simpler since the inner structure is simply a PKCS1 blob (which can be decoded by the standard library).

Add support for importing RSA-PSS keys into Transit

---

api/lifetime_watcher.go

Added a comment to clarify the intentional use of the `math/rand` package in `lifetime_watcher.go`'s `NewLifetimeWatcher` func.

Explain use of math/rand in LifetimeWatcher

---

builtin/logical/pki/path_fetch.go
sdk/helper/testhelpers/schema/response_validation.go
sdk/helper/testhelpers/schema/response_validation_test.go

A number of special fields can get assigned to response data that should not be added to response validation schema. The fields are defined here:
https://github.com/hashicorp/vault/blob/ed08e45069d60fc4452fad7d44bcfd3b2e4c8236/sdk/logical/response.go#L17-L50

Ignore special HTTP fields in response validation tests

---

changelog/18863.txt
command/agent/auth/jwt/jwt.go
command/agent/auth/jwt/jwt_test.go
command/agent/jwt_end_to_end_test.go
command/agent/testing.go
website/content/docs/agent/autoauth/methods/jwt.mdx

The current behaviour was:
- Agent would correctly read the JWT by following the symlink
- Agent would then delete the symlink, instead of the JWT (when `remove_jwt_after_reading` is set to true)
In other words, it followed the symlink correctly for reading, but incorrectly for deleting.
I've added a new option, `remove_jwt_follows_symlinks`, that will change this behaviour when set to delete the JWT, instead of the symlink, when removing the JWT.

VAULT-12798 Correct removal behaviour when JWT is symlink

---

changelog/19260.txt
command/agent.go
command/agent/auth/oci/oci.go
command/agent/oci_end_to_end_test.go
website/content/docs/agent/autoauth/methods/oci.mdx
website/data/docs-nav-data.json

This PR adds the OCI (Oracle Cloud Infrastructure) auto-auth method to the Vault Agent.
It supports authentication via API Keys and Instance Principals.
The end to end test must be executed in an OCI compute instances, as the OCI auth backend in Vault currently only supports Instance Principal authentication. See: https://developer.hashicorp.com/vault/docs/auth/oci#configure-the-oci-tenancy-to-run-vault
To run the tests, set the following environment variables:
- `OCI_TEST_TENANCY_OCID`
- `OCI_TEST_USER_OCID`
- `OCI_TEST_FINGERPRINT`
- `OCI_TEST_PRIVATE_KEY_PATH`
- `OCI_TEST_OCID_LIST`
Test results:
```
$ make testacc TEST=./command/agent TESTARGS="-run=TestOCIEndToEnd"
==> Checking that build is using go version >= 1.20...
==> Using go version 1.20.1...
VAULT_ACC=1 go test -tags='' …
```

Add Oracle Cloud auth to the Vault Agent

---

website/content/docs/agent/autoauth/methods/token_file.mdx

Reported by https://github.com/hashicorp/vault/issues/19539
Just a mistake in the docs. Correcting it, then will backport.

Update auto-auth docs to remove tilde for home

---

.github/workflows/enos-fmt.yml
.github/workflows/enos-run-k8s.yml
.github/workflows/test-enos-scenario-ui.yml
.github/workflows/test-run-enos-scenario-matrix.yml

Terraform 1.4.x introduced an issue that prevents some enos resources from planning correctly. This pins the version of Terraform until the issue between provider and Terraform 1.4.x is resolved.
```
╷
│ Error: exit status 1
│
│ Error: Provider produced invalid plan
│
│ Provider "app.terraform.io/hashicorp-qti/enos" planned an invalid value for
│ module.get_vault_cluster_ips.enos_remote_exec.get_leader_private_ip.environment:
│ sensitive planned value does not match config value.
│
│ This is a bug in the provider, which should be reported in the provider's own
│ issue tracker.
│ 
│
│   (source code not available)
```

ci: pin terraform until planning bug is resolved

---

.github/workflows/test-go.yml

This PR comments out the **HCP_SCADA_ADDRESS** environment variable so that the HCP Link tests are skipped when go test is run on GitHub Actions.

Comment Out HCP_SCADA_ADDRESS Environment Variable

---

ui/app/components/sidebar/frame.hbs
ui/app/components/sidebar/frame.js
ui/app/components/sidebar/nav/access.hbs
ui/app/components/sidebar/nav/cluster.hbs
ui/app/components/sidebar/nav/cluster.js
ui/app/components/sidebar/nav/policies.hbs
ui/app/components/sidebar/nav/tools.hbs
ui/app/components/sidebar/user-menu.hbs
ui/app/components/sidebar/user-menu.js
ui/app/styles/app.scss
ui/app/styles/components/console-ui-panel.scss
ui/app/styles/components/sidebar.scss
ui/app/templates/application.hbs
ui/app/templates/components/link-status.hbs
ui/app/templates/components/namespace-picker.hbs
ui/app/templates/vault.hbs
ui/ember-cli-build.js
ui/package.json
ui/tests/acceptance/cluster-test.js
ui/tests/acceptance/mfa-setup-test.js
ui/tests/helpers/components/sidebar-nav.js
ui/tests/integration/components/sidebar/frame-test.js
ui/tests/integration/components/sidebar/nav/access-test.js
ui/tests/integration/components/sidebar/nav/cluster-test.js
ui/tests/integration/components/sidebar/nav/policies-test.js
ui/tests/integration/components/sidebar/nav/tools-test.js
ui/tests/integration/components/sidebar/user-menu-test.js
ui/yarn.lock

Adds components for sidebar frame and navigation links. A follow up PR will be opened to add the components in the template and clean up any components that are no longer needed.
For the nav components, I pulled the links directly from existing templates that used the `MenuSidebar` component. The nav cluster component also took links from the `ClusterInfo` component.
_Note that the test run will fail until the nav addon is published since it is linked locally_

Sidebar Navigation Components

---

.copywrite.hcl
enos/modules/k8s_deploy_vault/raft-config.hcl

The addition of the copyright and license headers to the file: `enos/modules/k8s_deploy_vault/raft-config.hcl` has caused the K8S/Docker integration test to fail since the Vault deployment uses that file when configuring the storage backend. The addition of the header breaks the helm release and therefore the headers have been removed.

[QT-523] Remove copyright/license header from raft config used in theDocker/K8S integration test

---

vault/hcp_link/capabilities/api_capability/token_manager.go

We are using a new HCP endpoint to fetch the policy associated with the API capability.
Note: converting to draft to prevent merge for now

update link policy fetch URL

---

website/content/api-docs/secret/kv/kv-v2.mdx

This came in as part of https://github.com/hashicorp/vault/issues/19599
We used to have a note at the top telling customers to sub out `/secret` for the path to their mount of interest, but if you were linked to a specific API, you could miss it.
I feel like, especially for API docs, we should call this out explicitly, so I've tried to do so. We also missed calling out `path` in a few places, so I added that too. Do feel free to tell me if you feel like this is the wrong idea, though. I'm totally open to not merging this if folks feel like it makes things more confusing instead of more clear.
See: https://vault-7r5tqdn4k-hashicorp.vercel.app/vault/api-docs/secret/kv/kv-v2 for a direct link.

Update KV-V2 docs to explicitly call out the secret mount path as a parameter

---

website/content/docs/upgrading/upgrade-to-1.12.x.mdx
website/content/docs/upgrading/upgrade-to-1.13.x.mdx
website/content/partials/ocsp-redirect.mdx

Write up the discovered issue of OCSP GET requests that contain multiple '/' characters within the encoded request, being responded with a 301 HTTP Permanent redirect status code instead of a valid OCSP response. 
The workaround for now is to submit the OCSP request using HTTP POST instead of GET which does not suffer from Go's HTTP mux getting in the way and returning the redirection response to the end-user.

Add known issue about OCSP GET redirection responses

---

builtin/logical/pki/backend_test.go
builtin/logical/pki/crl_util.go
builtin/logical/pki/path_revoke.go
changelog/19624.txt

- A refactoring that occurred in 1.13 timeframe removed what was considered a specific check for standby nodes that wasn't required as a writes should be returning ErrReadOnly.
- That sadly exposed a long standing bug where the errors from the storage layer were not being properly wrapped, hiding the ErrReadOnly coming from a write and failing the request which causes a failure to forward revocation requests from standby nodes.

Forward PKI revocation requests received by standby nodes to active node

---

builtin/logical/pki/crl_util.go
builtin/logical/pki/storage.go
builtin/logical/ssh/path_issue_sign.go
builtin/logical/transit/path_keys.go

None of these appear to be related to storage issues, so I'm not inclined to backport them. But for completeness, I audited the rest of PKI, SSH, and Transit for errors which are created but don't wrap anything and found a few more places. 
Related to #19624.

More wrapped errors - PKI, SSH, Transit 

---

changelog/19600.txt
sdk/framework/openapi.go
sdk/framework/openapi_test.go

The previous logic for matching unauthenticated & sudo paths in OpenAPI did not take into account the `+` wildcard, so some of the PKI paths were skipped.
With new logic, these are the new unauthenticated paths introduced for builtin plugins:
```sh
❱ diff unauth_before unauth_after2
27a28,30
> "/identity/oidc/provider/{name}/.well-known/keys"
> "/identity/oidc/provider/{name}/.well-known/openid-configuration"
> "/identity/oidc/provider/{name}/token"
57a61,69
> "/{pki_mount_path}/issuer/{issuer_ref}/crl"
> "/{pki_mount_path}/issuer/{issuer_ref}/crl/delta"
> "/{pki_mount_path}/issuer/{issuer_ref}/crl/delta/der"
> "/{pki_mount_path}/issuer/{issuer_ref}/crl/delta/pem"
> "/{pki_mount_path}/issuer/{issuer_ref}/crl/der"
> "/{pki_mount_path}/issuer/{issuer_ref}/crl/pem"
> …
```

openapi: Fix logic for labeling unauthenticated/sudo paths

---

changelog/19640.txt
go.mod
go.sum

This PR upgrade vault-plugin-secrets-openldap to [v0.10.1](https://github.com/hashicorp/vault-plugin-secrets-openldap/releases/tag/v0.10.1) to bring in a bug fix from https://github.com/hashicorp/vault-plugin-secrets-openldap/pull/56.

secrets/ldap: upgrades plugin to v0.10.1

---

changelog/19641.txt
go.mod
go.sum

This PR upgrade vault-plugin-secrets-openldap to [v0.9.1](https://github.com/hashicorp/vault-plugin-secrets-openldap/releases/tag/v0.9.1) to bring in a bug fix from https://github.com/hashicorp/vault-plugin-secrets-openldap/pull/56.

secrets/ldap: upgrades plugin to v0.9.1

---

website/content/docs/commands/plugin/deregister.mdx

https://developer.hashicorp.com/vault/docs/commands/plugin/deregister does not show the information relevant to the additional parameter `-version=` that is included from Vault 1.12.0 onwards - https://github.com/hashicorp/vault/blob/v1.12.0/command/plugin_deregister.go#L59 and the commit that added it: https://github.com/hashicorp/vault/pull/16856/files#diff-068ff36161239648c34a6fd7e1c450f20e249215ad8e4c7aaf0e6bfcbdb80ebbR59
On the https://github.com/hashicorp/vault/blob/main/CHANGELOG.md as `plugins: Add plugin version to auth register, list, and mount table [https://github.com/hashicorp/vault/pull/16856]`
preview: https://vault-ktctkyqtj-hashicorp.vercel.app/vault/docs/commands/plugin/deregister

docs / update 'vault plugin deregister' command doc

---

changelog/19378.txt
command/kv_list.go
command/kv_test.go
website/content/docs/commands/kv/list.mdx

Add `-mount` flag to kv list command

---

builtin/logical/pki/backend_test.go

- Remove wait call to testhelpers.WaitForActiveNodeAndStandbys and leverage testhelpers.WaitForStandbyNode instead.

Fix for PKI.TestStandby_Operations test to work in ENT

---

vault/activity/query.go

This PR fixes the output from a Trace-level log in `pq.Get()`.

activitylog: Fix pq.Get trace logger output

---

changelog/19541.txt
ui/app/components/auth-jwt.js
ui/app/templates/components/auth-form.hbs
ui/app/templates/vault/cluster/auth.hbs
ui/tests/acceptance/enterprise-namespaces-test.js
ui/tests/pages/auth.js

So this was tricky to reproduce and due to the whack-a-mole nature of these bugs, here is a very thorough breakdown:
The auth form component updates as the namespace changes to show the correct associated login methods (and corresponding button styles, if applicable). This means the form often reverts to the dropdown menu because by default auth methods are not listed as tabs when unauthenticated (this is a separate config option)
Notice in the gif below, there is an `oidc` tab because in `/Root` oidc has been configured so `listing_visibility='unauth'` [(docs)](https://developer.hashicorp.com/vault/api-docs/system/auth#listing_visibility). However, as another namespace is typed, the default form changes because `testns` has no unuath'd methods.
<hr>
For both OIDC and JWT, the `role` is …

UI/update auth form to fetchRoles after a namespace is inputted, prior to OIDC auth

---

vault/hcp_link/capabilities/node_status/node_status.go

The `OS` from host info will be less specific than `Platform`. For example, `OS` would be `linux` but `Platform` would be `ubuntu`. The node status correctly uses `PlatformVersion` for the OS version but that does not properly correspond to `OS`.

use Platform from host info for node status OS

---

website/content/api-docs/secret/databases/postgresql.mdx

Updated connection_url to be according to the options available in the pgx library instead of the now deprecated use of the lib/pq which was done as part of Vault 1.11 as documented here - https://github.com/hashicorp/vault/blob/main/CHANGELOG.md#june-20-2022

Updated connection_url to be pgx library relevant

---

.github/actionlint.yaml
.github/workflows/actionlint.yml
.github/workflows/build-vault-oss.yml
.github/workflows/build.yml
.github/workflows/changelog-checker.yml
.github/workflows/ci.yml
.github/workflows/enos-release-testing-oss.yml
.github/workflows/enos-run-k8s.yml
.github/workflows/godoc-test-checker.yml
.github/workflows/oss.yml
.github/workflows/security-scan.yml
.github/workflows/test-ci-cleanup.yml
.github/workflows/test-enos-scenario-ui.yml
.github/workflows/test-go.yml
.github/workflows/test-run-acc-tests-for-path.yml
.github/workflows/test-run-enos-scenario-matrix.yml

This PR introduces a **diff-oss-ci** and a **test-ui** GitHub Actions Workflow Job based on the CircleCI jobs bearing the same names.
The **diff-oss-ci** job is skipped when the workflow executions stems from a repository other than `hashicorp/vault-enterprise`.
This PR also introduces a few adjustments to satisfy issues found by the GitHub Actions linter.

Migrating CircleCI Jobs to GHA Workflow

---

ui/app/adapters/pki/crl.js
ui/app/models/mount-config.js
ui/app/models/pki/crl.js
ui/app/styles/core/helpers.scss
ui/lib/pki/addon/components/page/pki-configuration-details.hbs
ui/lib/pki/addon/routes/configuration/index.js
ui/lib/pki/addon/templates/configuration/index.hbs
ui/tests/acceptance/pki/pki-engine-workflow-test.js
ui/tests/helpers/pki/page/pki-configuration-details.js
ui/tests/integration/components/pki/page/pki-configuration-details-test.js

- Instead of creating a model for `pki/config`, we opted to create separate models for each section
- For the configuration page, we only show CRL (`pki/crl` model), URL (`pki/urls` model), and mount config (`secret-engine` which belongs to the `mount-config` model).

UI: VAULT-6519 PKI configuration read 

---

website/data/docs-nav-data.json

It was reported that the `userpass` auth method title appears...
This PR fixes this issue.
🔍 [Deploy preview](https://vault-git-docs-fix-format-userpass-hashicorp.vercel.app/vault/docs/auth/userpass)

[Docs] Fix the title parsing error - userpass

---

changelog/19541.txt
ui/app/components/auth-jwt.js
ui/app/templates/components/auth-form.hbs
ui/app/templates/vault/cluster/auth.hbs
ui/tests/acceptance/enterprise-namespaces-test.js
ui/tests/acceptance/enterprise-oidc-namespace-test.js
ui/tests/pages/auth.js

Backport for #19541
Plus enterprise test fixes from #19671

Backport 1.13.x: UI/update auth form to fetchRoles after a namespace is inputted, prior to OIDC auth #19541

---

changelog/19460.txt
ui/app/routes/vault/cluster/oidc-callback.js
ui/tests/unit/routes/vault/cluster/oidc-callback-test.js

Backport 1.11.x: AD FS namespace OIDC bug fix #19460

---

vault/request_forwarding.go

Make sure that we specify Backoff in conjunction with MinConnectTimeout

---

vault/request_handling.go
vault/token_store.go

This reverts commit 160196f4bc270ea0698b894d4f5f3e84426b77c9.
To be merged and backported. This will be re-reverted later when the full change gets added.
I can only add one Milestone, but this should be in and backported for all of the release branches.

VAULT-8337 Revert "VAULT-8337 OSS changes"

---

ui/app/styles/components/box-label.scss
ui/app/styles/components/icon.scss
ui/app/styles/components/modal.scss
ui/app/styles/core.scss
ui/app/styles/core/box.scss
ui/app/styles/core/bulma-classes.css
ui/app/styles/core/buttons.scss

This PR finishes up the last of moving Bulma classes into the component files (see first [PR](https://github.com/hashicorp/vault/pull/19683))
Targeting the components before core scss was intentional. There are less issues and only a couple of components with the same names as the Bulma classes (e.g. modal or box).
Below are the components addressed and their relevant pictures:
* `box-label.scss`. An easy fix now that we can use the extends because those helpers exists.
* `icon.scss` this file was orginally "bulma free" but it made sense to me to carry over any bulma classes that impacted the `class="icon"` to be moved here. I alphabetized a little as well. The color is wrong but that's a helper issue I'll address in another PR.
* `modal.scss` I just missed a couple of bulma classes here …

Step three cont. Bulma classes to component files

---

changelog/19703.txt
ui/app/templates/vault/cluster/secrets/backend/metadata.hbs
ui/tests/acceptance/secrets/backend/kv/breadcrumbs-test.js

It was discovered that a 404 was thrown when navigating back a level from the metadata tab of a secret using the breadcrumbs. The link was pointing to the `show` route in the metadata view rather than `list` route as in secret tab. 
Before:
https://user-images.githubusercontent.com/24611656/227052386-287bf581-34b1-4f3a-8f6e-68d9a2a05b05.mov
After:
https://user-images.githubusercontent.com/24611656/227052440-ae5cf5dd-2390-4189-b693-a8f842230b57.mov

Secret Metadata Breadcrumb Bug

---

builtin/credential/aws/backend.go
builtin/credential/aws/client.go
builtin/credential/aws/path_config_rotate_root.go
builtin/credential/aws/path_config_rotate_root_test.go
builtin/credential/aws/path_login.go
builtin/logical/aws/backend_test.go
builtin/logical/aws/iam_policies.go
builtin/logical/aws/iam_policies_test.go
builtin/logical/aws/path_config_rotate_root.go
builtin/logical/aws/path_user.go
builtin/logical/aws/secret_access_keys.go
changelog/19365.txt

Fixes #19364 by passing through `context.Context` and cancellation signals to AWS SDK client requests in auth/aws and secrets/aws backends.

auth/aws: pass cancelable context with AWS calls

---

changelog/19720.txt
go.mod
go.sum

Update to the latest k8s-auth release [v0.13.3](https://github.com/hashicorp/vault-plugin-auth-kubernetes/releases/tag/v0.13.3)

auth/kubernetes: upgrade to v0.13.3

---

.github/workflows/enos-fmt.yml
.github/workflows/enos-run-k8s.yml
.github/workflows/test-enos-scenario-ui.yml
.github/workflows/test-run-enos-scenario-matrix.yml

A prior planning bug was resolved in Terraform 1.4.2

Backport of ci: unpin terraform in CI  into release/1.12.x

---

website/content/docs/get-started/developer-qs.mdx

🎫 [Jira](https://hashicorp.atlassian.net/browse/VAULT-12522)
🎟️ [Asana](https://app.asana.com/0/563192436488770/1203633559435202/f)
🔍 [Deploy preview](https://vault-git-docs-add-openapi-sdks-hashicorp.vercel.app/vault/docs/get-started/developer-qs)
Update the [Developer Quick Start](https://developer.hashicorp.com/vault/docs/get-started/developer-qs) page by adding new tabs in the Install Client Library, Authenticate to Vault, Store a secret & Retrieve a Secret for "**OpenAPI Go (Beta)**", and "**OpenAPI C# (Beta)**"
**What's missing:** 
- No example code in the [vault-examples](https://github.com/hashicorp/vault-examples/tree/main) repo for OpenAPI Go and OpenAPI C#.
- No code example equivalent to:
```
if value != "Hashi123" {
log.Fatalf("unexpected password value %q retrieved from …
```

Add OpenAPI Go and C#

---

website/content/api-docs/secret/aws.mdx

Update username template description for AWS by calling out what DisplayName and PolicyName actually are placeholders for

Update username template description for AWS

---

changelog/19721.txt
vault/ha.go

Fixes https://github.com/hashicorp/vault/issues/17737.

Address regression introduced by #15493 for non-raft storage backends.

---

ui/app/components/sidebar/frame.hbs
ui/app/components/sidebar/frame.js
ui/app/styles/components/console-ui-panel.scss
ui/app/styles/components/sidebar.scss
ui/app/templates/components/console/log-command.hbs
ui/app/templates/components/console/ui-panel.hbs
ui/tests/acceptance/console-test.js

This PR consists of mostly style updates to the console panel to align with the sidebar navigation. These changes include:
- changed background color to match sidebar
- changed button icon color from grey to white
- added close button in top right of panel
- added white border to input
- align command with chevron icon in log
- panel now pushes content down rather than overlap (no changes in this PR but a product of moving things around)
The styling for the HCP link banner was also updated:

Console Panel Updates

---

.github/workflows/ci.yml
.github/workflows/test-go.yml

This is an ENT-specific job, so it won't as part of CI here. 
It's worth noting that I am proposing a new way of injecting environment variables to the `test-go` workflow in this one. The Go test FIPS job itself is pretty much the same as our standard `test-go`, but it has some extra build tags and an extra environment variable.

Migrate the FIPS testing job to GitHub Actions

---

changelog/19738.txt
website/content/docs/platform/aws/lambda-extension.mdx

Add a warning in the Vault Lambda Extension docs about the cache ttl.

add warning for vault lambda extension cache ttl

---

website/content/api-docs/secret/kv/kv-v2.mdx

docs: Fix duration format link in kv-v2 docs page

---

ui/app/decorators/model-expanded-attributes.js
ui/app/models/secret-engine.js
ui/app/routes/vault/cluster/secrets/backend/create-root.js
ui/app/routes/vault/cluster/secrets/backend/list.js
ui/app/routes/vault/cluster/secrets/backend/secret-edit.js
ui/tests/acceptance/settings/mount-secret-backend-test.js
ui/tests/unit/decorators/model-expanded-attributes-test.js
ui/tests/unit/models/secret-engine-test.js

This PR updates the `secret-engine` model from a Classic to Octane 🎉 ahead of some changes we will make for the new PKI engine. 
My approach was to first update the tests for this model to be more thorough (and also updated). I made sure the tests passed with the old implementation, updated the model, then ran the tests again. This worked well, because the tests actually caught something that I translated incorrectly 😄

UI: secret-engine model octanified

---

ui/app/routes/vault/cluster/oidc-callback.js
ui/tests/unit/routes/vault/cluster/oidc-callback-test.js

This PR moves the logic that happens in `beforeModel` for the oidc callback route into an easily-testable method.

UI: Test business logic for oidc callback params

---

.github/scripts/generate-test-package-lists.sh
builtin/logical/pki/acme/jws.go

This fixes the CI execution, to add the new pki/acme subpacakge that was missed in #19778 and adds limits around JWS algorithm selection.

Tighten JWS algorithm lists

---

.github/workflows/ci.yml

This allows branches to be able to be run on both `push` and `PR` events

fix github ref

---

vault/rollback.go
vault/testing.go

When testing the rollback mechanism, there's two categories of tests typically written:
1. Ones in which the rollback manager is entirely left alone, which usually are a bit slower and less predictable. However, it is still sufficient in many scenarios.
2. Ones in which the rollback manager is explicitly probed by tests and "stepped" to achieve the next rollback.
Here, without a mechanism to fully disable the rollback manager's periodic ticker (without affecting its ability to work!) we'll continue to see races of the sort:
>     --- FAIL: TestRevocationQueue (50.95s)
>     panic: sync: WaitGroup is reused before previous Wait has returned [recovered]
>         panic: sync: WaitGroup is reused before previous Wait has returned
This allows us to disable the ticker, returning control to the …

Add mechanism to disable automatic rollbacks

---

builtin/logical/pki/acme/state.go
builtin/logical/pki/acme/state_test.go
builtin/logical/pki/backend.go
builtin/logical/pki/backend_test.go
builtin/logical/pki/path_acme_nonce.go
builtin/logical/pki/path_acme_test.go
builtin/logical/pki/test_helpers.go

Initial ACME new-nonce API implementation. 
Missing bits 
✅  204 no-content-type response status code for GET requests
- ~~rework tests to use proper Vault instance~~ Will do outside of this PR.

Initial ACME new-nonce API

---

changelog/19625.txt

A changelog entry was pre-emptively added for no-op functionality. Remove it for now.

changelog: Drop entry for no-op

---

builtin/logical/pki/acme/errors.go
builtin/logical/pki/acme/jws.go
builtin/logical/pki/acme/state.go
builtin/logical/pki/backend.go
builtin/logical/pki/backend_test.go
builtin/logical/pki/path_acme_directory.go
builtin/logical/pki/path_acme_new_account.go
builtin/logical/pki/path_acme_nonce.go

~This builds on top of #19803; will be rebased once that is complete.~
---
We start adding handlers for ACME accounts, and in particular, the New Account mechanism. 
One thing that isn't clear is whether the account path (from the KID) is meant to be fetched directly or not. We'll also need to handle converting the kid into a sanitized/kid-only version (without the URL) to fetch from disk.
This does make it clear though that, barring a single static RR URL for all nodes in a cluster, ACME would require the account KID to point to a specific PR cluster.

Add ACME new account creation handlers

---

website/content/docs/platform/k8s/csi/index.mdx
website/content/docs/platform/k8s/csi/installation.mdx
website/content/docs/platform/k8s/index.mdx
website/content/docs/platform/k8s/vso/api-reference.mdx
website/content/docs/platform/k8s/vso/examples.mdx
website/content/docs/platform/k8s/vso/helm.mdx
website/content/docs/platform/k8s/vso/index.mdx
website/content/docs/platform/k8s/vso/installation.mdx
website/content/docs/platform/k8s/vso/telemetry.mdx
website/content/docs/secrets/pki/considerations.mdx
website/content/partials/vso-beta-note.mdx
website/data/docs-nav-data.json

Add the initial developer documentation for the `vault-secrets-operator`.

Add vault-secrets-operator beta docs.

---

builtin/logical/pki/acme_errors.go
builtin/logical/pki/acme_jws.go
builtin/logical/pki/acme_state.go
builtin/logical/pki/acme_state_test.go
builtin/logical/pki/backend.go
builtin/logical/pki/path_acme_directory.go
builtin/logical/pki/path_acme_new_account.go

Based on #19820; will be rebased once that merges. 
```
commit 944588f57a51ad16206d9c7e57b718c96b11f9a6 (HEAD -> merge-acme-package-back-in, upstream/cipherboy-merge-acme-package-back-in)
Author: Alexander Scheel <alex.scheel@hashicorp.com>
Date:   Wed Mar 29 14:53:55 2023 -0400
Properly format errors for missing parameters
When missing required ACME request parameters, don't return Vault-level
errors, but drop into the PKI package to return properly-formatted ACME
error messages.
commit ff1ad202ac8323d21334144adae723e546da2ba9
Author: Alexander Scheel <alex.scheel@hashicorp.com>
Date:   Wed Mar 29 14:48:48 2023 -0400
Squash pki/acme package down to pki folder
Without refactoring most of PKI to export the storage layer, which we …
```

Merge ACME package back into the PKI package

---

website/content/docs/platform/k8s/csi/index.mdx
website/content/docs/platform/k8s/csi/installation.mdx
website/content/docs/platform/k8s/index.mdx
website/content/docs/platform/k8s/vso/api-reference.mdx
website/content/docs/platform/k8s/vso/examples.mdx
website/content/docs/platform/k8s/vso/helm.mdx
website/content/docs/platform/k8s/vso/index.mdx
website/content/docs/platform/k8s/vso/installation.mdx
website/content/docs/platform/k8s/vso/telemetry.mdx
website/content/partials/vso-beta-note.mdx
website/data/docs-nav-data.json

Another attempt at backporting https://github.com/hashicorp/vault/pull/19827
(Original backport is #19831)

backport of commit 25934124a046199f7434f9c61e1454bcbef08cdf

---

website/content/docs/commands/pki/index.mdx
website/content/docs/commands/pki/issue.mdx
website/content/docs/commands/pki/list-intermediates.mdx
website/content/docs/commands/pki/reissue.mdx
website/content/docs/commands/pki/verify-sign.mdx
website/data/docs-nav-data.json

🔍 [Deploy preview](https://vault-git-docs-pki-cli-addition-hashicorp.vercel.app/vault/docs/commands/pki)

Add PKI-CLI to docs

---

changelog/19846.txt
go.mod
go.sum

This PR upgrades the [vault-plugin-secrets-alicloud](https://github.com/hashicorp/vault-plugin-secrets-alicloud) dependency to the latest pseudo-version from its main branch. The plugin recently had some of its dependencies upgraded in https://github.com/hashicorp/vault-plugin-secrets-alicloud/pull/74, which is why additional `go.mod` changes are present in this PR.
Steps:
```sh
go get github.com/hashicorp/vault-plugin-secrets-alicloud@main
go mod tidy
```

plugin/secrets/alicloud: upgrade dependencies

---

website/content/api-docs/system/audit.mdx

The current API documentation doesn't specify the valid type of audit device (`string`) that can be supplied to Vault when enabling an audit backend. 
See: https://developer.hashicorp.com/vault/api-docs/system/audit#type
Adding the currently supported types available.
https://github.com/hashicorp/vault/blob/main/command/commands.go#L172-L174

Add available types to API documentation for enable audit

---

changelog/19861.txt
go.mod
go.sum

This PR upgrades the [vault-plugin-secrets-mongodbatlas](https://github.com/hashicorp/vault-plugin-secrets-mongodbatlas) dependency to the latest pseudo-version from its main branch. The plugin recently had some of its dependencies upgraded in https://github.com/hashicorp/vault-plugin-secrets-mongodbatlas/pull/42, which is why additional `go.mod` changes are present in this PR.
Steps:
```sh
go get github.com/hashicorp/vault-plugin-secrets-mongodbatlas@main
go mod tidy
```

secrets/mongodbatlas: upgrade dependencies

---

ui/app/components/namespace-picker.js
ui/app/styles/components/env-banner.scss
ui/app/styles/components/namespace-picker.scss
ui/app/templates/components/namespace-picker.hbs

The following updates have been made to the namespace picker component for use in the sidebar:
- always display the namespace when user has access to the feature (defaults to root)
- updates icons for current selected namespace
- removes back action from current namespace heading
- removes green check icon from current namespace in menu
- updates menu styling

Namespace Picker Updates

---

website/content/docs/concepts/integrated-storage/autopilot.mdx

Suggested edit based on ZenDesk ticket #102314. Customer didn't understand the default values are simply a guideline and will not fit every environment.

Added note about Autopilot default values.

---

website/content/docs/secrets/databases/oracle.mdx

This PR fixes Oracle Plugin documentation where whitespace was wrapped around various `{{username}}` or `{{password}}` fields.
Confirmed fix working at customer site.

fixes oracle plugin whitespace

---

changelog/19875.txt
helper/random/string_generator.go

A data race in vault/helper/random.(*StringGenerator).validateConfig() was exposed by new text coverage that was recently introduced. 
```
Read at 0x00c005d77000 by goroutine 10158:
github.com/hashicorp/vault/helper/random.(*StringGenerator).validateConfig()
/home/circleci/go/src/github.com/hashicorp/vault/helper/random/string_generator.go:243 +0x3e6
```
and
```
Previous write at 0x000006f28ae0 by goroutine 10155:
github.com/hashicorp/vault/helper/random.(*StringGenerator).validateConfig()
/home/circleci/go/src/github.com/hashicorp/vault/helper/random/string_generator.go:238 +0x293
```
Failure: https://app.circleci.com/pipelines/github/hashicorp/vault/51983/workflows/d654323c-baa8-4985-9838-a4131f8900f5/jobs/607405/steps

fix race condition in string generator helper

---

.github/workflows/ci.yml

This PR fixes the issue where the **browser-actions/setup-chrome** action would fail in the **test-ui** workflow job: https://github.com/hashicorp/vault/actions/runs/4575976373/jobs/8079513066
The problem was that an incorrect commit hash was being used. The proposed commit hash is the correct one and it was verified by temporarily removing the **if** condition on the **test-ui** job. This caused the job to execute in this branch: https://github.com/hashicorp/vault/actions/runs/4575747084/jobs/8078976210

Correct Issue browser-actions/setup-chrome

---

.github/workflows/test-go.yml

DataDog CI visibility test view allows you to view metrics and results from your tests in DataDog. It can help you investigate performance problems and test failures that concern you primarily because you work on the related code (and less because you maintain the pipelines they are run in).

Add DataDog test visibility to the test-go job

---

.github/workflows/test-run-enos-scenario-matrix.yml

Recently the enos-provider was updated to add automatic application log file collection for all vault and remote exec resources. This PR updates the enos run workflow to turn on this feature and to add an upload artifact step to store the logs in the build artifacts. The logs will be zipped up in a file that has the same name as the scenario that failed, with spaces being replaced by underscores.

Download Application log files and upload as an artifact when enos scenarios fail

---

website/content/api-docs/secret/pki.mdx

From discussion with UI team, this clarifies that the other operations run while tidy is paused (sleeping during this pause duration), not while tidy is not-sleeping.

Clarify that other operations run while tidy is paused

---

website/content/api-docs/system/replication/replication-dr.mdx

In testing, disabling the dr secondary requires a DR Operations token, not a vault token. See #19603
I have not looked at the code to see if additional parameters are supported.

Update api dr/secondary/disable documentation

---

builtin/logical/pki/acme_jws.go
builtin/logical/pki/acme_state.go
builtin/logical/pki/path_acme_directory.go
builtin/logical/pki/path_acme_new_account.go
builtin/logical/pki/path_acme_nonce.go

This finishes adding ACME Account storage to the engine. 
---
<details>
<summary> Testing with CertBot </summary>
```
Saving debug log to /home/cipherboy/GitHub/cipherboy/vault/letsencrypt.log
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Would you be willing, once your first certificate is successfully issued, to
share your email address with the Electronic Frontier Foundation, a founding
partner of the Let's Encrypt project and the non-profit organization that
develops Certbot? We'd like to send you email about our work encrypting the web,
EFF news, campaigns, and ways to support digital freedom.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
(Y)es/(N)o: y
Account registered.
Requesting a certificate for …
```

Add acme account storage

---

vault/activity_log.go
vault/activity_log_test.go

This makes it easier to split up the precomputed query worker and unit test its components.

VAULT-14733: Refactor processClientRecord in activity log

---

ui/app/templates/components/secret-form-show.hbs
ui/tests/acceptance/secrets/backend/cubbyhole/secret-test.js
ui/tests/acceptance/secrets/backend/kv/secret-test.js

tooltip + Version time still rendered for secret backends that don't provide that data

ui: fix empty tooltip rendering when no creation time

---

website/content/docs/auth/oci.mdx

This PR extends the effort made by https://github.com/hashicorp/vault/pull/19488
On top of the https://github.com/hashicorp/vault/pull/19488, I made format fixes with the rest. 
🔍 [Deploy Preview](https://vault-git-docs-fix-auth-oci-hashicorp.vercel.app/vault/docs/auth/oci)

OCI auth doc clean up

---

website/content/docs/configuration/index.mdx

This PR is related to https://github.com/hashicorp/vault/issues/19818
Since the `api_addr` parameter definition is on the [Vault Configuration](https://developer.hashicorp.com/vault/docs/configuration) page, updated the example configuration on that page to address `api_addr`.
🔍 [Deploy preview](https://vault-git-docs-update-config-example-hashicorp.vercel.app/vault/docs/configuration)

Updated the example config with api_addr parameter

---

website/content/api-docs/secret/ssh.mdx

The subheading states you can update a named role but for navigation purposes I think it would also make sense to add it to the heading too.

Update Create Role heading to Create/Update Role

---

ui/app/styles/components/masked-input.scss
ui/app/styles/components/sidebar.scss
ui/app/styles/core.scss
ui/app/styles/core/buttons.scss
ui/app/styles/core/element-styling.scss
ui/app/styles/core/label.scss
ui/app/styles/core/message.scss
ui/app/styles/helper-classes/typography.scss
ui/app/styles/utils/_bulma_variables.scss
ui/app/styles/utils/_font_family_variables.scss
ui/app/styles/utils/_size_variables.scss

**TLDR**: I am not replacing hard-coded size values. Instead, I cleaned up the remaining size vars, and moved out font-family vars into a separate utils folder.
**Longer version:** Originally, I had intended to replace all hard-coded sizes in the scss files with their corresponding size var (e.g. `width: 2.5rem` with `width: $size-2`). After some internal debate and feedback from teammates, I opted not to do this. At least not now and not in this sidebranch. While, yes, I _could_ replace a lot of hard-coded px and rem values with their respective `size_variable`, I think that work would eventually be overridden. Once we figure out our sizing vars (e.g. rem for size values and px for margins/padding??? or all rem) then we can override the hardcoded values. Any work to do so before this …

Finish size var clean up

---

ui/app/components/sidebar/nav/access.hbs
ui/app/components/sidebar/nav/cluster.hbs
ui/app/components/sidebar/nav/policies.hbs
ui/app/routes/vault/cluster.js
ui/app/routes/vault/cluster/clients.js
ui/app/templates/vault/cluster.hbs
ui/app/templates/vault/cluster/clients.hbs
ui/app/templates/vault/cluster/clients/loading.hbs
ui/tests/integration/components/sidebar/nav/access-test.js
ui/tests/integration/components/sidebar/nav/cluster-test.js
ui/tests/integration/components/sidebar/nav/policies-test.js

There were some issues with the sidebar nav animations where the access template was re-rendering each time a child route was navigated to causing the cluster nav to briefly show during the transition. This was caused by the loading event that was handled in the cluster route which was conditionally showing the `LogoSplash` and removing the outlet during the transition. As such the access route would need to render again once the loading event was finished. The loading event handler was removed in favor of using the loading templates, which there were several in place that weren't actually being rendered.
There was also an issue with the animation between the access and policies routes. Since the policies route isn't actually a child of access, the slide animation will not work since it …

Sidebar Animation Glitch Fixes

---

ui/app/styles/core/buttons.scss
ui/app/styles/core/columns.scss
ui/app/styles/core/control.scss
ui/app/styles/core/field.scss
ui/app/styles/core/inputs.scss
ui/app/styles/core/label.scss
ui/app/styles/core/layout.scss
ui/app/styles/core/menu.scss
ui/app/styles/core/navbar.scss
ui/app/styles/core/select.scss
ui/app/styles/core/tag.scss
ui/app/styles/helper-classes/flexbox-and-grid.scss

I suspected there would be some regression after I did all the var and core file work. There was, and while I have tickets for specifically broken things (that have always been broken on this branch), I wanted to tackle some of these regressions before moving forward.
* splash screen page-container (tested desktop, mobile and tablet)
* fixed `button.is-primary.is-outlined` styles.
* fixed some issues on inputs. They now all seem to look good (not the final qa but so far so good).
* fixed a status menu alignment issue. 
* I thought I could get away with a 13.75 px value instead of 14px and that backfired. Fixed on labels.
I know each of these changes won't make a lot of sense at this point because it's nearly impossible to tell from this PR what is bulma and what was original scss. …

Small fixes post var and core file work

---

website/content/docs/platform/k8s/vso/helm.mdx

I was wondering why the default VaultAuth CR was not created. It was due the fact that I copy/pasted the snippet from the docs here, which has the wrong key.

Replace defaultVaultAuthMethod with defaultAuthMethod in Snippet

---

website/content/docs/upgrading/upgrade-to-1.13.x.mdx

Updates the upgrade guide to include documentation about a known issue causing STS lease_duration to become zero.

add upgrade documentation around STS lease_duration issue

---

go.mod

Point vault to the latest version of `vault/sdk`

Use vault/sdk v0.9.0

---

website/content/docs/configuration/service-registration/kubernetes.mdx
website/content/docs/platform/k8s/helm/configuration.mdx
website/content/docs/platform/k8s/helm/enterprise.mdx
website/content/docs/platform/k8s/helm/examples/enterprise-dr-with-raft.mdx
website/content/docs/platform/k8s/helm/examples/enterprise-perf-with-raft.mdx
website/content/docs/platform/k8s/helm/examples/enterprise-with-raft.mdx
website/content/docs/platform/k8s/helm/run.mdx
website/content/partials/helm/install.mdx
website/content/partials/helm/repo.mdx

Release: https://github.com/hashicorp/vault-helm/releases/tag/v0.24.0

Update docs for Helm 0.24.0 release

---

vault/rollback.go

When testing the Rollback Manager's one-time invocation in Enterprise, it was noticed that due to the channel being closed, we'd always hit this case and thus spam logs rather quickly with this message.
Switch to a boolean flip to log this once, as it is not executed in parallel and thus doesn't need a `sync.Once`.
This only affected anyone calling the test core's `StopAutomaticRollbacks()` helper.
This was introduced in #19748 though the enterprise counterpart had not merged yet.

Only log stopping rollback manager once

---

website/content/docs/commands/token/create.mdx

This PR manually cherry-pick https://github.com/hashicorp/vault/pull/19981 
Add the missing Command Option `-wrap-ttl`

[Backport] Update create.mdx (#19981)

---

website/content/docs/configuration/index.mdx

The automatic backport did not get triggered for [PR 19985](https://github.com/hashicorp/vault/pull/19985). 😢
So, this PR manually cherry-picks the commit.

Updated the example config with api_addr parameter (#19985)

---

builtin/logical/pki/crl_util.go
changelog/20057.txt

When the PBPWF fails on the Active node of a PR Secondary cluster with a read-only failure, there is no value in forwarding this request up to the Active node of the PR Primary cluster: it does not have the local revocation context necessary to write a Delta WAL entry for this request, and would likely end up writing a cross-cluster revocation entry (if it is enabled) or else erring completely.
Instead, log this error like we do when failing to write unified CRL entries. Switch both to using Error instead of Debug for this type of failure.

Log, don't err, on unified delta WAL write failure

---

website/content/api-docs/secret/ldap.mdx

The endpoint to [generate dynamic creds](https://github.com/hashicorp/vault-plugin-secrets-openldap/blob/aaefa7ce8d0b0f5c724f6c902534fae533849052/path_dynamic_creds.go#L21) is missing from the [API docs](https://developer.hashicorp.com/vault/api-docs/secret/ldap#dynamic-roles).

secrets/openldap: add creds/ endpoint to API docs

---

helper/testhelpers/testhelpers.go

Sometimes the tests will modify the client to set a namespace; this results in `testhelpers` sometimes trying to access `sys/` endpoints with a namespace, which usually don't work well.
Detect an unset namespaces, if present, before executing, and restore afterwards so as not to affect the tests.

Support namespaces in test helpers

---

builtin/logical/pki/storage.go

When reading the config, we attempt to detect if the running Vault instance has been changed from its Enterprise status on write. Similarly, we should detect if the mount is a local mount instead. While this isn't changeable at runtime, using sys/raw to side-load an invalid config could be possible.

Make config load consistent with config write

---

changelog/20078.txt
vault/logical_system_activity.go

This PR adds a check when updating the activity log config so that the retention months are greater than a minimum value when reporting is enabled.

Require activity log retention months at least the minimum

---

website/content/docs/auth/jwt/oidc-providers/azuread.mdx

Fix list formatting per [Jira request](https://hashicorp.atlassian.net/browse/SPE-71?atlOrigin=eyJpIjoiOWMzODI4NDY4ODA2NDNhNDk2MTAwNzA5NWZlZTRkMjUiLCJwIjoiaiJ9)
- Change spacing on ordered and nested unordered lists

Fix list formatting

---

.github/workflows/test-run-enos-scenario-matrix.yml

Artifact upload action fails to find relative path to upload the debug data directory, so moving it to /tmp for easier find and cleanup

Use absolute path for debug datadir

---

vault/testing.go
vault/testing_util.go

The extra core setup is no longer needed in Vault Enterprise, and the licensing code here has no effect here or in Vault Enterprise.
I pulled this commit into Vault Enterprise and it still compiled fine, and all tests pass. (Though a few functions can be deleted there as well after this is merged.)

Remove dead licensing code and extra core setup

---

changelog/20064.txt
ui/.template-lintrc.js
ui/app/templates/components/console/log-command.hbs
ui/app/templates/components/console/log-help.hbs
ui/app/templates/components/console/log-list.hbs
ui/tests/integration/components/console/log-command-test.js

During the Ember upgrade to 3.24 we implemented some linting changes that inadvertently affected the browser console’s output. Each command should be on a separate line. Fixes #19568 
- each command is on a separate line
- previous command displays beside chevron icon `>` (not on line below)

UI: fix browser console formatting

---

builtin/logical/pki/crl_util.go
builtin/logical/pki/periodic.go
changelog/20058.txt

Built on top of #20057; will be rebased once that merges.
---
Perhaps best to review this commit by commit as it should make most sense that way. If short summaries are nice:
1. We only considered certificates from the current primary cluster when building the unified delta CRL.
2. We only considered last-revoked serials from the current primary cluster when deciding to build the unified delta CRL.
3. We only wrote out last-revoked serials to the current primary cluster's last-built entry, meaning if 2 wasn't also a bug, we could potentially rebuild more frequently than necessary (without new revocations).
4. When doing the build, the last read serial wasn't the current primary cluster's cross-cluster last revoked serial, but instead its local delta WAL last revoked serial. These entries …

Fix building unified delta WAL, unified delta CRLs

---

sdk/framework/field_type.go

This PR just fixes a misleading comment typo in the sdk package.

Fix RFC3339 comment typo

---

website/content/api-docs/secret/kv/kv-v2.mdx

🔍 [Deploy preview](https://vault-git-docs-update-kv-destroy-doc-hashicorp.vercel.app/vault/api-docs/secret/kv/kv-v2#destroy-secret-versions)
This PR fixes an issue reported by https://hashicorp.atlassian.net/browse/VAULT-15124
**Summary:**
The `-output-curl-string` command returns `PUT` as the HTTP verb, but the API doc uses `POST`. Since it works either `PUT` or `POST`, updates the doc for consistency.

[Docs] Update the KV v2 API docs 

---

builtin/logical/pki/acme_jws.go
builtin/logical/pki/acme_state.go
builtin/logical/pki/path_acme_new_account.go

Based on top of #19949, switch out the existing kid value being a thumbprint of the public key to a UUID generated value so we can properly support the key-change ACME semantics at a later time. This is required as the kid should not change when the backing account key changes.

Use a UUID for ACME kid instead of a key fingerprint

---

builtin/logical/pki/acme_authorizations.go
builtin/logical/pki/acme_jws.go
builtin/logical/pki/acme_state.go
builtin/logical/pki/backend.go
builtin/logical/pki/backend_test.go
builtin/logical/pki/path_acme_authorizations.go
builtin/logical/pki/path_acme_challenges.go

This adds the data structures and path handling for ACME authorization and challenge objects in the PKI engine.
Currently the logic around creating these objects hasn't yet been implemented, as pre-authz likely won't be supported in the first pass, so we'll only create these objects as a result of Orders (which aren't yet implemented either).

Add ACME authorizations & challenges

---

website/content/api-docs/secret/transit.mdx
website/content/api-docs/system/managed-keys.mdx
website/content/docs/enterprise/managed-keys.mdx

This helps clarify use of Managed Keys in the Transit secrets engine and describes the limitations of support for convenience functionality (e.g. automatic key generation.)

Update docs to include specifics and caveats around Transit Managed Keys support.

---

builtin/plugin/backend.go
sdk/logical/logical.go
sdk/plugin/plugin.go
sdk/plugin/plugin_v5.go
vault/auth.go
vault/mount.go
vault/plugin_reload.go

Following on from https://github.com/hashicorp/vault/pull/19814#discussion_r1153698708, this PR removes the `logical.Externaler` interface in favour of checking for a running SHA256 value, which will always be populated when the plugin is external, and will always be empty when it's builtin.

Simplify tracking of external plugins

---

website/content/api-docs/secret/kv/kv-v2.mdx

https://github.com/hashicorp/vault/pull/20101 throws CLA check failure which I cannot solve.
So, this PR manually cherry-picks the https://github.com/hashicorp/vault/pull/20056

[Backport] Update the HTTP verb for consistency (#20056)

---

builtin/credential/ldap/backend_test.go
changelog/20144.txt
sdk/helper/ldaputil/client.go
sdk/helper/ldaputil/config.go
sdk/helper/ldaputil/config_test.go
website/content/api-docs/auth/ldap.mdx
website/content/api-docs/secret/ad.mdx
website/content/api-docs/secret/ldap.mdx

The go-ldap package sets a 60 second timeout in their package for dial attempts which aligns with Vault's 60 second client timeout. Since these timeouts are the same if the first value in our LDAP config `url` is unavailable, no other URLs in the list will be tried and all connections will fail. 
This adds a new LDAP config `connection_timeout` which allows operators to override this timeout value. By setting this value lower you can leverage the backup URLs in the config.
This is not the same as the existing config `request_timeout` which tunes timeout values *after* a connection is made to LDAP.
A workaround exists where clients can set `VAULT_CLIENT_TIMEOUT`. By adding this config though we can set timeouts for all user connections and may be a better overall experience.

sdk/ldaputil: add connection_timeout configurable

---

changelog/20150.txt
vault/activity_log_test.go
vault/logical_system_activity.go

This PR cleans up the expected results from the last config endpoint update and adds a new field for use in the UI.
Changelog to come.

Add minimum_retention_months to config endpoint

---

builtin/credential/cert/backend_test.go
builtin/credential/cert/path_certs.go
builtin/credential/cert/path_login_test.go
changelog/20154.txt

Per conversation with @hellobontempo, cert auth UI uses the open API data to determine fields. In our case, these fields were already present, but we needed to return them from the read API response status for them to be visible in the UI. Otherwise, they'd be set server side (on the first submission), but any further changes would potentially overwrite them as the UI would use default/zero values for the fields it doesn't see.

Add missing cert auth ocsp read data

---

.github/enos-run-matrices/build-github-oss-linux-amd64-zip.json
.github/enos-run-matrices/build-github-oss-linux-arm64-zip.json
.github/enos-run-matrices/enos_release_testing_oss-artifactory-oss-linux-amd64-zip.json
.github/enos-run-matrices/enos_release_testing_oss-artifactory-oss-linux-arm64-zip.json
.gitignore
enos/ci/service-user-iam/main.tf
enos/ci/service-user-iam/service-quotas.tf
enos/enos-modules.hcl
enos/enos-scenario-agent.hcl
enos/enos-scenario-autopilot.hcl
enos/enos-scenario-replication.hcl
enos/enos-scenario-smoke.hcl
enos/enos-scenario-ui.hcl
enos/enos-scenario-upgrade.hcl
enos/modules/target_ec2_instances/main.tf
enos/modules/target_ec2_instances/outputs.tf
enos/modules/target_ec2_instances/variables.tf
enos/modules/target_ec2_spot_fleet/main.tf
enos/modules/target_ec2_spot_fleet/outputs.tf
enos/modules/target_ec2_spot_fleet/variables.tf
enos/modules/vault_cluster/main.tf
enos/modules/vault_cluster/outputs.tf
enos/modules/vault_cluster/templates/install-packages.sh
enos/modules/vault_cluster/templates/vault-write-license.sh
enos/modules/vault_cluster/variables.tf

The previous strategy for provisioning infrastructure targets was to use
the cheapest instances that could reliably perform as Vault cluster
nodes. With this change we introduce a new model for target node
infrastructure. We've replaced on-demand instances for a spot
fleet. While the spot price fluctuates based on dynamic pricing, 
capacity, region, instance type, and platform, cost savings for our
most common combinations range between 20-70%.
This change only includes spot fleet targets for Vault clusters.
We'll be updating our Consul backend bidding in another PR.
* Create a new `vault_cluster` module that handles installation,
configuration, initializing, and unsealing Vault clusters.
* Create a `target_ec2_instances` module that can provision a group of
instances on-demand.
* Create …

[QT-525] enos: use spot instances for Vault targets

---

changelog/20125.txt
ui/app/components/clients/config.js
ui/app/decorators/model-validations.js
ui/app/models/clients/config.js
ui/app/templates/components/clients/config.hbs
ui/app/templates/components/clients/dashboard.hbs
ui/app/templates/vault/cluster/clients.hbs
ui/app/templates/vault/cluster/clients/config.hbs
ui/tests/integration/components/clients/config-test.js

The following updates were made to the clients configuration edit view to accommodate census reporting:
- Adds validation to the retention period form field. Value must be 0 or greater if reporting is disabled and a minimum of 24 with reporting enabled
- The data collection toggle is disabled when reporting is enabled
- Copy updates to modal when enabling data collection
- Model validations were expanded to support a function for the message property

Clients config updates for census reporting

---

sdk/framework/path.go

Fixing the comments for `OperationPrefix` / `OperationVerb` / `OperationSuffix` used to construct OpenAPI operation ID's.

openapi: Better comments for OperationPrefix/Verb/Suffix

---

changelog/20044.txt
command/server/config.go
http/sys_config_state_test.go

This PR adds a `raft` sub-field to the [sanitized config](https://developer.hashicorp.com/vault/api-docs/system/config-state#get-sanitized-configuration-state) storage and HA storage details in order to expose Raft's [max_entry_size](https://developer.hashicorp.com/vault/docs/configuration/storage/raft#max_entry_size).

add max_entry_size to sanitized config output

---

builtin/logical/pki/acme_authorizations.go
builtin/logical/pki/acme_state.go
builtin/logical/pki/backend.go
builtin/logical/pki/backend_test.go
builtin/logical/pki/path_acme_authorizations.go
builtin/logical/pki/path_acme_order.go
builtin/logical/pki/path_acme_test.go

Implement some of the order ACME APIs, new-order, list-order and get-order. This does not implement the finalize nor the final cert fetch order APIs, that will come in a future PR.

Implement ACME order API

---

builtin/logical/pki/acme_authorizations.go
builtin/logical/pki/acme_errors.go
builtin/logical/pki/acme_jws.go
builtin/logical/pki/acme_state.go
builtin/logical/pki/acme_state_test.go
builtin/logical/pki/acme_wrappers.go
builtin/logical/pki/path_acme_authorizations.go
builtin/logical/pki/path_acme_challenges.go
builtin/logical/pki/path_acme_directory.go
builtin/logical/pki/path_acme_new_account.go
builtin/logical/pki/path_acme_nonce.go
builtin/logical/pki/path_acme_order.go
builtin/logical/pki/path_acme_test.go

- Make it easier to figure out where the various wrappers for ACME exist by locating them inside a dedicated go file instead of spread out across the various path_acme_xxx files.
- No code changes have occurred within this PR, just moving code around.

Move all ACME wrappers into a dedicated go file

---

builtin/logical/pki/acme_wrappers.go
builtin/logical/pki/backend.go
builtin/logical/pki/path_acme_authorizations.go
builtin/logical/pki/path_acme_challenges.go
builtin/logical/pki/path_acme_directory.go
builtin/logical/pki/path_acme_new_account.go
builtin/logical/pki/path_acme_nonce.go
builtin/logical/pki/path_acme_order.go

I got tired of defining all the various flavors of the ACME API patterns, so this helper function allows us to define the base and we will dynamically generate the various framework.Path definitions to be used. 
- `/acme/orders`
- `/roles/<role>/acme/orders`
- `/issuer/<issuer>/acme/orders`
- `/issuer/<issuer>/roles/<role>/acme/orders`

Add a helper function to build PKI ACME API patterns

---

ui/app/components/sidebar/frame.hbs
ui/app/styles/components/console-ui-panel.scss
ui/app/templates/components/console/log-command.hbs
ui/app/templates/components/console/ui-panel.hbs

This PR moves the console panel from the top of the viewport to the bottom to improve UX and give it a more natural feel.
Before
_As you can see in the screenshot the close button is pushed up when the content scrolls. This has been fixed to anchor it to the top right of the panel._
After

Move console panel to bottom

---

changelog/20181.txt
sdk/helper/ocsp/client.go
sdk/helper/ocsp/ocsp_test.go

When calling `ocsp.ParseRequest(req, issue)` with a non-nil `issuer` on a ocsp request which _unknowingly_ contains an entry in the `BasicOCSPResponse`'s `certs` field, Go incorrectly assumes that the issuer is a direct parent of the _first_ certificate in the `certs` field, discarding the rest.
As documented in the Go issue, this is not a valid assumption and thus causes OCSP verification to fail in Vault with an error like:
> ```
> bad OCSP signature: crypto/rsa: verification error
> ```
which ultimately leads to a cert auth login error of:
> ```
> no chain matching all constraints could be found for this login certificate
> ```
We address this by using the unsafe `issuer=nil` argument, taking on the task of validating the OCSP response's signature as best we can in the absence of full …

Add fix for Go x/crypto/ocsp failure case

---

ui/lib/pki/addon/routes/application.js
ui/lib/pki/addon/routes/certificates/index.js
ui/lib/pki/addon/routes/configuration/create.js
ui/lib/pki/addon/routes/configuration/index.js
ui/lib/pki/addon/routes/issuers/generate-intermediate.js
ui/lib/pki/addon/routes/issuers/import.js
ui/lib/pki/addon/routes/issuers/index.js
ui/lib/pki/addon/routes/issuers/issuer.js
ui/lib/pki/addon/routes/issuers/issuer/cross-sign.js
ui/lib/pki/addon/routes/issuers/issuer/details.js
ui/lib/pki/addon/routes/issuers/issuer/edit.js
ui/lib/pki/addon/routes/issuers/issuer/rotate-root.js
ui/lib/pki/addon/routes/issuers/issuer/sign.js
ui/lib/pki/addon/routes/keys/create.js
ui/lib/pki/addon/routes/keys/import.js
ui/lib/pki/addon/routes/keys/index.js
ui/lib/pki/addon/routes/keys/key.js
ui/lib/pki/addon/routes/keys/key/details.js
ui/lib/pki/addon/routes/keys/key/edit.js
ui/lib/pki/addon/routes/overview.js
ui/lib/pki/addon/routes/roles/index.js
ui/lib/pki/addon/routes/roles/role/generate.js
ui/lib/pki/addon/routes/roles/role/sign.js
ui/lib/pki/addon/templates/certificates/index.hbs
ui/lib/pki/addon/templates/issuers/index.hbs
ui/lib/pki/addon/templates/keys/index.hbs
ui/lib/pki/addon/templates/overview.hbs
ui/lib/pki/addon/templates/roles/index.hbs

This PR untangles the routing for the PKI engine. Extending other routes was causing confusion and it wasn't clear why some routes were even extended. As part of this PR, all the PKI models using openAPI are also instantiated at the engine application route so that the models are hydrated and available for the rest of the engine.

UI: PKI routes extend base Route

---

changelog/20044.txt
command/server/config.go
http/sys_config_state_test.go

This PR is was meant to be auto-generated from #20044 but there were merge conflicts so I am opening up a new PR with a manual cherry-pick.
---
This PR adds a `raft` sub-field to the [sanitized config](https://developer.hashicorp.com/vault/api-docs/system/config-state#get-sanitized-configuration-state) storage and HA storage details in order to expose Raft's [max_entry_size](https://developer.hashicorp.com/vault/docs/configuration/storage/raft#max_entry_size).
---
<details>
<summary> Overview of commits </summary>
- ca702745e8bb68994fd2e323dfba78f144abbcb8 
</details>

add max_entry_size to sanitized config output (#20044)

---

builtin/logical/pki/acme_challenges.go
builtin/logical/pki/acme_challenges_test.go
builtin/logical/pki/acme_state.go
builtin/logical/pki/path_acme_order.go
builtin/logical/pki/path_acme_test.go

This adds the initial challenge validation function for the HTTP-01 challenge, checking the remote server for the presence of the specified key authorization. We attempt to set some safety timeouts and buffers to avoid endlessly hanging the Vault server.

Add ACME HTTP-01 Challenge

---

sdk/helper/ldaputil/client.go
sdk/helper/ldaputil/ldap.go

I recently merged https://github.com/hashicorp/vault/pull/20144 which adds connection timeout configuration, however, this was causing race tests to fail since it was changing a package variable. To fix this, I've changed the LDAP interface to use the suggested `ldap.DialURL` function instead of the deprecated `ldap.Dial` and `ldap.DialTLS` functions.

sdk/ldap: update interface to use DialURL

---

changelog/19862.txt
scripts/build.sh

Currently if the $GOPATH/bin directory does not exist, the binary will fail to be copied to the location.
I don't believe an if statement is needed to check for directory existence before the mkdir command, it simply does nothing when the directory already exists.
Closes https://github.com/hashicorp/vault/issues/7170

build: try creating the go bin directory

---

builtin/logical/pki/storage.go
changelog/20220.txt
website/content/api-docs/secret/pki.mdx

Fix PKI issuer upgrade logic when upgrading to 1.12 or later, to
actually turn off the issuer crl-signing usage when it intended to.
Fix minor typo in docs.
Closes #20189

Minor follow-ups to #16865

---

ui/app/styles/components/auth-buttons.scss
ui/app/styles/components/auth-form.scss
ui/app/styles/components/b64-toggle.scss
ui/app/styles/components/box-radio.scss
ui/app/styles/components/confirm.scss
ui/app/styles/components/console-ui-panel.scss
ui/app/styles/components/hover-copy-button.scss
ui/app/styles/components/icon.scss
ui/app/styles/components/license-banners.scss
ui/app/styles/components/list-pagination.scss
ui/app/styles/components/masked-input.scss
ui/app/styles/components/namespace-picker.scss
ui/app/styles/components/page-header.scss
ui/app/styles/components/popup-menu.scss
ui/app/styles/components/tabs.scss
ui/app/styles/components/vlt-table.scss
ui/app/styles/core/breadcrumb.scss
ui/app/styles/core/buttons.scss
ui/app/styles/core/file.scss
ui/app/styles/core/footer.scss
ui/app/styles/core/inputs.scss
ui/app/styles/core/level.scss
ui/app/styles/core/progress.scss
ui/app/styles/core/toggle.scss
ui/app/styles/utils/_font_variables.scss
ui/app/styles/utils/_size_variables.scss
ui/tests/integration/components/kubernetes/page/configure-test.js
ui/tests/integration/components/pki/pki-role-form-test.js

**TLDR** 
* This pr removes any out of scope changes from my side branch. This includes changing hardcode values to vars and adding extra spaces between class definitions.
* Small changes to get tests passing.
Jordan had left a comment on my[ last PR](https://github.com/hashicorp/vault/pull/20196/files#diff-e4a6c8154565bc0b278bb723063e63dbe12a4a035070225aa3770e96a8ae0100) about changing hardcode px or rem values to vars. Ex: `padding: 1rem` to `padding: $size-6`. After looking at my sidebranch diff against main I saw how doing this extra work had done a number on the already large file count. If we decide as a team that it's worth going through all previously hard-coded rem and px and replacing them with size vars when applicable we can do that. However, to keep the scope of this PR as …

Remove out of scope changes

---

website/content/docs/commands/debug.mdx

Adding an example policy for creating debug packages.

docs/debug: add example policy for debug command

---

.github/workflows/build.yml
.github/workflows/ci.yml
.github/workflows/milestone-checker.yml

Right now UI tests only run on: 
>   - pushes to main and branches starting with "release/"
>   - PRs where the branch starts with "ui/", "backport/ui/", "merge", or when base branch starts with "release/"
This adds an additional conditional to run tests for PRs that have the `ui` label so tests can run without special branch naming.

Run UI tests on PRs with "ui" label

---

website/content/docs/platform/k8s/csi/configurations.mdx

Added in https://github.com/hashicorp/vault-csi-provider/pull/194, and released in [v1.3.0](https://github.com/hashicorp/vault-csi-provider/releases/tag/v1.3.0).

Docs: CSI encoding config released in v1.3.0

---

website/content/partials/tokenfields.mdx

🎫 [Github issue](https://github.com/hashicorp/vault/issues/18361)
🔍 [Deploy preview](https://vault-git-docs-update-tokenfields-partial-hashicorp.vercel.app/vault/api-docs/auth/kubernetes#policies)
This PR updates the token fields list, and mark the `policies` parameter as deprecated in favor of `token_policies` (see the [code](https://github.com/hashicorp/vault-plugin-auth-kubernetes/blob/530b5e913097cf7eea6ff1e2d7b977dd3dba2a16/path_role.go#L65-L69)).
See the [Github issue](https://github.com/hashicorp/vault/issues/18361) for more context.

[Docs] Mark the 'policies' parameter as deprecated for tokens

---

website/content/api-docs/secret/databases/postgresql.mdx

Update the postgresql secret engine API docs to include some "caveats"
of the pgx library. In particular, this enhances the docs to inform the
user that if any sslcreds are supplied as a part of the Database
connection string, the user/vault admin will need to ensure that the
certificates are present at those paths.

docs(postgresql): Update Postgresql SE API doco

---

builtin/credential/cert/path_login.go
changelog/20234.txt

This returns OCSP validation errors (that aren't simply a revoked certificate) to the login client, hopefully helping them to understand why their request was rejected (if by OCSP or otherwise). 
We make an attempt to deduplicate these errors.

Return OCSP errors on cert auth login failures

---

changelog/20243.txt
command/namespace_list.go
website/content/docs/commands/namespace.mdx

This enhances the namespace list command to include a `detailed` flag which will output additional data such as namespace IDs. This is very useful because without this you would either need to use curl or do a `vault namespace lookup` for every namespace you wanted the ID for in a loop. This lets you get all the information in one command:
```bash
$ vault namespace list -detailed
Keys    custom_metadata    id       path
----    ---------------    --       ----
bar/    map[]              yva5e    bar/
foo/    map[]              iZULg    foo/
$ vault namespace list -detailed -format=json
{
"bar/": {
"custom_metadata": {},
"id": "yva5e",
"path": "bar/"
},
"foo/": {
"custom_metadata": {},
"id": "iZULg",
"path": "foo/"
}
}
```

cli/namespace: add detailed flag to namespace list

---

changelog/20235.txt
ui/app/components/diff-version-selector.js
ui/app/components/wizard-content.js
ui/app/components/wizard/features-selection.js
ui/app/templates/components/diff-version-selector.hbs
ui/app/templates/components/wizard-progress.hbs
ui/lib/core/addon/components/confirm.js
ui/lib/core/addon/components/replication-dashboard.js
ui/lib/core/addon/helpers/sanitized-html.js
ui/lib/core/addon/templates/components/replication-dashboard.hbs
ui/lib/core/app/helpers/sanitized-html.js
ui/lib/core/package.json
ui/lib/kubernetes/addon/components/page/role/create-and-edit.hbs
ui/lib/kubernetes/addon/components/page/role/create-and-edit.js
ui/package.json
ui/tests/integration/helpers/sanitized-html-test.js
ui/yarn.lock

This PR removes ad-hoc usages of htmlSafe and replaces it with a custom helper which sanitizes the HTML string before passing it to `htmlSafe`

UI: Remove usage of htmlSafe

---

builtin/credential/aws/path_role.go
builtin/credential/cert/path_certs.go
builtin/credential/ldap/path_groups.go
builtin/credential/ldap/path_users.go
builtin/credential/okta/path_groups.go
builtin/credential/radius/path_config.go
builtin/credential/radius/path_users.go
builtin/credential/userpass/path_user_policies.go
changelog/20163.txt
sdk/framework/path.go
sdk/helper/tokenutil/tokenutil.go
ui/app/components/generated-item.js
ui/app/models/pki/certificate/base.js
ui/app/models/pki/issuer.js
ui/app/models/pki/role.js
ui/app/models/pki/urls.js
ui/app/styles/core/forms.scss
ui/app/utils/openapi-to-attrs.js
ui/lib/core/addon/components/form-field.hbs
ui/lib/core/addon/components/string-list.hbs
ui/lib/core/addon/components/string-list.js
ui/lib/pki/addon/components/pki-generate-toggle-groups.hbs
ui/lib/pki/addon/components/pki-key-usage.hbs
ui/tests/acceptance/auth-list-test.js
ui/tests/integration/components/pki/pki-generate-root-test.js
ui/tests/integration/components/string-list-test.js
ui/tests/unit/utils/openapi-to-attrs-test.js

Models that build from openApi use the `description` key as `helpText` which renders as a tooltip beside the label. These descriptions are written for CLI users and so the tooltips are misleading in the UI for inputs with `editType: stringArray`. The tooltip will say to input `comma separated` values, but the UI doesn't actually accept this for that specific input type.
This PR: 
1. Adds a new `description` block to the `DisplayAttributes` struct that generates an attrs open api schema
2. globally adds `Add one item per row` as subtext to all `<StringList>` inputs rendered by the `<FormField>` component (which all models that leverage openAPI use) 
3. adds a warning to the `<StringList>` input itself if a comma exists and reminding to input separate values individually
Fixes …

UI: remove references to comma separation for string array edit types

---

ui/app/styles/components/tabs.scss
ui/app/styles/core/checkbox-and-radio.scss
ui/app/templates/components/transit-key-action/datakey.hbs
ui/app/templates/components/transit-key-action/decrypt.hbs
ui/app/templates/components/transit-key-action/encrypt.hbs
ui/app/templates/components/transit-key-action/hmac.hbs
ui/app/templates/components/transit-key-action/rewrap.hbs
ui/app/templates/components/transit-key-action/verify.hbs

* Fixes current issue with active tabs on auth mounts not showing. While this is a current/main issue, I fixed on this branch as it's wrapped up in the new CSS structure.
Before:
After:
* A fix I'm arguing we shouldn't make. At the very top of the css heirarchy we say that all links should be text underline `a {text-transform: underline}`. We then proceed to override this in most all cases, except when we forget. An example of when we forget (I think) is on `Secret Engine-> Transform -> create an alphabet -> Look at the list view`. Here's a screenshot, binary on the left, my branch on the right. I'm going to argue we keep it `a { text-transform: none}` which was my css to clean up all the overriding. **Thoughts?**

Fixes found while QA'ing Secret Engines

---

api/client.go
changelog/20265.txt

Without this method, there's no way to obtain the TLSConfig of a client.
This is extracted from #20224 so that the sdk changes can depend on it.

Add new method to access a client config's TLSConfig.

---

builtin/logical/pki/integration_test.go
sdk/helper/ocsp/ocsp_test.go

This prevents SDK from having a circular import on the main Vault package.
---
@ncabatoff As this didn't yet make it into a release of the SDK, I don't think I'll need a changelog entry?

Move OCSP/PKI interop test to PKI engine

---

sdk/helper/consts/consts.go
vault/core.go
vault/testing.go

OSS changes for https://github.com/hashicorp/vault-enterprise/pull/3826

OSS changes for new update-primary API endpoint

---

changelog/20257.txt
command/server.go
command/server/config.go
command/server/config_test.go
command/server_test.go

The -dev-tls command wasn't working on windows, because the filepaths in the hcl config had unescaped backslashes. This PR adds escaping.
I also tested the changes on a windows VM, and confirmed that they resolved the problem.
Closes #20038

VAULT-15668: fix windows issues with -dev-tls flag 

---

builtin/logical/pki/acme_authorizations.go
builtin/logical/pki/acme_errors.go
builtin/logical/pki/acme_state.go
builtin/logical/pki/backend.go
builtin/logical/pki/backend_test.go
builtin/logical/pki/cert_util.go
builtin/logical/pki/crl_test.go
builtin/logical/pki/path_acme_order.go
builtin/logical/pki/path_acme_test.go

Implement ACME CSR signing and certificate retrieval. This at the moment will only use the default issuer along with a sign-verbatim style role. Leveraging the proper issuer/role will come in a later PR.

Implement ACME CSR signing and certificate retrieval

---

.github/scripts/verify_changes.sh
.github/workflows/build.yml

Skip builds and Enos tests for docs PRs.  Following https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks we conditionally skip the jobs.

[QT-517] Skip builds for docs PRs

---

builtin/logical/pki/acme_authorizations.go
builtin/logical/pki/acme_state.go
builtin/logical/pki/cert_util.go
builtin/logical/pki/path_acme_order.go
builtin/logical/pki/path_acme_test.go

This refactors `pki/cert_util.go`'s wildcard validation, moving it into separate helper functions for use by ACME.
Per RFC 8555, various limitations around wildcards are enforced and authorizations should not include the original label in the identifier (just the non-wildcard domain suffix and asserting `wildcard` on the authz entry). 
We additionally enforce that DNS-typed entries are not IP addresses, as `idna.ValidateForRegistration(...)` does not enforce this for IPv4 addresses.  
Lastly, we restrict challenge types for IP and wildcard authorizations.

Better ACME wildcard validation

---

website/content/docs/platform/k8s/injector/index.mdx

From every other example I can find, the secret name in the template should match the one in the inject annotation. Indeed the same example appears in the examples page.
https://github.com/hashicorp/vault/blob/main/website/content/docs/platform/k8s/injector/examples.mdx#patching-existing-pods

Docs: Fix k8s injector templating example

---

vault/activity_log.go
vault/activity_log_test.go
vault/activity_log_util.go
vault/census.go
vault/core.go
vault/logical_system_activity.go
vault/testing.go

This is the OSS portion of https://github.com/hashicorp/vault-enterprise/pull/3952

Refactor reporter for unseal setup

---

enos/modules/target_ec2_instances/main.tf
enos/modules/target_ec2_spot_fleet/main.tf

The security groups that allow access to remote machines in Enos scenarios have been configured to only allow port 22 (SSH) from the public IP address of machine executing the Enos scenario. To achieve this we previously utilized the `enos_environment.public_ip_address` attribute. Sometime in mid March we started seeing sporadic SSH i/o timeout errors when attempting to execute Enos resources against SSH transport targets. We've only ever seen this when communicating from Azure hosted runners to AWS hosted machines.
While testing we were able to confirm that in some cases the public IP address resolved using DNS over UDP4 to Google and OpenDNS name servers did not match what was resolved when using the HTTPS/TCP IP address service hosted by AWS. The Enos data source was implemented in a …

[QT-530] enos: allow-list all public IP addresses

---

.github/enos-run-matrices/build-github-oss-linux-amd64-zip.json
.github/enos-run-matrices/build-github-oss-linux-arm64-zip.json
.github/enos-run-matrices/enos_release_testing_oss-artifactory-oss-linux-amd64-zip.json
.github/enos-run-matrices/enos_release_testing_oss-artifactory-oss-linux-arm64-zip.json
.gitignore
enos/ci/service-user-iam/main.tf
enos/ci/service-user-iam/service-quotas.tf
enos/enos-modules.hcl
enos/enos-scenario-agent.hcl
enos/enos-scenario-autopilot.hcl
enos/enos-scenario-replication.hcl
enos/enos-scenario-smoke.hcl
enos/enos-scenario-ui.hcl
enos/enos-scenario-upgrade.hcl
enos/modules/target_ec2_instances/main.tf
enos/modules/target_ec2_instances/outputs.tf
enos/modules/target_ec2_instances/variables.tf
enos/modules/target_ec2_spot_fleet/main.tf
enos/modules/target_ec2_spot_fleet/outputs.tf
enos/modules/target_ec2_spot_fleet/variables.tf
enos/modules/vault_cluster/main.tf
enos/modules/vault_cluster/outputs.tf
enos/modules/vault_cluster/templates/install-packages.sh
enos/modules/vault_cluster/templates/vault-write-license.sh
enos/modules/vault_cluster/variables.tf

The previous strategy for provisioning infrastructure targets was to use
the cheapest instances that could reliably perform as Vault cluster
nodes. With this change we introduce a new model for target node
infrastructure. We've replaced on-demand instances for a spot
fleet. While the spot price fluctuates based on dynamic pricing, 
capacity, region, instance type, and platform, cost savings for our
most common combinations range between 20-70%.
This change only includes spot fleet targets for Vault clusters.
We'll be updating our Consul backend bidding in another PR.
* Create a new `vault_cluster` module that handles installation,
configuration, initializing, and unsealing Vault clusters.
* Create a `target_ec2_instances` module that can provision a group of
instances on-demand.
* Create …

Backport of [QT-525] and [QT-530] into release/1.12.x

---

.github/enos-run-matrices/build-github-oss-linux-amd64-zip.json
.github/enos-run-matrices/build-github-oss-linux-arm64-zip.json
.github/enos-run-matrices/enos_release_testing_oss-artifactory-oss-linux-amd64-zip.json
.github/enos-run-matrices/enos_release_testing_oss-artifactory-oss-linux-arm64-zip.json
.gitignore
enos/ci/service-user-iam/main.tf
enos/ci/service-user-iam/service-quotas.tf
enos/enos-modules.hcl
enos/enos-scenario-agent.hcl
enos/enos-scenario-autopilot.hcl
enos/enos-scenario-replication.hcl
enos/enos-scenario-smoke.hcl
enos/enos-scenario-ui.hcl
enos/enos-scenario-upgrade.hcl
enos/modules/target_ec2_instances/main.tf
enos/modules/target_ec2_instances/outputs.tf
enos/modules/target_ec2_instances/variables.tf
enos/modules/target_ec2_spot_fleet/main.tf
enos/modules/target_ec2_spot_fleet/outputs.tf
enos/modules/target_ec2_spot_fleet/variables.tf
enos/modules/vault_cluster/main.tf
enos/modules/vault_cluster/outputs.tf
enos/modules/vault_cluster/templates/install-packages.sh
enos/modules/vault_cluster/templates/vault-write-license.sh
enos/modules/vault_cluster/variables.tf

The previous strategy for provisioning infrastructure targets was to use
the cheapest instances that could reliably perform as Vault cluster
nodes. With this change we introduce a new model for target node
infrastructure. We've replaced on-demand instances for a spot
fleet. While the spot price fluctuates based on dynamic pricing, 
capacity, region, instance type, and platform, cost savings for our
most common combinations range between 20-70%.
This change only includes spot fleet targets for Vault clusters.
We'll be updating our Consul backend bidding in another PR.
* Create a new `vault_cluster` module that handles installation,
configuration, initializing, and unsealing Vault clusters.
* Create a `target_ec2_instances` module that can provision a group of
instances on-demand.
* Create …

Backport of [QT-525] and [QT-530] into release/1.13.x

---

.github/enos-run-matrices/build-github-oss-linux-amd64-zip.json
.github/enos-run-matrices/build-github-oss-linux-arm64-zip.json
.github/enos-run-matrices/enos_release_testing_oss-artifactory-oss-linux-amd64-zip.json
.github/enos-run-matrices/enos_release_testing_oss-artifactory-oss-linux-arm64-zip.json
.gitignore
enos/ci/service-user-iam/main.tf
enos/ci/service-user-iam/service-quotas.tf
enos/enos-modules.hcl
enos/enos-scenario-agent.hcl
enos/enos-scenario-autopilot.hcl
enos/enos-scenario-replication.hcl
enos/enos-scenario-smoke.hcl
enos/enos-scenario-ui.hcl
enos/enos-scenario-upgrade.hcl
enos/modules/target_ec2_instances/main.tf
enos/modules/target_ec2_instances/outputs.tf
enos/modules/target_ec2_instances/variables.tf
enos/modules/target_ec2_spot_fleet/main.tf
enos/modules/target_ec2_spot_fleet/outputs.tf
enos/modules/target_ec2_spot_fleet/variables.tf
enos/modules/vault_cluster/main.tf
enos/modules/vault_cluster/outputs.tf
enos/modules/vault_cluster/templates/install-packages.sh
enos/modules/vault_cluster/templates/vault-write-license.sh
enos/modules/vault_cluster/variables.tf

The previous strategy for provisioning infrastructure targets was to use
the cheapest instances that could reliably perform as Vault cluster
nodes. With this change we introduce a new model for target node
infrastructure. We've replaced on-demand instances for a spot
fleet. While the spot price fluctuates based on dynamic pricing, 
capacity, region, instance type, and platform, cost savings for our
most common combinations range between 20-70%.
This change only includes spot fleet targets for Vault clusters.
We'll be updating our Consul backend bidding in another PR.
* Create a new `vault_cluster` module that handles installation,
configuration, initializing, and unsealing Vault clusters.
* Create a `target_ec2_instances` module that can provision a group of
instances on-demand.
* Create …

Backport of [QT-525] and [QT-530] into release/1.11.x

---

sdk/helper/docker/testhelpers.go
sdk/helper/testcluster/docker/environment.go

When using the podman service runner (creating a socket equivalent to Docker's), tests fail with a nil pointer exception since the bridge network is named "podman", not "bridge".
Allow single networked containers and use whatever name the container runner assigns to it.

Fix support on Podman service

---

.github/scripts/verify_changes.sh

Fix the git diff script to use `...` in the correct pattern.

Fix script to verify docs changes

---

.github/workflows/milestone-checker.yml

https://github.com/hashicorp/vault/pull/18406 added a check to require a milestone for PRs.  This check needed to be triggered to re-run when a milestone is actually added (or removed)

Re-run Milestone Check when Milestones are Applied

---

builtin/logical/pki/backend_test.go
builtin/logical/pki/path_fetch_issuers.go
changelog/20341.txt

This variable had a spelling mistake in the handler; `GetOk(...)` appears to swallow scheme failures, unlike the regular `Get(...)` which panics.

Fix issuer patch of leaf_not_after_behavior

---

builtin/logical/pkiext/acme_test.go
builtin/logical/pkiext/test_helpers.go

This spins up Vault in a container image to allow other containers (in this case, Certbot) to bidirectionally connect to/from Vault.
Based on top of #20247; will be rebased once that merges. 
---
Ideally I'd like to spin up a DNS server that `certbot` has a plugin for and update our configuration to allow specifying custom DNS resolvers for all challenge types.
But we'll get there. For now, we use an `/etc/host` hack on the Vault container.

Start container-based PKI ACME tests

---

builtin/logical/pki/backend_test.go
builtin/logical/pki/path_fetch_issuers.go
changelog/20354.txt

This value was incorrectly left off the issuer's configuration on the read endpoint, when the AIA config was set. Note that modifying/patching per-issuer-AIA templating when no per-issuer AIA urls exist does nothing.
This is the follow up to #20341 with comprehensive PATCH tests for each value.

Fix reading issuer's enable_aia_url_templating value

---

builtin/logical/pki/acme_state.go
builtin/logical/pki/backend.go
builtin/logical/pki/backend_test.go
builtin/logical/pki/path_acme_order.go
builtin/logical/pki/path_acme_revoke.go
builtin/logical/pki/path_revoke.go
builtin/logical/pkiext/acme_test.go

This refactors path_revoke to expose Proof of Possession verification, which is reused by ACME to allow methods 1 and 2:
1. Revocation of a certificate issued by the account, using account signature as sufficient proof.
2. Revocation of a certificate via proving possession of its private key, using this private key to create the JWS signature.
We do not support the third mechanism, completing challenges equivalent to those on the existing certificate and then performing a revocation under an account which didn't issue the certificate but which did solve those challenges.
We additionally create another map account->cert->order, allowing us to quickly look up if a cert was issued by this particular account. Note that the inverse lookup of cert->(account, order) lookup isn't yet possible due …

Add ACME revocation handlers

---

.github/workflows/test-go.yml

Currently, the step gets auto-skipped because of how GitHub Actions handles [if conditions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsif), especially the default behaviour of [status check functions](https://docs.github.com/en/actions/learn-github-actions/expressions#status-check-functions).

Run Upload test results to DataDog every time test-go runs

---

.github/workflows/build.yml

The `completed-successfully` required status check is now being skipped if any of the dependent jobs fail.  This commit is a workaround to force the check and fail the status if any of the dependent jobs fail.  If the any of the dependent jobs are skipped the required status check will be skipped as well.

Fail completed successfully check for failing Enos tests

---

changelog/20375.txt
vault/login_mfa.go

This PR adds a nil check around the namespace for a MFA enforcement config. This resolves a panic experienced on login after deleting a namespace which contains a MFA enforcement configuration.
Example Panic: 
```
2023-04-26T12:39:37.380-0400 [INFO]  http: panic serving 127.0.0.1:64255: runtime error: invalid memory address or nil pointer dereference
goroutine 930 [running]:
net/http.(*conn).serve.func1()
/Users/runner/actions-runner/_work/_tool/go/1.19.4/x64/src/net/http/server.go:1850 +0xbf
panic({0x5dfd600, 0xae57de0})
/Users/runner/actions-runner/_work/_tool/go/1.19.4/x64/src/runtime/panic.go:890 +0x262
github.com/hashicorp/vault/vault.(*Core).buildMFAEnforcementConfigList(0xc000ae6000, {0x7dca1b8, 0xc000adf3e0}, 0xc0012de1c0, {0xc001cf723a, 0x17}) …
```

add nil check for mfa enforcement config namespace on login

---

website/content/docs/enterprise/replication.mdx

Related to https://github.com/hashicorp/vault/pull/20114
I found one more, and I think this is it. 
The correct GDPR org URL should be https://gdpr.eu/

[Docs] Fix the GDPR link

---

builtin/logical/pki/acme_challenge_engine.go
builtin/logical/pki/acme_challenges.go
builtin/logical/pki/acme_challenges_test.go
builtin/logical/pki/acme_state.go
builtin/logical/pki/backend.go
builtin/logical/pki/dnstest/server.go
builtin/logical/pki/path_config_acme.go
sdk/helper/docker/testhelpers.go

This:
- Adds a custom DNS resolver for ACME, allowing it to be used in environments where the operator might wish to use a different resolver but not have access to modify the host's resolvers.
- Adds new config caching to the ACME state, plumbing it through to the validation engine.
- Adds tests against a new bind9 container to ensure dns-01 challenges work, by providing a custom resolver address pointing to the container image.

Add custom DNS resolver to ACME configuration

---

builtin/logical/pki/acme_challenge_engine.go
builtin/logical/pkiext/pkiext_binary/acme_test.go

- Leveraging the new Vault docker based tests along with nginx and the Go ACME library, verify that Vault can properly perform ACME validations for IP identifiers

Add PKI ACME IP SANS test case

---

website/content/api-docs/secret/pki.mdx

The current api-docs for the PKI secrets engine mark `common_name` as being a required parameter when requesting a certificate to be issued. It is only required if `require_cn` is set to true on the role.

api-docs/pki: common_name is no longer required.

---

builtin/logical/aws/backend_test.go

We removed the lease and then added it back recently for STS tokens so we will revert this test as well.

secrets/aws: fix acc test for sts

---

audit/format.go
changelog/20411.txt

[VAULT-15882](https://hashicorp.atlassian.net/browse/VAULT-15882)
required for Vault Insights, this PR simply pipes the existing `Request.MountPoint` into audit logs
[VAULT-15882]: https://hashicorp.atlassian.net/browse/VAULT-15882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Pipe MountPoint to audit logs

---

changelog/20418.txt
command/server.go
command/server_test.go

Fixes regression in recovery mode where Vault panics, the bug was introduced by log rotation features (1.13) and this PR should correct the issue. 
We're no longer calling `.Flags()` which already happens at the top of our `Server.Run` func, and instead accessing the relevant field (`.flags`). A test case has been added to verify recovery mode (and a flag check which matches the vanilla `Server.Run` path added within `runRecoveryMode`).
Thanks to folks for reporting and assisting with identifying the issue 👍🏼 
Closes #20396

Fix panic when Vault enters recovery mode, added test

---

changelog/19814.txt

Following our internal changelog process, [the original PR](https://github.com/hashicorp/vault/pull/19814) should have `improvement` as the correct changelog type

update changelog type from feature to improvement

---

website/content/docs/upgrading/index.mdx
website/content/docs/upgrading/vault-ha-upgrade.mdx
website/data/docs-nav-data.json

1. Created a new separate page for HA upgrade instructions Pre 1.11 and moved the existing instructions there
2. Added a note on that new page to disable the automated upgrade feature.
🔍 [Deploy preview](https://vault-git-jpenghashi-patch-ha-hashicorp.vercel.app/vault/docs/upgrading/vault-ha-upgrade)

Updated the HA Upgrade Instructions

---

builtin/logical/pki/path_acme_order.go
builtin/logical/pki/path_acme_order_test.go

Perform some initial validation against the order's requested identifiers during creation; this gives a client a heads up that their request might be rejected by the server before they have to solve challenges for these, only to find out during CSR submission time that there is no way to request the specified certificate.

Validate identifiers against role when creating order

---

sdk/helper/testcluster/docker/environment.go
sdk/helper/testcluster/docker/replication.go
sdk/helper/testcluster/exec.go
sdk/helper/testcluster/replication.go
sdk/helper/testcluster/types.go
vault/external_tests/replication_binary/replication_ent_test.go
vault/external_tests/replication_binary/replication_test.go
vault/testing.go

This one's a bit more experimental, in that the ReplicationSet approach is different from how we're grouping clusters in our tests at present.  I'm trying to steer us in the direction of allowing arbitrary collections of clusters, and of them having names that aren't based on their intended initial roles.
Although this relies on an Enterprise feature (replication), most of this code will live in the sdk.  The actual tests will live in ent only though, since they rely on ent binaries that won't be available in the OSS CI.  For now I'm including an example test for reference.  The test can actually be run in a local checkout of OSS, provided you set VAULT_BINARY to point to an enterprise binary.
One thing that I probably still want to improve is a bit of UX.  This log is pretty convenient: …

Simple perf replication test using docker containers

---

website/content/docs/commands/operator/key-status.mdx

🎫 [Jira](https://hashicorp.atlassian.net/browse/VAULT-13949)
🎟️ [Zendesk ticket](https://hashicorp.zendesk.com/agent/tickets/100237)
This PR updates the command output for `vault operator key-status`.
Customer reported that `Encryption Count` is missing in the doc.

Update the command output example

---

website/content/docs/commands/print.mdx
website/data/docs-nav-data.json

🎫 [Jira ticket](https://hashicorp.atlassian.net/browse/VAULT-14362)
🔍 [Deploy preview](https://vault-git-docs-cherry-pick-pr19183-hashicorp.vercel.app/vault/docs/commands/print)
It was reported that the `vault print` command doc is missing in the `1.13.x` docs. Looks like the changes made with https://github.com/hashicorp/vault/pull/19183 was not cherry picked into the `release/1.13.x` branch.
This PR manually cherry picks the commit.

Add vault print token to commands in Vault docs (#19183)

---

changelog/20368.txt
vault/identity_store_aliases.go
vault/identity_store_aliases_test.go

With these changes, the following works. Previously, the final call would return an empty map:
```sh
$ vault auth enable userpass 
$ MA1=$(vault auth list -format=json | jq -r '."userpass/" | .accessor')
$ EID=$(vault write -field=id identity/entity name=max-winslow policies=entity-policy)
$ AID=$(vault write -field=id identity/entity-alias name=max1 canonical_id=$EID mount_accessor=$MA1)
$ vault write identity/entity-alias/id/$AID \
- <<<'{"custom_metadata":{"foo":"bar"}}'
$ vault read -field=custom_metadata identity/entity-alias/id/$AID
map[foo:bar]
```
Closes #19434

VAULT-15840: Allow updates of only entity-alias custom-metadata

---

changelog/20430.txt
ui/app/utils/path-encoding-helpers.js
ui/lib/core/addon/components/key-value-header.js
ui/package.json
ui/tests/acceptance/secrets/backend/kv/secret-test.js

Fixes #11616 where the UI fails to list or view details for secrets with `%` in the path name. This is because the path encoder and decoder we are using does not encode or decode `%` in the path. We have replaced this library with `encodeUriComponent` and `decodeUriComponent` for each of the path pieces. 
After fix:
Before:

UI: fix secret with % in path

---

builtin/logical/pki/backend_test.go
builtin/logical/pki/path_tidy.go
changelog/20442.txt
website/content/api-docs/secret/pki.mdx

This updates tidy-status to include a few missing parameters and document them in the API docs.
We also add a new parameter, `last_auto_tidy_finished`, for the time of when the last auto-tidy finished; this may be different than `time_finished` for reasons noted in the docs.

Update to tidy status and docs

---

website/content/docs/secrets/databases/oracle.mdx

🔍 [Deploy preview](https://vault-e17o7dppd-hashicorp.vercel.app/vault/docs/secrets/databases/oracle)
- Add tabs with steps and callouts specific to HCP Vault.
-- I opted for tabs in each section to maintain the right hand navigation based on section headers to stay consistent with other docs in the database secret engine category.
- Apply Vale language suggestions
- Switch to sentence case for section headings and title
- Minor numbering sequence fix for Vault steps
- Validate ciper suites for Oracle on RDS

Add HCP tabs, apply Vale suggestions, fix heading case

---

builtin/logical/pkiext/pkiext_binary/acme_test.go
builtin/logical/pkiext/pkiext_binary/pki_cluster.go
builtin/logical/pkiext/pkiext_binary/pki_mount.go
sdk/helper/testcluster/docker/environment.go

- Rework test suite to use a single Vault cluster with different mounts.
- Refactor convenience methods to write PKI tests.
- ~~Add ContainerID and ExposedHostPort to DockerClusterNode~~
~~Tagging @ncabatoff just to have a look at the changes within `sdk/helper/testcluster/docker/environment.go`~~

Initial refactoring of ACME PKI binary tests

---

.github/workflows/build.yml
.github/workflows/ci.yml

I validated that after my last push, the build and test-go-race/test-go-fips workflows/jobs were skipped.  Then once I clicked ready for review, new workflows were launched without skipping those.

Don't run build workflow on draft PRs.

---

builtin/logical/pki/path_acme_order.go
builtin/logical/pkiext/pkiext_binary/acme_test.go

- When someone is fetching the order to get it's status, compute if we need to bump the status to Ready like we do in finalize handler
- Add a wait state to the ACME docker test suite to deal with a race condition, this fixes a failure we saw on the main branch for the Test_ACME.group.acme_ip_sans test.

Update ACME order status on order fetch API

---

ui/lib/core/addon/components/masked-input.hbs
ui/lib/core/addon/components/masked-input.js
ui/tests/integration/components/masked-input-test.js

The PR which glimmerized Masked Input (#20431) missed the keyUp functionality, which mostly triggers validations. This fixes the issue and adds tests 😄

UI: Fix keyup trigger on masked input

---

api/client_test.go

Without this change, test failures only report the last value of `name`:
```
/Users/mpalmi/scm/vault-enterprise/api/client_test.go:258: Disabled redirects: Moved permanently: expected 3 request(s) but got 1
/Users/mpalmi/scm/vault-enterprise/api/client_test.go:258: Disabled redirects: Moved permanently: expected 5 request(s) but got 1
/Users/mpalmi/scm/vault-enterprise/api/client_test.go:258: Disabled redirects: Moved permanently: expected 4 request(s) but got 1
/Users/mpalmi/scm/vault-enterprise/api/client_test.go:258: Disabled redirects: Moved permanently: expected 6 request(s) but got 2
```
Capturing the loop var results in the following output:
```
/Users/mpalmi/scm/vault-enterprise/api/client_test.go:258: Disabled redirects: Temporary Redirect: expected 5 request(s) but got 1 …
```

Capture loop var in TestClientDisabledRedirects

---

website/content/docs/what-is-vault.mdx

It was reported that the "What is Vault?" page header is not parsing correctly. This PR fixes the page title.
🔍 [Deploy preview](https://vault-git-docs-fix-docs-title-hashicorp.vercel.app/vault/docs/what-is-vault)

Fix the title header - What is Vault

---

changelog/20464.txt
command/kv_helpers.go
command/kv_test.go

The `walkSecretsTree` helper function will be used by `vault agent generate-config` to produce a recursive list of secrets rooted at the given path. The output of `walkSecretsTree` is DFS sorted by keys at each level.

Add walkSecretsTree helper function

---

builtin/logical/pki/acme_authorizations.go
builtin/logical/pki/path_acme_order.go
builtin/logical/pki/path_acme_test.go

- Do not serialize the entire internal object, instead return just the Type and Value fields back to the caller.
- Also within authorization responses, return the base domain on wildcard queries, dropping the *. as the RFC requests.
- Update tests to reflect/test this logic.

In ACME responses only return Type, Value fields

---

vault/activity_log.go
vault/activity_log_test.go

Manual backport due to an issue with the backport-assistant when the original PR was merged.

Backport of VAULT-14733: Refactor processClientRecord in activity log into release/1.11.x

---

ui/app/models/pki/crl.js
ui/app/routes/vault/cluster/access/control-group-accessor.js
ui/app/routes/vault/cluster/access/control-groups-configure.js
ui/app/routes/vault/cluster/access/control-groups.js
ui/app/services/version.js
ui/lib/pki/addon/components/page/pki-configuration-details.hbs
ui/lib/pki/addon/components/page/pki-configuration-details.ts
ui/lib/pki/addon/components/page/pki-configuration-edit.hbs
ui/lib/pki/addon/components/page/pki-configuration-edit.ts
ui/tests/helpers/pki/page/pki-configuration-edit.js
ui/tests/integration/components/pki/page/pki-configuration-details-test.js
ui/tests/integration/components/pki/page/pki-configuration-edit-test.js
ui/tests/unit/services/version-test.js

In addition to adding these enterprise params to the configuration form, this PR updates the `version` service so that it could be declared in a typescript file.

UI: add enterprise only pki/config/crl parameters to edit configuration form

---

ui/lib/pki/addon/components/pki-import-pem-bundle.hbs
ui/lib/pki/addon/components/pki-import-pem-bundle.ts
ui/tests/acceptance/pki/pki-action-forms-test.js
ui/tests/integration/components/pki/pki-import-pem-bundle-test.js
ui/types/vault/app-types.ts
ui/types/vault/models/pki/action.d.ts

After importing a PEM bundle in the UI, we want to make sure to link to all imported items returned from the UI. Before this change, only the items listed in the `mapping` object were shown after success. This change also ensures that if nothing new is imported, the UI still shows something reasonable after the API action. 
**Empty state:**

UI: Handle edge cases for PKI import results

---

changelog/20488.txt
command/kv_delete.go
command/kv_destroy.go
command/kv_get.go
command/kv_helpers.go
command/kv_helpers_test.go
command/kv_list.go
command/kv_metadata_delete.go
command/kv_metadata_get.go
command/kv_metadata_patch.go
command/kv_metadata_put.go
command/kv_patch.go
command/kv_put.go
command/kv_rollback.go
command/kv_undelete.go

Improving the functionality of the existing `addPrefixToKVPath` CLI helper. It will allow to optionally skip the prefix if it already exists in the path, which is required for the `vault agent generate-config` functionality.
This change does not affect any of the existing code, since `skipIfExists` is set to false for all calls to `addPrefixToKVPath`.

Improve addPrefixToKVPath helper

---

builtin/logical/pki/dnstest/server.go
builtin/logical/pki/path_config_acme.go
builtin/logical/pkiext/pkiext_binary/acme_test.go
builtin/logical/pkiext/pkiext_binary/pki_cluster.go
sdk/helper/docker/testhelpers.go
sdk/helper/testcluster/docker/environment.go

This refactors the test execution environments a little to make executing commands a little easier. It turns out that the issue with loading the DNS server onto the network was fixed by setting `forceLocalAddr`; this does not impact the ability to get a real IP address later (cc @ncabatoff).
I've added another conditional into the DNS server though, so that when no network is specified (i.e., this is the first loaded server), we can get the network address in case we add another container to the same network.
With this, we can then load the DNS resolver helper alongside the Vault cluster, giving us the ability to solve DNS challenges and more cleanly set dependent container's IP addresses (instead of via `/etc/hosts` poking).
Also fixes a bug in the DNS configuration validation code.

Add dns resolver to PKI Binary Cluster

---

ui/tests/integration/components/sidebar/frame-test.js
ui/tests/unit/services/version-test.js

This fixes some sidebar component test failures caused by updates to the version service from https://github.com/hashicorp/vault/pull/20479

UI: update setting version service for sidebar frame test

---

api/client.go

Updating the deprecation messages to point to the proper alternatives.

Clarify deprecation comments for RawRequest* functions

---

builtin/logical/pki/dnstest/server.go
builtin/logical/pkiext/pkiext_binary/acme_test.go
builtin/logical/pkiext/pkiext_binary/pki_cluster.go
builtin/logical/pkiext/pkiext_binary/pki_mount.go

This refactors the Go ACME client tests to have an external helper function to solve challenges on behalf of the validator.
We then add a new test which validates that wildcards work properly using this validator, solving wildcard challenges.

Add DNS wildcard tests to ACME test suite

---

vault/rollback.go

When executing multi-stage, multi-namespace tests, stopping the ticker multiple times (via closing the StopTicker channel) results in a panic.
Store whether or not we've stopped it once, and do not close it again.

Allow ensuring ticker is stopped multiple times

---

command/command_test.go
command/server.go
helper/testhelpers/seal/sealhelper.go
http/sys_init_test.go
physical/raft/raft.go
vault/core.go
vault/ha.go
vault/init.go
vault/raft.go
vault/rekey.go
vault/seal.go
vault/seal/seal.go
vault/seal/seal_testing.go
vault/seal_access.go
vault/seal_autoseal.go
vault/seal_autoseal_test.go
vault/seal_testing_util.go

This is the OSS side of the work to refactor seal code. 
This PR converts the Access struct in the seal package into an interface.
It also refactors the code to better isolate the usage of Access and the underlying encryption Wrapper. 
The vault-enterprise PR is: https://github.com/hashicorp/vault-enterprise/pull/3955

Convert seal.Access struct into a interface (OSS)

---

changelog/20519.txt
scripts/ci-helper.sh

By reversing the logic and adding a `REMOVE_SYMBOLS` environment variable that, when set, will remove symbols.
This has been requested to re-enable Dynatrace support, which requires symbols are intact.
Sadly this increases the size (on my mac) from 192,609,682 bytes to 236,696,722 bytes (+23% increase).
I confirmed that this adds symbols back, and that `dlv` will load the Vault binary.

Keep symbols by default

---

website/content/docs/interoperability-matrix.mdx

Automatic backport with `backport/1.12.x` label failed for https://github.com/hashicorp/vault/pull/20501. So, this PR manually cherry pick the commit made by the https://github.com/hashicorp/vault/pull/20501.

[Backport] Update interoperability-matrix.mdx (#20501)

---

changelog/20502.txt
command/base.go
command/ssh.go
command/ssh_test.go

Addresses https://github.com/hashicorp/vault/issues/19785
Echoing what @maxb has mentioned in the ticket:
```
The vault ssh command has the unusual purpose of being a wrapper that invokes the real ssh command (after obtaining credentials). 
Moreover, the ssh command can take another command on its command line, to run on the remote machine. 
Because of this, there are multiple ways in which it can be a normal use-case for there to be option-like arguments later in the command line, 
which are deliberately intended either for ssh, or for a command being run via ssh on the remote machine.
This is quite unlike most other commands, where option-like things occurring after positional arguments are often a mistake.
```

disable printing flags warning message for the ssh command

---

.github/scripts/verify_changes.sh
.github/workflows/build.yml

This commit updates the verify_changes script to consider forked branches.  This will allow skipping builds for docs changes  from external contributors.  Also reverts QT-545 as the secrets in public repos can only be read in workflow_run events.

Update verify-changes to support external docs branches

---

changelog/20502.txt
command/base.go
command/ssh.go
command/ssh_test.go

This is the backport of https://github.com/hashicorp/vault/pull/20502
* disable printing flags warning message for the ssh command
* adding a test
* CL
* add go doc on the test

disable printing flags warning message for the ssh command (#20502)

---

website/content/docs/commands/server.mdx

added a note detailing that usage of `-log-file` functions as an additional output, does not replace journald / stdout
from: https://developer.hashicorp.com/vault/docs/commands/server#_log_file
preview: https://vault-9ujc04ufh-hashicorp.vercel.app/vault/docs/commands/server#_log_file
cc @aphorise

docs / update info for -log-file config parameter

---

website/content/docs/platform/k8s/injector/examples.mdx

Fixed a typo in the "Environment Variable Example" because it was generating a parsing error:
template server error: error="(dynamic): execute: template: :2:30: executing \"\" at <.Data.data.payments_api_key>: can't evaluate field data in type *dependency.Secret"](template.server: template server error: error="(dynamic): parse: template: :1: bad character U+002F '/'"
EDIT: I'm sorry I put the wrong error in the commit message...

Fixed a typo in the "Environment Variable Example"

---

builtin/logical/pki/acme_eab_policy.go
builtin/logical/pki/acme_jws.go
builtin/logical/pki/acme_state.go
builtin/logical/pki/acme_wrappers.go
builtin/logical/pki/backend.go
builtin/logical/pki/backend_test.go
builtin/logical/pki/path_acme_account.go
builtin/logical/pki/path_acme_directory.go
builtin/logical/pki/path_acme_eab.go
builtin/logical/pki/path_acme_eab_test.go
builtin/logical/pki/path_acme_test.go
builtin/logical/pki/path_config_acme.go
builtin/logical/pkiext/pkiext_binary/pki_cluster.go

Add support for external account bindings within the PKI ACME code base. This will only verify against keys that were generated within the same PKI mount using the new authenticated Vault API `/pki/acme/eab`. The API will return a single use key to associate an ACME account with this EAB token which will prevent anonymous users from creating ACME accounts.
The following Vault PKI APIs have been added within this PR
- LIST `/pki/acme/eab` - This will list the various EAB ids generated and waiting to be used within storage. The detailed view contains details of creation time, key type and key bits
- UPDATE `/pki/acme/eab` - Generate a one-time key, returning the EAB id, private_key in base64 url encoded
- DELETE `/pki/acme/eab/{{key_id}}` - Allows an operator to delete a generated one-time …

Add External Account Binding support to ACME 

---

ui/app/styles/utils/_size_variables.scss

The only use case of this var was removed in the sidebar navigation work. This is a follow up task to remove it once that sidebranch was merged.

Remove fullhd var

---

builtin/logical/pki/acme_state.go
builtin/logical/pki/acme_wrappers.go
builtin/logical/pki/path_acme_account.go
builtin/logical/pki/path_acme_order.go
builtin/logical/pki/path_acme_revoke.go

- When we issue a new ACME certificate, attempt to update the account's last issued field
- Within ACME account tidy, use both account creation and last issue date to provide a buffer before we mark the account as revoked.
- Cleanup the cert serial to account tracker
- Misc formatting fixes in JSON objects

Add a last issued date on ACME accounts

---

ui/app/decorators/model-validations.js
ui/docs/model-validations.md

This PR adds documentation for the `model-validations` util and removes the original comments from the file.

Model validations docs

---

builtin/logical/pki/path_acme_account.go
builtin/logical/pki/path_config_acme.go

There are a few validation errors related to the new ACME endpoints in the generated OpenAPI spec:
```sh
$  openapi-generator validate -i scripts/openapi.json 
...
- paths.'/{pki_mount_path}/acme/account/{kid}'. Declared path parameter kid needs to be
defined as a path parameter in path or operation level
...
- attribute components.schemas.PkiConfigureAcmeRequest.default is not of type `array`
```
This PR adds a `kid` parameter:
```diff
"/{pki_mount_path}/acme/account/{kid}": {
"description": "Query a certificate's revocation status through OCSP'",
"parameters": [
+        {
+          "name": "kid",
+          "description": "The key identifier provided by the CA",
+          "in": "path",
+          "schema": {
+            "type": "string"
+          },
+          "required": true
+ …
```

openapi: Fix ACME-related errors

---

changelog/20603.txt
ui/app/templates/vault/cluster/access/mfa/methods/method/index.hbs
ui/tests/acceptance/mfa-method-test.js

The toolbar action for creating a new enforcement from the mfa method enforcements tab was broken and did not transition to the enforcements create route. This PR fixes that link and adds a test.

MFA Create Enforcement Bug

---

ui/tests/acceptance/secrets/backend/engines-test.js

When running the full test suite I'm battling more than one secret engine and the filtering by name and selecting the first object does not reliably return the same secret engine each time. While ideally I could select by option name, I wasn't able to do that so I am filtering by the first item in the list, confirming one is returned and that it matches the name of the filtered item.

Fix flaky filtering test

---

ui/package.json
ui/yarn.lock

Cleans up some errors and warnings from the `yarn start` output:
- Removes export in the `yarn start` command which is unnecessary since `VAULT_ADDR` env var will be passed directly to the script execution
- Updates caniuse-lite to get rid of the warnings

Yarn start cleanup

---

builtin/logical/pki/path_acme_account.go
builtin/logical/pki/path_acme_authorizations.go
builtin/logical/pki/path_acme_challenges.go
builtin/logical/pki/path_acme_directory.go
builtin/logical/pki/path_acme_eab.go
builtin/logical/pki/path_acme_nonce.go
builtin/logical/pki/path_acme_order.go
builtin/logical/pki/path_acme_revoke.go

- Use generic help synopsis and help description values for the various ACME endpoints defined.
- Add missing values for the Vault ACME EAB apis
Fixes VAULT-16265

Update ACME endpoint help synopsis and description

---

helper/random/string_generator.go
vault/logical_system.go

This changes the password policy testing to attempt to construct a test password rather than generating random passwords and checking them against the rules. This stops Vault from erroring out on policies that are restrictive, but still possible.

Vault-12308: Change password policy testing to be deterministic

---

vault/logical_system_helpers.go

The path stubs created for enterprise endpoints in #18870 caused the automated OpenAPI specification generator to fail for paths that include a parameter in its pattern.
The reason for the failure is that the generator needs to find a corresponding framework.Field struct instance within the framework.Path struct. This PR changes the structure of the map provided to the **buildEnterpriseOnlyPaths** function from a map of `string` (pattern) to `[]logical.Operation` (slice of Operations) to a map of `string` (pattern) to `enterprisePathStub` (a struct containing a slice of parameter names and a slice of Operations).

VAULT-16217 Fixing Broken OpenAPI Specification Generation

---

builtin/logical/pki/path_acme_order.go
builtin/logical/pkiext/pkiext_binary/acme_test.go
sdk/helper/certutil/helpers.go

This adds a test to ensure that intermediate CAs aren't allowed to be issued. They aren't and weren't, because `certutil` ignores the basic constraints extension from the request.

ACME tests for Intermediate CA issuance prevention

---

builtin/logical/pki/crl_util.go
builtin/logical/pki/path_revoke.go
changelog/20643.txt
sdk/logical/response_util.go
vault/request_handling.go

OSS version of https://github.com/hashicorp/vault-enterprise/pull/3937
Addresses [VAULT-15375](https://hashicorp.atlassian.net/browse/VAULT-15375)
Core elides intermediate error messages during request forwarding.
There are two main places where Alex and I find that we need to report the errors considering request forwarding. One is in the request handling where we initially forward the request upon getting a read only error. Two is in the replication code [here](https://github.com/hashicorp/vault-enterprise/blob/6ee821519bf288d7e61c1b3e5c21f3983ace97d2/vault/replication_rpc_ent.go#L869-L875). 
Having aggregate the errors in the above places, we noticed that the reported error has many duplicates. Below is a sample of the existing behaviour:
```
backend_revocation_queue_ent_test.go:391: …
```

report intermediate error messages during request forwarding

---

builtin/logical/pki/acme_billing_test.go

Namespace ID is a random value that would involve querying the namespace `sys/` endpoint to correlate.

Correctly search for namespace path, not id

---

builtin/logical/pki/backend_test.go
builtin/logical/pki/fields.go
builtin/logical/pki/path_fetch_keys.go
changelog/20642.txt
sdk/helper/certutil/helpers.go

This will be helpful for the Terraform Vault Provider to detect migration of pre-1.11 exported keys (from CA generation) into post-1.11 Vault.

pki: add subject key identifier to read key response

---

Dockerfile

Updating the [ubi base image](https://catalog.redhat.com/software/containers/ubi8/ubi-minimal/5c359a62bed8bd75a2c3fba8) and backporting to 1.13, 1.12, 1.11.

dockerfile: ubi-minimal:8.7 -> 8.8

---

builtin/logical/transit/backend_test.go
builtin/logical/transit/path_cache_config.go
builtin/logical/transit/path_keys.go
builtin/logical/transit/path_keys_config.go
builtin/logical/transit/path_rotate.go
builtin/logical/transit/path_trim.go
changelog/20652.txt

When writing to an endpoint, currently transit responds with `nil, nil`, meaning any invalid parameter warnings are hidden, and the user doesn't know the results of the operation.
We should respond with the key policy on writes (or, on the other endpoint, the config), to show users the changes they made and show any invalid parameter warnings that might've been ignored.

Transit UX improvements: show key policy, configs on write

---

website/content/docs/commands/operator/raft.mdx

Added a note to the`remove-peer` section stating that the Raft data needs to be removed after a remove and prior to adding the node back to a cluster.

Added a note to remove-peer

---

builtin/logical/pki/fields.go
builtin/logical/pki/path_tidy.go
changelog/20664.txt

The logic around the check to set both to false was wrong, and should be validated independently.
Additionally, these fields should only exist on auto-tidy and not on the manual tidy endpoint.

Fix tidy with maintain_stored_certificate_counts == publish_stored_certificate_count_metrics == false

---

api/secret.go
api/secret_test.go
changelog/20636.txt

When the `vault login` command is executed and a valid token that has associated Identity Policies in Namespaces other than the current namespace, an error is reported. This is due to the fact that the Vault CLI could not process the response from the Vault server for the Token Lookup request. Specifically, the **identity_policies** key in the response is set to `nil`. The Vault CLI code uses code (that has been fixed in this PR) that expects that either the **identity_policies** key to be absent in the response or present and set to either a string slice or a slice of values that can be casted to the string type.
This minor fix allows that code to deal with the **identity_policies** key being set to `nil` in the same manner as if it was absent.

VAULT-5094: Deal with identity_policies Set to nil in Secret Data Field

---

ui/app/templates/vault/cluster/settings/auth.hbs
ui/tests/acceptance/sidebar-nav-test.js

When mounting or configuring an auth method the route changes to `settings/auth` which is not nested under the access route causing the top level nav panel to activate. While this is technically correct it is not the intended UX and an issue with the route structure in general. Until the route structure can be updated a `settings.auth` template was added with the sidebar access nav component.

Sidebar nav access bug

---

ui/lib/core/addon/components/search-select.hbs
ui/lib/core/addon/components/search-select.js
ui/lib/pki/addon/components/page/pki-overview.hbs
ui/lib/pki/addon/components/page/pki-overview.ts
ui/tests/acceptance/pki/pki-overview-test.js
ui/tests/helpers/pki/overview.js
ui/tests/integration/components/search-select-test.js

Due to a known issue when using control groups on issuer GET requests, we are adding a box to the overview page that allows a user to go directly to the issuer details page, which will allow control groups to work as expected.

UI: View PKI issuer from overview page

---

changelog/20530.txt
command/agent_generate_config.go
command/agent_generate_config_test.go
command/command_test.go
command/commands.go
go.mod
go.sum

> Note: documentation will be added in a different PR
This pull request implements a new sub-command `agent generate-config`. It is part of the larger effort to add environment variable support within Vault Agent ([VLT-253](https://docs.google.com/document/d/1HLTkPtxUTtW-wMkePWoHmZoGt9lLg2POslt1ranaWE8/edit#)).
The goal of this sub-command is to help new users with an easy on-boarding to Vault, specifically for integrating Vault into their applications. It will recurse through the Vault path tree for the given path(s) and produce an `agent.hcl` configuration file with `token_file` authentication method and default environment-variable-to-secret mappings. The file can then be used by Vault Agent in a process supervisor mode (will be implemented in future PRs).
For the first release of this …

cli: Add 'agent generate-config' sub-command

---

vault/acme_billing_system_view.go
vault/mount_util.go

Note the three overlapping scenarios discussed in the comments. In the future, when this interface is more broadly supported, we should likely add the interface directly to SystemView and implement it over the GRPC interface, removing this nasty layering of already complex SystemView implementations.
Additionally, we restrict provisioning of this view to only PKI mounts.

Fix entropy sourcing on Vault Enterprise

---

command/server.go
command/server_test.go

This PR proposes moving logic from the **(*ServerCommand) Run(args []string)** function that relates specifically to configuring TLS when the Vault server is being launched in *dev* mode, into its own function in order to facilitate testing of that logic and clearing some of the noise from the Run function.

Refactor Code Focused on DevTLS Mode into New Function

---

builtin/logical/pki/backend_test.go
builtin/logical/pki/cert_util.go
changelog/20654.txt

* In the tests, make sure we validate the expected error message; over time, the role definition changed to prevent issuance of this ICA leaf.
* Add warning when issuing a leaf cert that looks like it could be an intermediate (has any basic constraint extension).
In the future, we might move to forbidding issuance of leaf certs from CSRs that contain asserted IsCA basic constraints.

Properly validate int ca lifetime error, add warning on leaf cert with basic constraints

---

builtin/logical/pki/periodic.go
changelog/20701.txt

During this race, we'll sometimes start (or fail to start) an additional unified transfer if the updated last run timestamp was written at the same time as another thread was reading it.
Instead, delay this check until we're holding the CAS guard; this will occasionally result in more messages saying that an existing process is already running, but otherwise shouldn't impact the functionality at all.
This manifests in the race detector as:
```
2023-05-22T15:38:20.0251871Z WARNING: DATA RACE
2023-05-22T15:38:20.0252056Z Read at 0x00c003f633b8 by goroutine 33457:
2023-05-22T15:38:20.0252340Z   github.com/hashicorp/vault/builtin/logical/pki.runUnifiedTransfer()
2023-05-22T15:38:20.0252973Z       /home/runner/actions-runner/_work/vault-enterprise/vault-enterprise/builtin/logical/pki/periodic.g …
```

Fix race in PKI's runUnifiedTransfer

---

audit/format.go
sdk/logical/request.go

**Enterprise only**: 
When a perf-standby node receives a request and eventually forwards it to the primary node, audit logs can be written on the the perf-standby and the primary node for both the incoming request, and outgoing response (max 4 entries in total, 2 per each node).
1. Performance Standby node logs request
2. Primary node logs (forwarded) request
3. Primary node logs response to (forwarded) request
4. Performance Standby node logs response to request
In order to make it clearer in the audit logs that a request was forwarded this PR will add forwarded data to the request object that is used to generate audit log entries. The forwarded data will contain the host (:) of the node that the request is either forwarded from or the primary node it is forwarded to.
e.g. …

VAULT-11595: Augment forwarded requests with host:port info (from/to nodes) (Enterprise)

---

changelog/pki-ui-improvements.txt
ui/app/models/pki/certificate/base.js
ui/lib/pki/README.md

Included in this release is:
- Mount overview page with issuer and role counts and quick actions to do the following: issue a certificate from a role, navigate to certificate details by serial number, view an issuer by its name or ID
- Multiple issuers can now be generated and managed in the UI
- Adds issuer metadata in the list view that includes a default issuer tag, whether it is a root or intermediate, serial number and the common name
- Guided root rotation by either using old root settings or customizing a new root certificate
- Perform cross-signing of multiple intermediates in a single step from a parent issuer
- Parses and displays more certificate metadata
- Surfaces more mount configuration parameters to allow setting URLs and revocation configuration
#19281
#19312
#19425 …

UI: Add PKI readme and changelog for UI improvements

---

ui/lib/pki/addon/components/page/pki-tidy-status.hbs
ui/lib/pki/addon/components/page/pki-tidy-status.ts
ui/lib/pki/addon/components/pki-tidy-form.hbs
ui/tests/acceptance/pki/pki-tidy-test.js
ui/tests/helpers/pki/page/pki-tidy-form.js
ui/tests/helpers/pki/page/pki-tidy.js
ui/tests/integration/components/pki/page/pki-tidy-status-test.js
ui/tests/unit/adapters/pki/tidy-test.js

- Fix failing tests on sidebranch
- Add tidy acceptance tests
- VAULT-16378 Hide `Tidy` action when auto-tidy is enabled
**When auto tidy is enabled:**
**When auto tidy not enabled we show a tidy modal w/ manual + auto tidy options:**

UI: VAULT-16367 VAULT-16378 Tidy acceptance tests + tidy toolbar cleanup

---

builtin/logical/transit/path_sign_verify.go

There are a few references to encryption in `builtin/logical/transit/path_sign_verify.go` (other than the `min_encryption_version` key policy field). This PR corrects those references.

Correct signing terminology in comments and error messages

---

website/content/api-docs/system/audit.mdx
website/content/docs/audit/index.mdx
website/content/docs/commands/audit/disable.mdx
website/content/docs/commands/audit/index.mdx

When a user disables an audit device, they will no longer be able to perform HMACing against it to compare values with entries in the existing audit logs.
Similarly, if they re-enable a disabled audit device, they will face this issue as a new salt is generated for hashing.
It seems sensible to warn users of the pitfalls before the turn off a device.

Docs: audit - add warning when disabling device regarding HMAC

---

helper/metricsutil/gauge_process.go
helper/metricsutil/gauge_process_test.go
helper/timeutil/timeutil.go
vault/activity_log.go
vault/activity_log_test.go
vault/activity_log_testing_util.go
vault/activity_log_util_common.go

This PR adds an exported interface to the timeutil package called `Clock`, which can be used to mock the standard lib time functions. 
I've used the interface in the activity log, so that tests can configure mocked time functions. I added a test that uses this functionality to mock the end of a month.

VAULT-15395: Support mocking time functions in the activity log

---

.github/scripts/generate-test-package-lists.sh
builtin/logical/pki/acme_state.go
builtin/logical/pki/acme_state_test.go
builtin/logical/pki/backend.go
sdk/helper/nonce/benchmark_test.go
sdk/helper/nonce/encrypted_nonce.go
sdk/helper/nonce/nonce.go
sdk/helper/nonce/nonce_test.go
sdk/helper/nonce/sync_map_nonce.go

This adds a new nonce service inspired in part by the design of the Let's Encrypt nonce service used in Boulder. This has the nice property that new nonce issuance consumes effectively no memory and is relatively fast. Only redemption of valid (unexpired) nonces consumes memory.
In the case of ACME, an external user can quickly acquire nonces (via `/get-nonce`) and redeem them (via `/new-account`); this mostly shifts the burden of memory. However, by using a time-bucketed redemption tracker, we can quickly expire the used nonce list by simply deleting the corresponding map entry.
Because the redemption map is short-lived, but can grow in size within that window, it can be freed back by Go's GC to the host when it shrinks. However, the two long-lived maps are bounded in size by some …

Add nonce service to sdk/helpers, use in PKI

---

vault/activity_log.go
vault/logical_system_activity_write_testonly.go
vault/logical_system_activity_write_testonly_test.go

This PR adds support for repeated or segmented clients. Repeated clients are copied from a previous month. Segmented clients are grouped together into segments that will be written out together.

VAULT-14735: repeated and segmented activity log clients

---

website/content/docs/platform/k8s/csi/configurations.mdx
website/content/docs/platform/k8s/csi/examples.mdx
website/content/docs/platform/k8s/csi/index.mdx

* New config options
* New advice on setting Vault address to avoid bypassing the Agent sidecar (see https://github.com/hashicorp/vault-csi-provider/issues/213)
* New JWT auth method support
* Delete some outdated advice (users working with older versions of Vault will still see the advice in the versioned docs)

Docs: Updates for latest Vault CSI Provider releases

---

builtin/logical/pki/acme_billing_test.go
vault/acme_billing_system_view.go

See suggested naming convention in the code. This moves this `acme` activity count type to `pki-acme`, defining a constant for it and noting that changing it would result in problems.
In particular, naming things both by the client type (`acme` certificates) and the plugin name `pki` could help disambiguate things in the future, if this gets opened to other use cases.

Move activityType to a constant, set precedence

---

builtin/logical/pki/acme_wrappers.go
builtin/logical/pki/path_acme_challenges.go
builtin/logical/pki/path_acme_revoke.go

- Make sure we have an ACME account in a valid state and enforce EAB policies on that account for the challenge and revocation by account ACME apis.

Enforce valid ACME accounts in challenge APIS

---

go.mod
go.sum

Updates vault-plugin-secrets-kv to [v0.15.0](https://github.com/hashicorp/vault-plugin-secrets-kv/releases/tag/v0.15.0)
Steps:
```
go get github.com/hashicorp/vault-plugin-secrets-kv@v0.15.0
go mod tidy
```

fix: upgrade vault-plugin-secrets-kv to v0.15.0

---

builtin/logical/pki/path_config_acme.go

These roles cannot be used with ACME; while they can change later, we do still want to validate it at configuration write time.

Validate no_store=false on role configuration

---

builtin/logical/pki/acme_jws.go
builtin/logical/pki/acme_state.go
builtin/logical/pki/backend.go
builtin/logical/pki/backend_test.go
builtin/logical/pki/path_acme_eab.go
builtin/logical/pki/path_acme_eab_test.go
builtin/logical/pki/path_acme_test.go
builtin/logical/pki/path_tidy.go
builtin/logical/pki/storage.go

This still needs a few tests around tidy operations for EAB but the rest should be good to go. Resolve a bunch of things that @cipherboy found when playing with ACME EAB apis.
- The LIST api doesn’t actually work, it isn’t setup correctly
- The EAB key value shouldn’t be an EC key, just random 32 byte data instead
- OpenAPI definitions for the EAB Vault APIs aren’t correct.
- We should clean up the unused EAB values through tidy

Address various issues related to ACME EAB

---

.github/workflows/ci.yml

Another option: to remove the packages instead. Release team did a test run on their end and it worked without it. The id seems to indicate that these are for browser actions and the test will run without them. Running this option on the third commit to also test. Second commit is with the `apt update command`.
Note: may need to backport as recent changes in this file were also backported—[see here](https://github.com/hashicorp/vault/issues/20360).
See failure [here](https://github.com/hashicorp/vault/actions/runs/5072296967/jobs/9109884829?pr=20747).
Step for failure
```
run: sudo apt install -y libnss3-dev libgdk-pixbuf2.0-dev libgtk-3-dev libxss-dev libasound2
```
Error:
```
E: Failed to fetch [http://azure.archive.ubuntu.com/ubuntu/pool/main/m/mesa/libegl-mesa0_22.2.5-0ubuntu0.1%7e22.0 …
```

Address Test-ui suite failure for package install issues

---

changelog/20766.txt
vault/core.go
vault/core_test.go
vault/external_tests/identity/userlockouts_test.go
vault/logical_system_user_lockout.go
vault/request_handling.go
vault/request_handling_util.go

Jira : https://hashicorp.atlassian.net/browse/VAULT-16051
This PR contains the following fixes:
Perf Standbys no longer try to update storage directly in places where we missed it. Checked if this happens for clean up and cleanups are already being handled the right way (updated comments to make this clear)
Updated the updateUserFailedLoginInfo to handle updates to both updateUserFailedLoginInfo map and storage.
We now check if the userlockout feature is disabled after login failure.
Added tests for namespaces (wherever missing), perf standbys, approle with batch tokens, disable env var test in external tests.
Ent branch: https://github.com/hashicorp/vault-enterprise/pull/4020

User Lockout Perf Standby Error oss 

---

vault/ha.go

The `Core.Leader` method can be used to retrieve information on whether the current node is the leader, and obtain leader and cluster addresses. However, the implementation of this method uses a struct field level lock on `Core` which means if we call this method while the state lock is already held by another reader we could deadlock. 
https://pkg.go.dev/sync#RWMutex.RLock
> It should not be used for recursive read locking; a blocked Lock call excludes new readers from acquiring the lock
Therefore the godoc comment for Leader has been updated to give developers some warning up front.

Leader godoc comment

---

vault/activity_log.go
vault/logical_system_activity_write_testonly.go
vault/logical_system_activity_write_testonly_test.go

This PR adds support for writing the entity data from the activity log data generation endpoint. The activity log's segment writing code needed to be refactored a bit to support force writing only entities.

VAULT-14735: write mock activity log entity files

---

changelog/20758.txt
go.mod
go.sum

Upgrades vault-plugin-auth-alicloud to [v0.15.0](https://github.com/hashicorp/vault-plugin-auth-alicloud/releases/tag/v0.15.0)
Steps
```
go get github.com/hashicorp/vault-plugin-auth-alicloud@v0.15.0
go mod tidy
```

upgrade vault-plugin-auth-alicloud to v0.15.0

---

builtin/logical/pki/path_roles.go
builtin/logical/pki/path_roles_test.go

This is a small fix to address an issue with the generated response brought up in https://github.com/hashicorp/vault-client-go/issues/175.

openapi: Fix response schema for pki list roles

---

changelog/20787.txt
go.mod
go.sum

Updates the plugin to [v0.15.0](https://github.com/hashicorp/vault-plugin-secrets-alicloud/releases/tag/v0.15.0)
Steps
```
go get github.com/hashicorp/vault-plugin-secrets-alicloud@v0.15.0
go mod tidy
```

upgrade vault-plugin-secrets-alicloud to v0.15.0

---

ui/README.md
ui/docs/ember-engines.md

Add some documentation on how to create an engine in Vault.
This PR contains the cherry-picked commits from https://github.com/hashicorp/vault/pull/20749 and addresses some of the newer comments made in the previous PR.

UI docs: Add ember engine creation documentation

---

ui/app/helpers/mountable-secret-engines.js
ui/app/helpers/supported-secret-backends.js
ui/app/templates/vault/cluster/secrets/backends.hbs
ui/lib/ldap/addon/engine.js
ui/tests/acceptance/secrets/backend/engines-test.js
ui/tests/acceptance/secrets/backend/kv/secret-test.js
ui/tests/acceptance/settings/mount-secret-backend-test.js
ui/tests/pages/secrets/backends.js

This PR adds LDAP as a mountable and supported secrets engine under the _generic_ section of the engines list.

Adds LDAP as Mountable and Supported Secrets Engine

---

ui/app/controllers/vault/cluster/secrets/backend/configuration.js
ui/app/templates/vault/cluster/secrets/backends.hbs
ui/lib/core/addon/helpers/options-for-backend.js

Now that the old pki code has been removed, this is one last piece that was left behind. This configure button is from the backend generator, now all pki related actions live with their own ember engine.

ui: update pki link

---

ui/app/adapters/pki/pki-role.js
ui/app/adapters/role-aws.js
ui/app/adapters/role-ssh.js
ui/app/adapters/transform.js
ui/app/adapters/transform/base.js
ui/app/components/role-aws-edit.js
ui/app/components/role-edit.js
ui/app/components/transformation-edit.js
ui/app/models/pki/pki-role.js
ui/app/models/role-aws.js
ui/app/models/role-ssh.js
ui/app/models/transform.js
ui/app/models/transform/alphabet.js
ui/app/models/transform/role.js
ui/app/models/transform/template.js
ui/app/models/transit-key.js
ui/app/serializers/role-aws.js
ui/app/serializers/role.js
ui/app/serializers/transform.js
ui/app/serializers/transform/alphabet.js
ui/app/serializers/transform/role.js
ui/app/serializers/transform/template.js
ui/lib/core/addon/components/form-field.js

Backports work from #19117 which we assumed got into the 1.13 release but got missed 😞 
Fixes issue where input only allows one character

Backport 1.13.x - UI: Fix id fields not allowing update (#19117)

---

go.mod

Pointing the go.mod to the updated SDK and API releases, then ran a go mod tidy.

Update SDK and API for 1.14 release

---

website/content/api-docs/secret/kubernetes.mdx
website/content/docs/secrets/kubernetes.mdx

* Add an option to set audiences on token create VAULT-6292
* Allow omitting kubernetes_namespace on token create VAULT-6293

update API docs for kubernetes secrets engine

---

ui/tests/integration/components/token-expire-warning-test.js

Looks like there were several prs to try and fix this test. Instead of backporting each one (which on their own did not fix it) I'm just copying from main and pasting the new test here (minus the token header). 
This test is causing problems on the 1.11 branch so pointing the fix for that release.

Backport: 1.11.x: Fix flaky token test

---

ui/tests/integration/components/token-expire-warning-test.js

Making the token test consistent through the release branches. Issues with flaky tests (in 1.11). See backport to 1.11.x [here](https://github.com/hashicorp/vault/pull/20812).

Backport 1.12.x: make token test consistent

---

builtin/logical/transit/path_export.go
builtin/logical/transit/path_import.go
builtin/logical/transit/path_import_test.go
sdk/helper/keysutil/policy.go

This changes the behavior of `import_version` to update the latest version if it is missing a private key, otherwise creating a new version, removing the need for `bump_version`. When an explicit version is specified, we check to see if we can add a private key to that particular key version. This is a follow-on of #17934 by @Gabrielopesantos :-)
Also updates public key exports to not require `exportable` on the key.
This fixes two bugs:
- Comparison of EC keys and missing Ed25519 key comparison
- Ensuring RSAPublicKey is always set, allowing us to unconditionally use it in some places.

Better transit import export semantics

---

builtin/logical/pki/acme_errors.go
builtin/logical/pki/acme_wrappers.go
builtin/logical/pki/backend.go
builtin/logical/pki/path_acme_test.go
builtin/logical/pki/path_config_acme.go
builtin/logical/pki/path_config_cluster.go

Two minor fixes within this PR, along with the enforcing of the `path` argument is set when enabling ACME
1. Fix ACME error translation code, if we don't match one of the ACME errors force ErrServerInternal instead of the last element that we iterated over
2. One of the logger statements was missing its argument name being passed into the call.

Enforce PKI cluster local 'path' argument is set when enabling ACME

---

builtin/logical/pki/acme_wrappers.go
builtin/logical/pki/path_acme_order.go
builtin/logical/pki/path_acme_test.go
builtin/logical/pkiext/pkiext_binary/acme_test.go

This PR includes two fixes we have been discussing in meetings
- We now override the issuer's `leaf_not_after_behavior` to `truncate` if it is set to `err` to allow certificate issuance when an issuer's `NotAfter` time is approaching. This was mainly done as we currently don't allow ACME clients to specify TTL values
- When signing a certificate, we now validate that the only ExtKeyUsage flag set can be the ServerAuth type.

ACME behavior changes - ExtKeyUsage verification and issuer leaf_not_after

---

builtin/logical/pki/path_acme_challenges.go
builtin/logical/pki/path_acme_test.go

Within the ACME spec section [7.5.1 Responding to Challenges](https://www.rfc-editor.org/rfc/rfc8555#section-7.5.1), mentions "{}" payload means client is accepting the challenge 
>  The client indicates to the server that it is ready for the challenge
>  validation by sending an empty JSON body ("{}") carried in a POST
>  request to the challenge URL (not the authorization URL).
But [6.3 GET and POST-as-GET Requests](https://www.rfc-editor.org/rfc/rfc8555#section-6.3), talks about "" as a payload
>  If a client wishes to fetch a resource from the server (which would
>  otherwise be done with a GET), then it MUST send a POST request with
>  a JWS body as described above, where the payload of the JWS is a
>  zero-length octet string.  In other words, the "payload" field of the
>  JWS …

Only accept an ACME challenge when payload is an empty JSON object not an empty string 

---

website/content/docs/release-notes/1.14.0.mdx
website/content/docs/upgrading/upgrade-to-1.14.x.mdx
website/content/partials/ui-pki-control-groups-known-issue.mdx
website/data/docs-nav-data.json

We've already identified a known issue for 1.14, so adding these draft docs (based on #18023 🙇)
The Known Issue in question happens when a user has a control group on reading a PKI issuer -- going to the Issuer details page from the list page will result in a UI loop as shown in the gif below:
The workaround is to access issuer details from the shortcut box on the Overview page:

Add 1.14 draft docs and UI known issue

---

command/agent/exec/exec.go

There is a potential issue with the existing code where `<-proc.ExitCh()` can return a `nil` channel. This is because the `ExitCh` is initialized within `Start()`not `New(...)`.
This PR fixes the potential race condition by calling Start() before the `<-proc.ExitCh()` is invoked.

agent: Fix a potential race condition in process supervisor mode

---

website/content/api-docs/secret/databases/mongodbatlas.mdx
website/content/docs/secrets/databases/index.mdx
website/content/docs/secrets/databases/mongodbatlas.mdx
website/content/partials/db-secrets-credential-types.mdx

This PR adds documentation for the new credential type `client_certificate` for MongoDB Atlas Secrets Engine

Add docs for new client cert credential type

---

command/agent.go

when trying out the new feature @averche  reported that the app never started. turned out this piece was missing from the original PR

Enable sending new tokens to agent exec server 

---

CODEOWNERS
builtin/logical/pkiext/pkiext_binary/acme_test.go

- Make sure we can unregister ACME accounts through Certbot to provide an additional validation.
- Add vault-crypto as a code owner for builtin/logical/pkiext

Add Certbot unregister integration test 

---

builtin/logical/transit/backend.go
builtin/logical/transit/path_byok.go
builtin/logical/transit/path_byok_test.go
changelog/20736.txt
go.mod
go.sum
sdk/go.mod
sdk/go.sum
sdk/helper/keysutil/policy.go
website/content/api-docs/secret/transit.mdx

This still needs tests, but this adds the bulk of the work to support BYOK exporting of keys, now that https://github.com/hashicorp/vault/pull/17934 has landed.
In particular, the combination of the two features allows an operator to securely establish key material between two separate Transit installations. This potentially allows one cluster to be used as a source cluster (encrypting a large amount of data) and a second cluster to decrypt this data later. This might be useful in hybrid or site-specific deployments of Vault for instance.
---
I want to make additional changes to `bump_version` before release, and wanted a way of testing export + import of keys easily, plus wanted to enable this particular use case.
In the future, it might be nice to move `UnwrapKey` into the shared …

Transit BYOK export capabilities

---

ui/lib/pki/addon/components/pki-issuer-cross-sign.js
ui/tests/integration/components/pki/pki-issuer-cross-sign-test.js

Before catching this error, step 4 was renaming the existing issuer instead of the new one. This is because during the issuer mapping process we use the key material of the existing issuer to find the new `issuer_id`, however in self-cross-signing this mapped to the existing `issuer_id` instead.
After discussing with @cipherboy we decided it best to prevents a user from cross-signing an issuer against itself in the UI. This is a more complex operation that should be handled manually by using the CLI. Now we check if the issuer inputted in "current issuer name" matches the id of the root issuer (where this cross-signing process begins) then we return and throw the error for that row. 
Note, any other valid issuers will still be cross-signed, this will only throw an error for invalid …

ui: pki prevent user from self cross-signing root issuer

---

builtin/logical/pki/path_tidy.go
builtin/logical/pki/path_tidy_test.go

This should help to prevent the issue of missing tidy configurations in the future, by placing all related configuration options at the top with common validation logic.
However, short from this approach is ensuring that each config option can be specified independently. Thus, the test allows (for any added and properly tracked tidy operations) verifying that we have enabled proper storage/retention of that attribute.

Fix enabling tidy_acme=true in auto-tidy config

---

builtin/logical/consul/path_config.go
changelog/20891.txt

When returning a logical error, we need to include all of the information the user should see within the response. As seen in #18705, there is currently no indication of _why_ the bootstrapping failed when it does.
Before:
```shell-session
$ vault write consul/config/access \
address="https://127.0.0.1:8500"
Error writing data to consul/config/access: Error making API request.
URL: PUT http://127.0.0.1:8200/v1/consul/config/access
Code: 400. Errors:
* Token not provided and failed to bootstrap ACLs
```
After:
```shell-session
$ vault write consul/config/access \
address="https://127.0.0.1:8500"
Error writing data to consul/config/access: Error making API request.
URL: PUT http://127.0.0.1:8200/v1/consul/config/access
Code: 400. Errors:
* Token not provided and failed to bootstrap ACLs: …
```

Improve consul secrets plugin error for failed bootstrap

---

command/agent/exec/exec.go

Since we are running consul-template manager in `dry` mode to render environment variable templates, they are by default [printed to `stdout`](https://github.com/hashicorp/consul-template/blob/29885821b9d62f06b28ce657e33923994069aa18/renderer/renderer.go#L98-L100), which means that secrets could be easily leaked.
___
This is a follow up to https://github.com/hashicorp/vault/pull/20628 and is part of a larger effort to introduce environment variable support in Vault Agent ([VLT-253](https://docs.google.com/document/d/1HLTkPtxUTtW-wMkePWoHmZoGt9lLg2POslt1ranaWE8/edit#)).
[VLT-253]: https://hashicorp.atlassian.net/browse/VLT-253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

agent: Don't render templates to stdout in supervisor mode

---

command/agent.go

This is a small follow up to #20628 to prevent errors from being printed if the child process exits on its own with error code `0`.

agent: Don't print errors on exit 0 in supervisor mode

---

changelog/20882.txt
go.mod
go.sum

Updates vault-plugin-database-mongodbatlas to [v0.10.0](https://github.com/hashicorp/vault-plugin-database-mongodbatlas/releases/tag/v0.10.0)
Steps taken:
```
go get github.com/hashicorp/vault-plugin-database-mongodbatlas@v0.10.0
go mod tidy
```

Update MongoDB Atlas plugin to v0.10.0

---

builtin/logical/transit/path_backup_test.go

Missed this in #20864 :/ 
Will fix in backports manually, since most failed.

Fix formatting

---

changelog/20881.txt
sdk/framework/openapi.go

Fixes a minor annoyance I discovered whilst comparing before and after
OpenAPI specs whilst working on hashicorp/vault-client-go#180.
Sort the entries in a JSON array which has set semantics, after we
construct it by iterating a map (non-deterministic ordering).

Fix non-deterministic ordering of 'required' field in OpenAPI spec

---

changelog/20897.txt
ui/app/controllers/vault/cluster/init.js
ui/tests/acceptance/init-test.js

It was discovered that the `secret_shares` and `secret_threshold` properties are no longer allowed to be passed when unsealing a cloud seal type cluster. These properties were being passed in the UI causing the unseal to fail. Removing these properties from the payload for seal types other than `shamir` allows the cluster to be unsealed as expected. 
Error before fix:
After fix:
https://github.com/hashicorp/vault/assets/24611656/e7270e83-8d94-41b5-ad59-750973c76b84
Resolves #20644

UI cluster unseal bug

---

ui/lib/pki/addon/components/pki-generate-csr.ts
ui/lib/pki/addon/components/pki-generate-root.ts
ui/lib/pki/addon/components/pki-import-pem-bundle.ts
ui/lib/pki/addon/components/pki-sign-intermediate-form.ts

For certain PKI forms we show the results on the same page rather than transitioning to a new page. This PR adds a window scroll back to the top of the page for those forms, so that it feels like other post-save transitions.

UI: Scroll to top after PKI form save

---

vault/external_tests/raft/raft_autopilot_test.go
vault/external_tests/raft/raft_test.go

The raft tests are our slowest test package, which means speeding them up speeds up our feedback loop, since test CI is as slow as the slowest package.  I might be making them flakier by doing this, but let's try it, we can always revert.

Add more parallelism to raft tests.

---

builtin/logical/pkiext/pkiext_binary/acme_test.go

- Saw a test failure when we generated an EAB key that started with -
```
acme_test.go:249: Certbot Issue Command: [certbot certonly
--no-eff-email --email certbot.client@dadgarcorp.com --eab-kid
0246913b-4382-10fc-bf57-b05f2dad0f13 --eab-hmac-key
-Avt5q_KUWWWL8slYJn_MdmiCA-jzvif6Tpt45gQNR0 --agree-tos --no-verify-ssl
--standalone --non-interactive --server
...
certbot: error: argument --eab-hmac-key: expected one argument
```

Escape the ACME eab key in the certbot command line within integration tests

---

builtin/logical/pki/acme_challenge_engine.go
builtin/logical/pki/acme_errors.go
builtin/logical/pki/path_acme_order.go
builtin/logical/pki/path_acme_test.go

- We now populate the error field within challenges with the error results from the challenge
- Update the status of the challenge and authorizations to invalid when we give up on the challenge
- Verify that only a single challenge within a given authorization can be accepted to avoid race conditions.
- Also address the computed ACME order status 
This addresses: VAULT-16701

Fix order, authorization, challenge status when failing to validate a challenge

---

command/agent.go
command/agent/config/config.go
command/agent/config/test-fixtures/config-env-templates-complex.hcl

Without this change we are currently getting the following error when `cache {}` is defined in agent config file:
```sh
error validating configuration: enabling the cache requires at least 1 template or 1 listener to be defined
```
_____
This PR is part of a larger effort to implement secrets as environment variable support in agent ([VLT-253](https://docs.google.com/document/d/1HLTkPtxUTtW-wMkePWoHmZoGt9lLg2POslt1ranaWE8/edit#))
[VLT-253]: https://hashicorp.atlassian.net/browse/VLT-253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

agent: Allow for a 'cache' stanza in environment template configuration

---

ui/app/models/secret-engine.js
ui/lib/ldap/addon/components/tab-page-header.hbs
ui/tests/integration/components/ldap/tab-page-header-test.js

This PR adds a header component for the LDAP secrets engine pages with breadcrumbs, tabs, toolbar filters and actions.

LDAP Secrets Engine Header Component

---

builtin/logical/pki/acme_wrappers.go
builtin/logical/pki/path_config_acme.go
website/content/api-docs/secret/pki.mdx

This changes all references to default_role to default_directory_policy which can be set to:
* "role:<role_name>" which behaves exactly the same as default_role did
* "forbid" which prevents usage of the default_directory
* "sign-verbatim" which allows the default_directory to be used like sign-verbatim
This is a more flexible structure for future improvements.
Sign-verbatim functions when allowed_roles are also specified.

Change from default_role to default_directory_policy

---

ui/lib/pki/addon/components/page/pki-issuer-details.hbs
ui/lib/pki/addon/components/page/pki-issuer-details.ts
ui/lib/pki/addon/components/parsed-certificate-info-rows.hbs
ui/lib/pki/addon/components/parsed-certificate-info-rows.ts
ui/tests/helpers/pki/pki-issuer-details.js
ui/tests/integration/components/pki/parsed-certificate-info-rows-test.js
ui/tests/integration/components/pki/pki-issuer-details-test.js

This removes the alert banner from leaf certs and only renders it on the issuer details view. Also updates the copy to mention cross-signing must happen manually.

UI: pki only render unable to parse banner on issuer details page

---

command/agent/config/config.go
command/agent/exec/exec.go
command/agent/exec/exec_test.go

We receive multiple events every `staticSecretRenderInterval` from `<-s.runner.TemplateRenderedCh()`, one for each secret. Only the last event in a batch will contain the latest set of all secrets and the corresponding environment variables. To account for this, we are adding "[debouncing](https://en.wikipedia.org/wiki/Switch#Debouncing)" logic with a timer that will fire after 2 seconds unless an event comes in which resets the timer back to 2 seconds.
___
This PR is part of a larger effort to implement secrets as environment variable support in agent ([VLT-253](https://docs.google.com/document/d/1HLTkPtxUTtW-wMkePWoHmZoGt9lLg2POslt1ranaWE8/edit#))
[VLT-253]: https://hashicorp.atlassian.net/browse/VLT-253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS …

agent: Prevent multiple restarts of child process in supervisor mode

---

vault/activity_log.go
vault/activity_log_test.go
vault/logical_system_test.go
vault/testing.go

Example failure: https://github.com/hashicorp/vault-enterprise/actions/runs/5144577938/jobs/9261153205
Fix is never starting the fragment worker instead of racing on stopping it. I added a log (since removed) so we can see more details about failures:
```
2023-06-01T09:41:46.769-0400 [TRACE] TestActivityLog_MultipleFragmentsAndSegments.activity: new local fragment created
2023-06-01T09:41:46.769-0400 [TRACE] TestActivityLog_MultipleFragmentsAndSegments.activity: shutting down activeFragmentWorkder
```
The issue was that by closing doneCh, we were hoping that our read of newFragmentCh wouldn't race with activeFragmentWorker's read. However, we don't control when activeFragmentWorker gets scheduled by the runtime, and sometimes it doesn't get scheduled until the new fragment has been …

Deflake TestActivityLog_MultipleFragmentsAndSegments

---

command/agent/exec/exec.go

There is an issue with the current agent supervisor mode where it occasionally exits while restarting the child process. The reason for it is that the `ExitCh` is [closed](https://github.com/hashicorp/consul-template/blob/e97a929318455f1ff0d11360a746412d633a004c/child/child.go#L342), which triggers an event causing an exit.
___
This PR is part of a larger effort to implement secrets as environment variable support in agent ([VLT-253](https://docs.google.com/document/d/1HLTkPtxUTtW-wMkePWoHmZoGt9lLg2POslt1ranaWE8/edit#))
[VLT-253]: https://hashicorp.atlassian.net/browse/VLT-253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

agent: Fix bug with early exits during restarts in supervisor mode

---

website/content/docs/enterprise/license/utilization-reporting.mdx
website/data/docs-nav-data.json

🎫 [SPE-41](https://hashicorp.atlassian.net/browse/SPE-41)
🔍 [Deploy preview](https://vault-git-docs-licnse-utilization-hashicorp.vercel.app/vault/docs/enterprise/license/utilization-reporting)
This PR adds a doc to describe the new automated license utilization reporting based on the [template](https://docs.google.com/document/d/18aZmcxMFMuVpoKdn-psDov9eQQy41yz2Bcvfd4PtQFs/edit#heading=h.4w8f3icadrv9). 
This is part of the [Consensus service integration](https://hashicorp.atlassian.net/browse/VAULT-13008).
[SPE-41]: https://hashicorp.atlassian.net/browse/SPE-41?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Automatic license utilization reporting

---

website/content/docs/platform/k8s/helm/run.mdx

Can be beneficial to know for users updating vault helm chart to delete standby pods sequentially to not break quorum and cause downtime.

Clarify vault helm upgrade instructions in HA mode

---

builtin/credential/aws/backend_e2e_test.go
builtin/logical/database/backend_test.go
command/agent_test.go
command/proxy_test.go
helper/testhelpers/minimal/minimal.go
vault/expiration_integ_test.go
vault/external_tests/approle/wrapped_secretid_test.go
vault/external_tests/expiration/expiration_test.go
vault/external_tests/identity/aliases_test.go
vault/external_tests/identity/entities_test.go
vault/external_tests/identity/group_aliases_test.go
vault/external_tests/identity/groups_test.go
vault/external_tests/identity/identity_test.go
vault/external_tests/identity/login_mfa_duo_test.go
vault/external_tests/identity/login_mfa_okta_test.go
vault/external_tests/kv/kv_patch_test.go
vault/external_tests/kv/kv_subkeys_test.go
vault/external_tests/kv/kvv2_upgrade_test.go
vault/external_tests/mfa/login_mfa_test.go
vault/external_tests/policy/acl_templating_test.go
vault/external_tests/policy/policy_test.go
vault/external_tests/router/router_ext_test.go
vault/external_tests/token/batch_token_test.go
vault/external_tests/token/token_test.go
vault/logical_system_integ_test.go

… but has batteries included.  Very often tests call NewTestCluster but never talk to standbys or do anything that motivates a multi-node cluster.  NewTestSoloCluster will be faster and easier for the common case.

Introduce a wrapper for NewTestCluster that only supports single node

---

command/test-backend/main.go
enos/enos-scenario-agent.hcl
enos/enos-scenario-autopilot.hcl
enos/enos-scenario-replication.hcl
enos/enos-scenario-smoke.hcl
enos/enos-scenario-ui.hcl
enos/enos-scenario-upgrade.hcl
enos/enos-variables.hcl
enos/modules/build_local/main.tf
enos/modules/get_local_metadata/main.tf
enos/modules/vault_cluster/main.tf
enos/modules/vault_cluster/outputs.tf
enos/modules/vault_cluster/scripts/create_audit_log_dir.sh
enos/modules/vault_cluster/scripts/enable_audit_logging.sh
enos/modules/vault_cluster/variables.tf
enos/modules/vault_get_cluster_ips/main.tf
enos/modules/vault_setup_perf_primary/main.tf
enos/modules/vault_unseal_nodes/main.tf
enos/modules/vault_verify_performance_replication/main.tf
enos/modules/vault_verify_read_data/main.tf
enos/modules/vault_verify_write_data/main.tf

- Updated the `vault_cluster` enos module to add support for enabling the file audit device. 
- Updated the all scenarios to add support for enabling the file audit device.

[QT-426] Add support for enabling the file audit device for enos scenarios

---

builtin/logical/pki/acme_billing_test.go
builtin/logical/pki/path_acme_test.go

- Since we can't control the challenge engine, flush the validation records it leverages prior to manually updating the authorization/challenge statuses
- This test became flaky due to the order status fix within #20914 as we now started racing against the failure status updates added in that PR.
- With this fix, I was able to successfully run the tests over 1k iterations without failure in untilfail
```
path_acme_test.go:261: csr: &{[] [] [] [] 0 [] 0 0 <nil> CN=*.localdomain [] [] [] [localhost.localdomain *.localdomain] [] [] []}
path_acme_test.go:300:
Error Trace:	/home/runner/actions-runner/_work/vault-enterprise/vault-enterprise/builtin/logical/pki/path_acme_test.go:300
Error:      	Received unexpected error:
403 urn:ietf:params:acme:error:orderNotReady: The request attempted to …
```

Attempt to resolve flaky test TestAcmeBasicWorkflow test

---

changelog/20964.txt
vault/identity_store_groups.go

https://hashicorp.atlassian.net/browse/VAULT-16649
Vault does not prevent the creation of duplicate groups when multiple "create group" requests with the same group name are sent simultaneously to different nodes. The issue arises because Vault relies on the view of MemDB from IdentityStore, which is independent for each node, to check for the presence of another group with the same name. As a result, when requests occur within a short time frame, the MemDB on each node may not have the group names.
Currently, the request is only forwarded to the active node for writing to storage based on the ID i.e, as part of UpsertGroupInTxn function, we would only forward the write to storage request using SendGroupUpdate https://github.com/hashicorp/vault-enterprise/blob/5e4c01ae563d2ad3f4138171e95cb …

Duplicate groups creation bug 

---

command/agent_generate_config.go

This PR adds a more descriptive `vault agent generate-config --help` entry:
```
$ vault agent generate-config --help
Usage: vault agent generate-config [options] [path/to/config.hcl]
Generates a simple Vault Agent configuration file from the given parameters.
Currently, the only supported configuration type is 'env-template', which
helps you generate a configuration file with environment variable templates
for running Vault Agent in process supervisor mode.
For every specified secret -path, the command will attempt to generate one or
multiple 'env_template' entries based on the JSON key(s) stored in the
specified secret. If the secret path ends with a '/*', the command will
attempt to recurse through the secrets tree rooted at the given path,
generating 'env_template' entries for each …
```

agent: Better help text for agent generate-config

---

enos/modules/vault_cluster/main.tf
enos/modules/vault_cluster/scripts/enable_audit_logging.sh

Updated the `vault_cluster` module to ensure that the file audit device is only enabled if the cluster is initialized.

[QT-426] Ensure file audit device is only enabled if the leader is initialized

---

builtin/logical/pki/path_acme_eab.go
builtin/logical/pki/path_acme_test.go
website/content/api-docs/secret/pki.mdx

- To avoid people having issues copying EAB tokens and using them on command lines when they start with - from the base64 encoded values, append a prefix.
- Remove the key_bits data from the eab api, not really useful and now technically wrong
- Fix up some issues with tests not running in parallel.
- Update docs to reflect new EAB apis.

Generate ACME EAB tokens that do not start with '-'

---

changelog/20841.txt
sdk/framework/openapi.go

Duration are sent as strings today (e.g. `"10s"`, `"20m"`, etc.), which breaks the code generated based on the current OpenAPI spec which encodes them as integers. This small fix addresses the issue.
> **Note**: "duration" is not yet officially supported in the OpenAPI spec [as of v3.0.3](https://spec.openapis.org/oas/v3.0.3#data-types), but it is planned [in future versions](https://github.com/OAI/OpenAPI-Specification/issues/845). For now, this format will be ignored by the openapi-generator.

openapi: Fix generated types for duration strings

---

changelog/20986.txt
physical/raft/raft_autopilot.go
vault/logical_system_raft.go

Don't call AddPeer for a new raft cluster member until it's in raftFollowerStates, or it might get cleaned up by dead server cleanup.

Fix race with dead server cleanup when adding new raft nodes

---

builtin/credential/radius/backend_test.go
builtin/logical/nomad/backend_test.go
helper/testhelpers/cassandra/cassandrahelper.go
helper/testhelpers/ldap/ldaphelper.go
helper/testhelpers/mssql/mssqlhelper.go
helper/testhelpers/mysql/mysqlhelper.go
physical/aerospike/aerospike_test.go
physical/cockroachdb/cockroachdb_test.go
physical/couchdb/couchdb_test.go
physical/dynamodb/dynamodb_test.go
plugins/database/influxdb/influxdb_test.go

The OSS portion of the changes required to enable ARM tests nightly. Repeating the salient part from the enterprise PR:
As part of this, I've needed to skip a lot of OSS tests with docker images because of incompatible images (to use an example: we use MySQL 5.7, which doesn't support ARM64, and we'd need to upgrade to 8.0 to have that).

VAULT-14847 Skip cetain tests on ARM

---

changelog/20933.txt
vault/audit.go
vault/audit_broker.go
vault/audit_test.go

This PR cleans up an unused field in the **backendEntry** struct and removes function arguments that were only needed to initialize that unnecessary field in the struct.
As an added bonus, the few compiler warnings that were reported in the _audit_test.go_ file were also resolved.

Code Cleanup Around Audit Backends

---

enos/modules/vault_cluster/main.tf

Updated the `vault-cluster` module to always create the log file directory for the file audit device logs.

[QT-426] Always create the file audit directory

---

builtin/logical/pki/cert_util.go
builtin/logical/pki/path_acme_order.go
builtin/logical/pki/path_acme_test.go
changelog/20981.txt

- If the normal NotAfter date that is calculated from the mount/issuer/role TTL values is greater than 90 days, override the value to use 90 days.

Limit ACME issued certificates to a max of 90 days

---

website/content/docs/platform/k8s/index.mdx
website/content/docs/platform/k8s/vso/api-reference.mdx
website/content/docs/platform/k8s/vso/examples.mdx
website/content/docs/platform/k8s/vso/helm.mdx
website/content/docs/platform/k8s/vso/index.mdx
website/content/docs/platform/k8s/vso/installation.mdx
website/content/docs/platform/k8s/vso/telemetry.mdx
website/content/partials/vso-beta-note.mdx

* Adds HCP vault to supported installation page
* Removes the beta tag everywhere
* Updates an out of date example to use role instead of name for PKI.

[docs] Remove beta tag and update example code
