enos/enos-scenario-autopilot.hcl
enos/modules/vault_cluster/main.tf
enos/modules/vault_cluster/scripts/create_audit_log_dir.sh

- The `get_updated_cluster_ips` step for autopilot was corrected to check for the leader IP in the upgraded cluster hosts
- Updated the path to the audit log file to `/var/log/vault`
- Added a retry to allow time for the vault user creation to complete before creating the vault audit log directory

Fix autopilot scenario failures

---

go.mod
go.sum

This PR upgrades hashicorp/cap to [v0.3.1](https://github.com/hashicorp/cap/releases/tag/v0.3.1) to fix failing tests in the nightly 32bit runs. We use this library as an OIDC client for the Vault OIDC provider tests, so this is not user facing (no changelog needed). Our tests exposed an issue in the library code. 
For details on the issue, see https://github.com/hashicorp/cap/pull/76.

Upgrade hashicorp/cap to fix OIDC provider test on 32bit

---

ui/app/components/license-banners.js
ui/app/lib/local-storage.js
ui/app/templates/vault/cluster.hbs
ui/tests/integration/components/license-banners-test.js
ui/tests/unit/lib/local-storage-test.js

There was a bug on the dismiss license banners for the following flow:
1. I dismiss a warning that my license is going to expire (or has expired).
2. I update my license.
3. For however long that new license works for I never update my version of vault or clear local storage .
4. A year or whatever later I get another warning that the license is going to expire. That banner does not show.
To fix this I had to be careful about the data I used to add to the key in local storage. I couldn't safely use anything from the `sys/license` endpoint because what if a user didn't have permissions to that but the user before them on the same computer did? They technically could see something saved in local storage from that endpoint. Thus, I went with the `expiry_time` which comes off the …

License banner - check for new license on localStorage.

---

ui/app/router.js
ui/app/routes/vault/cluster/dashboard.js
ui/app/templates/vault/cluster/dashboard.hbs
ui/tests/unit/routes/vault/cluster/dashboard-test.js

- Initial dashboard route set up
- I created card blocks in the route template for some of the sections and the content in the screenshot is not finalized and is just a placeholder.

UI: VAULT-16941 Initial dashboard route set up

---

builtin/logical/pkiext/pkiext_binary/acme_test.go
builtin/logical/pkiext/test_helpers.go
helper/testhelpers/testhelpers.go

#Summary
Adds an ACME validation failure test for certbot that doesn't run in CI unless a particular regression test env var is provided. Also includes a helper function to determine whether or not CI is running and if the regression test env var is provided.

Adds an ACME validation failure test for certbot.

---

website/content/docs/upgrading/upgrade-to-1.12.x.mdx
website/content/docs/upgrading/upgrade-to-1.13.x.mdx

Reported in https://github.com/hashicorp/vault/issues/21042 and the [fix](https://github.com/hashicorp/vault/pull/18186) is being backported to 1.12 and 1.13.

secret/pki: add known issue for slow startup times

---

ui/app/components/license-banners.js
ui/app/lib/local-storage.js
ui/tests/integration/components/license-banners-test.js
ui/tests/unit/lib/local-storage-test.js

License banner - check for new license on localStorage.[ (#20999)](https://github.com/hashicorp/vault/pull/20999/files)
Manual backport. Did not include the conditional around the LicenseBanners in the cluster.hbs. This file is significantly different because of the sidebar work from 1.14. And it was a nice to have anyways, there is no change in functionality.

Backport 1.13.x: License banner fix with expiry on localStorage key name

---

.gitignore
enos/enos-modules.hcl
enos/enos-terraform.hcl
enos/k8s/enos-modules-k8s.hcl
enos/k8s/enos-scenario-k8s.hcl
enos/k8s/enos-terraform-k8s.hcl
enos/modules/vault_cluster/main.tf
enos/modules/vault_cluster/variables.tf

Temporarily pin the enos provider to < 0.4.0 to gracefully roll out new provider changes. We also include some minor changes to handle new features coming in the consul module.

[QT-509] enos: pin to enos-provider < 0.4.0

---

enos/enos-modules.hcl
enos/enos-scenario-agent.hcl
enos/enos-scenario-autopilot.hcl
enos/enos-scenario-replication.hcl
enos/enos-scenario-smoke.hcl
enos/enos-scenario-upgrade.hcl
enos/enos-terraform.hcl
enos/modules/vault_cluster/main.tf
enos/modules/vault_cluster/variables.tf

Use the latest version of enos-provider and upstream consul module. These changes allow us to configure the vault log level in configuration and also support configuring consul with an enterprise license.

[QT-527][QT-509] enos: use latest version of enos-provider

---

enos/enos-scenario-agent.hcl
enos/enos-scenario-autopilot.hcl
enos/enos-scenario-replication.hcl
enos/enos-scenario-smoke.hcl
enos/enos-scenario-upgrade.hcl
enos/modules/vault_cluster/templates/install-packages.sh

We seen instances where we try to schedule a spot fleet in the us-east-1d of the vault CI AWS account and cannot get capacity for our instance type. That zone currently supports far fewer instance types so we'll bump our max bid to handle cases where slightly more expensive instances are available. Most of the time we'll be using much cheaper instances but it's better to pay a fraction of a cent more than have to retry the pipeline. As such, we increase our max bid price to something that will almost certainly be fullfilled.
We also allow our package installer to go ahead when cloud init does not update sources like we expect. This should handle occasional failures where cloud-init doesn't update the sources within a reasonable amount of time.

test: handle occasional lower capacity in zone d

---

website/content/docs/commands/pki/health-check.mdx

Update the existing PKI health-check docs to add the two new health-checks that were added in the 1.14.x release.

Update docs for new 1.14 ACME health checks

---

vault/seal_autoseal.go
vault/seal_util.go

Centralize the seal wrapping/unwrapping of recovery keys, just as we did for the the stored barrier key in #21044.

Refactor seal wrapping of recovery keys.

---

website/content/api-docs/secret/pki.mdx

Adds the `remove_roots_from_chain` option to the docs for `/pki/issue`, based on [addNonCACommonFields()](https://github.com/hashicorp/vault/blob/4620a301dfe4a9be03f09c51ca8be93d20a60be5/builtin/logical/pki/fields.go#L95).

docs/pki: add remove_roots_from_chain option to /pki/issue

---

changelog/21110.txt
vault/core.go
vault/logical_system.go
vault/request_handling.go

I'm working on some code in ent that messes with how we use these locks, so I turned on deadlock detection, and I found a pre-existing issue.  Creating this PR to highlight it.

Fix: non-login requests shouldn't care about login roles for lease quotas.  Also fix a potential deadlock

---

builtin/logical/pki/backend.go
builtin/logical/pki/backend_test.go
builtin/logical/pki/cert_util.go
builtin/logical/pki/crl_util.go
builtin/logical/pki/fields.go
builtin/logical/pki/path_issue_sign.go
builtin/logical/pki/path_root.go
builtin/logical/pki/path_tidy.go
builtin/logical/pki/path_tidy_test.go
builtin/logical/pki/storage.go
changelog/18186.txt

* Telemetry Metrics Configuration.
* Err Shadowing Fix (woah, semgrep is cool).
* Fix TestBackend_RevokePlusTidy_Intermediate
* Add Changelog.
* Fix memory leak.  Code cleanup as suggested by Steve.
* Turn off metrics by default, breaking-change.
* Show on tidy-status before start-up.
* Fix tests
* make fmt
* Add emit metrics to periodicFunc
* Test not delivering unavailable metrics + fix.
* Better error message.
* Fixing the false-error bug.
* make fmt.
* Try to fix race issue, remove confusing comments.
* Switch metric counter variables to an atomic.Uint32
- Switch the metric counter variables to an atomic variable type so that we are forced to properly load/store values to it
* Fix race-issue better by trying until the metric is sunk.
* make fmt.
* empty commit to retrigger non-race …

Backport of Telemetry Metrics Configuration. (#18186) into release/1.12.x

---

.github/workflows/build.yml
.release/ci.hcl

Finally! 😄 
Sorry that this was missed with all the CircleCI migration work.
This reduces all of the binary processing common workflows (sign, notarize etc..) to just the one `prepare` workflow. More runs in parallel, so execution time is cut down. See [here](https://hashicorp.atlassian.net/wiki/spaces/RELENG/pages/2489712686/Dec+7th+2022+-+Introducing+the+new+Prepare+workflow) for more info.
This is the result of the prepare workflow run from this branch - https://github.com/hashicorp/crt-workflows-common/actions/runs/5258231286

Onboard Vault to the prepare workflow.

---

builtin/logical/pki/path_acme_revoke.go
builtin/logical/pki/path_acme_test.go
builtin/logical/pki/path_revoke.go

ACME's proof of possession based revocation uses a signature from the private key, but only sends the public copy along with the request. Ensure the public copy matches the certificate, instead of failing to cast it to a private key.

Correctly validate ACME PoP against public key

---

builtin/logical/pki/backend_test.go
builtin/logical/pki/cert_util.go
changelog/21209.txt

When templating is enabled in `config/urls`, with a URL that includes the best-practice suggestion of `{{issuer_id}}`, we fail to generate root CAs because there is no issuer ID yet. While this is true, the best practice _is_ to include `{{issuer_id}}` on the AIA info, but Root CAs need not specify AIA info; indeed, most public root CAs do not.
Instead of erring, allow this issuance to silently succeed with no AIA information; if AIA information is necessary, it can be manually specified (e.g., using `enable_templating=false` or without `{{issuer_id}}`, such as with a fixed, manually-specified name for this one root certificate).

Allow issuance of root certs no AIA when templating is enabled

---

changelog/21223.txt
sdk/physical/cache.go

Add barrierSealConfigPath and recoverySealConfigPlaintextPath to cacheExceptionsPaths in order to avoid a race that causes some nodes to always see a nil value.

Add paths for seal config to cache exceptions.

---

ui/app/templates/components/database-connection.hbs
ui/app/templates/components/database-role-edit.hbs
ui/app/templates/components/generate-credentials-database.hbs
ui/app/templates/components/generate-credentials.hbs
ui/app/templates/components/license-banners.hbs
ui/app/templates/components/oidc-callback-splash.hbs
ui/app/templates/components/raft-join.hbs
ui/app/templates/components/raft-storage-restore.hbs
ui/app/templates/components/role-aws-edit.hbs
ui/app/templates/components/secret-create-or-update.hbs
ui/lib/core/addon/components/alert-banner.hbs
ui/tests/acceptance/client-dashboard-test.js
ui/tests/acceptance/enterprise-license-banner-test.js
ui/tests/acceptance/pki/pki-action-forms-test.js
ui/tests/acceptance/secrets/backend/database/secret-test.js
ui/tests/acceptance/secrets/backend/kv/secret-test.js
ui/tests/acceptance/settings/mount-secret-backend-test.js
ui/tests/helpers/pki/workflow.js
ui/tests/integration/components/license-banners-test.js
ui/tests/integration/components/oidc/client-form-test.js
ui/tests/integration/components/oidc/key-form-test.js
ui/tests/integration/components/oidc/provider-form-test.js
ui/tests/integration/components/oidc/scope-form-test.js
ui/tests/integration/components/pki/page/pki-issuer-rotate-root-test.js
ui/tests/integration/components/pki/pki-generate-csr-test.js
ui/tests/integration/components/pki/pki-issuer-cross-sign-test.js

UI: HDS adoption replace AlertBanner part 1

---

ui/lib/pki/addon/decorators/check-issuers.js
ui/lib/pki/addon/routes/certificates/index.js
ui/lib/pki/addon/routes/configuration/index.js
ui/lib/pki/addon/routes/keys/index.js
ui/lib/pki/addon/routes/overview.js
ui/lib/pki/addon/routes/roles/index.js
ui/lib/pki/addon/routes/tidy.js

To differentiate from the `fetch-secrets-engine-config` decorator in the core addon which is being implemented as part of the LDAP secrets engine work, this PR renames the `check-config` decorator in the PKI engine to `check-issuers`.

Rename PKI check-config Decorator

---

changelog/16000.txt
changelog/16146.txt
changelog/16162.txt
changelog/16184.txt
changelog/16447.txt
go.mod
go.sum
vault/activity_log.go
vault/activity_log_test.go
vault/activity_log_util_common.go
vault/activity_log_util_common_test.go
vault/logical_system_activity.go

This PR encapsulates the backports for ActivityLog changes to get more correct current month estimates using HLL sketches.
This is a pre-cursor to the [ActivityLog backport for 1.11.x](https://github.com/hashicorp/vault/pull/21210). Once merged, we can rebase that PR to get feature parity across 1.11-1.14.
Apologies for the large PR. It may be easiest to review by comparing each backport commit with the original. I can split this up if others think it's worthwhile.

backports for HLL estimates in ActivityLog 1.11.x

---

changelog/12166.txt
physical/raft/fsm.go
physical/raft/raft.go
physical/raft/raft_autopilot.go
vault/core.go
vault/core_metrics.go
vault/ha.go
vault/request_forwarding_rpc.go
website/content/docs/internals/telemetry.mdx

This required a manual backport since the original PR was before the GHA migration.
There was one conflict that needed to be resolved, I'll point it out in a comment

Backport to 1.11.x: Add more raft metrics, emit more metrics on non-perf standbys (#12166)

---

changelog/21249.txt
physical/raft/raft.go

... where RaftBackend.raft has been set to nil by TeardownCluster:
```
TestVaultExecClusterMigrateShamirToTransit-vault-srv-4: 2023-06-15T10:12:29.670-0400 [INFO]  core: vault is sealed
TestVaultExecClusterMigrateShamirToTransit-vault-srv-4: panic: runtime error: invalid memory address or nil pointer dereference
TestVaultExecClusterMigrateShamirToTransit-vault-srv-4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x27e2631]
TestVaultExecClusterMigrateShamirToTransit-vault-srv-4: 
TestVaultExecClusterMigrateShamirToTransit-vault-srv-4: goroutine 137 [running]:
TestVaultExecClusterMigrateShamirToTransit-vault-srv-4: github.com/hashicorp/raft.(*Raft).Stats(0x0)
TestVaultExecClusterMigrateShamirToTransit-vault-srv-4: …
```

Fix a panic I observed in a sealed node running CollectMetrics

---

changelog/21260.txt
helper/testhelpers/teststorage/teststorage.go
vault/auth.go
vault/core.go
vault/mount.go
vault/mount_util.go

This fixes a bug with backend initialization and path filters.  This requires that we hold both the mountsLock and authLock (instead of just one or the other) while calling it, so for simplicity we grab them both at the outset.
While working on this I noticed that ListAuths grabs the wrong lock, so I also fixed that.
And I modified ClusterSetup: as a convenience, it now populates the factories for all the builtin engines in the config it returns.

Call runFilteredPathsEvaluation from within mountInternal/enableCredentialInternal

---

builtin/logical/pki/acme_challenges.go
builtin/logical/pki/acme_challenges_test.go
builtin/logical/pkiext/pkiext_binary/acme_test.go
builtin/logical/pkiext/pkiext_binary/pki_cluster.go
builtin/logical/pkiext/pkiext_binary/pki_mount.go
builtin/logical/pkiext/pkiext_binary/testdata/caddy_http.json
builtin/logical/pkiext/pkiext_binary/testdata/caddy_http_eab.json
builtin/logical/pkiext/pkiext_binary/testdata/caddy_tls_alpn.json

Tests Vault issuing certificates to Caddy via ACME. Includes coverage for HTTP challenges, EAB functionality, and TLS-ALPN challenges.

Adds automated ACME tests using Caddy.

---

website/content/docs/agent-and-proxy/agent/caching/index.mdx
website/content/docs/agent-and-proxy/proxy/apiproxy.mdx
website/content/docs/agent-and-proxy/proxy/caching/index.mdx
website/content/docs/agent-and-proxy/proxy/index.mdx
website/content/docs/commands/agent.mdx
website/content/docs/commands/proxy.mdx
website/content/docs/get-started/developer-qs.mdx
website/data/docs-nav-data.json

Thanks to @miagilepner for finding some of these issues when testing! I also added some fixes to issues I found myself when I was poking around.
Docs are here, and all seems to be fixed: https://vault-3qm8zqt7a-hashicorp.vercel.app/vault/docs/agent-and-proxy

Fix some broken links/clarify some things in the Vault Proxy docs

---

.github/workflows/test-go.yml

It seems like this must've been lost somehow, though I haven't dug into how.  I changed the script yesterday, but it's always depended on having Go present.

Setup Go before calling the test package test script

---

changelog/21223.txt
sdk/physical/cache.go

Add paths for seal config to cache exceptions.
Add barrierSealConfigPath and recoverySealConfigPlaintextPath to cacheExceptionsPaths in order to avoid a race that causes some nodes to always see a nil value.

Backport: Add paths for seal config to cache exceptions. (#21223)

---

changelog/21297.txt
command/agent_generate_config.go
website/content/docs/agent-and-proxy/agent/generate-config/index.mdx

Fixing `vault agent generate-config` to accept `-namespace`, `VAULT_NAMESPACE`, and other client-modifying flags.
```sh
$ export VAULT_NAMESPACE="admin"
$ vault agent generate-config -type="env-template" -path="path/without/namespace" ...
```
OR
```sh
$ vault agent generate-config -type="env-template" -path="path/without/namespace" -namespace="admin" ...
```
This addresses VAULT-17295

agent: Fix agent generate-config to accept namespace

---

changelog/21342.txt
command/server.go

Fixes https://github.com/hashicorp/vault/issues/21338

Don't exit just because we think there was a possible deadlock

---

website/content/docs/secrets/pki/considerations.mdx

These don't do anything but reject requests:
> ```
> The server will not issue certificates for the identifier:
> role (something) will not issue certificate for name
> xps15.local.cipherboy.com
> ```

Add ACME consideration about entity templating

---

builtin/credential/aws/path_login.go
builtin/credential/aws/path_role_tag.go
builtin/logical/aws/path_config_lease.go
builtin/logical/pki/crl_test.go
builtin/logical/pki/crl_util.go
builtin/logical/pki/path_config_crl.go
builtin/logical/pki/path_ocsp.go
builtin/logical/pki/path_ocsp_test.go
builtin/logical/pki/path_tidy.go
changelog/21357.txt
command/base_flags.go
physical/raft/raft.go
physical/raft/raft_autopilot.go
sdk/database/dbplugin/v5/testing/test_helpers.go
sdk/helper/identitytpl/templating.go
sdk/helper/pointerutil/pointer.go
tools/semgrep/ci/time-parse-duration.yml
vault/identity_store_oidc_provider_test.go
vault/logical_system_activity.go
vault/token_store.go

Vault's duration string format is supports a strict superset of options compared to Go's duration string format: https://developer.hashicorp.com/vault/docs/concepts/duration-format
In particular, we support days, e.g. `5d`, whereas `time.ParseDuration` does not.
We use `parseutil.ParseDurationSeconds` everywhere in the code we can, to support our advertised duration format and to be consistent with ourselves. The majority of our code already uses `parseutil.ParseDurationSeconds`, but there were a few places I found that `time.ParseDuration` was still being used as part of poking around, so I thought I'd fix them all at once.
I'm not worried about the fact this change changes a lot of files. `ParseDurationSeconds` is battle-tested, and there's no valid duration that `time.ParseDuration` …

Replace all remaining time.ParseDurations with parseutil.ParseDurationSeconds

---

.github/workflows/ci.yml

Currently we rely heavily on branch naming prefixes to decide whether to run specific jobs within the `CI` workflow on open/ready PRs. This knowledge isn't known to all teams or contributors, but they may find the `docs` label more easily during the creation of their PR within GitHub.
This PR also checks for the existence of the `docs` label and if found, skips jobs which are not required.
The PR could be thought of as a more temporary fix as there may be additional use cases for `ui` and `backport` related labels too, and we could also consider our grouping of CI related jobs so that we could simplify using [paths-ignore](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths) for `website/content/**` in the future.
`Prettier` kindly …

Fix: prevent unrequired CI jobs running when 'docs' label is added

---

ui/app/adapters/ldap/config.js
ui/app/models/ldap/config.js
ui/lib/ldap/addon/components/page/configure.hbs
ui/lib/ldap/addon/components/page/configure.ts
ui/lib/ldap/addon/routes/configure.ts
ui/lib/ldap/addon/templates/configure.hbs
ui/lib/ldap/package.json
ui/tests/integration/components/ldap/page/configure-test.js
ui/types/vault/models/ldap/config.d.ts

This PR adds a page component for the ldap configure route that includes the form. 
https://github.com/hashicorp/vault/assets/24611656/460ced55-4f2f-47cc-b7cd-ba780517c140

LDAP Configure Page Component

---

website/content/api-docs/secret/transit.mdx

- The argument `bump_version` was removed within #20814 along the development path, but the documentation update was missed.

Remove bump_version from transit import docs

---

builtin/logical/pki/storage_migrations.go
builtin/logical/pki/storage_migrations_test.go
changelog/21316.txt
website/content/docs/upgrading/upgrade-to-1.11.x.mdx
website/content/docs/upgrading/upgrade-to-1.12.x.mdx
website/content/docs/upgrading/upgrade-to-1.13.x.mdx
website/content/partials/pki-double-migration-bug.mdx

Later in Vault 1.11, 1.12, and 1.13's release, we added a fix for a regression regarding chain building that resulted in a small migration to rebuild all issuer's chains within the mount. This resulted in a second storage migration "version" being created, which was unfortunate as the existing logic resulted in the entire migration being re-attempted:
```go
if (migrationInfo.migrationLog == nil) ||
(migrationInfo.migrationLog.Hash != migrationInfo.legacyBundleHash) ||
(migrationInfo.migrationLog.MigrationVersion != latestMigrationVersion) {  /// <<--- HERE
```
As a result, if the migrated legacy issuers (from storage version 0/1) were deleted prior to version 2's upgrade (to 1.13.0, 1.12.2, and 1.11.6), these would be recreated and would need to be removed again. Additionally, when …

Fix re-migration of existing CA bundles

---

builtin/credential/ldap/backend.go
builtin/credential/ldap/path_login.go
changelog/21282.txt
vault/request_handling.go

Attempts to fix https://github.com/hashicorp/vault/issues/20923.
With this change, every combination of an invalid username or invalid password when authenticating against LDAP should return an `HTTP 400` with the error message:
```json
{
"errors": [
"ldap operation failed: failed to bind as user"
]
}
```
Demo: 
https://github.com/hashicorp/vault/assets/6120955/3c3cc77a-054b-4efe-b86d-6d3cc57a21e7

normalize LDAP auth HTTP responses

---

website/content/docs/agent-and-proxy/agent/generate-config/index.mdx
website/content/docs/agent-and-proxy/agent/process-supervisor.mdx
website/content/docs/auth/jwt/index.mdx
website/content/docs/platform/k8s/vso/index.mdx
website/content/docs/secrets/ldap.mdx
website/content/docs/secrets/pki/index.mdx

This PR adds **Tutorial** section to those doc pages that has related tutorial(s).
🔍 [Deploy preview - PKI secrets engine](https://vault-git-docs-add-tutorial-links-hashicorp.vercel.app/vault/docs/secrets/pki#tutorial)
🔍 [Deploy preview - Vault Agent](https://vault-git-docs-add-tutorial-links-hashicorp.vercel.app/vault/docs/agent-and-proxy/agent/process-supervisor#tutorial)
🔍 [Deploy preview - OIDC auth](https://vault-git-docs-add-tutorial-links-hashicorp.vercel.app/vault/docs/auth/jwt#tutorial)
🔍 [Deploy preview - VSO](https://vault-git-docs-add-tutorial-links-hashicorp.vercel.app/vault/docs/platform/k8s/vso#tutorial)
🔍 [Deploy preview - LDAP secrets engine](https://vault-git-docs-add-tutorial-links-hashicorp.vercel.app/vault/docs/secrets/ldap#tutorial)

[Docs] Add cross-links to related tutorials

---

website/content/api-docs/secret/cubbyhole.mdx
website/content/api-docs/secret/kv/kv-v1.mdx
website/content/api-docs/secret/kv/kv-v2.mdx

There were a few things that could be clarified, so I clarified them. I left explanations in-line for my changes.
The most salient updates contained within this are the updates to the KV API docs not linking directly to the corresponding secret engine docs.

Some small KV API docs improvements

---

website/data/api-docs-nav-data.json

https://github.com/hashicorp/vault/pull/20595/files#diff-9c9c146a6465b0deafac528d60a94bee5f609ac37c203005bd3b5cda6c190882 was a contrib which added a new endpoint, however the ref to the page in api-docs-nav-data.json was incorrectly added and thus appears out of order in the left sidebar, i.e. https://developer.hashicorp.com/vault/api-docs/system/decode-token
preview: https://vault-j9dk3o0r1-hashicorp.vercel.app/vault/api-docs/system/decode-token

Fix incorrect ordering in api-docs-nav-data.json

---

website/content/api-docs/auth/ldap.mdx

https://github.com/hashicorp/vault/pull/18225 added the ability to authenticate to Vault using LDAP auth method while supplying the password via the `VAULT_LDAP_PASSWORD` environment variable, however the original PR didn't include any docs update so raising this PR to include a note. This functionality exists in Vault 1.14.0 onwards.
current page: https://developer.hashicorp.com/vault/api-docs/auth/ldap#login-with-ldap-user
preview: https://vault-ktgbkryd6-hashicorp.vercel.app/vault/api-docs/auth/ldap#login-with-ldap-user

[Docs] ldap auth add VAULT_LDAP_PASSWORD environment variable

---

enos/enos-modules.hcl
enos/enos-scenario-agent.hcl
enos/enos-scenario-autopilot.hcl
enos/enos-scenario-replication.hcl
enos/enos-scenario-smoke.hcl
enos/enos-scenario-ui.hcl
enos/enos-scenario-upgrade.hcl

We seem to hit occasional capacity issues when attempting to launch spot fleets with arm64 instance types. After checking pricing in the regions that we use, it appears that current and older generation amd64 t2 and t3 instance types are running at quite a discount whereas t4 arm64 instances are barely under on-demand price, suggesting limited capacity for arm64 spot instances at this time. We'll change our default backend instance architecture to amd64 to bid for the cheaper t2 and t3 instances and increase our `max_price` globally to that of a RHEL machine running on-demand with a t3.medium.

enos: use linux/amd64 for consul storage backend

---

sdk/framework/openapi.go
sdk/framework/openapi_test.go
sdk/framework/path.go

Vault API endpoints are defined using regexes in instances of the SDK's
framework.Path structure. However, OpenAPI does not use regexes, so a
translation is performed. It is technically possible that this
translation produces colliding OpenAPI paths from multiple
framework.Path structures. When this happens, there has formerly been no
diagnostic, and one result silently overwrites the other in a map.
As a result of this, several operations are currently accidentally
missing from the Vault OpenAPI, which is also the trigger for
https://github.com/hashicorp/vault-client-go/issues/180.
This PR adds a log message, to help catch such accidents so that they
can be fixed. Much of the PR is propagating a logger to the point where
it is needed, and adjusting tests for the API change.
With current …

Add a new log message, reporting collisions between OpenAPI paths

---

builtin/logical/pki/integration_test.go
builtin/logical/pki/path_fetch.go
builtin/logical/pki/path_fetch_issuers.go
builtin/logical/pki/path_issue_sign.go
builtin/logical/pki/path_manage_issuers.go
builtin/logical/pki/path_revoke.go
builtin/logical/pki/path_roles.go
builtin/logical/pki/path_tidy.go
changelog/21449.txt

The response schema for `pki/issue/*` requests have expiration represented as `int64` rather than a `string`.
https://github.com/hashicorp/vault/blob/922daee688f62e40da77ed42727958052811f830/builtin/logical/pki/path_issue_sign.go#L418-L421
This PR fixes the corresponding OpenAPI schema and should address https://github.com/hashicorp/vault-client-go/issues/185

openapi: Fix response schema for PKI Issue requests

---

builtin/logical/pki/path_acme_eab.go
changelog/21458.txt

- Do not generate duplicate operation ids for the various new-eab apis
- Fill out proper operation verb for eab delete call
- Pluralize operation verb for list-eab-keys api
- Fill out proper response data for new-eab and list-eab-keys

Fix OpenAPI spec definitions for PKI EAB APIs

---

website/content/docs/commands/auth/tune.mdx

Fix the reported issue: https://hashicorp.atlassian.net/browse/VAULT-10452
🔍 [Deploy preview](https://vault-git-docs-update-auth-tune-hashicorp.vercel.app/vault/docs/commands/auth/tune)
This PR:
- Makes minor format updates to improve readability
- Add a step to revert back the system default

[Docs] Add a step to revert the auth configuration

---

changelog/24170.txt
vault/auth.go
vault/mount.go

This is essentially the 'fix' code we used as part of resolving a recent sev 1, where we pre-calculate the namespace path, as we do in the other place we call `c.router.Taint(ctx, path)`. The PR for that change is here: #15067 . I added debug logging including the places where we disagree, and added it to the other place we pre-calculate namespace prefixes.
There may be more adjustments/improvements we want to make to add additional safety to tainting, such as preventing the root "sys/" from ever being tainted, but if we did want to add those, we can do as part of a different PR. I wanted to keep this PR with a small scope, specifically targeting the fix.

Calculate namespace prefix before tainting route entries

---

website/content/docs/upgrading/upgrade-to-1.14.x.mdx
website/content/partials/known-issues/ui-safari-login-screen.mdx
website/content/partials/safari-login-screen.mdx
website/content/partials/ui-safari-login-screen.mdx

There is a known issue on the 1.14 release for the Safari browser. When you navigate to the UI login screen there appears to be a large white screen. If you scroll down you can find the login area, but it's not immediately apparent. 
https://github.com/hashicorp/vault/assets/6618863/1283c19c-7a95-40c2-b5d5-62543964319c

Add UI safari login screen known issue

---

website/content/docs/platform/k8s/vso/index.mdx
website/content/docs/secrets/pki/index.mdx

Accidentally, I pointed to the tutorial in the [Vault 1.14 Release highlights](https://developer.hashicorp.com/vault/tutorials/new-release) collection. 
This PR points to the respective permanent collection link for those tutorials. 
- `/vault/tutorials/new-release/...` --> `/vault/tutorials/kubernetes/...` 
- `/vault/tutorials/new-release/...` -->  `/vault/tutorials/secrets-management/...`

[Docs] Update the tutorial links

---

ui/app/templates/components/keymgmt/key-edit.hbs
ui/app/templates/components/secret-delete-menu.hbs
ui/app/templates/vault/cluster/secrets/backend/metadata.hbs
ui/lib/core/addon/components/modal.hbs
ui/lib/core/addon/templates/components/replication-action-demote.hbs
ui/lib/core/addon/templates/components/replication-action-disable.hbs
ui/lib/core/addon/templates/components/replication-action-promote.hbs
ui/lib/core/addon/templates/components/replication-action-recover.hbs
ui/lib/core/addon/templates/components/replication-action-reindex.hbs
ui/lib/core/addon/templates/components/replication-action-update-primary.hbs
ui/lib/kmip/addon/templates/role.hbs
ui/lib/replication/addon/templates/components/known-secondaries-card.hbs
ui/tests/integration/components/replication-actions-test.js

For all titles that are not form titles (largely denoted in our app by the `class="title is-5"`) only the first word is capitalized. Below are some screenshot examples.
In overview cards
In detail pages broken up by sections
The title for modals
Ran the enterprise test suite locally ✅

Capitlization Policy: First word only for `title is-5`

---

.github/workflows/plugin-update-check.yml

The plugin dependency automation (ref: https://github.com/hashicorp/vault/pull/21491) needs a GH token set so that we can use the GH CLI. See failure here: https://github.com/hashicorp/vault/actions/runs/5405229617/jobs/9820485201

plugin: use gh token for plugin workflow

---

api/client.go
api/client_test.go
changelog/21424.txt

Add option to clone `api.Config.clientTLSConfig` when cloning either `api.Config` or `api.Client`. This feature is needed by the Terraform Vault Provider.
Additional fixes:
- handle a failed type assert in api.Config.configureTLS() (see https://github.com/hashicorp/terraform-provider-vault/issues/1916 for more details).

Add support for cloning a Client's tls.Config

---

.github/scripts/plugin-helper-gh-pr-create.sh
.github/workflows/plugin-update-check.yml

We were passing the Vault Branch when attempting to get Plugin PR number. This makes sure we pass the plugin branch name and also makes the plugin branch name an input to the Vault workflow

plugin automation: fix branch name

---

changelog/21466.txt
command/agent_generate_config.go

There is a typo in the URL provided, should be "https://developer.hashicorp.com/vault/docs/agent-and-proxy/autoauth" instead of "https://developer.hashicorp.com/vault/docs/agentandproxy/autoauth".

Fix "vault agent generate-config" documentation URL

---

website/content/docs/platform/mssql/changelog.mdx
website/content/docs/platform/mssql/troubleshooting.mdx

v0.2.1 available [here](https://releases.hashicorp.com/vault-mssql-ekm-provider/0.2.1+ent/).
BUGS
* The provider now correctly uses a previous key version for decryption when the transit key is rotated but the DEK has not yet been re-encrypted.
* Fixed a bug that prevented the provider from emitting Event logs.

Docs: Updates for vault-mssql-ekm-provider-enterprise release v0.2.1

---

.github/workflows/test-run-enos-scenario-matrix.yml

This PR adds Slack notifications for failed Enos `run`, `run_retry` and `destroy` steps so we can more easily and quickly notice and troubleshoot failures. Notifications are currently sent to the #feed-vault-enos-failures channel.

Add Slack notification for failed Enos workflow runs 

---

vault/token_store.go

The operation ID for `GET auth/token/lookup` has been overridden in
a way which *implies* it can only perform lookup-self operations.
This isn't actually the case, as shown:
1) Here is my current token:
```
$ vault read -field=display_name auth/token/lookup
userpass-admin
```
2) I create a second token, with a different display name to distinguish
it:
```
$ othertoken=$(vault token create -field=token -display-name=testing123)
```
3) I use this operation, still authenticated with the first token, to
lookup the second token, showing it is not actually a lookup-self operation:
```
$ vault read -field=display_name auth/token/lookup token=$othertoken
token-testing123
```
I have set the new operation ID suffix to `"2"` adhering to current
conventions in `vault-client-go` and …

Fix incorrect OpenAPI operation ID

---

.github/workflows/build.yml
.github/workflows/ci.yml
.github/workflows/test-go.yml

This PR adds a concurrency parameter to the build.yml and ci.yml workflows. There will only ever be one job running with the same `group` label. The group will either be the head branch, which is only present in PRs, or will be the uniquely assigned runID. That means that if it's a PR, there will only ever one of each of these workflows running for the same branch and an in-progress workflow will be cancelled in favor of a new one. For all other triggers, there will be no cancellation.

VAULT-17586: Add concurency to ci and build workflows

---

changelog/21562.txt
ui/app/components/sidebar/nav/cluster.hbs
ui/app/components/sidebar/nav/cluster.js
ui/tests/helpers/components/sidebar-nav.js
ui/tests/integration/components/sidebar/nav/cluster-test.js

A [condition was missed](https://github.com/hashicorp/vault/blob/release/1.13.x/ui/app/templates/vault/cluster.hbs#L71-L86) when moving the navigation links to the new sidebar component which prevented certain enterprise related links from showing when using Vault in a child namespace. This PR adds that condition back in for the relevant links (Disaster Recovery, Performance, Replication, Raft Storage, License, Seal Vault).

Hide Nav Links in Child Namespaces

---

.github/workflows/build.yml
.github/workflows/ci.yml
vault/request_handling.go

This uses GitHub secrets as Vault is not yet available in the `vault` repo. The `vault-enterprise` file will use the secret in Vault.
Upon a failure on `main` or a release branch, a failure notification will be sent to `#feed-vault-ci-official`. Some examples are in that channel already, although instead of saying e.g. `21561/merge` it will say the branch it was from, e.g. `main`, or `release/1.14.x` etc.
What's left is to merge this PR, do an OSS merge, then update these notifications so that they use the CI Vault for Ent and say they're an ent run etc. Note that while this will mean we do have 'drift', we have differences in these files for OSS/ent already, so this is 'expected'.

VAULT-17590 Add failure notifications for OSS builds

---

changelog/21582.txt
ui/app/styles/components/icon.scss

A display issue was discovered in Safari where on the login screen it appeared that it was not loading on smaller viewports. In reality, there was a style issue where the icon would stretch the height of the parent container and push the content down, potentially out of view. Adding an explicit height to the parent div of the icon fixes the issue. 
https://github.com/hashicorp/vault/assets/24611656/23372ea1-555a-4974-9325-d02b9b8f2c28
Resolves #21406

Login View Fix for Safari

---

builtin/logical/pki/acme_challenge_engine.go
builtin/logical/pki/acme_challenges.go
builtin/logical/pki/acme_challenges_test.go
builtin/logical/pki/dnstest/server.go
builtin/logical/pki/path_acme_test.go
builtin/logical/pki/path_config_acme.go

- The ACME tests were using ttl_duration and max_ttl_duration instead of ttl and max_ttl as input parameters to roles.
- Add missing copyright headers

Fix incorrect role ttl parameters in ACME tests

---

ui/lib/ldap/addon/components/page/overview.hbs
ui/lib/ldap/addon/routes/overview.ts
ui/lib/ldap/addon/templates/overview.hbs
ui/tests/helpers/ldap.js
ui/tests/integration/components/ldap/page/configuration-test.js
ui/tests/integration/components/ldap/page/overview-test.js

This PR adds the LDAP overview route and page component. The necessary card components will be added in a separate PR.

LDAP Overview Route and Page Component

---

.github/actionlint.yaml
.github/workflows/actionlint.yml
.github/workflows/build-vault-oss.yml
.github/workflows/build.yml
.github/workflows/changelog-checker.yml
.github/workflows/ci.yml
.github/workflows/drepecated-functions-checker.yml
.github/workflows/enos-fmt.yml
.github/workflows/enos-release-testing-oss.yml
.github/workflows/enos-run-k8s.yml
.github/workflows/godoc-test-checker.yml
.github/workflows/milestone-checker.yml
.github/workflows/nil-nil-function-checker.yml
.github/workflows/oss.yml
.github/workflows/plugin-update-check.yml
.github/workflows/security-scan.yml
.github/workflows/setup-go-cache.yml
.github/workflows/stable-website.yaml
.github/workflows/test-ci-bootstrap.yml
.github/workflows/test-ci-cleanup.yml
.github/workflows/test-enos-scenario-ui.yml
.github/workflows/test-go.yml
.github/workflows/test-run-acc-tests-for-path.yml
.github/workflows/test-run-enos-scenario-matrix.yml

Improve our build workflow execution time by using custom runners,
improved caching and conditional Web UI builds.
Runners
-------
We improve our build times[0] by using larger custom runners[1] when
building the UI and Vault.
Caching
-------
We improve Vault caching by keeping a cache for each build job. This
strategy has the following properties which should result in faster
build times when `go.sum` hasn't been changed from prior builds, or
when a pull request is retried or updated after a prior successful
build:
* Builds will restore cached Go modules and Go build cache according to
the Go version, platform, architecture, go tags, and hash of `go.sum`
that relates to each individual build workflow. This reduces the
amount of time it will take to download the cache on hits and upload …

[QT-576] Optimize build workflow

---

scripts/gen_openapi.sh

1) Reduce sleep time - in my experience, 1 second is plenty for a dev
Vault to start up its HTTP listener - having the user wait for
5 seconds seems excessive.
2) Comment reason for both sleeps.
3) Remove line of code that is obsolete, now the Enterprise transition
from stored to autoloaded licenses has completed.

Minor improvements to gen_openapi.sh

---

ui/app/components/console/ui-panel.js

In [this PR](https://github.com/hashicorp/vault/pull/21578), I missed the hardcoded route link in the console. The "api" keyword wasn't working in the console, now it is.

Fix link to API Explorer in console 

---

.github/actionlint.yaml
.github/workflows/actionlint.yml
.github/workflows/build-vault-oss.yml
.github/workflows/build.yml
.github/workflows/changelog-checker.yml
.github/workflows/ci.yml
.github/workflows/drepecated-functions-checker.yml
.github/workflows/enos-fmt.yml
.github/workflows/enos-release-testing-oss.yml
.github/workflows/enos-run-k8s.yml
.github/workflows/godoc-test-checker.yml
.github/workflows/milestone-checker.yml
.github/workflows/oss.yml
.github/workflows/security-scan.yml
.github/workflows/setup-go-cache.yml
.github/workflows/stable-website.yaml
.github/workflows/test-ci-bootstrap.yml
.github/workflows/test-ci-cleanup.yml
.github/workflows/test-enos-scenario-ui.yml
.github/workflows/test-go.yml
.github/workflows/test-run-acc-tests-for-path.yml
.github/workflows/test-run-enos-scenario-matrix.yml

Improve our build workflow execution time by using custom runners, improved caching and conditional Web UI builds.
Runners
-------
We improve our build times[0] by using larger custom runners[1] when building the UI and Vault.
Caching
-------
We improve Vault caching by keeping a cache for each build job. This strategy has the following properties which should result in faster build times when `go.sum` hasn't been changed from prior builds, or when a pull request is retried or updated after a prior successful build:
* Builds will restore cached Go modules and Go build cache according to the Go version, platform, architecture, go tags, and hash of `go.sum` that relates to each individual build workflow. This reduces the amount of time it will take to download the cache on hits and upload …

[QT-576] Optimize build workflow (#21486)

---

changelog/21215.txt
command/server.go
command/server/config.go
command/server/config_test.go
command/server/config_test_helpers.go
command/server/test-fixtures/config3.hcl
command/server/test-fixtures/config_with_valid_admin_ns.hcl
command/server/test-fixtures/config_with_valid_admin_ns.json
http/sys_config_state_test.go
internalshared/configutil/config.go
sdk/helper/testcluster/docker/environment.go
sdk/helper/testcluster/types.go
vault/core.go
vault/core_util.go
vault/logical_system_paths.go
vault/mount.go
vault/testing.go

Full functionality only works in enterprise. This adds the core implementation pieces needed.

Introduce high privilege namespace (administrative namespace)

---

.github/workflows/build.yml
.github/workflows/ci.yml
vault/request_handling.go

I thought this approach, of making two jobs, one running on OSS, one on Ent, was probably best, since we can keep both in the OSS repo and avoid merge conflicts if we need to change them.
Sorry about the commit history, I accidentally included the commits from the old PR. Should be good, though, and naturally, will be squashed.

VAULT-17590 Enterprise-side changes (using CI Vault over GH Secret)

---

vault/test_stubmaker.go
vault/test_stubmaker_oss.go

This change will be reverted, but first I want to commit and merge it to ent, to validate that stubmaker will prevent the build from breaking as a result.  I've done lots of other testing, but now I want to test the real thing.  cf https://github.com/hashicorp/vault/pull/21564

Test: add code that would break ent if merged prior to stubmaker

---

changelog/21633.txt
go.mod
go.sum

This PR upgrades vault-plugin-secrets-azure to [v0.14.2](https://github.com/hashicorp/vault-plugin-secrets-azure/releases/tag/v0.14.2) to bring in a bug fix from https://github.com/hashicorp/vault-plugin-secrets-azure/pull/150.

secrets/azure: upgrade to v0.14.2 for bug fix

---

changelog/21632.txt
go.mod
go.sum

This PR upgrades vault-plugin-secrets-azure to [v0.15.1](https://github.com/hashicorp/vault-plugin-secrets-azure/releases/tag/v0.15.1) to bring in a bug fix from https://github.com/hashicorp/vault-plugin-secrets-azure/pull/150.

secrets/azure: upgrade to v0.15.1 for bug fix

---

changelog/21631.txt
go.mod
go.sum

This PR upgrades vault-plugin-secrets-azure to [v0.16.1](https://github.com/hashicorp/vault-plugin-secrets-azure/releases/tag/v0.16.1) to bring in a bug fix from https://github.com/hashicorp/vault-plugin-secrets-azure/pull/150.

secrets/azure: upgrade to v0.16.1 for bug fix

---

builtin/logical/pki/backend.go
builtin/logical/pki/backend_oss.go

Allow Vault enterprise to tweak the PKI backend attributes during mount creation

Add the ability for enterprise to override PKI backend attributes during setup

---

.github/scripts/plugin-helper-gh-pr-create.sh
.github/workflows/plugin-update-check.yml

Use the plugin branch name as the ref for `go get` so that we can make this callable as a standalone job outsite of auto dep update PRs.

workflows: update plugin check job to use branch as ref

---

.github/workflows/test-go.yml

This PR will cause the test artifacts (the XML and JSON reports generated by `gotestsum`) to be uploaded to a single Artifact/zip-file per test type (normal, race, fips) to make the CI workflow run summary page nicer to navigate and less noisy. This will come particularly in handy once we implement VAULT-17592 and get a nice test summary going.
Here are some visuals. We're going from this:
to this:
Don't worry, all of the results are still in the archive, they are just in separate files in a single archive per test type.

Group CI artifacts per test type to reduce noise on GHA run summary page

---

.github/workflows/add-hashicorp-contributed-label.yml

This is the inverse of https://github.com/hashicorp/vault/pull/21600, and was done for reasons explained in the comments of this GHA (forks can't have write permissions). We should be able to find community contributed PRs by adding `-label:hashicorp-contributed-pr` to the search bar.
See also (specifically, the maximum access for forks column is _all_ `read`):
I'll have to manually go back and update all open PRs with this label, where appropriate, but this one-time cost seems better than the alternate solution of having a cron job have to re-process every PR every time it runs. I'll make sure everything has the correct label.

VAULT-17736 Add HashiCorp contributed label to HC contributed PRs

---

changelog/21640.txt
vault/router.go

- There is a data race updating a route entry's tainted status and loading the current status with new incoming requests. 
Exposed by an enterprise unit test.

Fix data race between updating a route entry's tainted status and incoming requests - OSS

---

changelog/21628.txt
helper/experiments/experiments.go
vault/audit.go
vault/audit_broker.go
vault/audit_test.go

This PR introduces an experiment that will allow the incremental addition of eventlogger-based implementation changes without impacting the code base until the legacy backend implementations can be completely removed to complete the migration.

Introduce Experiment to Toggle Between Legacy Auditing Backends/EventLogger

---

changelog/21215.txt
command/server.go
command/server/config.go
command/server/config_test.go
command/server/config_test_helpers.go
command/server/test-fixtures/config3.hcl
command/server/test-fixtures/config_with_valid_admin_ns.hcl
command/server/test-fixtures/config_with_valid_admin_ns.json
http/sys_config_state_test.go
internalshared/configutil/config.go
vault/core.go
vault/core_util.go
vault/logical_system_paths.go
vault/mount.go
vault/testing.go

Manual backport PR due to conflict in the auto-generated one: https://github.com/hashicorp/vault/pull/21608
---
Full functionality only works in enterprise. This adds the core implementation pieces needed.
---
<details>
<summary> Overview of commits </summary>
- 4c1a7b53d362ee733707de2fa3280596e35d7f03 
</details>

Backport 1.13: Add high privilege namespace (#21215)

---

.github/workflows/add-hashicorp-contributed-label.yml

We don't want backports etc showing up :)

Run HashiCorp contributed labeler on every branch

---

builtin/logical/pki/dnstest/server.go

- We've seen a few issues with bind's auto-loading of configuration too quickly at bad times leading to it having partial configurations or not all files/permissions being restored properly during it's read attempt.
- See if the freeze/thaw rndc commands will help out with these timing issues

Attempt to address autoloading issues within Bind backend tests

---

builtin/logical/pki/path_tidy_test.go

- There's a race within the Plugin reloading mechanism that isn't trivial to address. To silence some of the failures, switch this test to use sealing of the cores instead of the plugin reload mechanism

Address data race warnings in TestCertStorageMetrics due to plugin reloading

---

.hooks/pre-commit
Makefile
builtin/logical/pki/path_acme_test.go
scripts/gofmtcheck.sh

This adds/updates the pre-commit hook to add a backend format checking prior to commit, similar to the existing UI check.
This should reduce the number of PR authors (mostly, myself) who commit things without checking that `fmt` CI has passed... :-)

pre-commit hook for formatting backend code

---

ui/app/adapters/kv/metadata.js
ui/app/serializers/kv/metadata.js
ui/lib/core/addon/components/page/breadcrumbs.hbs
ui/lib/kv/addon/components/kv-page-header.hbs
ui/lib/kv/addon/components/page/configuration.hbs
ui/lib/kv/addon/components/page/secret/details.hbs
ui/lib/kv/addon/components/page/secret/edit.hbs
ui/lib/kv/addon/components/page/secret/metadata-details.hbs
ui/lib/kv/addon/components/page/secret/metadata-edit.hbs
ui/lib/kv/addon/components/page/secrets.hbs
ui/lib/kv/addon/components/page/secrets/create.hbs
ui/lib/kv/addon/routes.js
ui/lib/kv/addon/routes/configuration.js
ui/lib/kv/addon/routes/secrets/create.js
ui/lib/kv/addon/routes/secrets/index.js
ui/lib/kv/addon/routes/secrets/secret/details.js
ui/lib/kv/addon/routes/secrets/secret/edit.js
ui/lib/kv/addon/routes/secrets/secret/metadata/details.js
ui/lib/kv/addon/routes/secrets/secret/metadata/edit.js
ui/lib/kv/addon/routes/secrets/secret/metadata/index.js
ui/lib/kv/addon/templates/configuration.hbs
ui/lib/kv/addon/templates/secrets/create.hbs
ui/lib/kv/addon/templates/secrets/index.hbs
ui/lib/kv/addon/templates/secrets/secret/details.hbs
ui/lib/kv/addon/templates/secrets/secret/edit.hbs
ui/lib/kv/addon/templates/secrets/secret/metadata/details.hbs
ui/lib/kv/addon/templates/secrets/secret/metadata/edit.hbs
ui/lib/kv/addon/templates/secrets/secret/metadata/index.hbs
ui/tests/integration/components/kv-page-header-test.js

**Note:** I have not tackled permissions here. For my brain to handle that, I need to have the models setup for each route so I can access the permission capabilities. I have added the permissions tasks as acceptance criteria on relevant tickets.
This PR creates the `KvPageHeader` component and adds it to the following views. The component is responsible for breadcrumbs, title, icon, version-tag, tabs, and toolbar actions/filters.
1. Secrets LIST view.
2. Configuration view. No toolbar in this view.
3. Create secret view. A toolbar will be added, once I handle the JSON functionality.
4. Secret Create new version/edit view. Toolbar actions in another PR.
5. Secret Details view
6. Secret Metadata Details/index view.
7. Secret Metadata Edit view.
**One last note:**
In another PR I'll address …

KvPageHeader component

---

.github/workflows/actionlint.yml
.github/workflows/milestone-checker.yml

The milestone checker will now be re-evaluated if the `pr/no-milestone` label is added or if a milestone is added to the PR. Github documentation doesn't list `milestoned` and `demilestoned` as valid, but they are working. Actionlint also isn't aware of them, so I added ignores for those particular checks to the actionlint action.

VAULT-15958: Fix pr/no-milestone 

---

builtin/logical/pki/backend.go
builtin/logical/pki/backend_oss.go

To allow us to support CIEPS backend state, allow the backend to contain enterprise only state variables. Also allow us to implement enterprise only hooks into the various backend functions to initialize, periodicFunc, cleanup and invalidate.

Add the ability to add enterprise only backend features in PKI - OSS

---

.hooks/pre-commit
scripts/gofmtcheck.sh

The pre-commit hook was taking quite a while to run. Let's just check changed files to avoid unnecessary `go fmt` on the entire tree.

Only run fmtcheck on changed files pre-commit

---

changelog/21739.txt
ui/app/serializers/application.js

This PR fixes an issue on the UI where editing an SSH role with `default_extension` set causes the `default_extension` to be cleared on edit (#21571)
I spot-checked all the other places where we use `attr('object')` and they seem to work (create, update) fine. Usually on update forms we use `POST` with the entire payload, so I'm not sure why this was the default behavior but if we find instances that this needs to be the case we can override those specific serializers.

UI: Remove logic that skips sending object if not changed

---

builtin/logical/pki/backend_oss_test.go
builtin/logical/pki/backend_test.go

- Allow enterprise repository to hook into and influence the proper authing test so we don't have to add values to OSS for enterprise work

Allow PKI enterprise to influence TestProperAuthing test case

---

.github/workflows/test-go.yml

These tests shouldn't be run as part of normal tests, just as part of the nightly enterprise tests.

Exclude vault/integ from normal go tests

---

builtin/logical/pki/path_tidy_test.go

- Add a little more debug to try and understand how we could get the following error I saw within GHA
```
path_tidy_test.go:769: Created root and leaf certificate, deleted leaf, but a got a certificate count of 2
```
- Fix some other issues discovered while running the test through stress locally

Add additional debug output to TestCertStorageMetrics

---

website/content/api-docs/system/storage/raft.mdx
website/content/api-docs/system/storage/raftautosnapshots.mdx

The header for the raft and raft/snapshot-auto API docs don't match the format conventions for other pages:
https://developer.hashicorp.com/vault/api-docs/system/storage/raft
https://developer.hashicorp.com/vault/api-docs/system/storage/raftautosnapshots
Expected:
Actual (to-be-fixed)

fix sys/raft doc headings

---

changelog/21800.txt
go.mod
go.sum

This PR upgrades vault-plugin-auth-azure to [v0.15.1](https://github.com/hashicorp/vault-plugin-auth-azure/releases/tag/v0.15.1) to bring in a bug fix from https://github.com/hashicorp/vault-plugin-auth-azure/pull/118.

auth/azure: upgrade to v0.15.1 for bug fix

---

.github/workflows/test-go.yml

Change github.base_ref to github.ref_name as re-run fails flag should be added when the workflow is triggered on release branches.

Change github.base_ref to github.ref_name for Vault-17777

---

website/content/docs/audit/file.mdx

Docs PR to update the text associated with the `discard` setting for a audit file device.
See: https://vault-3zuxpmrs1-hashicorp.vercel.app/vault/docs/audit/file#discard

Docs: audit file setting 'discard' description update

---

changelog/21642.txt
vault/ha.go

This bug only ever occurs on enterprise, as we only ever call `sealInternalWithOptions` with `keepHALock` as `true` in enterprise, and so `keepHALockOnStepDown` is always 0 in OSS. When we step down as a leader but keep the HA lock, we should still unlabel ourselves as leader in k8s, but that happens in `clearLeader`, so before this fix if we keep the HA lock we'll never unlabel ourselves. Essentially, this change ensures we more closely track the core's `standby` state variable in that case.
I'm not sure about automated testing yet. I've been using the following script for reproducing the issue locally.
<details><summary>Repro script</summary>
<p>
```bash
#!/usr/bin/env bash
#
#
#
WAL_ITERATIONS=50 
TXTBLU="$(tput setaf 4)"
TXTCYA="$(tput setaf 6)"
TXTGRN="$(tput setaf 2)"
TXTMGT="$(tput …
```

Fix k8s service registration case where Vault fails to unlabel itself as a leader

---

builtin/logical/pki/acme_wrappers.go
builtin/logical/pki/path_acme_order.go
builtin/logical/pki/path_acme_test.go
builtin/logical/pki/path_config_acme.go
changelog/21702.txt
ui/app/models/pki/config/acme.js
website/content/api-docs/secret/pki.mdx

As discussed in #21549, there is some use cases where allowing expanding ExtKeyUsage is adequate (eg containers).  
This PR adds a new configuration option on ACME to allow usage of the ExtKeyUsage field defined within a role.

Add a parameter to allow ExtKeyUsage field usage from a role

---

.github/workflows/test-go.yml

- Fix the permissions issue we see in the enterprise repo.
- Make `Fetch job logs URL` fail without spamming the workflow run summary annotations.
- Fix the issues with the API call (missing results due to pagination).

Go test failure summaries fixes and improvements

---

vault/testing.go

I missed this small testing update required for the enterprise repo's test of #21642.

Use config's service registration in test cluster

---

vault/testing.go

Backports #21907, to enable a test in the enterprise repo. Manually resolves the conflicts that happened in #21908
Closes #21911

Use config's service registration in test cluster (#21907)

---

changelog/21951.txt
go.mod
go.sum

This updates go-secure-stdlib's awsutil to bring in a change (https://github.com/hashicorp/go-secure-stdlib/pull/80) to fix a regression where Vault no longer respects AWS_ROLE_ARN, AWS_WEB_IDENTITY_TOKEN_FILE, and AWS_ROLE_SESSION_NAME.
Closes https://github.com/hashicorp/vault/issues/21465 https://github.com/hashicorp/vault/issues/21478
Steps:
```
go get github.com/hashicorp/go-secure-stdlib/awsutil@v0.2.3
go mod tidy
```

awsutil: update to v0.2.3

---

website/content/docs/agent-and-proxy/agent/apiproxy.mdx
website/content/docs/agent-and-proxy/agent/index.mdx

[:mag: Preview Link for Agent page](https://vault-git-nq-fix-autoauth-docs-links-hashicorp.vercel.app/vault/docs/agent-and-proxy/agent)
[:mag: Preview Link for API proxy page](https://vault-git-nq-fix-autoauth-docs-links-hashicorp.vercel.app/vault/docs/agent-and-proxy/agent/apiproxy)
---
This PR removes `agent` from links to the Auto-Auth docs page, fixing the links.
1. Click each of the preview links above.
2. Press `Ctrl+F` and search for "Auto-Auth" to find the relevant links. 
3. Click these links. They should successfully navigate you to [the Auto-Auth page](https://vault-git-nq-fix-autoauth-docs-links-hashicorp.vercel.app/vault/docs/agent-and-proxy/autoauth).

fix: Broken docs links for Auto-Auth page

---

ui/lib/core/addon/templates/components/confirm.hbs

Adds sanitization to computed style on confirm dropdown, which should fix the confirm dropdown not rendering correctly on HSM builds:

UI: Fix confirm dropdown not rendering on HSM

---

.github/actions/set-up-gotestsum/action.yml
.github/workflows/build.yml
.github/workflows/ci.yml
.github/workflows/security-scan.yml
.github/workflows/test-enos-scenario-ui.yml
.github/workflows/test-go.yml

We further optimize the CI workflow for better costs and speed. We tested the Go CI workflows across several instance classes and update our compute choices. We achieve an average execution speed improvement of 2-2.5 minutes per test workflow while reducing the infrastructure cost by about 20%. We also also save another ~2 minutes by installing `gotestsum` from the Github release instead of downloading the Go modules and compiling it every time.
In addition to the speed improvements, we also further reduced our cache usage by updating the `security-scan` workflow to not cache Go modules. We also use the `cache/save` and `cache/restore` actions for timing caches. This results is saving half as many cache results for timing data.
results for 2x runs:
* c6a.2xlarge (12m54s, 11m55s)
* …

[QT-590] Optimize the CI testing workflow

---

builtin/logical/pki/path_tidy_test.go

This fix seems to have been missed on the 1.13.x branch, as these are the values used on [1.12.x](https://github.com/hashicorp/vault/blob/release/1.12.x/builtin/logical/pki/path_tidy_test.go#L256-L257), [1.14.x](https://github.com/hashicorp/vault/blob/release/1.14.x/builtin/logical/pki/path_tidy_test.go#L584-L585)

Address memory consumption from TestCertStorageMetrics

---

.github/actions/set-up-go/action.yml
.github/workflows/test-go.yml

* restore old timing results before saving new cache
* don't do an unecessary checkout in set-up-go

ci: restore old timing before saving new cache

---

builtin/credential/approle/path_role.go
builtin/logical/aws/path_user.go
sdk/framework/backend.go
vault/identity_store_oidc_provider.go
vault/logical_system_paths.go
vault/token_store.go

Also improve the documentation comment for `Query` to guide people better how they should be setting `Query` in the future.
Endpoints affected:
- auth/approle/role/{role_name}/secret-id/destroy
- auth/approle/role/{role_name}/secret-id-accessor/destroy
- auth/token/lookup
- auth/token/lookup-self
- sys/internal/specs/openapi
- sys/wrapping/lookup
- identity/oidc/provider/{name}/authorize
- aws/creds/{name}
- aws/sts/{name}
There are also endpoints in the `gcp` secrets engine which need the same treatment in its own PR.
When working on the `auth/token/lookup-self` path, I discovered that it
had a parameter which was completely pointless - it was even documented
as unused. It only existed because the `auth/token/lookup-self` code
path was implemented by bodging the current token into the …

Add missing `Query: true` metadata to API definitions

---

website/content/docs/secrets/azure.mdx

This PR updates the Azure secrets permissions recommendations (again 😄) to:
- Add a note that `Application.ReadWrite.All` is needed for rotate root
- Scope down the role assignment from `Owner` to `User Access Administrator`
Related PR:
- https://github.com/hashicorp/vault-plugin-secrets-azure/pull/158

secrets/azure: adds permissions note on rotate root and change role assignment

---

helper/testhelpers/corehelpers/corehelpers.go
helper/testhelpers/minimal/minimal.go
vault/testing.go

This should get us closer to avoiding all the log noise that occurs in tests after Cleanup.

Make TestLogger an InterceptLogger and use it a little more widely

---

vault/logical_system.go
vault/logical_system_sync_secrets_stub.go

Added secrets sync backend stub. Used so Vault ENT can use the real implementation of the sync backend while makign it clear this is not a dependency that should be used or modified here.

Added secrets sync backend stub

---

ui/app/adapters/kv/data.js
ui/app/models/kv/data.js
ui/app/serializers/kv/data.js
ui/lib/kv/addon/components/page/secret/details.hbs
ui/lib/kv/addon/components/page/secret/details.js
ui/lib/kv/addon/routes/secret.js
ui/lib/kv/addon/templates/secret/details.hbs
ui/tests/acceptance/secrets/backend/kv/kv-engine-permissions-test.js
ui/tests/helpers/kv/kv-general-selectors.js
ui/tests/helpers/kv/kv-run-commands.js
ui/tests/helpers/policy-generator/kv.js
ui/tests/integration/components/kv/page/kv-page-secret-details-test.js

- Hides tabs if no metadata access
- Shows empty state if no read permission
<hr>
- shows empty state if version is deleted
<hr>
- and if destroyed

UI: KV secret details empty states and permissions

---

sdk/framework/openapi.go
vault/logical_cubbyhole.go

Update the OpenAPI generation code to render TakesArbitraryInput
appropriately.
Mark the cubbyhole write operation as TakesArbitraryInput.
Contributes to fixing
https://github.com/hashicorp/vault-client-go/issues/201.
We will also need
https://github.com/hashicorp/vault-plugin-secrets-kv/pull/114 merged and
a new version of that plugin brought into Vault.

TakesArbitraryInput fixes

---

vault/token_store.go

This is a follow-up to #21772.
Historically, for some reason, `auth/token/revoke-orphan` was
sudo-protected by writing custom code in its handler function, instead
of via the usual declarative PathsSpecial.Root mechanism.
In fact, there was a declaration mentioning revoke-orphan in the token
backend's PathsSpecial.Root, but it was incorrect! That was corrected
in #21772, making the custom code in the handler function redundant.
However, removal of the now-redundant code was deferred to this
follow-up PR, out of an abundance of caution, and wanting extra eyes on
a change deleting a security check.

Remove redundant sudo check

---

changelog/21942.txt
sdk/framework/openapi.go
sdk/framework/openapi_test.go

Currently, the OpenAPI generator logic is wrong about how it maps from
Vault framework fields to OpenAPI. This manifests most obviously with
endpoints making use of `framework.OptionalParamRegex` or similar
regex-level optional path parameters, and results in various incorrect
fields showing up in the generated request structures.
The fix is a bit complicated, but in essence is just rewriting the
OpenAPI logic to properly parallel the real request processing logic.
With these changes:
* A path parameter in an optional part of the regex, no longer gets
erroneously treated as a body parameter when creating OpenAPI
endpoints that do not include the optional parameter.
* A field marked as `Query: true` no longer gets incorrectly skipped
when creating OpenAPI `POST` operations.

OpenAPI: Fix generation of correct fields

---

sdk/framework/openapi.go

In my recent #21942, I overlooked the need to sort another part of the
OpenAPI document to ensure stable output.
I've also removed `strings.ToLower()` from the code I copied from, as
this code is sorting Vault API parameter names, which are all lowercase
anyway!

OpenAPI: Sort parameters for stable output

---

builtin/logical/pki/acme_challenges_test.go
builtin/logical/pki/dnstest/server.go

- Avoid issues with t.Logf data races if a log message is called post test completion from a background go routine.
Sample data race seen in CI
```
Read at 0x00c00054bd83 by goroutine 148:
testing.(*common).logDepth()
/opt/hostedtoolcache/go/1.20.5/x64/src/testing/testing.go:992 +0xc4
testing.(*common).log()
/opt/hostedtoolcache/go/1.20.5/x64/src/testing/testing.go:985 +0xa4
testing.(*common).Logf()
/opt/hostedtoolcache/go/1.20.5/x64/src/testing/testing.go:1036 +0x6a
github.com/hashicorp/vault/builtin/logical/pki.TestAcmeValidateTLSALPN01Challenge.func3()
/home/runner/work/vault/vault/builtin/logical/pki/acme_challenges_test.go:287 +0x444
Previous write at 0x00c00054bd83 by goroutine 30:
testing.tRunner.func1() …
```

Use hclog instead of t.Logf within PKI ACME test suite

---

builtin/logical/pki/cert_util.go
builtin/logical/pki/path_issue_sign.go

- Extract out the sign/issue certificate (non-CA) response into a function that can be used by the CIEPS sign/issue API handlers.

Refactor sign/issue response logic to be usable by CIEPS codebase

---

vault/logical_system_helpers.go

As discussed in https://github.com/hashicorp/vault-client-go/issues/208

Add a distinguishing prefix to OpenAPI operation IDs for enterprise stubs

---

tools/stubmaker/main.go

This fixes a dropped `err` variable in `tools/stubmaker`.

tools/stubmaker: fix dropped error

---

builtin/credential/aws/path_config_client.go
builtin/credential/aws/path_login.go
builtin/credential/aws/path_login_test.go
changelog/21960.txt
website/content/api-docs/auth/aws.mdx

Adds support to the AWS auth plugin so that when the `use_sts_region_from_client` configuration is set, the global STS endpoint (https://sts.amazonaws.com) will be overridden to instead use the [regional STS endpoints](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html) based on the region provided in the `Authorization` header.
This change allows for DR situations and AWS regional outages by supporting flexibility in where the login region is calling from.
Without this change, clients would run into an error message when logging in if there were a region mismatch between client and server:
```
Error authenticating: Error making API request.
URL: PUT http://127.0.0.1:8200/v1/auth/aws/login
Code: 400. Errors:
* error making upstream request: received …
```

AWS auth login with multi region STS support

---

audit/entry_formatter.go
audit/entry_formatter_test.go
audit/entry_formatter_writer.go
audit/entry_formatter_writer_test.go
audit/options.go
audit/types.go
audit/writer_json_test.go
audit/writer_jsonx_test.go
builtin/audit/file/backend.go
builtin/audit/socket/backend.go
builtin/audit/syslog/backend.go
helper/testhelpers/corehelpers/corehelpers.go

A bit of clean up as the parameter isn't always required, so moving to an option (reduces `nil` in a lot of tests)

Moved HeaderFormatter to an Option for NewEntryFormatter, updated tests

---

vault/external_tests/api/kv_helpers_test.go

This test, trying to test KV v2 behaviour, should be sending its
requests to a KV v2! Not the KV v1!

Fix bad test

---

changelog/22039.txt
ui/app/templates/components/secret-form-show.hbs
ui/lib/core/addon/components/masked-input.hbs
ui/tests/integration/components/masked-input-test.js
ui/tests/pages/components/masked-input.js

1. This PR changes what the `<MaskedInput>` component shows when it has no value
- Before: it showed just a blank space when the "show value" button is pressed. 
- After: it shows a minus icon (`<Icon @name="minus" />`) so that it is more clear to users that there is simply no value there
- When downloaded, the content is an empty string
- When copied, a blank space is copied and a copy success alert shows
2. This PR changes what the KV secrets page shows when there secrets with no value
- Reproduction Steps: enable KV engine > create a path > create a secret in that path with only a key, no value > view the path so you can see the key/value pairs
- Before: secrets with only a key and no value showed the minus icon for the value. 
- After: a key with no value shows the …

UI: Display minus icon for empty MaskedInput value. Show MaskedInput for KV secrets without values

---

ui/app/adapters/ldap/role.js
ui/app/models/ldap/config.js
ui/lib/core/addon/components/filter-input.hbs
ui/lib/core/addon/components/filter-input.ts
ui/lib/core/app/components/filter-input.js
ui/lib/ldap/addon/components/page/roles.hbs
ui/lib/ldap/addon/components/page/roles.ts
ui/lib/ldap/addon/routes/error.ts
ui/lib/ldap/addon/routes/roles/index.ts
ui/lib/ldap/addon/routes/roles/role.ts
ui/lib/ldap/addon/templates/error.hbs
ui/lib/ldap/addon/templates/roles/index.hbs
ui/tests/integration/components/filter-input-test.js
ui/tests/integration/components/ldap/page/roles-test.js
ui/tests/unit/adapters/ldap/role-test.js
ui/types/vault/app-types.ts

This PR adds a route for ldap roles as well as a page component and an error route for the ldap engine. Additional error handling was added in the adapter since roles are fetched from different endpoints depending on type (static or dynamic). The partial error info (when only one request fails) can be conditionally enabled through the adapter options. Since the roles card component on the overview route only shows the total number of roles created it was deemed by design that surfacing the partial error is less helpful in that scenario.  
_error handling when request to one of the roles endpoint fails_
_error handling when both requests fail_

LDAP Roles

---

builtin/logical/pkiext/pkiext_binary/acme_test.go
helper/testhelpers/consul/consulhelper.go

We should be pulling docker images through the Hashicorp Docker proxy and not directly from docker hub.

Use Hashicorp docker proxy for CI docker images

---

go.mod
go.sum

Update `go-eventlogger` to bring in fixes for pipeline registration policy.

Bump go-eventlogger to v0.2.2

---

enos/enos-scenario-replication.hcl
enos/enos-scenario-smoke.hcl
enos/enos-scenario-ui.hcl
enos/enos-scenario-upgrade.hcl
enos/enos-variables.hcl
enos/modules/backend_raft/main.tf
enos/modules/vault_cluster/main.tf

Previously we were not able to test Vault with enterprise edition Consul. We added support for this in the vault-cluster module, and now needed to actually begin passing the Consul license in the scenarios that use a Consul backend.

Pass consul license in Enos scenarios that have `backend` in the matrix

---

ui/app/utils/validators.js
ui/tests/unit/utils/validators-test.js

PR adds validator to model validation helpers to return `isValid = false` if a string ends in a forward slash

ui: add validator to check if string ends in slash

---

website/content/api-docs/auth/ldap.mdx
website/content/docs/auth/ldap.mdx

Provides clarification in the ldap auth docs for `userfilter`. We've had multiple users report that the `userfilter` isn't being applied, or seems to be getting skipped.
Addresses https://github.com/hashicorp/vault/issues/17898.

clarify docs in ldap/auth for userfilter

---

sdk/helper/certutil/cieps.go

Update CIEPS model to use strings instead of the typed integers.

Send leaf_not_after_behavior as string not an integer - OSS

---

website/content/docs/enterprise/sentinel/index.mdx

Forgot to add the link to the **Policy override** section to explain how soft-mandatory works. 
This PR simply adds the link to the `override` text in the table.

Add an anchor link to policy override section

---

builtin/logical/pki/cert_util.go

- Allow us to call and apply an issuer's leaf_not_after_behavior to a leaf certificate from various locations.

Refactor logic on applying leaf_not_after_behavior

---

changelog/22235.txt
vault/external_tests/router/router_ext_test.go
vault/mount.go
vault/router_testing.go

During reload and mount move operations, we want to ensure that errors created by the final Rollback are not fatal (which risk failing replication in Enterprise when the core/mounts table gets invalidated). This mirrors the behavior of the periodic rollback manager, which only logs the error.
This updates the noop backend to allow failing just rollback operations, which we can use in tests to verify this behavior and ensure the core operations (plugin reload, plugin move, and seal/unseal) are not broken by this. Note that most of these operations were asynchronous from the client's PoV and thus did not fail anyways prior to this change.
reg: VAULT-18857

Ignore errors from rollback manager invocations

---

website/content/api-docs/secret/databases/index.mdx

Backporting to 1.14.x so this change will be available on the website immediately

docs/db: fix outdated static role information

---

changelog/22191.txt
ui/app/models/pki/certificate/generate.js
ui/app/models/pki/role.js

Add `allowed_user_ids` under the **Additional subject fields** section of Create Role in PKI
Add `user_ids` under the **Common name** field in Generate Credentials in PKI
Confirmed with crypto (Alex + Steve) that it makes sense to place the fields in these sections/areas^

UI: Add missing allowed_user_ids to role form in PKI

---

ui/lib/core/addon/components/form-field.hbs

Before fix:
The only way to change the default value was by `cmd + A` and selecting all using the keyboard. Clicking the backspace button reset the input to the default value. In the gif below I'm clicking `backspace` to no avail
After fix 🔧

ui: remove `on input` event from `<input>` in `<FormField>` component

---

changelog/22249.txt
sdk/helper/ldaputil/client.go
sdk/helper/ldaputil/client_test.go

Applies changes to the LDAP client from https://github.com/hashicorp/cap/pull/77 and https://github.com/hashicorp/cap/pull/78.
This is a temporary solution until cap/ldap has support for pagination.
For the longer term solution, see https://github.com/hashicorp/vault/pull/22185.

Address LDAP issues

---

builtin/logical/database/rotation.go
changelog/22253.txt

This PR improves the error logs that can result from failed database static role rotations by including the role and database names. This will help Vault operators know where to start troubleshooting when these logs appear.
Fixes: https://github.com/hashicorp/vault/issues/21433

secrets/db: improves error logs for static role rotation

---

website/content/api-docs/secret/pki.mdx

This does not doc configuration currently, but docs new issuance APIs.

Add API docs on CIEPS issuance

---

website/content/api-docs/secret/pki.mdx

This adds a missing commit from #22098 (oops), plus API docs on the configuration of CIEPS and a bunch of EnterpriseAlert references now.

Docs CIEPS Configuration

---

changelog/22233.txt
website/content/docs/secrets/identity/index.mdx

I think it is a good idea to clarify that the entity is only created if the authentication is successful.

clarify when a entity is created

---

audit/nodes.go
audit/nodes_test.go
builtin/audit/file/backend.go
builtin/audit/socket/backend.go
builtin/audit/syslog/backend.go

This PR brings parity for logging a test probe message (unless `skip_test` option is supplied) when enabling an audit device.

VAULT-18157: Audit events:  Log Test Message

---

command/healthcheck/pki_enable_acme_issuance.go

This fixes a dropped `err` variable in `command/healthcheck`.

command/healthcheck: fix dropped error

---

audit/event.go
audit/sink_wrapper.go
audit/types.go
builtin/audit/file/backend.go
builtin/audit/socket/backend.go
builtin/audit/syslog/backend.go
vault/audit.go

This PR records the amount of time spent processing an event in each pipeline by creating a wrapper for Sink Nodes that adds a deferred function that records the elapsed time since the Event's creation time (when the Event's payload was passed to the `(*eventlogger.Broker) Send(context.Context, eventlogger.EventType, interface{})` method) in the `Process(context.Context, *eventlogger.Event) (*eventlogger.Event, error)` method and calls the underlying Sink node's Process method.

VAULT-18934: Record individual metrics for each Auditing Event Pipeline

---

builtin/logical/pki/path_root.go
builtin/logical/pki/path_sign_issuers.go
sdk/helper/certutil/cieps.go

- Allow the sign-intermediate response handling code to be shared across different API calls.

Refactor sign-intermediate API response

---

website/content/docs/platform/mssql/changelog.mdx

BUGS
* Fixed a bug that stopped the provider from successfully negotiating a TLS handshake directly with a Vault server in some configurations.

Docs: Changelog for MSSQL EKM Provider v0.2.2

---

plugins/database/mssql/mssql_test.go

I don't know if this will make the test less flaky or not, but we're seeing a lot of timeouts, and I know the container is quite heavyweight.  If nothing else this will make CI cheaper.

Share the same mssql container across all four subtests.

---

website/content/docs/audit/socket.mdx

Socket audit device has a configurable setting that doesn't appear in our documentation: `write_timeout`.
This PR updates the docs to reflect the availability of the option (and backports to older versions).

documenting missing option

---

website/content/api-docs/system/quotas-config.mdx

Fixes https://github.com/hashicorp/vault/issues/21904
We have poor documentation around the `enable_rate_limit_response_headers` feature today, where we don't describe what the headers are that are being enabled. I've added documentation describing these headers and what they mean.
https://vault-73hnne0n9-hashicorp.vercel.app/vault/api-docs/system/quotas-config
Updated looks like this:

Improve docs around enable_rate_limit_response_headers

---

sdk/helper/certutil/cieps.go

- Remove the omitempty flag from issuer_ref, and add it to the warnings and error fields

Adjust the omitempty json flags within CIEPSResponse

---

ui/app/models/kv/data.js
ui/lib/kv/addon/components/kv-tooltip-timestamp.hbs
ui/lib/kv/addon/components/page/secret/details.hbs
ui/lib/kv/addon/components/page/secret/details.js
ui/lib/kv/addon/components/page/secret/metadata/details.hbs
ui/lib/kv/addon/components/page/secret/metadata/version-history.hbs
ui/tests/acceptance/secrets/backend/kv/kv-create-new-version-test.js
ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-navigation-test.js
ui/tests/helpers/kv/kv-selectors.js
ui/tests/integration/components/kv/page/kv-page-secret-details-test.js

1. adds `deletion_time` to secret details
2. hides version history tab if no metadata read access
Note: in the gif below I change the version view by updatibg the URL - but we don't give users the ability to navigate to different versions in the UI without metadata `READ` access
<hr>
```
path "my-kv/metadata/*" {
capabilities = ["list"]
}
path "my-kv/data/*" {
capabilities = ["list", "create", "read", "update"]
}
```

UI: add deletion_time to details

---

builtin/logical/database/backend.go
builtin/logical/database/path_roles.go
builtin/logical/database/path_roles_test.go
builtin/logical/database/rotation.go

This PR adds the `rotation_window` field to the Create/Update static role endpoint.

adv ttl mgmt: add rotation_window field

---

changelog/21641.txt
command/agentproxyshared/auth/ldap/ldap.go
command/agentproxyshared/auth/ldap/ldap_test.go
command/agentproxyshared/helpers.go
website/content/docs/agent-and-proxy/autoauth/methods/ldap.mdx
website/data/docs-nav-data.json

This PR adds support for "ldap" authentication in Vault agent.
This feature comes in handy in situations where entities in ldap are used as a service accounts.

Support ldap authentication in vault agent

---

audit/entry_formatter.go
audit/nodes.go
audit/nodes_test.go
audit/types.go

This PR fixes an issue discovered while testing the disabling and enabling Audit Devices when the experimental framework is used. The issue prevented the enabling of an Audit Device because during its creation and mounting, its Event Pipeline nodes that make use of the Audit Device's Salt method was being used (For instance, https://github.com/hashicorp/vault/blob/main/audit/entry_formatter.go#L181). This triggered a salt value to be generated and it be written to Storage, but during the enabling and mounting of Audit Devices, the Storage view is placed in _read-only_ mode which prevents data from being written to it.
However, the current framework doesn't suffer from this issue because it generates a different Formatter that uses a different Salt configuration that's not persisted in …

Use non-persistent Salter for logging test message

---

changelog/22330.txt
go.mod
go.sum

Fix ldap secrets engine bug causing schema and password_policy to be overwritten in config.  Bump version to v0.11.1

secrets/ldap: upgrade to v0.11.1 for bug fix

---

changelog/22332.txt
go.mod
go.sum

Fix ldap secrets engine bug causing schema and password_policy to be overwritten in config. Bump version to v0.9.2

secrets/ldap: upgrade to v0.9.2 for bug fix

---

ui/app/adapters/ldap/library.js
ui/app/styles/components/overview-card.scss
ui/app/styles/helper-classes/colors.scss
ui/app/styles/helper-classes/flexbox-and-grid.scss
ui/lib/core/addon/components/overview-card.hbs
ui/lib/ldap/addon/components/accounts-checked-out.hbs
ui/lib/ldap/addon/components/accounts-checked-out.ts
ui/lib/ldap/addon/components/page/library/details/accounts.hbs
ui/lib/ldap/addon/components/page/overview.hbs
ui/lib/ldap/addon/components/page/overview.ts
ui/lib/ldap/addon/routes/overview.ts
ui/lib/ldap/addon/templates/overview.hbs
ui/tests/integration/components/ldap/accounts-checked-out-test.js
ui/tests/integration/components/ldap/page/configuration-test.js
ui/tests/integration/components/ldap/page/configure-test.js
ui/tests/integration/components/ldap/page/libraries-test.js
ui/tests/integration/components/ldap/page/library/details/accounts-test.js
ui/tests/integration/components/ldap/page/overview-test.js
ui/tests/integration/components/ldap/page/roles-test.js
ui/types/vault/adapters/ldap/library.d.ts

This PR adds overview cards for roles, libraries, checked-out accounts and generating credentials to the ldap overview route.

LDAP Overview Cards

---

builtin/logical/database/path_roles.go
builtin/logical/database/rotation.go

This PR ensures that roles loaded from storage are rotated on the correct `rotation_schedule` or `rotation_period` depending on the configuration. We do this by updating the NextRotationTime() method to account for schedule or period-based rotations.

adv ttl mgmt: Ensure initialization sets appropriate rotation schedule

---

vault/audit_broker.go

This PR removes duplicate metric logging for an audit request and response.

audit: remove extra metric

---

.github/workflows/ci.yml
.github/workflows/security-scan.yml

These two jobs would simply fail on community PRs, with no way to make them pass, due to permissions issues. This should skip them.

Skip security-scan and test comment notifications on community PRs

---

.github/workflows/build-vault-oss.yml

This updates the linux package license to BUSL-1.1.
This PR should be merged to main so that the change is included in the next minor release that is cut from main.
License changes are not required on release branches (ongoing patch releases of current minor releases).

Update linux package license to BUSL-1.1

---

ui/app/adapters/kv/data.js
ui/app/adapters/kv/metadata.js
ui/app/models/kv/metadata.js
ui/app/styles/components/modal-component.scss
ui/app/styles/core/buttons.scss
ui/app/styles/helper-classes/layout.scss
ui/app/styles/helper-classes/typography.scss
ui/app/utils/kv-path.ts
ui/lib/kv/addon/components/kv-delete-modal.hbs
ui/lib/kv/addon/components/kv-delete-modal.js
ui/lib/kv/addon/components/page/list.js
ui/lib/kv/addon/components/page/secret/details.hbs
ui/lib/kv/addon/components/page/secret/details.js
ui/lib/kv/addon/components/page/secret/metadata/details.hbs
ui/lib/kv/addon/components/page/secret/metadata/details.js
ui/lib/kv/addon/components/page/secret/metadata/version-diff.hbs
ui/lib/kv/addon/components/page/secret/metadata/version-diff.js
ui/lib/kv/addon/components/page/secret/metadata/version-history.hbs
ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-navigation-test.js
ui/tests/integration/components/kv/page/kv-page-version-history-test.js
ui/tests/unit/adapters/kv/data-test.js
ui/tests/unit/adapters/kv/metadata-test.js

This component handles ALL kv delete/undelete actions. Screenshots of each below.
Notes:
* I renamed some of the key values in the destroyRecord on the data adapter. This helped match the "mode" and "delete-type" in the component and made it a little easier to read.
* I moved the delete on metadata to the metadata adapter and metadata view. 
* The design changes were confirmed with design. (Still confirming language changes from design but they won't effect functionality).

KV delete modal

---

changelog/22374.txt
vault/expiration.go

Deadlock occurs when Restore grabs lease lock then pending lock, while a revocationJob's OnFailure grabs those lock in the reverse order.

Prevent a deadlock in expiration

---

builtin/logical/database/path_roles_test.go
builtin/logical/database/rotation_test.go

Adds some validation for the init queue path and normalizes some of the Rotation test names so they are easier to run as a subset.

adv ttl mgmt: add tests for init queue

---

ui/lib/kv/addon/components/page/secret/details.js
ui/lib/kv/addon/components/page/secret/metadata/details.hbs
ui/lib/kv/addon/components/page/secret/metadata/version-history.hbs

All of the timestamps are hover-able and render the ISO timestamp 
- Adds `updated_time` to the metadata details as `Last updated`
- Adds `updated_time` to version history view
- Adds `deletion_time` to deleted secrets in version history
src="https://github.com/hashicorp/vault/assets/68122737/fa8ec7f3-18f3-40b9-98e4-015e8ce4174f">

ui: add deleted and updated time to kv secret

---

changelog/22390.txt
ui/app/styles/components/sidebar.scss
website/content/docs/enterprise/hsm/index.mdx

Small fix for a styling issue in the revoke token confirmation dialog triggered by the revoke action in the user menu. This was noticed while looking into issue #21390.
Before
After

Revoke Token Confirmation Text Fix

---

website/content/docs/agent-and-proxy/agent/template.mdx
website/content/docs/internals/telemetry/enable-telemetry.mdx

Currently the presence of a code block within a `<tip>` seems to cause issues with rendering. This PR moves the code block and accompanying text to below the actual tip.
[internals - telemetry - enable](https://developer.hashicorp.com/vault/docs/internals/telemetry/enable-telemetry#step-3-configure-telemetry-collection)
**Before**:
**After**:
Deployed here: https://vault-git-docs-internal-telemetry-enablefix-tip-hashicorp.vercel.app/vault/docs/internals/telemetry/enable-telemetry
---
Note: the 'bug' has been reported to the dev portal/ui team.
---
Additionally, it appears that `<tip>` requires newlines either side of content to ensure formatting is applied on markdown such as code.
See the `tip` section on the [agent template configuration](https://developer.hashicorp.com/vault/docs/agent- …

Move code block outside of 'tip' to resolving layout issues

---

changelog/22394.txt
ui/app/models/secret-v2.js

The default value of a secret's metadata was incorrectly setting `max_versions` to 10 which caused unintended side effects. This PR fixes #8656. Instead of setting the metadata's `max_versions` from the engine's config, leaving unset has the same result without manipulating any values under the hood.
The greater number takes precedence if both the engine _and_ secret metadata have `max_versions` configured. Otherwise, `0` means unset and if **neither** have a `max_versions` value, Vault will keep the 10 latest versions. 
| global (engine) | secret metadata | *versions kept - why?! |
| --------------- | --------------- | --------------------------------------------------------------------- |
| 0 | 0 | But are unset so Vault keeps 10 versions |
| 0 | 2* |  The engine has no global …

UI: remove default setting for `max_versions` in kv metadata

---

.github/workflows/milestone-checker.yml

Used the same logic as we do in other areas.
This check doesn't make much sense for community PRs, and hopefully this change goes towards keeping community PR checks greener!

Skip milestone check for community PRs

---

api/client.go
api/client_test.go
changelog/22410.txt

Fixes https://github.com/hashicorp/vault/issues/22393
I pushed the locking out of the top level Headers method, and use `headersInternal` with the lock held, instead, inside top level client functions. The test, `TestCloneWithHeadersNoDeadlock`, consistently failed before the fix, and consistently passes.

Fix client clone with headers deadlock

---

website/content/docs/concepts/policies.mdx

Updates a few markdown codeblocks from `ruby` to `hcl`

docs: fix codeblock language

---

changelog/22396.txt
website/content/docs/platform/aws/lambda-extension.mdx

The link pointing to supported lambda runtimes does not use correct markdown formatting so it is not rendered as a link on developer.hashicorp.com. This commit renders it as a link again.
|Before|After|
|-|-|
|![Screen Shot 2023-08-17 at 14 32 19](https://github.com/hashicorp/vault/assets/663247/a8ec50c7-6a20-480e-9101-273fae7c50e4)|![Screen Shot 2023-08-17 at 14 32 07](https://github.com/hashicorp/vault/assets/663247/fee950fa-a90f-4530-9d5d-815330f8c01d)|

Fix link formatting in Vault lambda extension docs

---

website/content/partials/telemetry-metrics/vault/raft_storage/bolt/write/time.mdx

The way it was written before made it sound like this is the amount of time it takes Bolt to write to disk _for each write_ when it's actually a cumulative total (not sure why that's useful, but at least let's make it less misleading).

Be more clear about bolt write timing

---

website/content/docs/enterprise/pkcs11-provider/oracle-tde.mdx

Remove text regarding setting encryption wallet in  sqlnet.ora in the "Enable TDE section".
Add steps to set the wallet location using parameters. 
Update Oracle Documentation references from 12c docs to 19c docs.

Update oracle-tde.mdx to remove deprecated sqlnet.ora configuration

---

vault/core.go

Fix to parse the ENV Var correctly (missed this case).
https://github.com/hashicorp/vault/pull/22344/files#diff-a0a40b411f03b3c927d6a2eafaf8a17693cc05a44e81bfe1362045a9372b9cfeR2367

Missed using the parseutil for parsing a Bool

---

.github/workflows/ci.yml
.github/workflows/test-go.yml
vault/logical_system_activity_write_testonly_test.go

Addresses https://hashicorp.atlassian.net/browse/VAULT-19122
There is a new build tag that is intended for testing purposes only. This PR adds a job to run some selected tests with the testonly build tag in addition to the explicit tests that are tagged with testonly.

adding testonly CI test job

---

builtin/logical/database/path_roles.go
builtin/logical/database/path_roles_test.go
builtin/logical/database/rotation.go

Description
This PR adds support for the rotation window. The `rotation_window` will define the window of time in which rotations are allowed to occur starting from a given `rotation_schedule`.  Any static role credentials that are not rotated during this window, due to a failure or otherwise, must wait to be rotated until the next rotation schedule.

adv ttl mgmt: consider rotation window

---

changelog/22458.txt
ui/lib/core/addon/components/form-field.hbs
ui/tests/integration/components/form-field-test.js

This reverts the work in this PR #22243 and actually solves the issue where the model default was overwriting the input and disallowing a user to clear the input
This line is redundant because `get @model this.valuePath` grabs the model default if there was one, so this was setting it again. Ember sets a model's attribute using the `defaultValue` and wherever we use `FormField` we also pass in the `@model` 
🐛 in the gif I'm clicking `backspace` but as soon as the input is cleared the value is replaced by the `defaultValue` - which is frustrating UX. For consistency the input should reflect the user's changes (which exist on the model)

UI: fix default values resetting form inputs

---

changelog/22400.txt
command/server/config_telemetry_test.go
command/server/config_test_helpers.go
command/server/test-fixtures/telemetry/rollback_mount_point.hcl
helper/metricsutil/wrapped_metrics.go
internalshared/configutil/config.go
internalshared/configutil/telemetry.go
vault/core.go
vault/rollback.go
vault/rollback_test.go
vault/router.go
vault/testing.go
website/content/docs/configuration/telemetry.mdx
website/content/docs/internals/telemetry/metrics/all.mdx
website/content/docs/internals/telemetry/metrics/core-system.mdx
website/content/docs/upgrading/upgrade-to-1.15.x.mdx
website/content/partials/telemetry-metrics/rollback-intro.mdx
website/content/partials/telemetry-metrics/route-intro.mdx
website/content/partials/telemetry-metrics/vault/rollback/attempt.mdx
website/content/partials/telemetry-metrics/vault/rollback/attempt/mountpoint.mdx
website/content/partials/telemetry-metrics/vault/route/rollback.mdx
website/content/partials/telemetry-metrics/vault/route/rollback/mountpoint.mdx

This PR creates two new metrics, `vault.route.rollback` and `vault.rollback.attempt`. These metrics replace the existing `vault.route.rollback.{MOUNT_POINT}` and `vault.rollback.attempt.{MOUNT_POINT}` metrics. By default, the metrics with the mount point in them are disabled, however they can be enabled with:
```
telemetry {
add_mount_point_rollback_metrics = true
}
```

[VAULT-17826] Remove mount point from rollback metrics

---

ui/lib/core/addon/components/input-search.hbs
ui/lib/core/addon/components/input-search.js
ui/lib/kv/addon/components/page/list.hbs
ui/lib/kv/addon/components/page/list.js
ui/lib/kv/addon/components/page/secret/details.hbs
ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-edge-cases-test.js
ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-navigation-test.js
ui/tests/helpers/kv/kv-selectors.js

This partially fixes the request here https://github.com/hashicorp/vault/issues/5362 so users can `LIST` at the secret level in the UI. 
Fixes https://github.com/hashicorp/vault/issues/20563 and https://github.com/hashicorp/vault/issues/13188 and https://github.com/hashicorp/vault/issues/20563
The user in the gif has the following policy where they can only `LIST` at the `my-secret/` level. Previously a user had to know the full secret path to view this list of secrets, now they just need the top-level secret path:
```
path "my-kv/metadata/my-secret/*" { capabilities = ["list", "read"] }
path "my-kv/data/my-secret/*" { capabilities = ["list", "read"] }
```
<hr>
If a user can only list metadata at the top level, so with a policy that looks something like: 
```
path "my-kv/data/*" { …
```

UI: allow navigation to subdirectory

---

changelog/22428.txt
changelog/22468.txt
physical/raft/raft.go
website/content/docs/upgrading/upgrade-to-1.14.x.mdx
website/content/partials/telemetry-metrics/vault/raft_storage/bolt/write/time.mdx

Changing this, per https://github.com/hashicorp/vault/pull/22428#issuecomment-1686230898

bolt.write.time should actually be a counter, not a gauge

---

changelog/22471.txt
ui/app/components/secret-create-or-update.js
ui/app/services/control-group.js
ui/app/templates/components/secret-create-or-update.hbs
ui/tests/acceptance/secrets/backend/kv/secret-test.js

This PR fixes the experience in the UI when attempting to create a new secret while a policy utilizing control groups. The example policy below which requires authorization for read, create, and update: 
```
path "kv-test/data/+/root" {
capabilities = [ "read","create","update" ]
control_group = {
factor "authorizer" {
identity {
group_names = [ "managers" ]
approvals = 1
}
}
}  
}
```
**Before**
Before, the submit button was disabled if there was an API error:
Once resubmit was enabled, there was a loop where each subsequent request to create the secret would generate a new control group accessor (which shows on the error banner):
**After**
I added notes to the codebase, but essentially we need to mark the token for unwrap when we handle the control group error in the control group, so …

UI: Enable KV create secret with Control Group

---

ui/app/adapters/kv/metadata.js
ui/lib/kv/addon/components/kv-delete-modal.js
ui/lib/kv/addon/components/kv-list-filter.hbs
ui/lib/kv/addon/components/kv-list-filter.js
ui/lib/kv/addon/components/page/list.hbs
ui/lib/kv/addon/components/page/list.js
ui/lib/kv/addon/components/page/secret/details.js
ui/lib/kv/addon/components/page/secret/metadata/details.hbs
ui/lib/kv/addon/components/page/secret/metadata/details.js
ui/lib/kv/addon/components/page/secrets/create.js
ui/lib/kv/addon/routes/list-directory.js
ui/lib/kv/addon/templates/list-directory.hbs
ui/lib/kv/addon/templates/list.hbs
ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-create-test.js
ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-navigation-test.js
ui/tests/integration/components/kv/kv-list-filter-test.js
ui/tests/unit/adapters/kv/metadata-test.js

I came across these 🧹 up tasks while working on the LIST Pagination functionality. I would like to address these changes before I open that PR for review.
Cleaned up:
* There was some lingering DELETE on kv/metadata issues. You can DELETE on metadata from two locations: the list view and the edit metadata view. I cleaned up the adapter destroyRecord and added comments to explain.
* Cleaned up KvListFilter by adding a navigate method.
* Solved issue of the queryParam pageFilter= when value was not set.

Delete on Metadata and KvListFilter clean up

---

ui/app/models/identity/entity.js
ui/app/models/kmip/credential.js
ui/app/models/kmip/role.js
ui/app/models/kmip/scope.js
ui/app/models/transform.js
ui/app/models/transform/alphabet.js
ui/app/models/transform/role.js
ui/app/models/transform/template.js

After the Ember 4.12 upgrade and the Ember-Data upgrade that went along with it, we found a strange error popping up intermittently: `Assertion Failed: Expected a stable identifier`
I tracked this down to the `store.unloadAll(modelType)` method failing when called during lazy pagination, and specifically to models which had a capabilities relationship via `attachCapabilities`. On any of the list routes for the models updated in this PR, if I left the list page (which has items) and then returned to it I would see the stable identifier issue. 
There's only one model left which has `attachCapabilities`, and that is `auth-method`. I left it because there is complexity with the path calculation which would require more refactoring than I'm comfortable with this close to a release, and the …

UI: Fix Expected a stable identifier error when leaving & reentering a route

---

builtin/logical/transit/path_certificates.go
builtin/logical/transit/path_certificates_test.go
builtin/logical/transit/path_export_test.go
sdk/helper/keysutil/policy.go

Fixes a bug in #21081 with CreateOperation without existence check -- I should've updated the branch prior to merging I guess :-) 
Also adds a new test to validate that importing a certificate with invalid key doesn't work.

Minor improvements to transit & csrs

---

changelog/20966.txt
go.mod
go.sum
sdk/go.mod
sdk/go.sum

Bumps the go-plugin package to pick up a [bugfix](https://github.com/hashicorp/go-plugin/issues/232) that broke our project on Windows. Our project uses the Vault SDK and we'd like to bump to the latest, but can't until the Windows bugfix is picked up.
I had some issues with the go tooling, it wasn't quite happy with the current state of go.mod. Forcing an upgrade of go-plugin to the same version that currently appears in go.mod resulted in many other dependency changes, so I resorted to editing manually ... what am I doing wrong?
Thanks in advance for your help here

Bump go-plugin dep

---

sdk/helper/testcluster/replication.go
sdk/helper/testcluster/types.go
sdk/helper/testcluster/util.go
vault/testing.go

OSS changes for https://github.com/hashicorp/vault-enterprise/pull/4585
Original PR https://github.com/hashicorp/vault-enterprise/pull/4254
The 1.13 ENT backport required a test helper that didn't get backported to 1.13, so these are the OSS changes required for my ENT backport PR.

Backport 1.13: Backport 1.13: Update-primary lite changes

---

command/events.go
http/events_test.go
http/handler.go

For now, only the leader of a cluster can handle subscription requests, so we forward the connection request otherwise.
We forward using a 307 temporary redirect (the fallback way). Forwarding a request over gRPC currently only supports a single request and response, but a websocket connection is long-lived with potentially many messages back and forth.
We modified the `vault events subscribe` command to honor those redirects. `wscat` supports them with the `-L` flag.
In the future, we may add a gRPC method to handle forwarding WebSocket requests, but doing so adds quite a bit of complexity (even over normal request forwarding) due to the intricate nature of the `http` / `vault.Core` interactions required. (I initially went down this path.)
I added tests for the forwarding header, and …

Forward websocket event subscription requests

---

api/client.go
changelog/22523.txt

The Host part of the URL doesn't actually get used when we initiate connections to UNIX domain sockets.  As of https://github.com/golang/go/issues/60374 (in the latest Go releases at the time of this writing), we must set it to something that looks like a hostname or requests will fail.

Work around issue with UNIX domain sockets in api.Client addresses

---

changelog/22519.txt
ui/lib/core/addon/components/info-table-row.hbs

The component `<InfoTableRow>` is a glimmer component, not a classic component, but some arguments in the handlebars file are still referred to in the classic Ember way. As a result, there is a problem where the "Last Vault Rotation" timestamp for static database roles is not rendering or copyable
This PR fixes this bug.

UI: Fix InfoTableRow args so row value renders with copyable tooltip

---

changelog/22533.txt
go.mod
go.sum

This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/5955888102

Update hashicorp/vault-plugin-secrets-alicloud to v0.15.1

---

ui/lib/core/addon/components/json-editor.hbs
ui/tests/integration/components/policy-example-test.js

The component `<JsonEditor>` has an unnecessary test selector `data-test-example-modal-json-text` I added to be used in the tests for the `<PolicyExample>` component. This PR cleans up the code by removing this test selector and using the existing one for the `<PolicyExample>` tests

UI: Clean up <JsonEditor> by removing unnecessary test selector

---

changelog/22541.txt
ui/app/routes/vault/cluster/secrets/backend/secret-edit.js

Before this change, if you click "cancel" on the "create secret" form in KV, a ghost secret would appear on the list when you return to the list view: 
In even older versions, this would cause the page to render a completely blank screen.

UI: Fix blank secret on KV create > cancel

---

ui/app/components/dashboard/client-count-card.js
ui/app/components/dashboard/quick-actions-card.js
ui/app/components/dashboard/vault-configuration-details-card.js
ui/app/controllers/vault/cluster/dashboard.js
ui/app/templates/components/dashboard/client-count-card.hbs
ui/app/templates/components/dashboard/quick-actions-card.hbs
ui/app/templates/components/dashboard/replication-card.hbs
ui/app/templates/components/dashboard/secrets-engines-card.hbs
ui/app/templates/components/dashboard/survey-link-text.hbs
ui/app/templates/vault/cluster/dashboard.hbs
ui/tests/acceptance/dashboard-test.js
ui/tests/acceptance/enterprise-replication-test.js
ui/tests/helpers/components/dashboard/quick-actions-card.js
ui/tests/helpers/components/dashboard/replication-card.js
ui/tests/helpers/replication.js
ui/tests/integration/components/dashboard/quick-actions-card-test.js
ui/tests/integration/components/dashboard/replication-state-text.js

- Acceptance tests for quick actions, client count, replication, and integration test for replication-state-text.js.
- Added the period for the feedback form to be after the icon
Other things added:
- kv tests + update to the quick actions kv model, update the id to have `kv version 1/2` 
- some small ui changes: hide show all button for secrets engines card when list < 5

UI: dashboard acceptance tests for quick actions, client count, replication

---

.github/workflows/test-go.yml

If any of the timing files end up being corrupted, we'd like to handle it gracefully without failing the test runner. In the worst case, we should fall back to building the default test matrix and persist any new entries in the cache. To prevent failure, we can check that all timing files are processed with `jq` at the time of `gotestsum` invocation.
As an extra precaution, we can also clear any bad timing files from the cache before they're persisted.

Fix malformed timing files

---

buf.yaml

Add the protobuf file to the list of exceptions for PACKAGE_DIRECTORY_MATCH and PACKAGE_VERSION_SUFFIX.

Fix multi_wrap_value.proto buf lint issues.

---

builtin/logical/database/backend.go
builtin/logical/database/path_creds_create.go
builtin/logical/database/path_roles.go
builtin/logical/database/path_roles_test.go
builtin/logical/database/path_rotate_credentials.go
builtin/logical/database/rotation.go
builtin/logical/database/rotation_test.go
changelog/22484.txt
go.mod
go.sum

This PR enables schedule-based auto-rotation of static roles for the Database Secrets engine. This rotation mechanism will be “embedded” in the Database Secrets engine and will not be reusable by other engines. In particular, this approach allows for exclusion windows (e.g. market hours) in which automatic rotations will not occur.
We add a new field `rotation_schedule` to the [create static role](https://developer.hashicorp.com/vault/api-docs/secret/databases#create-static-role) endpoint. This field can be set with a cron-style string that will define the schedule on which rotations should occur:
```
// set rotations to occur on Saturday at 00:00
vault write database/static-roles/test-role \
db_name=postgresql \
username="vault" \
rotation_schedule="0 0 * * SAT"
```
Additionally, we add …

secrets/database: advanced TTL management for static roles

---

changelog/22551.txt
ui/lib/core/addon/components/code-snippet.hbs
ui/lib/core/addon/components/info-table-row.hbs
ui/lib/kv/addon/components/page/secret/details.hbs
ui/lib/kv/addon/components/page/secret/metadata/details.hbs
ui/lib/kv/addon/components/page/secret/metadata/version-history.hbs
ui/lib/kv/addon/components/page/secret/paths.hbs
ui/lib/kv/addon/components/page/secret/paths.js
ui/lib/kv/addon/routes.js
ui/lib/kv/addon/routes/secret/paths.js
ui/lib/kv/addon/templates/secret/paths.hbs
ui/tests/helpers/kv/kv-selectors.js
ui/tests/integration/components/kv/page/kv-page-secret-paths-test.js

This adds a `paths` tab to the kv engine secret view that gives users the API and CLI paths for copying, plus sample commands

UI: add copyable paths for CLI and API commands to kv v2

---

ui/app/templates/components/dashboard/client-count-card.hbs
ui/app/templates/components/dashboard/replication-card.hbs
ui/tests/acceptance/dashboard-test.js
ui/tests/integration/components/dashboard/secrets-engines-card-test.js

- Fix client count + replication card date format for "updated at" to be 12 hr format.
- Move Show all button acceptance tests to be in the component tests. Tests were failing locally since we don't delete secrets engines so they were failing on re-run.

UI: VAULT-19359 update acceptance test and date format

---

vault/request_handling.go

This PR addresses a potential race introduced in https://github.com/hashicorp/vault/pull/18809. We want to make sure the activitylog doesn't change from underneath us, so we should make sure to use the activitylog pointer we've copied in a read lock, rather than `c.activityLog`.

Fix potential race on core.activityLog

---

ui/tests/acceptance/dashboard-test.js

In order to prevent enterprise test failures before the weekend, I opted to skip two community version-specific tests for now. 
**Possible solutions:**
- Create a dashboard component so that we can create integration tests. By making the dashboard a component we can set the version to be enterprise vs. community. 
- Separate oss and enterprise tests and make tests more general since all tests should pass regardless of enterprise or oss when testing in enterprise tests

UI: Skip some community tests for now

---

vault/eventbus/bus.go
vault/eventbus/bus_test.go

This PR fixes `EventBus.Subscribe()` for non-root namespaces without requiring callers to modify the `Path` field of the passed `namespace.Namespace`. It's most common for the namespace path to contain a trailing slash. The [filter node predicate](https://github.com/hashicorp/vault/blob/main/vault/eventbus/bus.go#L270) trims leading/trailing slashes which resulted in the events being filtered.
Added a test that would fail before this change.

Fixes events subscribe for non-root namespaces

---

.github/workflows/plugin-update.yml

Includes everything after the 3rd position as the PLUGIN_SERVICE, so that plugins like "vault-plugin-database-redis-elasticache" end up with the full name in the changelog entry.
```console
$ echo "vault-plugin-database-redis-elasticache" | awk -F- '{print $4}'
redis
$ echo "vault-plugin-database-redis-elasticache" | cut -d- -f 4-
redis-elasticache
$ echo "vault-plugin-database-snowflake" | cut -d- -f 4-
snowflake
```

ci/plugin-update: use rest of repo name as service

---

vault/logical_system.go
vault/logical_system_helpers.go

This PR adds a stubbed `InitializeFunc` to the system backend. This follows the same pattern as the `Invalidate` function. The intent it to have an enterprise-only `InitializeFunc` on the system backend for specific features.

Adds stubbed InitializeFunc to the system backend

---

builtin/logical/database/backend.go
builtin/logical/database/path_roles.go
builtin/logical/database/path_roles_test.go
builtin/logical/database/rotation.go
builtin/logical/database/rotation_test.go
builtin/logical/database/schedule/schedule.go

Define a new interface called Scheduler. This allows the unit tests to define their own implementation of Scheduler so that we can set seconds in the cron schedule and lower the rotation window. Additionally, we define a DefaultScheduler that the backend will use for production.

adv ttl mgmt: define schedule interface

---

changelog/22583.txt
http/util.go
sdk/logical/request.go
vault/login_mfa.go
vault/request_handling.go

The main purpose of this PR is to reduce calls to `c.DetermineRoleFromLoginRequest` in order to reduce the latency of login requests. 
Benchmarking results:
Main `mean: 704.492117ms`:
Main with changes from PR `mean: 341.443427ms`:
Vault v1.10.4 `mean: 180.187269ms`:

reduce calls to DetermineRoleFromLoginRequest from 3 to 1 for aws auth method

---

website/content/docs/configuration/storage/raft.mdx

Calling out corresponding parameter for Vault's integrated storage `max_entry_size` with Consul's `kv_max_value_size`.

Add note to outline correspondence with Consul config

---

vault/auth.go
vault/mount.go

This PR sets the namespace context key for backend `InitializeFunc` calls. The storage view is properly set for the namespace, but I noticed that the namespace associated with the context is always the root namespace. This allows backend `InitializeFunc` implementations to know which namespace they're being initialized in.

Set proper namespace in context given to backend InitializeFunc

---

command/commands.go

This PR lifts the `loginHandlers` map containing auth method CLI login handlers to a package variable. This allows enterprise-only auth methods to be added to it following a similar pattern as enterprise-only `logicalBackends`.

Lifts login handlers map to a variable

---

ui/app/templates/components/generated-item.hbs
ui/app/templates/components/transit-key-actions.hbs
ui/tests/acceptance/auth-list-test.js
ui/tests/acceptance/transit-test.js

- Separates the larger `keyTypes` array into smaller groups to remove some of the conditionals from the test loop. 
- Changes some assertions from general `assert.ok()` that just return a boolean to clearer methods like `exists()` to more easily track down any future flakiness
- Updates userpass auth test

ui: addressing flaky transit backend and userpass tests

---

changelog/22597.txt
http/util.go
vault/core.go
vault/quotas/quotas.go
vault/quotas/quotas_test.go
vault/request_handling.go

This PR skips `ResolveRoleOperation` calls for requests if the namespace/mount doesn't have role-based quotas.
We later perform the operation on-demand for lease creation if it has not already been done.

Skip unneeded resolve role

---

website/content/docs/concepts/resource-quotas.mdx
website/content/docs/enterprise/lease-count-quotas.mdx

Correct link: https://developer.hashicorp.com/vault/docs/internals/telemetry/metrics/core-system#quota-metrics
Incorrect link: https://developer.hashicorp.com/vault/docs/internals/telemetry#Resource-Quota-Metrics

Fix broken quotas metrics links

---

.github/workflows/ci.yml

I accidentally merged this on the ent side (#4597), but meant to apply it to OSS instead.  This PR consists simply of copying the ci.yml from #4597.

Sync CE with Ent: improve slack notifications for test failures

---

changelog/22655.txt
go.mod
go.sum

This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/6028146752

Update hashicorp/vault-plugin-database-mongodbatlas to v0.10.1

---

ui/lib/kv/addon/components/page/secret/edit.js
ui/tests/acceptance/enterprise-namespaces-test.js
ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-create-test.js
ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-edge-cases-test.js
ui/tests/integration/components/kv/page/kv-page-secret-edit-test.js
ui/tests/pages/auth.js

This fixes an issue in a namespace where the UI was not navigating the latest secret version details view after creating a new secret version.
This was also tested in a namespace with a policy that had `CREATE` but no `READ` capabilities
```shell
path "test-ns-1/kv-ns/data/*" {
capabilities = [ "create", "update", "list" ]
}
path "test-ns-1/kv-ns/metadata/*" {
capabilities = [ "create", "update", "list"]
}
```
Add-on to work in this PR: https://github.com/hashicorp/vault/pull/22426

UI: fix redirect after creating new version of a KV v2 secret in a namespace

---

command/auth_enable_test.go

This PR adds an adjustment factor for assertions in auth enable tests. This will allow for adjustments to the test assertions when enterprise auth methods are added.
This follows a similar pattern as https://github.com/hashicorp/vault/blob/main/command/secrets_enable_test.go#L19-L22.

Adds adjustment factor for assertions in auth enable tests

---

sdk/helper/pluginutil/runner.go
vault/logical_system.go
vault/logical_system_test.go
vault/plugin_catalog.go
vault/plugin_catalog_test.go
vault/testing.go

Use a struct arg instead of a long list of args. Plugins running in containers will require even more args and it's getting difficult to maintain.

Refactor plugin catalog set functions

---

audit/options.go
audit/options_test.go
changelog/22694.txt

This PR updates the way in which the HeaderFormatter option is applied such that it will not allow interfaces with `nil` type or value to be set. 
The aim of the PR is to prevent the ability for audit code to panic in certain circumstances when the formatter appears to be `!=nil` but ends up as a nil pointer receiver.

Fix potential panic in audit during header formatting

---

ui/lib/kv/addon/components/page/secret/details.hbs
ui/lib/kv/addon/components/page/secret/details.js
ui/lib/kv/addon/components/page/secret/edit.hbs
ui/lib/kv/addon/components/page/secret/edit.js
ui/lib/kv/addon/components/page/secrets/create.hbs
ui/lib/kv/addon/components/page/secrets/create.js
ui/lib/kv/addon/routes/secret.js
ui/lib/kv/addon/routes/secret/details.js
ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-edge-cases-test.js
ui/tests/helpers/kv/kv-run-commands.js

Deleting a secret **in a namespace** initially renders an empty state but if you navigate between sibling routes (click another tab) the stale secret model (`kv/data`) re-renders when you return to the details view (`Secret` tab). The deleted state restores when you refresh the page.
<hr>

ui: Refreshes parent route to fix secret state discrepancies within a namespace for kv v2 

---

changelog/22696.txt
go.mod
go.sum

This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/6040678199

Update hashicorp/vault-plugin-database-elasticsearch to v0.13.3

---

changelog/22678.txt
go.mod
go.sum

This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/6030728227

Update hashicorp/vault-plugin-auth-jwt to v0.17.0

---

ui/app/models/kv/metadata.js
ui/lib/kv/addon/components/kv-delete-modal.js
ui/tests/unit/adapters/kv/metadata-test.js

We first wrote the adapter test before completing the project. We ended up adding a couple of methods and needed to add test coverage for them.
I also came across the selector `getSecret` on the model failing on the test view because we don't have version information at this point. I amended the getter and where the getter was being consumed to prevent any potential issues.

Add missing kv/metadata adapter test coverage

---

changelog/22657.txt
command/server.go
command/server/config.go
command/server/tls_util.go
command/server/tls_util_test.go
command/server_test.go

This is helpful when wanting to set up a dev server with TLS in Kubernetes and any other situations where the dev server may not be the same machine as the Vault client (e.g. in combination with some /etc/hosts entries)

Add -dev-tls-san flag

---

vault/seal/seal.go
vault/seal/seal_wrapper.go
vault/seal_autoseal.go
vault/seal_autoseal_test.go

Extract method SealWrapper.CheckHealth out of StartHealthCheck.
Restore the metrics around overall seal health, so that we have metrics for
individual seal wrappers as well as the backend itself.

Refactor the seal wrapper health check

---

changelog/22716.txt
go.mod
go.sum

This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/6043692362

Update hashicorp/vault-plugin-secrets-kv to v0.16.1

---

changelog/22734.txt
go.mod
go.sum

This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/6051637937

Update hashicorp/vault-plugin-secrets-openldap to v0.11.2

---

website/content/docs/internals/telemetry/enable-telemetry.mdx
website/content/docs/internals/telemetry/index.mdx

Add links to the best practices guide for telemetry metrics so it's easier for folks to find.
On the Enable telemetry how-to guide:
On the telemetry landing page:

[DOCS] Add WAF links for metric best practice guide

---

command/server.go
helper/testhelpers/seal/sealhelper.go
vault/core.go
vault/logical_system.go
vault/rekey.go
vault/seal/seal.go
vault/seal/seal_testing.go
vault/seal/seal_wrapper.go
vault/seal_autoseal.go
vault/seal_autoseal_test.go
vault/seal_config.go
vault/seal_testing_util.go

Create accessors for SealWrapper fields protecteb by the lock.
Make the fields "private" and add accessors and mutators for those fields to ensure proper lock handling.
Use NewSealWrapper constructor to create all seal wrappers.
Add convenience method NewAccessFromWrapper for the common case of creating an Access for single seal wrapper.
Use pointers to SealWrapper rather than direct variables.

Protect SealWrapper health fields

---

.github/workflows/security-scan.yml

This reverts commit 980857808644b091f87ecef0527f1a08f903fced (#22731).
Previous issue fixed in returntocorp/semgrep#8604, released in 1.38.1

Revert "Pin security scan's semgrep version to 1.37.0 (#22731)"

---

changelog/22746.txt
go.mod
go.sum

This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/6053665653

Update hashicorp/vault-plugin-secrets-gcp to v0.17.0

---

changelog/22748.txt
go.mod
go.sum

This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/6054223735

Update hashicorp/vault-plugin-secrets-mongodbatlas to v0.10.1

---

vault/rollback_test.go

Before, the test didn't know which backends had rolled back and it was possible that if we stopped the rollback manager before rollbacks for the test backends were queued, then the test would fail. It was also possible that the test would check the GreaterOrEqual condition before the element was added to the map.
I've switched up the test to instead require that we get responses from all of the backends before stopping.

Fix flaky rollback test

---

changelog/22753.txt
sdk/helper/keysutil/policy.go

When an invalid (non-PEM) public key is given to Transit's import, this fails with a panic in server logs:
2023-09-05T08:11:11.526-0400 [INFO]  http: panic serving 127.0.0.1:42414: runtime error: invalid memory address or nil pointer dereference
goroutine 950 [running]:
net/http.(*conn).serve.func1()
/usr/local/go/src/net/http/server.go:1868 +0xb9
panic({0x8371620?, 0x1050b390?})
/usr/local/go/src/runtime/panic.go:920 +0x270
github.com/hashicorp/vault/sdk/helper/keysutil.(*Policy).ImportPublicOrPrivate(0xc003fff440, {0xaf02918, 0xc004509920}, {0xaf03670, 0xc0032e4180}, {0xc004532ea0, 0x188, 0x1a0}, 0x0, {0xae7f5e0, ...})
/home/cipherboy/GitHub/cipherboy/vault/sdk/helper/keysutil/policy.go:1538 +0x687
github.com/hashicorp/vault/sdk/helper/keysutil.(*LockManager).ImportPolicy(0xc001a29410, …

Fix transit panic with invalid PEM

---

changelog/22758.txt
go.mod
go.sum

This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/6086077151

Update hashicorp/vault-plugin-auth-cf to v0.15.1

---

changelog/_22733.txt
ui/app/styles/components/namespace-picker.scss
ui/app/styles/helper-classes/typography.scss
ui/app/templates/components/namespace-picker.hbs

UI: [VAULT-18126] adding style to prevent namespace to overflow on sidebar

---

changelog/22757.txt
go.mod
go.sum

This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/6086081175

Update hashicorp/vault-plugin-secrets-gcpkms to v0.15.1

---

changelog/22760.txt
go.mod
go.sum

As with 1.13, this required a specific Azure SDK version.

Update go-kms-wrapping to get Azure HTTP/2 workaround (1.14.x)

---

ui/lib/kv/addon/components/kv-delete-modal.js
ui/lib/kv/addon/components/page/secret/metadata/details.hbs
ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-delete-test.js
ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-edge-cases-test.js

See original PR [here](https://github.com/hashicorp/vault/pull/22773). 
Did a manual backport because the backport label does not exist yet for this release branch.

Backport 1.15.x: Manual to rename delete metadata

---

ui/app/styles/helper-classes/general.scss
ui/lib/core/addon/components/info-table-row.hbs
ui/lib/core/addon/components/info-table-row.js
ui/lib/kv/addon/components/page/secret/paths.hbs

**Before**
**After truncating long path names:**

UI: [VAULT-19478] Fix info table row value overflow

---

changelog/22790.txt
go.mod
go.sum

Bumping to v0.16.2 to get some [additional event metadata](https://github.com/hashicorp/vault-plugin-secrets-kv/pull/129) needed to properly handle destroy events.
Steps:
```
go get github.com/hashicorp/vault-plugin-secrets-kv@v0.16.2
go mod tidy
```

Bumped kv plugin

---

vault/seal/seal.go
vault/seal/seal_wrapper.go
vault/seal_autoseal.go

Add timeout to Access.Encrypt() to allow for partial success.
Start goroutines for each of the seal wrappers to encrypt values. After a timeout, return any successful encryption results and errors for those that failed or did not complete on time.
Return from Access.Decrypt() on first successful result.
Start goroutines for each of the seal wrappers to decrypt values, and return on the first successful result.
Start the highest priority wrapper immediately, and the rest after a delay to give it a head start.

Skip unhealthy seal wrappers when performing encryption or decryption.

---

ui/app/styles/core/buttons.scss
ui/app/styles/helper-classes/flexbox-and-grid.scss
ui/app/templates/components/transit-key-action/datakey.hbs
ui/app/templates/components/transit-key-action/decrypt.hbs
ui/app/templates/components/transit-key-action/encrypt.hbs
ui/app/templates/components/transit-key-action/export.hbs
ui/app/templates/components/transit-key-action/hmac.hbs
ui/app/templates/components/transit-key-action/rewrap.hbs
ui/app/templates/components/transit-key-action/sign.hbs
ui/tests/integration/components/transit-key-actions-test.js

This is the 3rd of 5 subtasks for the replacement of the structure `<CopyButton>` with the `<Hds::Copy::Button>`. In this subtask, I replaced the copy buttons in 7 files, namely the files in ui/app/templates/components/transit-key-action. Photos of each before and after are shown in the comments.
Sticking with the plan of making the HDS copy button look similar to the structure copy button until all buttons are replaced, I created a class to mimic the old style of the "Copy & Close" button you'll see in 6 of the 7 changed files. After this PR and all other subtasks are merged into my side branch, I will get feedback from Design about the implementation.
**NOTE:**
The icon of the `<Hds::Copy::Button>` changes to show success or error when it is clicked. Therefore, with the HDS copy button, …

UI: HDS adoption replace <CopyButton> part 3

---

changelog/22824.txt
go.mod
go.sum

This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/6101735864

Update hashicorp/vault-plugin-secrets-azure to v0.16.3

---

ui/app/routes/vault/cluster/tools/tool.js
ui/app/templates/vault/cluster/tools/error.hbs

Closes issue #10534 where a mistyped tool name in the URL would not indicate that something was amiss. 
Now, if the URL does not include a valid tool it shows an error message "Not found" with the attempted URL:

UI: Show error if tool action is not recognized

---

ui/lib/ldap/addon/components/page/libraries.ts
ui/lib/ldap/addon/components/page/roles.ts

When deleting a library or role from an LDAP secrets engine the following error was being caught and displayed in a flash message:
It seems that using `removeObject` on a `RecordArray` is not allowed and also unnecessary since the array is updated automatically on `model.destroyRecord` success.

LDAP Libraries and Roles Delete Bug

---

ui/app/models/ldap/library.js
ui/app/models/ldap/role.js
ui/tests/integration/components/ldap/page/library/create-and-edit-test.js
ui/tests/integration/components/ldap/page/role/create-and-edit-test.js

Since the name field for LDAP library and roles corresponds to the path, changing the name when editing will actually create a new library or role. This PR updates the name fields to be disabled when editing.

LDAP Disable Name Edit

---

ui/lib/ldap/addon/components/accounts-checked-out.ts
ui/lib/ldap/addon/components/page/library/details/accounts.hbs
ui/lib/ldap/addon/components/page/overview.hbs
ui/tests/integration/components/ldap/accounts-checked-out-test.js

There was an error caught when checking in a library account from the overview route that prevented the view from updating. Since this component is used in a couple of different places a success callback was added to the component so refreshing the view can be handled depending on where it's used.

LDAP Library Check-in Bug

---

http/events_test.go

The more I looked at this test, the more I realized it wasn't testing anything except that the namespace parameter was being parsed by the websocket.
So, I moved that parameter parsing check to `TestEventsSubscribe()`, which is not flaky, and removed the flaky test altogether.
There is a similar set of tests in the enterprise repo that I will try to simplify and make less flaky, though.

events: remove flaky test

---

changelog/22815.txt
command/server.go
command/server/config.go
helper/experiments/experiments.go
http/events_test.go
http/logical.go
vault/auth.go
vault/core.go
vault/events_test.go
vault/mount.go

The flag `events.alpha1` will no longer do anything, but we keep it to prevent breaking users who have it in their configurations or startup flags, or if it is referenced in other code.

events: Enable by default, disable flag

---

changelog/22818.txt
command/kv_patch.go
command/kv_put.go

The CLI currently fails to output the wrapping info for `vault kv patch` and `vault kv put` commands.
Output before:
Output after:
The fix was copied from a PR that fixed the same problem for `vault kv list`: https://github.com/hashicorp/vault/pull/12031

[VAULT-1324] Fix the CLI failing to return wrapping information for KV PUT and PATCH operations when format is set to 'table'

---

changelog/22835.txt
command/events.go
go.mod
go.sum
http/events.go
http/events_test.go
sdk/logical/events.go
vault/eventbus/bus.go
vault/eventbus/bus_test.go
vault/events_test.go

Subscribing to events through a WebSocket now support boolean expressions to filter only the events wanted based on the fields
* `event_type`
* `operation`
* `source_plugin_mount`
* `data_path`
* `namespace`
Example expressions:
These can be passed to `vault events subscribe`, e.g.,:
* `event_type == abc`
* `source_plugin_mount == secret/`
* `event_type != def and operation != write`
```sh
vault events subscribe -filter='source_plugin_mount == secret/' 'kv*'
```
The docs for the `vault events subscribe` command and API endpoint will be coming shortly in a different PR, and will include a better specification for these expressions, similar to (or linking to) https://developer.hashicorp.com/boundary/docs/concepts/filtering

events: WebSocket subscriptions support go-bexpr expressions

---

ui/lib/ldap/addon/components/page/role/credentials.hbs
ui/lib/ldap/addon/components/page/role/credentials.ts
ui/lib/ldap/addon/routes/roles/role/credentials.ts
ui/lib/ldap/addon/templates/roles/role/credentials.hbs
ui/tests/integration/components/ldap/page/role/credentials-test.js

This PR moves the error handling for fetching LDAP role credentials to the credentials route rather than deferring to the top level error route for the engine.
_Before_
_After_

LDAP Role Credentials Error Handling

---

http/events_test.go

When #22835 was merged, it was auto-squashed, so the `experiments` import was removed, but the test still referenced it.
This removes the (now unnecessary) experiment from the test.

Fix auto-squash events experiments

---

changelog/22879.txt
go.mod
go.sum

This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/6115342773

Update hashicorp/vault-plugin-auth-kubernetes to v0.17.1

---

.github/workflows/test-go.yml
vault/external_plugin_container_test.go

We can't use `sudo` on our self-hosted runners at the moment to do the install and Docker reload.
So, we'll disable this for now, which should automatically cause the gVisor-related tests to be skipped.

Disable gVisor in tests (for now)

---

http/events_test.go

This is a bit of a guess, but I've had a couple of CI runs timeout recently, and when I compare the logs of tests that completed with a log of the test order running locally, it looks like TestBexprFilters _might_ be the test that's hanging: https://github.com/hashicorp/vault/actions/runs/6114814016/job/16597219838. Naturally this isn't actually a fix for the test, but hopefully it will more quickly expose any failures.

Add timeout for http events tests

---

website/content/docs/enterprise/namespaces.mdx

I noticed these were missing when reviewing PRs for the admin namespace work, and thought I should amend it.

Add sys/monitor and sys/audit-hash to root only namespace list

---

ui/lib/ldap/addon/components/page/overview.hbs

The second row of cards on the LDAP overview route were not using the responsive grid classes which was causing the view to be partially broken on smaller viewports. This PR updates the classes and now the cards are stacked in a full width column.

LDAP Overview Responsive Layout

---

changelog/22907.txt
go.mod
go.sum

This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/6123809373

Update hashicorp/vault-plugin-secrets-terraform to v0.7.3

---

changelog/22914.txt
helper/testhelpers/pluginhelpers/pluginhelpers.go
sdk/plugin/grpc_backend_client.go
vault/plugin_catalog.go

Also fixes a function where we may call go-plugin's client.Client() without ever calling client.Kill(), which could leak plugin processes.
It's pretty tricky to write an automated test for this, I'm still working on it, but wanted to get the change in before code freeze. To test manually, install runsc, and then break it for plugins by removing the additional runsc args we require - i.e. /etc/docker/daemon.json should look like this:
```json
{
"runtimes": {
"runsc": {
"path": "/usr/local/bin/runsc"
}
}
}
```
Then run `sudo systemctl reload docker` and run some of the tests in `external_plugin_container_test.go`. Prior to this change it will hang indefinitely and then leave docker containers hanging around if you kill it. After this change, it should fail quickly and clean up after itself.

Avoid Vault hang when no communication established with plugin

---

http/events.go
http/events_test.go
vault/request_handling.go

We grab the state lock and check that the core is not shutting down.
This panic mostly seems to happen if Vault is shutting down, usually in a test.

Safer check in http/events validateSubscribeAccessLoop

---

ui/lib/kmip/addon/templates/credentials/show.hbs

When viewing credentials in KMIP, there is a small styling problem. The `<MaskedInput>` in the "Private Key" row doesn't look right.
Reproduction steps:
1. Enable KMIP engine and configure it
2. Create scope
3. Click on scope and create role
4. Click on role and generate credentials in any format
5. View credentials
Before:
After:

UI: Small styling fix when viewing KMIP credentials

---

command/agent_test.go

If the agent fails to start, for example when a port conflict occurs, we want the test to fail fast, rather than continuing until the test times out.
If this 5-second timeout occurs waiting for the agent to start up, then it does not make logical sense to continue the test. So, we use `t.Fatalf` to trigger the failure.

agent: Fail fast if agent doesn't start

---

.github/workflows/test-go.yml

This adds back the CI step to install gVisor, but skips it on enterprise where the runners don't allow sudo, see a test run here: https://github.com/hashicorp/vault-enterprise/actions/runs/6120353721/job/16612145892
I'll be working with release engineering to get gVisor installed by default, as well as rootless runtimes and possibly podman, so depending on the outcome of that, this may just a temporary measure to give us some better CI coverage in the meantime.

Conditionally install gVisor in CI

---

internalshared/configutil/kms.go

- This addresses a test-failure in ENT and a use-case in which we would force a migration for stored configs that had been written with a nil configuration. 
- This also keeps the behavior consistent if no configuration values exist the map member variable is nil and not an empty map.

Only initialize the KMS config map if env map contains values

---

.github/workflows/enos-release-testing-oss.yml

The CRT orchestrator triggers the release testing workflows for all release versions using the same main ref. Therefore, if we have concurrency controls in place we could cancel them if more than one release branch is executing workflows.

release: remove concurrency groups from release testing

---

.github/workflows/test-run-enos-scenario-matrix.yml

This adds edition handling to the test-run-enos-scenario-matrix workflow. Previously we'd pass the version and edition from the caller, but that isn't an option in the release testing workflow, which only passes the metadata version without the edition.

test: handle the edition in the release testing workflow

---

ui/tests/integration/components/mount-backend/type-form-test.js

Previously this was trying to count secret engines. Fixed so its now counting auth methods.

Fix SAML auth count test

---

ui/tests/acceptance/auth-test.js

This test is now flaky because we removed the login/logout in the test hooks for the[ Ember upgrade.](https://github.com/hashicorp/vault/pull/22122/files#diff-502ad095ef43cf3ff2bf2bdd5fa7ca44e498d0f74d2a44c0970e570ab956386e)
Because we don't consistently login/logout this test holds onto the github login from the previous flow and instead of showing the queryParam of token, it shows github. I confirmed by checking past Vault versions that this _is_ expected behavior. 
I think it's safe to remove this line because we're testing similar functionality in the test before it, with the "auth query params".

Fix flaky auth test

---

CODEOWNERS

This PR adds the vault-ecosystem-applications team as code owners of Vault OIDC provider and identity tokens.

codeowners: adds identity oidc and token integrations to ecosystem

---

changelog/22997.txt
vault/eventbus/bus.go

Now that events are enabled by default in 1.15.0, it seems a bit too noisy to log each event at info level.

Events: Drop log level for events to debug

---

ui/lib/kv/addon/components/page/secret/paths.js

This encodes the namespace value for API paths - the screenshot below shows paths for `namespace%1`

ui: encode namespace for copyable KV v2 API paths

---

changelog/_22640.txt

This PR removes a changelog entry for 1.15 which came from https://github.com/hashicorp/vault/pull/22640. It will be replace by another changelog entry.

ui: remove a changelog entry for 1.15

---

builtin/logical/pki/crl_test.go
builtin/logical/pki/path_fetch_issuers.go
builtin/logical/pki/storage.go
changelog/23007.txt

When a issuer is removed, the space utilized by its CRL was not freed, both from the CRL config mapping issuer IDs to CRL IDs and from the CRL storage entry. We thus implement a two step cleanup, wherein orphaned CRL IDs are removed from the config and any remaining full CRL entries are removed from disk.
This relates to a Consul<->Vault interop issue (#22980), wherein Consul creates a new issuer on every leadership election, causing this config to grow. Deleting issuers manually does not entirely solve this problem as the config does not fully reclaim space used in this entry.
Notably, an observation that when deleting issuers, the CRL was rebuilt on secondary clusters (due to the invalidation not caring about type of the operation); for consistency and to clean up the unified CRLs, we …

Clean up unused CRL entries when issuer is removed

---

changelog/23025.txt
ui/app/components/generate-credentials.js

Previous to this change, having a control group on the `ssh/creds/*` path would result in a generic, unhelpful "Adapter Error" message when attempting to generate a credential: 
After this change, the user sees the full Control Group message and has access to the control group accessor:

UI: Handle control group error on SSH

---

changelog/21641.txt

It wasn't using the right feature format, and also should probably have been an improvement.

Fix LDAP auto auth changelog

---

changelog/23042.txt
vault/eventbus/bus.go
vault/eventbus/bus_test.go

I noticed this while reviewing #23024. It seems the `broker` field was never populated, so we never cleaned up the pipeline on close. However, we only need one method from the broker, so I narrowed the field down to one function as well.

events: Ensure pipelines are cleaned up on closing subscription

---

http/events.go
http/events_test.go
vault/eventbus/bus.go

The WebSocket tests have been very flaky because we weren't able to tell when a WebSocket was fully connected and subscribed to events.
We reworked the websocket subscription code to accept the websocket only after subscribing.
This should eliminate all flakiness in these tests. 🤞 (We can follow-up in an enterprise PR to simplify some of the tests after this fix is merged.)
I ran this locally a bunch of times and with data race detection enabled, and did not see any failures.

events: Don't accept websocket connection until subscription is active

---

website/pages/api-docs/system/plugins-reload-backend.mdx

It was reported that the sample request is missing data from the **1.4.x** doc.
🧵 [Slack](https://hashicorp.slack.com/archives/C012RTGJR1V/p1694527942628429)
This PR adds the missing `--data @payload.json` to the request example.

[Docs] Add missing parameter in the request

---

go.mod
go.sum
sdk/go.mod
sdk/go.sum

Fixes a bug that prevented Vault from streaming plugin containers' logs

Bump plugincontainer dep v0.2.0 -> v0.2.1

---

vault/policy_store.go
vault/policy_store_test.go
vault/request_handling.go

This PR changes how we evaluate Sentinel Role Governing Policies (RGPs) in two ways:
1. From now on, RGPs will not be affected by the [group_policy_application_mode setting](https://developer.hashicorp.com/vault/api-docs/system/config-group-policy-application). At all.
2. RGPs derived from token's memberships in identity groups can only apply to requests in child namespaces in the same hierarchy.

[VAULT-14497] Ensure Role Governing Policies are only applied down the namespace hierarchy

---

website/content/docs/upgrading/upgrade-to-1.13.x.mdx
website/content/docs/upgrading/upgrade-to-1.14.x.mdx
website/content/partials/known-issues/transit-managed-keys-panics.mdx
website/content/partials/known-issues/transit-managed-keys-sign-fails.mdx

- Document known issue around managed key encryption failure with Cloud KMS backed keys and the failure to sign with managed keys

Add known issues around transit managed keys

---

changelog/23103.txt
go.mod
go.sum
sdk/go.mod
sdk/go.sum
sdk/helper/ldaputil/connection.go

Follow up to #22185, which introduced the cap/ldap library, and bumped the go-ldap library version to v3.4.5. Unfortunately, this caused some test failures due to race conditions.
This PR downgrades go-ldap to v3.4.4 to avoid the race conditions.
Example of data race:
```
Read at 0x00c00d6a6480 by goroutine 108756:
github.com/go-ldap/ldap/v3.(*Conn).Close()
/home/runner/go/pkg/mod/github.com/go-ldap/ldap/v3@v3.4.5/conn.go:291 +0x1bd
github.com/go-ldap/ldap/v3.(*Conn).reader.func1()
/home/runner/go/pkg/mod/github.com/go-ldap/ldap/v3@v3.4.5/conn.go:582 +0x104
runtime.deferreturn()
/home/runner/actions-runner/_work/_tool/go/1.21.1/x64/src/runtime/panic.go:477 +0x30
github.com/go-ldap/ldap/v3.(*Conn).Start.func1()
/home/runner/go/pkg/mod/github.com/go-ldap/ldap/v3@v3.4.5/con …
```

downgrade go-ldap client to v3.4.4 due to race conditions in tests

---

enos/enos-globals.hcl
enos/enos-scenario-agent.hcl
enos/enos-scenario-autopilot.hcl
enos/enos-scenario-proxy.hcl
enos/enos-scenario-replication.hcl
enos/enos-scenario-smoke.hcl
enos/enos-scenario-ui.hcl
enos/enos-scenario-upgrade.hcl
enos/enos-variables.hcl
enos/enos.vars.hcl
enos/modules/vault_cluster/main.tf
enos/modules/vault_cluster/outputs.tf
enos/modules/vault_cluster/scripts/enable_audit_logging.sh
enos/modules/vault_cluster/templates/install-packages.sh
enos/modules/vault_cluster/variables.tf

This PR also enables the **syslog** and **socket** Audit Devices in the *vault_cluster* module of the enos scenarios.

Enabling all 3 Audit Device types in enos

---

ui/.template-lintrc.js

First some history. We wanted to tell `ember-template-lint` to not lint test files which works fine using the `ignore` field in the config. Unfortunately, the `ember-language-server` VSCode plugin does not support that field so we had a mismatch between linting via the CLI and what we were seeing in the editor.
To solve this problem, the full rule set from `ember-template-lint` was required in the config and then looped to turn off each rule within tests using the `overrides` config field (see #13632). This worked for a time, until it didn't.
Fast forward and `ember-template-lint` upgraded to use modules (esm) and we could no longer _require_ the rules within the config. A [hacky workaround](https://github.com/hashicorp/vault/pull/14763/files#diff-7cd0cd936ce0b05b5380c1116ddddca6b7ad412d51 …

Ember Template Linting in Tests

---

changelog/23119.txt
ui/app/models/role-ssh.js

This PR adds the `allowed_domains_attribute` to the UI interface for CA type SSH roles only.

UI: add SSH role attribute `allowed_domains_template`

---

ui/lib/core/addon/components/json-editor.hbs

This PR fixes an issue with the `json-editor` toolbar scrolling unnecessarily off the page which was caused by some updates to the `is-label` class.
Before (copy icon is overflowing)
After

JSON Editor Toolbar Styling Fix 

---

changelog/22810.txt
changelog/23123.txt
ui/app/services/store.js

**Before bug fix:** <img width="1620" alt="Screenshot 2023-09-06 at 9 47 25 AM" src="https://github.com/hashicorp/vault/assets/30884335/c3179442-5b92-4b98-bf0a-87fccb38116d">
**After:** Fixes pki bug for filtering roles. 
This is the bugfix from https://github.com/hashicorp/vault/pull/22810.

UI: [VAULT-18178] Fix filter/search bug in search secrets engines

---

enos/modules/vault_cluster/scripts/enable_audit_logging.sh
enos/modules/vault_cluster/templates/install-packages.sh

Fix an issue where netcat would not be installed correctly with certain package managers. We also fix an issue where SSH cannot exit because nc is waitaing for SIGHUP, resulting in scenarios running forever.

test: fix netcat install and listen for socket audit device

---

changelog/23118.txt
helper/testhelpers/ldap/ldaphelper.go

This is causing nightly tests to fail on arm64 architecture with:
```
could not start local LDAP docker container: no port mapping found for 389/tcp
```
For now, we'll disable them again.

disable ldap tests for arm

---

enos/modules/vault_cluster/scripts/enable_audit_logging.sh

This PR adjusts the enable_audit_logging.sh script to ensure that the **enos_remote_exec** resource that invokes it using an SSH session isn't blocked indefinitely.
I've done some local testing of ssh behaviour when invoking a script that launches **nc** in the background and found that **nohup** didn't have any effect, neither did the redirecting stdin from _/dev/null_. It was redirecting both stdout and stderr to _/dev/null_ (`&> /dev/null`) that stopped the ssh session from being blocked even after the script was done executing.

Fix Enos Issues Relating to Vault Auditing

---

vault/seal_autoseal.go

This fixes a log message in the seal health check so that the fields match up and the downtime is reported correctly

Fix seal health check log message

---

enos/enos-globals.hcl
enos/modules/vault_cluster/scripts/enable_audit_logging.sh

Remove the hardcoded sleep in favor testing the listener before connecting. We also keep the listener running after the initial connection to support vault testing the socket and a service restart.

test: wait for nc to be listening before enabling auditor

---

command/agent_test.go
command/proxy_test.go

```
panic: Fail in goroutine after TestProxy_Config_ReloadTls has completed
goroutine 262000 [running]:
testing.(*common).Fail(0xc00abffa00)
/home/runner/actions-runner/_work/_tool/go/1.21.1/x64/src/testing/testing.go:952 +0xd4
testing.(*common).Errorf(0xc00abffa00, {0xa9c2b7a?, 0x121?}, {0xc00689bfc0?, 0xc00546b760?, 0x3e0cb25?})
/home/runner/actions-runner/_work/_tool/go/1.21.1/x64/src/testing/testing.go:1069 +0x5e
github.com/hashicorp/vault/command.TestProxy_Config_ReloadTls.func1()
/home/runner/actions-runner/_work/vault-enterprise/vault-enterprise/command/proxy_test.go:1179 +0x115
created by github.com/hashicorp/vault/command.TestProxy_Config_ReloadTls in goroutine 261997
/home/runner/actions-runner/_work/vault-enterprise/vault-enterprise/command/proxy_test.go:1176 +0xa1f
```

fix: Fail in goroutine after tests have completed

---

ui/app/components/mount-backend-form.js
ui/app/components/sidebar/nav/access.hbs
ui/tests/acceptance/access/methods-test.js

After the [upgrade to Ember 4.12, and specifically updating](https://github.com/hashicorp/vault/commit/8731cee07a0e3120fd7b45f7ee529d5f74c9a4b9#diff-0794c5a33b7a6bfb0e40beb904101eded845f9124dd00b3e39637d451c53d43aL37-L44) to use `rollbackAttributes` in the `mount-backend-form` component, there was an issue where navigating to mount an auth method and then moving to another route would cause the last method in the list to disappear when returning to the auth methods list view (see video). Since we are only dealing with new models here, exclusively using `unloadRecord` should be adequate and fixes the issue. I wasn't able to track down why `rollbackAttributes` was causing this to happen since it should do an `unloadRecord` behind the scenes for new models 🤷‍♂️. 
_Before_ …

Missing Auth Methods

---

ui/app/mixins/unsaved-model-route.js
ui/app/routes/vault/cluster/access/identity/aliases/add.js
ui/app/routes/vault/cluster/access/identity/aliases/edit.js
ui/app/routes/vault/cluster/access/identity/create.js
ui/app/routes/vault/cluster/access/identity/edit.js
ui/app/routes/vault/cluster/access/method/item/create.js
ui/app/routes/vault/cluster/access/method/item/edit.js
ui/app/routes/vault/cluster/policies/create.js
ui/app/routes/vault/cluster/secrets/backend/secret-edit.js
ui/lib/core/addon/decorators/confirm-leave.js

This PR fixes a unload error when using the `unsaved-model-route` -- it was rolling back changes and then triggering `unloadRecord` from the `unload-model-route` mixin, which seemed to cause issues. Simply rolling back the changes when leaving seems to work well and does not cause the issues we saw. 
Symptom of this problem: 
* Go to edit an existing item (for example, a KV V1 secret)
* Exit before saving eg. by clicking the breadcrumbs
* Go to list view for same type of item you were just editing
* Will see an extra item on the list, meaning the item that you attempted to edit did not get unloaded and got stuck in the cache.

UI: cleanup unload model logic

---

changelog/23166.txt
ui/lib/pki/addon/components/page/pki-configuration-details.hbs
ui/lib/pki/addon/routes/configuration/index.js
ui/lib/pki/addon/templates/configuration/index.hbs
ui/tests/integration/components/pki/page/pki-configuration-details-test.js

- Update the mount configuration details to look like the new configuration details

UI: [VAULT-17461] add mount configuration as toggle for pki

---

vault/logical_system_paths.go

As mentioned in https://github.com/hashicorp/vault-client-go/pull/188#issuecomment-1626167085, this will change the OpenAPI operation ID to `decode-token` and the corresponding generated method name to `DecodeToken(...)`.

Fix OpenAPI OperationID for sys/decode-token

---

vault/eventbus/bus.go

We're now generating 300MB log files for some test runs, making the UI difficult to use.  In one that I looked at, 80% of the lines in the file (450k/564k) were this one.

Remove an extremely noisy log line

---

website/content/docs/secrets/ldap.mdx

Change in vault mount in older versions, the new mount defaults to auth/ldap

Update ldap.mdx - auth/ path missing from commands

---

builtin/logical/database/backend_test.go
builtin/logical/database/path_config_connection_test.go
builtin/logical/database/path_roles_test.go
builtin/logical/database/rollback_test.go
builtin/logical/database/rotation_test.go
helper/testhelpers/postgresql/postgresqlhelper.go

We add a test to verify that failed rotations can successfully recover and that they do not occur outside of a rotation window. Additionally, we remove registering some external plugins in `getCluster()` that shaves off about 5 minutes from the database package tests.

secrets/db: add rotation error path test

---

vault/external_tests/api/kv_helpers_test.go
vault/external_tests/api/kv_test.go

This was causing a little bit of foot-gunning, so it seems best to remove the global client. The tests from the package all pass locally.

Remove global client assignment in KV tests

---

command/server.go
command/server_sealgenerationinfo_test.go
internalshared/configutil/kms.go
vault/seal/seal.go

- This fix addresses an issue that changing any seal configuration in an existing seal stanza such as the Vault token would fail the seal matching against an existing seal.
- If this was the only seal that was previously used or slight tweaks happened to all the seals Vault would fail to start with an error of
"must have at least one seal in common with the old generation."
- Also add a little more output to the validation error messages about the current seal and configured seal information to help in diagnosing errors in the future

Seal-HA: Match multiple seals using name/type only

---

command/server_sealgenerationinfo_test.go
vault/seal/seal.go

- Specifically callout during cluster initialization or initial beta seal migration that we can only have a single seal enabled with the following error message:
`Initializing a cluster or enabling multi-seal on an existing cluster must occur with a single seal before adding additional seals`
~- Handle the use case that we have multiple seals configured, but some are disabled, leaving a single enabled seal. This is the legacy seal migratation case that works without the BETA flag set, so should work with it set as well.~ Reverted after some internal discussions.

Provide a better error message around initializing with multiple seals

---

Dockerfile

Alpine 3.15 will be end-of-life on Nov 1 2023

Update Docker base image to Alpine 3.18

---

command/server.go

- Only enable the warning mode for seals being unavailable when multiple exist when running within multi-seal mode.
- This addresses a panic that occurs when a legacy style migration is attempted and the non-disabled seal is unavailable.
- The fix also reverts back some of the previous logic around ignoring KeyNotFoundErrors that was removed from within [#23192](https://github.com/hashicorp/vault/pull/23192/files#diff-de23c936a9ff46fc796a96721e088734a0d6281da4f7c0fe19c3ca6fc86c5dc4L2634-L2645) 
```
panic: runtime error: index out of range [0] with length 0
goroutine 1 [running]:
github.com/hashicorp/vault/vault.(*sealWrapMigration).Type(0xc002c852cc?, {0xc3aba50, 0x11f124a0})
/Users/sclark/git-repos/vault-enterprise/vault/sealwrap_sealmigration_ent.go:42 +0x7b …
```

Restore seal startup behavior when not in multi-seal mode

---

changelog/23232.txt
ui/lib/pki/addon/components/page/pki-tidy-status.hbs
ui/lib/pki/addon/components/page/pki-tidy-status.ts

Fixes duplicate `tidy_revocation_queue`  which should have been `tidy_revoked_certs` 
src="https://github.com/hashicorp/vault/assets/68122737/45c50f35-957c-4ccb-9def-d8b6ea43bed4">

UI: Adds tidy_revoked_certs and revoked_cert_deleted_count to PKI tidy status page 

---

sdk/logical/storage.go

This adds `AbortableScanView` to be able to use the passed-in function to abort the scan

Add AbortableScanView function

---

command/agentproxyshared/cache/cacheboltdb/bolt.go
command/agentproxyshared/cache/cachememdb/index.go
command/agentproxyshared/cache/cachememdb/index_test.go
command/agentproxyshared/cache/lease_cache.go
command/proxy.go
command/proxy/config/config.go
command/proxy_test.go

What this does:
If a new config value is set, then we cache all secrets as static secrets. We check new requests coming in to see if they can share the path. If they have demonstrated they can access this secret before, they'll receive the cached value.
This won't affect any old functionality, as it relies on the new config value being set to true. It's far from a complete solution, but I'd rather have 'smaller' PRs than a couple of thousand line monsters, for reviewers' sanity and also code quality purposes.
What's missing:
- The caching of a token's permissions
- This will come in the next PR
- The updating of a token's permissions via /sys/capabilities (via the jobmanager approach)
- This will come in a later PR and is part of a later ticket
- The updating (event system)
- This will …

VAULT-19233 First part of caching static secrets work

---

changelog/23215.txt
go.mod
go.sum
sdk/go.mod
sdk/go.sum
sdk/helper/pluginutil/run_config.go

Manual backport of #23215 after #23241 had conflicts in the go.sum files.

backport 1.15.x: Support mlock and custom tmpdir for containerized plugins (#23215)

---

changelog/23013.txt
helper/testhelpers/consul/cluster_storage.go
helper/testhelpers/consul/consulhelper.go
helper/testhelpers/teststorage/consul/consul.go
physical/consul/consul.go
physical/consul/consul_test.go
sdk/helper/testcluster/docker/environment.go
sdk/helper/testcluster/types.go
sdk/helper/testcluster/util.go
sdk/physical/physical.go
sdk/physical/testing.go
vault/external_tests/consul_fencing_binary/consul_fencing_test.go
vault/ha.go

This PR will add a test and then a fix for a correctness bug when using Consul as a HA backend.
This issue, while possible to hit in our Community Edition as shown by the test added, is much less likely to cause noticeable problem in CE. It could at worse cause a major failure - say if the mount table was simultaneously modified by two active nodes in the small window of time that they both thing they are active. Chances are, even if you do manage to hit this, you will only loose a handful of updates, and even then only if multiple clients are writing to the same keys at the same time.
The issue is much more pronounced in Vault Enterprise where the active node is responsible for managing replicated state and does so with use of an index that must remain perfectly consistent with the …

Prevent split-brain active node writes when using Consul

---

changelog/23260.txt
ui/lib/core/addon/components/download-button.js
ui/lib/core/addon/components/masked-input.hbs
ui/lib/core/addon/components/masked-input.js
ui/tests/index.html
ui/tests/integration/components/masked-input-test.js
ui/tests/pages/components/masked-input.js

In https://github.com/hashicorp/vault/pull/20431 we added the ability to download a secret value. To prevent accidentally downloading sensitive data, we've added a confirmation modal prompting users to cancel or proceed with the download. 
<hr>
🎥

UI: add warning before downloading secret data

---

website/content/docs/sync/azurekv.mdx
website/content/docs/sync/github.mdx
website/content/docs/sync/vercelproject.mdx

This PR updates the new secret sync docs (https://github.com/hashicorp/vault/pull/23189) to comply with styles for consistency:
🔍 [Deploy preview - Azure](https://vault-git-sync-docs-formats-hashicorp.vercel.app/vault/docs/sync/azurekv)
🔍 [Deploy preview - Github](https://vault-git-sync-docs-formats-hashicorp.vercel.app/vault/docs/sync/github)
🔍 [Deploy preview - Vercel](https://vault-git-sync-docs-formats-hashicorp.vercel.app/vault/docs/sync/vercelproject)

[Secret Sync Docs] Format & style

---

builtin/logical/pki/acme_state.go
builtin/logical/pki/backend.go

Missed this from #23278, we need to optionally close out the plugin if we aren't the active node.

Do not attempt to shutdown ACME thread on non-active nodes

---

changelog/23297.txt
ui/app/components/policy-form.hbs

Fixes regression caused by styling changes to `is-label`. Caught one of them in  https://github.com/hashicorp/vault/pull/23120 but missed this one. 
<hr>

UI: Policy JSON Editor Toolbar Styling Fix 

---

changelog/22996.txt
command/agentproxyshared/auth/azure/azure.go
command/agentproxyshared/auth/azure/azure_test.go

The Agent Injector doesn't support boolean literals, so the ability for us to convert string to bool makes things a lot easier to use.
The 1.15.1 milestone doesn't exist, but if it did, I'd put it on this PR.

Add support for true/false string literals for agent injector

---

.github/workflows/enos-lint.yml
enos/enos-samples-ce-build.hcl
enos/enos-samples-ce-release.hcl
enos/enos-scenario-upgrade.hcl

Remove the old initial versions as they are unreliable.

enos: remove old initial version from upgrades

---

ui/app/models/pki/urls.js

Fixes typo, backport(ish) of https://github.com/hashicorp/vault/pull/23316

Backport: Vault PKI: Fix typo OSCP -> OCS

---

enos/modules/vault_verify_performance_replication/scripts/verify-replication-status.sh

Increase the amount of time we'll wait for replication to sync from 30 seconds to 110. This ought to cover most cases where we fail twice because we're still waiting for replication.

replication: wait longer for replication to resync

---

ui/app/styles/core/element-styling.scss
ui/lib/core/addon/components/json-editor.hbs
ui/lib/core/addon/components/json-editor.js
ui/lib/core/addon/modifiers/code-mirror.js

Small changes to prepare for implementing the `<Hds::Modal>` component. 
Adds `@container` to the JsonEditor so copy buttons work inside modals, also moves overflow styling to `.body`
> ### Page scroll 
> When a Modal is open, the rest of the page is disabled (via inert). The page scrolling is also disabled by applying `overflow: hidden` to the `<body>` element, to make it clear to the user that the underlying elements are not interactive and to avoid confusion. Depending on users’ scroll bar settings, opening a Modal may cause slight layout shifts on the horizontal axis.[[docs](https://helios.hashicorp.design/components/modal?tab=code#page-scroll)]

U: preparation for HDS adoption to replace <Modal> 

---

website/content/docs/platform/k8s/index.mdx
website/content/docs/platform/k8s/vso/api-reference.mdx
website/content/docs/platform/k8s/vso/examples.mdx
website/content/docs/platform/k8s/vso/helm.mdx
website/content/docs/platform/k8s/vso/index.mdx
website/content/docs/platform/k8s/vso/installation.mdx
website/content/docs/platform/k8s/vso/sources/hvs.mdx
website/content/docs/platform/k8s/vso/sources/index.mdx
website/content/docs/platform/k8s/vso/sources/vault.mdx
website/content/partials/vso/blurb-api-reference.mdx
website/data/docs-nav-data.json

Doc updates are mostly focused on HCP Vault Secrets support.
I've added the concept of "secret sources", with each supported source having its own dedicated page. The VSO docs index now just provides a high level overview of VSO and links to its supported secret sources.

Update VSO docs for v0.3.0

---

website/content/docs/upgrading/upgrade-to-1.15.x.mdx
website/content/partials/known-issues/transit-managed-keys-panics.mdx
website/content/partials/known-issues/transit-managed-keys-sign-fails.mdx

We missed the window for the next releases for the transit managed key fixes so update the affected versions within the existing known issues.

Bump versions within transit managed key known issues

---

ui/app/components/database-connection.js
ui/app/components/policy-form.hbs
ui/app/styles/components/sidebar.scss
ui/app/styles/core/buttons.scss
ui/app/templates/components/clients/attribution.hbs
ui/app/templates/components/clients/config.hbs
ui/app/templates/components/database-connection.hbs
ui/app/templates/components/link-status.hbs
ui/app/templates/components/oidc/scope-form.hbs
ui/app/templates/components/transformation-edit.hbs
ui/lib/core/addon/components/policy-example.hbs
ui/lib/core/addon/components/search-select-with-modal.hbs
ui/tests/acceptance/secrets/backend/database/secret-test.js
ui/tests/integration/components/clients/attribution-test.js
ui/tests/integration/components/clients/config-test.js
ui/tests/integration/components/link-status-test.js
ui/tests/integration/components/oidc/scope-form-test.js
ui/tests/integration/components/search-select-with-modal-test.js
ui/tests/integration/components/sidebar/frame-test.js

🔄  Replaces modal in
- `policy-form.hbs`
- `clients/attribution.hbs`
- `clients/config.hbs`
- `database-connection.hbs`
- `link-status.hbs` * pending design questions with this one
- `scope-form.hbs`
- `transformation-edit.hbs`

UI: Part 1 - hds adoption replace <Modal>

---

website/content/docs/platform/k8s/index.mdx

https://developer.hashicorp.com/vault/docs/platform/k8s contained references to the Vault reference architecture for Kubernetes, however it looks like this has been [removed from tutorials](https://github.com/hashicorp/tutorials/pull/1617).
This PR removes the references to clear things up.
Vercel deployed page: https://vault-c150g3d53-hashicorp.vercel.app/vault/docs/platform/k8s

Kubernetes reference architecture link removal

---

website/content/docs/platform/k8s/index.mdx

https://developer.hashicorp.com/vault/docs/platform/k8s contained references to the Vault reference architecture for Kubernetes, however it looks like this has been https://github.com/hashicorp/tutorials/pull/1617.
This PR removes the references to clear things up.
Manually backported to `1.12.x` based on PR: https://github.com/hashicorp/vault/pull/23381

removed references to Vault reference architecture on Kubernetes

---

enos/enos-globals.hcl

An ongoing incident in us-east-1 is impacting CI. We'll temporarily use Ohio as it's cheaper than California.

test: don't use us-east-1 during an outage

---

enos/modules/vault_cluster/scripts/enable_audit_logging.sh

We occasionally see initial failures when waiting for the netcat listener to start for the vault socket auditor sink. This usually happens on RHEL but I haven't been able to figure out why. On the retry it always seems to work, which I assume is due to attempting to start the listener again. This adds a checks for the process in the retry loop and starts it again if we can't find it.

test: restart socket sink if it's not listening

---

ui/app/templates/components/transit-key-action/datakey.hbs
ui/app/templates/components/transit-key-action/decrypt.hbs
ui/app/templates/components/transit-key-action/encrypt.hbs
ui/app/templates/components/transit-key-action/export.hbs
ui/app/templates/components/transit-key-action/hmac.hbs
ui/app/templates/components/transit-key-action/rewrap.hbs
ui/app/templates/components/transit-key-action/sign.hbs
ui/app/templates/components/transit-key-action/verify.hbs
ui/package.json
ui/tests/acceptance/transit-test.js
ui/tests/integration/components/transit-key-actions-test.js
ui/yarn.lock

UI: Part 2 - hds adoption replace <Modal> 

---

website/content/api-docs/auth/saml.mdx

This PR adds API documentation for the `verbose_logging` option in the SAML auth method configuration.

auth/saml: adds API docs for verbose_logging config

---

ui/app/styles/components/masked-input.scss
ui/app/styles/core/buttons.scss
ui/app/templates/components/link-status.hbs
ui/app/templates/vault/cluster/init.hbs
ui/app/templates/vault/cluster/policy/show.hbs
ui/lib/core/addon/components/download-button.hbs
ui/lib/core/addon/components/download-button.js
ui/lib/core/addon/components/info-table-row.hbs
ui/lib/core/addon/components/masked-input.hbs
ui/lib/kmip/addon/templates/configuration.hbs
ui/lib/pki/addon/components/page/pki-issuer-details.hbs
ui/lib/pki/addon/components/page/pki-issuer-rotate-root.hbs
ui/lib/pki/addon/components/page/pki-key-details.hbs
ui/lib/pki/addon/components/page/pki-key-list.hbs
ui/tests/integration/components/download-button-test.js

The modal in `MaskedInput` includes a `DownloaButton` so I opted to go ahead and implement `<Hds::Button>` there instead of wrangle CSS to accommodate me 😅

UI: Part 3 - hds adoption replace <Modal>

---

changelog/23446.txt
ui/app/services/path-help.js

This UI only regression bug was potentially introduced by this [PR](https://github.com/hashicorp/vault/pull/21723). 
The reproduction steps of how the bug was reported:
1. on a binary
2. Create a namespace
3. Within the namespace mount the auth method userpass.
4. Create a user userpass and navigate to the list view. No users would show and there was a 301 followed by a 404 error on the network request on this LIST endpoint. if you look closely, you'll see a double forward slash. 
`http://localhost:4200/v1/auth/userpass/users//?list=true`
This fix cleans out the double forward slash and resolves the issue. The `sanitizePath` method removes any whitespace and trailing and leading slashes.
TODO:
- test to make sure doesn't break anything ✅
- run enterprise tests locally. ✅

Bug fix for double slash in LIST endpoint

---

.github/workflows/ci.yml

In #22817, we've introduced a CI bug where we started checking out the `github.base_ref` instead of the `github.ref`, which meant the tests were running against the target branch of the pull request, so not testing the changes.
From the docs: https://docs.github.com/en/actions/learn-github-actions/contexts
`github.base_ref`  
The base_ref or target branch of the pull request in a workflow run. This property is only available when the event that triggers a workflow run is either pull_request or pull_request_target.
`github.ref`
The fully-formed ref of the branch or tag that triggered the workflow run. For workflows triggered by push, this is the branch or tag ref that was pushed. For workflows triggered by pull_request, this is the pull request merge branch.

[VAULT-20630] CI: Fix the CI workflow issue where we check out base ref instead of the ref that triggered the workflow run

---

.github/workflows/ci.yml
.github/workflows/test-go.yml

A companion PR to #23453. 
This one changes the default value of the `checkout-ref` input in the test-go.yml workflow (from `github.base_ref` to `github.ref`). Currently, nothing (that I am aware of) uses that default, but it could bite us in the future.

[VAULT-20630] CI: Use 'ref' (not 'base_ref') as a default git reference to check out code in the test-go GHA workflow

---

website/content/docs/platform/k8s/vso/sources/hvs.mdx

PR adds a link to https://developer.hashicorp.com/vault/tutorials/hcp-vault-secrets-get-started/kubernetes-vso.

docs: link to the VSO+HVS quick-start tutorial

---

ui/app/styles/core/buttons.scss
ui/app/styles/core/element-styling.scss
ui/lib/core/addon/helpers/message-types.js
ui/lib/kubernetes/addon/components/page/configure.hbs
ui/lib/kv/addon/components/kv-delete-modal.hbs
ui/lib/kv/addon/components/kv-delete-modal.js
ui/lib/kv/addon/components/page/secret/details.hbs
ui/lib/kv/addon/components/page/secret/metadata/details.hbs
ui/lib/ldap/addon/components/accounts-checked-out.hbs
ui/lib/ldap/addon/components/page/configure.hbs
ui/lib/ldap/addon/components/page/library/details/accounts.hbs
ui/lib/pki/addon/components/page/pki-issuer-details.hbs
ui/lib/pki/addon/components/page/pki-tidy-status.hbs

Replaces modals in ember engines

UI: Part 4 - hds adoption replace <Modal> 

---

changelog/23470.txt
ui/app/models/role-aws.js
ui/lib/core/addon/helpers/jsonify.js

This fixes a regression caused by a PR [here](https://github.com/hashicorp/vault/pull/19117/files#diff-21e5ef7b872398bce34be2638fe826222f894d722d838292c289ca95a9a10508R52) that fixed a larger issue.
AWS is a unique case where we can't default the json form field to an empty object. A user needs to return nothing if no `policy_document` is added.
**With the fix:**
https://github.com/hashicorp/vault/assets/6618863/b0ef6e6d-9cf5-43a8-882b-6d503627d34d

Allow AWS secret engine to send empty policy document

---

.github/workflows/test-run-enos-scenario-matrix.yml
enos/enos-scenario-replication.hcl
enos/modules/vault_get_cluster_ips/scripts/get-follower-private-ips.sh

Sometimes destroying resources in AWS will fail because of unexpected dependency violations or other such nonsense. When this happens the behavior of Vault that we wanted to verify has already been successfully accomplished, however the required workflow will fail. This change allows us to succeed if `enos scenario launch` completes but allows `enos scenario destroy` to fail. We still notify our slack channel on destroy failures so that we can investigate issues, however it won't require a PR author to retry.
* Execute `enos scenario launch` instead of `enos scenario run` to allow for very occasional issues when tearing down test infrastructure.
* Improve an error message when getting secondary cluster IP addresses.
* Don't race to get secondary cluster IP addresses.
* Add secondary token …

[QT-602] Don't fail if scenarios cannot completely destroy infra

---

.github/workflows/test-go.yml

The goal is to avoid overwhelming the GHA UI with excessive log lines, so we can see failures without having to download logs.

Set VAULT_TEST_LOG_DIR, logs from NewTestLogger will be written there

---

.github/workflows/enos-lint.yml
.github/workflows/enos-run-k8s.yml
.github/workflows/test-enos-scenario-ui.yml
.github/workflows/test-run-enos-scenario-matrix.yml

Terraform 1.6.x seems to have some incompatiblity with the current version fo enos and its usage of tfjson. Pin to 1.5.x until it has been resolved.
```
│ Error: json: cannot unmarshal array into Go struct field rawState.checks of type tfjson.CheckResultStatic
│
```

[QT-623] Pin to terraform 1.5.x

---

changelog/23516.txt
ui/app/templates/vault/cluster/policies/error.hbs

This PR adds an error route for policies to allow for the policy navigation links to show if the route transition errors. Interestingly enough the error was bubbling up to the `cluster.error` route which I would expect that the cluster navigation links would display but for some reason no links were rendering.
In any case we want the policy links to render in the case of an error so adding the error route template was necessary.

Policies Error Route

---

command/command_stubs_oss.go
command/commands.go
command/server.go
command/server/config.go
command/server/server_stubs_oss.go
command/server_util.go

After this change lands on ent, I will create an ent PR that renames the ent funcs currently being assigned in init blocks.   For example instead of doing `initCommandsEnt = initCommandsEntImpl` in an init func, I'll rename initCommandsEntImpl to be entInitCommands.  This will break ent, unfortunately, because the CE files will still be invoking initCommandsEnt - things will still compile, but tests are likely to break and the binary won't behave correctly.
Finally, once that ent PR merges, the last step will be to create another CE PR that gets rid of the current var hooks and replaces references to them with the new stubmaker funcs.
To minimize the ent breakage, ideally I'd do all of the stubs at once, but I want to validate the process at a smaller scale before I invest too much time.

Start process of replacing init-style ent hooks with stubmaker

---

helper/testhelpers/teststorage/teststorage.go

Fix for enterprise failures when we don't have `DefaultHandlerProperties -> ListenerConfig` initialized in `ClusterSetup`
Related to: https://github.com/hashicorp/vault/pull/23534

Fix for failing enterprise test

---

helper/builtinplugins/registry.go
helper/builtinplugins/registry_stubs_oss.go
http/util.go
http/util_stubs_oss.go
vault/core.go
vault/core_stubs_oss.go
vault/init.go
vault/request_handling.go

See https://github.com/hashicorp/vault/pull/23545 for background on strategy.  I was a little more ambitious this time: funcs which took Core as a first argument are now Core methods instead.  In some cases I renamed funcs to ensure that I didn't collide with existing ent func names, or for consistency.  I've decided that it's desirable to use `ent` or `Ent` as a prefix to these methods that are called (as stubs) from CE code but do something more in the Ent repo.  It helps to draw attention to the fact that these funcs are special, and that if you're modifying code using them in CE, you should probably be testing in Ent.

Define a bunch of stubs that will replace existing init hooks.

---

ui/app/components/sidebar/user-menu.hbs

This is more or less a manual backport but with changes because we don't have the HDS copy button in 1.15. See original PR [here](https://github.com/hashicorp/vault/pull/23331).

Fix copy button in collapsed sidebar nav in CopyButton component

---

changelog/23470.txt
ui/app/helpers/jsonify.js
ui/app/models/role-aws.js

Manual Backport of [PR](https://github.com/hashicorp/vault/pull/23470)

Backport 1.14.1x: Allow AWS secret engine to send empty policy document (#23470)

---

api/sys_seal.go
changelog/23022.txt
command/format.go
command/format_test.go
vault/logical_system.go

And at the same time add a RecoverySealType to the response which preserves the old meaning.
Updated the CLI to display both when relevant.

Correct the post-unseal meaning of the seal status type

---

website/content/docs/configuration/listener/index.mdx

Documentation for per-listener redaction configuration (https://github.com/hashicorp/vault/pull/23534)
Deployed page: https://vault-git-docs-peteski22vault-19863listener-re-abd165-hashicorp.vercel.app/vault/docs/configuration/listener

documentation for redaction configuration on listeners

---

website/content/api-docs/system/config-state.mdx

Remove asterixes in header to keep formatting uniform across the docs.

Remove asterixes in header

---

website/content/api-docs/secret/kv/kv-v2.mdx

Fix `Path` value for `Delete metadata and all versions` - use template `:secret-mount-path` instead of `secret`.

Fix path for Delete metadata and all versions

---

website/content/api-docs/auth/jwt.mdx

Read config is the 1st level header (single `#`). This does not generate an in-page link for the header.
The PR moves the header to the second level, so link is generated and header is the same level as other headers.

Fix Read config header level

---

ui/tests/integration/components/dashboard/overview-test.js

Fixes failing dashboard tests. Remove replication tests since we have acceptance tests for these in https://github.com/hashicorp/vault/pull/23452. 
This backport is for https://github.com/hashicorp/vault/pull/23452

Backport 1.15.x: Fix failing dashboard tests

---

vault/logical_system_user_lockout.go

This PR fixes a panic when attempting to unlock an already unlocked user.
Example Panic: 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x380c80a]
goroutine 147274 [running]:
github.com/hashicorp/vault/vault.unlockUser({0xa434c80, 0xc00fa6aeb0}, 0xc00ef26900, {0xc00e8cfb11, 0x16}, {0xc00e8cfb2f, 0x6})
/home/runner/actions-runner/_work/vault-enterprise/vault-enterprise/vault/logical_system_user_lockout.go:61 +0x28a
github.com/hashicorp/vault/vault.(*SystemBackend).handleUnlockUser(0xc005b7e740, {0xa434c80, 0xc00fa6aeb0}, 0x0?, 0xffffffffffffffff?)
/home/runner/actions-runner/_work/vault-enterprise/vault-enterprise/vault/logical_system.go:2492 +0x27b …
```

Fix panic when unlocking unlocked user

---

website/content/docs/release-notes/1.15.0.mdx
website/content/docs/upgrading/upgrade-to-1.15.x.mdx
website/content/partials/known-issues/1_15-audit-file-sighup-does-not-trigger-reload.mdx

Documentation to describe a known issue which has been reported where Vault file audit devices do no honor reopening after Vault processes a `SIGHUP` command. 
PR: https://github.com/hashicorp/vault/pull/23598
Issue: https://github.com/hashicorp/vault/issues/23596
Release notes: https://vault-git-docs-peteski22audit-file-sighup-issue-hashicorp.vercel.app/vault/docs/release-notes/1.15.0
Upgrade guide: https://vault-git-docs-peteski22audit-file-sighup-issue-hashicorp.vercel.app/vault/docs/upgrading/upgrade-to-1.15.x#file-audit-devices-do-not-honor-sighup-signal-to-reload

Docs: known issue - audit file reload on SIGHUP

---

.github/scripts/verify_changes.sh
.github/workflows/security-scan.yml
.github/workflows/test-go.yml
builtin/audit/file/backend.go
builtin/logical/aws/path_static_roles.go
builtin/logical/aws/path_static_roles_test.go
changelog/23528.txt
changelog/23547.txt
changelog/23565.txt
changelog/23598.txt
command/server.go
command/server/config_test_helpers.go
command/server/listener.go
http/handler.go
http/util.go
internalshared/configutil/config.go
internalshared/configutil/listener.go
internalshared/configutil/listener_test.go
ui/app/components/auth-form.js
vault/audit_broker.go
vault/logical_system_user_lockout.go
website/content/api-docs/secret/aws.mdx
website/content/docs/configuration/listener/tcp.mdx

This PR adds the ability to parse a configuration setting in the TCP listener configuration section so that the value can be stored in the http.Request context. This will allow the enterprise version implementation of the replication status endpoints:
- `sys/replication/status`
- `sys/replication/dr/status`
- `sys/replication/performance/status`
to react accordingly.

Add Ability to Disable Replication Status Endpoints in Listener Configuration

---

website/content/api-docs/system/internal-counters.mdx

`Read the client count configuration` misses HTTP verb and endpoint path.
This PR fixes this.

Add method and path for Read the client count configuration

---

changelog/23140.txt
command/server.go
command/server/config_test_helpers.go
http/sys_config_state_test.go
internalshared/configutil/config.go
internalshared/configutil/merge.go
vault/core.go
vault/logical_system_user_lockout.go
vault/request_handling.go

Backporting #23140 and #23611 to 1.14.x release branch

Backport of Implement user lockout log into release/1.14.x

---

changelog/23636.txt
command/server.go

I forgot to close the file when generating pprof files using SIGUSR2.

command/server: fix bug with sigusr2 where pprof files were not closed

---

website/content/partials/kubernetes-supported-versions.mdx

Dropping 1.23 since 1.24 is the oldest supported by the cloud providers ([EKS](https://endoflife.date/amazon-eks), [GKE](https://endoflife.date/google-kubernetes-engine), [AKS](https://endoflife.date/azure-kubernetes-service)), and 1.28 is the latest release.
Related to https://github.com/hashicorp/vault-plugin-auth-kubernetes/pull/212

docs/k8s-versions: updating supported k8s versions

---

command/server.go
helper/builtinplugins/registry.go
http/handler.go
http/logical.go
http/sys_health.go
vault/core.go
vault/dynamic_system_view.go
vault/init.go
vault/logical_system.go
vault/logical_system_raft.go
vault/raft.go
vault/request_forwarding.go
vault/request_forwarding_rpc.go
vault/request_handling.go

This continues on the work from https://github.com/hashicorp/vault-enterprise/pull/4825.  After this lands in Ent, we can start getting rid of the hooks.

Step 3 of part 3 of removing ent init hooks: call stubs instead of var func hooks

---

helper/forwarding/util.go
http/handler.go
http/util.go
sdk/logical/request.go
vault/cluster_test.go
vault/request_forwarding.go

This PR introduces a required change and some code clean up changes. The changes have been isolated into specific commits and the description below references the specific commits along with explaining the changes. Each commit can be reviewed independently by clicking the commit hash in this description.
The primary change consists of introducing a custom type to be used as the key when setting a value in the context to propagate the **disable_replication_status_endpoints** throughout the request handling chain and making use of that custom type instead of the hard coded string that the custom type replaces - f07b711
In addition to the primary change, some code clean up changes were also made.
This change removes an unnecessary if condition to check if `origBody` is nil because it is …

VAULT-19869: Use Custom Types for Context Keys

---

vault/request_handling.go

This PR makes a necessary change missed in a previous PR to copy the **logical.CtxKeyDisableReplicationStatusEndpoints** value from the **context.Context** of the **http.Request** to the active **context.Context** maintained by the instance of **vault.Core** at the point where we switch **context.Context**.
This is necessary because when the request handling chains are constructed, a middleware function that _adds_ the **logical.CtxKeyDisableReplicationStatusEndpoints** value to the context is used if the **disable_replication_status_endpoints** configuration parameter is set to `true` for the TCP listener in question. However, in order for this context value to make it all the way to the actual handler functions, which receive the **vault.Core**'s active context, not the **http.Request** …

VAULT-19869: Copy disable_replication_status_endpoints value to Active Context

---

helper/builtinplugins/registry.go

I've broken many tests on ent that relied on a broken behaviour.  I'll fix them properly later, for now I want to unbreak the build.

For now, go back to the hook approach for addExternalPlugins. 

---

vault/auth.go
vault/core.go
vault/core_test.go
vault/core_util.go
vault/logical_system.go
vault/mount.go
vault/mount_util.go
vault/plugin_reload.go
vault/router.go
vault/token_store.go
vault/token_store_test.go

Tech debt ticket.
Cyclomatic complexity: `gocyclo vault/core.go | grep NewCore`
Before:`29`
After: `20`
Split out `NewCore` into more testable receivers, some other refactoring work for naming and moving from funcs to receivers.
`gocyclo vault/core.go | grep configure`:
```
(*Core).configureLogicalBackends: 4
(*Core).configureLogRequestLevel: 4
(*Core).configureListeners: 3
(*Core).configureCredentialsBackends: 2
(*Core).configureAuditBackends: 2
```
Ent PR: https://github.com/hashicorp/vault-enterprise/pull/4824
One for later (TODO): Review the way we handle this shared state on reload funcs for config + core.

VAULT-20476: vault.NewCore refactor.

---

changelog/23573.txt
vault/seal_autoseal.go

Fixes an error when going from single to multiple auto seals of the same
type

Allow multiseal to mismatch stored conf type

---

ui/lib/core/addon/helpers/doc-link.js
ui/lib/core/app/helpers/doc-link.js

Template helper to assist migration to using HDS components with a `@href` arg
Example use: 
```js
<Hds::Button
@text="Learn more"
@icon="docs-link"
@isHrefExternal={{true}}
@href={{doc-link "/vault/tutorials/getting-started-ui)"}}
/>
```
```js
<Hds::Link::Standalone @icon="film" @text="Watch tutorial video" @href={{doc-link "/some-path"}} />
```
It also throws an error if the path arg does not begin with a forward slash `/`

ui: doc-link helper

---

ui/app/helpers/decode-uri.js
ui/app/templates/components/database-connection.hbs
ui/tests/acceptance/secrets/backend/database/secret-test.js

`connection_url` was being displayed with encoded characters. I added a `decode_uri` helper to decode_uri's in templates. 
Bug:
After decoding:

UI: [VAULT-20186] decode uri for all attributes in the table

---

Makefile

Hopefully this helps avoid problems like https://github.com/hashicorp/vault/issues/23544

require minimum go version for bootstrapping

---

changelog/23702.txt
ui/lib/core/addon/components/kv-object-editor.hbs
ui/lib/core/addon/components/kv-object-editor.js
ui/tests/integration/components/kv-object-editor-test.js

This PR adds a warning when whitespace is detected in a key of a KV engine secret.
Closes #6714

KV Key Whitespace Warning

---

helper/forwarding/util.go
http/handler.go
http/util.go
sdk/database/dbplugin/v5/plugin_client_test.go
sdk/logical/request.go
sdk/logical/request_test.go
vault/cluster_test.go
vault/request_forwarding.go
vault/request_handling.go

This PR makes recently introduced types used as keys for Context values no longer exported and instead introduce functions to read the corresponding value from a Context and to create a Context with the corresponding value.
The reasoning for this change is that with the previous approach, there was considerable metaphorical distance between when a Context was created with a value and where it was being read. This was problematic, since Context values are read as the `any` type and then must be cast to the type that was used to create the Context with the value. Since the code that creates the Context and the one that reads it are often in disparate regions of the code base, it's easy to introduce mistakes that are difficult to find.
By making the custom types …

Improve Robustness of Custom Context Values Types

---

website/content/docs/agent-and-proxy/proxy/apiproxy.mdx

I noticed these typos when referencing these docs in a discussion today.

Fix docs Agent -> Proxy

---

changelog/23726.txt
ui/app/components/dashboard/vault-configuration-details-card.js
ui/app/templates/components/dashboard/vault-configuration-details-card.hbs
ui/tests/acceptance/dashboard-test.js

The TLS field of the configuration details section on the dashboard was not displaying accurately based on the configuration settings. Since the `tls_disable` default value is `false`, it doesn't need to be defined and could be missing from the configuration. In addition, when using TLS the `tls_cert_file` and `tls_key_file` values are required. I updated to check that `tls_disable` is either `undefined` or `false` and both file properties have value to determine if TLS is enabled.
The screen shot below is after the changes with the following config:
```hcl
api_addr = "https://127.0.0.1:8200"
disable_mlock = true
listener "tcp" {
address = "127.0.0.1:8200"
tls_cert_file = "./certs/vault-cert.pem"
tls_key_file = "./certs/vault-key.pem"
}
storage "inmem" {}
```
I also noticed when running a …

Dashboard TLS Configuration Details Bug

---

.github/workflows/build.yml

This will mean we can see, at a glance, if it's an enos failure or a build failure. I kept it very tight instead of making it one line per type of enos/build failure.
The linting failure is unrelated to this change.
These builds don't actually run on branches, but I still feel like my branch's test is good enough. See #test-vault-ci-integration for details.

VAULT-20487 update build failure slack output

---

vault/logical_system.go
vault/logical_system_helpers.go

Vault Enterprise needs to execute some clean-up code to close some metrics-gathering background jobs that do not exist on the community version. This PR adds a stub similar to `InitializeFunc` or `Invalidate` so it can overridden by the ENT codebase.
We plan to backport this change so it is available on the 1.15.1 release.

Added clean function stub so it can be used in Vault ENT

---

website/content/docs/concepts/client-count/index.mdx

Received feedback that it wasn't clear what we were considering as certificate identifiers within the ACME client counting section.

Specify within ACME client counting what are the certificate identifiers

---

builtin/logical/transit/backend.go
builtin/logical/transit/path_datakey.go
builtin/logical/transit/path_keys_config.go
changelog/23723.txt

- Prevent and guard against auto-rotating managed keys as we generate an invalid key version without the UUID field set.
- Hook in the datakey generation api into managed key encryption.
- Tests will come within a seperate enterprise PR

Forbid setting auto_rotate_period on transit managed keys

---

vault/logical_system.go

Quick bug fix, ensure we handle any errors returned by `SetRotationConfig` when attempting to update the key rotation configuration.
https://developer.hashicorp.com/vault/api-docs/system/rotate-config#create-or-update-the-auto-rotation-configuration

Bug: handle error on updating rotation config (/sys/rotate/config)

---

api/plugin_helpers.go
changelog/23549.txt

If Vault is running in an ephemeral environment where nodes are often replaced and are randomly assigned IP addresses, it can be difficult to have IP SANs in server certs. By adding a TLS server name configurable we allow operators to register a plugin and specify the acceptable SAN for TLS verification.

api/plugins: add tls-server-name arg for plugin registration

---

changelog/23140.txt
command/server.go
command/server/config_test_helpers.go
http/sys_config_state_test.go
internalshared/configutil/config.go
internalshared/configutil/merge.go
vault/core.go
vault/logical_system_user_lockout.go
vault/request_handling.go

This reverts commit 8f70fb907458ae0325191deba35b476e1a4bc33f.

Backport Revert "Implement user lockout log (#23140)" 1.13.x

---

changelog/23747.txt
ui/lib/core/addon/components/masked-input.hbs
ui/lib/core/addon/components/masked-input.js
ui/tests/integration/components/masked-input-test.js

Backport KV Download Value Stringify Toggle (#23747) to 1.14

---

changelog/23771.txt
sdk/plugin/serve.go

This fixes an issue where external plugins were not reporting logs below INFO level.

plugins: allow all log levels for external plugins

---

changelog/23702.txt
ui/lib/core/addon/components/kv-object-editor.hbs
ui/lib/core/addon/components/kv-object-editor.js
ui/tests/integration/components/kv-object-editor-test.js

Backports KV Key Whitespace Warning (#23702) to 1.15

---

.github/workflows/copywrite.yml

Apply only to PRs, and to pushes to our main and release branches.

Use the same approach for copywrite checks as we do in our other workflows

---

builtin/credential/approle/path_login.go
builtin/credential/approle/path_login_test.go
changelog/23786.txt

Addresses https://hashicorp.atlassian.net/browse/VAULT-20374

Normalize error response messages when invalid credentials are provided

---

ui/tests/acceptance/policies/index-test.js

A policies test was failing consistently when running the full test suite on enterprise. It looks like after updating the pagination controls to HDS the previous fix was no longer working. I updated the test to use the search filter to find the policies to ensure that if they exist they will be rendered on the page. All tests are now passing on enterprise when running locally.

Flaky Policies Test

---

builtin/logical/pkiext/pkiext_binary/acme_test.go

- Try to avoid these build failures as our proxy does seem to have issues around pulling images with the 'latest' tag at times.
```
acme_test.go:206:
Error Trace:	/home/runner/actions-runner/_work/vault-enterprise/vault-enterprise/builtin/logical/pkiext/pkiext_binary/acme_test.go:206
/home/runner/actions-runner/_work/vault-enterprise/vault-enterprise/builtin/logical/pkiext/pkiext_binary/acme_test.go:75
Error:      	Received unexpected error:
container create failed: Error response from daemon: No such image: docker.mirror.hashicorp.services/curlimages/curl:latest
Test:       	Test_ACME/group/caddy_http_eab
Messages:   	could not start cURL container
```

Pin curl docker image to a specific version instead of latest

---

website/content/docs/platform/k8s/helm/configuration.mdx

This PR fixes the reported docs link issue --> [Slack thread](https://hashicorp.slack.com/archives/C012RTGJR1V/p1698201257328469)
I couldn't find any docs for `ResourceRequirement`, so it looks like the suggested [Resource Management for Pods and Containers](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/) is the correct reference to link to. And change `ResourceRequirement` to just `resource`?
🔍 [Deploy preview](https://vault-git-docs-fix-k8s-resource-link-hashicorp.vercel.app/vault/docs/platform/k8s/helm/configuration#resources)

[Docs] Fix reported link issue

---

website/content/docs/secrets/mongodbatlas.mdx

Update link format to MongoDB Atlas database secrets engine
Backport to 1.15 and 1.14 only as the note does not exist in 1.13 or earlier

Update link for MongoDB Atlas database secrets engine

---

command/agentproxyshared/cache/cacheboltdb/bolt.go
command/agentproxyshared/cache/cacheboltdb/bolt_test.go
command/agentproxyshared/cache/cachememdb/cache_memdb.go
command/agentproxyshared/cache/cachememdb/cache_memdb_test.go
command/agentproxyshared/cache/cachememdb/index.go
command/agentproxyshared/cache/lease_cache.go
command/agentproxyshared/cache/static_secret_capability_manager.go
command/agentproxyshared/cache/static_secret_capability_manager_test.go
command/proxy.go
command/proxy/config/config.go
command/proxy/config/config_test.go
command/proxy/config/test-fixtures/config-cache-static-secret-cache.hcl
command/proxy_test.go

This subsystem manages the capabilities of tokens that have been used in static secret caching by sending a job to the queue every duration `d` that will check if the capabilities are the same, and if not, update. I tried to leave good godocs where I could.
This docs page might be useful pre-reading if you're unfamiliar with the capabilities API: https://developer.hashicorp.com/vault/api-docs/system/capabilities-self
The most likely happy path through this subsystem will be during token expiry, in which situation we evict the capabilities index and update all related path indexes. However, it fully supports updated permissions, too.
We use `gammazero/workerpool` as it's a good fit for the problem, as well as having usage elsewhere in Vault.
There were some bugs related to restoring from …

VAULT-19232 Add static secret capability manager to Vault Proxy

---

website/content/api-docs/secret/pki.mdx

This replaces quotes with backticks in the documentation.

Fix backticks for cluster_aia_path

---

changelog/23849.txt
go.mod
go.sum

This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/6654356604

Update hashicorp/vault-plugin-secrets-mongodbatlas to v0.10.2

---

website/content/api-docs/secret/transit.mdx

Document that sign/verify work across all managed key types and encryption/decryption only for PKCS#11 at this time.

Update specifics around managed keys support in Transit

---

ui/tests/acceptance/enterprise-namespaces-test.js

This is an attempt at fixing a flaky namespace test. I got it to fail locally once, at which point I made some changes and wasn't able to get it to fail again. Not to say that it won't but these changes don't appear to have made it worse.
I was able to get it to fail when running in isolation so after the changes I ran the test within a loop where I would repeatable run it hundreds of times, restarting the server occasionally just to see if that would make a difference. Hopefully this will help and it will pass reliably.

Flaky Namespace Test

---

.github/workflows/security-scan.yml

Temporary fix due to incompatibility in new version of semgrep.

fix security-scanner: temporarily pin semgrep to 1.45.0

---

changelog/23861.txt
command/server.go
http/sys_seal.go
vault/core.go
vault/core_test.go
vault/hcp_link/capabilities/node_status/node_status.go
vault/hcp_link/internal/wrapped_hcpLink.go
vault/init.go
vault/logical_system.go

PR https://github.com/hashicorp/vault/pull/10725 introduced a change to support namespaces in vault status requests but introduced a deadlock on calls to `sys/seal-status` when namespaces are included.
When requests have a namespace configured the handler routes the request through `switchedLockHandleRequest` and holds the read statelock for the duration of the request: https://github.com/hashicorp/vault/blob/550c99ae3b6553f12e4a862c915155b8d0a53516/vault/request_handling.go#L530-L533.
I've added a locking arg so the caller can decide if the statelock needs to be grabbed or not.

api/seal-status: fix deadlock when namespace is set on seal-status calls

---

version/version_test.go

This PR fixes a test that is passing when run in this repository but is failing when run from the enterprise edition repository.
This fix consists of making sure that the VersionMetadata field is properly set and reset during the test, because in this repository, that variable is not set to any value by the compiler, but in the enterprise repository that's not the case.

Fix Broken Test When VersionMetadata is Set by Compiler

---

ui/tests/acceptance/enterprise-namespaces-test.js

This reverts commit 0e3697382589aa89392f6cc225595ca846bfa9b2 and skips the test for now since it is not reliably passing. See #23867 for original fix attempt but the tests are still failing in CI.

Revert Namespace Test Fix Attempt 

---

changelog/23802.txt
vault/logical_system.go

Addresses https://hashicorp.atlassian.net/browse/VAULT-21207
Reading an "auth" mount using "sys/internal/ui/mounts/" when filter paths are enforced returns 500 error code from the secondary:
```
failed to read a mount point in allow mode, Error making API request.
URL: GET https://127.0.0.1:49227/v1/sys/internal/ui/mounts/auth/d0681fa6-a5be-4d7e-8c38-c443325bb3ee
Code: 500. Errors:
* unable to retrieve route entry for mount path
```

fix a bug reading auth mount using sys/internal/ui/mount endpoint when filter paths are enforced

---

changelog/23902.txt
vault/core.go
vault/core_test.go
vault/expiration.go
vault/quotas/quotas.go
vault/quotas/quotas_rate_limit_test.go
vault/quotas/quotas_test.go
vault/testing.go
website/content/docs/configuration/index.mdx

PR #18604 introduced a bug where deadlock detection was always on for both expiration and quota subsystems. This can result in negative server performance as deadlock detection adds overhead to locks.
Deadlock detection can now be toggled on expiration and quotas via `detect_deadlocks="statelock,expiration,quotas"`.

core: fix bug where deadlock detection was always on for expiration and quotas

---

ui/tests/acceptance/enterprise-control-groups-test.js

There was an enterprise control group test failing pretty regularly with the following error:
I was able to recreate locally by skipping the other tests in the module and running it in a loop where it failed at least once each time I ran it.
```js
let i = 0;
while (i < 50) {
test('for v2 secrets it redirects you if you try to navigate to a Control Group restricted path', async function (assert) {
// setup, actions and assertions
});
i++;
}
```
Since the test was being torn down (and by extension the store) before the capabilities request resolved, I added `settled` at the end of the test which seems to have fixed the problem. The test should now wait for pending request to finish before tearing down. I bumped the loop to 500 to verify the fix and all tests passed.

Flaky Enterprise Control Group Test Fix

---

changelog/23894.txt
vault/request_handling.go

This PR skips the unnecessary deriving of policies from a fetched entity. The returned policies are ignored so we can safely skip doing the work here.

Skip unnecessary deriving of policies from entity on Login MFA check

---

go.mod
go.sum
http/handler.go

The github.com/nytimes/gziphandler package appears to no longer be maintained. The github.com/klauspost/compress/gzhttp package is an actively maintained fork of the former.

VAULT-19328: Replace nytimes/gziphandler With klauspost/compress/gzhttp

---

enos/enos-modules.hcl
enos/enos-scenario-seal-ha.hcl
enos/modules/start_vault/main.tf
enos/modules/start_vault/variables.tf
enos/modules/verify_seal_type/main.tf
enos/modules/verify_seal_type/scripts/verify-seal-type.sh

Test seal migration in the `seal_ha` scenario by removing the primary seal, waiting for seal rewrap to complete, and verifying data written only through the primary seal. We also add a verification for the seal type at various stages of the scenario.
* Allow configuring the seal alias and priority in the `start_vault` module.
* Add seal migration to `seal_ha` scenario.
* Verify the data written through the original primary seal after the seal migration.
* [QT-629] Verify the seal type at various stages in `seal_ha`.
[QT-629]: https://hashicorp.atlassian.net/browse/QT-629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[QT-617] Add seal migration to `seal_ha` scenario

---

website/content/api-docs/secret/ldap.mdx

This is the doc-side update for the addition of a new parameter to the LDAP secrets engine. The new parameter will allow users to skip the initial rotation that Vault does when adding a new static role. See [the feature PR](https://github.com/hashicorp/vault-plugin-secrets-openldap/pull/83) for more information.
This PR should be merged after that PR, or I suppose at the same time.

Add documentation for new ldap param

---

website/content/api-docs/system/mounts.mdx

- We had updated the mount tune api, but missed it within the creation api docs

Add missing allowed_managed_keys param to mount creation doc

---

changelog/23942.txt
ui/app/adapters/cluster.js
ui/app/models/cluster.js
ui/app/models/node.js
ui/app/routes/vault/cluster/dashboard.js
ui/app/services/version.js
ui/app/templates/error.hbs
ui/app/templates/vault/cluster/dashboard.hbs
ui/mirage/handlers/chroot-namespace.js
ui/mirage/handlers/index.js
ui/package.json
ui/tests/acceptance/chroot-namespace-test.js
ui/tests/acceptance/dashboard-test.js

This PR consists of updates to make the UI usable when [chroot namespace listener](https://developer.hashicorp.com/vault/tutorials/enterprise/namespace-structure#chroot-namespace) is set. 
When accessing the UI via a listener where chroot_namespace is set, but the defined namespace does not exist, the UI will show an error: 
Otherwise, the UI should work normally*
* there is still a known issue where the UI in a chrooted listener incorrectly hides navigation items when not logged in with a root token. This is due to the [resultant-acl](https://developer.hashicorp.com/vault/api-docs/system/internal-ui-resultant-acl) endpoint not stripping out the chrooted namespace from the paths. This will be addressed separately from this PR.

UI: chroot namespace listener

---

changelog/23964.txt
ui/app/components/sidebar/nav/cluster.hbs
ui/tests/acceptance/secrets/backend/database/secret-test.js
ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-edge-cases-test.js
ui/tests/acceptance/sidebar-nav-test.js
ui/tests/integration/components/sidebar/nav/cluster-test.js
ui/tests/pages/settings/mount-secret-backend.js

Updated sidebar/nav "Secrets engines" to "Secret Engines"

UI: Update secrets engines sidenav to title-casing

---

command/agent.go
command/agent/cache_end_to_end_test.go
command/agentproxyshared/cache/api_proxy_test.go
command/agentproxyshared/cache/lease_cache.go
command/agentproxyshared/cache/lease_cache_test.go
command/agentproxyshared/helpers_test.go
command/proxy.go

I think this was a miss when I split Agent and Proxy. The LifetimeWatcher subsystem uses the Agent user agent even if it's Proxy's lifetime watcher.
I think this will cause merge conflicts with #23801 when I merge it, but they should be easy enough to resolve, and I'm happy to fix them.
I don't think this will have any user-facing impact yet, since this doesn't yet show up in audit logs, so I don't know that a changelog is necessary. Still, it seems good to do since we're planning on doing that eventually. I noticed this when doing work in the area and it's an easy fix.

Fix lifetime watcher user-agent reporting Vault Agent for Vault Proxy requests

---

changelog/23908.txt
ui/app/components/auth-jwt.js
ui/app/templates/components/auth-jwt.hbs
ui/tests/acceptance/oidc-auth-method-test.js
ui/tests/integration/components/auth-jwt-test.js

There is an issue with error handling in the `AuthJwt` component where errors when attempting to fetch the role were being thrown with no catch. This gave the user the impression that nothing was happening when they would try to login via OIDC/JWT. This PR updates the workflow to surface all role related fetch errors so the user can better troubleshoot setup issues.
The attached video illustrates a 403 error that would have previously been unhandled and is now displayed as an alert. The network inspector is also visible to illustrate that when changing mount path or type that a request is made to fetch the role which is necessary to determine whether or not the mount is configured for JWT authentication. This is only provided as verification that regressions were not introduced in the …

OIDC/JWT Role Fetch Error Handling Updates

---

website/content/docs/platform/github-actions.mdx

Minor updates due to URL change:  `vault-secrets` is no longer accurate and should simply say, "Vault Github action"
🔍 [Deploy preview](https://vault-d3jewxrmy-hashicorp.vercel.app/vault/docs/platform/github-actions)

[DOCS] Update 'vault-secrets' to 'Vault' for clarify

---

changelog/22038.txt
command/server.go
helper/logging/logger.go
helper/testhelpers/corehelpers/corehelpers.go
vault/activity_log.go
vault/audit.go
vault/auth.go
vault/cluster.go
vault/core.go
vault/core_util.go
vault/expiration.go
vault/identity_store.go
vault/logical_system_test.go
vault/mount.go
vault/policy_store.go
vault/raft.go
vault/rollback.go
vault/seal_autoseal.go
vault/testing.go

This reverts commit 4c8cc87794ed2d989f515cd30c1c1b953d092ef3.

Revert "Automatically track subloggers in allLoggers (#22038)"

---

website/content/docs/release-notes/1.14.0.mdx
website/content/docs/release-notes/1.15.0.mdx
website/content/partials/known-issues/internal-error-namespace-missing-policy.mdx

Add workaround to known issue loading missing policies from other namespaces

docs: add workaround to known issue loading missing policies from other namespaces

---

website/content/docs/sync/github.mdx

[GitHub recommends against using structured data as secrets](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions) since it is more likely that the default obfuscation system will not recognize complex sensitive values.
We plan to address this issue by flattening all subkeys into individual secrets so the default behavior is more secure and users to not need to handle this pitfall themselves. In the meantime, we are adding a disclaimer and workaround in the documentation to help people prevent any unintended disclosure of secrets while they experiment with the Beta version.

Add GHA snippet to obfuscate synced secrets

---

vault/policy_store.go
vault/policy_store_test.go
vault/request_handling.go

This PR fixes the issue where Vault returns  a 500/Internal Error when an internal lookup of policy type fails.
This PR is a CE companion for the changes in hashicorp/vault-enterprise#4919. The changelog will be filed on the ENT side, since CE is not affected by the bug.

[VAULT-21461] Do not error when token policy type lookup fails

---

go.mod

Error we're trying to fix: module declares its path as: github.com/moov-io/signedxml but was required as: github.com/ma314smith/signedxml.

Add replace directive to work around an issue in ent with github.com/ma314smith/signedxml

---

ui/app/templates/components/clients/config.hbs
ui/app/templates/components/control-group-success.hbs
ui/app/templates/components/control-group.hbs
ui/app/templates/components/generate-credentials.hbs
ui/app/templates/components/generated-item.hbs
ui/app/templates/components/secret-create-or-update.hbs
ui/app/templates/components/transit-form-create.hbs
ui/app/templates/components/transit-form-edit.hbs

Some of the `<LinkTo>` components have `class="button"` and therefore look like buttons but are technically not. These also need to be swapped for `<Hds::Button>` when used in places like forms, so this PR tackles those missed during the initial button replacement sweep through these files.
Follow on to https://github.com/hashicorp/vault/pull/23698

UI: Replace buttons for HDS in component templates part 2

---

vault/core.go
vault/core_test.go

A refactoring change introduced a bug where the incorrect value (log level rather than log requests level) is suppled to the receiver which configures the log requests level on a Core.
Fixes: https://github.com/hashicorp/vault/issues/24045

fix `log_requests_level` misconfiguration

---

website/content/docs/release-notes/1.14.0.mdx
website/content/docs/release-notes/1.15.0.mdx
website/content/partials/known-issues/ephemeral-loggers-memory-leak.mdx

Remove partial references from release-notes that link to upgrade guides, and change link in partial to anchor.

Remove duplicate partial reference from release-notes

---

vault/core.go

Do not blindly store computed seal configuration information during unsealing. Instead, read any configuration already stored and determine whether the computed configuration during startup is newer (has a newer generation number), whether the in-memory re-wrapped status needs to be updated (if the generation numbers match), or whether the in-memory seal configuration is outdated (the stored seal generation is newer).

Read seal configuration info from storage during unseal process.

---

vault/core.go
vault/logical_system.go
vault/logical_system_test.go

This PR passes the `logical.BackendConfig` to `NewSystemBackend()` so that it can be used to properly setup the secrets sync backend with a system view.

sync: setup backend with system backend config

---

builtin/logical/transit/path_export.go
builtin/logical/transit/path_export_test.go
builtin/logical/transit/path_keys.go
changelog/24054.txt

- When attempting to export the public key for an RSA key that we only have a private key for, the export panics with a nil deference.
- Add additional tests around Transit key exporting
- Fixes #23980

Address a panic when exporting RSA public keys in transit

---

.hooks/pre-commit
ui/.copywrite.hcl
ui/.gitignore

This PR adds a bash function to be executed in the pre-commit hook for automatically adding copyright headers to staged files using the [Copywrite](https://github.com/hashicorp/copywrite) tool.

Copywrite pre-commit

---

vault/identity_store_entities.go

Pretty self-explanatory. Our error could be a lot better here. Not going to tackle the root cause of what might be wrong but this is a step forward.

Update error message when merging entity fails due to alias deletion failure

---

command/agentproxyshared/cache/static_secret_cache_updater_test.go

This test failed in CI, and I think this might be the reason why. In either case, it can't hurt.

Add a sleep to give the event system time to start

---

ui/app/components/dashboard/quick-actions-card.js
ui/lib/kv/addon/components/page/list.hbs

Shows a folder if the item in a KV engine is a directory. Also includes a fix for the dashboard quick actions card if the user does not have list permissions and falls back to string input

Kv directory fixes

---

changelog/24103.txt
ui/app/routes/vault/cluster/access/identity/aliases/index.js
ui/app/routes/vault/cluster/access/identity/index.js
ui/app/serializers/identity/_base.js
ui/app/serializers/identity/entity-alias.js
ui/app/serializers/identity/entity.js
ui/app/services/store.js
ui/app/utils/sort-objects.js
ui/tests/unit/utils/sort-objects-test.js

Backport of #24103 
* move list to component
* use helper instead
* add changelog
* clarify changelog copy
* delete components now that helper is in use
* move helper to util, remove template helper invokation
* add optional sorting to lazyPaginatedQuery based on sortBy query attribute
* Add serialization to entity-alias and entity so that they can be sorted by name on list view
* Same logic as base normalizeItems for extractLazyPaginatedData so that metadata shows on list
* Add headers
---------

Backport of UI: helper sort-objects to alphabetize list items (#24103)

---

changelog/24147.txt
ui/app/components/auth-config-form/options.js
ui/tests/acceptance/auth-list-test.js

The previous [PR](https://github.com/hashicorp/vault/pull/12904) that fixed this issue only did so for non-namespace token mounts. We didn't realize `ns_token` was a token type, so this checks the correct model attribute with `ns_` stripped away

UI: Allow token configuration tune from namespace

---

changelog/24165.txt
vault/logical_system.go
vault/seal_autoseal.go
vault/seal_autoseal_test.go

A seal's Access object contains all seal configuration, which in the case of seal migration includes the "unwrap seal" as well as the barrier seal. Thus, to determine whether an autoSeal is of a specific type such as 'Transit' or whether it is a 'Multiseal', use the wrappers of the seal's Access.
In addition: Fix an error that resulted in the wrong seal type being reported while Vault is in seal migration mode.

Use seal wrappers rather than config to determine autoSeal barrier type.

---

website/content/docs/configuration/service-registration/kubernetes.mdx
website/content/docs/platform/k8s/helm/configuration.mdx
website/content/docs/platform/k8s/helm/enterprise.mdx
website/content/docs/platform/k8s/helm/examples/enterprise-dr-with-raft.mdx
website/content/docs/platform/k8s/helm/examples/enterprise-perf-with-raft.mdx
website/content/docs/platform/k8s/helm/examples/enterprise-with-raft.mdx
website/content/docs/platform/k8s/helm/run.mdx
website/content/partials/helm/install.mdx
website/content/partials/helm/repo.mdx

Backporting the [docs update for vault-helm 0.26.0 and 0.26.1](https://github.com/hashicorp/vault/pull/23890), since backport-assistant got hung up on the command/kv_test.go fix: https://github.com/hashicorp/vault/pull/23920

Backport/1.15.x: update vault-helm docs for release 0.26.1

---

builtin/logical/pki/path_ocsp.go
builtin/logical/pki/path_ocsp_test.go
changelog/24192.txt
website/content/api-docs/secret/pki.mdx

When the `ocsp_expiry` field within [config/crl](https://developer.hashicorp.com/vault/api-docs/secret/pki#ocsp_expiry) is set to 0, we should not be setting the `NextUpdate` field within OCSP responses. We were setting it to the current time, which effectively means that the response has expired and shouldn't be used. 
Based on [RFC 6960: 4.2.2.1. Time](https://datatracker.ietf.org/doc/html/rfc6960#section-4.2.2.1), we shouldn't have set this field to indicate newer information is available right away
>    If nextUpdate is not set, the responder is indicating that newer revocation information is available all the time.

PKI: Do not set NextUpdate OCSP field when ocsp_expiry is 0

---

vault/identity_store_entities.go

Related to the escalation we've been looking into, this should hopefully signpost better if this issue recurs.
Jason, I know you're OOO, but adding you for visibility.

VAULT-22030 update error message when from entity isn't found as part of automated entity merge

---

changelog/24193.txt
sdk/helper/ocsp/client.go
sdk/helper/ocsp/ocsp_test.go

- If a server replies with what we considered an expired OCSP response, NextUpdate is now or in the past, and it was our only response we would panic due to missing error handling logic.

Handle expired OCSP responses from server

---

changelog/24168.txt
ui/app/adapters/capabilities.js
ui/app/services/namespace.js
ui/lib/core/addon/utils/sanitize-path.js
ui/lib/core/app/utils/sanitize-path.js
ui/tests/unit/adapters/capabilities-test.js
ui/tests/unit/utils/sanitize-path-test.js

`sys/capabilities-self` is an endpoint the UI uses to surface actions that a user can take within the GUI. The endpoint is on the default policy so that users can by default use the UI in the intended way. 
However, the policy is only applicable to the namespace where the user's auth mount is, so a user with the default policy only who logs into a child namespace that they have access to might see an error related to capabilities-self, or erroneously see buttons for actions they don't have capabilities to perform. 
This PR fixes that experience by ensuring the capabilities-self endpoint is always queried on the user's root namespace, and adds the rest of the current namespace to the beginning of the queried path.

UI: always send capabilities-self request in user's root namespace

---

vault/rekey_test.go

This change is required by an ENT test.

Augment testCore_Rekey_Update_Common to test for RekeyUpdate errors.

---

command/transit_import_key_test.go

- This is an attempt to resolve the timeout issues we are seeing on a nightly basis on the 32 bit runner
```
=== FAIL: command TestTransitImport (83.73s)
transit_import_key_test.go:123: Got unexpected failure from test (ret 3): Retrieving wrapping key.
failed to fetch wrapping key: error fetching wrapping key: context deadline exceeded
```
- Instead of relying on the initial call to import to generate the wrapping key, generate it within the test setup with a longer dedicated timeout.

TestTransitImport: Generate Transit wrapping key with a longer context

---

vault/identity_store_entities.go

This PR adjusts the framework paths for entity endpoints, so they all use the new `OperationHandler` structure.
This not only makes the implementation consistent in this file, but allows for use of `PathOperation` fields which were previously unavailable.

Consistently use OperationHandler for entity paths

---

changelog/24224.txt
ui/lib/kv/addon/components/kv-data-fields.hbs
ui/lib/kv/addon/components/kv-data-fields.js
ui/lib/kv/addon/components/page/secret/edit.hbs
ui/lib/kv/addon/components/page/secret/edit.js
ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-edge-cases-test.js
ui/tests/integration/components/kv/kv-data-fields-test.js

After the KV V2 refactor, there was strange behavior when attempting to paste into the JSON editor as described in #23940. This PR fixes that issue, and restores previous behavior where the edit mode defaulted to JSON when the KV secret is "complex" (has nested objects within it).

UI: Fix KV v2 json editor

---

api/go.mod
api/go.sum
go.mod
go.sum

A vulnerability came up today regarding version 3.0.0 of the `go-jose` package (more context [here](https://osv.dev/vulnerability/GO-2023-2334)).
This was detected by the [osv-scanner](https://github.com/google/osv-scanner) in a private repository I'm working on (which uses `vault`).

Update go-jose dependency to v3.0.1 due to vulnerability

---

changelog/24256.txt
vault/ha.go
vault/logical_system.go
vault/raft.go

Very similar bug fix to https://github.com/hashicorp/vault/pull/23861, a deadlock can occur on calls to `sys/leader` when namespaces are included.
Identified through an enterprise PKI test that was being written.

api/leader: fix deadlock when namespace is set on leader calls

---

builtin/logical/pki/acme_challenges.go
builtin/logical/pki/path_resign_crls.go
builtin/logical/pki/test_helpers.go

Fix up some error wrapping issues. I don't believe these actually cause/fix real issues, as we only really care about the ErrReadOnly case and the forwarding handler looks for both the error type or the special error string "cannot write to readonly storage", which the %v would have included.
Also add some testhelper methods mainly for enterprise tests to help lookup if a particular cluster has a certificate stored or not.

PKI: Address some errors that were not wrapped properly

---

website/content/api-docs/system/secrets-sync.mdx

Wasn't sure if/where we should include any section about configuration in the main docs.

Add configuration section to sync api

---

changelog/24250.txt
command/plugin_deregister.go
command/plugin_deregister_test.go
command/plugin_info.go
command/plugin_info_test.go
command/plugin_reload.go
command/plugin_reload_test.go

`vault plugin info` and `vault plugin deregister` have accepted either 1 or 2 positional args since we introduced types for plugins way back in v1.0.0 (#5536). This PR drops CLI support for type-less plugins on those commands, but the API can still be used to query any extremely old legacy plugins (although based on the plugin catalog's [UpgradePlugins](https://github.com/hashicorp/vault/blob/511ce92852eea274f0a72a8b718c3217de47dbcb/vault/plugin_catalog.go#L753) function, run during unseal, I don't think it should be possible for v1.0.0+ versions of Vault to have functioning type-less plugins). In return, we can get a much nicer UX on the CLI. It also improves the error reporting for `vault plugin reload`, which was simply buggy.
Examples of previous bad behaviour:
```shell-session
$ …
```

cli: Improve error handling for plugin commands

---

vault/external_tests/raft/raft_test.go
vault/seal/seal.go
vault/seal/seal_test.go
vault/seal/seal_testing.go
vault/seal_autoseal_test.go
vault/seal_testing_util.go

The Access object which manages the KMS encryption wrappers relies on the wrappers providing unique key IDs.
This PR adds a guard to Access.Encrypt to verify that the key IDs are unique. If any wrappers produce duplicates, their BlobInfo is replaced by an error.
This PR also fixes various unit tests that were using test wrappers that were equivalent when they were meant not to be so.

Check that multi-seal wrappers provide unique key IDs

---

vault/external_plugin_container_test.go

On vault-enterprise, this test fails because the rootless docker runtime isn't installed, so it can't build the plugin image when configured to use a rootless docker runtime.

testfix: Skip runsc test earlier

---

ui/lib/replication/addon/templates/components/known-secondaries-card.hbs
ui/tests/acceptance/enterprise-replication-test.js
ui/tests/helpers/openapi/auth-model-attributes.js

This PR address two sets of Failures for enterprise test:
1. LDAP failure. I believe this failure started because of this [PR](https://github.com/hashicorp/vault/pull/24099/files#diff-488a96fb64f816186eb8d54271a15655a0758c77c0d7375d4c5396020d11e211R54) which appears to add Password Policy to the LDAP configuration Open API.
2. Replication. Due to this [PR](https://github.com/hashicorp/vault/issues/24257). 
Locally, now all enterprise tests are passing.

Fix failing LDAP test with new attribute

---

website/content/docs/agent-and-proxy/proxy/caching/static-secret-caching.mdx

Spotted by @ccapurso during testing of the feature. It seems to have been a new add to the event system that I missed when writing the docs.

Correct required policy in static secret caching docs

---

command/agentproxyshared/cache/lease_cache.go
command/proxy_test.go

We were missing a `&& req.Token != ""` in the check to get something from the cache, as the validation logic assumes you have a token.
`TestProxy_Cache_EventSystemUpdatesCacheUseAutoAuthToken` isn't strictly related to this bug, but I noticed we didn't have a test for this, so I added it. The new additions to the test above this ensure that this bug is fixed.

Fix bug in static secret caching where no token is present in a request to Proxy

---

changelog/24292.txt
ui/lib/core/addon/components/replication-action-disable.js
ui/lib/core/addon/templates/components/replication-action-disable.hbs

Previously we were incorrectly sending a payload on the `replication/disable` endpoint, which returned a warning. This PR fixes the disable callback so that no payload is sent. 
Before:

UI: Prevent replication disable action from sending data payload

---

changelog/24290.txt
ui/lib/kv/addon/components/kv-data-fields.hbs
ui/lib/kv/addon/components/kv-data-fields.js
ui/lib/kv/addon/components/page/secret/details.hbs
ui/lib/kv/addon/components/page/secret/details.js
ui/lib/kv/addon/components/page/secret/edit.hbs
ui/lib/kv/addon/components/page/secrets/create.hbs
ui/tests/integration/components/kv/kv-data-fields-test.js
ui/tests/integration/components/kv/page/kv-page-secret-details-test.js

For a secret that is an object/nested ex: `{ "foo": { "bar": "baz" } }`, when you navigate to the details view it should default to a readonly JSON editor and disabled JSON toggle.
Making a different ticket for a nice-to-have as it's "new" and should not be backported: show only the keys unless “show values” is toggled on (new toggle)

Default to Json editor if KV secret is nested

---

changelog/24201.txt
vault/core.go
vault/eventbus/bus.go
vault/eventbus/bus_test.go
vault/eventbus/filter.go
vault/eventbus/filter_test.go

This adds a very basic implementation of a list of namespace+eventType combinations that each node is interested in by just running the glob operations in for-loops. Some parallelization is possible, but not enabled by default.
It only wires up keeping track of what the local event bus is interested in for now (but doesn't use it yet to filter messages).

events: Add filters to keep track of local and other subscriptions

---

.hooks/pre-commit

I am facing a bug in the pre commit hook where if the staged files include non-ui changes, they are being modified as well. This has happened to me when trying to merge main into a branch and there are ui changes, and then the precommit hook will modify go.mod, some go files, etc.

only update license changes in ui related files in ui precommit hook

---

changelog/24325.txt
vault/identity_store_entities.go

Update requests to `/sys/identity/entity/merge` perform merges on perfStandby nodes in memory and skip the persist call. 
This PR changes the behavior for the merge endpoint, forcing it to be forwarded from the standby to the active node. This change is specifically scoped to manual merges, as automatic merges are not isolated to a specific endpoint and require careful consideration for all callers.
Tests are on Enterprise: https://github.com/hashicorp/vault-enterprise/pull/5008/files

Always forward entity merge requests from perfStandby

---

changelog/24336.txt
vault/barrier_aes_gcm.go
vault/core.go

The recently introduced short timeout to prevent slow HSMs causing trouble while persisting barrier encryptions was also affecting more important code paths.  This changes that timeout to only be applied on encryption count persists.

Only use the short persistKeyring timeout for encryption count tracking

---

vault/seal/seal.go

This could be useful in an emergency where a seal config change was made, a rewrap was in progress, and one of the seals was irrevocably lost (think AWS KMS key deletion).  Otherwise the default safety check is good most of the time.

Make it possible to skip the seal re-wrap in progress check

---

LICENSE

Should avoid the need to continually update these files on release.
The text is text I got from an appropriate source, not legal text I wrote. It now matches the file contents on `main`. This is a cherry-pick backport.

Cherry pick license updates from main

---

website/content/docs/platform/k8s/vso/helm.mdx
website/content/docs/platform/k8s/vso/installation.mdx
website/content/docs/platform/k8s/vso/openshift.mdx

Update platform docs for the v0.4.1 VSO release.
Milestone: https://github.com/hashicorp/vault-secrets-operator/milestone/16

Update VSO docs for v0.4.1

---

builtin/logical/pki/backend_test.go
builtin/logical/pki/fields.go
builtin/logical/pki/path_manage_keys.go
builtin/logical/pki/path_manage_keys_test.go
website/content/api-docs/secret/pki.mdx

- Noticed that our documentation was out of date, we allow 8192 bit RSA keys to be used as an argument to the various PKI issuer/key creation APIs.
- Augument some unit tests to verify this continues to work

Document and augment tests that PKI accepts 8192 bit RSA keys

---

ui/app/adapters/cluster.js
ui/app/components/sidebar/nav/cluster.hbs
ui/app/models/cluster.js
ui/app/routes/vault/cluster/dashboard.js
ui/app/templates/components/dashboard/overview.hbs
ui/lib/replication/addon/routes/application.js
ui/mirage/handlers/reduced-disclosure.js
ui/tests/acceptance/enterprise-reduced-disclosure-test.js

This PR hides replication-related features when `disable_replication_status_endpoints` is true on the vault configuration. Specifically, when replication endpoints are disabled the UI should:
- hide the replication nav item in the sidebar
- hide the replication card on the dashboard
- disallow access to replication pages (eg. `/ui/vault/replication`) 
- redirect to login page when attempting to access `/ui/vault/replication-dr-promote` when vault is set up as DR secondary
To test, first make sure you are on a 1.16.0-beta+ent or above build of vault. Add `disable_replication_status_endpoints = true` to your listener config like so:
```
listener "tcp" {
address               = "0.0.0.0:8200"
cluster_address       = "0.0.0.0:8201"
disable_replication_status_endpoints = true
tls_disable = 1
} …
```

UI: handle reduced disclosure on replication endpoints

---

helper/testhelpers/corehelpers/corehelpers.go
vault/testing.go

Ensure we enable audit right after we're all good and unsealed... then `kv` after audit is done.

update testing.go: `initCores`

---

ui/lib/kv/addon/components/page/secret/details.js
ui/lib/sync/addon/components/secrets/landing-cta.hbs
ui/lib/sync/addon/components/secrets/landing-cta.ts
ui/lib/sync/addon/components/sync-header.hbs
ui/lib/sync/addon/components/sync-header.ts
ui/tests/helpers/sync/sync-selectors.js
ui/tests/integration/components/sync/secrets/landing-cta-test.js
ui/tests/integration/components/sync/secrets/page/destinations-test.js
ui/tests/integration/components/sync/secrets/page/overview-test.js
ui/tests/integration/components/sync/sync-header-test.js

This PR removes the `is-version` helper in the sync engine since it was removed from the core addon as part of another project.

Remove is-version Helper

---

ui/tests/helpers/general-selectors.js
ui/tests/helpers/sync/sync-selectors.js
ui/tests/integration/components/sync/secrets/page/destinations-test.js
ui/tests/integration/components/sync/sync-header-test.js

Some of the early tests written in the sync engine were using selectors directly ([data-test-selector]) rather than importing from the common selector files. This PR removes all selectors from tests in favor of the new pattern.

Common Selectors for Sync Tests

---

command/server.go

With the introduction of the Seal High Availability feature, the presence of multiple seals in configuration does not necessarily mean that the configuration entails a seal migration.
Instead of checking for multiple seals, check for the presence on an "unwrap" seal, which is only used for seal migrations.

Fix recovery mode check for seal migration configuration

---

website/content/partials/authn-names.mdx

This PR adds the SAML auth method to the [client count](https://developer.hashicorp.com/vault/docs/concepts/client-count#standard-entity-assignments) entity assignment table.

docs: adds saml to client count entity assignment table

---

builtin/logical/pki/backend.go
builtin/logical/pki/issuing/issue_common.go
builtin/logical/pki/parsing/certificate.go
builtin/logical/pki/path_acme_order.go
builtin/logical/pki/path_issue_sign.go
builtin/logical/pki/path_root.go
builtin/logical/pki/pki_backend/common.go
builtin/logical/pki/util.go

- Move the copy/pasted code to store certificates into a common method within the PKI plugin

PKI: Refactor storage of certificates into a common method

---

vault/seal/seal.go

The first could happen if an error is received and we call reportResult
synchronously.  But there is no one listening on the other side until later
in the function.  The second could occur if the context becomes done before
we receive the result.  The goroutine would be stuck trying to report the
result to the chan which is still open, but the for { select } loop is no
longer checking resultCh.

Fix two potential channel hangs in access.tryDecrypt

---

vault/core.go
vault/logical_system_quotas.go
vault/quotas/quotas.go
vault/quotas/quotas_rate_limit_test.go
vault/quotas/quotas_test.go

This commit moves quota storage updates into the storage package to facilitate testing. As a part of the change, we create a new `ManagerFlags` struct to make Setup invocations a bit more ergnomic.

quotas: Move storage updates into quotas package

---

vault/seal/seal.go

Otherwise if the ctx times out, but outstanding goroutines try to call reportResults, they panic sending to the closed channel.

use a stop chan to prevent sends on the closed result channel

---

vault/core.go
vault/external_tests/raft/raft_autopilot_test.go
vault/ha.go
vault/testing.go

Currently periodicLeaderRefresh polls the leader status every 2.5s.  When a test makes use of a perf standby node, it could get unlucky and issue a request right when that refresh is firing and discovering the leader for the first time, resulting in a 500 error while the perf standby re-initializes itself as a result of periodicLeaderRefresh having closed newLeaderCh.
We could just sleep for 3s after creating a cluster when we want to talk to perf standbys, but that seems an excessive delay, hence this PR to make the polling interval of periodicLeaderRefresh configurable.
After pushing this change I found that some Autopilot tests were failing, I think because of the sleep I added to NewTestCluster.  I want to keep that sleep, because it allows tests to avoid having to worry about …

Make leaderCheckInterval configurable.

---

ui/app/styles/helper-classes/flexbox-and-grid.scss
ui/lib/core/addon/components/enable-input.hbs
ui/lib/core/addon/components/enable-input.ts
ui/lib/core/addon/components/form-field.hbs
ui/lib/core/addon/components/text-file.hbs
ui/lib/core/app/components/enable-input.js
ui/tests/integration/components/enable-input-test.js
ui/tests/integration/components/form-field-test.js

`EnableInput` wraps a yielded input to disable after a user clicks `Edit`. The purpose of this component is to add an extra click so users are intentionally editing values that are not returned from the API after create. Per design, there is no toggling back after clicking "edit" - the user needs to refresh or `Cancel` to return to the initial state

UI: Create enable input component

---

go.mod
go.sum

Update `go-eventlogger` dependency to `v0.2.8` and `go mod tidy`. 
New version adds `Broker.SuccessThreshold()` and `Broker.SuccessThresholdSinks()` receivers as a way to examine the current threshold settings for a given event type.

Bump go-eventlogger to v0.2.8

---

.hooks/pre-commit

#24091 added a pre-commit hook for scanning and adding copyright headers to staged files in the UI directory. Recently, this has caused some commits to be blocked or files to be committed with modifications other than just adding the copyright headers. This PR removes the hook until it can be tested further or a better solution is devised.

Remove ui_copywrite  Pre-commit Hook

---

changelog/24404.txt
ui/app/models/kv/metadata.js
ui/lib/kv/addon/components/page/list.hbs
ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-create-test.js
ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-delete-test.js
ui/tests/helpers/kv/kv-selectors.js
ui/tests/helpers/policy-generator/kv.js

Backport for 1.15.x: add full path to KV v2 capabilities check

---

command/server.go
vault/core.go

It is not sufficient to check that function setSeal in server.go does not return an "unwrap seal". For migrations away from a Shamir seal, NewCore constructor sets up an unwrap seal by calling method adjustForSealMigration.
Factor out new method checkForSealMigration out of adjustForSealMigration so that NewCore can verify that there won't be a migration when returning early due to running in recovery mode.

Update recovery mode guard to account for migrating away from Shamir

---

website/content/docs/platform/mssql/installation.mdx

Slack discussion with @tomhjp for context:
https://hashicorp.slack.com/archives/CPEPB6WRL/p1701966885637999?thread_ts=1701957028.186399&cid=CPEPB6WRL
The important part of the slack discussion, for transparency... I did some testing of the EKM provider to see how it behaved. My findings below:
EKM authenticates with Vault, gets a token with a specific TTL, then eventually that token expires.
After a few minutes of inactivity, looks like EKM did re-auth with Vault, and got itself a new token
```
Key                 Value
---                 -----
accessor            fBQVRIPK3td6ptYMNwNIIK9r
creation_time       1701956971
creation_ttl        2h
display_name        approle
entity_id           03ca3e9c-400a-1ab6-1580-58ea08f7437f
expire_time         2023-12-07T15:49:31.693948538Z …
```

docs: clarified the MS SQL EKM provider's authentication behavior, and the implications for AppRole configuration

---

ui/lib/sync/addon/components/secrets/page/destinations/destination/sync.ts
ui/tests/integration/components/sync/secrets/page/destinations/destination/sync-test.js

This PR fixes an issue where newly synced associations were not appearing in the list on the destination secrets page. Sync associations needed to be cleared from the store so that `lazyPaginatedQuery` would fetch results from the server.

Sync Destination List Refresh Bug

---

website/content/docs/agent-and-proxy/proxy/index.mdx

Looks like a copy/paste error, but yeah, this shouldn't be here (the links do not work, and this functionality is not supported for Vault Proxy).

Fix templating mention in Proxy docs

---

vault/seal/seal.go

The wg.Add calls are concurrent due to decrypt() being run in goroutines. 
Instead add before spawning the routine.

Fix race in the tryDecrypt waitgroup

---

ui/lib/core/addon/components/kv-suggestion-input.hbs
ui/lib/sync/addon/components/secrets/page/destinations/destination/sync.hbs
ui/lib/sync/addon/components/secrets/page/destinations/destination/sync.ts
ui/tests/helpers/sync/sync-selectors.js
ui/tests/integration/components/sync/secrets/page/destinations/destination/sync-test.js

This PR adds a success banner to the destination sync page since the user remains on the page and is able to sync more secrets.

Sync Success Banner

---

ui/app/serializers/sync/destination.js
ui/lib/sync/addon/components/secrets/page/destinations.ts
ui/tests/acceptance/sync/secrets/destinations-test.js
ui/tests/helpers/general-selectors.js

This PR fixes 2 bugs surrounding filtering of the destinations list view. The first where duplicate destination types were appearing in the type filter dropdown, and the second where destinations were not filtering properly based on the selections.
_Before. Notice the pagination totals are correct but all types are returned. The same would be true if we filtered by name._
_After_

Sync Destinations List Filter Bug

---

ui/app/adapters/sync/destination.js
ui/tests/unit/adapters/sync/destinations-test.js

This PR adds the `?purge=true` query param which is working under the assumption that this PR is merged https://github.com/hashicorp/vault-enterprise/pull/5056

UI Secrets sync: Add purge query param to delete endpoint

---

builtin/audit/file/backend.go
builtin/audit/socket/backend.go
builtin/audit/syslog/backend.go
helper/builtinplugins/builtinplugins_test.go
helper/testhelpers/corehelpers/corehelpers.go
vault/testing.go

* Prevent overwriting pipelines and nodes
* Remove unused bits of test cluster
* Test flaking didn't need audit, so supply a factory to prevent auto-enabling audit

Audit related foibles

---

builtin/logical/database/backend.go
builtin/logical/database/backend_test.go
builtin/logical/database/path_config_connection.go
changelog/24472.txt
website/content/api-docs/secret/databases/index.mdx

This complements the [reset connection](https://developer.hashicorp.com/vault/api-docs/secret/databases#reset-connection) API, to also be able to restart by plugin instead of just by connection. This is especially helpful for completing plugin upgrades. In a future PR, I plan to support making an internal call to this endpoint from a more generic plugin reload endpoint to support database plugin reloads across multiple database mounts.
I had originally planned to implement cross-mount plugin reloads by killing plugins directly from the plugin catalog. However, that wouldn't give the best possible UX because the plugin catalog only knows what's currently running, not what the next config should be, so it would only be able to kill the existing plugins and not restart them. Then if the new …

New database plugin API to reload by plugin name

---

api/sys_capabilities.go
changelog/24479.txt
command/token_capabilities.go
command/token_capabilities_test.go

Command: token capabilities using accessor

---

website/content/docs/concepts/client-count/index.mdx

- The existing bare *.test.com triggered italics and stripped the * from the output 🤕

Quote example domains within ACME entity docs

---

audit/types.go
builtin/audit/file/backend.go
builtin/audit/socket/backend.go
builtin/audit/syslog/backend.go
helper/testhelpers/corehelpers/corehelpers.go
internal/observability/event/pipeliner.go
vault/audit.go
vault/audit_broker.go

This PR tries to provide `AuditBroker` with more information to let it manage pipelines and set the success threshold (for sinks) based on whether we have:
* Only non-filtering pipelines
* Mixed filtering and non-filtering pipelines
* Only filtering pipelines

Attempt to move control of registration for nodes and pipelines to the audit broker

---

website/content/api-docs/auth/aws.mdx

Noticed a small mistake in AWS auth method doc. This PR fixes it.

docs: fix typo in api-docs/auth/aws.mdx

---

changelog/24492.txt
ui/app/components/sidebar/nav/cluster.hbs
ui/app/components/sidebar/nav/cluster.js
ui/app/services/permissions.js
ui/lib/core/addon/utils/sanitize-path.js
ui/mirage/handlers/chroot-namespace.js
ui/tests/acceptance/chroot-namespace-test.js
ui/tests/pages/auth.js
ui/tests/unit/services/permissions-test.js
ui/tests/unit/utils/sanitize-path-test.js

Backport UI: show correct nav items when logged into chrooted namespace

---

ui/lib/core/addon/components/form-field.hbs
ui/lib/core/addon/components/form-field.js
ui/tests/integration/components/form-field-test.js

This updates the radio form fields to have radio group styles. Radio groups include label and subtext!

UI: Update radio form field to have group styles and label/subtext

---

audit/entry_formatter.go
audit/event.go
audit/event_test.go
audit/sink_wrapper.go
audit/types.go
helper/testhelpers/corehelpers/corehelpers.go
http/logical_test.go
http/sys_generate_root_test.go
vault/audit_test.go
vault/core_test.go
vault/external_tests/identity/login_mfa_totp_test.go

This PR is intended to remove the reliance on the old behavior of audit, which was possible as we supported it via the environment variable `VAULT_AUDIT_DISABLE_EVENTLOGGER`.
Test code has been updated so the eventlogger code is exercised instead.
As a side effect of this, `AuditEvent` has been exported as a type from the `audit` package.

Remove old audit behavior from test code

---

changelog/24549.txt
vault/core.go
vault/ha.go

If a consumer of the sys/leader api relies on ActiveTime, they can be misled by our current behaviour, whereby ActiveTime gets set to "now" during postUnseal and to the zero time during preSeal.  We sometimes preSeal/postUnseal while remaining the active node.  Instead, only set these when we actually change active role.

Don't touch ActiveTime in preSeal/postUnseal

---

helper/testhelpers/teststorage/teststorage.go
vault/external_tests/raft/raft_autopilot_test.go
vault/external_tests/raft/raft_test.go
vault/testing.go

Also replace VersionMap and RedundancyZoneMap with PerNodePhysicalFactoryConfig.

Simplify raft tests, use inmem networking instead of address providers

---

helper/testhelpers/testhelpers.go
helper/testhelpers/teststorage/teststorage.go
helper/testhelpers/teststorage/teststorage_reusable.go
physical/raft/raft.go
sdk/helper/testcluster/util.go
vault/cluster.go
vault/core.go
vault/external_tests/raft/raft_autopilot_test.go
vault/external_tests/raft/raft_test.go
vault/external_tests/raftha/raft_ha_test.go
vault/external_tests/sealmigration/seal_migration_test.go
vault/raft.go
vault/testing.go

To accommodate our use of ephemeral cluster ports (":0"), we have been using a ServerAddressProvider that we pass to Raft. This is because when we create the raft backend and the raft library instance, we don't know what the actual port/address each node will have, and this was a mechanism to provide that information late, after each listener has started and we do know the port. However, this required sealing a node to install the address provider, which adds some non-determinism to our tests and complicates them.
Instead, most tests are now using the inmem network layer, which has no need for a server address provider. For a handful of tests this is inconvenient, and we'd also still like to be able to run raft tests using TCP networking, so for those we use a new address provider, which …

Simplify raft cluster address management in tests

---

website/content/api-docs/system/secrets-sync.mdx

Backport from PR against main didn't work so I cherry-picked the commit with the fix. Not needed for version <1.15.x since the feature launched with 1.15.
```
git cherry-pick b169526d69a1d7d57c046a2299e490942a135f28
```

Fix remove endpoint doc

---

vault/logical_system_custom_messages.go
vault/logical_system_custom_messages_test.go

The @hashicorp/vault-ui team provided feedback that the response structure for the Create, Read, and Update operations on the Custom Messages endpoint could be simplified. This PR does exactly that by moving the contents of the following JSON path `.data.data` into `.data` and removing `.data.data`. This change simplifies the code that builds the response and the code that tests the handlers as well.

VAULT-21608: Flatten Custom Messages Response Structure

---

ui/app/adapters/sync/association.js
ui/lib/sync/addon/components/secrets/page/destinations/create-and-edit.ts
ui/lib/sync/addon/components/secrets/page/destinations/destination/secrets.hbs
ui/lib/sync/addon/components/secrets/page/destinations/destination/secrets.ts
ui/lib/sync/addon/components/secrets/page/destinations/destination/sync.ts
ui/lib/sync/addon/routes/secrets/destinations/destination/secrets.ts
ui/lib/sync/addon/routes/secrets/destinations/index.ts
ui/mirage/handlers/sync.js
ui/tests/integration/components/kv/page/kv-page-secret-details-test.js
ui/tests/integration/components/sync/secrets/page/destinations/destination/sync-test.js
ui/tests/unit/adapters/sync/associations-test.js

- Fix `404` error for `/sys/sync/associations/:mount/:secret` endpoint which does not work with nested secret paths because the endpoint URL has no way of differentiating between the mount and secret path. Update UI to use query params:  `/sys/sync/associations/destinations?mount=:mount&secret_name=:secret`
- Add `{ list: true }` to `GET sys/sync/associations`
- Reset sync error when form re-submits
- ~Add `willDestroy` hook to cleanup destination model in create-and-edit form~ (introduced too many regressions, caused lots of test failures. Separate ticket created to investigate.)
- Fixes pagination by adding `refreshModel` in route for params
- Fix styling for `Sync now` action (previously the grey hover only happened

Secrets Sync: Bug fixes part 1

---

enos/enos-modules.hcl
enos/enos-scenario-autopilot.hcl
enos/modules/vault_verify_default_lcq/main.tf
enos/modules/vault_verify_default_lcq/scripts/smoke-verify-default-lcq.sh

This PR adds a new Default LCQ verification to the autopilot upgrade scenario to verify that:
Upgrades from 1.16 -> 1.16+ have the new Default LCQ
Upgrade from <1.16 -> 1.16+ DO NOT have the Default LCQ
This resolves VAULT-22083

enos: Add Default LCQ validation to autopilot upgrade scenario

---

website/content/docs/configuration/storage/raft.mdx

This small edit to wording was made based on customer feedback, which suggested that the previous wording was confusing as well as not sufficiently descriptive. The new wording hopefully describes the use of this stanza a bit more clearly.

Add some clarity to `retry_join` docs

---

website/content/docs/configuration/storage/raft.mdx

Due to merge conflict, manually cherry-pick a commit made by https://github.com/hashicorp/vault/pull/24605

[Backport] Add some clarity to `retry_join` docs (#24605)

---

website/content/docs/auth/saml.mdx

This PR fixes the code snippet copy function in the SAML auth method docs. It also fixes quoting inconsistency of arguments in the CLI examples.

docs: fix code snippet copy for SAML auth method

---

website/content/docs/secrets/gcp.mdx

This PR improves the guidance given for authenticating GCP integrations using workload identities by providing more targeted links.

docs: adds more targeted guidance for GCP workload identity

---

changelog/24616.txt
helper/fairshare/jobmanager.go
helper/fairshare/jobmanager_test.go

Our race detector is giving us a warning when we iterate the map as a job finishes (which decrements the worker count).
Instead of returning the map, we should instead clone it so that readers can access it safely.
Tested via
```
go test ./helper/fairshare/... -run TestJobManager_GetWorkerCounts_RaceCondition -race
```

fix race condition on GetWorkerCounts by cloning map

---

website/content/docs/plugins/containerized-plugins/add-a-containerized-plugin.mdx
website/content/docs/plugins/containerized-plugins/index.mdx
website/data/docs-nav-data.json

The automated cherry-pick failed to backport https://github.com/hashicorp/vault/pull/24537.
This PR performs manual cherry-pick to replace auto-generated PR: https://github.com/hashicorp/vault/pull/24606
🔍 [Deploy preview](https://vault-hsd4i97if-hashicorp.vercel.app/vault/docs/plugins/containerized-plugins/add-a-containerized-plugin)

[DOCS] Add how-to guide for containerize plugins (#24537)

---

ui/app/models/sync/destinations/vercel-project.js
ui/app/serializers/sync/destination.js
ui/app/transforms/comma-string.js
ui/mirage/factories/sync-destination.js
ui/tests/integration/components/sync/secrets/page/destinations/create-and-edit-test.js
ui/tests/unit/transforms/comma-string-test.js

The [docs](https://developer.hashicorp.com/vault/api-docs/system/secrets-sync#deployment_environments) mentioned `deployment_environments` will be a string but when testing noticed the value returned as an array of strings. Confirmed with the backend team that the type should be updated to an array.
Ember's `changedAttributes()` does not track `array` types, so we transform it to a string to effectively track which keys to include in the `PATCH` payload

Secrets Sync UI: Refactor vercel-project destination to expect array from server

---

ui/lib/sync/addon/components/secrets/landing-cta.hbs
ui/lib/sync/addon/components/secrets/page/destinations.hbs
ui/lib/sync/addon/components/secrets/page/destinations.ts
ui/lib/sync/addon/components/secrets/page/destinations/destination/secrets.hbs
ui/lib/sync/addon/components/secrets/page/destinations/destination/secrets.ts
ui/lib/sync/addon/components/secrets/page/overview.hbs
ui/lib/sync/addon/components/secrets/page/overview.ts
ui/tests/helpers/general-selectors.js
ui/tests/integration/components/sync/secrets/landing-cta-test.js
ui/tests/integration/components/sync/secrets/page/destinations-test.js
ui/tests/integration/components/sync/secrets/page/destinations/destination/secrets-test.js
ui/tests/integration/components/sync/secrets/page/overview-test.js

- Fixes the secrets status in the list view so it updates if the `sync now` popup menu action returns an error. 
- Previously, the type filter only included types that were on the current page (because of pagination). Refactoring so all destination types are filter-able and rely on the empty state to let the user know none exist
- Only displays `Create first destination` CTA for enterprise versions
<hr> 
<hr>
_CTA button is hidden, just learn more link displays_

Secrets sync UI: Round of bug fixes part 2

---

ui/app/templates/components/console/log-help.hbs
ui/app/templates/components/console/ui-panel.hbs
ui/app/templates/components/wizard/secrets-list.hbs
ui/tests/integration/components/secret-edit-test.js
website/content/docs/commands/web.mdx
website/content/docs/configuration/ui.mdx
website/data/docs-nav-data.json

So this is loooooong overdue, and I think I've promised it at least a couple of times over the years. But! This is a first pass at adding a page about the Web CLI / Web [REPL](https://en.wikipedia.org/wiki/Read%E2%80%93eval%E2%80%93print_loop) to the docs. I think we should explicitly call it the Web REPL everywhere so that it's clear it's not a fully-functioning CLI and so users don't expect it to have every feature the `vault` CLI does.
Open questions: 
1. **Is this the right place for this to live in the docs?** There aren't a lot of other UI-specific docs, so I nested it in at the top of the CLI docs.
2. **Is this complete?** It's been a while since I did anything related to the REPL, so there could be new functionality. I looked through the code a bit and I think I got everything, …

docs(web repl): add initial docs about the UI REPL

---

ui/lib/sync/addon/components/secrets/page/destinations/destination/secrets.hbs
ui/tests/acceptance/sync/secrets/destination-test.js

Transitioning to the sync overview route from the destination secrets or details route via the breadcrumb was resulting in the following error:
Since `@model` was not provided to the `Hds::Pagination::Numbered` component, a transition away from the parent destination route (where the necessary model was loaded) was resulting in an error from a `LinkTo` component.

Sync Destination Transition Bug

---

builtin/logical/database/rotation.go
builtin/logical/database/rotation_test.go
command/agentproxyshared/auth/alicloud/alicloud.go
command/agentproxyshared/auth/aws/aws.go
command/agentproxyshared/auth/ldap/ldap.go
vault/core.go
vault/request_forwarding.go

`time.NewTicker` panics if given a value `<= 0`. As a result, it needs to be given a positive number (above 0). These were all of the cases I found where this could happen, and I added a test for the main one called out in the bug report.

VAULT-8790 Ensure time.NewTicker never gets called with a negative value

---

.github/workflows/security-scan.yml

Similar to https://github.com/hashicorp/consul/pull/19978#discussion_r1430706090, we can remove the unused GitHub Token from this step.

Remove unused token

---

website/content/api-docs/secret/transit.mdx
website/content/api-docs/system/auth.mdx
website/content/api-docs/system/mounts.mdx
website/content/docs/concepts/user-lockout.mdx
website/content/docs/platform/k8s/csi/configurations.mdx

- corrected 4 misspellings of the word precedence in these locations
- corrected spelling and grammar in securely export key api doc description

typo corrections - spelling and grammar

---

changelog/24667.txt
command/agent.go
command/agent/config/config.go
command/agentproxyshared/auth/auth.go
command/agentproxyshared/cache/api_proxy.go
command/proxy.go
command/proxy/config/config.go
website/content/docs/agent-and-proxy/agent/index.mdx
website/content/docs/agent-and-proxy/autoauth/index.mdx
website/content/docs/agent-and-proxy/proxy/apiproxy.mdx
website/content/docs/agent-and-proxy/proxy/index.mdx

The CE portion of the 17292 changes. Missing are the tests, which are in the ent repo.

VAULT-17292 CE portion of changes

---

command/agentproxyshared/auth/auth.go
command/agentproxyshared/auth/auth_test.go
sdk/helper/backoff/backoff.go
sdk/helper/backoff/backoff_test.go

I have an upcoming PR for event notifications that needs similar exponential backoff logic, and I prefer the API and logic in the auto-auth exponential backoff rather than that of
github.com/cenkalti/backoff/v3.
This does have a small behavior change: the auto-auth min backoff will now be randomly reduced by up to 25% on the first call. This is a desirable property to avoid thundering herd problems, where a bunch of agents won't all try have the same retry timeout.

Refactor auto-auth backoff to helper package.

---

vault/activity_log_util_common.go
vault/activity_log_util_common_test.go

This PR adds secret sync association estimates to hyperloglog calculations for the current month count.

[VAULT-22641] Include secret sync associations with hyperloglog estimations

---

website/content/docs/concepts/client-count/index.mdx

I introduced a pluralization error within #24501 when updating the ACME entity assignment docs.

Fix pluralization error in ACME entity assignment doc

---

ui/app/models/sync/destinations/azure-kv.js
ui/tests/integration/components/sync/secrets/page/destinations/create-and-edit-test.js

In https://github.com/hashicorp/vault/pull/24644 I mistakingly added `key_vault_uri` to the credentials block because it is an obfuscated param - however it is not actually editable which is the intention of the credentials section. 
See below - there is an "enable" button to intentionally change the sensitive value. This doesn't make sense for a non-editable param.
This PR moves the param back to the main section of the form

UI: remove keyvauluri from credentials section

---

vault/core.go
vault/custom_messages_manager.go
vault/logical_system.go
vault/logical_system_custom_messages.go
vault/logical_system_custom_messages_test.go
vault/logical_system_paths.go
vault/logical_system_test.go
vault/ui_custom_messages/manager.go
vault/ui_custom_messages/manager_test.go
vault/ui_custom_messages/namespace.go
vault/ui_custom_messages/namespace_test.go

This PR completes the changes in this repository for the UI Custom Messages feature. It introduces two more endpoints:
1. `sys/internal/ui/unauthenticated-messages`
2. `sys/internal/ui/authenticated-messages`
This PR introduces the handler for these endpoints and tests to cover them.
This PR also includes a change in the structure of the link parameter in the request body or in the response body. The previous structure was:
```json
{
"link": {
"title": "Click Here",
"href": "https://www.example.com"
}
}
```
The new structure is changing to:
```json
{
"link": {
"Click Here": "https://www.example.com"
}
}
```
The tests that cover functions impacted by this change weren't doing much in verifying the previous structure, but have been improved to properly check that this structure is properly …

VAULT-21608: Endpoints to Retrieve Active Pre- and Post- Login Messages

---

changelog/24686.txt
ui/app/models/pki/issuer.js
ui/tests/acceptance/pki/pki-engine-workflow-test.js
ui/tests/acceptance/pki/pki-overview-test.js
ui/tests/acceptance/policies-acl-old-test.js
ui/tests/helpers/pki/pki-run-commands.js

There was a bug where capabilities on PKI issuers were incorrectly calculated. The workflow tests did not catch this because we weren't clearing the store of `capabilities` entries after setup, which means the UI was using the old capabilities in memory from the root setup.

UI: fix PKI issuer capabilities

---

ui/app/styles/helper-classes/typography.scss
ui/lib/core/addon/components/search-select-placeholder.hbs
ui/lib/sync/addon/components/secrets/page/destinations.hbs
ui/lib/sync/addon/components/secrets/page/destinations.ts
ui/lib/sync/addon/components/secrets/page/destinations/create-and-edit.ts
ui/lib/sync/addon/routes/secrets/destinations/destination/secrets.ts
ui/lib/sync/addon/routes/secrets/destinations/index.ts
ui/tests/acceptance/sync/secrets/destinations-test.js
ui/tests/helpers/general-selectors.js
ui/tests/integration/components/sync/secrets/page/destinations-test.js

This PR updates the sync destinations list name filter from the `SearchSelect` component to `FilterInput`. There was originally a bug where the `SearchSelect` was only populated with the names on the current page but when looking at that it was determined that using the `FilterInput` would be more appropriate.

Sync Destinations List Name Filter Updates

---

changelog/24697.txt
ui/app/models/auth-config/jwt.js

Fixes https://github.com/hashicorp/vault-plugin-auth-jwt/issues/248 by adding upload capabilities for the `jwks_ca_pem` param. Previously the input was a basic (single line) text input, now a user can upload a PEM certificate or paste it in a multi-line text area.  The CA is submitted in the correct format now, see the screenshot below includes line breaks where expected:

UI: Changes jwks_ca_pem param to a 'file' edit type

---

builtin/logical/database/backend_test.go
builtin/logical/database/versioning_large_test.go
builtin/plugin/backend_test.go
changelog/24512.txt
http/plugin_test.go
vault/external_tests/plugin/plugin_test.go
vault/logical_system.go
vault/mount.go
vault/plugin_reload.go

This builds on #24472 to support reloading database plugins across multiple mounts. The next stage will be to implement a new root-namespace-only endpoint that allows reloading plugins across multiple namespaces, which will leverage the same function but with some updates. At that point, admins in the root namespace will have everything they need to ensure they can reload all instances of a plugin they've just updated in the plugin catalog without having to enumerate all mounts and namespaces.
This also adds a warning to the response if a reload request ever succeeds but without actually reloading a plugin, for example because the plugin wasn't in use, or if the plugin doesn't even exist in the catalog. We report number of reloads instead of explicitly telling users about whether or not …

Support reloading database plugins across multiple mounts

---

changelog/24686.txt
ui/app/models/pki/issuer.js
ui/tests/acceptance/pki/pki-engine-workflow-test.js
ui/tests/acceptance/pki/pki-overview-test.js
ui/tests/acceptance/policies-acl-old-test.js
ui/tests/helpers/pki/pki-run-commands.js

Backport UI: fix PKI issuer capabilities (#24686)

---

.github/workflows/test-go.yml

We had a recent failure with `find: cannot delete ‘test-results/go-test/logs-13’: Directory not empty`, a failure to delete a non-empty directory. Limiting this to just the files seems to be an easy win.

Add -type -f to the -find delete call as part of test collect reports

---

vault/external_tests/raft/raft_test.go

They've been flakier since #24557 so we hypothesize that change had a negative impact.

Make the TestRaft_Snapshot_API "rotate" tests use TCP networking again

---

website/content/api-docs/auth/aws.mdx

Current docs for the AWS auth method login request have an empty object as the sample payload for the request.
https://developer.hashicorp.com/vault/api-docs/auth/aws#login. This is inaccurate as the request requires values in the data payload.

Sample payload is empty for AWS auth login request in API docs

---

vault/audit_broker.go

As `retErr` is referenced by the defer, we should ensure that it always contains the most up to date set of errors.

Audit Broker: Log Response should always assign the multierror before returning from it.

---

ui/tests/pages/components/console/ui-panel.js

There was an uptick in flaky tests [due to an error](https://github.com/hashicorp/vault/actions/runs/7466007078/attempts/1#summary-20316427775) accessing the `lastLogOuput` from the console ui-panel. A check was added to verify that there are output items returned before attempting to access the last item in the array.

Flaky Tests from lastLogOutput Error

---

ui/app/models/sync/destination.js
ui/app/models/sync/destinations/azure-kv.js
ui/lib/core/addon/components/text-file.hbs
ui/lib/core/addon/helpers/sync-destinations.ts
ui/lib/kv/addon/components/page/secret/details.hbs
ui/lib/sync/addon/components/secrets/page/destinations/create-and-edit.hbs
ui/lib/sync/addon/components/secrets/page/destinations/destination/sync.hbs
ui/lib/sync/addon/components/secrets/page/destinations/destination/sync.ts
ui/tests/integration/components/sync/secrets/page/destinations/destination/sync-test.js

- Only render success banner in sync form if `mountPath` is set
- Remove trailing space from kv details banner
- Un-obfuscate `key_vault_uri` following backend bug fix
- Add validation for space in destination name

Secrets Sync UI: Small bug fixes from more QA 

---

.github/workflows/milestone-checker.yml
.github/workflows/test-go.yml

`Prepare datadog-ci` has been failing on enterprise. My theory is that it still had binaries around on old runners from before we added the repo check, but it's failing on new/cleaned runners. This should fix that.
I also noticed milestone checker wasn't running on enterprise, so thought I'd do an easy fix of that too.

Fix some GHAs not running on enterprise

---

.github/workflows/test-go.yml

The `actions/upload-artifact` action does not support filenames with special characters as it needs to maintain restore compatibility with NTFS filesystems. Instead of uploading raw log files, which can inherit names with special characters and break the upload, we tar them all together to preserve their names and upload the resulting tarball.

actions: upload go test logs as a tarball

---

ui/app/models/sync/destination.js
ui/app/serializers/sync/destination.js
ui/lib/kv/addon/components/page/secret/details.hbs
ui/lib/sync/addon/components/secrets/destination-header.hbs
ui/lib/sync/addon/components/secrets/destination-header.ts
ui/lib/sync/addon/components/secrets/page/destinations.ts
ui/lib/sync/addon/components/secrets/page/destinations/create-and-edit.ts
ui/mirage/factories/sync-destination.js
ui/mirage/handlers/sync.js
ui/tests/helpers/sync/sync-selectors.js
ui/tests/integration/components/sync/secrets/destination-header-test.js
ui/tests/integration/components/sync/secrets/page/destinations-test.js
ui/tests/integration/components/sync/secrets/page/destinations/create-and-edit-test.js

Secrets Sync UI: Add purge delete progress and error banner to destination header

---

ui/app/templates/vault/cluster/unseal.hbs
ui/tests/acceptance/reduced-disclosure-test.js
ui/tests/acceptance/unseal-test.js

When we adopted ember-exam we had to skip the tests for seal/unseal flow because it seals the vault used on the concurrent tests and causes them to fail. This PR uses mocked endpoints to approximate the seal flow without jeopardizing the other tests.

UI: unseal tests used mocked endpoints

---

.github/workflows/build.yml
.github/workflows/ci.yml
.github/workflows/test-go.yml

We had a dependabot for this (https://github.com/hashicorp/vault/pull/21605) but it's a bit old and borked, so I thought I'd just do it from scratch. There are some ent specific files to get afterwards.

CE Update of vault-action from 2.5 to 2.74

---

vault/core.go
vault/core_util.go
vault/ui_custom_messages/manager.go
vault/ui_custom_messages/manager_test.go

This PR makes changes that allow replacing the **nsManager** global variable with a field bearing the same name in the **uicustommessages.Manager** struct. The refactoring will avoid a potential data race due to the updating of the **nsManager** global variable, which happens when running the enterprise edition. Instead, by making **nsManager** a field of the **Manager** struct, it can be initialized appropriately, based on the edition.

VAULT-21608: Make Namespace Manager a Field in the Manager Structure

---

.github/workflows/test-go.yml

When it failed, we didn't run this, and then therefore get the outputs

Run archive test logs always

---

website/content/api-docs/system/leader.mdx

The `/sys/leader` endpoint returns additional fields that are not in the current sample response. This PR updates the API docs at https://developer.hashicorp.com/vault/api-docs/system/leader to include the `active_time`, `last_wal`, `raft_committed_index`, and `raft_applied_index` fields.
<details><summary>Real response I received for reference</summary>
```json
{
"ha_enabled": true,
"is_self": true,
"active_time": "2024-01-09T00:11:46.439409062Z",
"leader_address": "https://node-13-1.helen-test-p-private-vault-22e7cae2.274d6236.z1.hashicorp.cloud:8202",
"leader_cluster_address": "https://172.25.21.40:8201",
"performance_standby": false,
"performance_standby_last_remote_wal": 0,
"last_wal": 643892,
"raft_committed_index": 2507946,
"raft_applied_index": 2507946
}
```
</details>

update /sys/leader api docs

---

website/content/docs/auth/jwt/oidc-providers/auth0.mdx
website/content/docs/auth/jwt/oidc-providers/azuread.mdx
website/content/docs/auth/jwt/oidc-providers/forgerock.mdx
website/content/docs/auth/jwt/oidc-providers/gitlab.mdx
website/content/docs/auth/jwt/oidc-providers/google.mdx
website/content/docs/auth/jwt/oidc-providers/ibmisam.mdx
website/content/docs/auth/jwt/oidc-providers/keycloak.mdx
website/content/docs/auth/jwt/oidc-providers/kubernetes.mdx
website/content/docs/auth/jwt/oidc-providers/okta.mdx
website/content/docs/auth/jwt/oidc-providers/secureauth.mdx
website/content/docs/internals/architecture.mdx

🔍 [Deploy preview](https://vault-lds2uebl9-hashicorp.vercel.app/vault/docs/auth/jwt/oidc-providers/auth0)
This PR fixes: 
- Grammar error pointed out by https://github.com/hashicorp/vault/pull/19582 which couldn't be merged due to CLA.
- Page title had to use `#` instead of `##` --> all pages under **JWT/OIDC > OIDC Providers** menu

[DOCS] Fix page heading

---

sdk/logical/audit.go

- As TestInteg_KMIP_Audit showed, the x509.Certificate's big.Int SerialNumber is mangled when we do a deep clone of the LogInput's Request TLSConnection object.
- As the tls.ConnectionState does not have a Clone itself and we don't modify this field, it should be safe to just grab the existing reference into the cloned version.
This addresses a test failure that was introduced by https://github.com/hashicorp/vault/pull/24811 within ENT.

Copy the Connection reference within LogInput Clone()

---

vault/activity_log.go
vault/activity_log_test.go
vault/census.go
vault/logical_system_activity.go

JIRA: https://hashicorp.atlassian.net/browse/VAULT-22877
Ent PR: https://github.com/hashicorp/vault-enterprise/pull/5168
Description
A customer may choose to manually export the data using the CLI command regardless if they have chosen to opt in or out of automated reporting. This is especially true if a customer has chosen to opt out of automated reporting especially because they have to use the manual method. Manual reporting can also be used to export data where automated reporting fails. Therefore, as part of this effort, manual reporting will always be enabled from now on.

Census manual reporting : Always enable manual reporting CE changes

---

changelog/24710.txt
vault/activity/query.go
vault/activity_log.go
vault/activity_log_util_common.go
vault/external_tests/activity_testonly/activity_testonly_test.go

Updating the documentation will be in a different PR.

VAULT-22642: Include secret syncs in activity log responses

---

vault/identity_store_oidc_test.go

We achieve that by disabling parallelism and increasing a sleep time in the test. Based on some local testing, this won't fix the test, but it does make its intermittent failures less flaky.

Make TestOIDC_PeriodicFunc less flaky.

---

vault/activity_log.go
vault/external_tests/activity_testonly/activity_testonly_oss_test.go
vault/external_tests/activity_testonly/activity_testonly_test.go

This PR fixes some failures occurring in enterprise:
1. There was a bug in computing counts that only an enterprise test caught. The bug is now fixed and there's a test in CE that will catch a regression
2. The activity log can no longer be disabled for enterprise, so the test to disable it was moved to its own file with build constraints

Fix mount counts in activity log

---

vault/logical_system_custom_messages.go
vault/logical_system_custom_messages_test.go

This PR adds an additional validation step that ensures that the message parameter provided is indeed base64 encoded as described in the API documentation (see https://github.com/hashicorp/vault/pull/24845)

Add Validation for message Parameter in Create/Update Custom Message Operation

---

changelog/24864.txt
command/plugin_runtime_list_test.go
vault/logical_system.go
vault/logical_system_test.go

The `api` package expects the `"runtimes"` key to always be there or it errors, but the API was omitting it when empty.
https://github.com/hashicorp/vault/blob/cd76e4fbc113a11d584b9359aa7e527e546af0c9/api/sys_plugins_runtimes.go#L162-L164

List plugin runtimes API always includes a list even if empty

---

sdk/logical/audit.go
sdk/logical/request.go

Use the existing `Request.Clone()` method (thanks to @stevendpclark for pointing that out), and update said method with missing fields that `copystructure` couldn't sort out for us.

Audit: `LogInput.Request` Cloning update

---

builtin/credential/aws/pkcs7/ber.go
builtin/credential/aws/pkcs7/ber_test.go
changelog/24891.txt

backport of https://github.com/hashicorp/vault/pull/24891

backport 1.15: pkcs7 fix slice out-of-bounds panic

---

builtin/credential/aws/pkcs7/ber.go
builtin/credential/aws/pkcs7/ber_test.go
changelog/24891.txt

backport of https://github.com/hashicorp/vault/pull/24891

backport 1.13: pkcs7 fix slice out-of-bounds panic

---

builtin/credential/aws/pkcs7/ber.go
builtin/credential/aws/pkcs7/ber_test.go
changelog/24891.txt

backport of https://github.com/hashicorp/vault/pull/24891

backport 1.14: pkcs7 fix slice out-of-bounds panic

---

website/content/docs/platform/k8s/vso/index.mdx

fix bad spelling of `HashiCorp` (`HahsiCorp`)

fix typo in vso platform docs

---

changelog/24898.txt
vault/identity_store.go
vault/identity_store_oidc.go
vault/identity_store_oidc_test.go

This PR adds an [openid-configuration](https://developer.hashicorp.com/vault/api-docs/secret/identity/tokens#read-well-known-configurations) and [keys](https://developer.hashicorp.com/vault/api-docs/secret/identity/tokens#read-active-public-keys) API for a new _plugin token issuer_. The issuer will only be capable of internally issuing tokens to Vault plugins for workload identity federation exchanges.
The issuer will provide unauthenticated APIs with the following paths:
- `/v1/identity/oidc/plugins/.well-known/openid-configuration`
- `/v1/identity/oidc/plugins/.well-known/keys`
The approach makes the "plugins" segment above optional so that we can serve both the identity token issuer and plugin token issuer APIs using the same request handlers. I've called these "child" issuers, but I'm …

identity/tokens: adds plugin issuer with openid-configuration and keys

---

ui/app/components/clients/sync-bar-chart.hbs
ui/app/components/clients/sync-bar-chart.ts
ui/app/components/clients/vertical-bar-chart.js
ui/app/styles/core/charts.scss
ui/app/utils/chart-helpers.js
ui/package.json
ui/tests/integration/components/clients/sync-bar-chart-test.js
ui/types/client-counts.ts
ui/yarn.lock

This PR adds a component for rendering a vertical bar chart for secret sync data. It does not make use of the chart. 
**Tooltips with data and without**
**Fluid layout**
it will fill the width of its parent. To change the height, pass `@chartHeight={{360}}`

UI: Secret sync bar chart

---

vault/request_handling.go

- The specified delegated authentication error handler should not have to worry about re-implementing the invalid credential handler logic. It should only worry about how to return/format the error back to the client.

Call the invalid credential handler even with a delegated auth error handler

---

builtin/logical/pki/backend_test.go
builtin/logical/pki/cert_util.go
builtin/logical/pki/issuing/issue_common.go
sdk/helper/certutil/helpers.go

This moves code for parsing OtherSANs from the backend to the SDK.
Code for parsing Certificates into the template of Fields used to call the PKI Backend is currently in client code.  To use this code for PKI backend parsing (for auditing purposes among other things) we need to put it in the sdk.  To make this useful to the backend we need to extend it to use fields that don't exist on CAs - in particular OtherSANS.  We therefore need the OtherSANs code to also live in the backend.  This just moves the OtherSANs code to the backend.

Migration of OtherSANs Parsing Call to SDK helper from pki-issuer

---

website/content/docs/release-notes/1.15.0.mdx
website/content/docs/upgrading/upgrade-to-1.15.x.mdx
website/content/partials/known-issues/1_15_audit-use-of-log-raw-applies-to-all-devices.mdx

This PR contains a release about a known issue related to auditing data in a raw format with Vault versions `1.15.0` - `1.15.4` when any device is configured to use `log_raw` as an option.
Vercel deployment for page review:
1.15 Release notes: https://vault-2zbb1o8z8-hashicorp.vercel.app/vault/docs/release-notes/1.15.0
1.15 Upgrade Guide: https://vault-2zbb1o8z8-hashicorp.vercel.app/vault/docs/upgrading/upgrade-to-1.15.x#audit-devices-could-log-raw-data-despite-configuration

VAULT-23122: Known Issues: Audit devices using `log_raw`

---

ui/app/serializers/sync/destination.js
ui/tests/helpers/general-selectors.js
ui/tests/integration/components/sync/secrets/page/destinations/create-and-edit-test.js

Because we use `PATCH` to update destinations, sending a new object would add key value pairs to an existing `custom_tags` object for a destination. 
The backend added a `tags_to_remove` param to improve the form UX so that the `custom_tag` field will match any updates made to the form

Secrets Sync UI: Update serializer to use tags_to_remove param for updating custom_tags

---

changelog/24979.txt
vault/identity_store_oidc_provider.go
vault/identity_store_oidc_provider_test.go
website/content/api-docs/secret/identity/oidc-provider.mdx
website/content/docs/secrets/identity/oidc-provider.mdx

This PR adds `code_challenge_methods_supported` to Vault OIDC provider [metadata](https://github.com/hashicorp/vault/issues/24854). See [rfc8414#section-2](https://datatracker.ietf.org/doc/html/rfc8414#section-2) for a description of the metadata value and [`code_challenge_method`](https://developer.hashicorp.com/vault/api-docs/secret/identity/oidc-provider#code_challenge_method) for the methods we accept.
Resolves: https://github.com/hashicorp/vault/issues/24854

oidc/provider: adds code_challenge_methods_supported to metadata

---

website/content/docs/upgrading/upgrade-to-1.13.x.mdx

This is a minor update to add a section about undo logs, and upgrade details which include Consul storage users.

Docs: add undo logs section in upgrade to 1.13.x

---

ui/app/styles/helper-classes/spacing.scss
ui/lib/config-ui/addon/components/messages/page/create-and-edit-message-form.hbs

Add inline form info when user is creating a unauth message.

UI: Add form inline warning

---

changelog/25001.txt
ui/app/templates/components/dashboard/quick-actions-card.hbs
ui/tests/acceptance/dashboard-test.js
ui/tests/helpers/components/dashboard/dashboard-selectors.js
ui/tests/integration/components/dashboard/quick-actions-card-test.js
ui/tests/integration/components/sync/secrets/page/overview-test.js

In the Secret Sync feature work a new component was added to solve the same issue of being unable to search within directories using the Search Select component. I added this new component to the dashboard.
Fixes Issue[ #23979](https://github.com/hashicorp/vault/issues/23979).
https://github.com/hashicorp/vault/assets/6618863/6c9096da-2211-4249-940e-87a8e571a67a
Note: this cannot be backported because the new component only exists as of 1.16.0

Allow Dashboard's QA card to search for nested KVv2 secrets

---

vault/logical_system_custom_messages.go
vault/logical_system_custom_messages_test.go

This PR adds extra handling to the handleCreateCustomMessage and the handleUpdateCustomMessage methods to handle all possible cases of incomplete and invalid link specifications.
Incomplete link specifications are simply ignored, as if the link wasn't specified at all. This is fine because the client clearly didn't provide any parts of a link. Here are all of the incomplete link forms:
- `"link": null`
- `"link":{}`
- `"link":{"":null}`
- `"link":{"":""}`
Any custom message created or updated using any of the _above_ forms, will have its **link** property set to `null` in the response to a Read custom message operation.
Invalid link specifications cause an error to be returned, since the client did provide some part of a link. Here are all of the invalid link forms:
- `"link":{"":"<any …

VAULT-23433: Dealing with Incomplete link Object in Custom Messages

---

changelog/25014.txt
go.mod
go.sum

This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/7632356603

Update vault-plugin-auth-alicloud to v0.16.1

---

ui/lib/core/addon/components/text-file.js

Using the very helpful method described in [this blog post](https://balinterdi.com/blog/testing-async-dom-functions-in-ember-js/) (shoutout to @Monkeychip for the find!), I added a custom waiter to the text-file component so that the tests will wait for the upload to finish before tearing down the component, which I think is what's causing this failure in CI: 
```
Source:
TypeError: Cannot read properties of null (reading 'args')
at Object.<anonymous> (http://localhost:7357/ui/assets/tests.js:52630:47)
```

UI: Stabilize text-file test

---

.github/actions/set-up-go/action.yml

Ensure that on the Ent side private modules are downloaded without proxy
https://github.com/hashicorp/vault/pull/25013

Manual backport of #25013  to 1.15 

---

README.md

Build and CI no longer uses CircleCI. This PR removes the original CircleCI badge and adds a `build` and `ci` badge to represent the status of the associated GitHub Action workflows.
The header of the README will now look like the following:

update build and ci badges in README

---

vault/external_tests/audit/audit_filtering_test.go

Some of the checks were missing a trailing slash when retrieving a key from a map, which made them fail without failing the assertion. These were always extra checks anyways, so there isn't anything to fix in the actual code, but these changes will make audit tests a bit better.

Fix faulty assertions in external tests for audit

---

vault/rotation.go

this changes the check queue loop so that out-of-window credentials don't terminate the looping.
in the following scenario:
1) time 12:00AM, window 1 minute
2) time 12:00AM, window 2 minutes
if the queue gets checked at 12:01AM, then the first item needs to not break the loop, since the second item is still ready to rotate.

[Rotate Root POC] Fix Check Queue logic

---

scripts/cross/Dockerfile
scripts/docker/Dockerfile.ui
ui/package.json

Node 16 is EOL, so this change bumps Node to 18 which is LTS. 
I followed the instructions as outlined in the document called "Updating Node Version for Vault UI"

UI: Bump Node to v18

---

physical/raft/raft_test.go

This is my attempt at fixing https://github.com/hashicorp/vault-enterprise/actions/runs/7659299079/job/20874615221#step:12:9086
I say attempt because I can't reproduce this failure locally. But, from what I can tell, the tests in question are changing a package level variable, which, when done from multiple parallel tests, causes the race. I'm not sure if there's a way to provide locking at that granular of a level or not. We could lock around the call to the test itself, but that would have the same effect as just not running them in parallel. So I figured the simplest thing was just to not run the tests in parallel.

remove t.Parallel() from testBothRaftBackends

---

ui/app/components/clients/page/overview.hbs
ui/app/components/clients/page/token.hbs
ui/app/components/clients/page/token.ts
ui/app/templates/components/clients/running-total.hbs
ui/app/templates/components/clients/usage-stats.hbs
ui/tests/acceptance/clients/counts/overview-test.js
ui/tests/helpers/clients.js
ui/tests/integration/components/clients/page/token-test.js
ui/tests/integration/components/clients/running-total-test.js
ui/tests/integration/components/clients/usage-stats-test.js

This PR addresses a few things surrounding clients running totals and usage stats:
- fixes issue where the usage stats were not showing correctly on the overview page from an incorrect conditional wrapping the `RunningTotal` component
- updates to use ChartContainer for line chart in `RunningTotal` component
- Adds sync to `UsageStats` for display on the overview page
- Updates `UsageStats` total to reflect only entity and non-entity clients when viewed on the token page

Clients Usage Stats/Running Total Updates

---

vault/external_tests/raft/raft_binary/raft_test.go

Failure this is meant to fix here https://github.com/hashicorp/vault-enterprise/actions/runs/7659299079/job/20874605694
This is another failure I can't reproduce locally, but this was my thought on how to fix it. I also removed `t.Parallel()` since I wasn't sure how well that played with docker tests and I was speculating that maybe that was contributing to the instability (although maybe it's fine?)

Fix docker raft wal test

---

api/client_test.go

This caused a data race due to https://github.com/golang/go/issues/23842. `wg.Add` should not be outside the goroutine of the call to `wg.Wait`

Move wg.Add outside of goroutine

---

changelog/25095.txt
command/server.go
command/server/config_util_test.go
internalshared/configutil/config.go
internalshared/configutil/merge.go
internalshared/configutil/request_limiter.go
limits/registry.go
vault/core.go

This PR builds on top of #25093 to establish a reloadable break-glass config for disabling the request limiter.
Two follow-up PRs are needed:
1. Docs
2. Reload test

Request Limiter reloadable config

---

changelog/25098.txt
command/agent_test.go
command/server.go
command/server/config_test_helpers.go
command/server/test-fixtures/config3.hcl
http/handler.go
http/util.go
internalshared/configutil/listener.go
internalshared/configutil/listener_test.go
sdk/logical/request.go

This new nice-to-have configuration should allow operators to opt out of Request Limiting on a per-listener basis.
This PR builds on top of #25093.
The config allows Vault to remain protected in break-glass scenarios, providing a means to turn off the request limiter for specific tasks. We can encourage users to bypass the limiter for specific actions, rather than shutting it all off.
I've done some manual verification and dev-testing.

Request Limiter listener config opt-out

---

go.mod
go.sum

This PR updates the version of `github.com/hashicorp/vault-hcp-lib` which incorporates bug fixes that were merged in the following external PRs:
- https://github.com/hashicorp/vault-hcp-lib/pull/32
- https://github.com/hashicorp/vault-hcp-lib/pull/33
- https://github.com/hashicorp/vault-hcp-lib/pull/34

Bump github.com/hashicorp/vault-hcp-lib

---

vault/core.go

This must have snuck in with a bad rebase. I have a few tickets open for testing, so issues like this will be avoided in the future.

Drop extra LimiterRegistry Enable

---

physical/raft/chunking_test.go

Problem this is intended to fix:
https://github.com/hashicorp/vault-enterprise/actions/runs/7701361714/job/20987721199#step:12:3397

Don't call t.Parallel() when changing package level variables

---

ui/tests/acceptance/chroot-namespace-test.js
ui/tests/acceptance/client-dashboard-test.js
ui/tests/acceptance/dashboard-test.js
ui/tests/acceptance/mfa-login-enforcement-test.js
ui/tests/acceptance/mfa-login-test.js
ui/tests/acceptance/mfa-method-test.js
ui/tests/acceptance/oidc-config/clients-assignments-test.js
ui/tests/acceptance/oidc-config/clients-keys-test.js
ui/tests/acceptance/oidc-config/providers-scopes-test.js
ui/tests/acceptance/reduced-disclosure-test.js
ui/tests/acceptance/secrets/backend/database/workflow-test.js
ui/tests/acceptance/secrets/backend/kubernetes/configuration-test.js
ui/tests/acceptance/secrets/backend/kubernetes/credentials-test.js
ui/tests/acceptance/secrets/backend/kubernetes/overview-test.js
ui/tests/acceptance/secrets/backend/kubernetes/roles-test.js
ui/tests/acceptance/secrets/backend/ldap/libraries-test.js
ui/tests/acceptance/secrets/backend/ldap/overview-test.js
ui/tests/acceptance/secrets/backend/ldap/roles-test.js
ui/tests/integration/components/oidc/assignment-form-test.js
ui/tests/integration/components/oidc/client-form-test.js
ui/tests/integration/components/oidc/key-form-test.js
ui/tests/integration/components/oidc/provider-form-test.js

After moving to `ember-exam` and running tests in parallel there have been some cases where a test that required mirage would fail and looking at the logs it was using a different set of request handlers than what it should. The old pattern to use mirage handlers in tests was to globally define it in the environment which is no longer viable since tests are running at the same time and that would override the handlers used in other tests.
This PR removes all instances of globally setting the mirage handler in tests and updates to import the required handle directly into the test for use.

Import Mirage Handlers in Tests

---

changelog/24978.txt
command/commands.go
command/server.go
command/server/config.go
command/server/config_test_helpers.go
command/server/test-fixtures/config.hcl
http/sys_config_state_test.go
sdk/helper/pluginutil/run_config.go
sdk/helper/pluginutil/runner.go
vault/core.go
vault/external_plugin_container_test.go
vault/plugincatalog/plugin_catalog.go
vault/plugincatalog/plugin_catalog_test.go
vault/plugincatalog/plugin_runtime_catalog.go
vault/testing.go
website/content/docs/configuration/index.mdx

To run containerized plugins under systemd with PrivateTmp=true, users need control over the tmpdir used for Unix sockets (see #23215). Previously we supported this solely with a `VAULT_PLUGIN_TMPDIR` env var, and this PR adds the option to the config file as well. As with other settings supported in config and env, the env takes precedence.

Support setting plugin TMPDIR in config as well as env

---

command/agentproxyshared/cache/static_secret_capability_manager_test.go

This seems to be contained to tests. Everywhere else in the code, access to this method is blocked by a lock, we simply didn't consult the lock in the tests. That's now fixed.

Fix data race with readable paths in our tests

---

tools/tools.sh

I hit an issue where running linter locally failed because `tools.sh` was checking for existence of `gotestsum` and recommending `make external-tools` to fix, but `make external-tools` didn't actually install `gotestsum`.
It's possible there was a reason for this I don't know but this change fixed things locally so that `make external-tools` actually installed gotestsum and make the checker pass again.

Install gotestsum as well as check for it

---

vault/identity_store_oidc_test.go

This PR attempts to fix a [flakey](https://github.com/hashicorp/vault/actions/runs/7647906091/job/20839788755) OIDC key rotation test. I've stopped the rollback manager which invokes periodic functions of backends. We're manually invoking the periodic function of the identity store which handles key rotations. I'm not fully convinced the rollback manager is the issue, but this will eliminate one potential reason for the flakiness. I've also slightly refactored the test to simplify it.
I ran this test ~5 times [in CI](https://github.com/hashicorp/vault/actions/runs/7719207517) and ~1000 times on my laptop without a failure. Running locally I used `go test -run=TestOIDC_PeriodicFunc -count 1000 -parallel 8 -failfast`.

identity/oidc: attempt to fix flakey key rotation test

---

.github/workflows/test-go.yml
command/command_testonly/server_testonly_test.go
command/server_test.go
command/server_util.go
http/handler.go
limits/limiter.go
limits/registry.go
sdk/logical/request.go
vault/core.go
vault/logical_system.go
vault/logical_system_limits.go
vault/logical_system_limits_testonly.go

This PR introduces a new `testonly` endpoint for introspecting the RequestLimiter state. It makes use of the endpoint to verify that changes to the `request_limiter` config are honored across reload.
In the future, we may choose to make the `sys/internal/request-limiter/status` endpoint available in normal binaries, but this is an expedient way to expose the status for testing without having to rush the design.
In order to re-use as much of the existing `command` package utility funcionality as possible without introducing sprawling code changes, I introduced a new `server_util.go` and exported some fields via accessors.
The tests shook out a couple of bugs (including a deadlock 😅 and lack of locking around the core `limiterRegistry` state).
This resolves VAULT-23584.

Request Limiter Reload tests

---

command/command_testonly/server_testonly_test.go

While introducing the new `testonly` package for testing Request Limiter reloads, we didn't initialize a license. As a result, the test fails in CI with the following error:
> Error initializing core: license check failed: no autoloaded license provided. Licenses can be obtained at https://vaultproject.io/trial
>    server_testonly_test.go:142: timeout
I wasn't able to reproduce locally because I have my vault license environment variable set!
This PR fixes the issue by setting `EnvVaultLicense` with the contents of the CI License.

Initialize license in command_testonly for enterprise

---

changelog/25171.txt
vault/logical_system.go
vault/seal/seal.go

Two changes:
- Add a fully_wrapped field to seal-backend-status
- Always attempt to find an in common wrapper, not just in the case a
blobInfo contains only one entry.  If none can be found, warn.

Seal HA Improvements, CE side

---

vault/seal/seal_testing.go

Should be a pointer to ToggleableWrapper, so we don't get a fresh mutex each time

Fix a race in ToggleableWrapper (test struct)

---

website/content/api-docs/secret/transform.mdx

Added missing parameter `expiration` that should be [part of API `/transform/encode`](https://developer.hashicorp.com/vault/api-docs/secret/transform#encode)
INITIAL: <img width="200" alt="Screenshot 2024-02-01 at 16 48 01" src="https://github.com/hashicorp/vault/assets/974854/e519d944-8dac-42dc-942b-3b3900445585">

Docs: Tranform secrets encode parameter: `expiration` added.

---

ui/lib/sync/addon/components/secrets/destination-header.hbs
ui/lib/sync/addon/components/secrets/page/destinations/destination/secrets.hbs
ui/lib/sync/addon/components/secrets/page/destinations/destination/secrets.ts
ui/lib/sync/addon/components/secrets/page/destinations/destination/sync.ts
ui/tests/helpers/sync/sync-selectors.js
ui/tests/integration/components/sync/secrets/destination-header-test.js
ui/tests/integration/components/sync/secrets/page/destinations/destination/sync-test.js

This PR addresses feedback that came out of a demo run with the UI.
- Clear secret path after successful sync submission. The feedback was that it wasn't completely clear if the submission was successful which led to users click the submit button numerous times.
https://github.com/hashicorp/vault/assets/24611656/95e6e187-7a12-4dcd-9ebd-5efa48ab0953
- Added refresh list button to destination secrets view. Since the backend needs to reach out to the destination to sync the secret, a user may view the list before the operation is complete and the synced secret does not appear in the list.

Secrets Sync Demo Feedback

---

Makefile

Git doesn’t allow hooks to be in-repo which prevents branch specific hooks. To get around this we’ve historically copied our hooks from .hooks into .git/hooks when running `make prep`.
That sort of works but has the following issues:
* If your hooks call into files in-repo and they are modified between branches you have to re-sync to resolve it
* Remembering to sync the hooks is cumbersome
We can’t exactly get around the first issue. It’s always possible that if you change branches and don’t update your hooks you could run into this problem if you try to commit without updating them. But we can make it less likely to fail by:
* Always syncing the hooks whenever make is called
* Updating the files in the hooks on all maintained branches to be consistent

[QT-669] Automatically synchronize git hooks on make invocation

---

website/content/docs/concepts/client-count/index.mdx

Update documentation to explain that `client_id` will not appear in audit log entries when the `client_id` was empty as part of the request being audited.
Resolves VAULT-23697
`/vault/docs/concepts/client-count#auditing-clients`

Docs: audit log: `client_id`

---

changelog/25217.txt
go.mod
go.sum

This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/7787534864

Update vault-plugin-auth-alicloud to v0.17.0

---

ui/app/models/auth-config/kubernetes.js
ui/tests/helpers/openapi/auth-model-attributes.js

This PR adds a new Kubernetes config param, `use_annotations_as_alias_metadata`. This was caught via one of the OpenAPI tests. 
The new param was added in [this PR](https://github.com/hashicorp/vault-plugin-auth-kubernetes/pull/226) and Vault is updated to consume the new version in [this PR](https://github.com/hashicorp/vault/pull/25207) 
Config form has param:

UI: k8s auth openapi update

---

vault/expiration.go
vault/token_store.go

Looking through this issue, there were two potential paths. First, we could have returned an error from the decrypt. Second, we could have kept the return as-is and handled the panic.
I opted for the second option after a bit of research/toying/deliberation. Changing the erroring of decryption of batch tokens has security impacts, and requires a lot more testing as it has the chance to be quite a disruptive refactor. While we wouldn't return nil, nil if implementing it today, in the interests of keeping impact low, I thought it best to document the behaviour and some of the motivation as well as fixing the panic, instead of refactoring an important area we're hazy about.
Resolves https://github.com/hashicorp/vault/issues/22065

VAULT-20086 Handle potential panic

---

ui/lib/sync/addon/components/secrets/page/destinations/create-and-edit.ts
ui/tests/acceptance/sync/secrets/destination-test.js
ui/tests/helpers/general-selectors.js

This PR fixes an issue with editing a sync destination and credential fields being overwritten with masked placeholder values. Since the server always returns credentials as `*****`, when a user would input a value and save, the model was being marked as dirty. If the model was saved again, the credential(s) would be returned from `changedAttributes` and the masked value would be sent in the `PATCH` request. To work around this, the model is now unloaded after save success since it is fetched when transitioning to the details route.

Sync Destination Edit Bug

---

changelog/25231.txt
go.mod
go.sum

This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/7801579038

Update vault-plugin-secrets-gcpkms to v0.16.0

---

changelog/25233.txt
go.mod
go.sum

This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/7802282077

Update vault-plugin-auth-gcp to v0.16.2

---

builtin/credential/ldap/path_config.go
vault/rotation.go

this adds some code that allows the system to track rotationIDs, allowing schedules to be updated without a new config entry in the manager.

rotation POC: detect schedule updates

---

vault/eventbus/bus.go
vault/eventbus/bus_test.go
vault/eventbus/filter.go
vault/eventbus/filter_test.go

This allows other parts of the code to be able to watch for changes to the event filter map, i.e., so that they can know when the global or local filters are changed.
This is going to be used in an upcoming enterprise PR for event replication to performance secondaries.

events: Add filter watch function

---

.github/workflows/ci.yml

Don't rely on the pass/fail result of the CI workflow for notifications. We do this to ensure we notify Slack on failures but still allow for merging.

ci: always trigger slack notification for any failure

---

changelog/25245.txt
go.mod
go.sum

This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/7807047877

Update vault-plugin-auth-oci to v0.15.1

---

changelog/25251.txt
go.mod
go.sum

This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/7817415528

Update vault-plugin-secrets-openldap to v0.12.0

---

changelog/25253.txt
go.mod
go.sum

This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/7818119667

Update vault-plugin-secrets-mongodbatlas to v0.11.0
