changelog/25257.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/7818366266
=> Update vault-plugin-secrets-alicloud to v0.16.0

changelog/25264.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/7819335409
=> Update vault-plugin-database-mongodbatlas to v0.11.0

changelog/25269.txt, ui/lib/core/addon/components/masked-input.hbs, ui/lib/core/addon/components/masked-input.js, ui/tests/integration/components/masked-input-test.js
This PR fixes an issue where non-string values would not be copied from the masked input view, and would throw an error in the console like 
```
Uncaught (in promise) Error: Assertion Failed: `hds-clipboard` modifier - `text` argument must be a string - provided: object
```
=> UI: Fix copy button not working for non-string masked values

vault/logical_system.go
This PR fixes enterprise tests that were encountering read-only storage errors for local-only mounts. The local-only mounts were trying to generate the OIDC default key which involves a storage write. We will simply log a warning and allow the local-only mount to be created for now.
This approach has an edge case where plugin workload identity would not work if:
- The local-only mount was the first mount ever enabled in Vault
- No identity token roles have been created
- No OIDC provider clients have been created
I'm going to think on a better solution for this. In the meantime, this PR fixes the tests.
=> identity: skip oidc default key generation on read-only storage error for local mounts

ui/lib/core/addon/components/masked-input.js, ui/tests/integration/components/masked-input-test.js
There was an issue where the test-ui GH action was being skipped but the check was reporting as passed which led to some PR's being merged that had failures and this PR fixes them.
=> Test Fixes

changelog/25289.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/7831119744
=> Update vault-plugin-database-redis to v0.2.3

go.mod
I'm surprised by no go.sum changes, but I did run a `go mod tidy`, and it's far from impossible.
=> Use new SDK and API versions for 1.16.0

ui/tests/acceptance/sync/secrets/destination-test.js, ui/tests/acceptance/sync/secrets/destinations-test.js, ui/tests/acceptance/sync/secrets/overview-test.js
Since mirage is used for all of the sync related requests in acceptance tests, this PR removes the enterprise label from the module names so that the tests will run on PR's in the community repo.
=> Remove Enterprise Label from Sync Acceptance Test Module Names

changelog/25296.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/7833345940
=> Update vault-plugin-database-redis-elasticache to v0.3.0

go.mod, go.sum
The plugin update reverts a dependency upgrade which fails to build on 32-bit systems.
=> Update couchbase database plugin to v0.10.1

go.mod, go.sum
This is needed so we can fix a go.mod issue in vault-ent
=> update opentelemetry dependencies

builtin/logical/pki/cert_util_test.go
Allow remarkably long time for certificate generation due to slowness of night-ci runners.
=> Fix test to be less flacky

http/handler.go
- CE fix for properly forwarding the EST .well-known requests to performance replicas internally instead of redirecting through http headers
=> Forward EST .well-known requests on performance replicas

changelog/25329.txt, helper/testhelpers/testhelpers.go, helper/testhelpers/teststorage/teststorage.go, sdk/helper/testcluster/replication.go, sdk/helper/testcluster/util.go, vault/testing.go
Add WaitForMatchingMerkleRootsClients and Clients to sdk testcluster.  Fix internal TestCluster.SetRootToken, which wasn't updating the builtin clients' token.  Improve some error messages.
=> Minor improvements to test cluster libraries

ui/app/models/auth-config/jwt.js, ui/tests/helpers/openapi/auth-model-attributes.js
This PR fixes the test that alerts us to a new JWT config attribute. As follow-on work, we need to handle the new attribute (which is of a new type, `objectArray`).
=> UI: Fix openAPI test for JWT

changelog/25335.txt, ui/app/components/token-expire-warning.hbs, ui/app/components/token-expire-warning.js
Adds a redirect back to the current URL if the user's token expires and they click "reauthenticate". 
This PR fixes #10963
=> UI: Redirect after logging in from token expiry

builtin/logical/transit/backend.go, builtin/logical/transit/path_decrypt.go, builtin/logical/transit/path_encrypt.go, builtin/logical/transit/path_hmac.go, builtin/logical/transit/path_rewrap.go, builtin/logical/transit/path_sign_verify.go, changelog/25336.txt
- Leverage defer statements to Unlock the fetched policy to avoid issues with forgetting to manually Unlock during each return statement
Fixes: https://github.com/hashicorp/vault/issues/25325
=> Transit: Release locks using defer statements

ui/app/models/sync/destination.js, ui/lib/sync/addon/routes/secrets/destinations/destination.ts, ui/tests/acceptance/sync/secrets/destination-test.js, ui/tests/integration/components/sync/secrets/destination-header-test.js, ui/types/vault/models/sync/destination.d.ts
If a purge has been initiated for a destination the user is unable to edit the destination config or sync secrets. This PR hides those actions from the destination view and adds a redirect if attempting to access the route.
=> Hide Sync Destination Actions When Purging

.github/scripts/changed-files.sh
A PR could set the `ui-changes` to true even if there is no ui-changes. [Example](https://github.com/hashicorp/vault/actions/runs/7848168666/job/21418704533#step:3:3134):
```
'40330b2eada30269f09e47d20a08ad9a660b34e2'
Run ./.github/scripts/changed-files.sh pull_request 25336/merge main
./.github/scripts/changed-files.sh pull_request 25336/merge main
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
From https://github.com/hashicorp/vault
* branch                  main       -> FETCH_HEAD
app-changed=false
docs-changed=false
ui-changed=true
files='builtin/logical/transit/backend.go
builtin/logical/transit/path_decrypt.go
builtin/logical/transit/path_encrypt.go
builtin/logical/transit/path_hmac.go
builtin/logical/transit/path_rewrap.go
builtin/logical/transit/path_sign_verify.go …
```
=> remove regular expression comparison in a GHA script

go.mod, go.sum
v2.7.x overflows on 386 targets:
../../../.go/pkg/mod/github.com/couchbase/gocb/v2@v2.7.0/search/internal.go:31:62: cannot use math.MaxUint32 (untyped int constant 4294967295) as int value in argument to fmt.Errorf (overflows)
This rolls us back to 2.6.5 until it's fixed upstream.
=> Rollback couchbase/gocb/v2 to v2.6.5 for 386 compat

.github/workflows/test-go.yml
* Namespace our data race logs so that other workflows don't use them to
set their status[0].
* Namespace our test results to avoid downloading other workflow
results.
* Handle multiline output of data race results
[0] https://github.com/hashicorp/vault-enterprise/actions/runs/7875954928/job/21490054433?pr=5411#step:3:39
=> ci: namespace data race logs

physical/raft/raft_test.go
A recent refactor to ensure all our raft tests run against both backend implementations also introduced a subtle new issue.
Because the `t` was being captured by the func passed as a test body, it was actually the parent's `t` which will panic whenever a test fails because the subtest goroutine called `Fatal` on the parent's `t`.
This small refactor fixes that so that the `t` used in test bodies is now the subtest `t` being passed in.
=> Fix raft tests so they don't capture the parent's t

.github/actions/install-external-tools/action.yml, .github/actions/set-up-gosimports/action.yml, tools/tools.sh
https://github.com/hashicorp/vault/pull/25383 added gosimports to the list of external tools that are required. The precheck for some linting workflows fail because we didn't add a corresponding workflow to install them.
=> [QT-670] ci: install gosimports

changelog/25364.txt, ui/app/routes/vault/cluster/access/method.js
This PR skips the OpenAPI call on auth methods which are not managed in the UI.  Resolves #24160
=> UI: Skip OpenAPI call for unmanaged auth methods

ui/app/components/sidebar/nav/cluster.js, ui/tests/acceptance/chroot-namespace-test.js
Logging in as root token to chroot listener should show the same nav items as logging in as root token to a child namespace. This PR correctly calculates what to show in the main nav.
=> UI: fix items displayed in sidenav for chroot

go.mod, go.sum
The raft library was [updated](https://github.com/hashicorp/vault-enterprise/commit/160f3d21fdc8ccda5707e0ae67f2738f01ffda75) with a manual backport without updating the [other required dependencies](https://github.com/hashicorp/vault-enterprise/commit/376812adaf08e1648566e62e2ed394434067c4ff). This has caused the issue with the autopilot.
Example test failure: https://github.com/hashicorp/vault-enterprise/actions/runs/7910970187/job/21594549679
=> revert accidental raft version update

ui/app/adapters/capabilities.js, ui/app/adapters/control-group.js
This is to resolve this error: 
which displayed locally as:
```
Async Request leaks detected. Add a breakpoint here and set store.generateStackTracesForTrackedRequests = true;to inspect traces for leak origins 
```
This error also stopped failing after this fix. But hard to know if it's related
=> UI: Control group flaky enterprise test fix attempt 1.14.x

Dockerfile
Fixes CVE's in sqlite and gnutls packages.
=> PSA-714 - update ubi-minimal to 8.9 for security fixes

audit/entry_formatter.go, changelog/25443.txt, vault/audit_broker.go
This PR addresses a potential race condition which occurred when an SSCT is present in the auth related audit entry.
It removes some unrequired code which captured the current headers, and moves the logic for updating the client token with the SSCT to the entry formatter which deals with a cloned version of the input.
Previous race detection occurred in `command/agentproxyshared/auth TestAuthHandler`
=> Audit: Extracted SSCT related auditing code to formatter node

builtin/credential/cert/backend.go, builtin/credential/cert/path_certs.go, builtin/credential/cert/path_config.go, builtin/credential/cert/path_crls.go, builtin/credential/cert/path_login.go, builtin/credential/cert/path_login_test.go, changelog/25421.txt, go.mod, go.sum, website/content/api-docs/auth/cert.mdx
Previously, trusted certs were loaded and parsed on every login call.  This
is both slow, and means a copy of the trusted certs is in memory per login. 
For highly concurrent use this raises Vault's memory usage unnecessarily.
=> Cache trusted cert values, invalidating when anything changes

website/content/docs/concepts/identity.mdx
The large paragraph is hard to read and it's easy to miss crucial details around when membership in an external group will be updated.
Membership isn't updated when the configuration of the external group is changed, which can be counterintuitive.
=> Clarify when external group membership is updated

ui/tests/helpers/openapi/auth-model-attributes.js
Update expected response for auth-config/cert
There don't seem to be user-facing changes 🤔 
Since the original PR was backported to 1.14, we will do the same for this one
=> UI: Update openAPI response for cert auth config

changelog/25436.txt, ui/app/adapters/transform.js, ui/app/models/transform.js, ui/tests/unit/adapters/transform-test.js
In 1.6 general requests to `/transform` (without `:type`) as part of the URL was deprecated [docs](https://developer.hashicorp.com/vault/api-docs/secret/transform#create-update-transformation-deprecated-1-6)
I decided against glimmerizing for backportability since this will go back to every supported release. Changes in this PR include:
- adds `deletion_allowed` to all transform types
- adds the third type, `tokenization` and associated [params](https://developer.hashicorp.com/vault/api-docs/secret/transform#create-update-tokenization-transformation)
- each transform type makes a request to the specific `:type` endpoint (e.g.`/transform/transformations/fpe/:name`
=> UI: add deletion_allowed to transform, add tokenization transform type

changelog/25095.txt, command/command_testonly/server_testonly_test.go, command/server.go, command/server/config_util_test.go, internalshared/configutil/request_limiter.go, vault/core.go
This PR flips the logic for the Request Limiter, setting it to default disabled.
We allow users to turn on the global Request Limiter, but leave the Listener configuration as a "disable per Listener".
=> Disable Request Limiter by default

audit/entry_filter.go, audit/entry_formatter.go, audit/entry_formatter_test.go, audit/event.go, audit/event_test.go, audit/nodes_test.go, audit/options.go, audit/options_test.go, audit/types.go
Started to move code out of `types.go` which was intended as a temporary place to collect types etc. 
For example:
* `EntryFilter` => `audit/entry_filter.go`
* `EntryFormatter` => `entry_formatter.go`
* `AuditEvent` => `audit/event.go`
* `Options` => `audit/options.go`
=> Audit: some refactoring out of types.go

audit/types.go
`EntryFormatterWriter` and the `Writer` interface are no longer required.
They were maintained during `1.15.x` as we allowed customers a way to revert to non-eventlogger audit behaviour, but this flag has been removed.
=> Audit: Removed unused code

website/content/api-docs/auth/jwt.mdx, website/content/docs/auth/jwt/index.mdx
This PR updates the JWT auth documentation to include the new `jwks_pairs` parameter added in https://github.com/hashicorp/vault-plugin-auth-jwt/pull/277.
=> auth/jwt: adds documentation for multi-jwks config parameter

builtin/credential/cert/backend.go, builtin/credential/cert/path_certs.go, builtin/credential/cert/path_config.go, builtin/credential/cert/path_crls.go, builtin/credential/cert/path_login.go, builtin/credential/cert/path_login_test.go, changelog/25421.txt, go.mod, go.sum, website/content/api-docs/auth/cert.mdx
=> Cache trusted cert values, invalidating when anything changes (#25421)

changelog/25524.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/7977649077
=> Update vault-plugin-secrets-openldap to v0.12.1

changelog/25497.txt, command/agent/exec/exec.go, command/agent/template/template.go, command/agentproxyshared/auth/auth.go, command/agentproxyshared/auth/auth_test.go, command/agentproxyshared/helpers.go, sdk/helper/consts/agent.go
Link to ENT PR: https://github.com/hashicorp/vault-enterprise/pull/5444
closes https://github.com/hashicorp/vault/issues/12566
closes https://github.com/hashicorp/vault/issues/22789
closes https://github.com/hashicorp/vault/issues/24657
=> Added exponential backoff

changelog/25500.txt, ui/app/models/sync/association.js, ui/app/models/sync/destination.js, ui/app/models/sync/destinations/aws-sm.js, ui/app/models/sync/destinations/azure-kv.js, ui/app/models/sync/destinations/gcp-sm.js, ui/app/models/sync/destinations/gh.js, ui/app/models/sync/destinations/vercel-project.js, ui/app/serializers/sync/association.js, ui/lib/core/addon/components/form-field.hbs, ui/lib/sync/addon/components/secrets/page/destinations.hbs, ui/lib/sync/addon/components/secrets/page/destinations.ts, ui/lib/sync/addon/components/secrets/page/destinations/destination/secrets.hbs, ui/lib/sync/addon/components/secrets/page/destinations/destination/secrets.ts, ui/lib/sync/addon/components/secrets/page/destinations/destination/sync.hbs, ui/mirage/factories/sync-destination.js, ui/mirage/handlers/sync.js, ui/tests/helpers/sync/sync-selectors.js, ui/tests/integration/components/form-field-test.js, ui/tests/integration/components/sync/secrets/page/destinations/create-and-edit-test.js
UI updates adding `granularity` field to a sync destination. 
- Added granularity field to destination form
- Added `secret key` badge to list view 
- Add copy to popup menu so user knows any actions performed on a key will apply to the secret, not the individual key. I updated to use the `Hds::Dropdown` so that adding copy to the popup menu was cleaner
=> Sync UI: Add granularity to sync destinations

command/commands.go
This is not going to be enabled in 1.16, so we can remove it from the default list of backends.
This removes about 600 KB of dead code from the
binary.
We can add this back in when the rest of the
event plugin endpoints are merged.
=> Don't load SQS events backend by default (for now)

website/content/docs/internals/telemetry/metrics/all.mdx, website/content/docs/internals/telemetry/metrics/secrets-sync.mdx, website/content/partials/telemetry-metrics/vault/secrets-sync/associations.mdx, website/content/partials/telemetry-metrics/vault/secrets-sync/destinations.mdx, website/data/docs-nav-data.json
Metrics on the `sys/metrics` endpoints have this format:
```
(...)
{
"Labels": {
"destination-type": "all"
},
"Name": "vault.secrets-sync.associations.count",
"Value": 15
},
{
"Labels": {
"destination-type": "gcm-sm"
},
"Name": "vault.secrets-sync.associations.count",
"Value": 10
},
{
"Labels": {
"destination-type": "azure-kv"
},
"Name": "vault.secrets-sync.associations.count",
"Value": 5
},
{
"Labels": {
"destination-type": "all"
},
"Name": "vault.secrets-sync.destinations.count",
"Value": 3
},
{
"Labels": {
"destination-type": "gcp-sm"
},
"Name": "vault.secrets-sync.destinations.count",
"Value": 2
},
{
"Labels": {
"destination-type": "azure-kv"
},
"Name": "vault.secrets-sync.destinations.count",
"Value": 1
},
(...)
```
=> Added sync telemetry doc

changelog/25509.txt, vault/logical_system_paths.go
Fixing the response fields to match the correct names and types declared in `http/sys_rekey.go`:
https://github.com/hashicorp/vault/blob/633dae1a6a6f11e4e64f42bb385838454f555523/http/sys_rekey.go#L369-L371
Fixing this and releasing the corresponding `openapi.json` should resolve https://github.com/hashicorp/vault-client-go/issues/251
=> openapi: Fix response fields for rekey operations

ui/app/models/sync/destinations/aws-sm.js, ui/app/models/sync/destinations/gcp-sm.js, ui/app/serializers/sync/destination.js, ui/lib/sync/addon/components/secrets/page/destinations.ts, ui/mirage/factories/sync-destination.js, ui/tests/integration/components/sync/secrets/page/destinations-test.js, ui/tests/integration/components/sync/secrets/page/destinations/create-and-edit-test.js
This PR adds some new fields to the aws and gcp sync destinations and fixes a couple of bugs:
- adds `role_arn` and `external_id` to aws-sm destination
- adds `project_id` to gcp-sm destination
- normalizes granularity returned as `granularity_level` in destination response
- routes to overview on destination delete success from list view to align with delete action on destination view
=> Sync Destination Updates

website/content/docs/ui/custom-messages.mdx, website/content/docs/ui/index.mdx, website/data/docs-nav-data.json
This PR includes suggestion for https://github.com/hashicorp/vault/pull/25435
Changes:
- Navigation --> moved "Vault UI" immediately after CLI (before the Vault Agent docs)
- Instead of creating `custom-messages` folder, add `custom-messages.mdx` under the `ui` folder
- Added an overview page (`index.mdx`) which covers the server configuration and add a link to tutorials
=> Restructuring suggestion - UI customer messages

website/content/docs/release-notes/1.16.0.mdx, website/content/docs/upgrading/upgrade-to-1.16.x.mdx, website/content/partials/known-issues/1_16-default-policy-needs-to-be-updated.mdx, website/data/docs-nav-data.json
When upgrading a Vault server to version 1.16.0, the Vault UI will no longer be able to display the version because it is now using a different endpoint. To account for this, the **default** policy has been updated to allow access to this endpoint, but the change is not applied to an existing **default** policy. This note serves to inform the users that they need to make a small change to the **default** policy to allow the Vault UI to retrieve the version.
=> Document known issue to release notes and upgrade guide for 1.16.0

website/content/docs/release-notes/1.16.0.mdx, website/content/docs/upgrading/upgrade-to-1.16.x.mdx, website/content/partials/known-issues/1_16-default-lcq-pre-1_9-upgrade.mdx
Default Lease Count Quotas are enabled for new clusters by consulting Vault's
past versions.
However, the version store was introduced in 1.9. As a result, upgrading from a
version prior to 1.9 enables the Default Lease Count Quota.
Added a Known Issue to the upgrade doc.
=> Default Lease Count Quota: Document pre-1.9 upgrades

website/content/docs/concepts/lease-count-quota-exceeded.mdx, website/content/docs/enterprise/lease-count-quotas.mdx, website/data/docs-nav-data.json
This PR adds a breadcrumb for any users seeing the `quota exceeded` error message to guide them on their journey.
=> Lease Count Quotas: include error message in docs

website/content/docs/plugins/plugin-management.mdx, website/content/docs/upgrading/upgrade-to-1.16.x.mdx
Adds docs for the new order of priority for plugin-specific environment variables. Also adds some explicit instructions on how to use those to configure different HTTP proxy settings for different plugins.
Depends on https://github.com/hashicorp/vault/pull/25540 for the upgrade guide page getting created.
=> Docs: Plugin env priority updates for 1.16.0

website/content/docs/release-notes/1.16.0.mdx, website/content/docs/upgrading/upgrade-to-1.16.x.mdx
Some formatting issues were introduced in the rebase shuffle for https://github.com/hashicorp/vault/commit/8f9e884beebfa660a946dc7a464882438091705e
This PR addresses those to fix the upgrade guide.
Note that the breaking change has not yet been backported, so it will be manually fixed in the backport PR (https://github.com/hashicorp/vault/pull/25590) before merging.
=> fix 1.16 upgrade guide

ui/app/models/config-ui/message.js
While writing the docs for custom messages, I noticed that the capabilities path wasn't correct for update, delete, and read. Update, delete, and read require the path to be "sys/config/ui/custom-messages/:id"
```
path "sys/config/ui/custom-messages" {
capabilities = ["list", "create"]
}
path "sys/config/ui/custom-messages/:id" {
capabilities = ["read"]
}
```
```
path "sys/config/ui/custom-messages" {
capabilities = ["list"]
}
path "sys/config/ui/custom-messages/:id" {
capabilities = ["read", "update"]
}
```
```
path "sys/config/ui/custom-messages" {
capabilities = ["list"]
}
path "sys/config/ui/custom-messages/:id" {
capabilities = ["delete"]
} 
```
=> UI: Fix capability path for custom messages

builtin/audit/syslog/backend.go
This code is no longer used, as `event/sink_syslog.go` handles it (see: `NewSyslogSink`)
https://github.com/hashicorp/vault/blob/main/internal/observability/event/sink_syslog.go#L38-L43
=> Audit: syslog: remove unused code

ui/lib/sync/addon/components/secrets/page/overview.hbs, ui/lib/sync/addon/templates/secrets/overview.hbs, ui/mirage/handlers/sync.js, ui/tests/integration/components/sync/secrets/page/overview-test.js
For the beta release `Total secrets` is a more useful metric for users because this number will likely correlate to the sync client count. `Associations` formally contributed to the client count number, but for now is a somewhat confusing count as it refers to the link between a secret and a destination. We're considering adding it back to the overview when the sync billing is live after design has time to consider the best way to display all of the counts.
=> Ui: update overview metric to total secrets instead of associations

ui/app/components/generated-item-list.js, ui/app/templates/components/generated-item-list.hbs, ui/app/templates/vault/cluster/access/namespaces/index.hbs, ui/lib/kmip/addon/templates/credentials/index.hbs, ui/lib/kmip/addon/templates/scope/roles.hbs, ui/lib/kmip/addon/templates/scopes/index.hbs
On list items that make use of the component's `callItem` method, we need to show the modal based on the item being deleted. Otherwise, a modal shows for each list item and it calls delete on the last item in the list (the top modal). For example, create 2 namespaces, try to delete the first one in the list, and you will see the deletion actually happens on the last item in the list. 
The only lists using `Item.callMethod` are generated auth items (eg. userpass users), namespaces, and kmip scopes/roles/creds. 
This bug was introduced in #25588, so has not been released to customers. Thus, I'm not including a changelog.
=> UI: Fix delete from list using Item.callMethod

.release/ci.hcl
This should cause CRT to trigger the [crt-generate-sbom](https://github.com/hashicorp/security-generate-release-sbom/blob/main/.github/workflows/crt-generate-sbom.yml) workflow post-release. Currently that workflow just stores the SBOM as a GitHub Actions Workflow Artifact. The purpose of this change is to establish the integration between Vault and Vault Enterprise releases and our SBOM-generating workflow. Once this link is established, we will continue to work on the SBOM side of things and shouldn't need to make further changes here.
See [PSP-1992](https://hashicorp.atlassian.net/browse/PSP-1992) and related tickets for more details.
**Question for reviewer:** do I need to make a similar change in Vault Enterprise, or will this be automatically ported there as well? Thanks. …
=> release: add config to trigger SBOM creation

ui/app/models/sync/destination.js, ui/lib/core/addon/components/form-field.hbs, ui/lib/core/addon/helpers/sync-destinations.ts, ui/lib/sync/addon/routes/secrets/destinations/create/destination.ts, ui/mirage/factories/sync-destination.js, ui/tests/acceptance/sync/secrets/destinations-test.js, ui/types/vault/helpers/sync-destinations.ts
This PR sets the granularity default depending on type. GitHub & Vercel have a default Granularity level of `secret-key`, the others are `secret-path`. It also updates the `secret_name_template` subtext to use accurate Go syntax
As a follow-on improvement we'll add `secret_name_template` default values to the form, but this requires a little more UX/design consideration because the default template depends on granularity
=> UI: add default granularity depending on type, add optional to secret_name_template

audit/entry_formatter.go, audit/entry_formatter_test.go, audit/types.go, builtin/audit/file/backend.go, builtin/audit/file/backend_test.go, builtin/audit/socket/backend.go, builtin/audit/socket/backend_test.go, builtin/audit/syslog/backend.go, builtin/audit/syslog/backend_test.go, changelog/25605.txt, helper/testhelpers/corehelpers/corehelpers.go, vault/audit.go, vault/audit_broker.go, vault/audit_broker_test.go
This PR fixes a regression in recovering Vault when audit related code panics. It appeared with the introduction of the go-eventlogger.
The changes involve continuing to handle the metrics updates in the audit broker, but making an entry formatter node responsible for handling panics that occur during formatting of the audit entry.
Addresses: https://github.com/hashicorp/vault/issues/16462
=> VAULT-24013: Audit regression attempting to recover from panic

changelog/25614.txt, ui/app/components/transit-edit.js, ui/app/templates/components/transit-form-edit.hbs, ui/tests/acceptance/transit-test.js
This PR fixes an issue where transitioning from the transit edit route to the show route would result in none of the tabs being active.
After fix
https://github.com/hashicorp/vault/assets/24611656/e2a56977-ac1f-4278-88a4-0fdcf11d241e
=> Transit Active Tab

audit/entry_formatter.go, audit/entry_formatter_test.go, audit/entry_formatter_writer.go, audit/entry_formatter_writer_test.go, audit/types.go, audit/writer_json_test.go, audit/writer_jsonx_test.go, builtin/audit/file/backend.go, builtin/audit/file/backend_test.go, builtin/audit/socket/backend.go, builtin/audit/syslog/backend.go, changelog/25605.txt, helper/testhelpers/corehelpers/corehelpers.go, vault/audit.go, vault/audit_broker.go, vault/audit_test.go
PR based on https://github.com/hashicorp/vault/pull/25605. Required some manual intervention as 1.15 supports disabling the eventlogger, so we needed to persist the old behaviour for handling panics.
=> Audit panic fix: PR based on #25605

website/content/docs/upgrading/upgrade-to-1.15.x.mdx, website/content/partials/known-issues/1_15-audit-panic-handling-with-eventlogger.mdx
`vault/docs/upgrading/upgrade-to-1.15.x#audit-fails-to-recover-from-panics-when-formatting-audit-entries`
=> VAULT-24362: Updated 'known issues' to include audit panic

builtin/credential/cert/path_login.go, changelog/25649.txt
By comparing public keys, we ensure the caller possessed the corresponding
private key of the role configured cert.  The TLS stack will have validated
the signature of the provided certificate.
=> Compare public keys on trusted leaf certs, to prevent use of alternate certs with the same/forged serial numbers

website/content/api-docs/system/secrets-sync.mdx
Since the global config endpoint is now registered in the administrative namespace, the disclaimer has to be updated.
=> Adjust sync config disclaimer

changelog/25636.txt, vault/barrier_aes_gcm.go, website/content/docs/internals/rotation.mdx
Adds VAULT_ENCRYPTION_COUNT_PERSIST_TIMEOUT, which overrides the default 1
second best effort timeout for encryption count tracking, as some customers
have slower HSMs that don't respond within 1 second.
=> Make encryption persistence timeout configurable via env var

ui/tests/acceptance/access/identity/_shared-alias-tests.js, ui/tests/acceptance/access/identity/entities/aliases/create-test.js, ui/tests/acceptance/access/identity/groups/aliases/create-test.js, ui/tests/pages/access/identity/create.js
After a change [here](https://github.com/hashicorp/vault/pull/25560), one test failure came through on the CI slack channel. Addressing a flake-light test failure and removing a skipped test while I was at it.
=> Test stability: textContent issues on identity/aliases and group/aliases acceptance tests

changelog/23621.txt, website/content/docs/agent-and-proxy/proxy/caching/static-secret-caching.mdx, website/data/docs-nav-data.json
I added to the summary at the top the 'why' for why this is an enterprise feature, and included the badge for the nav bar.
I updated the changelog too, following the pattern I saw https://github.com/hashicorp/vault/pull/25671/files
=> VAULT-24385 docs updates for proxy static secret caching -> ent

ui/app/adapters/sync/association.js, ui/app/serializers/sync/association.js, ui/mirage/handlers/sync.js, ui/tests/unit/serializers/sync/associations-test.js
The ID for sync associations was not being consistently set which was causing Ember Data to throw an error alerting the mismatch. This PR updates it to a consistent format.
=> Sync Associations ID Bug

ui/app/components/clients/attribution.hbs, ui/app/components/clients/attribution.js, ui/app/components/clients/charts/line.hbs, ui/app/components/clients/charts/line.ts, ui/app/components/clients/page/sync.ts, ui/app/components/clients/running-total.hbs, ui/app/components/clients/usage-stats.hbs, ui/app/components/sidebar/nav/cluster.hbs, ui/app/router.js, ui/app/styles/core/charts.scss, ui/app/templates/vault/cluster/clients.hbs, ui/lib/sync/addon/components/secrets/page/overview.hbs, ui/lib/sync/addon/components/sync-header.hbs, ui/tests/acceptance/clients/counts/overview-test.js, ui/tests/integration/components/clients/page/sync-test.js, ui/tests/integration/components/clients/running-total-test.js, ui/tests/integration/components/clients/usage-stats-test.js, ui/tests/integration/components/sidebar/nav/cluster-test.js, ui/tests/integration/components/sync/secrets/page/destinations-test.js, ui/tests/integration/components/sync/secrets/page/overview-test.js, ui/tests/integration/components/sync/sync-header-test.js
This PR reverts https://github.com/hashicorp/vault/pull/25170 by revealing the sync billing tab and removing `Beta` tags in the UI.
=> Sync UI: Remove beta tags, and reveal sync client count billing tab

vault/auth.go, vault/mount.go, vault/namespaces.go
This PR is a no-op in Vault CE but includes a stub that is used in a corresponding (approved) Enterprise PR that fixes a subtle issue with the order namespaces are loaded into memory on unseal.
The issue was introduced in Vault 1.15 so backporting to 1.15 and 1.16.
No changelog as the bug-fix note is in the ent PR.
=> Stub for namespace cache warming fix

changelog/25697.txt, vault/request_handling.go
Semgrep found an instance in user lockout request handling where we can return without unlocking due to an error.
=> core/login: fix potential deadlock for failed logins when user lockout is enabled

changelog/25391.txt, command/server.go
PR https://github.com/hashicorp/vault/pull/20609 introduced a way to get pprof files from Vault without needing the handler. We have found that the need for environment variables to use that feature was too restrictive and caused several missed opportunities when debugging issues live. This PR lifts that requirement.
I've also added CPU profile support which was missing from the first iteration.
=> command/server: remove env var requirement for sigusr2 pprof output

website/content/docs/configuration/replication.mdx, website/data/docs-nav-data.json
🧵 [Reported via Slack](https://hashicorp.slack.com/archives/C012RTGJR1V/p1709139139031729)
🔍 [Deploy preview](https://vault-c4cphqzst-hashicorp.vercel.app/vault/docs/configuration/replication)
This PR adds the ENTERPRISE badge to the [replication](https://developer.hashicorp.com/vault/docs/configuration/replication) doc which was missing.
=> [DOCS] Add enterprise badge

vault/logical_system.go, website/content/api-docs/system/config-ui-custom-messages.mdx, website/content/api-docs/system/internal-ui-authenticated-messages.mdx, website/content/api-docs/system/internal-ui-unauthenticated-messages.mdx, website/data/api-docs-nav-data.json
This change contains the code change to remove the `sys/config/ui/custom-messages` paths from the community edition in commit b374b78.
The remaining commits contain documentation changes.
=> VAULT-24439: Make sys/config/ui/custom-messages enterprise paths

ui/tests/acceptance/enterprise-control-groups-test.js
Backport of #23911 to fix flaky control group test
I wasn't able to reproduce the issue we're seeing in CI locally, but saw that the fix merged into 1.16 was not backported so figured that's worth a shot.
=> Backport Flaky Control Group Test Fix to 1.15.x

vault/logical_system.go, vault/logical_system_paths.go, vault/logical_system_test.go, vault/well_known_redirect.go, website/content/api-docs/system/well-known.mdx, website/data/api-docs-nav-data.json
- Add new interfaces LIST/GET /sys/well-known which will provide a list of keys which are registered labels within the /.well-known space on the local server, along with a detailed info map for each
- Add GET /sys/well-known/<label> to get details on a specific registered label
- Add api-docs and tests for the new API endpoints
VAULT-24499
=> Add new /sys/well-known interface to get information about registered labels

changelog/25713.txt, helper/metricsutil/wrapped_metrics.go, vault/activity_log.go, vault/activity_log_test.go
This PR refactors the metrics reporting from the activity log to move it to a separate function. I've also added a test and two new metrics for secret sync.
The documentation for the new metrics will be in a separate PR, along with the rest of the secret sync client count documentation.
=> VAULT-17555: Secret sync client metrics

command/server.go
This is a cosmetic change to make the info key on server start more in line with existing info keys: space separated strings.
This change will break the [pre-existing test](https://github.com/hashicorp/vault-enterprise/pull/5528) on enterprise, so I'm going to manually merge these together to prevent disruption.
=> remove _ from server info

ui/app/adapters/sync/association.js, ui/app/serializers/sync/association.js, ui/tests/acceptance/sync/secrets/destination-test.js, ui/tests/integration/components/sync/secrets/page/destinations/destination/sync-test.js
This PR fixes an issue where association records with secret-key granularity were being loaded with duplicate ids and only one of the associations would render in the list.
_Notice in the list that the total count in the pagination bar is 2 but only one list item is displayed_
=> Sync Associations ID Format

command/agent.go, command/proxy.go
The lock wouldn't be unlocked before this return.
=> Fix lock issue for Agent and Proxy

.gitignore, command/test-fixtures/config.hcl
Fixes ent-only test `Test_loadGCPCredentialsFile ` following on from https://github.com/hashicorp/vault/pull/25744.
=> Add test data file to fix ent-only unit test

vault/logical_system_paths.go
- The `well-known-list` operation id was duplicated across different API endpoints, for the `sys/well-known` list operations, GET and LIST verbs.
- Separate each endpoint operation id so the LIST version uses `well-known-list-labels` and the GET version uses `well-known-list-labels2`
=> Fix duplication of OpenAPI operation ids in sys/well-known list apis

website/content/docs/commands/index.mdx
See: https://developer.hashicorp.com/vault/docs/commands#files
The Vault CLI interprets `@` as the first part of a value or as an entire k/v pair to mean it should parse the contents of the file location following the symbol.
This has caused issues for users that intend to supply a value beginning with `@` (the literal character), this PR updates the commands documentation to give users a hint as to how they should deal with that situation.
For an example of this causing friction please see: https://github.com/hashicorp/vault/issues/25787.
=> Extra information about how to escape an @ as the first char in kv value

website/content/docs/enterprise/namespaces/index.mdx
There is a reference in the third sentence on this page, https://developer.hashicorp.com/vault/docs/enterprise/namespaces, to "Visualization as a Service".
I suspect that this is a typo, and that the original author meant to write "Vault as a Service". This would reflect the "Vault as a service" reference in the first sentence, and fit better with the page's context and content.
=> fix "Vault as a service" reference in namespace docs

website/content/docs/platform/k8s/vso/index.mdx, website/content/docs/platform/k8s/vso/openshift.mdx
State the supported OpenShift versions in our docs, and mention the customization options for an operator installed from OperatorHub.
Changed pages:
- https://vault-iaeunj1p1-hashicorp.vercel.app/vault/docs/platform/k8s/vso#supported-kubernetes-distributions
- https://vault-iaeunj1p1-hashicorp.vercel.app/vault/docs/platform/k8s/vso/openshift
=> docs/vault-secrets-operator: supported openshift versions and OperatorHub options

.github/workflows/build.yml
On docs only changes, or any other changes where we don’t build artifacts, we need to skip building a metadata file so that the prepare workflow can short circuit before attempting to notarize, sign, and upload artifacts.
=> [QT-683] only create artifact metadata on changes that build artifacts

ui/tests/acceptance/enterprise-control-groups-test.js
Manual backport of #23911 to fix flaky test
=> Backport UI: fixes flaky enterprise control group test (#23911)

website/content/api-docs/system/plugins-pins.mdx, website/data/api-docs-nav-data.json
API docs for the new plugin version pinning API. I haven't planned it yet, but if there's any usage documentation it will follow in a separate PR.
=> Docs: New plugins pinned versions APIs

ui/lib/sync/addon/components/secrets/landing-cta.hbs, ui/lib/sync/addon/components/secrets/page/overview.hbs, ui/lib/sync/addon/components/secrets/page/overview.ts, ui/lib/sync/addon/routes/secrets.ts, ui/lib/sync/addon/routes/secrets/overview.ts, ui/lib/sync/addon/templates/secrets/overview.hbs, ui/mirage/handlers/sync.js, ui/tests/acceptance/sync/secrets/destinations-test.js, ui/tests/helpers/sync/sync-selectors.js, ui/tests/integration/components/sync/secrets/landing-cta-test.js, ui/tests/integration/components/sync/secrets/page/overview-test.js
Copied from original #25739 PR
This PR adds a modal within the overview page to prompt the user to read the documentation and confirm acknowledgment before enabling the feature. We will not know if a user has destinations or not (if they're upgrading say from beta) until they opt-in.
https://github.com/hashicorp/vault/assets/6618863/544f7895-9e60-4f4a-8008-de1a5d51822e
=> Backport 1.16.x: Sync Enable Feature Workflow (#25739)

ui/lib/sync/addon/components/secrets/page/overview.hbs, ui/lib/sync/addon/components/secrets/page/overview.ts
New link: https://developer.hashicorp.com/hcp/docs/vault/client
And new language to modal:
=> Secret sync modal language and link change

.github/workflows/test-go.yml
This is change we ought to make for a few reasons:
* Release branches are the code we actually to ship to end users. As such, release branches ought to be the most well tested and verified of the bunch. The current behavior allows papering over test failures on `release/1.14.x` and `release/1.16.x` by having `gotestsum` silently re-run them for us. While this might make it easier to merge changes, it introduces a vector where actual bugs that might be unearthed by our testing are silently hidden and we're lured into a false sense of quality and correctness.
* Due to the logic that's already present, `release/1.15.x` and has had this behavior for a while now. This change would only introduce it for `release/1.16.x`, which is very new and hasn't diverged much from `main`, and …
=> ci: remove re-runs logic for failed tests on release branches

ui/app/components/mfa/mfa-login-enforcement-form.js, ui/app/components/tool-actions-form.js, ui/app/transforms/array.js, ui/lib/core/addon/components/replication-actions.js, ui/lib/core/addon/components/shamir/flow.js, ui/lib/replication/addon/components/replication-summary.js, ui/types/ember-cli-flash/services/flash-messages.d.ts
[Ember-Data 4.12](https://api.emberjs.com/ember-data/4.12/classes/CurrentDeprecations/properties/DEPRECATE_A_USAGE?anchor=DEPRECATE_A_USAGE) deprecated the use of `A()`, on ember-data ArrayLike class, so this PR removes `A()` instances. filterBy was already replaced in a [prior PR](https://github.com/hashicorp/vault/pull/25674)
=> UI: Ember Deprecation - Remove A import from ember/array

audit/entry_formatter.go, audit/entry_formatter_test.go, audit/event.go, audit/event_test.go, audit/types.go
* Lexicographical reordering of struct fields in `types.go`
* `Backend` interface moved to top of `types.go` to sit alongside other interface types
* Added `subtype` stringer
* Use `any` for format request/response to make code easier to understand
* Put header checks/formatting/assignment together when processing a format node
* Added some comments, tests
=> Audit: package refactor

changelog/25874.txt, ui/app/utils/kv-path.ts, ui/lib/core/app/utils/sanitize-path.js, ui/tests/unit/utils/kv-path-test.js
Typically we avoid sanitizing in the UI to minimize data manipulation, however we decided to strip secret paths of the leading slash to copy CLI functionality. 
```
vault kv put -mount=kv /my-secret foo=my-long-passcode
== Secret Path ==
kv/data/my-secret
======= Metadata =======
Key                Value
---                -----
created_time       2024-03-11T16:59:42.502882Z
custom_metadata    <nil>
deletion_time      n/a
destroyed          false
version            1
⇒ vault kv put -mount=kv //my-secret foo=my-long-passcode
== Secret Path ==
kv/data/my-secret
======= Metadata =======
Key                Value
---                -----
created_time       2024-03-11T17:00:01.047652Z
custom_metadata    <nil>
deletion_time      n/a
destroyed          false
version            2
=> UI: Remove leading slash from kv version 2 secret path

website/content/api-docs/system/lease-count-quotas.mdx, website/content/api-docs/system/rate-limit-quotas.mdx
Creating, updating, and deleting quotas within a parent or sibling namespace is not allowed. Reading and listing, however, is. This PR introduces a few small documentation changes to clarify this difference for both rate limit and lease count quota API endpoints.
=> Add clarification to quota docs regarding parent ns access

website/content/api-docs/system/rate-limit-quotas.mdx
This is a followup to https://github.com/hashicorp/vault/pull/25894 in order to fix a typo.
=> Fix typo in rate limit quota API docs

website/content/api-docs/system/replication/index.mdx
Example missing needed `curl` parameters
=> Correcting Sample Request to use token and POST

website/content/docs/platform/k8s/vso/api-reference.mdx, website/content/docs/platform/k8s/vso/helm.mdx, website/content/docs/platform/k8s/vso/installation.mdx, website/content/docs/platform/k8s/vso/openshift.mdx
Docs update for the VSO [v0.5.2](https://github.com/hashicorp/vault-secrets-operator/milestone/21) release.
=> Update docs for VSO v0.5.2

changelog/25953.txt, http/auth_token_test.go, sdk/logical/error.go, vault/core_test.go, vault/request_handling.go
Adds the "Invalid Token" error message to the error response whenever (1) the token is revoked (2) the token does not exist, (3) the token lease is expired, (4) the token is some hocus value.
We've decided to add this value to the error message instead of replace it essentially allows all other subsystems to work as it was working previously, but adds an extra layer of information for Agent and Proxy to use when identifying when to retrigger auto auth.
Link to ENT Pr: https://github.com/hashicorp/vault-enterprise/pull/5588
closes https://github.com/hashicorp/vault-enterprise/pull/5588
=> Added new "Invalid Token" Error Message

ui/package.json, ui/yarn.lock
Trace of `socket.io-parser` vulnerability: 
```sh
⇒ yarn why socket.io-parser           
└─ socket.io@npm:4.5.2
└─ socket.io-parser@npm:4.2.1 (via npm:~4.2.0)
⇒ yarn why socket.io
└─ testem@npm:3.10.1
└─ socket.io@npm:4.5.2 (via npm:^4.1.2)
⇒ yarn why testem
└─ ember-cli@npm:4.12.1
└─ testem@npm:3.10.1 (via npm:^3.10.1)
```
[socket.io](https://github.com/socketio/socket.io/blob/4.6.2/package.json#L54) version `4.6.2` has the desired `socket.io-parser` version ~4.2.4 (we want >= 4.2.3 ) 
the latest release of [testem](https://github.com/testem/testem/releases) only goes up to `socket.io: 4.5.4` (see package.json [here](https://github.com/testem/testem/compare/v3.11.0...v3.12.0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R48)) and so there isn't an `ember-cli` …
=> UI: Add socket.io v4.5.4 to resolutions

api/sys_auth.go, changelog/25968.txt, website/content/api-docs/system/auth.mdx
This PR proposes the following changes
- remove sudo requirement for GetAuthWithContext and GetAuth API wrapper methods
- add the missing sudo requirement to the API docs for `sys/auth/:path`
This should allow the TFVP to use the API wrapper and remove the `sudo` requirement for managing auth methods.
See
- https://github.com/hashicorp/terraform-provider-vault/pull/2145#issuecomment-1999443231
=> api: do not require sudo for GetAuth wrapper

ui/package.json, ui/yarn.lock
This [dependabot vulnerability](https://github.com/hashicorp/vault-enterprise/security/dependabot/239) for `browserify-sign >= 2.6.0, <= 4.2.1` traced back to `ember-tether`. The dependency [was originally added](https://github.com/hashicorp/vault/pull/13574/files#diff-193b27d62e4fbda3d563009fed5ec6761a05f73558d94b39fab63ae948c679ea) to during 1.10.x client count work to add the tooltip to the charts and can be removed when we fully migrate to lineal. 
I did look into update the tooltips in the charts but the lift was too large for a component that is going to be updated in the near future.
```
⇒ yarn why browserify-sign        
└─ crypto-browserify@npm:3.12.0
└─ browserify-sign@npm:4.2.1 (via npm:^4.0.0)
⇒ yarn why crypto-browserify
└─ node-libs-browser@npm:2.2.1
└─ …
```
=> UI: Update ember-tether to v3.0.0 to resolve browserify-sign vulnerability

ui/app/components/database-connection.js, ui/app/components/resultant-acl-banner.hbs, ui/app/components/token-expire-warning.hbs, ui/app/templates/vault/cluster.hbs, ui/ember-cli-build.js, ui/lib/config-ui/addon/components/messages/preview-image.hbs, ui/lib/core/addon/components/form-field.hbs, ui/lib/core/addon/templates/components/replication-secondary-card.hbs, ui/lib/kmip/package.json, ui/lib/kubernetes/package.json, ui/lib/kv/addon/components/page/secret/details.hbs, ui/lib/ldap/package.json, ui/lib/pki/addon/components/page/pki-issuer-rotate-root.hbs, ui/lib/pki/package.json, ui/lib/replication/package.json, ui/lib/sync/package.json, ui/package.json, ui/tests/integration/components/confirm-modal-test.js, ui/yarn.lock
Updates Vault to the latest HDS & flight-icons version by bumping the following packages:
```
"@hashicorp/design-system-components": "^4.1.0",
"@hashicorp/ember-flight-icons": "^5.0.1",
"ember-auto-import": "^2.7.2", // necessary for us to consume v2 addons, see note*
"@embroider/macros": "^1.15.0"
```
This originally came up while auditing the UI to see if we needed to update any icons/colors. It looks like our icon & color usage is up to date, but we might as well update the HDS & icon dependencies to ensure we have access to all the latest ones, since we may need them for the future.
*Note:* `@hashicorp/design-system-components @4.x` is a v2 addon. We're able to consume this addon because we're using [ember-auto-import @2.x](https://github.com/embroider-build/ember-auto-import/blob/main …
=> update HDS and ember-flight-icons

builtin/logical/pki/integration_test.go, changelog/25986.txt, sdk/helper/ocsp/client.go, sdk/helper/ocsp/ocsp_test.go
- The OCSP cache built into the client that is used by cert-auth would cache the responses but when pulling out a cached value the response wasn't validating properly and was then thrown away. So effectively we were operating with no cache.
- The issue was around a confusion of the client's internal status vs the Go SDK OCSP status integer values.
=> Address OCSP client caching issue

ui/package.json, ui/yarn.lock
Backport for https://github.com/hashicorp/vault/pull/25985 - I technically couldn't cherry-pick this and instead upgraded to ember-tether 3.0.0 manually.
=> Backport 1.16.x: Update ember-tether to v3.0.0 to resolve browserify-sign vulnerability #25985

changelog/25999.txt, ui/app/components/mount-backend/type-form.hbs, ui/app/helpers/mountable-auth-methods.js, ui/app/helpers/supported-auth-backends.js, ui/app/helpers/supported-managed-auth-backends.js, ui/tests/acceptance/auth-list-test.js
This PR reverts a regression introduced by https://github.com/hashicorp/vault/pull/25364 which accidentally hid the `roles` tab in the kubernetes UI.
=> UI: Fix kubernetes auth method role management

builtin/credential/cert/path_certs.go, builtin/credential/cert/path_login.go, changelog/25912.txt, sdk/helper/ocsp/client.go, sdk/helper/ocsp/ocsp_test.go, website/content/api-docs/auth/cert.mdx
Support OCSP responses without a NextUpdate value set within cert-auth OCSP verification. Responses without a NextUpdate value are allowed based on [RFC6960 Section 4.2.2.1](https://datatracker.ietf.org/doc/html/rfc6960#section-4.2.2.1)
Previous to this fix, if OCSP checks were enabled and an OCSP response didn't contain a NextUpdate value, cert auth logins would fail with a message similar to 
```
no chain matching all constraints could be found for this login certificate; additionally got errors during verification: 1 error occurred:
* invalid validity: producedAt: 2024-02-29 17:06:00 +0000 UTC, thisUpdate: 2024-02-29 17:06:03 +0000 UTC, nextUpdate: 0001-01-01 00:00:00 +0000 UTC
``` 
Now OCSP responses without a NextUpdate field set will be allowed, the response will not be cached, as …
=> Support OCSP responses without NextUpdate field set

builtin/credential/cert/backend.go, builtin/credential/cert/backend_test.go, builtin/credential/cert/path_certs.go, builtin/credential/cert/path_login.go, changelog/25982.txt, sdk/helper/ocsp/client.go, website/content/api-docs/auth/cert.mdx
When the cert auth had the role property [ocsp_fail_open](https://developer.hashicorp.com/vault/api-docs/auth/cert#ocsp_fail_open) set to true, when network errors occurred, the errors would bubble up and prevent login attempts. 
The error would look something like this:
```
vault: 2024/02/03 12:01:16 [ERR] GET .... = request failed: Get "...": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
`ocsp_max_retries` config was added to allow easier testing of these use cases
=> Allow cert auth login attempts if ocsp_fail_open is true and servers are unreachable

builtin/logical/pki/acme_billing_test.go, changelog/26020.txt, vault/activity/query.go, vault/activity_log.go, vault/activity_log_test.go, vault/activity_log_util_common.go
https://hashicorp.atlassian.net/browse/VAULT-24625
I applied the diff on the linked Jira and adjusted a few tests. Some of the tests mentioned in the Jira didn't look like they needed adjusting? Or maybe I misread them?
=> Add acme clients internal data structures and adjust tests

ui/tests/integration/components/confirm-modal-test.js
✂️ Removes a flaky `confirm-modal` test
➕ added more thorough test coverage for disabled state / custom title & message etc
Unfortunately testing that the modal's `@onClose` arg is called is flaky because the component itself gets torn down almost immediately after clicking close (see screenshot). Instead of adding an arbitrary `waitFor` or `setTimeout`, i think it's safe to rely on the `HDS::Modal` integration tests to cover this situation.
=> tests: remove flaky confirm-modal test

ui/package.json, ui/yarn.lock
I couldn't backport these package changes from https://github.com/hashicorp/vault/pull/25985 and updating to ember tether 3.0.0 didn't remove the vulnerable dependency as it did in 1.1.6.x so I settled for adding to the resolutions block.
=> UI: Add browserify-sign to resolutions vulnerability #25985

ui/package.json, ui/yarn.lock
Fixes typo in this PR https://github.com/hashicorp/vault/pull/25975 
I noticed that it didn't automagically resolve the dependabot alert and I realized there was a typo in my resolution fix 😵‍💫 . Notice in this PR that the `yarn.lock` file correctly updates `socket.io-parser` to version ~4.2.4 (we want >= 4.2.3 to resolve the dependabot alert) 
<hr>
Trace of `socket.io-parser` vulnerability: 
```sh
⇒ yarn why socket.io-parser           
└─ socket.io@npm:4.5.2
└─ socket.io-parser@npm:4.2.1 (via npm:~4.2.0)
⇒ yarn why socket.io
└─ testem@npm:3.10.1
└─ socket.io@npm:4.5.2 (via npm:^4.1.2)
⇒ yarn why testem
└─ ember-cli@npm:4.12.1
└─ testem@npm:3.10.1 (via npm:^3.10.1)
```
[socket.io](https://github.com/socketio/socket.io/blob/4.6.2/package.json#L54) version `4.6.2` has the desired …
=> UI: resolve dependabot socket.io parser vulnerability (actually)

ui/package.json, ui/yarn.lock
Fixes typo in this PR https://github.com/hashicorp/vault/pull/25975 
I noticed that it didn't automagically resolve the dependabot alert and I realized there was a typo in my resolution fix 😵‍💫 . Notice in this PR that the `yarn.lock` file correctly updates `socket.io-parser` to version ~4.2.4 (we want >= 4.2.3 to resolve the dependabot alert) 
<hr>
Trace of `socket.io-parser` vulnerability: 
```sh
⇒ yarn why socket.io-parser           
└─ socket.io@npm:4.5.2
└─ socket.io-parser@npm:4.2.1 (via npm:~4.2.0)
⇒ yarn why socket.io
└─ testem@npm:3.10.1
└─ socket.io@npm:4.5.2 (via npm:^4.1.2)
⇒ yarn why testem
└─ ember-cli@npm:4.12.1
└─ testem@npm:3.10.1 (via npm:^3.10.1)
```
[socket.io](https://github.com/socketio/socket.io/blob/4.6.2/package.json#L54) version `4.6.2` has the desired …
=> Backport: UI: resolve dependabot socket.io parser vulnerability (actually)

ui/package.json, ui/yarn.lock
This dependency is used in a lot of ember packages and so adding it to the resolutions block seemed the best way to resolve this security vulnerability. 
one traced back to `ember-cli-page-object` 
```
ui|main⚡ ⇒ yarn why json5
├─ babel-core@npm:6.26.3
│  └─ json5@npm:0.5.1 (via npm:^0.5.1)
│
├─ find-babel-config@npm:1.2.0
│  └─ json5@npm:0.5.1 (via npm:^0.5.1)
│
├─ loader-utils@npm:1.4.0
│  └─ json5@npm:1.0.1 (via npm:^1.0.1)
```
```
└─ ember-cli-page-object@npm:1.17.10
└─ ember-native-dom-helpers@npm:0.7.0 (via npm:^0.7.0)
└─ ember-cli-babel@npm:6.18.0 (via npm:^6.6.0)
└─ broccoli-babel-transpiler@npm:6.5.1 (via npm:^6.5.0)
└─ babel-core@npm:6.26.3 (via npm:^6.26.0)
└─ json5@npm:0.5.1 (via npm:^0.5.1)
```
Another traced back to many, many ember packages
```
├─ …
```
=> UI: Fix json5 security vulnerability for version < 1.0.2 

ui/package.json, ui/yarn.lock
"Backport" of https://github.com/hashicorp/vault/pull/26041
This dependency is used in a lot of ember packages and so adding it to the resolutions block seemed the best way to resolve this security vulnerability. 
one traced back to `ember-cli-page-object` 
```
ui|main⚡ ⇒ yarn why json5
├─ babel-core@npm:6.26.3
│  └─ json5@npm:0.5.1 (via npm:^0.5.1)
│
├─ find-babel-config@npm:1.2.0
│  └─ json5@npm:0.5.1 (via npm:^0.5.1)
│
├─ loader-utils@npm:1.4.0
│  └─ json5@npm:1.0.1 (via npm:^1.0.1)
```
```
└─ ember-cli-page-object@npm:1.17.10
└─ ember-native-dom-helpers@npm:0.7.0 (via npm:^0.7.0)
└─ ember-cli-babel@npm:6.18.0 (via npm:^6.6.0)
└─ broccoli-babel-transpiler@npm:6.5.1 (via npm:^6.5.0)
└─ babel-core@npm:6.26.3 (via npm:^6.26.0)
└─ json5@npm:0.5.1 (via npm:^0.5.1)
```
Another traced back to …
=> Backport 1.16.x: Fix json5 security vulnerability for version < 1.0.2

ui/package.json, ui/yarn.lock
Combines resolution of `socket.io-parser` and `json5` security vulnerabilities from these PRs
[UI: resolve dependabot socket.io parser vulnerability #26042](https://github.com/hashicorp/vault/pull/26042)
[UI: Fix json5 security vulnerability for version < 1.0.2 #26041](https://github.com/hashicorp/vault/pull/26041)
<hr>
Original PRs merged to main
https://github.com/hashicorp/vault/pull/26042
https://github.com/hashicorp/vault/pull/26041
=> "Backport" 1.15.x dependabot alerts socket.io parser and json5 

ui/package.json, ui/yarn.lock
Combined resolutions for socket.io-parser, browserify, json5
- "Backport" of https://github.com/hashicorp/vault/pull/26050 which combined resolutions for socket.io parser and json5
- "Backport" of https://github.com/hashicorp/vault/pull/26011 which resolved `browserify-sign` (upgrading ember-tether didn't resolve the vulnerability like it did on main._ 
<hr>
Original PRs merged to main:
`socket.io-parser` - https://github.com/hashicorp/vault/pull/26042
`json5` - https://github.com/hashicorp/vault/pull/26041
`browserify-sign` - https://github.com/hashicorp/vault/pull/25985
=> "Backport" 1.14.x: security vulnerability resolutions for socket.io-parser, browserify, json5

ui/tests/integration/components/confirm-modal-test.js, vault/audited_headers.go, vault/audited_headers_test.go
This PR adds a mechanism to allow for invalidation of audit request headers.
ENT PR: https://github.com/hashicorp/vault-enterprise/pull/5616
=> VAULT-15682: Audit request header invalidation

physical/raft/config.go, physical/raft/config_test.go, physical/raft/raft_util_stubs_oss.go
I added this while developing #25992 as a quick check that the warnings were omitted (and that this test functionality worked) but didn't intend to commit it since it will conflict with Enterprise code.
Perhaps later it would be nice to have a clean way to be able to encode these warnings here but only for CE but that is a bigger change that is a bit gross so want to just get this mergeable in Ent for now while we discuss the cleanest pattern for that.
=> Remove CE-only warning from shared tests

.github/workflows/plugin-update-check.yml
When the Vault PR exists the workflow is unable to pass the PR num and url to the following steps. Example failure run: https://github.com/hashicorp/vault/actions/runs/8104485741/job/22151188307
=> fix plugin update check pr num fetching

ui/app/components/clients/activity.ts, ui/app/components/clients/page/sync.hbs, ui/app/components/clients/page/sync.ts, ui/app/routes/vault/cluster/clients/counts.ts, ui/app/routes/vault/cluster/clients/counts/sync.ts, ui/app/templates/vault/cluster/clients/counts/sync.hbs, ui/tests/acceptance/clients/counts/sync-test.js, ui/tests/helpers/clients.js, ui/tests/integration/components/clients/page/sync-test.js
Adds an empty state to the Clients > Secrets Sync tab when the feature hasn't been activated yet.
Note: in the next PR we'll hide this page altogether for any user that doesn't have this feature included in their license.
n/a
With an OSS license:
1. Visit `/vault/clients/counts/sync`
2. You should see an empty state indicated that Secrets Sync has not been enabled yet
With an ENT license that doesn't have secrets sync enabled:
_same steps as OSS above_
With an ENT license that has secrets sync enabled:
1. Visit `/vault/clients/counts/sync`
2. You should NOT see the empty state. You should see client count charts instead.
=> Show empty state on client count sync page if feature isn't activated

ui/lib/sync/addon/components/secrets/page/overview.ts, ui/tests/acceptance/sync/secrets/overview-test.js
Recent changes to the backend mean that we now only make the POST request to activation-flags in the root namespace.
=> Update POST activation-flags call

vault/external_tests/activity_testonly/activity_testonly_test.go
The actual changes for this ticket got completed as part of https://github.com/hashicorp/vault/pull/26020, so this PR just generalizes the some tests so that they run for all client types, instead of just secret sync.
=> VAULT-24581: Generalize activity log tests to run for all client types

audit/entry_formatter.go, audit/entry_formatter_test.go, audit/event.go, audit/event_test.go, audit/types.go, changelog/26088.txt
Previously when entries for audit were written to configured sinks (file, socket, syslog) the time associated with each entry was related to the exact time the sink tried to write it, and not the time the audit entry itself was created. 
This PR changes this so that the time the entry (audit event) is created is the time which appears in the sink logs, this will help Operators to coordinate entries across multiple audit device sinks.
Addresses https://github.com/hashicorp/vault/issues/8466
=> Audit: Timestamps on sink entries should match the creation time of the audit event

command/server.go, command/server_test.go, vault/core.go, vault/core_test.go, vault/ha.go
As part of the process of becoming a leader node, check to see if the seal configuration needs to be reloaded. Reloading may be necessary if the seal generation information computed during start up is outdated. For example, a new node that has just joined the cluster will have incorrect seal generation information in memory, even if it has the correct seal configuration, since it did not have access to the stored seal generation information.
(This PR was originally vault-enterprise PR 5619.)
=> Reload seals if necessary when a node gains leadership.

website/content/docs/auth/kubernetes.mdx
Existing link is wrong - https://developer.hashicorp.com/vault/docs/auth/jwt/oidc-providers/kubernetes#specifying-ttl-and-audience and doesn't lead to the section in the browser. Correct link is - https://developer.hashicorp.com/vault/docs/auth/jwt/oidc-providers/kubernetes#specify-ttl-and-audience and leads to the correct section in the browser
=> fix link to specifying ttl and audience section of kubernetes oidc provider

ui/app/components/clients/page/counts.hbs, ui/app/components/clients/page/sync.hbs, ui/app/routes/vault/cluster/clients/counts.ts, ui/tests/acceptance/clients/counts-test.js, ui/tests/acceptance/clients/counts/overview-test.js, ui/tests/integration/components/clients/page/sync-test.js
Fixes issue on community where a default 0 date `0001-01-01T00:00:00Z` value for the billing start caused incorrect date querying. This regression was introduced when we refactored to use the `v1/sys/internal/counters/config` for the start time instead of making a query to the license for that info (which would fail on CE)
This PR also hides average sync count when the average is 0
<hr>
because there are so many months in the average calculation, the average is a decimal below 1 which rounds to `0` this isn't great UX so hiding in situations like this
<hr>
enterprise passed ✅
=> UI: Follow on sync updates for 1.16 GA 

ui/tests/acceptance/clients/counts/overview-test.js
Removes a test failure caused by an incorrect assertion.
@hellobontempo and I paired on this and we believe the error is occurring because client activity data is generated as the test suite runs other acceptance tests. This correctly caused the `<UsageStats />` component not to render (since there was activity data). 
Next up we should rewrite the test to stub the activity response to return 0 clients. That way we're ensuring that we can consistently predict the Vault cluster's client activity.
=> [secrets sync] remove incorrect dom assertion

changelog/26110.txt, sdk/helper/template/template.go, sdk/helper/template/template_test.go
We now enforce a limit of 100,000 characters on string templates in the `sdk/helpers` library. This should be large enough to support almost all use cases, even if it is a change.
See Jira for further details.
=> VAULT-20396 Add limit of 100,000 to string templates

website/content/docs/plugins/plugin-development-event-notifications.mdx, website/data/docs-nav-data.json
This adds a short doc describing the basic process of adding event notifications to a plugin as well
as some examples and best practices.
=> docs: Adding events to a plugin

ui/package.json
I searched the codebase for each resolution and removed it if there was no reference to it. Afterward running `yarn install`, as expected, did **not** update the `yarn.lock` file  🎉
=> Cleanup package resolutions

website/content/partials/telemetry-metrics/vault/audit/log_response_failure.mdx
I've changed the description for the vault.audit.log_response_failure metric from:
Number of audit log request failures across all devices 
into: 
Number of audit log response failures across all devices
I've changed the explanation from:
A non-zero value for vault.audit.log_response_failure indicates that one of the configured audit log devices failed to respond to Vault. If Vault cannot properly audit a request, or the response to a request, the original request will fail.
into:
A non-zero value for vault.audit.log_response_failure indicates that all of the configured audit log devices failed to respond to Vault. If Vault cannot properly audit a request, or the response to a request, the original request will fail.
=> changing vault.audit.log_response_failure metric doc

Makefile
Enterprise will have deletes for the `_stubs_ent.go` files
=> Add make clean command

website/content/docs/release-notes/1.15.0.mdx, website/content/docs/upgrading/upgrade-to-1.15.x.mdx, website/content/partials/known-issues/1_15-audit-vault-enterprise-perf-standby-logs-all-headers.mdx
Related to Jira ticket: VAULT-24016
=> Known issues: Vault Enterprise - Performance Standby nodes audit log all request headers

builtin/logical/database/backend.go, builtin/logical/database/backend_get_test.go, builtin/logical/database/mockv5.go, builtin/logical/database/rotation_test.go, changelog/26147.txt, helper/syncmap/syncmap.go
When creating database connections, there is a race condition when multiple goroutines try to create the connection at the same time. This happens, for example, on leadership changes in a cluster.
Normally, the extra database connections are cleaned up when this is detected. However, some database
implementations, notably Postgres, do not seem to clean up in a timely manner, and can leak in these scenarios.
To fix this, we create a global lock when creating database connections to prevent multiple connections from being created at the same time.
We also clean up the logic at the end so that if (somehow) we ended up creating an additional connection, we use the existing one rather than the new one. This by itself would solve our problem long-term, however, would still involve many …
=> database: Avoid race condition in connection creation

vault/identity_store.go
This is just one preliminary refactoring from many more to come, that makes the IdentityStore code more readable ahead of performance improvement changes that will come later on.
This change is limited to extracting the code from a switch case into its own function. Later on, the content of the newly extracted function will be changed. These changes should be easier to review since they are isolated into their own function.
The same will be done with the other switch cases in different PRs.
=> VAULT-25207: [Refactor] Extract switch case code into separate function

ui/app/components/sidebar/user-menu.hbs, ui/app/templates/components/calendar-widget.hbs, ui/lib/core/addon/components/copy-secret-dropdown.hbs, ui/lib/kv/addon/components/kv-version-dropdown.hbs, ui/lib/pki/addon/components/page/pki-issuer-details.hbs, ui/lib/pki/addon/components/page/pki-issuer-list.hbs, ui/lib/pki/addon/components/page/pki-issuer-rotate-root.hbs
Small clean up task to remove the use of the `class="action"`. This class was likely removed during a HDS component adoption. 
I checked these visually after removing the class and they functioned/appeared the same.
=> Remove undefineded class=action

internalshared/configutil/kms.go
Their SetConfigs check the local, not global opt.  Will clean up the
distinction in the future.
=> Use local wrapping option for withDisallowEnvVars for AWS & Azure

ui/lib/sync/addon/components/sync-header.hbs, ui/tests/integration/components/sync/secrets/page/destinations-test.js, ui/tests/integration/components/sync/secrets/page/overview-test.js, ui/tests/integration/components/sync/sync-header-test.js
Removes the extra breadcrumb on the Secrets Sync overview page per [HDS guidance](https://helios.hashicorp.design/components/breadcrumb#usage).
=> [secrets sync] remove extra breadcrumb

vault/core.go
This can happen if storage changes out from under you, and both the previous
and new seal gen information were rewrapped but may not be safe.  This can
happen for example when restoring a snapshot.
=> Force a seal rewrap when stored generation is higher than existing (main)

vault/core.go
This can happen if storage changes out from under you, and both the previous
and new seal gen information were rewrapped but may not be safe.  This can
happen for example when restoring a snapshot.
=> Force a seal rewrap when stored generation is higher than existing

ui/tests/acceptance/pki/pki-engine-route-cleanup-test.js
This PR is a follow on from https://github.com/hashicorp/vault/pull/26170 and handles removing `objectAt()` in tests which failed when running the full test suite and throwing errors for `matchId: 'ember-data:deprecate-array-like'`
✅ enterprise tests
=> UI: Ember deprecation prep for 5.0: ember-data:deprecate-array-like, part 2

ui/tests/integration/utils/client-count-utils-test.js
In preparation for some client count util refactoring I used mock data to generate a response, then passed it to each helper function to capture the expected shape. 
I was the one who originally wrote these util tests, and in hindsight they weren't really testing for things that I wanted them to.
=> Cleanup client-count-utils tests to prep for refactor

changelog/26243.txt, command/base.go, go.mod, go.sum
When HCP subcommands were added it created a hard dependency on HOME being configured for users. The [upstream HCP lib](https://github.com/hashicorp/vault-hcp-lib/pull/37) has been slightly refactored to take a path argument and in the Vault CLI we are just ignoring home directory not set errors.
Fixes https://github.com/hashicorp/vault/issues/26199.
=> cli: fixed HOME not set error

audit/entry_formatter.go, audit/entry_formatter_test.go, audit/options.go, audit/options_test.go, audit/types.go, builtin/audit/file/backend.go, builtin/audit/file/backend_filter_node_test.go, builtin/audit/file/backend_test.go, builtin/audit/socket/backend.go, builtin/audit/socket/backend_filter_node_test.go, builtin/audit/socket/backend_test.go, builtin/audit/syslog/backend.go, builtin/audit/syslog/backend_filter_node_test.go, builtin/audit/syslog/backend_test.go, helper/testhelpers/corehelpers/corehelpers.go, http/logical_test.go, vault/audit_test.go, vault/audited_headers.go, vault/audited_headers_test.go, vault/core_test.go
This PR makes changes to the `EntryFormatter` node so that it requires a `HeaderFormatter` rather than accepting it as an option.
ENT PR: https://github.com/hashicorp/vault-enterprise/pull/5680
=> VAULT-25710: Audit - enforce header formatter requirement in EntryFormatter

website/content/docs/platform/mssql/installation.mdx, website/content/docs/platform/mssql/rotation.mdx, website/data/docs-nav-data.json
Fixes the KEK rotation instructions to ensure the old KEK can be fully decommissioned from the Vault transit mount (via min decrypt version) after rotating.
Also creates a dedicated page for key rotation to make it easier to discover in the sidebar, rather than hidden at the bottom of a long installation page.
=> Docs: Fix SQL Server EKM Provider KEK rotation instructions

ui/app/services/permissions.js, ui/app/templates/vault/cluster.hbs, ui/tests/unit/services/permissions-test.js
This PR is to update the behavior of the Resultant ACL banner so that it no longer shows in child namespaces if the user has a `"*"` path in their policy. 
To set up namespaces with some users to log in and verify the behavior, run the following script: 
```
vault namespace create admin
vault namespace create -namespace=admin child
vault policy write root-admin - <<EOF
path "*" {
capabilities = ["read", "list", "create", "update", "delete"]
}
EOF
vault policy write -namespace=admin admin - <<EOF
path "*" {
capabilities = ["read", "list", "create", "update", "delete"]
}
EOF
vault auth enable userpass
vault write auth/userpass/users/root password=password policies=root-admin
vault auth enable -namespace=admin userpass
vault auth tune -namespace=admin -listing-visibility="unauth" userpass …
```
=> UI: Don't show Resultant-ACL banner when wildcard policy present

ui/tests/acceptance/sync/secrets/overview-test.js, ui/tests/helpers/sync/sync-selectors.js, ui/tests/integration/components/sync/secrets/page/overview-test.js, ui/tests/integration/components/sync/sync-header-test.js
Adds tests & reorganizes existing tests to ensure we are covering the Secrets Sync / Overview page when:
Refer to the Whimsical diagram for another example of all possible states that the page could have. I used this as a reference when outlining all of the tests.
Note the tests now being organized in modules that make it clearer which scenario we're testing
Take a look at the following test files and make sure they cover the scenarios outlined above:
- `tests/acceptance/sync/secrets/overview-test.js`
- `tests/integration/components/sync/secrets/page/overview-test.js`
=> [secrets sync] add more thorough Secrets Sync landing page tests

vault/external_plugin_container_test.go
This test started failing on all branches this morning. Merging this to main won't help most of those branches, but at least it keeps main green and lets people get their branches green by merging in main while they wait for the proper fix.
=> Temporarily skip broken test

website/content/api-docs/secret/transit.mdx
I was browsing the docs trying to understand the use of "Sign CSR" and notice the doc for "Set Certificate Chain" `certificate_chain` parameter is incorrect from the description in the PR #21081.
=> Update "Set Certificate Chain" docs for Transit secret engine

ui/app/services/permissions.js, ui/app/templates/vault/cluster.hbs, ui/tests/unit/services/permissions-test.js
=> Backport UI: Don't show Resultant-ACL banner when wildcard policy (#26233)

ui/app/services/permissions.js, ui/app/templates/vault/cluster.hbs, ui/tests/unit/services/permissions-test.js
=> Backport UI: Don't show resultant-ACL banner if wildcard policy

command/agent/agent_auto_auth_self_heal_test.go
This test failed in Enterprise CI and seems prone to problems in race tests. 
I've made some adjustments to prevent it from erroring, the other test function in this file might need to be looked at too separately. 
Reproduced this locally using `untilfail` and it's fixed with this PR locally (tested the same way). (Ironically doesn't seem to have been happy in its first CI run though)
Enterprise related CI issue: https://github.com/hashicorp/vault-enterprise/actions/runs/8563046808/job/23467651239#step:13:19884
=> Agent: Improve `TestAutoAuthSelfHealing_TokenFileAuth_SinkOutput`

changelog/26263.txt, ui/app/templates/components/tool-hash.hbs, ui/lib/core/addon/components/json-editor.hbs, ui/lib/core/addon/components/json-editor.js, ui/lib/core/addon/modifiers/code-mirror.js, ui/tests/integration/components/console/log-json-test.js, ui/tests/integration/components/form-field-test.js, ui/tests/integration/components/kubernetes/page/role/create-and-edit-test.js, ui/tests/integration/components/kubernetes/page/role/details-test.js, ui/tests/integration/components/kv/kv-data-fields-test.js, ui/tests/integration/components/kv/page/kv-page-secret-details-test.js, ui/tests/integration/components/ldap/page/role/create-and-edit-test.js, ui/tests/integration/components/oidc/scope-form-test.js, ui/tests/integration/components/policy-example-test.js, ui/tests/integration/components/policy-form-test.js, ui/tests/integration/components/secret-edit-test.js, ui/tests/integration/components/transform-advanced-templating-test.js, ui/tests/integration/components/transit-key-actions-test.js
If merged, this PR:
- fixes instances where CodeMirror JSON editor components did not have an appropriate label for accessibility compliance.
- fixes an instance where a label existed for an input but had the incorrect value to be appropriately associated with the input
- removes label-related TODOs and ember-a11y-testing config from test files (no longer needed); ran tests locally to ensure they pass.
=> Bug: fixed cases where CodeMirror textarea inputs did not have associated labels

helper/storagepacker/storagepacker_test.go, vault/identity_store.go, vault/identity_store_aliases.go, vault/identity_store_entities.go, vault/identity_store_group_aliases.go, vault/identity_store_test.go, vault/identity_store_util.go
Manual backport of https://github.com/hashicorp/vault/pull/26072
The issue was the orders of the imports in `vault/identity_store_test.go`.
I believe this shouldn't get merged until 1.16 is GA. I'll put a reminder so that I don't forget.
=> 1.16 Manual backport of https://github.com/hashicorp/vault/pull/26072

website/content/docs/secrets/kmip.mdx
Fix a couple of typos in the KMIP backend documentation.
=> Fix typo in KMIP backend documentation

helper/constants/constants_oss.go
I'm not sure if this was just an oversight or if there's a special reason we'd have the `constants.IsEnterprise` as a `var` which could be modified vs a `const` which cannot.
ENT PR: https://github.com/hashicorp/vault-enterprise/pull/5698
=> `IsEnterprise` as `const` rather than `var`

command/agent/agent_auto_auth_self_heal_test.go
Was flaking like this:
```
agent_auto_auth_self_heal_test.go:207: 
Error Trace:	/home/runner/actions-runner/_work/vault-enterprise/vault-enterprise/command/agent/agent_auto_auth_self_heal_test.go:207
Error:      	Received unexpected error:
timed out waiting for templates to render, last error: %!w(<nil>)
Test:       	TestAutoAuthSelfHealing_TokenFileAuth_SinkOutput
2024-04-09T12:37:47.155Z [TRACE] vault.read(auth/token/lookup-self): GET /v1/auth/token/lookup-self
```
I think what was happening is we didn't get the initial template render time, but the second render was happening before we started waiting in CI, so we would wait forever since the template has already rendered twice.
To solve this, I got the initial render time for the template, and waited based on that.
=> Attempt to address TestAutoAuthSelfHealing_TokenFileAuth_SinkOutput flakiness

ui/lib/sync/addon/components/secrets/page/overview.hbs, ui/lib/sync/addon/components/secrets/page/overview.ts, ui/lib/sync/addon/routes/secrets/overview.ts, ui/lib/sync/addon/templates/secrets/overview.hbs, ui/tests/acceptance/sync/secrets/overview-test.js, ui/tests/integration/components/sync/secrets/page/overview-test.js
During the opt-in banner work we missed a conditional to not call the associations and destinations endpoints if the feature has not been activated. This PR moves the `isActivated` definition to the secrets model so that we can call on it to determine if destinations and associations should be called.
To test:
- On a fresh VRD, navigate to the Secrets sync page. You should not see any network requests made to the destinations or associations list endpoints. 
- Activate the feature via the opt-in modal.
- Look at the network request after the modal closes. The secrets model has been updated and thus the destinations and associations endpoints have been called.
=> Secrets Sync: only call destinations and associations if isActivated

ui/lib/sync/addon/components/secrets/page/overview.hbs, ui/lib/sync/addon/components/secrets/page/overview.ts, ui/lib/sync/addon/routes/secrets/overview.ts, ui/lib/sync/addon/templates/secrets/overview.hbs, ui/tests/acceptance/sync/secrets/overview-test.js, ui/tests/integration/components/sync/secrets/page/overview-test.js
=> Backport 1.16.2: only call associations and destinations if activated

changelog/26307.txt, command/agent.go, command/agent/cache_end_to_end_test.go, command/agentproxyshared/cache/api_proxy.go, command/agentproxyshared/cache/api_proxy_test.go, command/agentproxyshared/cache/cache_test.go, command/agentproxyshared/cache/handler.go, command/agentproxyshared/cache/static_secret_cache_updater.go, command/agentproxyshared/cache/static_secret_cache_updater_test.go, command/proxy.go, command/proxy_test.go
Auto Auth will self heal if Proxy is using an auto auth token that is bogus, has reached max uses, or max ttl. 
Approved Ent Pr: https://github.com/hashicorp/vault-enterprise/pull/5672
closes : https://github.com/hashicorp/vault-enterprise/pull/5672
=> Auto Auth Healing for Proxy

website/content/docs/agent-and-proxy/autoauth/index.mdx
Documentation for how Auto Auth will self-heal for Agent and Proxy.
RFC: https://hermes.hashicorp.services/document/1yTtWJEvyoYLPkYRQ3lxs6dHmqAVyC177BMEBEXuu8fE?draft=false
=> Documentation for Self Healing Auto Auth Proxy and Agent

changelog/26325.txt, ui/lib/replication/addon/components/replication-summary.js, ui/lib/replication/addon/templates/components/replication-summary.hbs, ui/mirage/handlers/index.js, ui/mirage/handlers/replication.js, ui/tests/acceptance/replication-nav-test.js
Backport of #26325 
Also updated the test mirage handler to match what we do in 1.15.x
=> Backport UI: Replication page navigation fix (#26325)

.github/workflows/enos-lint.yml, .github/workflows/enos-run-k8s.yml, .github/workflows/test-ci-bootstrap.yml, .github/workflows/test-enos-scenario-ui.yml, .github/workflows/test-run-enos-scenario-matrix.yml
It appears that our scenario modules have some sort of incompatibility with Terraform 1.8.0. Pin to 1.7.5 until it has been resolved.
Example: https://github.com/hashicorp/vault/actions/runs/8637615983/job/23680543071#step:10:86
=> terraform: pin to 1.7.5 until 1.8.0 crash is resolved

audit/entry_filter.go
Don't wrap the underlying error on filter field validation failure.
Once the Operator has seen:
```
filter references an unsupported field: foo == bar: invalid configuration
```
... then the following 'extra' info isn't really useful at all:
```
error finding value in datum: /foo at part 0: couldn't find key: struct field with name "foo"
```
We document the filter fields for Vault Operators: [filter properties for audit devices](https://developer.hashicorp.com/vault/docs/enterprise/audit/filtering#filter-properties-for-audit-devices).
Before:
After:
* Please ignore the sneaky `bar` in screenshots, which goes against what we document (should be `\"bar\"`)
=> VAULT-24798: Audit - error tweak

ui/lib/core/addon/components/replication-page.js
The changes in #26325 did not completely fix the issue for 1.16 because in 1.17 and beyond, `replication-page` is a glimmer component, but in 1.16 and before it's a classic component. This PR updates the the calculation of mode-specific attributes for the replication-page component so that the tests pass.
=> UI: fix replication nav 1.16.x

ui/app/components/clients/page/counts.ts, ui/app/routes/vault/cluster/clients.ts, ui/app/routes/vault/cluster/clients/counts.ts, ui/tests/acceptance/clients/counts-test.js, ui/tests/integration/components/clients/page/counts-test.js
Some of the `as` typescript declarations were overriding the actual values. This cleans up some of those returns and uses the `<ModelFrom>` helper to derive the route model types (instead of explicitly defining them in the file)
=> UI: clients typescript cleanup

go.mod, go.sum
Pull in version v2.0.12 of the GCP wrapper from [go-kms-wrapper](https://github.com/hashicorp/go-kms-wrapper) pulling in fix https://github.com/hashicorp/go-kms-wrapping/pull/250
Changelog will be added to the corresponding ENT PR as this fix is used for ENT only use-cases.
=> Update GCP wrapper to v2.0.12

website/content/api-docs/system/lease-count-quotas.mdx
This PR removes extraneous `max_leases` and `role` fields from the lease-count quota API docs.
=> remove extraneous max_leases and role fields

website/data/docs-nav-data.json
This PR adds a comma that was missing from an array element in `website/data/docs-nav-data.json`, which causes the JSON file to be unable to be parsed.
=> fix: add missing comma to docs nav data

changelog/26381.txt, command/server.go, vault/core.go
When `enable_multiseal` was enabled, along with a configured auto-seal on enterprise standby nodes, if a SIGHUP were sent to Vault the seal config would be read and if modified would attempt to update the local seal barrier only to get an ErrReadOnly error.
Trap the case on standby nodes, we load seal config but throw it away as we won't use it, on perf standby's we update the core barrier information in memory while on active nodes we perform the update as we did before.
=> During a seal reload through SIGHUP, only write updated seal barrier on an active node

website/content/docs/secrets/transform/index.mdx
The current docs for the transform secrets engine uses a deprecated command. Updating the command in favor of the type specific configuration endpoint.
- https://developer.hashicorp.com/vault/api-docs/secret/transform#create-update-transformation-deprecated-1-6
- https://developer.hashicorp.com/vault/api-docs/secret/transform#create-update-fpe-transformation
=> Docs: update deprecated transform command

api/lifetime_watcher.go, changelog/26383.txt
I just opened up a bug for this PR, this fixes it. Here's the original context from the bug:
**Describe the bug**
We were using the Vault `LifetimeWatcher` from the `api` package in an internal project and noticed an issue with the backoff behavior of token renewal that was causing a bunch of our tests to fail when we upgraded to a new version of Vault.
The bug is here:
https://github.com/hashicorp/vault/blob/1274f2d79a1ae6f589ad64af2c1ab930545943c0/api/lifetime_watcher.go#L348-L354
`sleepDuration` appears to be the `time.Duration` used prior to re-running the renewal loop. In the case when `errBackoff` is `nil`, then a simple backoff duration is calculated based on the call to `calculateSleepDuration`. If `errBackoff` is **not nil** then `sleepDuration` is never set and the timeout in …
=> Fix exponential backoff for api.LifetimeWatcher

command/agent.go, command/agent/cache_end_to_end_test.go, command/agent_test.go, command/agentproxyshared/cache/api_proxy_test.go, command/agentproxyshared/cache/cache_test.go, command/agentproxyshared/cache/handler.go, command/proxy.go, command/proxy_test.go
There was a bug introduced as part of the self-healing work that I caught as part of review.
The two tests added (one in `agent_test.go` and one in `proxy_test.go`) failed before the code changes. It surprised me we didn't have the coverage so I thought it was important to add.
I also renamed `proxyVaultToken` to `forceAutoAuthToken` to make it clearer what this config does, as well as preventing multiple negations. It's easier to reason about now.
=> VAULT-23742 Fix issue with use_auto_auth_token being always on

command/agent_test.go, command/proxy_test.go
`makeTempFile` now uses `t.TempDir()` so it will remove files for you when your test finishes.
=> Agent: helper func tweak

changelog/26384.txt, sdk/plugin/grpc_system.go, vault/dynamic_system_view.go
We need to set the namespace on the context for external plugins. Otherwise, we won't be able to fetch the storage entry.
=> plugin/wif: support external plugins

website/content/docs/auth/login-mfa/index.mdx, website/content/docs/auth/token.mdx
The [Token auth method](https://developer.hashicorp.com/vault/docs/auth/token) does not support [Login MFA](https://developer.hashicorp.com/vault/docs/auth/login-mfa). This PR adds two callouts on each of the linked pages.
Vercel preview:
- [Token auth method](https://vault-pxfk2h1vw-hashicorp.vercel.app/vault/docs/auth/token)
- [Login MFA](https://vault-pxfk2h1vw-hashicorp.vercel.app/vault/docs/auth/login-mfa)
=> [docs] Clarify that Login MFA is not supported for token auth

website/content/docs/platform/k8s/injector/examples.mdx
Adds an agent injector example showing annotations for cross namespace secret sharing.
Preview: https://vault-2ufl1m9vk-hashicorp.vercel.app/vault/docs/platform/k8s/injector/examples#cross-namespace-secret-sharing
=> docs/vault-agent-injector: cross namespace secret sharing example

website/content/api-docs/system/ha-status.mdx, website/content/api-docs/system/health.mdx, website/content/api-docs/system/replication/index.mdx, website/content/api-docs/system/replication/replication-dr.mdx, website/content/api-docs/system/replication/replication-performance.mdx
There are also some additional undocumented-until-now fields introduced previously that are unrelated, e.g. last_reindex_epoch and last_start and ssct_generation_counter.
=> Update api docs to reflect changes brought in by replication canary and clock skew

serviceregistration/consul/consul_service_registration.go
I spotted this as part of investigating an escalation. It wasn't the issue in the escalation but it felt like an easy win to just fix this after seeing it as opposed to waiting for it to cause a deadlock somewhere.
This defer is called as part of a for loop, which can cause problems, and the intent seems to be just for that line, so it makes sense to make it explicit.
=> Fix incorrectly deferred unlock in Consul service registration

ui/app/adapters/sync/association.js, ui/tests/integration/components/sync/secrets/page/destinations/destination/secrets-test.js
Fixes a broken flash message when unsyncing a secret.
<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
1. create a KV v2 secret
2. Go to secret syncs and create a Github destination
3. Sync a secret to the destination
4. Unsync the destination
5. No more flash error! 🎉
=> fix: don't show an undefined error in flash msg when unsyncing

website/content/partials/authn-names.mdx
Currently the Kubernetes entity alias source is listed as "not configurable", but there's the choice between Service Account UID and Service Account Name via the `alias_name_source` parameter. 
Should be backported to 1.14+.
=> Clarify the description of the Kubernetes entity alias configuration

vault/testing.go
Have any cluster created for testing by `NewTestCluster` default to supporting the expected `file`, `socket` and `syslog` audit backends.
=> Testing: `NewTestCluster` use default audit backends

vault/audit.go
Adjusts the ordering within `enableAudit` to reduce potential issues if there is an issue enabling an audit device. 
ENT PR: https://github.com/hashicorp/vault-enterprise/pull/5736
=> Audit: update `enableAudit` ordering

changelog/26464.txt, sdk/helper/compressutil/compress.go, sdk/helper/compressutil/compress_test.go
I also added a test to make sure it works with large compressions.
For what it's worth, it _seems_ to be a little bit faster, too, though that wasn't really the intent.
=> VAULT-20405 chunk decompression to prevent loading full decompressed data into memory at once

.github/actions/set-up-misspell/action.yml
The upstream golangci/misspell has modified the asset's filenames within their v0.5.0 release.
v0.5.0 changed mac to darwin and the 64bit to amd64
=> Adapt CI to use new filenames for misspell releases

builtin/logical/pki/integration_test.go, builtin/logical/pki/path_config_urls.go, changelog/26477.txt
* Use a less strict URL validation for PKI issuing and crl distribution urls
* comma handling
* limit to ldap
* remove comma hack
* changelog
* Add unit test validating ldap CRL urls
---------
=> Backport: Use a less strict URL validation for PKI issuing and crl distribution urls (#26477)

builtin/logical/pki/integration_test.go, builtin/logical/pki/path_config_urls.go, changelog/26477.txt
* Use a less strict URL validation for PKI issuing and crl distribution urls
* comma handling
* limit to ldap
* remove comma hack
* changelog
* Add unit test validating ldap CRL urls
---------
=> Manual backport: Use a less strict URL validation for PKI issuing and crl distribution urls (#26477)

changelog/26528.txt, go.mod, go.sum
Upgrades the Azure Secrets plugin to [v0.17.1](https://github.com/hashicorp/vault-plugin-secrets-azure/releases/tag/v0.17.1)
=> Upgrade `vault-plugin-secrets-azure` to `v0.17.1`

command/agent/agent_auto_auth_self_heal_test.go, command/agent_test.go
The root issue is that we weren't waiting for a new sink, just any sink (which included the file that we created earlier). If CI was especially fast or slow, it might simply read the old sink instead of the new sink (our intent).
I decided to ultimately remove the initial sink checks. Since sending it to the token channel won't send it to the sink channel at the same time, and we got race-y behaviour by the template server being able to re-auth (which does send to the sink channel). Further, these checks seemed unnecessary for testing what we wanted.
I also made some various cleanups and standardizations to these tests and added some additional assertions.
=> VAULT-25987 de-flake Test_NoAutoAuthSelfHealing_BadPolicy

ui/lib/sync/addon/components/secrets/page/overview.hbs, ui/tests/integration/components/sync/secrets/page/overview-test.js
Clarify that total secrets refers to total secrets of all time.
<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
</table>
Running against mirage (or a cluster that contains secrets sync data), visit the secrets sync overview page. Note the total # of secrets card.
=> [UI] Clarify total secrets on Sync overview page

changelog/26577.txt, ui/app/components/generated-item.js, ui/app/services/path-help.js, ui/app/templates/components/generated-item.hbs
Userpass has a new way of adding or updating the user's password: `password_hash`. This PR updates the validation on userpass auth method in the following ways:
* move the validation check to on submit instead of key up, to match how our other forms work 
* If editing a user, skip validation and let the API return the error if there is one
* If password AND password_hash are blank on a new user, show the validation message and prevent API request
* If password AND password_hash are present on a new user, show the validation message and prevent API request
=> Update userpass validations to handle password_hash

builtin/logical/transit/backend.go, builtin/logical/transit/path_cmac_ce.go, builtin/logical/transit/path_keys.go, builtin/logical/transit/path_keys_test.go
- Due to the amount of shared code for various key operations, have a general failure mechanism for CMAC key types within Transit when operating in CE
=> Transit operations on CMAC key types should fail on CE

ui/app/components/clients/page/acme.hbs, ui/app/components/clients/page/sync.hbs, ui/app/components/clients/page/token.hbs, ui/lib/core/addon/components/stat-text.hbs, ui/tests/integration/components/clients/page/acme-test.js, ui/tests/integration/components/clients/page/sync-test.js, ui/tests/integration/components/clients/page/token-test.js
=> UI: add monthly new chart to sync clients tab

website/content/docs/auth/login-mfa/faq.mdx, website/content/docs/concepts/namespace-api-lock.mdx, website/content/docs/configuration/storage/index.mdx, website/content/docs/enterprise/license/faq.mdx, website/content/docs/enterprise/namespaces/create-admin-namespace.mdx, website/content/docs/enterprise/namespaces/index.mdx, website/content/docs/interoperability-matrix.mdx, website/content/docs/partnerships.mdx, website/content/docs/secrets/databases/oracle.mdx, website/content/docs/secrets/venafi.mdx, website/content/docs/what-is-vault.mdx, website/content/partials/alerts/enterprise-and-hcp-use.mdx, website/content/partials/alerts/enterprise-and-hcp.mdx
This PR manually cherry-pick commits made by https://github.com/hashicorp/vault/pull/26457
* Replace 'HCP Vault' with 'HCP Vault Dedicated'
* Replace 'HCP Vault' with 'HCP Vault Dedicated' where applicable
* Replace 'Terraform Cloud' with 'HCP Terraform'
* Minor format fixes
* Update the side-nav title to 'HCP Terraform'
* Undo changes to Terraform Cloud secrets engine
=> Replace 'HCP Vault' with 'HCP Vault Dedicated' (#26457)

website/content/docs/upgrading/upgrade-to-1.16.x.mdx
I initially had the content in the partial file. Then I opted to put the content in the website/content/docs/upgrading/upgrade-to-1.16.x.mdx file instead. This was not a known issue but a behavior change.
=> docs: remove non-existing file reference

CODEOWNERS
Adds team [vault-ui](https://github.com/orgs/hashicorp/teams/vault-ui) as codeowners of the `ui` directory
=> Add vault-ui team to codeowners file

ui/app/components/clients/attribution.hbs, ui/app/components/clients/horizontal-bar-chart.js
I believe this bug was caused by upgrading the d3 pacakges
=> UI: Fix horizontal bar chart tooltip rendering

website/content/docs/release-notes/1.16.1.mdx
Add https://developer.hashicorp.com/vault/docs/upgrading/upgrade-to-1.16.x#ldap-auth-entity-alias-names-no-longer-include-upndomain to the Release Notes for 1.16
=> docs: update release notes for ldap auth change

ui/tests/acceptance/settings/mount-secret-backend-test.js
Backend PR: https://github.com/hashicorp/vault/pull/23914 updated the value returned by `sys/mounts/internal` to give the actual system default value instead of `0`
=> UI: update secret engine mount ttl format

ui/app/adapters/secret-engine.js, ui/tests/unit/adapters/secret-engine-test.js
This failure was introduced by the ember upgrade, merged into 1.17 only, so there is no changelog.
=> UI: Fix AWS secrets engine configure leases tab error

enos/enos-scenario-agent.hcl, enos/enos-scenario-autopilot.hcl, enos/enos-scenario-proxy.hcl, enos/enos-scenario-replication.hcl, enos/enos-scenario-smoke.hcl, enos/enos-scenario-ui.hcl, enos/modules/start_vault/main.tf, enos/modules/start_vault/variables.tf, enos/modules/vault_cluster/main.tf
The `VAULT_ENABLE_SEAL_HA_BETA` env var is still required to enable multiseal in 1.15.x.
=> enos: set the seal_ha_beta environment variable in 1.15.x

changelog/26525.txt, command/command_testonly/operator_usage_testonly_test.go, command/operator_usage.go
https://hashicorp.atlassian.net/browse/VAULT-24578
=> Add ACME client counts to vault operator usage

ui/package.json, ui/yarn.lock
"Backport" of https://github.com/hashicorp/vault/pull/26676
the vulnerable version (`< 8.4.31`) of `postcss` traced back to `ember-cli-autoprefixer` which was originally installed to support IE 11 by this [PR](https://github.com/hashicorp/vault/pull/4379/files#diff-193b27d62e4fbda3d563009fed5ec6761a05f73558d94b39fab63ae948c679eaR47). We stopped supporting IE 11 as far back as 1.9.x, see [Vault UI Browser Support](https://developer.hashicorp.com/vault/docs/v1.9.x/browser-support). 
Uninstalling the dependency instead of updating.
=> Backport 1.14.x: UI: Dependabot alert for postcss

ui/package.json, ui/yarn.lock
"Backport" of https://github.com/hashicorp/vault/pull/26676
the vulnerable version (`< 8.4.31`) of `postcss` traced back to `ember-cli-autoprefixer` which was originally installed to support IE 11 by this [PR](https://github.com/hashicorp/vault/pull/4379/files#diff-193b27d62e4fbda3d563009fed5ec6761a05f73558d94b39fab63ae948c679eaR47). We stopped supporting IE 11 as far back as 1.9.x, see [Vault UI Browser Support](https://developer.hashicorp.com/vault/docs/v1.9.x/browser-support). 
Uninstalling the dependency instead of updating.
=> Backport 1.16.x: UI: Dependabot alert for postcss

ui/.yarn/patches/lodash.template-npm-4.5.0-5272df3039.patch, ui/package.json, ui/yarn.lock
`ember-cli` and `ember-fetch` both use [lodash.template](https://www.npmjs.com/package/lodash.template) which is outdated. This PR patches the version we import with the changes from [this change to lodash](https://github.com/lodash/lodash/commit/3469357cff396a26c363f8c1b5a91dde28ba4b1c)
=> UI: patch lodash.template nested dependency

ui/lib/open-api-explorer/addon/components/swagger-ui.js, ui/tests/integration/components/open-api-explorer/swagger-ui-test.js
Fixes the search filter on the OpenAPI explorer.
https://github.com/hashicorp/vault/assets/903288/91e8ea50-a1a0-446c-86d4-9b9634738c09
Visit the OpenApi explorer page and the search box should work again 🎉
=> [UI] fix filter on api explorer

website/content/docs/concepts/tokens.mdx
Add documentation that specifies what error messages are returned by Vault when an invalid token is used.
=> Added docs for the error message changes

builtin/credential/aws/path_config_identity.go, builtin/credential/aws/path_login.go, website/content/api-docs/auth/aws.mdx, website/content/docs/concepts/identity.mdx, website/content/partials/authn-names.mdx
Hi,
This is another quality of life change. Using the assumed-role arn as the full_arn option has issues,
if you want predictable entity alias names -> in the case of EC2 and Code Build this is not the case.
This change adds canonical_arn as another option for identity configuration in addition to the others for IAM alias.
Thanks
=> Add canonicalArn as a entity alias name

http/handler.go, sdk/helper/consts/error.go, sdk/physical/inmem/inmem.go
This PR is some simple plumbing for a new error type that will be used to implement overload protection in Vault Enterprise.
No changelog since that will be added in the Enterprise PR. A link here is not very meaningful as this is just simple plumbing and testing infrastructure.
Docs are being added in a separate PR.
=> Overload error support for Adaptive Overload Protection (Enterprise)

ui/app/components/sidebar/nav/cluster.hbs, ui/app/components/sidebar/nav/cluster.js, ui/app/routes/application.js, ui/app/services/flags.ts, ui/app/services/version.js, ui/lib/sync/addon/components/secrets/landing-cta.hbs, ui/lib/sync/addon/components/secrets/page/overview.hbs, ui/lib/sync/addon/components/secrets/page/overview.ts, ui/lib/sync/addon/components/sync-header.ts, ui/lib/sync/addon/routes/secrets/overview.ts, ui/lib/sync/addon/templates/secrets/overview.hbs, ui/tests/acceptance/sync/secrets/overview-test.js, ui/tests/helpers/sync/sync-selectors.js, ui/tests/integration/components/sidebar/nav/cluster-test.js, ui/tests/integration/components/sync-status-badge-test.js, ui/tests/integration/components/sync/secrets/landing-cta-test.js, ui/tests/integration/components/sync/secrets/page/overview-test.js, ui/tests/integration/components/sync/sync-header-test.js, ui/tests/unit/services/flags-test.js
Note: merging to sidebranch until backend changes are merged. Final screenshots of all views will be added to sidebranch PR.
* Allows Managed clusters to view Secrets Sync from the sidebar nav and secrets sync overview.
* Updates badge text to include "Plus" when a user is coming from a managed cluster.
* Shows only one CTA message regardless of license / managed type.
* Updates tests.
=> Allow Managed clusters to see Secrets Sync Overview and Sidebar nav

ui/app/components/transit-edit.js, ui/app/routes/vault/cluster/secrets/backend/actions.js, ui/app/templates/components/transit-edit.hbs, ui/app/templates/components/transit-form-create.hbs, ui/app/templates/components/transit-form-edit.hbs, ui/app/templates/components/transit-form-show.hbs, ui/app/templates/vault/cluster/secrets/backend/transit-actions-layout.hbs, ui/tests/acceptance/transit-test.js, ui/tests/integration/components/transit-edit-test.js
This work is related to #26561 (see PR for motivation)
This PR adds the backend params to Transit secret engine links which were failing after replacing the router in the logout route. As part of this work, I replaced `KeyValueHeader` in transit with our `Page::Breadcrumbs` component, which has been our newer pattern. Both of the components use HDS breadcrumbs, but I didn't want to further complicate the logic in KeyValueHeader if we had a good replacement pattern.  
**Before**
**After**
=> UI: Update transit links

ui/app/styles/core/select.scss
=> UI: fix missing arrow for select dropdown

Makefile
Moves the tools step in `make bootstrap` to occur before prep.
`enumer` is a new required tool, and building fails without it:
```
==> Running go generate...
builtin/logical/pki/path_config_acme.go:397: running "enumer": exec: "enumer": executable file not found in $PATH
```
`make bootstrap` which is supposed to acquire all necessary tools for building eventually fails on this same tool error.
=> Call tools before prep in "make bootstrap" rule

website/content/api-docs/secret/identity/group-alias.mdx, website/content/api-docs/secret/identity/group.mdx
This PR corrects the _heading level_ for the **Parameters** sub-section of the **Delete group by ID** section. The incorrect heading level was causing **On this page** TOC to contain a Parameters section.
=> Fix heading level for Parameters in Identity/Group API doc page

ui/app/components/auth-jwt.js, ui/app/components/sidebar/nav/cluster.js, ui/app/controllers/vault/cluster/auth.js, ui/app/routes/vault/cluster.js, ui/app/services/flags.ts, ui/app/templates/vault/cluster/auth.hbs, ui/lib/sync/addon/components/secrets/page/overview.hbs, ui/lib/sync/addon/components/sync-header.ts, ui/lib/sync/addon/routes/secrets/overview.ts, ui/lib/sync/addon/templates/secrets/overview.hbs, ui/tests/acceptance/sync/secrets/overview-test.js, ui/tests/integration/components/sync/secrets/page/overview-test.js, ui/tests/unit/services/flags-test.js
`isManaged` -> `isHvdManaged`
`managedNamespaceRoot` -> `hvdManagedNamespaceRoot`
We decided to rename these to clarify what "managed" means—see original [PR discussion](https://github.com/hashicorp/vault/pull/26649/files#r1583563102).
=> Rename isManaged and managedNamespaceRoot

vault/logical_system_activity_write_testonly.go, vault/logical_system_activity_write_testonly_test.go
Now that we can directly pass an intent log into precomputedQueryWorker, we can call that directly rather than needing to make the precomputed queries ourselves.
=> Client count generation simplification

helper/testhelpers/testhelpers.go
Fixed a linty thing with `RetryUntilAtCadenceWithHandler` go doc, and added a note on `RetryUntil`.
=> Updated comments

builtin/logical/pki/cert_util.go, vault/audit.go, vault/auth.go, vault/core.go, vault/logical_system_helpers.go, vault/login_mfa.go
Already reviewed in Enterprise. 
These places all mask errors by not only not wrapping them but not even including the string of the underlying error and in a code path where the error could have come from Storage. We rely on propagating certain types of errors like `ErrReadOnly` for correctness so these all represent potential bugs.
Note that I have not chosen to normalize error wrapping here. We have a separate later task to standardize error wrapping but that is a much larger PR touching hundreds of thousands of lines of error handling with no functional change. These are all potential bugs currently since we use string comparison to detect these errors.
=> Fix places where we fail to propagate storage errors

http/handler.go, http/logical.go, http/priority/priority.go, sdk/logical/request.go, sdk/logical/response_util.go, vault/request_handling.go
This PR introduces the CE plumbing for a new HTTP header, called X-Vault-AOP-Force-Reject, which will force any associated request to reject storage writes as if Vault were overloaded.
This flag is intended to test end-to-end functionality of write rejection in Vault. This is specifically useful for testing 503 - Service Unavailable HTTP response codes during load shedding.
Associated tests are included in the Enterprise PR: https://github.com/hashicorp/vault-enterprise/pull/5770
=> AOP: Force reject header (enterprise)

website/content/docs/platform/servicenow/installation.mdx
It's not immediately obvious that the demo policy needs to be created beforehand and does not exist if only the tutorial steps are followed. Prompted by support ticket ZD-143426.
=> Add policy creation to AppRole setup

website/content/docs/concepts/events.mdx
Added missing ' to the command at the end
=> [DOCS]update events.mdx

website/content/docs/upgrading/vault-ha-upgrade.mdx
Due to the reported issue under https://github.com/hashicorp/vault/pull/24441, we identified that there are users issuing step-down during the upgrade, which is unintended.
We modified the documentation to make it clear that step-down should not be attempted, in addition rephrased the sentence with "step-down" word and exclude that term to avoid confusion.
=> Update vault-ha-upgrade.mdx to not step-down during upgrades

vault/logical_system.go, vault/logical_system_stubs_oss.go
This is used so that Enterprise code can do
additional initialization and store additional
state in the logical `SystemBackend`.
=> Add stub enterprise logical system backend and init

changelog/26790.txt, ui/lib/sync/addon/components/secrets/page/overview.ts, ui/tests/acceptance/sync/secrets/overview-test.js
If you were in a namespace and you activated the feature the secrets.overview model would not refresh. Because this model is generated from the route and not a backing ember data model, it's not super easy to just pass in the model to the transitionTo method. Instead, we need to trigger the model refresh manually via the [router.refresh()](https://api.emberjs.com/ember/5.8/classes/Route/methods/modelFor?anchor=refresh) method.
**Before within namespace**
https://github.com/hashicorp/vault/assets/6618863/8611a853-ca22-4da3-bfc2-45d12bbf8308
**After within a namespace**
https://github.com/hashicorp/vault/assets/6618863/37afefc2-2519-442e-b4d8-2cc5637ab3b1
- I checked if this was an issue on 1.16.x or maybe a result of a recent dependency upgrade but it appears to be a bug there as well.
=> Namespace banner bug Secrets Sync

.github/actions/build-vault/action.yml, .github/actions/changed-files/action.yml, .github/actions/checkout/action.yml, .github/actions/set-up-go/action.yml, .github/workflows/actionlint.yml, .github/workflows/build-artifacts-ce.yml, .github/workflows/build.yml, .github/workflows/changelog-checker.yml, .github/workflows/ci.yml, .github/workflows/code-checker.yml, .github/workflows/copywrite.yml, .github/workflows/enos-lint.yml, .github/workflows/enos-release-testing-oss.yml, .github/workflows/enos-run-k8s.yml, .github/workflows/oss.yml, .github/workflows/plugin-update-check.yml, .github/workflows/plugin-update.yml, .github/workflows/security-scan.yml, .github/workflows/stable-website.yaml, .github/workflows/test-ci-bootstrap.yml, .github/workflows/test-ci-cleanup.yml, .github/workflows/test-enos-scenario-ui.yml, .github/workflows/test-go.yml, .github/workflows/test-run-acc-tests-for-path.yml, .github/workflows/test-run-enos-scenario-matrix.yml
Pin to the latest actions in preparation for the migration to `actions/upload-artifact@v4`, `actions/download-artifact@v4`, and `hashicorp/actions-docker-build@v2` on May 6 or 7.
=> [QT-711] Pin to latest github actions

audit/broker.go
Use `timeout` rather than specifying separately.
~Fix~ tweak for https://github.com/hashicorp/vault/pull/26616 which used inline setting of `5 * time.Second` vs the `timeout` constant.
=> audit: log request: use `timeout` (5s)

ui/lib/core/package.json
=> Backport 1.16.x - ui deps: specify ember scope explicitly

ui/lib/core/package.json
=> Backport 1.15.x - ui deps: specify ember scope explicitly

ui/lib/core/addon/components/empty-state.hbs, ui/tests/acceptance/clients/counts/overview-test.js, ui/tests/acceptance/clients/counts/sync-test.js, ui/tests/acceptance/mfa-login-test.js, ui/tests/helpers/clients/client-count-selectors.ts, ui/tests/helpers/general-selectors.ts, ui/tests/integration/components/clients/line-chart-test.js
- uses test selectors instead of hard-coded `data-test-*` values
- nest some sync tests in top level module for easier test runs
Refer to our team Pattern Discussion document
=> [Secrets sync] update sync test selectors

ui/package.json, ui/tests/acceptance/clients/counts-test.js, ui/tests/acceptance/clients/counts/acme-test.js, ui/tests/acceptance/clients/counts/overview-test.js, ui/tests/acceptance/clients/counts/sync-test.js, ui/tests/acceptance/enterprise-license-banner-test.js, ui/tests/integration/components/calendar-widget-test.js, ui/tests/integration/components/clients/attribution-test.js, ui/tests/integration/components/clients/line-chart-test.js, ui/tests/integration/components/clients/page/counts-test.js, ui/tests/integration/components/clients/running-total-test.js, ui/tests/integration/components/dashboard/client-count-card-test.js, ui/tests/integration/components/date-dropdown-test.js, ui/tests/integration/components/keymgmt/key-edit-test.js, ui/tests/integration/components/kubernetes/page/credentials-test.js, ui/tests/integration/components/license-banners-test.js, ui/tests/test-helper.js, ui/tests/unit/adapters/clients-activity-test.js, ui/tests/unit/utils/timestamp-test.js, ui/yarn.lock
We’ve recently has some flaky client count tests `Attempted to wrap now which is already wrapped` and [this](https://github.com/hashicorp/vault/actions/runs/8925563058#summary-24514533520) failure (snippet below) a lot lately on CI
```
Error: Browser timeout exceeded: 10s
Error while executing test: Acceptance | wrapped_token query param functionality: it should authenticate when hitting logout url with wrapped_token when logged out
Stderr: 
Fontconfig error: No writable cache directories
[0502/143350.692707:INFO:config_dir_policy_loader.cc(118)] Skipping mandatory platform policies because no policy file was found at: /etc/opt/chrome/policies/managed
[0502/143350.712793:INFO:config_dir_policy_loader.cc(118)] Skipping recommended platform policies because no policy file was found at: …
```
=> install ember-sinon-qunit

ui/mirage/handlers/clients.js, ui/tests/acceptance/clients/counts/sync-test.js
In order to fix the sync test failing on the empty state, I added a mirage response for `sys/internal/counters/config` to set a static `billingStartTimestamp`. Before, the test was relying on the real vault config, which has an unreliable billing start date. 
Unclear if we need to backport this or not -- if we find more client count tests failing on release branches we can backport this as necessary
=> UI: Fix sync test

ui/app/services/flags.ts, ui/lib/sync/addon/components/secrets/page/overview.hbs, ui/lib/sync/addon/components/secrets/page/overview.ts, ui/tests/acceptance/clients/counts/overview-test.js, ui/tests/acceptance/sync/secrets/overview-test.js, ui/tests/helpers/sync/sync-selectors.js, ui/tests/integration/components/sync/secrets/page/overview-test.js
This PR adds a permissions check inside the `flags.js` service, using the `lazy-capabilities` macro. While this is the first use case of a permissions check inside a service it made sense. The prevalent pattern is to check capabilities inside the model. But this one endpoint is a POST with no data returned or used on it, so adding a model/adapter/serializer is not necessary.
**No permissions to POST to `sys/activation-flags/secrets-sync/activate`**
**With permissions to POST**
_Same view as before_
=> Add permissions check to show/hide activate button

changelog/26858.txt, ui/app/templates/components/console/log-help.hbs
The UI console has a broken link for the `web` command (missing an `s`).
=> ui: fix broken helper link for web command

helper/builtinplugins/builtinplugins_test.go, vault/testing.go
There was a previous fail in a test (`TestBuiltinPluginsWork/Whole_OpenAPI_document`) which claimed to be related to audit, but 
This is no longer required, `NewTestCluster` will not create `noop` audit, if no device types are configured, it will add the three supported ones (file, socket, syslog), and enable a file device with the discard file path (similar to a noop).
Also removes [this code](https://github.com/hashicorp/vault/pull/24493/files#diff-b1c046263e9208998666de7c5b5ad210feddbd4e3fc894ac61d64455f195c4b2R48-R52) which was added not long ago to get a test working during the migration to eventlogger for audit,
=> NewTestCluster: default to enabling a 'discard' file audit device when none are configured

changelog/26848.txt, ui/app/adapters/clients/activity.js, ui/app/components/dashboard/client-count-card.hbs, ui/app/components/dashboard/client-count-card.js, ui/app/components/dashboard/overview.hbs, ui/app/components/dashboard/replication-card.hbs, ui/mirage/handlers/clients.js, ui/tests/integration/components/dashboard/client-count-card-test.js, ui/tests/integration/components/dashboard/overview-test.js, ui/tests/unit/adapters/clients-activity-test.js
In https://github.com/hashicorp/vault/pull/26729 I removed the `@license` arg because the card no longer required the start time to pass to the activity log query. Inadvertently, this showed the card for users with just a default policy because the `@license` call would fail if a user didn't have permission. 
This PR wraps the card in an explicit permissions conditional, which is the same one we use to hide the link in the sidebar for users who do not have permission to `/activity`. Tests have also been added to avoid a future regression.
User with default policy
=> UI: wrap client count card in permission conditional

vault/logical_system.go, website/content/api-docs/system/config-auditing.mdx
Elsewhere in Vault the term used is `HMAC'd` as opposed to `HMAC'ed`.
=> Consistency using HMAC'd vs HMAC'ed in docs

ui/app/components/dashboard/client-count-card.hbs, ui/app/components/dashboard/learn-more-card.hbs, ui/app/components/dashboard/quick-actions-card.hbs, ui/app/components/dashboard/secrets-engines-card.hbs
If merged, this PR resolves the issue where dashboard heading levels did not only increase by one. **There should be no visual change with this PR, only underlying markup change.**
Bug: 
How it looked before:
How it looks after:
=> bugfix: dashboard overview heading levels

ui/lib/core/addon/components/toolbar-actions.hbs, ui/lib/core/addon/components/toolbar-filters.hbs, ui/lib/core/addon/components/toolbar.hbs
If merged, this PR would resolve the issue where toolbar navigation components did not have unique accessible names. 
Details:
- Added aria-label attributes to the different toolbar `nav` elements
=> bugfix: landmark elements must have unique accnames

ui/lib/core/addon/utils/client-count-utils.ts, ui/mirage/handlers/clients.js, ui/tests/helpers/clients/client-count-helpers.js, ui/tests/integration/components/clients/page/counts-test.js, ui/tests/integration/components/open-api-explorer/swagger-ui-test.js, ui/tests/integration/utils/client-count-utils-test.js
This way the upgrade banner only displays for users upgrading to 1.17. For users with `previous_version: null` the alert banner is not relevant.
=> UI: Only include upgrades with previous versions

website/content/docs/concepts/events.mdx, website/content/docs/concepts/seal.mdx, website/content/partials/telemetry-metrics/vault/audit/log_response_failure.mdx
Covers the following updates
Original PR | Failed backport | PR title
----------- | --------------- | -----------
#25119      | #26773          | Fix "auto unseal" case inconsistency
#25835      | #26755          | [DOCS] update events.mdx
#26038      | #26141          | changing vault.audit.log_response_failure metric
#25743      | #25796          | Documentation: WAF: add merkle-check documentation
=> [BACKPORT] Manual cherry-pick of failed release/1.15.x backport PRs

website/content/docs/concepts/events.mdx, website/content/docs/concepts/seal.mdx
Covers the following updates
Original PR | Failed backport | PR title
----------- | --------------- | -----------
#25119      | #26772          | Fix "auto unseal" case inconsistency
#25835      | #26754          | [DOCS] update events.mdx
#25743      | #25795          | Documentation: WAF: add merkle-check documentation
=> [BACKPORT] Manual cherry-pick of failed release/1.14.x backport PRs

changelog/26876.txt, command/secrets_enable.go, command/secrets_enable_test.go, command/secrets_tune_test.go, vault/logical_system.go, website/content/docs/commands/secrets/enable.mdx, website/content/docs/commands/secrets/tune.mdx
- The field hadn't been properly populated in the JSON struct being returned through the API response, but had been properly set in the stored structs in the backend.
- Add missing update to the command tune docs for the -delegated-auth-accessors option that existed
- Add -delegated-auth-accessors to the secret enable vault command along with a docs update
=> Add missing delegated_auth_accessors config field to /sys/mounts/<path> response

helper/testhelpers/corehelpers/corehelpers.go
Make it possible to add a suffix to the file used by `TestLogger`.
This feature is to be used a unit test in vault-enterprise.
=> Add NewTestLoggerWithSuffix for tests that need multiple log files

builtin/logical/pki/path_acme_order.go, builtin/logical/pki/path_acme_test.go, builtin/logical/pki/path_config_acme.go, changelog/26797.txt, website/content/api-docs/secret/pki.mdx, website/content/docs/secrets/pki/considerations.mdx
Add a new configuration parameter `max_ttl` within `/config/acme` that allows operators to configure the maximum TTL behavior of ACME issued certificates. The new argument defaults to the existing 90 day limit.
=> PKI: Allow operators to increase the maximum TTL for ACME issued certificates

builtin/logical/pki/backend_test.go, builtin/logical/pki/path_root.go, builtin/logical/pki/path_sign_issuers.go, changelog/26796.txt, website/content/api-docs/secret/pki.mdx, website/content/docs/upgrading/upgrade-to-1.17.x.mdx, website/data/docs-nav-data.json
- The PKI sign-intermediate API allowed an end-user to request a TTL value that would extend beyond the signing issuer's notAfter. This would generate an invalid CA chain when properly validated.
- We are now changing the default behavior to truncate the returned certificate to the signing issuer's notAfter.
- End-users can get the old behavior by configuring the signing issuer's leaf_not_after_behavior field to permit, and call sign-intermediary with the new argument enforce_leaf_not_after_behavior to true. The new argument could also be used to enforce an error instead of truncating behavior if the signing issuer's leaf_not_after_behavior is set to err.
=> PKI: Change sign-intermediate to truncate notAfter by default (behavior change)

.github/workflows/build.yml, .github/workflows/enos-lint.yml
A reimplementation of https://github.com/hashicorp/vault/pull/26892 that uses commit hashes (required by security) instead of direct versions.
=> Update hashicorp/set-product-version to version 2

website/content/partials/faq/client-count/upgrading.mdx
Corrected docs to say that upgrading from a version  <= 1.6 will cause only active clients after the upgrade to be stored.
Upgrades from any version > 1.6 will not have this issue.
=> Client Count Docs Change

ui/app/models/pki/config/acme.js, ui/app/models/pki/sign-intermediate.js, ui/lib/pki/addon/components/page/pki-configuration-details.hbs, ui/tests/acceptance/open-api-path-help-test.js, ui/tests/helpers/openapi/expected-secret-attrs.js, ui/tests/integration/components/pki/pki-sign-intermediate-form-test.js
Adds `max_ttl `to ACME config form and openApi expected attrs. In PKI sending `0` does not mean "use system defaults" and it is not an acceptable value. Hide the toggle for this TTL input and instead always show to avoid assumed default values.
And adds `enforce_leaf_not_after_behavior` for Sign intermediate actions
=> UI: Add max ttl to acme certificates 

command/server.go, vault/core_stubs_oss.go, vault/core_util.go
CE stubs to support reloadable AOP config.
Enterprise PR: https://github.com/hashicorp/vault-enterprise/pull/5805/files
=> AOP: Make config reloadable (enterprise)

builtin/logical/pki/backend.go
Certificate meta-data should remain local to the cluster that is issuing the certificate, not be replicated to another cluster.
=> PKI cert metadata should not cross cluster boundaries

.github/actions/build-vault/action.yml, .github/workflows/build.yml, .github/workflows/ci.yml, .github/workflows/copywrite.yml, .github/workflows/enos-lint.yml, .github/workflows/test-go.yml
Update `hashicorp/actions-packaging-linux` to our rewritten version
that no longer requires building a Docker container or relies on code
hosted in a non-hashicorp repo for packaging.
As internal actions are not managed in the same manner as external
actions in via the tsccr trusted components db, the tsccr helper is
unable to easily re-pin `hashicorp/*` actions. As such, we unpin some
pinned `hashicorp/*` actions to automatically pull in updates that are
compatible.
=> [QT-687] use new packaging action

http/handler.go, sdk/logical/request.go, vault/request_handling.go
This PR introduces a new TraceID context key for tracing forwarded requests.
Enterprise PR: https://github.com/hashicorp/vault-enterprise/pull/5822
=> Add a TraceID for forwarded request tracing

website/content/partials/ui/policy-requirements.mdx
https://developer.hashicorp.com/vault/docs/concepts/policies#ui-policy-requirements
`to the ui/mountsand ui/resultant-acl`
needs a space after mounts
=> [docs] fix lack of space character

changelog/26878.txt, command/server.go, vault/cluster.go
Vault currently displays duplicate and blank cluster labels when deployments are made with k8s.
This is the result of a race condition during the activation of the telemetry system. Telemetry is initialized before Vault is unsealed, therefore it is not able to pull the cluster name and information that is stored in encrypted storage.
To solve this, it was suggested that we store the cluster name in unencrypted storage, so that it can be accessed prior to Vault being unsealed. Vault will then attempt to pull from encrypted storage first, and if it is unable to pull out a valid name, it will then use the value stored in unencrypted storage.
=> Store Cluster Name in Physical Storage

scan.hcl
This PR introduces a few Semgrep rules:
- [trailofbits.go.hanging-goroutine.hanging-goroutine](https://semgrep.dev/playground/r/trailofbits.go.hanging-goroutine.hanging-goroutine?editorMode=advanced)
- [trailofbits.go.racy-append-to-slice.racy-append-to-slice](https://semgrep.dev/playground/r/trailofbits.go.racy-append-to-slice.racy-append-to-slice?editorMode=advanced)
- [trailofbits.go.racy-write-to-map.racy-write-to-map](https://semgrep.dev/playground/r/trailofbits.go.racy-write-to-map.racy-write-to-map?editorMode=advanced)
=> Add ToB Semgrep Rules

ui/tests/acceptance/enterprise-replication-modes-test.js
Not sure why this wasn't working, but it wasn't just flaky, it was consistently failing. I broke apart the `setupMocks` function and called it directly inside the test itself and that fixed it. 
This is failing on 1.15.x and 1.16.x to so i'll attempt a backport.
=> Fix failing enterprise-replication-modes-test

changelog/27019.txt, ui/app/models/secret-engine.js, ui/app/routes/vault/cluster/secrets/backend/list.js, ui/tests/acceptance/secrets/backend/generic/secret-test.js
This PR fixes the links for generic engines that were upgraded to V2 so that they can see the correct data. 
**Before, after upgrading:**
**After**
=> UI: Fix generic v2 secret engine links

changelog/26993.txt, ui/lib/core/addon/components/choose-pgp-key-form.hbs, ui/lib/core/addon/components/shamir/dr-token-flow.hbs, ui/tests/integration/components/choose-pgp-key-form-test.js, ui/tests/integration/components/shamir/dr-token-flow-test.js
This PR improves the DR Operation Token flow when using a PGP key. It replaces the CopySnippet component with CodeBlock which supports line wrapping, and it is updated so that errors returned from the API after clicking "Generate Operation Token" will show on the PGP screen. 
After: 
Before: 
This is only being backport to 1.16 because CodeSnippet was released in [Helios 3.1.0](https://github.com/hashicorp/design-system/releases/tag/%40hashicorp%2Fdesign-system-components%403.1.0) and Vault upgraded to v3 in 1.16
=> UI: improve DR Operation Token flow with PGP 

website/content/api-docs/index.mdx
This PR adds an explanation that when a **LIST** operation is issued and there are no results to return, the response is an HTTP 404 response.  For example, when no UI headers are configured:
```bash
$ curl -v -H "X-Vault-Token: $VAULT_TOKEN" -X LIST "$VAULT_ADDR/v1/sys/config/ui/headers"
*   Trying [::1]:8200...
* Connected to localhost (::1) port 8200
> LIST /v1/sys/config/ui/headers HTTP/1.1
> Host: localhost:8200
> User-Agent: curl/8.4.0
> Accept: */*
> X-Vault-Token: ********
>
< HTTP/1.1 404 Not Found
< Cache-Control: no-store
< Content-Type: application/json
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< Date: Fri, 03 May 2024 17:51:46 GMT
< Content-Length: 14
<
{"errors":[]}
```
=> Clarify behavior of list operations when no results found

go.mod, go.sum, sdk/go.mod, sdk/go.sum
https://github.com/protocolbuffers/protobuf-go/releases suggests no worrying changes since `v.1.33.0`
=> updated protobuf dependency to `v1.34.1` in main `go.mod` and `sdk/go.mod`

enos/README.md, enos/enos-dev-scenario-pr-replication.hcl, enos/enos-dev-scenario-single-cluster.hcl, enos/enos-dev-variables.hcl, enos/enos-globals.hcl, enos/enos-modules.hcl, enos/enos-terraform.hcl, enos/enos-variables.hcl, enos/enos.vars.hcl, enos/k8s/enos-terraform-k8s.hcl, enos/k8s/enos-variables-k8s.hcl, enos/modules/build_artifactory_package/main.tf, enos/modules/build_crt/main.tf, enos/modules/build_local/main.tf, enos/modules/vault_cluster/main.tf, enos/modules/vault_cluster/scripts/set-up-login-shell-profile.sh
Create developer scenarios that have simplified inputs designed for provisioning clusters and limited verification.
* Migrate Artifactory installation module from support team focused scenarios to the vault repository.
* Migrate support focused scenarios to the repo and update them to use the latest in-repo modules.
* Fully document and comment scenarios to help users outline, configure, and use the scenarios.
* Remove outdated references to the private registry that is not needed.
=> [VAULT-26888] Create developer scenarios

enos/enos-dev-scenario-pr-replication.hcl, enos/modules/vault_cluster/main.tf, enos/modules/vault_cluster/scripts/set-up-login-shell-profile.sh
Handle cases where `vault_cluster` is used more than once on a host. This includes cases where we aren't initing.
=> enos: correctly set up profile

website/content/docs/enterprise/mfa/index.mdx
🔍 [Preview deployment](https://vault-git-docs-fix-broken-mfa-links-hashicorp.vercel.app/vault/docs/enterprise/mfa)
- Remove broken links from top of page
- Add additional resources section to bottom with links to docs (so a practitioner does not leave the page by clicking links at the top)
- Make API section H2 so it appears in sidebar
=> Fix broken MFA links, add links to bottom of page

website/content/docs/upgrading/upgrade-to-1.14.x.mdx, website/content/docs/upgrading/upgrade-to-1.15.x.mdx, website/content/docs/upgrading/upgrade-to-1.16.x.mdx, website/content/partials/known-issues/perf-standbys-revert-to-standby.mdx
This PR adds a known issue for the read-only storage error introduced in https://github.com/hashicorp/vault/pull/26118.
=> Add a known issue for perf standby reverting to standby

changelog/27063.txt, go.mod, go.sum
This PR upgrades vault-plugin-auth-jwt to 0.17.3.
=> Update vault-plugin-auth-jwt to v0.17.3 in release/1.15.x

ui/lib/core/addon/components/selectable-card.hbs, ui/tests/integration/components/selectable-card-test.js
**Previously:**
https://github.com/hashicorp/vault/assets/6618863/a0513dff-3be7-4d2f-9584-fd4b62a9af58
**With Fix:**
https://github.com/hashicorp/vault/assets/6618863/d470d07d-3e69-4506-989c-28150c078c89
Guessing a backport to 1.16.x as I think [this](https://github.com/hashicorp/vault/issues/23739) might have been the regression pr.
=> Prevent SelectableCards from click events when disabled

go.mod
We upgraded sentinel and this is no longer needed.
=> Remove rsc/script replace directive for CE

website/content/api-docs/secret/pki.mdx, website/content/docs/secrets/pki/considerations.mdx
- Add missing enterprise notices on parameters and titles
- Mention that the metadata parameter is a base64 encoded string
- Tweak the no_store_metadata description
- Update some entries within the PKI considerations page
=> Update cert metadata docs

scripts/cross/Dockerfile, scripts/docker/Dockerfile.ui, ui/package.json
Now that we're on [Ember 5.4](https://github.com/hashicorp/vault/pull/26708), we can use [Node v20](https://github.com/ember-cli/ember-cli/blob/master/docs/node-support.md) 🎉
=> UI: Update node to version 20

ui/tests/acceptance/enterprise-control-groups-test.js, ui/tests/acceptance/enterprise-kmip-test.js, ui/tests/acceptance/enterprise-namespaces-test.js
This PR updates a couple test failures after #26872 was merged. I also attempted to stabilize the KMIP flaky tests in this
=> Fix enterprise tests failing after Web REPL a11y updates

website/content/partials/known-issues/perf-standbys-revert-to-standby.mdx
This PR adds some workarounds to the perf standby unseal known issue affecting Vault version 1.14.12, 1.15.8, and 1.16.2.
=> Retention months known issue workaround

vault/audit_test.go, vault/logical_system_test.go, vault/mount_test.go, vault/testing.go
This PR attempts to reduce the usage of a noop audit backend (`NoopAudit`), which exists only in test code, in almost every case it's fine (and preferable) to use a `file` backend with a `file_path` of `discard` as per the [documentation](https://developer.hashicorp.com/vault/docs/audit/file#discard).
The main thing to note in the PR is really the change to `NewTestCluster` which comes read-made with the three supported audit backends and no longer attempts to auto-enable an audit backend if none are provided in engineer supplied config.
`InitCores` was removed as it didn't appear to be used (`initCores` remains).
=> Audit: reduce usage of noop audit backend in tests

ui/tests/acceptance/enterprise-kmip-test.js
I discovered through searching slack for KMIP test failures that this test was flaky due to a lower limit of 1024 on the listener port. This PR updates the random port fn to have a lower limit of 1024
Will need to do manual backports so I left off the backport tags and will open those separately
=> UI: Fix flaky KMIP test

changelog/27094.txt, changelog/278094.txt, ui/lib/core/addon/utils/advanced-secret.js, ui/tests/unit/utils/advanced-secret-test.js
Regression PR #24530  
Fixes Issue #26709
Note: confirmed that you can in fact pass null as a value using curl, so this was a situation we needed to allow in the UI.
**Before:**
https://github.com/hashicorp/vault/assets/6618863/4bf5b87e-cd88-4e5a-ae5e-139d98b86837
**After:**
https://github.com/hashicorp/vault/assets/6618863/b75ce618-4c6a-40d4-a7ef-da8d411052b8
=> UI fix KVv2 in json editor when value is null

changelog/27134.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/9162913268
=> Update vault-plugin-secrets-alicloud to v0.17.0

changelog/27139.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/9163625731
=> Update vault-plugin-database-redis-elasticache to v0.4.0

changelog/27149.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/9165910390
=> Update vault-plugin-secrets-mongodbatlas to v0.12.0

changelog/27122.txt, go.mod, go.sum
This PR upgrades vault-plugin-auth-jwt 0.16.0 -> 0.16.1 in release/1.14.x.
=> Update vault-plugin-auth-jwt to v0.16.1 in release/1.14.x

sdk/helper/keysutil/policy.go, sdk/helper/keysutil/policy_test.go
- Missed during the initial development of the Transit CMAC feature, on initial key creation we did not generate HMAC keys when the key type was CMAC. The call to the policy's Upgrade function though would treat this key as requiring an upgrade and add one back.
- Fix this by adding an HMACSupported argument and verifying on upgrade for HMAC creation that the key type supports HMAC
- Add generic test that verifies we aren't changing a key type iota value, string it defined and the proper operation of HMACSupported and CMACSupported functions
=> Do not generate HMAC keys for CMAC keys on calls to Upgrade

ui/tests/helpers/openapi/expected-auth-attrs.js
Two changes: auth method config Azure and one for auth method config GCP.
I confirmed all of these changes are now on the UI config forms for these auth methods and they work as expected.
**Azure:**
**GCP:** _hard to get the full form in view_
=> Update OpenAPI glob to match backend response

changelog/27163.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/9181070003
=> Update vault-plugin-secrets-gcpkms to v0.17.0

ui/lib/sync/addon/components/secrets/page/overview.hbs, ui/lib/sync/addon/components/secrets/page/overview.ts, ui/lib/sync/addon/components/secrets/sync-activation-modal.hbs, ui/lib/sync/addon/components/secrets/sync-activation-modal.ts, ui/tests/acceptance/sync/secrets/overview-test.js, ui/tests/helpers/sync/sync-selectors.js, ui/tests/integration/components/sync/secrets/page/overview-test.js, ui/tests/integration/components/sync/secrets/sync-activation-modal-test.js
Split Activation modal into a separate component. There are no user facing changes here; just the new component and tests.
=> [Secrets Sync] split activation modal into separate component

builtin/logical/pki/ca_util.go, builtin/logical/pki/ca_util_test.go, changelog/27093.txt, sdk/helper/certutil/types.go, sdk/helper/certutil/types_test.go
This PR is to address the error described in issue #26089 with ed25519 keys
=> Fix ed25519 key type in ca_util

vault/activity_log.go
While creating CE PR for retention months bug PR https://github.com/hashicorp/vault-enterprise/pull/5869, removing SetConfig from setDefaultRetentionMonthsInConfig was missed. 
We do not need this, we call SetConfigInit immediately after setDefaultRetentionMonthsInConfig is called in NewActivityLog()
https://github.com/hashicorp/vault/blob/1884267e0f03f5e44c1100d3f5c790050068a9b3/vault/activity_log.go#L286
=> Remove SetConfig from setDefaultRetentionMonthsInConfig

go.mod
CI sadness meant that `api` was updated in https://github.com/hashicorp/vault/pull/27190
=> Use new sdk and api versions

ui/app/controllers/vault/cluster/access/leases/list.js, ui/app/controllers/vault/cluster/access/leases/show.js
Building off of this [PR](https://github.com/hashicorp/vault/pull/27144), I caught a few more cases of missing Title Case breadcrumbs. 
**Screenshots of the updated views:**
=> Title case Leases edit and show breadcrumbs

changelog/27203.txt, website/content/api-docs/secret/ldap.mdx, website/content/docs/secrets/ldap.mdx
This PR proposes documentation updates to the LDAP secrets engine for hierarchical path handling.
Relavant plugin PRs:
- https://github.com/hashicorp/vault-plugin-secrets-openldap/pull/102
- https://github.com/hashicorp/vault-plugin-secrets-openldap/pull/104
- https://github.com/hashicorp/vault-plugin-secrets-openldap/pull/105
Vault PR to update the bundled plugin
- https://github.com/hashicorp/vault/pull/27137
=> docs: ldap secrets hierarchical paths

builtin/logical/transit/path_hmac.go, builtin/logical/transit/path_hmac_test.go, changelog/27211.txt
Parameter 'algorithm' has been deprecated in favour of 'hash_algorithm', so update the pathHMACVerify() handler to use it when it is present.
=> Use hash_algorithm parameter on Transit's verify HMAC requests.

website/content/api-docs/secret/pki.mdx
- The API docs for the PKI EST configuration was missing the audit_fields parameter.
- Also fix up the example EST responses
=> Add missing audit_fields EST configuration parameter to docs

vault/external_tests/consul_fencing_binary/consul_fencing_test.go
Change the total timeout for the test from 5 to 15 minutes.
Use a corehelters.TestLogger so that the output of the test gets saved on a file on failures.
=> Increment timeout of TestConsulFencing_PartitionedLeaderCantWrite.

changelog/11084.txt, serviceregistration/consul/consul_service_registration.go, serviceregistration/consul/consul_service_registration_test.go, website/content/docs/configuration/service-registration/consul.mdx, website/content/docs/configuration/storage/consul.mdx
Hi there!
I'd love to be able to set [`ServiceMeta`](https://www.consul.io/api-docs/catalog#servicemeta) on the Consul service registered by Vault by specifying the desired tags in the config file, and I'm submitting this PR to that effect.
I'm not happy about unmarshalling json during `NewServiceRegistration` but considered that a simpler change than the couple of alternatives I came up from a quick glance at the codebase. That is to say, I'd love feedback on the approach (and perhaps suggestions on a proper testing strategy should folks feel this approach works).
fixes #9121
see also #10233
=> Allow setting of Consul ServiceMeta tags from config file

changelog/26993.txt, ui/lib/core/addon/components/choose-pgp-key-form.hbs, ui/lib/core/addon/components/shamir/dr-token-flow.hbs, ui/tests/helpers/clients.js, ui/tests/integration/components/choose-pgp-key-form-test.js, ui/tests/integration/components/shamir/dr-token-flow-test.js
=> Backport UI: improve DR Operation Token flow with PGP  (#26993)

website/content/docs/configuration/storage/raft.mdx
Link and link title were the wrong way round. Quick PR to fix that.
Will also need backporting to the 1.17 branch. I think I've added the right labels for that, but I don't do this regularly so I'm not sure :)
=> Docs: Correct the link to namespace limits from within the new max_mount_and_namespace_table_entry_size docs

changelog/27263.txt, ui/app/services/permissions.js, ui/tests/unit/services/permissions-test.js
This PR builds on the work from #26233. It hides the resultant-ACL banner if there are non-deny wildcard policies present for any ancestor of the current namespace. The changes in this PR are best illustrated through an example:
**Example scenario**
User Bob logs in at `foo` namespace and then navigates to namespace `/foo/bar/baz`. Bob has a policy with the following block: 
```
path "bar/*" {
capabilities = ["read", "update", "list"]
}
```
before, the wildcard calculation would determine the user does not have access because it was only checking a wildcard path at the user's relative root namespace (in this case, `foo/`). With this change, the wildcard calculation takes the current namespace `foo/bar/baz` and checks at each level if the Bob has wildcard access. The results are as …
=> UI: Don't show resultant-ACL banner in nested namespace if ancestor wildcard policy 

website/content/docs/agent-and-proxy/agent/winsvc.mdx, website/content/docs/agent-and-proxy/index.mdx
While we don't have a page dedicated to it, Vault Proxy is supported as a Windows Service too, just like Agent. This caused some confusion (and a customer wondering if they had a migration path from Agent) so I thought it best to confirm that it does work.
=> Note that Vault Proxy is supported as a Windows Service

website/content/api-docs/secret/transit.mdx
Add a little bit of cross linking within the Transit API docs along with documenting the new missing `cmac` argument within the existing verify API.
=> Add missing cmac argument to Transit verify API docs

ui/lib/sync/addon/routes/secrets/overview.ts, ui/tests/acceptance/sync/secrets/overview-test.js
Adds a secondary layer of protection to the Sync overview page, ensuring users can't access the page by pasting the URL directly.
+ Adds additional acceptance tests to cover this. We already have thorough integration testing of the sidebar, sync page, and flags service, but the acceptance tests here help verify that the redirects are working if a user directly visits the URL.
Follow up to https://github.com/hashicorp/vault/pull/27262/files
Ent tests pass locally except for unrelated replication / kv tests
🚫 Using an OSS cluster, verify you cannot directly access `http://localhost:4200/ui/vault/sync/secrets/overview`.
✅ Using an ENT cluster, verify you _can_ access `http://localhost:4200/ui/vault/sync/secrets/overview` (and see "sync" in the sidebar).
=> Gate sync overview route for users without access

changelog/9733.txt, website/content/docs/configuration/storage/cassandra.mdx
This is a strange PR, but it's a supporting PR for the code changes that come as part of this community PR: https://github.com/hashicorp/vault/pull/9733
This PR has been open for ~four years, and it seems unreasonable to ask the submitter to come back after all that time to add a changelog/docs. However, I don't want to let it languish since the PR seems like an easy win.
This is the compromise -- I can add the docs/changelog, since it's easy enough, and I'll merge both together so everyone wins.
=> Add docs and changelog for PR 9733

.github/actions/install-external-tools/action.yml, tools/tools.sh
Pin `protoc-gen-go-grpc` to `v1.3.0` as `v1.4.0` requires `google.golang.org/grpc >= v1.62`, which we are not currently updating on older branches. If we end up upgrading the grpc module we can upin this bring in the latest gRPC changes.
=> proto: pin protoc-gen-go-grpc to v1.3.0

changelog/27289.txt, ui/app/components/tool-actions-form.js, ui/app/components/tool-wrap.js, ui/app/templates/components/tool-actions-form.hbs, ui/app/templates/components/tool-hash.hbs, ui/app/templates/components/tool-lookup.hbs, ui/app/templates/components/tool-random.hbs, ui/app/templates/components/tool-rewrap.hbs, ui/app/templates/components/tool-unwrap.hbs, ui/app/templates/components/tool-wrap.hbs, ui/tests/acceptance/tools-test.js, ui/tests/helpers/tools-selectors.ts, ui/tests/integration/components/tools/tool-wrap-test.js
After initially wrapping data, clicking "Back" and then "Wrap data" again results in the incorrect data being sent to the backend, so upon "unwrapping" we do not get `{foo:"bar"}` but instead `{token:""}`
Notice that now both generated tokens unwrapped the expected data
=> UI:  Allow repeat data wrapping for wrap tool

.github/workflows/do-not-merge-checker.yml
This PR adds a new CI check for the do-not-merge label. The check just fails if the label is present.
=> Add a CI check for do-not-merge label

website/content/docs/configuration/listener/tcp/index.mdx, website/content/docs/configuration/listener/tcp/tcp-tls.mdx, website/data/docs-nav-data.json
* Add TCP TLS guide
* Apply Suggestions for TCP-TLS docs (#27335)
=> Manual backport for Add TCP TLS guide into release/1.16.x (#27318)

website/content/docs/configuration/listener/tcp/index.mdx, website/content/docs/configuration/listener/tcp/tcp-tls.mdx, website/data/docs-nav-data.json
* Add TCP TLS guide
* Apply Suggestions for TCP-TLS docs (#27335)
---------
Co-authored-by: Jamie Finnigan <jfinnigan@hashicorp.com>
Co-authored-by: Sarah Chavis <62406755+schavis@users.noreply.github.com>
=> Manual backport for Add TCP TLS guide into release/1.15.x (#27318)

enos/enos-samples-ce-build.hcl, enos/enos-samples-ce-release.hcl
Temporarily removing SLES from Enos samples while we troubleshoot some issues with package installs.
=> Temporarily remove SLES from samples

changelog/27379.txt, command/operator_usage.go, vault/external_tests/activity/activity_util.go, vault/logical_system_activity.go
Relevant ENT PR: https://github.com/hashicorp/vault-enterprise/pull/5917
Docs PR: https://github.com/hashicorp/vault/pull/27266
Deprecate default_report_months PR: https://github.com/hashicorp/vault/pull/27350
`closes` https://github.com/hashicorp/vault-enterprise/pull/5917
=> Set default reporting start time to billing start date

builtin/logical/pki/acme_challenge_engine.go, builtin/logical/pki/acme_state.go, builtin/logical/pki/acme_wrappers.go, builtin/logical/pki/ca_util.go, builtin/logical/pki/cert_util.go, builtin/logical/pki/cert_util_test.go, builtin/logical/pki/cieps_util_oss.go, builtin/logical/pki/crl_util.go, builtin/logical/pki/key_util.go, builtin/logical/pki/path_acme_order.go, builtin/logical/pki/path_config_acme.go, builtin/logical/pki/path_fetch_keys.go, builtin/logical/pki/path_issue_sign.go, builtin/logical/pki/path_ocsp.go, builtin/logical/pki/path_revoke.go, builtin/logical/pki/path_root.go, builtin/logical/pki/periodic.go, builtin/logical/pki/secret_certs.go, builtin/logical/pki/storage.go, builtin/logical/pki/util.go
The Backend field in the struct storageContext in the pki package makes it impossible to re-use the code that uses it in other PKI backends.
Change the code to avoid making direct usage of the Backend field in preparation to make it more modular.
=> Remove direct usage of logical/pki's storageContext.Backend field

.github/actions/set-up-misspell/action.yml
It appears that starting with v0.5.2 the misspell linter embeds the version directory into the release archive.
=> lint: fix misspell linter install

enos/enos-globals.hcl, enos/enos-scenario-agent.hcl, enos/enos-scenario-autopilot.hcl, enos/enos-scenario-proxy.hcl, enos/enos-scenario-replication.hcl, enos/enos-scenario-seal-ha.hcl, enos/enos-scenario-smoke.hcl, enos/enos-scenario-upgrade.hcl, enos/enos-variables.hcl, enos/enos.vars.hcl, enos/modules/ec2_info/main.tf
This weekend, assumingly in accordance with Leap 15.4 EOL processes, all Leap 15.4 AMIs were pulled (except for a single micro AMI), therefore breaking our query for these AMIs. In this PR we remove the broken Leap 15.4 data source as well as references to Leap 15.4 in Enos testing. We also remove a few vestiges from previous testing of Ubuntu 18.04 which is EOL as well.
=> Remove Leap 15.4 from Enos testing matrices and AMI data sources

vault/expiration.go
Added a note to give callers a warning that under certain circumstances both return values may be `nil`.
=> Leases: added note to go doc for loading an entry from the expiration manager

changelog/27424.txt, ui/app/models/role-aws.js
This PR fixes a bug where choosing `session_token` type when creating a role broke the creation flow:
After fix:
=> UI: Allow creation of AWS session_token type role

changelog/27426.txt, vault/logical_system_activity.go, website/content/api-docs/system/internal-counters.mdx, website/content/docs/upgrading/upgrade-to-1.18.x.mdx
ENT PR: https://github.com/hashicorp/vault-enterprise/pull/5997
=> Deprecates current_billing_period

vault/external_tests/consul_fencing_binary/consul_fencing_test.go
`TestConsulFencing_PartitionedLeaderCantWrite` has been intermittently failing in CI. This PR disables (skips) the test for now. Once this is merged in we will focus on making the test more reliable and re-enabling it.
=> Skip TestConsulFencing_PartitionedLeaderCantWrite until we make it less flaky

builtin/logical/pki/backend.go, builtin/logical/pki/cert_util.go, builtin/logical/pki/crl_util.go, builtin/logical/pki/issuing/issuers.go, builtin/logical/pki/parsing/certificate.go, builtin/logical/pki/path_fetch_issuers.go, builtin/logical/pki/path_tidy.go, builtin/logical/pki/periodic.go, builtin/logical/pki/pki_backend/common.go, builtin/logical/pki/pki_backend/storage_context.go, builtin/logical/pki/revocation/revocation_entry.go, builtin/logical/pki/revocation/revoke.go, builtin/logical/pki/storage.go, builtin/logical/pki/storage_unified.go, builtin/logical/pki/util.go
Continue refactoring PKI code to decouple it from the main PKI `Backend`.
These changes build on the work started on PR #27401.
=> Ongoing refactoring of PKI revocation code

website/content/docs/concepts/seal.mdx, website/content/docs/configuration/seal/seal-ha.mdx
Accidentally have it in a couple places.  Will backport to 1.16.x.
=> Remove the Beta flag from Seal HA

.github/workflows/test-run-enos-scenario-matrix.yml
Fix a node deprecation warning by updating our actions-slack-status to v2.0.1, which pulls in a newer version of the github-script action that causes the deprecation warning.
=> actions: update actions-slack-status to v2.0.1

.github/workflows/changelog-checker.yml, changelog/27450.txt
This makes the changelog checker fail when a feature changelog is incorrectly formatted, and updates the information about where to find info on changelogs.
Fails like this:
For the following changelog:
I've validated that this works correctly with a correctly formatted changelog for features and non-features alike.
Passes fine for e.g.
=> Automate feature changelog checking

.github/pull_request_template.md
Removes the changelog checklist item from the PR template. 
I updated the GHA and enhanced it to check for the `feature` formatting here: https://github.com/hashicorp/vault/pull/27450
Based in discussion of the initial implementation of this, I believe this obviates the need for the changelog checklist item. I'm open to being challenged on that, and if there's additional changes we'd like to make to the changelog checker before we think it's okay to remove, I'm happy to implement those as part of this PR. …
=> Remove changelog checklist item from PR template

changelog/14723.txt, vault/mount.go
resolves #14696 
I didn't expect this to be so simple, but it seems like removing `identity` from the "non tunable" mounts list just works, at least for the audit hmac tuning I've tested.
There may be other impacts I'm not aware of due to this, if y'all can think of any you want me to test for specifically please let me know, I'm happy to do so
I built my branch locally and started a Vault test server
```
> bin/vault server -dev -dev-root-token-id=test        
```
In another shell I ran the follow commands to enable audit logs, write some groups, tune identity to allow the `name` field to be printed in plaintext in audit logs, and then write some groups again:
```
>  vault audit enable file file_path=/tmp/vault.log
Success! Enabled the file audit device at: file/
> vault write …
```
=> Allow `identity` mount to be tunable

changelog/27464.txt, physical/raft/raft_autopilot.go
While dealing with an autopilot escalation, I noticed that the logging when autopilot starts up is suboptimal, for a few reasons.
* The struct that is written to the logs is fairly useless, as you only see values, not struct member names
* If the autopilot reconcile interval hasn't been modified via the config (which is the case the overwhelming majority of the time, I imagine) then `reconcile_interval 0s` is printed to the logs, which is incorrect, and actually alarming. What's happening is it's printing out the value of the reconcile interval as it exists on the raft backend, which is 0 by default, but _that's not actually the value autopilot is using_. This is misleading.
This makes the autopilot config struct print in a better way and also updates the logging to not actually print the …
=> improve autopilot logging when it starts up

website/content/docs/upgrading/upgrade-to-1.16.x.mdx, website/content/partials/known-issues/1_16-jwt_auth_bound_audiences.mdx
=> docs: backport to 1.16.x jwt auth bound audiences

website/content/docs/upgrading/upgrade-to-1.15.x.mdx, website/content/partials/known-issues/1_15-jwt_auth_bound_audiences.mdx
=> docs: backport to 1.15.x jwt auth bound audiences

helper/testhelpers/ldap/ldaphelper.go
This PR also captures the logs of the docker container launched to run an LDAP server fas a fixture for testing when the **PrepareTestContainer** function itself fails the test currently running.
Since the t.Fatalf() method is equivalent to calling t.Logf() followed by t.FailNow(); this change replaces the call to t.Fatalf() with a t.Logf() call and then _also logs the failed docker container logs_ before finally calling t.FailNow().
=> capture docker logs if container creation failed

changelog/27474.txt, vault/namespaces_oss.go, vault/raft.go
CE part of https://github.com/hashicorp/vault-enterprise/pull/6059
files.
=> VAULT-25456 CE side of changes for snapshot restore namespace cache bug

website/content/api-docs/system/secrets-sync.mdx
Remove association mistakenly had two `name` parameters instead of `name` and `secret_name`.
=> Fix remove association parameter in secrets-sync.mdx

enos/enos-globals.hcl, enos/enos-scenario-autopilot.hcl, enos/enos-scenario-upgrade.hcl
Fix a race in the `upgrade` scenario by waiting for the cluster to elect a leader before attempting to get the ip addresses.
https://github.com/hashicorp/vault/actions/runs/9503957362/job/26200475179?pr=27493#step:11:55
files.
=> enos: use the initial version's install dir in upgrade

website/content/docs/platform/servicenow/configuration.mdx
🔍 [Deploy preview](https://vault-8ybwqkcp3-hashicorp.vercel.app/vault/docs/platform/servicenow/configuration#configuring-discovery-credentials)
This PR fixes the [broken hyperlink](https://developer.hashicorp.com/vault/docs/platform/servicenow/configuration#creating-a-secret-in-vault) due to an extra space
files.
description. …
=> [Docs] Remove an extra space

command/server/listener_tcp_test.go
* Removed `td` temp dir creation as not used.
* Switched to testify to clean up tests
* Set dial timeout to 3 secs
=> Clean up test file

changelog/27510.txt, command/agent.go, command/agent_test.go, command/commands.go, command/proxy.go, command/proxy_test.go, command/server.go, command/util.go
This adds the ability to get pprof data from Agent and Proxy using SIGUSR2, similar to Vault server.
=> Add SIGUSR2 pprof to agent and proxy

vault/activity/query.go, vault/activity/query_test.go
Adds functions to combine the precomputed Query and the current month records. This functions are unused at the moment. This is scaffolding to be able to combine the new totals we will calculate in future PR's using the HLL's.
ENT PR: https://github.com/hashicorp/vault-enterprise/pull/6079
closes https://github.com/hashicorp/vault-enterprise/pull/6079
files.
in the PR description, …
=> Added method to join PQ and current month, with tests

website/content/docs/release-notes/1.17.0.mdx, website/content/docs/upgrading/upgrade-to-1.17.x.mdx, website/content/partials/known-issues/agent-and-proxy-excessive-cpu-1-17.mdx, website/content/partials/known-issues/ocsp-redirect.mdx
This adds a known issue for the issue fixed by https://github.com/hashicorp/vault/pull/27518 and described by VAULT-28192.
As per guidance, I added versions to all of the Changes as opposed to adding a new Versions column.
files.
=> VAULT-28192 Add known issue for Agent/Proxy CPU issue

audit/broker.go, audit/broker_test.go, changelog/27531.txt
When the audit system is asked to log a request or response, it now checks the viability of the existing supplied context. The context is considered unviable if it has `<5s` remaining on its deadline, and a new context is created for use.
However, we're seeing issues where some users are getting audit log failures as the incoming context is already cancelled entirely. This means that audit will fail and report telemetry etc. which isn't what users want. 
This PR includes the cancelled context in its evaluation of viability, and will create a new context with a `5s` timeout if it is cancelled. 
NOTE: We don't just return immediately from `LogRequest` and `LogResponse` if the context was cancelled, as we want to make every effort to capture that Vault was asked to service a request - in the …
=> Audit: check if context is already cancelled when assessing viability for audit

website/content/docs/upgrading/upgrade-to-1.17.x.mdx, website/content/partials/known-issues/1_16-jwt_auth_bound_audiences.mdx
This PR clarifies the upgrade docs around the JWT bound_audiences change (the fact that it becomes a mandatory field if the JWT presents an `aud`, which is very often the case (e.g. with GitLab)).
=> clarify the JWT auth bound_audiences change in behaviour

changelog/27518.txt, command/agent/template/template.go, command/agentproxyshared/auth/auth.go
Fixes an issue introduced in 1.17 where CPU usage in Agent and Proxy are extremely high due to the code taking the same path down a select statement repeatedly (in an infinite loop).
Will be backported to 1.17.
Fixes https://github.com/hashicorp/vault/issues/27505
files. …
=> VAULT-28192 fix Agent and Proxy consuming large amounts of CPU for auto-auth self-healing

vault/activity_log_util_common.go, vault/activity_log_util_common_test.go
I'm sorry this PR is so large! Most of it is from test changes. 
files.
=> VAULT-28024: Current month new clients by namespace and mount

vault/activity/query.go, vault/activity/query_test.go
I realized I missed something when reviewing the original PR - this needs to be adding the *new* counts to the existing precomputed query, not the total counts. My bad!!
Updated the test to verify that we're combining the NewClients.Namespaces field, and not Namespaces.
files. …
=> add new clients to namespace counts

website/content/docs/release-notes/1.15.0.mdx, website/content/docs/release-notes/1.16.1.mdx, website/content/docs/upgrading/upgrade-to-1.15.x.mdx, website/content/partials/known-issues/1_15-auto-upgrade.mdx
Manual backport of changes in #27454 to the 1.16.x release branch
=> [BACKPORT] Manual cherry-pick of #27454 to 1.16.x

website/content/docs/release-notes/1.15.0.mdx, website/content/docs/upgrading/upgrade-to-1.15.x.mdx, website/content/partials/known-issues/1_15-auto-upgrade.mdx
Manual backport of changes in #27454 to the 1.15.x release branch
=> [BACKPORT] Manual cherry-pick of #27454 to 1.15.x

website/content/docs/release-notes/1.16.1.mdx, website/content/docs/upgrading/upgrade-to-1.16.x.mdx, website/content/partials/known-issues/1_16_secrets-sync-chroot-activation.mdx
Adds a known issue for chroot namespaces when trying to activate secrets sync. Adds a release note regarding the need to use the new activation-flags for secrets sync.
files.
=> Add chroot known-issue and sync activation-flag release note

changelog/27559.txt, ui/app/adapters/clients/activity.js, ui/app/components/clients/no-data.hbs, ui/app/components/dashboard/client-count-card.hbs, ui/app/components/dashboard/client-count-card.js, ui/app/models/clients/config.js, ui/mirage/handlers/clients.js, ui/tests/acceptance/dashboard-test.js, ui/tests/integration/components/clients/no-data-test.js, ui/tests/integration/components/dashboard/client-count-card-test.js
The `sys/internal/counters/activity` response now defaults to use the license start time to the current month as start and end time params (previously the `start_time` was the current month minus one year and `end_time` was the month before current. For example, if it's currently June 2024, the data returned would be from June 2023-May 2024.)
As a result, `current_billing_period` is now deprecated so we can remove this query param from the dashboard request to the activity log.
✅ enterprise tests
=> UI: remove `current_billing_period` from dashboard activity log request

ui/docs/how-to-docfy.md, ui/package.json, ui/scripts/docfy-md.js, ui/scripts/generate-docs.sh
update docfy readme and add command to run enterprise tests
=> add command to run enterprise tests and update docfy readme

changelog/27563.txt, physical/azure/azure.go, physical/azure/azure_test.go
Solves Azure Storage Backend initialization issue due to invalid account name. The container name was being passed into the account name verification function which has the potential of violating Azure's storage account name requirements.
- [N/A] **Labels:** If this PR is the CE portion of an ENT change, and that ENT change is
- [✅ ] **Labels:** If this PR is a CE only change, it can only be backported to N, so use
- [N/A] **ENT Breakage:** If this PR either 1) removes a public function OR 2) changes the signature
applying the …
=> VAULT-28281: Pass in accountName variable into validation function

enos/enos-scenario-agent.hcl, enos/enos-scenario-autopilot.hcl, enos/enos-scenario-proxy.hcl, enos/enos-scenario-replication.hcl, enos/enos-scenario-seal-ha.hcl, enos/enos-scenario-smoke.hcl, enos/enos-scenario-upgrade.hcl
In preparation for arm64 builds of `hsm`, `fips1402`, and `hsm.fips1402` editions of Vault Enterprise we'll allow them in our test scenarios.
Enterprise counterpart: https://github.com/hashicorp/vault-enterprise/pull/6106
files.
=> VAULT-28307 enos: allow arm64 fips1402 and hsm editions

ui/app/components/auth-jwt.js, ui/app/components/mfa/mfa-form.js, ui/app/templates/components/mfa/mfa-form.hbs, ui/tests/acceptance/oidc-auth-method-test.js, ui/tests/integration/components/auth-form-test.js, ui/tests/integration/components/auth-jwt-test.js, ui/tests/integration/components/control-group-success-test.js, ui/tests/integration/components/edit-form-kmip-role-test.js, ui/tests/integration/components/edit-form-test.js, ui/tests/integration/components/mfa-form-test.js, ui/tests/integration/components/mount-backend-form-test.js, ui/tests/unit/components/auth-jwt-test.js
This PR stabilizes several form-related tests that were failing, presumably due to `cancelTimers` or other async tasks not completing before assertions were made.
Enterprise tests pass locally ✅
files.
=> UI: fix flaky form-related integration tests

.github/workflows/ci.yml
Temporarily pin the version of Chrome that we install in UI tests while we work to resolve a failure with the latest version.
files.
=> ui: pin chrome in UI tests

vault/external_tests/consul_fencing_binary/consul_fencing_test.go
This PR increases the timeout used by the requests by writer goroutines in TestConsulFencing_PartitionedLeaderCantWrite to address the test's flakiness in our enterprise repo's CI.
This test used to very frequently fail (flake) in our CI (over 10% runs flaking on long-running branches) in the enterprise repo.  Upon investigation, we've found that the test used to get stuck in the forever loop around line 208, since all of the requests were timing out. We've run the test a few times in our enterprise CI and it passed every time. That does not mean that the flakiness is gone, but the plan going forward is to merge this fix in and monitor the test in CI.
the normal …
=> [VAULT-27978] Increase writer request timeout in TestConsulFencing_PartitionedLeaderCantWrite to fix flakiness in CI

command/server.go, vault/activity_log.go, vault/census.go, vault/census_stubs_oss.go, vault/core.go, vault/logical_system_activity.go
This PR adds the CE plumbing to prepare enterprise for the SetMetadata
API.
Enterprise PR: hashicorp/vault-enterprise#5955
Resolves: VAULT-27310
files.
=> Prepare CE changes for [census.Agent] SetMetadata

website/content/docs/configuration/listener/tcp/index.mdx
Update docs to mention version 1 and version 2 support which existed since Vault `v1.10.0`.
files.~
description. Also, make sure the changelog is in this PR, _not_ in your ENT PR.~
=> Docs: fix listener 'proxy_protocol_behavior' support version 1 and 2

changelog/26828.txt, plugins/database/mysql/connection_producer.go, sdk/database/helper/connutil/cloudsql.go, sdk/database/helper/connutil/sql.go, website/content/api-docs/secret/databases/postgresql.mdx, website/content/docs/secrets/databases/postgresql.mdx
🛠️ Description
add the ability to speificy if the cloudsql postgresql instance has private ip we should use 
right now we fail if the instance has only public ip 
Closes [#26827](https://github.com/hashicorp/vault/issues/26827)
=> Add usePrivateIP for cloudsql postgresql instances 

.github/actions/metadata/action.yml
We have seen instances where the `github.event.pull_request.labels.*.name` context in Github Actions doesn't actually include the labels. I suspect this is due to an incomplete webhook. Instead of relying on that context we'll query the API for labels ourselves. 
files. …
=> actions: use the Github API for pull request labels

.github/actions/metadata/action.yml
We have seen instances where the github.event.pull_request.labels.*.name context in Github Actions doesn't actually include the labels.
Instead, we now pull and parse them ourselves instead of relying on that context.
=> actions: use the Github API for pull request labels (#27603)

changelog/27574.txt, ui/app/components/mfa/mfa-form.js, ui/tests/integration/components/mfa-form-test.js
Fixes a bug where the MFA form wasn't displaying an error message nor countdown when a user tried to enter an incorrect one-time password too many times.
Fixes JIRA ticket # VAULT-28437
To replicate this you'll need to set up MFA and a userpass user. I recommend having two browser windows open: one for the `root` user and one for a userpass user. 
1. Create a policy `test` with all privileges (so the user can eventually enable MFA on their login):
```bash
path "*" {
capabilities = ["create", "read", "update", "delete", "list", "sudo"]
}
```
2. Enable the `userpass` auth method
3. Create a user with the `test` policy
4. In the left sidebar, click "Multi-factor authentication"
5. Select TOTP and 'next'
6. Fill out `Vault` as the **issuer** (though it doesn't really matter). Enter 2 as the …
=> UI: allow retries for MFA form errors

api/auth/approle/go.mod, api/auth/approle/go.sum, api/auth/aws/go.mod, api/auth/aws/go.sum, api/auth/azure/go.mod, api/auth/azure/go.sum, api/auth/gcp/go.mod, api/auth/gcp/go.sum, api/auth/kubernetes/go.mod, api/auth/kubernetes/go.sum, api/auth/ldap/go.mod, api/auth/ldap/go.sum, api/auth/userpass/go.mod, api/auth/userpass/go.sum, api/go.mod, api/go.sum, go.mod, go.sum
Upgrades go-retryablehttp to 0.7.7.
Needs to be backported to 1.15, 1.16, 1.17. I will probably have to do them manually but let's see.
files.
=> VAULT-28422 Upgrade go-retryablehttp for CE

sdk/go.mod, sdk/go.sum
I accidentally missed this one as part of https://github.com/hashicorp/vault/pull/27602
I'll have to backport this too. For 1.15 and 1.16 the assistant seems broken (and it'd probably fail anyway?) so I'll do a big bundle PR manually.
files.
=> VAULT-28422 SDK upversion for go-retryablehttp

website/content/api-docs/secret/aws.mdx
Clarifies the rotation of static role access keys using the IAM User example
files.
Closes #27477
=> Update docs wording with example for static role rotation of access keys for AWS IAM Users

website/content/docs/concepts/tokens.mdx
Briefly explain Vault token prefixes in the concepts page.
files.
Closes #27151
=> Document token format/prefix differences in the token concepts page

website/content/docs/agent-and-proxy/index.mdx
Clarifies that Agent and Proxy are available in both CE/ent binaries/images as this has been confusing in the field.
I also updated and re-ordered the table to make it a little nicer.
See and interact here: https://vault-git-violethynes-clarify-agent-proxy-cli-usage-hashicorp.vercel.app/vault/docs/agent-and-proxy
files. …
=> Add section clarifying Agent and Proxy availability

website/content/docs/secrets/databases/index.mdx
🎟️ [Jira tickert](https://hashicorp.atlassian.net/browse/SPE-837?atlOrigin=eyJpIjoiNDdlODc3YjRkYzQ0NGI4YWJiMmI0Y2UxZTNjNjJlZTUiLCJwIjoiaiJ9)
Remove link to deprecated tutorial (static roles)
files.
=> Remove link to static role tutorial

changelog/27605.txt, go.mod, go.sum
This upgrades raft to 1.7.0 which includes the pre-vote extensions.
Jira: https://hashicorp.atlassian.net/browse/VAULT-28426
files.
=> upgrade raft to v1.7.0

changelog/27631.txt, vault/logical_system_paths.go
Force the rotate root (/sys/rotate) api call to the active node. 
ENT portion which includes tests [PR](https://github.com/hashicorp/vault-enterprise/pull/6149)
[JIRA reporting bug](https://hashicorp.atlassian.net/browse/VAULT-20017)
files.
=> Force rotate root to the active node

.github/actions/changed-files/action.yml, .github/actions/checkout/action.yml, .github/workflows/actionlint.yml, .github/workflows/build-artifacts-ce.yml, .github/workflows/build.yml, .github/workflows/changelog-checker.yml, .github/workflows/ci.yml, .github/workflows/code-checker.yml, .github/workflows/copywrite.yml, .github/workflows/enos-lint.yml, .github/workflows/enos-release-testing-oss.yml, .github/workflows/enos-run-k8s.yml, .github/workflows/oss.yml, .github/workflows/plugin-update-check.yml, .github/workflows/plugin-update.yml, .github/workflows/security-scan.yml, .github/workflows/stable-website.yaml, .github/workflows/test-ci-bootstrap.yml, .github/workflows/test-ci-cleanup.yml, .github/workflows/test-enos-scenario-ui.yml, .github/workflows/test-go.yml, .github/workflows/test-run-acc-tests-for-path.yml, .github/workflows/test-run-enos-scenario-matrix.yml
A superset of https://github.com/hashicorp/vault/pull/27476 which upgrades older versions to 4.1.7 also.
I'm going to do the ent backports manually since the there's an issue with it right now, and also it'll likely have conflicts.
files.
=> VAULT-28522: Update actions/checkout to 4.1.7

helper/testhelpers/ldap/ldaphelper.go
This PR adds a for loop to try up to 3 times to call runner.StartService successfully in the helper/testhelpers/ldap package. This function is used by testing functions.
files.
=> add retry logic in ldap.PrepareTestContainer

builtin/logical/aws/backend_test.go, builtin/logical/aws/path_roles.go, builtin/logical/aws/path_roles_test.go, builtin/logical/aws/path_user.go, builtin/logical/aws/secret_access_keys.go, changelog/27620.txt, website/content/api-docs/secret/aws.mdx
Adds support for configuring session tags for assume role operations.
This PR takes over the work started in #18813
See https://github.com/hashicorp/vault/pull/18813#issue-1554095028 for details.
files.
=> AWS secrets: add support for STS session tags

changelog/27633.txt, vault/core.go, vault/core_test.go, vault/logical_system.go
This PR changes the mountsLock and authLock fields in the Core struct from `locking.DeadlockRWMutex` to `locking.RWMutex`. This change allows the fields to be set to either `locking.DeadlockRWMutex` or `locking.SyncRWMutex` (or any other type that fulfills the `locking.RWMutex` interface for that matter).
These fields are now set using the `locking.CreateConfigurableRWMutex` function which selects the `locking.DeadlockRWMutex` implementation if the provided lock type name is present in the provided **detectDeadlocks** slice.
The `detect_deadlocks` configuration parameter is used to specify which locks are configured to use the `locking.DeadlockRWMutex`. If a lock is not specified in that parameter, it is configured to use the `locking.SyncRWMutex` which is an alias for `sync.RWMutex`. …
=> Make mountsLock and authLock in Core configurable

changelog/27656.txt, helper/timeutil/timeutil.go, helper/timeutil/timeutil_test.go
Adding CE changes for ENT PR https://github.com/hashicorp/vault-enterprise/pull/5681/files that auto-rolls billing start date. 
JIRA: https://hashicorp.atlassian.net/browse/VAULT-24059
files.
=> Add auto-roll billing start date changes CE changes

changelog/27660.txt, http/handler.go, http/help.go, http/logical.go, http/sys_rekey.go
Fix redirects when a namespace is included in the namespace header, or for events when it's included in the path.
Fixes #27551. 
files.
=> VAULT-28255: Fix namespaced redirects

ui/package.json, ui/tests/integration/components/transit-key-actions-test.js, ui/yarn.lock
This PR makes a few dependency package updates to address the security vulnerability in `braces v3.0.3` and upgrades `ws` to `8.17.1`. I recommend reviewing by commit, general breakdown of each commit:
1. Deleted the yarn.lock file and re-ran yarn resolved some of the issues
2. Added braces to the resolution block resolved some more vulnerable versions
There was one test failure after upgrading, but the test ran the same before and after the package changes. Closing the modal in the test resolved the issue.
✅ enterprise tests
=> UI: resolves braces < 3.0.3 dep vulnerability and ws < 8.17.1

command/server.go, command/server_util.go, vault/census_stubs_oss.go
This PR adds the CE plumbing and stubs for forcing agent instantiation whenever the Vault license changes.
Resolves: VAULT-28583
Enterprise PR: hashicorp/vault-enterprise#6168
files.
=> Add CE plumbing for CensusManager reload

website/content/api-docs/secret/azure.mdx
Very small PR to update azure docs to include new param `explicit_max_ttl`. 
PR: https://github.com/hashicorp/vault-plugin-secrets-azure/pull/199
=> Update azure docs to include new param

builtin/logical/pki/path_fetch.go, changelog/27681.txt
Previously, in the default: case of pathFetchRead, not providing the serial
parameter results in a panic when casting the empty result.
=> Handle missing serial number more gracefully

ui/package.json, ui/tests/integration/components/transit-key-actions-test.js, ui/yarn.lock
"Backport" of: https://github.com/hashicorp/vault/pull/27657
This PR makes a few dependency package updates to address the security vulnerability in braces v3.0.3 and upgrades ws to 8.17.1. I recommend reviewing by commit, general breakdown of each commit:
1. Deleted the yarn.lock file and re-ran yarn resolved some of the issues
2. Added braces to the resolution block resolved some more vulnerable versions
3. There was one test failure after upgrading, but the test ran the same before and after the package changes. Closing the modal in the test resolved the issue.
of a public function, even if that change …
=> Backport 1.17.x: resolves braces < 3.0.3 dep vulnerability and ws < 8.17.1

changelog/27578.txt, command/command_stubs_oss.go, command/command_test.go, command/server.go, helper/testhelpers/corehelpers/corehelpers.go, helper/testhelpers/minimal/minimal.go, helper/testhelpers/pluginhelpers/pluginhelpers.go, helper/testhelpers/seal/sealhelper.go, helper/testhelpers/testhelpers.go, helper/testhelpers/testhelpers_oss.go, helper/testhelpers/teststorage/consul/consul.go, helper/testhelpers/teststorage/teststorage.go, helper/testhelpers/teststorage/teststorage_reusable.go, http/forwarding_bench_test.go, http/plugin_test.go, sdk/helper/testcluster/exec.go, sdk/helper/testhelpers/output.go, sdk/logical/testing.go, vault/expiration_test.go, vault/external_tests/api/api_integration_test.go, vault/external_tests/pprof/pprof.go, vault/external_tests/pprof/pprof_binary/pprof_test.go, vault/external_tests/pprof/pprof_test.go, vault/external_tests/raft/raft_test.go, vault/plugincatalog/testing.go, vault/seal_testing.go, vault/seal_testing_util.go, vault/testing.go, vault/testing_util.go, vault/token_store_test.go
This is the CE PR for https://github.com/hashicorp/vault-enterprise/pull/6101
files.
=> Removal of go-testing-interface (CE changes)

.github/workflows/test-go.yml
This PR enables the `--rerun-fails` option for all Go tests in our enterprise repo. This is to reduce the impact of individual flaky tests on the CI reliability.
files.
=> [VAULT-28664] Enable the --rerun-fails option in gotestsum for enterprise to reduce the impact of flaky tests on the CI

.github/workflows/enos-release-testing-oss.yml
Removes a deprecated `runs-on` label
files.
=> actions: don't use linux runs-on label

website/content/docs/upgrading/upgrade-to-1.17.x.mdx, website/content/partials/known-issues/transit-input-on-cmac-response.mdx
Add a section to the 1.17 upgrade guide documenting the known issue in Transit's Generate CMAC.
files.
=> Document the Transit AES CMAC known issue

vault/external_tests/plugin/external_plugin_test.go
This PR proposes some refactoring to the external plugin tests. We use goroutines instead of parallel tests to make the intent clearer; which is to simulate real-world traffic to the plugin.
There are a few other small improvements like making slower tests Parallel and removing unnecessary code.
=> refactor external plugin tests

website/content/docs/internals/telemetry/metrics/all.mdx, website/content/partials/telemetry-metrics/vault/audit/device/log_request_failure.mdx, website/content/partials/telemetry-metrics/vault/audit/device/log_response_failure.mdx
Manual backport of https://github.com/hashicorp/vault-enterprise/pull/6204 based on https://github.com/hashicorp/vault/pull/27698
=> Backport: Docs: fix telemetry docs for Audit into 1.15.x

website/content/docs/internals/telemetry/metrics/all.mdx, website/content/partials/telemetry-metrics/vault/audit/device/log_request_failure.mdx, website/content/partials/telemetry-metrics/vault/audit/device/log_response_failure.mdx
Manual backport of https://github.com/hashicorp/vault-enterprise/pull/6205 based on https://github.com/hashicorp/vault/pull/27698
=> Backport: Docs: fix telemetry docs for Audit into 1.16.x 

builtin/logical/pki/integration_test.go, changelog/27696.txt, sdk/helper/ocsp/client.go
- We returned the issuer's certificate number instead of the serial number of the actual certificate we validated from an OCSP request that confirmed the certificate was revoked
Fixes #27126
VAULT-28667
files.
=> Return the proper serial number in OCSP verification errors

changelog/27726.txt, physical/raft/raft_autopilot.go
Sometimes autopilot can cause a panic when shutdown logic is triggered (stepping down from active duty) because we aren't waiting for autopilot to shutdown gracefully.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0x1c66537]
goroutine 907 [running]:
github.com/hashicorp/raft-autopilot.(*Autopilot).GetState(0xc0005ec850?)
/home/runner/go/pkg/mod/github.com/hashicorp/raft-autopilot@v0.2.0/autopilot.go:222 +0x37
github.com/hashicorp/vault/physical/raft.(*Delegate).KnownServers(0xc006eca120)
/home/runner/actions-runner/_work/vault-enterprise/vault-enterprise/physical/raft/raft_autopilot.go:389 +0xfc
github.com/hashicorp/raft-autopilot.(*Autopilot).gatherNextStateInputs(0xc006ecc000, {0x89cd4b8, …
```
=> raft/autopilot: fix panic during autopilot shutdown

changelog/27728.txt, ui/app/styles/components/namespace-picker.scss, ui/app/templates/components/namespace-picker.hbs
In small screens where the navbar gets collapsed by default, the namespace picker was broken in that nothing would happen when you open the sidebar, click the dropdown, and try to navigate to one of the namespace options. With this PR, the namespace picker dropdown is fully functional even in screens where the side nav is collapsed by default. 
`renderInPlace` is what fixed the behavior, but some CSS changes were necessary to make sure visually it looks the same as before:
=> UI: Fix namespace picker in small screens

website/content/docs/enterprise/license/utilization-reporting.mdx
I noticed in our meeting earlier that the steps were weirdly lowercased, not fitting with our title format.
files.
=> Fix lowercase steps in utilization docs

website/content/docs/configuration/index.mdx
This PR adds a mention to the `administrative_namespace_path` in the Configuration section as this is the go-to document when a user wants to modify the `config.hcl` file.
Details about the parameter is available here https://developer.hashicorp.com/vault/docs/enterprise/namespaces/create-admin-namespace but it needs to be available under the Configuration section as well.
files.~~
in …
=> Docs: Add "administrative_namespace_path" as an available parameter in Vault config

changelog/27742.txt, ui/app/models/pki/tidy.js, ui/tests/acceptance/pki/pki-tidy-test.js, ui/tests/integration/components/pki/pki-tidy-form-test.js
This PR fixes a bug where turning on "ACME Account Safety Buffer" in PKI Tidy and then turning it off would not allow to save due to sending the value for `acme_account_safety_buffer` as `0s`. To resolve, I set the default value for this setting to `720h` which is the equivalent of 30 days -- the [default according to the docs](https://developer.hashicorp.com/vault/api-docs/secret/pki#acme_account_safety_buffer). 
**Error on save**
**Success with changes**
=> UI: Fix ACME Account Safety Buffer not able to be turned off

website/content/docs/sync/index.mdx
Add a section about custom tags to the secrets sync overview. Also specifically calls out text that is normalized for syncing (secret names, tag keys and values).
files.
=> Add custom tags section to sync overview, denote normalized values

website/content/docs/sync/index.mdx
Backport of docs update in https://github.com/hashicorp/vault/pull/27757
=> Backport of Add custom tags section to sync overview, denote normalized values into release/1.16.x

.github/actions/install-external-tools/action.yml, .github/scripts/retry-command.sh
This PR adds a shell script called `retry-command.sh` to allow retrying things up to 5 times. I'm not a GHA wizard, so maybe there's a better way to do this. @kubawi kindly pointed out https://github.com/nick-fields/retry which serves this purpose and is already vetted apparently, but has the downside of being another external dependency to deal with. But, if people think using that is better, I'm happy to make the switch. I'm not married to this particular approach by any means.
applying the patch for this PR to the ENT repo …
=> add a retry-command script

go.mod, sdk/go.mod
This PR updates the version of Go referenced in our `go.mod` (and SDK `go.mod`) to use version `1.22`.
`go mod tidy` ran on the base `go.mod` and `sdk/go.mod`.
files.
=> Update go.mod and sdk/go.mod to Go 1.22

website/content/docs/concepts/pgp-gpg-keybase.mdx
Added notes in [Developer / Vault / Documentation / Concepts / **PGP, GnuPG, and Keybase**](https://developer.hashicorp.com/vault/docs/concepts/pgp-gpg-keybase) regarding GnuGPG versions 2.2.21 or higher being required where padding differences with ECDH keys used in Vault versions 1.12.x or earlier work with older GPG versions but newer Vault versions encounter the generic error: `gpg: decryption failed: No secret key`
Fixes #25965
=> Docs: PGP & gpg version requirements with ECDH & Vault 1.13.x or higher

.github/actions/set-up-staticcheck/action.yml
The `staticcheck` download intermittently fails with network issues. Let's automatically retry it when things go wrong.
files.
=> [VAULT-28666] Retry staticcheck download on failure in GitHub Actions (GHA)

.github/actions/set-up-buf/action.yml, .github/actions/set-up-gofumpt/action.yml, .github/actions/set-up-gosimports/action.yml, .github/actions/set-up-gotestsum/action.yml, .github/actions/set-up-misspell/action.yml, .github/workflows/security-scan.yml
This PR uses the new retry script to deal with intermittent network issues we've experienced while downloading CI tools from GitHub releases.
- [] **Labels:** If this PR is a CE only change, it can only be backported to N, so use
files.
=> [VAULT-28666] Retry tool download from GitHub releases on failure in GitHub Actions (GHA)

ui/app/components/mount-backend-form.hbs, ui/app/components/mount-backend-form.ts, ui/app/models/mount-config.js, ui/app/models/secret-engine.js, ui/lib/core/addon/components/form-field-groups.hbs, ui/lib/core/addon/components/form-field-groups.ts, ui/lib/core/addon/components/search-select-with-modal.hbs, ui/lib/core/addon/components/search-select-with-modal.js, ui/tests/acceptance/settings/mount-secret-backend-test.js, ui/tests/integration/components/mount-backend-form-test.js, ui/tests/unit/adapters/secret-engine-test.js, ui/tests/unit/models/secret-engine-test.js
- adds the `identity_token_key` to the mount-config model. API [here](https://developer.hashicorp.com/vault/api-docs/system/mounts#identity_token_key)
- adds the `config.identityTokenKey` param to the secret-engine model to render under optional form fields. 
- renders the field in a named-block. UPDATE: will show if community and or enterprise. Following convention of other enterprise only fields.
- adds test coverage: field renders only for aws and payload is correct for when identity_token_key is set.
This PR does not add the modal functionality (e.g. creating an oidc/key). That will come in the next PR.
=> WIF AWS: Add identity_token_key to model and render

website/content/api-docs/system/storage/raftautopilot.mdx, website/content/docs/concepts/integrated-storage/autopilot.mdx
@mpalmi and I responded to a sev0 over the weekend that was caused by Dead Server Last Contact Threshold being set to 1m. The customer wasn't sure why, but I figured bolstering our docs to make it clear that this is a bad idea would be good.
See also: https://github.com/hashicorp/tutorials/pull/2174
files.
description. Also, make …
=> Update docs around dead_server_last_contact_threshold

ui/app/templates/vault/cluster/secrets/backend/overview.hbs, ui/lib/core/addon/components/overview-card.hbs, ui/lib/kubernetes/addon/components/page/overview.hbs, ui/lib/kv/addon/components/page/list.hbs, ui/lib/ldap/addon/components/accounts-checked-out.hbs, ui/lib/ldap/addon/components/page/library/details/accounts.hbs, ui/lib/ldap/addon/components/page/overview.hbs, ui/lib/pki/addon/components/page/pki-overview.hbs, ui/lib/sync/addon/components/secrets/page/overview.hbs, ui/tests/integration/components/overview-card-test.js, ui/tests/integration/components/sync/secrets/page/overview-test.js
Yields actions to the `OverviewCard` template so multiple can be passed. There are no user facing changes
files.
=> UI: update overview card action handling

website/content/api-docs/secret/databases/mssql.mdx
We can see it is supported here: https://github.com/hashicorp/vault/blob/b9c892f8aa37c130dbb46c39972dccbaed42ba1b/plugins/database/mssql/mssql.go#L347 
and we have test coverage for the field in https://github.com/hashicorp/vault/blob/e88b6b117e3e9288352518f37a716013991afcc3/plugins/database/mssql/mssql_test.go#L188
=> docs: add missing rotation_statements to mssql api docs

vault/core.go
Sets the name of the logger used by the audit broker to be `audit` in the same we do for `vault/audit.go => setupAudits`.
https://github.com/hashicorp/vault/blob/main/vault/audit.go#L420-L422
files.
=> audit: name `audit` logger used by audit broker for `standardUnsealStrategy`'s `unseal` method

audit/broker.go, changelog/27809.txt
Within `audit` there exists an scenario where the `eventlogger` broker reports that audit was deemed a success (because it managed to successfully log to at least 1 sink node), but there were warnings (errors) that came back from other audit devices where audit failed. 
We want to ensure that we capture these warnings in the server log so that they don't go missing because we managed to log to a single device.
This PR has ENT and CE components.
break any …
=> Audit: log 'warnings' from eventlogger even if audit is deemed a success

website/content/docs/concepts/policies.mdx
🔍 [Deploy preview](https://vault-git-docs-priority-matching-example-hashicorp.vercel.app/vault/docs/concepts/policies#priority-matching)
This PR adds an additional example to the Priority matching [section](https://developer.hashicorp.com/vault/docs/concepts/policies#priority-matching) showing the Priority matching rules when using a fully-qualified path in a policy defined in the `root` namespace vs a relative path defined in a policy in the nested namespace itself.
applying the patch for this PR to the ENT repo and running …
=> Docs: Add a Priority matching policy example using Namespaces

website/content/api-docs/index.mdx
🧵 [Slack thread](https://hashicorp.slack.com/archives/C8DK5PR0B/p1721200987445919)
It was reported that the given example API call does not work due to missing `X-Vault-Namespace` header when you're working with HCP Vault Dedicated. 
Although it was reported specifically with AppRole auth API doc, it is relevant to all API calls --> I cannot just update the AppRole API doc. 
So, this PR adds a callout note to the API doc landing page.
break any tests. …
=> [Docs] Add a warning about namespace info for HVD

changelog/27790.txt, vault/activity_log.go
Previously, when you queried the activity log from a namespace you would get the following responses:
```
{
"by_namespace": [{...}], // filtered by the request namespace
"months": [{
"counts": {...}, // NOT filtered
"namespaces": [{...}], // filtered by the request namespace
"new_clients": {
"counts: {...}, // NOT filtered
"namespaces": [{...}], // filtered by the request namespace
}
}],
"total": {...} // filtered by the request namespace
}
```
This was very confusing, and also makes the UI a bad experience if you try to look at only one namespace.
This PR fixes this for the /activity and /activity/monthly endpoints.
Ent PR: https://github.com/hashicorp/vault-enterprise/pull/6260
instead of the old style …
=> VAULT-28329: Fix `months` activity log counts when querying for a namespace

website/content/docs/platform/k8s/vso/installation.mdx
Update the VSO docs for the new auto CRD upgrade behaviour being introduced in 0.8.0.
files.
=> Update VSO docs for auto CRD upgrade behaviour

website/content/docs/platform/k8s/vso/api-reference.mdx, website/content/docs/platform/k8s/vso/helm.mdx, website/content/docs/platform/k8s/vso/installation.mdx, website/content/docs/platform/k8s/vso/openshift.mdx, website/content/docs/platform/k8s/vso/sources/vault/auth/index.mdx, website/content/docs/platform/k8s/vso/sources/vault/index.mdx, website/content/partials/vso/common-links.mdx, website/data/docs-nav-data.json
Documents the newly added VaultAuthGlobals feature for VSO.
- [] **Labels:** If this PR is a CE only change, it can only be backported to N, so use
files.
=> VSO: update docs for VaultAuthGlobals

builtin/logical/database/secret_creds.go, command/agentproxyshared/auth/auth.go, command/pki_reissue_intermediate.go, helper/testhelpers/pluginhelpers/pluginhelpers.go, vault/eventbus/bus.go
This fixes a few issues raised by a static analysis tool indicating incorrect assignments, and unchecked errors via shadowing or simply missed checking. 
None of these are security issues or anything like that, but we should definitely clean them up.
I don't think this is worth a changelog, as nothing should really change, this is mostly housekeeping, but if folks feel otherwise I'm all ears. …
=> VAULT-27384 Fix faulty assignments and unchecked errors

website/content/docs/platform/k8s/vso/helm.mdx, website/content/docs/platform/k8s/vso/installation.mdx, website/content/docs/platform/k8s/vso/openshift.mdx
=> Bump VSO versions to 0.8.0

ui/package.json, ui/yarn.lock
Upgrades @hashicorp/design-systems to the latest version `4.6.0`, additionally this resolves `ember-a11y-refocus` to `4.1.1` which fixes https://github.com/hashicorp/vault/issues/27768
Only backporting to 1.17 because that's the only version of Vault running HDS `v4.x`.
In addition, I ran a fresh install of the yarn.lock to get any additional patch updates. I will _not_ do this for the 1.17.x branch …
=> UI: upgrade HDS to 4.6.0

ui/package.json, ui/yarn.lock
Manual "backport" of https://github.com/hashicorp/vault/pull/27843
✅ enterprise tests
files.
=> UI Backport 1.17.x: Upgrade HDS to 4.6.0

.github/scripts/retry-command.sh
What it says on the tin. We've added this script recently, but missed that the `errexit` option was enabled. 
This meant that the whole script failed when the command to be retried failed. Now it should work fine.
files.
=> [VAULT-28666] Remove the errexit option from the retry script and add increasing wait on failure (up to 5 seconds and 5 retries)

ui/app/templates/components/oidc/key-form.hbs, ui/app/templates/vault/cluster/access/oidc/keys/create.hbs, ui/app/templates/vault/cluster/access/oidc/keys/key/edit.hbs, ui/tests/integration/components/oidc/key-form-test.js
Moves the form page header to the route component, this supports the WIF work so that the form can be rendered in a search select modal. There are no user facing changes
files.
=> UI: Move OIDC key header out of form component

.github/actions/set-up-buf/action.yml, .github/actions/set-up-gofumpt/action.yml, .github/actions/set-up-gosimports/action.yml, .github/actions/set-up-gotestsum/action.yml, .github/actions/set-up-misspell/action.yml, .github/actions/set-up-staticcheck/action.yml
=> [VAULT-28666] Enable the --clobber flag on GitHub CLI release downloads in CI to avoid errors when retrying

vault/activity_log.go, vault/census_manager.go, vault/core.go
CE Changes for https://github.com/hashicorp/vault-enterprise/pull/6240
files.
=> VAULT-27563 CE changes

vault/logical_system.go
Small change to use the same logger that most things use here, this prevents the output in the logs being from something with sys/secret'y and instead says core.
files.
=> Audit: Use the `core` logger for audit enable errors (not the system backend)

audit/backend_file.go, audit/backend_socket.go, audit/backend_syslog.go, changelog/27859.txt, internal/observability/event/options.go, internal/observability/event/options_test.go, internal/observability/event/sink_file.go, internal/observability/event/sink_socket.go, internal/observability/event/sink_syslog.go, vault/audit.go
Allows audit sink nodes to receive an optional `logger` which is then used if an error is intended to be returned, but the context is already done. In this case it will log the error before returning.
files.
=> Audit: optional logger for sinks will log on errors when context is done

audit/broker.go, vault/audit_test.go
Removes the use of multierror and instead uses the Go stdlib errors join.
ENT PR: https://github.com/hashicorp/vault-enterprise/pull/6285
files.
=> Audit: Remove multi-errors and update expected error msg in tests

vault/identity_store_util.go, vault/testing.go
If a DR secondary is promoted to become a DR Primary as well as a PR secondary, the promotion will fail and the cluster will never become available. This is because of an ongoing issue with duplicate aliases. If vault detects duplicate aliases, it will merge them, causing vault to update it's groups with the new entity members. However, the newly promoted DR primary/PR secondary fails to persist the group change to storage because it's rpc client has not been initialized yet.
To avoid this failure, we check if `UpsertGroupInTxn` returns an ErrReadOnly error, and instead log a warning message.
[Jira](https://hashicorp.atlassian.net/browse/VAULT-28191)
the normal …
=> Send warning and do not return error on group update if cluster is a PR secondary and RPC client is nil

vault/activity_log.go
Now that the correct current month values are present in the handleQuery response, we can do some cleanup.
This will need to be backported, but that will be in a separate manual backport.
files.
=> VAULT-28029: Cleanup for activity log

ui/app/components/modal-form/oidc-key-template.hbs, ui/app/components/modal-form/oidc-key-template.js, ui/app/components/mount-backend-form.hbs, ui/app/components/mount-backend-form.ts, ui/app/components/oidc/key-form.js, ui/app/helpers/mountable-secret-engines.js, ui/app/serializers/secret-engine.js, ui/app/templates/components/oidc/key-form.hbs, ui/lib/core/addon/components/input-search.hbs, ui/lib/core/addon/components/search-select-with-modal.hbs, ui/lib/core/addon/components/search-select-with-modal.js, ui/tests/acceptance/settings/mount-secret-backend-test.js, ui/tests/helpers/general-selectors.ts, ui/tests/helpers/secrets/policy-generator.ts, ui/tests/integration/components/mount-backend-form-test.js, ui/tests/integration/components/search-select-with-modal-test.js, ui/tests/unit/adapters/secret-engine-test.js
This PR adds the modal/create part to the aws secret engine mount. 
* if a user has read access it `identity/oidc/key` they can either search existing oidc/keys or they can create one. 
* if a user does _not_ have read access they can type a key into an input box. If the key does not exist then the API will surface an error.
* **FYI**: We are surfacing about half the fields used to create an `identity/oidc/key` (at the very bottom I'll provide a screenshot of that full form). Design would like to only include a limited / required set of form fields to create an identity_token_key here. This has been cleared with the backend as well. 
* It's important that a user is given the ability to add a key at the mounting stage of an engine because they cannot add this later via the UI. 
**If they …
=> WIF AWS: add create functionality to SearchSelectWithModal for identity_token_key (take 2)

vault/activity_log.go, website/content/api-docs/system/internal-counters.mdx
Remove fields `distinct_entities` and `non_entity_tokens` from RespounseCounts structure, so that this is completely removed from the response. This change is NOT backwards compatible. This change follows the major change (https://github.com/hashicorp/vault/commit/b32231a9eb14e19b81e9a04f017d0ea783ddbcda) which contains the changelog. 
ENT PR: https://github.com/hashicorp/vault-enterprise/pull/6280 …
=> Remove distinct_entities and non_entity_tokens from ResponseCounts and update docs

changelog/27750.txt, vault/identity_store.go, vault/identity_store_test.go, website/content/docs/release-notes/1.16.1.mdx, website/content/docs/release-notes/1.17.0.mdx, website/content/docs/upgrading/upgrade-to-1.16.x.mdx, website/content/docs/upgrading/upgrade-to-1.17.x.mdx, website/content/partials/known-issues/dangling-entity-aliases-in-memory.mdx
This change corrects a regression that was introduced by #27184.
When an entity has been modified in a storage bucket such that one or more aliases has been removed, those removed aliases were not being deleted from the MemDB table containing them. This change corrects this by scanning all associated aliases with entities that have been determined to be modified in the storage bucket, and deleting any associated aliases from MemDB that are no longer associated with the entity in the storage bucket.
applying the patch for this …
=> VAULT-28677: Fix dangling entity-aliases in MemDB after invalidation

vault/identity_store_aliases.go
Instead of passing a pointer to the alias, we should pass a clone to `handleAliasUpdate`.  Otherwise, it is possible to alter the alias outside of a transaction. One example is if a performance standby fails to write to storage and attempts to rollback changes made during `upsertEntity`, vault won't rollback the changes that were made directly to the alias pointer. 
ENT PR with tests [here](https://github.com/hashicorp/vault-enterprise/pull/6271)
break any …
=> Prevent vault from directly altering a canonical ID belonging to an alias, not a clone

.github/actions/set-up-buf/action.yml, .github/actions/set-up-gofumpt/action.yml, .github/actions/set-up-gosimports/action.yml, .github/actions/set-up-misspell/action.yml, .github/actions/set-up-staticcheck/action.yml
We've seen the release version lookup fail with connection issues recently, so we're adding retries to it too.
files.
=> [VAULT-28666] Use the retry script to check release versions for external tools installed in CI

.github/actions/set-up-gotestsum/action.yml
I've missed this one in the last PR.
files.
=> [VAULT-28666] Use the retry script to check release version for gotestsum in CI

changelog/27656.txt, command/server.go, command/server_util.go, helper/timeutil/timeutil.go, helper/timeutil/timeutil_test.go, vault/activity_log.go, vault/census.go, vault/census_stubs_oss.go, vault/core.go, vault/logical_system_activity.go
This PR contains all of the CE backports for the auto-rolling billing start date.
Enterprise PR: https://github.com/hashicorp/vault-enterprise/pull/6279
Addresses: VAULT-28005
files.
=> Backport 1.17.x auto rolling

changelog/27883.txt, website/content/api-docs/secret/azure.mdx
Adds API documentation for 'delete role' on the Azure Secrets Engine
Issue #27882
=> added delete role to website documentation

.github/actions/install-external-tools/action.yml, tools/tools.sh
They introduced a replace statement within the go.mod file which causes failures running `go install protoc-gen-go-grpc@latest`
```
Run ./.github/scripts/retry-command.sh go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
go: downloading google.golang.org/grpc/cmd/protoc-gen-go-grpc v1.5.0
go: downloading google.golang.org/grpc v1.65.0
go: google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest (in google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.5.0):
The go.mod file for the module providing named packages contains one or
more replace directives. It must not contain directives that would cause
it to be interpreted differently than if it were the main module.
```
Workaround for now is to pin to the previous version
See https://github.com/grpc/grpc-go/issues/7448
getting …
=> Pin protoc-gen-go-grpc to 1.4.0

README.md
I am on a fresh new laptop, getting the vault repo set up again. When I run `make bootstrap`, it no longer seems to work just with `$GOPATH` set and `$GOPATH/bin` added to the path like in the original instructions. Now, the external tools installation step will fail with the following message:
```
==> Running go generate...
builtin/logical/pki/path_config_acme.go:420: running "enumer": exec: "enumer": executable file not found in $PATH
command/operator_generate_root.go:26: running "enumer": exec: "enumer": executable file not found in $PATH
...
```
Explicitly setting the GOBIN variable in my `~/.zshrc` fixes the problem.
The difference between whether it works or not is literally in whether I comment out the below GOBIN line:
```
export PATH="$PATH:$GOPATH/bin"
GOPATH="$HOME/go" …
```
=> Add note requiring GOBIN to readme

website/content/docs/platform/k8s/vso/api-reference.mdx, website/content/docs/platform/k8s/vso/helm.mdx, website/content/docs/platform/k8s/vso/installation.mdx, website/content/docs/platform/k8s/vso/openshift.mdx, website/content/docs/platform/k8s/vso/sources/vault/index.mdx
Other fixes:
- Including missing Helm documentation.
- Add feature availability tip for `Instant updates` feature.
files.
=> Update VSO docs for v0.8.1

website/content/docs/platform/k8s/injector/annotations.mdx
Update the documentation of the `vault.hashicorp.com/agent-pre-populate` to describe:
1. The accepted values.
2. What the default value is.
I sourced this info from https://github.com/hashicorp/vault-k8s/blob/6b9d13434ddac091684c61946d978767b9abbb77/agent-inject/agent/annotations.go#L703-L710.
=> Add expected and default values for the `vault.hashicorp.com/agent-pre-populate` annotation

audit/broker.go, audit/entry_formatter.go, audit/hashstructure.go, audit/hashstructure_test.go, audit/headers.go, audit/headers_test.go
un-exports functions used for hashing e.g. hash: auth, request, response and string from the audit package, so they cannot be used elsewhere.
files.
=> Audit: un-export `hashstructure.go` funcs

builtin/logical/pki/cert_util.go, builtin/logical/pki/issuing/issue_common.go, builtin/logical/pki/issuing/sign_cert.go, sdk/helper/certutil/certutil_test.go, sdk/helper/certutil/helpers.go, sdk/helper/certutil/types.go
Allow callers of the SignCertificate method to disable the signature verification within the passed in CSR. We are leveraging this new feature flag as we are constructing a CSR based on the information from a CMPv2 message where we have access to the public key but not the private key, but have validated proof of possession through the CMPv2 popo signatures.
This was easily then adapting the flows for creating certificates as that flow assumes a private key is present during construction. 
- [] **Labels:** If this PR is the CE portion of an ENT change, and that ENT change is
of a public function, even if …
=> Allow SignCert callers to override CSR signature checks

ui/app/serializers/clients/activity.js, ui/lib/core/addon/utils/client-count-utils.ts, ui/mirage/handlers/clients.js, ui/mirage/handlers/sync.js, ui/tests/helpers/clients/client-count-helpers.js, ui/tests/integration/utils/client-count-utils-test.js
This PR removes references and expectations around deprecated keys in the client count activity response, namely `distinct_entities` and `non_entity_tokens`. This PR has no user-facing changes, as we were already filtering out the deprecated values from the API response.
=> UI: Remove deprecated Client Count keys

vault/identity_store_util.go
When debugging duplicate groups, it would be really helpful to check the unseal debug logs to check which groups are duplicates. Right now, this is difficult because we don't know which namespace each group lives in. 
[Jira](https://hashicorp.atlassian.net/browse/VAULT-29193)
Based on these previous logs its hard to tell if these are duplicate groups. They have the same name `group1`, but they have different IDs. 
Previous Logs: 
```
2024-07-31T15:25:09.909Z [DEBUG] identity: loading group: name=group1 id=aa8bff0b-5978-c1a9-f45b-f7e0ec655408
2024-07-31T15:25:09.909Z [DEBUG] identity: loading group: name=group1 id=e68144b7-8c19-add8-2f8a-a51e08a1732c
```
In the new logs, it is easy to discern that the group names are the same, but that it is not a problem because they are in different …
=> add namespace ID to loading groups debug message on unseal

builtin/credential/cert/backend.go
To 100k.  Note that it is very unusual to need many cert auth roles, and may
be indicative of an inoptimal PKI architecture.
=> Increase cert auth role cache max size

ui/tests/integration/components/clients/export-button-test.js, ui/tests/unit/adapters/clients-activity-test.js
After merging some updates to client count exporting, the export-button test started to fail in enterprise CI only. This is an attempt to resolve those failures, or at least make them easier to parse instead of the non-helpful: 
```
[vault]         actual: >
[vault]             [object Object]
[vault]         expected: >
[vault]             [object Object]
```
=> UI: fix export button tests

changelog/27939.txt, vault/logical_system.go
CE component of https://github.com/hashicorp/vault-enterprise/pull/6343
files.
=> VAULT-25883: Fix namespace errors with path filters on sys/internal/ui/mounts

website/content/docs/agent-and-proxy/agent/winsvc.mdx
This has been causing some confusion in the field, and seemed to be an easy fix.
https://vault-rih9vxiie-hashicorp.vercel.app/vault/docs/agent-and-proxy/agent/winsvc
files.
=> Add docs note about Windows paths

ui/app/components/console/ui-panel.js, ui/app/components/generated-item-list.js, ui/app/components/raft-storage-overview.js, ui/app/components/raft-storage-restore.js, ui/app/services/auth.js, ui/app/services/console.js, ui/lib/kmip/addon/controllers/credentials/index.js, ui/lib/kmip/addon/controllers/scope/roles.js, ui/lib/kmip/addon/controllers/scopes/index.js, ui/lib/kubernetes/addon/components/page/roles.js, ui/lib/kv/addon/components/page/list.js, ui/lib/ldap/addon/components/page/libraries.ts, ui/lib/ldap/addon/components/page/roles.ts, ui/lib/pki/addon/controllers/certificates/index.js, ui/lib/pki/addon/controllers/issuers/index.js, ui/lib/pki/addon/controllers/keys/index.js, ui/lib/pki/addon/controllers/roles/index.js, ui/lib/sync/addon/components/secrets/page/destinations.ts, ui/lib/sync/addon/components/secrets/page/destinations/destination/secrets.ts
Updates the import of getOwner from `@ember/application`, where it is deprecated, to `@ember/owner`. This should have no user-facing changes
=> UI: update getOwner import

audit/backend_noop.go, audit/entry_formatter.go, audit/entry_formatter_test.go, audit/event.go, audit/hashstructure.go, audit/hashstructure_test.go, audit/types.go, changelog/27952.txt
This PR is a bit of a re-write/refactor of the existing audit code, intended to improve performance. Various binaries/builds have been tested internally in collaboration with our Customer Engineering team to confirm the improvement on CPU, memory usage, barrier gets etc.
The 'guts' of the PR are in `audit/entry_formatter.go`.
**Summary of larger changes**:
`audit/types.go`
* combine `RequestEntry` and `ResponseEntry` into a single type `Entry` (as `omitempty` is set on fields it won't make a difference to the output).
`audit/hashtructure.go`: 
* change hash funcs to accept the `audit` types vs. the `logical` ones.
`audit/entry_formatter.go`:
* introduce new funcs `newAuth`, `newRequest` and `newResponse` that can be used early to translate the incoming `LogInput` components into domain …
=> Audit: rewrite audit entry formatting to improve performance

website/content/partials/telemetry-metrics/vault/audit/log_request_failure.mdx, website/content/partials/telemetry-metrics/vault/audit/log_response_failure.mdx
There has been confusion around the `vault.audit.log_request_failure` and `vault.audit.log_response_failure` metrics, which are documented as counters.
The metrics emit a number of values that can be checked e.g. `count`, `mean`, `min`... the `count` for this metric just indicates how many times it was called, however Vault will increment the metric on every success or failure (supplying either the value `0` or `1` respectively). This is done so that systems like Prometheus don't 'forget' the metric if they don't see it fail for a while. 
of a public function, even if that change is in a CE file, _double …
=> Audit: explain 'failure' metrics better

enos/enos-descriptions.hcl, enos/enos-qualities.hcl, enos/enos-scenario-agent.hcl, enos/enos-scenario-autopilot.hcl, enos/enos-scenario-proxy.hcl, enos/enos-scenario-replication.hcl, enos/enos-scenario-seal-ha.hcl, enos/enos-scenario-smoke.hcl, enos/enos-scenario-upgrade.hcl, enos/modules/vault_upgrade/main.tf, enos/modules/vault_upgrade/scripts/maybe-remove-old-unit-file.sh, enos/modules/vault_upgrade/scripts/restart-vault.sh, enos/modules/vault_verify_version/main.tf, enos/modules/vault_verify_version/scripts/verify-cli-version.sh, enos/modules/vault_verify_version/scripts/verify-cluster-version.sh
When verifying the Vault version, in addition to verifying the CLI version we also check that the `/sys/version-history` contains the expected version.
As part of this we also fix a bug where when doing an in-place upgrade with a Debian or Redhat package we also remove the self-managed `vault.service` systemd unit to ensure that correctly start up using the new version of Vault. …
=> [VAULT-2937] Verify the `/sys/version-history` in enos scenarios

enos/modules/vault_upgrade/scripts/maybe-remove-old-unit-file.sh
Amazon Linux 2 uses an ancient version of Systemd/systemctl so instead of using -P when determining the unit file we use the less convenient -p.
files.
=> enos: support ancient systemd in `vault_upgrade`

audit/entry_formatter.go
* updates comments to inform callers about the `nil, nil` potential return value.
* merges two consecutive `if` conditions in `clientCertSerialNumber` func 
files.
=> Audit: comment updates and conditional merge

website/content/docs/auth/userpass.mdx
It's not clear from the get go how to use the userpass auth method with a custom path. Hence why this change brings clarity recycling the wording from the API page. An example could be added, but that would mean change the whole page not to use the default path, which would be inconsistent with the rest of the docs.
=> Update userpass CLI doc for custom path flag

Dockerfile
Rather than pin to specific minor versions of Alpine 3 and UBI 8, we instead roll on the latest version. This should resolve issues with outdated software versions in our container. 
files.
=> docker: use alpine 3 and UBI 8 tags instead of minor version pins

website/content/partials/telemetry-metrics/vault/audit/log_request_failure.mdx, website/content/partials/telemetry-metrics/vault/audit/log_response_failure.mdx
We recently changed the docs for these metrics to try to clarify how to actually monitor them usefully. Unfortunately the clarification only makes sense for the in-memory sink which could further confuse Prometheus or other metrics Sink users.
This attempts to clarify how to correctly monitor this metric.
files.
description. Also, …
=> Clarify audit log failure telemetry docs.

website/content/docs/upgrading/upgrade-to-1.15.x.mdx, website/content/docs/upgrading/upgrade-to-1.16.x.mdx, website/content/docs/upgrading/upgrade-to-1.17.x.mdx, website/content/docs/upgrading/upgrade-to-1.18.x.mdx
Adds upgrade notes for the removal of `curl` in the Docker container images.
files.
=> docker: add upgrade notes for curl removal

website/content/api-docs/system/internal-counters.mdx
Client count documentation updates. 
The main objectives:
- Remove any version related descriptions; the docs team wants to train customers to use the versioned docs for this information.
- Try to condense multiple bullets into as few as possible.
- Remove repetitive information, and remedy any incorrect information.
files. …
=> Client Count Docs Updates/Cleanup

website/content/docs/configuration/programmatic-management.mdx
Clarifies wording on Terraform prereqs to manage Vault (you don't need to be admin, just have sufficient access (write in TFE/TFC, or just have the Terraform CE binary).
=> Update programmatic-management.mdx to clarify Terraform prereqs

website/content/api-docs/system/internal-counters.mdx, website/content/docs/concepts/billing-start-date.mdx, website/content/docs/enterprise/license/utilization-reporting.mdx, website/content/docs/upgrading/upgrade-to-1.16.x.mdx, website/content/partials/auto-roll-billing-start-example.mdx, website/content/partials/auto-roll-billing-start.mdx, website/data/docs-nav-data.json
* auto-roll docs changes
* addressing comments
* address comments
* Update website/content/api-docs/system/internal-counters.mdx
* addressing some changes
* update docs
* update docs with common explanation file
* updated note info
* fix 1.18 upgrade doc
* fix content-check error
* Update website/content/partials/auto-roll-billing-start-example.mdx
--------- …
=> Backport of Auto-rolling billing start docs PR into release/1.16.x

.github/actions/set-up-misspell/action.yml
It appears that starting with v0.5.2 the misspell linter embeds the version directory into the release archive.
=> lint: fix misspel linter install

CHANGELOG.md
Adds the changelog entries for the new minor release.
- [N/A] **Labels:** If this PR is the CE portion of an ENT change, and that ENT change is
- [N/A] **Labels:** If this PR is a CE only change, it can only be backported to N, so use
- [N/A] **ENT Breakage:** If this PR either 1) removes a public function OR 2) changes the signature
files.
- [N/A] **Jira:** If this change has an …
=> Changelog for 1.17.3, 1.16.7 enterprise, 1.15.13 enterprise

website/content/api-docs/auth/kubernetes.mdx
We wanted to clarify the difference between the two options and the implications.
I've attached a screenshot because Vercel failed. It seems to look ok. The preview is missing one set of backticks which I've added in a new commit.
=> Edit alias_name_source explanation

website/content/docs/internals/telemetry/index.mdx
Update telemetry metric name from `vault.kv.secret.count` to `vault.secret.kv.count`
=> [DOCS] Correct telemetry metric name

sdk/helper/testcluster/docker/environment.go
The most recent version of `Alpine` doesn't appear to automatically add `iptables` like it used to, which caused some Enterprise (external) tests to fail.
The reason we are seeing this now is that we made a change to stay up to date with latest: https://github.com/hashicorp/vault/pull/27971 and we've gone from Alpine 3.18 to 3.19.
ENT PR: https://github.com/hashicorp/vault-enterprise/pull/6420 …
=> SDK: fix docker helper (explicitly add `iptables`)

ui/mirage/handlers/clients.js, ui/tests/acceptance/clients/counts/acme-test.js
This PR updates our Mirage scenario for client counts so that it filters based on the passed namespace header, similar to what the API does. Before, when using the clients mirage scenario, the activity response would stay the same when filtering by a namespace. Now, it filters the data consistently so we won't have weird unreliable numbers. 
To show what changed, in the GIF below I am logging the number `activity.total.clients` coming from the response, which should match the running total in the UI. Before this change the number would stay the same as when we are not filtering by a namespace. 
No user-facing changes, but this will be essential for updating the filter behavior without breaking a bunch of tests.
This doesn't *really* have to go into the sidebranch, other than I updated a …
=> UI [to sidebranch]: Update CC mirage filtering

website/content/docs/auth/approle.mdx
This PR is related to a tutorial PR: https://github.com/hashicorp/tutorials/pull/2210 and its Jira ticket (https://hashicorp.atlassian.net/browse/VAULT-11085).
To make the best practices guide to be more discoverable, adding a link to the AppRole doc page.
🔍 [Deploy preview](https://vault-hqeodnfnp-hashicorp.vercel.app/vault/docs/auth/approle#tutorial)
----
files.
in the PR …
=> [Docs] Add cross referencing link to AppRole usage best practices

audit/backend_file.go, audit/backend_file_ce_test.go, audit/backend_file_test.go, audit/backend_noop.go, audit/backend_socket.go, audit/backend_socket_test.go, audit/backend_syslog.go, audit/backend_syslog_test.go, audit/backend_test.go, audit/broker.go, audit/broker_ce.go, audit/broker_test.go, audit/entry_filter.go, audit/entry_filter_test.go, audit/entry_formatter.go, audit/entry_formatter_config.go, audit/entry_formatter_test.go, audit/errors.go, audit/event.go, audit/event_test.go, audit/hashstructure.go, audit/hashstructure_test.go, audit/headers.go, audit/headers_test.go, audit/nodes.go, audit/nodes_test.go, audit/options.go, audit/options_test.go, audit/sink_metric_timer.go, audit/types.go
Reduces the surface area of the package as much as possible, unexporting whatever seemed reasonable.
Remaining exported:
```
Interfaces:
----------
Auditor
Backend
HeaderFormatter
Registrar
Salter
Structs:
-------
Event
BackendConfig
Broker
HeadersConfig
NoopAudit // Test only, marked as 'deprecated'
Funcs:
-----
AuditedHeadersKey
ConvertToExternalError
Factory
HasInvalidOptions
NewBroker
NewFileBackend
NewHeadersConfig
NewNoopAudit // Test only, marked as 'deprecated'
NewSocketBackend
NewSyslogBackend
NoopAuditEventListener // Test only, marked as 'deprecated'
TestNoopAudit // Test only, marked as 'deprecated'
Consts:
------
AuditedHeadersSubPath
RequestType
ResponseType
TypeFile
TypeSocket
TypeSyslog
Errors:
------
ErrExternalOptions
ErrInternal
ErrInvalidParameter
```
Also adds …
=> Audit: unexport as much as possible in the audit package

builtin/logical/database/backend_test.go, changelog/28024.txt, helper/testhelpers/postgresql/postgresqlhelper.go, plugins/database/mysql/connection_producer.go, plugins/database/postgresql/postgresql.go, plugins/database/postgresql/postgresql_test.go, sdk/database/helper/connutil/cloudsql.go, sdk/database/helper/connutil/postgres.go, sdk/database/helper/connutil/sql.go, sdk/go.mod
This PR adds support for inline TLS configuration. 
We add new fields to the plugin's config endpoint: `tls_certificate`, `tls_private_key` and `tls_ca`. These fields will take certificate data as a string. This allows Vault Operators and/or development teams to configure TLS when they do not have access to the Vault Server.
Here is an example of configuring TLS inline via the new fields on the plugin’s config endpoint:
```
CONN_URL="user='{{username}}' database='postgres' \
host='localhost' port='5432' sslmode='verify-full'"
vault write database/config/postgres-db \
plugin_name=postgresql-database-plugin \
allowed_roles="*" \
connection_url="$CONN_URL" \
username=client \
tls_certificate="@/path/to/client.crt" \
tls_private_key="@/path/to/client.key" \
tls_ca="@/path/to/ca.crt"
```
The …
=> database/postgres: add inline certificate authentication fields

changelog/28042.txt, vault/activity_log.go, vault/external_tests/activity_testonly/activity_testonly_test.go
ENT PR  : 
https://github.com/hashicorp/vault-enterprise/pull/6427
Adjusts the query response to include current month data when endTime = future date. Once this is approved, I will make a subsequent CE PR.
files.
=> Show Current Month When Future Month Start Date is Provided

.github/workflows/test-run-enos-scenario-matrix.yml, enos/enos-dev-scenario-pr-replication.hcl, enos/enos-dev-scenario-single-cluster.hcl, enos/enos-globals.hcl, enos/enos-samples-ce-build.hcl, enos/enos-samples-ce-release.hcl, enos/enos-scenario-agent.hcl, enos/enos-scenario-autopilot.hcl, enos/enos-scenario-proxy.hcl, enos/enos-scenario-replication.hcl, enos/enos-scenario-seal-ha.hcl, enos/enos-scenario-smoke.hcl, enos/enos-scenario-ui.hcl, enos/enos-scenario-upgrade.hcl, enos/enos-variables.hcl, enos/enos.vars.hcl, enos/modules/build_artifactory_artifact/locals.tf, enos/modules/ec2_info/main.tf, enos/modules/install_packages/main.tf, enos/modules/softhsm_create_vault_keys/main.tf, enos/modules/softhsm_distribute_vault_keys/main.tf, enos/modules/softhsm_init/main.tf, enos/modules/softhsm_install/main.tf, enos/modules/vault_cluster/main.tf, enos/modules/vault_upgrade/scripts/maybe-remove-old-unit-file.sh, enos/modules/vault_verify_version/scripts/verify-cluster-version.sh
Our scenarios have been running the last gen of distributions in CI. This updates our default distributions as follows:
- Amazon: 2023
- Leap:   15.6
- RHEL:   8.10, 9.4
- SLES:   15.6
- Ubuntu: 20.04, 24.04
With these changes we also unlock a few new variants combinations:
- `distro:amzn seal:pkcs11`
- `arch:arm64 distro:leap`
We also normalize our distro key for Amazon Linux to `amzn`, which matches the uname output on both versions that we've supported. …
=> VAULT-29583: Modernize default distributions in enos scenarios

enos/enos-scenario-replication.hcl
Fix a race where we might configure replication before getting secondary cluster IP addresses when using shamir seals.
files.
=> enos(replication): wait for both clusters to be healthy before enabling replication

audit/broker.go, audit/sink_metric_labeler.go, changelog/28056.txt, go.mod, go.sum, internal/observability/event/sink_file.go, internal/observability/event/sink_file_test.go, internal/observability/event/sink_socket.go
This PR improves the audit subsystem: 
* Updates the `go-eventlogger` library to `v0.2.10` which [includes context errors](https://github.com/hashicorp/go-eventlogger/releases/tag/v0.2.10) when needed in logging requests/responses
* Adds `TRACE` logging to indicate when a context must be derived as the existing one is not viable for logging requests/responses
* Improves the sensitivity of 'sink' nodes (`file`, `socket`) to context cancellation, and prevent any potential contention over locks during attempts to write audit entries
of a public function, even if that change is in a CE file, _double check_ …
=> Audit: logging and improvements

changelog/28062.txt, vault/activity_log_util_common.go
Sort the activity log clients before adding them to the hyperloglog to ensure consistent results.
Performance:
```
$ VAULT_TEST_LOG_DIR=$(mktemp -d) go test -bench=^BenchmarkLargeClientCount$  -tags="ent enterprise testonly" $(pwd)/vault/external_tests/activity_testonly -run "^$" -benchmem 
goos: darwin
goarch: arm64
pkg: github.com/hashicorp/vault/vault/external_tests/activity_testonly
BenchmarkLargeClientCount/10000_per_mount-10                  18          56399891 ns/op        32806902 B/op      50671 allocs/op
BenchmarkLargeClientCount/100000_per_mount-10                  2         762893583 ns/op        207117244 B/op    465944 allocs/op
BenchmarkLargeClientCount/500000_per_mount-10                  1        5710724250 ns/op        1496278752 B/op  2420449 allocs/op …
```
=> Sort namespaces, mounts, and clients before adding them to HLL

changelog/28068.txt, command/operator_usage.go, vault/logical_system_activity.go
CE PR equivalent of https://github.com/hashicorp/vault-enterprise/pull/6450
files.
=> VAULT-29738 CE changes for client count warning

ui/app/components/clients/attribution.hbs, ui/app/components/clients/attribution.js, ui/app/components/clients/page-header.hbs, ui/app/components/clients/page-header.js, ui/app/components/clients/page/counts.hbs, ui/app/components/clients/page/counts.ts, ui/app/components/clients/page/overview.hbs, ui/mirage/handlers/clients.js, ui/tests/helpers/clients/client-count-selectors.ts, ui/tests/integration/components/clients/attribution-test.js, ui/tests/integration/components/clients/page-header-test.js
This PR moves the export button from the attribution block to the page header. It also fixes an issue with the filter data test helper which was mutating the original data (thanks @hellobontempo for tracking that down with me!)
**New page header:**
**Attribution block (will change again soon):**
=> UI: Move Client Count Export button

enos/enos-scenario-autopilot.hcl, enos/modules/vault_get_cluster_ips/main.tf, enos/modules/vault_verify_undo_logs/main.tf, enos/modules/vault_verify_undo_logs/scripts/smoke-verify-undo-logs.sh, enos/modules/vault_verify_version/scripts/verify-cli-version.sh
After VAULT-20259 we did not enable the undo logs verification. This
re-enables the check but modified to check the status of the primary and
follower nodes, as they should have different values.
While testing this I accidentally flubbed my version input and found the
diagnostic a bit confusing to read so I updated the error message on
version mismatch to be a bit easier to read.
=> enos: renable undo logs verification

.github/workflows/security-scan.yml
Optimize the cost of the Security `scan` workflow by utilizing a
different runner. Previously this workflow would use the
`custom-linux-xl` in `vault` vs. the `c6a.4xlarge` on-demand runner in
`vault-enterprise`. This resulted in the `vault` workflow costing an
order of magnitude more each month.
I tested with the following instances sizes to compare cost to execution
time:
| Runnner | Estimated Time | Cost Factor | Cost Score |
|---------|-----------------|-------------|-------------|
|ubuntu-latest|19m|1|19|
|custom-linux-small|21.5m|2|43|
|custom-linux-medium|11.5m|4|46|
|custom-linux-xl|8.5m|16|136|
Currently the `CI` and `build` require workflows take anywhere from
16-20 minutes on `vault`. Our goal is to not exceed that.
At this time we're going to try out `ubuntu-latest` as it …
=> VAULT-28638: Cost optimize the Security `scan` workflow

vault/activity_log.go, vault/activity_log_util_common.go, website/content/api-docs/system/internal-counters.mdx
When a namespace is deleted, display "deleted namespace <ns_id>" as the namespace path.
ENT pr: https://github.com/hashicorp/vault-enterprise/pull/6448
files.
=> CE: Added deleted namespace string

Dockerfile
Fixes the Dockerfile LICENSE path
files.
=> Fix Dockerfile LICENSE.txt path

changelog/27547.txt, changelog/28042.txt, changelog/28062.txt, vault/activity_log.go, vault/activity_log_util_common.go, vault/external_tests/activity_testonly/activity_testonly_test.go, website/content/api-docs/system/internal-counters.mdx
This PR is a manual backport to 1.17 of all of the CE PRs for fixing current month inconsistencies. 
files.
=> 1.17 Manual backport: Current month inconsistencies

ui/app/components/clients/activity.ts, ui/app/components/clients/attribution.hbs, ui/app/components/clients/attribution.js, ui/app/components/clients/date-range.hbs, ui/app/components/clients/page/counts.hbs, ui/app/components/clients/page/overview.hbs, ui/app/components/clients/page/overview.ts, ui/app/styles/components/chart-container.scss, ui/app/styles/core/charts.scss, ui/lib/core/addon/utils/client-count-utils.ts, ui/tests/acceptance/clients/counts/overview-test.js, ui/tests/helpers/clients/client-count-helpers.js, ui/tests/integration/components/clients/attribution-test.js
This PR updates the client count dashboard overview so that attribution for both namespaces and mount paths are shown unless we are filtered on the mount path level. 
**Updated attribution:**
**Not shown when filtered:**
=> UI: Split client count attribution

changelog/28093.txt, ui/lib/kv/addon/components/page/secret/details.js, ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-delete-test.js
Fixes an incorrect flash message when deleting a secret that says `Successfully created`:
files.
=> UI: Fix toast message text when deleting a kv v2 secret

audit/broker.go
when the eventlogger broker encounters an error during `Send`, this PR adjusts the way the error message is created when we `LogRequest` and `LogResponse` for audit (nil warnings should look a bit prettier in the server log).
files.
=> treat all errors as part of the same variadic set of arguments

.github/actions/build-vault/action.yml
Original PR https://github.com/hashicorp/vault/pull/28008
This PR missed updating some occurences 
files.
=> updating versions on remaining occurances of upload-artifact

.github/actions/build-vault/action.yml
Original PR https://github.com/hashicorp/vault/pull/28008
This PR missed updating some occurences
files.
=> Backport of  updating remaining occurances of upload-artifact into release/1.17.x

.github/workflows/security-scan.yml
Update our community PR detection in security scan to look at the `fork` attribute in the `pull_request` event payload.
files.
=> scan: skip running if the PR head is a fork

.github/actions/set-up-go/action.yml
Original PR https://github.com/hashicorp/vault/pull/27756/files
Updating missed occurrences of setup-go
files.
=> Backport of Updating remaining occurances of setup-go into release/1.17.x

.github/actions/set-up-go/action.yml
Original PR https://github.com/hashicorp/vault/pull/27756/files
Updating missed occurrences of setup-go
files.
=> Updating remaining occurances of setup-go

changelog/27457.txt, sdk/helper/testcluster/docker/environment.go, sdk/helper/testcluster/docker/environment_test.go
Currently NewTestDockerCluster had no means for setting any environment variables. This makes it tricky to create test for functionality that require thems, like having to set AWS environment variables.
DockerClusterOptions now exposes an option to pass extra enviroment variables to the containers, which are appended to the existing ones.
Related to: https://github.com/hashicorp/vault/issues/26852
applied. Brand new features have a differently
formatted changelog than other changelogs, so pay attention to that. If this
PR is the CE portion of an ENT PR, put the changelog here, _not_ in your ENT
PR. Feel free to refer to the [instructions](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md#changelog-entries) on changelog formatting if necessary.
getting backported to N-2, use the …
=> Add ENVs using NewTestDockerCluster

website/content/docs/commands/operator/generate-root.mdx
Updates the link to the old tutorial to point at the new how-to guide
files.
=> [DOCS] Fix broken link

ui/app/components/clients/activity.ts, ui/app/components/clients/page/counts.hbs, ui/app/components/clients/page/counts.ts, ui/app/components/clients/page/overview.ts, ui/tests/acceptance/clients/counts-test.js, ui/tests/integration/components/clients/page/counts-test.js, ui/tests/integration/components/clients/page/overview-test.js
Updates the client count filter behavior. Before, the namespace and mount path filters were mutually exclusive, and you could filter on the current namespace that you are logged into. 
With these changes: 
* the user can no longer see the current namespace as a filter option (because it doesn't do anything to filter on the current namespace)
* the mount filter is always available, listing the namespaces within the current OR chosen filtered namespace
* the namespace filter is hidden if there are no child namespaces available to filter on
When no counts are within child namespaces - namespace filter is hidden:
When namespace counts available - current namespace is not shown in options
When both namespace & mount are filtered - hides attribution blocks
Nested namespaces with clients - shows …
=> UI: CC Filter bar update

enos/enos-scenario-upgrade.hcl, enos/modules/vault_verify_billing_start_date/main.tf, enos/modules/vault_verify_billing_start_date/scripts/verify-billing-start.sh
Previously we'd fail in the verify-billing-start.sh retry loop instead of returning a 1. This fixes that and normalizes the script.
Fixes errors as seen here: https://github.com/hashicorp/vault/actions/runs/10478967676
We'll want to backport this to https://github.com/hashicorp/vault/pull/28130 and include both changes in the 1.15.x+ent and 1.16.x+ent changes.
- [] **Backport Labels:** If this PR is in the ENT repo and needs to be backported, backport   …
=> enos: don't exit in verify-billing-start retry loop

Dockerfile
Fix license file directory for ubi dockerfile
files.
=> Fix license for ubi dockerfile

ui/app/adapters/aws/lease-config.js, ui/app/adapters/aws/root-config.js, ui/app/adapters/secret-engine.js, ui/app/components/secret-engine/configure-aws.hbs, ui/app/components/secret-engine/configure-aws.ts, ui/app/components/secret-engine/configure-ssh.ts, ui/app/helpers/aws-regions.js, ui/app/models/aws/lease-config.js, ui/app/models/aws/root-config.js, ui/app/routes/vault/cluster/secrets/backend/configuration/edit.ts, ui/app/templates/vault/cluster/secrets/backend/configuration/edit.hbs, ui/lib/core/addon/components/form-field-groups.hbs, ui/lib/core/addon/components/form-field-groups.ts, ui/tests/acceptance/secrets/backend/aws/aws-configuration-test.js, ui/tests/helpers/general-selectors.ts, ui/tests/helpers/secret-engine/secret-engine-helpers.js, ui/tests/helpers/secret-engine/secret-engine-selectors.ts, ui/tests/helpers/sync/sync-selectors.js, ui/tests/integration/components/secret-engine/configure-aws-test.js, ui/tests/integration/components/secret-engine/configure-ssh-test.js, ui/types/vault/models/secret-engine.d.ts
* Removes tabs on AWS config form and puts Lease and Root configuration on one edit/create view (per designs).
* Adds form validations to root and lease models.
* Removes old methods under the secret-engine model and adapter that handled aws configuration saving.
* Add any new fields, specifically AWS WIF fields. This will be done in a PR targeted at the sidebranch.
**Create View**
**Edit View**
**Lease Validations**
=> AWS refactor, move to one form

ui/tests/acceptance/wrapped-token-test.js, ui/tests/helpers/auth/auth-helpers.ts
Attempts to stabilize the wrapped_token tests, which have been particularly flaky in CI with the following: 
```
Error: Browser timeout exceeded: 10s
Error while executing test: Acceptance | wrapped_token query param functionality: it authenticates you if the query param is present
Stderr: 
[0822/150758.502910:WARNING:sandbox_linux.cc(430)] InitializeSandbox() called with multiple threads in process gpu-process.
DevTools listening on ws://127.0.0.1:39411/devtools/browser/b2d2da15-9f0f-4565-b919-f198a86a795b
[0822/150800.909169:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
```
I'm not totally confident this will fix the flakiness because the error seems Chrome-related, but at least the test is using more modern patterns
=> UI: update wrapped token test

ui/tests/acceptance/clients/counts/overview-test.js
Filters out the current (root) namespace from the client count results before picking the top, because the current ns is excluded from the dropdown.
=> UI: stabilize clients overview test

website/content/docs/configuration/entropy-augmentation.mdx
Seal HA added this parameter to let people pick a seal to get entropy from
but it wasn't documented.
=> Document seal_name parameter to entropy

builtin/logical/pkiext/zlint_test.go
Sometimes we are failing to pull the zlint tagged version from GitHub when building up the test containers. Add a simple retry around the container building step to see if this resolves the issue.
Sample run: https://github.com/hashicorp/vault/actions/runs/10515176400/job/29134760780
```
{"stream":" ---\u003e Running in 8cb432ed9fde\n"}
{"stream":"\u001b[91mgo: github.com/zmap/zlint/v3/cmd/zlint@v3.6.2: github.com/zmap/zlint/v3/cmd/zlint@v3.6.2: Get \"[https://proxy.golang.org/github.com/zmap/zlint/v3/cmd/zlint/@v/v3.6.2.info\](https://proxy.golang.org/github.com/zmap/zlint/v3/cmd/zlint/@v/v3.6.2.info/)": net/http: TLS handshake timeout\n\u001b[0m"}
{"stream":" ---\u003e Removed intermediate container 8cb432ed9fde\n"}
{"errorDetail":{"code":1,"message":"The command '/bin/sh -c go install …
```
=> Add retry logic to building zlint test container

vault/activity_log.go, vault/activity_log_test.go, vault/external_tests/activity_testonly/activity_testonly_test.go
This PR changes some field names in the activity export API to be more consistent with entity nomenclature.
- `identity_name` -> `entity_name`
- `alias_name` -> `entity_alias_name`
- `local_alias` -> `local_entity_alias`
- `identity_metadata` -> `entity_metadata`
- `alias_metadata` -> `entity_alias_metadata`
- `alias_custom_metadata` -> `entity_alias_custom_metadata`
- `identity_group_ids` -> `entity_group_ids`
RFC: https://docs.google.com/document/d/1L42mm7rSwJSwMN4h7TnJCwt2GJ_DjKnlJIW8LxJzRgU/edit
ENT PR: https://github.com/hashicorp/vault-enterprise/pull/6515
of a public function, even if that change is …
=> Rename activity export API identity fields

.github/workflows/ci.yml
It appears that with the latest runner image[0] that we occasionally see
a flaky test with an error related to the fontconfig cache:
```
Error: Browser timeout exceeded: 10s
Error while executing test: Acceptance | wrapped_token query param functionality: it authenticates when used with the with=token query param
Stderr:
Fontconfig error: No writable cache directories
[0822/180212.113587:WARNING:sandbox_linux.cc(430)] InitializeSandbox() called with multiple threads in process gpu-process.
```
This change rebuilds the fontconfig cache on Github hosted runners.
Hopefully we can remove this at some point when a new runner image is
released.
[0] https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240818.1
to N, N-1, and N-2, using the …
=> ui: rebuild fontconfig cache on Github hosted runners

.github/workflows/enos-lint.yml
Set up the Go toolchain on the lint job. This already worked on CE because Github runners have a Go toolchain by default, but the same job will fail on self-hosted runners that do not.
I'll manually backport this to the `shfmt` changes.
files.
=> enos: install go toolchain on lint

.github/workflows/ci.yml
Reverts #28159 and adds back the pinned chrome version. Without it we are seeing a lot of failed tests (specifically on enterprise, like [this](https://github.com/hashicorp/vault-enterprise/actions/runs/10531689862)). Also, Ryan has [resolved](https://github.com/hashicorp/vault/pull/28177) 🤞🏻 the wrapped_token flakiness that we were seeing in CE
=> CI: add back chrome version pin

ui/app/services/flags.ts
This was removed by mistake in #28168 some `inject as service` are in the codebase intentionally. Original PR: #25367 
files.
=> UI: Add service injection back to flags service

website/content/docs/platform/aws/lambda-extension.mdx
🔍 [Deploy preview](https://vault-git-fork-aztalbot-docs-lambdaextensionca-d0296c-hashicorp.vercel.app/vault/docs/platform/aws/lambda-extension#caching)
- adds warning in the caching section of the vault—lambda-extension docs
- explains how distributed tracing headers can produce unintended consequences on caching
- if this behavior changes in a future version of the vault-extension (see open [PR](https://github.com/hashicorp/vault-lambda-extension/pull/145) and [issue](https://github.com/hashicorp/vault-lambda-extension/issues/146)), a warning like this may still be useful for usage of older versions
=> Docs (lambda-extension): add warning about caching re. distributed tracing headers

website/content/docs/upgrading/upgrade-to-1.15.x.mdx, website/content/docs/upgrading/upgrade-to-1.16.x.mdx, website/content/docs/upgrading/upgrade-to-1.17.x.mdx, website/content/docs/upgrading/upgrade-to-1.18.x.mdx
Update the upgrade guides for the removal of `curl` in the Docker containers. Specifically we handle the case where users are utilizing our security contexts and running the container as `vault` and without privilege escalation.
=> docs: update Docker `curl` upgrade guide

ui/app/components/secret-engine/configure-aws.hbs, ui/app/components/secret-engine/configure-aws.ts, ui/app/routes/vault/cluster/secrets/backend/configuration/edit.ts, ui/app/templates/vault/cluster/secrets/backend/configuration/edit.hbs, ui/lib/core/addon/components/form-field.hbs, ui/tests/helpers/secret-engine/secret-engine-selectors.ts, ui/tests/integration/components/form-field-test.js, ui/tests/integration/components/secret-engine/configure-aws-test.js, ui/types/vault/models/aws/lease-config.d.ts, ui/types/vault/models/aws/root-config.d.ts
This PR adds a WIF-only field `issuer` to the AWS configure form. This value is read and written to a [global endpoint](https://developer.hashicorp.com/vault/api-docs/secret/identity/tokens#read-configurations-for-the-identity-tokens-backend), not part of the AWS configuration models. On the configuration edit route we attempt to read this value if it's enterprise + AWS, and pass the currently configured value to the form component so a user can choose to update it. 
The field has a placeholder when issuer is not set or can't be read: 
When the issuer could not be read, but the user updates it the modal says:
Otherwise when the value is changed, the modal says:
=> UI (sidebranch) WIF Issuer field

changelog/28204.txt, ui/app/components/auth-jwt.js, ui/app/services/auth.js, ui/tests/acceptance/auth-test.js
When logging in with a non-renewable token (such as root or batch), I was seeing that upon login the UI immediately triggered a `renew-self` call. I traced it back to [this PR](https://github.com/hashicorp/vault/pull/27479) where we updated the batch token to also updates expirationTime even though it's not renewable. This caused `setLastFetch` to try to compare now to null, which caused it to always renew. 
Batch token after login before
=> UI: remove renew self call after login

changelog/28207.txt, command/agentproxyshared/cache/cachememdb/cache_memdb.go, command/agentproxyshared/cache/cachememdb/index.go, command/agentproxyshared/cache/lease_cache.go, command/agentproxyshared/cache/lease_cache_test.go, command/agentproxyshared/cache/static_secret_cache_updater.go, command/agentproxyshared/cache/static_secret_cache_updater_test.go
CE counterpart for https://github.com/hashicorp/vault-enterprise/pull/6544
files.
=> VAULT-30219 CE changes for versioned secret fix

ui/lib/kv/addon/components/kv-subkeys-card.hbs, ui/lib/kv/addon/components/page/secret/overview.hbs, ui/lib/kv/addon/components/page/secret/overview.js, ui/lib/kv/addon/routes/secret.js, ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-navigation-test.js, ui/tests/integration/components/kv/page/kv-page-overview-test.js
=> UI: Add enterprise checks

go.mod, go.sum
We recently updated raft on `main` to 1.7.0 to include the pre-vote reliability improvement. This is due to be release in Vault 1.18 and has not yet been released.
We've since discovered a bug in this version of raft that is fixed in 1.7.1 so we should include this minor bug fix before 1.18 is released. Details in the [1.7.1 release notes](https://github.com/hashicorp/raft/releases/tag/v1.7.1). …
=> Bump raft to 1.7.1 to include pre-vote fixes

Dockerfile
When https://github.com/hashicorp/vault/pull/27154 and subsequently https://github.com/hashicorp/vault/pull/28141 were merged we stopped creating a top level `licenses` directory in the UBI container. That directory with our licenses and terms are required to pass [Redhat's container requirements](https://docs.redhat.com/en/documentation/red_hat_software_certification/2024/html-single/red_hat_openshift_software_certification_policy_guide/index#con-image-content-requirements_openshift-sw-cert-policy-container-images), which we [failed when trying to promote the latest containers](https://github.com/hashicorp/crt-workflows-common/actions/runs/10604245970/job/29392127321#step:12:115).
```json
"failed": [
{
"name": "HasLicense",
"elapsed_time": 0,
"description": "Checking if terms and …
```
=> ubi: fix `HasLicense` Redhat requirement

Dockerfile, changelog/28204.txt, changelog/28207.txt, command/agentproxyshared/cache/cachememdb/cache_memdb.go, command/agentproxyshared/cache/cachememdb/index.go, command/agentproxyshared/cache/lease_cache.go, command/agentproxyshared/cache/lease_cache_test.go, command/agentproxyshared/cache/static_secret_cache_updater.go, command/agentproxyshared/cache/static_secret_cache_updater_test.go, ui/app/components/auth-jwt.js, ui/app/services/auth.js, ui/tests/acceptance/auth-test.js
To ensure that 1.17.4+ent and 1.17.4 have commit parity and are releasable, this PR the following actions:
* Fix the `HasLicense` requirements in the UBI container
* Temporarily revert a [proxy change](https://github.com/hashicorp/vault/commit/ff2e104a3e39c23de793635c3c89a2c9074e212f) and [UI change](https://github.com/hashicorp/vault/commit/d2d795815f1f2daa472b60fe70ad7855feccd672) so that 1.17.4 CE will match the already release 1.17.4+ent
* Build all artifacts so that the result of this merge can be our release SHA
applying …
=> Prepare for 1.17.4 release

changelog/28204.txt, changelog/28207.txt, command/agentproxyshared/cache/cachememdb/cache_memdb.go, command/agentproxyshared/cache/cachememdb/index.go, command/agentproxyshared/cache/lease_cache.go, command/agentproxyshared/cache/lease_cache_test.go, command/agentproxyshared/cache/static_secret_cache_updater.go, command/agentproxyshared/cache/static_secret_cache_updater_test.go, ui/app/components/auth-jwt.js, ui/app/services/auth.js, ui/tests/acceptance/auth-test.js
Redo the changes that were reverted in https://github.com/hashicorp/vault/pull/28220 for the 1.17.4 release 
files.
=> Redo reverted 1.17.4 prep changes

ui/app/models/kv/data.js, ui/lib/kv/addon/components/kv-subkeys-card.hbs, ui/lib/kv/addon/components/page/secret/details.hbs, ui/lib/kv/addon/components/page/secret/overview.hbs, ui/lib/kv/addon/routes/secret.js, ui/lib/kv/addon/routes/secret/patch.js, ui/lib/kv/addon/templates/secret/details/index.hbs, ui/lib/kv/addon/templates/secret/index.hbs, ui/tests/helpers/kv/policy-generator.js, ui/tests/integration/components/kv/kv-subkeys-card-test.js
The original designs placed `Create new version` and `Patch latest version` into a dropdown. However, with feature freeze tomorrow we don't have time to do this because updating the tests will take too long. As an interim solution, adding the action to the toolbar and then as a follow-on we can put it in a dropdown for enterprise users only, pending permissions of course.
files.
in the …
=> UI: Add patch latest version to toolbar

ui/app/components/database-connection.js, ui/app/templates/components/database-connection.hbs, ui/tests/acceptance/secrets/backend/database/secret-test.js
After #28199 merged we got failing UI tests because the Postgresql test scenario didn't fill in username/password, which are required now (API responds with error without them)
=> UI: fix DB Postgres test

changelog/28186.txt, physical/raft/raft.go, physical/raft/raft_autopilot.go, vault/external_tests/raft/raft_test.go, vault/logical_system_raft.go, vault/raft.go
When setting up Raft and autopilot, the leader node will read a storage entry (`core/raft/autopilot/states`), which has a map of server IDs to upgrade and sdk versions. Autopilot will store this map in memory in a structure called `persistedStates`. If the storage entry does not exist, an error is logged but operation continues.
Whenever the autopilot library calls `NotifyStates` to inform the vault delegate that a state has changed, the leader will check to see if the cluster membership differs from what is in the `persistedStates` map, or if the upgrade version or sdk version differs from the `persistedStates` map. If either of these conditions is true, `persistedStates` is updated and written to storage at the path `core/raft/autopilot/states`.
`core/raft/autopilot/states` is not …
=> VAULT-28477 Bootstrap and persist autopilot versions

command/agentproxyshared/cache/static_secret_cache_updater.go, command/agentproxyshared/cache/static_secret_cache_updater_test.go
CE PR for https://github.com/hashicorp/vault-enterprise/pull/6553
files.
=> VAULT-30219 Bug fix for race condition

audit/hashstructure.go
- [ x ] **Backport Labels:** If this PR is in the ENT repo and needs to be backported, backport  
- [ x ] **ENT Breakage:** If this PR either 1) removes a public function OR 2) changes the signature
files.
- [ x ] **Jira:** If this change has an associated Jira, it's referenced either
description. Also, make …
=> VAULT-30557 - Adding some code to fix a regression.

website/content/docs/audit/syslog.mdx
Updates docs after a community question came up about an audit error:
https://github.com/hashicorp/vault/issues/28136
files.
=> Added some documentation

ui/tests/acceptance/clients/counts/overview-test.js
(Correctly) fixes a test that sometimes gets itself into an impossible situation due to generated mirage data
=> UI: correctly fix cc overview test

audit/entry_formatter.go
Removes `multierror` from `entry_formatter` (which completes removing it from the `audit` package).
See: https://github.com/hashicorp/vault/pull/27861/
files.
=> Audit: remove multierror package - from entry formatter

vault/logical_system.go, vault/logical_system_test.go
To address the TOB finding, this PR removes multiple "/" characters from a path during sanitization. It also adds tests.
files.
=> VAULT-27398: (TOB) remove / prefixes in sanitizePath

ui/app/adapters/kv/data.js, ui/app/components/control-group-success.js, ui/app/models/kv/metadata.js, ui/app/services/control-group.js, ui/lib/core/addon/components/control-group-inline-error.hbs, ui/lib/core/app/components/control-group-inline-error.js, ui/lib/kv/addon/components/page/secret/details.hbs, ui/lib/kv/addon/components/page/secret/details.js, ui/lib/kv/addon/components/page/secret/metadata/details.hbs, ui/lib/kv/addon/components/page/secret/metadata/details.js, ui/lib/kv/addon/components/page/secret/overview.hbs, ui/lib/kv/addon/components/page/secret/overview.js, ui/lib/kv/addon/components/page/secret/patch.hbs, ui/lib/kv/addon/components/page/secret/patch.js, ui/lib/kv/addon/routes/secret.js, ui/lib/kv/addon/routes/secret/metadata.js, ui/lib/kv/addon/templates/secret/details/index.hbs, ui/lib/kv/addon/templates/secret/index.hbs, ui/lib/kv/addon/templates/secret/metadata/index.hbs, ui/mirage/factories/kv-metadatum.js, ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-create-test.js, ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-edge-cases-test.js, ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-navigation-test.js, ui/tests/helpers/kv/kv-selectors.js, ui/tests/integration/components/edit-form-kmip-role-test.js, ui/tests/integration/components/kv/page/kv-page-metadata-details-test.js, ui/tests/integration/components/kv/page/kv-page-overview-test.js, ui/tests/integration/components/kv/page/kv-page-patch-test.js, ui/tests/integration/components/kv/page/kv-page-secret-details-test.js
Small follow-on to https://github.com/hashicorp/vault/pull/28212
This addresses a case where a user has control group access to `/data/` but does not have "read" access to `/metadata/`. Adds a manual request for the `Metadata` tab to request `custom_metadata` via `/data/` if a user has read access via control groups. 
Sample policy 
```
path "secret/data/*" {
capabilities = ["create", "read", "update", "delete", "list"]
control_group = {
max_ttl = "24h"
factor "approver" {
controlled_capabilities = ["read"]
identity {
group_names = ["managers"]
approvals = 1
}
}
}
}
```
<hr>
<hr>
of a public function, even …
=> UI: improve control group UX

ui/lib/kv/addon/components/kv-subkeys-card.js, ui/lib/kv/addon/components/page/secret/details.js, ui/lib/kv/addon/components/page/secret/overview.js
Adds `isPatchAllowed` to jsdoc component notes. Follow-on to https://github.com/hashicorp/vault/pull/28212
files.
=> UI: add `isPatchAllowed` to jsdoc component notes

builtin/logical/pki/backend.go, builtin/logical/pki/revocation/revoke.go
When we factored out the revocation API, I missed the fact that the `RevokeCert` implementation failed to grab the revocation storage lock prior to calling `revokeCert` method.
- Leverage the GetConfigWithUpdate to fetch the current CRL config, otherwise we can use older or nil configs.
- Change the API to process a little bit the logical.Response/error returns to a "normal" Go API to be used internally. This will require additional refactoring in the future to expose more specific ideas of what went wrong to the callers
applying …
=> Add missing revocation storage lock on RevokeCert refactoring

helper/locking/core_locking.go, internalshared/configutil/listener.go, vault/ha_test.go
fix some function names
files.
=> chore: fix some function names

audit/broker.go, audit/broker_test.go, changelog/28286.txt
This PR makes the following changes to the Audit system:
* Always use a newly derived context so that we cannot be cancelled by the HTTP request etc.
* Increase new context timeout to 10 secs
* Remove non-required code and tests (`isContextViable`)
No ENT PR required.
**NOTE:** 
The reason we are not currently looking into making the timeout tuneable/configurable is that it's an easy/surefire way to brick your Vault cluster if you turn this up too high. 
Each attempt to log a request or response means the eventlogger could spin up multiple goroutines for Vault's audit devices, if we're dealing with clusters experiencing 10s of thousands of requests per second, this could mean there's a lot 'in flight', and giving audit longer and longer likely won't resolve an issue if a …
=> Audit: always use derived context for audit logging, increase timeout to 10s

changelog/28293.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/10723842049
=> Update vault-plugin-database-redis-elasticache to v0.5.0

website/redirects.js
The current redirect for the lease explosion document is stale, and points to `/vault/docs/troubleshoot/lease-explosions`, which is 404.
This PR updates the redirects file so that there are two redirects for the document (the original URL and the stale target URL) which both point to the correct current target: `/vault/docs/configuration/prevent-lease-explosions`.
- `/vault/docs/concepts/lease-explosions` →  `/vault/docs/configuration/prevent-lease-explosions`
- `/vault/docs/troubleshoot/lease-explosions` →  `/vault/docs/configuration/prevent-lease-explosions`
of a public function, …
=> Docs: update redirect

ui/tests/helpers/auth/auth-form-selectors.ts, ui/tests/integration/components/auth-jwt-test.js, ui/tests/integration/components/control-group-success-test.js
After merging https://github.com/hashicorp/vault/pull/28262 these tests started failing consistently.  
```
Integration | Component | auth jwt: oidc: test role: it renders: Chrome 128.0
fetches the auth_url when the path changes
Expected:
3
Result:
4
```
```
Integration | Component | control group success: render without token: Chrome 128.0
shows unwrapped data
Expected:
true
Result:
false
``` …
=> UI: address flaky auth-jwt and control group tests

website/content/api-docs/system/secrets-sync.mdx, website/content/docs/deprecation/index.mdx, website/content/docs/sync/github.mdx
Add docs for github sync environment secrets
files.
=> Add docs for github sync environment secrets

ui/lib/kv/addon/components/kv-subkeys-card.js, ui/lib/kv/addon/components/page/secret/details.js, ui/lib/kv/addon/components/page/secret/overview.js, ui/lib/kv/addon/routes/secret.js, ui/lib/kv/addon/routes/secret/patch.js, ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-delete-test.js, ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-edge-cases-test.js, ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-navigation-test.js, ui/tests/helpers/kv/policy-generator.js
Follow-on to https://github.com/hashicorp/vault/pull/28212. I forgot to check for the secret state in the original implementation PR. This was caught from smoke testing (thanks, @Monkeychip!) Patching a secret is only available if the latest version has not been deleted or destroyed.
files.
description. Also, make sure the changelog …
=> UI: Hide patch for deleted or destroyed secrets

website/content/docs/release-notes/1.16.1.mdx, website/content/docs/release-notes/1.17.0.mdx
- [ x] **Backport Labels:** If this PR is in the ENT repo and needs to be backported, backport  
- [x ] If this fixes a critical security vulnerability or [severity 1](https://www.hashicorp.com/customer-success/enterprise-support) bug, it will also need to be backported to the current [LTS versions](https://developer.hashicorp.com/vault/docs/enterprise/lts#why-is-there-a-risk-to-updating-to-a-non-lts-vault-enterprise-version) of Vault. To ensure this, use **all** available enterprise labels.
- [ x] **ENT Breakage:** If this PR either 1) removes a public function OR 2) changes the …
=> DOCS: Updating the release notes with the known issue for hmac audit values

website/content/docs/secrets/pki/est.mdx
Fix some broken links on the PKI EST docs page when we moved the EST api-docs to a separate page.
=> Fix some broken links on the PKI EST docs page

ui/app/adapters/capabilities.js, ui/app/serializers/capabilities.js, ui/app/services/capabilities.ts, ui/tests/unit/services/capabilities-test.js
This bugfix is a follow-on to #28212 which added new capabilities features. Before this fix, accessing the KV secret data without access when within a namespace would incorrectly calculate that the user had read access, even though they didn't, resulting in a screen like: 
With this fix, the namespace secret tab correctly shows an empty state:
=> UI: Fix no data read within namespaces

ui/app/components/clients/page/token.hbs, ui/app/components/clients/page/token.ts
Follow-on to #28036. This PR fixes a bug where the new monthly chart in client counts entity/non-entity dashboard is hidden if there are very few new tokens. This is because it was being shown depending on an average instead of whether there is data to show. 
**Before Left // After Right**
=> UI: Fix client counts hiding new monthly based on average

ui/app/components/clients/date-range.hbs, ui/tests/integration/components/clients/date-range-test.js
Follow-on to #28036. Only shows reset button in enterprise. Still includes validation for Community version when start/end dates are not filled in:
=> UI: only render date range reset button in enterprise

.github/workflows/test-go.yml
In order for our enterprise nightlies to run the same test-go job but across a matrix of different base references we need to consider the checkout ref in our failure and summary uploads in order to prevent an upload race.
We also configure Git with our token before setting up Go so that enterprise CI workflows can execute without downloading a module cache.
CE bits extracted from https://github.com/hashicorp/vault-enterprise/pull/6586
break any tests. …
=> VAULT-30640: support running test-go in parallel on multiple branches

enos/modules/shutdown_multiple_nodes/main.tf, enos/modules/shutdown_node/main.tf, enos/modules/target_ec2_instances/main.tf
Previously our `shutdown_nodes` modules would halt the machine. While this is useful for simulating a failure, cleaning up the halted machines is very slow in AWS for some reason.
Instead, we now poweroff the machines and utilize EC2's instance poweroff handling to immediately terminate the instances.
I've tested both scenarios that use these modules locally and they still work as expected. I also timed before and after and this change saves 5 MINUTES in total runtime (~40%) for the PR replication scenario. I assume it yields similar results for autopilot.
of a public function, even if that change is in a …
=> enos: poweroff and terminate instances when shutting them down

vault/logical_system_activity_write_testonly.go
Enforce storage limits when writing activity log data
CE PR : https://github.com/hashicorp/vault-enterprise/pull/6579/files
closes https://github.com/hashicorp/vault-enterprise/pull/6579/files
files.
=> Added storage limits when writing activity log data in clientcount util

api/auth/approle/go.mod, api/auth/approle/go.sum, api/auth/aws/go.mod, api/auth/aws/go.sum, api/auth/azure/go.mod, api/auth/azure/go.sum, api/auth/gcp/go.mod, api/auth/gcp/go.sum, api/auth/kubernetes/go.mod, api/auth/kubernetes/go.sum, api/auth/ldap/go.mod, api/auth/ldap/go.sum, api/auth/userpass/go.mod, api/auth/userpass/go.sum
Update vault auth submodules to api/v1.15.0, in preparation for cutting the 1.18 release branch.
files.
=> update vault auth submodules to api/v1.15.0

.release/versions.hcl
Update the Backport assistant release file on CE to add 1.18.x branch. This was accidentally only done on ENT.
files.
=> Update the backport assistant release versions adding 1.18.x

ui/lib/core/addon/utils/client-count-utils.ts, ui/tests/integration/utils/client-count-utils-test.js
Follow-on to #28036. This PR fixes an issue where filtering to a mount from within a namespace was not correctly returning the matching data. 
Before / After
=> UI: Fix CC mount filter

ui/app/components/sidebar/nav/cluster.hbs, ui/app/components/sidebar/nav/cluster.js, ui/tests/integration/components/sidebar/nav/cluster-test.js
Follow-on to #28036. There is undesirable behavior when accessing the client count dashboard within a chrooted listener, so this PR removes the nav item to client counts when the GUI is accessed on a chrooted listener. 
Here is the sidenav as a root user logged into a chrooted listener:
=> UI: hide client count nav link when chrooted listener

builtin/credential/cert/path_login.go, builtin/credential/cert/path_login_test.go, changelog/28309.txt, sdk/helper/ocsp/client.go, sdk/helper/ocsp/ocsp_test.go
=> Ferry ocsp_ca_certificates over the OCSP ValidationConf

ui/app/components/secret-engine/configure-aws.hbs, ui/app/helpers/mountable-secret-engines.js
Spelling error caught in the demo. Thank you Steve A.!
See documentation [here](https://developer.hashicorp.com/vault/tutorials/enterprise/plugin-workoad-identity-federation) that confirms the correct spelling
=> Change "Workflow" to "Workload" 

changelog/28361.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/10816864015
=> Update vault-plugin-secrets-ad to v0.19.0

ui/app/components/clients/page/counts.hbs, ui/app/components/clients/page/counts.ts, ui/app/components/clients/page/overview.hbs
Follow-on to #28036. This PR fixes a bug where if there are only client counts in the child namespaces (not root/current), the filter bar is incorrectly hidden. It also would show "No data found" for mount attribution which is correct (because there are no mounts with clients in the current namespace) but misleading because there are mounts with attribution in other namespaces. 
Before/After
=> UI: Show filters and hide mount attribution when child clients only

changelog/28360.txt, go.mod, go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/10816862785
=> Update vault-plugin-secrets-gcpkms to v0.19.0

changelog/28371.txt, ui/app/app.js, ui/lib/replication/addon/components/enable-replication-form.js, ui/lib/replication/addon/components/page/mode-index.hbs, ui/lib/replication/addon/components/page/mode-index.js, ui/lib/replication/addon/controllers/index.js, ui/lib/replication/addon/engine.js, ui/lib/replication/addon/routes/application.js, ui/lib/replication/addon/templates/index.hbs, ui/tests/integration/components/page/mode-index-test.js
A user with the policy below (which is used in this [tutorial](https://developer.hashicorp.com/vault/tutorials/enterprise/disaster-recovery#policy-requirements)) was unable to enable replication in the GUI because the UI wasn't checking specifically for `/dr/` or `/performance/` in the original capabilities check. 
```js
// original check, path didn't include type
canEnablePrimary: this.store
.findRecord('capabilities', 'sys/replication/primary/enable')
.then((c) => c.canUpdate),
canEnableSecondary: this.store
.findRecord('capabilities', 'sys/replication/secondary/enable')
.then((c) => c.canUpdate),
```
Now type is included in the path passed to the capabilities endpoint which hides or shows "Enable" accordingly. If there's a problem reading capabilities, then the default is `true` …
=> UI: Fix enabling replication capabilities bug

website/content/docs/auth/cert.mdx
=> Mention the cert forwarding header in cert auth docs

builtin/logical/aws/path_static_roles.go, changelog/28330.txt
- [x ] **Backport Labels:** If this PR is in the ENT repo and needs to be backported, backport  
- [x ] If this fixes a critical security vulnerability or [severity 1](https://www.hashicorp.com/customer-success/enterprise-support) bug, it will also need to be backported to the current [LTS versions](https://developer.hashicorp.com/vault/docs/enterprise/lts#why-is-there-a-risk-to-updating-to-a-non-lts-vault-enterprise-version) of Vault. To ensure this, use **all** available enterprise labels.
- [x ] **ENT Breakage:** If this PR either 1) removes a public function OR 2) changes the …
=> VAULT-30694 Adding a check for nil values returned by the queue

builtin/logical/pki/backend_test.go, builtin/logical/pki/cmpv2_util_oss.go, builtin/logical/pki/fields.go, builtin/logical/pki/path_tidy.go, website/content/api-docs/secret/pki/index.mdx
=> add ce changes and documentation for tidying cmpv2 nonce store

ui/lib/core/addon/components/replication-header.hbs, ui/lib/replication/addon/components/page/mode-index.hbs, ui/lib/replication/addon/templates/index.hbs, ui/lib/replication/addon/templates/mode.hbs, ui/tests/acceptance/enterprise-replication-modes-test.js, ui/tests/acceptance/enterprise-replication-test.js, ui/tests/integration/components/replication-page-test.js
This PR attempts to stabilize flaky replication tests by adding specificity to the test selectors so that we can wait for specific selectors in the tests.
=> UI: stabilize replication tests

CHANGELOG.md
- This PR removes a 100% duplication section in the changelog file, for version 1.13.6
- One of the toughest PRs you'll ever see :)
files.
=> Remove 100% dup section for 1.13.6 in changelog

website/content/docs/platform/aws/lambda-extension.mdx
- Adds to the current explanation about auth token refreshes to explain the new optional header that forces a token refresh
-  header `X-Vault-Token-Options: revoke`
- This feature was added in this PR: https://github.com/hashicorp/vault-lambda-extension/pull/149
files.
description. Also, make sure the changelog is in this PR, _not_ …
=> Docs (lambda-extension): add explanation of `X-Vault-Token-Options: revoke`

website/content/docs/sync/github.mdx
Fixes issue with build being broken due to spaces before code block, e.g.: 
https://vercel.com/hashicorp/vault/5JEnsMKDPQtFFpoMhJ9LpUGrXoCf?filter=errors
Unclear why this started happening now, as it's been like that for over a year, but hey.
Green build: https://vercel.com/hashicorp/vault/HPb2SM71PoBPtECabfMPkBH5Z8Uj
files. …
=> Fix Vercel error caused by spaces before code snippet

.github/workflows/ci.yml
Once this PR is merged, we will be sending our UI test results to DataDog.
files.
=> Send the UI test results from the CI to DataDog

changelog/27559.txt, ui/app/adapters/application.js, ui/app/adapters/clients/activity.js, ui/app/components/clients/no-data.hbs, ui/app/components/dashboard/client-count-card.hbs, ui/app/components/dashboard/client-count-card.js, ui/app/models/clients/config.js, ui/mirage/handlers/clients.js, ui/tests/acceptance/chroot-namespace-test.js, ui/tests/acceptance/dashboard-test.js, ui/tests/helpers/auth/auth-helpers.ts, ui/tests/integration/components/clients/no-data-test.js, ui/tests/integration/components/dashboard/client-count-card-test.js, ui/tests/unit/adapters/application-test.js
This PR removes the info flash message from showing on the dashboard page when the client count card is shown. These changes were already incorporated into main/1.18 in [this PR](https://github.com/hashicorp/vault/pull/28036), but the backend backported the API changes that set the default date range and added the warning message so we must also backport this change.
=> UI: hide client count warning on dashboard

vault/external_tests/audit/audit_test.go
This PR adds a new end to end test `TestAudit_HMACFields` which verifies that the proper fields are HMACed in audit request and response entries.
files.
=> add end-to-end test for audit HMACing

website/content/docs/enterprise/lts.mdx
Unlike where we say that:
> **standard maintenance** for a given Vault version lasts approximately 1 year
We said that extended maintenance lasts for one year, but in a later section said that it's three major releases. As a result, it's unclear which is right. The correct answer is three major releases, which is approximately (not exactly) a year.
Closes https://github.com/hashicorp/vault/issues/28135 …
=> Update LTS language to not contradict

website/content/docs/secrets/pki/est.mdx, website/data/docs-nav-data.json
Currently, the versioned [doc](https://developer.hashicorp.com/vault/docs/secrets/pki/est) still shows `BETA` tag since the changes were only applied to `main`.
🔍 [Deploy preview](https://vault-4gcmhz1pi-hashicorp.vercel.app/vault/docs/secrets/pki/est)
* Remove the BETA badge from EST
* Add ent badge
files. …
=> Remove the BETA badge from EST in documentation (#28265)

website/content/docs/secrets/ldap.mdx
This PR adds an AD lifetime period of an old password  note to Vault LDAP secrets Engine Documentation. 
files.
=> Adding AD lifetime period of an old password  note to Vault LDAP secrets Engine Documentation.

website/content/api-docs/secret/ldap.mdx
This PR adds an AD lifetime period of an old password note to Vault LDAP secrets Engine API Documentation.
files.
=> Adding AD lifetime period of an old password note to Vault LDAP secrets Engine API Documentation

website/content/docs/sync/github.mdx
=> [MANUAL BACKPORT] Fix Vercel error caused by spaces before code snippet (#28408)

.github/workflows/ci.yml
Pins chrome in CI to the same version that is on `main`. An attempt to fix the flakiness we're seeing recently on the release branch runs.
=> UI: pin chrome to same version as is on main

website/content/docs/platform/k8s/helm/index.mdx
This PR updates the document of vault helm about what needs to be done if there is a special requirement of running vault with NLB.
files.
=> updated vault helm chart doc with usecase of nlb

website/content/docs/platform/aws/lambda-extension.mdx
Standard distributed tracing headers are now excluded from the cache key since https://github.com/hashicorp/vault-lambda-extension/pull/145 was merged. 
So, I've updated the warning about distributed tracing headers to focus on nonstandard headers. Such headers may still cause issues without consumers being aware of them. I didn't call it out, but for example: New Relic adds a vendor-specific distributed tracing header for backwards compatibility that needs to be explicitly turned off.
applying the patch for this PR to the ENT …
=> docs(lambda-extension): update distributed tracing headers warning;

builtin/credential/approle/path_login.go, builtin/credential/userpass/path_login.go, changelog/28441.txt, vault/external_tests/delegated_auth/delegated_auth_test.go
This PR updates the error handling for AppRole and UserPass when login credentials are missing. Currently, a `500` error is returned, but a `400` error is more accurate and aligns with the behavior of other auth engines (e.g., LDAP).
Original output:
```sh
> curl --request POST -v \
http://127.0.0.1:8200/v1/auth/userpass/login/mitchellh | jq -r ".auth"
...
< HTTP/1.1 500 Internal Server Error
...
```
New output:
```sh
> curl --request POST -v \
http://127.0.0.1:8200/v1/auth/userpass/login/mitchellh | jq -r ".auth"
...
< HTTP/1.1 400 Bad Request
...
```
=> Improve Error Handling for Missing Credentials in AppRole and UserPass

helper/testhelpers/mssql/mssqlhelper.go
- Get better test failure error messages by not shadowing the errors when we are attempting to start the MSSQL docker container, so we can fail the tests with the proper error message that is occuring instead of mssqlhelper.go:60: Could not start docker MSSQL: %!s(<nil>)
files. …
=> Do not shadow err within MSSQL test container intialization

api/auth/approle/LICENSE, api/auth/aws/LICENSE, api/auth/azure/LICENSE, api/auth/gcp/LICENSE, api/auth/kubernetes/LICENSE, api/auth/ldap/LICENSE, api/auth/userpass/LICENSE, changelog/27920.txt
This change copies `./api/LICENSE` to each sub-module `./api/auth/*`
Fixes #27775
Go module tooling mandates that each sub-module contains its own LICENSE file. If absent, it defaults to the LICENSE file in the root of the git repository. This resulted in the `api/auth/*` modules erroneously inheriting the BUSL license instead of the correct MPL license, as indicated by the SPDX info in the actual API code.
See https://go.dev/ref/mod#vcs-license
> When the go command creates a .zip file for a module that is not in the repository root directory, if the module does not have a file named LICENSE in its root directory (alongside go.mod), the go command will copy the file named LICENSE from the repository root directory if it is present in the same revision.
Adding the LICENSE files to each …
=> core/api: Add missing LICENSE files to sub-modules

helper/testhelpers/mssql/mssqlhelper.go
- I believe the `if t.Failed` prevents the logging of the container logging as when executed the test isn't considered failed yet.
- Use a test core logger so that we can capture the container output all the time and get it from the captured log files when the test fails
files. …
=> Add a core test logger to help capture the MSSQL container output

ui/app/components/secret-engine/configure-ssh.hbs, ui/app/models/role-ssh.js, ui/app/models/ssh-sign.js, ui/app/templates/vault/cluster/secrets/backend/sign.hbs, ui/tests/acceptance/secrets/backend/ssh/roles-test.js, ui/tests/helpers/openapi/expected-secret-attrs.js
https://github.com/hashicorp/vault/pull/28466 Added `allow_empty_principals` to the ssh engine. Though it's recommended to keep this value `false` we've added for parity with the backend. Also, an acceptance test was failing because a `valid_principals` was not provided and is now required.
files. …
=> UI: add `allow_empty_principals` to ssh engine (fixes failing test)

changelog/28494.txt, command/agentproxyshared/cache/lease_cache.go
See: https://github.com/hashicorp/vault-enterprise/pull/6725
Fixes this data race that I spotted as part of an unrelated test run.
Will be backported.
files.
=> Fix static secret caching race condition

changelog/28498.txt, vault/token_store.go
The `max_lease_ttl` config of the token backend is not used to constrain a token's TTL when creating a token directly using the `auth/token/create` endpoint. Instead, the system level default is used.
This PR introduces a fix that calculates a token's TTL by using the tuned `max_lease_ttl` value.
ENT PR: https://github.com/hashicorp/vault-enterprise/pull/6706
files.
in the PR …
=> calculate token lease TTL using tune config

builtin/logical/pki/fields.go, builtin/logical/pki/path_manage_issuers.go, builtin/logical/pki/path_sign_issuers.go, builtin/logical/pki/storage_test.go
This should be two fields: one field for the Cert Endpoints (Sign-intermediate/Generate Root) the other for the CSR Endpoint (intermediate generate).  These have different defaults, and descriptions.
This fixes the help text and open-api text of the key_usage parameter on 
- [*] **Backport Labels:** If this PR is in the ENT repo and needs to be backported, backport  
- [*] **Jira:** If this change has an associated Jira, it's referenced either
=> Split the Key_Usage Field into separate fields

ui/package.json
In 1.18 we removed running the tests in parallel to address test flakiness https://github.com/hashicorp/vault/pull/28262. We seem to be seeing similar flakiness in 1.17, hoping removing this command (even though it will make running test 1.5 times longer) reduces flakes.  
files. …
=> UI: Remove parallel command for running tests on github

ui/app/models/role-ssh.js, ui/app/models/ssh-sign.js, ui/app/templates/vault/cluster/secrets/backend/sign.hbs, ui/tests/acceptance/ssh-test.js, ui/tests/helpers/openapi/expected-secret-attrs.js
Manual backport of #28484 
<hr>
#28466 Added allow_empty_principals to the ssh engine. Though it's recommended to keep this value false we've added for parity with the backend. Also, an acceptance test was failing because a valid_principals was not provided and is now required.
files.
description. Also, make sure the changelog is in …
=> Backport 1.17.x: add allow_empty_principals to ssh engine (fixes failing test)

ui/tests/helpers/openapi/expected-secret-attrs.js
To fix a test failure `Acceptance | Heads up - backend param changes! Expected OpenAPI attributes enterprise > pki engine: pki/sign-intermediate model getProps returns correct attributes: Chrome 128.0`
Original PR #28502
=> Fix OpenAPI attr for pki key-usage helpText

CHANGELOG.md
Update changelog for the 1.17.6, 1.16.10, and 1.15.15 releases
files.
=> Update changelog for the 1.17.6, 1.16.10, and 1.15.15 releases

builtin/logical/pki/backend.go, builtin/logical/pki/path_tidy.go, builtin/logical/pki/path_tidy_test.go, builtin/logical/pki/storage.go, changelog/28488.txt, ui/app/models/pki/tidy.js, ui/app/serializers/pki/tidy.js, ui/lib/pki/addon/components/pki-tidy-form.hbs, ui/lib/pki/addon/components/pki-tidy-form.ts, ui/tests/acceptance/pki/pki-tidy-test.js, ui/tests/helpers/openapi/expected-secret-attrs.js, ui/tests/helpers/pki/pki-selectors.ts, ui/tests/integration/components/pki/page/pki-tidy-auto-settings-test.js, ui/tests/integration/components/pki/pki-tidy-form-test.js, ui/types/vault/models/pki/tidy.d.ts, website/content/api-docs/secret/pki/index.mdx
Start persisting the last time we ran auto-tidy in order to not lose the information across restarts. If an auto-tidy schedule was set to run every 7 days, but there was a scheduled Vault restart every 6 days, auto-tidy would never run as the counter would be reset on restart.
We add in two new auto-tidy fields to control a possible thundering herd problem of having too many auto-tidy processes starting up at once. `min_startup_backoff_duration` and `max_startup_backoff_duration` fields with defaults of 5m and 15m respectively. 
The UI for auto-tidy has been updated, adding the two new fields to the auto-tidy configuration screen, the new fields are hidden if not enabled, as well as being displayed within the auto-tidy configuration view. They do not appear on the manual tidy screens.
to …
=> PKI: Track last time auto tidy was run across restarts

ui/package.json, ui/yarn.lock
Resolves security vulnerability in `body-parser < 1.20.3` https://github.com/hashicorp/vault-enterprise/security/code-scanning/2022
After upgrading `ember-a11y-testing` package there was still one dependency relying on a vulnerable version (`ember-cli` -> `express` -> `body-parser 1.20.2`)
files. …
=> UI: address body-parser security vulnerability 

ui/tests/integration/components/pki/pki-tidy-form-test.js
Addresses a breakage on 1.17.x enterprise 
```
Integration | Component | pki tidy form: it renders all attribute fields, including enterprise: Chrome 128.0
Expected 35 assertions, but 33 were run
```
files.
=> Update UI test assertion for pki tidy form

website/content/api-docs/secret/ssh.mdx
When we introduced the new field `allow_empty_principals` within the ssh plugin docs, we missed an update to the `valid_principals` saying if the role had a default_user set it would be used and not that valid_principals is now always needed.
files.
=> Update ssh docs to add missing conditional for valid_principals

command/server.go
This PR adds an informational log message to clarify that the observed goroutine dumps are expected behavior and do not indicate a panic. The log message reassures that Vault is still running normally and can be unsealed. This should help reduce confusion when encountering goroutine dumps in the logs.
=> Add log message indicating expected goroutine dump behavior

website/content/api-docs/system/internal-counters.mdx
Add a couple more examples to the activity export API response to outline what AWS and k8s entity records might look like.
files.
=> add aws and k8s auth examples to export

builtin/logical/pki/path_tidy_test.go
- I have a suspicion the for loop with the timer can be infinite loops in certain circumstances. Instead leverage the normal test helpers for fetching tidy status
I've checked and no ENT specific tests call this function, so the API change is safe. 
files.
description. Also, make sure the changelog is in this PR, _not_ in your ENT …
=> Update PKI tests to leverage the tidy-status test helper

vault/init.go
Move the call to SetStoredKeys to the end of the initialization process. On Vault Enterprise, this minimizes the chances that the initial seal re-wrap fails when a node other than the one performing initialization becomes the active one.
files.
=> Move writing of stored keys to the end of Vault initialization.

ui/config/deprecation-workflow.js
Early-static deprecation was handled in [this](https://github.com/hashicorp/vault/pull/28444/commits/38ccb9ee78541673568ef7bc3a2dfd3fe06cc071) commit. I confirmed it was all handled and this PR removes the check from the config blob.
=> Remove early-static config check

builtin/logical/pki/backend.go, builtin/logical/pki/path_tidy.go
A deadlock can occur when we are reading the PKI tidy-status endpoint. This was introduced within [PR28488](https://github.com/hashicorp/vault/pull/28488) so no version of Vault that was released contains this issue.
The deadlock occurs when
1. The tidy-status api is called and acquires the read lock on `tidyStatusLock` at the top of pathTidyStatusRead [line 1689](https://github.com/hashicorp/vault/blob/main/builtin/logical/pki/path_tidy.go#L1689)
2. A blocking Lock call is performed against `tidyStatusLock` say within startTidyOperation [line 999](https://github.com/hashicorp/vault/blob/main/builtin/logical/pki/path_tidy.go#L999) 
3. The call to b.getLastAutoTidyTime() on [line 1727](https://github.com/hashicorp/vault/blob/main/builtin/logical/pki/path_tidy.go#L1727) attempts to …
=> Do not acquire a read lock twice on tidyStatusLock during tidy-status

.github/workflows/test-go.yml
- If we encounter a deadlock/long running test it is better to have go test timeout. As we've noticed if we hit the GitHub step timeout, we lose all information about what was running at the time of the timeout making things harder to diagnose.
- Having the timeout through go test itself on a long running test it outputs what test was running along with a full panic output within the logs which is quite useful to diagnose
break any tests. Sometimes ENT only …
=> Have go-test timeout before the GH step timeout to gather information

vault/init.go
This reverts commit dcbc4f333048604d7f6e908000b6e0dd13308867.
As there is some uncertainty about whether the fix committed on PR #28538 is safe, we are rolling back the fix from 1.18 and 1.17. 
files.
=> Revert "backport of commit e7e16fd1756afa5921f402ee9bff0bd58b422023 (#28555)"

vault/init.go
This reverts commit c77aa48e72ee923d45a66db839f0cf4f51aa8a1a.
files.
=> Revert "backport of commit e7e16fd1756afa5921f402ee9bff0bd58b422023 (#28554)"

ui/app/templates/vault/cluster/access/mfa/enforcements/enforcement/index.hbs
Fixes transition when navigating away from mfa enforcements back to dashboard
```
Preparing to transition from 'vault.cluster.access.mfa.enforcements.enforcement.index' to 'vault.cluster.index'
runtime.js:4142 
Error occurred:
- While rendering:
-top-level
application
sidebar/frame
hds/app-frame
hds/app-frame/parts/main
vault
vault.cluster
token-expire-warning
vault.cluster.access
vault.cluster.access.mfa
vault.cluster.access.mfa.enforcements
vault.cluster.access.mfa.enforcements.enforcement
vault.cluster.access.mfa.enforcements.enforcement.index
link-to
router_js.js:1010 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'shouldSupersede')
at NamedTransitionIntent.applyToHandlers (router_js.js:1010:1)
at NamedTransitionIntent.applyToState (router_js.js:959:1) …
```
=> add model to linkto

ui/app/adapters/application.js, ui/app/components/raft-storage-restore.js, ui/app/services/auth.js, ui/mirage/handlers/mfa-login.js, ui/package.json, ui/tests/integration/components/clients/page-header-test.js, ui/tests/integration/components/raft-storage-restore-test.js, ui/yarn.lock
This is part 1 of resolving the `rollup` security vulnerability. There is no refactoring necessary because we can just use the native JS fetch method: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch which uses the same syntax
```
⇒ yarn why rollup
├─ broccoli-rollup@npm:2.1.1
│  └─ rollup@npm:0.57.1 (via npm:^0.57.1)
│
├─ broccoli-rollup@npm:4.0.0
│  └─ rollup@npm:1.32.1 (via npm:^1.12.0)
│
└─ broccoli-rollup@npm:5.0.0
└─ rollup@npm:2.79.1 (via npm:^2.50.0)
⇒ yarn why broccoli-rollup
├─ @ember-data/private-build-infra@npm:4.12.8
│  └─ broccoli-rollup@npm:5.0.0 (via npm:^5.0.0)
│
├─ ember-fetch@npm:8.1.2
│  └─ broccoli-rollup@npm:2.1.1 (via npm:^2.1.1)
│
└─ ember-service-worker@https://github.com/meirish/ember-service-worker.git#commit=dda14187aace0d73ecdb6a55beac2194 …
```
=> UI: remove`ember-fetch` which used vulnerable version of `rollup`

changelog/28564.txt, vault/seal_autoseal.go
Vault's seal health checking is advisory, meaning it doesn't affect the operation of Vault to detect an unhealthy seal.  As such we originally logged failures as Warn.  In particular, we only logged at Warn level the message indicating all seals are unhealthy, which is a bad situation for operators.  This quick PR changes that line to ERROR to make it easier for operators to spot.  Addresses SR-175. …
=> Log when the seal is unavailable as error

ui/app/adapters/application.js, ui/app/components/raft-storage-restore.js, ui/app/services/auth.js, ui/mirage/handlers/mfa-login.js, ui/package.json, ui/tests/integration/components/raft-storage-restore-test.js, ui/yarn.lock
Manual backport of https://github.com/hashicorp/vault/pull/28575
files.
=> Backport 1.17.x UI: remove ember-fetch which used vulnerable version of rollup 

ui/package.json, ui/yarn.lock
Part 2 of resolving the `rollup` security vulnerability. Now that `ember-fetch` has been removed by https://github.com/hashicorp/vault/pull/28575, we can pin the version of `rollup` in the resolutions block. (Doing so beforehand broke the build)
files.
=> UI: pin rollup version in resolutions to `2.79.2`

helper/dhutil/dhutil.go
dhutil uses ScalarMult for ed25519 math, which has been deprecated because it can be problematic copying
data into fixed size arrays. This PR switches to the X25519 function instead.
files.
=> Remove one more use of ScalarMult from CE

api/client.go, api/output_string.go, command/main.go
Resolves https://github.com/hashicorp/vault/issues/25213
There is some confusion in the code around how `-output-curl-string` actually works, so I attempted to explain it in some comments.
files.
=> explain how -output-curl-string works in comments to avoid confusion

changelog/28574.txt, command/base.go
Resolves https://github.com/hashicorp/vault/issues/27404
The issue here, as I understand it, is that the `VAULT_AGENT_ADDR` environment variable takes higher precedence than the `-agent-address` CLI flag, in violation of what our docs say about how CLI flags should take precedence. The people reporting and commenting on the issue provided a wonderful reproduction shell script that makes this problem easy to see.
From what I can tell, [NewClient](https://github.com/hashicorp/vault/blob/main/api/client.go#L639-L642) is doing the right thing, by prioritizing the agent address over the regular address. The main problem is that the API client doesn't have access to CLI flags - it can only work from the config it's given.
I _think_ the fix I've done here is correct, in that 1) the repro shell …
=> -agent-address flag should have higher precedence than the env var

changelog/28597.txt, sdk/helper/ocsp/client.go
=> Dont add the error from validating via issuer signature if the subsequent verification from extraCas succeeds

audit/headers.go, audit/headers_test.go, changelog/28596.txt, vault/external_tests/audit/audit_test.go, website/content/docs/audit/index.mdx
This PR adds the [User-Agent](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent) as a default header in audit request entries. As with other request headers, this will not be hashed by default. One can override this and choose to HMAC the value via the[ /sys/config/auditing/request-headers/:name](https://developer.hashicorp.com/vault/api-docs/system/config-auditing#create-update-audit-request-header) endpoint.
break any tests. Sometimes …
=> VAULT-30108: Include User-Agent header in audit requests by default

.github/actions/containerize/action.yml, .github/workflows/build-artifacts-ce.yml
Use the latest Docker action to ensure correct arm64 container builds. It looks like this never made it to 1.18 somehow.
files.
=> containerize: use latest docker action

website/content/docs/enterprise/pkcs11-provider/index.mdx
- Add a missing architecture that we have published for a while to the existing table
- Add a Changelog to the end of the page
files.
=> Update Vault PKCS11 Provider docs

builtin/logical/pki/path_tidy.go
Refactor into a common definition the tidy status response field definitions for OpenAPI to avoid needing to update the same thing in different areas of the code. 
Also fix two small warnings around a missing case in a switch (that couldn't technically happen), and clean up an error check to use errors.Is instead of a straight comparison. 
files.
in the PR description, commit message, …
=> Cleanup some duplication in the PKI tidy response field definitions

ui/config/deprecation-workflow.js
Follow-on to https://github.com/hashicorp/vault/pull/28603
files.
=> Remove deprecation from workflow

ui/app/components/mfa/mfa-login-enforcement-form.js, ui/app/templates/components/mfa/mfa-login-enforcement-form.hbs, ui/config/deprecation-workflow.js
Address Ember data 5 deprecation No A with Array Like—see [here](https://deprecations.emberjs.com/id/ember-data-no-a-with-array-like/).
Running the whole test suite with the flag on, it only showed up in the mfa create enforcements form. 
In the template, we use  `map-to` on the search select, passing in the model property `mfa_methods`. However, `mfa-methods` is a hasMany model property, which means when it's called directly it returns a PromiseManyProxy. I followed the established component pattern of fetching methods in the constructor of the component and setting to a tracked property, resolving this issue. Note: this was also an issue in another use of mfa_methods, resolved [here](https://github.com/hashicorp/vault/pull/25952/files).
=> Address Deprecation no-a-wth-array-like

website/content/docs/configuration/replication.mdx
🧵 [Slack thread](https://hashicorp.slack.com/archives/C012RTGJR1V/p1728322182350659)
🔍 [Deploy preview](https://vault-git-docs-add-ent-rep-parameter-hashicorp.vercel.app/vault/docs/configuration/replication)
It was reported that the [replication config doc](https://developer.hashicorp.com/vault/docs/configuration/replication) does not mention `replication_canary_write_interval_seconds`.
This PR adds the parameter to the doc page.
break any tests. Sometimes …
=> [Docs] Add a missing parameter

.github/actions/install-external-tools/action.yml, tools/tools.sh
Update our version of buf to the latest 1.45.0 as version 1.25.0 has fallen off the first page of the `gh list` causing builds to fail. 
I imagine this will require an additional run of something, but let CI figure that out for me.
files.
=> Update buf to 1.45.0

changelog/28629.txt, ui/app/templates/components/secret-edit.hbs, ui/lib/kv/addon/components/kv-page-header.hbs, ui/lib/kv/addon/components/page/secret/details.hbs, ui/lib/kv/addon/components/page/secret/metadata/details.hbs, ui/lib/kv/addon/components/page/secret/metadata/version-history.hbs, ui/lib/kv/addon/components/page/secret/overview.hbs, ui/lib/kv/addon/components/page/secret/paths.hbs, ui/tests/integration/components/kv/kv-page-header-test.js
Adds a copy button for secret paths in both kv v2 and v1 secrets engines
files.
=> UI: Add copy button for secret path

website/content/docs/auth/azure.mdx, website/content/docs/secrets/azure.mdx
Update Azure secrets engine docs to use AZURE_SDK_GO_LOGGING for Azure debug
files.
=> Update Azure SDK logger variable in docs
