- changelog/28631.txt
- vault/logical_system.go
Use stored seal generation info for response to `sys/seal-backend-status`.
This fixes an issue where reading from `sys/seal-backend-status` can return stale information from non-active nodes.
files.
> Use stored seal generation info for response to sys/seal-backend-status

- .github/actions/install-external-tools/action.yml
- tools/tools.sh
Pin protoc-gen-go to 1.34.2 to resolve delta checks between the latest and the version for the 1.17.x branch.
files.
> protobuf: pin protoc-gen-go to 1.34.2 (1.17)

- ui/app/controllers/vault/cluster/access/mfa/methods/create.js
- ui/config/deprecation-workflow.js
Removes any of the no longer supported methods on PromiseManyArray's. There was only one remaining use case left—we we're using slice() in an MFA methods workflow.
[Here](https://deprecations.emberjs.com/id/ember-data-deprecate-promise-many-array-behaviors/) are the deprecation notes
[Here](https://rfcs.emberjs.com/id/0745-ember-data-deprecate-methods-on-promise-many-array/) is an RFC mentioning that `slice()` is no longer supported.
> Ember data remove deprecation Ember Promise Many Array behaviors

- command/agentproxyshared/cache/static_secret_capability_manager.go
Needed to copy the map behind the locking.
```
Write at 0x00c01a2f3470 by goroutine 86930:
runtime.mapassign_faststr()
/home/runner/actions-runner/_work/_tool/go/1.22.7/x64/src/runtime/map_faststr.go:203 +0x0
github.com/hashicorp/vault/command/agentproxyshared/cache.(*LeaseCache).storeStaticSecretIndex()
/home/runner/actions-runner/_work/vault-enterprise/vault-enterprise/command/agentproxyshared/cache/lease_cache.go:801 +0x5e4
github.com/hashicorp/vault/command/agentproxyshared/cache.(*LeaseCache).cacheStaticSecret()
/home/runner/actions-runner/_work/vault-enterprise/vault-enterprise/command/agentproxyshared/cache/lease_cache.go:696 +0x145e
github.com/hashicorp/vault/command/agentproxyshared/cache.(*LeaseCache).Send() …
```
> Fix data race around static secret capability manager

- website/content/api-docs/auth/cert.mdx
> Tweak the ocsp_ca_certificate param docs to be more clear about what kind of cert it wants

- CHANGELOG.md
> added changelog update records for 1.18.0, 1.17.7, 1.16.11, and 1.15.16

- vault/init.go
Revert "Move writing of stored keys to the end of Vault initialization. (#28538)"
This reverts commit e7e16fd1756afa5921f402ee9bff0bd58b422023.
A better fix is being implemented, see PR #28674.
Note that this PR does not need to be back ported, since the changes were only done in main.
files. …
> Revert "Move writing of stored keys to the end of Vault initialization. (#28538)"

- vault/init.go
- vault/seal.go
- vault/seal_autoseal.go
Prevent node activation while Vault initialization is in progress.
Store a value to storage to signal that initialization is in progress. Look for this entry when trying to unseal using stored keys, and bail out if the entry is found.
files.
> Prevent node activation while Vault initialization is in progress

- vault/init.go
Call ClearInitializationFlag before preSeal during Initialization.
files.
> Call ClearInitializationFlag before preSeal during Initialization.

- website/content/docs/internals/high-availability.mdx
- website/content/docs/internals/integrated-storage.mdx
Adds explanations of the HA active node elections and timing parameters for leadership elections
files.
> VAULT-28520: Docs describing active node/leadership election timing

- website/content/docs/configuration/adaptive-overload-protection.mdx
- website/data/docs-nav-data.json
The Adaptive Overload Protection configuration documentation required updating for the latest release.
files.
> Update AOP config docs

- ui/app/components/console/ui-panel.js
- ui/app/components/generated-item-list.js
- ui/app/routes/vault/cluster/access/identity/aliases/index.js
- ui/app/routes/vault/cluster/access/identity/index.js
- ui/app/routes/vault/cluster/access/leases/list.js
- ui/app/routes/vault/cluster/access/method/item/list.js
- ui/app/routes/vault/cluster/access/namespaces/index.js
- ui/app/routes/vault/cluster/policies/index.js
- ui/app/routes/vault/cluster/secrets/backend/list.js
- ui/app/services/store.js
- ui/lib/core/addon/mixins/list-route.js
- ui/lib/kmip/addon/routes/scopes/index.js
- ui/tests/unit/services/store-test.js
Slowly chipping away at cleaning up our manual store. This PR removes stubbed methods `unloadAll` and `unloadRecord` which are no longer necessary due to fixes released in ember data 4.12
files.
> UI: Ember data upgrade prep: cleanup store and lazyPaginatedQuery

- website/content/docs/platform/k8s/vso/secret-transformation.mdx
- website/content/docs/platform/k8s/vso/sources/hvs.mdx
Documents usage of HVS rotating and dynamic secrets with VSO, part of VSO v0.9.0.
Preview links:
* https://vault-git-docs-vault-30504vault-30502vso-hvs-r-0297a3-hashicorp.vercel.app/vault/docs/platform/k8s/vso/sources/hvs
* https://vault-git-docs-vault-30504vault-30502vso-hvs-r-0297a3-hashicorp.vercel.app/vault/docs/platform/k8s/vso/secret-transformation#map-functions
- [-] If this fixes a critical security vulnerability or [severity 1](https://www.hashicorp.com/customer-success/enterprise-support) bug, it will also need to be backported to the current [LTS …
> docs/vso: hvs rotating and dynamic secrets

- .github/actions/changed-files/action.yml
- .github/actions/install-external-tools/action.yml
- .github/actions/run-apupgrade-tests/action.yml
- .github/actions/set-up-sqlc/action.yml
- .github/scripts/changed-files.sh
- .github/workflows/ci.yml
This PR adds automated Autopilot upgrade tests to our CI. The ability to manually run the workflow from the GitHub UI will be added in https://github.com/hashicorp/vault-enterprise/pull/6696.
Co-authored by @raskchanky.
files.
> [VAULT-28762] Run Autopilot upgrade tests on main and PRs to main on ENT if the AP code has changed

- changelog/28704.txt
- go.mod
- go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/11335146286
> Update vault-plugin-secrets-openldap to v0.14.2

- website/content/docs/secrets/transform/index.mdx
- website/content/docs/secrets/transform/tokenization.mdx
> Document the encryption algorithms used in ADP auditing purposes

- builtin/logical/pki/acme_challenge_engine.go
- builtin/logical/pki/acme_challenges.go
- builtin/logical/pki/acme_errors.go
- builtin/logical/pki/path_acme_test.go
- changelog/28678.txt
> Adds ACME specific error types to errors returned by challenge validation functions.

- builtin/logical/pki/cert_util.go
> add error info to internal error

- website/content/docs/internals/rotation.mdx
- website/content/docs/internals/telemetry/metrics/all.mdx
- website/content/docs/internals/telemetry/metrics/core-system.mdx
- website/content/docs/internals/telemetry/metrics/storage.mdx
- website/content/partials/telemetry-metrics/vault/barrier/estimated_encryptions.mdx
[SPE-962](https://hashicorp.atlassian.net/browse/SPE-962): Add information around missing metric `vault.barrier.estimated_encryptions` and update key rotation info to mention it
[All metrics reference preview](https://vault-git-docs-spe-962-hashicorp.vercel.app/vault/docs/internals/telemetry/metrics/all#vault-barrier-estimated_encryptions)
[Core system metrics reference](https://vault-git-docs-spe-962-hashicorp.vercel.app/vault/docs/internals/telemetry/metrics/core-system#barrier-metrics)
[Storage metrics reference](https://vault-git-docs-spe-962-hashicorp.vercel.app/vault/docs/internals/telemetry/metrics/storage#barrier-metrics)
[Key rotation preview](https://vault-git-docs-spe-962-hashicorp.vercel.app/vault/docs/internals/rotation)
[SPE-962]: …
> [DOCS] Add missing metric: vault.barrier.estimated_encryptions

- website/content/docs/configuration/listener/tcp/index.mdx
- website/content/docs/interoperability-matrix.mdx
- website/content/partials/alerts/ipv6-compliance.mdx
- website/data/docs-nav-data.json
Add information about IPv6 compliance per the conversation in [VAULT-29153](https://hashicorp.atlassian.net/browse/VAULT-29153)
Interoperability page preview: https://vault-git-docs-ipv6-updates-hashicorp.vercel.app/vault/docs/interoperability-matrix
TCP listener page preview: https://vault-git-docs-ipv6-updates-hashicorp.vercel.app/vault/docs/configuration/listener/tcp
[VAULT-29153]: https://hashicorp.atlassian.net/browse/VAULT-29153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> VAULT-29153: Update docs with IPv6 compliance info

- website/content/partials/faq/client-count/computing-clients.mdx
Update client counting FAQ to reflect changes in the Nomad integration and in how Vault counts non-entity tokens.
(Can't update the labels, but this applies to all recent Vault versions).
> update wording of Nomad Client Counting FAQ to reflect the new Integration

- ui/package.json
- ui/yarn.lock
Upgrading HDS to the latest [@hashicorp/design-system-components@4.13.0](https://github.com/hashicorp/design-system/pull/2469). Fast follow-up on #28525.
For context, 4.10.0 introduced a change in the Dropdown behavior (the list content was preserved in the DOM) that was reverted in 4.13.0. Raising this PR to prevent any potential unexpected impact on end-users, although there are no issues surfaced by manual and automated testing in `vault`.
break any …
> UI: upgrade HDS to 4.13.0

- CHANGELOG.md
- changelog/28330.txt
This entry in the changelog should actually be `secret/aws` instead of `auth/aws`
The original fix is [here](https://github.com/hashicorp/vault/pull/28330)
> Fix typo in changelog

- changelog/28742.txt
- ui/app/templates/components/identity/item-alias/alias-details.hbs
- ui/app/templates/components/identity/item-details.hbs
- ui/app/templates/vault/cluster/access/mfa/methods/method/index.hbs
Adds copy buttons to ids for entities, aliases and mfa methods
<hr>
<hr>
files.
> Adds copy button to entity, alias and mfa method ID fields

- changelog/28748.txt
- command/agentproxyshared/sink/file/file_sink.go
- helper/osutil/fileinfo_unix.go
- helper/osutil/fileinfo_windows.go
Closes #28734
Sets chown to a noop on windows, instead of erroring. 
files.
> Fix Windows chown error

- api/sys_mounts.go
- changelog/28752.txt
- command/auth_enable.go
- command/auth_enable_test.go
- command/auth_tune.go
- command/auth_tune_test.go
- command/commands.go
- command/secrets_enable.go
- command/secrets_enable_test.go
- command/secrets_tune.go
- command/secrets_tune_test.go
- vault/logical_system.go
- vault/logical_system_paths.go
- vault/mount.go
- vault/request_handling.go
- vault/router.go
- website/content/docs/commands/auth/enable.mdx
- website/content/docs/commands/auth/tune.mdx
- website/content/docs/commands/secrets/enable.mdx
- website/content/docs/commands/secrets/tune.mdx
- website/content/docs/secrets/pki/cmpv2.mdx
CMPv2 specifies that the cmp path may or may not end in a trailing slash. 
Vault's request processing has a requirement that they do not for POST.  To
make this work, add a tuneable to the mount that will trim slashes if
enabled.  All existing mounts will default to off, preserving the existing
behavior.  CMPv2 capable PKI mounts will enable this.
files.
in the PR description, commit …
> Support trimming trailing slashes via a mount tuneable to support CMPv2

- changelog/28751.txt
- vault/audit.go
- vault/audit_test.go
Prevent the audit process from allowing duplicate file path targets
files.
> VAULT-21710 - prevent duplicate audit file_path targets

- vault/router.go
When adding the new method `MatchingMountAndEntry` within https://github.com/hashicorp/vault/pull/28752, no locks were being acquired which lead to some race conditions on mount creations. This has not made it into any released versions of Vault.
```
Write at 0x00c000b493f8 by goroutine 4501:
github.com/armon/go-radix.(*node).addEdge()
/home/runner/go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:43 +0x3ce
github.com/armon/go-radix.(*Tree).Insert()
/home/runner/go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:184 +0x2fd
github.com/hashicorp/vault/vault.(*Router).Mount()
/home/runner/work/vault/vault/vault/router.go:239 +0x8b4
github.com/hashicorp/vault/vault.(*Core).enableCredentialInternal()
/home/runner/work/vault/vault/vault/auth.go:220 +0x1e26 …
```
> Fix a race condition in mount lookups

- vault/activity_log_stubs_oss.go
- vault/activity_log_util.go
Moves the method to a stub so that ENT no longer breaks
files.
> Added Stubs to Stop Breaking Builds in Ent

- go.mod
- go.sum
Upgrade GCP Secrets plugin to v0.20.1. Will be backported to upcoming Vault 1.18.1 patch release
> Upgrade GCP Secrets to v0.20.1

- go.mod
- go.sum
Upgrade GCP Auth plugin to v0.19.1. Will be backported to upcoming Vault 1.18.1 patch release
> Upgrade GCP Auth to v0.19.1

- vault/core.go
- vault/external_tests/raft/raft_test.go
- vault/logical_system.go
- vault/logical_system_raft.go
- vault/raft.go
Adds limits for raft challenges. Ent PR: https://github.com/hashicorp/vault-enterprise/pull/6865
files.
> VAULT-31264: Limit raft joins

- website/content/docs/what-is-vault.mdx
🎫 [Jira issue](https://hashicorp.atlassian.net/browse/SPE-993)
🔍 [Deploy preview](https://vault-git-docs-fix-duplicated-header-hashicorp.vercel.app/vault/docs/what-is-vault)
Reported issue: The "[What is Vault?](https://developer.hashicorp.com/vault/docs/what-is-vault)" heading and text were repeated. 
This PR:
- Removes the repeated heading
- Fix some of the H3 to H2 so that they'll show up on the TOC
- Updated the old callout box style to use new
break any …
> [Docs] Remove duplicated text

- .github/actions/create-dynamic-config/action.yml
[Cache scopes allow other branches to inherit default branch scopes](https://github.com/actions/cache?tab=readme-ov-file#cache-scopes). In practice this means that release branches can restore dynamic config from `main`. Instead, we now include the vault version as part of the cache key to ensure we don't include versions that are incompatible with our version.
files.
in the PR …
> pipeline: include the version in the dynamic config key

- ui/lib/core/addon/templates/components/replication-action-disable.hbs
The modal originally read the following which is incorrect. Secondary storage is not wiped when disabling replication on the primary.
files.
> UI: Update disabling replication copy 

- ui/app/components/transit-edit.js
- ui/app/templates/components/transit-edit.hbs
- ui/app/templates/components/transit-form-create.hbs
> UI: Display error message if no key name

- website/content/docs/platform/k8s/helm/index.mdx
fixed some lower case instances of Helm
Found two instances where Helm is lower case.
[Link to Helm chart](https://vault-kssw4284y-hashicorp.vercel.app/vault/docs/platform/k8s/helm#using-the-helm-chart)
files.
> Update index.mdx - fixed some lower case instances of Helm

- physical/raft/raft.go
- physical/raft/raft_test.go
- sdk/physical/physical.go
This PR creates a new interface and the raft implementation of that interface, in order to support handling of removed nodes from an HA cluster 
files.
> VAULT-31748: add removable node HA backend interface and raft implementation

- website/content/partials/global-settings/both/ca-cert.mdx
Fixes references to VAULT_CACERT. Closes #28725
files.
> Fix VAULT_CACERT environment variable

- physical/raft/raft_test.go
Hopefully deflakes TestRaft_Removed.
files.
> Fix flaky TestRaft_Removed

- website/content/docs/configuration/seal/seal-ha.mdx
Fix a typo in the URL pointing to "sys/sealwrap/rewrap" API-Docs, in "Removing seal HA", step 2.
files.
> Docs: fix url typo in removing seal ha

- .github/actions/run-apupgrade-tests/action.yml
This PR does what it says on the tin. VCM is changing and we need to pin the version of it we use in CI to stop it from affecting our workflows.
files.
> CI: Pin VCM version used in Run Autopilot upgrade tests workflow

- builtin/logical/transit/path_sign_verify.go
- builtin/logical/transit/path_sign_verify_ce.go
- sdk/helper/keysutil/policy.go
- website/content/api-docs/secret/transit.mdx
- website/content/docs/secrets/transit/index.mdx
- This PR allows us to add new enterprise only fields and behaviors to the Transit sign/verify APIs.  
- It also includes a significant refactoring to reduce the code duplication across the sign/verify 
files.
> Transit: Allow ENT only arguments for sign/verify.

- builtin/logical/pki/backend_test.go
- builtin/logical/pki/issuing/issuers.go
- builtin/logical/pki/issuing/issuers_oss.go
- builtin/logical/pki/path_fetch_issuers.go
- builtin/logical/pki/path_fetch_issuers_stubs_oss.go
- builtin/logical/pki/path_manage_issuers.go
Add PKI issuer config fields to enable check disablement parameters, an upcoming ENT feature.
Add the following new configuration fields for issuers:
allow_disable_critical_extension_checks
allow_disable_path_length_checks
allow_disable_name_checks
allow_disable_name_constraint_checks
The ENT PR is https://github.com/hashicorp/vault-enterprise/pull/6924.
files.
in the PR description, …
> Add PKI issuer config fields to enable check disablement parameters 

- builtin/logical/pki/path_fetch_issuers.go
- changelog/28832.txt
Fix bug setting PKI issuer enable_aia_url_templating to be set to false.
files.
> Fix bug setting PKI issuer enable_aia_url_templating to be set to false

- builtin/logical/transit/path_keys.go
- changelog/28839.txt
- The key update API would release the lock a little too early after it persisted the update so the reference could be updated when it was preparing the response to the caller across updates and/or key rotations
- The storage updates were okay, just the response back to the caller of the update might see a mixture of different updates
files.
in the PR description, commit message, or …
> Transit: fix race in the key update api responses

- builtin/logical/transit/path_sign_verify.go
- builtin/logical/transit/path_sign_verify_ce.go
- builtin/logical/transit/path_sign_verify_test.go
- sdk/helper/keysutil/policy.go
- website/content/api-docs/secret/transit.mdx
1. Only accept sha2-512 hash_algorithm values for Ed25519ph signatures. It made things easier to understand instead of accepting both none or sha2-512 values.
2. Fix a bug in the sign api that an error was being swallowed
3. Add the new fields to CE schema definition as we want to accept a value for them and error out to the end-user if they are provided on CE. This is mainly to make sure end-users get an error on CE instead of a Pure Ed25519 signature as before and then get different values when they upgrade to ENT and they start getting a ph/ctx signature back.
4. Add a few more tests for Ed25519 modes with invalid data.
to N, N-1, and N-2, using the `backport/ent/x.x.x+ent` labels. If this PR is in the CE repo, you should only backport to N, using the `backport/x.x.x` label, not the …
> Fail sign/verify apis when Ed25519ph/ctx arguments are provided on CE

- vault/core_metrics.go
- vault/core_metrics_test.go
CE side changes for https://github.com/hashicorp/vault-enterprise/pull/6923
files.
> VAULT-31075 CE changes

- website/content/docs/concepts/resource-quotas.mdx
Updates docs to describe how resource quotas work with replication.
files.
> VAULT-24466: Quotas and replication docs

- changelog/28807.txt
- vault/request_handling.go
- vault/request_handling_test.go
Enterprise PR: https://github.com/hashicorp/vault-enterprise/pull/6920
files.
> VAULT-31393: Return 500 for some gRPC errors during login on perf standbys

- builtin/logical/pkiext/zlint_test.go
- Leverage the versioned golang images which should be more static avoiding issues we somtimes encounter pulling latest images from our docker mirror.
- We use the golang runtime version to avoid having to update this test continuously.
files.
> Pull versioned golang images in Zlint testsuite to avoid pulling with latest

- vault/activity_log.go
- vault/activity_log_test.go
- vault/activity_log_testing_util.go
Jira: https://hashicorp.atlassian.net/browse/VAULT-31928
Approved ENT PR: https://github.com/hashicorp/vault-enterprise/pull/6906
As part of this ticket, whenever we use a client, we check if it is local.
If a client is local, it is written to a local fragment and is tracked using partialMonthLocalClientTracker. For now, this is also added to current fragment and partialMonthClientTracker as to not break tests as these values are not written to storage.
When receiving fragments from standby nodes, these local clients are tracked in partialMonthLocalClientTracker and standbyLocalFragmentsReceived. For now, this is also added to partialMonthClientTracker and standbyFragmentsReceivedas to not break tests as these values are not written to storage.
Next ticket to work on …
> adding local clients to local fragments  ce changes

- vault/activity_log_testing_util.go
Jira: https://hashicorp.atlassian.net/browse/VAULT-31928
Approved ENT PR: https://github.com/hashicorp/vault-enterprise/pull/6906
files.
> add fragment locks to GetActiveLocalFragment and GetActiveFragment

- vault/request_handling.go
- vault/request_handling_test.go
Fix a test that was failing in enterprise by correcting the error check. I've verified that the enterprise test which was previously failing with race detection now passes
files.
> 500 for grpc context canceled errors during login

- website/content/docs/auth/azure.mdx
- website/content/docs/secrets/azure.mdx
This PR updates the 1.16.x docs to reflect that `AZURE_SDK_GO_LOGGING` is the correct environment variable to set if you want to enable Azure-level logging.
@ram-parameswaran already updated the docs for both the [latest](https://developer.hashicorp.com/vault/docs/secrets/azure#azure-debug-logs) and [1.17.x ](https://developer.hashicorp.com/vault/docs/v1.17.x/secrets/azure#azure-debug-logs) versions of the Azure plugin docs to have the [new AZURE_SDK_GO_LOGGING](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/new-version-guideline.md#logging) variable provided by the azcore package, instead of the [old AZURE_GO_SDK_LOG_LEVEL](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/previous-versions-quickstart.md#built-in-basic-requestresponse-logging) variable …
> Manual backport of Update Azure SDK logger variable in docs (#28622)

- changelog/28867.txt
- vault/identity_store_test.go
- vault/identity_store_util.go
- vault/identiy_store_test_stubs_oss.go
- vault/testing.go
To optimize loading entities into the IdentityStore during unseal we current load the 256 buckets from storage in parallel. We then process them in whatever order they load. This determinism should be fine because each entity should be loaded by ID and so the loading order shouldn't matter.
But in real-life historical (and potentially current) bugs can cause there to be duplicated aliases in storage. We have for many years attempted to cleanup and merge such problematic duplicate aliases on load, however we always merge them in the order they are encountered during loading. Because this is non-deterministic, it means that different aliases can "win" this merge process after different unseals causing unpredictable behaviour. It will often also mean that Enterprise Performance Standbys may …
> Make identity store loading and alias merging deterministic

- website/content/docs/upgrading/upgrade-to-1.19.x.mdx
- website/data/docs-nav-data.json
Add a 1.19.x upgrade note around Transit API change for Ed25519ph signatures.
files.
> Add 1.19.x upgrade note around Transit API change for Ed25519ph signatures

- Makefile
`quickdev` does not include the `prep` step for when it isn't needed during local testing.
files.
> Add quickdev Make target

- website/content/docs/commands/operator/rotate.mdx
Update rotate encryption key doc.
- Add command examples from the tutorial (as part of user journey/SEO) [SPE-1010](https://hashicorp.atlassian.net/browse/SPE-1010)
- Update for linting
files.
[SPE-1010]: …
> Docs: Update rotate encryption key command doc

- website/content/docs/commands/operator/rekey.mdx
The rekey and rotate tutorial is being deprecated, so this link pointing to it needs to be removed.
Part of user journey/SEO [SPE-1010](https://hashicorp.atlassian.net/browse/SPE-1010)
files.
[SPE-1010]: …
> Docs: remove link to archived tutorial

- website/content/api-docs/system/managed-keys.mdx
- website/content/docs/configuration/seal/pkcs11.mdx
Add a note that one should disable the `generate_key` flag in PKCS#11 and managed_key scenarios after the initial key was created to prevent any unwanted key creations in the future.
files.
> Add notes within the documentation about the generate_key flag

- builtin/logical/ssh/backend_test.go
- builtin/logical/ssh/path_roles.go
- changelog/28901.txt
- Return the new field in the read response API
- This fixes the reported UI issues as well.
- Add a test case that will catch these errors in the future of adding a field to the ssh role and not returning it in the read api response
Fixes https://github.com/hashicorp/vault/issues/28883
files. …
> secrets/ssh: Return the allow_empty_principals field in read api

- .github/pull_request_template.md
The previous instructions were a bit confusing for new developers to the codebase, as it didn't account for situations where you want to backport to older release branches but are on the CE repo.
- [N/A] **Backport Labels:** If this PR is in the ENT repo and needs to be backported, backport  
- [N/A] If this fixes a critical security vulnerability or [severity 1](https://www.hashicorp.com/customer-success/enterprise-support) bug, it will also need to be backported to the current [LTS versions](https://developer.hashicorp.com/vault/docs/enterprise/lts#why-is-there-a-risk-to-updating-to-a-non-lts-vault-enterpr …
> Clarify backport instructions further in PR template

- http/sys_seal.go
- http/sys_seal_test.go
- vault/core.go
- vault/core_test.go
- vault/testing.go
This PR adds a check for whether the node was removed from a cluster in the handler for `/sys/unseal`.
If the node was indeed removed, we will respond with a status code `500` and an error saying `node was removed from a HA cluster`.  
files.
> [VAULT-31754] Check removed status in sys/unseal and error out if the node has been removed from the cluster

- website/content/docs/commands/auth/move.mdx
- website/content/docs/commands/secrets/move.mdx
Update secret and auth method move command documentation as part of [SPE-897](https://hashicorp.atlassian.net/browse/SPE-897):
- Add a namespace example for secrets move
- Add a namespace example for auth method move
- Add post-move considerations for both
files.
description. Also, make sure the changelog is in this PR, _not_ in …
> Docs: update move commands

- changelog/28858.txt
- website/content/docs/configuration/index.mdx
- website/content/docs/configuration/reporting.mdx
- website/content/docs/enterprise/license/product-usage-reporting.mdx
- website/content/docs/release-notes/1.16.1.mdx
- website/content/docs/upgrading/upgrade-to-1.16.x.mdx
- website/data/docs-nav-data.json
Manual backport of https://github.com/hashicorp/vault/pull/28904 + https://github.com/hashicorp/vault/pull/28858 for 1.16
files.
> 1.16 Manual Backport: Release notes and docs for product usage data

- changelog/28858.txt
- website/content/docs/configuration/index.mdx
- website/content/docs/configuration/reporting.mdx
- website/content/docs/enterprise/license/product-usage-reporting.mdx
- website/content/docs/release-notes/1.16.1.mdx
- website/content/docs/release-notes/1.17.0.mdx
- website/content/docs/upgrading/upgrade-to-1.16.x.mdx
- website/content/docs/upgrading/upgrade-to-1.17.x.mdx
- website/data/docs-nav-data.json
Manual backport of https://github.com/hashicorp/vault/pull/28904 + https://github.com/hashicorp/vault/pull/28858 for 1.17
files.
> 1.17 Manual Backport: Release notes and docs for product usage data

- builtin/logical/pki/backend_test.go
- builtin/logical/pki/issuing/issue_common.go
- builtin/logical/pki/path_acme_order.go
- builtin/logical/pki/path_acme_test.go
- builtin/logical/pki/path_fetch_issuers.go
- builtin/logical/pki/path_root.go
- changelog/28907.txt
- sdk/helper/certutil/certutil_test.go
- sdk/helper/certutil/types.go
- ui/app/models/pki/issuer.js
- ui/lib/pki/addon/components/page/pki-issuer-edit.hbs
- ui/tests/integration/components/pki/page/pki-issuer-edit-test.js
- website/content/api-docs/secret/pki/index.mdx
- We introduce a new value called `always_enforce_err` for the existing leaf_not_after_behavior on a PKI issuer. The new value will force we error out all requests that have a TTL beyond the issuer's NotAfter value.
- This will apply to leaf certificates issued through the API as did err, but now to CA issuance and ACME requests for which we previously changed the err configuration to truncate.
Added a simple option with text drop down, I only saw the field saw on the PKI edit configuration screen. The new value is the one above the selected value in the screenshot.
of a public function, even if that change …
> PKI: Add a new leaf_not_after_behavior value to force erroring in all circumstances

- website/content/docs/release-notes/1.16.1.mdx
- website/content/docs/release-notes/1.17.0.mdx
- website/content/docs/release-notes/1.18.0.mdx
- website/content/docs/upgrading/upgrade-to-1.16.x.mdx
- website/content/docs/upgrading/upgrade-to-1.17.x.mdx
- website/content/docs/upgrading/upgrade-to-1.18.x.mdx
Manual backport of https://github.com/hashicorp/vault/pull/28904 for 1.18
files.
> Release notes backport for 1.18

- website/content/docs/upgrading/upgrade-to-1.16.x.mdx
- website/content/docs/upgrading/upgrade-to-1.17.x.mdx
- website/content/docs/upgrading/upgrade-to-1.18.x.mdx
Keeps wording consistent to the backports on https://github.com/hashicorp/vault/pull/28915 etc
files.
> Keep wording consistent on main

- builtin/credential/ldap/backend.go
- builtin/credential/ldap/path_config_rotate_root.go
- changelog/28881.txt
This PR updates the LDAP authentication to use debug level logging. After the introduction of the CAP library the debug logging was removed. This PR adds it back.
- [x ] **Backport Labels:** If this PR is in the ENT repo and needs to be backported, backport  
files.
- [ x ] **Jira:** If this change has an associated Jira, it's referenced either
in the PR …
> VAULT-31594 Add debug level logging to the LDAP auth library

- website/content/docs/partnerships.mdx
> Change link to HCP HVN docs

- website/content/docs/enterprise/entropy-augmentation.mdx
Updates entropy augmentation docs to include supelmental content from archived tutorial as part of [SPE-892](https://hashicorp.atlassian.net/browse/SPE-892).
files.
[SPE-892]: https://hashicorp.atlassian.net/browse/SPE-892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Docs: entropy augmentation updates

- CODEOWNERS
The default codeowner will be used as a point of contact for the repository.
This should make us conformant with CODEOWNER requirements in RND-010, and give a GitHub group that can serve as a default point of contact for the vault and vault-enterprise repositories.
files. …
> Sets a default codeowner for the repo

- website/content/docs/concepts/events.mdx
> Add note regarding event notification with perf replication

- api/sys_seal.go
- changelog/28938.txt
- command/command_test.go
- command/format.go
- command/status_test.go
- vault/logical_system.go
- vault/logical_system_test.go
- website/content/api-docs/system/seal-status.mdx
- website/content/docs/commands/status.mdx
This PR adds an optional field to the sys/seal-status endpoint and vault status output. If the storage/HA backend supports removability (currently this is only raft), then `removed_from_cluster` is included in the output with a value of true or false.
- [] **ENT Breakage:** If this PR either 1) removes a public function OR 2) changes the signature
files.
> VAULT-31751, VAULT-31752: `removed_from_cluster` in vault status

- command/command_testonly/operator_usage_testonly_test.go
- sdk/helper/clientcountutil/clientcountutil.go
- sdk/helper/clientcountutil/clientcountutil_test.go
- vault/activity_log.go
- vault/activity_log_test.go
- vault/activity_log_testing_util.go
- vault/activity_log_util_common.go
- vault/activity_log_util_common_test.go
- vault/external_tests/activity_testonly/acme_regeneration_test.go
- vault/external_tests/activity_testonly/activity_testonly_oss_test.go
- vault/external_tests/activity_testonly/activity_testonly_test.go
- vault/logical_system_activity_write_testonly.go
Saves all the local clients in local fragment to local segments and stores them in local/log/ entity
Jira: https://hashicorp.atlassian.net/browse/VAULT-31234
Ent approved PR: https://github.com/hashicorp/vault-enterprise/pull/7003
files.
> Storing local clients to local storage paths ce changes

- vault/mount_test.go
This was causing a data race in tests due to some new code that runs and reads the mount table.
Will need to backport this to N-2.
files.
> Add locking to mount tests that write to the mount table

- website/content/docs/secrets/kv/index.mdx
lower cased "key-value"
lower cased "key-value"
Just a text change on docs
files.
> lower case "key-value"

- website/content/docs/enterprise/license/product-usage-reporting.mdx
Manual docs backport from https://github.com/hashicorp/vault/pull/28931
files.
> 1.17 Docs for auth product usage metrics

- website/content/docs/enterprise/license/product-usage-reporting.mdx
Manual docs backport from https://github.com/hashicorp/vault/pull/28931
files.
> 1.16 Docs for auth product usage metrics

- .github/workflows/backport-ce.yml
Use the latest version of the backport assistant. As this workflow is only run on workflow_dispatch from the main branch no backporting is required.
files.
> backport-assistant: bump version to 0.5.3

- enos/modules/install_packages/scripts/synchronize-repos.sh
Enos test job handling exit code 2 on ubuntu 24.04 repo sync
files.
> adding logic to handle cloud-init error code 2

- website/content/docs/enterprise/license/product-usage-reporting.mdx
Docs for https://github.com/hashicorp/vault-enterprise/pull/7035
Will need backport to 1.18 and manual backport to 1.17 and 1.16.
files.
> VAULT-32507: Docs for secret engine usage metrics

- website/content/docs/platform/k8s/vso/secret-transformation.mdx
docs: Fix path to allowedSprigFuncs
files.
> docs: Fix path to allowedSprigFuncs

- builtin/logical/pki/issuing/cert_verify.go
- builtin/logical/pki/issuing/issuing_stubs_oss.go
- builtin/logical/pki/path_issue_sign.go
This PR is part of the re-implementation of PR #28921.
Add hook for ENT tweaking of PKI contraints verification options.
files.
> Add hook for ENT tweaking of PKI contraints verification options

- builtin/credential/okta/path_config.go
- builtin/logical/pki/issuing/cert_verify.go
- tools/pipeline/internal/cmd/generate_enos_dynamic_config.go
- tools/pipeline/internal/cmd/releases_list_versions.go
- tools/pipeline/internal/pkg/generate/enos_dynamic_config.go
- tools/pipeline/internal/pkg/generate/enos_dynamic_config_test.go
- tools/pipeline/internal/pkg/releases/client.go
- tools/pipeline/internal/pkg/releases/client_mock.go
- tools/pipeline/internal/pkg/releases/list_versions.go
Updates files after runnning `make fmt`
files.
> Run make fmt

- website/content/api-docs/secret/pki/index.mdx
- We missed adding this flag to the root CA generation call, but we do support it.
files.
> Update docs adding use_pss to PKI root generation api

- vault/external_tests/raftha/raft_ha_test.go
This test has been failing with the following:
```
=== FAIL: vault/external_tests/raftha TestRaftHA_Recover_Cluster/file (32.37s)
teststorage.go:98: unlinkat /tmp/vault-integ-file-1848360437: directory not empty
```
This is since Vault is still writing to it when we attempt to clean it up. Hopefully, calling cleanup manually and removing the cleanup earlier in the function should fix it.
Running untilfail locally didn't seem to reproduce the issue, so hopefully this works? If not, we can iterate more.
files. …
> Seal and cleanup cluster before test teardown for TestRaftHA_Recover_Cluster

- builtin/credential/cert/backend_test.go
- builtin/credential/cert/path_config.go
- builtin/credential/cert/path_login.go
- builtin/credential/cert/path_login_test.go
- changelog/29044.txt
- sdk/logical/response.go
- sdk/logical/response_test.go
- vault/identity_store_entities.go
- website/content/api-docs/auth/cert.mdx
Add a new cert auth configuration flag called "enable_metadata_on_failures" that if manually enabled, upon failures logging into cert-auth with a client certificate we would return the fields common name, serial, subject key id and authority key id from the client certificate in the response which will also appear in the audit log.
With the feature enabled in configuration, these are the audit logs assuming the keys have been marked to not hmac (they will be by default)
```
{
...
"response": {
"data": {
"data": {
"authority_key_id": "1c:a7:bb:5a:97:4d:bd:0d:12:ad:78:cc:f7:34:61:8d:9e:03:0b:03",
"common_name": "localhost.local",
"serial_number": "74414280014409089681629505391221737844000336179",
"subject_key_id": "72:e7:ae:72:a9:db:a8:1a:59:79:1b:2e:5b:97:4e:06:d1:d2:8a:ec"
},
"error": …
```
> Add an option to allow cert-auth to return metadata about client cert that fails login

- changelog/29050.txt
- sdk/physical/inmem/inmem_ha.go
- vault/sealunwrapper.go
- vault/sealunwrapper_test.go
Starting after commit 0ec3524, for each `GET` request Vault makes to the storage backend, the OSS seal unwrapper will make 1 additional `GET` request plus 1 additional `PUT` request. This is because the seal unwrapper now tries to unwrap all storage entries, even if the entry was not wrapped in the first place! Prior to 0ec3524, there was a check to see if the storage entry was wrapped before proceeding with the unwrap procedure, which prevented this behavior.
The increased storage latency, writes, and traffic  resulting from the extra requests causes noticeable performance degradation for some workloads. 0ec3524 was first included in Vault `v1.15.0`, and after upgrading from Vault `v1.14.9` to `v1.15.6`, some of our Vault clusters would take 2-3x longer to start up.
Other users have also …
> Fix OSS sealunwrapper adding extra get + put request to all storage get requests

- website/content/docs/enterprise/lts.mdx
The "Feature updates and improvements" line is misleading since we do not backport feature updates to N-1 or N-2. Since the answer is "no" for both columns, it creates less confusion to just delete it.
> [DOCS] Clarify maintenance table

- physical/raft/raft.go
- physical/raft/raft_test.go
- vault/core.go
- vault/external_tests/raft/raft_test.go
- vault/init.go
- vault/raft.go
- vault/request_forwarding.go
- vault/testing.go
This PR has a removed node shutdown if it sees that it's not in the raft configuration. For extra safety's sake, the node must have previously been present in the configuration in order for the node to shutdown.
files.
> VAULT-32568: Shutdown node when it's not in the raft config

- builtin/logical/database/path_roles_test.go
- builtin/logical/database/rotation.go
- changelog/28989.txt
Previously, when a static role rotation failed, we would store the password in the WAL entry. Upon retries, this same stored password would be reused. This leads customers to infinite loop cases where a failing password is infinitely retried.
This PR adds a fix which will generate a new credential and delete the existing WAL entry if it has failed on a retry. This will unblock customers until we can provide them with more control over their password policies so that password rotation failures don't happen as often.
files.
in the PR description, commit message, or …
> Update DB Static role rotation logic to generate new password if retried password fails

- vault/activity_log.go
- vault/activity_log_stubs_oss.go
- vault/activity_log_test.go
- vault/activity_log_util_common.go
- vault/activity_log_util_common_test.go
Migrate all clients from old storage locations to the correct new storage locations on secondaries and on primaries
Link to ENT pr: https://github.com/hashicorp/vault-enterprise/pull/7032
files.
> Migrate Clients From Old Storage Paths to New Paths During Upgrade #7032

- website/content/docs/enterprise/license/product-usage-reporting.mdx
Docs PR for https://github.com/hashicorp/vault-enterprise/pull/7072
Will need to be backported and manually backported
files.
> VAULT-32158 docs for secret sync usage metrics

- CODEOWNERS
Updates `CODEOWNER`:
- Makes `@hashicorp/vault-education-approvers` owner for files under the `website` directory.
- Removes explicit `@hashicorp/vault-education-approvers` entries for individual `website/` subdirectories and files.
> Make EDU owner for files under website/

- CODEOWNERS
Manual backport of [PR #29078](https://github.com/hashicorp/vault/pull/29078)
Updates `CODEOWNER`:
- Makes `@hashicorp/vault-education-approvers` owner for files under the `website` directory.
- Removes explicit `@hashicorp/vault-education-approvers` entries for individual `website/` subdirectories and files.
> [BACKPORT] Make EDU owner for files under website/ under release/1.18

- api/sys_health.go
- changelog/28991.txt
- http/sys_health.go
- http/sys_health_test.go
- vault/cluster/inmem_layer.go
- vault/core.go
- vault/external_tests/raft/raft_test.go
- vault/ha.go
- vault/ha_test.go
- vault/request_forwarding.go
- vault/request_forwarding_rpc.go
- vault/testing.go
This PR adds HA health and removed as statuses to the sys/health endpoint. 
- If a node has been removed from the cluster, its status code will be 530 (or the value from the `removedcode` query parameter) 
- If a node has missed 2 request forwarding heartbeats, its status code will be 474 (or the value from the `haunhealthycode` query parameter) 
The health response has new fields:
```
type HealthResponse struct {
...
RemovedFromCluster  *bool    // present when raft is the HA/storage backend
HAConnectionHealthy *bool    // present when the node is a standby/perf standby
LastRequestForwardingHeartbeatMillis int64   // non-zero when the node has completed at least one request forwarding heartbeat 
}
```
applying …
> VAULT-31755: Add removed and HA health to the sys/health endpoint

- changelog/29091.txt
- vault/core.go
- vault/core_metrics.go
- vault/expiration.go
- vault/expiration_test.go
- vault/token_store_test.go
This commit enforces complete censusManager teardown prior to stopping the expiration manager, allowing us to simplify locking elsewhere in censusManager code.
We're now guaranteed to not have state change underneath us, since censusManager goroutine lifecycles are postUnseal -> preSeal.
files.
> Fix unlocked mounts read

- vault/core_metrics.go
CE pair PR for https://github.com/hashicorp/vault-enterprise/pull/7096
files.
> VAULT-32159 CE changes for PKI metrics

- website/content/docs/enterprise/license/product-usage-reporting.mdx
1.17: Manual backport of https://github.com/hashicorp/vault/pull/29058
files.
> 1.17 Backport: VAULT-32158 docs (#29058)

- website/content/docs/enterprise/license/product-usage-reporting.mdx
Docs corresponding to https://github.com/hashicorp/vault-enterprise/pull/7096
Will need manual backport for 1.17 and 1.16.
files.
> VAULT-32159 docs for pki metrics

- vault/core_metrics.go
CE PR for https://github.com/hashicorp/vault-enterprise/pull/7101
files.
> VAULT-32159 issuers not certs CE changes

- website/content/docs/enterprise/license/product-usage-reporting.mdx
- website/content/docs/release-notes/1.16.1.mdx
1.16 Backport of https://github.com/hashicorp/vault/pull/29058
files.
> 1.16 Backport: VAULT-32158 docs (#29058)

- website/content/api-docs/system/storage/raftautosnapshots.mdx
This PR adds the missing documentation for azure autosnapshot auth modes.
> VAULT-32598: add docs for azure autosnapshot auth modes

- website/content/docs/enterprise/license/product-usage-reporting.mdx
Manual backport of https://github.com/hashicorp/vault/pull/29102
files.
> Manual 1.16 Backport: VAULT-32159 docs for pki metrics (#29102)

- website/content/docs/enterprise/license/product-usage-reporting.mdx
Manual backport of https://github.com/hashicorp/vault/pull/29102
files.
> 1.17 Manual backport: VAULT-32159 docs for pki metrics (#29102)

- vault/mount_test.go
Looks like `c2` was just missed by accident. This is causing races when other processes read the mount table.
See: https://github.com/hashicorp/vault-enterprise/actions/runs/12187321355/job/33999445396#step:7:223
files.
> Fix missing locking in mount tests

- website/content/docs/sync/awssm.mdx
- website/content/docs/sync/azurekv.mdx
- website/content/docs/sync/gcpsm.mdx
- website/content/docs/sync/github.mdx
- website/content/docs/sync/index.mdx
- website/content/docs/sync/vercelproject.mdx
- website/data/docs-nav-data.json
This PR updates the doc page title and description for secrets sync. The intent is to improve the clarity and discoverability of these doc pages.
🔍 [Deploy preview](https://vault-git-docs-update-sync-docs-seo-hashicorp.vercel.app/vault/docs/sync)
files.
> [DOCS] Update the doc title and description for SEO improvements

- changelog/29117.txt
- vault/core.go
- vault/raft.go
Fix decryption of raft bootstrap challenge in multi-seal scenarios (Vault Enterprise).
files.
> Fix decryption of raft bootstrap challenge in multi-seal scenarios

- changelog/29128.txt
- vault/diagnose/tls_verification.go
- The duration returned from the `NearExpiration` is supposed to represent the time till expiry from now and not the calculated time a month from now.
- Also flip the returned value to be a duration value that can be added to time.Now() to get to the expiration value, instead of a negative value that was previously returned.
files.
> Fix return certificate expiry time from NearExpiration

- changelog/29131.txt
- go.mod
- go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/12244663465
> Update vault-plugin-secrets-openldap to v0.14.4

- changelog/29131.txt
- go.mod
- go.sum
Backports https://github.com/hashicorp/vault/pull/29131 into `release/1.18.x`
> Backport of Update vault-plugin-secrets-openldap to v0.14.4 into release/1.18.x

- vault/activity_log.go
- vault/activity_log_test.go
- vault/activity_log_testing_util.go
- vault/activity_log_util.go
- vault/activity_log_util_common.go
- vault/activity_log_util_common_test.go
During an upgrade, the secondary will send its global data to the primary. It will use exponential backoff to keep trying to send data
The primary will wait until it receives data from all of its connected secondaries, and then store that data in new locations
This PR also modifies tests accordingly
During an upgrade a primary/secondary will store data at the old locations until the upgrade is complete.
Link to ENT PR: https://github.com/hashicorp/vault-enterprise/pull/7090
files. …
> Send Global Data From Secondary to Primary During Upgrade

- ui/app/adapters/azure/config.js
- ui/app/components/secret-engine/configuration-details.hbs
- ui/app/components/secret-engine/configure-aws.hbs
- ui/app/helpers/mountable-secret-engines.js
- ui/app/helpers/supported-secret-backends.js
- ui/app/models/aws/lease-config.js
- ui/app/models/aws/root-config.js
- ui/app/models/azure/config.js
- ui/app/models/identity/oidc/config.js
- ui/app/models/ssh/ca-config.js
- ui/app/routes/vault/cluster/secrets/backend/configuration/index.js
- ui/app/routes/vault/cluster/secrets/backend/list.js
- ui/app/serializers/azure/config.js
- ui/app/templates/vault/cluster/secrets/backend/configuration/index.hbs
- ui/lib/core/addon/components/secret-list-header.hbs
- ui/lib/core/addon/components/secret-list-header.js
- ui/tests/acceptance/secrets/backend/aws/aws-configuration-test.js
- ui/tests/acceptance/secrets/backend/azure/azure-configuration-test.js
- ui/tests/acceptance/secrets/backend/engines-test.js
- ui/tests/acceptance/settings/mount-secret-backend-test.js
- ui/tests/helpers/secret-engine/secret-engine-helpers.js
- ui/tests/integration/components/secret-engine/configuration-details-test.js
- ui/types/vault/models/azure/config.d.ts
Breaking up the Azure WIF configuration work by separating out configuration details changes into a separate pr. This PR can merge into main with a small amount of short-term conditionals. 
note: no changelog as the final PR will have a changelog for the full feature.
1. Allows Azure to be a "supported secret engine".
2. Shows a Configuration details view, separating out the mount config details from the secret engine details.
3. Shows an empty state for when an engine is not configured.
> Add Azure configuration details view

- changelog/29090.txt
- physical/raft/raft.go
- vault/external_tests/raft/raft_test.go
- vault/external_tests/raftha/raft_ha_test.go
- vault/raft.go
This PR has a raft node write to its stable store when it's been removed. When a raft backend is created, the backend reads this value from the stable store to set the removed flag. If you try to add back a raft node that's been removed to a cluster, it will error (instead of returning a successful status without doing anything).  
files.
> VAULT-31758: Store when a node is removed in the raft stable store

- .github/workflows/benchmark-prevent-performance-degradations.yml
This should make it so that the benchmark performance degradation check only fires on main. It also renames the file to not say hack week in it.
files.
> Run benchmark only on PRs to main (and rename the file)

- vault/logical_system_activity.go
- Disallows querying activity API during upgrade
- Ent PR: https://github.com/hashicorp/vault-enterprise/pull/7148
files.
> Disallow querying of activity APIs during upgrade

- changelog/29114.txt
> Update changelog to clarify fix applies to any database with template variables in `connection_url`

- sdk/logical/events.go
- vault/eventbus/bus.go
Adds a const `path` for indicating the `path` metadata key used for in eventing
> use const for  in relation to vault eventing metadata

- changelog/29024.txt
The PR removes the #29024's unnecessary changelog
files.
> remove changelog #29024

- website/content/docs/platform/k8s/vso/installation.mdx
- [-] **ENT Breakage:** If this PR either 1) removes a public function OR 2) changes the signature
files.
in the PR description, commit message, …
> vso/docs: restore upgrade instructions

- website/content/api-docs/system/health.mdx
This PR adds the new parameters and return values to the docs. The feature code is here: https://github.com/hashicorp/vault/pull/28991
files.
> VAULT-31756: Include removed and HA health in sys/health docs

- website/content/docs/troubleshoot/generate-root-token.mdx
- website/content/docs/troubleshoot/lease-issues.mdx
- website/content/docs/troubleshoot/tune-lease-ttl.mdx
- website/data/docs-nav-data.json
Add troubleshooting docs to 1.16.x branch to support vault associate exam
files.
> Add troubleshooting section to 1.16.x docs for Vault 003 exam

- website/content/docs/upgrading/upgrade-to-1.17.x.mdx
- website/content/partials/known-issues/1_17_secrets-sync-ssrf-private-endpoints.mdx
Manual backport of https://github.com/hashicorp/vault/pull/28746
🔍 [Deploy preview](https://vault-git-docs-upgrade-guide-update-hashicorp.vercel.app/vault/docs/upgrading/upgrade-to-1.17.x#secrets-sync-ssrf-protection-may-block-private-endpoints)
* docs: add Secrets Sync SSRF protection breaking change to 1.17 upgrade guide
The Secrets Sync feature in 1.17.3 introduced SSRF protection that blocks private IP ranges, affecting users accessing secret stores through private endpoints. This adds documentation about the change and available options.
* renamed issue
* referenced secret sync ssrf known issue
* re-ordered secret sync known issue in page
* Hide copy-to-clipboard button on the output example codeblock
---------
of a public function, even if that change is in a …
> [DOCS] Manual cherry pick PR 28746 to 1.17.x doc

- website/content/docs/upgrading/upgrade-to-1.17.x.mdx
- website/content/partials/known-issues/1_17_secrets-sync-ssrf-private-endpoints.mdx
Manual backport of https://github.com/hashicorp/vault/pull/28746
* docs: add Secrets Sync SSRF protection breaking change to 1.17 upgrade guide
The Secrets Sync feature in 1.17.3 introduced SSRF protection that blocks private IP ranges, affecting users accessing secret stores through private endpoints. This adds documentation about the change and available options.
* renamed issue
* referenced secret sync ssrf known issue
* re-ordered secret sync known issue in page
* Hide copy-to-clipboard button on the output example codeblock
---------
files. …
> [DOCS] Manual cherry pick PR 28746 to 1.18.x doc

- vault/identity_store_conflicts.go
- vault/identity_store_structs.go
- vault/identity_store_util.go
This PR introduces a new interface for conflict resolution of duplicate Identity artifacts. The initial implementation just reorganizes the code to use the interface with no behavior change.
The interface is intended to provide a minimal touchpoint for implementing new conflict resolution behavior. Since those changes will also introduce significant testcases, the aim here is to merge the new interface and ensure the current code works as intended (according to existing tests).
files.
description. Also, make sure …
> identity: Introduce ConflictResolver interface

- website/content/docs/secrets/databases/cassandra.mdx
- website/content/docs/secrets/databases/couchbase.mdx
- website/content/docs/secrets/databases/custom.mdx
- website/content/docs/secrets/databases/db2.mdx
- website/content/docs/secrets/databases/hanadb.mdx
- website/content/docs/secrets/databases/index.mdx
- website/content/docs/secrets/databases/influxdb.mdx
- website/content/docs/secrets/databases/mongodb.mdx
- website/content/docs/secrets/databases/mongodbatlas.mdx
- website/content/docs/secrets/databases/mssql.mdx
- website/content/docs/secrets/databases/mysql-maria.mdx
- website/content/docs/secrets/databases/oracle.mdx
- website/content/docs/secrets/databases/postgresql.mdx
- website/content/docs/secrets/databases/redis.mdx
- website/content/docs/secrets/databases/rediselasticache.mdx
- website/content/docs/secrets/databases/redshift.mdx
- website/content/docs/secrets/databases/snowflake.mdx
- Match the `page_title` and the H1 header for consistency
- Use `>-` instead of `|-` for the description so that extra spaces won't be included in the char length
files.
> [DOCS] Match the page_title and H1 header

- vault/activity_log.go
- vault/activity_log_util_common.go
ENT PR: https://github.com/hashicorp/vault-enterprise/pull/7162
files.
> Run Migrations If Migration Worker has not been run #7162

- website/content/docs/platform/mssql/configuration.mdx
- website/content/docs/platform/mssql/installation.mdx
- website/content/docs/platform/mssql/rotation.mdx
- website/content/docs/platform/mssql/troubleshooting.mdx
- website/content/docs/platform/mssql/upgrading.mdx
- website/content/docs/platform/servicenow/configuration.mdx
- website/content/docs/platform/servicenow/index.mdx
- website/content/docs/platform/servicenow/installation.mdx
- website/content/docs/platform/servicenow/troubleshooting.mdx
- Check the `description` matches the content of the doc
- Match the `page_title` and the H1 header for consistency
- Capitalization for consistency
- `ServiceNow credential resolver` should be `ServiceNow Credential Resolver` ([ServiceNow docs](https://store.servicenow.com/sn_appstore_store.do#!/store/application/3ee1c80c1b257010c216ebd56e4bcb33))
files.
> [DOCS] Match the page_title with H1 header

- vault/core.go
- vault/raft.go
If we error here, it causes the vault server to exit. Instead, we should be starting up but in the removed and sealed state.
files.
> Do not error during retry join if the node is removed

- builtin/logical/database/backend.go
- builtin/logical/database/path_config_connection.go
- builtin/logical/database/path_roles.go
Fix a bug where the `self_managed` field was not being evaluated correctly. We use WeakDecode to read the DB config's `connection_details` map and coerce the `self_managed` field to a boolean.
Related to https://github.com/hashicorp/vault/pull/29093
files.
> db: fix skip-import-rotation/rootless integration

- CODEOWNERS
> Add ui team to oidc and jwt codeowners

- website/content/docs/get-started/operations-qs.mdx
- website/data/docs-nav-data.json
- Migrate basic steps from CLI quick start tutorial to ops quick start doc (not all steps were migrated).
- Tried to match flow/language to developer quick start doc
- Update nav to point to foundations tutorial (with tutorial in nav label to be clear)
🔍 [Deploy preview](https://vault-git-vault-retire-cli-quickstart-hashicorp.vercel.app/vault/docs/get-started/operations-qs)
files.
> Add ops quick start, update nav

- CODEOWNERS
Manual backport of https://github.com/hashicorp/vault/pull/29124
> [BACKPORT] Add EDU as approvers for more granular targets

- scripts/go-helper.sh
Various different CI jobs need Go modules in order to build or test
Vault. To speed this up in CI we cache them in Github Actions.
The caching requires downloading all modules first in order to upload
them to the actions cache, which is performed by calling the
`go-mod-download` Make target. This target will iterate over the
directory tree and download Go modules in all directories that include
a `go.mod` file.
There are two small problems with this approach that we resolved with
this PR:
* Our `go-mod-download` target would download modules for all
`go.mod`'s present in the directory tree, regardless of whether or not
they are required to build or test Vault. Only downloading those
required results in slightly smaller caches.
* `tools/pipeline` is intentionally a separate Go module so as …
> go: don't download pipeline modules when caching build modules

- builtin/logical/transit/path_keys_test.go
> Fix key type for hybrid key creation tests

- CHANGELOG.md
Adds a changelog item referencing https://github.com/hashicorp/vault/issues/28670
files.
> update changelog for GH-28670

- changelog/29226.txt
- ui/app/templates/vault/cluster/policies/index.hbs
Update tutorial link for creating a policy. 
Note: Had to get a little hacky to test/render screenshots. Hardcoded list & message if/else conditional in order to display empty state w/ link. Default state is not empty & unable to delete/remove default policy, so not sure when/if empty state is actually rendered.
Before:
After:
"Getting started with policies" link points to new url
files.
> [VAULT-33146] Update tutorial link for creating a policy

- builtin/credential/approle/backend.go
- changelog/28703.txt
Some customers may want additional protection for the secret values of
approle authentication. This change makes them seal wrapped if the mount was
mounted with seal wrap enabled.
files.
> Enable seal wrapping for approle secret storage

- changelog/29145.txt
- vault/activity_log.go
- vault/external_tests/activity_testonly/activity_testonly_test.go
> Revert "Added LocalMount field to Export API"

- builtin/logical/pki/cert_util_test.go
- builtin/logical/pki/issuing/cert_verify.go
- changelog/29255.txt
In order for the Certificate.Verify method to work correctly, the certificates in the CA chain need to be sorted into separate root and intermediate certificate pools.
Add unit tests to verify that name constraints in both the root and intermediate certificates are checked.
files.
> Sort CA chain into root and intermediates on VerifyCertificate.

- ui/tests/acceptance/open-api-path-help-test.js
- ui/tests/helpers/openapi/expected-secret-attrs.js
Fixes open API failures for params added by https://github.com/hashicorp/vault/pull/29245
files.
> UI: Fix open API failures for pki name constraint params

- ui/lib/core/addon/components/policy-example.hbs
- ui/tests/integration/components/policy-example-test.js
What does this PR do? Updates to Policy Modal:
* Update all links to use HDS (Helios Design System) links
* Add link to "get started" with ACL Policies
ACL Policy Modal: NEW Link: "ACL Policies"
ACL Policy Modal: UPDATED (to HDS) Link: "HCL"
ACL Policy Modal: UPDATED (to HDS) Link: "here" (policy capabilities)
Role-Governing Policy Modal: UPDATED (to HDS) Link: "ACL Policies"
Role-Governing Policy Modal: UPDATED (to HDS) Link: "Sentinel"
Role-Governing Policy Modal: UPDATED (to HDS) Link: "here" (sentinel role governing policies)
Endpoint Governing Policy Modal: UPDATED (to HDS) Link: "Sentinel"
Endpoint Governing Policy Modal: UPDATED (to HDS) Link: "properties"
Endpoint Governing Policy Modal: UPDATED (to HDS) Link: "here" (sentinel endpoint governing policies)
of a public function, …
> [VAULT-33207] Update Policy Modal links to use HDS, add ACL Policies "get started" link

- ui/lib/core/addon/components/policy-example.hbs
What does this PR do? This is a followup PR to add `isHrefExternal` attribute to external HDS links in the Policy Modal
Original PR: https://github.com/hashicorp/vault/pull/29254
ACL Policies: HCL Link
Endpoint Governing Policies: Sentinel Link
files.
> [VAULT-33207] Update Policy Modal to add isHrefExternal to External Links

- changelog/29176.txt
- vault/barrier_aes_gcm.go
- vault/barrier_aes_gcm_test.go
- Upon requesting to rotate the barrier key if we overflow the term uint32, fail the rotation.
files.
> Prevent barrier term overflow on rotation

- CHANGELOG.md
Addresses VAULT-33223
Corrects the changelog to reflect that the feature was not implemented for Oracle DB yet.
files.
> Correcting the changelog

- ui/tests/helpers/openapi/expected-secret-attrs.js
I fixed the typo in the [go file
](https://github.com/hashicorp/vault/pull/29263/files#diff-22663f59eb7343dfccf79ce2731482c07b5d867d2a8942a7b81270d34a9c6f91R422)
but forgot to update the ui openapi files (which only run on enterprise)
files.
> Fix openapi test typo

- ui/app/adapters/gcp/config.js
- ui/app/components/secret-engine/configuration-details.hbs
- ui/app/helpers/mountable-secret-engines.js
- ui/app/helpers/supported-secret-backends.js
- ui/app/models/gcp/config.js
- ui/app/routes/vault/cluster/secrets/backend/configuration/index.js
- ui/app/serializers/gcp/config.js
- ui/app/templates/vault/cluster/secrets/backend/configuration/index.hbs
- ui/tests/acceptance/secrets/backend/gcp/gcp-configuration-test.js
- ui/tests/helpers/secret-engine/secret-engine-helpers.js
- ui/tests/integration/components/secret-engine/configuration-details-test.js
This PR adds the GCP configuration details view, separating out mount details in a toggle. It does not yet allow users to edit or create the configuration.
> Add GCP configuration details

- vault/activity_log_testing_util.go
> Revert "add fragment locks to GetActiveLocalFragment and GetActiveFragment"

- builtin/logical/pki/cert_util_test.go
- builtin/logical/transit/backend_ce.go
- builtin/logical/transit/path_export_ce_test.go
- builtin/logical/transit/path_export_test.go
- builtin/logical/transit/path_import.go
- builtin/logical/transit/path_keys.go
- sdk/helper/keysutil/policy.go
- sdk/helper/keysutil/policy_ce.go
- sdk/helper/keysutil/policy_test.go
Supporting changes for key types for ML-DSA/Hybrid Ed25519.
files.
> CE side changes to key policy engine for ML-DSA/Hybrid support

- builtin/logical/database/rotation_test.go
Attempt to fix a data race for the queue tick interval on the logical.BackendConfig map. I was unable to repro the data race locally, but I think reinitializing the BackendConfig for each value under test should fix the issue.
Failure: https://github.com/hashicorp/vault-enterprise/actions/runs/12584472353/job/35075729417
Test data race output:
```
Write at 0x00c00cedad80 by goroutine 29135:
runtime.mapassign_faststr()
/home/runner/actions-runner/_work/_tool/go/1.23.3/x64/src/runtime/map_faststr.go:223 +0x0
github.com/hashicorp/vault/builtin/logical/database.TestQueueTickIntervalKeyConfig()
/home/runner/actions-runner/_work/vault-enterprise/vault-enterprise/builtin/logical/database/rotation_test.go:1045 +0x308
testing.tRunner() …
```
> fix db test data race for queue tick interval

- vault/activity_log.go
- vault/activity_log_test.go
- vault/activity_log_util_common.go
- vault/activity_log_util_common_test.go
> Revert "Store tokens in local storage paths"

- website/content/docs/enterprise/license/utilization-reporting.mdx
This section of the docs implies a way for customers to use and ingest the automated reporting, which has confused customers. I think it's clearer if we simply remove it.
files.
> Remove potentially misleading part of automated reporting docs

- changelog/29290.txt
- ui/lib/kv/addon/components/kv-data-fields.hbs
Removing the ability to download a row of kv secret data (added by #20431) until we can implement this functionality in a way that can be gated by policy or admin configuration (requested by #23981)
Users can still copy or wrap secret data.
files.
> UI: Remove kv data download button

- helper/testhelpers/testhelpers.go
- physical/raft/testing.go
- vault/external_tests/raft/raft_test.go
- vault/external_tests/raftha/raft_ha_test.go
Updates the tests to fix occasional flakes.
Adds a helper method for an enterprise test. Enterprise PR: https://github.com/hashicorp/vault-enterprise/pull/7199
files.
> fixes for flakes in raft removed tests

- builtin/logical/database/rotation_test.go
Fix a test diff in CE vs Ent.
files.
> test: fix ce/ent diff

- go.mod
- go.sum
This PR updates the `raft-autopilot` dependency from v0.2.0 to v0.3.0. We are doing this to pull in a fix for an issue described in VAULT-21282, which was fixed in https://github.com/hashicorp/raft-autopilot/pull/55. This change intends to fix an issue with Autopilot redundancy zones, so the changelog will be added on the ENT side.
files.
> [VAULT-21282] Bump raft-autopilot dependency to v0.3.0

- changelog/29293.txt
- ui/app/adapters/ldap/library.js
- ui/app/adapters/ldap/role.js
- ui/app/models/ldap/library.js
- ui/app/models/ldap/role.js
- ui/lib/ldap/addon/components/page/libraries.hbs
- ui/lib/ldap/addon/components/page/libraries.ts
- ui/lib/ldap/addon/components/page/roles.hbs
- ui/lib/ldap/addon/components/page/roles.ts
- ui/lib/ldap/addon/routes.js
- ui/lib/ldap/addon/routes/libraries/library/check-out.ts
- ui/lib/ldap/addon/routes/libraries/library/details.ts
- ui/lib/ldap/addon/routes/libraries/library/edit.ts
- ui/lib/ldap/addon/routes/libraries/subdirectory.ts
- ui/lib/ldap/addon/routes/roles/role/credentials.ts
- ui/lib/ldap/addon/routes/roles/role/details.ts
- ui/lib/ldap/addon/routes/roles/role/edit.ts
- ui/lib/ldap/addon/routes/roles/subdirectory.ts
- ui/lib/ldap/addon/templates/libraries/subdirectory.hbs
- ui/lib/ldap/addon/utils/ldap-breadcrumbs.ts
- ui/mirage/handlers/ldap.js
- ui/mirage/scenarios/ldap.js
- ui/tests/acceptance/secrets/backend/ldap/libraries-test.js
- ui/tests/helpers/ldap/ldap-selectors.ts
- ui/tests/integration/components/ldap/page/libraries-test.js
- ui/tests/unit/adapters/ldap/role-test.js
- ui/tests/unit/utils/ldap-breadcrumbs-test.js
- ui/types/vault/models/ldap/library.d.ts
- ui/types/vault/models/ldap/role.d.ts
This PR adds hierarchical role navigation to the UI for LDAP libariries which was added to the CLI in 1.17 ([Hierarchical Paths](https://developer.hashicorp.com/vault/docs/secrets/ldap#hierarchical-paths)). 
Follow-on to https://github.com/hashicorp/vault/pull/28824
https://github.com/user-attachments/assets/85bffbde-62e8-471d-bb1e-9edb8ed7e848
files.
> UI: LDAP Hierarchical Library names

- builtin/logical/database/backend.go
- builtin/logical/database/backend_test.go
- builtin/logical/database/path_config_connection.go
- builtin/logical/database/path_config_connection_ce.go
- builtin/logical/database/path_roles.go
- builtin/logical/database/path_roles_ce.go
- builtin/logical/database/path_rotate_credentials.go
- builtin/logical/database/rotation.go
- builtin/logical/database/rotation_test.go
Manual backport into `release/1.18.x` of https://github.com/hashicorp/vault/pull/29093, https://github.com/hashicorp/vault/pull/29202, https://github.com/hashicorp/vault/pull/29283, and https://github.com/hashicorp/vault/pull/29307
files.
> backport release/1.18.x: db skip auto import rotation

- scripts/copywrite-exceptions.sh
This PR updates copywrite-exceptions script to exclude *_ent.go which are not intended for public use
files.
> update copywrite exceptions to exclude *_ent.go

- scripts/copywrite-exceptions.sh
This PR updates copywrite-exceptions.sh exclude *_ent_test.go
files.
> exclude *_ent_test.go from copywrite-exceptions.sh

- vault/logical_system_activation_flags.go
- vault/logical_system_activation_flags_test.go
Add identity cleanup activation flag. 
files.
> Add identity cleanup activation flag

- changelog/29334.txt
- go.mod
- go.sum
The keyring library has an outstanding bug that causes zombie dbus-daemon processes on each execution. This only happens on certain systems. Vault has an indirect dependency on keyring via gosnowflake.  This replace is a stopgap measure until either gosnowflake or keyring addresses the issue.
See https://github.com/99designs/keyring/issues/103 and https://github.com/snowflakedb/gosnowflake/issues/1183
Support has published 5 workarounds for this issue here: [Vault 1.13.7+ and Linux DBus leftover processes](https://support.hashicorp.com/hc/en-us/articles/20562543907859-Vault-1-13-7-and-Linux-DBus-leftover-processes). This has also been reported in GitHub: https://github.com/hashicorp/vault/issues/22560. Additionally, some customers have reported that none of the workarounds resolve the …
> replace keyring dependency to address zombie dbus-daemons processes

- vault/logical_system_activation_flags_test.go
Mark CE tests with a CE-specific build flag so we can run separate tests on enterprise.
files.
> Add build flag for CE-specific activation flag tests

- physical/raft/raft.go
- vault/external_tests/raftha/raft_ha_test.go
Exits the checker. This prevents log spamming.
files.
> Exit raft removed checker if raft isn't initialized

- ui/app/models/aws/lease-config.js
- ui/app/models/aws/root-config.js
- ui/app/models/gcp/config.js
- ui/app/models/ssh/ca-config.js
- ui/tests/acceptance/secrets/backend/aws/aws-configuration-test.js
- ui/tests/acceptance/secrets/backend/azure/azure-configuration-test.js
- ui/tests/acceptance/secrets/backend/gcp/gcp-configuration-test.js
- ui/tests/helpers/secret-engine/secret-engine-helpers.js
- ui/tests/integration/components/secret-engine/configuration-details-test.js
- ui/tests/integration/components/secret-engine/configure-aws-test.js
- ui/tests/integration/components/secret-engine/configure-azure-test.js
Pulling out some changes from a larger PR #29323. These changes are more clean up 🧹 related and distract a little from the core changes to that pr.
Specifically:
* Cleaned up AWS models to match the pattern of Azure and GCP. All the changes are naming changes. No functional changes.
* Using my new helper `string-array-to-camel` I was able to greatly simplify the method `expectedConfigKeys` which I use heavily in testing WIF engines. Before, this method was handling all sorts of options ex: `expectedConfigKeys("aws-root-create")` or ``expectedConfigKeys("aws-root-create-wif")`. To simplify this method and clarify the potential keys, I pulled all the key options out. Now each engine has three options: generic, account or wif. And these key selectors change depending on if I'm viewing …
> Prep work for creating one WIF configuration component

- website/content/api-docs/secret/databases/index.mdx
- website/content/docs/secrets/databases/index.mdx
Documentation for https://github.com/hashicorp/vault/pull/29093 which adds support to the DB engine for skipping auto rotation of static roles on import (VAULT-31657).
files.
> docs: DB skip auto import rotation

- changelog/29356.txt
- helper/activationflags/activation_flags.go
- helper/identity/identity.go
- vault/identity_store.go
- vault/identity_store_conflicts.go
- vault/identity_store_conflicts_test.go
- vault/identity_store_entities.go
- vault/identity_store_test.go
- vault/identity_store_util.go
- vault/logical_system_activation_flags.go
- vault/logical_system_activation_flags_test.go
This PR introduces a new type of conflict resolution for duplicate Entities and Groups. This provides a way of preventing Vault from entering case-sensitive mode, which is the current behavior for any kind of duplicate.
Renames append the conflicting identity artifact's UUID to its name and updates a metadata field to indicate the pre-existing artifact's UUID.
The feature is gated by the `force-identity-deduplication activation` flag.
In order to maintain consistent behavior between the reporting resolver and the rename operation, we need to adjust the behavior of generated reports. Previously, they intentionally preserved existing Group merge determinism, wherein the last MemDB update would win and all others would be renamed. This approach is more complicated for the rename resolver, …
> identity: Resolve conflicts with rename

- website/content/docs/secrets/kv/kv-v2/upgrade.mdx
This PR fixes a typo/logical error in the KV v1 to KV v2 upgrade docs.
https://developer.hashicorp.com/vault/docs/secrets/kv/kv-v2/upgrade
The docs describe how the paths in KV v1 policies have to be migrated and prefixed with `/data` but the example does not show that, instead the engine is changed.
files.
> docs: fixed typo in kv v1 upgrade docs

- changelog/29371.txt
- physical/dynamodb/dynamodb.go
- physical/dynamodb/dynamodb_test.go
- website/content/docs/configuration/storage/dynamodb.mdx
Fixes Issue https://github.com/hashicorp/vault/issues/25114.
This PR introduces support for creating the DynamoDB table that Vault would use with PAY_PER_REQUEST billing mode, and introduces support for allowing Vault to modify the billing mode and read/write capacity of the table if it already exists. This is done with new environment variables, and the current default behaviour is left unchanged (no-ops if the table already exists).
cc @schavis, @VioletHynes
> [Storage/DynamoDB] Let vault modify dynamodb tables

- website/content/partials/telemetry-metrics/vault/identity/entity/active/monthly.mdx
- website/content/partials/telemetry-metrics/vault/identity/entity/active/partial_month.mdx
- website/content/partials/telemetry-metrics/vault/identity/entity/active/reporting_period.mdx
- website/content/partials/telemetry-metrics/vault/identity/entity/count.mdx
- website/content/partials/telemetry-metrics/vault/identity/entity/creation.mdx
As reported in https://github.com/hashicorp/vault/issues/29330, these metrics are not per namespace, and in general that's not a pattern that we think is good for metrics (if they were namespace cardinality, we'd want to fix it so they weren't).
This fixes the language suggesting they're per namespace, and also some of the tables were incorrectly formatted, so I autoformatted them.
files.
> Fix misleading comments about namespaces in docs

- ui/lib/ldap/addon/components/page/library/details/accounts.ts
- ui/mirage/handlers/ldap.js
- ui/mirage/models/ldap-account-status.js
- ui/mirage/scenarios/ldap.js
- ui/tests/acceptance/secrets/backend/ldap/libraries-test.js
- ui/tests/acceptance/secrets/backend/ldap/overview-test.js
- ui/tests/acceptance/secrets/backend/ldap/roles-test.js
- ui/tests/integration/components/ldap/page/library/details/accounts-test.js
Manual backport of https://github.com/hashicorp/vault/pull/28432
files.
> Backport 1.18.x - UI: Fix LDAP Mirage Handler

- website/content/docs/concepts/events.mdx
Manually backport event doc changes to 1.17.x release branch
> update docs for eventing (#28950)

- buf.yaml
This PR ignores  `sdk/plugin/pb/system_view_service_ent.proto` in `buf.yaml` to fix protobuf linter
files.
> ignore system view service ent in buf linter

- changelog/29293.txt
- ui/app/adapters/ldap/library.js
- ui/app/adapters/ldap/role.js
- ui/app/models/ldap/library.js
- ui/app/models/ldap/role.js
- ui/lib/ldap/addon/components/page/libraries.hbs
- ui/lib/ldap/addon/components/page/libraries.ts
- ui/lib/ldap/addon/components/page/roles.hbs
- ui/lib/ldap/addon/components/page/roles.ts
- ui/lib/ldap/addon/routes.js
- ui/lib/ldap/addon/routes/libraries/library/check-out.ts
- ui/lib/ldap/addon/routes/libraries/library/details.ts
- ui/lib/ldap/addon/routes/libraries/library/edit.ts
- ui/lib/ldap/addon/routes/libraries/subdirectory.ts
- ui/lib/ldap/addon/routes/roles/role/credentials.ts
- ui/lib/ldap/addon/routes/roles/role/details.ts
- ui/lib/ldap/addon/routes/roles/role/edit.ts
- ui/lib/ldap/addon/routes/roles/subdirectory.ts
- ui/lib/ldap/addon/templates/libraries/subdirectory.hbs
- ui/lib/ldap/addon/utils/ldap-breadcrumbs.ts
- ui/mirage/handlers/ldap.js
- ui/mirage/scenarios/ldap.js
- ui/tests/acceptance/secrets/backend/ldap/libraries-test.js
- ui/tests/helpers/ldap/ldap-selectors.ts
- ui/tests/integration/components/ldap/page/libraries-test.js
- ui/tests/unit/adapters/ldap/role-test.js
- ui/tests/unit/utils/ldap-breadcrumbs-test.js
- ui/types/vault/models/ldap/library.d.ts
- ui/types/vault/models/ldap/role.d.ts
Manual backport https://github.com/hashicorp/vault/pull/29293
files.
> Backport 1.18.x UI: LDAP Hierarchical Library names (#29293)

- .github/workflows/plugin-update.yml
This PR updates the `plugin-update` GHA to  use the elevated GitHub token in the `Update Enterprise-only plugin` step to `go get` dependencies from private repos.
<details><summary>Local testing</summary>
Tested the `plugin-update` GHA on `vault-enterprise` with these changes https://github.com/hashicorp/vault-enterprise/pull/7299 and manually triggering the GHA at https://github.com/hashicorp/vault-enterprise/actions/workflows/plugin-update.yml.
Before this change: https://github.com/hashicorp/vault-enterprise/actions/runs/12919423225/job/36029907171. `plugin-update` workflow against `main` was failing on the `Update Enterprise-only plugin` step with the following error:
```
go: github.com/hashicorp/go-census/v2@v2.1.0: reading github.com/hashicorp/go-census/go.mod at revision v2.1.0: …
```
> use elevated github token in plugin-update gha ent step

- go.mod
- go.sum
does not affect vault but addresses CVE-2025-0377 to reduce scanner noise
files.
> update go-slug to 0.16.3

- changelog/29326.txt
- vault/identity_store_util.go
This PR has 3 performance improvements in the `loadEntities` function:
1. Batch memDB operations into groups of 1024. Previously, we were creating a new transaction per entity.
2. Cache the bucket reads from the local alias storage packer and use those when loading entities
3. Deserialize the entities concurrently 
I ran [benchmarks](https://github.com/hashicorp/vault-enterprise/compare/miagilepner/exp-faster-identity-load?expand=1) using:
* 200k total entities
* Each entity had 1 local alias and 1 non-local alias
I got the number 1024 by batching entities together across buckets (which this branch **does not** implement, but I used for benchmarking so that I wouldn't need to create millions of entities). These batches are counted by adding the number of entities and the number of aliases …
> VAULT-31907: Entity loading speedup

- go.mod
- go.sum
- physical/alicloudoss/alicloudoss.go
- physical/azure/azure.go
- physical/cockroachdb/cockroachdb.go
- physical/cockroachdb/cockroachdb_ha.go
- physical/consul/consul.go
- physical/couchdb/couchdb.go
- physical/dynamodb/dynamodb.go
- physical/etcd/etcd3.go
- physical/gcs/gcs.go
- physical/manta/manta.go
- physical/manta/manta_test.go
- physical/mssql/mssql.go
- physical/mysql/mysql.go
- physical/oci/oci.go
- physical/postgresql/postgresql.go
- physical/raft/raft.go
- physical/s3/s3.go
- physical/spanner/spanner.go
- physical/swift/swift.go
- sdk/go.mod
- sdk/go.sum
- sdk/physical/file/file.go
- sdk/physical/inmem/inmem.go
- sdk/physical/inmem/transactions_test.go
- sdk/physical/physical.go
The `PermitPool` type is being moved to go-secure-stdlib to be shared with Boundary.
> physical: use permitpool from go-secure-stdlib

- builtin/logical/database/path_roles.go
Ensure we return a success response on static role create/update
files.
> db: return success response on static role create/update

- .github/actions/build-vault/action.yml
- .github/actions/changed-files/action.yml
- .github/actions/checkout/action.yml
- .github/actions/create-dynamic-config/action.yml
- .github/actions/run-apupgrade-tests/action.yml
- .github/actions/set-up-go/action.yml
- .github/actions/set-up-pipeline/action.yml
- .github/workflows/actionlint.yml
- .github/workflows/benchmark-prevent-performance-degradations.yml
- .github/workflows/build-artifacts-ce.yml
- .github/workflows/build.yml
- .github/workflows/changelog-checker.yml
- .github/workflows/ci.yml
- .github/workflows/code-checker.yml
- .github/workflows/copywrite.yml
- .github/workflows/enos-lint.yml
- .github/workflows/enos-release-testing-oss.yml
- .github/workflows/oss.yml
- .github/workflows/plugin-update-check.yml
- .github/workflows/plugin-update.yml
- .github/workflows/security-scan.yml
- .github/workflows/stable-website.yaml
- .github/workflows/test-ci-bootstrap.yml
- .github/workflows/test-ci-cleanup.yml
- .github/workflows/test-enos-scenario-ui.yml
- .github/workflows/test-go.yml
- .github/workflows/test-run-acc-tests-for-path.yml
- .github/workflows/test-run-enos-scenario-containers.yml
- .github/workflows/test-run-enos-scenario-matrix.yml
- .github/workflows/test-run-enos-scenario.yml
The genesis of this PR is updating our cache action due to older actions being shut down[0]. While not mentioned in the changelog, the migration guide does call out versions <3.4.0 or <4.2.0 as too old.[1]
Since I was updating cache I went ahead and updated minor versions of all our actions.
[0]: https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
[1]: https://github.com/actions/cache/discussions/1510
files.
in the PR description, commit …
> actions: pin to the latest approved workflows

- ui/tests/helpers/openapi/expected-auth-attrs.js
Adds `enableSamaccountnameLogin` param to the openAPI tests, also double check the field displayed in the UI (no code changes necessary for this as it's a purely openAPI derived model).
files.
> OpenAPI LDAP config update: Add enableSamaccountnameLogin param

- website/content/docs/commands/token/renew.mdx
Add missing doc with `accessor` command option for `vault token renew` command. The command option seems to have existed since Vault 1.3, we're just missing a reference to it on the docs.
files.
> add docs for missing accessor flag in token renew command

- ui/tests/helpers/openapi/expected-secret-attrs.js
For now adding this to stop the backend test from failing. However, waiting to hear Design's thoughts about the best way and where to display this on the ui. 
Backend param was added in PR #29369
> Add serialNumberSource to OpenAPI test (not added to form)

- changelog/29432.txt
- vault/activity_log.go
- vault/activity_log_test.go
- vault/core.go
- vault/core_test.go
Deleted namespace client counts is now shown when queried from admin namespace.
Jira: https://hashicorp.atlassian.net/browse/VAULT-33413
Admin namespace is set using administrative_namespace_path in configuration file. Included test that reloads config with different administrative_namespace_path and verifies that only the right admin path has deleted namespaces.
Approved ENT: https://github.com/hashicorp/vault-enterprise/pull/7328
files. …
> Deleted namespace client counts is now shown when queried from admin namespace CE changes

- sdk/helper/certutil/certutil_test.go
- sdk/helper/certutil/helpers.go
- website/content/api-docs/secret/pki/index.mdx
This PR fixes two issues with PR https://github.com/hashicorp/vault/pull/29245:
- Use PermittedDNSDomains parameter when signing certificates.
- Add missing name constraints extension docs for PKI root/generate.
files.
> Fix missing permitted_dns_domains parameter when signing certificates

- website/content/api-docs/secret/pki/index.mdx
Update the PKI role api-docs for the new field `serial_number_source` that was added within https://github.com/hashicorp/vault/pull/29369
files.
> Document new serial_number_source PKI role field

- website/content/docs/concepts/policies.mdx
> Fix reference to "vault policies" command

- website/content/api-docs/system/internal-counters.mdx
"Techn preview" should be "tech preview"
files.
> Fix tech preview typo in export API docs

- website/content/docs/concepts/policies.mdx
> [v1.17] Fix reference to "vault policies" command

- website/content/docs/concepts/policies.mdx
> [v1.16] Fix reference to "vault policies" command

- physical/raft/raft.go
A non-removed raft node would always print this error log line, which could be confusing for users. Switch the log line to debug level.
files.
> Fix log level of when starting a raft node

- vault/identity_store.go
- vault/identity_store_injector.go
- vault/identity_store_injector_testonly.go
Add testonly endpoints for Identity testing. These create objects directly in storage. Should **only** be used for testing.
files.
> Add testonly endpoints for Identity testing

- website/content/docs/upgrading/upgrade-to-1.16.x.mdx
- website/content/docs/upgrading/upgrade-to-1.17.x.mdx
- website/content/docs/upgrading/upgrade-to-1.18.x.mdx
- website/content/partials/known-issues/database-skip-static-role-rotation.mdx
Add known issues for db and ldap secrets engine. I will have to manually backport this to the 1.18.x branch since currently these files are out-of-sync with main on that branch.
files.
> docs: db and ldap secrets engine known issues

- vault/activity_log_test.go
Updated includeInResponse test to check for admin namespaces
Jira: https://hashicorp.atlassian.net/browse/VAULT-33413
files.
> Extra test for vault-33413

- changelog/29423.txt
- ui/app/adapters/gcp/config.js
- ui/app/components/secret-engine/configuration-details.hbs
- ui/app/helpers/mountable-secret-engines.js
- ui/app/models/gcp/config.js
- ui/app/routes/vault/cluster/secrets/backend/configuration/edit.ts
- ui/app/templates/vault/cluster/secrets/backend/configuration/index.hbs
- ui/tests/acceptance/secrets/backend/aws/aws-configuration-test.js
- ui/tests/acceptance/secrets/backend/azure/azure-configuration-test.js
- ui/tests/acceptance/secrets/backend/gcp/gcp-configuration-test.js
- ui/tests/helpers/general-selectors.ts
- ui/tests/helpers/secret-engine/secret-engine-helpers.js
- ui/tests/integration/components/secret-engine/configuration-details-test.js
- ui/tests/integration/components/secret-engine/configure-wif-test.js
* Adds the ability to configure GCP secret engine. 
* For enterprise users, allows them to configure WIF
Walk through of the changes
https://github.com/user-attachments/assets/cca57d1c-0860-4bf3-95b3-bdd109be123b
> Add GCP secret engine configuration Create/Edit views

- helper/activationflags/activation_flags.go
- sdk/framework/backend.go
- vault/core.go
- vault/identity_store.go
- vault/identity_store_conflicts.go
- vault/identity_store_structs.go
- vault/identity_store_test.go
- vault/identity_store_util.go
- vault/logical_system.go
- vault/logical_system_activation_flags.go
This PR introduces some changes to the way activation flags are
processed in Vault.
Rather than reaching into subsystems and modifying
state from the activationflags package, each plugin can now register its
own ActivationFunc. Updates to activation flags now trigger the the
feature's ActivationFunc, which can encapsulate the associated
subsystem state.
We include a few bugfixes and minor cosmetic changes, like updates to
log lines and godocs.
Enterprise PR: hashicorp/vault-enterprise#7359
Resolves VAULT-33427, VAULT-33615
files.
in the PR description, commit message, …
> identity: Introduce ActivationFunc for managing feature state

- ui/app/models/pki/role.js
- ui/tests/integration/components/pki/pki-role-form-test.js
Adds `serial_number_source` implemented by https://github.com/hashicorp/vault/pull/29369 to the UI "Additional subject fields" section of the PKI role form
files.
> UI: Adds `serial_number_source` to pki role form

- changelog/29470.txt
- http/handler.go
- vault/eventbus/bus.go
- vault/eventbus/bus_test.go
These are the CE changes and changelog for https://github.com/hashicorp/vault-enterprise/pull/7185
- …
> CE changes for VAULT-33018

- changelog/29416.txt
- ui/app/services/auth.js
- ui/tests/acceptance/auth-test.js
- ui/tests/helpers/auth/auth-form-selectors.ts
- ui/tests/helpers/auth/auth-helpers.ts
✅ enterprise tests passed
The UI makes a lot of inferences based on the shape of the auth response we receive. The UI relies on the `namespace_path` from the auth response to set the user's root namespace which is then used to calculate capabilities.
https://github.com/hashicorp/vault/blob/dcdbacd281052a7baf898f1129ce6801ae930d22/ui/app/adapters/capabilities.js#L16-L30
`renew-self` does not return `namespace_path`, so this PR manually adds it in the `renew()` method, if it exists. The auth code is challenging to parse and is prone to regressions. I double checked that this change does not affect the bug the previous PR was solving that introduced these code changes: https://github.com/hashicorp/vault/pull/24168/files
This fixes a bug where clicking `Renew token` would incorrectly gate …
> UI: Fix token renewal breaking policy checks

- website/content/docs/upgrading/upgrade-to-1.16.x.mdx
- website/content/docs/upgrading/upgrade-to-1.17.x.mdx
- website/content/docs/upgrading/upgrade-to-1.18.x.mdx
> docs: fix include syntax in upgrade guides

- website/content/docs/upgrading/upgrade-to-1.16.x.mdx
- website/content/docs/upgrading/upgrade-to-1.17.x.mdx
- website/content/docs/upgrading/upgrade-to-1.18.x.mdx
manual backport of https://github.com/hashicorp/vault/pull/29487
files.
> backport: 1.18.x: docs: fix include syntax in upgrade guides

- website/content/partials/known-issues/aws-auth-external-id.mdx
- website/content/partials/known-issues/duplicate-hsm-key.mdx
- website/content/partials/known-issues/sync-activation-flags-cache-not-updated.mdx
Fix build, missing 2 files
files.
> docs: backport: 1.18.x: fix build

- ui/tests/helpers/auth/auth-form-selectors.ts
- ui/tests/helpers/auth/auth-helpers.ts
Enterprise tests passed ✅ 
Backports some helpers that were used in tests for https://github.com/hashicorp/vault/pull/29416 
files.
> UI: backport auth test helpers

- ui/app/components/secret-engine/configure-wif.ts
- ui/app/models/azure/config.js
- ui/app/models/gcp/config.js
- ui/tests/acceptance/secrets/backend/azure/azure-configuration-test.js
- ui/tests/helpers/secret-engine/secret-engine-helpers.js
- ui/tests/integration/components/secret-engine/configure-wif-test.js
**TLDR:** `Root password TTL` has to be moved from an Azure account access type to a generic one that can bet set be set alongside wif and non-wif attributes. See original PR [#29047](https://github.com/hashicorp/vault/pull/29047) description's, this change adds `Root password TTL` to both columns, like `Environment`. 
Context: `Root password TTL` is only ever used when the user rotates their root credentials (not currently supported in this work), and is used to set an expiration date on the newly created credential. So a user could theoretically use WIF to set up Azure first (thereby using a zero-secret configuration for Vault), and then rotate root credentials to then start leveraging the `Root password TTL` to generate a new Client Secret value for future use.
**Note**: I updated the …
> Clean up on Azure configuration

- vault/core.go
- vault/core_test.go
- vault/identity_store_conflicts.go
- vault/identity_store_conflicts_test.go
- vault/identity_store_test.go
- vault/identity_store_test_stubs_oss.go
- vault/identity_store_util.go
This PR ensures that automatic de-duplication is consistent across all
nodes in an Enterprise cluster by persisting conflict resolution on the
active node. 
This logic to prevents Enterprise clusters from accidentally reverting
any conflict resolution after it's performed.
The PR includes some modifications to deterministic reload testing,
since they now have the side-effect of persistence on active nodes, as
well as tests for consistency in the face of storagePacker bucket
invalidation.
Enterprise PR: https://github.com/hashicorp/vault-enterprise/pull/7343
Resolves: VAULT-33555, VAULT-33504
break any tests. Sometimes ENT only tests rely …
> identity (CE): Persist conflict resolution after rename

- website/content/api-docs/system/storage/raftautosnapshots.mdx
- Ensure new parameters are present for 1.18.x backport per [SPE-998](https://hashicorp.atlassian.net/browse/SPE-998)
- Update heading
files.
[SPE-998]: https://hashicorp.atlassian.net/browse/SPE-998?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Docs: API: Raft snapshot configuration updates

- changelog/29506.txt
- vault/barrier_aes_gcm.go
> Undo additions to the barrier encryption count if persisting those encryptions fails

- ui/lib/core/addon/components/kv-object-editor.js
Fix jsdoc typo so docs compile
files.
> fix jsdoc typo

- vault/auth.go
- vault/mount.go
- vault/mount_util.go
This PRs allows Enterprise Vault to set external plugin config
Related ENT PR: https://github.com/hashicorp/vault-enterprise/pull/7269
Ticket: [VAULT-33300](https://hashicorp.atlassian.net/browse/VAULT-33300)
RFC: https://go.hashi.co/rfc/vlt-337
files.
[VAULT-33300]: https://hashicorp.atlassian.net/browse/VAULT-33300?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> add stubs oss for entSetExternalPluginConfig()

- website/content/api-docs/system/storage/raftautosnapshots.mdx
This is manual backport of #29508 for [SPE-998](https://hashicorp.atlassian.net/browse/SPE-998) to the release/1.18.x branch since the backport assistant failed.
files.
[SPE-998]: https://hashicorp.atlassian.net/browse/SPE-998?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Docs: API: Manual backport of API docs raft auto snapshot updates

- sdk/logical/system_view.go
- sdk/logical/system_view_stubs_oss.go
This PR adds EntStaticSystemView to StaticSystemView and its CE stubs
Related ENT PR: https://github.com/hashicorp/vault-enterprise/pull/7269
Ticket: [VAULT-33300](https://hashicorp.atlassian.net/browse/VAULT-33300)
RFC: https://go.hashi.co/rfc/vlt-337
files.
[VAULT-33300]: https://hashicorp.atlassian.net/browse/VAULT-33300?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
> add EntStaticSystemView to StaticSystemView and its ce stubs

- website/content/api-docs/secret/pki/index.mdx
Add a missing parameter `signature_bits` to the Generate Root PKI API documentation.  
files.
> Add missing parameter signature_bits to the generate root PKI API docs

- ui/app/models/config-ui/message.js
- ui/lib/config-ui/addon/components/messages/page/create-and-edit.js
- ui/tests/integration/components/config-ui/messages/page/create-and-edit-test.js
This replaces `new Date()` with `timestamp.now()` which can be more reliable stubbed in tests. See https://github.com/hashicorp/vault/issues/19521 for more context
✅ enterprise tests (because of timezone weirdness, double checked enterprise tests by [opening a PR to the enterprise](https://github.com/hashicorp/vault-enterprise/actions/runs/13207666265/job/36874612485) repo)
files.
> UI: Use timestamp.now() in custom messages

- changelog/29551.txt
- go.mod
- go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/13266874403
> Update vault-plugin-secrets-openldap to v0.14.5

- builtin/credential/aws/path_config_client.go
- builtin/logical/aws/path_config_root.go
- builtin/logical/database/backend.go
- builtin/logical/database/backend_test.go
- builtin/logical/database/path_config_connection.go
- builtin/logical/database/path_rotate_credentials.go
- changelog/29497.txt
- changelog/29557.txt
- sdk/helper/automatedrotationutil/fields.go
- sdk/helper/automatedrotationutil/fields_test.go
- sdk/rotation/rotation_job.go
Adds automated root rotation support to DB Secrets
Other changes:
- wrap error if storage entry fails but rotation manager succeeded in AWS Auth and Secrets
- ensure schedule can be set without window
> Add automated root rotation support to DB Secrets

- .release/versions.hcl
This PR adds 1.19.x to the versions file to allow for backports.
files.
> add 1.19.x to versions

- vault/identity_store_conflicts.go
- vault/identity_store_conflicts_test.go
- vault/identity_store_group_aliases.go
- vault/identity_store_test.go
- vault/identity_store_util.go
Fixes a bug introduced in #29483. That PR included an attempt to prevent duplicate groups with different IDs being created by a race condition, however that fix interferes in a subtle way when duplicate groups (causes by historical bugs, like the one it was trying to fix) are already present in storage. It turns out that that code was not actually necessary for the fix - removing it doesn't make any of the test cases added in https://github.com/hashicorp/vault-enterprise/pull/6990 fail - I ran them over 40 times each locally with no failures.
This PR also fixes up the URL in the reports since the docs were moved around.
Fixes [VAULT-33879](https://hashicorp.atlassian.net/browse/VAULT-33879). This also fixes a bunch of potential new issues in the case that duplicate groups already exist - …
> Fix issue caused by group-creation forwarding.

- ui/app/serializers/aws/root-config.js
- ui/tests/acceptance/secrets/backend/aws/aws-configuration-test.js
When I originally wrote the aws-configuration acceptance test, `maxRetries` would return -1 and be scrubbed from the details view by the adapter. 
1. With [pr #29497 ](https://github.com/hashicorp/vault/pull/29497/files#diff-11906daf04096f16c364abff4761df97c3b879915152cee7f14a03e1f74dc32eR192) maxRetries now returns `0`. The intention of this PR was
>AWS Secrets persists entries between writes. This means that if you had previously set a value, it will remain in the config even if you do not provide it in a following update.
I informed the backend that even on a fresh cluster with no AWS mounts the first AWS mount returns `0` for the `maxRetries` config value. Pushing this fix through to stop test failures, but if this was not their intention then you'll likely see another pr to address …
> Fix failing AWS configuration test

- website/content/docs/enterprise/automated-upgrades.mdx
Adds a note about Autopilot server cleanup for [SPE-27](https://hashicorp.atlassian.net/browse/SPE-27)
files.
[SPE-27]: https://hashicorp.atlassian.net/browse/SPE-27?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Docs: Automatic cluster upgrades Autopilot note

- website/content/docs/internals/integrated-storage.mdx
Mention scaling window and Autopilot wrt dead_server_last_contract_threshold for [SPE-994](https://hashicorp.atlassian.net/browse/SPE-994)
files.
[SPE-994]: https://hashicorp.atlassian.net/browse/SPE-994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Docs: add a note for quorum size scaling

- changelog/29583.txt
- go.mod
- go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/13293444327
> Update vault-plugin-secrets-mongodbatlas to v0.14.0

- changelog/29562.txt
- vault/activity_log.go
- vault/activity_log_test.go
- vault/core.go
- vault/core_util.go
- vault/external_tests/activity_testonly/activity_testonly_test.go
The export API will return different results than the sys/counters API when using a date that is in the middle of the month; to fix this, we should normalize the start_date parameter to the start of the month as is done in the sys/counters API.
files.
> VAULT-33603: normalize start time in export api

- changelog/29542.txt
- go.mod
- go.sum
backport vault-plugin-database-elasticsearch update to the 1.19.x release branch
> Update vault-plugin-database-elasticsearch to v0.17.0 (#29542)

- changelog/29594.txt
- go.mod
- go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/13296968507
> Update vault-plugin-database-redis-elasticache to v0.6.0

- changelog/29597.txt
- go.mod
- go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/13297977745
> Update vault-plugin-database-redis to v0.5.0

- changelog/29598.txt
- go.mod
- go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/13298028710
> Update vault-plugin-secrets-gcp to v0.21.0

- builtin/logical/pki/cert_util.go
- builtin/logical/pki/issuing/signing_utils.go
- builtin/logical/pki/parsing/asn1.go
- builtin/logical/pki/parsing/asn1_test.go
- helper/pkcs7/decrypt.go
- helper/pkcs7/encrypt.go
- helper/pkcs7/encrypt_test.go
- helper/pkcs7/pkcs7.go
This adds some underlining work within the PKI engine and PKCS7 library to support the Enterprise PKI SCEP work that is ongoing. 
- PKCS7 library
- Allow per call encryption selection instead of updating a global variable
- Add 3DES encryption support
- PKI
- Move around existing code within the issuing package out of the main pki package so other pki sub-packages can use it
- Add a helper ASN.1 method that will mimic asn1.Unmarshal but also error out on trailing data.
files. …
> Add underlining support for the PKI Enterprise SCEP work

- changelog/29612.txt
- go.mod
- go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/13314432818
> Update vault-plugin-secrets-gcpkms to v0.20.0

- changelog/29613.txt
- go.mod
- go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/13314431382
> Update vault-plugin-auth-alicloud to v0.20.0

- ui/tests/helpers/openapi/expected-auth-attrs.js
These fields were added from PR #29401
**Note:** there is a known behavior change where if a user submits a default gcp auth config they hit an API error. This is because the backend sees the default of `0` as a value, and both `rotation_window` and `rotation_period` cannot be set. This is something the backend will be addressing in a different pr. 
Confirmed the fields have been added to the auth form.
* Note this form is huge and a literal copy/paste of the openApi so it's not very pretty nor helpful.
files. …
> Fix OpenApi test for GCP Auth

- changelog/29618.txt
- vault/eventbus/bus.go
- vault/eventbus/bus_test.go
- vault/eventbus/filter.go
- vault/eventbus/filter_test.go
CE changes and changelog for https://github.com/hashicorp/vault-enterprise/pull/7400
- [-] **ENT Breakage:** If this PR either 1) removes a public function OR 2) changes the signature
break any tests. Sometimes ENT only tests rely on …
> CE changes for VAULT-33452

- ui/tests/helpers/openapi/expected-auth-attrs.js
Very similar to PR #29610, update OpenAPI params for Azure auth method.
Confirmed new attrs show:
Note: Azure does not hit the same config issue that GCP does.
> Fix OpenAPI test Azure Auth

- builtin/credential/aws/path_config_client.go
- builtin/logical/aws/path_config_root.go
- builtin/logical/database/path_config_connection.go
Only logs a certain error if Rotation Manager operations were performed. Moves the log into the if block as it was incorrectly placed before.
> Fix rotation manager plugin logs in case of storage errors

- builtin/logical/aws/backend.go
- builtin/logical/aws/client.go
- builtin/logical/aws/client_ce.go
- builtin/logical/aws/iam_policies.go
- builtin/logical/aws/path_config_rotate_root.go
- builtin/logical/aws/path_static_roles.go
- builtin/logical/aws/path_static_roles_ce.go
- builtin/logical/aws/path_static_roles_test.go
- builtin/logical/aws/path_user.go
- builtin/logical/aws/rotation.go
- builtin/logical/aws/rotation_test.go
- builtin/logical/aws/secret_access_keys.go
- website/content/api-docs/secret/aws.mdx
This is the CE component of adding cross account management of static roles for AWS Secrets. 
ENT PR: https://github.com/hashicorp/vault-enterprise/pull/7353
files.
> Add support for cross account management of static roles in AWS Secrets

- vault/testing.go
This PR exposes NetworkLayer on a TestClusterCore via a convenience method for testing purposes 😁 
This change was made on main in #28991, but never backported. I need it for a test on an ENT 1.18 branch.
files.
> [VAULT-21282] Expose NetworkLayer on a TestClusterCore via a convenience method for testing purposes

- ui/app/components/policy-form.hbs
- ui/tests/integration/components/policy-form-test.js
Noticed that the json specific message `You can use Alt+Tab (Option+Tab on MacOS) in the code editor to skip to the next field.` showed when I was not on the json editor view.
BEFORE
AFTER
* The message about using Alt+tab is only relevant if you're viewing the code editor.
> 🧹 on policy upload file view

- changelog/29680.txt
- command/agent/config/config.go
- command/agent/config/config_test.go
- command/agent/config/test-fixtures/config-template-min-no-auth.hcl
This change fixes https://github.com/hashicorp/vault/issues/29654, where giving the vault agent multiple config files can cause the resulting merged config to be incorrect when `template_config` is set in one of the config files. Specifically, when the first config file provided to the vault agent has a `template_config` stanza, and the second one doesn't, the merged config only has default `template_config` values. This is because we started creating a `TemplateConfig` struct even for configs that didn't specify it, to ensure that the `MaxConnectionsPerHost` default was being honored (https://github.com/hashicorp/vault/pull/24989). But we were still doing a nil check for `TemplateConfig` during the merge process to determine if it needed to be updated, so we were overwriting it with the …
> Fix bug with merging vault agent configs that set template_config

- website/content/docs/secrets/kv/kv-v2/random-string.mdx
This PR adds missing `**`.
🔍 [Deploy preview](https://vault-e12ceq2a7-hashicorp.vercel.app/vault/docs/secrets/kv/kv-v2/random-string)
files.
> [DOCS] Add missing '**' to bold text

- changelog/29677.txt
- ui/app/components/tools/wrap.hbs
- ui/app/components/tools/wrap.js
- ui/tests/integration/components/tools/wrap-test.js
This PR adds a KV view to the wrap tool based off the existing pattern when creating KV secrets. This resolves #28579. The default view is the still the JSON editor, but can be toggled between the two views while retaining input.
This also shifts from disabling the wrap button when there are errors to displaying a warning message while leaving the button enabled. 
Previous:
Current:
Current with Warning:
files.
> UI: Add KV view for wrap tool

- CHANGELOG.md
Update CHANGELOG.md for 1.18.5, 1.17.12, 1.16.16
files.
> Update CHANGELOG.md for 1.18.5, 1.17.12, 1.16.16

- changelog/_go-ver-1190.txt
Fix up a formatting issue within the Go changelog on 1.19.
files.
> Fix formatting issue in Go changelog on 1.19

- changelog/_go-ver-1183.txt
- changelog/_go-ver-1185.txt
Fix up a formatting issue within some of the Go changelogs on 1.18.
files.
> Fix formatting issue in Go changelogs on 1.18

- changelog/_go-ver-1190.txt
- changelog/_go-ver-1200.txt
Rename the 1.20.0 Go changelog to the proper name and fix a formatting error in another Go changelog
files.
> Fix some formatting issues for Go changelogs

- .github/actions/metadata/action.yml
Fix pull request label metadata when triggered by `push` event types. We now use Github's `associatedPullRequests()` connection on the `Commit` associated with the SHA to resolve the labels.
files.
> VAULT-33693 actions: fix push event PR labels

- sdk/plugin/grpc_system.go
Resolve a conflict between when we handle durations as nanoseconds vs. seconds.
> Update GRPC functions to send rotation window and period as seconds explicitly

- ui/tests/helpers/openapi/expected-auth-attrs.js
Changes the `rotationPeriod` and `rotationWindow` for all three configs from a `number` to `ttl`.
Azure:
GCP:
LDAP:
> UI: update openapi for auth-config/azure, auth-config/ldap and auth-config/gcp

- ui/package.json
- ui/tests/acceptance/enterprise-kmip-test.js
- ui/yarn.lock
Note: This PR was cherrypicked from https://github.com/hashicorp/vault/pull/29558. Library updates were separated from the code changes (https://github.com/hashicorp/vault/pull/29720) to make it easier to backport the library updates if needed in the future.
files.
> [VAULT-33968] UI: Update HDS

- ui/package.json
- ui/yarn.lock
Bumps the `devDependency` `dompurify` up a minor version from 3.0.3 to 3.2.4. This dependency was first added in pr #20235. And while that PR didn't specify backporting, we did later in pr #26369.
Note: the backport for 1.18.x is probably only an ent backport, but label has not yet been created, stay tuned.
> UI: dependency bump for dompurify

- website/content/api-docs/secret/pki/issuance.mdx
- website/content/docs/secrets/pki/cmpv2.mdx
Document new PKI CMPv2 configuration field disabled_validations.
files.
> Document new PKI CMPv2 configuration field disabled_validations

- builtin/logical/aws/path_config_root.go
- builtin/logical/aws/path_config_root_test.go
In #29497, we added distinction between a create and update operation in AWS Secrets, which was causing default values for `max_retries` to be returned as `0` instead of the previous expected value of `-1`. This was because the `CreateOperation` was not properly supported, and each operation was treated as an update which messed with the defaults.
This PR correctly distinguishes between the Create and Update operations, and also includes a test to ensure the legacy behavior of the `max_retries` parameter is still enforced.
> secrets/aws: ensure `max_retries` default value is unchanged

- changelog/29736.txt
- go.mod
- go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/13556786942
> Update vault-plugin-auth-gcp to v0.20.1

- changelog/29747.txt
- go.mod
- go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/13572852288
> Update vault-plugin-secrets-gcp to v0.21.1

- website/content/docs/platform/k8s/injector/annotations.mdx
Updates documentation for the Vault Agent injector [v1.6.2](https://github.com/hashicorp/vault-k8s/releases/tag/v1.6.2) release (just bumps the default Vault Agent version).
Preview link:
https://vault-git-docs-vault-33856vault-k8s-v162-hashicorp.vercel.app/vault/docs/platform/k8s/injector/annotations#vault-hashicorp-com-agent-image
- [-] **ENT Breakage:** If this PR either 1) removes a …
> docs/vault-k8s: update for v1.6.2 release

- ui/tests/acceptance/secrets/backend/aws/aws-configuration-test.js
In 1.19.0 work, the default value for the AWS root-config parameter `max_retries` changed from -1 to 0. I updated my test to reflect this change, but I was aware of an existing ticket to revert it to the original default. That ticket has been completed, and the default has been restored to its expected value. As a result, I’ve updated my test accordingly.
See PR #29737, which implements the fix
files.
> Update default expected for AWS max retries

- builtin/credential/ldap/backend_test.go
- scripts/go-helper.sh
- sdk/database/dbplugin/plugin.go
- sdk/database/dbplugin/v5/grpc_client.go
- sdk/database/dbplugin/v5/grpc_database_plugin_oss.go
- tools/pipeline/internal/cmd/github_list_runs.go
- tools/pipeline/internal/pkg/generate/enos_dynamic_config_test.go
`gosimports` is the preferred style for module imports and it is enforced via CI. I've found that things often manage to drift so I've taken the liberty to update our pre-commit hook to verify our imports formatting before a change is committed.
Along with updating the formatting helper I've also run `make fmt` to resolve any formatting drift that managed to make it into the codebase.
files.
> fmt: check gosimports during pre-commit hooks

- vault/identity_store.go
- vault/identity_store_structs.go
- vault/identity_store_test.go
- vault/identity_store_util.go
- vault/logical_system_activation_flags.go
Previously identity cleanup was running with the context of the activation request, which would time out for large workloads, resulting in bad failure states. This PR moves the ActivationFunc call to its own goroutine/background Context, so it can proceed uninterrupted. 
Enterprise PR: hashicorp/vault-enterprise#7551
Resolves: VAULT-34330
files.
> identity: Perform runtime cleanup in goroutine

- website/content/docs/concepts/events.mdx
Updates the note about client redirect for event subscriptions, since as of Vault 1.19.0-rc1+ent, the redirect is no longer necessary in a cluster with performance standby nodes.
Preview link:
* https://vault-git-docs-vault-33453update-119-event-docs-hashicorp.vercel.app/vault/docs/concepts/events#subscribing-to-event-notifications
- [-] **ENT Breakage:** If this PR either 1) removes a …
> docs/events: update note about client redirect for 1.19

- ui/package.json
- ui/yarn.lock
Was trying to tackle third party dependency updates:
-  `path-to-regexp` bumping from 0.1.11 to 0.1.12
-  `nanoid` bumping to 3.3.8
I got these updates for free by deleting and re-installing `yarn.lock`, but then I broke the app. To fix the app, I then had to bump `@ember/test-waiters` to the next major version 3->4 🫠.
Breaking changes on the ember/test-waiters bumps do not seem to have any impact on us. Here is their [changelog](https://github.com/emberjs/ember-test-waiters/releases/tag/v4.0.0-%40ember%2Ftest-waiters).
This is not going to be fun to backport.... …
> UI: Dependency updates for third-party: nanoid and path-to-regexp

- ui/app/styles/utils/swagger.scss
- ui/lib/open-api-explorer/addon/components/swagger-ui.js
- ui/mirage/factories/open-api-explorer.js
- ui/tests/integration/components/open-api-explorer/swagger-ui-test.js
In preparation for use of the OpenAPI generated client, this PR adds the `operationId` from the spec to the API Explorer when viewed in the development environment. A plugin was added to the swagger UI config to camelize the value so that it matches the method names in the generated client since the value is dasherized in the spec.
files.
> [UI] Display Camelized Operation ID in API Explorer

- changelog/29792.txt
- go.mod
- go.sum
Fixes Azure auth for both managed and workload identities
files.
> Update Azure wrapper to address VAULT-29717

- website/content/docs/release-notes/1.16.1.mdx
- website/content/docs/release-notes/1.17.0.mdx
- website/content/docs/release-notes/1.18.0.mdx
- website/content/docs/upgrading/upgrade-to-1.16.x.mdx
- website/content/docs/upgrading/upgrade-to-1.17.x.mdx
- website/content/docs/upgrading/upgrade-to-1.18.x.mdx
- website/content/partials/known-issues/azure-unseal-regression.mdx
Add known issue for Azure credential failure regression in the most recent versions of Vault.
files.
> Add known issue for Azure credential failure

- website/content/docs/sync/gcpsm.mdx
Document Customer-managed Encryption Keys for GCP secrets sync.
Add note about the two required GCP APIs to be enabled.
files.
> sync/gcp: document CMEK and CloudResourceManager API requirement

- website/content/api-docs/system/activation-flags.mdx
- website/content/api-docs/system/secrets-sync.mdx
- website/content/docs/sync/azurekv.mdx
- website/content/docs/sync/index.mdx
- website/content/partials/sync-ssrf-fields.mdx
Documents 4 new fields for all secrets sync destinations:
`disable_strict_networking`
`allowed_ipv4_addresses`
`allowed_ipv6_addresses`
`allowed_ports`
Adds doc text to describe when and why to set these
files.
> sync: document new allowlist fields and disable field for SSRF-strict networking

- website/content/api-docs/system/secrets-sync.mdx
Fix a typo and anchor link
files.
> Fix small typo/anchor link in GCP sync API docs section

- website/content/docs/platform/k8s/vso/api-reference.mdx
- website/content/docs/platform/k8s/vso/helm.mdx
- website/content/docs/platform/k8s/vso/installation.mdx
- website/content/docs/platform/k8s/vso/openshift.mdx
Update the VSO docs for 0.10.0. All documentation was auto generated from the VSO code.
files.
>  Update VSO docs for v0.10.0

- enos/enos-dev-scenario-pr-replication.hcl
- enos/enos-dev-scenario-single-cluster.hcl
Now that we have full tutorials for the [single cluster](https://eng-handbook.hashicorp.services/internal-tools/enos/tutorial-vault-dev-scenario-single-cluster/) and [PR replication](https://eng-handbook.hashicorp.services/internal-tools/enos/tutorial-vault-dev-scenario-pr-replication/) dev scenarios, we can remove the extended instructions for how to run the scenario from the scenario `description`.
files.
> [Enos] Update descriptions for dev scenarios

- .github/actions/build-vault/action.yml
- scripts/ci-helper.sh
Install and configure an s390x C toolchain when building Vault editions that need CGO on s390x. x86_64 and aarch64 need no special handling as it is assumed that those binaries are compiled on runners with matching architecture.
CE counterpart to https://github.com/hashicorp/vault-enterprise/pull/7586
files.
> VAULT-34477: Add s390x multilib compiler to build-vault action

- vault/identity_store_test.go
- vault/identity_store_util.go
This test adds some synchronization for a goroutine in test assertions.
Enterprise PR: https://github.com/hashicorp/vault-enterprise/pull/7591
files.
> identity: fix a racy deduplication test assertion

- CHANGELOG.md
1.16.17 does not have any changelog entries this time, as there were only a few minor dependency version bumps since the last minor release about a week ago, which don't typically have changelog entries.
> Changelog for 1.19.0, 1.18.6, 1.17.13, and 1.16.17

- website/content/docs/release-notes/1.19.0.mdx
- website/content/docs/upgrading/upgrade-to-1.19.x.mdx
Adds documentation around case sensitivity changes in the RADIUS auth plugin.
files.
- [x ] **Jira:** If this change has an associated Jira, it's referenced either
> (DOCS) VAULT-31525 Added note for case sensitivity changes in the RADIUS auth plugin

- api/sys_utilization_report.go
This just has the API changes. CE component of https://github.com/hashicorp/vault-enterprise/pull/7585
files.
> VAULT-34126 CE part

- builtin/logical/pki/path_tidy.go
- builtin/logical/pki/path_tidy_test.go
- changelog/29852.txt
Fix a bug when writing auto tidy config field that prevents field tidy_cmpv2_nonce_store from being set.
files.
> Fix bug when writing auto tidy config field tidy_cmpv2_nonce_store

- ui/package.json
- ui/yarn.lock
Manual backport of PR #29784
For this, I didn't do a cherry pick, but instead deleted yarn lock, and bumped the test waiters and then ran yarn install. Backporting yarn.locks just doesn't seem like the right idea.
> Backport 1.19.x: bump test-watiers and reinstall yarn lock

- website/content/docs/secrets/aws.mdx
Fix docs to indicate we are enabling the aws secrets engine, not the gcp secret engine.
files.
> docs: enable aws secrets engine, not gcp

- command/server/config.go
- command/server/config_test_helpers.go
- command/server/test-fixtures/raft_retry_join_attr.hcl
- command/server/test-fixtures/raft_retry_join_block.hcl
- command/server/test-fixtures/raft_retry_join_mixed.hcl
`go-discover` supports being configured with some configuration strings that include double-quotes, backslashes and escapes. As such, we now use its own parser when normalizing `auto_join` config that may have addresses.
Fixes: https://github.com/hashicorp/vault/issues/29863
files.
> VAULT-34581: retry_join: handle escapes in `auto_join` config

- website/content/api-docs/secret/aws.mdx
- website/content/docs/secrets/aws.mdx
> Updating docs to include new assume role fields

- vault/core_metrics.go
- vault/mount.go
CE Changes for https://github.com/hashicorp/vault-enterprise/pull/7608
files.
> VAULT-34593 CE changes

- builtin/logical/aws/backend.go
- builtin/logical/aws/path_static_roles.go
- builtin/logical/aws/path_static_roles_test.go
- changelog/29842.txt
- website/content/api-docs/secret/aws.mdx
This PR adds a LIST endpoint to aws/static-roles/
files.
> Add LIST endpoint to AWS Secrets static roles

- enos/modules/target_ec2_instances/main.tf
Default to Encrypted EBS Volumes for new EC2 instances.
files.
> SECVULN-18432: Default to Encrypted Root Volumes

- changelog/29917.txt
- command/server.go
This fixes a bug with how vault handles logging to the log_file in configuration. 
Initially, `ServerCommand.run` sets up a gated writer to standard error, which is passed through configureLogging to `loghelper.Setup`. This setup combines the gated writer with a file (log_file) using a multiwriter, ensuring logs go to both destinations. Later in `server.Run`, vault flushes the gated writer by calling the function `ResetOutputWithFlush`. Unfortunately, this replaces the InterceptLogger’s output with a single writer that logs only to standard error. Some logs still get written to both destinations. This is likely because vault defines some subloggers (like core) before the flush occurs. Naming a sublogger creates a copy of the underlying writer, which remains connected to the original …
> Ensure logger writes to log_file by preventing overwrite of InterceptLogger's output

- ui/package.json
- ui/yarn.lock
There were a number of warnings output from `ember-cli-typescript` during the build that complained about the `ember-cli-babel` version.
This was fixed in the [5.3.0 release of ember-cli-typescript](https://github.com/typed-ember/ember-cli-typescript/releases/tag/v5.3.0) (the title says it all 😁). We don't directly use `ember-cli-typescript` but a number of dependencies do and since some have not been updated in recent years they may no longer be maintained. By using yarn to resolve the version to at least `5.3.0` we get rid of the warning and there doesn't appear to be any issues with the build when forcing the dependencies to use the newer version.
applying the patch for this PR to the ENT repo and running …
> [UI] Resolve ember-cli-typescript to 5.3.0

- CODEOWNERS
- api/auth/cert/cert.go
- api/auth/cert/cert_test.go
- api/auth/cert/go.mod
- api/auth/cert/go.sum
The new certificate client api introduced within https://github.com/hashicorp/vault/pull/29546 had some limitations, while it worked well, due to it using just the address from the passed in api.client, a lot of the properties that could be set weren't being honored unlike the other client APIs when communicating with Vault. 
This is the list of changes being performed, note that we have changed the API removing the TLS options as we now delegate that to passed in client assuming it has been setup correctly. 
- Use the passed in Vault API client to perform the connection
- This provides namespace support, retry behaviors and uses the existing secret parsing logic instead of re-implementing it
- Secondly this means the end-user using this API, doesn't have to setup a Vault API client with …
> Rework certificate authentication client api

- vault/identity_store_injector_testonly.go
- vault/identity_store_test.go
- vault/identity_store_util.go
Fixes a couple of bugs found while manual testing.
1. The recent change to persist alias merges accidentally created a situation where we run a second pass at loading entities with rename active without clearing the DB. This means that we end up appending the UUID twice!
2. We made the activation flag async, but we didn't move the reset of the DB or locking which means that
a. The actual loading of entities is not done with a lock held!
b. there could be a gap between clearing the identity store and reloading it where we are not holding the lock and requests that come in would get errors like entity not found etc. 
No changelog needed as these are unreleased bugs.
It's unforunate at least the first one wasn't caught by existing tests so we should add something or add assertions to make …
> Fix double-rename bug and locking issues

- ui/package.json
- ui/yarn.lock
Bumps the babel devDependency and dependency "@babel/core": "^7.26.10".
> Bump @babel/core to 7.26.10 in devDependency AND dependency

- ui/package.json
- ui/yarn.lock
Manual backport of PR #29937
files.
> Backport 1.19.x: Manual backport of bump babel/core

- enos/enos-scenario-seal-ha.hcl
backport VAULT-34555 fix seal_ha failure to release/1.19.x
files.
> backport VAULT-34555 fix seal_ha failure to release/1.19.x

- api/sys_utilization_report.go
- vault/core_metrics.go
CE side of https://github.com/hashicorp/vault-enterprise/pull/7622
files.
> VAULT-34541 CE changes

- ui/lib/core/addon/components/form-field.hbs
- ui/lib/core/addon/components/form-field.js
This PR lays the groundwork for migrating (one by one) the different input types handled within the `FormField` component to their equivalent HDS components (eg. we will start with `textarea`, `password`, generic `select`, generic `input`, etc)
For now the PR doesn't contain actual code migration, there are just placeholder comments. If you want to have an idea of what the migrated code would look like (approximately) have a look at this explorations/spike that I did, that led to this "official" PR: https://github.com/hashicorp/vault/pull/29943/files
The goal of this PR is to validate the approach with the Vault UI Engineers and see if this is a direction they approve, gather their feedback, and have them do a code review to see if things could be done in a different …
> [VAULT-34728] UI: prepare `FormField` template logic for migration to HDS components

- ui/lib/core/addon/components/form-field.hbs
- ui/lib/core/addon/components/form-field.js
- moved template logic for `checkboxList` of `FilterInput` under the `isHdsField` block
- added handling of `label/helpText/subText/docLink` + validation errors message for `checkboxList`
- moved `validationWarning` block out of the conditional so it can serve both HDS and non-HDS use cases 
Jira ticket: https://hashicorp.atlassian.net/browse/VAULT-34792
files.
> [VAULT-34792] UI: refactor `FormField` template code to move `checkboxList` under the newly added HDS block

- ui/package.json
- ui/scripts/start-vault.js
- ui/testem.js
At some point in the recent past, an update to Chrome(Mac) has caused tests to fail locally when running in headless mode. Specifically, on HDS modal dismiss [the attached listener on the close event](https://github.com/hashicorp/design-system/blob/%40hashicorp/design-system-components%404.13.0/packages/components/src/components/hds/modal/index.ts#L186-L196) is not triggering which results in a pending test waiter that causes a timeout. Interestingly enough, this is not an issue with the linux version of Chrome as witnessed in passing CI runs and on my local linux machine.
This PR updates the `start-vault` script to conditionally add the `--launch` flag to the testing command that will run the tests in headless Firefox instead when the environment is not CI and the server flag is not …
> [UI] Local Testing Workaround

- .github/workflows/plugin-update.yml
When doing the first ENT release for this plugin ahead of Vault 1.19 for [VAULT-31444](https://hashicorp.atlassian.net/browse/VAULT-31444), the automated plugin-update workflow kept failing with permission issues so we had to manually create plugin-update PRs for KMSE into vault-enterprise like https://github.com/hashicorp/vault-enterprise/pull/7478 and https://github.com/hashicorp/vault-enterprise/pull/7530.
This PR fixes the plugin-update workflow for our first ENT-only plugin, [vault-plugin-secrets-keymgmt](https://github.com/hashicorp/vault-plugin-secrets-keymgmt) (and presumably other ENT-only plugins in private repositories down the line) by setting the `GOPRIVATE` env var.
Tested by running the plugin-update GHA against https://github.com/hashicorp/vault-enterprise/pull/7646: …
> set GOPRIVATE in plugin-update gha ent step

- ui/lib/core/addon/components/filter-input.hbs
- ui/lib/core/addon/components/filter-input.ts
- ui/lib/core/addon/components/kv-suggestion-input.hbs
- ui/lib/ldap/addon/components/page/libraries.hbs
- ui/lib/ldap/addon/components/page/roles.hbs
- ui/lib/sync/addon/components/secrets/page/destinations.hbs
- ui/lib/sync/addon/components/secrets/page/destinations/destination/sync.hbs
- ui/tests/integration/components/filter-input-test.js
- in the process we have made a few structural changes:
- removed the `<div class="control >` wrapper (not needed anymore)
- removed the autofocus feature (has negative accessibility implications, see [thread](https://hashicorp.slack.com/archives/C05DGFEBCP2/p1742246879189389))
Jira ticket: https://hashicorp.atlassian.net/browse/VAULT-34704
A few video recordings of the updates UIs:
- https://github.com/user-attachments/assets/1415e3ae-ecfd-4747-9471-9bab0a951adf
- https://github.com/user-attachments/assets/0782dbcb-c118-43a2-b62c-a365dda16482
- https://github.com/user-attachments/assets/332f4045-3444-4886-8420-5a878bacdfc7
- https://github.com/user-attachments/assets/041c337b-edbb-485b-a3aa-0068e58364f7
of a public function, even if that change is in a CE file, …
> [VAULT-34704] UI: update `FilterInput` component to use `Hds::Form::TextInput`

- enos/modules/target_ec2_instances/main.tf
Enforces IMDSv2 on AWS instances.
files.
> [enos] SECVULN-18910: Enforce IMDSv2 on AWS instances

- changelog/29970.txt
- go.mod
- go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/13973668555
> Update vault-plugin-secrets-gcp to v0.21.2

- changelog/29978.txt
- vault/plugincatalog/plugin_catalog_stubs_oss.go
When running Vault via systemd and `PrivateTmp=on`, the Vault register command fails, even when setting the `VAULT_PLUGIN_TMPDIR` environment variable:
```
ubuntu@ip-172-25-19-239:~$ vault plugin register -sha256="${SHA256}" -oci_image=hashicorp/vault-plugin-secrets-kv secret my-kv-container
WARNING! VAULT_ADDR and -address unset. Defaulting to https://127.0.0.1:8200/.
Error registering plugin my-kv-container: Error making API request.
URL: PUT https://127.0.0.1:8200/v1/sys/plugins/catalog/secret/my-kv-container
Code: 400. Errors:
* unable to run plugin: 1 error occurred:
* error creating container: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /tmp/plugin-dir3781501367
*
```
This change makes it so that the register flow respects the …
> bugfix: vault register should respect tmpdir

- enos/modules/install_packages/scripts/synchronize-repos.sh
In the `synchronize-repos.sh` script we use `cloud-init status --wait` to ensure that `cloud-init` is not running when we attempt to sync the repositories. This is all fine and good except that modern versions of `cloud-init` can exit with 2 if they encounter an error but recover. Since we're running the script with `-e` and don't gate the exit with an expression the script will fail rather than recover when we receive that code.
Ought to fix: https://github.com/hashicorp/vault-enterprise/actions/runs/13976392635/job/39133116883
files.
in the PR description, commit …
> enos(install_packages): handle cloud-init exit code 2 and subshells

- ui/app/config/environment.d.ts
- ui/app/lib/local-storage.ts
- ui/app/lib/memory-storage.ts
- ui/app/services/api.ts
- ui/tests/unit/services/api-test.js
- ui/types/vault/api.d.ts
- ui/types/vault/services/auth.d.ts
- ui/types/vault/services/control-group.d.ts
- ui/types/vault/services/namespace.d.ts
This PR adds an API service to configure and expose the `vault-client-typescript` API's. The middleware was ported from the application adapter to preserve the global request behavior as much as possible. 
files.
> [UI] API Service

- ui/.eslintignore
- ui/.prettierignore
- ui/tsconfig.json
While the generated API client lives in Vault UI, treat it as if it were a third party dependency (it will be soonish 😁) and ignore it from linters. 
files.
> [UI] Lint Ignore API Client

- ui/lib/core/addon/components/form-field.hbs
- ui/lib/core/addon/components/form-field.js
- updated logic in `isHdsFormField` of `FormField` to include the generic `select` use case 
- moved template logic for generic `select` in `FormField` under the `isHdsField` block 
Jira ticket: https://hashicorp.atlassian.net/browse/VAULT-34742
A few examples of before vs after:
**Before**:
**After**:
---
**Before**:
**After**:
👉 In this case the `@helpText` instead of being hidden behind a tooltip, is exposed as field's helper text (better for accessibility)
files.
description. Also, make …
> [VAULT-34742] UI: move the generic `select` block in `FormField` under the HDS block

- changelog/29976.txt
- go.mod
- go.sum
This PR updates the hashicorp/raft library version from 1.7.1 to 1.7.3 to add extra logging on a leader node when it opens and sends a snapshot to a follower. We are doing this in order to make debugging and supporting Vault easier.
Full changes here: https://github.com/hashicorp/raft/compare/v1.7.1...v1.7.3 
files.
> [VAULT-29278] Update hashicorp/raft library from v1.7.1 to v1.7.3 to add logging on leader node when opening and sending a raft snapshot to a follower

- ui/lib/core/addon/components/form-field.hbs
- ui/lib/core/addon/components/form-field.js
- updated logic in `isHdsFormField` of `FormField` to include the `password` use case 
- added large comments as visual code delimiters
- I hope you don't mind, but my eyes were twitching with all those `if/else/elseif` and these help to quickly scan the area where one is
- moved template logic for `password` in `FormField` under the `isHdsField` block  
Jira ticket: https://hashicorp.atlassian.net/browse/VAULT-34729
files.
description. Also, make sure the changelog is in this PR, _not_ in …
> [VAULT-34729] UI: move the `password` block in `FormField` under the HDS block

- go.mod
- go.sum
Resolve an advisory by bumping jwt to the latest patch versions. 
files.
> go: resolve GHSA-mh63-6h87-95cp by bumping github.com/golang-jwt/jwt/v*

- ui/app/components/tools/wrap.ts
- ui/app/utils/api-error-message.ts
- ui/app/utils/error-message.js
- ui/package.json
- ui/tests/integration/components/tools/wrap-test.js
- ui/tests/unit/utils/api-error-message-test.js
- ui/types/vault/api.d.ts
- ui/yarn.lock
This PR converts the `tools/wrap` component to `ts` and updates the wrap request to use the api service. Additionally, types were added for codemirror and an `api-error-message` util was created to handle api errors. 
files.
> [UI] Ember Data Migration - Tools Wrap Component

- go.mod
- go.sum
Bumps `go-git` version to v5.14.0 as part of VAULT-34474
files.
> Bump go-git version

- ui/app/components/dashboard/overview.ts
- ui/app/services/namespace.js
- ui/tests/integration/components/dashboard/overview-test.js
- ui/types/vault/services/namespace.d.ts
- Fixes an edge case where the client count card would appear for children named `admin/`
✅ enterprise passed
files.
> UI: Updates the namespace service to explicitly check for the HVD managed admin namespace

- website/content/partials/known-issues/aws-fallback-sts.mdx
Add a brief known issue line for the STS region mismatch issue. Hopefully this won't be in-tree for long.
> Add known issue for sts region/sts endpoint mismatch bug

- enos/modules/install_packages/scripts/synchronize-repos.sh
`$?` in bash is wonky. When you evaluate an expression in an `if` statement the `$?` variable is only set to the actual exit value in blocks scoped in the statement. Therefore, since we rely on it in synchronize-repos we have to evaluate the rest of the function in a scope of that statement.
files.
> enos(cloud-init): fix synchronize-repos

- vault/identity_store.go
- vault/identity_store_util.go
This PR fixes a legitimate data race caused by two separate goroutines accessing `(*IdentityStore).disableLowerCasedNames` concurrently without locking.
This was found by the race detector in CI.
Enterprise PR: https://github.com/hashicorp/vault-enterprise/pull/7678
files.
> usage (CE): Fix data race on IdentityStore metric

- .github/actions/install-external-tools/action.yml
- .github/actions/set-up-buf/action.yml
- .github/actions/set-up-gofumpt/action.yml
- .github/actions/set-up-gosimports/action.yml
- .github/actions/set-up-gotestsum/action.yml
- .github/actions/set-up-misspell/action.yml
- .github/actions/set-up-shfmt/action.yml
- .github/actions/set-up-sqlc/action.yml
- .github/actions/set-up-staticcheck/action.yml
- sdk/go.mod
- sdk/go.sum
- tools/tools.sh
Pin the CI tool versions in 1.19.x to match main. A manual backport of https://github.com/hashicorp/vault/pull/29665
This should resolve our proto delta check failing on 1.19.
files.
> Pin CI tool versions 1.19.x (#29665)

- builtin/logical/aws/client.go
- changelog/29982.txt
As of today, WIF is unusable in certain environments that make use of AWS Profiles or environment variables for other purposes, such as using KMS or HVD. This is due to the AWS Secrets Engine picking up the shared credentials in the environment, and adding multiple providers when generating its credential chain.
This PR explicitly disables Shared Credential and Environment Variable Providers if WIF parameters are explicitly set as part of the root AWS Config. If WIF is not being used, environment / shared credentials can be used as expected.
> secrets/aws: disable environment and shared credential providers when using WIF

- ui/app/components/tools/random.ts
This PR converts the `tools/random` component to `ts` and updates it to use the api service.
files.
> [UI] Ember Data Migration - Tools Random Component

- ui/api-client/dist/esm/runtime.d.ts
- ui/api-client/dist/esm/runtime.js
- ui/api-client/dist/runtime.d.ts
- ui/api-client/dist/runtime.js
- ui/api-client/src/runtime.ts
- ui/app/components/tools/unwrap.ts
- ui/app/services/api.ts
- ui/tests/unit/services/api-test.js
This PR converts the `tools/unwrap` component to `ts` and updates it to use the api service.
This component broke the `VoidResponse` pattern which assumed that a response marked as void would only return when there was no data under the `response.data` key. For the unwrap endpoint, the component needs access to both information under the `data` key as well as the outer request object.
The generator runtime template was updated to handle the data extraction in the `JSONApiResponse` class and the `extractData` middleware was removed from the api service. This allows void response types to be returned with the full response from the server while preserving the json responses.
applying the patch for this PR to the …
> [UI] Ember Data Migration - Tools Unwrap Component

- website/content/docs/sync/index.mdx
🔍 [Deploy preview](https://vault-git-docs-update-secrets-sync-callout-hashicorp.vercel.app/vault/docs/sync)
This PR:
- Updates the product callout to include HVD
- Updates the callout for HVS users
- Adds the tutorial link
files.
> [DOCS] Update the callout note for accuracy

- website/content/partials/kubernetes-supported-versions.mdx
Manual backport of https://github.com/hashicorp/vault/pull/29932
- [-] **ENT Breakage:** If this PR …
> docs/k8s: update supported k8s versions for 1.18

- website/content/partials/kubernetes-supported-versions.mdx
Update the supported k8s versions list to 1.28-1.32.
Related:
* https://github.com/hashicorp/vault-k8s/pull/747
* https://github.com/hashicorp/vault-csi-provider/pull/350
* https://github.com/hashicorp/vault-helm/pull/1098
* https://github.com/hashicorp/vault-secrets-operator/pull/1033
* https://github.com/hashicorp/vault-plugin-auth-kubernetes/pull/290
* https://github.com/hashicorp/vault-plugin-secrets-kubernetes/pull/92
- [-] **LTS**: If this fixes a critical security vulnerability or [severity 1](https://www.hashicorp.com/customer-success/enterprise-support) bug, it will also need to be backported to the current [LTS versions](https://developer.hashicorp.com/vault/docs/enterprise/lts#why-is-there-a-risk-to-updating-to-a-non-lts-vault-enterprise-version) of Vault. To ensure this, use …
> docs/k8s: update supported k8s versions

- ui/app/services/namespace.js
- ui/tests/integration/components/dashboard/overview-test.js
When adding the explicit namespace check in https://github.com/hashicorp/vault/pull/30000 I mistakenly added a `/` to the end, but the path is manually set to `admin` by [this getter](https://github.com/hashicorp/vault/blob/629b04c0030041b93aa77f8796d70d8b754d5181/ui/app/services/flags.ts#L37) 
files.
> UI: Remove slash from check for admin namespace path

- .github/actions/install-external-tools/action.yml
- tools/tools.sh
Switch out the enumer tool to a version that is compatible with Go 1.24 resolving the following errors when running under that Go version. 
```
enumer: internal error: package "fmt" without types was imported from "github.com/hashicorp/vault/builtin/logical/pki"
builtin/logical/pki/path_config_acme.go:420: running "enumer": exit status 1
enumer: internal error: package "context" without types was imported from "github.com/hashicorp/vault/builtin/logical/pki/pki_backend"
builtin/logical/pki/pki_backend/common.go:29: running "enumer": exit status 1
enumer: internal error: package "context" without types was imported from "github.com/hashicorp/vault/command"
command/operator_generate_root.go:26: running "enumer": exit status 1
enumer: internal error: package "fmt" without types was imported …
```
> Switch to enumer tool that works with Go 1.24

- website/content/api-docs/system/config-cors.mdx
🎫 [Jira ticket](https://hashicorp.atlassian.net/browse/FRB-1367)
🔍 [Deploy preview](https://vault-git-docs-update-api-config-cor-hashicorp.vercel.app/vault/api-docs/system/config-cors#configure-cors-settings)
This PR adds a sentence to describe how `sys/config/cor` endpoing works with Performance Replication. 
files.
> [DOCS] Add an description for performance replication

- website/content/docs/auth/azure.mdx
- website/content/docs/upgrading/upgrade-to-1.18.x.mdx
The PR adds azure auth security improvement to upgrade guide 1.18.x. The PR needs https://github.com/hashicorp/vault/pull/29969
files.
> add azure auth security improvement to upgrade guide 1.18.x

- changelog/30052.txt
- go.mod
- go.sum
The PR upgrades vault-plugin-auth-azure to v0.20.2 into release/1.19.x
files.
> upgrade vault-plugin-auth-azure to v0.20.2 into release/1.19.x

- website/content/docs/auth/login-mfa/index.mdx
🎫 [Jira ticket](https://hashicorp.atlassian.net/browse/SPE-1141)
🔍 [Deploy preview](https://vault-git-docs-update-mfa-doc-hashicorp.vercel.app/vault/docs/auth/login-mfa#time-based-one-time-password-totp-1)
This PR:
- Updates the callout title to draw user attention
- Adds "Known compartibility" table at the end as a reference
files.
> [Docs] MFA TOTP doc added info

- builtin/credential/aws/path_config_client.go
- builtin/credential/ldap/path_config.go
- builtin/logical/aws/path_config_root.go
- builtin/logical/database/path_config_connection.go
- changelog/30039.txt
Fixes a bug where Performance Secondaries panic when they attempt to de-register / register jobs to the RM, since the RM is nil on Perf Secondaries. This fix appropriately forwards such requests to the Primary node in the cluster.
> Forward Performance Standby Requests when configuring root credentials for AWS and LDAP

- website/content/docs/release-notes/1.19.0.mdx
- website/content/docs/upgrading/upgrade-to-1.19.x.mdx
- website/content/partials/known-issues/1_19-failures-after-external-group-changes-standby.mdx
Adds known issue for failed login/token renewals occuring because a perf standby can't write to storage
files.
> add known issue for login/token renewals failing on perf standbys if an external group has changed VAULT-34956

- go.mod
- go.sum
This PR bumps the version of dockertest to a hash that includes a desired version of a dependency. RE: VAULT-34474
files.
> Bump dockertest version

- go.mod
- go.sum
This PR bumps the version of dockertest to a hash that includes a desired version of a dependency. RE: VAULT-34474
files.
> 1.19.x Backport: bump dockertest to update indirect dependency

- changelog/30069.txt
- vault/identity_store.go
- vault/identity_store_oss.go
- vault/identity_store_structs.go
- vault/identity_store_util.go
This change reintroduces the UpsertGroup RPC functionality for use by the refreshExternalGroupMembershipsByEntityID function. Users were unable to log in or renew their tokens if their entity's external group association changed. This issue stemmed from performance standby nodes being unable to write group updates to storage. To fix this regression, we’ve restored the RPC functionality, allowing performance standbys to forward group update logic to the active node.
files.
description. Also, make sure the changelog …
> Reintroduce UpsertGroupRequest for targeted use in external groups refresh CE

- vault/activity_log.go
- vault/activity_log_testonly_oss_test.go
- vault/activity_log_testonly_test.go
- vault/activity_log_util.go
- vault/activity_log_util_common.go
Jira: https://hashicorp.atlassian.net/browse/VAULT-34676
A field called clientIDsUsageInfo is added to core struct. This holds the clientIDs in memory.
During post-unseal, the clientIDs from the current billing cycle until the last month are loaded and stored in core.clientIDsUsageInfo on the active node.
Added tests
Approved ENT PR: https://github.com/hashicorp/vault-enterprise/pull/7672
files.
description. Also, make sure the changelog is in this PR, _not_ in your ENT …
> Vault 34676: set up client count usage map upon startup ce changes

- changelog/30071.txt
- vault/activity/query.go
- vault/activity_log.go
- vault/activity_log_util_common.go
Adds mount_type to sys/counters/activity response
ENT PR: https://github.com/hashicorp/vault-enterprise/pull/7656/files
files.
> Add mount_type to sys/counters/activity response

- changelog/30079.txt
- go.mod
- go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/14133773942
> Update vault-plugin-secrets-openldap to v0.15.2

- vault/logical_system.go
- vault/logical_system_plugins_stubs_oss.go
- vault/logical_system_test.go
- vault/plugincatalog/pin_test.go
- vault/plugincatalog/plugin_catalog_test.go
This PR adds an ENT-only validation `validateSha256IsEmptyForEntPluginVersion` to the `handlePluginCatalogUpdate` functio, along with the CE stub for it.
Links:
- Related ENT PR: https://github.com/hashicorp/vault-enterprise/pull/7695 (which needs to be rebased off `main` after these CE changes are brought into ENT `main`)
- Ticket: [VAULT-34579](https://hashicorp.atlassian.net/browse/VAULT-34579)
files.
[VAULT-34579]: …
> Vault 34579 ce stubs to support external ce to ent plugin upgrade

- changelog/30081.txt
- go.mod
- go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/14133838536
> Update vault-plugin-auth-gcp to v0.20.2

- website/data/docs-nav-data.json
Hides Venafi usage docs from the nav while leaving the page findable for folks currently using it.
> [DOCS] Hide venafi docs

- website/content/api-docs/system/internal-counters.mdx
Updated docs to reflect sys/counters API response changes
ENT PR : https://github.com/hashicorp/vault-enterprise/pull/7656
CE PR: https://github.com/hashicorp/vault/pull/30071
files.
> Docs: Added mount_type to sys/counters API response

- vault/plugincatalog/plugin_catalog_test.go
Missed adding `Sha256` to in one of the CE tests in https://github.com/hashicorp/vault/pull/30041. This is needed before merging https://github.com/hashicorp/vault-enterprise/pull/7695
files.
> add Sha256 to plugin catalog Set call in one more ce test

- ui/api-client/dist/esm/runtime.js
- ui/api-client/dist/runtime.js
- ui/api-client/src/runtime.ts
This PR regenerates the api client with changes that allow for the query object to be mutated on a per request basis. This is necessary since the spec does not have all of the query parameters listed for certain endpoints and until that can be updated we need a way to manually add them.
files.
> [UI] API Client Update - Override Query

- ui/app/components/auth/page.hbs
- ui/app/components/auth/page.js
- ui/tests/acceptance/auth-test.js
- ui/tests/acceptance/auth/mfa-test.js
- ui/tests/acceptance/oidc-auth-method-test.js
- ui/tests/acceptance/saml-auth-method-test.js
- ui/tests/helpers/auth/auth-form-selectors.ts
- ui/tests/helpers/auth/auth-helpers.ts
- ui/tests/helpers/mfa/mfa-helpers.js
- ui/tests/helpers/mfa/mfa-selectors.ts
- ui/tests/helpers/oidc-window-stub.js
- ui/tests/integration/components/auth/login-form-test.js
- ui/tests/integration/components/auth/page-test.js
✅ enterprise passed
Manual backport of #30033 to hopefully address test flakiness due to use of `later()` from `@ember/runloop`
This test in particular:
```
Acceptance | oidc auth method: it prompts mfa if configured: Chrome 134.0
Test took longer than 60000ms; test timed out. 
More information has been printed to the console. Please use that information to help in debugging.
```
files.
> Backport 1.19.x: UI: Add auth tests

- .github/workflows/build.yml
- .github/workflows/ci.yml
Now that we require `vault-auth` sometimes in `build` and `ci` we need the appropriate permissions.
files.
> actions: set permissions for build and ci

- ui/tests/acceptance/enterprise-replication-test.js
Note: It seems like sometimes mount paths have `/` while others do not, causing this enterprise test to fail inconsistently. Updating the assertion to exclude the trailing `/` and check for `hasTextContaining` instead of `includesText` to make this test more reliable and less flaky. 
files.
> UI: Fix vault enterprise replication test failure

- sdk/helper/pluginruntimeutil/config.go
Fixes a typo in the structs tag for `rootless`. This should not be a breaking change, since we don't take use `fatih/structs` to serialize/deserialize this type. All serialization seems to go through `encoding/json`.
files.
> fix rootless typo

- builtin/credential/userpass/path_user_password.go
Because err has been judged before, err here must be nil.
According to the context logic, it should be `intErr`
For https://github.com/hashicorp/vault/issues/29936
files.
> fix: Fix problematic error returns

- changelog/29798.txt
- website/content/docs/enterprise/sentinel/index.mdx
- website/data/docs-nav-data.json
Fixes typos in:
- [website/content/docs/enterprise/sentinel/index.mdx](https://github.com/hashicorp/vault/blob/main/website/content/docs/enterprise/sentinel/index.mdx)
- [website/data/docs-nav-data.json](https://github.com/hashicorp/vault/blob/a66bd4ec20e4d7a31d6b8e1233db0bc98cfdbc62/website/data/docs-nav-data.json#L3171)
`Mange -> Manage`
> Fix tutorial typos

- website/data/docs-nav-data.json
Corrects the `"hiddden": true` setting to remove the quotes and actually hide the nav item >_<
> [DOCS] Fix true setting in nav

- builtin/credential/ldap/backend_test.go
- builtin/credential/ldap/path_config_rotate_root_test.go
- helper/testhelpers/ldap/ldaphelper.go
- sdk/helper/docker/testhelpers.go
- vault/external_tests/identity/groups_test.go
- vault/external_tests/identity/identity_test.go
- vault/external_tests/policy/policy_test.go
- vault/external_tests/token/token_test.go
The test container that we use for many LDAP tests recently merged a breaking change: https://github.com/rroemhild/docker-test-openldap/issues/62
Pin to the latest working version until the issue has been resolved.
files.
> ldap: pin test container to latest working version

- vault/activity_log.go
- vault/activity_log_testing_util.go
- vault/activity_log_util.go
JIRA: https://hashicorp.atlassian.net/browse/VAULT-34677
At the end of the current month (start of the next month), update the in-memory map with all the clients seen in the current month.
This is done in the background as the segments for the last month need to be loaded from storage.
If we identify that we are in a new billing cycle at the end of the month, reset the in-memory map as it should only contain clients in the current billing cycle.
Add required tests.
This change should be backported to 1.19.x and 1.19.x+ent and 1.18.x+ent.
**_Note: This change should be reflected only on ent and it is no-op on CE_**
Approved Ent: https://github.com/hashicorp/vault-enterprise/pull/7707 …
> Vault-34677-Removing estimates from counters api- handle end of month and end of current billing cycle CE changes

- ui/app/components/namespace-picker.hbs
- ui/app/components/namespace-picker.js
- ui/app/components/namespace-picker/after-options.hbs
- ui/app/components/namespace-picker/after-options.ts
- ui/tests/acceptance/enterprise-namespaces-test.js
| ℹ️ **NOTE: This branch is merging into a feature side branch** (not `main`) |
| ---|
> 236 tests completed in 171425 milliseconds, with 0 failed, 10 skipped, and 0 todo.
> 1432 assertions of 1432 passed, 0 failed.
- All/Matching Namespaces Label w/ Count Badge
- "You are logged in with a root token and will have to re-authenticate when switching namespaces."
- Expanded namespace picker width to support long namespace paths
- Tab to auto-complete namespace path
- Styling to match Figma designs
- Add test coverage
- Manual testing
| ⚠️  **NOTE: The current implementation looks ugly, styling will be addressed in a separate PR** |
| --- |
|![Screenshot 2025-03-31 at 6 17 49 PM](https://github.com/user-attachments/assets/65b73790-cde3-4d77-9cae-f55ccc23ef66)|
of a public function, even if …
> [VAULT-35044] UI: implement action buttons in updated namespace picker

- website/content/docs/release-notes/1.16.1.mdx
- website/content/docs/release-notes/1.17.0.mdx
- website/content/docs/release-notes/1.18.0.mdx
- website/content/docs/release-notes/1.19.0.mdx
- website/content/docs/upgrading/upgrade-to-1.16.x.mdx
- website/content/docs/upgrading/upgrade-to-1.17.x.mdx
- website/content/docs/upgrading/upgrade-to-1.18.x.mdx
- website/content/docs/upgrading/upgrade-to-1.19.x.mdx
- website/content/partials/known-issues/static-role-premature-rotations.mdx
> [docs] add known issue where static roles get rotated on upgrade

- changelog/30136.txt
- physical/mysql/mysql.go
- website/content/docs/configuration/storage/mysql.mdx
Adds ability to read in mysql backend storage credentials from environment variables. Updates the documentation to support this, as well as correcting the `plaintext_connection_allowed` - it seems like `plaintext_credentials_transmission` has not been a part of the implementation for a while
> Support reading mysql backend credentials from environment variables

- helper/pkcs7/ber.go
- The function was incrementing and decrementing a global variable but was never used so remove it completely and all the commented out code that references the encodeIndent global.
files.
> Fix race within pkcs7.asn1Structured.EncodeTo

- builtin/logical/pki/backend_test.go
- builtin/logical/pki/path_root.go
- changelog/30034.txt
- sdk/helper/certutil/types.go
- website/content/api-docs/secret/pki/index.mdx
Allows Root and Intermediate Key_Usage to be set via CLI, not just in the CSR
Fixes: https://github.com/hashicorp/vault/issues/29362
The test here doesn't successfully fail on a bad branch, so this is a draft right now.
files.
> Allow Root + Intermediate Key_Usage to be set

- website/content/docs/release-notes/1.16.1.mdx
- website/content/docs/release-notes/1.17.0.mdx
- website/content/docs/release-notes/1.18.0.mdx
- website/content/docs/upgrading/upgrade-to-1.16.x.mdx
- website/content/docs/upgrading/upgrade-to-1.17.x.mdx
- website/content/docs/upgrading/upgrade-to-1.18.x.mdx
- website/content/partials/known-issues/static-role-premature-rotations.mdx
> Backport of [docs] add known issue where static roles get rotated on upgrade into release/1.18.x

- enos/README.md
- enos/ci/service-user-iam/main.tf
VAULT-30187: adding aws vault ci permissions to destroy enos aws engine test resources
files.
> VAULT-30187: adding aws vault ci permissions to destroy enos aws engine test res

- builtin/logical/pki/crl_util.go
a simple bugfix, the err is nil value, should use checked err ingoreErr
files.
> fix: fix call Sprintf with wrong err

- website/content/docs/platform/k8s/vso/openshift.mdx
Updates the list of available environment variable options when deploying Vault Secrets Operator from OperatorHub.
Preview link: https://vault-git-docs-vault-35235update-vso-openshift-3a4435-hashicorp.vercel.app/vault/docs/platform/k8s/vso/openshift#options
- [-] **ENT Breakage:** If this PR either 1) removes a public function OR 2) changes the signature
of a public function, even if that …
> docs/vso: update env options for operatorhub deployments

- website/content/docs/auth/github.mdx
> docs(github): add note about `VAULT_AUTH_GITHUB_TOKEN`

- changelog/29874.txt
Add a changelog for https://github.com/hashicorp/vault/pull/29874
files.
> changelog: add changelog for 29874

- website/content/api-docs/system/utilization-report.mdx
- website/data/api-docs-nav-data.json
Adds documentation for the sys/utilization-report API.
files.
> VAULT-34809 Utilization Report docs

- enos/modules/verify_secrets_engines/scripts/pki-verify-certificates.sh
VAULT-35305: fixing enos pki verification issue
files.
> VAULT-35305: fixing enos pki verification issue

- .github/workflows/test-run-enos-scenario-matrix.yml
- enos/modules/verify_secrets_engines/scripts/pki-verify-certificates.sh
VAULT-35305: fixing enos pki verification
files.
> VAULT-35305: fixing enos pki verification

- .github/workflows/build.yml
- .github/workflows/ci.yml
- .github/workflows/test-enos-scenario-ui.yml
- .github/workflows/test-run-enos-scenario.yml
See also: https://github.com/hashicorp/vault/pull/29947
files.
> VAULT-35290 update setup-node to v4.3.0

- .github/workflows/test-ci-cleanup.yml
- enos/ci/aws-nuke.yml
VAULT-30187: updating aws-nuke version
files.
> VAULT-30187: updating aws-nuke version

- ui/app/components/usage/page/index.ts
- ui/tests/integration/components/usage/page/index-test.js
Updates the report data fetching function to map in the "Friendly" names for auth methods and secret engine data.
files.
> [UI] Add engine and auth method mappings to data fetching function

- ui/tests/acceptance/enterprise-kmip-test.js
Fixes failing KMIP test for checking header count, was updated in 1.20 but was not backported with HDS upgrade change
noted PR with test fix: #29719  
files.
> UI: Fix KMIP test in 1.19.x

- ui/app/services/capabilities.ts
- ui/docs/models.md
- ui/lib/kv/addon/routes/secret.js
- ui/lib/replication/addon/routes/application.js
- ui/tests/unit/services/capabilities-test.js
This PR updates the capabilities service to use the api service to make requests to the `capabilities-self` endpoint. Logic from the capabilities model was moved into the service to maintain backwards compatibility.
files.
> [UI] Ember Data Migration - Update Capabilities Service

- ui/lib/core/addon/utils/paginate-list.ts
- ui/tests/unit/utils/paginate-list-test.js
This PR adds a pagination util that when used together with the `api` service will replace the functionality of the `lazyPaginatedQuery` method of the `pagination` service. The current pagination service is tightly coupled with Ember Data and has methods to cache the raw data and manage pushing records into the store. This will no longer be necessary so the new util simply slices an array based on the provided pagination options. To maintain backwards compatibility, the `meta` object is returned as expected. 
files.
in the PR description, commit message, or branch …
> [UI] Ember Data Migration - Pagination Util

- Makefile
- tools/tools.sh
Sync the `Makefile` and `tools/tools.sh` to support installing the `pipeline` tool in CI, which is required for the docs checks.
files.
> docs only: add pipeline targets to Makefile

- command/server.go
- vault/activity_log.go
- vault/activity_log_util_common.go
- vault/census.go
Jira: https://hashicorp.atlassian.net/browse/VAULT-34678
Handles cases where billing start date is reset on license change and config updates
- When billing start date is updated, the clientIDs map in memory is reset
- If the billing start date is before the current date, all the existingsclients until the last month are reloaded into memory 
- If it is the current or future date, the clientIDs map in memory is empty
Added test cases that covers the above scenarios.
ReloadCensusManager reuses the `setupClientIDsUsageInfo`to setup clients upon reload
Approved ent: https://github.com/hashicorp/vault-enterprise/pull/7807 …
> Vault 34678-Removing estimates from counters api: Handle billing start date updates CE

- ui/app/services/capabilities.ts
- ui/tests/unit/services/capabilities-test.js
This PR fixes an issue in the capabilities service where the data object keys returned did not match the provided paths. The `relativeNamespace` was being stripped from the response key which resulted in the provided path always having a leading slash. The issue was that the path can be provided without a leading slash so this was causing a mismatch and capabilities could not be accessed via the originally provided path.
_This was originally discovered from an enterprise test failure. The full test suite passed locally with these changes._
files.
in the PR …
> [UI] Capabilities Service Path Bug

- vault/external_tests/raftha/raft_ha_test.go
This PR does what it says on the tin.
files.
> [VAULT-34116] Skip TestRaftHACluster_Removed_ReAdd until we fix its flakiness

- builtin/logical/ssh/path_config_ca.go
- builtin/logical/ssh/path_config_ca_test.go
- builtin/logical/ssh/path_fetch.go
- builtin/logical/ssh/path_issue_sign.go
- builtin/logical/ssh/path_roles.go
Refactors SSH CA code to support managed keys.
files.
> Refactoring for returning SSH CA public key with managed keys

- changelog/30265.txt
- go.mod
- go.sum
Uppdate vault-plugin-secrets-openldap to v0.15.3 
files.
> Update vault-plugin-secrets-openldap to v0.15.3

- .github/actions/metadata/action.yml
- .github/actions/set-up-go/action.yml
- .github/actions/set-up-pipeline/action.yml
- .github/workflows/build.yml
- .github/workflows/ci.yml
- tools/pipeline/internal/pkg/changed/checkers.go
- tools/pipeline/internal/pkg/changed/checkers_test.go
- tools/pipeline/internal/pkg/changed/file.go
- tools/pipeline/internal/pkg/github/list_changed_files.go
To fully support automated Enterprise to Community backports we need to have better changed file detection for community and enterprise only files. Armed with this metadata, future changes will be able to inspect changed files and automatically remove enterprise only files when creating the CE backports.
For this change we now have the following changed file groups:
- autopilot
- changelog
- community
- docs
- enos
- enterprise
- app
- gotoolchain
- pipeline
- proto
- tools
- ui
Not included in the change -- but something I did while updating out checkers -- was generate a list of files that only exist in vault-enteprise and ran every path through the updated enterprise detection rules to ensure that they are categorized appropriately post changes in VAULT-35431. While it's possible that …
> VAULT-34834: pipeline: add better heuristics for changed files

- ui/app/components/auth/form/base.hbs
- ui/app/components/auth/form/base.ts
- ui/tests/integration/components/auth/form/base-test.js
- ui/tests/integration/components/auth/form/oidc-jwt-test.js
- ui/tests/integration/components/auth/form/okta-test.js
- ui/tests/integration/components/auth/form/saml-test.js
- ui/tests/integration/components/auth/form/test-helper.js
This adds falling back to the default path to the base form functionality. When a custom path is not inputted in the login form, the web UI assumes the default path which is the same as the auth method type.
files.
> UI: Assume default auth path if custom path is not provided 

- CODEOWNERS
Update `@hashicorp/quality-team` references in CODEOWNERS to be `@hashicorp/team-vault-quality` and add `@hashicorp/vault-customer-engineering` as a CODEOWNER for docs content changes.
files.
> CODEOWNERS: update quality group name and add customer eng to docs

- ui/tests/acceptance/auth/mfa-test.js
- ui/tests/acceptance/leases-test.js
- ui/tests/acceptance/oidc-auth-method-test.js
- ui/tests/acceptance/transit-test.js
- ui/tests/integration/components/auth/login-form-test.js
Using datadog stats, determined the tests with the most failures. Addressed those here.
The biggest change is how we're using the `logout()` method in the `oidc-auth-method-test`. Previously, the `beforeEach`  did not have an `await` before the `logout()` method, so the logout wasn’t actually completing. When I added the `await`, it caused other issues due to the timing of when `logout()` was being called.
The fix was to move `await logout()` into each test, placing it right before the user selects the auth method. With this change, all tests are now passing.
This test has been responsible for most of our CI failures due to timeouts, so hopefully this significantly reduces those failures. I’ve run the tests multiple times locally—previously I hit frequent timeouts, but I’m not seeing any …
> Address UI Flaky Tests

- ui/app/components/namespace-picker.hbs
- ui/app/components/namespace-picker.js
- ui/tests/acceptance/enterprise-namespaces-test.js
- ui/tests/integration/components/namespace-picker-test.js
| ℹ️ **This branch is merging into a feature side branch** (not `main`) |
| --- |
| ℹ️ The current implementation looks ugly, styling will be addressed in a separate PR |
| --- |
> 239 tests completed in 168817 milliseconds, with 0 failed, 10 skipped, and 0 todo.
1449 assertions of 1449 passed, 0 failed.
https://github.com/user-attachments/assets/0e9b5682-e359-4b48-a824-3a5b85d84a5f
files.
> [VAULT-35183] UI: enable search for updated namespace picker

- ui/tests/integration/components/database-role-edit-test.js
Ent tests pass: ✅ 
Separating tests out for checking edit views based on role data
Fixes failing test in CI reported [here](https://github.com/hashicorp/vault-enterprise/actions/runs/14582311209)
> UI: Fix for failing DB role test

- builtin/logical/pki/backend_test.go
- builtin/logical/pki/issuing/aia.go
- builtin/logical/pki/path_config_urls.go
- builtin/logical/pki/path_fetch_issuers.go
- builtin/logical/pki/path_intermediate.go
- builtin/logical/pki/path_manage_issuers.go
- builtin/logical/pki/path_root.go
- changelog/30319.txt
- sdk/helper/certutil/helpers.go
- sdk/helper/certutil/types.go
This introduces a feature which allows Freshest or Delta CRL information to be added to the AIA (Authority Access Information) available on a certificate.  This AIA information is configured per mount or per issuer (as other AIA information is), and a warning is returned if no base CRL information is also specified.
- features aren't backported
in the PR description, commit message, or branch name. Branch name is Jira.
> Delta CRL enablement, including tests.

- enos/README.md
- enos/ci/aws-nuke.yml
- enos/enos-globals.hcl
- enos/modules/start_vault/main.tf
- enos/modules/start_vault/variables.tf
- enos/modules/vault_cluster/main.tf
Synchronize the `enos` directory with that of `main` after changes introduced in https://github.com/hashicorp/vault/pull/29974 were not backported.
files.
> enos(mlock): sync enos changes from main to 1.19

- .github/workflows/build.yml
Build the artifacts when `enos` files change. Previously `enos` changes we're grouped as pipeline but with the most recent refactor they have their own group category.
files.
> test(enos): always build artifacts and test when enos files change

- .github/workflows/backport-ce.yml
Update the backport assistant to the latest version.
files.
> backport-assistant: use the latest version of the backport-assistant

- ui/app/components/auth/form/base.ts
- ui/app/components/auth/form/okta.hbs
- ui/app/components/auth/form/okta.js
- ui/app/components/auth/form/okta.ts
- ui/lib/core/addon/utils/uuid.js
- ui/lib/core/app/utils/uuid.js
- ui/tests/integration/components/auth/form/okta-test.js
- ui/tests/integration/components/auth/form/test-helper.js
- ui/types/vault/services/auth.d.ts
❗ No user facing changes 
Builds Okta auth method component which displays the OktaNumberChallenge (if configured by the okta profile). Right now the okta logic is spread out across a couple different files: auth service and login-form.js. Now it's all nicely consolidated in one component 🎉 
files.
> UI: Build Okta auth method component

- .release/security-scan.hcl
- scan.hcl
An upstream CVE in busybox is tripping the security scanner: https://github.com/hashicorp/crt-workflows-common/actions/runs/14623987904/job/41031896870#step:9:16
Since this will require a new version of Alpine we can’t do much except suppress it until a new version has been released with Busybox >= 1.38
We’re already rolling on the latest Alpine 3 so we ought to get the fix as soon as it’s released and available, but this will unbreak the pipeline until then.
files.
description. Also, make sure the changelog is in …
> VAULT-35615 security(scanner): suppress CVE-2025-46394

- .github/workflows/backport-ce.yml
Starting with 0.5.4 the container tag changed from 0.5.4 to v0.5.4, as such we need update our container tag to the new schema.
files.
> backport-assistant: use the new tag schema

- .release/security-scan.hcl
- scan.hcl
A manual backport of https://github.com/hashicorp/vault/pull/30350
An upstream CVE in busybox is tripping the security scanner: https://github.com/hashicorp/crt-workflows-common/actions/runs/14623987904/job/41031896870#step:9:16
Since this will require a new version of Alpine we can’t do much except suppress it until a new version has been released with Busybox >= 1.38
We’re already rolling on the latest Alpine 3 so we ought to get the fix as soon as it’s released and available, but this will unbreak the pipeline until then.
files.
in the PR description, commit …
> VAULT-35615 security(scanner): suppress CVE-2025-46394 1.19.x (#30350)

- vault/logical_system_raft.go
- vault/logical_system_stubs_oss.go
- vault/snapshots/source.go
This PR adds a snapshots package and in it, a Source interface. In CE, we have only one source for snapshots, which is a manual file upload.
Ent PR: https://github.com/hashicorp/vault-enterprise/pull/7922
files.
> VAULT-35624: Common snapshot source interface

- website/content/docs/release-notes/1.16.1.mdx
- website/content/docs/release-notes/1.17.0.mdx
- website/content/docs/release-notes/1.18.0.mdx
- website/content/docs/release-notes/1.19.0.mdx
- website/content/docs/upgrading/upgrade-to-1.16.x.mdx
- website/content/docs/upgrading/upgrade-to-1.17.x.mdx
- website/content/docs/upgrading/upgrade-to-1.18.x.mdx
- website/content/docs/upgrading/upgrade-to-1.19.x.mdx
- website/content/partials/known-issues/azure-auth-fails-uniform-vmss.mdx
Adds known issue docs for Azure Auth Uniform VMSS regression related to token validation changes introduced in 1.19.1, 1.18.7, 1.17.14, and 1.16.18.
files.
- x ] **Jira:** If this change has an associated Jira, it's referenced either
> add known issue docs for azure auth uniform vmss regression

- ui/app/forms/form.ts
- ui/app/utils/forms/field.ts
- ui/tests/unit/forms/form-test.js
- ui/tests/unit/utils/forms/field-test.js
This PR returns a proxy from the Form class constructor that proxies get/set of form field properties to the data object. Originally, the `fieldValue` property on form fields was mapped to the data object which worked fine in the `FormField` component. The issue was that there are numerous places where form fields are accessed and set outside of that component. Rather than updating all references to prepend `data.`, the proxy allows for the existing references to function as intended. 
files.
description. Also, …
> [UI] Ember Data Migration: Form Class Proxy

- ui/package.json
- ui/yarn.lock
After some recent dependency changes the UI was failing to load at runtime with the following error `Uncaught Error: Could not find module @ember/test-helpers imported from ember-cli-mirage/get-rfc232-test-context`. The macros dep was already in the resolutions block but it was resolving to the latest minor version. Pinning the version to `1.15.0` solves the issue.
files.
> [UI] Pins Embroider Macros Dep to 1.15.0

- website/content/docs/release-notes/1.16.1.mdx
- website/content/docs/release-notes/1.17.0.mdx
- website/content/docs/upgrading/upgrade-to-1.16.x.mdx
- website/content/docs/upgrading/upgrade-to-1.17.x.mdx
- website/content/partials/known-issues/azure-auth-fails-uniform-vmss.mdx
Backports https://github.com/hashicorp/vault/pull/30373 to 1.17
files.
> manual backport of #30373 to 1.17: add known issue docs for azure auth uniform vmss regression

- website/content/docs/release-notes/1.16.1.mdx
- website/content/docs/upgrading/upgrade-to-1.16.x.mdx
- website/content/partials/known-issues/azure-auth-fails-uniform-vmss.mdx
Backports https://github.com/hashicorp/vault/pull/30373 to 1.16
files.
> manual backport of #30373 to 1.16: add known issue docs for azure auth uniform vmss regression

- vault/activity_log.go
- vault/activity_log_test.go
- vault/activity_log_util_common.go
- vault/activity_log_util_common_test.go
Jira: https://hashicorp.atlassian.net/browse/VAULT-34682
Ent: https://github.com/hashicorp/vault-enterprise/pull/7919
files.
> Vault 34682: Remove references to hyperloglog CE

- ui/mirage/factories/login-rule.js
- ui/mirage/handlers/custom-login.js
- ui/mirage/handlers/index.js
- ui/mirage/scenarios/custom-login.js
- ui/mirage/scenarios/index.js
Builds mirage to mock API to unblock development of custom logic work for ui team. 
To run mirage with the custom-login handler start yarn with the `MIRAGE_DEV_HANDLER` variable set
```
export MIRAGE_DEV_HANDLER=customLogin; yarn start
```
Now the following requests can be made: 
```js
const adapter = this.store.adapterFor('application');
// GET rule by name
await adapter.ajax(`/v1/sys/config/ui/login/default-auth/${encodeURI('Login rule 1')}`, 'GET');
// LIST rules
await adapter.ajax('/v1/sys/config/ui/login/default-auth', 'GET', { data: { list: true } });
// DELETE rule by name
await adapter.ajax(`/v1/sys/config/ui/login/default-auth/${encodeURI('Login rule 2')}`, 'DELETE');
// GET login rule for namespace 
await adapter.ajax('/v1/sys/internal/ui/default-login-methods', 'GET', { …
```
> UI: Add mirage handler and scenarios for custom login work

- enos/enos-modules.hcl
Fix a module import that was added in 3011c4328f88
files.
> enos(raft): fix vault_verify_removed_node source

- ui/app/components/auth/form/base.ts
- ui/app/components/auth/form/oidc-jwt.ts
- ui/app/utils/supported-login-methods.ts
- ui/tests/helpers/auth/auth-helpers.ts
- ui/tests/integration/components/auth/form-template-test.js
- ui/tests/integration/components/auth/form/base-test.js
- ui/tests/integration/components/auth/form/oidc-jwt-test.js
- ui/tests/integration/components/auth/form/okta-test.js
- ui/tests/integration/components/auth/form/test-helper.js
This logic was reused in `oidc-jwt` so opted to consolidate it to the parent. Still TBD if it will move to a serializer or the auth service, but that decision will happen when things are wired up.
Since I touched some of the test logic, double checked enterprise tests for good measure 
✅ enterprise pass
files.
> UI: Consolidates form parsing logic to `base.ts` component

- .github/workflows/test-run-enos-scenario-matrix.yml
Turning off aws secrets engine tests 
files.
> VAULT-35686: turning off aws secrets engine tests 

- enos/modules/install_packages/main.tf
- enos/modules/softhsm_install/main.tf
Remove straggling references to RHEL 9.4
I'll manually backport them to 1.16-1.18 with the other PR that yanked RHEL 9.4
files.
> enos(rhel): remove references to 9.4

- enos/modules/softhsm_install/main.tf
🤦 There is yet another 9.4
files.
> enos(rhel): remove references to 9.4 again

- builtin/logical/aws/client.go
- builtin/logical/aws/path_config_root_test.go
- changelog/30312.txt
This PR should resolve an issue with certain secrets/aws configurations where we weren't properly handling default values, and additionally where we weren't handling GovCloud iam endpoints.
This change will allow the config.Region setting to flow through as the default in all cases for IAM, and when no stsRegion is set for STS. The fallback values (AWS_REGION, etc) will show up in fewer cases.
In the GovCloud case, it's possible that one might be able to work around the existing issue by setting the `AWS_REGION` environment variable and explicitly setting the `iam_endpoint` value.
Areas of Concern:
I tested this to work on all permutations of IAM and STS endpoints, regions, etc, that I could think of, but
1) We don't have access to GovCloud, so I can't definitively verify that it works …
> propgate config.Region in the IAM and STS clients

- website/content/docs/agent-and-proxy/agent/index.mdx
API proxy feature is being deprecated from Vault Agent, and the users should use Vault Proxy. 
This PR update the [Vault Agent example configuration](https://developer.hashicorp.com/vault/docs/agent-and-proxy/agent#example-configuration) by removing the `api_proxy` and `listener` stanzas. Instead, adding `log_file` and `template_config` to the example.
🔍 [Deploy preview](https://vault-git-docs-update-config-example-hashicorp.vercel.app/vault/docs/agent-and-proxy/agent#example-configuration)
----
files. …
> [DOCS] Update the agent config example

- ui/app/components/namespace-picker.hbs
- ui/app/components/namespace-picker.js
- ui/lib/core/addon/utils/key-codes.js
- ui/lib/core/addon/utils/keyboard-keys.ts
- ui/tests/acceptance/enterprise-namespaces-test.js
- ui/tests/helpers/namespace-picker.js
- ui/tests/integration/components/namespace-picker-test.js
> 248 tests completed in 182277 milliseconds, with 0 failed, 10 skipped, and 0 todo.
1468 assertions of 1468 passed, 0 failed.
https://github.com/user-attachments/assets/1aa0a709-c0ea-46c9-820c-420d46db9a86
files.
> [VAULT-35469] UI: navigate to namespace on enter/return

- website/content/api-docs/secret/databases/snowflake.mdx
- website/content/docs/deprecation/index.mdx
- website/content/docs/secrets/databases/index.mdx
- website/content/docs/secrets/databases/snowflake.mdx
- website/content/partials/deprecation/snowflake-password-auth.mdx
Backport of https://github.com/hashicorp/vault/pull/30327
files.
> Backport of Add snowflake DB deprecation docs into release/1.17.x

- website/content/api-docs/secret/databases/snowflake.mdx
- website/content/docs/deprecation/index.mdx
- website/content/docs/secrets/databases/index.mdx
- website/content/docs/secrets/databases/snowflake.mdx
- website/content/partials/deprecation/snowflake-password-auth.mdx
Backport of https://github.com/hashicorp/vault/pull/30327
files.
> Backport of Add snowflake DB deprecation docs into release/1.16.x

- website/content/api-docs/secret/databases/snowflake.mdx
- website/content/docs/deprecation/index.mdx
- website/content/docs/secrets/databases/index.mdx
- website/content/docs/secrets/databases/snowflake.mdx
- website/content/partials/deprecation/snowflake-password-auth.mdx
Backport of https://github.com/hashicorp/vault/pull/30327
files.
> Backport of Add snowflake DB deprecation docs into release/1.18.x

- changelog/30434.txt
- go.mod
- go.sum
Backport for upgrading Auth JWT plugin to 0.23.2 for Vault 1.19.x
> Backport Upgrade Auth JWT plugin to 0.23.2 for Vault 1.19.x

- physical/raft/snapshot.go
- physical/raft/snapshot_test.go
- physical/raft/testdata/TestLoadReadOnlySnapshot.bin
This PR implements a function that loads a snapshot file into a supplied boltDB, while filtering out the paths that are present in the supplied immutable radix tree. See ENT PR for details.
files.
> [VAULT-35190] Implement logic for writing snapshot data to an FSM

- physical/raft/snapshot_test.go
What it says on the tin. I pushed up a comment that was formatted differently in the two repos and it's causing our automation some pain. 
files.
> Fix misformatted comment causing the CE-ENT diff to fail

- ui/api-client/dist/esm/runtime.js
- ui/api-client/dist/runtime.js
- ui/api-client/src/runtime.ts
There was an issue in the API client `VoidApiResponse` handler where truly void responses were triggering an error since the `json` method was being invoked. Enterprise specific tests picked it up but it wasn't an enterprise specific issue and would have impacted all uses of the api client where a response was not being returned from the server. 
files.
> [UI] API Client Runtime Fix

- ui/app/components/auth/form/okta.ts
- ui/app/components/auth/form/saml.hbs
- ui/app/components/auth/form/saml.js
- ui/app/components/auth/form/saml.ts
- ui/tests/integration/components/auth/form/saml-test.js
- ui/types/vault/adapters/auth-method.d.ts
Builds new auth form component for `saml` auth method. Much of the code is transferred from: https://github.com/hashicorp/vault/blob/741721ad0e2f1888114941a3009133cccdc4b7b2/ui/app/components/auth-saml.js (added in https://github.com/hashicorp/vault/pull/22640)
files.
> UI: Build SAML auth component

- ui/app/components/auth/fields.hbs
- ui/app/components/auth/fields.ts
- ui/tests/integration/components/auth/fields-test.js
After consulting with security folks, we decided to hold off on implementing "autocomplete" functionality in the login form for now. There's concern this will upset the security expectations of some users. 
We can revisit this if a strong case comes up to support autocomplete. If we end up making this change, we will likely only support autocomplete for non-token fields. 
files.
> PR: Set `autocomplete="off"` for new auth fields

- vault/logical_system_activity.go
Jira: https://hashicorp.atlassian.net/browse/VAULT-35676
Approved ent: https://github.com/hashicorp/vault-enterprise/pull/7997
files.
> vault-35676 Remove current month estimate warning ce changes

- ui/app/components/namespace-picker.ts
- ui/types/vault/services/namespace.d.ts
> [VAULT-34483] update namespace-picker from javascript to typescript

- ui/app/components/sidebar/nav/cluster.hbs
- ui/lib/config-ui/addon/routes.js
- ui/lib/config-ui/addon/routes/login-settings/index.js
- ui/lib/config-ui/addon/routes/login-settings/rule/details.js
- ui/lib/config-ui/addon/templates/login-settings/index.hbs
- ui/lib/config-ui/addon/templates/login-settings/rule/details.hbs
- ui/tests/integration/components/sidebar/nav/cluster-test.js
**[Merging into a side branch]**
mainly an initial setup for future work 
Adding routes for custom login setting pages, 
route added to side nav (for sanity check / instead of manually typing in url)
files.
> UI: Adding routes for custom login settings 

- website/content/partials/known-issues/database-static-role-premature-rotations.mdx
> Backport of make correction to known issue to include roles created prior to 1.15.0 into release/1.18.x

- website/content/partials/known-issues/database-static-role-premature-rotations.mdx
> Backport of make correction to known issue to include roles created prior to 1.15.0 into release/1.16.x

- website/content/docs/updates/release-notes.mdx
Add explicit links to older release notes since the version drop-down won't list older versions :(
> [DOCS] Add explicit links to older release notes

- ui/tests/acceptance/oidc-auth-method-test.js
Bumping from 50 to 500 for the remaining flaky `oidc-auth-method-test`. In the long term, there is some code that we could refactor.
> Bump wait timer for flaky OIDC auth method test

- website/content/docs/updates/important-changes.mdx
- website/content/docs/updates/release-notes.mdx
- website/content/partials/known-issues/1_19-failures-after-external-group-changes-standby.mdx
- website/content/partials/known-issues/database-static-role-premature-rotations.mdx
- website/content/partials/known-issues/log_file_flush_issue.mdx
- website/content/partials/known-issues/static-role-premature-rotations.mdx
- Replaces database static role summary in important changes section 
- Add fix version 1.19.3 (not 1.19.0-1.19.2)
files.
> Replace summary in important changes section

- website/content/docs/updates/important-changes.mdx
- website/content/docs/updates/release-notes.mdx
- website/content/partials/known-issues/1_19-failures-after-external-group-changes-standby.mdx
- website/content/partials/known-issues/database-static-role-premature-rotations.mdx
- website/content/partials/known-issues/log_file_flush_issue.mdx
- website/content/partials/known-issues/static-role-premature-rotations.mdx
> [backport 1.19.x]: update versions, and replace summary in important changes section

- website/content/partials/known-issues/database-static-role-premature-rotations.mdx
- website/content/partials/known-issues/log_file_flush_issue.mdx
- website/content/partials/known-issues/static-role-premature-rotations.mdx
> [backport 1.18.x]: update versions, and replace summary in important changes section

- website/content/partials/known-issues/database-static-role-premature-rotations.mdx
- website/content/partials/known-issues/log_file_flush_issue.mdx
- website/content/partials/known-issues/static-role-premature-rotations.mdx
> [backport 1.16.x]: update versions, and replace summary in important changes section

- changelog/30349.txt
- ui/app/components/clients/date-range.hbs
- ui/app/components/clients/date-range.ts
- ui/app/components/clients/page-header.hbs
- ui/app/components/clients/page-header.js
- ui/app/components/clients/page/counts.hbs
- ui/app/components/clients/page/counts.ts
- ui/app/styles/helper-classes/flexbox-and-grid.scss
- ui/tests/acceptance/clients/counts-test.js
- ui/tests/acceptance/clients/counts/overview-test.js
- ui/tests/helpers/clients/client-count-selectors.ts
- ui/tests/integration/components/clients/date-range-test.js
- ui/tests/integration/components/clients/page/counts-test.js
This PR mainly affects how the enterprise date picker functions, but there are also visual changes for CE header as well which are shown below. 
For the enterprise date picker, only the start time will be shown in the dropdown and included in the request. The backend will determine the appropriate end time which will be shown in the header to maintain consistency. This restriction of selectable start times for billing periods enables the UI to stay in sync with the backend and defer to the backend for end times for each billing period. 
Ent:
CE: 
enterprise tests ✅ …
> UI: Update Enterprise Client Count Datepicker

- CHANGELOG-v1.10-v1.15.md
- CHANGELOG.md
Update the changelog for the first time in a whole long while.
files.
> changelog: sync changelog with main (1.17)

- CHANGELOG-v1.10-v1.15.md
- CHANGELOG.md
Update the changelog for the first time in a whole long while.
files.
> changelog: sync changelog with main (1.18)

- CHANGELOG-v1.10-v1.15.md
- CHANGELOG.md
Update the changelog for the first time in a whole long while.
files.
> changelog: sync changelog with main (1.16)

- ui/app/components/namespace-picker.hbs
- ui/app/components/namespace-picker.ts
- ui/tests/acceptance/enterprise-namespaces-test.js
- ui/tests/helpers/commands.js
- ui/tests/helpers/namespace-picker.js
- ui/tests/integration/components/namespace-picker-test.js
| 🗒️  Merging into sidebranch not main |
| -- |
| 🗒️ Recommend hiding whitespace changes when reviewing file changes |
| -- |
> 248 tests completed in 163372 milliseconds, with 0 failed, 10 skipped, and 0 todo.
1468 assertions of 1468 passed, 0 failed.
files.
> [VAULT-35780] address TODOs

- website/content/docs/sync/index.mdx
Fix typo in secrets sync documentation
files.
> VAULT-35498: fix typo in secrets sync docs

- ui/app/components/auth-form.js
- ui/app/components/auth/page.hbs
- ui/app/components/auth/page.js
- ui/app/templates/components/auth-form.hbs
- ui/tests/integration/components/auth/login-form-test.js
- ui/tests/integration/components/auth/page-test.js
Moves CSP error to page alert, out of auth form
files.
> Move CSP error to page component

- ui/app/models/database/connection.js
Fixes documentation links for some postgreSQL input fields that were pointing to invalid doc links
Ex: `https://developer.hashicorp.comhttps//developer.hashicorp.com/vault/api-docs/secret/databases/postgresql#auth_type.`
files.
> UI: fix doc links for postgres plugin type

- ui/app/components/auth/fields.hbs
- ui/app/components/auth/form-template.hbs
- ui/app/components/auth/form/base.hbs
- ui/app/components/auth/form/oidc-jwt.hbs
- ui/app/components/auth/form/okta.hbs
- ui/app/components/auth/form/saml.hbs
- ui/app/components/auth/namespace-input.hbs
- ui/app/components/auth/tabs.hbs
- ui/app/components/generate-credentials-totp.hbs
- ui/app/components/secret-list/totp-list-item.hbs
- ui/app/components/totp-edit.hbs
- ui/app/components/totp/key-create-toggle-groups.hbs
- ui/app/components/totp/key-create.hbs
- ui/app/components/totp/key-details.hbs
- ui/app/components/totp/key-qr-code.hbs
Update the headers of `.hbs` files that still contain a `~` to prevent noisy output when building. 
files.
> UI: Update remaining copyright headers 

- ui/app/components/auth/form-template.hbs
- ui/app/components/auth/form-template.ts
- ui/app/components/auth/form/base.hbs
- ui/app/components/auth/form/base.ts
- ui/app/components/auth/form/oidc-jwt.hbs
- ui/app/components/auth/form/okta.hbs
- ui/app/components/auth/form/saml.hbs
- ui/app/components/auth/namespace-input.hbs
- ui/app/components/auth/page.js
- ui/app/components/auth/tabs.hbs
- ui/app/components/auth/tabs.ts
- ui/app/routes/vault/cluster/auth.js
- ui/app/templates/vault/cluster/auth.hbs
- ui/app/utils/supported-login-methods.ts
- ui/tests/acceptance/oidc-provider-test.js
- ui/tests/acceptance/wrapped-token-test.js
- ui/tests/integration/components/auth/form-template-test.js
- ui/types/vault/auth/form.d.ts
- ui/types/vault/services/auth.d.ts
Fetching mounts in the component started to feel really awkward and resulted in a lot of manual state management. The `sys/internal/ui/mounts` request has to be re-fetched anytime the namespace query param changes anyway (which can happen when the namespace input is updated). 
While I don't entirely agree with the namespace being a query param in the URL (see note below) it's out of scope to change it for this auth form refactor work. In short, fetching this data in the route model hook seems to most sensible and as you can see drastically cleaned up the component logic 🎉 
**Why the namespace param in the url is confusing**
The namespace architecture of the web ui (and vault) is confusing because there is a narrow distinction between **authenticating** vs **navigating** to a namespace. 
- …
> Move fetching unauthenticated mounts to the route

- ui/api-client/dist/esm/models/EntityAliasesCreateDuplicatesRequest.d.ts
- ui/api-client/dist/esm/models/EntityAliasesCreateDuplicatesRequest.js
- ui/api-client/dist/esm/models/SystemListSyncAssociationsResponse.d.ts
- ui/api-client/dist/esm/models/SystemListSyncAssociationsResponse.js
- ui/api-client/dist/esm/models/SystemListSyncDestinationsResponse.d.ts
- ui/api-client/dist/esm/models/SystemListSyncDestinationsResponse.js
- ui/api-client/dist/esm/models/SystemReadSyncDestinationsTypeNameAssociationsResponse.d.ts
- ui/api-client/dist/esm/models/SystemReadSyncDestinationsTypeNameAssociationsResponse.js
- ui/api-client/dist/models/EntityAliasesCreateDuplicatesRequest.d.ts
- ui/api-client/dist/models/EntityAliasesCreateDuplicatesRequest.js
- ui/api-client/dist/models/SystemListSyncAssociationsResponse.d.ts
- ui/api-client/dist/models/SystemListSyncAssociationsResponse.js
- ui/api-client/dist/models/SystemListSyncDestinationsResponse.d.ts
- ui/api-client/dist/models/SystemListSyncDestinationsResponse.js
- ui/api-client/dist/models/SystemReadSyncDestinationsTypeNameAssociationsResponse.d.ts
- ui/api-client/dist/models/SystemReadSyncDestinationsTypeNameAssociationsResponse.js
- ui/api-client/src/models/EntityAliasesCreateDuplicatesRequest.ts
- ui/api-client/src/models/SystemListSyncAssociationsResponse.ts
- ui/api-client/src/models/SystemListSyncDestinationsResponse.ts
- ui/api-client/src/models/SystemReadSyncDestinationsTypeNameAssociationsResponse.ts
This PR updates the API client with some missing parameters for sync endpoints.
files.
> [UI] API Client Update - Sync

- sdk/plugin/mock/backend.go
- sdk/plugin/mock/path_config.go
This PR adds RotationManager stubs to the mock plugin to keep it in line with other CE plugins with similar stub code.
(On the enterprise side, this code can interact with the actual rotation manager, e.g., for tests.)
> Add RotationManager stubs to the mock plugin

- ui/lib/config-ui/addon/routes/messages/index.js
- ui/lib/config-ui/addon/templates/messages/index.hbs
There were some updates to capabilities in #30524 that caused/revealed issues in the custom messages engine that caused some enterprise tests to fail. This PR fixes those issues and enterprise tests are now passing locally.
files.
> [UI] Fixes Capabilities Issues in Custom Messages

- website/content/docs/license/product-usage-reporting.mdx
Adds docs for phase 1 added metrics
files.
> Docs for Phase 1 Census Metrics

- ui/app/routes/vault/cluster/auth.js
- ui/tests/acceptance/auth/auth-test.js
The `redirect` hook was causing a double transition because `directLinkData` is `null` if no param exists. We only want to redirect if the param exists AND it's invalid. I meant to include this in https://github.com/hashicorp/vault/pull/30500 but the change got lost locally in a stash somewhere 🙃 
No changelog because it's a follow-on. 
files.
> UI: Add param check to redirect hook

- vault/acl.go
- vault/acl_test.go
- vault/logical_system.go
- vault/logical_system_test.go
- vault/policy.go
- vault/policy_test.go
This PR adds a new policy capability called `recover`. The `recover` capability is required to perform a recover operation.
RFC: https://go.hashi.co/prd/vlt-045
files.
> VAULT-35082: Recovery policy capability

- ui/app/components/auth/form-template.ts
- ui/app/components/auth/page.hbs
- ui/app/components/auth/page.js
- ui/tests/integration/components/auth/form-template-test.js
- ui/tests/integration/components/auth/page-test.js
While adding the logic for the login customization feature, it seemed like it'd eventually get confusing to have the preset type logic happen partially in the parent, moving to the child to simplify things.
files.
> UI: Move preselected auth type logic to Auth::FormTemplate

- .github/workflows/security-scan.yml
This PR refactors the security-scan GitHub Actions workflow to clean it up and take advantage of some of the newer features of the action. This primarily aims to make the workflow simpler while retaining the same functionality.
1. The `codeql` binary is installed under-the-hood by default in `scan-plugin-codeql`, so we don't need to install it manually anymore. We do not (yet?) install `semgrep` under-the-hood, so we need to still use Python for that.
2. We can customize which plugins are installed by the action using the `plugins:` option. Since we're only using CodeQL and Semgrep plugins in the `scan.hcl` file, I've set it to only install those.
https://github.com/hashicorp/vault/blob/92362bd3dc8b345424e7e24aa0a688d093517570/scan.hcl#L13-L28
3. The `cache-*` options have been …
> Refactor security-scan workflow

- ui/app/components/auth-config-form/options.hbs
- ui/app/components/auth-config-form/options.js
- ui/app/models/mount-config.js
- ui/tests/acceptance/auth/test-helper.js
- ui/tests/integration/components/auth-config-form/options-test.js
Replaces listingVisibility checkbox to be a toggle button and adds a direct login link based on auth type + copy button
files.
> UI: Updating visibility attr on auth config to be a toggle with direct login link

- http/handler.go
- http/handler_test.go
- http/logical.go
- http/logical_test.go
This PR adds support for extracting two query parameters:
* `recover_snapshot_id` (can be specified with PUT, POST)
* `read_snapshot_id` (can be specified with GET, LIST)
If the query parameter exists for a request with the correct HTTP verb, then request.RequiredSnapshotID is set to the query parameter value. 
These requests are also always forwarded to the active node, rather than being served on a perf standby.
RFC: https://go.hashi.co/prd/vlt-045
files. …
> VAULT-35081: Extract query parameters for snapshot read/recover

- changelog/30447.txt
- vault/external_tests/quotas/quotas_test.go
- vault/logical_system_quotas.go
- vault/quotas/quotas.go
- vault/quotas/quotas_rate_limit.go
- vault/quotas/quotas_rate_limit_test.go
- vault/quotas/quotas_test.go
This PR adds the `group_by` and `secondary_rate` fields to the RLQ API. These won't provide any additional functionality in CE, as we maintain support only to the current behavior there, but now as an explicit "IP" grouping mode. On enterprise we'll add 3 additional grouping modes to support different use cases:
* `group_by: none` groups all requests to which the RLQ applies together (i.e. collective rate limit);
* `group_by: entity_then_ip` groups requests to which the RLQ applies by entity Id if available, otherwise by the client IP address (e.g. login or root token requests);
* `group_by: entity_then_none` groups requests to which the RLQ applies by entity Id if available, and all entity-less requests together (e.g. login or root token requests)
To make things simpler most of the API …
> VAULT-35628 Add group_by and secondary_rate to RLQ API

- ui/app/components/namespace-picker.hbs
- ui/app/components/namespace-picker.ts
- ui/app/styles/components/namespace-picker.scss
- ui/app/styles/core.scss
- ui/app/styles/helper-classes/spacing.scss
Address design UI feedback on namespace picker:
> 249 tests completed in 138252 milliseconds, with 0 failed, 10 skipped, and 0 todo.
1464 assertions of 1464 passed, 0 failed.
Screenshots:
| Narrow | Expanded | 
| -- | -- |
| ![Screenshot 2025-05-12 at 3 41 45 PM](https://github.com/user-attachments/assets/1f913ea7-2210-4a99-bcf9-f89f2cf08253) | ![Screenshot 2025-05-12 at 3 42 39 PM](https://github.com/user-attachments/assets/5a1d9c73-ef9e-49ee-b47a-37a4af5d6cbc) |
| ![Screenshot 2025-05-12 at 3 44 20 PM](https://github.com/user-attachments/assets/2523cacb-e5eb-4de1-9261-18f92e87e8ae) | |
> [VAULT-35871] UI: Address design UI feedback on namespace picker

- vault/testing.go
ENT PR: https://github.com/hashicorp/vault-enterprise/pull/8044
files.
> Phase 2 Census Usage Metrics

- sdk/helper/keysutil/policy_test.go
Revert a partial fix/change had been implemented way back when we were originally looking at the 1.24 update and I missed reverting the change back then and it made it into https://github.com/hashicorp/vault/pull/30576
files.
> Revert partial test changes for skipping FIPS tests for unsupported SHA3 hashes

- website/content/docs/internals/telemetry/metrics/core-system.mdx
- website/content/partials/telemetry-metrics/vault/core/response_status_code.mdx
Docs for https://github.com/hashicorp/vault/pull/30354
files.
> VAULT-35385 docs for response_status_code metric

- ui/.stylelintignore
Updates the stylelintignore to include the vault-reporting folder. Since these are generated dist files they should not be actively linted.
https://hashicorp.atlassian.net/browse/VAULT-36173
files.
> [UI] Remove vault-reporting from stylelint

- command/server_test.go
Remove the fips_140_3 build tag limitation from the test file as this test should run under that Go test suite.
files.
> Remove FIPS build tag from command/server_test.go

- ui/lib/core/addon/components/form-field.hbs
- ui/lib/core/addon/components/form-field.js
- ui/tests/acceptance/secrets/backend/totp/key-test.js
- ui/tests/acceptance/sync/secrets/destinations-test.js
- ui/tests/helpers/general-selectors.ts
- ui/tests/helpers/sync/sync-selectors.js
- ui/tests/integration/components/form-field-test.js
- ui/tests/integration/components/kubernetes/page/role/create-and-edit-test.js
- ui/tests/integration/components/ldap/page/library/create-and-edit-test.js
- ui/tests/integration/components/mfa/method-form-test.js
- ui/tests/integration/components/oidc/client-form-test.js
- ui/tests/integration/components/totp/key-form-test.js
- ui/tests/pages/components/form-field.js
- updated logic in `isHdsFormField` of `FormField` to include the `editType === 'radio'` use case 
- moved template logic for `editType === 'radio'` in `FormField` under the `isHdsField` block
- because the HDS input doesn't have an `onChange` argument, I had to add a new `setAndBroadcastRadio` action in the controller
Jira ticket: https://hashicorp.atlassian.net/browse/VAULT-34808
files.
> [VAULT-34808] UI: move the `radio` block in `FormField` under the HDS block

- vault/core.go
- vault/core_stubs_oss.go
- vault/core_test.go
CE side change for VAULT-34562
files.
> VAULT-34562: Add required CE stubs

- website/content/docs/secrets/terraform.mdx
This PR removes the statement about _HCP Terraform API limits both Organization and Team roles to one active token at any given time_ since it's no longer true.
🧵 [Slack thread](https://hashicorp.slack.com/archives/C03BX0MJD27/p1747231261629569)
🔍 [Deploy preview](https://vault-git-docs-update-tf-plugin-hashicorp.vercel.app/vault/docs/secrets/terraform#organization-and-team-roles)
----
files.
> [DOCS] Remove the out-dated statement about HCP Terraform

- website/content/docs/license/product-usage-reporting.mdx
Adds two metrics:
- num nodes per cluster
- whether adaptive overload protection was enabled
files.
> Docs for Phase 2 Census Usage metrics

- sdk/plugin/context.go
- sdk/plugin/grpc_backend_client.go
- sdk/plugin/grpc_backend_server.go
- sdk/plugin/grpc_backend_test.go
- sdk/plugin/grpc_storage.go
- sdk/plugin/mock/backend.go
This PR converts a context key into GRPC metadata and back again to include the snapshot ID for a request. The PR also does this conversion on requests to the storage service. This is necessary in order to support recover/read from snapshot operations on external plugins
RFC: https://go.hashi.co/rfc/vlt-347
files.
> VAULT-35080: Snapshot ID context conversion for GRPC plugins

- helper/testhelpers/pluginhelpers/pluginhelpers.go
This PR fixes CompilePlugin which would fail when run locally in certain situations based on relative directory paths. This change makes CompilePlugin perform os.Stat on the full path to the plugin's main.go file to ensure the test changes to the appropriate directory for building the plugin.
files.
> test: fix CompilePlugin test helper

- sdk/helper/consts/replication.go
- vault/census.go
- vault/census_manager.go
- vault/core.go
Corresponding CE changes to https://github.com/hashicorp/vault-enterprise/pull/7989
Jira: https://hashicorp.atlassian.net/browse/VAULT-35165
RFC: https://go.hashi.co/rfc/vlt-348
files.
> [VAULT-35165] CE changes for development cluster setting

- .github/workflows/code-checker.yml
Something recently changed in Github Actions' decoding and display of git errors is output. Now previously benign errors are showing up as annotations and causing confusion. This isn't actually necessary because the the cache should have all the required modules but it ought to get rid of the errors.
files.
> VAULT-36174: code-checker: Configure git with the ELEVATED_GITHUB_TOKEN

- command/server.go
Based on conversations with support, we decided to ignore the absence of `disable_mlock` in the config if a system does not support mlock.
This PR adds that check.
files.
> do not fail to start if missing mlock config on systems that do not support mlock

- website/content/docs/license/product-usage-reporting.mdx
Adds documentation for 3 usage metrics
files.
> Added Docs for Phase 3 Usage Metrics

- .github/actions/set-up-go/action.yml
- scripts/go-helper.sh
`actions/cache/restore` has some surprising relative pathing behavior we need
to deal with. When it restores a previously created cache it does it relative to the
checkout working directory. Since that can be different depending on our
self-hosted vs Github hosted runners:
`home/runner/actions-runner/_work` vs. `/home/runner/work`
we need to factor in the absolute path of our working directory in our cache key.
If we don't then cache restores will be incompatible on one or the other runner
as the relative depth is different.
We also slightly change our module caches here to only get `.../mod/cache` instead
of the whole `.../mod` directory. Go is able to unzip the modules in `.../mode/cache`
faster than what it takes to download the entire directory.
This will double our module caches (in …
> VAULT-36174: pipeline(go): deal with relative path issues in cache restore

- .golangci.yml
- tools/pipeline/internal/pkg/git/apply.go
- tools/pipeline/internal/pkg/git/branch.go
- tools/pipeline/internal/pkg/git/checkout.go
- tools/pipeline/internal/pkg/git/cherry-pick.go
- tools/pipeline/internal/pkg/git/client.go
- tools/pipeline/internal/pkg/git/clone.go
- tools/pipeline/internal/pkg/git/commit.go
- tools/pipeline/internal/pkg/git/fetch.go
- tools/pipeline/internal/pkg/git/merge.go
- tools/pipeline/internal/pkg/git/opts_test.go
- tools/pipeline/internal/pkg/git/pull.go
- tools/pipeline/internal/pkg/git/push.go
- tools/pipeline/internal/pkg/git/rebase.go
- tools/pipeline/internal/pkg/git/reset.go
- tools/pipeline/internal/pkg/git/rm.go
- tools/pipeline/internal/pkg/git/show.go
- tools/pipeline/internal/pkg/git/status.go
As I was working on VAULT-34829 it became clear that we needed to solve the problem of using Git from Go. Initially I tried to use the go-git/go-git pure Go implementation of Git, but it lacked several features that we needed.
The next best option seemed to be shelling out to Git. What started as a simple way to execute Git commands with the requisite environment and configuration led to the implementation.
A few notes:
- I did not add support for all flags for the implemented sub-commands
- I wanted it to handle automatic injection and configuration of PATs when operating against private remote repositories in Github.
- I did not want to rely on the local machine having been configured. The client that is built in is capable of configuring everything that we need via environment …
> [VAULT-36201] pipeline(git): add Go git client

- ui/app/components/generate-credentials-totp.hbs
- ui/app/components/generate-credentials-totp.js
- ui/app/routes/vault/cluster/secrets/backend/credentials.js
This PR address the remaining TODOs in the TOTP logic. If an error is encountered when retrieving the totp code's period (the time for which the code is valid), the default will be 30 seconds which is the default in the api spec. 
files.
> UI: Tidy up TOTP logic

- website/content/docs/license/product-usage-reporting.mdx
Added two metadata usage metrics.
files.
> Added docs for metadata I missed

- changelog/30659.txt
- website/content/docs/configuration/reporting.mdx
- website/content/docs/license/product-usage-reporting.mdx
- website/content/docs/license/utilization/auto-reporting.mdx
- website/content/docs/license/utilization/manual-reporting.mdx
This PR adds the documentation for the new `development_cluster` config value and Census report metadata field. It also includes the changelog for the feature. 
Jira: https://hashicorp.atlassian.net/browse/VAULT-35162
RFC: https://go.hashi.co/rfc/vlt-348
files.
> [VAULT-35162] Development Cluster setting docs

- sdk/framework/openapi.go
- sdk/framework/openapi_test.go
- sdk/framework/testdata/operations.json
- vault/logical_system.go
The PR adds `PATCH` endpoints to the generated OpenAPI spec.
files.
> OpenAPI Patch Endpoints

- vault/core_metrics.go
This PR adds autopilot enabled or not metrics to census
Jira ticket: https://hashicorp.atlassian.net/browse/VAULT-35523
ENT PR: https://github.com/hashicorp/vault-enterprise/pull/8102
files.
> Vault-35523 add autopilot metrics

- ui/app/components/section-tabs.hbs
- ui/app/helpers/supported-managed-auth-backends.js
- ui/app/templates/components/generated-item-list.hbs
- ui/app/templates/vault/cluster/access/method/section.hbs
- ui/app/templates/vault/cluster/access/methods.hbs
- ui/tests/acceptance/access/methods-test.js
- ui/tests/acceptance/auth/auth-list-test.js
- ui/tests/acceptance/settings/auth/configure/section-test.js
- ui/tests/acceptance/settings/auth/enable-test.js
- ui/tests/acceptance/sidebar-nav-test.js
- ui/tests/helpers/auth/auth-form-selectors.ts
- ui/tests/helpers/general-selectors.ts
- ui/tests/pages/settings/auth/configure/section.js
Attempts to fix and clean up the flaky:
```
auth backend list > auth methods are linkable and link to correct view: userpass auth method
```
files.
> Fix auth flaky test

- http/handler.go
- http/logical.go
- vault/external_tests/raft/raft_test.go
- vault/logical_system_raft.go
- vault/raft.go
ENT PR: https://github.com/hashicorp/vault-enterprise/pull/7908
files.
> [VAULT-35075] Add API paths for loaded snap

- vault/quotas/quotas_rate_limit.go
PR #30633 was missing commit b646694 from the ent PR, which fixed a bug with the new group_by modes in ent by updating this CE file. Not sure why my diff command didn't pick this one up.
Slack thread: [#feed-vault-ci-official](https://hashicorp.slack.com/archives/C05AABYEA9Y/p1747767517120989)
Jira: [VAULT-35628](https://hashicorp.atlassian.net/browse/VAULT-35643)
- [-] **LTS**: If this fixes a critical security vulnerability or [severity 1](https://www.hashicorp.com/customer-success/enterprise-support) …
> VAULT-35628: add missing change to fix ce-ent diff

- changelog/30692.txt
- ui/app/controllers/vault/cluster/access/namespaces/index.js
- ui/app/templates/vault/cluster/access/namespaces/index.hbs
- ui/tests/acceptance/access/namespaces/index-test.js
> 258 tests completed in 148164 milliseconds, with 0 failed, 10 skipped, and 0 todo.
1492 assertions of 1492 passed, 0 failed.
files.
> [VAULT-36271] UI: Add refresh namespaces button and breadcrumb to manage namespace page

- website/content/docs/commands/license/get.mdx
- website/content/docs/commands/license/index.mdx
- website/content/docs/commands/license/inspect.mdx
Adds the "Vault Enterprise" banner on the docs for these subcommands. As we're interacting with a Vault license... this is kinda implied. But this should make it clear that you explicitly need an enterprise binary if you want to inspect an enterprise license (and that you cannot inspect a license with a CE binary).
The wording isn't 100% clear here; the partial
https://github.com/hashicorp/vault/blob/main/website/content/partials/alerts/enterprise-only.mdx says that an enterprise _license_ is required to run this command...
But I think the implication may be sufficient.
For example, the operator import command:
https://github.com/hashicorp/vault/blob/main/website/content/docs/commands/operator/import.mdx
Needs both an enterprise license, and an enterprise binary.
to N, N-1, and N-2, using …
> docs: Make it clear that an Enterprise Vault binary is required to use the License subcommands

- website/content/docs/secrets/azure.mdx
Azure WIF Docs
- The subject identifier actual value is NAMESPACE_ID, so <NAMESPACE> is confusing.
- identity_token_audience has an audience value in Azure Federation, so examples like an existing vault URL are confusing.
> Change subject identifier and identity_token_audience to realistic example value

- website/content/docs/updates/important-changes.mdx
- website/content/docs/updates/release-notes.mdx
This PR adds a guide for updating Vault configs when using integrated storage for Vault 1.20.0. 
[Jira Issue](https://hashicorp.atlassian.net/browse/VAULT-35291)
files.
> add upgrade guide for disable_mlock change in 1.20

- ui/app/styles/helper-classes/general.scss
- ui/app/templates/components/auth-form.hbs
Previously, if a mount description has a line break `\n` in it the UI ignored it. Now it doesn't. 
```
{
"auth": {
"userpass/": {
"description": "this is my long description with \nline breaks\nhellloooooo",
"options": {},
"type": "userpass"
}
},
}
```
files.
> UI: Render line breaks for mount description in login form

- builtin/logical/transit/path_byok.go
- builtin/logical/transit/path_export.go
- builtin/logical/transit/path_import.go
- builtin/logical/transit/path_keys.go
- builtin/logical/transit/path_keys_test.go
- builtin/logical/transit/path_sign_verify_ce.go
- sdk/helper/keysutil/lock_manager.go
- sdk/helper/keysutil/policy.go
- sdk/helper/keysutil/policy_test.go
CE-changes makes AES192-CMAC work in enterprise.
- no backports necessary.
applying this patch for this PR to the ENT repo and running tests doesn't
files. 
-- no signature is changed by these change
in the PR description, commit message, or branch name: https://hashicorp.atlassian.net/browse/VAULT-35005
- No RFC
-- this is the corresponding CE PR to : https://github.com/hashicorp/vault-enterprise/pull/8126/files
-- this is a ent-feature, so changelog is in ent.
> CE-changes for ent-feature AES192-CMAC for transit.

- enos/modules/verify_secrets_engines/modules/create/kv.tf
VAULT-36377: adding kv policy writers to depends on
files.
> VAULT-36377: adding kv policy writers to depends on

- website/content/docs/license/product-usage-reporting.mdx
This PR adds docs for the new product metrics being added to track the `group_by` field in rate limit quotas.
Jira: [VAULT-35632](https://hashicorp.atlassian.net/browse/VAULT-35632)
Ent PR: https://github.com/hashicorp/vault-enterprise/pull/8124
- [-] **LTS**: If this fixes a critical security vulnerability or [severity 1](https://www.hashicorp.com/customer-success/enterprise-support) bug, it will also need to be backported to the current [LTS versions](https://developer.hashicorp.com/vault/docs/enterprise/ …
> VAULT-35632: docs for new RLQ product metrics

- builtin/logical/transit/path_keys.go
- changelog/30728.txt
Storing the wrapping key for BYOK is causing a key named `import/` to appear when listing keys. This PR excludes that entry from the list operation
files.
> Exclude wrapping key from list operation

- .release/security-scan.hcl
This PR aims to refactor the release security scanner configuration to:
1. Enable scan features that have been turned off (likely by mistake, or due to bugs that have likely been resolved).
> [!IMPORTANT] 
>    When we have the following:
>        https://github.com/hashicorp/vault/blob/18f558159025c4856f8e63a7adc024d50a550544/.release/security-scan.hcl#L6-L8
>       ☝️  It effectively means that Go modules scanning is _disabled_, despite two vulnerability databases being enabled. That probably isn't intentional (seemingly done as part of https://github.com/hashicorp/vault/pull/30350), so I went ahead and re-enabled it.
2. Enable the OSV vulnerability database for container scans: it provides broader coverage and support for container OS package types, including APK, Debian, RPM, etc. …
> Refactor Release Security Scanner Config

- .release/security-scan.hcl
Manual backport of https://github.com/hashicorp/vault/pull/30597
files.
> Backport Refactor release security scan config (#30597) into release/1.19.x

- tools/pipeline/go.mod
- tools/pipeline/internal/cmd/github.go
- tools/pipeline/internal/cmd/github_create.go
- tools/pipeline/internal/cmd/github_create_backport.go
- tools/pipeline/internal/cmd/root.go
- tools/pipeline/internal/pkg/git/am.go
- tools/pipeline/internal/pkg/git/opts_test.go
- tools/pipeline/internal/pkg/github/create_backport.go
- tools/pipeline/internal/pkg/github/create_backport_test.go
- tools/pipeline/internal/pkg/github/embeds.go
- tools/pipeline/internal/pkg/github/embeds/backport-pr.tmpl
Add a new `github create backport` sub-command that can create a backport of a given pull request. The command has been designed around a Github Actions workflow where it is triggered on a closed pull request event with a guard that checks for merges:
```yaml
pull_request_target:
types: closed
jobs:
backport:
if: github.even.pull_request.merged
runs-on: "..."
```
Eventually this sub-command (or another similar one) can be used to implemente backporting a CE pull request to the corresponding ce/* branch in vault-enterprise. This functionality will be implemented in VAULT-34827.
This backport runner has several new behaviors not present in the existing backport assistant:
- If the source PR was made against an enterprise branch we'll assume that we want create a CE backport.
- Enterprise …
> [VAULT-34829] pipeline(backport): add `github create backport` command

- changelog/30748.txt
- changelog/30775.txt
- go.mod
- go.sum
Update vault-plugin-database-snowflake to v0.13.1 in release/1.19.x
files.
> Update vault-plugin-database-snowflake to v0.13.1 in release/1.19.x

- vault/quotas/quotas_rate_limit_test.go
Every now and then we see this failure:
```
=== FAIL: vault/quotas TestRateLimitQuota_Update (0.45s)
2025-05-28T14:59:30.422Z [DEBUG] enabling deadlock detection
quotas_rate_limit_test.go:235: found unexpected goroutines:
[Goroutine 6 in state select, with github.com/sethvargo/go-limiter/memorystore.(*store).purge on top of the stack:
github.com/sethvargo/go-limiter/memorystore.(*store).purge(0xc00017c500)
/home/runner/go/pkg/mod/github.com/sethvargo/go-limiter@v0.7.1/memorystore/store.go:222 +0x19f
created by github.com/sethvargo/go-limiter/memorystore.New in goroutine 74
/home/runner/go/pkg/mod/github.com/sethvargo/go-limiter@v0.7.1/memorystore/store.go:105 +0x375
Goroutine 9 in state select, with github.com/sethvargo/go-limiter/memorystore.(*store).purge on top of the stack: …
```
> Try again to fix sporadic goroutine leak in test

- ui/lib/core/addon/components/form-field.hbs
- ui/tests/integration/components/form-field-test.js
- It mainly adds new integration tests for some of the form fields, that were missed when migrated to HDS components (see single commits descriptions for details).
- it also brings back a test that was removed in #30768 (see [thread here](https://github.com/hashicorp/vault/pull/30768/files#r2112332572)) 
files.
> [VAULT-36594] UI: add missing integration tests for `FormField` component

- ui/app/components/clients/page/overview.ts
- ui/tests/integration/components/clients/page/overview-test.js
This updates the month options to show in order of recent -> oldest. This matches the billing period dropdown format and suits the expected use case of investigating recent activity spikes.
files.
> UI: Update Month Order to be Recent - Oldest

- changelog/30785.txt
- go.mod
- go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/15330028378
> Update vault-plugin-database-redis-elasticache to v0.7.0

- changelog/30796.txt
- go.mod
- go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/15352942307
> Update vault-plugin-database-elasticsearch to v0.18.0

- website/content/api-docs/system/rate-limit-quotas.mdx
These are the API docs for the 2 new fields on rate limit quotas.
Jira: [VAULT-34527](https://hashicorp.atlassian.net/browse/VAULT-34527)
Main PR for feature: #30633
PR with education docs: #30717
- [-] **LTS**: If this fixes a critical security vulnerability or [severity 1](https://www.hashicorp.com/customer-success/enterprise-support) bug, it will also need to be backported to the current [LTS versions](https://developer.hashicorp.com/vault/docs/enterprise/lts#why-is-there-a-risk-to-updating-to-a-non-lts- …
> VAULT-34527: API docs for identity-based and collective rate-limit quotas

- ui/app/components/auth-config-form/options.hbs
- ui/app/components/auth-config-form/options.js
- ui/app/components/auth/page.ts
- ui/app/models/auth-method.js
- ui/app/templates/components/auth-method/configuration.hbs
- ui/lib/config-ui/addon/components/login-settings/page/list.hbs
- ui/tests/acceptance/settings/auth/enable-test.js
- ui/tests/integration/components/auth-method/configuration-test.js
No changelog because follow on to https://github.com/hashicorp/vault/pull/30592
- Adds `namespace` when applicable to direct link
- Displays direct link in configuration details view
files.
> UI: Fix direct login link for auth mounts

- changelog/30797.txt
- go.mod
- go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/15353158621
> Update vault-plugin-database-redis to v0.6.0

- ui/app/components/auth/page.ts
- ui/tests/acceptance/config-ui/login-settings-test.js
- ui/tests/integration/components/auth/page-test.js
No changelog because follow-on to https://github.com/hashicorp/vault/pull/30700
Fixes a bug where the form rendered the alternate view (backup tabs) if `backup_auth_types` included `default_auth_type`.
```
vault write sys/config/ui/login/default-auth/root-rule \
default_auth_type=token \
backup_auth_types=userpass \
backup_auth_types=oidc \
backup_auth_types=token \
disable_inheritance=false \
namespace=""
```
Now the form properly renders the default (initial) view and does not pre-toggle the form.
files. …
> UI: Fixes issue where backup tab was selected if they included default type

- website/content/partials/known-issues/database-skip-static-role-rotation.mdx
> Backport of upgrade known issue documentation with fix version for roles with skip_import_rotation=true into release/1.18.x

- .build/entrypoint.sh
- .build/go.sh
- .build/system.sh
- .github/actions/build-vault/action.yml
- .github/actions/metadata/action.yml
- .github/workflows/build-artifacts-ce.yml
- .github/workflows/build.yml
- Dockerfile
- tools/pipeline/internal/pkg/changed/checkers.go
- tools/pipeline/internal/pkg/changed/checkers_test.go
Ubuntu 20.04 has reached EOL and is no longer a supported runner host distro. Historically we've relied on it for our CGO builds as it contains an old enough version of glibc that we can retain compatibility with all of our supported distros and build on a single host distro. Rather than requiring a new RHEL 8 builder (or some equivalent), we instead build CGO binaries inside an Ubuntu 20.04 container along with its glibc and various C compilers.
I've separated out system package changes, the Go toolchain install, and external build tools tools install into different container layers so that the builder container used for each branch is maximally cacheable.
On cache misses these changes result in noticeably longer build times for CGO binaries. That is unavoidable with this strategy. Most …
> [VAULT-35682] build(cgo): Build CGO binaries in a container

- vault/acl.go
- vault/observations/observations_consts.go
CE counterpart of Ent PR.
files.
> VAULT-36495 CE changes

- website/content/api-docs/secret/transit.mdx
- website/content/docs/secrets/transit/index.mdx
Docs update, based on work: https://github.com/hashicorp/vault-enterprise/pull/8126
- Not a backported change, so no need to backport docs
- Doesn't touch any functions - backported or not
in the PR description, commit message, or branch name: https://hashicorp.atlassian.net/browse/VAULT-35005
- No RFC
- ? **ENT PR:** If this change has an associated ENT PR, please link it in the
description. Also, make sure the changelog is in this PR, _not_ in your ENT PR. - not sure why the changelog would be here - this is entirely an ent change: https://github.com/hashicorp/vault-enterprise/pull/8126
> Add 192 to the list of key sizes supported in the docs.

- changelog/30838.txt
- ui/app/routes/vault/cluster/oidc-provider.js
- ui/tests/acceptance/oidc-provider-test.js
- ui/tests/helpers/stubs.js
Resolves https://github.com/hashicorp/vault/issues/27772
When the error handling changed in this PR: https://github.com/hashicorp/vault/pull/25953 the error handling failed to redirect users to authenticate in the OIDC provider workflow. 
> ### Testing
> I spent a while trying to figure out a way to revoke the user's token to simulate the reported bug but with our test  architecture that's very challenging. Instead, the auth service is stubbed and rejects the authorize url with the updated error format. I confirmed the added test fails before the fix.
1. revoke user's token
2. submit OIDC authorize request
3. 🐛 ❌ error is returned and user is not redirected (Ignore large `Success` message). 
> The error returned by [oidcdebugger](https://oidcdebugger.com/) is URL-encoded:
> …
> UI: Fix error handling so users are redirected to log in when token expires if using Vault as an OIDC provider

- changelog/30856.txt
- go.mod
- go.sum
This PR was generated by a GitHub Action. Full log: https://github.com/hashicorp/vault/actions/runs/15454713241
> Update vault-plugin-database-mongodbatlas to v0.15.0

- api/sys_rekey.go
- changelog/30794.txt
- command/operator_rekey.go
- command/operator_rekey_test.go
- http/http_test.go
- http/sys_rekey.go
- http/sys_rekey_test.go
- vault/rekey.go
- vault/rekey_test.go
- vault/seal_config.go
- website/content/api-docs/system/rekey-recovery-key.mdx
- website/content/api-docs/system/rekey.mdx
- website/content/docs/updates/important-changes.mdx
This PR adds a nonce for rekey cancellations 
Enterprise PR: https://github.com/hashicorp/vault-enterprise/pull/8169
files.
> VAULT-36229: Nonce for rekey cancellations

- go.mod
Updates to API and SDK for Vault release candidate 1.20
files.
> Use new sdk and api versions for v1.20

- ui/lib/config-ui/addon/components/login-settings/page/details.js
- ui/lib/config-ui/addon/components/login-settings/page/list.hbs
- ui/tests/acceptance/auth/login-settings-test.js
- ui/tests/acceptance/config-ui/login-settings-test.js
Frontend compliment to https://github.com/hashicorp/vault-enterprise/pull/8211
No changelog because follow-on to https://github.com/hashicorp/vault/pull/30700
files.
> UI: Update `namespace` key to `namespace_path`

- changelog/30867.txt
- go.mod
- go.sum
> backport 1.19.x: Update vault-plugin-database-snowflake to v0.13.2

- ui/lib/config-ui/addon/components/login-settings/page/details.js
- ui/lib/config-ui/addon/components/login-settings/page/list.hbs
- ui/tests/acceptance/auth/login-settings-test.js
- ui/tests/acceptance/config-ui/login-settings-test.js
Backport for https://github.com/hashicorp/vault/pull/30848
files.
> Backport 1.20.x UI: Update `namespace` key to `namespace_path`

- website/content/docs/upgrading/upgrade-to-1.16.x.mdx
- website/content/docs/upgrading/upgrade-to-1.17.x.mdx
- website/content/partials/known-issues/enterprise-plugins.mdx
> [DOCS] Add missing update info to v1.17 docs

- website/content/docs/upgrading/upgrade-to-1.16.x.mdx
- website/content/partials/known-issues/1_13-reload-census-panic-standby.mdx
- website/content/partials/known-issues/1_17_audit-log-hmac.mdx
- website/content/partials/known-issues/autopilot-upgrade-upgrade-version.mdx
- website/content/partials/known-issues/enterprise-plugins.mdx
- website/content/partials/known-issues/sync-activation-flags-cache-not-updated.mdx
> [DOCS] Add missing update info to v1.16 docs

- ui/app/components/dashboard/secrets-engines-card.hbs
Switch to HDS icon for ensure accessibility. 
* No visual change
files.
> UI: Use HDS icon instance for accessibility

- website/redirects.js
> [DOCS] Remove 1.19 from upgrade guide redirect (v1.19.x)

- website/redirects.js
> [DOCS] Remove 1.19 from the versioned redirect

- .release/versions.hcl
This PR sets 1.19.x `ce_active` in versions back to true to allow for backports.
files.
> re-enable 1.19.x as ce_active

- changelog/30890.txt
- vault/logical_system.go
- vault/logical_system_stubs_oss.go
- vault/plugincatalog/plugin_catalog_stubs_oss.go
Stub updates for Enterprise.
files.
> Stub updates for Ent

- ui/app/templates/components/identity/lookup-input.hbs
Adds missing aria-label to alias name dropdown on Entities page - reported in this [a11y ticket ](https://hashicorp.atlassian.net/browse/VAULT-32377)
files.
> UI: Add missing aria-label to entities alias dropdown

- website/content/api-docs/system/rekey-recovery-key.mdx
- website/content/api-docs/system/rekey.mdx
- website/content/docs/upgrading/upgrade-to-1.18.x.mdx
Original PR: https://github.com/hashicorp/vault/pull/30794
files.
> Manual backport of VAULT-36229 docs: Nonce for rekey cancellations into release/1.18.x

- website/content/api-docs/auth/azure.mdx
- website/content/docs/auth/azure.mdx
A recent update ([PR here](https://github.com/hashicorp/vault-plugin-auth-azure/pull/219)) to the Azure Auth Plugin requires that either `bound_service_principal_ids` or `bound_group_ids` be provided when creating an azure auth role in Vault. This PR updates the documentation for Vault 1.20 to accomodate this change.
files.
> Update Azure Auth Docs To State Required Parameters

- builtin/logical/transit/path_hmac.go
- builtin/logical/transit/path_hmac_test.go
- changelog/30852.txt
With `omitempty`, the` valid` field won't be returned in `batch_results` if the provided HMAC is invalid
files.
> Ensure valid field is returned when set to false

- ui/lib/config-ui/addon/components/login-settings/page/list.hbs
Adds docs link to login settings empty state
files.
> UI: Adds custom login settings link to empty state

- vault/auth.go
- vault/mount.go
- vault/observations/observations_consts.go
> VAULT-36565 CE changes

- vault/core_metrics.go
This is an OSS patch for a PR that was merged here: https://github.com/hashicorp/vault-enterprise/pull/8247
[Remove active flag from retrieve ui banners. There is actually no way to set this "active" flag in the UI so it doesn't make sense to include it.]
files.
> OSS patch: Remove active flag from ui banner metrics

- go.mod
- go.sum
Remediate https://github.com/advisories/GHSA-2x5j-vhc8-9cwm by bumping [http://github.com/cloudflare/circl](https://github.com/cloudflare/circl) to v1.6.1
This will be manually backported.
files.
> Update circl dependency to v1.6.1 to remediate GHSA-2x5j-vhc8-9cwm

- changelog/30926.txt
- scripts/ci-helper.sh
- scripts/windows/build.bat
Attempt to revert to the older behavior to not include the VCS information into the Vault binary for vault itself. This doesn't attempt to bake in the proper version as that issue wants us too as I believe we tag after the build so additional CI changes would be required to do this correctly.
This is the behavior I'm trying to get us back too as it appears in the 1.19.3 binary.
```
❯ go version -m vault_1.19.3
vault_1.19.3: go1.23.8
path    github.com/hashicorp/vault
mod     github.com/hashicorp/vault      (devel)
```
This is the 1.19.4 binary where this was reported.
```
vault_1.19.4: go1.24.3
path    github.com/hashicorp/vault
mod     github.com/hashicorp/vault      v0.0.0-20250514170447-322786e236e2+dirty
```
of a public function, even if that change is in a CE file, _double check_ …
> Add buildvcs=false to revert to older behavior of not embedding VCS info into Vault binary

- vault/core_metrics.go
This is OSS patch for an ENT PR here: https://github.com/hashicorp/vault-enterprise/pull/8275
[This PR removes error messages when config values for storage and autopilot metrics are empty. We should not log them as error messages as they are not technically failures in Vault. It also fixes wording in messages in the storage metric function.]
Jira: https://hashicorp.atlassian.net/browse/VAULT-36902
files.
> VAULT-36902: Remove error messages when max_entry_size, max_mount_entry_size and autopilot config are empty 

- .github/workflows/add-hashicorp-contributed-label.yml
Fix `failed to run git: fatal: not a git repository (or any of the parent directories): .git` error. I suspect the `gh pr edit` command recently added a new requirement in order to operate.
files.
> pipeline(actions): fix hashicorp contributed label job

- ui/tests/helpers/secret-engine/secret-engine-helpers.js
Fixes [this enterprise test failure](https://github.com/hashicorp/vault-enterprise/actions/runs/15692016702#summary-44209290728) that was introduced when #30829 was merged.
files.
> [UI] Enterprise WIF Test Failure

- changelog/fix-entity-ns.txt
- vault/identity_store_util.go
This PR fixes an error made in a previous PR (https://github.com/hashicorp/vault-enterprise/pull/7770), wherein we force the request context to match the namespace of the entity being merged. Consequently, a namespace check which should have failed would pass (specifically for entity merges). This PR reverts that change and introduces a test which would have caught the error.
Enterprise PR: https://github.com/hashicorp/vault-enterprise/pull/8145
files. …
> identity: use request context namespace for entity merges

- enos/enos-scenario-upgrade.hcl
Streamline semver constraints to update fips version only for active release branches containing both fips1402 and fips1403. This addresses a gap similar to the autopilot scenario fix that was previously implemented.
See https://github.com/hashicorp/vault-enterprise/actions/runs/15708575074/job/44263534866?pr=8290
Related: https://github.com/hashicorp/vault/pull/30831
files.
> enos(fips1403): simplify semver constraint to only consider currently mixed versions for upgrade scenario

- website/content/docs/secrets/aws.mdx
Manual backport of changes from https://github.com/hashicorp/vault/pull/30747
> [DOCS] Manual backport of Add example policy to AWS secrets engine for AssumeRole that will still be able to rotate itself into release/1.19.x

- website/content/docs/updates/important-changes.mdx
> [DOCS] Remove 1.20 note from 1.19 ic page

- website/content/api-docs/auth/kubernetes.mdx
- website/content/docs/auth/kubernetes.mdx
Currently, Vault's Kubernetes authentication method does not require roles to specify an audience. As a result, an attacker could potentially craft a malicious JWT from a compromised or rogue Kubernetes cluster and use it to authenticate against Vault, especially if the associated cluster does not validate the `aud` claim.
There has been a [PR](https://github.com/hashicorp/vault-plugin-auth-kubernetes/pull/301) that logs a warning when a user creates a role without an audience and there are [plans](https://github.com/hashicorp/vault-plugin-auth-kubernetes/pull/300) to make the `audience` field required in the 1.21 release. This PR updates the docs so that users know that future versions of Vault will require the `audience` field in k8s roles.
> Update Docs to Include Notice that Audience is Required in K8s Roles

- vault/seal/seal.go
- vault/seal_autoseal.go
Perform an immediate check when starting the seal health check.
The ENT PR is https://github.com/hashicorp/vault-enterprise/pull/8289.
files.
> Fix premature stop of seal rewrap process due to partial rewrap (CE)

- enos/enos-globals.hcl
Right now our logic for consul doesn't consider whether or not the version is available for ent or ce. Make sure that the versions we used are available for both.
files.
> enos(consul): only use versions that are CE and ENT

- vault/seal/seal.go
- vault/seal_autoseal.go
Revert "Perform an immediate check when starting the seal health check. (#31030)
This reverts commit 12bd92059ed57be7eed66ca1c41ab521d3b2562a.
Reverting as there are failures in some of the back port PRs.
files.
> Revert "Perform an immediate check when starting the seal health check. 

- builtin/credential/aws/path_login.go
- changelog/31022.txt
- go.mod
- go.sum
- sdk/framework/backend.go
- sdk/go.mod
- sdk/go.sum
- vault/external_tests/interned_regexp/interned_regexp_test.go
> [VAULT-21456] Use interned regexp when initialising backends and validating authz headers in the AWS backend

- ui/app/components/namespace-picker.hbs
- ui/app/components/namespace-picker.ts
- ui/app/routes/vault/cluster/access/namespaces/index.js
- ui/app/templates/vault/cluster/access/namespaces/index.hbs
- ui/lib/config-ui/addon/components/messages/page/list.hbs
- ui/lib/core/addon/components/filter-input-explicit.hbs
- ui/tests/acceptance/access/namespaces/index-test.js
- ui/tests/acceptance/auth/auth-test.js
- ui/tests/acceptance/config-ui/messages/messages-test.js
- ui/tests/acceptance/config-ui/messages/messages-unauth-auth-test.js
- ui/tests/acceptance/dashboard-test.js
- ui/tests/acceptance/enterprise-namespaces-test.js
- ui/tests/acceptance/secrets/backend/kubernetes/roles-test.js
- ui/tests/acceptance/sync/secrets/destination-test.js
- ui/tests/acceptance/sync/secrets/destinations-test.js
- ui/tests/helpers/config-ui/message-selectors.ts
- ui/tests/helpers/general-selectors.ts
- ui/tests/helpers/namespace-picker.js
- ui/tests/integration/components/config-ui/messages/page/list-test.js
- ui/tests/integration/components/filter-input-explicit-test.js
- ui/tests/integration/components/namespace-picker-test.js
- ui/tests/integration/components/sidebar/frame-test.js
Refactors and improves the namespace picker and config-ui/message tests. We remove duplication between component and acceptance tests. I also added a cleanup test in the config-ui/messages because we continue to have issues there especially if you are debugging any of the tests. This test should clean up the state of authenticated messages and reduce flakyness.
**Key Changes**
Namespace Picker
- Updated `data-test attributes` for clarity and consistency (e.g., `data-test-toggle-input="namespace-picker"`, `data-test-button`, `data-test-input="Search namespaces"`).
- Improved width calculation and accessibility for the picker dropdown.
Testing Improvements
- Refactored acceptance and integration tests to use new selectors and patterns.
- Consolidated selector logic and removed the obsolete …
> Address flaky tests: namespace and config-ui/messages

- website/content/docs/ui/namespaces.mdx
| BEFORE | AFTER |
| -- | -- |
| ![screencapture-developer-hashicorp-vault-docs-v1-20-x-ui-namespaces-2025-06-23-14_33_04](https://github.com/user-attachments/assets/7f01394f-b79a-46fd-bf95-adfb414cca24) | ![screencapture-localhost-3000-vault-docs-v1-20-x-ui-namespaces-2025-06-23-14_33_22](https://github.com/user-attachments/assets/19e20155-4d26-409c-865c-58811f016d84) |
files.
> [VAULT-34486] Docs: fix broken images

- website/content/api-docs/system/internal-ui-namespaces.mdx
> [VAULT-34485] UI: Internal namespace documentation updates

- ui/lib/open-api-explorer/addon/components/swagger-ui.js
- ui/mirage/factories/open-api-explorer.js
- ui/tests/integration/components/open-api-explorer/swagger-ui-test.js
This PR addresses a severe accessibility concern on the swagger ui page. 
**Problem**: Parameter inputs are disabled until the `Try it out` button is clicked which makes them inaccessible to keyboard users or screen readers. 
**Solution**: After the swagger ui completes rendering and an operation block is expanded, the parameter input's `disabled` attribute will be removed and replaced with `readonly`. This preserves the original behavior of making the inputs immutable until the `Try it out` button is clicked, but makes them accessible.
Tests have also been updated confirming these a11y fixes are applied. This will protect us in the instance that we upgrade the swagger version and an assumption we're making about the HTML breaks the a11y fixes. 
of a public function, even if that change …
> UI: A11y fix for disabled swagger interarctive

- buf.yaml
Fix `buf lint` errors that cause the code checks workflow to fail. It appears that this began after a new file was added here: https://github.com/hashicorp/vault/pull/31054. This PR adds the exclusions to the buf linter config.
files.
> ci(code-checks): fix buf lint linter errors for new proto files

- go.mod
- vault/quotas/quotas_rate_limit_test.go
This test has been sporadically failing and after some investigation we are fairly confident this is not actual issue, but just an artifact of trying to inspect go internal stuff. As we won't be putting any more time into the investigation I'm removing the test entirely, as well as the goleak library which was only used in this one test.
Another argument for removing it is that it's basically testing the library behavior, that when close is called it should stop the goroutines spawned.
Jira: [VAULT-36611](https://hashicorp.atlassian.net/browse/VAULT-36611)
- [-] **Backport Labels:** If this fix needs to be backported, use the appropriate `backport/` label that matches the desired release branch. Note that in the CE repo, the latest release branch will look like `backport/x.x.x`, but older …
> VAULT-36611 remove goleak test

- vault/observations/observations_consts.go
Small fix to the observation type names  from `*MountNamespace*` to `*Namespace*`
files.
> Fix small typo in observation type

- changelog/31094.txt
- ui/app/routes/vault/cluster/auth.js
- ui/lib/sync/addon/components/secrets/page/destinations/destination/sync.ts
- ui/tests/acceptance/auth/auth-login-test.js
- ui/tests/acceptance/auth/login-settings-test.js
- ui/tests/acceptance/secret-engine-list-view-test.js
- ui/tests/helpers/auth/auth-helpers.ts
- ui/tests/integration/components/auth/form-template-test.js
- ui/tests/integration/components/auth/page-test.js
- ui/tests/integration/components/auth/tabs-test.js
Backport https://github.com/hashicorp/vault/pull/31094
files.
> Backport 1.20.x UI: Revert api service use for requests to sys/internal/ui/mounts

- website/content/api-docs/system/leases.mdx
The current [Sample request](https://developer.hashicorp.com/vault/api-docs/system/leases#sample-request-8) of the [API: `/sys/leases` & `/sys/leases/count`](https://developer.hashicorp.com/vault/api-docs/system/leases#lease-counts) are not correct where `-d type=irrevocable` should in fact be query-strings like: `?type=irrevocable`.
> Docs: Leases list API corrected required query-strings parameters.

- website/content/api-docs/system/leases.mdx
* Docs: Leases list API corrected required query-strings parameters.
* Docs: Leases list API corrected required query-strings parameters & quotes for &
files.
> Manual backport of #31123 to 1.19.x

- website/content/api-docs/system/leases.mdx
* Docs: Leases list API corrected required query-strings parameters.
* Docs: Leases list API corrected required query-strings parameters & quotes for &
files.
> Manual backport of #31123 to 1.18.x

- website/content/api-docs/system/leases.mdx
* Docs: Leases list API corrected required query-strings parameters.
* Docs: Leases list API corrected required query-strings parameters & quotes for &
files.
> Manual backport of #31123 to 1.17.x

- ui/tests/acceptance/secret-engine-list-view-test.js
Fixes failing ENT tests with asserting secret engines being shown to a user according to namespace permission
files.
> UI: Fix failing secret engine ENT tests with ns

- ui/tests/acceptance/secret-engine-list-view-test.js
> Backport of UI: Fix failing secret engine ENT tests with ns (#31099)

- changelog/31136.txt
- ui/lib/kv/addon/routes/secret.js
- ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-edge-cases-test.js
The new api service returns capabilities camel-cased instead of matching the original path one to one so [this map](https://github.com/hashicorp/vault/blob/main/ui/app/services/capabilities.ts#L96) fails and returns a false positive that a user can read subkeys. 
It's unusual for a capability check to fail, but it's always been the pattern that if a capability check errors we return true and let the API handle permissions as a fallback. However, in this case the false positive means entering a conditional that then attempts to destructure an undefined object which is what surfaces this error. 
This does not address the larger api path manipulation, but instead adds a default for to `subkeysMeta` which should have been there all along. (This is why typescript is so …
> UI: Fixes kv v2 secret overview for failed subkeys policy check for secrets with underscores

- ui/lib/core/addon/components/form-field.hbs
- ui/lib/core/addon/components/form-field.js
- ui/tests/acceptance/secrets/backend/ssh/configuration-test.js
- ui/tests/acceptance/secrets/backend/totp/key-test.js
- ui/tests/integration/components/form-field-test.js
- updated logic in `isHdsFormField` of `FormField` to include the `type|editType === 'boolean'` use cases
- moved template logic for `type|editType === 'boolean'` in `FormField` under the `isHdsField` block
- fix a couple of failing tests by updating the selectors to match the new DOM structure
Jira ticket: https://hashicorp.atlassian.net/browse/VAULT-34798
**Before**:
**After**:
files.
> [VAULT-34798] UI: move the `boolean` block in `FormField` under the HDS block

- ui/app/components/secret-list/totp-list-item.hbs
HDS `v4.12.0` deprecated passing `@text` to `Hds::Dropdown` list items in favor of yielding. This was updated in https://github.com/hashicorp/vault/pull/28525 but the new [TOTP feature](https://github.com/hashicorp/vault/pull/29751) (which originated from a community PR based off of an older branch) still used the deprecated pattern. This PR updates it. (I came across the deprecation error while trying to update tests to run in parallel)
files.
description. Also, make sure the changelog is in this PR, _not_ in …
> UI: Yield HDS dropdown text

- ui/tests/acceptance/access/namespaces/index-test.js
- ui/tests/acceptance/auth/auth-list-test.js
- ui/tests/acceptance/auth/login-settings-test.js
- ui/tests/acceptance/dashboard-test.js
- ui/tests/acceptance/enterprise-namespaces-test.js
- ui/tests/acceptance/enterprise-oidc-namespace-test.js
- ui/tests/acceptance/reduced-disclosure-test.js
- ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-edge-cases-test.js
- ui/tests/acceptance/sync/secrets/overview-test.js
✅ enterprise tests pass 
Follow-on to this PR https://github.com/hashicorp/vault/pull/31016 which added `deleteNS` commands to cleanup namespaces, however the command was not being run from the `root` namespace so the command was not actually deleting the namespace. 
I noticed this because a test failure checking for an empty state in the namespace list view returned a list of namespaces
files.
> UI: Stabilize namespace tests

- changelog/31150.txt
- ui/app/app.js
- ui/app/components/secret-list/totp-list-item.hbs
- ui/lib/config-ui/addon/components/login-settings/page/list.hbs
- ui/lib/config-ui/addon/engine.js
- ui/lib/config-ui/addon/routes/login-settings/index.js
- ui/tests/acceptance/config-ui/login-settings-test.js
Reverts the use of the api service in the login settings list view. The api service camelizes keys which mutates the server response. This means the `key_info` would not properly map to the key in the `keys` array. Until we resolve this in the api service itself, reverting the use in the login settings list view.
**actual**
```
{
"key_info": {
"test_rule": {
"name": "test_rule",
"namespace_path": "fake/",
"disable_inheritance": false
}
},
"keys": [
"test_rule"
]
}
```
**response from request made via api service**
```
{
"keyInfo": {
"testRule": {
"name": "test_rule",
"namespacePath": "fake/",
"disableInheritance": false
}
},
"keys": [
"test_rule"
]
}
```
applying the patch for this PR to the ENT repo and …
> UI: Fix login settings list view if names include an underscore

- website/redirects.js
Adds a redirect for URLs with two version slugs that strips out the extra version slug
> [DOCS] Add redirect to correct double versioning

- website/redirects.js
Adds a redirect for URLs with two version slugs that strips out the extra version slug
> [DOCS] Add redirect to remove double version slug

- .github/actionlint.yml
- .github/workflows/copy-external-contributor-pull-request-ce.yml
A follow-up to https://github.com/hashicorp/vault/pull/31095 that creates a "deployment" that will trigger the pull request copy workflow in enterprise.
As this is intended to be a `repository_dispatch` into `vault/enterprise` we'll need to hold off merging it until after the corresponding enterprise pull request has been merged. We also have two other considerations. The first is that we expect this to normally be triggered from fork PR's, but we don't actually want to turn this on until after the migration to the new workflow. That leaves us with `workflow_dispatch` as an adhoc way to test before then. However, `workflow_dispatch` jobs are required to be on main before you can run them (🐔 meet 🥚), so we have to merge this to test it 🙃.
As this will only be run on active CE branches we …
> [VAULT-34827]: pipeline(actions): add workflow to trigger the enterprise pull request copier

- website/content/docs/platform/servicenow/configuration.mdx
Confirmed Yokohama is compatible with HashiCorp Vault, there is a work around which is listed under the In the ServiceNow UI.
files.
> ServiceNow Update to Yokohama work around

- .github/pull_request_template.md
> VAULT-36002 update pull_request_template.md for PCI

- .github/workflows/benchmark-prevent-performance-degradations.yml
Disables the benchmark GHA
files.
> Disable bench GHA

- ui/app/services/flags.ts
- ui/tests/acceptance/sync/secrets/overview-test.js
There seem to be some timing issues with cleanup in the `afterEach` hook and the stubbed mirage endpoint. `req.passthrough()` didn't consistently return a response in time so the `.includes()` check here would fail because `this.activatedFlags` would return undefined ([here](https://github.com/hashicorp/vault/blob/3f7b8a66714b10080ccd0b50e6953de8fc7676bf/ui/app/services/flags.ts#L60))
Moving the cleanup directly into the test and manually stubbing the response _seems_ to have resolved the flakiness 🤞 
> [vault] not ok 1 Chrome 128.0 - [2333 ms] - Acceptance | sync | overview > when feature is not activated > enterprise with namespaces: it should make activation-flag requests to correct namespace when managed
[vault]     ---
[vault]         stack: >
[vault]             TypeError: Cannot …
> UI: Fix flaky secrets-sync test with optional chaining

- .github/workflows/build.yml
In anticipation of our reversed merge workflow we need to ensure that no enterprise files are added to `ce/` branches originally hosted in `hashicorp/vault-enterprise`. We can do that by looking at the PR changed files and their associated groups to determine if such has occurred.
This was tested on two commits on enterprise: https://github.com/hashicorp/vault-enterprise/actions/runs/16037841447/job/45253499258?pr=8404
files.
Examples …
> [VAULT-36232] pipeline(changed-files): fail if we change enterprise files on ce/* branches

- ui/app/components/secret-list/totp-list-item.hbs
- website/content/docs/updates/important-changes.mdx
- website/content/partials/release-notes/change-summary/1_20.mdx
Adds a known issue to the docs
(Issue fixed by PR: https://github.com/hashicorp/vault/pull/31136)
files.
> UI: Known issue for KV v2 secrets containing underscores if no `read` permissions for the `subkeys` endpoint

- ui/lib/core/addon/components/text-file.hbs
- ui/tests/acceptance/pki/pki-action-forms-test.js
- ui/tests/acceptance/pki/pki-cross-sign-test.js
- ui/tests/acceptance/pki/pki-engine-workflow-test.js
- ui/tests/acceptance/secrets/backend/gcp/gcp-configuration-test.js
- ui/tests/helpers/general-selectors.ts
- ui/tests/helpers/secret-engine/secret-engine-helpers.js
- ui/tests/helpers/sync/sync-selectors.js
- ui/tests/integration/components/form-field-test.js
- ui/tests/integration/components/pki/page/pki-issuer-import-test.js
- ui/tests/integration/components/pki/pki-import-pem-bundle-test.js
- ui/tests/integration/components/text-file-test.js
> 268 tests completed in 175979 milliseconds, with 0 failed, 10 skipped, and 0 todo.
1523 assertions of 1523 passed, 0 failed.
> [VAULT-37111] UI: use general selector for textarea toggle

- changelog/31223.txt
- website/content/docs/updates/important-changes.mdx
- website/content/partials/release-notes/change-summary/1_20.mdx
Update the development cluster known issue created in 1.20.0 as fixed for 1.20.1. Also add a changelog entry. The known issue was created in https://github.com/hashicorp/vault/pull/31067. The actual fix was merged in https://github.com/hashicorp/vault-enterprise/pull/8325. 
Jira for the bug: https://hashicorp.atlassian.net/browse/VAULT-37317
files.
Examples of changes to security controls include using new access control methods, …
> Update development cluster known issue as fixed

- audit/backend.go
- audit/backend_file.go
- audit/backend_file_ce_test.go
- audit/backend_file_test.go
- audit/entry_formatter_config.go
- changelog/31211.txt
- command/server.go
- command/server/config.go
- command/server/config_test_helpers.go
- http/sys_config_state_test.go
- vault/audit.go
- vault/core.go
- website/content/docs/configuration/index.mdx
> Add additional validations to the destination and properties of file audit sinks

- website/content/docs/sysadmin/snapshots/restore.mdx
- Correct unseal example for CLI in snapshot restore documentation
files.
> Docs: update restore snapshot content

- builtin/credential/userpass/path_login.go
Updates the user pass dummy string, see https://github.com/hashicorp/vault-enterprise/pull/8418
> auth/userpass: update dummy string

- tools/pipeline/internal/cmd/github.go
- tools/pipeline/internal/cmd/github_copy_pull_request.go
- tools/pipeline/internal/cmd/github_sync.go
- tools/pipeline/internal/cmd/github_sync_branch.go
- tools/pipeline/internal/pkg/git/client.go
- tools/pipeline/internal/pkg/github/copy_pull_request.go
- tools/pipeline/internal/pkg/github/create_backport.go
- tools/pipeline/internal/pkg/github/list_workflow_runs_test.go
- tools/pipeline/internal/pkg/github/sync_branch_request.go
- tools/pipeline/internal/pkg/github/templates_test.go
- tools/pipeline/internal/pkg/github/workflow_run_summary.go
Add a new `pipeline github sync branches` command that can synchronize two branches. We'll use this to synchronize the
`hashicorp/vault-enterprise/ce/*` branches with `hashicorp/vault/*`.
As the community repository is effectively a mirror of what is hosted in Enterprise, a scheduled sync cadence is probably fine. Eventually we'll hook the workflow and sync into the release pipeline to ensure that `hashicorp/vault` branches are up-to-date when cutting community releases.
As part of this I also fixed a few static analysis issues that popped up when running `golangci-lint` and fixed a few smaller bugs.
break any tests. Sometimes ENT only …
> [VAULT-32028] pipeline(github): add `sync branches` sub-command

- enos/modules/verify_log_secrets/main.tf
Updates the version of Radar that Enos uses to the most recent version
files.
> (enos) Update Vault Radar version

- website/content/docs/enterprise/audit/filtering.mdx
We've noticed that users often find the audit filtering page, but miss the related page for filtering. This is probably because the two aren't linked to each other. This is an attempt to make this a little bit better. I tried to follow (what I think is) the existing pattern, but I am not sure if I got it right.
files.
> Add links to the filtering concept page and the audit API page to the audit filtering doc

- website/content/docs/updates/important-changes.mdx
Documents a known issue and adds a workaround.
> Add known issue and workaround for Snowflake Keypair connection timeouts

- changelog/31271.txt
- ui/app/services/capabilities.ts
- ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-create-test.js
- ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-delete-test.js
- ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-edge-cases-test.js
- ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-navigation-test.js
- ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-version-history-paths-test.js
- ui/tests/unit/services/capabilities-test.js
Resolves a regression introduced by https://github.com/hashicorp/vault/pull/30222 that mutated any paths containing underscores sent to the [sys/capabilities check](https://developer.hashicorp.com/vault/api-docs/system/capabilities-self) by returning them as camel-cased.
For example if the path payload was: `kvv2_admin/metadata/my_secret` the api service would return:
```js
"data": {
"kvv2Admin/metadata/mySecret": [
"read"
],
}
```
This means the `mapCapabilities` [method](https://github.com/hashicorp/vault/blob/main/ui/app/services/capabilities.ts#L47) incorrectly mapped permissions because it would not be able to match the original path to the mutated, camel-cased version. The result is some dropdown items and actions would display that a user may not have …
> UI: Revert api service request in capabilities service

- website/content/api-docs/secret/ldap.mdx
> LDAP Secrets Engine api documentation: URL to external link is broken, this PR corrects the URL

- website/content/docs/internals/telemetry/key-metrics.mdx
added runtime metrics to Resource metrics section
files.
> Update key-metrics.mdx to add runtime metrics

- website/content/docs/auth/gcp.mdx
Fix small docs formatting error causing a text block instead of bulleted list.
Before: The block in step 3 here below the line "To configure a trusted relationship between Vault and GCP:" https://developer.hashicorp.com/vault/docs/auth/gcp#configuration
After: Same block in step 3 is now a bulleted list https://vault-pj6mvl375-hashicorp.vercel.app/vault/docs/auth/gcp#configuration
> Fix gcp auth trust relationship requirements textblock

- changelog/31287.txt
- ui/app/components/control-group-success.js
- ui/app/components/tools/unwrap.ts
- ui/tests/acceptance/tools-test.js
- ui/tests/integration/components/control-group-success-test.js
- ui/tests/integration/components/tools/unwrap-test.js
The api service returns camel-cased keys so if a key contained an underscore unwrapping the data would return the value camel cased. Replacing the api service in calls to `sys/wrapping/unwrap` ([docs](https://developer.hashicorp.com/vault/api-docs/system/wrapping-unwrap)) for unwrapping data. This is only going in to 1.20 because for 1.21 the issue will be addressed upstream. 
Test coverage was added before the request was replaced.
| data to wrap                                                                                                                                         | unwrapped data                                                                                                                                       |
| …
> UI: Revert api service for unwrapping data

- website/content/api-docs/secret/transit.mdx
> Add mac_length to verify docs

- website/content/api-docs/auth/jwt.mdx
- website/content/docs/auth/jwt/index.mdx
Backport of https://github.com/hashicorp/vault/pull/30519 into 1.17.x.
files.
> Backport of Update Docs For Bound Audience Explanation (#30519)

- ui/app/components/namespace-picker.hbs
- ui/app/components/namespace-picker.ts
- ui/tests/integration/components/namespace-picker-test.js
The [previous namespace picker](https://github.com/hashicorp/vault/pull/30490/files#diff-b5c15d9ca82ad8f80680ec98014281bf0533f7ed9da72bddfcf70a4b04890c4bL43) made a request to [sys/namespaces](https://developer.hashicorp.com/vault/api-docs/system/namespaces) and so “refresh list” was wrapped in the relevant capabilities. The new namespace picker makes a request to [sys/internal/ui/namespaces](https://developer.hashicorp.com/vault/api-docs/system/internal-ui-namespaces) which is an endpoint that any user has access to (it is not policy gated) and so these capabilities do not need to wrap that button.
break any tests. Sometimes ENT only …
> UI: Remove capabilities check from namespace picker refresh list button

- changelog/31326.txt
- ui/app/components/namespace-picker.hbs
- ui/app/components/namespace-picker.ts
- ui/tests/integration/components/namespace-picker-test.js
The namespace picker was using the node as the `id` key (the segment of the current namespace context) which was used to select a namespace. However, a namespace path could have matching nodes so it may not be a unique value. Updated the namespace picker select a namespace by the full path which is unique.
files.
Examples of changes to security controls include using new access control methods, adding or removing logging pipelines, …
> UI: Fix namespace picker selecting all namespaces with matching nodes

- website/redirects.js
> Add missing redirects for UDR migration

- builtin/credential/userpass/path_login.go
Ensures the dummy string goes through the same code path as any password
> auth/userpass: update dummy string generation

- vault/external_tests/identity/login_mfa_totp_test.go
- vault/login_mfa.go
normalizes the loginmfa totp code and adjusts the used code cache duration
> login/mfa: update loginmfa cache and tests

- builtin/credential/userpass/path_login.go
follow up to #31318 which did not have the intended effect
> update user pass dummy string

- ui/tests/acceptance/auth/auth-login-test.js
- ui/tests/acceptance/config-ui/login-settings-test.js
Fixes a couple of enterprise tests that were failing from #31347 
files.
> [UI] Enterprise Test Fixes

- changelog/31331.txt
- sdk/framework/openapi.go
- sdk/framework/openapi_test.go
- sdk/framework/testdata/operations.json
- vault/logical_cubbyhole.go
This PR adds support to the secret recovery operations on the API explorer module.
Jira: [VAULT-35087](https://hashicorp.atlassian.net/browse/VAULT-35087)
- - ] **ENT Breakage:** If this PR either 1) removes a public function OR 2) changes the signature
applying the patch for this PR to the ENT repo and running …
> VAULT-35087: add Open-API support for secret recovery operations

- api/cliconfig/config_test.go
- api/cliconfig/hcl_dup_attr_deprecation.go
- api/hcl_dup_attr_deprecation.go
- api/ssh_agent_test.go
- changelog/31215.txt
- command/agent_test.go
- command/login_test.go
- command/operator_migrate_test.go
- command/policy_fmt_test.go
- command/proxy_test.go
- command/server/config.go
- command/server/config_test_helpers.go
- helper/random/parser.go
- vault/logical_system_test.go
- vault/policy_store_test.go
- website/content/docs/updates/deprecation.mdx
- website/content/partials/deprecation/duplicate-hcl-attributes.mdx
This is a follow up to #30386, which went into Vault v1.20 (and backported to v1.1.6) and started to print warnings whenever Vault parsed any HCL with duplicate attributes, as well as returning some API warnings when creating policies with those duplicate attributes in their HCL definition.
Continuing to follow our deprecation process, this PR changes those warnings to be actual errors, preventing the parsing of HCL files containing duplicate attributes in Vault v1.21.x. The previous "log-only" behavior of v1.20.x can be restored in v1.21.x by setting the `VAULT_ALLOW_PENDING_REMOVAL_DUPLICATE_HCL_ATTRIBUTES` to `true`.
I'm also rectifying the deprecation notice for duplicate attributes, which was incorrectly added directly to the "pending removal" stage in #30512. As for updating it to …
> VAULT-35838: advance deprecation of duplicate HCL attributes to pending removal stage

- tools/pipeline/internal/cmd/github_sync_branch.go
Fix the default value of `to-repo` for the `pipeline github sync branch` command.
files.
> pipeline(github sync branch): fix default to-repo

- ui/tests/acceptance/settings/mount-secret-backend-test.js
Addressing a flaky test for duplicate path name, as its come up failing in the vault CI a bit more recently.
It locally has what seems like a 99.9% pass rate 
(was able to make it fail twice locally out like 200+ tries - and only in firefox browser)
Adding `await settled();` right before the dom check seems to have helped that .1% 
(havent seen it fail locally in firefox since)
files.
Examples of changes to …
> UI: Fix flaky test for duplicate path name

- ui/app/components/transform-edit-form.js
After merging the template colocation change, enterprise tests failed with this stack trace:
```
Acceptance | Enterprise | Transform secrets: it shows a message if an update fails after save: Chrome 128.0
global failure: Error: Cannot call `setComponentTemplate` multiple times on the same class (`Class`)
Source:
Error: Cannot call setComponentTemplate multiple times on the same class (Class) at setComponentTemplate`
```
It turns out that this the `transform-edit-form` component was just re-exporting another component class, which was already used by `setComponentTemplate`, so the fix for this is to add `extend()` when re-exporting so it's a different class by the time it gets compiled. The associated template did get moved in the colocation change, but I'm not sure why it being in the …
> [UI] - fix error on transform-edit-form component

- ui/app/components/dashboard/replication-card.hbs
- ui/app/components/dashboard/replication-state-text.hbs
- ui/tests/helpers/components/dashboard/dashboard-selectors.js
This PR replaces the internal `ToolTip` component with the HDS Tooltip. We also do a small language tweak to make the card a bit more understandable.
NOTE: I think the _need_ for this tooltip is highly debatable. But I'm not here to change everything I don't need to change! I'm here to change the a subset of random things I don't need to change...
jira: https://hashicorp.atlassian.net/browse/VAULT-38495
Before:
After:
Thankfully, you can just lie about the primary cluster being in replication state:
- launch the UI against an ent cluster locally
- replication -> enable DR and/or PR
- back to the dashboard page
- BEHOLD!
✅  - ent tests pass …
> [UI] - Replace tooltip and tweak working on for replication dash card

- changelog/31422.txt
- vault/activity_log.go
- vault/external_tests/activity_testonly/activity_testonly_test.go
- vault/logical_system_activity_write_testonly.go
- vault/logical_system_activity_write_testonly_test.go
Jira: https://hashicorp.atlassian.net/browse/VAULT-37794
Approved ent: https://github.com/hashicorp/vault-enterprise/pull/8501
files.
> Export api changes to add first used timestamp column in query period - CE changes

- builtin/credential/ldap/backend.go
- builtin/credential/ldap/path_login.go
- sdk/helper/ldaputil/client.go
[ent: a552ac1e80e3d334673c59a5bb825082cd56b1bf]
files.
> auth/ldap: ensure consistent entity aliasing when set from the username

- builtin/credential/ldap/backend.go
- builtin/credential/ldap/path_login.go
- sdk/helper/ldaputil/client.go
Backports https://github.com/hashicorp/vault/pull/31427 into release/1.20.x branch
> Manual backport for #31427 in for 1.20.x

- changelog/31443.txt
- physical/raft/raft_autopilot.go
This PR updates autopilot to persist redundancy zones for the nodes in the cluster, and use the persisted zone a node hasn't contacted the leader.
Enterprise PR: https://github.com/hashicorp/vault-enterprise/pull/8566
files.
> VAULT-37080: Maintain redundancy zones for unhealthy nodes

- api/sys_utilization_report.go
This PR updates the utilization report API client to include namespace as a parameter. This is to support the namespace filter changes introduced on the utilization report API.
files.
> Updating utilization report API client

- enos/enos-scenario-autopilot.hcl
> VAULT-30196: Use updated vault cluster for autopilot

- ui/app/components/secret-engine/list.hbs
Per new designs for the secret engines plugin work (and HDS standards) action buttons that navigate away from the page need to be separated out of the toolbar since items in the toolbar should focus manipulating data thats displayed on the current page (ie. filtering etc)
No functionality with the button has changed, simply pulled out of toolbar and made as its own button, clicking the button routes user to select a secret engine as expected.
*More follow-up visual updates to the list page will come as plugin work continues
| Before | After |
|--------|--------|
| <img width="1061" height="329" alt="image" src="https://github.com/user-attachments/assets/29cc47f1-4c6d-442c-af62-d73efffd617d" /> | <img width="1061" height="329" alt="image" …
> UI: moving CTA out from toolbar into separate hds button on secret engines page

- ui/app/components/secret-form-show.hbs
- ui/app/models/secret.js
- ui/package.json
- ui/tests/acceptance/enterprise-replication-test.js
- ui/yarn.lock
This PR upgrades `@hashicorp/design-system-components` to 4.20.1 ([release notes](https://helios.hashicorp.design/whats-new/release-notes#4201)) to get a bug fix for an issue that prevented the `AdvancedTable` from updating when the argument changes
This is a blocker to implement Hds::AdvancedTable for the client count work for 1.21 and work in PR https://github.com/hashicorp/vault/pull/31439
files.
Examples of changes to security …
> UI: Upgrade to HDS 4.20.1

- ui/app/components/secret-engine/security-card.hbs
- ui/app/components/secret-engine/security-card.ts
- ui/app/templates/vault/cluster/secrets/backend/configuration/index.hbs
***Non customer facing until parent component is completed & wired up***
[Per new designs](https://www.figma.com/design/YVOfvCoypjzxr758OT6hvj/Plugin-management?node-id=786-58263&t=FKRmN1Z6XZ8eHUvZ-1) - Creating a new 'Security' card component with toggle buttons as part of secret engine configuration tuning
Will currently live in its own component, but could be merged into parent component if we decide to go that route
Usage ---> `<SecretEngine::SecurityCard @model={{this.model.secretsEngine}} />`
| Design | Current Implementation (can change once put into parent comp) |
|--------|--------|
| <img width="401" height="224" alt="image" src="https://github.com/user-attachments/assets/bd15fbd5-f490-4a02-b8c8-5fb0c25120c4" /> | <img width="563" height="172" alt="image" …
> UI: Security card component for new configuration page

- ui/app/components/oidc/assignment-form.hbs
- ui/app/styles/components/popup-menu.scss
- ui/app/styles/components/search-select.scss
- ui/lib/core/addon/components/search-select-with-modal.hbs
- ui/lib/core/addon/components/search-select.hbs
- ui/lib/core/addon/components/search-select.js
- ui/lib/kubernetes/addon/components/page/overview.hbs
- ui/lib/ldap/addon/components/page/overview.hbs
- ui/lib/pki/addon/components/page/pki-overview.hbs
- ui/lib/replication/addon/components/path-filter-config-list.hbs
- ui/lib/sync/addon/components/secrets/page/destinations.hbs
- ui/lib/sync/addon/components/secrets/page/destinations/destination/sync.hbs
Using the [Hds::SuperSelect](https://helios.hashicorp.design/components/form/super-select) component is not possible right now because there are a lot of manual overrides for `.ember-power-select-` in our css. This PR is to unblock new features from using the HDS component by only applying those overrides to the custom `SearchSelect` component. 
https://github.com/user-attachments/assets/5cf870ed-e5f6-4a1a-9e09-1c49332dd4b6
https://github.com/user-attachments/assets/858aefab-bf0d-4583-8fac-e436e7865181
<hr> 
files.
in the PR description, commit message, or branch …
> UI: wrap ember-power-select- overrides so Hds::SuperSelect is usable

- .github/workflows/plugin-update.yml
Support updating both CE and Enterprise plugins when the plugin update workflow targets `vault-enterprise` instead of CE.
This needs to be merged in conjunction with https://github.com/hashicorp/vault-plugin-release/pull/62 right before we do the merge workflow cutover.
files.
> VAULT-34830 actions(plugin-update): update plugins from enterprise

- helper/testhelpers/ldap/ldaphelper.go
Pass in a context with a timeout of 1 minute to ensure we always short circuit in CI if the container fails to start up.
files.
> testhelpers(ldap): always time out if we can't start the container in 1 minute
