hashicorp/vault

website/source/docs/secrets/consul/index.html.md
=> msyql to consul on consul backend docs

.travis.yml
:red_circle: :construction: :construction_worker:
=> Install godep

website/source/intro/getting-started/first-secret.html.md
First secret in getting started has broken link.
=> Fixed link to HTTP API

.gitignore, Makefile, scripts/coverage.sh
Was broken since go test cannot handle multiple packages
=> Make make cover work

.travis.yml, http/logical_test.go, vault/audit_test.go, vault/auth_test.go, vault/core_test.go, vault/expiration_test.go, vault/mount_test.go, vault/testing.go
**DO NOT MERGE!**
:red_circle: :construction: :construction_worker: 
**DO NOT MERGE!**
=> Require sudo in Travis

physical/file.go
Open a file, create it if it doesn't exist, and for gods sake don't leave it 0666.
=> Sensible permissions on creating a file

make.bat, scripts/windows/build.bat
=> make.bat: add Makefile-like functionality for Windows

vault/barrier_aes_gcm_test.go
Not likely to fail, but if it did would result in complete failure, so
probably good to have a test for it.
=> Add test that ensure keylength check is working

command/format.go
I got the following and it will fix that.
```
$ vault read secret/hello
Key            	Value
lease_id       	secret/hello/f83e12b9-3470-6bea-9e7b-193e806ecae3
lease_duration 	2592000
lease_renewable	%!d(string=false)
to             	world
value          	hello
```
=> Fix lease_renewable output

builtin/credential/github/cli.go
Fixes https://github.com/hashicorp/vault/issues/159
=> Fix output from GitHub help

website/source/docs/auth/userpass.html.md
In response to Issue #155
Looking through the logs allowed me to figure out how authenticate, via userpass, over the HTTP API.
=> In response to Issue #155

physical/consul.go
=> pysical: minor doc error in consul

builtin/credential/github/backend_test.go
This fix a very small mis typo.
Thanks
=> Fix Error message

physical/physical_test.go, physical/zookeeper.go
* multiple Puts to the same node causes zk errors
=> fixes #189; zk version conflict

website/source/intro/vs/chef-puppet-etc.html.md
Fixes a minor typo I found when reading some of the Vault docs.
=> Fix minor documentation typo.

website/source/intro/vs/keywhiz.html.md
=> update info on keywhiz vs vault

builtin/credential/app-id/backend_test.go, logical/framework/path_map.go, logical/framework/path_map_test.go, logical/framework/path_struct.go, logical/framework/path_struct_test.go
Fixes #191 
Adds necessary delete support to PathMap and PathStruct.
=> credential/app-id: Support deleting user-ids from mapping

api/client.go
=> Improve error message when TLS is disabled

command/server.go
Fixes https://github.com/hashicorp/vault/issues/197
=> Explicitly check if tls_disable == 1

command/unseal.go
=> Improve unseal CLI message

website/source/docs/internals/architecture.html.md, website/source/docs/internals/security.html.md
I fixed a couple of minor typos I noticed reading through the docs. 
Thanks for writing documentation! <3
=> Minor documentation typo fixes.

builtin/credential/ldap/path_login.go
=> Allow dot in LDAP login username

command/read.go, command/read_test.go, website/source/docs/commands/read-write.html.md
=> Add ability to read raw field from secret

website/source/docs/http/libraries.html.md, website/source/layouts/http.erb
These are all the libraries I could find so far. They should have tests and be feature complete.
=> Add libraries section to HTTP docs

website/source/docs/commands/help.html.md, website/source/docs/concepts/ha.html.markdown, website/source/docs/config/index.html.md, website/source/docs/secrets/index.html.md
Small changes to maintain consistency in documentation.
=> replaced confusing term 'physical' with 'storage'. Fix for #262

website/source/docs/config/index.html.md, website/source/intro/getting-started/deploy.html.md
Refers to hashicorp/vault#122.
=> Document unprivileged mlock on Linux

website/source/docs/concepts/dev-server.html.md
- "You" as subject instead of "Vault"
- give the actual command
- minor formatting changes
=> Put me in charge of dev mode :)

.gitignore, Makefile, README.md
Added Makefile target to bootstrap external tools
=> Makefile bootstrap

website/source/docs/auth/ldap.html.md, website/source/docs/auth/userpass.html.md
=> docs: Fix examples of auth via JSON

http/sys_mount.go, http/sys_mount_test.go
=> Accept PUT as well as post to sys/mounts

physical/mysql.go, physical/mysql_test.go, physical/physical.go
I am new to Golang. I followed the logic in existing backends and tried to port it for MySQL. I am not sure if having MySQL as one of the physical makes sense or not. Kindly please review the code and provide me feedback.
Thank you !!
=> MySQL physical backend implementation

helper/password/password_unix.go
Allow this file to build on FreeBSD. Fixes #136
=> allow building on FreeBSD

http/handler.go, vault/router.go, vault/router_test.go
Trying to get more meaningful http responses back for some operations
=> Better http responses

Godeps/Godeps.json, Godeps/_workspace/src/github.com/go-ldap/ldap/conn.go, Godeps/_workspace/src/github.com/go-ldap/ldap/todo
Without force-pushing, we are limited to doing this :frowning:
=> Restore authorship on commits

physical/zookeeper.go
=> Fix zookeeper break.

website/source/docs/auth/index.html.md
=> fixed secrets backend url

physical/consul.go, website/source/docs/config/index.html.md
resolves https://github.com/hashicorp/vault/issues/378
=> allow specifying certificates used to talk to consul for storage backend

audit/format_json.go, audit/format_json_test.go
Title says it all, resolves https://github.com/hashicorp/vault/issues/493
=> add a time field to the log entries

.gitignore, builtin/credential/cert/cli.go, command/meta.go
=> Documentation fixes

builtin/credential/github/path_login.go
PR #459 was accidentally removed when I submitted #489 and it got merged in. This fixes that. 
/cc @rpete
=> Reimplements #459

physical/mysql.go
=> Use varbinary instead of varchar for mysql, fixes #512

vault/auth.go, vault/auth_test.go
Making use of my previous pull req, this fixes #392.
=> Fix #392 by giving a more specific error

builtin/logical/pki/backend_test.go, builtin/logical/pki/cert_util.go, builtin/logical/pki/path_roles.go
=> Allow enforcement of hostnames to be toggleable for certificates.

api/auth_token_test.go
=> Add test coverage for auth tokens

website/source/docs/commands/environment.html.md, website/source/layouts/docs.erb
I'm not sure how to generate tables using your doc generator, but hopefully this will work.
=> docs: Document environment variables

builtin/logical/postgresql/backend.go, logical/framework/backend.go, logical/logical.go, vault/mount.go, vault/router.go, vault/router_test.go, vault/testing.go
Proposal to implement cleanup routine for backends. #554
=> Backend cleanup

command/token_create.go, command/token_renew.go, vault/token_store.go, website/source/docs/auth/token.html.md, website/source/docs/concepts/auth.html.md, website/source/docs/concepts/tokens.html.md, website/source/intro/getting-started/install.html.md
=> Improve documentation of token renewal

builtin/logical/postgresql/backend.go, builtin/logical/postgresql/path_role_create.go, builtin/logical/postgresql/secret_creds.go
=> Explicitly set timezone with PostgreSQL timestamps.

logical/system_view.go, vault/dynamic_system_view.go, vault/token_store.go, vault/token_store_test.go
=> TokenStore: Provide access based on sudo permissions and not policy name

website/source/docs/secrets/jwt/index.html.md, website/source/layouts/docs.erb
The new JWT secret backend documenation was not integrated into the website.
=> Fixes docs for new JWT secret backend

api/auth_token.go, api/secret.go, api/ssh.go, api/ssh_agent.go
Fix comments on exported methods in api.
=> Fix some lint warnings.

builtin/logical/mysql/backend.go, builtin/logical/mysql/path_config_connection.go, builtin/logical/postgresql/backend.go, builtin/logical/postgresql/path_config_connection.go, website/source/docs/secrets/mysql/index.html.md, website/source/docs/secrets/postgresql/index.html.md
=> Parameterize max open connections in postgresql and mysql backends

command/server.go
Tested on Linux (Mint) and Windows (2012R2)
https://github.com/hashicorp/vault/issues/704
=> Resolves issue 704 (Windows VAULT_ADDR env var)

CHANGELOG.md, vault/core.go
=> Return data on a token with one use left if there is no Lease ID

CHANGELOG.md, audit/format_json.go, audit/hashstructure.go, vault/audit.go
=> Write HMAC-SHA256'd client token to audited requests

CHANGELOG.md, api/auth_token.go, api/auth_token_test.go
=> Implement LookupSelf, RevokeSelf, and RenewSelf in the API client

CHANGELOG.md, builtin/logical/consul/backend_test.go, builtin/logical/consul/path_roles.go, builtin/logical/consul/path_token.go
=> Allow creating Consul management tokens

CHANGELOG.md, physical/etcd.go, website/source/docs/config/index.html.md
=> Switch etcd default port to 2379, in line with 2.x.

vault/token_store.go
=> Remove warning about nonexistent root policy by using GetPolicy instead

CHANGELOG.md, api/auth_token.go, command/token_create.go, http/sys_policy_test.go, vault/core.go, vault/core_test.go, vault/logical_system_test.go, vault/policy_store.go, vault/token_store.go, vault/token_store_test.go, website/source/docs/auth/token.html.md
It is forced to be included with each token, but can be changed (but not
deleted).
Fixes #732
=> Create a "default" policy with sensible rules.

CHANGELOG.md, physical/consul.go, website/source/docs/config/index.html.md
=> Remove datacenter from Consul configuration

physical/etcd.go
fixes vault initialization from #780
=> fixing etcd missing key error

CHANGELOG.md, vault/logical_passthrough.go
=> Return 400 instead of 500 if generic backend is written to without data.

website/source/intro/vs/kms.html.md
=> Fix typo in Amazon KMS comparison

builtin/logical/pki/cert_util.go
* Move to one place for both code paths
* Assign ExtKeyUsageAny to CA certs to help with validation with the
Windows Crypto API and Go's validation logic
Fixes #846
=> Update key usage logic

website/source/docs/http/libraries.html.md
vault-java implements the basic HTTP API, more endpoints are in the
pipeline
=> Add vault-java to libraries

website/source/docs/secrets/consul/index.html.md
=> Update documentation with Consul backend `token_type` parameter.

command/server.go, website/source/docs/commands/environment.html.md, website/source/docs/config/index.html.md
=> Allow setting the advertise address via an environment variable.

website/source/assets/stylesheets/_docs.scss, website/source/assets/stylesheets/_global.scss
Fix for https://github.com/hashicorp/vault/issues/858
=> flexbox should only have been used on website subpages

physical/s3.go
variables over configuration values.
=> Make S3 act like other parts of vault by prioritizing environment

vault/core.go
mode, don't advertise that we are active.
Ping #872
=> If we have not yet completed post-unseal when running in single-node

http/handler.go
Fixes a regression introduced in 0.3.
=> Have 'sys/renew' return the value provided in Secret.

command/init_test.go, command/pgp_test.go, command/rekey_test.go, helper/pgpkeys/flag.go
=> Allow ASCII-armored PGP pub keys to be passed into -pgp-keys.

command/init.go, command/init_test.go
=> Add -check flag to init.

website/source/docs/http/sys-seal-status.html.md
=> mention that this is an unauthenticated endpoint 

website/source/docs/auth/github.html.md
1. fix login link
2. added personal access token to request message
3. added a sample json response
=> fixed login link,request params,add json response

builtin/logical/postgresql/backend.go, builtin/logical/postgresql/path_config_connection.go, website/source/docs/secrets/postgresql/index.html.md
=> Add a max_idle_connections parameter.

website/source/docs/secrets/aws/index.html.md
@jefferai Forgot to add in website docs for AWS policies changes done via https://github.com/hashicorp/vault/pull/895 :)
=> AWS secret backend use of existing policy - docs

website/source/docs/secrets/cubbyhole/index.html.md
cubbyhole delete api details were missing. added them.
=> added the delete api details to cubbyhole

website/source/docs/secrets/generic/index.html.md
documentation was missing this api description
=> added the delete api details to generic backend

physical/postgresql.go, website/source/docs/config/index.html.md
Tested locally on PostgreSQL versions 9.4 and 9.5.
---
RFC @jefferai
=> Make the PostgreSQL backend more performant

api/auth_token_test.go, http/logical_test.go, logical/framework/backend_test.go, logical/framework/lease.go, logical/framework/lease_test.go
Change LeaseExtend to honor backend default if set but use system view value if not; to honor backend max if set but only if not greater than the system view value.
=> Rejig leases

builtin/logical/cassandra/backend.go, builtin/logical/cassandra/path_config_connection.go, builtin/logical/cassandra/util.go, website/source/docs/secrets/cassandra/index.html.md
* Add ability to change protocol version
* Remove config as a root path, use normal ACLs
* Update docs
=> Cassandra updates

builtin/logical/pki/ca_util.go, builtin/logical/pki/cert_util.go, builtin/logical/pki/fields.go, builtin/logical/pki/path_intermediate.go, builtin/logical/pki/path_issue_sign.go, builtin/logical/pki/path_root.go, website/source/docs/secrets/pki/index.html.md
concatenated PEM file.
Fixes #992
=> Allow the format to be specified as pem_bundle, which creates a

website/source/docs/secrets/ssh/index.html.md
it seems to be 200 on valid OTP and 204 on invalid OTP. (i think it should be an error.. 400 or 404)
but for the moment, fixing the docs to match the existing behavior.
=> fixing the return type of verify otp

builtin/logical/ssh/backend_test.go
The variables set in testingFactory.initTest were not picked up by the test cases properly.
initTest() was used to set variables like testIP, testUserName and testAdminUser.
Also, the input data which was common to many tests were being set here.
The username field was not reaching the test cases.
Now, I am initializing all the data required by the test case in the test case itself.
Since acceptance tests are not automated anyways, I have added a hardcoded username that is required to run the tests.
All tests are passing.
=> Fix SSH tests

builtin/logical/postgresql/secret_creds.go
This PR fixes #699 by adding additional revocation statements. Primarily, revoking a user's USAGE on the public schema, as well as revoking CONNECT privileges to the database. Failing to revoke these privileges, resulted in Vault attempting and failing to revoke the credentials, and using up all our available Postgres connections.
=> Fix PostgreSQL secret backend issues revoking users

physical/consul.go
And give it 4 idle connections
=> Use a pooled transport for the Consul physical backend

website/source/docs/secrets/pki/index.html.md
1. added the private_key_type field
2. changed "serial" to "serial_number"
3. added the warnings field
=> fixing response fields of /pki/issue

website/source/docs/secrets/consul/index.html.md
added the lease and token type field to the read role response.
=> added missing fields to read role

website/source/docs/secrets/pki/index.html.md
1. adding superset of fields in response, so that folks can see all possible response fields.
2. also added the less important "warnings" field
=> adding full response for intermediate/generate

builtin/logical/ssh/path_verify.go
=> SSH: Fix response code for ssh/verify

builtin/credential/github/path_login.go
Fixes #999 
Before the vault token is renewed, the following are reverified: base_url, user belonging to organization and the associated policies.
All acceptance tests are passing.
=> GitHub renewal enhancements

builtin/credential/ldap/backend.go
=> Properly escape filter values.

builtin/logical/aws/backend_test.go, builtin/logical/aws/path_sts.go, builtin/logical/aws/secret_access_keys.go
=> Set limits on generated IAM user and STS token names.

builtin/credential/cert/backend.go
=> Remove root requirement for certs/ and crls/ in TLS auth backend.

command/write.go
Making clear in the the write help that when using "@file", the file must be a JSON file.
=> When writing from a file it must be a JSON file

builtin/logical/mysql/backend.go, builtin/logical/mysql/backend_test.go, builtin/logical/postgresql/backend.go, builtin/logical/postgresql/backend_test.go, builtin/logical/postgresql/path_config_connection.go, website/source/docs/secrets/mysql/index.html.md, website/source/docs/secrets/postgresql/index.html.md
=> postgres: connection_url fix

builtin/logical/aws/backend_test.go, builtin/logical/aws/path_sts.go, website/source/docs/secrets/aws/index.html.md
=> Improve error message when client attempts to generate STS creds for managed policy

builtin/credential/cert/backend.go, builtin/credential/cert/path_config.go, builtin/credential/cert/path_login.go, builtin/logical/ssh/path_roles.go, vault/expiration.go, vault/router.go, vault/token_store.go, website/source/docs/auth/cert.html.md
=> Cert: renewal enhancements

physical/etcd.go
=> Output original error on etcd sync failure.

builtin/logical/cassandra/path_creds_create.go
Handles app-id generated display names.
Fixes #1140
=> Apply hyphen/underscore replacement across the entire username.

website/source/docs/secrets/ssh/index.html.md
=> zeroaddress documentation fix

vault/expiration.go, vault/expiration_test.go, vault/token_store.go
All tests are passing.
Fixes #1164
=> Change expiration.RenewToken's response from logical.Auth to logical.Response

builtin/logical/pki/backend_test.go, builtin/logical/pki/cert_util.go, builtin/logical/pki/path_fetch.go
=> Add revocation information to PKI fetch output (non-raw only).

builtin/logical/pki/path_revoke.go
=> Sanitize serial number in revocation path.

builtin/credential/github/backend_test.go
(tests fail for non hashicorp people)
=> fix github tests to use the provided GITHUB_ORG environment variable

vault/core.go
that as the definitive source for the response Auth object.
=> Sort and filter policies going into the create token entry, then use

builtin/credential/cert/backend.go, builtin/credential/cert/backend_test.go, builtin/credential/cert/path_certs.go, website/source/docs/auth/cert.html.md
=> Add list support to certs in cert auth backend.

command/write.go
=> Add `-field` and `-format` to write command.

builtin/logical/pki/backend_test.go, builtin/logical/pki/cert_util.go, builtin/logical/pki/fields.go
=> Add ability to exclude adding the CN to SANs.

website/source/docs/secrets/mysql/index.html.md
Documentation update to reflect mysql config connection from the old to the newer format
=> Change mysql connection to match new

website/source/docs/secrets/mysql/index.html.md
=> Revert "Change mysql connection to match new"

vault/token_store.go, vault/token_store_test.go
=> Check for auth/ in the path of the prefix for revoke-prefix in the token

builtin/credential/ldap/backend.go, builtin/credential/ldap/backend_test.go, builtin/credential/ldap/path_login.go
return a warning, rather than just trying to do an LDAP search on an
empty string.
=> If no group DN is configured, still look for policies on local users and

command/read.go, command/write.go
=> Fix panic when using -field with read or write with a non-string value.

builtin/credential/userpass/backend.go, builtin/credential/userpass/backend_test.go, builtin/credential/userpass/path_user_password.go, builtin/credential/userpass/path_user_policies.go, builtin/credential/userpass/path_users.go
Remove some unneeded existence checks. Remove paths from requiring root.
Fixes #911
=> Add list support to userpass users.

website/source/docs/auth/token.html.md
=> Should be renew not revoke

website/packer.json, website/scripts/deploy.sh
=> Update website push script to fix metadata

command/delete.go, command/revoke.go, command/token_revoke.go, website/source/intro/getting-started/authentication.html.md, website/source/intro/getting-started/dynamic-secrets.html.md, website/source/intro/getting-started/first-secret.html.md
=> Clarify output of idempotent calls

website/source/docs/concepts/policies.html.md, website/source/docs/secrets/generic/index.html.md
Prompted by: feedback from conference attendees at PGConf '16
=> Wordsmith the docs around the `list` command.

website/source/downloads.html.erb
http://mathiasbynens.github.io/rel-noopener/
=> Do not allow referrer to modify the parent

Godeps/Godeps.json, physical/azure.go, physical/azure_test.go, physical/physical.go, vendor/github.com/Azure/azure-sdk-for-go/LICENSE, vendor/github.com/Azure/azure-sdk-for-go/storage/blob.go, vendor/github.com/Azure/azure-sdk-for-go/storage/blob_test.go, vendor/github.com/Azure/azure-sdk-for-go/storage/client.go, vendor/github.com/Azure/azure-sdk-for-go/storage/client_test.go, vendor/github.com/Azure/azure-sdk-for-go/storage/file.go, vendor/github.com/Azure/azure-sdk-for-go/storage/file_test.go, vendor/github.com/Azure/azure-sdk-for-go/storage/queue.go, vendor/github.com/Azure/azure-sdk-for-go/storage/queue_test.go, vendor/github.com/Azure/azure-sdk-for-go/storage/util.go, vendor/github.com/Azure/azure-sdk-for-go/storage/util_test.go, vendor/vendor.json, website/source/docs/config/index.html.md
Simple Azure Blob Storage Backend similar to the S3 one. 
It supports the following config: 
backend "azure" {
container = "containerName"
accountName = "azure storage account name"
accountKey = "azure storage account key"
}
=> added Azure Blobstore backend support

vault/token_store.go, vault/token_store_test.go, website/source/docs/auth/token.html.md
=> Fix fetching parameters in token store when it's optionally in the URL

meta/meta.go
=> Fix help text around preference of ca-cert/ca-path.

builtin/credential/github/backend_test.go, builtin/credential/github/path_login.go
=> Make GitHub org comparison case insensitive.

helper/policyutil/policyutil.go, helper/strutil/strutil.go
Split comma separated apps, comma separated groups, merge the policies of multiple apps and remove duplicates, etc. is made easier by these utilities.
=> Updates to policy and string helpers

builtin/logical/aws/client.go, helper/awsutil/generate_credentials.go, helper/awsutil/generate_providers.go, physical/s3.go
Refactor AWS credential code into a function that returns a static->env->instance chain
Fixes #307
=> AWS cred chain helper

physical/etcd.go
Should be `127.0.0.1`, not `128.0.0.1`
=> Fix default etcd address

vault/logical_system_helpers.go
=> Fix mount tune bounds checking

website/source/docs/config/index.html.md
=> Document configuring listener to use a CA cert

builtin/credential/ldap/backend.go, builtin/credential/ldap/backend_test.go, builtin/credential/ldap/path_groups.go, builtin/credential/ldap/path_users.go
=> Support listing ldap group to policy mappings

command/ssh.go
=> Fix mapstructure decoding error

builtin/logical/pki/path_roles.go
=> Remove deprecated entries from PKI role output.

builtin/credential/app-id/path_login.go, builtin/credential/aws/path_login.go, builtin/credential/cert/backend_test.go, builtin/credential/cert/path_login.go, builtin/credential/github/path_login.go, builtin/credential/ldap/path_login.go, builtin/credential/userpass/path_login.go, builtin/logical/consul/path_token.go, builtin/logical/consul/secret_token.go, builtin/logical/mssql/secret_creds.go, builtin/logical/pki/secret_certs.go, builtin/logical/postgresql/secret_creds.go, vault/expiration.go, vault/token_store.go
Did manual testing and it works fine.
Fixes #1433
=> Fix the consul secret backends renewal revocation problem

website/source/intro/getting-started/deploy.html.md
- Fixed the statement that HCL is JSON compatible; it's backwards
- Added that HCL is a superset of JSON to eliminate any lingering confusion
=> Fixed & clarified grammar around HCL & JSON

vault/barrier_aes_gcm.go, vault/keyring.go, vault/util.go
appropriate places. Known to be best-effort, but may help in some cases.
Fixes #1446
=> Add keyring zeroize function and add some more memzero calls in

builtin/logical/ssh/backend_test.go, builtin/logical/ssh/path_creds_create.go, website/source/docs/secrets/ssh/index.html.md
=> Ssh allowed users

command/ssh.go, website/source/docs/secrets/ssh/index.html.md
=> Provide option to disable host key checking

website/source/docs/concepts/pgp-gpg-keybase.html.md, website/source/docs/http/sys-init.html.md, website/source/intro/getting-started/deploy.html.md, website/source/layouts/docs.erb
=> Add a page for step-by-step gpg/keybase

website/source/docs/internals/rotation.html.md
"invaliding" => "invalidating"
=> Small grammatical error

builtin/logical/pki/backend.go, builtin/logical/pki/backend_test.go, builtin/logical/pki/path_fetch.go, website/source/docs/secrets/pki/index.html.md
This PR includes the ability to list PKI certs by their serial numbers and a rough version of a test for this functionality.
Fixes #1466
=> PKI List Functionality

builtin/logical/transit/backend_test.go, builtin/logical/transit/lock_manager.go, builtin/logical/transit/path_config.go, builtin/logical/transit/path_encrypt.go, builtin/logical/transit/path_keys.go, builtin/logical/transit/policy.go, builtin/logical/transit/policy_test.go, website/source/docs/secrets/transit/index.html.md
=> Add convergent encryption option to transit.

command/auth.go
=> Added -path option to 'vault auth' command

builtin/logical/aws/backend.go, builtin/logical/aws/path_roles.go, builtin/logical/aws/path_roles_test.go, builtin/logical/pki/path_roles.go, website/source/docs/secrets/aws/index.html.md
=> Added list functionality to logical aws backend's roles

command/util.go, command/write.go
Also fix the write command to use the shared function with aliases.
Fixes #1566
=> Add aliases for field flag to allow printing auth results.

physical/etcd.go, physical/etcd_test.go, website/source/docs/commands/environment.html.md, website/source/docs/config/index.html.md
This PR goes towards #1574. 
The test suite seems to pass on my local setup. Unfortunately I was not able to build the binary for some weird go path reasons.
=> Etcd addr env

builtin/logical/mssql/backend.go, builtin/logical/mysql/backend.go, builtin/logical/postgresql/backend.go, builtin/logical/postgresql/backend_test.go
If unsuccessful, reestablish connections as needed.
=> Have SQL backends Ping() before access.

vault/request_handling.go, vault/request_handling_test.go
=> Add response wrapping support to login endpoints.

website/source/docs/auth/aws-ec2.html.md
=> [Docs] aws-ec2 -- note IAM action requirement

builtin/logical/postgresql/backend_test.go, builtin/logical/postgresql/secret_creds.go
Should fix https://github.com/hashicorp/vault/issues/1535
First foray into go, so any suggestions are welcome.
=> handle revocations for roles that have privileges on sequences

vault/core.go
This can be helpful for detecting flapping.
Fixes #1544
=> Add metrics around leadership

builtin/logical/mysql/backend.go, builtin/logical/mysql/backend_test.go, builtin/logical/mysql/path_config_connection.go, website/source/docs/secrets/mysql/index.html.md
=> Added maximum idle connections to mysql

builtin/credential/cert/path_login.go
=> Ensure we never return a nil set of trusted CA certs

builtin/credential/cert/path_login.go
=> Fix panic if no certificates are supplied by client

helper/policyutil/policyutil.go, helper/strutil/strutil.go, helper/strutil/strutil_test.go, physical/consul.go, physical/consul_test.go, website/source/docs/config/index.html.md
=> Added `service-tags` config option to Consul storage backend

command/server.go, command/server/config.go, command/server/config_test.go, command/server/test-fixtures/config2.hcl.json, vendor/github.com/armon/go-metrics/circonus/circonus.go, vendor/github.com/circonus-labs/circonus-gometrics/README.md, vendor/github.com/circonus-labs/circonus-gometrics/api/api.go, vendor/github.com/circonus-labs/circonus-gometrics/api/broker.go, vendor/github.com/circonus-labs/circonus-gometrics/api/check.go, vendor/github.com/circonus-labs/circonus-gometrics/api/checkbundle.go, vendor/github.com/circonus-labs/circonus-gometrics/checkmgr/broker.go, vendor/github.com/circonus-labs/circonus-gometrics/checkmgr/cert.go, vendor/github.com/circonus-labs/circonus-gometrics/checkmgr/check.go, vendor/github.com/circonus-labs/circonus-gometrics/checkmgr/checkmgr.go, vendor/github.com/circonus-labs/circonus-gometrics/checkmgr/metrics.go, vendor/github.com/circonus-labs/circonus-gometrics/circonus-gometrics.go, vendor/github.com/circonus-labs/circonus-gometrics/counter.go, vendor/github.com/circonus-labs/circonus-gometrics/gauge.go, vendor/github.com/circonus-labs/circonus-gometrics/histogram.go, vendor/github.com/circonus-labs/circonus-gometrics/submit.go, vendor/github.com/circonus-labs/circonus-gometrics/text.go, vendor/github.com/circonus-labs/circonus-gometrics/tools.go, vendor/github.com/circonus-labs/circonus-gometrics/util.go, vendor/github.com/circonus-labs/circonusllhist/LICENSE, vendor/github.com/circonus-labs/circonusllhist/circonusllhist.go, vendor/vendor.json, website/source/docs/config/index.html.md
Same type of integration as done for consul and nomad.
=> Circonus integration for telemetry metrics

http/sys_health.go, http/sys_health_test.go, website/source/docs/http/sys-health.html.md
=> Add version information to health status

http/sys_policy_test.go, vault/logical_system_test.go, vault/policy_store.go, vault/policy_store_test.go, vault/token_store.go, vault/token_store_test.go
DO NOT MERGE. STILL BEING WORKED.
Fixes #1618
=> Block internal policies from being assigned to tokens

command/server/listener_atlas.go
Report a more machine readable version string to Atlas.
=> Report the simple version string

command/server.go, command/server/config.go, command/server/config_test.go, command/server/test-fixtures/config-dir/baz.hcl, command/server/test-fixtures/config.hcl, command/server/test-fixtures/config.hcl.json, http/sys_health.go, http/sys_health_test.go, http/sys_seal_test.go, vault/cluster.go, vault/cluster_test.go, vault/core.go, website/source/docs/http/sys-health.html.md
Unfinished business. Do Not Merge.
=> Vault cluster name and ID

builtin/logical/pki/cert_util.go, builtin/logical/pki/crl_util.go, builtin/logical/pki/path_config_ca.go, builtin/logical/pki/path_fetch.go, builtin/logical/pki/path_intermediate.go, builtin/logical/pki/path_issue_sign.go, builtin/logical/pki/path_revoke.go, builtin/logical/pki/path_root.go, builtin/logical/transit/path_datakey.go, builtin/logical/transit/path_decrypt.go, builtin/logical/transit/path_encrypt.go, builtin/logical/transit/path_rewrap.go, builtin/logical/transit/policy.go, helper/certutil/helpers.go, helper/certutil/types.go, helper/errutil/error.go, logical/framework/backend.go, vault/core.go
=> Fix invalid input getting marked as internal error

website/source/docs/secrets/pki/index.html.md
Missing the mount point for the list roles endpoint.
=> Small doc fix

command/server.go, physical/consul.go, physical/consul_test.go, physical/physical.go
=> Add waitgroup wait to allow physical consul to deregister checks

command/ssh.go
=> Support execution of remote commands using 'vault ssh'

http/handler.go, vault/token_store.go
=> Add extra nil check for an error response/use duration helper for TTL values

vault/policy_store.go
=> Make `capabilities-self` part of the default policy.

http/sys_health.go, http/sys_seal.go, vault/cluster.go
=> Fix Cluster object being returned as nil when unsealed

builtin/credential/aws-ec2/path_login.go
=> aws-ec2: se max_ttl when ttl is not set, during login

website/Vagrantfile
* Upgrade base box to `bento/ubuntu-16.04`
* Remove JS stuff
* Install `git` and `bundler`
* Add gpg key for RVM
=> Update website Vagrantfile

builtin/logical/ssh/secret_dynamic_key.go
=> Decode secret internal data into struct and fix type assertion.

api/auth_token.go, vault/core_test.go, vault/token_store.go, vault/token_store_test.go, website/source/docs/install/upgrade-to-0.6.2.html.md
=> Don't allow tokens in paths.

command/server.go, command/server/config.go, command/server/config_test.go, command/server/test-fixtures/config2.hcl.json, physical/cache.go, physical/cache_test.go, vault/core.go, website/source/docs/config/index.html.md
=> Plumb through the ability to set the storage read cache size.

builtin/logical/transit/backend_test.go, builtin/logical/transit/lock_manager.go, builtin/logical/transit/path_keys.go, builtin/logical/transit/policy.go, website/source/docs/secrets/transit/index.html.md
=> Use key derivation for convergent nonce.

builtin/logical/transit/backend_test.go, builtin/logical/transit/policy.go
=> Derive nonce fully in convergent mode

builtin/logical/aws/secret_access_keys.go
=> Mark STS secrets as non-renwable

vault/token_store.go
=> Add back token/accessor URL parameters but return a warning.

logical/framework/path.go
closes https://github.com/hashicorp/vault/issues/1809
=> Support for 1 and 2 char names in GenericNameRegex

website/source/docs/http/sys-seal-status.html.md
adding the missing "version" field in json response.
also adding a new response when the unseal completes, and 2 more fields are returned. (cluster..)
=> doc: add missing version and cluster fields

command/format.go
=> Don't output key/value header if there are no values to display.

command/auth.go
=> Avoid commas while printing policies

vault/generate_root.go
=> Return bad request error on providing same key for root generation

command/auth.go
=> Add more examples and cleanup docs for auth

command/audit_enable.go
=> Update audit-enable to show more examples

website/source/docs/secrets/aws/index.html.md
response field is security_token, not secret_token.
=> doc: fixing field name to security_token

website/source/docs/secrets/ssh/index.html.md
invalid otp response code is 400 bad request.
https://github.com/hashicorp/vault/pull/1086
=> doc: change invalid otp response code to 400

command/auth.go
=> Don't panic on bad auth path

vault/audit.go, vault/auth.go, vault/mount.go, vault/rollback.go
=> Rejig locks during unmount/remount.

http/sys_rekey.go
=> Redirect rekey operation from standby to master

builtin/logical/transit/backend_test.go, builtin/logical/transit/path_decrypt.go, builtin/logical/transit/path_encrypt.go
=> Allow encrypting empty ciphertext values.

builtin/credential/aws-ec2/path_login.go
=> Only use running state for checking if instance is alive.

website/source/docs/auth/aws-ec2.html.md
$() doesnt get evaluated in single quotes, so you need to break out of it first
=> fix shell quoting

builtin/credential/approle/path_login.go, builtin/credential/approle/path_login_test.go, builtin/credential/approle/path_role.go, builtin/credential/approle/path_role_test.go, builtin/credential/approle/validation.go, builtin/logical/ssh/path_roles.go, builtin/logical/ssh/util.go, helper/cidrutil/cidr.go, helper/cidrutil/cidr_test.go, website/source/docs/auth/approle.html.md
=> CIDR restrictions on Secret ID

vault/token_store.go, vault/token_store_test.go
=> Handle token entry upgrade gracefully

CHANGELOG.md, builtin/logical/cassandra/backend_test.go, builtin/logical/cassandra/path_creds_create.go, builtin/logical/cassandra/path_roles.go, website/source/docs/secrets/cassandra/index.html.md
=> Adding consistency into cassandra

builtin/credential/aws-ec2/backend.go, builtin/credential/aws-ec2/client.go, builtin/credential/aws-ec2/path_config_client.go, builtin/credential/aws-ec2/path_login.go, builtin/credential/aws-ec2/path_role.go, website/source/docs/auth/aws-ec2.html.md
=> Proper naming for bound_iam_instance_profile_arn

api/client.go, api/logical.go, command/rekey_test.go, command/unwrap.go, command/util.go, http/handler.go, http/logical.go, http/sys_wrapping_test.go, meta/meta.go, vault/core.go, vault/core_test.go, vault/logical_system.go, vault/logical_system_test.go, vault/policy_store.go, vault/policy_store_test.go, vault/request_handling.go, vault/router.go, vault/testing.go, vault/token_store.go, vault/token_store_test.go, website/source/docs/http/sys-wrapping-lookup.html.md, website/source/docs/http/sys-wrapping-rewrap.html.md, website/source/docs/http/sys-wrapping-unwrap.html.md, website/source/docs/http/sys-wrapping-wrap.html.md, website/source/layouts/http.erb
=> Wrapping enhancements

builtin/credential/approle/path_role.go, builtin/credential/approle/path_role_test.go, builtin/credential/approle/validation_test.go, website/source/docs/auth/approle.html.md
=> Introduce lookup and destroy endpoints for secret IDs and its accessors

command/server/config.go, command/server/config_test.go, command/server/test-fixtures/config-dir/foo.hcl, command/server/test-fixtures/config.hcl, command/server/test-fixtures/config.hcl.json, command/server/test-fixtures/config2.hcl.json, website/source/docs/concepts/ha.html.markdown, website/source/docs/config/index.html.md
=> Switch default case of disable cluster.

builtin/credential/aws-ec2/path_config_client.go
Updated to reflect enhanced functionality and clarify necessary
permissions.
=> Update aws-ec2 configuration help

builtin/logical/cassandra/backend_test.go, builtin/logical/cassandra/path_roles.go
=> Fix empty consistency option issue for Cassandra

audit/formatter.go, builtin/audit/file/backend.go, builtin/audit/file/backend_test.go, website/source/docs/audit/file.html.md
Added an option to the audit file permissions.
Resolves #1977
=> Audit file update

website/source/docs/concepts/ha.html.markdown
=> Docs: Update the client redirection defaults

builtin/credential/approle/path_role.go, builtin/credential/approle/path_role_test.go
=> Fix regression caused by not creating a role_id secondary index

builtin/logical/postgresql/path_roles.go, website/source/docs/secrets/postgresql/index.html.md
=> Added revocation_sql to the website docs

website/source/docs/auth/approle.html.md, website/source/intro/getting-started/apis.html.md
=> Docs: Update for getting started API section

physical/cache.go
=> Don't cache physical responses when thre was an error

website/source/docs/http/libraries.html.md
Add Spring Vault to community-managed libraries for Java.
=> Add Spring Vault to client libraries

builtin/logical/consul/backend.go, builtin/logical/consul/backend_test.go, builtin/logical/consul/path_roles.go, builtin/logical/consul/path_token.go
And use unixnano for timestamps to be more unique
=> Add listing to Consul secret roles

website/source/docs/auth/github.html.md
Added documentation on user-specific policies for github auth backend.
=> Added document to github auth backend covering user-specific policies.

vault/logical_system.go, vault/request_handling.go, vault/router.go
Take the lesser of the request/response times
=> Allow wrapping to be specified by backends

vault/cluster.go, vault/core.go, vault/request_forwarding.go
=> Add extra logic around listener handling.

website/source/docs/http/libraries.html.md
Added the Haskell Community library requested by: #2095
=> Update libraries doc for Haskell community library

website/source/intro/getting-started/first-secret.html.md
These were discovered to be out of date as per https://github.com/hashicorp/vault/issues/2116
=> Change command examples for First Secrets #2116

command/server.go, helper/mlock/mlock_unavail.go, helper/mlock/mlock_unix.go
=> Don't say mlock is supported on OSX when it isn't.

website/source/docs/secrets/aws/index.html.md
Should be arn, not policy - latter will error as that assume an inline policy json document
=> Minor documentation tweak

api/client.go, command/init.go
=> Use Vault client's scheme for auto discovery

website/source/intro/getting-started/acl.html.md, website/source/intro/getting-started/authentication.html.md, website/source/intro/getting-started/deploy.html.md, website/source/intro/getting-started/dev-server.html.md, website/source/intro/getting-started/dynamic-secrets.html.md, website/source/intro/getting-started/first-secret.html.md, website/source/intro/getting-started/help.html.md, website/source/intro/getting-started/install.html.md, website/source/intro/getting-started/secret-backends.html.md
I've been working through the Getting Started guide and updating some formatting, language and documentation as I go. I've tried to make a commit per file.
I'll try to get the rest of the guide soon.
=> Documentation updates

website/source/_ember_templates.html.erb
Removes the akward browser autocomplete bar from the tutorial input.
=> website: turn off autocomplete on the demo

builtin/credential/ldap/path_config.go
=> Don't panic when TLS is enabled but the initial dial doesn't return a connection.

command/token_create.go, helper/policyutil/policyutil.go, helper/strutil/strutil.go, helper/strutil/strutil_test.go, vault/token_store.go, vault/token_store_test.go, website/source/docs/auth/token.html.md
=> Don't add default policy to child token if parent does not have it

website/source/docs/secrets/mysql/index.html.md
add DSN as link to go-sql-driver/mysql to know the syntax
=> docs/secrets/mysql/index.html.md: add DSN link

website/source/docs/secrets/mysql/index.html.md
=> docs/secrets/mysql/index.html.md: add mysql socket example

builtin/audit/syslog/backend.go
Noticed these discrepancies when looking at some other items
=> Minor cleanup in audit backend

website/source/docs/http/libraries.html.md
Adding a C# port of the go api client.
=> Adding Vault.NET C# Library

website/source/downloads.html.erb
Largely copy pasta'd from the Terraform downloads.html page.
=> Adds a link to the latest releases CHANGELOG on the downloads.html page

vendor/github.com/hashicorp/go-syslog/builtin.go, vendor/github.com/hashicorp/go-syslog/unix.go, vendor/github.com/hashicorp/go-syslog/unsupported.go, vendor/vendor.json
=> Update go-syslog package

physical/s3.go
S3 results require paging to ensure that all results are returned. This PR changes the S3 physical backend to use the new ListObjectV2 method and pages through all the results.
Fixes #2223.
=> Page results from S3.

website/source/docs/auth/token.html.md
reflect the true 0.6.4 response.
=> fix lookup-self response json

builtin/logical/transit/path_keys.go, website/source/docs/secrets/transit/index.html.md
Adds policy fields to the transit key read response indicating what actions that type of key supports.
=> Transit key actions

logical/framework/path_map.go, logical/framework/path_map_test.go
=> Support LIST on auth/github/map/teams and /users

vault/auth.go, vault/mount.go
=> Sync the locking behavior between logical/auth backend

helper/strutil/strutil.go, vault/token_store.go, vault/token_store_test.go
=> Don't sanitize disallowed_policies on token role

website/source/docs/auth/token.html.md
=> tokenStore: document the 'period' field

builtin/credential/ldap/backend_test.go, builtin/credential/ldap/path_users.go, website/source/docs/auth/ldap.html.md
=> ldap: Minor enhancements, tests and doc update

builtin/logical/cassandra/backend.go, builtin/logical/mssql/backend.go, builtin/logical/mysql/backend.go, vault/mount.go
Ensure it's called on unmount, not just for seal.
=> Add cleanup functions to multiple DB backends

builtin/credential/approle/backend.go, builtin/credential/approle/path_role.go, builtin/credential/approle/validation.go
=> approle: secret-id listing lock sanity check

vault/core.go
=> Rejig check for HA/Sealed in Leader to check for sealed first.

vault/expiration.go
=> Add count of leases during load

builtin/audit/socket/backend.go, cli/commands.go, website/source/docs/audit/index.html.md, website/source/docs/audit/socket.html.md, website/source/layouts/docs.erb
This PR builds off of @hharnisc's work on #2161
=> Add Socket Audit Backend

command/server.go
=> Correct port parsing.

builtin/credential/ldap/backend_test.go, builtin/credential/ldap/path_config.go, website/source/docs/auth/ldap.html.md
=> Add support for backup/multiple LDAP URLs.

builtin/credential/okta/backend.go, builtin/credential/okta/backend_test.go
=> Fix Okta auth issue when a user has no policies and/or groups set.

website/source/docs/auth/aws-ec2.html.md
Fixes https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/vault-tool/sYCUQfAkIRE/9TH6pKMDEQAJ
=> aws-ec2 auth: fix docs

builtin/credential/aws-ec2/path_role.go, builtin/credential/aws-ec2/path_role_test.go
=> aws-ec2 auth: Return the role period in seconds

vault/audit_test.go, vault/audited_headers.go, vault/audited_headers_test.go
=> Compare headers case-insensitively for auditing

builtin/logical/pki/backend_test.go, builtin/logical/pki/cert_util.go, builtin/logical/pki/path_roles.go, website/source/docs/secrets/pki/index.html.md
=> Add Organization support to PKI backend.

website/source/intro/vs/hsm.html.md
Complementary and complimentary mean quite different things
=> Update hsm.html.md to use the correct word

http/logical.go, http/logical_test.go
=> Internally append trailing slash for all LIST operations.

http/handler_test.go, http/sys_mount_test.go, vault/logical_cubbyhole.go, vault/logical_cubbyhole_test.go, vault/logical_system_test.go, vault/mount.go, vault/mount_test.go
This doesn't really change behavior, just what it looks like in the UX.
However, it does make tests more complicated. Most were fixed by adding
a sorting function, which is generally useful anyways.
=> Make cubbyhole local instead of replicated.

builtin/credential/aws-ec2/path_login.go, builtin/credential/aws-ec2/path_role.go, builtin/credential/aws-ec2/path_role_test.go, website/source/docs/auth/aws-ec2.html.md
=> Aws Ec2 additional binds for SubnetID, VpcID and Region

website/source/docs/http/sys-health.html.md
=> Doc sys health codes

builtin/logical/ssh/path_fetch.go, builtin/logical/ssh/path_roles.go, builtin/logical/ssh/path_sign.go, website/source/docs/secrets/ssh/index.html.md
=> Rework ssh ca

builtin/logical/ssh/backend_test.go, builtin/logical/ssh/path_config_ca.go, website/source/docs/secrets/ssh/index.html.md
=> Allow internal generation of the signing SSH key pair

website/source/docs/commands/read-write.html.md, website/source/intro/getting-started/dynamic-secrets.html.md
=> Updated doc to match real output

website/source/docs/configuration/index.html.md
=> docs: clarify 'storage' and 'ha_storage' config requirements

builtin/credential/ldap/backend.go, builtin/logical/pki/cert_util.go, helper/policyutil/policyutil.go, helper/strutil/strutil.go, vault/token_store.go
After, separately dedup and use new flag to not lowercase value.
Fixes #2555
=> Use ParseStringSlice on PKI organization/organizational unit.

website/source/docs/auth/ldap.html.md
See commit messages for additional info
=> Ldap auth doc fix

plugins/database/mssql/mssql.go
This is related to a change in the current mssql backend.
=> Adding explicit database to sp_msloginmappings call

builtin/credential/ldap/path_users.go
=> Do not lowercase groups attached to users in ldap

builtin/logical/pki/cert_util.go, helper/certutil/types.go
=> Return error message for failure to parse CSR

version/version.go
Add version metadata to be used for different types of vault binaries
=> Add version metadata

builtin/credential/approle/path_role_test.go, builtin/credential/approle/validation.go, builtin/credential/aws/path_role_test.go, builtin/credential/ldap/path_config.go, helper/awsutil/generate_credentials.go, helper/keysutil/lock_manager.go, vault/router_test.go, vault/token_store.go
These were suggested by `go vet`
=> Fixing printf (and similar) issues

website/source/api/secret/pki/index.html.md
=> fix format for secret/pki

command/write.go
=> Write always needs a path, even with force.

website/redirects.txt, website/scripts/deploy.sh
=> Add project-side redirects

website/source/api/secret/transit/index.html.md
=> Updating key export documentation for transit

website/redirects.txt
Updating moved documentation to new location.
=> Adding leases documentation redirects

builtin/logical/pki/path_intermediate.go, helper/certutil/types.go
fixed spelling error in error message and comment
=> Fix typos in error message

Makefile, api/client.go, builtin/credential/github/path_config.go, builtin/logical/cassandra/path_creds_create.go, command/audit_enable.go, http/handler.go, scripts/gofmtcheck.sh, vault/barrier_view.go
Adding what is done is terraform to ensure gofmt is enforced on non-vendor files.
=> Add gofmt checks to Vault and format existing code

builtin/logical/ssh/util.go
=> Added host key call back for ssh config

vault/logical_system.go
Fixes #2763 
Follow up for https://github.com/hashicorp/vault/issues/2763#issuecomment-304080294
=> Input checks for policy rules

website/source/docs/configuration/index.html.md
=> Add plugin_directory to configuration page

physical/s3.go
=> Avoid panic in s3 list operation

website/Gemfile, website/Gemfile.lock
To update the meganav on the website
=> update middleman version from 24 to 26

builtin/credential/aws/path_login.go
=> Honor role period for IAM auth type in AWS backend

plugins/database/cassandra/cassandra_test.go, plugins/database/cassandra/connection_producer.go, plugins/database/mongodb/connection_producer.go, plugins/database/mssql/mssql_test.go, plugins/database/mysql/mysql_test.go, plugins/database/postgresql/postgresql_test.go, plugins/helper/database/connutil/sql.go
=> Use WeakDecode to decode the initialized values in database plugins

website/source/api/libraries.html.md
=> Content updates for News section

README.md
Need(ed) to change a GA reference
=> Changed campaign in links

vault/token_store.go, vault/token_store_test.go
=> Don't allow overriding token ID with the same token ID

http/sys_wrapping_test.go
I found some places in the tests for the http package where errors were being ignored.
=> Fix Swallowed Errors in http Package.

builtin/logical/transit/path_keys.go, builtin/logical/transit/path_keys_test.go, builtin/logical/transit/path_sign_verify_test.go
=> Don't panic in audit logs when reading transit keys.

physical/mssql.go
This fixes a swallowed error in the physical package.
=> Fix swallowed error in physical package.

builtin/audit/file/backend_test.go, builtin/credential/approle/path_role_test.go, builtin/credential/aws/backend_test.go, builtin/credential/aws/path_login.go, builtin/credential/aws/path_login_test.go, builtin/credential/aws/path_role_test.go, builtin/credential/radius/path_login.go, builtin/logical/aws/backend_test.go, builtin/logical/transit/backend_test.go
Fixes for swallowed errors under the builtin subdirectory.
=> Fix swallowed errors in builtin

website/source/api/system/generate-root.html.md
=> DOCS: Update API docs for /sys/generate-root

api/renewer.go
=> Do not double-convert to seconds

vault/policy_store.go, website/source/api/system/wrapping-wrap.html.md
=> Revert "Remove wrapping/wrap from default policy and add a note about guarantees"

builtin/audit/file/backend.go
Addresses a pain point from
https://github.com/hashicorp/vault/issues/2863#issuecomment-309434605
=> Opportunistically try re-opening file audit fd on error

vault/audit.go
=> Add metrics counters for audit log failures

builtin/credential/ldap/path_config.go
=> Adding validation for certificates to be proper x509 PEM encoded

website/source/docs/vault-enterprise/hsm/configuration.html.md
Update to HSM docs to address PKCS#11 library use.
=> Update HSM Docs

plugins/helper/database/credsutil/credsutil.go, plugins/helper/database/credsutil/credsutil_test.go, plugins/helper/database/credsutil/sql.go
=> Enforce alphanumeric requirement in RandomAlphaNumeric

physical/etcd3.go
Not sure how other backend handles this. But I feel adding a reasonable default timeout is good enough for vault use case.
=> physical: add default timeout for etcd3 requests

vault/token_store.go
I found an error in the vault package that was being ignored.
=> Fix swallowed error in vault package.

physical/etcd3.go
context takes time.Duration not timeInSeconds. I made a mistake on that. Now fixed.
=> physical: format fixes

builtin/credential/app-id/backend.go, builtin/credential/approle/backend.go, builtin/credential/aws/backend.go, builtin/credential/cert/backend.go, builtin/credential/github/backend.go, builtin/credential/ldap/backend.go, builtin/credential/okta/backend.go, builtin/credential/radius/backend.go, builtin/credential/userpass/backend.go, builtin/logical/aws/backend.go, builtin/logical/cassandra/backend.go, builtin/logical/consul/backend.go, builtin/logical/database/backend.go, builtin/logical/mongodb/backend.go, builtin/logical/mssql/backend.go, builtin/logical/mysql/backend.go, builtin/logical/pki/backend.go, builtin/logical/postgresql/backend.go, builtin/logical/rabbitmq/backend.go, builtin/logical/ssh/backend.go, builtin/logical/totp/backend.go, builtin/logical/transit/backend.go
=> Add BackendType to existing backends

.github/ISSUE_TEMPLATE.md
Adding an issue template to prevent people from opening issues for questions, and direct them to the Google Group forum instead.
=> Add GitHub template

api/sys_health.go
=> Have sys health api always return even in an error case

builtin/logical/pki/path_issue_sign.go
=> Adding warning for conflicting role and request parameters

vendor/github.com/SAP/go-hdb/README.md, vendor/github.com/SAP/go-hdb/driver/driver.go, vendor/github.com/SAP/go-hdb/internal/protocol/littleendian.go, vendor/vendor.json
=> Update vendored library go-hdb

website/source/docs/secrets/databases/index.html.md
A small mistake I noticed in the documentation for database secret backends.
=> Fix minor grammatical error

website/source/api/system/mfa.html.md
Minor stuff for json formatting.
/cc @vishalnayak
=> Fix formatting in mfa docs

command/ssh.go
From the sshpass manpage:
> The -p option should be considered the least secure of all of sshpass's options. All system users can see the password in the command line with a simple "ps" command. Sshpass makes a minimal attempt to hide the password, but such attempts are doomed to create race conditions without actually solving the problem. Users of sshpass are encouraged to use one of the other password passing techniques, which are all more secure.
This PR changes the sshpass behavior to execute a subprocess with the SSHPASS envvar (which is generally regarded as more secure) than using the -p option.
I also broke up the sshcmdargs onto their own lines for better readability and future diffing.
=> Use SSHPASS envvar instead of -p for sshpass

command/server.go, vault/logical_system.go, website/source/api/system/plugins-catalog.html.md
Also, Change (with backwards compatibility) sha_256 to sha256 for plugin registration
=> Add ability to specify a plugin dir in dev mode

website/source/docs/auth/gcp.html.md
Update GCP docs to have a similar section layout to other auth backend docs.
/cc @emilymye
=> Update gcp auth backend docs

website/source/api/libraries.html.md
A new PHP client has arrived! :)
=> add new php client to the doc

website/source/docs/secrets/ssh/signed-ssh-certificates.html.md
=> Addd more SSH CA troubleshooting

command/ssh.go, website/source/docs/secrets/ssh/signed-ssh-certificates.html.md
I couldn't figure out why I wasn't getting errors, then I saw it. It looks like we weren't previously including stderr as a stream from the command - was there a reason? /cc @vishalnayak
=> Thread stderr through too

physical/gcs/gcs.go, website/source/docs/configuration/storage/google-cloud.html.md
fixes https://github.com/hashicorp/vault/issues/3242
=> add support to use application default credentials to gcs storage backend

builtin/audit/file/backend.go, website/source/docs/audit/file.html.md
=> Add 'discard' target to file audit backend

physical/consul/consul.go
=> Use net.SplitHostPort on Consul address

vault/expiration.go
Bring back the parallel implementation to the lazy loaded expiration manager.
=> Add parallel loading to lazy loaded expiration manager

website/source/api/auth/approle/index.html.md, website/source/api/auth/aws/index.html.md, website/source/api/auth/gcp/index.html.md, website/source/api/auth/github/index.html.md, website/source/api/auth/okta/index.html.md, website/source/api/auth/radius/index.html.md, website/source/api/auth/userpass/index.html.md
=> Remove token header from login samples

builtin/credential/aws/path_config_certificate.go, website/source/api/auth/aws/index.html.md
=> docs: Added certificate deletion operation API

website/source/api/auth/kubernetes/index.html.md
Also changed capitalization for consistency.
=> Fix grammatical error

website/source/api/auth/aws/index.html.md, website/source/api/secret/aws/index.html.md, website/source/api/secret/ssh/index.html.md, website/source/api/system/replication-dr.html.md, website/source/docs/secrets/aws/index.html.md
Fixes some spelling errors on the website. You all may want to consider adding
a step in your make file to check for spelling errors. Here is a reference for
you all to use: https://github.com/hashicorp/nomad/pull/3292
=> Fix spelling errors on website

api/client.go, api/client_test.go
=> Fix panic when setting a client http client with no transport

scripts/build.sh
This will allow you to set gcflags to do things like disable optimized builds for debugging.
=> Adding ability to set gcflags on build

website/source/docs/secrets/databases/mssql.html.md
=> Updating mssql docs

vault/acl.go, vault/acl_test.go, vault/policy.go, vault/policy_test.go, website/source/docs/concepts/policies.html.md
=> Add ability to require parameters in ACL

vault/core.go, vault/core_test.go
Since token store isn't available after when using single-use tokens
Fixes #3497
=> Ensure revocation happens before seal/step-down

vault/capabilities.go, vault/capabilities_test.go, vault/core.go, website/source/api/system/capabilities-accessor.html.md, website/source/api/system/capabilities-self.html.md, website/source/api/system/capabilities.html.md
=> Capabilities responds considering policies on entities and groups

vault/identity_store_util.go
Plus a few minor tweaks.  I probably need to add some tests to cover these scenarios.
=> Fix group/policy iterators with multiple groups

vault/rollback_test.go
This fixes some goroutine-swallowed error variables in the vault package rollback tests.
=> Fix swallowed errors in TestRollbackManager_Join()

command/server/config.go, command/server/config_test.go, command/server/test-fixtures/config2.hcl
=> Move HA-related config values to top level

helper/wrapping/wrapinfo.go, vault/request_handling.go, vault/router.go, vault/wrapping.go
Ref 84f80db4bf499ce7345615cc2def77e7d48bc690
=> Add ability to send seal wrap response info into cubbyhole request.

website/source/docs/configuration/seal/awskms.html.md, website/source/docs/configuration/seal/gcpckms.html.md, website/source/docs/configuration/seal/index.html.md, website/source/docs/configuration/seal/pkcs11.html.md, website/source/docs/enterprise/auto-unseal/index.html.md, website/source/layouts/docs.erb
=> Update docs on auto unseal

website/source/docs/secrets/kv/index.html.md
Added clarification to KV documentation about default CLI behavior and how to preserve non-string type values.
=> KV documentation update

website/source/api/relatedtools.html.md
Add link to Goldfish a  web UI for Vault.
=> update relatedtools, add Goldfish UI.

website/source/api/secret/ssh/index.html.md
=> Fix spelling

vendor/github.com/go-ldap/ldap/bind.go, vendor/github.com/go-ldap/ldap/del.go, vendor/github.com/go-ldap/ldap/search.go, vendor/vendor.json
Fixes #3656
Fixes #3625
Fixes #3402
=> Update go-ldap with our patch for control packets.

CHANGELOG.md, builtin/logical/transit/path_config.go, builtin/logical/transit/path_keys.go, website/source/api/secret/transit/index.html.md
@vishalnayak if you get a chance to review this before you go, great, otherwise I'll just merge it.
=> Minor fixups to transit backup/restore

CHANGELOG.md, builtin/logical/transit/backend.go, builtin/logical/transit/path_backup.go, builtin/logical/transit/path_backup_test.go, builtin/logical/transit/path_config.go, builtin/logical/transit/path_keys.go, builtin/logical/transit/path_restore.go, helper/keysutil/lock_manager.go, helper/keysutil/policy.go, website/source/api/secret/transit/index.html.md
=> Transit: backup/restore

website/source/api/system/seal-status.html.md
- seal status response also has the nonce field.
- while here, also changing version
=> added the missing nonce and type fields

api/sys_seal.go, command/status.go
=> Adding recovery info to seal status

builtin/credential/github/backend.go
Adding MFA to GitHub authentication backend.
=> Add (Duo) MFA to the Github backend

website/source/docs/internals/telemetry.html.md
- Reformatted from table based content to header based so that
each metric can be directly linked via URL fragment
- Added some tips about monitoring and alerting on some metrics
- Corrected and validated some metric types and defintions
- Added missing storage backend metrics
- Generous interlinking to other documentation
=> Docs: Updated Telemetry documentation

website/source/docs/concepts/pgp-gpg-keybase.html.md
I found this out the hard way, so I updated the docs to indicate it more clearly.
=> Clarify that keybase is supported only in the CLI

http/sys_health.go, vault/core.go
=> Port IsDRSecondary over and enable returning it via sys_health

plugins/database/mongodb/connection_producer.go, plugins/database/mongodb/mongodb.go
=> CreateUser deadlock fix

api/secret_test.go, builtin/credential/token/cli.go, vendor/github.com/hashicorp/vault-plugin-auth-kubernetes/README.md, website/source/docs/audit/file.html.md, website/source/docs/audit/index.html.md, website/source/docs/auth/gcp.html.md, website/source/docs/concepts/auth.html.md, website/source/docs/concepts/policies.html.md, website/source/docs/concepts/tokens.html.md, website/source/docs/enterprise/mfa/mfa-duo.html.md, website/source/docs/enterprise/mfa/mfa-okta.html.md, website/source/docs/enterprise/mfa/mfa-pingid.html.md, website/source/docs/enterprise/mfa/mfa-totp.html.md, website/source/docs/secrets/pki/index.html.md, website/source/docs/secrets/ssh/signed-ssh-certificates.html.md
Removed just a few occurrences of the old, deprecated commands.
=> Cleanup of deprecated commands in tests, docs

helper/mfa/duo/path_duo_access.go
=> Fix intermittent panic connecting to Duo

website/source/api/auth/approle/index.html.md
=> docs/approle: Fix the expected type of metadata field in secret-id

website/source/docs/internals/telemetry.html.md
=> docs/telemetry: remove merge conflict remnant

builtin/credential/aws/client.go, helper/awsutil/generate_credentials.go
=> Propose small spelling change

website/source/intro/getting-started/install.html.md
Ref: https://github.com/mitchellh/cli/pull/72
https://github.com/hashicorp/vault/blob/f2dfba96558aa3a48590b0b8c7355eba9b562cb8/vendor/vendor.json#L1341-L1346
=> website: Include `fish` as a supported shell

builtin/credential/approle/backend.go, builtin/credential/aws/backend.go, builtin/logical/aws/backend.go, builtin/logical/aws/rollback.go, builtin/logical/pki/path_roles.go, vault/rollback.go
=> Don't run rollback and upgrade functionality if we are a replication secondary

api/renewer.go
=> Fix renewAuth to use the increment value

builtin/credential/cert/path_certs.go, builtin/logical/mssql/path_roles.go, builtin/logical/mysql/path_roles.go, vendor/github.com/hashicorp/vault-plugin-auth-gcp/plugin/path_role.go
does it help to update the spelling?
=> Propose fix a typo

command/operator_init.go, website/source/intro/getting-started/authentication.html.md, website/source/intro/getting-started/deploy.html.md, website/source/intro/getting-started/secrets-engines.html.md
Read through the initial docs and noticed a few typos
=> Lil typo fixes

website/source/docs/enterprise/replication/index.html.md
After discussing with Jeff Mitchell to get clarification, I updated the Replication table in https://www.vaultproject.io/docs/enterprise/replication/index.html to be more accurate and less confusing.
=> Updated replication table

command/audit_list.go, command/auth_list.go, command/base.go, command/commands.go, command/format.go, command/lease_renew.go, command/list.go, command/login.go, command/main.go, command/operator_generate_root.go, command/operator_init.go, command/operator_key_status.go, command/operator_rekey.go, command/operator_unseal.go, command/policy_list.go, command/policy_read.go, command/read.go, command/rotate.go, command/secrets_list.go, command/ssh.go, command/status.go, command/token_capabilities.go, command/token_create.go, command/token_lookup.go, command/token_renew.go, command/unwrap.go, command/write.go
Also remove OutputWithFormat as the logic can cause issues.
=> Pull formatting much further up to remove the need to use c.flagFormat

builtin/logical/transit/path_keys.go
=> Fix auditing for transit keys with backup/restore info

builtin/credential/okta/backend.go, builtin/credential/okta/path_config.go, website/source/api/auth/okta/index.html.md
Unlike before, the administrator opts-in to this behavior, and is
suitably warned.
Fixes #3872
=> Adds the ability to bypass Okta MFA checks.

physical/consul/consul.go, physical/consul/consul_test.go
=> Validate Consul service name is RFC 1123 compliant

website/source/api/auth/aws/index.html.md
Fixes the ambiguity called out in
https://groups.google.com/forum/#!msg/vault-tool/X3s7YY0An_w/yH0KFQxlBgAJ
=> auth/aws: Improve role tag docs as suggested on mailing list

website/source/docs/internals/telemetry.html.md
- Correct time to millis
- Correct storage backend summaries from # ops to duration of ops
=> DOCS: upadte Telemetry

website/source/assets/stylesheets/_global.scss
This fixes the tiny code font in header names.
=> Fix code in header font size

website/source/docs/internals/telemetry.html.md
- Add initial secrets engines metrics
- Update metrics types/values
- Update language for auth methods, secrets engines, audit devices
- Add more linking to relevant documentation
=> DOCS: update Telemetry with more coverage

builtin/credential/okta/backend.go
supports Okta Push. In lieu of #3908
=> Add Okta specific MFA workflow to Okta auth method. Note this only

website/source/api/secret/databases/index.html.md
=> Docs: Adding LIST for connections in database backend

website/source/guides/identity/authentication.html.md
=> Fixed a broken link

command/auth_help.go
=> Fix confusing error messages around help for 'vault auth'

website/source/docs/auth/aws.html.md
=> Correct endpoint's path in Doc

vault/core.go, vault/logical_system_integ_test.go
This allows giving up the HA lock to be skipped.
=> Rearrange shutdown logic to remove some lock switching

website/source/guides/secret-mgmt/dynamic-secrets.html.md
Like
```
guides-secret-mgmt--dataynamic-secrets
```
Obviously this should be
```
guides-secret-mgmt-dynamic-secrets
```
=> Fix autoreplacing issue

builtin/logical/database/path_creds_create.go
=> Honor mount-tuned ttl/max ttl for database credential generation

physical/couchdb/couchdb.go
Fixes #4124 
Performed manual testing and verified the fix.
=> physical/couchdb: Remove listing limit

website/source/api/relatedtools.html.md
Cryptr is a newly open sourced GUI for Vault, targeting the users of vault rather than the administrators.
This is provided to the community under Adobe's open sourcing initiatives.
=> Add Cryptr to related tools

builtin/logical/pki/cert_util.go, builtin/logical/pki/path_intermediate.go
=> Add ability to set CA:true when generating intermediate CSR.

builtin/credential/ldap/backend.go
=> We don't need to limit the size of ldap queries, so set a high limit

command/policy.go, website/source/docs/auth/github.html.md, website/source/docs/auth/ldap.html.md, website/source/intro/getting-started/deploy.html.md
- Remove redundant text
- Correct an example that triggers a deprecation warning
=> Fix minor docs and help text issues

website/source/guides/upgrading/index.html.md
A bit of information about upgrading in performance replication scenarios
=> Docs: add note about enterprise replication installations section to upgrade guide

website/source/api/auth/github/index.html.md
To address the issues reported --> https://app.asana.com/0/112957393038545/606134359086545/f
Added:
- Map GitHub Teams
- Read Team Mapping
- Map GitHub Users
- Read User Mapping
=> Update Github auth method API reference

command/commands.go, physical/gcs/gcs.go, physical/gcs/gcs_ha.go, physical/gcs/gcs_ha_test.go, physical/gcs/gcs_test.go, vault/core.go, website/source/docs/configuration/storage/google-cloud.html.md, website/source/docs/configuration/storage/spanner.html.md
Closes https://github.com/hashicorp/vault/pull/3466
This also:
- Converts things to use errwrap for consistency
- Adds additional logging during setup
- Allows more configuration via envvars
/cc @jefferai
=> Add HA support to the Google Cloud Storage backend

builtin/credential/okta/backend.go
Simple typo fix and line wrapping adjustment.
=> Fixed typo and adjusted line wrapping in backend help

website/source/intro/vs/keywhiz.html.md
As per Franklin Davis suggestion on the mailing list.
=> Grammatical error

CHANGELOG.md, builtin/credential/ldap/backend.go, builtin/credential/ldap/backend_test.go, builtin/credential/ldap/path_config.go, builtin/credential/ldap/path_groups.go, builtin/credential/ldap/path_users.go, website/source/api/auth/ldap/index.html.md
=> Case insensitive behavior for LDAP

vault/expiration.go
The latter removes a case where a token being revoked would end up
logging twice.
=> Allow not showing expirations, and don't log when skipToken

api/logical.go, command/delete.go, command/write.go
Done this way, existing tests pass, and it makes logical sense, so we're
likely to have the least impact like this.
=> Rejig 404 handling again.

website/redirects.txt, website/source/docs/configuration/storage/google-cloud-spanner.html.md, website/source/docs/configuration/storage/google-cloud-storage.html.md, website/source/docs/internals/telemetry.html.md, website/source/layouts/docs.erb
Marketers gonna market. Fully BC with redirects
=> Rename Google things to say "Google", update telemetry docs

website/source/guides/identity/approle-trusted-entities.html.md
Finally...  Found the broken link.  Removed the extra "( )" around the link.  Also, the link was missing "and".
=> Removed extra '( )' in the link

ui/app/adapters/auth-config/azure.js, ui/app/controllers/vault/cluster/settings/mount-secret-backend.js, ui/app/helpers/mountable-auth-methods.js, ui/app/helpers/tabs-for-auth-section.js, ui/app/models/auth-config/azure.js, ui/app/routes/vault/cluster/settings/auth/configure/section.js, ui/config/environment.js
Adds support for enabling the new GCP secrets engine and enabling and configuring the new Azure auth method.
=> UI - new backends

ui/app/adapters/secret.js, ui/app/controllers/vault/cluster/settings/mount-secret-backend.js, ui/app/models/mount-options.js, ui/app/models/secret-engine.js, ui/app/routes/vault/cluster/secrets/backend.js, ui/app/templates/vault/cluster/secrets/backend/list.hbs, ui/app/templates/vault/cluster/secrets/backends.hbs, ui/app/templates/vault/cluster/settings/mount-secret-backend.hbs
=> Update ui to reflect config changes for kv. versioned -> version

api/sys_mounts.go, vault/logical_system.go
Make options only run when the map is not empty and something has
changed.
=> Don't run every tune function every time tune is called.

website/source/docs/configuration/index.html.md
* Available in OSS Vault from 0.10+
=> Remove Enterprise Only flag

vault/identity_store_aliases.go, vault/identity_store_group_aliases.go, vault/identity_store_groups.go, vault/logical_system.go
Just added a few entries from missing path-help and fixed some in identity
=> Replacing wrong entries in path-help

ui/README.md
The UI README now has some relevant information 🙃.
=> update the readme to be more useful for UI development

builtin/logical/ad/backend_test.go, builtin/logical/ad/config/handler.go, builtin/logical/ad/creds/cred.go, builtin/logical/ad/creds/handler.go, builtin/logical/ad/roles/handler.go, builtin/logical/ad/roles/role.go, builtin/logical/ad/roles/role_test.go
- Respond with a 200 and no body other than a warning when posting the config
- Respond with a 204 and no body when posting roles
- Do not return the role name when getting roles by name
- Do not return the role name when getting creds by role name
=> Changes from RFC feedback

ui/app/templates/vault/cluster/settings/mount-secret-backend.hbs
=> Update seal wrap text in UI

command/login.go
Trivially manually tested
Closes #2758
=> Add -no-print to 'vault login'

builtin/credential/cert/path_login.go
=> Fix alias data being used for cert auth (serial number -> common name)

api/renewer.go
=> Close the doneCh in the renewer when we return from Renew

website/source/guides/operations/vault-ha-consul.html.md
Updated the HA with Consul Guide based on feedback. Current examples were incorrect and not working.
=> Clarify HA params, fixed typos

CHANGELOG.md, command/operator_init.go, website/source/docs/commands/operator/init.html.md, website/source/guides/upgrading/upgrade-to-0.9.0.html.md
Fixing a minor spelling mistake.
=> Fix minor spelling mistake

website/source/guides/identity/policies.html.md
=> fixed spelling error in step 1

physical/zookeeper/zookeeper.go
This should decrease chances of potential deadlock observed in https://github.com/hashicorp/vault/issues/4491 .
The patch keeps existing behavior of ZK backend in terms of public interface. Internally it adds re-try gouroutine that will attempt to release distributed lock multiple times. The goroutine is hardcoded to make 10 attempts each 1 second apart to release distributed lock. Reason for this is that ZK backend hardcodes ZK SessionTimeout to 1 second.
=> physical/zookeeper: Re-try to release lock in case of failure

ui/app/templates/components/shamir-flow.hbs
=> Update command in UI DR guide to non-deprecated version

website/source/api/system/mounts.html.md
=> Docs: Adding options information to mount endpoint

command/commands.go, command/format.go, command/format_test.go, command/main.go, command/operator_unseal_test.go
This turns out to not work very well for the demo server. Also,
it's kinda hacky.
=> Don't use environment as a mechanism for floating format around.

website/source/_ember_steps.html.erb, website/source/assets/javascripts/demo/initializer/load-steps.js
Added more steps to showcase the KV v2 features:
- Update data (both `put` and `patch`)
- View specific version of the data
- Delete data
- Recover the deleted data
- Permanently delete (destroy) data
- View the metadata
=> Vault Interactive Tutorial updates

command/format.go
I noticed a test failing and I don't think this line was intentionally placed.
=> Strip panic

vault/logical_system.go, vault/mount.go
Small typo in ListingVisibility type
Also added the accepted values in Description
=> Typo in Visibility + Add accepted values in Description

website/source/api/auth/userpass/index.html.md
Updates documentation related to the capability added in #4557
=> Add to doc for userpass bound cidrs

builtin/logical/pki/path_tidy.go
=> Ensure safety_buffer in PKI is greater than zero

Makefile, vendor/github.com/hashicorp/vault-plugin-secrets-ad/plugin/passwordconf.go, vendor/github.com/hashicorp/vault-plugin-secrets-ad/plugin/path_config.go, vendor/github.com/hashicorp/vault-plugin-secrets-ad/plugin/path_creds.go, vendor/github.com/hashicorp/vault-plugin-secrets-ad/plugin/util/passwords.go, vendor/vendor.json
This will allow us to pick up the `"formatter"` parameter.
=> Update ad plugin

command/auth_list.go, command/secrets_list.go
This makes them significantly easier to find/consume
=> Show mount accessors in normal secrets/auth list commands

website/source/docs/auth/cert.html.md
=> Tiny formalized edit

vault/expiration.go
This essentially caches lease information for token lookups, preventing
going to disk over and over.
=> Store lease times suitable for export in pending

plugins/database/mssql/mssql.go, plugins/database/mssql/mssql_test.go
=> Fix MSSQL Root Rotation Statement

website/source/guides/encryption/spring-demo.html.md, website/source/guides/secret-mgmt/dynamic-secrets.html.md
Two minor updates:
- Found an error in the sample payload JSON file in _Dynamic Secrets_ guide
- Launce added AWS support for his Spring demo (_Java Sample App using Spring Cloud Vault_)
=> Vault guides example update

builtin/logical/pki/backend_test.go, builtin/logical/pki/ca_util.go, builtin/logical/pki/cert_util.go, builtin/logical/pki/fields.go, builtin/logical/pki/path_issue_sign.go, builtin/logical/pki/path_roles.go, builtin/logical/pki/path_roles_test.go, builtin/logical/pki/path_root.go, website/source/api/secret/pki/index.html.md
This is a re-push of #4675 so that it can actually be dev'd in this repo.
Obsoletes #4675
=> Add URI SANs

website/source/api/secret/ad/index.html.md
This PR updates our docs to match the state of the world from the following PRs:
- https://github.com/hashicorp/vault-plugin-secrets-ad/pull/20
- https://github.com/hashicorp/vault-plugin-secrets-ad/pull/21
- https://github.com/hashicorp/vault-plugin-secrets-ad/pull/22
=> Update Active Directory secret engine docs

vault/barrier_view.go
=> Check for nil value in BarrierView.Put

website/source/docs/secrets/databases/mssql.html.md
Quick and easy change to make the passwords match.
=> Make documentation match Code example

website/source/guides/operations/disaster-recovery.html.md
Found a few minor typos that I missed.
=> Typo fixes in DR Setup guide

command/operator_init.go, command/operator_init_test.go
/cc @chrishoffman @jefferai 
Also lol, there was a test that tried to submit args
=> Validate operator init args

builtin/logical/database/backend_test.go, builtin/logical/database/secret_creds.go
=> Fix interface conversion panic during database creds revoke

website/source/api/system/key-status.html.md
=> Adding sample request to key status api docs

command/base_flags.go
=> Properly parse envvars for bools

website/source/api/auth/github/index.html.md, website/source/docs/auth/gcp.html.md, website/source/docs/secrets/identity/index.html.md, website/source/layouts/api.erb
It's really bothering me, sorry.
=> Properly capitalize H in GitHub

command/format.go
I'm open to alternative ideas here, but this seems fastest and least intrusive.
=> Special case handle TTLs in TableFormatter

builtin/logical/pki/backend_test.go, builtin/logical/pki/cert_util.go, website/source/api/secret/pki/index.html.md
It should not require a period to indicate subdomains being allowed
Fixes #4863
=> Fix permitted dns domain handling

physical/gcs/gcs.go, physical/gcs/gcs_ha.go, physical/gcs/gcs_ha_test.go, physical/gcs/gcs_test.go, physical/spanner/spanner.go, physical/spanner/spanner_ha.go, physical/spanner/spanner_ha_test.go, physical/spanner/spanner_test.go
Also fix a logging discrepancy
=> Use context from stdlib in google physical backends

builtin/credential/radius/path_login.go
=> Fix context shadowing during radius login

ui/app/adapters/control-group-config.js, ui/app/adapters/pki-config.js, ui/app/components/edit-form.js, ui/app/components/ttl-picker.js, ui/app/controllers/vault/cluster/settings/control-groups.js, ui/app/models/control-group-config.js, ui/app/models/control-group.js, ui/app/router.js, ui/app/routes/vault/cluster/access/control-group-accessor.js, ui/app/routes/vault/cluster/access/control-group.js, ui/app/routes/vault/cluster/access/control-groups.js, ui/app/routes/vault/cluster/settings/control-groups.js, ui/app/styles/components/control-group.scss, ui/app/templates/components/edit-form.hbs, ui/app/templates/vault/cluster/access/control-group-accessor.hbs, ui/app/templates/vault/cluster/access/control-groups.hbs, ui/app/templates/vault/cluster/settings.hbs, ui/app/templates/vault/cluster/settings/control-groups.hbs, ui/tests/integration/components/edit-form-test.js, ui/tests/pages/components/edit-form.js
This is the last Control Group PR before merging to master.
This adds the ability to specify the max ttl of a control group at `sys/config/control-groups`. 
Additionally, the feature detection for Control groups was added so that OSS and Pro Enterprise editions correctly mark the the feature as Premium.
Config:
OSS: 
Pro:
=> UI control groups config

website/source/docs/internals/telemetry.html.md
- Add Merkle related telemetry
- Add WAL related telemetry
=> Add missing telemetry metrics

logical/plugin/grpc_backend_client.go, logical/plugin/serve.go
=> plugins: Allow the server to receive large messages

physical/azure/azure.go, physical/azure/azure_test.go
=> Read all pages when listing in Azure physical backend

ui/app/components/identity/item-details.js, ui/app/controllers/vault/cluster/access/identity/index.js
Found these while prepping the demo site 😬
=> UI - e.errors not e.error

website/source/api/auth/approle/index.html.md
=> Docs: Add missing properties to AppRole 

website/source/docs/agent/autoauth/methods/aws.html.md
Minor addition, I wasn't familiar with the acronym and had to look it up. This might help the next person in the same position!
=> Expand TOFU acronym in AWS auto-auth docs

website/source/api/auth/jwt/index.html.md, website/source/guides/identity/secure-intro.html.md
Two small errors in documentation
=> Fix two errors in docs

vendor/github.com/hashicorp/vault-plugin-auth-gcp/plugin/cli.go, vendor/vendor.json
=> Update GCP auth plugin

api/api_integration_test.go, builtin/logical/database/backend_test.go, builtin/logical/postgresql/backend_test.go, physical/dynamodb/dynamodb_test.go, plugins/database/mongodb/mongodb_test.go, plugins/database/postgresql/postgresql_test.go
=> Docker container cleanup in tests

website/source/docs/secrets/databases/mssql.html.md
We should also look at updating the revocation code to handle some of these variations more gracefully.
=> Add RDS notes to MSSQL docs

website/source/docs/commands/index.html.md
=> Clarify "Commands" docs

website/source/intro/getting-started/authentication.html.md
This is for clarity since I had to check back to remember where it was mentioned.
=> Added a link to the "previous section" mentioned

website/source/docs/secrets/pki/index.html.md
https://github.com/hashicorp/vault/pull/5053
=> Add ttl params into csr signing docs

website/source/docs/auth/gcp.html.md
Fixes hashicorp/vault-plugin-auth-gcp#47
=> Fix docs typo (service-account => service_account)

helper/identity/templating.go, helper/identity/templating_test.go, vault/core.go, vault/dynamic_system_view.go, vault/ha.go, vault/logical_system.go, vault/policy.go, vault/policy_store.go, vault/policy_store_ext_test.go, vault/policy_store_test.go, vault/request_handling.go
Note when reviewing: this is definitely unoptimized, but I probably won't have a chance to work on optimization this cycle, so that can come over time.
=> ACL Templating

website/source/intro/getting-started/apis.html.md
Small edit to the documentation.
=> Edit, missing "to"

website/source/docs/commands/delete.html.md
Minor typo in `delete` command docs
=> Update delete.html.md - minor typo

website/source/guides/operations/index.html.md
Deployment Guide was missing from the index
=> [Guide] Added Deployment Guide in the index

ui/app/templates/components/wizard/init-setup.hbs
Just a couple minor edits to the UI init help text
=> Minor grammar edits

website/source/guides/upgrading/upgrade-to-0.11.0.html.md
- Correct typo
- Remove trailing spaces
=> Minor edits

website/source/guides/identity/authentication.html.md
Fix for https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/vault-tool/TmLjtdDxRvM/KHllk959AgAJ
=> [Guide] Fixed the reported issue

website/source/guides/identity/policy-templating.html.md
Fix the [issue](https://github.com/hashicorp/vault/commit/59c47a1b43f87d9362db0e8b301ac262e75dd700#r30360541)
=> Fixed the incomplete sentense

builtin/logical/pki/cert_util.go
=> Fix sign-verbatim PKI endpoint not honoring extra subject names

builtin/logical/database/backend_test.go, builtin/logical/database/secret_creds.go
=> Fix nil pointer if the embedded revocation statements from a role are nil

command/agent.go, command/agent/alicloud_end_to_end_test.go, command/agent/auth/alicloud/alicloud.go, vendor/github.com/hashicorp/vault-plugin-auth-alicloud/path_login.go, vendor/vendor.json, website/source/docs/agent/autoauth/methods/alicloud.html.md, website/source/layouts/docs.erb
- Adds AliCloud auth to the Vault Agent
- Adds docs
=> Add AliCloud auth to the Vault Agent

ui/app/components/mount-backend-form.js, ui/app/helpers/mountable-auth-methods.js, ui/app/helpers/mountable-secret-engines.js, ui/app/templates/components/wizard-content.hbs, ui/app/templates/components/wizard/alicloud-method.hbs, ui/app/templates/components/wizard/azure-engine.hbs, ui/app/templates/components/wizard/tutorial-idle.hbs, ui/app/templates/components/wizard/tutorial-paused.hbs
These were new in 0.11, and now we can enable them in the UI - thanks @joshuaogle for already adding the SVGs 🎉 :
=> UI - azure secrets alicloud auth

website/source/docs/enterprise/namespaces/index.html.md
If merged, this PR changes `identitys` to `identities` in `index.html.md` of Enterprise Namespace docs.
=> Typo: identities.

website/source/docs/commands/namespace.html.md
Minor edit to `lookup` subcommand description text
=> Docs: namespaces edit lookup subcommand text

website/source/guides/identity/index.html.md, website/source/guides/identity/policy-templating.html.md, website/source/layouts/guides.erb
Changed the title from "_ACL Policy Templating_" to "_ACL Policy **Path** Templating_" to be accurate.
=> [Guide] Title update

website/source/guides/identity/lease.html.md, website/source/guides/operations/autounseal-aws-kms.html.md
Updated the **Tokens and Leases** guide to clarify the `root` or `sudo` requirements for creating an orphan token.
=> [Guide] Tokens & Leases guide **Correction** 

website/source/api/system/audit.html.md
fixes file path option in samples
=> fixes file path option in samples

website/Gemfile, website/Gemfile.lock
- Mimics the approach taken in https://github.com/hashicorp/consul/pull/4670.
- Tested by running `$ make website` and `$ make build` and everything checks out fine. 
- Additional tests needed?
=> Update ffi to avoid CVE-2018-1000201

website/source/guides/partnerships/index.html.md
Fix partnerships docs formatting issues
=> Fix header issues

website/source/guides/partnerships/index.html.md
Upload docs fix to the website
=> Partnerships docs fix

website/source/guides/partnerships/index.html.md
=> partnerships-format

website/source/guides/partnerships/index.html.md
=> Broken link fix

builtin/credential/okta/path_config.go
=> Fix reading Okta token parameter when config param exists

ui/app/routes/vault/cluster.js
I've noticed that our polling was a bit race-y, so you could get in a state where it would poll much more often than it was supposed to. This moves the polling to ember-concurrency which will guarantee that there's only ever one instance of the task running (that's what the `drop` modifier does).
=> UI - fix the top level polling and use ember-concurrency

command/operator_init.go
=> UPDATE operator_init.go - minor grammar/doc fix

vault/identity_store_util.go
=> Fix remove Group Member in Identity Group not working

helper/namespace/namespace.go, helper/namespace/namespace_test.go
=> Fix issue with revoking leases that have periods in them

builtin/logical/pki/cert_util.go
=> Re-add default NotBefore duration in PKI

command/server.go
Fixes some sources of user strife
=> Warn when users don't configure api_addr

command/agent/auth/auth.go
=> Buffer authhandler output channel to prevent hang on shutdown

api/sys_health.go, api/sys_leader.go, command/format.go, http/sys_health.go, http/sys_leader.go, vault/core.go
Approved via BK in another channel
=> Add LastWAL in leader/health output

website/source/docs/concepts/tokens.html.md
=> Docs: Basics: Tokens: Note

ui/app/styles/components/ui-wizard.scss, ui/app/styles/core/buttons.scss, ui/app/styles/utils/_bulma_variables.scss, ui/app/templates/components/wizard-progress.hbs, ui/app/templates/components/wizard/auth-details.hbs, ui/app/templates/components/wizard/policies-others.hbs, ui/app/templates/components/wizard/replication-details.hbs, ui/app/templates/components/wizard/secrets-display.hbs, ui/app/templates/components/wizard/tools-unwrapped.hbs, ui/app/templates/components/wizard/tutorial-error.hbs
- Adds more styles for Wizard Progress
- Moves the bar over the header line
- Fixes a semi-related issue regarding the wizard buttons in Firefox
=> UI: Wizard progress styles

physical/mysql/mysql.go
Fixes https://github.com/hashicorp/vault/issues/5529 issue introduced with HA support for Mysql (#4686 )
=> [5529] Mysql HA: table creation error using InnoDB and utf8 charset

website/deploy/variables.tf
I'm so sorry for missing this one 😢
=> Small website deployment fix

website/config.rb, website/source/layouts/layout.erb
Analytics wasn't configured correctly previously - this resolves that issue, and also removed some unused and commented out methods from the config file.
=> Analytics Correction, config file cleanup

website/data/docs_detailed_categories.yml, website/source/docs/plugin/partnerships.html.md
Updates to include partnerships within new site
=> Partnerships docs updates

command/base_helpers.go
=> Fix command panic by returning empty (not nil) map

website/source/docs/concepts/tokens.html.md
I think that is a duplicated word.
=> fix duplicated word

website/source/docs/secrets/gcpkms/index.html.md
Closes https://github.com/hashicorp/vault-plugin-secrets-gcpkms/pull/3
=> Update docs and permissions

website/assets/css/pages/_downloads.css, website/assets/package.json
Some spacing adjustments based on feedback for the downloads page, including a version bump for the `product-downloader` component that will further fix some responsive/spacing issues inside the component itself.
=> website: adjust downloads page responsive behaviors

command/seal_migration_test.go, command/server.go, command/server/config.go, command/server/seal/server_seal.go, vault/seal/seal_testing.go
This allows for testing auto unseals using the test seal in dev mode.
=> Add -dev-auto-seal option

command/agent.go, command/agent/approle_end_to_end_test.go, command/agent/auth/approle/approle.go, website/source/docs/agent/autoauth/methods/approle.html.md
On some part of our infrastructure, we want to use the vault agent against AppRole authentication method.
This PR adds abilities to vault agent to get a token from AppRole auth method.
Role-id/secret-id is placed in files and path to this files must be specified in config.
=> WIP Agent AppRole auto-auth

website/source/community.html.erb
Just a minor adjustment to the wording of the training item on the community page.
=> website: community page content update

command/agent/approle_end_to_end_test.go, command/agent/auth/approle/approle.go, website/source/docs/agent/autoauth/methods/approle.html.md
=> Add approle agent method removing secret ID file by default.

website/source/layouts/api.erb
[This commit](https://github.com/hashicorp/vault/commit/48385d53aa0d162219b046554426f841805a6287#diff-dea425496a57aa530af5ad4c5d38acba) broke the sidebar nav, this fixes it! 🎉
=> Fix sidebar links

website/source/docs/auth/jwt.html.md
- Add convenience/contextual link to API documentation
=> docs: update JWT auth method

physical/consul/consul_test.go, physical/dynamodb/dynamodb_test.go, physical/etcd/etcd3_test.go, physical/etcd/etcd_test.go, physical/foundationdb/foundationdb_test.go, physical/gcs/gcs_ha_test.go, physical/inmem/inmem_ha_test.go, physical/mysql/mysql_test.go, physical/spanner/spanner_ha_test.go, physical/testing.go, physical/zookeeper/zookeeper_test.go
Closes #5588
Also removed the type assertions since we are now guarding during build time.
=> Clean up HABackend tests

vault/seal/alicloudkms/alicloudkms.go
=> Matching AliCloud seal config name to storage backend

website/assets/package.json, website/assets/yarn.lock
Just a routine dependency update! 😁
=> Add analytics tracking to downloads component

website/source/netlify-redirects
Added a redirect for _Vault Cluster Monitoring_ guide.
=> [Learn] Added a missing redirect link

command/agent/approle_end_to_end_test.go
Essentially the same as https://github.com/hashicorp/vault/pull/5663.
=> Bump timeout due to potential backoff retry delay

vault/logical_passthrough.go
Follow up of hashicorp/vault-plugin-secrets-kv#18.
Fixes #5596.
=> Disallow writing to empty paths

vault/barrier_aes_gcm.go
=> Fix panic when storage value is nil

website/README.md
The new website has a few different places that display navigation in different ways, this PR expands the readme to explain how and where to update them!
=> Update website readme with instructions for updating navigation

vault/seal/alicloudkms/alicloudkms.go, vault/seal/alicloudkms/alicloudkms_acc_test.go
This also adds the acceptance test from #5738.
Supersedes #5738
=> Fixing AliCloud KMS seal encryption/decryption

website/source/docs/enterprise/hsm/behavior.html.md
=> Fix CLI flag name for rekeying

website/source/docs/auth/aws.html.md
=> Recommend IAM auth over EC2

website/source/api/system/replication/replication-dr.html.md
Reported by Naomi --> https://hashicorp.slack.com/archives/C04L34UGZ/p1542244669909400?thread_ts=1542244599.909200&cid=C04L34UGZ
=> [API doc] Fixed broken link in the DR replication API doc

ui/app/components/search-select.js, ui/app/styles/app.scss, ui/app/styles/components/popup-menu.scss, ui/app/styles/components/search-select.scss, ui/app/styles/core/forms.scss, ui/app/styles/core/title.scss, ui/app/templates/components/form-field.hbs, ui/app/templates/components/kv-object-editor.hbs, ui/app/templates/components/search-select-placeholder.hbs, ui/app/templates/components/search-select.hbs, ui/app/templates/vault/cluster/access/methods.hbs
@madalynrose We basically just had the list left so I put that together. When I reset to your branch I noticed that the input doesn't autofocus there either, but it is a bit of a problem that it's even less obvious now. Think there's any way to focus the input for them?
Also includes some fixes for the form section headers since those have been bugging me. Also fixes that wide popover menu on Auth Methods which I could have sworn we already fixed once.
=> UI: Search select styles

website/assets/package.json
This should patch a navigation issue that was reported this week!
=> Update docs sidenav

command/agent/auth/auth.go
=> agent: fix auth when multiple redirects

ui/app/styles/components/popup-menu.scss, ui/app/templates/partials/status/cluster.hbs
- Removes highlight from popup menu links for current page
- Fixes issue with license link
- Add chevron to "See details" item
=> UI: Fix popup menu active color and license link

scripts/gen_openapi.sh
Noticed and fixed this minor typo in a comment.
=> Fixed typo in a comment

ui/app/components/masked-input.js, ui/app/models/auth-config/ldap.js, ui/app/styles/components/masked-input.scss, ui/app/templates/components/form-field.hbs, ui/app/templates/components/masked-input.hbs, ui/tests/integration/components/form-field-test.js, ui/tests/pages/components/form-field.js
Mask the password when setting up the LDAP auth method!
Before:
_______
After:
=> mask password on ldap auth form

website/source/docs/auth/kubernetes.html.md
Signed-off-by: Bert Roos <Bert-R@users.noreply.github.com>
=> Added comma for readability

website/source/layouts/docs.erb
Adds missing MSSQL storage docs to sidebar
=> Add MSSQL storage docs to sidebar

command/operator_generate_root.go, command/operator_migrate_test.go, helper/base62/base62.go, helper/base62/base62_test.go, helper/keysutil/encrypted_key_storage.go, http/sys_generate_root.go, plugins/helper/database/credsutil/credsutil.go, vault/expiration.go, vault/generate_root_test.go, vault/token_store.go
Also move existing base62 encode/decode operations to their only points
of use.
=> Simplify base62.Random

website/README.md, website/bootstrap.sh
Readme expanded to include both docker and direct run instructions, and bootstrap script improved to be more thorough.
=> Improve local development instruction

ui/app/templates/vault/cluster/policies.hbs, ui/app/templates/vault/cluster/policy.hbs
=> fix policies sidebar title

website/source/guides/operations/deployment-guide.html.md
Updated the Deployment guide with Additional available in Vault 1.0 and bumped product version to 1.0
=> Update DG to Vault 1.0

vault/seal/awskms/awskms.go
Closes #6016. I used a t2.nano instance to verify that this approach works IRL.
=> Check ec2 instance metadata for region

vault/seal/gcpckms/gcpckms.go
=> Typo fix in gcpckms.go

vault/acl.go, vault/logical_system.go, vault/policy.go, vault/policy_test.go
=> Rename glob -> prefix in ACL internals

plugins/database/mssql/mssql_test.go
We have a few issues open related to MSSQL (#6060, #5977, and #5914). 
This PR converts MSSQL to using Docker so it's easier to quickly develop and test against it to help solve those issues in separate PRs.
=> Convert MSSQL tests to Docker

website/source/docs/commands/operator/unseal.html.md
=> Update documentation for command operator unseal

website/source/docs/auth/azure.html.md
There are probably better ways to massage this but I think it would be helpful to have something like this included
=> Docs: Azure auth example using metadata service

builtin/credential/aws/path_config_identity.go
Small typo introduced in #6133
=> Fix typo in help text

builtin/credential/approle/backend.go, builtin/credential/approle/path_role.go, builtin/credential/aws/backend.go, builtin/credential/aws/path_role.go, builtin/credential/ldap/path_config.go, builtin/logical/aws/path_roles.go, builtin/logical/aws/rollback.go
These are locations where we may need/want perf standby guards but do not currently have them.
=> Add more perf standby guards

website/source/api/auth/approle/index.html.md
- Use consistent "Create/Update" heading text style
=> Update AppRole API docs

builtin/logical/database/backend_test.go, builtin/logical/database/path_creds_create.go
=> Return a more helpful error message for unknown db roles

website/source/docs/configuration/index.html.md
Documentation : Add the supported log level configurations
`Supported log levels: Trace, Debug, Error, Warn, Info.`
=> Documentation : Add Vault supported log levels

vault/cors.go, vault/logical_system_test.go
=> Don't duplicate CORS headers

website/source/docs/configuration/listener/tcp.html.md
- Clarify that PROXY protocol version 1 is currently supported
- Add missing backtick to fix formatting issue
=> Update configuration/listener documentation

.travis.yml, ui/scripts/start-vault.js
Quick update to https://github.com/hashicorp/vault/pull/6218/ to ensure we're not swallowing errors.
=> throw an error when starting vault if one occurs

vault/router.go
=> typo in pathsToRadix doc

website/source/docs/commands/server.html.md
Based on an answer from Brian Kassouf on the Google Group: https://groups.google.com/d/msg/vault-tool/7Qf9Hn1w3jA/yGUIKZxHGAAJ
=> Documenting -dev-plugin-dir vault server option

CHANGELOG.md, builtin/credential/aws/cli.go, helper/awsutil/region.go, helper/awsutil/region_test.go, vault/seal/awskms/awskms.go, website/source/docs/configuration/seal/awskms.html.md
@joelthompson what do you think of this? If you think this is the way to go, I'll add some unit tests to the region-parsing code and merge it into the branch.
Thanks! :-)
=> Support env vars for STS region

website/source/intro/getting-started/secrets-engines.html.md
That sentence sounds weird to me. I think this way is better.
=> [Documentation] Update secrets-engines.html.md

website/source/guides/identity/policy-templating.html.md
showing how to allow users auth'd with userpass method to modify their own passwords
=> fix example that was out-of-date

command/server/seal/server_seal.go, command/server/seal/server_seal_transit.go, vault/seal/seal.go, vault/seal/transit/transit.go, vault/seal/transit/transit_acc_test.go
This adds the ability to use a different Vault instance as an autounseal using Vault's Transit secret engine.
=> Transit Autounseal

builtin/logical/database/backend_test.go, builtin/logical/database/path_roles.go, builtin/logical/database/path_roles_test.go
- Implements functions directly rather than as callbacks, mainly to reduce complexity. This makes this PR look like more code change than it is, because when I did it I needed to de-dent a bunch of code.
- Errors if someone tries to set rotation frequency to something under than 60 seconds.
=> Tweaks from testing

website/source/docs/partnerships/index.html.md
=> Update partnership doc

website/source/docs/secrets/databases/oracle.html.md
=> Correct doc

website/source/docs/secrets/gcp/index.html.md
=> Fixed typo

vault/seal/transit/test-tmp/.gitignore, vault/seal/transit/transit_acc_test.go
Dockertest is not mounting the temporary directory correctly.  Trying to workaround this issue for travis.
=> Fixing transit seal tests

vault/testing.go
Addresses https://github.com/hashicorp/vault/issues/6339.
=> testing: allow logger and audit backends to be set in TestCoreWithSeallAndUI

command/agent/cache_end_to_end_test.go
... to extract bits relating to setting up approle-based auth and authing/token-reading.  This should be helpful for writing end-to-end tests for the client support for auto-auth.
=> Refactor TestCache_UsingAutoAuthToken 

ui/app/components/alert-popup.js, ui/app/templates/components/alert-popup.hbs, ui/app/templates/vault/cluster.hbs
This PR moves our implementation of a flash message into a component using`AlertBanner` and `AlertInline` as references.
=> add AlertPopup

command/ssh.go
=> ssh on windows: fix file handling problem

command/commands.go, command/commands_nonwindows.go, command/commands_windows.go
=> Fix windows build by moving references to SIGUSR2 into a file not built

plugins/database/elasticsearch/client.go, plugins/database/elasticsearch/client_test.go, plugins/database/elasticsearch/test-fixtures/responses.go
This PR is identical to https://github.com/hashicorp/vault-plugin-secrets-elasticsearch/pull/1 but moved over to the Vault repo.
=> Add Elasticsearch client 

ui/app/styles/components/popup-menu.scss, ui/app/styles/core/footer.scss, ui/app/templates/components/auth-info.hbs, ui/app/templates/vault.hbs
Before:
After:
---
Before:
After:
=> UI: Mobile style fixes

website/source/docs/concepts/lease.html.md
=> Clarify that token revocation leads to lease revocation

website/source/docs/configuration/storage/consul.html.md, website/source/docs/configuration/storage/zookeeper.html.md
=> Clarify config option wording

website/source/docs/secrets/azure/index.html.md
This will ensure that the docs render correctly.
=> [docs] Fix a minor issue with Azure secrets docs

website/source/docs/configuration/seal/gcpckms.html.md
Sorry for mistake typo 😢 
Ref: https://github.com/hashicorp/vault/pull/6327/files#r270674452
=> fix typo in gcpckms.html.md, `cloudkms.cryptoKeys.get`

physical/dynamodb/dynamodb.go, physical/dynamodb/dynamodb_test.go
=> Fix dynamodb HA lock race

physical/dynamodb/dynamodb_test.go
=> DynamoDB test method typo fix

website/source/docs/auth/jwt_oidc_providers.html.md
Based on my experience documented in this issue https://github.com/hashicorp/vault/issues/6494, and encouraged by @kalafut, I am adding some documentation for using the OIDC auth method with Azure AD. I have not put it in bullet form, since it does not cover every single necessary step, and I did not want to take up too much space on the page.
Please let me know if it follows the spirit of the docs and if I need to update/change/expand something.
=> Update OIDC docs for Azure AD

vault/acl.go, vault/acl_test.go, vault/policy.go
It should have exactly the same behaviour, at least, that's the intent.
=> Tweak Jeff's implementation for greater readability/debuggability.

builtin/credential/okta/backend.go
=> Fix a dropped Okta error

website/source/api/libraries.html.md
=> docs: added support for .net standard 2.0 as well

website/source/docs/configuration/seal/azurekeyvault.html.md
Fixed some typos on the environment variable names
=> azurekeyvault doc fixed typos

.circleci/config.yml, ui/testem.js
This configures an initial (passing!) CircleCI pipeline!
=> Add initial CircleCI config

.circleci/config.yml
This adds a quick check to make sure the vendor dir is up to date.
=> add go mod vendor check

website/source/docs/concepts/seal.html.md
Fixed for sentence flow: "When you bring up your server back up" to "When you bring your server back up".
=> docs: better sentence flow

audit/format.go, audit/format_jsonx_test.go
For consideration in 1.1 since it'll need a CHANGES entry but this could be deferred further.
=> Add some omitempties to audit logs

website/source/docs/secrets/consul/index.html.md
Fixed typo: appropiate/appropriate
=> docs: fixed typo

sdk/framework/backend.go
Multierror is not nil unless you return ErrorOrNil, so this was causing
non-nil errors to be returned when not expected.
Also we need to ensure we only call handleWALRollback if a function
exists.
=> Fix some regressions

go.mod, go.sum, sdk/database/dbplugin/database.pb.go, sdk/plugin/pb/backend.pb.go, vault/request_forwarding_service.pb.go
gRPC updated to 1.20.1 which fixes a couple of important bugs.
Updates protos as well.
=> Update grpc and protos

sdk/logical/audit.go
Adds Type field and makes Request and Response interface{}.  The one in audit will go away in a subsequent changeset.
Add OptMarshaler interface for doing JSON marshaling with options.
=> Copy LogInput from audit package, add OptMarshaler

ui/app/components/toolbar-download-button.js, ui/app/components/toolbar-filters.js, ui/app/components/toolbar-secret-link.js, ui/app/templates/vault/cluster/policy/show.hbs, ui/lib/core/addon/components/confirm-action.js, ui/lib/core/addon/components/toolbar-actions.js, ui/lib/core/addon/components/toolbar-link.js, ui/lib/core/addon/components/toolbar.js, ui/lib/core/addon/helpers/message-types.js, ui/lib/core/addon/templates/components/confirm-action.hbs, ui/stories/confirm-action.md, ui/stories/confirm-action.stories.js, ui/stories/toolbar/toolbar-actions.md, ui/stories/toolbar/toolbar-actions.stories.js, ui/stories/toolbar/toolbar-download-button.md, ui/stories/toolbar/toolbar-download-button.stories.js, ui/stories/toolbar/toolbar-filters.md, ui/stories/toolbar/toolbar-filters.stories.js, ui/stories/toolbar/toolbar-link.md, ui/stories/toolbar/toolbar-link.stories.js, ui/stories/toolbar/toolbar-secret-link.md, ui/stories/toolbar/toolbar-secret-link.stories.js, ui/stories/toolbar/toolbar.md, ui/stories/toolbar/toolbar.stories.js
Adds Toolbar and updates ConfirmAction:
=> UI: Add Toolbar to Storybook

website/source/docs/secrets/nomad/index.html.md
Fixed wording: "lets create an"/"lets create a"
=> docs: wording

website/source/api/auth/jwt/index.html.md
=> Fix OIDC API examples

api/secret.go
=> Added missing entity_id to SecretAuth struct

website/source/docs/commands/operator/rotate.html.md, website/source/docs/configuration/storage/dynamodb.html.md, website/source/docs/configuration/storage/etcd.html.md
Added minor fixes to improve sentence flow.
=> docs: minor fixes to improve sentence flow

website/source/docs/upgrading/index.html.md
Making the warning to be more visually alerting. 
(Ref: [Asana task](https://app.asana.com/0/112957393038545/1123313636499446/f))
=> upgrade guide warning about downgrading

api/sys_rekey.go, command/operator_rekey.go
=> Fixed wrong rekey recovery backup client API URL

website/source/api/auth/okta/index.html.md
=> Switch to simpler 'configured'

.gitignore, website/assets/package-lock.json
Trying to work out some build issues with the website, and seeing if this helps!
=> Add lockfile for website

physical/raft/fsm.go
=> Fix 32-bit builds

sdk/helper/tokenutil/tokenutil.go
@madalynrose going to merge this now but please let me know if the chosen words/verbiage will end up looking weird in the UI!
=> Add DisplayAttributes to tokenutil fields

builtin/credential/approle/path_role.go, builtin/credential/aws/path_role.go, builtin/credential/cert/path_certs.go, builtin/credential/github/path_config.go, builtin/credential/okta/path_config.go, builtin/credential/userpass/path_users.go, sdk/helper/tokenutil/tokenutil.go
This drastically reduces boilerplate for upgrading existing values
=> Add UpgradeValue path to tokenutil

ui/app/adapters/kmip/credential.js, ui/app/adapters/kmip/role.js, ui/app/adapters/kmip/scope.js, ui/app/models/kmip/credential.js, ui/app/models/kmip/role.js, ui/app/models/kmip/scope.js, ui/app/serializers/application.js, ui/app/utils/api-path.js, ui/lib/core/addon/components/list-item.js, ui/lib/core/addon/components/menu-loader.js, ui/lib/core/addon/components/model-wrap.js, ui/lib/core/addon/mixins/list-controller.js, ui/lib/core/addon/templates/components/menu-loader.hbs, ui/lib/core/addon/templates/components/model-wrap.hbs, ui/lib/core/app/components/menu-loader.js, ui/lib/core/app/components/model-wrap.js, ui/lib/kmip/addon/components/edit-form-kmip-role.js, ui/lib/kmip/addon/routes/scope/roles/create.js, ui/lib/kmip/addon/routes/scopes/create.js, ui/lib/kmip/addon/templates/components/edit-form-kmip-role.hbs, ui/lib/kmip/addon/templates/credentials/index.hbs, ui/lib/kmip/addon/templates/credentials/show.hbs, ui/lib/kmip/addon/templates/role.hbs, ui/lib/kmip/addon/templates/scope/roles.hbs, ui/lib/kmip/addon/templates/scopes/index.hbs, ui/tests/integration/components/edit-form-kmip-role-test.js, ui/tests/unit/adapters/kmip/role-test.js, ui/tests/unit/utils/api-path-test.js
Scopes and roles may now be deleted from the UI and credentials can be revoked.
=> UI - add delete for the various kmip models

website/source/docs/configuration/storage/foundationdb.html.md
Fixed minor spelling error: sychronized/synchronized.
=> docs: spelling

website/source/api/auth/token/index.html.md
- Update sample `payload.json`
- Update sample response
=> Update API docs for Create Token — resolves #7053

vault/wrapping.go
Wrapping validation was deferring the function to audit log before
actually checking if we were sealed or standby, and without having the
read lock grabbed.
=> Fix nil pointer panic in wrapping validation

website/source/docs/concepts/dev-server.html.md
=> Explain the dev server mounts a KV store

command/commands.go, command/operator_raft.go, command/operator_raft_snapshot.go, command/operator_raft_snapshot_restore.go, command/operator_raft_snapshot_save.go
Additionally, did a few small cosmetic changes to be consistent with the existing layout.
=> Added operator raft and operator raft snapshot descriptions

Makefile, audit/hashstructure_test.go, builtin/logical/pki/path_root.go, helper/metricsutil/metricsutil.go, physical/foundationdb/foundationdb_test.go
=> Call goimports as well as gofmt when doing a `make fmt`

command/agent/cache/handler.go, command/agent/cache/lease_cache_test.go, physical/raft/logstore/bolt_store.go, physical/raft/raft.go, physical/raft/snapshot.go, sdk/plugin/grpc_backend_client.go, sdk/queue/priority_queue_test.go, vault/external_tests/response/allowed_response_headers_test.go, vault/identity_store_oidc.go, vault/policy_store.go, vault/request_forwarding_rpc.go, vault/rollback.go
Just a bunch of nitpicky typo fixes.
=> Fixed a bunch of typos

builtin/credential/aws/path_login.go, builtin/credential/cert/path_login.go, builtin/credential/github/path_login.go, builtin/credential/ldap/path_login.go, builtin/credential/okta/backend.go, builtin/credential/radius/path_login.go, builtin/credential/userpass/path_login.go
=> Add req.Connection check in front of bound cidrs

builtin/logical/pki/path_revoke.go
It needs to do a write for the CRL and to move to the revoked prefix
=> Don't try to revoke certs from PKI on perf standby

vault/testing.go
When cleaning up a TestCluster, set each core's logger to level Error. This eliminates a bunch of noise at the end of a test's logs, making it easier to diagnose test failures.
Add TestCluster.Logger.  This is intended to be used when test helpers want to log something. If TestClusterOptions.Logger is non-nil, it will be used as the cluster logger, otherwise we create one based on test name.  In the absence of CoreConfig.Logger, this logger is also used as the parent of each core's log.  This makes it easy when running parallel tests to identify which log message came from which test.
=> Improve logging in tests

helper/builtinplugins/registry.go, ui/app/routes/vault/cluster/access/method/item/list.js, ui/app/services/path-help.js, ui/app/templates/components/generated-item-list.hbs, ui/app/templates/components/generated-item.hbs, ui/app/utils/openapi-to-attrs.js, ui/tests/unit/utils/openapi-to-attrs-test.js
=> UI OpenAPI fixes

CHANGELOG.md
fixup the semantic version number
=> fixup the semantic version number

helper/testhelpers/testhelpers.go
We're waiting for perf standby last wal segments, but not generating any traffic, so the condition is never satisfied.  Fixed by continuously updating a KV value.  It's a little weird to do so in each of the goroutines, but there's no harm and it's simplest.
All my original testing was done with a version of WaitForActiveNodeAndPerfStandbys that lacked the actual test, so it didn't fail but it also didn't serve it's intended purpose.  This was discovered in review, but when I added the test condition I neglected to re-run tests.  Unfortunately this code lives in a repo that can't exercise it because perf standbys don't exist in OSS.  I should've copied it to ent and tested it there, but I didn't.
=> Fix regression introduced with WaitForActiveNodeAndPerfStandbys

scripts/gen_openapi.sh
Noticed we've added a couple of engines that it would be nice to have in the `gen-openapi` script.
=> Add engines to OpenAPI

.circleci/config.yml, .circleci/config/jobs/test-ui-browserstack.yml
- Specifically to solve an OOM for babel.
=> ci: increase memory for browserstack tests

command/agent/auth/alicloud/alicloud.go, command/agent/auth/aws/aws.go
=> Backport 1.2.1: avoid a panic on failed creds polling

ui/app/components/key-value-header.js, ui/app/components/namespace-picker.js, ui/app/lib/key-utils.js, ui/app/mixins/with-nav-to-nearest-ancestor.js, ui/app/routes/vault/cluster/logout.js, ui/app/services/namespace.js, ui/app/templates/components/namespace-link.hbs, ui/app/templates/components/namespace-picker.hbs, ui/tests/acceptance/enterprise-namespaces-test.js
This is a back port of https://github.com/hashicorp/vault/pull/7186
=> Backport 1.2.1: ui namespace fixes

helper/testhelpers/testhelpers.go
Eliminate a race stemming from each core's monitoring goroutine sharing the client for the active node.
=> fix race in WaitForActiveNodeAndPerfStandbys

builtin/logical/aws/path_roles.go, builtin/logical/aws/path_roles_test.go
This refactors role validation for the AWS secrets engine to be in a
separate method. Previously, all validation was interspersed with the
parsing of parameters when creating/updating a role, which led to a high
degree of complexity. Now, all validation is centralized which makes it
easier to understand and also easier to test (and so a number of test
cases have been added).
=> logical/aws: Refactor role validation

builtin/credential/radius/path_login.go
=> Fix regression that causes panic when logging in via Radius.

builtin/credential/approle/path_role_test.go, sdk/logical/token.go, sdk/logical/token_test.go
=> Backport 1.2: sdk/logical: handle empty token type string values as TokenTypeDefault

ui/lib/core/addon/components/string-list.js, ui/lib/core/addon/templates/components/string-list.hbs, ui/tests/acceptance/settings/configure-secret-backends/pki/section-urls-test.js, ui/tests/integration/components/form-field-test.js, ui/tests/pages/components/form-field.js, ui/tests/pages/secrets/backend/pki/edit-role.js
Backport of #7254
* change input to textarea and use autosize on them
* fix some tests
=> Backport: 1.2.2: multiline input for string-list

ui/app/services/auth.js, ui/app/templates/components/status-menu.hbs
Backport of #7337 
* dismiss status menu on click instead of hover
* allow redirect on 204
=> Backport: 1.2.3: Ui/dismiss status menu click (#7337)

command/debug.go
This PRs is based off https://github.com/hashicorp/vault/pull/7375, which contains scaffolded code for the debug CLI. This particular set of changes adds the metrics target for capture.
=> debug: add metrics capture target

vault/identity_store_groups.go, website/source/docs/configuration/storage/oci-object-storage.html.md
This is documentation for OCI Object Storage as backend storage in this PR https://github.com/hashicorp/vault/pull/6985
=> OCI Object Storage documentation

physical/raft/snapshot_test.go
Fix snapshot test by changes from #7369
=> raft: fix TestRaft_Snapshot_Take_Restore

website/source/api/auth/azure/index.html.md.erb
=> Fix Azure auth api docs

website/source/docs/configuration/storage/postgresql.html.md
=> Document Postgres ha_table parameter

website/source/api/secret/databases/mysql-maria.html.md, website/source/api/secret/databases/postgresql.html.md
Closes #7433
Documenting the mysql and postgres password policy based on this code:
- https://github.com/hashicorp/vault/blob/master/plugins/database/mysql/mysql.go#L126
- https://github.com/hashicorp/vault/blob/master/plugins/database/postgresql/postgresql.go#L184
- https://github.com/hashicorp/vault/blob/master/sdk/database/helper/credsutil/sql.go#L70
=> document mysql and postgres generated password complexity

website/source/docs/commands/kv/destroy.html.md
This PR includes a minor change in kv api docs
=> Fix kv destroy command in API docs

website/source/docs/enterprise/replication/index.html.md
A Vault Enterprise Pro customer in Japan has tried to get Vault DR replication working using Google Cloud Storage.
They were frustrated to learn that GCS may not have support for transactional updates which has resulted in a lot of wasted time.
The complaint was that this was not clear from our documentation.
This note may help customers to understand sooner that not all highly available backends support transactional updates.
=> Early indication of storage backend requirements

command/login.go, command/login_test.go
=> Ignore any existing token during CLI login

website/source/api/system/metrics.html.md
- Format curl command to be similar to other sample requests
- Add single quotes to URL for '?' so that sample is functional
- Delete trailing space
- Add ellipsis for longer sample response output
=> Update sample request/response

website/source/docs/configuration/seal/transit.html.md
=> Fix transit docs env var typo

command/server.go
=> Backport: Log proxy settings from environment on startup (#7528)

helper/metricsutil/metricsutil.go, http/sys_metrics.go, http/sys_metrics_test.go, vault/logical_system.go
=> Unauth metrics: Fix missing parse form and error response

website/source/api/relatedtools.html.md
Hi folks! Added new tool:
It's JS CLI tool that fetches secrets in parallel, puts them into the environment and then execs the process that needs them. Supports auth token renewal, multiple auth backends, verbose logging and dummy mode.
It used widely for production infrastructure at Namecheap.
=> New third-party tool added

http/logical.go, vault/external_tests/misc/recovery_test.go, vault/generate_root.go
Improve integ test to actually make changes while in recovery mode and
verify they're still there after coming back in regular mode.
=> Fix a panic triggered when handling a request that yields a nil response.

website/source/docs/commands/operator/init.html.md
=> Revert "Minor typo fix on website/docs"

website/source/docs/agent/autoauth/methods/aws.html.md, website/source/docs/agent/autoauth/methods/kubernetes.html.md, website/source/docs/agent/caching/index.html.md, website/source/docs/auth/approle.html.md, website/source/docs/concepts/policies.html.md, website/source/docs/configuration/seal/awskms.html.md, website/source/docs/configuration/seal/azurekeyvault.html.md, website/source/docs/configuration/seal/gcpckms.html.md, website/source/docs/configuration/seal/pkcs11.html.md, website/source/docs/configuration/seal/transit.html.md, website/source/docs/enterprise/control-groups/index.html.md, website/source/docs/enterprise/namespaces/index.html.md, website/source/docs/enterprise/replication/index.html.md, website/source/docs/enterprise/sentinel/index.html.md, website/source/docs/secrets/azure/index.html.md, website/source/docs/secrets/cubbyhole/index.html.md, website/source/docs/secrets/databases/index.html.md, website/source/docs/secrets/kmip/index.html.md, website/source/docs/secrets/kv/kv-v1.html.md, website/source/docs/secrets/kv/kv-v2.html.md, website/source/docs/secrets/pki/index.html.md, website/source/docs/secrets/ssh/one-time-ssh-passwords.html.md, website/source/docs/secrets/transit/index.html.md
To cross-reference, I added a link to matching guide on the [learn.hashicorp.com](https://learn.hashicorp.com/vault) site:
=> [Doc] Added links to matching Learn URL

command/agent/auth/aws/aws.go
https://github.com/hashicorp/vault/pull/7632
=> Backport: Add region parameter to AWS agent auto auth (#7632)

builtin/credential/aws/cli.go
https://github.com/hashicorp/vault/pull/7622
=> Backport:  Default to us-east-1 for CLI logins (#7622) 

builtin/logical/pki/path_tidy.go
Fixes #7588 which basically exposed that my change in #5931 was incomplete.
=> Don't continue in a few places in pki tidy if value is nil

website/source/docs/audit/file.html.md
- Add section + note about proper File Audit Device log rotation
=> Docs: File Audit Device

CONTRIBUTING.md
=> Updating contributing to mention CLA

website/source/docs/platform/aws-mp/index.html.md, website/source/docs/platform/aws-mp/run.html.md
Made a couple of small changes to AWS Marketplace title/menu headers
=> Update Title for AWS Marketplace

command/agent/sink/inmem/inmem_sink.go
Fixes a data race caught by CI on inmemSink's token value.
```
==================
Write at 0x00c00081f8a0 by goroutine 22:
github.com/hashicorp/vault/command/agent/sink/inmem.(*inmemSink).WriteToken()
/home/circleci/src/command/agent/sink/inmem/inmem_sink.go:32 +0x47
github.com/hashicorp/vault/command/agent/sink.(*SinkServer).Run.func1()
/home/circleci/src/command/agent/sink/sink.go:93 +0x18f
github.com/hashicorp/vault/command/agent/sink.(*SinkServer).Run()
/home/circleci/src/command/agent/sink/sink.go:146 +0x612
Previous read at 0x00c00081f8a0 by goroutine 69:
github.com/hashicorp/vault/command/agent/sink/inmem.(*inmemSink).Token()
/home/circleci/src/command/agent/sink/inmem/inmem_sink.go:42 +0x3e
github.com/hashicorp/vault/command/agent/cache.processTokenLookupResponse …
```
=> agent: fix data race on inmemSink's token

command/namespace_list.go
=> Backport 1.2.4: cli: fix json output for namespace list command

ui/package.json, ui/yarn.lock
Backport of https://github.com/hashicorp/vault/pull/7757
=> fix security alerts (#7757)

builtin/logical/rabbitmq/backend_test.go, builtin/logical/rabbitmq/path_role_create.go, builtin/logical/rabbitmq/path_roles.go, go.mod, go.sum, website/source/api/secret/rabbitmq/index.html.md, website/source/docs/secrets/rabbitmq/index.html.md
I extended the RabbitMQ backend with support for the new topic permissions introduced in RabbitMQ 3.7. I also extended the acceptance tests and the documentation.
Discussion started in Google Groups.
https://groups.google.com/forum/#!topic/vault-tool/7b9EZ52zzCU
=> Rabbitmq topic permissions

ui/app/helpers/has-permission.js, ui/app/services/permissions.js, ui/tests/unit/services/permissions-test.js
Backport of https://github.com/hashicorp/vault/pull/7590
=> Backport 1.3: Only link to nav items that user has access to (#7590)

api/client.go, api/sys_raft.go
* Dropped cancel func
* Bad struct tag
=> Fix some vet issues in api package:

api/client.go, api/sys_raft.go
* Dropped cancel func
* Bad struct tag
=> Backport 1.3: Fix some vet issues in api package (#7789)

vault/core_util.go, vault/request_forwarding.go, vault/request_forwarding_rpc.go
* Port OSS changes from perf standby fix
* Fix build
=> Backport 1.3.x: Port OSS changes from perf standby fix (#7818)

vault/core_util.go, vault/request_forwarding.go, vault/request_forwarding_rpc.go
* Port OSS changes from perf standby fix
* Fix build
=> Backport 1.2.x: Port OSS changes from perf standby fix (#7818)

go.mod, website/source/community.html.erb
This reverts commit 553bc729c9229fd0736e5fb9a01da7c89a1fa8b8.
=> Revert "updating community page (#7829)"

api/logical.go, go.mod
closes https://github.com/hashicorp/vault/issues/7610
=> adding a write bytes method to the logical api

website/source/docs/platform/k8s/helm.html.md, website/source/docs/platform/k8s/run.html.md
In anticipation for the upcoming Vault Helm 0.2.0 release, the documentation has been updated to include new features and expand on examples.
=> doc: update vault-helm for 0.2.0

website/source/api/secret/transit/index.html.md, website/source/docs/secrets/transit/index.html.md
Updated the Transit secrets engine docs.  ([Asana task](https://app.asana.com/0/112957393038545/1147321170259393/f))
=> [docs] Adding ciphertext description 

ui/tests/acceptance/enterprise-replication-test.js
backport of https://github.com/hashicorp/vault/pull/7776
=> backport 1.3: loosen match checking on replication show page (#7776)

command/agent.go, command/agent/template/template.go, command/agent/template/template_test.go, go.sum, vendor/github.com/hashicorp/consul-template/logging/logging.go, vendor/github.com/hashicorp/consul-template/logging/syslog.go, vendor/github.com/hashicorp/logutils/.gitignore, vendor/github.com/hashicorp/logutils/LICENSE, vendor/github.com/hashicorp/logutils/README.md, vendor/github.com/hashicorp/logutils/go.mod, vendor/github.com/hashicorp/logutils/level.go, vendor/modules.txt
Builds off of https://github.com/hashicorp/vault/pull/7739 and fixes https://github.com/hashicorp/vault/issues/7804. Do not merge until #7739 is merged.
=> Update how Vault Agent configures Consul Templates internal logger

website/source/docs/internals/telemetry.html.md
Improve the telemetry documentation so that it is formatted more nicely and is easier to read.
This document could be improved further by adding a "Key Metrics" section, like [Consul](https://www.consul.io/docs/agent/telemetry.html) has.
=> Improve telemetry docs

website/source/docs/platform/k8s/helm.html.md, website/source/docs/platform/k8s/run.html.md
Minor bug fix release of Vault Helm so updating the doc to reflect the new release.
=> Update vault-helm to 0.2.1

website/source/docs/concepts/tokens.html.md
=> Fix minor typo in website docs

website/source/docs/enterprise/entropy-augmentation/index.html.md, website/source/docs/secrets/ad/index.html.md
Added the **Learn** section at the bottom to introduce the related guide in Learn. 
- AD Check-in --> https://github.com/hashicorp/vault/pull/7898/files#diff-56d9d4903eeefc004ed3fcd12bb76d4aR337
- Entropy Augmentation --> https://github.com/hashicorp/vault/pull/7898/files#diff-69e199ec4271dd7b71f152c86bb8788dR56
=> Added a cross-referencing link to Learn

website/Gemfile.lock
...to work around netlify build image bug
=> Removed "bundled with" in lockfile

website/source/docs/secrets/kmip/index.html.md
- Streamline flow of introductory paragraph
- Grammar edits
- Streamline Client Certificate Generation section
- Remove trailing space
=> Docs: Secrets engines: KMIP

website/source/docs/what-is-vault/index.html.md
The url does not exist, the correct one is updated.
install.html -> index.html
=> Typo fix, getting started guide link

website/source/docs/configuration/telemetry.html.md
=> Docs: Add enable_hostname_label

website/source/docs/internals/telemetry.html.md
- Add wal_loadWAL metric
- Create section for Merkle Tree and WAL metrics
- Remove trailing spaces
=> Docs: Update Telemetry

physical/s3/s3.go, physical/s3/s3_test.go
Also remove some incorrect skipping of the S3 test.
Fixes #7362
=> Fix S3 configurable path handling

Makefile
=> Fix UI build in fresh repo

website/source/docs/plugin/index.html.md, website/source/docs/upgrading/plugins.html.md, website/source/layouts/docs.erb
props to @brianshumate for coming up with this!
=> docs: add section on upgrading plugins

website/source/api/secret/kmip/index.html.md, website/source/docs/secrets/kmip/index.html.md
=> Update KMIP docs re supported operations.

command/base.go
Fixes https://github.com/hashicorp/vault/issues/7923
=> Fix error handling during client TLS config setup

website/source/docs/partnerships/index.html.md
edited email address so they are visible, removed confusing EMAIL, email text.
=> typos to email visibility

builtin/logical/database/rotation.go, builtin/logical/database/rotation_test.go
=> Fix potential panic in database credential role rotation

ui/package.json, ui/yarn.lock
Backport for https://github.com/hashicorp/vault/commit/5e970a42204d8668f6eef25da7d0661be6d876b4
=> upgrade handlebars (#8112)

sdk/framework/backend.go, sdk/framework/backend_test.go, sdk/framework/path.go, vendor/github.com/hashicorp/vault/sdk/framework/backend.go, vendor/github.com/hashicorp/vault/sdk/framework/lease.go, vendor/github.com/hashicorp/vault/sdk/framework/path.go
=> Backport: framework redirect attributes

website/source/docs/commands/kv/get.html.md
Ordering matters here and its a constant question both from customers and new folks. This will help to show the right syntax.
=> Update docs to add example of field output for KV get

builtin/logical/database/path_rotate_credentials.go
Related PR https://github.com/hashicorp/vault/pull/8105
Fixes a bug that allows secondaries/performance standby's to rotate root DB credentials.
=> Fix DB root rotation replication issue

website/source/docs/enterprise/mfa/mfa-duo.html.md
Add example of using hardware tokens (e.g. TOTP)
=> Update Duo docs

builtin/logical/database/path_rotate_credentials.go
Backport of https://github.com/hashicorp/vault/pull/8105
=> Backport: Fix DB static role credential rotation replication issue

builtin/logical/database/path_rotate_credentials.go
Backport of https://github.com/hashicorp/vault/pull/8106
=> Backport: Fix DB root rotation replication issue

website/source/docs/internals/telemetry.html.md
Fixes https://github.com/hashicorp/vault/issues/7974
=> Docs: Add vaul.token.create_root metric

.circleci/config.yml, .circleci/config/@config.yml
Backport for https://github.com/hashicorp/vault/pull/8152, which fixes our UI tests in CI.
=> Backport pr 8152 1.3.x

builtin/credential/aws/path_login.go, builtin/credential/aws/path_login_test.go
=> Backport: Add aws metadata to identity alias

website/_redirects, website/pages/docs/index.mdx, website/pages/intro/getting-started/index.mdx
=> [website] fix a couple broken links

command/agent.go, command/debug.go, command/server.go, helper/gated-writer/writer.go, helper/gated-writer/writer_test.go
This is to smooth some other changes coming once
https://github.com/hashicorp/go-hclog/pull/56 lands
=> Update gated-writer logic a bit

website/data/version.js
=> Updating download page version

website/package-lock.json, website/package.json
Patches an issue with the docs sidenav introduced by changes yesterday.
=> [website] docs sidenav patch

website/pages/home/index.jsx
Updating to images with outlined type to avoid relying on system fonts
=> Website: Update diagram images

website/package.json
Updating to meganav@4.0.1-2 to deploy copy change - “HashiCorp Suite” -> “HashiCorp Stack”
=> Website: mega nav package version bump

website/pages/api-docs/secret/nomad/index.mdx
Related PR: https://github.com/hashicorp/vault/pull/8083
=> Docs: Add nomad TLS options

api/sys_raft.go, vendor/github.com/hashicorp/vault/api/sys_raft.go
Related PR: https://github.com/hashicorp/vault/pull/8211
=> Backport: Fix redoing redirect response raft snapshot cli

website/pages/api-docs/secret/pki/index.mdx
- Old link: https://www.vaultproject.io/api/secret/pki/index.html#create-update-role
- New link: https://www.vaultproject.io/api/secret/pki/index.html#createupdate-role
=> Website API docs for PKI: fix broken create/update link

website/pages/docs/platform/k8s/helm/configuration.mdx, website/pages/docs/platform/k8s/injector/examples.mdx, website/pages/docs/platform/k8s/injector/index.mdx
Minor doc updates for Vault k8s to 0.2.0
=> docs: update vault k8s to 0.2.0

website/package-lock.json, website/package.json
small dependency boost! nothing major here
=> [website] update dependencies

website/pages/api-docs/auth/azure/index.mdx
By reading the code looks like `subscription_id` and `resource_group_name` are required in the end https://github.com/hashicorp/vault-plugin-auth-azure/blob/master/path_login.go#L192-L194.
=> Update vault azure api docs

ui/app/styles/components/search-select.scss, ui/ember-cli-build.js, ui/package.json, ui/yarn.lock
**SUMMARY**
This PR is to standardize on the dart sass from lib sass, following the instructions [here](https://groups.google.com/a/hashicorp.com/forum/?hl=en#!topic/frontend-engineering/eLrmaonAjJo). There was one update required for the sass to compile, but I made sure the focused state on the dropdown still looks like hover state when :active
**CHANGES**
Should be a no-op
=> UI feature: dart sass

serviceregistration/consul/consul_service_registration.go
This PR fixes an issue where, if the `default` clause was picked up when a notification was received, the notification would not be retried.
=> Preserve Consul service registration notifications immediately

website/pages/api-docs/auth/jwt/index.mdx
Only API docs will be updated at this time as form_post mode is fairly niche and opt-in.
=> Update API docs for OIDC form_post mode

ui/app/components/auth-jwt.js
Backport to 1.3.x for PR [8385](https://github.com/hashicorp/vault/pull/8385).  Fixes OIDC modal bug.
=> Backport 1.3.x: Fix OIDC modal bug

website/package.json, website/pages/downloads/index.jsx, website/pages/downloads/style.css
@jescalan I based this off how we were previously doing alerts on betas in the Downloads page, but I can't get the message to show as an alert box. Not sure what needs to be done in order to make this work.
=> website: add alert box for 1.4.0-beta1

website/pages/docs/configuration/storage/mssql.mdx
This PR documents the addition of the port configuration parameter for the MSSQL storage backend.
=> Document changes from #6145 in MSSQL Documentation

website/data/api-navigation.js, website/data/docs-navigation.js, website/pages/api-docs/secret/openldap/index.mdx, website/pages/docs/secrets/openldap/index.mdx
This adds the user guide and API documentation for the OpenLDAP secret engine beta.
=> docs: add openldap secret engine

ui/app/templates/components/wizard/kmip-engine.hbs
Backport for https://github.com/hashicorp/vault/pull/8255
=> Backport 1.3.x: show kmip in wizard

ui/.eslintignore, ui/app/components/transit-key-actions.js, ui/app/templates/components/transit-key-action/decrypt.hbs, ui/app/templates/components/transit-key-action/encrypt.hbs, ui/app/templates/components/transit-key-action/hmac.hbs, ui/app/templates/components/transit-key-action/rewrap.hbs, ui/app/templates/components/transit-key-action/verify.hbs, ui/tests/acceptance/transit-test.js, ui/tests/integration/components/transit-key-actions-test.js
Backport for https://github.com/hashicorp/vault/pull/8462
=> Backport 1.4.x: Transit Key Actions Textareas

website/data/docs-navigation.js, website/pages/docs/platform/k8s/injector/annotations.mdx, website/pages/docs/platform/k8s/injector/index.mdx
This updates the Vault K8s docs with the new features added in 0.3.0.  Additionally I broke out the annotations to a separate webpage as the list is growing and needed better navigation for users.
=> docs: update vault k8s to 0.3.0

command/operator_migrate.go
=> Backport: Fix migrating away from raft storage (#8485)

website/package-lock.json
There is an odd html encoding bug on one of the docs pages that appears to be resolved by refreshing some of the deep-nested outdated dependencies.
=> [website] update dependency lockfile

website/pages/docs/secrets/databases/mssql.mdx
=> Document MSSQL revocation behaviour

ui/app/components/auth-config-form/options.js, ui/app/templates/components/auth-config-form/options.hbs
Backport for PR[ 8500](https://github.com/hashicorp/vault/pull/8500)
=> Backport: Show Error messages on Auth Configuration page (#8500) into 1.4.x

website/pages/api-docs/secret/gcp/index.mdx, website/pages/docs/secrets/gcp/index.mdx
This is a new operation for 1.4.
=> Add docs for GCP Secrets rotate root operation
