hashicorp/vault

- website/pages/docs/auth/jwt.mdx
Add mention of new-ish CLI parameters.
> Update JWT docs

- ui/app/models/auth-config/github.js
Backport for PR [8519](https://github.com/hashicorp/vault/pull/8519)
> Backport: 1.4.x remove duplicate form inputs for the github config

- ui/app/templates/partials/transit-form-show.hbs
- ui/app/templates/vault/cluster/secrets/backend/transit-actions-layout.hbs
Backport for PR [8258](https://github.com/hashicorp/vault/pull/8528)
> Backport into 1.4.x.  Bug fix capitalization of HMAC

- physical/spanner/spanner.go
This was incorrectly being reported as List
> Fix Spanner metrics

- website/README.md
updates netlify readme badge to use production credentials.
> website: update netlify badge in website/readme

- website/README.md
- website/package-lock.json
- website/package.json
- website/pages/docs/platform/k8s/helm/index.mdx
- website/pages/docs/platform/k8s/helm/run.mdx
- website/pages/docs/secrets/identity/index.mdx
- website/pages/use-cases/secrets-management/index.jsx
This current iteration adds a script that can be run locally. We are working on a version of this script that will run as a PR check through github as well!
> [website] Add broken link checker, fix some broken links

- website/pages/docs/partnerships/index.mdx
This PR is to fix the reported missing link in the doc
> Fixes reported missing link

- website/README.md
- website/pages/downloads/index.jsx
Better readme docs for releases and prereleases, better error message if someone bumps the version too early!
> Website release process clarification

- website/pages/docs/agent/autoauth/methods/kerberos.mdx
- website/pages/docs/auth/kerberos.mdx
Closes #8536 
Relates to https://github.com/hashicorp/vault-plugin-auth-kerberos/pull/43
This PR adds documentation for the field added above.
> Add docs for Kerb field

- ui/lib/core/addon/templates/components/replication-action-demote.hbs
Backport for PR [8555](https://github.com/hashicorp/vault/pull/8555)
> Backport 1.4.x: add in missing curly braces to demote danger message (#8555)

- website/package-lock.json
- website/package.json
- website/pages/downloads/index.jsx
Small update for the latest version of nextjs!
> Website Deps Upgrade

- ui/app/styles/components/list-item-row.scss
- ui/app/templates/partials/transit-form-show.hbs
* Update transit versions list styling and add ability to copy public key from dropdown menu for asymmetric key types
* Cursor is default if list item row has no destination
> Backport 1.4.x: Ui/transit key versions update (#8480)

- ui/app/models/auth-config/ldap.js
Backport for [PR 8573](https://github.com/hashicorp/vault/pull/8573)
> Backport: for PR 8573, fix certificates field on LDAP config

- terraform/aws/variables.tf
- website/data/version.js
- website/pages/downloads/index.jsx
Bump website version to 1.3.4
Bump prelease version to 1.4.0-rc1
> bump website version to 1.3.4

- ui/app/helpers/all-features.js
Backport for this [PR](https://github.com/hashicorp/vault/pull/8618)
> Backport to 1.4.x: add missing license features (#8618)

- README.md
I added a few links to the bullets at the top and expanded the "Getting Started" section to include links to the Learn guides and product certifications.
> Added links to Learn and certification exams to the README

- website/pages/docs/secrets/aws/index.mdx
Corrected code snippet to be copy paste ready (& properly terminating).
> Overtabed example corrected.

- website/pages/docs/secrets/index.mdx
The sentence did read clearly so I added a change to make it read a little cleaner
> fixed some grammar issue

- website/_redirects
- website/package-lock.json
🔍 [Preview link](https://deploy-preview-8657--vault-www.netlify.com/)
Netlify [is adjusting the way they handle redirects](https://community.netlify.com/t/changed-behavior-in-redirects/10084) to be more explicit. If a path has content (i.e. it's not `404`), then any redirects _without_ the `!` after the status code will be ignored and the content will be served. 
We always want these redirect rules to be honored, even in the unlikely event that we had content at the source path. 
This PR adds the status code with the force directive (`301!`) to all redirects. Future redirects should follow this pattern, unless they are a proxy `200` redirect, or we want to take advantage of Netlify's conditional redirect behavior.
> website: update netlify redirects

- sdk/logical/request.go
- vendor/github.com/hashicorp/vault/sdk/logical/request.go
This comment seems to be outdated and doesn't apply anymore.
> Fix outdated comment about logical request path

- website/lib/globalThis.js
- website/netlify.toml
- website/pages/404/index.js
- website/pages/404/style.css
- website/pages/_app.js
- website/pages/_error.jsx
- website/pages/style.css
Dupe of https://github.com/hashicorp/vault/pull/8530, rebased on top of the latest master
> Track 404 Pages with Analytics

- command/token_create.go
- website/pages/api-docs/auth/token/index.mdx
- website/pages/docs/concepts/tokens.mdx
This PR adds the doc update in #8725 to the stable-website branch so they can go out before the next release.
> stable-website: Minor clarifications on token docs (#8725)

- website/pages/docs/configuration/seal/azurekeyvault.mdx
Clarifies capabilities of auto-unsealing using Azure's Key Vault to indicate that no additional steps are required for Vault to recognize new keys in AKV.
> Clarify key rotation capabilities for Azure auto-unseal

- sdk/version/version_base.go
> Update the version prelease value

- website/pages/docs/agent/autoauth/sinks/file.mdx
Clarifying customer experience. Ie, don't try this on 1.2.1
> Clarify version that sink mode is in

- website/README.md
As we have worked through more docs website conversions, we have added some additional useful sections to the readmes - bringing these back to hopefully be helpful on vault as well!
- add section on redirects
- add section on markdown enhancements
- consistently wrap at col 81
- add fix for safe write issue
> Website readme update!

- website/data/version.js
- website/pages/downloads/index.jsx
As requested by the one and only @calvn
> Add changelog url to data file for website

- command/unwrap.go
- vault/logical_system.go
* Support unwrapping tokens that does not contain data
* s/token/secret
> Backport: Support unwrapping tokens that does not contain data (#8714)

- builtin/credential/ldap/backend.go
Backporting https://github.com/hashicorp/vault/pull/8740 to 1.4.1
> Backport PR #8740 to 1.4.1 (Improve error outputs in LDAP auth plugin)

- website/pages/community/index.jsx
🔗  [Preview Link](https://deploy-preview-8942--vault-www.netlify.app/community) 
Adds the following section...
> website: add link to certification on /community

- website/pages/docs/what-is-vault/index.mdx
> docs: remove comparison reference in what-is-vault page

- website/pages/docs/auth/azure.mdx
Add information about user-assigned identity support.
> Update Azure Auth docs

- website/pages/docs/enterprise/control-groups/index.mdx
- website/pages/docs/secrets/databases/mssql.mdx
- website/pages/docs/secrets/transform/index.mdx
I'm not sure about the first list item. There seems to be no mistake.
Fixes #8815
> Fix minor typos in docs

- website/data/docs-navigation.js
- website/pages/docs/upgrading/upgrade-to-1.3.5.mdx
- website/pages/docs/upgrading/upgrade-to-1.4.1.mdx
Adds important information about AWS Auth metadata changes.
> Add 1.4.1 upgrade guide

- go.mod
- go.sum
- vendor/github.com/hashicorp/vault-plugin-secrets-gcp/plugin/secrets_service_account_key.go
- vendor/modules.txt
Backport: https://github.com/hashicorp/vault-plugin-secrets-gcp/pull/85
> Backport: service account key should use config ttl

- builtin/credential/aws/path_login.go
> Backport 1.3.x: Fix AWS auth renewals (#8991)

- builtin/credential/aws/path_login.go
> Backport 1.4.x: Fix AWS auth renewals (#8991)

- go.mod
- go.sum
- internalshared/configutil/config.go
- internalshared/configutil/encrypt_decrypt.go
- internalshared/configutil/encrypt_decrypt_test.go
- internalshared/configutil/kms.go
See #8562 for more information about this. This simply ports shared parts over to a separate PR.
> Port encrypted config shared bits to a separate PR

- go.mod
- go.sum
- vendor/github.com/hashicorp/vault-plugin-secrets-ad/plugin/path_rotate_root_creds.go
- vendor/modules.txt
> Backport: Update vault-plugin-secret-ad dependency

- go.mod
- go.sum
This is only a go.mod cleanup. The previously vendored code
remains the same.
> Update AD plugin dependency

- website/pages/docs/secrets/transform/index.mdx
A calculator might have been nice. :)
> Document and give an example of the input size limits when using the FF3-1 transform.

- website/pages/guides/operations/rekeying-and-rotating.mdx
Same as earlier PR #8075 (But based on latest master)
(Comes from issue: https://github.com/hashicorp/vault/issues/6658)
> Add note about flag -target=recovery for auto-unseal mode

- builtin/logical/aws/backend.go
This PR adds an `invalidate()` method to the AWS secrets backend. The `invalidate()` method is used to clear cached IAM and STS clients after a credential update to `config/root`.
This fixes an issue where performance standby instances aren't able to serve requests to [generate credentials](https://www.vaultproject.io/api-docs/secret/aws#generate-credentials) via the `/aws/sts/:name` API. This can happen when an access key is rotated in AWS followed by a credential update to `config/root`.
I verified that this fixes the issue on performance standbys by allowing them to continue to generate credentials in this scenario.
> fix: invalidate cached clients after a config change in the aws secrets backend

- website/pages/api-docs/system/rekey.mdx
Fixes two very simple typos.
Mostly I want to ease myself into the collaboration workflow.
> Simple typos

- builtin/logical/aws/backend.go
This PR backports a bug fix from https://github.com/hashicorp/vault/pull/9186.
> Backport 1.4.3: invalidate cached clients after a config change in the aws secrets backend

- sdk/helper/awsutil/generate_credentials.go
> Backport: feat: replace the way AWS sessions are created and added a new WebIdentity

- ui/app/components/secret-edit.js
Backport this [PR](https://github.com/hashicorp/vault/pull/9242).
> Backport to 1.4.x:  Disallow kv2 with too large 'max versions' value (#9242)

- website/pages/api-docs/secret/transform/index.mdx
- website/pages/docs/secrets/transform/index.mdx
@yhyakuna tagging you in case you need these changes on the Learn side.
> docs: add additional info around transform for tweak and template type

- website/pages/docs/platform/k8s/helm/examples/enterprise-best-practice.mdx
- website/pages/docs/platform/k8s/helm/examples/enterprise-dr-with-raft.mdx
- website/pages/docs/platform/k8s/helm/examples/enterprise-perf-with-raft.mdx
- website/pages/docs/platform/k8s/helm/examples/enterprise-with-raft.mdx
The image references in the enterprise doc are currently out of date, so updating them to the latest!
> doc: update vault helm enterprise image examples

- go.mod
- go.sum
- vendor/github.com/hashicorp/vault-plugin-secrets-openldap/go.mod
- vendor/github.com/hashicorp/vault-plugin-secrets-openldap/go.sum
- vendor/github.com/hashicorp/vault-plugin-secrets-openldap/path_roles.go
- vendor/github.com/hashicorp/vault-plugin-secrets-openldap/path_rotate.go
- vendor/modules.txt
Updating go.mod for OpenLDAP secret engine bug fixes:
hashicorp/vault-plugin-secrets-openldap#13
hashicorp/vault-plugin-secrets-openldap#14
> plugins/openldap: update go mod

- go.mod
- go.sum
- vendor/github.com/hashicorp/vault-plugin-auth-kerberos/path_login.go
- vendor/modules.txt
Backport of #9307 
Bring in UPN fix.
> Backport: update kerberos auth plugin

- vault/core_metrics.go
While fixing merge conflicts I forgot to make sure these gauges are enabled.  :(
> Enable identity entity collection.

- physical/raft/raft.go
This issue came up during the HA Raft feature testing. Went through the scenario with Calvin and I added a comment as to how/why this could happen.
> physical/raft: Add nil check to Shutdown

- vault/core_metrics_test.go
- vault/identity_store_test.go
- vault/token_store_test.go
> Unit test that fails to demonstrate identity store problem.

- vault/logical_system.go
This PR partially addresses monitor blocking state read lock release by looking at the seal state. Other blocking scenarios that hold the state lock regardless of seal status will be addressed in the separate PR, likely  https://github.com/hashicorp/vault/pull/9312
> monitor: watch for seal state during monitor request

- website/pages/api-docs/system/replication/index.mdx
- website/pages/api-docs/system/replication/replication-dr.mdx
- website/pages/api-docs/system/replication/replication-performance.mdx
These are the doc changes for https://github.com/hashicorp/vault-enterprise/pull/1259
> Update replication status API docs with new fields

- CHANGELOG.md
- api/sys_plugins.go
- command/commands.go
- command/plugin_reload.go
- command/plugin_reload_status.go
- command/plugin_reload_test.go
- go.mod
- go.sum
- vault/logical_system.go
- vault/logical_system_helpers.go
- vault/logical_system_paths.go
- vendor/github.com/hashicorp/vault-plugin-database-mongodbatlas/go.sum
- vendor/github.com/hashicorp/vault/api/sys_plugins.go
- vendor/modules.txt
Carefully move changes from the plugin-cluster-reload branch into this clean branch off master.
> Global Plugin Reload: OSS Changes Take II

- vault/expiration.go
Changed log messages to be clearer about quota operations.
This should fix enterprise unit test failures.
> Don't return quota error on revoke.

- vault/expiration.go
Changed log messages to be clearer about quota operations.
This should fix enterprise unit test failures.
> Backport 1.5.x: fix handling of quota errors (should fix unit test errors on enterprise)

- vault/auth.go
- vault/core.go
- vault/mount.go
* Add nil check for quota manager
* Add missing nil checks
> Backport 1.5.0: Add nil check for quota manager (#9379)

- helper/testhelpers/testhelpers.go
- vault/core.go
- vault/external_tests/sealmigration/seal_migration_pre14_test.go
- vault/external_tests/sealmigration/seal_migration_test.go
- vault/testing.go
* Fix issue migrating from Auto->Shamir and improve tests
* Undo newline
* fix panic in test
* Fix test panic
> Backport 1.5.x: seal: Fix issue migrating from Auto->Shamir and improve tests (#9430)

- vault/testing.go
- vault/testing_util.go
port https://github.com/hashicorp/vault-enterprise/pull/1315 from enterprise.
> tests: Port #1315 from enterprise

- vault/testing.go
- vault/testing_util.go
Backport https://github.com/hashicorp/vault/pull/9437 into 1.5.x
> Backport 1.5.x: tests: Port #1315 from enterprise

- website/pages/docs/concepts/password-policies.mdx
Adds links from the password policy docs to the password policy API docs.
> Add links to API docs for password policies

- ui/app/services/auth.js
> Backport: Add truthy check for data.policies before calling 'includes' (#9467)

- sdk/helper/awsutil/generate_credentials.go
> Backport #9416 to 1.5

- ui/app/styles/core.scss
- ui/app/styles/core/alert-banner.scss
- ui/lib/core/addon/templates/components/alert-banner.hbs
This is a backport for this [PR](https://github.com/hashicorp/vault/pull/9463)
> Backport 1.5.x: Update Alert banner message-body to match design system (#9463)

- sdk/logical/request.go
- vendor/github.com/hashicorp/vault/sdk/helper/awsutil/generate_credentials.go
- vendor/github.com/hashicorp/vault/sdk/logical/request.go
To be used when there's a need to modify the current request before saving it
> Adding a Clone() function to the request handler 

- ui/app/models/pki-certificate.js
[A PR](https://github.com/hashicorp/vault/pull/9405) was merged to address a bug fix.  However, it created another bug, and to solve for this we are looking at changing the workflow to make this process clearer.
> Bug Fix: revert initialValue for PKI CA cert

- ui/app/models/pki-certificate.js
This is a backport for this [PR](https://github.com/hashicorp/vault/pull/9493)
> Backport: 1.5.x: remove default value based on workflow discussions (#9493)

- vault/core.go
Add a lock to seal migration so we'll know if its already in progress
> Add a lock to seal migration

- go.mod
- go.sum
- vendor/github.com/hashicorp/vault-plugin-auth-gcp/plugin/aliasing.go
- vendor/github.com/hashicorp/vault-plugin-auth-gcp/plugin/gcp_config.go
- vendor/modules.txt
This PR backports https://github.com/hashicorp/vault/pull/9507 by cherry-picking https://github.com/hashicorp/vault/commit/773c6d108ab215374496a96238237963b439479d.
> Backport 1.5.0: Updates the GCP auth plugin

- CHANGELOG.md
> Add CL entry for mount_type addition (#9489)

- vault/external_tests/sealmigration/seal_migration_test.go
This is a slightly speculative fix for errors like this one: https://app.circleci.com/pipelines/github/hashicorp/vault/10751/workflows/1aa9ba61-b677-483b-8f1e-c1976e1ca6ae/jobs/71593
```
seal_migration_test.go:758: Get "https://127.0.0.1:22402/v1/kv-wrapped/foo": redirects not allowed in these tests
```
> Make runTransit tolerate a non-core-0 leader.

- website/pages/api-docs/system/raw.mdx
curl command incorrect: `---header` should be `--header`
> curl command incorrect: ---header should be --header

- website/pages/docs/secrets/openldap/index.mdx
> Update OpenLDAP docs

- command/server.go
> Use printf field widths instead of strings.Repeat.

- go.mod
- go.sum
- vendor/github.com/sethvargo/go-limiter/internal/fasttime/fasttime.go
- vendor/github.com/sethvargo/go-limiter/internal/fasttime/fasttime_windows.go
- vendor/github.com/sethvargo/go-limiter/memorystore/store.go
- vendor/modules.txt
This should fix the windows build.
> update go-limiter to v0.3.0

- ui/app/serializers/transit-key.js
- ui/app/templates/partials/transit-form-show.hbs
Backport for this [PR](https://github.com/hashicorp/vault/pull/9520)
> Backport 1.4.x: UI/transit add missed algorithms follow up (#9520)

- website/pages/docs/upgrading/upgrade-to-1.3.0.mdx
> Added upgrade guidance on mount -> path filters

- go.mod
- go.sum
- vendor/github.com/hashicorp/consul-template/config/env.go
- vendor/github.com/hashicorp/consul-template/config/template.go
- vendor/github.com/hashicorp/consul-template/dependency/vault_common.go
- vendor/github.com/hashicorp/consul-template/dependency/vault_read.go
- vendor/github.com/hashicorp/consul-template/dependency/vault_token.go
- vendor/github.com/hashicorp/consul-template/manager/runner.go
- vendor/github.com/hashicorp/consul-template/renderer/renderer.go
- vendor/github.com/hashicorp/consul-template/template/funcs.go
- vendor/github.com/hashicorp/consul-template/template/template.go
- vendor/github.com/hashicorp/consul-template/version/version.go
- vendor/modules.txt
[Consul Template v0.25.1](https://github.com/hashicorp/consul-template/blob/master/CHANGELOG.md#v0251-jul-27-2020) has bug fixes for templating Vault secrets (specifically kvv2 and PKI certificates).  Updating the dependency to pull in these fixes.
> agent/templates: update consul-template to v0.25.1

- physical/raft/fsm.go
- physical/raft/fsm_test.go
- physical/raft/raft.go
- physical/raft/snapshot_test.go
* set path properly in NewRaftBackend()
* get rid of storeLatestState
> Backport 1.5.x: set path properly in NewRaftBackend() (#9128)

- website/pages/docs/secrets/databases/mysql-maria.mdx
Talks more about the options described in #9671
> Add a section to the MySQL secrets plugin docs about x509

- website/pages/docs/auth/jwt_oidc_providers.mdx
This PR publishes documentation for an OIDC provider specific extension for G Suite that'll be in the Vault 1.5.1 release.
Original docs PR: https://github.com/hashicorp/vault/pull/9454
> Publish documentation for OIDC provider specific extension for G Suite (#9454)

- builtin/credential/aws/backend.go
- builtin/credential/aws/path_config_client.go
- builtin/credential/aws/path_login.go
- builtin/credential/aws/path_login_test.go
- website/source/api/auth/aws/index.html.md.erb
Backport PSIRT-37 AWS fixes to 1.3.x
> Backport 9825 1.3.x

- builtin/credential/aws/backend.go
- builtin/credential/aws/path_config_client.go
- builtin/credential/aws/path_login_test.go
- website/pages/api-docs/auth/aws/index.mdx
Backport PSIRT-37 AWS fixes to 1.4.x
> Backport 9825 1.4.x

- CHANGELOG.md
Wanted to make a PR to check for comments
> Changelog updates for 1.5.3 etc

- website/pages/partials/aws-invalid-header.mdx
Provide information about AWS IAM fix versions.
> Update Known Issues

- website/pages/api-docs/auth/jwt/index.mdx
> Update docs to add EdDSA to supported algorithms

- website/pages/docs/upgrading/upgrade-to-1.5.0.mdx
This is a companion to https://github.com/hashicorp/vault/pull/9881
> Add upgrade note about the KV metric crash.

- command/agent/auth/kerberos/kerberos.go
- command/agent/auth/kerberos/kerberos_test.go
* agent/auth/kerberos: add disable_fast_negotiation
* simplify test
* Update command/agent/auth/kerberos/kerberos_test.go
Co-authored-by: Calvin Leung Huang <cleung2010@gmail.com>
* simplify tests
Co-authored-by: Calvin Leung Huang <cleung2010@gmail.com>
> agent/auth/kerberos: add disable_fast_negotiation (#9892)

- website/components/columns/style.module.css
This should make the styles on the plugins portal page a little nicer on mobile!
> Improve mobile styling for columns component

- website/pages/docs/secrets/aws/index.mdx
Clarification for us that didn't know.
> Docs: Add note that vault deletes IAM user

- website/pages/docs/configuration/index.mdx
Adds the documentation for #9931 to the website.
> doc: add VAULT_DISABLE_MLOCK env

- go.mod
- go.sum
- vendor/github.com/google/go-cmp/cmp/compare.go
- vendor/github.com/google/go-cmp/cmp/export_panic.go
- vendor/github.com/google/go-cmp/cmp/export_unsafe.go
- vendor/github.com/google/go-cmp/cmp/internal/diff/diff.go
- vendor/github.com/google/go-cmp/cmp/internal/value/name.go
- vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go
- vendor/github.com/google/go-cmp/cmp/internal/value/pointer_unsafe.go
- vendor/github.com/google/go-cmp/cmp/path.go
- vendor/github.com/google/go-cmp/cmp/report.go
- vendor/github.com/google/go-cmp/cmp/report_compare.go
- vendor/github.com/google/go-cmp/cmp/report_references.go
- vendor/github.com/google/go-cmp/cmp/report_reflect.go
- vendor/github.com/google/go-cmp/cmp/report_slices.go
- vendor/github.com/google/go-cmp/cmp/report_text.go
- vendor/github.com/hashicorp/raft/raft.go
- vendor/modules.txt
Bump Raft commit to b7cd2b346b06 which includes the fix for updating peer IDs.
> Bump Raft Commit

- ui/lib/core/addon/templates/components/info-table-item-array.hbs
Fixes test selector for new transform tests
> Wrap info-table-item-array in data-test selector for testing

- go.mod
- go.sum
- vendor/github.com/hashicorp/vault-plugin-secrets-gcp/plugin/rollback.go
- vendor/modules.txt
Just backporting a version update of vault-plugin-secrets-gcp here.
> Update vault-plugin-secrets-gcp to v0.6.5

- sdk/framework/filter.go
This can be wrapped around any existing list operationFunc along with declaring what the filter field name is in the Schema.
> Add a helper function which adds glob filtration to any LIST endpoint

- ui/app/models/identity/entity.js
See #9958 for description of change
> Backport 1.5.4: replace identityType with 'entity' on model (#9958)

- website/pages/docs/configuration/storage/raft.mdx
I changed some verbiage in the page as well.
> docs: Change sidebar labeling to use Integrated Storage

- builtin/logical/pki/crl_util.go
Backport of https://github.com/hashicorp/vault/pull/9880
> Backport: Allow expiration of a cert not in storage to succeed

- website/data/version.js
See the release procedure doc, publishing, step 8.
> Updating version for website to 1.5.4

- go.mod
- go.sum
- vendor/github.com/hashicorp/raft/CHANGELOG.md
- vendor/github.com/hashicorp/raft/raft.go
- vendor/github.com/hashicorp/raft/replication.go
- vendor/modules.txt
- website/pages/docs/internals/telemetry.mdx
Related PR: https://github.com/hashicorp/vault/pull/10055
> Backport: Pull latest raft updates

- api/go.mod
- api/go.sum
- sdk/go.mod
- vendor/github.com/hashicorp/vault/api/go.sum
- vendor/modules.txt
Introduced attempting to resolve a circular dependency problem that wasn't.
> Revert unnecessary changes to api/go.mod

- api/README.md
Closes https://github.com/hashicorp/vault/issues/10041
> Add README.md to api

- website/data/api-navigation.js
- website/pages/api-docs/system/monitor.mdx
Closes https://github.com/hashicorp/vault/issues/9953
> Add API docs for sys/monitor

- website/pages/docs/secrets/aws/index.mdx
> lease_renewable false on STS AWS credentials docs

- go.mod
- go.sum
- vendor/modules.txt
Checksum got screwed up, so this should fix it.
> Fix checksum for vault-plugin-secrets-ad

- plugins/database/influxdb/connection_producer.go
- plugins/database/influxdb/influxdb.go
- plugins/database/influxdb/influxdb_test.go
Updates the InfluxDB Database plugin to adhere to the v5 Database interface.
> DBPW - Update InfluxDB to adhere to v5 Database interface

- website/pages/docs/upgrading/upgrade-to-1.5.0.mdx
> Add GCS storage change to 1.5.0 upgrade guide

- sdk/helper/awsutil/generate_credentials.go
- vendor/github.com/hashicorp/vault/sdk/helper/awsutil/generate_credentials.go
Backporting https://github.com/hashicorp/vault/pull/10133
> backport 1.6: Set default IMDS timeouts to match AWS SDK (#10133)

- sdk/helper/awsutil/generate_credentials.go
- vendor/github.com/hashicorp/vault/sdk/helper/awsutil/generate_credentials.go
Backporting https://github.com/hashicorp/vault/pull/10133
> backport 1.5: Set default IMDS timeouts to match AWS SDK (#10133)

- ui/app/adapters/generated-item-list.js
- ui/app/services/path-help.js
- ui/app/templates/components/generated-item-list.hbs
- ui/app/templates/vault/cluster/access/methods.hbs
- ui/tests/acceptance/auth-list-test.js
[Backport for PR 10122](https://github.com/hashicorp/vault/pull/10122)
> Backport 1.6.x: Auth list fix by returning dynamicApiPath from the model (#10122)

- ui/app/adapters/generated-item-list.js
- ui/app/services/path-help.js
- ui/app/templates/components/generated-item-list.hbs
- ui/app/templates/vault/cluster/access/methods.hbs
- ui/tests/acceptance/auth-list-test.js
[Backport PR for 10122](https://github.com/hashicorp/vault/pull/10122)
> Backport 1.5.x: Auth list fix by returning dynamicApiPath from the model (#10122)

- ui/lib/core/addon/templates/components/shamir-modal-flow.hbs
[Backport PR](https://github.com/hashicorp/vault/pull/10155)
> Backport 1.6.x: update dr promote modal text to clarify action (#10155)

- command/operator_raft_remove_peer.go
- vault/logical_system.go
- vault/logical_system_helpers.go
- vault/logical_system_raft.go
- website/pages/api-docs/system/storage/raft.mdx
Backport https://github.com/hashicorp/vault/pull/10059 to 1.5.x
> Backport 1.5.x: #10059

- website/pages/docs/configuration/telemetry.mdx
zero prometheus_retention_time will disable.
> Clarify prometheus_retention_time to 0

- sdk/version/version_base.go
This PR in preparation for the SDK update. There will be another to follow after this one is merged.
> Updating Vault version in the SDK

- ui/app/adapters/metrics/activity.js
- ui/app/components/pricing-metrics-dates.js
- ui/app/serializers/metrics/config.js
- ui/app/templates/components/pricing-metrics-dates.hbs
- ui/app/templates/vault/cluster/metrics/index.hbs
> Backport 1.6.0: Pricing Metrics UI updates for API

- builtin/credential/aws/path_login.go
* Improve errors for aws login with an unbound ARN
* Factor hasWildcardBind into its own function
Co-authored-by: Calvin Leung Huang <cleung2010@gmail.com>
> Backport 1.6.0: Improve errors for aws login with an unbound ARN (#10036)

- go.mod
- go.sum
- vendor/github.com/hashicorp/vault-plugin-auth-jwt/path_config.go
- vendor/modules.txt
Pulls in a fix for the OIDC config UI: https://github.com/hashicorp/vault-plugin-auth-jwt/pull/141
> Update auth/jwt to latest release/vault-1.5.x

- website/pages/docs/secrets/venafi/index.mdx
- Introduced _Venafi Secret_ to add support for token authentication with Trust Protection Platform
- Added support for requesting specific validity periods using the Vault native `ttl` and `max_ttl` parameters
- Added support for Trust Protection Platform Custom Fields
> Update Venafi Secrets Engine doc to account for recent enhancements

- physical/oci/oci.go
Follow up of https://github.com/hashicorp/vault/pull/9302
> OCI: Don't store region in the backend struct

- ui/lib/replication/addon/templates/components/known-secondaries-card.hbs
> Backport 1.6.0: Update replication secondaries language

- vault/mount.go
Co-authored-by: Jim Kalafut <jkalafut@hashicorp.com>
Co-authored-by: Vishal Nayak <vishalnayak@users.noreply.github.com>
> Backport: Add omitempty's to MountEntry and MountConfig (#7154)

- ui/app/templates/components/pricing-metrics-dates.hbs
> Add Learn More Here link to vault learn pricing metrics tutorial

- vault/mount.go
- vault/mount_test.go
> Fix remount race

- go.mod
- go.sum
- vendor/github.com/hashicorp/vault-plugin-auth-jwt/cli.go
- vendor/github.com/hashicorp/vault-plugin-auth-jwt/path_config.go
- vendor/github.com/hashicorp/vault-plugin-auth-jwt/path_oidc.go
- vendor/modules.txt
Pulls in https://github.com/hashicorp/vault-plugin-auth-jwt/pull/137 and https://github.com/hashicorp/vault-plugin-auth-jwt/pull/140
> Updating to jwt plugin@master

- go.mod
- go.sum
- vendor/modules.txt
Steps taken:
1. `git cherry-pick 65a6c4e`
2. `go mod vendor`
3. `go mod tidy`
> Backport 1.6.0: mod: update database-couchbase to v0.2.1 (#10286)

- vault/expiration.go
- website/pages/docs/internals/telemetry.mdx
Backport of: https://github.com/hashicorp/vault/pull/10268/files
> Backport expiration hotfix

- vault/activity_log.go
* Reintroduce a feature flag to disable the activity log entirely.
* Add log message when disabled.
Backport of vault-enterprise/#1575
> Reintroduce a feature flag to disable the activity log entirely. 

- vault/counters.go
- vault/logical_system.go
Backport of fix from enterprise side, affecting performance replication.
> Move "counters" path to the logical system's local path list.

- ui/app/routes/vault/cluster/metrics/index.js
> Backport 1.6.0: Update query params sent to activity endpoint

- ui/app/templates/components/transform-list-item.hbs
> Backport 1.6.0: Fix link on transform item

- CHANGELOG.md
- website/data/version.js
I wasn't entirely sure what the changelog should look like for the release candidate.
> Proposed changelog for the 1.6.0 RC

- vault/external_tests/quotas/quotas_test.go
- vault/logical_system_quotas.go
- vault/quotas/quotas.go
Changes to fix an ENT unit test, backported to OSS.
> Backport last quota fix changes to OSS

- vault/external_tests/quotas/quotas_test.go
- vault/logical_system_quotas.go
- vault/quotas/quotas.go
Backport quota conflict fixes to 1.6.x OSS
> Backport 10285 10335 1.6.x

- builtin/logical/database/path_rotate_credentials.go
* Error on root rotation when username is empty
* Don't panic if the field doesn't exist
> Backport 1.6: Error on root rotation when username is empty (#10344)

- ui/app/templates/components/pricing-metrics-dates.hbs
- ui/app/templates/vault/cluster/metrics/index.hbs
- ui/mirage/config.js
- ui/mirage/factories/metrics/activity.js
- ui/mirage/factories/metrics/config.js
- ui/mirage/factories/user.js
- ui/mirage/scenarios/default.js
- ui/mirage/serializers/application.js
- ui/package.json
- ui/tests/acceptance/usage-metrics-test.js
- ui/tests/pages/metrics.js
- ui/yarn.lock
> Backport 1.6.0: Ui/test metrics mirage (#10341)

- website/pages/docs/secrets/transform/index.mdx
Fix some typos and a small omission from the tokenization docs.
> Transform doc fix

- website/pages/docs/upgrading/upgrade-to-1.6.0.mdx
> Added upgrade note about go version

- vault/activity_log_test.go
e.g., https://app.circleci.com/pipelines/github/hashicorp/vault/13651/workflows/f256e841-3c5b-4bef-923f-d71a4dfd9c15/jobs/112342
> Disable test that fails on OSS.

- website/pages/docs/commands/debug.mdx
Based on the [inclusive language style guide](https://github.com/hashicorp/engineering-docs/blob/master/writing/style-guide.md#inclusive-language), remove the usage of "sane".
[Netlify deploy preview](https://deploy-preview-10400--vault-www.netlify.app/docs/commands/debug#examples)
> Update 'sane' default to say 'reasonable' default

- website/pages/docs/secrets/consul/index.mdx
- website/pages/docs/secrets/nomad/index.mdx
- website/pages/docs/secrets/transform/tokenization.mdx
Adding cross-referencing links to matching Learn tutorials.
> Add Learn links

- website/pages/docs/auth/azure.mdx
i missed this last week - preview showed fine in VS code but need to remove the space
> remove space which caused formatting weirdness

- website/pages/docs/secrets/nomad/index.mdx
> Change API token to ACL token

- .circleci/config.yml
- .circleci/config/jobs/test-ui.yml
- ui/yarn.lock
Ran `yarn install` locally and pushed the changes to yarn.lock to this branch so that the cache is properly persisted between jobs.
Upped the resource_class to xlarge (from medium+) as this seemed to be needed for the tests to run. 
Angel is checking whether this is definitely needed.
> updates to get tests running

- changelog/10375.txt
From: https://github.com/hashicorp/vault/pull/10379
> Using changelog tool to update changelog [VAULT-1055]

- changelog/10386.txt
related PR: https://github.com/hashicorp/vault/pull/10386/files
> Changelog update [VAULT-849]

- builtin/logical/transit/path_encrypt.go
- builtin/logical/transit/path_encrypt_test.go
- changelog/10386.txt
PR: https://github.com/hashicorp/vault/pull/10386/files
> backport for vault-849 changes [VAULT-849]

- vault/external_tests/quotas/quotas_test.go
- vault/logical_system_quotas.go
Backport of https://github.com/hashicorp/vault/pull/10285
> Backport: 10285 to 1.5.x

- builtin/logical/database/backend_test.go
- builtin/logical/database/path_config_connection.go
- changelog/10416.txt
- changelog/README.md
> Backport 1.6.1: sanitize private key

- helper/timeutil/timeutil.go
- vault/activity_log.go
- vault/activity_log_test.go
- vault/activity_log_testing_util.go
- vault/core.go
Also moved some testing utilities away from the main activity log logic
> Fix Racy Activity Log Tests

- changelog/10477.txt
Adds changelog for previous PR that I missed adding
> Add changelog for #10477

- physical/consul/consul.go
- website/pages/docs/internals/telemetry.mdx
* Update consul.go
* Update telemetry.mdx
> Backport 1.6.1: Telemetry consul transaction (#10486)

- changelog/10417.txt
- ui/lib/core/addon/components/search-select.js
- ui/tests/integration/components/search-select-test.js
> Backport 1.6.1: Fix delete role issue on Transform

- go.mod
- go.sum
- vendor/github.com/hashicorp/vault-plugin-auth-jwt/path_config.go
- vendor/github.com/hashicorp/vault-plugin-auth-jwt/path_login.go
- vendor/github.com/hashicorp/vault-plugin-auth-jwt/path_oidc.go
- vendor/github.com/hashicorp/vault-plugin-auth-jwt/provider_azure.go
- vendor/github.com/hashicorp/vault-plugin-auth-jwt/provider_config.go
- vendor/github.com/hashicorp/vault-plugin-auth-jwt/provider_gsuite.go
- vendor/github.com/hashicorp/vault/api/client.go
- vendor/modules.txt
Updates vault-plugin-auth-jwt to v0.8.1
Steps taken:
- `get github.com/hashicorp/vault-plugin-auth-jwt@release/vault-1.6.x`
- `go mod vendor && go mod tidy`
> mod: update auth-jwt to v0.8.1

- changelog/10558.txt
Add entry for secrets/gcp update on #10558
> changelog: add entry for 10558

- changelog/10558.txt
Backporting changelog addition for #10558 into release/1.6.x.
> changelog: add entry for 10558 (#10563)

- website/pages/docs/plugin-portal/index.mdx
List PrimeKey Solutions AB's secrets plugin in Plugin Portal
> Add PrimeKey EJBCA as partner secrets plugin

- website/data/version.js
Will merge this after the release is done.
Feel free to add any upgrade notes or other guidance to this PR.
> Updating version to 1.6.1

- vault/token_store_test.go
See commit messages for back story.
> Fix test for expiring root tokens creating non-expiring root tokens

- website/content/docs/platform/k8s/helm/configuration.mdx
- website/content/docs/platform/k8s/helm/index.mdx
- website/content/docs/platform/k8s/helm/openshift.mdx
- website/content/docs/platform/k8s/helm/run.mdx
Vault Helm 0.9.0 was just released so I added the new configurables and updated relevant documentation.
> docs: update Vault Helm to 0.9.0

- website/content/api-docs/secret/databases/snowflake.mdx
- website/content/docs/secrets/databases/index.mdx
- website/content/docs/secrets/databases/snowflake.mdx
- website/data/api-navigation.js
- website/data/docs-navigation.js
This PR looks to add Snowflake docs to the website.
> Add Snowflake docs to the website

- changelog/10613.txt
- http/handler.go
- http/sys_feature_flags.go
- vault/external_tests/api/feature_flag_ext_test.go
- vault/logical_system.go
- vault/logical_system_paths.go
- website/content/api-docs/system/internal-ui-feature.mdx
- website/data/api-navigation.js
* Added sys/internal/ui/feature-flags endpoint.
* Added documentation for new API endpoint.
* Added integration test.
Co-authored-by: swayne275 <swayne@hashicorp.com>
> Backport 1.6.x: Feature flags API

- website/data/alert-banner.js
- website/package-lock.json
- website/package.json
- website/pages/_app.js
- website/pages/style.css
Adds our shared `AlertBanner` react component and enables it to promote an[ upcoming webinar](https://www.hashicorp.com/events/webinars/cloud-service-networking-secrets-management). 
Note the `expirationDate` prop - the banner will auto-hide after that date.
> website: add alert banner to promote webinar

- changelog/10684.txt
- ui/app/routes/application.js
- ui/tests/acceptance/managed-namespace-test.js
> Backport 1.6.2: Fix shape of response anticipated from feature-flags endpoint

- website/content/docs/secrets/databases/snowflake.mdx
Snowflake docs had an issue, `DEFAULT ROLE` should be `DEFAULT_ROLE`
> Update Snowflake docs

- website/data/alert-banner.js
Change alert banner to promote HCP Vault public beta.
> website: update alert banner for HCP Vault public beta

- website/vercel.json
This will quiet the vercel bot commenting about new deployments on PRs 😀
> Add vercel config for website

- vault/activity_log.go
- vault/activity_log_test.go
- vault/activity_log_testing_util.go
- vault/logical_system_activity.go
Backport https://github.com/hashicorp/vault/pull/10485 to 1.6.x
> [backport] 1.6.x: core: add warning when disabling activity 

- command/operator_raft_listpeers.go
- vault/logical_system.go
- vault/logical_system_raft.go
OSS changes for enabling listing of peers on DR secondary clusters.
> Add list peers to DR secondaries

- go.mod
- go.sum
- vendor/github.com/hashicorp/vault-plugin-secrets-gcp/plugin/rollback.go
- vendor/modules.txt
This is bumping the GCP secrets plugin to 0.8.2
> Updating GCP secrets plugin

- website/content/docs/agent/template.mdx
Alternatively this could be changed to "1/3 remaining", but I think this is clearer?
> Clarify agent lease renewal docs

- changelog/10705.txt
Forgot to include a CL entry to #10705, so adding one post-merge.
> changelog: add entry for PR 10705

- website/pages/api-docs/[[...page]].jsx
- website/pages/docs/[[...page]].jsx
- website/pages/guides/[[...page]].jsx
- website/pages/intro/[[...page]].jsx
A change in dependencies accidentally broke this link, this PR should fix it!
> fix "edit page" links on website

- ui/vercel.json
This should remove the extra vercel comments in github, which I know is annoying
> Add vercel config for UI

- CHANGELOG.md
- changelog/10759.txt
* CHANGELOG update: GCP secrets WAL issue fix
> Backport CHANGELOG update for gcp/secrets WAL fix

- changelog/_ 1686.txt
- website/content/api-docs/secret/kmip.mdx
This PR goes hand in hand with: https://github.com/hashicorp/vault-enterprise/pull/1686
> changelog for entropy augmentation PR [VAULT-1179]

- changelog/10072.txt
- website/content/docs/configuration/listener/tcp.mdx
This is the docs upgrade and changelog for https://github.com/hashicorp/vault/pull/10072
> Docs and changelog for max_request_size upgrade [VAULT-990]

- changelog/_1680.txt
> changelog++ (#10748)

- changelog/_2021Jan26.txt
* More CL notes for 1.6.2
* Update _2021Jan26.txt
* Update _2021Jan26.txt
> More CL notes for 1.6.2 (#10792)

- website/pages/style.css
Adds back some table styles that seem to have gone missing.
> website: add table styles to style.css

- changelog/_1705.txt
This is for https://github.com/hashicorp/vault-enterprise/pull/1705
> Add changelog entry for ent PR 1705

- website/content/api-docs/secret/openldap.mdx
- website/content/docs/secrets/openldap.mdx
Adds documentation for OpenLDAP dynamic secrets (https://github.com/hashicorp/vault-plugin-secrets-openldap/pull/21)
> Add docs for OpenLDAP dynamic secrets

- changelog/10689.txt
- vault/logical_system_quotas.go
- vault/quotas/quotas_rate_limit.go
- vault/quotas/quotas_test.go
* Fix db indexing issue
* Add CL update
> Backport: Fix quota enforcing old path issue (#10689)

- ui/tests/acceptance/enterprise-kmip-test.js
**Enterprise only**
The KMIP UI tests were failing due to a change in 1.6.2 that causes an error when KMIP secrets engine is mounted on a port that is already in use. This change updates the test so that each new tests mounts KMIP on a new port.
> Fix KMIP UI tests failing after 1.6.2

- ui/tests/acceptance/enterprise-kmip-test.js
> Backport 1.6.3: Fix KMIP tests failing after 1.6.2 (#10891)

- website/content/docs/internals/limits.mdx
> Docs - Namespace monitoring corrected examples

- website/content/docs/secrets/identity.mdx
Corrected the text about token auth method.
> Added a table showing the entity alias name used by each auth method.

- helper/fairshare/fairshare_testing_util.go
- helper/fairshare/jobmanager.go
- helper/fairshare/jobmanager_test.go
- helper/fairshare/workerpool.go
- helper/fairshare/workerpool_test.go
This PR ports over the workerpool and job manager fairsharing layers
> VAULT-1401 and 1402 - preliminary fair sharing (#1701)

- website/content/docs/auth/jwt_oidc_providers.mdx
Resolves #8191 with clearer external groups configuration.
> docs: Update Azure AD OIDC documentation

- changelog/10951.txt
- ui/app/templates/vault/cluster/metrics/index.hbs
> Backport 1.6.3: UI add usage metrics description (#10951)

- go.mod
- go.sum
- vendor/github.com/hashicorp/consul-template/dependency/vault_common.go
- vendor/github.com/hashicorp/consul-template/logging/logging.go
- vendor/github.com/hashicorp/consul-template/version/version.go
- vendor/modules.txt
This was created via running:
go get github.com/hashicorp/consul-template@v0.25.2
and go mod vendor. 
The ask is part of the thread in https://hashicorp.atlassian.net/browse/VAULT-871
> Depend on the most recent consul-template version [VAULT-871]

- changelog/10644.txt
For: https://github.com/hashicorp/vault/pull/10644
> Changelog: Agent Retry Stanza

- api/client.go
- command/agent.go
- command/agent/cache/api_proxy.go
- command/agent/cache/api_proxy_test.go
- command/agent/config/config.go
- command/agent/config/config_test.go
- command/agent/config/test-fixtures/config-consistency.hcl
- helper/storagepacker/storagepacker.go
- helper/testhelpers/teststorage/teststorage.go
- http/handler.go
- http/logical.go
- http/logical_test.go
- http/util.go
- physical/raft/fsm.go
- physical/raft/raft.go
- sdk/logical/request.go
- vault/cluster.go
- vault/core.go
- vault/core_util.go
- vault/dynamic_system_view.go
- vault/identity_store.go
- vault/identity_store_entities.go
- vault/identity_store_util.go
- vault/request_handling.go
- vault/wrapping.go
- vendor/github.com/hashicorp/vault/api/client.go
- vendor/github.com/hashicorp/vault/sdk/logical/request.go
This has little effect on Vault OSS, excluding the client and agent changes when used with an enterprise vault instance.
> OSS parts of the new client controlled consistency feature

- command/base_flags.go
- command/base_flags_test.go
Lets you know if a boolean flag was set or not.
> Bool pointer flag

- api/client.go
- api/client_test.go
- api/go.sum
- vendor/github.com/hashicorp/vault/api/client.go
- vendor/github.com/hashicorp/vault/api/go.sum
added some unit tests as well.
> don't panic on connection errors in DefaultRetryPolicy

- changelog/10995.txt
- go.mod
- go.sum
- vendor/github.com/hashicorp/vault-plugin-database-couchbase/README.md
- vendor/github.com/hashicorp/vault-plugin-database-couchbase/couchbase.go
- vendor/github.com/hashicorp/vault-plugin-database-couchbase/go.mod
- vendor/github.com/hashicorp/vault-plugin-database-couchbase/go.sum
- vendor/github.com/hashicorp/vault-plugin-database-couchbase/httputils.go
- vendor/modules.txt
Updates Couchbase DB plugin to v0.3.0 with `username_template` support.
> Vendor Couchbase DB plugin v0.3.0

- ui/tests/acceptance/secrets/backend/pki/cert-test.js
Tested this five times in Circle CI and could not get PKI tests to fail.
> PKI flaky test

- website/content/docs/secrets/mongodbatlas.mdx
PR for backport: https://github.com/hashicorp/vault/pull/10966
> Add notice about MongoDB Atlas whitelist deprecation

- changelog/11018.txt
- ui/app/templates/components/database-role-setting-form.hbs
- ui/tests/integration/components/database-role-setting-form-test.js
Adds test for db role form component
> Add test for db role setting form component

- ui/app/components/database-role-edit.js
- ui/app/models/database/role.js
Per discussion with backend team. 
Also, remove console log that snuck in there.
> Bug fix: change default root rotation on DBSE static role from 5s to 24hr

- changelog/10603.txt
Backporting a changelog update for 1.7 release.
> Add changelog entry for Snowflake DB support being added (#11078)

- physical/raft/fsm.go
- physical/raft/raft.go
* Fix autopilot fsm race
* No need to grab backend's lock
> Backport: Fix autopilot fsm race (#11091)

- website/data/alert-banner.js
As requested by revenue marketing, updates the alert banner to promote HCP Vault beta.
> Update alert banner

- website/content/api-docs/secret/transform.mdx
- website/content/docs/secrets/transform/tokenization.mdx
This is branched of document-mysql.
> Document snapshot, restore, and export decoded.

- sdk/version/version_base.go
- vendor/github.com/hashicorp/vault/sdk/version/version_base.go
> Update SDK version to 1.7.0rc2

- ui/tests/acceptance/access/identity/entities/create-test.js
- ui/tests/acceptance/enterprise-control-groups-test.js
- ui/tests/acceptance/enterprise-kmip-test.js
- ui/tests/acceptance/redirect-to-test.js
- ui/tests/acceptance/secrets/backend/pki/role-test.js
- ui/tests/acceptance/settings/configure-secret-backends/pki/section-cert-test.js
- ui/tests/pages/auth.js
- ui/tests/pages/components/config-pki-ca.js
- ui/tests/pages/components/console/ui-panel.js
- ui/tests/pages/secrets/backend/pki/edit-role.js
- ui/tests/pages/secrets/backend/pki/show.js
- ui/tests/pages/settings/mount-secret-backend.js
See original PR [here](https://github.com/hashicorp/vault/pull/11065)
> Backport 1.7.x fix flaky test and remove their skips

- physical/mysql/mysql_test.go
Tested with untilfail with parallel=3 to 150 runs.
> fix for mysql flaky test

- website/content/docs/internals/plugins.mdx
> Docs - Plugin register operator & example add

- website/content/docs/configuration/storage/consul.mdx
Updated link to: https://www.consul.io/api-docs/features/consistency
> Docs - Corrected links for Consul Consistency Modes

- changelog/11119.txt
- ui/app/components/database-role-edit.js
- ui/app/templates/components/database-connection.hbs
- ui/tests/acceptance/secrets/backend/database/secret-test.js
> Backport 1.7: UI: Connection "Add Role" automatically populates database

- changelog/11127.txt
- ui/app/adapters/database/connection.js
- ui/tests/acceptance/secrets/backend/database/secret-test.js
- ui/tests/pages/secrets/backend/database/connection.js
> Backport 1.7: UI/fix backend db connection (#11127)

- plugins/database/influxdb/connection_producer.go
> Backport 1.7: fix uninitialized tlsConfig in influxdb plugin 

- changelog/11142.txt
- ui/app/templates/components/token-expire-warning.hbs
* Update MMMM Do yyyy to MMMM do yyyy per date-fns format docs
* Add changelog
> Update MMMM Do yyyy to MMMM do yyyy per date-fns format docs (#11142)

- go.mod
- go.sum
- vendor/github.com/hashicorp/vault-plugin-auth-jwt/path_oidc.go
- vendor/modules.txt
Updates `go.mod` to bring in a bug fix from https://github.com/hashicorp/vault-plugin-auth-jwt/pull/163.
The following steps were taken:
1. `go get github.com/hashicorp/vault-plugin-auth-jwt@v0.9.2`
2. `go mod vendor`
3. `go mod tidy`
> Updates the JWT/OIDC auth plugin to v0.9.2

- go.mod
- go.sum
- vendor/github.com/hashicorp/vault-plugin-auth-jwt/path_oidc.go
- vendor/modules.txt
This PR backports a bug fix for the JWT/OIDC auth plugin from #11157.
The following steps were taken:
1. `git checkout release/1.7.x`
2. `git checkout -b backport-pr-11157-1.7.x`
3. `git cherry-pick 0658e3a`
> Backport 1.7.x: Updates the JWT/OIDC auth plugin to v0.9.2 (#11157)

- changelog/_1739.txt
This PR adds a changelog entry for 1.7 changes to the key management secrets engine.
> Adds a changelog entry for key management secrets engine

- website/data/alert-banner.js
🎟️ [Asana](https://app.asana.com/0/1187888078520425/1200082617596402/f)
🔍 [Preview](https://vault-55xf0620m-hashicorp.vercel.app)
Updates the alert banner to promote an upcoming webinar.
> website: update alert banner for webinar

- changelog/11182.txt
- ui/app/components/namespace-link.js
See original PR [here](https://github.com/hashicorp/vault/pull/11182).
> Backport 1.7.x: UI/namespace bug

- ui/app/components/namespace-picker.js
Original [PR](https://github.com/hashicorp/vault/pull/11186)
> Backport 1.7.x: namespace fix

- website/content/docs/plugin-portal.mdx
Added the link to the Redis Enterprise database plugin GitHub repository.
> Added Redis Enterprise database plugin

- website/content/docs/plugin-portal.mdx
Adding a newly discovered community plugin
> Adding HSM PKI plugin

- website/data/alert-banner.js
🎟️ [Asana ticket](https://app.asana.com/0/1187888078520425/1200082617596402/f)
🔍 [Preview](https://vault-5gktk4vra-hashicorp.vercel.app)
Copy change to alert banner.
> website: update alert banner copy

- changelog/11213.txt
- ui/app/services/namespace.js
See original PR [here](https://github.com/hashicorp/vault/pull/11213).
> Backport 1.7.x: UI: Fix status menu bug

- changelog/11258.txt
- ui/app/models/database/connection.js
- ui/app/models/mount-options.js
- ui/app/models/secret-engine.js
- ui/lib/core/addon/components/message-error.js
- ui/lib/core/addon/templates/components/form-field.hbs
- ui/tests/acceptance/secrets/backend/kv/secret-test.js
> Backport 1.7.1: UI/fix kvv2 version (#11258)

- website/content/docs/concepts/integrated-storage/index.mdx
Fixes incorrectly formatted frontmatter
> website: fix incorrectly formatted frontmatter

- changelog/11283.txt
- ui/app/components/auth-jwt.js
See original PR [here](https://github.com/hashicorp/vault/pull/11283)
> Backport 1.7.x: Fix OIDC with hcp flag (#11283)

- website/pages/home/index.jsx
Swap Get Started & Try Cloud CTAs on the homepage hero
> Update the homepage hero CTAs

- website/pages/downloads/index.jsx
> Fix downloads page typos

- website/content/docs/agent/index.mdx
fixed link for vault agent as windows service
> Update index.mdx to fix link to vault agent as a windows service link

- changelog/11360.txt
- ui/app/styles/components/search-select.scss
- ui/lib/core/addon/templates/components/search-select.hbs
- Fixed styling for better readability and access to delete action
> Updated search select component styling

- website/content/docs/secrets/openldap.mdx
It's small bug, but took me few hours to get correct endpoint. So let's save someone else time.
> Fix endpoint path in example

- website/data/alert-banner.js
> disable alert banner

- command/commands.go
- command/license.go
- command/license_get.go
This is the OSS portion of https://github.com/hashicorp/vault-enterprise/pull/1860. The tests are in the ENT PR.
> Introduce a "vault license get" command

- website/content/docs/platform/k8s/csi/configurations.mdx
#11518 introduced a duplicate config so removing it.
> docs: remove duplicate config from csi

- website/content/api-docs/auth/userpass.mdx
This is for replacing the following PR: https://github.com/hashicorp/vault/pull/9685
> Docs - auth username characters

- website/content/docs/concepts/response-wrapping.mdx
Based on the gap analysis. I'm not sure this addition is correct though.
> Add functional to logical description

- changelog/11596.txt
- vault/dynamic_system_view.go
- vault/dynamic_system_view_test.go
- vault/password_policy_util.go
Backport of https://github.com/hashicorp/vault/pull/11596
> Backport 1.7: Fix plugin password policy bug not supporting namespaces

- changelog/11596.txt
- vault/dynamic_system_view.go
- vault/dynamic_system_view_test.go
- vault/password_policy_util.go
> Backport 1.6: Fix plugin password policy bug not supporting namespaces

- changelog/11094.txt
- ui/app/routes/vault/cluster.js
* Add null check before getting userRootNamespace from storage
* Add changelog
> Backport 1.6.x UI: Add null check before getting userRootNamespace from storage

- changelog/11182.txt
- ui/app/components/namespace-link.js
* fix with console to confirm showing
* remove console
* move order
* add changelog
> Backport 1.6.x: UI/namespace bug (#11182)

- ui/app/components/namespace-picker.js
* fix known issues not including picker
* fix namespace picker, thank you brian
> Backport 1.6.x: Bug fix namespace issues (#11186)

- website/content/api-docs/system/storage/raft.mdx
This is the follow up for the work done by @martinhristov90 in https://github.com/hashicorp/vault/pull/10517.
> Minor fix to the raft docs

- changelog/11641.txt
- ui/app/models/identity/group.js
- ui/app/templates/components/database-connection.hbs
- ui/app/templates/components/identity/item-details.hbs
- ui/app/templates/components/identity/item-groups.hbs
- ui/app/templates/components/identity/item-members.hbs
- ui/app/templates/components/identity/item-metadata.hbs
- ui/app/templates/components/identity/item-parent-groups.hbs
- ui/app/templates/components/identity/item-policies.hbs
- ui/app/templates/vault/cluster/access/identity/show.hbs
- ui/tests/acceptance/access/identity/_shared-tests.js
- ui/tests/pages/components/identity/edit-form.js
> Backport 1.7.2: UI fix identity model (#11641)

- website/data/alert-banner.js
Adds info for upcoming HashiConf to website's `<AlertBanner />` 
[🔍 Preview](https://vault-git-jmupdate-hashiconf-alert-banner-hashicorp.vercel.app/)
> [Website] Add HashiConf info to alert banner

- website/content/docs/platform/k8s/helm/configuration.mdx
A few small updates to the k8s helm configuration doc.
> docs: small fixes in k8s docs

- website/data/version.js
Update JS so the correct version is marked as latest.
> Update website version

- website/content/docs/secrets/terraform.mdx
Fixes a typo in the CLI commands for terraform secrets engine.
> Changes role/roles

- CODEOWNERS
An initial cut at some CODEOWNERS rules.
> Initial list for CODEOWNERS

- website/content/docs/platform/k8s/helm/configuration.mdx
- website/content/docs/platform/k8s/helm/examples/enterprise-dr-with-raft.mdx
- website/content/docs/platform/k8s/helm/examples/enterprise-perf-with-raft.mdx
- website/content/docs/platform/k8s/helm/examples/enterprise-with-raft.mdx
- website/content/docs/platform/k8s/helm/index.mdx
- website/content/docs/platform/k8s/helm/openshift.mdx
- website/content/docs/platform/k8s/helm/run.mdx
- website/content/docs/platform/k8s/injector/annotations.mdx
- website/content/docs/platform/k8s/injector/installation.mdx
Updating the doc for the latest releases of Vault K8s and Vault Helm:
https://github.com/hashicorp/vault-helm/blob/master/CHANGELOG.md#0120-may-25th-2021
https://github.com/hashicorp/vault-k8s/blob/master/CHANGELOG.md#0101-may-25-2021
> docs/k8s: update for latest releases

- changelog/11705.txt
- ui/app/controllers/vault/cluster/unseal.js
- ui/app/styles/components/empty-state.scss
- ui/app/styles/components/splash-page.scss
- ui/app/templates/vault/cluster/unseal.hbs
- ui/lib/core/addon/components/empty-state.js
- ui/lib/core/addon/components/shamir-flow.js
- ui/lib/core/addon/templates/components/shamir-flow.hbs
> Backport 1.7.3: UI message on unseal fail due to license

- changelog/11696.txt
Add changelog entry for #11696.
> changelog: add entry for #11696

- physical/alicloudoss/alicloudoss.go
- physical/azure/azure.go
- physical/cassandra/cassandra.go
- physical/cockroachdb/cockroachdb.go
- physical/consul/consul.go
- physical/couchdb/couchdb.go
- physical/dynamodb/dynamodb.go
- physical/etcd/etcd.go
- physical/etcd/etcd3.go
- physical/foundationdb/foundationdb.go
- physical/foundationdb/foundationdb_test.go
- physical/gcs/gcs.go
- physical/gcs/gcs_ha.go
- physical/manta/manta.go
- physical/mssql/mssql.go
- physical/mysql/mysql.go
- physical/oci/oci.go
- physical/oci/oci_ha.go
- physical/postgresql/postgresql.go
- physical/raft/fsm.go
- physical/raft/raft.go
- physical/raft/streamlayer.go
- physical/s3/s3.go
- physical/spanner/spanner.go
- physical/spanner/spanner_ha.go
- physical/swift/swift.go
- physical/zookeeper/zookeeper.go
This deprecates `errwrap.Wrapf()` in every subpackage of `physical`.
> physical: deprecate errwrap.Wrapf()

- command/server.go
> Restore lost server license config propagation

- sdk/database/dbplugin/v5/testing/test_helpers.go
- vendor/github.com/hashicorp/vault/sdk/database/dbplugin/v5/testing/test_helpers.go
> Fix MSSQL TestDeleteUser in MSSQL by increasing request timeouts

- command/operator_diagnose.go
- command/operator_diagnose_test.go
- vault/diagnose/helpers.go
- vault/diagnose/os_common.go
- vault/diagnose/os_openbsd_arm.go
- vault/diagnose/os_unix.go
- vault/diagnose/os_unix_other.go
- vault/diagnose/os_windows.go
- vault/diagnose/output.go
Also add a spot skipped helper.
> Segment out disk checks to disable on openbsd/arm

- vault/logical_system.go
- vault/logical_system_helpers.go
- vault/logical_system_paths.go
- vault/testing.go
- vault/testing_util.go
- website/content/api-docs/system/config-reload.mdx
- website/data/api-docs-nav-data.json
ENT PR https://github.com/hashicorp/vault-enterprise/pull/1908
> OSS parts of sys/config/reload/license

- builtin/credential/approle/backend_test.go
- changelog/11647.txt
- sdk/helper/tokenutil/tokenutil.go
- vendor/github.com/hashicorp/vault/sdk/helper/tokenutil/tokenutil.go
* Perform num uses check earlier
* Add CL
* Ensure that login works
> Backport: Tokenutil: Perform num uses check earlier (#11647)

- command/server.go
- vault/core.go
ENT PR https://github.com/hashicorp/vault-enterprise/pull/1926
> OSS parts of sighup license reload

- ui/app/templates/components/transit-edit.hbs
- ui/app/templates/components/transit-form-create.hbs
- ui/app/templates/components/transit-form-edit.hbs
- ui/app/templates/components/transit-form-show.hbs
Very similar to the other processes: removal of a transit-form-* partials.
> Partials Transit removal

- changelog/_1819.txt
- vault/acl.go
- vault/policy.go
- vault/policy_test.go
- website/content/docs/enterprise/control-groups.mdx
This PR copies the OSS components of: https://github.com/hashicorp/vault-enterprise/pull/1819/files
> oss part of control groups upgrade

- command/operator_diagnose.go
- go.mod
- go.sum
- vault/diagnose/helpers.go
- vault/diagnose/helpers_test.go
- vault/diagnose/output.go
- vendor/github.com/mitchellh/go-wordwrap/LICENSE.md
- vendor/github.com/mitchellh/go-wordwrap/README.md
- vendor/github.com/mitchellh/go-wordwrap/go.mod
- vendor/github.com/mitchellh/go-wordwrap/wordwrap.go
- vendor/modules.txt
Also finishes implementing indentation and adds word wrapping to messages,
warnings, and advice.
> Add Advice and Advise functions for adding an advice section to any span.

- website/content/docs/concepts/client-count.mdx
:mag: [Deploy preview](https://vault-git-doc-update-client-count-hashicorp.vercel.app/docs/concepts/client-count)
- Moved the **What is a Client?** doc from cloud.hashicorp.com repo to vault repo.
> moved client content from cloud to vault

- vault/diagnose/os_openbsd_arm.go
Did get the arm build working to validate it this time though...
> Third time trying to get the os_openbsd_arm.go right.

- website/data/alert-banner.js
---
Updates the alert banner data for HashiConf europe going live.
> chore: updates alert banner data

- website/pages/home/index.jsx
Fixes typo on homepage callout.
> website: fix incorrect content

- command/server.go
- command/server_test.go
ENT PR https://github.com/hashicorp/vault-enterprise/pull/1944
> OSS parts of sighup license reload test

- changelog/11838.txt
- go.mod
- go.sum
Updates consul-template@v026.0
Closes https://github.com/hashicorp/vault/issues/9816
> dep: update consul-template to v0.26.0

- changelog/11836.txt
- go.mod
- go.sum
Updating AD dependency for latest release.
> mod: update vault-plugin-secrets-ad@v0.9.1

- .circleci/config.yml
- .circleci/config/commands/exit-if-branch-does-not-need-test-ui.yml
- .circleci/config/workflows/ci.yml
- .github/workflows/changelog-checker.yml
- .github/workflows/stable-website.yaml
- scripts/dist.sh
- scripts/update_plugin_modules.sh
Prepare to rename the Vault repo master branch to main.
> Rename some references from master to main

- changelog/11796.txt
Add changelog for InfluxDB username_template
> InfluxDB - add changelog

- vault/diagnose/file_checks.go
CI Failure: https://app.circleci.com/pipelines/github/hashicorp/vault-enterprise/5319/workflows/de447959-e092-4ac1-8aff-d4aa46042468/jobs/196526
> Remove Lingering Print Statements in Diagnose

- changelog/11884.txt
- ui/app/components/auth-jwt.js
- ui/app/routes/vault/cluster/oidc-callback.js
- ui/app/templates/components/auth-form.hbs
- ui/tests/integration/components/auth-jwt-test.js
> Backport 1.6.6: UI/fix safari oidc login (#11884)

- changelog/11884.txt
- ui/app/components/auth-jwt.js
- ui/app/routes/vault/cluster/oidc-callback.js
- ui/app/templates/components/auth-form.hbs
- ui/tests/integration/components/auth-jwt-test.js
> Backport 1.7.3: UI/fix safari oidc login (#11884)

- website/components/subnav/index.jsx
Small update to help improve attribution for HCP signups.
> update content param for improved attribution

- command/operator_diagnose.go
- helper/constants/constants_oss.go
- helper/testhelpers/testhelpers_oss.go
- vault/core_util.go
- vault/diagnose/constants.go
- vault/external_tests/raft/raft_test.go
This is the OSS part of the Diagnose License Checking. The full PR can be found here: https://github.com/hashicorp/vault-enterprise/pull/1975/files
> Diagnose License Check (OSS)

- changelog/11502.txt
Just a changelog entry for #11502
> Adding changelog for #11502

- .circleci/config.yml
- .circleci/config/commands/go_test.yml
These files do not need to be different, so making them the same.
> ci: update go_test to match one from ent

- vault/logical_system.go
- vault/logical_system_paths.go
- vault/logical_system_test.go
brian and i discussed this - tagging scott and roy since you were involved with the runner up PR to this
> remove trailing / on leases API endpoint

- vault/expiration_testing_util_common.go
- Adds OSS changes for https://github.com/hashicorp/vault-enterprise/pull/1979
> [VAULT-1981] Add OSS changes

- ui/app/components/secret-edit.js
Adding a conditional to only check path not the key.
> UI KV validation fix

- changelog/12003.txt
- ui/app/helpers/all-features.js
CLI and UI properly list all features that license allows.
> Adds transform secrets engine to feature

- website/content/docs/enterprise/license/faq.mdx
- website/content/docs/enterprise/license/index.mdx
- website/data/docs-nav-data.json
:mag: [Deploy preview](https://vault-us6b3zqn6-hashicorp.vercel.app/docs/enterprise/license/faq)
> changed name from faqs to faq

- website/content/api-docs/secret/databases/influxdb.mdx
Updating API docs for InfluxDB to include username_template parameter.
> InfluxDB - Update API docs

- website/content/docs/commands/operator/step-down.mdx
Clarify that step-down can be run against any node in the cluster
> Clarify step-down functionality in docs 

- changelog/12024.txt
- ui/app/adapters/database/credential.js
- ui/app/adapters/secret-v2-version.js
- ui/app/components/generate-credentials-database.js
- ui/app/components/secret-list-header-tab.js
- ui/app/models/database/credential.js
- ui/app/routes/vault/cluster/secrets/backend/credentials.js
- ui/app/serializers/database/credential.js
- ui/app/templates/components/database-list-item.hbs
- ui/app/templates/components/database-role-edit.hbs
- ui/app/templates/components/generate-credentials-database.hbs
- ui/app/templates/components/get-credentials-card.hbs
- ui/app/templates/vault/cluster/secrets/backend/credentials.hbs
> Backport 1.7.4: UI Database control group access

- changelog/12035.txt
- ui/app/routes/vault/cluster/logout.js
> Backport 1.6.6: Automatically refresh UI page on logout (#12035)

- changelog/11942.txt
* secrets/ad: change improvement to feature in changelog
* Update per feature requirements
> Backport: secrets/ad: change improvement to feature in changelog (#12095)

- changelog/12035.txt
- ui/app/routes/vault/cluster/logout.js
> Backport 1.7.4: Automatically refresh UI page on logout (#12035)

- changelog/11956.txt
Update the changelog for https://github.com/hashicorp/vault/pull/11956 to match the "feature" CL requirements
> mongodbatlas: update changelog for username customization

- changelog/11956.txt
Update the changelog for #11956 to match the "feature" CL requirements
> Backport: mongodbatlas: update changelog for username customization

- physical/azure/azure.go
- physical/azure/azure_test.go
This is exposing a problem with the Azurite List implementation and how it handles pagination, so this PR is on hold until they fix that.
> Add support for testing Azure storage backend in CI using Azurite.

- changelog/12035.txt
- ui/app/routes/vault/cluster/logout.js
> Backport 1.8.0: Automatically refresh UI page on logout (#12035)

- changelog/11958.txt
- changelog/12023.txt
This PR updates the formatting of changelog entries for GCP and Key Management features coming in 1.8.
> changelog: update feature formatting for gcp and key management secrets

- website/content/api-docs/system/storage/raft.mdx
> Document raft bootstrap API.

- changelog/12079.txt
- ui/app/templates/vault/cluster/secrets/backend/versions.hbs
- ui/lib/core/addon/components/linked-block.js
- ui/lib/core/addon/components/list-item.js
- ui/lib/core/addon/templates/components/list-item.hbs
- ui/tests/acceptance/secrets/backend/kv/secret-test.js
See PR [here.](https://github.com/hashicorp/vault/pull/12079)
> Backport: 1.8.x Fix KV version history linkedblock

- changelog/12111.txt
- ui/app/adapters/database/credential.js
- ui/app/adapters/database/role.js
- ui/app/components/database-role-edit.js
- ui/app/controllers/vault/cluster/secrets/backend/credentials.js
- ui/app/controllers/vault/cluster/secrets/backend/show.js
- ui/app/helpers/secret-query-params.js
- ui/app/models/database/role.js
- ui/app/routes/vault/cluster/secrets/backend/credentials.js
- ui/app/routes/vault/cluster/secrets/backend/secret-edit.js
- ui/app/serializers/database/role.js
- ui/app/templates/components/database-role-edit.hbs
- ui/app/templates/components/secret-list/database-list-item.hbs
> Backport: 1.8.x UI/database cg read role (#12111)

- changelog/12111.txt
- ui/app/adapters/database/credential.js
- ui/app/adapters/database/role.js
- ui/app/components/database-role-edit.js
- ui/app/controllers/vault/cluster/secrets/backend/credentials.js
- ui/app/controllers/vault/cluster/secrets/backend/show.js
- ui/app/helpers/secret-query-params.js
- ui/app/models/database/role.js
- ui/app/routes/vault/cluster/secrets/backend/credentials.js
- ui/app/routes/vault/cluster/secrets/backend/secret-edit.js
- ui/app/serializers/database/role.js
- ui/app/templates/components/database-list-item.hbs
- ui/app/templates/components/database-role-edit.hbs
> Backport 1.7.x: UI/database cg read role (#12111)

- website/content/docs/secrets/databases/index.mdx
Update Database Capabilities docs page to include username customization column
> docs: Update Database Capabilities to include username customization

- vault/activity_log.go
- vault/request_handling.go
- vault/token_store.go
OSS only version of https://github.com/hashicorp/vault-enterprise/pull/2047
> [VAULT-2807] Count entity tokens on use

- physical/raft/snapshot.go
Followup to https://github.com/hashicorp/vault/pull/12034 (I missed a case).
> Tweak creation of vault.db file, take 2

- CHANGELOG.md
> Correct changelog re log shipper buffer size config

- builtin/logical/pki/path_issue_sign.go
> Forward cert signing requests to primary from perf secondaries

- website/content/docs/upgrading/upgrade-to-1.8.0.mdx
- website/data/docs-nav-data.json
> Add 1.8 upgrade guide

- website/data/version.js
> Update website download link

- website/content/docs/concepts/client-count.mdx
- website/content/docs/concepts/password-policies.mdx
- website/content/docs/internals/security.mdx
**What does this PR do**
Fix dead or broken links in this docs page, making navigation easy for others.
> Docs: Fix broken link

- CHANGELOG.md
The PR had a CL entry, no idea how it got lost.
> Add a missing CL entry for #11269 and make raft CL entries for 1.8 more consistent

- website/content/docs/platform/k8s/helm/configuration.mdx
- website/content/docs/platform/k8s/injector/annotations.mdx
Covers the changes in the v0.11.0 release: https://github.com/hashicorp/vault-k8s/blob/master/CHANGELOG.md#0110-july-28-2021
> docs: updates for vault-k8s v0.11.0

- ui/tests/acceptance/secrets/backend/kv/secret-test.js
Fixes failing browserstack tests
> Add settled() to failing browserstack tests

- website/content/docs/concepts/ha.mdx
- website/content/docs/concepts/integrated-storage/index.mdx
- website/content/docs/configuration/storage/raft.mdx
* add missing markup
* add more links to the configuration pages
> Improve "Integrated Storage" documentation

- changelog/12229.txt
- go.mod
- vault/diagnose/os_common.go
Backport of: https://github.com/hashicorp/vault/pull/12229
> backport disk usage print fixes

- website/content/docs/commands/operator/usage.mdx
Simple add to link to the quite-useful Learn tutorial on usage metrics
> Add link to Learn's usage tutorial

- sdk/version/version_base.go
@sgmiller I'm not sure if I should be doing something else for this update?
> Updating SDK version for 1.9 dev

- website/content/docs/agent/template.mdx
static_secret_render_interval mention
> Agent template static secrets docs update

- vault/activity_log.go
OSS part of https://github.com/hashicorp/vault-enterprise/pull/2064/files
> [VAULT-2822] Sort client count response

- website/content/docs/upgrading/upgrade-to-1.9.0.mdx
- website/data/docs-nav-data.json
Since we've already identified something for the 1.9 upgrade guide, we'll create the guide now but:
1. not cherry pick it
2. leave it out of the sidebar
3. add a disclaimer to the top
> Add draft upgrade guide

- changelog/12351.txt
- sdk/database/dbplugin/v5/grpc_client.go
Small PR to correct the error message for `DeleteUser`.
> dbplugin: fix error message in DeleteUser

- website/content/docs/agent/autoauth/methods/approle.mdx
adding sample file after seeing it asked in the wild a bit
> Add agent approle method example

- changelog/12351.txt
- sdk/database/dbplugin/v5/grpc_client.go
* dbplugin: fix error message in DeleteUser
* add changelog
> Backport1.8.x: dbplugin: fix error message in DeleteUser (#12351)

- website/content/docs/platform/k8s/helm/configuration.mdx
- website/content/docs/platform/k8s/helm/examples/enterprise-dr-with-raft.mdx
- website/content/docs/platform/k8s/helm/examples/enterprise-perf-with-raft.mdx
- website/content/docs/platform/k8s/helm/examples/enterprise-with-raft.mdx
- website/content/docs/platform/k8s/helm/examples/injector-tls-cert-manager.mdx
- website/content/docs/platform/k8s/helm/index.mdx
- website/content/docs/platform/k8s/helm/openshift.mdx
- website/content/docs/platform/k8s/helm/run.mdx
- website/content/docs/platform/k8s/injector/annotations.mdx
- website/content/docs/platform/k8s/injector/installation.mdx
https://github.com/hashicorp/vault-helm/blob/master/CHANGELOG.md#0150-august-19th-2021
https://github.com/hashicorp/vault-k8s/blob/master/CHANGELOG.md#0120-august-18-2021
Depends on https://github.com/hashicorp/vault-helm/pull/598
> docs: updates for vault-helm-0.15.0 and vault-k8s-0.12.0

- sdk/version/version_base.go
- vendor/github.com/hashicorp/vault/sdk/version/version_base.go
This is the PR corresponding to step 1c in Release doc https://docs.google.com/document/d/16sjIk3hzFDPyY5A9ncxTZV_9gnpYSF1_Vx6UA1iiwgI/edit#bookmark=id.82xjf6b7po1e
> [VAULT-3268] Update sdk vault version

- website/content/api-docs/index.mdx
> Document some missing http status codes.

- changelog/12339.txt
- vault/auth.go
- vault/quotas/quotas.go
Backport for: https://github.com/hashicorp/vault/pull/12339/files
Backport of Ent tests (for 1.7): https://github.com/hashicorp/vault-enterprise/pull/2137
> (OSS Backport 1.7.5): Restrict Quota Deletion to Primary Cluster [vault-2399]

- website/content/docs/configuration/seal/awskms.mdx
This PR was opened in order to get the change merged from the original PR, which is stuck at the CI check stage and we are unable to locate it. 
https://github.com/hashicorp/vault/pull/11497
:mag: [Deploy Preview](https://vault-gqdvir4i0-hashicorp.vercel.app/docs/configuration/seal/awskms)
> adding ARN in description

- website/content/api-docs/system/audit.mdx
- website/content/docs/audit/index.mdx
By popular customer question.. clarified in docs.
> Clarify on overview page that audit is default replicated

- website/content/docs/platform/k8s/helm/configuration.mdx
Using the commented values from the Helm Chart's `values.yaml`
> fix: update injector resources requirements

- changelog/12478.txt
- ui/app/routes/vault/cluster.js
- ui/app/templates/vault/cluster.hbs
> Backport 1.8.x: UI Fix missing nav links on namespace login (#12478)

- website/content/docs/commands/index.mdx
- Updates the CLI documentation with the edge case that was discovered while looking into https://github.com/hashicorp/vault/issues/12290
> Update kv input documentation with edge case

- website/content/docs/commands/audit/enable.mdx
Based on customer feedback I've added a link to the extended configuration parameters to help enable customers to onboard without needing to reach out to support.
> audit page tweaks based on customer feedback

- website/content/docs/configuration/entropy-augmentation.mdx
- website/content/docs/enterprise/control-groups.mdx
- website/content/docs/enterprise/entropy-augmentation.mdx
- website/content/docs/enterprise/hsm/index.mdx
- website/content/docs/enterprise/mfa/index.mdx
- website/content/docs/enterprise/sealwrap.mdx
- website/content/docs/enterprise/sentinel/index.mdx
- website/content/docs/secrets/key-management/index.mdx
- website/content/docs/secrets/transform/index.mdx
Update language to support current enterprise packaging.
> docs: update packaging

- website/content/api-docs/auth/kubernetes.mdx
- website/content/docs/auth/kubernetes.mdx
- website/content/docs/platform/k8s/csi/index.mdx
Link to the instructions for looking up a Kubernetes cluster's service
account issuer.
Closes #11953
> docs: k8s auth issuer lookup

- website/content/docs/commands/secrets/tune.mdx
Been asked this a few times.. so figured I'd doc it instead of pasting in my last response to others.
> add example for secret tuning

- website/content/docs/plugin-portal.mdx
Added Artifactory secrets vault plugin under partner programs
> Added Artifactory secrets plugin

- go.mod
- go.sum
See https://github.com/sethvargo/go-limiter/commit/748ae80bc17999c55910c5fd6d901d6f87e7f366
> Upgrade go-limiter to v0.7.1 to fix build failure in go1.17.1

- website/content/docs/platform/k8s/helm/configuration.mdx
- website/content/docs/platform/k8s/helm/enterprise.mdx
- website/content/docs/platform/k8s/helm/examples/enterprise-dr-with-raft.mdx
- website/content/docs/platform/k8s/helm/examples/enterprise-perf-with-raft.mdx
- website/content/docs/platform/k8s/helm/examples/enterprise-with-raft.mdx
- website/content/docs/platform/k8s/helm/index.mdx
- website/content/docs/platform/k8s/helm/openshift.mdx
- website/content/docs/platform/k8s/helm/run.mdx
- website/content/docs/platform/k8s/injector/annotations.mdx
- website/content/docs/platform/k8s/injector/installation.mdx
Updating the k8s platform docs for the vault-k8s and vault-helm releases:
- https://github.com/hashicorp/vault-k8s/blob/master/CHANGELOG.md#0130-september-15-2021
- https://github.com/hashicorp/vault-helm/blob/master/CHANGELOG.md#0160-september-16th-2021
> docs: vault-k8s 0.13.0 and vault-helm 0.16.0

- command/token_renew.go
- website/content/api-docs/auth/token.mdx
- website/content/docs/commands/token/renew.mdx
- Clarifies some details around the `increment` parameter for token renewal
Fixes https://github.com/hashicorp/vault/issues/12556
> Update token renew docs

- website/content/docs/auth/gcp.mdx
🎟️ [Asana ticket](https://app.asana.com/0/563192436488770/1200994557550686/f)
🔍 [Deploy Preview](https://vault-git-add-gcp-auth-snippet-hashicorp.vercel.app/docs/auth/gcp#code-example)
This PR adds code snippet to demonstrate the `gcp` auth in Go.
> Add code snippet to demonstrate GCP auth in Go

- command/config/validate_listener.go
Adds missing build tag from PR 12421
> Fix build tag

- website/content/docs/platform/servicenow/installation.mdx
Reverts hashicorp/vault#12516
The discovery plugin is required for the installation and configuration steps detailed on the website.
> Revert "Update installation.mdx"

- website/content/docs/concepts/dev-server.mdx
Added information flag to enable v1 KV secret engine in dev mode
> Add additional info on v1 KV engine

- website/content/guides/operations/production.mdx
Quick update to the production guidelines based on a previous audit
> Update production hardening guidelines

- website/content/docs/enterprise/sealwrap.mdx
Updated docs to align with Enterprise package name.
> docs: updated enterprise package name

- website/data/version.js
Per https://github.com/hashicorp/vault/tree/main/website#changing-the-release-version
> Updating website latest to 1.8.3

- changelog/12008.txt
- changelog/12478.txt
Fix is not a valid release-note type
> Fix changelogs

- .github/workflows/changelog-checker.yml
Fail on invalid changelog type: "fix".
> Update changelog checker

- website/content/docs/enterprise/namespaces.mdx
This was implied but could be clearer.
> Highlight that password policies are defined in a namespace

- changelog/12688.txt
- go.mod
- go.sum
Upgrade vault-plugin-auth-kubernetes. Includes:
-  https://github.com/hashicorp/vault-plugin-auth-kubernetes/pull/114
> upgrade vault-plugin-auth-kubernetes

- go.mod
- go.sum
Run `go mod tidy` to sync up and clean up `go.mod` and `go.sum` files.
> gomod: run go mod tidy

- website/data/version.js
Not going to merge this until we're good to go, but getting it queued up.
> Updating website for 1.8.4

- ui/app/components/clients/history.js
- ui/app/templates/components/clients/history.hbs
- ui/lib/core/addon/components/search-select.js
Backport for https://github.com/hashicorp/vault/pull/12964
> Backport 1.9.0: On bar chart selection replace search component with HTML (#12964)

- ui/app/components/clients/history.js
- ui/app/templates/components/clients/history.hbs
Backport for https://github.com/hashicorp/vault/pull/12960
> Backport 1.9.0: Added date range to client count csv filename (#12960)

- ui/app/styles/components/global-flash.scss
> Break line if words are long in flash messages

- sdk/version/version_base.go
@kpenfound @claire-labry We'll also need this to go in
> 1.8.5 version bump

- sdk/version/version_base.go
Updating version (SDK version_base) for release 1.7.6
> Release branch

- website/content/api-docs/system/internal-counters.mdx
- Just the docs change from https://github.com/hashicorp/vault-enterprise/pull/2277/files
- This OSS change was missed when merging the PR above, adding it in now so that the docs update shows up on stable-website
> Add docs update for counter forwarding to oss

- website/content/docs/platform/k8s/helm/configuration.mdx
> Format Docs Vault-Helm v0.17.0

- changelog/12888.txt
> fix 12888 release note format

- changelog/12888.txt
* fix release note format
* deprecation -> change
> Backport 1.9.0: Update expiration flag changelog

- ui/app/templates/components/secret-delete-menu.hbs
- ui/tests/acceptance/secrets/backend/kv/secret-test.js
See original PR [here](https://github.com/hashicorp/vault/pull/13050)
> Backport: 1.9.x KV bug fix for delete modal

- changelog/13038.txt
- ui/app/components/pgp-list.js
- ui/tests/integration/components/pgp-list-test.js
Original PR https://github.com/hashicorp/vault/pull/13038
> Backport  to 1.7.x - PGP list bug fix

- changelog/13038.txt
- ui/app/components/pgp-list.js
- ui/tests/integration/components/pgp-list-test.js
Original PR https://github.com/hashicorp/vault/pull/13038
> Backport to 1.8.x - PGP list bug fix

- changelog/13038.txt
- ui/app/components/pgp-list.js
- ui/tests/integration/components/pgp-list-test.js
Original PR https://github.com/hashicorp/vault/pull/13038
> Backport to 1.9.x - PGP list bug fix

- website/content/api-docs/secret/azure.mdx
- website/content/docs/secrets/azure.mdx
Documentation related to the rotate-root feature and notes about migrating from Azure AD to MS Graph.
> secrets/azure: add doc for rotate-root and AAD migration

- website/content/api-docs/secret/azure.mdx
- website/content/docs/secrets/azure.mdx
* secrets/azure: add doc for rotate-root and AAD migration
* Formatting
* Fix bad link, update warnings
> Backport: secrets/azure: add doc for rotate-root and AAD migration (#13066)

- changelog/13054.txt
- ui/app/templates/components/generated-item-list.hbs
> Backport 1.8.0: UI/Adds pagination to auth methods list (#13054)

- changelog/13054.txt
- ui/app/templates/components/generated-item-list.hbs
> Backport 1.9.0: UI/Adds pagination to auth methods list (#13054)

- ui/app/adapters/secret-engine.js
> Backport 1.9.0: UI Show detailed error response on failed secret-engine list call

- ui/app/templates/components/database-connection.hbs
- ui/app/utils/database-helpers.js
- ui/tests/acceptance/secrets/backend/database/secret-test.js
- ui/tests/integration/components/database-role-setting-form-test.js
Backport for https://github.com/hashicorp/vault/pull/13087
> Backport 1.9.0: Add message while adding Oracle db connection (#13087)

- changelog/12621.txt
Backports the Changelog updates in `changelog/12621.txt` from https://github.com/hashicorp/vault/pull/13117
> Backport Changelog updates from #13117

- internalshared/configutil/config.go
- internalshared/configutil/kms_library.go
- Add a new top level configuration stanza named kms_library with Vault's SharedConfig struct
> OSS parts to support new kms_library configuration stanza.

- website/content/api-docs/system/internal-counters.mdx
- website/content/docs/concepts/client-count.mdx
This PR edits and addresses the remaining review comments from https://github.com/hashicorp/vault/pull/13007
> Docs Updates for Client Counting non-entity tokens

- go.mod
> Updating SDK in go.mod

- changelog/13152.txt
- ui/app/models/database/connection.js
> Backport 1.8.6: UI hide verify-connection attribute on connection config show page (#13152)

- website/content/docs/platform/mssql/index.mdx
- website/content/docs/platform/mssql/installation.mdx
- website/content/docs/platform/mssql/troubleshooting.mdx
- website/data/docs-nav-data.json
Provides overview, installation and troubleshooting docs for the upcoming Vault EKM provider for MS SQL server
> Website docs for Vault EKM provider for MS SQL

- website/content/docs/concepts/client-count/faq.mdx
- website/content/docs/release-notes/1.9.0.mdx
Minor corrections/changes to 1.9 documentation:
- Client Count FAQ (:mag: [Deploy Preview](https://vault-git-update-1-9-docs-hashicorp.vercel.app/docs/concepts/client-count/faq))
- Release Notes (:mag: [Deploy Preview](https://vault-git-update-1-9-docs-hashicorp.vercel.app/docs/release-notes/1.9.0))
> Updated Vault 1.9 documentation

- ui/app/templates/components/generate-credentials.hbs
- ui/app/templates/components/pki-cert-show.hbs
> Backport 1.9.x: UI/Make revocation time and credential dates human-readable (#13196)

- changelog/13107.txt
- ui/app/adapters/application.js
- ui/tests/integration/components/raft-storage-restore-test.js
> Backport 1.9.x: Raft Snapshot Restore Bug (#13107)

- changelog/13107.txt
- ui/app/adapters/application.js
- ui/tests/integration/components/raft-storage-restore-test.js
> Backport 1.8.x: Raft Snapshot Restore Bug (#13107)

- changelog/13107.txt
- ui/app/adapters/application.js
- ui/tests/integration/components/raft-storage-restore-test.js
> Backport 1.7.x: Raft Snapshot Restore Bug (#13107)

- changelog/13133.txt
- ui/app/components/auth-jwt.js
- ui/app/routes/vault/cluster/oidc-callback.js
- ui/tests/integration/components/auth-jwt-test.js
- ui/tests/pages/components/console/ui-panel.js
- ui/tests/unit/components/auth-jwt-test.js
> Backport 1.9.x: OIDC Auth Bug (#13133)

- changelog/13133.txt
- ui/app/components/auth-jwt.js
- ui/app/routes/vault/cluster/oidc-callback.js
- ui/tests/integration/components/auth-jwt-test.js
- ui/tests/pages/components/console/ui-panel.js
- ui/tests/unit/components/auth-jwt-test.js
> Backport 1.7.x: OIDC Auth Bug (#13133)

- changelog/13133.txt
- ui/app/components/auth-jwt.js
- ui/app/routes/vault/cluster/oidc-callback.js
- ui/tests/integration/components/auth-jwt-test.js
- ui/tests/pages/components/console/ui-panel.js
- ui/tests/unit/components/auth-jwt-test.js
> Backport 1.8.x: OIDC Auth Bug (#13133)

- helper/testhelpers/testhelpers.go
OSS component of https://github.com/hashicorp/vault-enterprise/pull/2354
> Enhance test utility metrics returned

- changelog/13166.txt
- ui/app/models/secret-v2-version.js
- ui/app/routes/vault/cluster/secrets/backend/secret-edit.js
- ui/app/styles/components/toolbar.scss
- ui/app/templates/components/secret-edit-toolbar.hbs
- ui/jsconfig.json
- ui/lib/core/addon/components/toolbar-link.js
- ui/lib/core/addon/templates/components/toolbar-link.hbs
- ui/lib/core/stories/toolbar/toolbar-link.md
- ui/lib/core/stories/toolbar/toolbar-link.stories.js
- ui/tests/acceptance/secrets/backend/kv/secret-test.js
- ui/tests/integration/components/toolbar-link-test.js
> Backport 1.9.x: KV automatic delete state issue in UI (#13166)

- changelog/13238.txt
- ui/app/helpers/parse-pki-cert.js
- ui/app/models/pki-ca-certificate.js
- ui/app/models/pki-certificate.js
- ui/app/templates/components/config-pki-ca.hbs
- ui/app/templates/components/pki-cert-show.hbs
- ui/tests/acceptance/settings/configure-secret-backends/pki/section-cert-test.js
- ui/tests/pages/components/config-pki-ca.js
> Backport 1.9.0: UI/Fix node-forge EC error (#13238)

- ui/tests/acceptance/settings/configure-secret-backends/pki/section-cert-test.js
Adds an `await settled` to fix a flaky test
> UI/Flaky test fix for EC certs

- ui/tests/acceptance/settings/configure-secret-backends/pki/section-cert-test.js
> Backport 1.9.0: UI/ flaky test for EC certs(#13265)

- sdk/version/version_base.go
> Updating version in SDK for 1.7.7

- CHANGELOG.md
Update the changelog to reflect improvements introduced with the 1.9.0-rc1 release
> Update 1.9.0-rc1 changelog

- ui/app/templates/components/generate-credentials-database.hbs
> Backport 1.8.6: Disable 'You will not be able to access these later' warning for static db creds

- ui/app/components/get-credentials-card.js
- ui/app/templates/components/get-credentials-card.hbs
- ui/app/templates/vault/cluster/secrets/backend/overview.hbs
- ui/tests/acceptance/secrets/backend/database/secret-test.js
[Original PR](https://github.com/hashicorp/vault/pull/13336)
> Backport: 1.9.x GetCredentials Card bug fix

- website/content/docs/secrets/databases/custom.mdx
Updates sample code snippet in the custom database docs to use the proper import path and functions from those packages.
> docs: update custom database sample code

- changelog/13365.txt
> auth/jwt: update changelog for pkce improvement

- changelog/13396.txt
- ui/app/components/clients/history.js
- ui/app/templates/components/clients/history.hbs
- ui/tests/integration/components/clients-current-test.js
> Backport 1.9.2: UI/fix client count partial (#13396)

- website/content/api-docs/auth/userpass.mdx
- website/content/api-docs/index.mdx
- Documents restriction around path parameter noticed in https://github.com/hashicorp/vault/issues/13353
> Add docs about path param restrictions

- ui/app/components/clients/horizontal-bar-charts.js
- ui/app/styles/components/horizontal-bar-charts.scss
- ui/app/styles/core.scss
- ui/app/styles/core/charts.scss
- ui/app/templates/components/clients/dashboard.hbs
- ui/app/templates/components/clients/horizontal-bar-charts.hbs
- ui/app/templates/components/clients/total-client-usage.hbs
Creates horizontal bar chart components
TO DO:
> UI/ Double horizontal bar charts

- website/content/docs/secrets/nomad.mdx
This PR updates some text in the Vault docs related to Nomad.
> website: Update Nomad-related text

- go.mod
- go.sum
> Backport 1.9.x: auth/gcp: update to v0.11.3 (#13457)

- website/next.config.js
- website/package-lock.json
- website/package.json
- website/pages/api-docs/[[...page]].jsx
- website/pages/docs/[[...page]].jsx
- website/pages/intro/[[...page]].jsx
https://vault-git-kevin-versioned-docs-hashicorp.vercel.app/
> feat(website): versioned-docs

- website/content/api-docs/system/replication/replication-dr.mdx
- website/content/docs/internals/replication.mdx
- website/content/docs/upgrading/index.mdx
Trying to clarify some upgrade questions. Learn update to follow in separate PR.
> Upgrade guidance updates from VLT-172

- changelog/12344.txt
- website/content/api-docs/secret/databases/cassandra.mdx
- website/content/api-docs/secret/databases/elasticdb.mdx
- website/content/api-docs/secret/databases/hanadb.mdx
- website/content/api-docs/secret/databases/index.mdx
- website/content/api-docs/secret/databases/influxdb.mdx
- website/content/api-docs/secret/databases/mongodb.mdx
- website/content/api-docs/secret/databases/mongodbatlas.mdx
- website/content/api-docs/secret/databases/mssql.mdx
- website/content/api-docs/secret/databases/mysql-maria.mdx
- website/content/api-docs/secret/databases/oracle.mdx
- website/content/api-docs/secret/databases/postgresql.mdx
- website/content/api-docs/secret/databases/redshift.mdx
- website/content/api-docs/secret/databases/snowflake.mdx
Fixed a bunch of formatting issues and broken JSON outputs.
> Improve databases documentation

- ui/tests/acceptance/enterprise-control-groups-test.js
- ui/tests/acceptance/enterprise-replication-test.js
- ui/tests/acceptance/ssh-test.js
Fixes more timing issues in acceptance tests since the Ember 3.24 upgrade.
> Fixes some flaky enterprise tests

- website/content/docs/internals/architecture.mdx
The words "can be" were missing
> Fix a sentence in architecture.mdx

- website/content/docs/auth/github.mdx
- website/content/docs/auth/index.mdx
- website/content/docs/internals/security.mdx
Provide changes based on recent audit feedback, and describes risks of third party auth methods and plugins
> docs: update GitHub auth method docs and security model

- README.md
- api/README.md
- website/content/api-docs/libraries.mdx
- website/content/docs/auth/approle.mdx
- website/content/docs/auth/aws.mdx
- website/content/docs/auth/azure.mdx
- website/content/docs/auth/gcp.mdx
- website/content/docs/auth/kubernetes.mdx
- website/content/docs/concepts/auth.mdx
- website/data/docs-nav-data.json
Backports doc changes from PR [13491](https://github.com/hashicorp/vault/pull/13491)
> Backport: Update example code links, remove unneeded comments (#13491)

- ui/tests/acceptance/enterprise-replication-test.js
- ui/tests/acceptance/secrets/backend/pki/role-test.js
- ui/tests/acceptance/transit-test.js
- ui/tests/acceptance/unseal-test.js
Small changes to address some flaky acceptance tests.
> Flaky Acceptance Tests

- changelog/13604.txt
- ui/app/templates/components/secret-list-header.hbs
> Backport 1.7.x: UI/Fix secrets list breadcrumb nav

- ui/tests/acceptance/enterprise-replication-test.js
- ui/tests/helpers/poll-cluster.js
This is a further attempt to get the replication acceptance tests to pass reliably.
> Flaky Replication Tests

- api/client.go
- command/agent.go
- command/agent/auth/cert/cert.go
- command/agent/sink/sink.go
OSS changes for the ENT PR https://github.com/hashicorp/vault-enterprise/pull/2329/files
> OSS changes for ent pr

- changelog/13604.txt
- ui/app/templates/components/secret-list-header.hbs
> Backport 1.9.x: UI/Fix secrets list breadcrumb nav

- changelog/13604.txt
- ui/app/templates/components/secret-list-header.hbs
> Backport 1.8.x: UI/Fix secrets list breadcrumb nav

- website/content/docs/release-notes/1.9.0.mdx
> Updated spelling

- changelog/12791.txt
- http/logical_test.go
- sdk/logical/translate_response.go
- website/content/api-docs/auth/token.mdx
Closes https://github.com/hashicorp/vault/issues/10664
> Return num_uses during authentication

- website/lib/consent-manager-services/index.ts
- website/pages/_app.js
[:mag: Preview Link](https://vault-git-nqweb-add-qualified-chatbot-consent-hashicorp.vercel.app/)
---
This PR adds the Qualified chatbot to the Vault website's consent manager.
> website: Add Qualified chatbot to consent manager

- builtin/logical/pki/backend_test.go
- builtin/logical/pki/ca_util.go
- builtin/logical/pki/cert_util.go
- builtin/logical/pki/crl_util.go
- builtin/logical/pki/fields.go
- builtin/logical/pki/managed_key_util.go
- builtin/logical/pki/path_fetch.go
- builtin/logical/pki/path_intermediate.go
- builtin/logical/pki/path_issue_sign.go
- builtin/logical/pki/path_root.go
- builtin/logical/pki/util.go
- sdk/helper/certutil/helpers.go
- sdk/helper/certutil/types.go
- sdk/logical/managed_key.go
- The OSS side of things to leverage managed keys from the PKI secrets engine
> OSS integration of the PKI plugin with managed key infrastructure

- website/content/docs/internals/security.mdx
Document the use of mTLS between nodes
> docs: add cluster-to-cluster communications to external threat overview

- builtin/logical/pki/fields.go
- builtin/logical/pki/util.go
This is the OSS counterpart for PR [vault-enterprise #2487](https://github.com/hashicorp/vault-enterprise/pull/2487).
> Add new parameter managed_key_id for PKI CA key generation.

- website/content/docs/configuration/seal/pkcs11.mdx
These new features have made it out into the new Vault releases 1.8.8 and 1.9.3
> Documentation updates for new keys for PKCS#11 unsealing

- website/content/docs/secrets/databases/mssql.mdx
> Update mssql.mdx with typo error

- .gitignore
- .release/ci.hcl
- .release/security-scan.hcl
- Dockerfile
* add security-scan
* updating the alpine version
* clean up
* update the alpine version to be more prescriptive
> add security-scan for CRT (#13627)

- CHANGELOG.md
This includes:
* HSEC-2021-33 / CVE-2021-45042
* HSEC-2021-30 / CVE-2021-43998
* HSEC-2021-27 / CVE-2021-41802
> update changelog with recent security entries

- changelog/13872.txt
- ui/app/routes/vault/cluster/secrets/backend/list.js
- Set permissions state when call is successful
> Fix kv secret access bug

- changelog/13872.txt
- ui/app/routes/vault/cluster/secrets/backend/list.js
* Fix kv secret access bug
- Set permissions state when call is successful
* Added changelog
> Backport 1.9.x: Fix kv secret access bug

- api/auth/ldap/ldap.go
- api/auth/ldap/ldap_test.go
The merge-oss CI job in vault-enterprise is failing on the format check.
> Run 'make fmt'.

- website/content/docs/auth/okta.mdx
This PR makes the following fixes and improvements to the Okta auth method documentation.
- Explain the MFA push behavior with respect to login and token renewal
- Fixes [bold text](https://www.vaultproject.io/docs/auth/okta#via-the-cli-1) callouts that weren't properly rendered (use the boxed note format instead)
- Fixes an [ordered list](https://www.vaultproject.io/docs/auth/okta#via-the-cli-1) that wasn't incrementing properly
> auth/okta: documentation improvements

- website/content/docs/configuration/storage/dynamodb.mdx
Following my previous fix, those are some small formatting touch ups.
> Formatting touch ups on storage/dynamodb.mdx

- website/content/docs/enterprise/license/faq.mdx
Per Asana, the Vault License FAQ page was updated to include additional questions.
:mag: [Deploy Preview](https://vault-git-vault-faq-updates-hashicorp.vercel.app/docs/enterprise/license/faq)
> Vault documentation: Updated Licensing FAQ page

- helper/testhelpers/consul/consulhelper.go
Formatting fix from `make fmt`
> Remove extra blank line from consul-scrt-eng-upd

- website/content/docs/get-started/developer-qs.mdx
This is my suggested format edits for [PR 14038](https://github.com/hashicorp/vault/pull/14038) for easy copy-and-paste.
🔍 [Deployment preview](https://vault-git-dev-quickstart-suggestions-hashicorp.vercel.app/docs/get-started/developer-qs)
Based off of `vault-new-developer-guide` branch.
> Some format edits for PR14038

- website/package-lock.json
- website/package.json
Updates docs-page to fix `CodeTabs` language syncing within docs content.
> website: update docs-page, fix code tabs syncing

- api/sys_mounts.go
- command/secrets_move.go
- command/secrets_move_test.go
- helper/namespace/namespace.go
- http/sys_mount_test.go
- vault/auth.go
- vault/core.go
- vault/logical_system.go
- vault/logical_system_paths.go
- vault/logical_system_quotas.go
- vault/logical_system_test.go
- vault/mount.go
- vault/mount_test.go
- vault/quotas/quotas.go
- vault/quotas/quotas_rate_limit.go
- vault/quotas/quotas_test.go
- vault/quotas/quotas_util.go
oss changes from https://github.com/hashicorp/vault-enterprise/pull/2435
> oss changes for cross ns remount

- command/write.go
CLI prints a warning message indicating the login request needs to get validated
> Improve CLI command for login mfa

- website/content/docs/commands/write.mdx
As mentioned by Steve Clark. :-)
---
Thanks @stevendpclark!
> Document `vault write` JSON request parameters

- website/content/docs/auth/gcp.mdx
- website/content/docs/auth/jwt/oidc_providers.mdx
G Suite has been rebranded as Google Workspace. This PR addresses this rebrand in our docs.
> update G Suite to Google Workspace in docs

- ui/app/adapters/clients/monthly.js
- ui/app/components/calendar-widget.js
- ui/app/styles/components/calendar-widget.scss
- ui/app/templates/components/calendar-widget.hbs
- ui/tests/integration/components/calendar-widget-test.js
- ui/tests/pages/components/calendar-widget.js
This PR is the component test for the calendar widget. It also fixes an issue of display on wider screens.
> Calendar widget test and small styling fix on wide screens

- builtin/logical/mysql/backend_test.go
- builtin/logical/postgresql/secret_creds.go
- builtin/logical/transit/backend_test.go
- builtin/logical/transit/stepwise_test.go
- http/handler.go
- http/sys_mounts_test.go
- plugins/database/influxdb/connection_producer.go
- serviceregistration/consul/consul_service_registration_test.go
- vault/activity_log.go
- vault/activity_log_test.go
- vault/barrier_aes_gcm_test.go
- vault/request_handling.go
cleanup (bool) == true and (bool) == false checks (where it didn't seem to harm readability)
this is the nittiest of nits, so not bummed if we think this isn't useful.
> Cleanup bool checks

- command/auth_move.go
- command/auth_move_test.go
- command/commands.go
- command/secrets_move.go
- all changes from https://github.com/hashicorp/vault-enterprise/pull/2520/files ( it's an oss only pr ), plus removed the redundant `existing`s based on the last bit of feedback here. ( not on the ENT pr as that'll just be closed out anyways )
> remount cli changes

- vault/logical_system_test.go
missed a test in my previous merge https://github.com/hashicorp/vault/pull/14141/files, adding that in now
> add missed test

- ui/app/serializers/clients/activity.js
- ui/app/serializers/clients/monthly.js
- ui/mirage/handlers/clients.js
- ui/mirage/handlers/index.js
Per PR [here](https://github.com/hashicorp/vault/pull/14164/files).
Additionally, made another mirage handler that is the exact payload on the RFC. Tested against this and all worked as expected.
> Prefix mount to path

- .github/workflows/build.yml
- vault/core.go
- vault/request_handling.go
Fixes diffs in request_handling.go and core.go
> Fix ent diff check 2022/02/23

- changelog/14233.txt
- ui/app/templates/components/transit-key-actions.hbs
> Backport 1.9: UI Fix incorrect validity message on transit verify

- sdk/go.mod
- sdk/go.sum
Steps to generate:
`go mod tidy`
`go mod download`
> sdk changes for 1.10.0 release branch

- .release/ci.hcl
https://docs.google.com/document/d/1dUjhfqccvDnfnKkSPxjTu19zn9v4jSMT4_Lfh0mQ1yQ/edit?usp=sharing
> Adding promotion and post publish events to the ci.hcl.

- builtin/logical/pki/backend.go
- builtin/logical/pki/path_intermediate.go
- builtin/logical/pki/path_root.go
- go.mod
- go.sum
OSS bits for the PKI forwarding issue VAULT-5135.
> Force certain PKI operations to go to the Primary Performance cluster

- api/go.mod
- api/go.sum
- go.mod
1. go mod tidy / go mod download in sdk (no changes)
2. create sdk v0.4.1 tag
3. go get github.com/hashicorp/vault/sdk@v0.4.1 in api
4. go mod tidy/go mod download in api
5. go get github.com/hashicorp/vault/sdk@v0.4.1 in vault
6. go mod tidy/go mod download in vault.
> update sdk in api and vault

- api/renewer_test.go
Use a buffered channel to ensure that we don't miss a renewal notice
> Fix LifetimeWatcher flaky test

- website/content/api-docs/system/mounts.mdx
> English Grammar.

- builtin/logical/database/backend_test.go
- builtin/logical/database/mockv5.go
- builtin/logical/database/versioning_large_test.go
Add test cases to cover multiplexing plugin lifecycle.
> db plugin multiplexing: add test coverage

- vault/token_store.go
- vault/version_store.go
This should fix failures like this https://app.circleci.com/pipelines/github/hashicorp/vault-enterprise/11490/workflows/d2540ff5-7327-4253-808d-878bd2853483/jobs/362948/tests#failed-test-1 on enterprise
> Fix version check

- vault/token_store.go
- vault/version_store.go
Original PR https://github.com/hashicorp/vault/pull/14395
> Backport 1.10: Fix version check

- Makefile
- ui/scripts/enos-test-ember.js
- Updated the `enos-test-ember.js` script to accept additional parameters
- Added makefile target `test-ember-enos` and factored out a common `install-ui-dependencies` target.
> [QTI-188] Add test-ember-enos Makefile target, update enos-test-ember script to accept additional parameters

- command/kv_put.go
Accidentally forgot about some commented-out code in my last merge.
> Remove unneeded comments

- command/commands.go
- command/pki.go
- command/pki_add_intermediate.go
Command code to add intermediate CA
> Command code for adding pki-intermediate

- website/content/api-docs/system/mounts.mdx
- website/content/docs/commands/secrets/disable.mdx
this is a follow-up to a [recently raised issue](https://github.com/hashicorp/vault/issues/14351)
> add tip for how to force a secrets engine disable

- command/base.go
- command/login.go
- command/write.go
- vault/login_mfa.go
Adding MFA validation support to `vault login` command
Correctly report when a new TOTP code is available
> add MFA validation support to vault login command

- changelog/14487.txt
- sdk/helper/cidrutil/cidr.go
Note: even though it's a 1-liner, I made the IP address check a function for future readability. If you disagree with that choice I can change it.
This is also in service of https://github.com/hashicorp/vault/issues/14350
> only check Contains if IP address

- sdk/plugin/grpc_storage.go
- vault/ui.go
This is the port of the semgrep fixes here: https://github.com/hashicorp/vault-enterprise/pull/2637/files
> oss port: semgrep fixes

- website/content/docs/internals/security.mdx
Clarify that compromised clients are not part of vault's threat model
> Addition to security model

- changelog/14489.txt
- ui/app/adapters/secret-v2-version.js
- ui/app/routes/vault/cluster/secrets/backend/secret-edit.js
- ui/app/templates/components/secret-create-or-update.hbs
- ui/app/templates/components/secret-edit-toolbar.hbs
- ui/tests/acceptance/access/identity/_shared-alias-tests.js
- ui/tests/acceptance/secrets/backend/kv/secret-test.js
- ui/tests/pages/components/identity/edit-form.js
> Backport 1.9.5: UI/fix kv data cache (#14489)

- changelog/14493.txt
- ui/app/components/clients/horizontal-bar-chart.js
- ui/mirage/handlers/clients.js
- ui/tests/acceptance/auth-list-test.js
- ui/tests/acceptance/client-current-test.js
- ui/tests/acceptance/client-history-test.js
- ui/tests/helpers/clients.js
> Backport: UI/d3 DOM cleanup hover issue 

- changelog/mount-migration.txt
- vault/logical_system.go
- vault/logical_system_test.go
- website/content/docs/commands/auth/move.mdx
> Fixes from mount move testing (#14492)

- website/content/docs/secrets/key-management/awskms.mdx
Per [Asana](https://app.asana.com/0/563192436488770/1201966870147616), a note has been added to the AWS KMS doc page.
:mag: [Deploy Preview](https://vault-git-add-note-awskms-hashicorp.vercel.app/docs/secrets/key-management/awskms)
> Vault documentation: added new note for AWS KMS doc

- website/content/docs/auth/login-mfa/faq.mdx
- website/content/docs/auth/login-mfa/index.mdx
- website/content/docs/configuration/replication.mdx
- website/content/docs/enterprise/consistency.mdx
- website/content/docs/faq/ssct.mdx
- website/content/docs/upgrading/upgrade-to-1.10.x.mdx
- website/data/docs-nav-data.json
Per [Doc](https://docs.google.com/document/d/1KLORSahjB0kcxCAE_hjn1KQ1WsX1SE5xdrWuqmKRAk4/edit), a new server side consistent token faq page was created.
:mag: [Deploy Preview](https://vault-git-ssct-faq-vault-1-10-hashicorp.vercel.app/docs/faq/ssct)
> New server side consistent token faq for vault 1.10

- website/content/api-docs/system/remount.mdx
- website/content/docs/concepts/mount-migration.mdx
- website/data/docs-nav-data.json
> Add mount move concepts page, update api docs (#14544)

- changelog/14545.txt
- ui/app/components/auth-form.js
- ui/app/components/auth-jwt.js
- ui/app/services/auth.js
- ui/app/templates/components/auth-form.hbs
- ui/tests/acceptance/logout-auth-method-test.js
- ui/tests/helpers/oidc-window-stub.js
- ui/tests/integration/components/auth-jwt-test.js
> Backport of OIDC Logout Bug into release/1.9.x

- changelog/14545.txt
- ui/app/components/auth-form.js
- ui/app/components/auth-jwt.js
- ui/app/services/auth.js
- ui/app/templates/components/auth-form.hbs
- ui/tests/acceptance/logout-auth-method-test.js
- ui/tests/helpers/oidc-window-stub.js
- ui/tests/integration/components/auth-jwt-test.js
> Backport of OIDC Logout Bug into release/1.8.x

- website/redirects.next.js
Adds redirect from `/api*` -> `/api-docs*`.
> website: add api -> api-docs redirect

- website/content/docs/internals/plugins/plugin-architecture.mdx
🔍 [Deploy Preview](https://vault-git-minor-format-updates-hashicorp.vercel.app/docs/internals/plugins/plugin-architecture#troubleshooting)
Since we're updating the docs, I wanted to push minor format fixes for https://github.com/hashicorp/vault/pull/14509.
> Minor format updates

- ui/tests/integration/components/auth-jwt-test.js
Fix for test that seemed to get through some CircleCI runs from https://github.com/hashicorp/vault/pull/14545
> OIDC Test Fix

- changelog/14551.txt
- ui/app/adapters/secret-engine.js
- ui/app/components/mount-backend-form.js
- ui/app/templates/components/mount-backend-form.hbs
- ui/tests/acceptance/settings/mount-secret-backend-test.js
> Backport: UI/Wrong sentinel error message for auth methods #14551 

- website/content/docs/release-notes/1.10.0.mdx
- website/data/docs-nav-data.json
- website/redirects.next.js
> Vault documentation: fixed release note version for 1.10.0

- website/content/docs/concepts/client-count/faq.mdx
The client count faq was updated to address recent feedback from Darshana.
:mag: [Deploy Preview](https://vault-git-fix-client-count-faq-hashicorp.vercel.app/docs/concepts/client-count/faq)
> Vault documentation: addressed recent feedback for client count faq

- website/content/docs/deprecation/faq.mdx
:mag: [Deploy Preview](https://vault-git-fix-spelling-error-hashicorp.vercel.app/docs/deprecation/faq)
> Vault documentation: fixed spelling error in deprecation notice

- changelog/14752.txt
- command/server.go
* Vault-4279 reporting redundant/unused keys in config
* missing validate step
* CL
* Change the log level
> Vault-4279 reporting redundant/unused keys in config (#14752)

- changelog/14791.txt
- command/agent.go
- command/operator_raft_snapshot_save.go
- command/server.go
- physical/raft/raft.go
- physical/raft/snapshot.go
* Fixing excessive unix file permissions
* CL
* reduce the permission from 750 to 700
> Fixing excessive unix file permissions (#14791)

- website/content/docs/enterprise/managed-keys.mdx
- website/content/docs/secrets/pki.mdx
Add more color around managed keys in their concepts page, and create additional links between the various docs pages related to them.
> Docs improvements for Managed Keys

- website/content/api-docs/secret/identity/mfa/duo.mdx
- website/content/api-docs/secret/identity/mfa/okta.mdx
- website/content/api-docs/secret/identity/mfa/pingid.mdx
We removed this from the code but failed to update the docs.
> remove mount_accessor from the docs

- website/content/docs/get-started/developer-qs.mdx
Added link to [hello-vault Java / Spring Boot](https://github.com/hashicorp/hello-vault-spring) sample app repo in developer quick start.
> docs: added hello-vault-spring repo link to developer-qs.mdx.

- ui/package.json
- ui/yarn.lock
No idea, but now on a different PR, the tests past.
> flight-icons

- sdk/framework/backend_test.go
> Run `make fmt`

- changelog/15009.txt
- vault/request_handling.go
* forwarding requests subjected to Login MFA to the active node
* CL, and making fmt happy
> forwarding requests subjected to Login MFA to the active node (#15009)

- website/content/docs/agent/autoauth/methods/approle.mdx
Also, a test of the updated docs backport action.
> Fix docs typo

- command/debug.go
- helper/osutil/fileinfo_unix.go
- helper/osutil/fileinfo_windows.go
backporting vault debug changes from main
> Fix vault debug for windows 1.9.x

- .circleci/config.yml
- .circleci/config/commands/go_test.yml
- .circleci/config/executors/@executors.yml
- .github/workflows/build.yml
- Makefile
- README.md
- changelog/15043.txt
- scripts/docker/Dockerfile
- scripts/docker/Dockerfile.ui
> Update to Go 1.17.9

- command/debug.go
- command/server_test.go
- helper/osutil/fileinfo_unix.go
- helper/osutil/fileinfo_windows.go
Back-porting windows debug changes from main
> Fix vault debug windows1.10.x

- changelog/15058.txt
- ui/README.md
- ui/lib/core/addon/components/search-select.js
> Backport 1.8.10: UI fix blank selection on search select field (#15058)

- changelog/15058.txt
- ui/README.md
- ui/lib/core/addon/components/search-select.js
> Backport 1.9.5: UI fix blank selection on search select field (#15058)

- .circleci/config.yml
- .circleci/config/commands/go_test.yml
- .circleci/config/executors/@executors.yml
- .github/workflows/build.yml
- Makefile
- README.md
- changelog/go-ver-1810.txt
- scripts/docker/Dockerfile
- scripts/docker/Dockerfile.ui
> Update Go version to 1.16.15

- ui/app/components/clients/current.js
- ui/app/components/clients/history.js
- ui/app/components/clients/line-chart.js
- ui/app/templates/components/clients/current.hbs
- ui/app/templates/components/clients/history.hbs
- ui/mirage/handlers/clients.js
> Refactor to account for chart indicator

- go.mod
Imports SDK version bump from #15137
> Import SDK for 1.10.2 version

- website/content/docs/internals/telemetry.mdx
CI is seemingly stuck for https://github.com/hashicorp/vault/pull/15193. Cherry-picking the commit to ensure credit to the original author is retained.
> Fix sentence under Integrated Storage (Raft) Autopilot docs

- .circleci/config.yml
- .circleci/config/commands/setup-go.yml
- .circleci/config/executors/@executors.yml
- .circleci/config/jobs/pre-flight-checks.yml
Addresses https://hashicorp.atlassian.net/browse/VAULT-5370
Update circleci jobs using Ubuntu 14.04/16.04 as stated in CircleCI post [here](https://circleci.com/blog/ubuntu-14-16-image-deprecation/?mkt_tok=NDg1LVpNSC02MjYAAAGDLWMxR7BjchCqBFmLcj0YNCo6xEPnR5QCU4QWXC4SEf1-8i0oDF4e_BhNQkVC9V6BiHzKwMXNTz14QrTlPUqjFJVCByEpp4bJXNzOfSnqlmLO4w)
> Upgrade CircleCI machine image

- .release/ci.hcl
Adding release metadata config key in `ci.hcl` for Release API
> [RelAPI Onboarding] Add release metadata config key

- changelog/15277.txt
> PKI Pod rotation Add Base Changelog

- ui/app/serializers/clients/version-history.js
- ui/mirage/handlers/clients.js
- ui/tests/acceptance/client-history-test.js
>  Backport 1.10.x: UI/Fix version-history serializer and update mirage to reflect real API #15362

- changelog/14899.txt
Adds bold face and more in-depth description for -output-policy change.
> Fix changelog formatting for feature

- website/content/docs/platform/k8s/injector/annotations.mdx
https://github.com/hashicorp/vault-k8s/blob/main/CHANGELOG.md#0160-may-11-2022
> docs: update for vault-k8s 0.16.0

- website/content/api-docs/system/monitor.mdx
Updated Curl command code block to ensure the URL is escaped properly
> docs: updated monitor doc

- website/content/docs/plugins/plugin-development.mdx
Adding a quick note about concurrency with plugin development
> Add note about concurrency to plugin dev docs

- ui/app/adapters/mfa-method.js
- ui/app/components/mfa/method-form.js
- ui/app/models/mfa-method.js
- ui/app/router.js
- ui/app/routes/vault/cluster/access/mfa/methods/method/edit.js
- ui/app/templates/components/mfa/method-form.hbs
- ui/app/templates/vault/cluster/access/mfa/methods/index.hbs
- ui/app/templates/vault/cluster/access/mfa/methods/method/edit.hbs
- ui/app/templates/vault/cluster/access/mfa/methods/method/index.hbs
- Updated model for form attributes
- Form for editing, creating mfa methods
> MFA method form

- changelog/15248.txt
- vault/external_tests/mfa/login_mfa_test.go
- vault/identity_store.go
- vault/login_mfa.go
* Globally scoped MFA method Get/List endpoints
Original PR: https://github.com/hashicorp/vault/pull/15248
> Globally scoped MFA method Get/List endpoints (#15248)

- vault/external_tests/identity/login_mfa_duo_test.go
- vault/external_tests/identity/login_mfa_okta_test.go
- vault/identity_store.go
- vault/login_mfa.go
- website/content/api-docs/secret/identity/mfa/duo.mdx
- website/content/api-docs/secret/identity/mfa/okta.mdx
- website/content/api-docs/secret/identity/mfa/pingid.mdx
- website/content/docs/auth/login-mfa/faq.mdx
Addresses https://hashicorp.atlassian.net/browse/VAULT-6123
> Username format login mfa

- ui/app/controllers/vault/cluster/access/mfa/methods/create.js
- ui/app/styles/core/helpers.scss
- ui/app/templates/components/radio-card.hbs
- ui/app/templates/vault/cluster/access/mfa/methods/create.hbs
Adds mfa method create route and type selection for guided setup.
> MFA Guided Setup Route

- website/content/api-docs/secret/identity/mfa/duo.mdx
- website/content/api-docs/secret/identity/mfa/okta.mdx
- website/content/api-docs/secret/identity/mfa/pingid.mdx
- website/content/docs/auth/login-mfa/faq.mdx
This PR is just some docs fixed for 1.10.x related to this original [PR](https://github.com/hashicorp/vault/pull/15363) on main.
> docs fix for login MFA changing username_template to username_format

- website/content/docs/configuration/service-registration/kubernetes.mdx
- website/content/docs/platform/k8s/helm/configuration.mdx
- website/content/docs/platform/k8s/helm/enterprise.mdx
- website/content/docs/platform/k8s/helm/examples/enterprise-dr-with-raft.mdx
- website/content/docs/platform/k8s/helm/examples/enterprise-perf-with-raft.mdx
- website/content/docs/platform/k8s/helm/examples/enterprise-with-raft.mdx
- website/content/docs/platform/k8s/helm/run.mdx
- website/content/partials/helm/install.mdx
- website/content/partials/helm/repo.mdx
Corresponds to https://github.com/hashicorp/vault-helm/releases/tag/v0.20.0.
> Update documentation for vault-helm v0.20.0 release

- audit/format.go
- changelog/15487.txt
- sdk/logical/auth.go
- vault/core_metrics_test.go
- vault/identity_store.go
- vault/identity_store_test.go
- vault/request_handling.go
- vault/request_handling_util.go
- vault/token_store.go
oss changes for https://github.com/hashicorp/vault-enterprise/pull/2815/files
> oss changes

- ui/app/components/mfa-login-enforcement-form.js
- ui/app/controllers/vault/cluster/access/mfa/methods/create.js
- ui/app/models/mfa-login-enforcement.js
- ui/app/routes/vault/cluster/access/mfa/methods/create.js
- ui/app/templates/components/mfa-login-enforcement-form.hbs
- ui/app/templates/components/radio-card.hbs
- ui/app/templates/vault/cluster/access/mfa/index.hbs
- ui/app/templates/vault/cluster/access/mfa/methods/create.hbs
- adds validations to mfa-login-enforcement model
- updates form to display validations messages
- performs validations check in form component and in guided setup workflow (mfa create route)
> MFA Login Enforcement Validations

- website/content/docs/audit/socket.mdx
The automated [backport PR](https://github.com/hashicorp/vault/pull/15496) had some issue rebasing.  
This PR manually cherry pick [PR 15459](https://github.com/hashicorp/vault/pull/15459) and resolve the merge conflict.
> Update socket device doc - Resolve the merge conflict

- website/content/docs/secrets/pki/considerations.mdx
First pass at some additional CA best practices.
Still missing:
> Add more CA usage best practices

- ui/app/components/mfa/method-form.js
- ui/app/controllers/vault/cluster/access/mfa/methods/create.js
- ui/app/models/mfa-method.js
- ui/app/templates/components/mfa/method-form.hbs
- ui/app/templates/vault/cluster/access/mfa/methods/create.hbs
> Added validations for mfa method model

- website/content/docs/platform/k8s/helm/configuration.mdx
> Fix typo in documentation

- website/content/docs/auth/login-mfa/index.mdx
simple typo for tense. changing the word embeds to embedded
> typo: embeds -> embedded

- website/content/api-docs/secret/pki.mdx
- website/content/api-docs/secret/ssh.mdx
- website/content/api-docs/secret/transit.mdx
- website/content/api-docs/system/tools.mdx
- website/content/docs/enterprise/fips/fips1402.mdx
- website/content/docs/enterprise/fips/index.mdx
- website/content/docs/enterprise/fips/sealwrap.mdx
- website/content/docs/enterprise/sealwrap.mdx
- website/content/docs/secrets/transit.mdx
- website/data/docs-nav-data.json
Due to various conflicts (especially in PKI related docs), this is a manual backport, under the assumption #15554 will land.
> Backport FIPS 140-2 Documentation

- website/content/docs/enterprise/fips/fips1402.mdx
> Link FIPS binary sources from the FIPS docs

- vault/external_tests/raft/raft_autopilot_test.go
> Update autopilot update interval

- website/content/api-docs/auth/kubernetes.mdx
- website/content/api-docs/secret/kubernetes.mdx
- website/data/api-docs-nav-data.json
- website/data/docs-nav-data.json
Adds API docs for the new Kubernetes secrets engine.
> Add API docs for Kubernetes secrets engine

- go.mod
- go.sum
Upgrade vault-plugin-secrets-ad to v0.13.0
> fix: upgrade vault-plugin-secrets-ad to v0.13.0

- go.sum
PR to clean up go.sum on some old plugins via `go mod tidy`.
> dep: go mod tidy

- website/content/docs/platform/k8s/helm/configuration.mdx
- website/content/docs/platform/k8s/helm/run.mdx
- website/content/docs/platform/k8s/injector/annotations.mdx
- website/content/partials/helm/install.mdx
- website/content/partials/helm/repo.mdx
Updating the doc for the latest releases of Vault K8s and Vault Helm:
https://github.com/hashicorp/vault-helm/blob/main/CHANGELOG.md#0201-may-25th-2022
https://github.com/hashicorp/vault-k8s/blob/main/CHANGELOG.md#0161-may-25-2022
> docs/k8s: update for latest helm release 0.20.1

- website/content/docs/configuration/index.mdx
- website/content/docs/plugins/plugin-architecture.mdx
- website/content/partials/plugin-file-permissions-check.mdx
https://hashicorp.atlassian.net/browse/VAULT-6037
> File permissions check documentation changes

- website/content/docs/secrets/kubernetes.mdx
> Fix K8s secrets docs typo

- ui/app/components/splash-page.js
- ui/app/templates/components/splash-page.hbs
Some clean up from the MFA project in 1.11. I had touched the SplashPage component and made a note to come back and glimmerize it when I had time.
Simple component, but I double checked all the properties where coming in as expected.
> Glimmerize SplashPage component

- website/content/api-docs/secret/azure.mdx
Per [Asana](https://app.asana.com/0/563192436488770/1202329869531924/f), the payload code sample was updated for the Azure Secrets Engine (API) document.
:mag: [Deploy Preview](https://vault-git-docs-update-code-snippet-hashicorp.vercel.app/api-docs/secret/azure#sample-payload-1)
> Vault documentation: update sample code for Azure API

- changelog/15769.txt
- ui/app/lib/local-storage.js
- ui/app/lib/token-storage.js
- ui/tests/acceptance/enterprise-control-groups-test.js
- ui/tests/acceptance/redirect-to-test.js
> Revert UI: replace localStorage with sessionStorage (#15769)

- .circleci/config.yml
- .circleci/config/commands/go_test.yml
- .circleci/config/executors/@executors.yml
- .github/workflows/build.yml
- Makefile
- README.md
- changelog/15818.txt
- scripts/docker/Dockerfile
- scripts/docker/Dockerfile.ui
See https://go.dev/doc/devel/release#go1.17.minor for release notes
> Update Go to 1.17.11

- ui/app/components/clients/horizontal-bar-chart.js
- ui/app/components/clients/line-chart.js
- ui/app/components/clients/monthly-usage.js
- ui/app/components/clients/running-total.js
- ui/app/components/clients/vertical-bar-chart.js
- ui/app/styles/core/charts.scss
- ui/app/templates/components/clients/attribution.hbs
- ui/app/templates/components/clients/history.hbs
- ui/app/templates/components/clients/horizontal-bar-chart.hbs
- ui/app/templates/components/clients/line-chart.hbs
- ui/app/templates/components/clients/monthly-usage.hbs
- ui/app/templates/components/clients/running-total.hbs
- ui/app/templates/components/clients/vertical-bar-chart.hbs
- ui/app/utils/chart-helpers.js
- ui/lib/core/addon/templates/components/stat-text.hbs
- ui/lib/core/addon/utils/date-formatters.js
- ui/mirage/handlers/clients.js
- ui/tests/acceptance/client-history-test.js
- ui/tests/helpers/clients.js
- ui/tests/integration/components/clients/line-chart-test.js
- ui/tests/integration/components/clients/monthly-usage-test.js
- ui/tests/integration/components/clients/running-total-test.js
- ui/tests/integration/components/clients/vertical-bar-chart-test.js
- ui/tests/unit/utils/chart-helpers-test.js
> Backport: UI/1.11 client count component tests #15748

- website/content/docs/secrets/ssh/signed-ssh-certificates.mdx
> Update documentation to reduce confusion about default_extensions.

- website/data/api-docs-nav-data.json
In dev portal the sidebar overview is automatically generated. This PR removes a duplicate item.
> chore: remove duplicate overview item

- website/content/docs/secrets/kmip.mdx
Update KMIP documentation:
Add new subsection describing Vault's KMIP conformance.
Update the list of supported operations.
> Update KMIP documentation to reflect Vault 1.11 changes.

- website/content/api-docs/secret/kv/kv-v2.mdx
- website/content/docs/commands/kv/put.mdx
- website/content/docs/secrets/kv/kv-v2.mdx
https://github.com/hashicorp/vault/issues/15676
> Kv cas parameter documentation

- go.mod
Ran `go get github.com/hashicorp/vault/sdk@release/1.9.x` and `go mod tidy`
> Import SDK 1.9.8

- website/content/api-docs/secret/pki.mdx
> Clarify permitted_dns_domains are Name Constraints

- changelog/16000.txt
- vault/activity_log.go
- vault/logical_system_activity.go
RFC: https://docs.google.com/document/d/1HC0pv7zX4KwkoSvaN946yMHiCGvb9AUA67KlOnDcfrw/edit
Jira : https://hashicorp.atlassian.net/browse/VAULT-6045
Limits the response data of activity log (client count api)
Approved ent pr : https://github.com/hashicorp/vault-enterprise/pull/2973
> Activity Log Filtering Limit Parameter

- website/content/docs/enterprise/fips/fips1402.mdx
> Document limitations in FIPS 140-2 migrations

- changelog/15989.txt
- vault/logical_system_quotas.go
- vault/quotas/quotas.go
- vault/quotas/quotas_rate_limit.go
- vault/quotas/quotas_rate_limit_test.go
- vault/quotas/quotas_test.go
The OSS PR containing the OSS changes for path suffix support for rate limit quotas.
> (OSS) Path Suffix Support for Rate Limit Quotas

- website/content/api-docs/auth/okta.mdx
Small PR to fix a typo in the okta verify sample command.
> docs: Fix sample request on okta verify nonce

- ui/app/router.js
- ui/app/routes/vault/cluster/access/oidc/applications/application.js
- ui/app/routes/vault/cluster/access/oidc/applications/application/edit.js
- ui/app/routes/vault/cluster/access/oidc/applications/create.js
- ui/app/routes/vault/cluster/access/oidc/applications/index.js
- ui/app/routes/vault/cluster/access/oidc/assignments/assignment.js
- ui/app/routes/vault/cluster/access/oidc/assignments/assignment/edit.js
- ui/app/routes/vault/cluster/access/oidc/assignments/create.js
- ui/app/routes/vault/cluster/access/oidc/assignments/index.js
- ui/app/routes/vault/cluster/access/oidc/clients/client.js
- ui/app/routes/vault/cluster/access/oidc/clients/client/edit.js
- ui/app/routes/vault/cluster/access/oidc/clients/create.js
- ui/app/routes/vault/cluster/access/oidc/clients/index.js
- ui/app/routes/vault/cluster/access/oidc/index.js
- ui/app/routes/vault/cluster/access/oidc/keys/create.js
- ui/app/routes/vault/cluster/access/oidc/keys/index.js
- ui/app/routes/vault/cluster/access/oidc/keys/key.js
- ui/app/routes/vault/cluster/access/oidc/keys/key/edit.js
- ui/app/routes/vault/cluster/access/oidc/providers/create.js
- ui/app/routes/vault/cluster/access/oidc/providers/index.js
- ui/app/routes/vault/cluster/access/oidc/providers/provider.js
- ui/app/routes/vault/cluster/access/oidc/providers/provider/edit.js
- ui/app/routes/vault/cluster/access/oidc/scopes/create.js
- ui/app/routes/vault/cluster/access/oidc/scopes/index.js
- ui/app/routes/vault/cluster/access/oidc/scopes/scope.js
- ui/app/routes/vault/cluster/access/oidc/scopes/scope/edit.js
Adds routing for OIDC configuration and nested crud routes for applications, keys, assignments, providers and scopes. Since controllers are optional they may be added later on an as needed basis.
> OIDC Config Routing

- website/content/api-docs/system/lease-count-quotas.mdx
Closes https://github.com/hashicorp/vault/issues/15661
> Document `LIST sys/quotas/lease-count`

- builtin/logical/pki/crl_test.go
- builtin/logical/pki/crl_util.go
PKI in Vault 1.11.0-rc1 contained a bug wherein, for an intermediate mount with an unkeyed issuer (such as a root), revocation would fail. This is because, at the time of revocation, we'd attempt to parse the issuers' bundles (into full signing form), just to extract the serial number. 
This ultimately lead us to surface an error like:
> URL: PUT http://127.0.0.1:8200/v1/pki_int/revoke
> * could not fetch the CA certificate for issuer id 156e1b99-4f04-5b5e-0036-cc0422c0c0d3: unable to fetch corresponding key for issuer 156e1b99-4f04-5b5e-0036-cc0422c0c0d3; unable to use this issuer for signing    
where this issuer ID corresponds to the root issuer in the intermediate mount.
We took this approach because, while the `issuerEntry` contains the serial number, on performance secondary …
> Fix leaf revocation under intermediate CAs 

- website/content/docs/secrets/databases/index.mdx
Updating learn links which were using the old URL structure.
> website: Update old learn links to redirect locations

- api/client.go
- changelog/15986.txt
- command/agent.go
- command/agent/config/config.go
- command/agent/config/config_test.go
- command/agent/config/test-fixtures/bad-config-disable-idle-connections.hcl
- command/agent/config/test-fixtures/config-disable-idle-connections-all.hcl
- command/agent/config/test-fixtures/config-disable-idle-connections-auto-auth.hcl
- command/agent/config/test-fixtures/config-disable-idle-connections-caching.hcl
- command/agent/config/test-fixtures/config-disable-idle-connections-empty.hcl
- command/agent/config/test-fixtures/config-disable-idle-connections-templating.hcl
- command/agent/template/template.go
- website/content/docs/agent/index.mdx
* agent: add disable_keep_alives configurable
* Add empty test
* Add website doc
* Change to disable_idle_connections
* Update tests and doc
* Add note about env
* Changelog
* Change to slice
* Remove unused disable keep alive methods
* Add invalid value test
> Backport: agent: add disable_idle_connections configurable (#15986)

- changelog/16063.txt
- website/content/docs/enterprise/replication.mdx
Currently only mentions Consul in the initial paragraph
> website: Update replication docs to mention Integrated Storage

- CHANGELOG.md
Replace consult-template with consul-template.
> changelog: fix spelling mistake

- Dockerfile
Just updating the base for the UBI images.
> dockerfile: use ubi-minimal:8.6

- website/content/docs/release-notes/1.11.0.mdx
> fix typo in release notes

- website/content/docs/platform/aws/lambda-extension.mdx
Fixes https://github.com/hashicorp/vault-lambda-extension/issues/76
> Docs: Fix typo for Lambda extension env var config

- ui/app/components/auth-form.js
- ui/app/services/auth.js
Implemented polling function to poll for correct answer in Okta number challenge every 1s. We keep polling for an answer until a non-404 response is given. Temporarily printing out the correct answer as the display screens are not implemented yet (will be done after this task).
> Create polling function for correct answer in okta number challenge

- ui/app/styles/components/radio-card.scss
Make the RadioCard component adjust size based on how many cards, and the width of the screen
> UI/RadioCard Adjust Sizes

- ui/app/components/mfa/mfa-login-enforcement-form.js
- ui/lib/core/addon/components/search-select.js
- ui/lib/core/addon/utils/search-select-has-many.js
In the OIDC config, many of the forms present an opportunity to leverage a `hasMany` relationship between models giving us a tidy way to handle the interrelated attrs.
examples of future use:
- Form to create a client (application) and search select for assignments 
- Form to create a `key` and search select for clients (applications)
- Form to create a `provider` and search select for clients and scopes 
- Form to create an 'assignment' and search select entities and groups
> UI/util for updating a hasMany relationship via SearchSelect

- website/content/api-docs/system/internal-counters.mdx
JIRA: https://hashicorp.atlassian.net/browse/VAULT-6045
> Documentation changes for limit parameter

- changelog/16162.txt
- vault/activity_log.go
- vault/activity_log_util_common.go
Approved Ent PR: https://github.com/hashicorp/vault-enterprise/pull/2994
> activity log refactoring port

- ui/app/components/oidc/scope-form.js
- ui/app/controllers/vault/cluster/access/oidc/scopes/scope/details.js
- ui/app/models/oidc/scope.js
- ui/app/templates/components/oidc/scope-form.hbs
- ui/app/templates/vault/cluster/access/oidc/scopes/scope/details.hbs
- ui/lib/core/addon/components/form-field.hbs
- adds OIDC scope details view 
- updates json editor format for scope template
- adds copy button for example template
> OIDC Scope Details View

- ui/app/routes/vault/cluster/access/oidc/scopes/index.js
- ui/app/templates/components/oidc/scope-form.hbs
- ui/app/templates/vault/cluster/access/oidc/scopes/index.hbs
- ui/app/templates/vault/cluster/access/oidc/scopes/scope/details.hbs
- adds oidc scopes list view
- adds missing nav for create and edit views
- updates description copy in scopes form
- adds capabilities checks for actions
> OIDC Scopes List View

- website/content/docs/get-started/developer-qs.mdx
Adding curl and bash commands for authentication, writing and reading a secret.
> Add curl commands to Dev Quickstart guide

- command/login.go
- website/content/docs/commands/login.mdx
Resolving conflicts via command line
https://github.com/hashicorp/vault/pull/10280
> Minor grammar correction in help for login command

- website/content/docs/concepts/seal.mdx
Update the reference to `master key` to say `root key`. ([GH-13324](https://github.com/hashicorp/vault/pull/13324))
> Update 'master key' -> 'root key'

- ui/app/components/auth-form.js
- ui/app/components/okta-number-challenge.js
- ui/app/templates/components/auth-form.hbs
- ui/app/templates/components/okta-number-challenge.hbs
- ui/tests/integration/components/okta-number-challenge-test.js
Added error screens to handle error state for Okta Number Challenge and created test for it
> Implement error handling and screens for okta number challenge

- website/content/docs/enterprise/fips/fips1402.mdx
> Back out panic message, add new warning to FIPS docs

- website/content/docs/concepts/client-count/faq.mdx
- website/content/docs/secrets/pki/considerations.mdx
> Update localhost:3000 links to be correct

- website/content/docs/commands/operator/migrate.mdx
- website/content/docs/configuration/index.mdx
- website/content/docs/configuration/storage/consul.mdx
- website/content/docs/platform/k8s/helm/configuration.mdx
- website/content/docs/platform/k8s/helm/run.mdx
This PR "Duplicates" https://github.com/hashicorp/vault/pull/10678/commits ; an old community PR.
That contributor has signed the CLA.  Unfortunately I'm not able to fix the merge conflict on that branch, so it's fixed here.
That PR is still relevant, we are still throwing a warning when someone follows the procedure laid out in the docs ( https://github.com/hashicorp/vault/blob/967b2987e5a17a82f9b46b6d0b4f93b42fd550cd/physical/consul/consul.go#L70 ).
> Cherry-Picked Community PR: append slash to consul path in doc

- command/agent/config/config_test.go
Update the test to fix a copy-paste error.
> Fix agent use_auto_auth_token force test

- website/content/docs/plugins/plugin-portal.mdx
Repository: https://github.com/manhtukhang/vault-plugin-harbor
Raised issue: #16319
also updated docs (link to the page for PR)
> Add Harbor Robot Account secrets plugin

- website/content/docs/platform/mssql/changelog.mdx
- website/data/docs-nav-data.json
Now that we have released 0.2.0, we need to publish the changelog notes somewhere. I've taken inspiration from the Sentinel changelog here: https://docs.hashicorp.com/sentinel/changelog
> Docs: Add release notes for MSSQL TDE

- changelog/16240.txt
- website/content/api-docs/secret/kubernetes.mdx
- website/content/docs/secrets/kubernetes.mdx
See https://github.com/hashicorp/vault-plugin-secrets-kubernetes/pull/10
> [Kubernetes Secret Engine]: Role namespace configuration possible via LabelSelector

- website/content/api-docs/system/storage/raftautosnapshots.mdx
Add when cannot use the combination of parameters.
> Information about aws_s3_server_side_encryption

- website/content/docs/enterprise/mfa/index.mdx
Per [Asana](https://app.asana.com/0/563192436488770/1202602158483584/f), a note was modified to provide clarity about the step-up MFA feature for enterprise users.
:mag: [Deploy Preview](https://vault-git-docs-update-mfa-note-hashicorp.vercel.app/docs/enterprise/mfa)
> Vault documentation: updated note about MFA feature

- api/plugin_helpers.go
- builtin/plugin/backend.go
- builtin/plugin/backend_lazyLoad_test.go
- changelog/15671.txt
- sdk/helper/pluginutil/env.go
- sdk/helper/pluginutil/multiplexing.go
- sdk/helper/pluginutil/run_config.go
- sdk/helper/pluginutil/run_config_test.go
- sdk/helper/pluginutil/runner.go
- sdk/plugin/backend.go
- sdk/plugin/plugin.go
- sdk/plugin/serve.go
- vault/logical_system_integ_test.go
- vault/plugin_catalog.go
This reverts commit 39bcd5c71529f5f4eb61aae68b17d06d192ea55f.
> Revert "AutoMTLS for secrets/auth plugins (#15671)"

- website/content/docs/secrets/databases/mssql.mdx
Can't believe this went unnoticed for 5 years :)
> Missing word

- website/content/api-docs/index.mdx
This may be a related issue: https://github.com/hashicorp/vault/issues/7161
> Add documentation  for KV Engine V2 API requests

- website/content/api-docs/secret/transform.mdx
- website/content/docs/secrets/transform/tokenization.mdx
Documents `auto_rotate` fields of Transform tokenization key config endpoints.
> Transform tokenization key auto-rotate docs

- ui/app/components/oidc/assignment-form.js
- ui/app/templates/components/oidc/assignment-form.hbs
- ui/tests/integration/components/oidc/assignment-form-test.js
This PR adds the updated/edit view for OIDC Assignments and adds tests coverage.
https://user-images.githubusercontent.com/6618863/180558002-79b40bed-8ec6-4e4a-807f-54553c53d962.mov
> Assignments Update/Edit View 

- website/content/docs/concepts/integrated-storage/autopilot.mdx
- website/content/docs/upgrading/upgrade-to-1.11.x.mdx
🎟️ [Asana](https://app.asana.com/0/563192436488770/1202657015050715/f)
This PR:
- Updates the **Upgrade Guide** for Vault 1.11 to mention the use of IS Automated Upgrade --> 🔍 [Deploy Preview](https://vault-git-docs-update-upgrade-guide-hashicorp.vercel.app/docs/upgrading/upgrade-to-1.11.x)
- Updates the **Integrated Storage Autopilot** doc with additional tutorials --> 🔍 [Deploy Preview](https://vault-git-docs-update-upgrade-guide-hashicorp.vercel.app/docs/concepts/integrated-storage/autopilot#tutorial)
> Add a note referring to automated upgrade

- website/content/api-docs/system/init.mdx
- website/content/docs/commands/operator/init.mdx
https://github.com/hashicorp/vault/pull/16379
Will merge this after https://github.com/hashicorp/vault/pull/16379
> Minor documentation changes for vault operator init

- ui/app/utils/validators.js
- ui/lib/core/addon/components/search-select-with-modal.hbs
- ui/lib/core/addon/components/search-select-with-modal.js
- ui/lib/core/app/components/search-select-with-modal.js
- ui/tests/integration/components/search-select-with-modal-test.js
- ui/tests/unit/utils/validators-test.js
Creates search select with modal component so that a user can create a new model inline, from a form that pops up into a modal
> UI/vault 7196/search select with modal

- changelog/16466.txt
- ui/app/components/auth-form.js
- ui/tests/acceptance/jwt-auth-method-test.js
> Backport UI: Fix JWT Auth login into 1.10.6

- website/content/docs/platform/k8s/injector/annotations.mdx
https://github.com/hashicorp/vault-k8s/releases/tag/v0.17.0
> docs/vault-k8s: updated for v0.17.0 release

- website/content/docs/use-cases.mdx
This PR suggest some edits on the proposed Vault use cases doc ([PR 16446](https://github.com/hashicorp/vault/pull/16446)).
🔍 [Deploy Preview](https://vault-git-vault-use-cases-hashicorp.vercel.app/docs/use-cases)
The **Secrets Management** section breaks the style of having the **Resources** sub-section, so I don't know how you feel about that. Feel free to make further edits. This PR is my _suggestions_ and _ideas_ for possible edits.
> Suggested edits on Vault use cases

- website/content/docs/enterprise/entropy-augmentation.mdx
- website/content/docs/enterprise/sealwrap.mdx
This doc's KMIP using EA and adding a similar section to the Seal Wrap docs. This list is not comprehensive but can be updated as people ask about _what_ is seal wrapped.
> Add KMIP CSPs + initial Seal Wrap list

- website/content/api-docs/secret/identity/mfa/totp.mdx
> Fix last sample request

- vault/expiration.go
OSS Side of changes. Find the Ent PR here: https://github.com/hashicorp/vault-enterprise/pull/3075
> VAULT-7065 move lease-quota updating to process restore

- website/content/docs/install.mdx
- website/content/docs/internals/high-availability.mdx
This is the second batch of changes as part of the efforts to clean up content for Vault documentation ([Asana](https://app.asana.com/0/563192436488770/1202671678968862/f))
The following files were edited and updated:
- Installing Vault :mag: [Deploy Preview](https://vault-git-docs-content-update-batch2-hashicorp.vercel.app/docs/install)
- High Availability :mag: [Deploy Preview](https://vault-git-docs-content-update-batch2-hashicorp.vercel.app/docs/internals/high-availability)
> Vault documentation: updated install and ha files

- website/content/api-docs/system/lease-count-quotas.mdx
- website/content/api-docs/system/rate-limit-quotas.mdx
- website/content/docs/concepts/resource-quotas.mdx
- website/content/docs/enterprise/lease-count-quotas.mdx
The docs updates required to go with VAULT-1817. Also included some other general improvements to the quota docs.
> VAULT-6615 Update docs for 1.12 quota changes

- website/content/docs/upgrading/upgrade-to-1.10.x.mdx
- website/content/partials/raft-retry-join-failure.mdx
* storage/raft: Add known issue for retry_join
* storage/raft: Update known issues with issue reference
* docs: Add return between includes
> Docs/vault 7338 retry join known issue (#16540)

- http/logical_test.go
- Based on group test fixing session from July 29, 2022
- Leverage the RetryUntil utility function to catch and re-attempt a kv store creation if the test receives an error about upgrading 
- Update the expected audit log entries accordingly along with the captured failures if any
- Fix up a copy/paste error within the test error message if the remote_address field is not of the expected type.
Reproduced the error by adding a `time.Sleep(1*time.Second)` within the [KV store's upgrade routine around line 214](https://github.com/hashicorp/vault-plugin-secrets-kv/blob/main/upgrade.go#L214).
This attempts to address the following error we occasionally see within test runs
```
2022-07-18T20:33:59.088Z [INFO]  core0.secrets.kv.kv_c345d978: collecting keys to upgrade
logical_test.go:560: write …
```
> Address test flakiness in TestLogical_AuditPort

- website/content/docs/enterprise/managed-keys.mdx
> Fix typo in managed-keys.mdx

- website/content/docs/internals/architecture.mdx
- website/content/docs/internals/index.mdx
Per [Asana](https://app.asana.com/0/563192436488770/1202671678968862/f), this is batch3 of a series of doc PRs to clean up existing Vault content.
This PR focuses on the following doc pages:
- Internals :mag: [Deploy Preview](https://vault-git-docs-update-architecture-hashicorp.vercel.app/docs/internals)
- Architecture :mag: [Deploy Preview](https://vault-git-docs-update-architecture-hashicorp.vercel.app/docs/internals/architecture)
> vault documentation: updated architecture doc page

- website/content/docs/internals/architecture.mdx
- website/content/docs/internals/index.mdx
This PR backports #16569 into release/1.11.x
> vault documentation: updated architecture doc page (#16569)

- changelog/16594.txt
- go.mod
- go.sum
- website/content/api-docs/auth/kerberos.mdx
- website/content/docs/auth/kerberos.mdx
* auth/kerberos: add remove_instance_name config
* Update website
* Fix doc
* Fix doc
* changelog
> Backport: auth/kerberos: add remove_instance_name config (#16594)

- website/content/docs/release-notes/1.11.0.mdx
- website/content/docs/upgrading/upgrade-to-1.10.x.mdx
- website/content/docs/upgrading/upgrade-to-1.11.x.mdx
- website/content/docs/upgrading/upgrade-to-1.8.x.mdx
- website/content/partials/pgx-params.mdx
- website/content/partials/raft-panic-old-tls-key.mdx
- website/content/partials/raft-retry-join-failure.mdx
Also some heading size tidying.
Of the eco folks tagged, I'd really just like confirmation that this looks good from one of you.
> Adding PGX change to release & upgrade notes

- .github/workflows/oss.yml
This will help us triage open source issues into our various internal
project boards.
I tested this on a separate repo, and it seems to work.
> Add Open Source project workflow

- .github/workflows/oss.yml
This token has been validated to work with the projects API.
> Update project auto-triage to use new token

- ui/app/components/oidc/client-form.js
- ui/app/controllers/vault/cluster/access/oidc/clients/client.js
- ui/app/models/oidc/client.js
- ui/app/templates/components/oidc/client-form.hbs
- ui/app/templates/components/oidc/provider-list.hbs
- ui/app/templates/components/radio-card.hbs
- ui/app/templates/vault/cluster/access/oidc.hbs
- ui/app/templates/vault/cluster/access/oidc/clients/client.hbs
- ui/app/templates/vault/cluster/access/oidc/clients/client/details.hbs
- ui/app/templates/vault/cluster/access/oidc/clients/index.hbs
- ui/app/templates/vault/cluster/access/oidc/index.hbs
- ui/lib/core/addon/components/form-field.hbs
- ui/lib/core/addon/components/info-table-row.hbs
- ui/lib/core/addon/components/radio-button.hbs
- ui/lib/core/addon/templates/components/box-radio.hbs
- ui/mirage/handlers/oidc-config.js
- ui/tests/acceptance/oidc-config/clients-test.js
- ui/tests/helpers/oidc-config.js
- ui/tests/integration/components/oidc/assignment-form-test.js
- ui/tests/integration/components/oidc/client-form-test.js
Fixed branch of #16592 (see for any original discussion)
> UI/Client route acceptance tests - fixed branch

- website/content/docs/internals/integrated-storage.mdx
- website/content/docs/internals/security.mdx
Per [Asana](https://app.asana.com/0/563192436488770/1202671678968862/f), this is batch4 of a series of doc PRs to clean up existing Vault content.
This PR focuses on the following doc pages:
- Integrated Storage- :mag:[Deploy Preview](https://vault-git-docs-update-vault-docs-batch4-hashicorp.vercel.app/docs/internals/integrated-storage)
- Security Model- :mag:[Deploy Preview](https://vault-git-docs-update-vault-docs-batch4-hashicorp.vercel.app/docs/internals/security)
> vault documentation: doc cleanup effort-batch4

- vault/request_handling.go
Prior bugfix work:
https://github.com/hashicorp/vault/pull/16112/files
https://github.com/hashicorp/vault/pull/16270
> handle ssct errors in PopulateTokenEntry

- ui/app/templates/components/oidc/client-list.hbs
- ui/tests/acceptance/oidc-config/clients-test.js
Added client ID metadata to list view for clients
> metadata for client list view

- ui/lib/replication/addon/templates/components/replication-summary.hbs
See https://github.com/hashicorp/vault/issues/16604
> Removed the extra div around the radio button.

- website/content/docs/configuration/service-registration/kubernetes.mdx
- website/content/docs/platform/k8s/helm/configuration.mdx
- website/content/docs/platform/k8s/helm/enterprise.mdx
- website/content/docs/platform/k8s/helm/examples/development.mdx
- website/content/docs/platform/k8s/helm/examples/enterprise-dr-with-raft.mdx
- website/content/docs/platform/k8s/helm/examples/enterprise-perf-with-raft.mdx
- website/content/docs/platform/k8s/helm/examples/enterprise-with-raft.mdx
- website/content/docs/platform/k8s/helm/examples/external.mdx
- website/content/docs/platform/k8s/helm/examples/ha-with-consul.mdx
- website/content/docs/platform/k8s/helm/examples/ha-with-raft.mdx
- website/content/docs/platform/k8s/helm/examples/index.mdx
- website/content/docs/platform/k8s/helm/examples/injector-tls.mdx
- website/content/docs/platform/k8s/helm/examples/kubernetes-auth.mdx
- website/content/docs/platform/k8s/helm/examples/standalone-audit.mdx
- website/content/docs/platform/k8s/helm/examples/standalone-load-balanced-ui.mdx
- website/content/docs/platform/k8s/helm/examples/standalone-tls.mdx
- website/content/docs/platform/k8s/helm/index.mdx
- website/content/docs/platform/k8s/helm/openshift.mdx
- website/content/docs/platform/k8s/helm/run.mdx
- website/content/partials/helm/install.mdx
- website/content/partials/helm/repo.mdx
- website/content/partials/helm/version.mdx
https://github.com/hashicorp/vault-helm/releases/tag/v0.21.0
> docs/vault-helm: updates for the v0.21.0 release

- ui/app/components/oidc/key-form.js
- ui/app/models/oidc/client.js
- ui/app/models/oidc/key.js
- ui/app/routes/vault/cluster/access/oidc/keys/create.js
- ui/app/routes/vault/cluster/access/oidc/keys/key.js
- ui/app/templates/components/oidc/key-form.hbs
- ui/app/templates/vault/cluster/access/oidc/keys/create.hbs
- ui/app/templates/vault/cluster/access/oidc/keys/key/edit.hbs
- ui/tests/integration/components/oidc/key-form-test.js
> UI: Key create/edit form

- ui/app/serializers/oidc/provider.js
- ui/app/templates/components/oidc/provider-list.hbs
Added issuer metadata to provider list view
> metadata for provider list view

- website/content/docs/platform/k8s/index.mdx
The automatic [backport PR](https://github.com/hashicorp/vault/pull/16769) failed, so this PR performs a manual cherry-pick
> Fix the referenced learn link (#16747)

- go.mod
- go.sum
Updates `consul-template` to `v0.28.3`
> Backport consul-template update

- website/content/docs/concepts/seal.mdx
Clarify documentation about distribution of Shamir shards in unsealing doc: https://developer.hashicorp.com/vault/docs/concepts/seal#unsealing
> Clarify key distribution in shamir unsealing

- website/content/docs/concepts/client-count.mdx
Add a cross-referencing link to Learn tutorial. 
This closes https://github.com/hashicorp/vault/pull/13565
> Add a reference to learn tutorial

- ui/app/controllers/vault/cluster/access/oidc/assignments/assignment/details.js
- ui/app/controllers/vault/cluster/access/oidc/clients/client/details.js
- ui/app/controllers/vault/cluster/access/oidc/keys/key/details.js
- ui/app/controllers/vault/cluster/access/oidc/providers/provider/details.js
- ui/app/controllers/vault/cluster/access/oidc/scopes/scope/details.js
> UI: rollbackAttributes when destroyRecord fails

- .github/workflows/enos-run.yml
- enos/README.md
- enos/enos-modules.hcl
- enos/enos-scenario-autopilot.hcl
- enos/enos-scenario-smoke.hcl
- enos/enos-terraform.hcl
- enos/enos-variables.hcl
- enos/modules/autopilot_upgrade_storageconfig/main.tf
- enos/modules/build_crt/main.tf
- enos/modules/build_local/main.tf
- enos/modules/build_local/templates/build.sh
- enos/modules/get_local_version_from_make/main.tf
- enos/modules/get_local_version_from_make/scripts/version.sh
- enos/modules/vault_verify_autopilot/main.tf
- enos/modules/vault_verify_autopilot/templates/smoke-verify-autopilot.sh
> [QTI-295] Add Autopilot upgrade tests to Enos scenario

- website/content/docs/internals/architecture.mdx
Tiny changes to make sentences flow a bit nicer.
> Update phrasing in internals/architecture

- builtin/logical/pki/backend.go
- changelog/16830.txt
Fixes an issue where the LIST endpoint required authentication.
> Fix LIST issuers endpoint

- website/content/docs/platform/aws/lambda-extension.mdx
Added in https://github.com/hashicorp/vault-lambda-extension/pull/69
Wait to merge until a new version of VLE has been released.
> Add VAULT_ASSUMED_ROLE_ARN parameter to VLE docs

- changelog/16890.txt
- go.mod
- go.sum
- website/content/api-docs/auth/kerberos.mdx
> Backport: auth/kerberos: add config to include ldap groups in group alias (#16890)

- website/content/docs/audit/index.mdx
- Update blocked audit device to use feedback from #6484
- This PR supersedes #6484
> Docs: Audit device: Clarifications based on feedback

- website/content/api-docs/secret/azure.mdx
- website/content/docs/secrets/azure.mdx
Updating all documentation so it refers to usage of MS graph instead of AAD graph.
> Update Azure docs

- ui/app/routes/vault/cluster/access/oidc/clients/index.js
- ui/tests/acceptance/oidc-config/clients-test.js
> UI: Add redirect when last client is deleted 

- website/content/docs/internals/integrated-storage.mdx
Updated section on dead server cleanup to state that it is now available in vault 1.7+
> Doc only: Dead Server Cleanup added in Vault 1.7

- website/content/docs/concepts/tokens.mdx
- website/content/docs/configuration/seal/transit.mdx
Applying some suggestions from https://github.com/hashicorp/vault/issues/14833.
> Point people in the right direction for tokens used in transit autounseal

- website/content/docs/concepts/client-count/faq.mdx
> docs: fix typo in faq.mdx

- website/content/docs/internals/architecture.mdx
Some minor typos fix after I read the whole page.
> Fix typos in architecture page

- changelog/16983.txt
- ui/app/components/secret-version-menu.js
- ui/app/components/status-menu.js
- ui/app/styles/core/generic.scss
- ui/app/styles/core/navbar.scss
- ui/app/templates/components/secret-link.hbs
- ui/app/templates/components/secret-version-menu.hbs
- ui/app/templates/components/status-menu.hbs
- ui/package.json
- ui/scripts/codemods/linkto-with-on-modifier.js
- ui/yarn.lock
> Backport of LinkTo Transition Bug into release/1.11.x

- website/content/api-docs/secret/transform.mdx
- website/content/docs/secrets/transform/index.mdx
- website/content/docs/secrets/transform/tokenization.mdx
Documents the addition of MSSQL support to Transform tokenization.
Resolves VAULT-6154
> Update transform documentation to include MSSQL.

- builtin/logical/transit/path_sign_verify_test.go
- sdk/helper/keysutil/policy_test.go
When we added new tests that validate the RSA PSS feature added in #16549, they work properly on normal Go builds, but running the tests underneath the BoringCrypto implementations fail due to a lack of SHA3 support within RSA in FIPS 140-2 mode.
> Address failures in FIPS builds around new transit RSA PSS tests

- ui/app/adapters/named-path.js
- ui/app/routes/vault/cluster/access/oidc/clients/client/providers.js
- ui/tests/unit/adapters/oidc/test-helper.js
Fixes the provider list view for a particular client now that #16991 is merged
> UI: Filter Client providers list view

- website/content/docs/internals/integrated-storage.mdx
Update to clarify present perfect tense.
> Minor doc grammar update

- builtin/credential/radius/backend_test.go
- helper/testhelpers/docker/testhelpers.go
See two commit messages for details of what and why :-)
This also incorporates the changes from #17046 for the test failure logger.
> Fix radiusd network connection limitations

- .circleci/config.yml
- .circleci/config/commands/go_test.yml
- .circleci/config/executors/@executors.yml
- Makefile
- README.md
- changelog/_go-ver-1120.txt
- go.mod
- scripts/docker/Dockerfile
- scripts/docker/Dockerfile.ui
https://hashicorp.atlassian.net/browse/VAULT-8153
Previous PR: https://github.com/hashicorp/vault/pull/17034
> updating go to 1.19.1

- website/content/docs/configuration/service-registration/kubernetes.mdx
- website/content/docs/platform/k8s/helm/configuration.mdx
- website/content/docs/platform/k8s/helm/enterprise.mdx
- website/content/docs/platform/k8s/helm/examples/enterprise-dr-with-raft.mdx
- website/content/docs/platform/k8s/helm/examples/enterprise-perf-with-raft.mdx
- website/content/docs/platform/k8s/helm/examples/enterprise-with-raft.mdx
- website/content/docs/platform/k8s/helm/run.mdx
- website/content/partials/helm/install.mdx
- website/content/partials/helm/repo.mdx
Including Prometheus Operator support.
> Update docs for helm 0.22.0

- helper/forwarding/types.pb.go
- helper/identity/mfa/types.pb.go
- sdk/database/dbplugin/v5/proto/database.pb.go
Just running `make proto`. On an ENT [PR](https://github.com/hashicorp/vault-enterprise/pull/3015), diff-oss is failing with the files in this PR.
> running make proto

- physical/consul/consul.go
- physical/consul/consul_test.go
- physical/raft/fsm.go
- physical/raft/fsm_test.go
- physical/raft/raft.go
- physical/raft/raft_test.go
- sdk/physical/entry.go
- sdk/physical/inmem/inmem.go
- sdk/physical/transactions.go
- vault/core.go
- vault/core_util_common.go
- vault/testing.go
OSS part of https://github.com/hashicorp/vault-enterprise/pull/2945
The changelog is on the ENT PR
> merkle sync undo logs

- changelog/17161.txt
- go.mod
- go.sum
https://github.com/hashicorp/vault-plugin-auth-kubernetes/releases/tag/v0.14.0
> auth/kubernetes: upgrade to v0.14.0

- .circleci/config.yml
- .circleci/config/executors/@executors.yml
- .circleci/config/jobs/semgrep.yml
Simple update of semgrep, no massive new features stand out from the previous 0.106.0.
> Update semgrep to 0.113.0

- website/content/docs/platform/k8s/injector/annotations.mdx
https://github.com/hashicorp/vault-k8s/releases/tag/v1.0.0
> docs/vault-k8s: update for v1.0.0 release

- physical/raft/fsm.go
- physical/raft/fsm_test.go
- physical/raft/raft.go
This has the latest OSS changes from the updates to https://github.com/hashicorp/vault-enterprise/pull/2945
> Adjust raft transactions to be safer with get operations

- website/content/docs/commands/server.mdx
- website/content/docs/deprecation/faq.mdx
- website/content/docs/deprecation/index.mdx
Update the feature deprecation page to describe the deprecation statuses and their effects.
> docs: Update the feature deprecation page

- changelog/17173.txt
- go.mod
- go.sum
Update kerberos auth plugin to v0.8.0.
```
go get github.com/hashicorp/vault-plugin-auth-kerberos/@v0.8.0
go mod tidy
```
> Update plugin to v0.8.0

- go.mod
- go.sum
Match up various dependency updates that occurred in ENT but not within OSS.
> Update OSS dependencies to match newer versions that ENT is using

- go.mod
- go.sum
Steps:
```
go get github.com/hashicorp/vault-plugin-secrets-kv@v0.13.0
go mod tidy
```
> bump secrets/kv plugin to v0.13.0

- changelog/17196.txt
- go.mod
- go.sum
```bash
go get github.com/hashicorp/vault-plugin-auth-cf@v0.13.0
go mod tidy
```
> fix: upgrade vault-plugin-auth-cf to v0.13.0

- ui/app/components/link-status.js
- ui/app/templates/components/link-status.hbs
- ui/mirage/handlers/hcp-link.js
- ui/tests/integration/components/link-status-test.js
The `hcp_link_status` message format has changed and connecting state errors were added. The `LinkStatus` component was updated to handle these changes and sample messages were added to the mirage handler.
> HCP Link Status Updates

- go.mod
- go.sum
```
go get github.com/hashicorp/vault-plugin-secrets-ad/@v0.14.0
go mod tidy
```
Changelog entries already included when plugin version v0.13.1 was tagged
> Update AD secrets plugin

- vault/external_tests/api/renewer_integration_test.go
I'm deleting this subtest because I don't think it adds value.  TestRenewer_Renew is exercising the api package's LifetimeWatcher construct, not database lease renewals specifically; in other words, it doesn't matter what kind of lease is being renewed.
The motivation for this removal is that testing db lease renewals requires a DB, which requires running a docker container, which results in all the tests in the package `vault/external_tests/api` being run as part of test-go-remote-docker.  We've seen some (I believe spurious) "potential deadlock detected" test failures in this package, which I believe is simply due to insufficient CPU in the executor for the amount of parallel short tests in the package.  The remote docker env is less well provisioned than the regular go test env, …
> Don't test LifetimeWatcher with database leases

- go.mod
Update Vault to newly tagged api release v1.8.0
> update vault to api/v1.8.0

- go.mod
Pull in rc1 SDK change from  #17230 into Vault.
> Pull in 1.12.0-rc1 SDK update to Vault

- changelog/17160.txt
As per instructions at https://www.vaultproject.io/docs/plugins/plugin-portal, adding a community secrets plugin.
> vault-plugin-secrets-apigee

- website/content/docs/plugins/plugin-portal.mdx
Adding a couple of secrets engines to the plugin portal page
> adding boundary and waypoint plugins to portal

- vault/auth.go
- vault/external_plugin_test.go
- vault/mount.go
- vault/plugin_reload.go
Some PRs got crossed and somehow these were missed in the build checks for #17182.
> Change usages of RunningSha to RunningSha256

- website/content/api-docs/system/managed-keys.mdx
- website/content/docs/enterprise/managed-keys.mdx
Add managed key API docs for GCP Cloud KMS keys
> Add managed key docs for gcp

- command/auth_list.go
- command/secrets_list.go
The table width is getting a bit much, but I'm not sure we can do too much about that.
> CLI: Add version info to auth/secrets list -detailed

- api/go.sum
- go.mod
- go.sum
- sdk/go.mod
- sdk/go.sum
> Update tlsutil to v0.1.2 for ecdsa algo naming

- ui/app/components/link-status.js
- ui/app/styles/core/buttons.scss
- ui/app/templates/components/link-status.hbs
- ui/app/templates/components/oidc/scope-form.hbs
- ui/mirage/handlers/hcp-link.js
- ui/tests/acceptance/transit-test.js
- ui/tests/integration/components/link-status-test.js
- ui/tests/integration/components/nav-header-test.js
- ui/tests/integration/components/replication-header-test.js
> Backport 1.12.x: HCP Link Status Parsing and Modal Update 

- changelog/17406.txt
- go.mod
- go.sum
Upgraded the version then did a `go mod tidy`.
> VAULT-8631 Upgrade vault-plugin-secrets to v0.13.3, to enable synchronous KVV2 creation

- CHANGELOG.md
* Update changelog with correct SHAs.
* Clean up some formatting.
> changelog: fix 1.12.0-rc1, 1.11.4, 1.10.7, 1.9.10

- enos/modules/vault_verify_version/templates/verify-cluster-version.sh
> Fix Vault version verification for ent editions

- vault/audit.go
- vault/auth.go
- vault/mount.go
I don't think there's a need for two iterations in persistMount
> Core: Persist Mount Table. One cicle

- builtin/logical/ssh/path_issue_sign.go
When requesting a SSH certificate with `default_extension` templating enabled, if the request lacks entity information and a particular extension requires templating, just these extensions will be elided. Other extensions (if present) will still be on the final certificate.
Add a warning in the event of missing entity information and at least one extension that was skipped as a result.
> Add warning on missing entity information

- physical/raft/raft.go
- physical/raft/raft_autopilot.go
- vault/core.go
- vault/core_metrics.go
- vault/core_util.go
- vault/external_tests/raft/raft_autopilot_test.go
- vault/external_tests/raft/raft_test.go
- vault/ha.go
- vault/logical_system.go
- vault/raft.go
- vault/request_forwarding_rpc.go
- vault/testing.go
OSS portion of https://github.com/hashicorp/vault-enterprise/pull/3249
> only enable undo logs if all cluster members support it

- vault/raft.go
ENT version https://github.com/hashicorp/vault-enterprise/pull/3277
> disable undo logs by default for 1.12.0

- sdk/plugin/grpc_system_test.go
Seems like this was left in by accident, so removing.
> Delete empty test

- website/content/api-docs/secret/transform.mdx
- Remove incorrect method name and payload from sample GET request
- Correct method name from POST request
> Docs: Update Transform API documentation

- go.mod
Ran `go get github.com/hashicorp/vault/sdk@release/1.12.x` and `go mod tidy`, staged changes, and pushed.
> Import SDK 1.12.1

- .github/workflows/enos-verify-stable.yml
- Update repo dispatch types
- Run Enos verify only on release branches
> Enos verify updates

- changelog/17593.txt
- go.mod
- go.sum
```
go get github.com/hashicorp/vault-plugin-database-snowflake@v0.6.1
go mod tidy
```
> database/snowflake: update plugin to v0.6.1

- website/content/docs/agent/index.mdx
- website/content/docs/auth/login-mfa/faq.mdx
- website/content/docs/enterprise/managed-keys.mdx
- website/content/docs/platform/k8s/injector/annotations.mdx
- website/content/docs/release-notes/1.12.0.mdx
Fixes some more broken links which were found through a recent check.
> website: fixes more broken links

- .github/workflows/enos-run.yml
> Download Enos test artifact only for CRT runs

- .github/workflows/enos-run.yml
> Enos verify stable needs Artifactory variables

- .github/workflows/enos-run-k8s.yml
backporting `46954b3fa5e38f7f177508588180757e068258c9`
> [QT-182] Fix broken k8s workflow for vault-enterprise (#17629)

- website/content/docs/secrets/kmip-profiles.mdx
- website/content/docs/secrets/kmip.mdx
- website/data/docs-nav-data.json
This PR adds the release specific documentation changes for KMIP and also adds a doc for kmip-profiles
> Backport pr 17294 1.11.x - Add documentation for KMIP features

- website/content/api-docs/secret/kv/kv-v2.mdx
🎟️ [Asana](https://app.asana.com/0/563192436488770/1203203410997453/f)
🔍 [Deploy Preview](https://vault-git-docs-fix-format-issue-hashicorp.vercel.app/vault/api-docs/secret/kv/kv-v2#patch-metadata)
This PR fixes the broken format + link.
> [API doc] Fix a broken link in KV v2 doc

- helper/testhelpers/testhelpers.go
- vault/external_tests/identity/login_mfa_totp_test.go
Revert the config settings for the TOTP method and tweak some of the variables for uniqueness. The latter shouldn't matter all that much, but is nonetheless nice to have.
> Tweak totp test to fix race failures

- website/content/docs/enterprise/replication.mdx
- website/data/docs-nav-data.json
Adding section clarifying Enterprise Replication behavior in relation to Load Balancers and mTLS.
> Add mTLS and Load Balancers section to Enterprise Replication Documentation

- changelog/17661.txt
- ui/app/components/auth-form.js
- ui/app/components/auth-jwt.js
- ui/app/templates/components/auth-form.hbs
- ui/tests/integration/components/auth-form-test.js
- ui/tests/integration/components/auth-jwt-test.js
- ui/tests/pages/components/auth-form.js
- ui/tests/unit/components/auth-form-test.js
> Backport of OIDC Alternate Path Bug into release/1.10.x

- changelog/17661.txt
- ui/app/components/auth-form.js
- ui/app/components/auth-jwt.js
- ui/app/templates/components/auth-form.hbs
- ui/tests/integration/components/auth-form-test.js
- ui/tests/integration/components/auth-jwt-test.js
- ui/tests/pages/components/auth-form.js
- ui/tests/unit/components/auth-form-test.js
> Backport of OIDC Alternate Path Bug into release/1.11.x

- website/content/docs/configuration/service-registration/kubernetes.mdx
- website/content/docs/platform/k8s/helm/configuration.mdx
- website/content/docs/platform/k8s/helm/enterprise.mdx
- website/content/docs/platform/k8s/helm/examples/enterprise-dr-with-raft.mdx
- website/content/docs/platform/k8s/helm/examples/enterprise-perf-with-raft.mdx
- website/content/docs/platform/k8s/helm/examples/enterprise-with-raft.mdx
- website/content/docs/platform/k8s/helm/run.mdx
- website/content/docs/platform/k8s/injector/annotations.mdx
- website/content/partials/helm/install.mdx
- website/content/partials/helm/repo.mdx
- Version bumps
- Updated defaults for ephemeral storage settings
> Update documentation for vault-helm v0.22.1 release

- website/data/docs-nav-data.json
> Docs: Remove patch from 1.10.x docs

- website/data/docs-nav-data.json
> Docs: Remove patch from 1.11.x docs

- website/data/docs-nav-data.json
> Docs: Remove patch from 1.12.x docs

- builtin/logical/pki/backend_test.go
> Bump validity period check to satisfy CircleCI

- ui/app/styles/components/popup-menu.scss
- ui/app/templates/vault/cluster.hbs
> UI: fix navbar active links

- website/content/api-docs/system/plugins-catalog.mdx
Make the request consistent with the response by adding the optional version query parameter.
Closes #17738
> Docs: Update sample plugin info request

- changelog/17769.txt
- ui/app/components/raft-storage-overview.js
- ui/lib/service-worker-authenticated-download/service-worker-registration/index.js
- ui/tests/integration/components/raft-storage-overview-test.js
> Backport of Raft Snapshot Download Bug into release/1.12.x

- changelog/17769.txt
- ui/app/components/raft-storage-overview.js
- ui/lib/service-worker-authenticated-download/service-worker-registration/index.js
- ui/tests/integration/components/raft-storage-overview-test.js
> Backport of Raft Snapshot Download Bug into release/1.11.x

- changelog/17338.txt
https://github.com/hashicorp/vault/pull/17338#discussion_r1014442446
> Fix changelog for vault-8305

- builtin/logical/pki/backend.go
- builtin/logical/pki/backend_test.go
- builtin/logical/pki/config_util.go
- builtin/logical/pki/crl_util.go
- builtin/logical/pki/path_config_ca.go
- builtin/logical/pki/path_fetch_issuers.go
- builtin/logical/pki/path_manage_issuers.go
- builtin/logical/pki/path_revoke.go
- builtin/logical/pki/path_root.go
- builtin/logical/pki/path_tidy.go
- builtin/logical/pki/storage.go
- builtin/logical/pki/util.go
Also remove one duplicate error masked by return.
> Move from %v->%w for errs for PKI

- changelog/17871.txt
- go.mod
- go.sum
`go get github.com/hashicorp/vault-plugin-secrets-gcp@main && go mod tidy`
> Updated secrets-gcp dependency

- api/plugin_helpers.go
- changelog/17839.txt
- sdk/framework/backend.go
- sdk/framework/openapi.go
- sdk/framework/openapi_test.go
- sdk/framework/path.go
- sdk/framework/testdata/legacy.json
- sdk/framework/testdata/operations.json
- sdk/framework/testdata/operations_list.json
- sdk/framework/testdata/responses.json
- vault/logical_system.go
- vault/logical_system_test.go
- website/content/api-docs/system/internal-specs-openapi.mdx
This reverts #17839 (commit 02064eccb42bb2ec1a3d12ec0d49c661312acd2d)
Reverting this due to failures in UI tests
> Revert "Add mount path into the default generated openapi.json spec"

- website/content/docs/plugins/plugin-portal.mdx
🔍 [Deploy Preview](https://vault-git-fork-johnsmartco-patch-1-hashicorp.vercel.app/vault/docs/plugins/plugin-portal#partner)
> Add DataStax Astra DB to Partner DBs

- builtin/logical/pki/config_util.go
Credit to Steve for finding this one.
> Handle removed default issuers

- website/content/docs/secrets/pki/considerations.mdx
> Fix docs by adding self-closing BRs

- Dockerfile
Updating the ubi base image, and backporting to 1.12, 1.11, 1.10.
> dockerfile: ubi-minimal:8.6 => 8.7

- changelog/17950.txt
- ui/app/templates/components/identity/item-policies.hbs
> cherry pick original commit
